### ISSUE TITLE
Api keys not removed when an API is deleted

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#10]
_From @aelamrani on May 24, 2016 7:45_

When an API is deleted, the api keys are still stored and valid. But if the API is restored, the keys are not displayed, but still valid

_Copied from original issue: gravitee-io/gravitee-management-rest-api#84_

**Comment by NicolasGeraud** [comment]
Same behaviour if I delete the application : the api-key is still valid

**Comment by brasseld** [comment]
I set milestone 0.17.0 for this issue 'cause it's a critical one.

**Comment by NicolasGeraud** [comment]
As a API Publisher of a public API, I have to set a default plan.
Or
Plan will be show on the api (some could be disabled) and the subscriber choose which plan match better its needs.

I think the second solution is better. And when social part will be implement in Gravitee.io, the subscriber could request for an api-key to a specific plan.

**Comment by brasseld** [comment]
I think that an API must not be deleted but may be "deactivated".

The reason for this is that if we really want to delete an API, we have to:
- Delete the API itself
- Delete all API Keys
- Delete analytics for these API / API keys

But by deleting analytics, we loose data coherency (hits between two dates, ...)

**Comment by brasseld** [comment]
Duplicate of #55
