### ISSUE TITLE
[portal] Allow API to be grouped on a single tile

### ISSUE THREAD

**Issue by David-V2** [gravitee-io/issues#1011]
### Expected Behavior
if I have 3 "foo api" version, display a "foo api" tile leeding to the (new view) version list (which should focus on the latest version)

### Current Behavior
There is one tile per api version

**Comment by tcompiegne** [comment]
More information for this issue : 

* Enhance view functionnalities
* Enable API list mode VS view list mode
* Select API list from view configuration screen
* Highlight APIs
