### ISSUE TITLE
Gravitee UI does not show the Applications and show error

### ISSUE THREAD

**Issue by gurucube** [gravitee-io/issues#10137]
## Bug description
During normal operational when we update the "application" name it disappear from the UI list/management and this error message is shown instead: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "<parameter1>" is null
The application record still in place into the "applications" collection.
Note: we are using external Mongo service (Atlas)

## To Reproduce
Steps to reproduce the behaviour:
1. Complete the cycle to create an API with plan and application
2. Modify the Application name
3. See error: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "<parameter1>" is null

## Environment
Gravitee Version in use 4.5
We deployed the Gravitee MongoDB directly in Atlas 7.0.14

Could you help us to fix this?
Thank you in advance

Roberto

**Comment by ax88008** [comment]
We are having exactly the same issue, after changing a name.  The applications are still there because we can see the application count and subscriptions and plans still work.  We use an external mongo in a seperate kubernetes namespace

**Comment by julienperignon** [comment]
Same issue after changing the name of the application

**Comment by ytvnr** [comment]
Hi,
Thank you for raising this.
This one has been resolved by https://github.com/gravitee-io/issues/issues/10130 and has been released with APIM 4.5.2
