### ISSUE TITLE
[gateway] NPE when using unknown properties

### ISSUE THREAD

**Issue by tdaghelet** [gravitee-io/issues#1013]
Hello,

I got an NPE when I use an unknown property in a policy 

08:58:30.200 [vert.x-eventloop-thread-0] [] ERROR i.v.c.h.impl.HttpClientResponseImpl - java.lang.NullPointerException

### Expected Behavior
It could be useful to have an information in the logs : "properties "xxxx" doesn't exist"

### Current Behavior
08:58:30.200 [vert.x-eventloop-thread-0] [] ERROR i.v.c.h.impl.HttpClientResponseImpl - java.lang.NullPointerException

### Steps to Reproduce (for bugs)

1. create an api
2. add a policy and use a unknown property
3. call the api
4. watch the logs

### Your Environment

* Version used: 1.12.2
* Browser Name and version: N/A
* Operating System and version: N/A

**Comment by NicolasGeraud** [comment]
hi @tdaghelet 
I've tried with the transform headers policy and there's no error.
Can you tell me what policy generate this stasktrace ?

thx

**Comment by tdaghelet** [comment]
hi @NicolasGeraud 

You're right, i'm not able to reproduce this problem : I had another (custom) policy which throws this NPE...

But it could be good to have an information which tell us that the property doesn't exists at runtime, no? (in the log call.. or gravitee log)

Thank you

**Comment by NicolasGeraud** [comment]
@brasseld 
what do you think about add a log here if the result is null ?
https://github.com/gravitee-io/gravitee-expression-language/blob/9f5a1e9c0f6a2582fb43cdb736722ba7886b371e/src/main/java/io/gravitee/el/spel/SpelTemplateEngine.java#L36

**Comment by brasseld** [comment]
We can add a log in gateway logs, but not in request logs (ES).
I'm not sure it makes sense to have such information while looking to API logs.
