### ISSUE TITLE
When importing a json / YAML api swagger we need clear error msg

### ISSUE THREAD

**Issue by ycamus** [gravitee-io/issues#1018]
Tried to put a YAML swagger  or json,
I did the mistake to forget title.

Error message show -1

Nothing i could get,

There should be some understandable error msg for the required field.

**Comment by brasseld** [comment]
Do you have a swagger example to reproduce the issue easily ?

**Comment by ycamus** [comment]
Hi, just set the title to empty. It will do thé trick

Le 26 janv. 2018 15:22, "Brassely David" <notifications@github.com> a
écrit :
