### ISSUE TITLE
[Policy] Jolt should not update Content-Type header

### ISSUE THREAD

**Issue by Matsa59** [gravitee-io/issues#1024]
Jolt is an amazing policy that allow api publisher to transform the back end API response. But if you use this policy, the `Content-Type` header, for the response (and request I suppose) will be update to `application/json`. For example, if you use mime type versioning system, using this policy will break your versioning system.

### Expected Behavior

The Jolt policy should not update the `Content-Type` header. 

### Possible Solution

Currently, only a groovy script can fix the bug without updating the jolt policy.

### Steps to Reproduce (for bugs)

1. Add transform header policy with `Content-Type` equal to what you want (except application/json of course)
2. Add `Json to Json transform` policy (add default spec to try) 
3. Request and look the response's headers

### Your Environment

* Version used:  #All

PR : https://github.com/gravitee-io/gravitee-policy-json-to-json/pull/5

**Comment by vdusauto** [comment]
Jolt should not change Accept Header either.
Alternatively JOLT Policy could propose a Mime type header to set on successful transformation.

**Comment by r00z** [comment]
Hello,
I've added a boolean config option to enable/disable Content-Type header override: 
Here is a pull request:
https://github.com/gravitee-io/gravitee-policy-json-to-json/pull/11
