### ISSUE TITLE
[management-api] Upgrade a subscription

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#1027]
I need to be able to move a subscription to another plan. With this feature, i can upgrade a consumer to another plan without forced the consumer to change its apikey

**Comment by pochadri** [comment]
+1

**Comment by NicolasGeraud** [comment]
hi @icandir ,
as you can see (no milestone set), this issue is in the backlog and not schedule yet.

- The main purpose of this issue is to be able to move a subscription to another plan in the same api. As a consumer, let say you have subscribed to a low rate plan for cheaper price. You are satisfied by the service and want a better plan (with more quote for example). With this feature, the api owner can promote an app to another plan.

- I don't understand your example (I mean, from a business point of view). If you fix a bug, why do you need to change version number ?
If you want to move all your consumers to the new Api, why not simply rename the first version of the API ?
If you want to manage 2 version of your API, it probably means that your api contract has changed. So your consumer need to upgrade his code. In this case, it makes sense to have 2 different subscriptions.

What do you think ?

**Comment by icandir** [comment]
- ok the main purpose is different than. because this action is upgrading subscription plan.
my purpose is to move the subscriptions of one api plan to the apis new version plan.

- I will reply second paragraph later.

**Comment by brasseld** [comment]
Hi @icandir any news about the second point ?

**Comment by NicolasGeraud** [comment]
I close this issue cause the main purpose of this issue will be resolved thanks to #1946
