### ISSUE TITLE
[management-api] [ldap] Full name of LDAP users not shown if LDAP object lacks givenname/sn

### ISSUE THREAD

**Issue by hfuru** [gravitee-io/issues#1030]
I can find a user by his name, but Gravitee just shows his username, not the full name it just found, because our LDAP objects do not contain the attributes Gravitee expects (givenName, sn).

(We use a patch which doesn't search persons at all, but accounts, hence the missing sn).

### Expected Behavior

Show the LDAP user's full name (cn) if other attrs are missing.

### Current Behavior

Showing username but not full name. 

### Possible Solution

LdapIdentityLookup.java (gravitee-management-rest-api) searches for a person by his CN, and then tries to show his givenName, sn and mail, as far as I can see from the code.  However, givenName and mail are not part of LDAP's 'person' objectclass.  For that matter, LDAP servers can use access controls to hide some attributes, and Gravitee does not look up the 'initials' attribute which could complete a person's name.

givenName/initials/mail are commonly from the inetOrgPerson object class, that is likely the class hwich the code is expecting.  But it also has a displayName attribute which is the preferred form to show the name.  Other variants are cn, or compose givenName+initials+sn.  However, remember that the order of these attributes vary between cultures, so there is no trivial and correct way to "translate" between the 3-attr form and 1-full-attr form.

### Steps to Reproduce (for bugs)

1. In apim management:gravitee.yml, refer {security:providers: type ldap} to an LDAP directory where ldap users have cn but not givenName (and sn, if you have that patch).
2.  On the web api, find an LDAP user by his full name (cn).
3. Gravitee shows the username  - and maybe sn if it is a person, I have not tested that.

More or less, anyway.  I don't have a working installation to test this on right now.

### Context

Authenticate users in LDAP and have them shown in a useful way.

### Your Environment

* Version used: Gravitee 1.12.2 + gravitee-io/issues#948
* Browser Name and version: Firefox
* Operating System and version: Red Hat Enterprise Linux Server release 7.4 (Maipo)

**Comment by brasseld** [comment]
As far as I understand, you need a way to customize the mapping between LDAP attributes and Gravitee user fields, am I right ? 

I mean this part from source code: https://github.com/gravitee-io/gravitee-management-rest-api/blob/master/gravitee-management-api-idp/gravitee-management-api-idp-ldap/src/main/java/io/gravitee/management/idp/ldap/lookup/LdapIdentityLookup.java#L137

**Comment by hfuru** [comment]
Yes, that would be preferable.  But more importantly, the default behavior is wrong.  You need a minimal fallback which should be either to display the same attr which was searched for, or just display "cn" since that is the attr which will most commonly be available.  Once you have that fallback, you can try something more fancy like showing displayName if it is there, or showing givenName+initials+sn if you find givenName+sn (similar to what you do now).

**Comment by brasseld** [comment]
Ok so you agree that we are speaking about the search functionality and not the authentication one ? In that case, it is easier for us to apply such changes.

**Comment by hfuru** [comment]
On 24. jan. 2018 08:35, Brassely David wrote:
> Ok so you agree that we are speaking about the search functionality and not 
> the authentication one ? In that case, it is easier for us to apply such changes.

Yes, it's about displaying users - existing ones and during search.
I've tested it now that we have a working Java again:

(user icon) -> Administration -> Configuration -> Roles -> API_PUBLISHER
shows just user names, not full names.

Add user -> type a personal name -> it shows a list of matching
user names, rather than names which match what I type.  This should
definitely show exactly the attribute which is being searched for.
As it is, it looks like I ought to type a user name, but doing
so finds nothing since Gravitee (fortunately) doens't search for uid.


Another issue is that Gravitee gave a red complaint about LDAP error
code adminLimitExceeded.  It shouldn't, this is a normal situation
(as is sizeLimitExceeded) when you do substring searches.  Our LDAP
server is configured to reject searches which would return too many
entries.  A list of e.g. 500 people would just be an annoyance to the
user, he'll simply type a bit more of the name to get a better search.


-- 
Hallvard

**Comment by hfuru** [comment]
On 24. jan. 2018 11:26, Hallvard Breien Furuseth wrote:
> As it is, it looks like I ought to type a user name, but doing
> so finds nothing since Gravitee (fortunately) doens't search for uid.

Er, I mean it "fortunately" doesn't do _substring_ search for uid
since in our case that would often give too many results, so our
LDAP server is configured to give adminLimitExceeded instead.

It might be good to search for (|(cn=*typed text*)(uid=typed text))
or do two or more searches, one for the exact username and then
substring search(es).  That way an adminLimitExceeded on 2nd
search won't deprive us of the result of first search.

-- 
Hallvard

**Comment by brasseld** [comment]
I had a deeper look on this issue.

I don't understand the `adminLimitExceeded` LDAP error because we have set the number of expected results in the LDAP query. See:
https://github.com/gravitee-io/gravitee-management-rest-api/blob/master/gravitee-management-api-idp/gravitee-management-api-idp-ldap/src/main/java/io/gravitee/management/idp/ldap/lookup/LdapIdentityLookup.java#L98

I'm having a look to the other points.

**Comment by hfuru** [comment]
On 05. feb. 2018 16:02, Brassely David wrote:
> I don't understand the |adminLimitExceeded| LDAP error because we have set 
> the number of expected results in the LDAP query. See:

adminLimitExceeded doesn't say "there would be too many returned
entries", it says "the server rejects all or some of this operation".

E.g. if a filter component isn't indexed, so the server would have to
walk through all entries in scope and check each against the filter.
Instead it just refuses if there are too many candidate entries to
examine.
Or maybe because the search is taking too long time.

-- 
Hallvard

**Comment by hfuru** [comment]
On 05. feb. 2018 16:36, Hallvard Breien Furuseth wrote:
> adminLimitExceeded doesn't say "there would be too many returned
> entries", it says "the server rejects all or some of this operation".
> (...)

I'll file it as separate issue if you like, I shouldn't have mixed
it up with attribute names.

-- 
Hallvard

**Comment by brasseld** [comment]
Yes please fill an other issue.
Let's keep this one for query / filter rules and attributes used to display user.
I let you create an other issue to manage the `adminLimitExceeded` error.

**Comment by brasseld** [comment]
Will be part of https://github.com/gravitee-io/issues/issues/1053

**Comment by brasseld** [comment]
Closed by #1053
