### ISSUE TITLE
Publish plan: Missing redeploy sync menu 

### ISSUE THREAD

**Issue by krish2609** [gravitee-io/issues#1043]
After creating plan and publishing the plan “Deploy API” sync menu is not displayed at the top to sync and redeploy the API

### Expected Behavior

After creating plan and publishing the plan “Deploy API” sync menu should be displayed to redeploy my API.

### Current Behavior

After creating plan and publishing the plan “Deploy API” sync menu is not displayed at the top to sync and redeploy the API

### Possible Solution

Might be refresh issue and not able to re produce consistently 
### Steps to Reproduce (for bugs)

1. Create plan and save
2. Under plans section select the corresponding PLAN's drop down menu to publish the plan

### Your Environment

* Version used: graviteeio-full-1.12.5
* Browser Name and version: Chrom Version 63.0.3239.132 (Official Build) (64-bit)
* Operating System and version: Windows 7 64 bit
[Gravitee_io_1.12.5_issues_publish_plan.docx](https://github.com/gravitee-io/issues/files/1673187/Gravitee_io_1.12.5_issues_publish_plan.docx)

**Comment by brasseld** [comment]
Fixed in 1.13
