### ISSUE TITLE
New feature: Delete the unwanted plan 

### ISSUE THREAD

**Issue by krish2609** [gravitee-io/issues#1046]
After closing the API PLAN if admin wants to delete the unwanted closed plan then admin should have options to delete that plan.
### Expected Behavior

Currently there is no option to delete the unwanted plan which was closed for some reason.

### Current Behavior

There is an option to close the PLAN but don't have a option to delete those closed plan.
### Steps to Reproduce (for bugs)

1.
2. 
3.
4.

### Your Environment

* Version used: 1.12.5
* Browser Name and version:
* Operating System and version:

**Comment by brasseld** [comment]
Hi @krish2609,

Keyless plan are deleted because there is no subscription to it.
For api_key plans, if there are subscriptions, it can't be deleted so the plan is closed. If they aren't, the plan is deleted.

**Comment by NicolasGeraud** [comment]
We do that because we need to keep the link between old api-keys used in requests. This is mandatory for Analytics
