### ISSUE TITLE
Subscription section overlaps with description section

### ISSUE THREAD

**Issue by krish2609** [gravitee-io/issues#1047]
Subscription section overlaps with description section
### Expected Behavior

Subscription section should not overlaps with description section
### Current Behavior

Subscription section overlaps with description section.
### Steps to Reproduce (for bugs)

1. Create plan with lengthy name
2. Under Subscription section create new and associate the corresponding PLAN you have created in the previous steps (ie lengthy plan name)
3. After associating the plan see the subscription section and it should overlap with RHS description section.
4.
[Gravitee_io_1.12.5_issues_subscription_section_overlapps.docx](https://github.com/gravitee-io/issues/files/1673262/Gravitee_io_1.12.5_issues_subscription_section_overlapps.docx)

### Your Environment

* Version used:
* Browser Name and version:
* Operating System and version:

**Comment by brasseld** [comment]
Hi @krish2609,

You will tell me that I'm closing all your issues... but subscriptions screen has been refactored in 1.13 ;)
