### ISSUE TITLE
[management-ui] API delete button is disabled

### ISSUE THREAD

**Issue by mathela59** [gravitee-io/issues#1055]
When you stop an api in order to delete it, the "delete" button does not activate and so he's not clickable.

### Expected Behavior
When you stop an api, the delete button should be activated

### Current Behavior
When you stop an api in order to delete it, the "delete" button does not activate and so he's not clickable.

### Steps to Reproduce (for bugs)
1. Create an api
2. Start an api
3. Try to delete the api

### Your Environment

* Version used: 1.12.4
* Browser Name and version: Chrome
* Operating System and version: Windows 10

**Comment by brasseld** [comment]
Hi @mathela59 

Don't know what is your role on the API, but only a role with a permission `api-definition-delete` is able to delete the API.
So I would advice you to check your permissions on the given API.

Regards,

**Comment by brasseld** [comment]
Hello @mathela59 

Any news about my previous comment ?

**Comment by mathela59** [comment]
Well I think permissions aren't in cause, because when i reload the page, the button is active without changing permissions.

I'll reproduce the bug.

**Comment by mathela59** [comment]
I did reproduce the bug with the admin account.

**Comment by brasseld** [comment]
Not able to reproduce with latest 1.15.x
