### ISSUE TITLE
[management-api] Using oauth scopes to assign roles in gravitee

### ISSUE THREAD

**Issue by chicco785** [gravitee-io/issues#1058]
### Expected Behavior
I suspect this is not implemented, but what i would expect is the following:

1. Using OAuth2/OIDC I log in in Gravitee.
1. Some specific roles are assigned to me in the client registered in OAuth2/OIDC provider (that maps to roles in Gravitee)
1. When logging in roles are assigned to me accordingly. (if roles in the provider are changed, it should be updated at the next login).

### Current Behavior
1. Default roles are assigned to new users connected via OAuth2.
1. An admin can manually change in Gravitee the roles.

### Possible Solution
Something similar to the way Group mapping works.

**Comment by brasseld** [comment]
You're absolutely right.
Currently only group mapping is possible but it must be extended in the same way for role mapping.

**Comment by chicco785** [comment]
would be a pr welcome?

**Comment by brasseld** [comment]
Sure, it would be!
