### ISSUE TITLE
Admin created by Gravitee seems to be a Super User (see all APIs), while later assigned Admins sees only owned APIs

### ISSUE THREAD

**Issue by chicco785** [gravitee-io/issues#1059]
### Expected Behavior
When a user is given role admin for the portal he should be able to see all APIs as the "first" admin.

Not sure is my misconfiguration or a bug...

### Current Behavior

The user while he can configure everything in the portal ect he cannot see all APIs

### Possible Solution
No idea :)

### Steps to Reproduce (for bugs)
1. A user login with oauth (so that he is registered in gravitee db)
1. The default admin logins.
1. The admin checks the API list and sees all APIs created by any user so far.
1. The default admin add the following roles MANAGEMENT:ADMIN and PORTAL:ADMIN to the new OAuth user.
1. The new user login again.
1. The new user checks the API list and sees nothing.

### Context
A Gravitee deployment using OAuth2 to allow other users to access it.
Gravitee access and in memory are enabled to.

**Comment by brasseld** [comment]
Fixed by https://github.com/gravitee-io/issues/issues/1035
