### ISSUE TITLE
[management-ui] Improvements to OAuth integration

### ISSUE THREAD

**Issue by chicco785** [gravitee-io/issues#1060]
### Expected Behavior
1. The users clicks on login and he is automatically redirected to the external id provider.
1. When the user logs out, he is logged out also from the OAuth provider
1. When the user is logged in, and he access his profile he cannot modify it, while he should be able to access the oidc/oauth account page.

### Current Behavior
1. Login form is shown, even though local login is not supported by the API.

### Possible Solution
1. Include a parameter in the UI configuration that disable local login and allow to show only the one of auth.
1. Include parameters in the UI config to support logout url from oidc /oauth
1. Include parameters in the UI config to support account url from oidc

### Context
1. Gravitee API with only OAuth provider as security.
1. Gravitee UI with OAuth provider.

**Comment by chicco785** [comment]
If relevant, we can work out a PR.

**Comment by brasseld** [comment]
I agree with solution for 1) and 2). 

For the third point, are you sure that user should be able to access oidc / oauth account page ? We get user informations thanks to /userinfo and we are storing them in gravitee datastore. What would be the added-value for 3) ?

**Comment by chicco785** [comment]
User may want to update something, and may not recall where to go to do so. Having some where a link that point him to the right place, may be of use.

**Comment by aelamrani** [comment]
Hello @chicco785,

Following your contribution on gravitee.io (and for the next ones :)), we need you to sign our CLA and send it to contact@graviteesource.com.

It should only take a few minutes and will help us a lot.

More info here: https://github.com/gravitee-io/gravitee-gateway/blob/master/CONTRIBUTING.adoc#contributor-license-agreement

A big thank-you!
