### ISSUE TITLE
[policy][dynamic-routing] How-to remove subpath

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#1065]
Hello,

i want to use different route for my api:
example:
api_context_path/fr
api_context_path/lu

but i want to use same endpoint without to transfer subpath. i mean that call to endpoint will always be
endpoint_path and not endpoint_path/fr.
I know that there is dynamic routing policy, but i have to explicitly name endpoint.
Is there a way with groovy policy to remove this subpath.
something like : request.uri = contextPath

thanks by advance

**Comment by brasseld** [comment]
You should be able to do so with dynamic routing policy, no ?

**Comment by vdelattre** [comment]
yes but with dynamic routing i lose loadbalancing functionality and blacklisting by healthcheck.

it should be great than dynamic routing can be relative and use backend instead of having explicit uri

**Comment by brasseld** [comment]
I agree with you.

Dynamic routing must also be used with relative path and not only absolute path. good point !
