### ISSUE TITLE
Add

### ISSUE THREAD

**Issue by Leggrand** [gravitee-io/issues#1071]
When you access the APIs or Applications don't display the create button. So we can't create a new API or a new Application.

### Expected Behavior
When access the APIs or Applications management show the create button, then this make the possible create a new api or application.

### Current Behavior
When access the management UI don't show the create button on any page: Applications, APIs.

### Context
Ruuning on docker.

### Your Environment

* Version used: 1.13.2
* Browser Name and version: Google Chrome 63.0.3239.132 (Versão oficial) 64 bits
* Operating System and version: Windows 10 x64

**Comment by brasseld** [comment]
Hi @Leggrand,

How are you connecting to the portal ? Using login form / social auth / oauth2 ?

**Comment by Leggrand** [comment]
Hi @brasseld,

I'm connecting to the portal using login form.

**Comment by brasseld** [comment]
Which account are you using ?
You have registered for a new account or you had use an existing one ?

**Comment by Leggrand** [comment]
Yeah, I couldn't be logon on admin's account. So, I'm reseted the password and now I can connect on admin's account

Tnk for your help my friend.
