### ISSUE TITLE
Cannot always scroll display of Gateway instance in API Management

### ISSUE THREAD

**Issue by hfuru** [gravitee-io/issues#1090]
Cannot always scroll the display in Firefox of a Gateway instance in API Management,
when  contextual documentation bar to the right is open.
Depends on the size of the Firefox window.  [Example screenshot](http://folk.uio.no/hbf/gravitee-screenshot.png).

### Expected Behavior

Normal scrolling up/down

### Current Behavior

See below
### Steps to Reproduce (for bugs)

1. With Firefox, log in as an administrator
2. Go to Administration: Gateways: (pick a gateway)
3. Ensure the contextual documentation bar to the right is open (via button next to avatar)
4. Size the browser window so it reaches at least down to plugin:groovy.  Though I'm guessing how far down depends on font sizes and whatnot.
5. Try to scroll the browser window via the Firefox slider at the right.  The window doesn't move.
6. It will scroll if I resize the window to be shorter (stop at plugins:mock) or close the contextual documentation.
7. The Monitoring display of the gateway also sometimes doesn't scroll.  Not sure when, it seems more unpredictable.
### Your Environment

* Version used: graviteeio-full-1.13.3
* Browser Name and version: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0, with various extensions including noscript and adblock. I've disabled those for Gravitee though.
* Operating System and version: RedHat Linux, RHEL 7.4

**Comment by brasseld** [comment]
No more relevant
