### ISSUE TITLE
Do not treat LDAP adminLimitExceeded as an error

### ISSUE THREAD

**Issue by hfuru** [gravitee-io/issues#1091]
When typing a user name to add in Configuration:Roles, Gravitee
displays a red error message if it receives LDAP adminLimitExceeded.

It should not.  adminLimitExceeded is a normal occurrence with
some kinds of searches, like substring search.  It means the
server rejects this operation or part of it, maybe because the
search term was too general.  This is independent of
client-specified limits, which are applied during the operation.

### Expected Behavior

No error message, or only in debug mode when an admin is trying
to find out why their LDAP config doesn't work.  Or always display it,
but not as an error/warning - just info about how the search is going.

### Current Behavior

Our LDAP is configured to return adminLimitExceeded if there
would be too many matches.  It just would be annoying to return
sizeLimitExceeded and some arbitrary matching users.  With our
60000 users, the list would rarely include the desired match.

So Gravitee displays red errors while the user types the first
characters in a name, then switches to displaying a list of users
when there are few enough matches and LDAP does return them.

### Steps to Reproduce (for bugs)

1. Set up Gravitee to use LDAP
2. Set up LDAP to return adminLimitExceeded in some cases.  With OpenLDAP,
e.g. with "olcSizeLimit: size.unchecked=200": Fail if more than 200 matches after
consulting indexes.  Note that this number includes possible hash collisions, so
it should be higher than the actual desired max.
3.  In the browser, go to Administration:Configuration:Roles:(add a user).
4. Start typing a user name.

### Context

I don't want it to look like something is wrong when all is well.

### Your Environment

* Version used: graviteeio-full-1.13.3
* Browser Name and version: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
* Operating System and version: RedHat Linux, RHEL 7.4

**Comment by brasseld** [comment]
I had a try with Apache Directory Studio, setting `ads-maxSizeLimit` to a low value (20) but it seems that the behavior of ADS is not the same as OpenLDAP.

Also, what I do not understand is that when doing a search we are clearly asking to limit the number of results, so I don't know how we can reach this adminLimitExceed.

```java
LdapQuery ldapQuery = LdapQueryBuilder
             .query()
             .base(baseDn)
             .countLimit(20)
             .timeLimit(5000)
             .searchScope(SearchScope.SUBTREE)
             .attributes(
                     LDAP_ATTRIBUTE_GIVENNAME,
                     LDAP_ATTRIBUTE_SURNAME,
                     LDAP_ATTRIBUTE_MAIL,
                     LDAP_ATTRIBUTE_DISPLAYNAME)
             .filter(new AndFilter().and(classFilter).and(queryFilter));
```

**Comment by hfuru** [comment]
On 21. feb. 2018 08:53, Brassely David wrote:
> I had a try with Apache Directory Studio, setting |ads-maxSizeLimit| to a low 
> value (20) but it seems that the behavior of ADS is not the same as OpenLDAP.

Not if it doesn't have something similar to the "unchecked" limit, no.

> Also, what I do not understand is that when doing a search we are clearly 
> asking to limit the number of results, so I don't know how we can reach this 
> adminLimitExceed.

Like I said, it's independent of the your client-specified limit.

The operation is rejected before it gets far enough to discover that it
would hit that limit.

Try our LDAP with the config below, and search for me.  It's structured
like our config, but searches different LDAP trees/classes, and the
groups/roles have dummy values.

     - type: ldap
       context-source-url: "ldaps://ldap.uio.no/"
       context-source-base: "dc=uio,dc=no"
       user-dn-patterns: "uid={0}"
       user-search-base: "cn=people"
       user-search-filter: "uid={0}"
       user-search-objectclass: "inetOrgPerson"
       group-search-base: "cn=group"
       group-search-filter: "(uid={0})"
       group-role-attribute: "cn"
       role-prefix: "none"
       role-mapping: true
       role-mapper: {
         FSPROD: USER,
       }

The server cert has root CA "DigiCert Assured ID Root CA", which is part
of /etc/ssl/certs/ca-bundle.crt on RedHat at least.  Or you could use
'ldap:' instead, just make sure no passwords for real users get sent.

-- 
Hallvard

**Comment by hfuru** [comment]
Hmm, should clearly have narrowed down the reply-to list.  anyway:

On 21. feb. 2018 11:25, Hallvard Breien Furuseth wrote:
>> Also, what I do not understand is that when doing a search we are clearly 
>> asking to limit the number of results, so I don't know how we can reach 
>> this adminLimitExceed.
> 
> Like I said, it's independent of the your client-specified limit.
> 
> The operation is rejected before it gets far enough to discover that it
> would hit that limit.

To explain a bit more: The server first consults its indexes, based on
filter, scope etc, and finds a set of candidate entries.  If that set is
bigger than the "unchecked" limit, the search stops right there and gets
adminLimitExceeded.  The server never looks at the candidate entires.
Otherwise it starts walking through the candidate entries, returning
those that match the filter, until done or a size/time limit is reached.

-- 
Hallvard

**Comment by brasseld** [comment]
Ok I got it with your LDAP.

So in that case, the search returns an empty list and we add a WARN log in the mgmt-api log files.

Is this ok for you ?

**Comment by hfuru** [comment]
On 21. feb. 2018 11:52, Brassely David wrote:
> So in that case, the search returns an empty list and we add a WARN log in 
> the mgmt-api log files.
> 
> Is this ok for you ?

Yes, fine.  That or INFO.

-- 
Hallvard
