### ISSUE TITLE
[portal] Refactor API Menu

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#1101]
```
Portal
	General
		Details (header d'api uniquement sur cette view) - description + icone + version + visibility
		+ portal views + labels + import / export + danger zone delete (à la github)
	Plans
		Plans
		Subscriptions
	Documentation
		Pages
		Metadata
	User and group access
		members
		groups
		transfer ownership
Gateway
	General
		Details (start / stop + context-path + logging)
		CORS
		Deployments (sharding-tags)
	Backend services
		Endpoints (+ Discovery (consul.io / ...))
		Load-balancing (LB + failover)
		Health-check
Design
    General
        Policies
	    Resources
	    Properties
Analytics
	General
		Overview
		Logs
Audit
	General
		Audit
		History
		Events
Notifications
```

Currently, the Configuration menu manages views, sharding tags, tenants, and groups.
With #468 an other configuration item will appears.

It can be useful to split the config menu between portal configuration and platform configuration.

Platform Cfg :

sharding tags
tenants
Portal Cfg :

views
groups
pages

**Comment by NicolasGeraud** [comment]
see #1124 for the refactoring of the Configuration menu

**Comment by fabMrc** [comment]
why create a new page for SD support and not include it on endpoint pages (select endpoint strategy for exemple, static, consul, eureka, ETCD, kubernetes) ?
and allowing in this way reuse of all others common parameters

**Comment by aelamrani** [comment]
OK to put SD sub menu to endpoints... i just updated the issue 👍
