### ISSUE TITLE
Store API config in a git repository

### ISSUE THREAD

**Issue by Tony-Proum** [gravitee-io/issues#1105]
Gravitee configuration could be versioned and stored in a git repository.

### Expected Behavior

API management configuration should have a project life-cycle that could be manage like all other projects.

### Current Behavior

A user create many gravitee environment on production, pre-production and some other platforms. Another user has the idea to test a behavior in pre-production environment. This test became a implicit behavior of the pre-production environment. Also, when this customer wanted to put a new version of it's product in production, he cannot understand why the configuration were not the same in production's API M and pre-production API M.

### Possible Solution
All the configuration should be pulled from a central git repository to ensure having a consistency over all environments

### Context
leaving an ear hanging 😄

**Comment by brasseld** [comment]
Hi @Tony-Proum 

Why not using export / import features of Gravitee ?

**Comment by Tony-Proum** [comment]
Yes I think that could be a workaround thanks !

Also, do you plan or studying a solution to allow teams to have something like API management as code or else ?

**Comment by brasseld** [comment]
Sorry, but I did not get you. 

WDYM by `a solution to allow teams to have something like API management as code or else` ?

**Comment by Tony-Proum** [comment]
Imagine I would install gravitee in an automated way for multiple environment. Will I have to install it on a platform, do a first configuration manually and finally export / import the configuration elsewhere ? or could I use something like a yml file to config my entry points ? (I didn't find discussions or documentation about this topic)

**Comment by brasseld** [comment]
I suppose you can invoke the management-api using CURL if you want to do so.
I know that some users are running Ansible to create APIs...

**Comment by brasseld** [comment]
Is it good for you @Tony-Proum ?

**Comment by Tony-Proum** [comment]
Yes Thanks, I think that I will try this way
