### ISSUE TITLE
[portal] APIs views

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#112]
When there are many and many APIs, the main portal page is not really useful for consumers and publishers to have a quick look to a group of APIs.
The idea here would be to create some kind of « views ». By default, portal must provide these views : my APIs (for which I’m owner / primary_owner), consuming APIs, favorites. Also, it will be very useful to define custom views (using a filter on the API manager / publisher, API tags, ...)

**Comment by aelamrani** [comment]
And gateway instances for admin users no?

**Comment by brasseld** [comment]
I'm talking about API view, what is the link with gateway instances ?

**Comment by aelamrani** [comment]
I think the issue should be more general and maybe we should provide specific main portal page for each kind of user...

**Comment by brasseld** [comment]
According to me, you're not talking about portal page but "dashboard" page...

**Comment by aelamrani** [comment]
Actually, i'm talking about **home** page...
