### ISSUE TITLE
[portal] Global events history

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#113]
Admin user should be able to see all the events in the platform (deploy / undeploy / start / stop events)

To get more details about APIs behavior, Admin should also see the following data : 

- **Top applications** order by API calls
- **Top failed APIs** order by APIs 5xx status calls
- **Top slow APIs** order by APIs response time calls

Admin should have the possibility to filter by API, Application and Event Type and choose a time interval.

**Comment by tcompiegne** [comment]
Here's a sneak peek at what's the admin dashboard is going to look like : 

![admin-dashboard](https://cloud.githubusercontent.com/assets/1927438/17287838/379f2d62-57d2-11e6-8ded-fed8dddfa16f.png)

@brasseld, @NicolasGeraud, @aelamrani, @lusoalex what do you think ?

**Comment by lusoalex** [comment]
Hello,

On filtering part, there's : LAST HOUR, LAS DAY... do you expect to add "CUSTOM"?
==> In fact, from my point of view, as soon as you select some date and then click on APPLY button, we can consider we are on custom ;)

The filtering part on API & Application is really a great idea!
Following how APIs will be grouped later, it could be usefull to filter on a group also. (But not possible currently)

Finally one more report which could be usefull : **TOP overheaded API.**
In this report, i expect to see APIs which consume more time inside the gateway _(only into the gateway, not carrying about the backend response time)_
It will highlight (i guess) APIs with too much/slows policies...

Wdyt?

Nothing more to say, it looks great 👍  (maybe with some more colors :D )

Good luck!

**Comment by tcompiegne** [comment]
Hello Alexandre,

As you pointed out, the datepickers let you choose any time interval you want, so yes, this is the custom part ;).

**TOP overheaded API** is a great idea and it will be added asap.

And the colors ... in my opinion it's the hardest part :D, I'll try to find something nice.

Thanks for the feedback.

Stay tuned.
