### ISSUE TITLE
[management] Reference data identifying a user is not consistent accross management API cluster

### ISSUE THREAD

**Issue by fabMrc** [gravitee-io/issues#1133]
Hi

Behind a Proxy , 2 api node
When I get a user with /search/users?q=myuser I get a json structure composed of 
* id 
* reference
* displayName

Because id is not always present (for exemple with default admin user) I use reference to identify my user in next actions

Now I want to transfer ownership using rest api
the endpoint response HTTP 404 user not found randomly

In a basic context with only one api node I have not such error, If a use user ID I have not error 

Seems clustering context generate some issue using user with reference

**Comment by fabMrc** [comment]
Any news about a release date that could embed this fix ?

**Comment by NicolasGeraud** [comment]
tomorrow if everything's ok.

**Comment by fabMrc** [comment]
Before Reopen a new issue I would just to be sure the bug is not fixed. With the 1.14.3 my admin local user with no ID but a reference ID works whereas it was not working before.
Now when a want to transfer ownership to a SSO user (hosted in a Keycloak) using the Reference ID it fails. The user is not found.
Please keep me in touch
