### ISSUE TITLE
[management] can not change  user role 

### ISSUE THREAD

**Issue by yang-dw** [gravitee-io/issues#1134]
can not change  user role  when the user is Logged by oauth2 !
when I find an user and selected it , the input will show  "[object Object]"
![qq 20180308154617](https://user-images.githubusercontent.com/28995740/37140053-4f7d42bc-22eb-11e8-9e85-bbbee72cf118.jpg)
![qq 20180308154710](https://user-images.githubusercontent.com/28995740/37140054-50a80b0e-22eb-11e8-8892-fdc360eeeeea.jpg)
![qq 20180308160856](https://user-images.githubusercontent.com/28995740/37140057-514ccedc-22eb-11e8-92af-36aa6215ac07.jpg)

**Comment by yang-dw** [comment]
I find , but I  don't konw how to fix it !

**Comment by NicolasGeraud** [comment]
hi @yang-dw what is your java version ?

**Comment by yang-dw** [comment]
hi @NicolasGeraud   java 8

**Comment by NicolasGeraud** [comment]
yes, but can you give me the output of `java -version`?

**Comment by yang-dw** [comment]
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)



docker  base  on java:8

**Comment by NicolasGeraud** [comment]
Are you able to upgrade to the latest java 8 version ? (8u162-b12)

**Comment by yang-dw** [comment]
OK

**Comment by yang-dw** [comment]
oh, so Nice , Thank you！ @NicolasGeraud

**Comment by NicolasGeraud** [comment]
I reopen this issue because we have to fix that

**Comment by yang-dw** [comment]
ok ,I don't know which is the right flow, you close or I close . Maybe，I did the wrong operation.

**Comment by brasseld** [comment]
Hi @yang-dw 

I see in screenshots that you have translate a part of the UI.
Perhaps you can share the i18n for chinese ?

Thanks a lot !

**Comment by yang-dw** [comment]
@brasseld  ok , My pleasure !

**Comment by NicolasGeraud** [comment]
hi @yang-dw ,

the root cause of this issue is described here : 
https://golb.hplar.ch/2017/10/JCE-policy-changes-in-Java-SE-8u151-and-8u152.html

This is why upgrading the jdk has solved it.

**Comment by yang-dw** [comment]
Thanks. I've been upgraded to the latest java 8 version!
