### ISSUE TITLE
[reporter] [elasticsearch] logging fail when header has null value

### ISSUE THREAD

**Issue by tdaghelet** [gravitee-io/issues#1140]
I use the transform header policy to create a header and sometimes the value of this header is null.

The API call works perfectly but I have an error in the log generation ([stack_error_log.txt](https://github.com/gravitee-io/issues/files/1811630/stack_error_log.txt))

How can we fix this ?
We see 2 solutions with @NicolasGeraud : 

- fix the log.ftl of the reporter-elastic to skip null values
- fix the transform header policy to prevent sending of the header if it value is null

What do you think about that @brasseld ?

Thank you

**Comment by brasseld** [comment]
which version of g.io ?

**Comment by tdaghelet** [comment]
1.13.3

**Comment by brasseld** [comment]
Are you sure that when the header's value is null, the value is transferred to the backend ?

**Comment by tdaghelet** [comment]
I'm not sure : I have my master API which call a sub API (both are on gravitee).

On the master API, I define a header with a null value and I call it : the log of the master API is empty because of the freemarker exception, and I can see the log on the sub API without this header. So I think that the header is not sent, else the log of the sub API should fail too

**Comment by brasseld** [comment]
ok, I will have a try.
