### ISSUE TITLE
[management] Allows to create a template for HTTP configuration for endpoints discovered by SD

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#1141]
This feature allows to create a template of endpoint on an endpoint group. 
This will allow especially to dynamically set the endpoint http configuration when service discovery is enabled.
The endpoint configuration override the group configuration.
The group HTTP configuration is mandatory.
The endpoint http configuration is by default inherited but can be overridden at the endpoint level.

**Comment by brasseld** [comment]
This will be done through endpoints group.
The goal will be to associate a default configuration for each endpoints which are part the group.
