### ISSUE TITLE
Cannot view analytics on Management UI

### ISSUE THREAD

**Issue by hunghoang** [gravitee-io/issues#1145]
I download version 1.14.2. 
When I:
1. start all component, add API and call it from postman
2. Browse Analytic on Management UI component

### Expected Behavior
All charts should be shown with related data

### Current Behavior
All charts have no data

### Possible Solution
I think there is a problem with ElasticReporter.
I can access Elastic from that server so i'm pretty sure no problem related connection to ElasticSearch.
I'm using Chrome, so I enable Developer Tab, take a look at network tab, and see empty response (http status = 200) for all the requests getting statistic data.
I see the strange exception in Gateway console:

freemarker.template.TemplateNotFoundException: Template not found for name "index-template-es-6x.ftl"

### Your Environment

* Version used: 1.14.2, 1.13.3, 1.13.2
* Browser Name and version: Chrome (latest)
* Operating System and version: Windows 10.

**Comment by NicolasGeraud** [comment]
Hi, es6 is not curently supported. You need v5.

**Comment by hunghoang** [comment]
That works wit ES V5. Should the doc be updated?
Thanks

**Comment by NicolasGeraud** [comment]
@hunghoang done. => https://docs.gravitee.io/apim_installguide_repositories_elasticsearch.html

thanks.
