### ISSUE TITLE
[portal] when creating the default application, give it the user name in place of "default app"

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#1153]
By default and if the option is enabled, a `default application` is created after first user connection.

Most of the time users don't change the name of the default app and administrator users end up with a lot of "same" applications which can be hard to maintain.

It can be useful to create the default app with a name containing the username.

**Comment by brasseld** [comment]
I'm not sure it's a good idea to change the default application since the problem is only valid for the administrator who is retrieving the full list of application.

**Comment by brasseld** [comment]
Why not providing a new column in the table containing the owner of the application if authenticated user is admin ?
