### ISSUE TITLE
[gateway] Authorization type is removed from header

### ISSUE THREAD

**Issue by LuisTAC** [gravitee-io/issues#1161]
I have a `Sample API` registered in the gateway, that's being secured by a fake/mocking OAuth server resource, `OAuth_Fake`, that gets the token through the Authorization header.
In the implementation of `OAuth_Fake` server, there's a logger printing the content of the header.  By making a direct request to it, the log prints just fine, `Authorization: Bearer <TOKEN>`, but if I make a request to the `Sample API`, which will then call the `OAuth_Fake` server with the same header, the log prints in the format `Authorization: <TOKEN>`.

API definition:
```json
{
  "id": "72e2237a-9546-4e07-a223-7a95466e0701",
  "name": "Sample API",
  "version": "v1",
  "description": "Sample API",
  "visibility": "public",
  "state": "started",
  "tags": [],
  "labels": [],
  "context_path": "/sampleapi",
  "proxy": {
    "context_path": "/sampleapi",
    "strip_context_path": false,
    "loggingMode": "NONE",
    "endpoints": [
      {
        "name": "default",
        "target": "http://localhost:8091",
        "weight": 1,
        "backup": false,
        "type": "HTTP",
        "http": {
          "connectTimeout": 5000,
          "idleTimeout": 60000,
          "keepAlive": true,
          "readTimeout": 10000,
          "pipelining": false,
          "maxConcurrentConnections": 100,
          "useCompression": true,
          "followRedirects": false
        }
      }
    ],
    "load_balancing": {
      "type": "ROUND_ROBIN"
    }
  },
  "paths": {
    "/white": [],
    "/black": [],
    "/_health": [],
    "/": []
  },
  "deployed_at": 1521219824791,
  "created_at": 1521122279162,
  "updated_at": 1521219824791,
  "owner": {
    "id": "b1cfe374-5b3a-4e60-8fe3-745b3a5e60a3",
    "displayName": "admin"
  },
  "services": {},
  "picture_url": "http://localhost:8083/management/apis/72e2237a-9546-4e07-a223-7a95466e0701/picture",
  "resources": [
    {
      "name": "OAuth_Fake",
      "type": "oauth2",
      "enabled": true,
      "configuration": {
        "authorizationServerUrl": "http://localhost:8091",
        "introspectionEndpoint": "oauth/authorize",
        "introspectionEndpointMethod": "GET",
        "scopeSeparator": "",
        "userInfoEndpoint": "",
        "userInfoEndpointMethod": "GET",
        "useClientAuthorizationHeader": false,
        "clientAuthorizationHeaderName": "",
        "clientAuthorizationHeaderScheme": "",
        "tokenIsSuppliedByQueryParam": false,
        "tokenQueryParamName": "",
        "tokenIsSuppliedByHttpHeader": true,
        "tokenIsSuppliedByFormUrlEncoded": false,
        "tokenFormUrlEncodedName": "",
        "clientId": "FAKE_CLIENTID",
        "clientSecret": "FAKE_CLIENTSECRET",
        "tokenHeaderName": "Authorization"
      }
    }
  ]
}
```
Plan definition:
```json
{
  "id": "c4715059-79e7-4fcc-b150-5979e73fcca7",
  "name": "OAuth Plan",
  "description": "OAuth Plan",
  "validation": "auto",
  "security": "oauth2",
  "securityDefinition": "{\"extractPayload\":false,\"checkRequiredScopes\":false,\"requiredScopes\":[],\"oauthResource\":\"OAuth_Fake\"}",
  "type": "api",
  "status": "published",
  "apis": [
    "72e2237a-9546-4e07-a223-7a95466e0701"
  ],
  "order": 2,
  "characteristics": [],
  "created_at": 1521122968155,
  "updated_at": 1521214374713,
  "published_at": 1521122971739,
  "paths": {
    "/": []
  },
  "excluded_groups": []
}
```

### Expected Behavior

It's expected that the content of the Authorization header doesn't change from the Gateway request to the OAuth request.

### Current Behavior

Currently, part of the Authorization header content is removed, specifically its type.

### Context

I believe this bug is the reason why I can't get successfully authorized in the real OAuth server.

**Comment by brasseld** [comment]
Hi @LuisTAC,

Your issue is caused by the empty value for `clientAuthorizationHeaderScheme` property. Please set it to `Bearer` and it should work as expected.

Thanks for your feedback.

**Comment by LuisTAC** [comment]
Unfortunately, it didn't. I ran a series of tests and none of them were successfull. The changes made and the respective resulting log are in the following table.

Changes | Result 
----|----
`"clientAuthorizationHeaderScheme":"Bearer"`	|	Authorization: \<TOKEN>
`"clientAuthorizationHeaderName": "Authorization", "clientAuthorizationHeaderScheme": "Bearer"`	|	Authorization: \<TOKEN>
`"useClientAuthorizationHeader": true, "clientAuthorizationHeaderName": "Authorization", "clientAuthorizationHeaderScheme": "Bearer"`	|	Authorization: [Bearer RkFLRV9DTElFTlRJRDpGQUtFX0NMSUVOVFNFQ1JFVA==, \<TOKEN>]
`"useClientAuthorizationHeader": true, "clientAuthorizationHeaderName": "Authorization", "clientAuthorizationHeaderScheme": "Bearer", "tokenIsSuppliedByHttpHeader": false`	|	Authorization: Bearer RkFLRV9DTElFTlRJRDpGQUtFX0NMSUVOVFNFQ1JFVA==
`"useClientAuthorizationHeader": true, "clientAuthorizationHeaderScheme": "Bearer"`	|	Authorization: \<TOKEN>

**Comment by LuisTAC** [comment]
Also, could you better explain what the Client Authorization Header properties are supposed to do? The description in the documentation isn't really clear.

> To prevent token scanning attacks, the endpoint MUST also require some form of authorization to access this endpoint. In this case we are using an HTTP header for client authentication.

My understanding is that the `tokenIsSuppliedBy(*)` and `token(*)Name` properties refer to passing the token to the OAuth server endpoint mentionded in the OAuth resource, while the `clientAuthorization` properties are used to pass client authorization details to the backend endpoint. Is this right? If so, does it make sense to change `clientAuthorizationHeaderScheme` to `Bearer` to use the OAuth resource?
Thanks, in advance.

**Comment by brasseld** [comment]
Hi @LuisTAC 

I'm sorry but I did not get you.

The purpose of the gateway is to validate an incoming access_token extracted from `Authorization` header against an authorization server.
So, the gateway extracts the token and send it to the authorization server through a check_token or introspection endpoint.
In that case, the token should not be send using the same `Authorization` header since this header can be used to authenticate the `ressource` which is trying to validate the token. Please have a look to https://tools.ietf.org/html/rfc7662#section-2.1:

```
To prevent token scanning attacks, the endpoint MUST also require
   some form of authorization to access this endpoint, such as client
   authentication as described in OAuth 2.0 [RFC6749] or a separate
   OAuth 2.0 access token such as the bearer token described in OAuth
   2.0 Bearer Token Usage [RFC6750].  The methods of managing and
   validating these authentication credentials are out of scope of this
   specification.

   For example, the following shows a protected resource calling the
   token introspection endpoint to query about an OAuth 2.0 bearer
   token.  The protected resource is using a separate OAuth 2.0 bearer
   token to authorize this call.

   The following is a non-normative example request:

     POST /introspect HTTP/1.1
     Host: server.example.com
     Accept: application/json
     Content-Type: application/x-www-form-urlencoded
     Authorization: Bearer 23410913-abewfq.123483

     token=2YotnFZFEjr1zCsicMWpAA
```

**Comment by brasseld** [comment]
Hi @LuisTAC 

what do you think about my latest comment ?

Regards,

**Comment by LuisTAC** [comment]
Hi again, @brasseld.
I wasn't able to fullly understand your comment, but I think it goes along the same lines as my previous question. The documentation and even the proposed standard its based on aren't really clear. I'll try to create a sequence diagram of my understanding and get back to you later.
Thanks for your response.

**Comment by brasseld** [comment]
Hi @LuisTAC 

We have a gitter channel: https://gitter.im/gravitee-io/gravitee-io
If you want we can have a direct chat there.

**Comment by LuisTAC** [comment]
A closing comment on this issue:
Talking with @brasseld through gitter, he explained all my questions which were in fact OAuth and authorization in general related, and not specific to Gravitee.io API Management solution. Maybe if I had better knowledge of this subject this issue wouldn't be created. But since there will probably be more people like me, I think it would be better to improve the documentation for the [Generic OAuth2 Authorization Server Resource](https://docs.gravitee.io/apim_resources_oauth2_generic.html) and [OAuth2 Policy](https://docs.gravitee.io/apim_policies_oauth2.html) pages. Stating exactly what the fields are for and how they modify the behavior of the request would be nice.
Thanks for the help, @brasseld.
