### ISSUE TITLE
How to manager API versions

### ISSUE THREAD

**Issue by hunghoang** [gravitee-io/issues#1185]
I have multiple versions of my API. How can I keep all version available in Gravitee.
### Expected Behavior
If I have a hello API, I can edit version property to create new version.
Then I can maintain 2 versions:
/hello-api/1.0.0 (first version)
/hello-api/1.0.1 (second version)
### Current Behavior
For now, I cannot do that. The new version seem to override the previous one.
Could you please help? Does Gravitee has that such feature? 
Thanks.

### Your Environment

* Version used: 1.14.3
* Browser Name and version: Chrome
* Operating System and version: Sieraa OS

**Comment by hunghoang** [comment]
Let's say we have one api with version 1.0.0
Now we have a new feature and we only want publish it for some applications for the experiment.
Could we publish this api with new version 1.0.1 and still keep the old one?

**Comment by NicolasGeraud** [comment]
if your new feature is a new route in your API, you can manage that with a new plan.
Let say we have a plan "stable" and a plan "latest", add a path restriction on the "stable" plan to forbid the new feature.

**Comment by hunghoang** [comment]
I don't want to define a new route, only the same route but with different version shoud be good.
So what the 'version' is supposed to be?

**Comment by NicolasGeraud** [comment]
so in your case you have 2 options, 

 - define 2 apis in gravitee, and introduce the version number in your context path (i.e. `/v1.0.0/myapi`and `/v1.0.1/myapi`and manage subecriptions on those 2 APIs.
 - define 2 paths on the same api (context path `/myapi` and path `/v1.0.0` and `/v1.0.1`) and if you really want to forbid one version for one application, use the ip filtering policy or implement the rule in groovy

**Comment by hunghoang** [comment]
Ok Thank Nicolas

**Comment by sunilb20** [comment]
Thanks, Option 2  helped.
However if I have to implement JSON to JSON transformation for each version, Is it possible ?
Transformation policy is applicable per api and it seems it can not be linked with versioning created using dynamic routing for same API. 

What do you think about this ?

**Comment by brasseld** [comment]
@sunilb20 All the policies are applicable to a single API for a given path and a couple of HTTP methods, meaning that you can have any policy for a specific path and a specific HTTP method, for example:

/products POST - Do transformation

Are you aware of this ?

**Comment by sunilb20** [comment]
Thanks!!! Have implemented for Paths but good to know about HTTP methods.

**Comment by brasseld** [comment]
May I close this issue @sunilb20 ?

**Comment by lpulec** [comment]
Hi @NicolasGeraud,
Is it possible to use _${api.version}_ property in API context-path?
When I try it, I get error message.

![image](https://user-images.githubusercontent.com/57493832/68929641-0a21ec80-078d-11ea-8e0c-2ec4e4d0abcf.png)

I'm not sure, but I think it was working in earlier version.
**Gravitee version:** 1.29.6

Thank you,
Lukas

**Comment by brasseld** [comment]
Hi @lpulec 

You can't use api.version in the path, but that's a nice idea. May I ask you to create a new issue for this?

Regards,

**Comment by lpulec** [comment]
Hi @brasseld,
ok, created #2889 

Regards
