### ISSUE TITLE
[global] Remove the definition from the API object

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#1196]
Currently, the API object is containing the full API definition.
It should not be a problem till you have a large number of 'complex' APIs.

We must have to avoid to mount all the API definitions each time we are invoking `apiRepository.findAll()` because it ends with an highest memory consumption and CPU usage (each 5 seconds by default).

**Comment by aelamrani** [comment]
Closed by https://github.com/gravitee-io/issues/issues/1367
