### ISSUE TITLE
[management] I can't submit a support ticket !

### ISSUE THREAD

**Issue by yang-dw** [gravitee-io/issues#1202]
the model of PrimaryOwnerEntity ，A field is missing，the errors below .

12:59:56.505 [gravitee-listener-22] INFO  i.g.m.service.impl.TicketServiceImpl - Creating a support ticket: NewSupportEntity{subject='gongdan', content='gongdan 222222222', application='ebc65abb-09b8-498c-865a-bb09b8a98c29', api='038927f4-0cad-489c-8927-f40cad489c11', copyToSender='true'}
12:59:57.301 [gravitee-listener-22] ERROR i.g.m.service.impl.EmailServiceImpl - Error while sending email notification
freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> application.primaryOwner.username  [in template "supportTicket.html" at line 12, column 75]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

**Comment by NicolasGeraud** [comment]
@yang-dw I thing it's better to fix the template (with the displayName) instead of adding the username in the PrimaryOwnerEntity.

wdyt ?

**Comment by yang-dw** [comment]
yeah , only I can't find the template where it is

**Comment by NicolasGeraud** [comment]
https://github.com/gravitee-io/gravitee-management-rest-api/blob/master/gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/templates/supportTicket.html

**Comment by yang-dw** [comment]
But which field should I use?

**Comment by yang-dw** [comment]
ok，I corrected it

**Comment by NicolasGeraud** [comment]
perfect, thanks for your contribution.

By the way, you could have forcepush your code on the previous pull request instead of close it and open a new one.
