### ISSUE TITLE
A user with username xxxx already exists error when using oauth and upgrading from 1.13.0 to 1.15.0 

### ISSUE THREAD

**Issue by chicco785** [gravitee-io/issues#1203]
### Expected Behavior
A previously existing user that was able to login with OAuth in 1.13.0 should be able to login also 1.15.0

### Current Behavior
User previously registered using OAuth cannot log-in.

### Possible Solution

To be investigated.

### Steps to Reproduce (for bugs)

1. Gravitee is configured to support only OAuth.
1. Login is working correctly using 1.13.0
1. When updating to 1.15.0 login is not working and the following error is returned: "A user with username xxxx already exists"

**Comment by NicolasGeraud** [comment]
hi @chicco785 
have you ran mongodb migrations scripts ? (https://docs.gravitee.io/apim_installguide_migration.html)

Especially this one : 1-users-migration.js

**Comment by chicco785** [comment]
hi,
indeed the migration seems to solve the issue!
