### ISSUE TITLE
[Dynamic routing] Routing doesn't fail with non existing endpoint

### ISSUE THREAD

**Issue by tdaghelet** [gravitee-io/issues#1204]
Hello,

We make dynamic routing with header like this :
{#endpoints['ENDPOINT_'+#request.headers['x-bu-code']]}/path1/path2

Sometimes, the resolved endpoint name doesn't match with any endpoint defined on the API, for example doesn't exists ENDPOINT_PLLM, and the gateway choose randomly an endpoint.

Should the gateway/dynamic routing policy not return an error if the requested endpoint name doesn't exist ?

**Comment by brasseld** [comment]
Hello @tdaghelet 

You're right, it may be a good option to send a 503 service unavailable in this case.

Regards,

**Comment by tdaghelet** [comment]
Ok,

Do you think it's the responsability of the policy to verify this or the gateway ?

I just reproduced in debug this problem in order to make a pull request, and for my example the SpelTemplateEngine resolve /path1/path2 as endpoint because {#endpoints['ENDPOINT_'+#request.headers['x-bu-code']]} return empty value.

Can we assume that the endpoint resolved by the policy must be start with http/https or else return a http 503 ?

**Comment by NicolasGeraud** [comment]
No, the policy allows relative path. 

So I think the errors must be thrown by the `•endpoints[]`call.

wdyt @brasseld ?
