### ISSUE TITLE
[management] sharing client id and secrets with developers

### ISSUE THREAD

**Issue by chicco785** [gravitee-io/issues#1205]
It would be nice to allow users, once subscribed to an API that is protected by OAuth, to see the client_id and secret_id that are needed to be configured in their apps to use a given OAuth protected API.

**Comment by brasseld** [comment]
Hi @chicco785,

Currently, only the `client_id` is needed to be configured per application.
We have no reference to any `client_secret`.

**Comment by chicco785** [comment]
hi @brasseld 
but you do support (require?) the client secret in the oauth part, so it would make sense to have it, or not (and keep it in synch with the resource one)?

**Comment by chicco785** [comment]
to interact with OAuth protected API from command line (rather than only
via oauth standard flow) you will need that or I am wrong?
i suppose APIs are not going only to be used via web apps

**Comment by brasseld** [comment]
From command-line, yes, you need them to interact with the authorization-server and generate an access_token. Then you use this access_token to make calls to protected API.

**Comment by chicco785** [comment]
correct, so to enable developers to do so, there would need to be the
possibility to advertise somewhere the secret

**Comment by brasseld** [comment]
Yes, know we have to figure it out how to get and store the client_secret.
Also, it is the responsibility of the application owner to provide these informations.

And finally, according to you, what would be the good places to inform the user about the client_secret to use ?

**Comment by chicco785** [comment]
hi,
in the short time, i would assume we can enter it manually. it would be
nice probably also to list the oauth grant-type supported (and depending on
that fill in secret or not).
then surely it could be nice to have a way to integrate this with an oauth
provider that has apis allowing to register and query clients (it could be
used also for the applications)

for the time being, the API owner (not sure why you mention the Application
owner) should provide this information.

from the point of view of the API subscriber, i think the most logic place
where to provide such information is in the subscriptions page, where he
sees also API Keys for a given APi.

feelings?

nice thing is that such information could be used as well to pre-configure:
- resource provider (or maybe, it is the other way around, you select from
which resource provider such client and secrete should be "read" to inform
the developer)
- swagger client (if needed)

**Comment by ryrun168** [comment]
Hi all, do you know the gravitee using technology for reverse proxy as zuul or spring cloud gateway?

**Comment by brasseld** [comment]
Hi @ryrun168,

Please create an other issue to ask your question since this one is not relative to the initial question.

**Comment by brasseld** [comment]
Hi @chicco785,

> then surely it could be nice to have a way to integrate this with an oauth
provider that has apis allowing to register and query clients (it could be
used also for the applications)

The best would be to follow https://openid.net/specs/openid-connect-registration-1_0.html specification for such thing.

> for the time being, the API owner (not sure why you mention the Application
owner) should provide this information.

Because, it is the rsponsability of the application to know about its own client_id and client_secret.... Seems there are some misunderstanding here...

**Comment by chicco785** [comment]
wait, the one thing are the Application client_id and client_secret,
another thing are the API client_id and client_secret.

we may need both, but they have different purpose.

the first one, is about authenticating the App, the second one is about
allowing the App to authenticate agains the API.

**Comment by brasseld** [comment]
Ok, so I fully agree with this. 

But your first comment was as follow:
> It would be nice to allow users, once subscribed to an API that is protected by OAuth, to see the client_id and secret_id that are needed to be configured in their apps to use a given OAuth protected API.

In this comment, you're talking about client_id and client_secret to be configured in apps, that's the reason why I was talking about the application owner.

**Comment by chicco785** [comment]
about opeind-connect-registration, totally agree!
we use keycloak and it supports that:
https://www.keycloak.org/docs/latest/securing_apps/index.html#openid-connect-dynamic-client-registration

**Comment by chicco785** [comment]
lol, sorry my fault, i wasn't clear, i meant that app developers need to
know the API client_id and client_secret (that's why i was thinking to link
them to the API key),
to be able to generate tokens towards the API.

**Comment by brasseld** [comment]
> app developers need to know the API client_id and client_secret (that's why i was thinking to link them to the API key)

Sorry but does it mean that you are using both api-keys and oauth access_token in the same time ? Meaning that applications are subscribing to api-key plan, and you have an oauth2 policy ? Why not defining oauth2 (or jwt) plan in that case ?

**Comment by chicco785** [comment]
indeed, but then also with the oauth2 plan, the developer does not see the
API client_id and secret, or am I missing something?

**Comment by brasseld** [comment]
I really don't understand why the developer has to see the API client_id / client_secret.

To clarify, and according to my understanding:
* API client_id / client_secret are the "credentials" to act as an OAuth Resource Server (ie. the gateway). These credentials must be put in an OAuth2 Resource (if you're relying on Keycloak, you are defining a Generic OAuth2 Resource, and, shortly, you will be happy to use the new Keycloak Resource :) )
These credentials are only used to check / introspect an incoming access_token.

* App client_id / client_secret are the "credentials" used to generate an access_token from an authorization server (your Keycloak instance). These should be shown to the developer during the subscription process.

Is it clear enough ? Do you agree ?

**Comment by brasseld** [comment]
Hi @zdenda-online 

> I think that App client_id / client_secret should be shown to the (TPP) developer during application creation (application is the client of AM), not during the subscription process (I suppose that when app subscribes to multiple APIs, it will still use the same client_id / client_secret credentials).

You're supposing well, one app = one client_id = multiple API subscriptions

> Is there any plan to implement showing client_id / client_secret to the developer (portal user) when registering application (I know there is a dynamic client registration with the app so probably after that step is done)? Or ideally, add some read-only field to application detail?

Yes, it is the purpose of implementing dynamic client registration from APIM.

**Comment by brasseld** [comment]
This has been developed as par of the DCR feature.

See https://github.com/gravitee-io/issues/issues/1580

**Comment by chicco785** [comment]
One question, by assuming that the developer needs to know only the app client and secret, somehow you assume that the token generated in the app can be accepted by the client used in the API. I am not sure this considered to be “usual”. Can you explain how you handle it? Thx!

**Comment by brasseld** [comment]
Sorry @chicco785 but I don't understand what you mean by:

> token generated in the app can be accepted by the client used in the API

Token is access_token ? Client is oauth client ?

**Comment by chicco785** [comment]
sorry:) i wrote from the phone, which leads me to be very concise.
In the scenario you were discussing above, in my understanding, the App developer (where app could be even a service - so no UI), will register a `OIDC client`. This OIDC client will be use by the App to obtain an `access_token`. At this point as far as I understand of the normal why clients works, you will be able to access the App, but no guarantee his given that this `access_token` can be used to access OIDC protected APIs. First of all because "scope" needed to access the API may not be the same as scope defined to access the "App", secondly because I believe you will need to put into place a token exchange mechanism (see [here](https://tools.ietf.org/id/draft-ietf-oauth-token-exchange-14.html)). Of course, I may be totally wrong!

**Comment by brasseld** [comment]
No worries,

I have to admit that I don't understand why you're a distinction between a client for an application and a client for an API... or perhaps I misunderstand something.

IMHO:
- A single client (oauth / oidc) is assigned to an application
- This application these client credentials to generate an access_token (AT)
- AT is used to call the API through the API Gateway
- API Gateway is validating the AT (using a public key if JWT) or by calling introspection endpoint on the authorization server (a dedicated client must be define in the authorization server to let the gateway being able to valide the AT (in keycloak, it is a bearer client))
- By validating the AT, we can have access to the scopes associated to the token
- API Publisher can add policy to validate that the incoming request is authorized to access a given resource (ex. /products) by checking that the token is associated to one or multiple scopes (should or must)

Hope it's clearest for you!

**Comment by chicco785** [comment]
Reading your flow, assuming App ODIC Client and API OIDC Client are different (which should be), it seems that you assume that a token issued for the App ODIC Client, can be validated against the API OIDC Client. I am simply not sure this assumption holds :)

**Comment by brasseld** [comment]
Why would you need an API OIDC Client ?
What's its purpose?

**Comment by chicco785** [comment]
To control the access to API from the API publisher perspective, which is not (always) the perspective of the API consumer (App developer in this case).

**Comment by brasseld** [comment]
but access to the API must be according to the token provided by the application, no ?

**Comment by chicco785** [comment]
that's why, as i was trying to explain at the beginning of the thread, that either 1) API Client/Secret somehow need to be exposable to the APP developer, so that he generate the token that the App will use to interact with the API, or 2) have in place, as mentioned above, token exchange at the level of the API gateway.

**Comment by brasseld** [comment]
So, I think I got your point.

Application Client / secret are specific client credentials per application to generate the token which will be used to call the API and then the API gateway will validate the token.

If you need token exchange, this will be done by the gateway itself, by exchanging the application access_token for a more specific token before calling your API backend. In that case, and according to the token exchange, you can make of API client / secret to access the exchange token protected endpoint.

But none of the application should have access to this API client / secret, since it is very specific to the API itself.

So, in your case, I think you would need a new policy Oauth2 Token Exchange to exchange for an app access_token for an API access_token.

**Comment by brasseld** [comment]
I'm pretty sure we are saying the same thing but with different vocabulary :)

**Comment by letshack** [comment]
@brasseld  - I am facing same issue "https://github.com/gravitee-io/issues/issues/1580" where ping federate is not returning registration_access_token and registration_uri. I see that other issue is closed. How did you guys fix it? Thank you !

**Comment by brasseld** [comment]
Hi @letshack 

Can you create a dedicated issue ? It would be easier to follow in the future.

Also if you can tell me more about the DCR integration done by Ping Federate. What can we do / we have to do if no registration_Access_token is returned ?

Thanks for your feedback.
