### ISSUE TITLE
[management-ui] swagger authentication not working using implicit flow

### ISSUE THREAD

**Issue by chicco785** [gravitee-io/issues#1206]
### Expected Behavior

When redirected to the auth url, the redirect_uri should be correct so that i can get
back to gravitee.

### Current Behavior
the following redirect uri is computed and auth fails:
http://localhost:3200/oauth2-redirect.html

### Possible Solution
configure swagger ui with oauth2RedirectUrl

https://github.com/swagger-api/swagger-ui/blob/911a140e38c8f292f7f64cf1dd9f77f00143579b/docs/usage/configuration.md

### Steps to Reproduce (for bugs)
1. register an api using oauth authentication and implicit flow
2. try to authenticate

**Comment by brasseld** [comment]
Ok, so as far as I understand, we have to set automatically the `oauth2RedirectUrl` property with the current browser URL, right ?

**Comment by chicco785** [comment]
to be tested, but i think that would be it.

**Comment by brasseld** [comment]
Clone by https://github.com/gravitee-io/issues/issues/1529
