### ISSUE TITLE
[question] Read/Write permissions for Gateway

### ISSUE THREAD

**Issue by DaspawnW** [gravitee-io/issues#1211]
We have configured Gateway and Management API to use a MongoDB ReplicaSet.

My question is, which read/write permissions does the Gateway need to connect to the MongoDB.
We are trying to deploy the Gateway in such a secure way, that not unauthorised users are possible to manipulate or delete data form MongoDB.

Is there some documentation for it?

Thank you in advance!

**Comment by brasseld** [comment]
Hi @DaspawnW 

Gateway is requiring a read access for the following collections:
- apis
- keys
- subscriptions
- plans

Gateway is requiring a read/write access for the following collections:
- events
- ratelimit (if you're applying ratelimit / quota rules).

**Comment by DaspawnW** [comment]
Hi @brasseld,

thank you very much :-)

**Comment by brasseld** [comment]
I will update documentation accordingly.

**Comment by brasseld** [comment]
I have added a new `Security` section in the documentation:
https://docs.gravitee.io/apim_installguide_repositories_mongodb.html#security
