### ISSUE TITLE
[portal] Management of second level with folder in the document menu

### ISSUE THREAD

**Issue by GGui** [gravitee-io/issues#1224]
The pages can be gathered by group. The groups are created in the title of the page.
The characters '::' in the title are used to define the group name and the page title. the first part is the group name and the second one is the page title.

Ex: API Management:: My page
Api Management is the group name and My page is the page title.

**Comment by NicolasGeraud** [comment]
Hi @GGui ,

sorry but i'm disagree with your solution. We need something that allows users to add any level of documentation and that don't rely on the page name.

Perhaps we also need to group pages in categories.

**Comment by GGui** [comment]
Hi @NicolasGeraud 

How i can move forward on this topic?
Are you ok if i implement a categorize for each page?

**Comment by NicolasGeraud** [comment]
Hi @GGui,
I think we have different needs mixed in this issue.

## Category
We need a category to generate a menu like this
```
Category 1
   page 1
   page 2
Category 2
   page 3
   page 4
```
This menu can also be rendered by columns in the footer of the homepage (for portal pages).

## Sub pages
I don't know if a parent page must be a real page or just an entry in the menu. I mean, does the parent page should have content?

### Solution 1
```
Category 1
   Technical Doc (parent page without content)
      readmeAsMarkdown
      descriptorAsSwagger
```
the `Technical Doc` is just a group of pages with a title. Perhaps it could be the same concept than category. It's like create a tree folder where you put pages inside.

### Solution 2
```
Category 1
   Technical Doc (parent page with markdown content)
      detailedDocAsMarkdown
```
The `Technical Doc` is a real page (markdown, swagger or raml) with subpages.


Do you prefer solution 1 or solution 2 ?

**Comment by GGui** [comment]
I prefer the solution 1.
With this solution, we will be able to reduce the menu with an accordion.

How do you want to display the menu in the footer with the "folder" mode?
Currently when you are a lot of item in the menu, the footer have a large height.
