### ISSUE TITLE
[question] Does gravitee support clustering and Gateways Load Balancing

### ISSUE THREAD

**Issue by sofGitAdmin** [gravitee-io/issues#1227]
This is a question:
Does Gravitee support Gateways Clustering , if so does the feature 'Load Balancing' apply for Gateways or API Endpoints .

### Your Environment
In my current environement ,we use clusters for gateways and vip ( F5) to balance load between Gateways .

**Comment by sofGitAdmin** [comment]
Thx @brasseld for the clarification about Load Balancer.
for the other question : Does Gravitee support Gateways Clustering ??(what's your clarification)

**Comment by brasseld** [comment]
You can have as many gateway instances as you need. Each gateway does not know about other instances, there is no communication between each of them. Each gateway is independent and just need a connection to the underlying repository (mongodb by default) to mount platform environment and expose APIs.
You have to manage gateway load-balancing with a front LB (your F5).

**Comment by sofGitAdmin** [comment]
I understand ,but u do agree that  there is no clustering between Gateways ??

**Comment by brasseld** [comment]
As I told you there is no communication between instances so I agree that there is no clustering between gateway. Clustering is based on clustering capabilities of data storage (for example replica set for Mongo)
It allows us to deploy multiple gateway instances in different data centers.

So even if there is no clustering, you can still run multiple instances for the same environment in a very simple way. Am I clear enough ?

**Comment by sofGitAdmin** [comment]
Yes ,it's clear enough clustering is made by a shared repo (Mongodb).

Thx For your help and availability.

**Comment by brasseld** [comment]
No problem, you're welcome ;)
