### ISSUE TITLE
[portal] Health-check page filter option

### ISSUE THREAD

**Issue by BlackTurtle123** [gravitee-io/issues#1233]
Health-check page can become very filled with old endpoints.
### Expected Behavior
On the health-check page there should be 2 improvements/filters
-Filter/show/differate active endpoints from inactive endpoints.
-Show/add the consul service name instead of only task name since this is autogenerated and not a lot saying.

### Current Behavior
It currently shows many many tasks in the Health-check display after a week of deployments have happened.

### Context
We were trying to watch the Health-check status and follow how those health-check were linked to know how to read the data and the logs. When we tryed to see most endpoints, they didn't existed anymore and it was very hard to find the existing ones.

### Your Environment
* Version used: Latest version + snapshot JDBC
* Operating System and version: Centos7

**Comment by aelamrani** [comment]
Hi @BlackTurtle123 we introduced the possibility to see HC transitions since 1.17.0 (https://github.com/gravitee-io/issues/issues/1240).

So this issue seems not relevant anymore?

**Comment by brasseld** [comment]
Hi @BlackTurtle123 

Can you indicate us what is the status of this issue?

**Comment by BlackTurtle123** [comment]
Hello!
Unfortunately the company that wanted to use Gravitee decided to look for a more lightweight solution, and this I haven't been able to follow up anymore.

**Comment by brasseld** [comment]
Ok Perfect,
Thanks for your feedback.
