### ISSUE TITLE
Importing v3.0 openAPI yaml/json is not working while creating new API. 

### ISSUE THREAD

**Issue by Raghu290** [gravitee-io/issues#1246]
While importing v3.0 openapi yaml/json it is throwing the format error. while same is working with v2.0 swagger specification

### Expected Behavior
New API should be created while importing v3.0 version of definition too.

### Steps to Reproduce (for bugs)
https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/yaml/petstore.yaml
1.import the yaml file from above git repo and try to import while creating the API it will create fine.
2.While importing V3.0 version from below location it will throw bad descriptor
https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml

### Context
We have another v3.0 of json which is also failing. Not working for any v3.0

**Comment by brasseld** [comment]
Closed
