### ISSUE TITLE
Getting a dark blank screen (no login) on Management UI

### ISSUE THREAD

**Issue by entvikas** [gravitee-io/issues#1247]
Getting a dark blank screen (no login) on Management UI in latest build

After setting up the docker the web UI is not working need some clarity for the configuration (if its a config issue also please update the docker documentation that will help in quick setup )

### Steps to Reproduce (for bugs)

1. By Running the .sh provided on the web 
2. By setting up manually on local docker
3. go to management ui web
4. a dark balnk screen

### Your Environment

Docker
Mac
latest : build / demo build

**Comment by brasseld** [comment]
Hi @entvikas 

Do you run Gravitee with docker compose?  I suppose, since you are talking  the .sh launch script.
Can you share your version of docker/compose please.
Also, please share logs you get while running gravitee with docker compose.

Thanks ,

**Comment by entvikas** [comment]
[gravitee.log](https://github.com/gravitee-io/issues/files/2015515/gravitee.log)
curl -L http://bit.ly/graviteeio-apim | bash  
have used this to setup the demo 

also when I am trying to do it via docker hub then also its the same issue please guide me to setup the error free environment

**Comment by entvikas** [comment]
https://github.com/gravitee-io/gravitee-docker this is what I was using to setup the docker

**Comment by brasseld** [comment]
Please provide the complete logs when running compose up.

**Comment by phamjp** [comment]
I've tried from a clean slate.

```
$ curl -L https://raw.githubusercontent.com/gravitee-io/gravitee-docker/master/environments/demo/common.yml -o "common.yml"
$ curl -L https://raw.githubusercontent.com/gravitee-io/gravitee-docker/master/environments/demo/docker-compose-local.yml -o "docker-compose-local.yml"
$ docker-compose -f docker-compose-local.yml pull
```
The downloaded common.yml and docker-compose-local.yml files are: 
[docker-yml.zip](https://github.com/gravitee-io/issues/files/2021917/docker-yml.zip)

Here is the `docker-compose -f docker-compose-local.yml up` log file
[docker-compose-up.log](https://github.com/gravitee-io/issues/files/2021875/docker-compose-up.log).

When I connect to `http://localhost:8002`, I can see the following console log.
![2018-05-21_10-55-24](https://user-images.githubusercontent.com/14042545/40299336-3732dd54-5ce6-11e8-8ef3-0367eacafeac.png)

Here is the expanded console log
![2018-05-21_11-03-14](https://user-images.githubusercontent.com/14042545/40299499-b415ddb2-5ce6-11e8-9acb-b375c38a337b.png)

**Comment by brasseld** [comment]
Hello @phamjp and @entvikas 

Can you try to change the version of Mongodb, from 3.6 or latest to 3.4 and run again docker compose.

Thanks

**Comment by phamjp** [comment]
Hi @brasseld ,

Mongdb fails to start. Here is the log after modifying mongoldb to 3.4 in common.yml
[docker-compose-up.log](https://github.com/gravitee-io/issues/files/2029710/docker-compose-up.log)

**Comment by brasseld** [comment]
Yes, because you were using the same volume for Mongo 3.6 and 3.4 and there'nt fully compatible.

Please remove the volume for mongodb before restarting:
`docker volume rm demo_local_datamongo`

**Comment by phamjp** [comment]
Yup, that worked out.

Also I increased docker memory limits to 4 Gb / container if not elastic search crashes with error 137. By default, docker on mac memory limit per container is at 2gb.

**Comment by brasseld** [comment]
Ok, so it works well with MongoDB 3.4

You can confirm ?

May I ask you to update the documentation to include the point about memory limit for docker on mac ?

**Comment by yinghe1** [comment]
I ran into the same issue when using the latest gravite-gateway, gravitee-management-rest-ui and gravitee-management-webui code. The fix is to use the latest gravitee-repository-mongodb for the plugin for the gateway and rest-ui. it is due to changeset in https://github.com/gravitee-io/issues/issues/1197

**Comment by yinghe1** [comment]
hi, David,

you are right if people are using the full distribution download. i am using git original master and have a different folder for plugins. Just want to point out what might cause it.

**Comment by yinghe1** [comment]
no. i don't build all plugin myself. earlier i used some old ones.

**Comment by brasseld** [comment]
Ok, that's what I'm doing also ;)

**Comment by brasseld** [comment]
@entvikas @phamjp 

For your information, we have rollback the MongoDB container to 3.4:
https://github.com/gravitee-io/gravitee-docker/commit/33daa47b1752bd3e530d540fffa47adbbd7877a5

Please tell us if it's fixing your issue.

Regards,

**Comment by saulgill** [comment]
@entvikas @brasseld I am not sure if my issue is related to this but I am getting a similar blank blue screen with only the message.

> **Management API unreachable or error occurs, please check logs**

In the console it says:

`Possibly unhandled rejection: {"data":null,"status":-1,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"http://localhost:8005/management/portal","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":""}`

All of the relevant containers are started, following the guidelines here using docker-compose:
[https://docs.gravitee.io/apim_installguide_docker.html#gravitee-quickstart](url)

I do get some errors through the docker logs of the management ui but no errors on the other containers

`<BROWSER_CLIENT_IP> - - [10/Sep/2018:15:49:06 +0000] "GET /favicon.ico HTTP/1.1" 200 4286 "http://<GRAVITEE_SERVER_IP>:8002/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36" "-"
2018/09/10 15:49:15 [error] 10#10: *26 open() "/var/www/html/swagger-ui.css.map" failed (2: No such file or directory), client: <BROWSER_CLIENT_IP>, server: _, request: "GET /swagger-ui.css.map HTTP/1.1", host: "<GRAVITEE_SERVER_IP>:8002"`

Because of this the UI is not accessible at all. Has anyone else experience this?

**Comment by brasseld** [comment]
Please try to remove cookies for localhost domain and refresh the ui.

**Comment by mknair75** [comment]
Can you please suggest the changes to be done for docker-compose to access the UI . I am using a VM and experiencing the same issue - blank scree with message "Management API unreachable or error occurs, please check logs"

**Comment by brasseld** [comment]
It means that the management-api can not be reach by the UI.

Did you check the docker-compose logs ?

**Comment by KondratenkoAndrey** [comment]
> @brasseld Thanks for your reply. I have solved the issue. The browser I was using to access the UI was not on the same machine as the docker-compose deployment. The deployment is on a VM. So it seemed that when the UI attempts to contact the management API, it is using localhost and therefore cannot access the management API.
> 
> After altering the docker-compose file to not use localhost but instead use the IP for my VM, the issue was resolved.
> 
> Thanks

Hello! I have the same problem! I need to browse UI from host machine...
How exactly did you change the docker-compose file?

**Comment by brasseld** [comment]
Hello,

Which docker-compose file are your running ?

**Comment by ehinolakingsley** [comment]
> @brasseld Thanks for your reply. I have solved the issue. The browser I was using to access the UI was not on the same machine as the docker-compose deployment. The deployment is on a VM. So it seemed that when the UI attempts to contact the management API, it is using localhost and therefore cannot access the management API.
> 
> After altering the docker-compose file to not use localhost but instead use the IP for my VM, the issue was resolved.
> 
> Thanks

Had the same issue. After reading this comment i changed the management -ui /constant.json base url to the ip of the server hosting the other server application and it worked. Thanks

**Comment by gummiost** [comment]
> 
> 
> @brasseld Thanks for your reply. I have solved the issue. The browser I was using to access the UI was not on the same machine as the docker-compose deployment. The deployment is on a VM. So it seemed that when the UI attempts to contact the management API, it is using localhost and therefore cannot access the management API.
> 
> After altering the docker-compose file to not use localhost but instead use the IP for my VM, the issue was resolved.
> 
> Thanks

**Wow, this comment saved my day.** 

I have used 10 hours trying to solve this error:
https://github.com/gravitee-io/issues/issues/3901

I just changed the default docker-compose.yml:

https://docs.gravitee.io/apim/3.x/apim_installguide_docker_compose.html

These two environment variables should not use "localhost" they must use the IP of your host machine.

```
MGMT_API_URL=http://INSERT_IP_HERE:8083/management/organizations/DEFAULT/environments/DEFAULT/
PORTAL_API_URL=http://INSERT_IP_HERE:8083/portal/environments/DEFAULT
```

Then run:

```
docker-compose up -d
docker-compose restart
```

Now everything works :-)
