### ISSUE TITLE
[management-api] No authentication provider found for type: gravitee

### ISSUE THREAD

**Issue by M3lkior** [gravitee-io/issues#125]
When i try to run the gravitee-management-api-standalone, i have this error : 

No authentication provider found for type: gravitee

User authentication is not possible if gravitee-management-api have no IDP plugin deployed but for me, the ERROR is not  detailled enough 

I will go to 
- interrupt the management-api when required plugins are not found
- and/or enhance the ERROR message adding the missing plugin or an orientation to the resolution

**Comment by brasseld** [comment]
Should be closed by gravitee-io/issues#194

**Comment by brasseld** [comment]
Closed by a previous version.
