### ISSUE TITLE
[gateway] Route to API by API Key in the Gateway

### ISSUE THREAD

**Issue by briankrug** [gravitee-io/issues#1252]
Routing of requests to the correct API is currently done by context path. I'd like the flexibility to choose the API based on the API Key that is used. The difficulty is that choosing the API makes most sense before constructing the chain of policies to process the request. (A single aggregate API with dynamic routing and all the policies on the Plan would not suffice because 1. metrics would not break down by real API 2. the Portal would not display each real API). 

### Expected Behavior
If configured as such, an API would be chosen not just by context path but also by the provided API Key during resolution.

### Possible Solution
I've proposed updating DefaultReactorHandlerResolver to accomplish this, but it has the unfortunate effect of mixing API Key policy functionality with the gateway-wide handler resolution

### Context
Without this, when portal user defines an API they have to select a context path that is unique across the whole gateway even if they don't have access to view/edit some other APIs.

**Comment by brasseld** [comment]
Sorry @briankrug but the api-key is also used to validate that you're allowed to access the API (define according to the context-path), so I'm not sure that api-key should be part of the API resolution.

Can you tell me what is a 'real' use-case for such scenario ? Also what if the plan is based on oauth2 or a JWT token ?

**Comment by brasseld** [comment]
In other words, you want multiple management-api / portal, but APIs are distributed on the same API Gateway instances, right ?

**Comment by brasseld** [comment]
Hello @briankrug I'm just thinking about this issue.

I think the best would be to provide a way to configure the gateway router and provide multiple implementations.

Default implementation is the current one, based on the context-path
An other implementation would be to answer to https://github.com/gravitee-io/issues/issues/503
And then, the latest would be to make routing based on api-key

But, as you mentioned, it means that `it has the unfortunate effect of mixing API Key policy functionality`.

**Comment by brasseld** [comment]
Hi @briankrug 

As you may notice, I'm currently looking and working on https://github.com/gravitee-io/issues/issues/503#issuecomment-378639399

I keep in mind that you were looking to route HTTP requests to API by API-Key mainly to respond to:
> multi-tenant scenario where different organizations / users are using the same gateway

But, in that case, and IMHO, routing by virtual-host and context-path should be sufficient. Each organizations / users must have dedicated virtual-host(s) to ensure that the gateway will not mix calls between each of them.

This way, we do not have to rework the algorithm and we can avoid mixin between api resolution and api-key policy.

WDYT ?

**Comment by briankrug** [comment]
We are realizing that we are probably less like to end up using multi-tenant Gateways. What's of greater concern to us is the performance of the API routing. I'd love to see that optimized so that the Gateway can support hundreds of APIs

**Comment by brasseld** [comment]
So I'm sure you will get benefits from virtual-hosting support.

Now about performances, we already have users and customers who are already handling hundreds of APIs from their gateways. But I know you have created an other issue for this point.

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/issues/issues/1594
