### ISSUE TITLE
[documentation] List all plugins

### ISSUE THREAD

**Issue by BlackTurtle123** [gravitee-io/issues#1256]
List all the plug-ins inside the documentation.
### Expected Behavior
List all the existing plug-ins inside the documentation.
https://docs.gravitee.io/apim_devguide_plugins.html

### Current Behavior
Plug-ins hard to find from documentation point

### Context
The company was looking for documentation about the plug-ins but couldn't find or link any examples with it.
https://docs.gravitee.io/apim_devguide_plugins.html

**Comment by NicolasGeraud** [comment]
moved to gravitee-io/gravitee-docs#65
