### ISSUE TITLE
[management-api] Add a developer profile to run management-api from command-line

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#126]
As a Gravitee.io developer, it would be appreciated to make easier to start to develop without having to set some system properties or configuration.

I need something like:
```
mvn exec:java
```

**Comment by M3lkior** [comment]
Missing one command line after `git clone` to checkout the correct branch :)

**Comment by aelamrani** [comment]
Hi @M3lkior,

I'm not sure to understand, but when the linked PR will be merged, the command will be available from master...

**Comment by M3lkior** [comment]
Exactly. it's just a note ;)
