### ISSUE TITLE
[management-ui] the old config file can not use in new version

### ISSUE THREAD

**Issue by yang-dw** [gravitee-io/issues#1268]
When I build the new version , the ui throw an exception and I can't do anything else, for example, login or Post /management/portal . everything stay at the page.

![qq 20180528161700](https://user-images.githubusercontent.com/28995740/40613401-f2209f78-62b0-11e8-8e55-a60f70bfd5e9.jpg)

![qq 20180528161351](https://user-images.githubusercontent.com/28995740/40613423-0b077dae-62b1-11e8-9915-3139da717abe.jpg)
![qq 20180528161409](https://user-images.githubusercontent.com/28995740/40613431-119a0a88-62b1-11e8-8824-f235af26f9b9.jpg)

![qq 20180528161507](https://user-images.githubusercontent.com/28995740/40613785-8d2deccc-62b2-11e8-814c-7b16f38a8d41.jpg)

**Comment by NicolasGeraud** [comment]
Hi,

yes, we have slightly changed the format of the constants.json file since release 1.16

Look at the migration guide : https://docs.gravitee.io/apim_installguide_migration.html#web_ui

**Comment by yang-dw** [comment]
oh , Yeah , My careless . Thanks a lot!
