### ISSUE TITLE
[management] add a warning if the jwt secret is the default one.

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#1269]

**Comment by 0xC4N1** [comment]
Thank you for providing this warning. Is there any documentation about generating and using my own JWT secret? Is HMAC, which is used for the default JWT secret, the only supported algorithm for JWT secrets? Do I need to provide a key? It doesn't seem to be mentioned in the [installation guide](https://docs.gravitee.io/am/2.x/am_installguide_configuration.html).
