### ISSUE TITLE
[gateway] Cors Policies Error

### ISSUE THREAD

**Issue by yang-dw** [gravitee-io/issues#1277]
When I update the version from 1.14.2 to 1.16.2 , The Cors Policies has changed.
When My Endpoints Response [ Access-Control-Allow-Origin = *  ] , The newest version throw some errors. 

declare 
web program url is : http://dw.banggood.cn/
gateway url is : http://172.16.13.230:8000

error below:
Failed to load http://172.16.13.230:8000/demo: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://dw.banggood.cn' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

my endpoints program config:
![qq 20180602215602](https://user-images.githubusercontent.com/28995740/40873124-fe21ea68-668c-11e8-8433-1c5cdb6ecc34.jpg)

my gateway  config:
![qq 20180602215601](https://user-images.githubusercontent.com/28995740/40877233-d7bec6f2-66af-11e8-8d96-0cd4753e2271.jpg)

my web program console:
![qq 20180602173201](https://user-images.githubusercontent.com/28995740/40873141-8210954a-668d-11e8-985e-d1dadbcfe38d.jpg)

my web program network:
![qq 20180602172801](https://user-images.githubusercontent.com/28995740/40873148-92c3cd1c-668d-11e8-860e-214af641a8d8.jpg)

**Comment by yang-dw** [comment]
the old version is ok ,but the new version is not  ok. and there is't  best config to compatible  them.

**Comment by yang-dw** [comment]
My Test Program:

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script type="text/javascript" src="jquery-3.3.1.min.js" ></script>
    <script type="application/javascript">

        function setCookie(c_name,value,expiredays)
        {
            var exdate=new Date()
            exdate.setDate(exdate.getDate()+expiredays)
            document.cookie=c_name+ "=" +encodeURIComponent(value)+
                ((expiredays==null) ? "" : ";expires="+exdate.toGMTString())
        }
        var setCode=false;
        if(location.search&&location.search.length>2){
           var arr= location.search.substr(1).split("&");
           for(var i=0;i<arr.length;i++){
               var arr2= arr[i].split("=");
               if(arr2[0]=="code"){
                   setCode=true;
                   setCookie("Authorization",'"Bearer '+arr2[1]+'"');
               }
           }
        }
        if(!setCode) {
            setCookie("Authorization", '"Bearer AT-1076902-eiAH1KdAZJP6-4vpx4-ZInU0OcCppIqZ"');
        }  
        $(function(){
        	$("#btnTest1").click(function(){
        		$.ajax({
			        url : 'http://172.16.13.230:8000/demo',
			        headers: {
             		'X-Gravitee-Api-Key':"8b108870-ae67-474c-9055-0226a9d0740d"
         			},
			        dataType: 'json',
			        type : 'GET',
			        xhrFields: {
			            withCredentials: true
			        },
			        crossDomain: true,
			        contentType: "application/json",
			        success:function(res){
			          console.log('success'); 
			        },
			        error:function(){
			          console.error('my error')	;
			        }
			      });
        		
        	});
        });
    </script>
</head>
<body>
测试按钮 <button id="btnTest1">测试</button>

</body>
</html>

**Comment by yang-dw** [comment]
$(function(){
        	$("#btnTest1").click(function(){
        		$.ajax({
			        url : 'http://172.16.13.230:8000/demo',
			        headers: {
             		'X-Gravitee-Api-Key':"8b108870-ae67-474c-9055-0226a9d0740d"
         			},
			        dataType: 'json',
			        type : 'GET',
			        xhrFields: {
			            withCredentials: true
			        },
			        crossDomain: true,
			        contentType: "application/json",
			        success:function(res){
			          console.log('success'); 
			        },
			        error:function(){
			          console.error('my error')	;
			        }
			      });
        		
        	});
        });


测试按钮 <button id="btnTest1">测试</button>

**Comment by yang-dw** [comment]
If  I   config the gateway  as  【CORS -> Access-Control-Allow-Origin -> *】  and remove endpoints program  config of 【Access-Control-Allow-Origin=*】 , Everything will be fine!

but， Could we be compatible with the cross domain setup of Endpoints  Programs?

**Comment by yang-dw** [comment]
My  web program

[web.zip](https://github.com/gravitee-io/issues/files/2065740/web.zip)

**Comment by brasseld** [comment]
Sorry @yang-dw but I did not get on this issue.

Cors behavior is handled by the class `CorsHandler` in the gateway, so, IMHO, there is absolutely no reason to make any change to the `ApiReactorHandler`: https://github.com/gravitee-io/gravitee-gateway/pull/263/files

Our concern with CORS is to let the user being able to fully configure CORS support at the gateway level instead of doing it per backend services.

If you want to let this responsibility to your backend services, I would advice you to disable the CORs feature from Gravitee

**Comment by aelamrani** [comment]
@yang-dw is it OK for you? Can we close this issue as you can configure the CORS on the endpoint..?

**Comment by yang-dw** [comment]
ok

**Comment by yang-dw** [comment]
I find a best gateway setting to compatible with client cors rule , It is to use Transform Headers to remove  origin http header !    

Thanks for all !

**Comment by brasseld** [comment]
Sorry @yang-dw but I did not get you...

Why would you want to remove the Origin HTTP header ?

**Comment by yang-dw** [comment]
Yes, To use the  Policies of Transform Headers , Solved my cross domain problem. 

Thanks !
