### ISSUE TITLE
[reporter] [kafka] Upgrade Kafka reporter to Vertx Kafka

### ISSUE THREAD

**Issue by fmercier-almerys** [gravitee-io/issues#1279]
Current Kafka reporter plugin relies on Akka stream and does not provide all features needed.

Expectation are :  
* Switch to vertx Kafka extension
* Full configuration included in gravitee.yml
* Allow all configuration properties available for officiel kafka client 
* Filter data sended to kafka broker (Log, Metric...)
* Possibility to enable or disable kafka reporting

**Comment by brasseld** [comment]
Commit https://github.com/gravitee-io/gravitee-reporter-kafka/commit/68e137fa988c455ea5df119740b4c752dbae4b22 has been merged: https://github.com/gravitee-io/gravitee-reporter-kafka
