### ISSUE TITLE
docker - error in launch.sh

### ISSUE THREAD

**Issue by lusoalex** [gravitee-io/issues#128]
Hello,

On branch feat/use_envvar_in_yml there's two problems : 

1°) .yml is missing in declare dc_exec="docker-compose -f docker-compose-local up"
Should be : declare dc_exec="docker-compose -f docker-compose-local.yml up"

2°) curl retrieves master yml files, not feat one.

Regards,
Alexandre.

**Comment by NicolasGeraud** [comment]
First point is fixed.

Second "bug" occurred because we have changed the way gravitee configuration file could be configured.

see gravitee-io/issues#93

We should synchronize gravitee.io release with docker-compose upgrades. You can't use the launch.sh until this PR was accepted.
