### ISSUE TITLE
[SOLVED] Unable to access Gravitee

### ISSUE THREAD

**Issue by syedhassan** [gravitee-io/issues#1292]
I have setup my gateway, management-api and management-ui running on localhost:8082, localhost:8083 and localhost:8000 respectively on a Ubuntu VM.

There is a nginx server in front the setup for SSL traffic and all gravitee setups running behind it. 

My nginx config is 

```
        location ~ ^/portal(.*) {
            root /home/graviteeio-full-1.16.3/graviteeio-management-ui-1.16.3;
            index  index.html;
            try_files $1 /index.html;
        }

        location ~ ^/management(.*) {
            proxy_pass  http://127.0.0.1:8083/management$1$is_args$args;
            proxy_redirect off;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location ~ ^/oauth2(.*) {
            proxy_pass  http://127.0.0.1:8080/oauth/$1$is_args$args;
            proxy_redirect off;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location ~ ^/(.*) {
            proxy_pass  http://127.0.0.1:8082/$1$is_args$args;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location / {
            proxy_pass  http://127.0.0.1:8000/$1$is_args$args;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
```

but when I go to my server at api.example.com I can't access anything and keep getting 
```No context-path matches the request URI.```

404 Not Found

What am I missing?

### Context
I am trying to access gravitee directly from a Chrome browser (67.0.3396.79 (Official Build) (64-bit)) from api.example.com and want to setup APIs, create user accounts and yada yada.

### Your Environment

* Version used: graviteeio-full-1.16.3
* Browser Name and version: Chrome
* Operating System and version: Ubuntu 16.04.4 x64

**Comment by brasseld** [comment]
I suppose this is because you don't have Apis deployed on the Gateway?

**Comment by brasseld** [comment]
Oups....

**Comment by syedhassan** [comment]
@brasseld I am trying to first access the gateway, this is the first time I am deploying a gateway and unclear with instructions

**Comment by syedhassan** [comment]
never mind, I was able to solve my issue and it is as follows (for someone that was struggling like me)

My nginx configuration finally was 

```server {
    listen 443 ssl default_server;

        location ~ ^/management(.*) {
            proxy_pass  http://127.0.0.1:8083/management$1$is_args$args;
            proxy_redirect off;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
        location / {
            proxy_pass  http://127.0.0.1:8000;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_redirect off;
        }
    
    ssl_certificate my_certificate.pem;
    ssl_certificate_key private_key.pem;
}```

**Comment by ehinolakingsley** [comment]
> never mind, I was able to solve my issue and it is as follows (for someone that was struggling like me)
> 
> My nginx configuration finally was
> 
> ```
> server {
>     listen 443 ssl default_server;
> 
>         location ~ ^/management(.*) {
>             proxy_pass  http://127.0.0.1:8083/management$1$is_args$args;
>             proxy_redirect off;
>             proxy_set_header Host $http_host;
>             proxy_set_header X-Real-IP $remote_addr;
>             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         }
>         
>         location / {
>             proxy_pass  http://127.0.0.1:8000;
>             proxy_set_header X-Forwarded-For $remote_addr;
>             proxy_redirect off;
>         }
>     
>     ssl_certificate my_certificate.pem;
>     ssl_certificate_key private_key.pem;
> }
> ```

Although you missed the part of updating the UI application constant.json baseUrl with the new domain name. i.e 
{
"baseUrl":"https://default_server/management/"
}
