### ISSUE TITLE
Getting  500 when trying to authenticate 

### ISSUE THREAD

**Issue by sofGitAdmin** [gravitee-io/issues#1299]
fter deploying gravitee using the docker-compose example, when accessing the portal, I get this error from my browser developer console

Request URL:http://xxxxxx:8083/management/user/
Request Method:GET
Status Code:500 Internal Server Error
Remote Address:
Referrer Policy:no-referrer-when-downgrade

and the response payload was

{
"message" : "Cannot pass null or empty values to constructor",
"http_status" : 500
}

Expected Behavior
No 500 error.

Current Behavior
500 error

Possible Solution
Probably the portal should be GETing the /users/ resource?
normally this kind of erro is generated when credentials in DB are empty ??

Steps to Reproduce (for bugs)
install service using docker-compose.yml provided at gravitee site
access the portal
Context
Trialing the solution

Your Environment
Version used: official gravitee docker image:latest
Browser Name and version: chrome Version 62.0.3202.75
Operating System and version: docker latest version running on Ubuntu

**Comment by sofGitAdmin** [comment]
This is tha API Management  gravitee.yml : 



############################################################################################################
################################ Gravitee.IO Management API - Configuration ################################
############################################################################################################

############################################################################################################
# This file is the general configuration of Gravitee.IO Management API:
# - Properties (and respective default values) in comment are provided for information.
# - You can reference other property by using ${property.name} syntax
# - gravitee.home property is automatically set-up by launcher and refers to the installation path. Do not override it !
#
# Please have a look to http://docs.gravitee.io/ for more options and fine-grained granularity
############################################################################################################

# HTTP Server
jetty:
 # IP/hostname to bind to. Default is 0.0.0.0
  host: 0.0.0.0
  port: 8083
  idleTimeout: 30000
  acceptors: -1
  selectors: -1
  pool:
    minThreads: 10
    maxThreads: 200
    idleTimeout: 60000
    queueSize: 6000
  jmx: false
  statistics: false
  accesslog:
    enabled: true
    path: ${gravitee.home}/logs/gravitee_accesslog_yyyy_mm_dd.log

http:
  cors:
    # Allows to configure the header Access-Control-Allow-Origin (default value: *)
    # '*' is a valid value but is considered as a security risk as it will be opened to cross origin requests from anywhere.
    #allow-origin: http://developer.mycompany.com
    # Allows to define how long the result of the preflight request should be cached for (default value; 1728000 [20 days])
    #max-age: 864000
    # Which methods to allow (default value: OPTIONS, GET, POST, PUT, DELETE)
    #allow-methods: 'OPTIONS, GET, POST, PUT, DELETE'
    # Which headers to allow (default values: Cache-Control, Pragma, Origin, Authorization, Content-Type, X-Requested-With, If-Match)
    #allow-headers: 'X-Requested-With'

# Plugins repository
plugins:
  path:
    - ${gravitee.home}/plugins
   # - ${gravitee.home}/my-custom-plugins
# If a external is already installed (but with a different version), management node does not start anymore
#  failOnDuplicate: true

# Management repository is used to store global configuration such as APIs, applications, apikeys, ...
# This is the default configuration using MongoDB (single server)
# For more information about MongoDB configuration, please have a look to:
# - http://api.mongodb.org/java/current/com/mongodb/MongoClientOptions.html
management:
  type: mongodb
  mongodb:
    dbname: ${ds.mongodb.dbname}
    host: ${ds.mongodb.host}
    port: ${ds.mongodb.port}
#    username:
#    password:
#    connectionsPerHost: 0
#    connectTimeout: 500
#    maxWaitTime: 120000
#    socketTimeout: 500
#    socketKeepAlive: false
#    maxConnectionLifeTime: 0
#    maxConnectionIdleTime: 0
#    serverSelectionTimeout: 0
#    description: gravitee.io
#    heartbeatFrequency: 10000
#    minHeartbeatFrequency: 500
#    heartbeatConnectTimeout: 1000
#    heartbeatSocketTimeout: 20000
#    localThreshold: 15
#    minConnectionsPerHost: 0
#    sslEnabled: false
#    threadsAllowedToBlockForConnectionMultiplier: 5
#    cursorFinalizerEnabled: true

# Management repository: single MongoDB using URI
# For more information about MongoDB configuration using URI, please have a look to:
# - http://api.mongodb.org/java/current/com/mongodb/MongoClientURI.html
#management:
#  type: mongodb
#  mongodb:
#    uri: mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]

# Management repository: clustered MongoDB
#management:
#  type: mongodb
#  mongodb:
#    servers:
#      - host: mongo1
#        port: 27017
#      - host: mongo2
#        port: 27017
#    dbname: ${ds.mongodb.dbname}
#    connectTimeout: 500
#    socketTimeout: 250

services:
  core:
    http:
      enabled: true
      port: 18083
      host: localhost
      authentication:
        # authentication type to be used for the core services
        # - none : to disable authentication
        # - basic : to use basic authentication
        # default is "basic"
        type: basic
        users:
          admin: adminadmin

# Analytics repository is used to store all reporting, metrics, healthchecks stored by gateway instances
# This is the default configuration using Elasticearch
analytics:
  type: elasticsearch
  elasticsearch:
    endpoints:
      - http://${ds.elastic.host}:${ds.elastic.port}
#    index: gravitee
#    cluster: elasticsearch
#    settings:
#      number_of_shards: 5
#      number_of_replicas: 1

# Authentication and identity sources
# Users can have following roles (authorities):
#  USER: Can access portal and be a member of an API
#  API_PUBLISHER: Can create and manage APIs
#  API_CONSUMER: Can create and manage Applications
#  ADMIN: Can manage global system
security:
  type: basic
  providers:  # authentication providers
    - type: memory
      # password encoding/hashing algorithm. One of:
      # - bcrypt : passwords are hashed with bcrypt
      # - none : passwords are not hashed/encrypted
      # default value is bcrypt
      password-encoding-algo: bcrypt
      users:
        - user:
          username: user
          # Passwords are encoded using BCrypt
          Password value: password
          password: $2a$10$9kjw/SH9gucCId3Lnt6EmuFreUAcXSZgpvAYuW2ISv7hSOhHRH1AO
          roles: MANAGEMENT:USER, PORTAL:USER
        - user:
          username: admin
          Password value: admin
          password: $2a$10$Ihk05VSds5rUSgMdsMVi9OKMIx2yUvMz7y9VP3rJmQeizZLrhLMyq
          roles: ADMIN
        - user:
          username: api1
          Password value: api1
          password: $2a$10$iXdXO4wAYdhx2LOwijsp7.PsoAZQ05zEdHxbriIYCbtyo.y32LTji
          # You can declare multiple roles using comma separator
          roles: MANAGEMENT:API_PUBLISHER, PORTAL:API_PUBLISHER
        - user:
          username: application1
          Password value: application1
          password: $2a$10$2gtKPYRB9zaVaPcn5RBx/.3T.7SeZoDGs9GKqbo9G64fKyXFR1He.
          roles: MANAGEMENT:USER, PORTAL:USER
    # Enable authentication using internal repository
#    - type: gravitee
#    - type: ldap
      # This is default LDAP configuration for ApacheDS
#      context-source-username: "uid=admin,ou=system"
#      context-source-password: "secret"
#      context-source-url: "ldap://localhost:10389/c=io,o=gravitee"
      context-source-base: "c=io,o=gravitee" # the context source base
      # The 'user-dn-patterns' value is a specific pattern used to build the user's DN, for example "uid={0},ou=people". The key "{0}" must be present and will be substituted with the username.
      user-dn-patterns: "uid={0},ou=people"
      # Search base for user searches. Defaults to "". Only used with user-search-filter.
      # It should be relative to the Base DN. If the whole DN is o=user accounts,c=io,o=gravitee then the user-search-base should be like this:
      user-search-base: "o=user accounts"
      # The LDAP filter used to search for users (optional). For example "(uid={0})". The substituted parameter is the user's login name.
#      user-search-filter: "mail={0}"
      # The objectclass used when searching for user (optional). Default is "person".
#      user-search-objectclass: "person"
      # The search base for group membership searches. Defaults to "".
      # It should be relative to the Base DN. If the whole DN is o=authorization groups,c=io,o=gravitee then the group-search-base should be like this:
      group-search-base: "o=authorization groups"
      # The LDAP filter to search for groups. Defaults to "(uniqueMember={0})". The substituted parameter is the DN of the user.
#      group-search-filter: "member={0}"
      # Specifies the attribute name which contains the role name. Default is "cn".
#      group-role-attribute: "cn"
      #   Use role-mapper to map LDAP role with internal Gravitee role (syntax { "user_ldap_role" : "user_new_added_ldap_role"})
      role-mapper: {
        GRAVITEE-CONSUMERS: API_CONSUMER,
        GRAVITEE-PUBLISHERS: API_PUBLISHER,
        GRAVITEE-ADMINS: ADMIN,
        GRAVITEE-USERS: USER,
      }
#    - type: google # Allow to authenticate to portal using a Google Plus account
#      clientId: xxxx-xxx-xxx-xxx
#      clientSecret: xxxx-xxx-xxx-xxxx
#    - type: github # Allow to authenticate to portal using a GitHub account
#      clientId: xxxx-xxx-xxx-xxx
#      clientSecret: xxxx-xxx-xxx-xxxx
#    - type: oauth2
#      clientId: xxxx-xxx-xxx-xxx
#      clientSecret: xxxx-xxx-xxx-xxx
#      tokenEndpoint: https://oauth2_authorization_server/token
#      userInfoEndpoint: https://oauth2_authorization_server/userinfo
#      accessTokenProperty: access_token
#      authorizationHeader: "Bearer %s"
#      mapping:
#        id: sub
#        email: email
#        lastname: family_name
#        firstname: given_name
#        picture: picture
      #   by default created user will have default role for MANAGEMENT and PORTAL
      #   you can override this by assigning user to groups, on user creation, if its user info content match expression
#     groups:
#       - mapping:
#           condition: "{#jsonPath(#profile, '$.identity_provider_id') == 'idp_5' && #jsonPath(#profile, '$.job_id') != 'API_BREAKER'}"
#           values: [Example group,soft user]
#       - mapping:
#           condition: "{#jsonPath(#profile, '$.job_id') != 'API_BREAKER'}"
#           values: ["Api consumer"]

# SMTP configuration used to send email
email:
  enabled: true
  host: smtp.gmail.com
  port: 587
  from: user@gmail.com
  username: azddine.rami@gmail.com
  password: aqwzsx12356
  properties:
    auth: true
    starttls.enable: true
    ssl.trust: smtp.gmail.com


#  properties:
#    auth: true
#    starttls.enable: true
#    ssl.trust: smtp.gmail.com
# Mail templates
templates:
  path: ${gravitee.home}/templates

# Referenced properties
ds:
  mongodb:
    dbname: gravitee
    host: ${GRAVITEEIO_MONGODB_HOST:localhost}
    port: ${GRAVITEEIO_MONGODB_PORT:27017}
  elastic:
    host: ${GRAVITEEIO_ELASTIC_HOST:localhost}
    port: ${GRAVITEEIO_ELASTIC_PORT:9200}

jwt:
  secret: myJWT4Gr4v1t33_S3cr3t
  # Allows to define the end of validity of the token in seconds (default 604800 = a week)
  #expire-after: 604800
  # Allows to define the end of validity of the token in seconds for email registration (default 86400 = a day)
  #email-registration-expire-after: 86400
  # Allows to define issuer (default gravitee-management-auth)
  #issuer: gravitee-management-auth
  # Allows to define cookie context path (default /)
  #cookie-path: /
  # Allows to define cookie domain (default "")
  #cookie-domain: .gravitee.io
  # Allows to define if cookie secure only (default false)
  #cookie-secure: true

swagger:
  # Default scheme used when creating an API from a Swagger descriptor if there is no scheme specified.
  scheme: https

user:
  login:
    # Create a default application when user connects to the portal for the very first time (default true)
    defaultApplication: true
  creation:
    # Allows to register new users from portal (default false)
    enabled: true
    token:
      #expire-after: 86400
  reference:
      # Secret key used to generate reference of a user which is unique (default: s3cR3t4grAv1t33.1Ous3D4R3f3r3nc3)
      # Must contains 32 chars (256 bits)
      #secret:

# The portal URL used in emails
portalURL: http://portal-url.net

# Allows to create support ticket (default value: false)
#support:
  #enabled: true

# Allows to rate an API (default value: false)
rating:
  enabled: true

**Comment by sofGitAdmin** [comment]
this my api management gravitee.yml content : 
[gravitee.txt](https://github.com/gravitee-io/issues/files/2090673/gravitee.txt)

**Comment by Sebbl22** [comment]
Same problem here with Docker on Windows and the official docker-compose files

**Comment by NicolasGeraud** [comment]
hi,
please provide the full gravitee.log file

**Comment by Sebbl22** [comment]
Hi,
I attached the logfile and gravitee.yml. Nothing was changed in the yml.

[gravitee_accesslog_2018_07_04.log](https://github.com/gravitee-io/issues/files/2164119/gravitee_accesslog_2018_07_04.log)
[gravitee.log](https://github.com/gravitee-io/issues/files/2164120/gravitee.log)

**Comment by aelamrani** [comment]
> jvm[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/25.162-b12] started in 13428 ms.
There is a known issue: https://github.com/gravitee-io/issues/issues/1134

And here a link related to this issue: https://golb.hplar.ch/2017/10/JCE-policy-changes-in-Java-SE-8u151-and-8u152.html

**Comment by brasseld** [comment]
Hello @Sebbl22 

Please remove existing Docker images for Gravitee.io and run docker-compose up again.

Thanks for your feedback.

**Comment by Sebbl22** [comment]
Hi @brasseld ,
I ran docker-compose rm, deleted all three graviteeio/* images and created new containers (docker-compose up). Unfortunately I recieve the same error.
One change I noticed was, that I now get a notification in the bottom right corner of the management-ui login screen stating "Cannot pass null or empty values to constructor " when trying to login. This notification hasn't been there before.
Note: This only happens if I try to login with a valid username/password combination like admin:admin or user:password. If I try invalid combinations I recieve the correct "wrong username or password" notiication.

Here is the new gravitee.log file. [gravitee.log](https://github.com/gravitee-io/issues/files/2164312/gravitee.log)

Since there was a comment (which is now deleted) stating that this issue (https://golb.hplar.ch/2017/10/JCE-policy-changes-in-Java-SE-8u151-and-8u152.html) might be related, I also updated the java version inside the container to 8u172 and changed the crypto.policy to "unimited" in the java.security file. Gravitee startet just fine and reported the new HotSpot 64-Bit Server VM/25.172 version in the gravitee.log file, but the execption still remained. If relevant, I can upload the gravitee.log file for this experiment as well.

Thank you for your help.

**Comment by brasseld** [comment]
Can you try to remove docker volume used for mongodb and restart the stack ?
There is absolutely no reason for this issue so I would be sure that you are running Gravitee from scratch.

Also please check that cookies / has been clean up for the Gravitee portal. 

Thanks again

**Comment by Sebbl22** [comment]
I completely removed all docker container and images, pulled them again and startet them. It didn't work either.
After that I deleted all cookies for localhost and it worked. I'm not sure how this could have happened, but I can login now without problems.

Thank you for your help and advice.

**Comment by brasseld** [comment]
Hi guys,

Any news about this issue ?

**Comment by Sebbl22** [comment]
Hi,
as I wrote, the issue was resolved by deleting all cookies for localhost. As far as I know cookies are only domain-specifiy (not considering ports). I tested some other docker containers (especially SonarQube) at the same time, so maybe there were some existing cookies with identical names but unexpected values.

The issue can be considered resolved / closed for me.

**Comment by brasseld** [comment]
Ok, thanks for your feedback @Sebbl22

**Comment by ynuosoft** [comment]
hi all,how to  resolve this bug,i use graviteeio-gateway-1.18.1

**Comment by NicolasGeraud** [comment]
hi @ynuosoft , what is the link between the current issue and your comment ?
