### ISSUE TITLE
Policies - API Key doesn't read the X-Gravitee-Api-Key header

### ISSUE THREAD

**Issue by syedhassan** [gravitee-io/issues#1300]
When we enable the policy for Api Key is not taking my `X-Gravitee-Api-Key` header into consideration. I have to add the params `api-key` to the GET request or else get the following message. So to come out of this situation I have to add both `api-key` an the header `X-Gravitee-Api-Key` or else it doesn't work!

```
{
    "message": "No API Key has been specified in headers (X-Gravitee-Api-Key) or query parameters (api-key).",
    "http_status_code": 401
}
```

### Expected Behavior
`X-Gravitee-Api-Key` should be allowed and the policy should just work and I don't need to add any param in the request.

### Current Behavior
Doesn't respect my headaer

### Possible Solution
Allow header to be used rather than the params

### Steps to Reproduce (for bugs)
1. Add the policy 'Api Key' to your API
2. Make a request by adding the `X-Gravitee-Api-Key`, this results in 401

### Context
I want to pass the API key to my backend but my backend is **NOT** receiving any API key.

### Your Environment

* Version used: 1.16.3
* Browser Name and version: Postman
* Operating System and version: Ubuntu 16.04

**Comment by syedhassan** [comment]
The way to fix this is to use the request context.

Add the policy "Transform Headers" and use it like
![image](https://user-images.githubusercontent.com/2409402/41423555-3d246a3c-6fc1-11e8-9877-0244c73c83e2.png)

@NicolasGeraud thank you for the help.

**Comment by ganesh993** [comment]
still not working
getting this error
{
  "message": "No API Key has been specified in headers (mQUBE-Api-Key) or query parameters (api-key).",
  "http_status_code": 401
}

**Comment by aelamrani** [comment]
@ganesh993 please stop commenting issues with no link at all with your issue.

If you have issues, please create a new ticket and explain it clearly.
