### ISSUE TITLE
Embed into definition repo Jackson classes for Eureka Discovery endpoints

### ISSUE THREAD

**Issue by fmercier-almerys** [gravitee-io/issues#1310]
Eureka service discovery plugin needs some classes for serialization/deserialization.
Such classes are commonly declared into gravitee-definition repository 

I understand the choice of keeping apart this plugin due to the weight of eureka java client but to continue to have a automatized deploiement process with Ansible I propose a PR to integrate few classes into gravitee-definition.

It consists of 3 packages : 
* io.gravitee.definition.model.services.discovery.eureka
* io.gravitee.definition.jackson.datatype.services.discovery.deser.eureka
* io.gravitee.definition.jackson.datatype.services.discovery.ser.eureka

Other parts : 
* Extension : https://github.com/fmercier-almerys/gravitee-gateway-services-endpoint-discovery-eureka
* WebUI : https://github.com/fmercier-almerys/gravitee-management-webui/commit/dd8803bb8e7025a2629cf14ce986d7ed48cb1872 : May have a better way to have Eureka UI form displayed only when plugin is deployed ?

**Comment by aelamrani** [comment]
Not relevant anymore with the `pluginification` of Service Discovery
