### ISSUE TITLE
Management api - SMTP error

### ISSUE THREAD

**Issue by sunilb20** [gravitee-io/issues#1321]
I am using gmail smtp server for email on signup. It throws connect error.

Issue 1 : org.springframework.mail.MailSendException: Mail server connection failed; nested exception is javax.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 465

It fails for 587 as well.

Issue 2 : Actually I am trying to understand how user management works , Can I sign up and use the user other than admin.

**Comment by NicolasGeraud** [comment]
hi @sunilb20, have you configured gravitee like this ?
https://docs.gravitee.io/apim_installguide_management_api_configuration.html#configure_the_gmail_smtp_server

**Comment by sunilb20** [comment]
Hi I have the following in gravitee yml 

email:
  enabled: true
  host: smtp.gmail.com
  subject: "[Gravitee.io] %s"
  port: 587
  from: noreply@gmail.com
  username: sunil.bharadwaj@gmail.com
  password: mypassword
  properties:
    auth: true
    starttls.enable: true
    ssl.trust: smtp.gmail.com

# Mail templates
templates:
  path: ${gravitee.home}/templates

**Comment by NicolasGeraud** [comment]
are you using the two factor authentication ?

I use the same config as you and it works well.

**Comment by sunilb20** [comment]
It seems a firewall issue. It works now.

But When I sign up, I see the user in users table but the user is not associated to any role in roles table.
Even the default user 'admin' too doesnt have roll mapping in DB.

**Comment by sunilb20** [comment]
It seems some of the tables are not used like user_roles instead membership_roles is used.
Got the answer but was little confusing. Closing it.. thanks
