### ISSUE TITLE
[management] oauth2 for the portal authentication is missing name, authorizationEndpoint and scope

### ISSUE THREAD

**Issue by yinghe1** [gravitee-io/issues#1324]
### Expected Behavior
When I config at gravitee-management-rest-api gravitee.yml for oauth2 for portal authentication. I should be able to use oauth2 to authenticate user at portal login. Here is a sample config:
security:
  providers:  # authentication providers
    - type: oauth2
      clientId: xxx
      clientSecret: xxx
      name: Google OAuth2
      authorizationEndpoint: https://accounts.google.com/o/oauth2/auth
      scope:
        - "profile"
        - "email"
      tokenEndpoint: https://accounts.google.com/o/oauth2/token
      userInfoEndpoint: https://www.googleapis.com/oauth2/v1/userinfo
      accessTokenProperty: access_token
      authorizationHeader: "Bearer %s"
      mapping:
        id: id
        email: email
        lastname: family_name
        firstname: given_name
        picture: picture

### Current Behavior
When i choose Sign In with oauth2, it will display a popup at the lower right hand to say "may not be empty" and failed the login. The issue is in the gravitee-management-webui code authentication.config.ts
let customConfig = Constants.authentication.oauth2;
Constants.authentication.oauth2 is missing authorizationEndpoint so it is not able to get code which is (@NotBlank
        String code; in AbstractAuthenticationResource.Payload)

### Possible Solution
1. quick test to add the following to authentication.config.ts will fix the issue but it is only for testing purpose:
// Custom
    let customConfig = Constants.authentication.oauth2;
    if (customConfig && customConfig.clientId) {
      $authProvider.oauth2(_.merge(customConfig, {
        url: Constants.baseURL + 'auth/oauth2',
        oauthType: '2.0',
        redirectUri: window.location.origin + (window.location.pathname == '/' ? '' : window.location.pathname),
        requiredUrlParams: ['scope'],
        scopeDelimiter: ' ',
        name: 'oauth2',
        authorizationEndpoint: 'https://accounts.google.com/o/oauth2/auth',
        scope: ['profile', 'email']
      }));
2. The preferrable way is allowing configure name, authorizationEndpoint and scope in gravitee.yml and when the webui query http://localhost:8083/management/portal, it will return these 3 fields and setup authentication.config.ts (so authentication.config.ts does not need change). For http://localhost:8083/management/portal to return the right info, ConfigServiceImpl.java will need to change to sending these 3 fields down. Sample gravitee.yml is at the expected behavior section. 
http://localhost:8083/management/portal will return
   "oauth2" : {
      "clientId" : "xxx",
      "name" : "Google OAuth2",
      "color" : "#0076b4",
      "authorizationEndpoint" : "https://accounts.google.com/o/oauth2/auth",
      "scope" : [ "profile", "email" ]
    }

### NOTE: 
1. when the webui load the login page, it queries management rest api http://localhost:8083/management/portal to pull down configuration info including authentication setup in gravitee.yml
2. it then passes the info to authentication.config.ts
### Steps to Reproduce (for bugs)

1. config a oauth2 in gravitee-management-rest-api gravitee.yml 
2. choose oauth2 to login at webui portal

### Context
The issue is at 1.17 code base. When the reported issues are fixed, oauth2 authentication for portal login is working.

### Your Environment

* Version used:
* Browser Name and version:
* Operating System and version:

**Comment by brasseld** [comment]
We are in the process of moving all parts from `constants.json` (UI) to the Management API (yml / Settings screen).

There are still some works to achieve before being able to provide all the configuration into this screen. 

So, as a workaround, I would advice you to set and configure correctly both the `gravitee.yml` and the Settings screen, Google Authentication section.

**Comment by brasseld** [comment]
@yinghe1 According to me, you do not have to edit the `constants.json` anymore to configure Google authentication.

I had a try on my own env (v1.17) and what I did was simply to configure the oauth2 properties from `gravitee.yml` as follow:

```yaml
    - type: google
      clientId: xxxxxxxxxxx-7n1mei7693ak72i937ijkgbgv8oma694.apps.googleusercontent.com
      clientSecret: vcSgaE3Ip65kecnbNo7XEkGG
```

And I'm now able to connect from the Portal.

**Comment by brasseld** [comment]
Oauth2 authentication will be configurable from the management-api (see https://github.com/gravitee-io/issues/issues/1595)

This issue will be resolved implicitly
