### ISSUE TITLE
Rate Limiting and Quota meta data neither saved in DB nor it works when testing the API

### ISSUE THREAD

**Issue by sunilb20** [gravitee-io/issues#1328]
As per the plan step in API creation wizard, I configured Rate Limit and Quota, But its niether present in DB nor it works when I test lets says only 1 request per minute.

As per the UI and Documentation, the feature should have worked.

Please let me know if the feature is available ?

**Comment by aelamrani** [comment]
Which gravitee.io version?
Which repository plugin? Which version?
What is the behavior? Is there any error in log?

**Comment by sunilb20** [comment]
graviteeio-full-1.16.3,
gravitee-repository-jdbc-1.16.0.zip
Plan gets saved but not the Quota and Rate Limits entered in Plan step of API creation wizard.

No errors present.

**Comment by sunilb20** [comment]
How ever , If I add the rate quota and Rate Limit after creating API using Rate Limit and Quota Policies, that works. But the same feature doesnt work in wizard.

**Comment by aelamrani** [comment]
OK thanks for theses information.

There is actually an issue with related. See https://github.com/gravitee-io/issues/issues/1286

If necessary you can build it and replace the plugin.
