### ISSUE TITLE
[portal] Add the i18n for brazilian portuguese

### ISSUE THREAD

**Issue by alvarollmenezes** [gravitee-io/issues#1333]
There is no Brazilian Portuguese translation for the gravitee-io/gravitee-management-webui.

### Expected Behavior
Should have a translation to brazilian portuguese.

### Current Behavior
Today we only have the portal in English, French and Chinese.

### Possible Solution
Creating a i18n json file translating the portal.

Thanks @vizeke for helping me translate it.

**Comment by brasseld** [comment]
Thanks à lot @alvarollmenezes !
