### ISSUE TITLE
Configuring  API endpoints with Oauth in Gravitee

### ISSUE THREAD

**Issue by abhijith-pk** [gravitee-io/issues#1334]
Hi,
I have recently started evaluating Gravitee for my company,please excuse me if this isn't the way these features are intended to be used.
I am trying to configure  API endpoints which has Oauth2 already enabled.I am trying to simplify the flow by making Gravitee to make the Oauth2 calls to the login system and get the auth token which will be passed to the endpoint request

### Expected Behavior
using policies and resources for fetching the Oauth token from the login url of our Authorization system and use the auth token for the API end point request.

### Current Behavior
after adding the Oauth resource and policy.The endpoint Oauth resource is not getting called before
the API endpoint call,I am getting 401 error instead

### Steps to Reproduce (for bugs)
the APIs we are testing are intranet but a similar example would be
1. create Endpoint API for azure VM detail fetching
2. Oauth for azure login added to generic oauth resource in  resources 
3. name of resource created in step 2 is added as an Oauth2 policy
4. accessing the Gravitee API call to get the VM details

### Context
we are trying to create an API frontend for multiple legacy APIs which have OAuth mechanisms inbuilt

### Your Environment
* Version used:1.17.0
* Browser Name and version:chrome
* Operating System and version:Windows 10

**Comment by brasseld** [comment]
Hi @abhijith-pk 

IMHO, it is not the Gravitee.io responsibility to let it make calls to OAuth2 to the authorization server.

I will strongly encourage you to keep two different components for
1) Authorization server
2) API Gateway

**Comment by abhijith-pk** [comment]
Hi @brasseld 

Thanks for the reply,
 will the authorization server help me for this (calling the  in-house Oauth server)?
 or 
do I have to make 2 API calls to the gateway ,one for fetching auth token from our in-house oauth server and second for accessing the resource with the access token obtained in the first call ?

Is this considered a good practice using gravitee, to use API gateway as frontend for legacy Oauth protected resource ?

**Comment by brasseld** [comment]
It is a very good practice, but imho I would prefer option 2 where you make 2 calls, one to fetch an access token and an other one to call the API with the given token.

**Comment by abhijith-pk** [comment]
Thanks @brasseld for the nice explanation.Will close the issue now
