### ISSUE TITLE
Deploy on kubernetes?

### ISSUE THREAD

**Issue by PierrickI3** [gravitee-io/issues#1339]
Have you considered providing yaml files to deploy on kubernetes?
A helm chart maybe?

**Comment by chicco785** [comment]
Please do so, I will push my helm chart

iFede - Fede's mobile edition

**Comment by brasseld** [comment]
Please: https://github.com/gravitee-io/gravitee-kubernetes

**Comment by PierrickI3** [comment]
@brasseld @jotamorais has done a great job but I am self-hosted right now and his repo is very much gke and ake centric.
I will be waiting for @chicco785 chart instead.

**Comment by chicco785** [comment]
how can i make PR to the repo? it looks like i can't even fork it (maybe because it's empty)

**Comment by brasseld** [comment]
Ok guys, I've added you as collaborators on this repository.

Please tell me if it's working as expecting.

**Comment by chicco785** [comment]
i did a PR, i think it is a better approach than direct commit

**Comment by chicco785** [comment]
https://github.com/gravitee-io/gravitee-kubernetes/pull/1

**Comment by brasseld** [comment]
Perfect,

I let @PierrickI3 / @jotamorais to give their opinion :)

**Comment by brasseld** [comment]
Support for Kubernetes has been added.

Now waiting for upcoming enhancements (in review) by @jonathas_morais and @chicco785.
