### ISSUE TITLE
Environment variables clarification

### ISSUE THREAD

**Issue by PierrickI3** [gravitee-io/issues#1340]
Thanks for your great product! I saw a presentation at BreizhCamp earlier this year in Rennes, France and I don't think I would have known about you without that.

I am a little bit confused with the environment variables that should be used to point to MongoDB and Elastic in each docker image.

For example, for MongoDB, sometimes, the documentation refers to GRAVITEEIO_MONGODB_HOST but in other locations, it refers to GRAVITEE_MANAGEMENT_MONGODB_URI or GRAVITEE_MANAGEMENT_MONGODB_DATABASE.

So, could you clarify which are available? Also, in the Management API docker image, what is the name of the environment variable for the Elastic Search service? I tried GRAVITEE_REPORTERS_ELASTICSEARCH_ENDPOINTS_0 but it does not work as it still tries to connect to localhost:9200

Thanks.

**Comment by brasseld** [comment]
Hi @PierrickI3 

Configuration using environment variables has been changed in 1.17 that's probably the reason why you may see a mix between the usage of some of them.

Please have a look to the documentation: https://docs.gravitee.io/apim_installguide_management_api_configuration.html#how_to_configure

Also, there is a good example we use for DevFest @ Lille: https://github.com/gravitee-io/devfestlille-2018/blob/master/docker-compose.yml#L70

If you still found references to GRAVITEEIO_MONGODB_HOST, please tell us where you see it and we will take time to update documentation.

Regards,

**Comment by NicolasGeraud** [comment]
hi,

the correct envvar for elasticsearch is not the same for the gateway and the api.

In the gateway, you use the reporter-plugin. The envvar is : `GRAVITEE_REPORTERS_ELASTICSEARCH_ENDPOINTS_0`

In the api, you use the repository-plugin. The envvar is : 
`GRAVITEE_ANALYTICS_ELASTICSEARCH_ENDPOINTS_0`

**Comment by PierrickI3** [comment]
That worked. Thanks! I blindly followed line #71 instead of the correct one.
