### ISSUE TITLE
[gateway] Handling of semicolons on request params

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#1342]
When calling these kind of endpoints: http://localhost:8082/gravitee.io-restapi/apis/362e7bc3-363c-4079-ae7b-c3363c607911/analytics?ranges=100:199;200:299;300:399;400:499;500:599

The outbound query become: http://localhost:8082/gravitee.io-restapi/apis/362e7bc3-363c-4079-ae7b-c3363c607911/analytics?ranges=100:199

**Comment by aelamrani** [comment]
The semi colon si a reserved character: https://tools.ietf.org/html/rfc3986#section-2.2

**Comment by RedChikoy** [comment]
What about URL with OData?
Ex.: 
`https://www.site.com?$top=100&$expand=Employee($select=SaleChannel,FilialId;$expand...`
It contains ";" symbol as part of OData request. And it not working under Gravitee.

**Comment by MTigra** [comment]
Need to be reopened since there is no solution yet
