### ISSUE TITLE
[portal] Upgrade Angular Material dependencies

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#1388]

**Comment by brasseld** [comment]
Some issues with latest upgrade:

<img width="1302" alt="capture d ecran 2018-08-20 a 13 12 07" src="https://user-images.githubusercontent.com/133094/44337388-d1f10880-a47a-11e8-8166-f819dba65198.png">

<img width="221" alt="capture d ecran 2018-08-20 a 12 59 13" src="https://user-images.githubusercontent.com/133094/44337389-d2899f00-a47a-11e8-8156-3ee4b2703d3c.png">

**Comment by brasseld** [comment]
<img width="582" alt="capture d ecran 2018-08-28 a 08 43 43" src="https://user-images.githubusercontent.com/133094/44705354-ae434900-aa9e-11e8-9211-a231638b7ae0.png">

The icon in the chip is not well centered
