### ISSUE TITLE
[gateway] Internal error when trying to access an API with multiple plans

### ISSUE THREAD

**Issue by hqrd** [gravitee-io/issues#1397]
### Context
I deployed an API with 2 plans attached to it. Each of those plans is using a separate OAuth2 resource and a specific scope.
Plan1 is using resource oauth1 with required scope : scope1
Plan2 is using resource oauth2 with required scope : scope2
Each resource has its own clientId and clientSecret, on the same access management.

### Expected Behavior
Each plan should work independently, when accessing the API with a scope1 token, I should access it via plan1. Same for a token with the scope2.

### Current Behavior
I'm getting a 500 internal error when calling the api with a token scope1 or scope2.
See : https://gist.github.com/hqrd/475c3a86413561c2c3bb717fde8bd215

I recreated the 2 plans, and I get `Bearer realm="gravitee.io", error="insufficient_scope", error_description="The request requires higher privileges than provided by the access token."` using the scope2, while the scope1 works. :confused: 

### Steps to Reproduce (for bugs)
1. Create 2 plans using OAuth2 and use a different resource and scope (step2 of plan creation).
2. Subscribe to the plans as a user, 
3. Generate the tokens and make an api call from each tokens

### Your Environment
nginx:1.12.1-alpine
graviteeio/am-webui:1.6.4
graviteeio/am-gateway:1.6.4
mongo:3.4
graviteeio/gateway:1.17.0
graviteeio/management-api:1.17.0
graviteeio/management-ui:1.17.0
mongo:3.4
docker.elastic.co/elasticsearch/elasticsearch:5.4.3

**Comment by brasseld** [comment]
```
io.gravitee.gateway.policy.PolicyChainException: io.gravitee.gateway.policy.PolicyException: java.lang.reflect.InvocationTargetException at io.gravitee.gateway.policy.impl.RequestPolicyChain.execute(RequestPolicyChain.java:46) at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:66) at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:51) at io.gravitee.gateway.policy.impl.RequestPolicyChainProcessor.execute(RequestPolicyChainProcessor.java:63) at io.gravitee.gateway.handlers.api.ApiReactorHandler.handleClientRequest(ApiReactorHandler.java:169) at io.gravitee.gateway.handlers.api.ApiReactorHandler.doHandle(ApiReactorHandler.java:121) at io.gravitee.gateway.reactor.handler.AbstractReactorHandler.handle(AbstractReactorHandler.java:75) at io.gravitee.gateway.reactor.impl.DefaultReactor.lambda$route$0(DefaultReactor.java:87) at io.gravitee.gateway.reactor.handler.transaction.TransactionHandler.handle(TransactionHandler.java:57) at io.gravitee.gateway.reactor.handler.transaction.TransactionHandler.handle(TransactionHandler.java:28) at io.gravitee.gateway.reactor.impl.DefaultReactor.route(DefaultReactor.java:98) at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.handleRequest(VertxReactorHandler.java:39) at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.handle(VertxReactorHandler.java:35) at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.handle(VertxReactorHandler.java:25) at io.vertx.core.http.impl.Http1xServerConnection.processMessage(Http1xServerConnection.java:454) at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:144) at io.vertx.core.http.impl.Http1xServerHandler.handleMessage(Http1xServerHandler.java:74) at io.vertx.core.http.impl.Http1xServerHandler.handleMessage(Http1xServerHandler.java:35) at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:146) at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337) at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195) at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:144) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.vertx.core.http.impl.HttpServerImpl$Http2UpgradeHandler.channelRead(HttpServerImpl.java:970) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61) at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141) at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.lang.Thread.run(Thread.java:748) Caused by: io.gravitee.gateway.policy.PolicyException: java.lang.reflect.InvocationTargetException at io.gravitee.gateway.policy.impl.PolicyImpl.invoke(PolicyImpl.java:91) at io.gravitee.gateway.policy.impl.PolicyImpl.onRequest(PolicyImpl.java:44) at io.gravitee.gateway.policy.impl.RequestPolicyChain.execute(RequestPolicyChain.java:44) ... 50 more Caused by: java.lang.reflect.InvocationTargetException at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at io.gravitee.gateway.policy.impl.PolicyImpl.invoke(PolicyImpl.java:89) ... 52 more Caused by: java.lang.IllegalArgumentException: Required type parameter does not match the resource type at io.gravitee.gateway.resource.internal.ResourceManagerImpl.getResource(ResourceManagerImpl.java:173) at io.gravitee.policy.oauth2.Oauth2Policy.onRequest(Oauth2Policy.java:72) ... 57 more 
```

**Comment by brasseld** [comment]
Hello @hqrd 

What is the reason to have two different resources ?

**Comment by hqrd** [comment]
In order to be able to have 2 different clientId (since the OAuth resource is linked to a clientId).

**Comment by brasseld** [comment]
I think there is a misunderstanding about the OAuth2 resource usage.
The client you should give to the resource is the one which is corresponding to the API gateway, which is acting as a resource server (in oauth2 terms).
Meaning that you don't have to put the client of your consumer, but the client ID dedicated to the gateway !

**Comment by hqrd** [comment]
Oh I see ! But I don't recall having to setup this clientId and secret for the gateway. And using the client's credentials, the resource was working. :confused: 
Where can I find the gateway's credentials ?

**Comment by brasseld** [comment]
Don't know which authorization server you are using and it doesn't matter.
What you have to do is to create a new client in your authorization server, and this client will be dedicated to the API Gateway. Then, you have to update your OAuth2 resource in Gravitee to set client_id and client_secret of the gateway.

**Comment by hqrd** [comment]
That's what I did, and I had 2 different clients on my authorization server. So I used 2 different resources with those 2 clients (pointing at the same server).

**Comment by brasseld** [comment]
I still don't understand why you need 2 different clients...

From my point of view, you have two clients because you have probably two applications which are consuming your API, and I'm ok with that part.

Now, from the API Gateway point of view, you didn't have to create an oauth2 resource per client, it is a non-sense. The OAuth2 resource is defined for the gateway, which is acting as a resource server (like your API backend).

**Comment by hqrd** [comment]
If I'm using a single resource, I get a 401 from the second client with the message "The request requires higher privileges than provided by the access token.".

**Comment by brasseld** [comment]
What are you trying to do ? Create an Oauth plan ? or just the oauth2 policy ?

**Comment by hqrd** [comment]
Having 2 OAuth plans for the API. One using a limited-scope, and one with access to everything.

**Comment by brasseld** [comment]
ok, so you just have to create a single resource, put oauth2 client credentials for the API gateway and then create 2 plans with limited access using scopes.

**Comment by hqrd** [comment]
I did that, deleted the 2nd resource and linked the 1st resource to the 2nd plan. 

But when I'm calling the API with the app using the 2nd plan, I'm getting a "The request requires higher privileges than provided by the access token.". But the scope is actually ok in the 2nd plan. Any idea why this won't work ?

**Comment by brasseld** [comment]
Please provide a json export of your API.

**Comment by hqrd** [comment]
Here it is : https://gist.github.com/hqrd/958f666bdf3ad9ef1b535a4eb52c3960

Btw thanks for the replies, really appreciate the support :+1:

**Comment by brasseld** [comment]
Ok @hqrd 

Can you tell me:
-> What is your authorization server
-> Are you sure you have the required scopes to make the second call ?

Also, I think it may be easier if we can discuss directly using our gitter channel, WDYT ?

https://gitter.im/gravitee-io/gravitee-io

**Comment by gitzalm** [comment]
I have a similar problem: 2 applications (with different clientId) authentified on 2 different OAuth2 resource but consuming the same API. Also get a 500 error as soon as I have 2 OAuth2 resource.

Is there any news about this bug ?

**Comment by brasseld** [comment]
Hello @gitzalm 

What is the reason for having two different oauth2 resources ?

**Comment by fmercier-almerys** [comment]
Ok to sum up our discussion on gitter : 

There is two use case concerned by multiple oauth2 plan : 
* Declare different consommation "contract" : You can have an oauth2 plan with limited access with quota and endpoint blacklist and another more open for premium customer
* Set multi tenancy Oauth2 strategy : For a same API you can set up different Oauth2 resources and each of the associated with a specific Oauth2 plan. In this way you can isolate Oauth2 REALM for exemple. 
* Beeing iso feature with API KEY plan 

For JWT oauth2 access token format no problem I agree, all information is contained inside the token and it is easy to associate a access token with the right plan (by issuer id for example)

For other access token format such UUID access token it is more complex because there is no data for the mapping. It behave more like an API KEY.

**Comment by brasseld** [comment]
This issue is closed by https://github.com/gravitee-io/issues/issues/2220

You now have the ability to configure the way to select for a plan according to the incoming access_token (if this one is a JWT token).
