### ISSUE TITLE
[policy] json schema filename is problematic on Windows OS

### ISSUE THREAD

**Issue by M3lkior** [gravitee-io/issues#140]
Any manipulation on json schema file in windows failed caused by `Invalid argument`

Problems occurs when : 
- try to clone policy repository
- try to pull/push this file
- gravitee-management-api try to unzip policy plugins on Windows `/plugins` path
- etc

Probably due to char : in path : https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#Naming_Conventions

**Comment by NicolasGeraud** [comment]
![microsoft_once_had_to_rebuild-399de53540c79757ac9af535579cdad9](https://cloud.githubusercontent.com/assets/1028285/16731496/afaca02e-4778-11e6-8260-745d0beaa27d.jpg)

**Comment by NicolasGeraud** [comment]
we have to rename all json resource to `schema-form.json`

**Comment by brasseld** [comment]
Maven plugin has also been upgraded thanks to @koh-osug:
https://github.com/gravitee-io/json-schema-generator-maven-plugin/pull/3
