### ISSUE TITLE
[ui] Keycloak service provider

### ISSUE THREAD

**Issue by rwxget** [gravitee-io/issues#1404]
Hi,

I installed Gravitee (version 1.18.1 (build: 345)) and started playing with it, but unlike what I've seen during your presentation at Devfest Lille 2018, in my resources list I don't see the Keyloack service provider : 

![image](https://user-images.githubusercontent.com/30153115/43050025-29e3681a-8e02-11e8-844b-c0e1eb536808.png)

Is that normal ? Should I install a plugin for that ?

Thank you.

**Comment by brasseld** [comment]
The plugin is not yet part of the final distribution.

You can download it from: https://download.gravitee.io/graviteeio-apim/plugins/resources/gravitee-resource-oauth2-provider-keycloak/gravitee-resource-oauth2-provider-keycloak-1.0.0.zip

Regards,

**Comment by brasseld** [comment]
You're welcome ;)

You can call me David (Brassely is my family name...).

A quick question: you were present at the DevFest presentation ?

**Comment by rwxget** [comment]
Oh ! sorry David :-)

No, I wasn't, I watched it via Youtube. But I hope to attend your next presentation. 

You guys do a great job. Thank you !

**Comment by brasseld** [comment]
May I ask you to share the link here ?  I did not watch it. Thanks!

**Comment by rwxget** [comment]
Yeah, sure : https://www.youtube.com/watch?v=Lkr3Hok-rfk

**Comment by brasseld** [comment]
Cool, thank you very much !

See you during the next one ;)
