### ISSUE TITLE
API key or Oauth vs API key and Oauth

### ISSUE THREAD

**Issue by sunilb20** [gravitee-io/issues#1407]
Does it make sense to use both API key and Oauth2 policy for the same api.
For Open Api's,  Max I can use Oauth grant type is Client_Credentials.

**Comment by brasseld** [comment]
It doesn't make sense.

**Comment by sunilb20** [comment]
It seems, then, Outh2 makes more sense , If I have to use one out of the 2, where I can play with Scopes as well.

**Comment by brasseld** [comment]
Is this a question ?

**Comment by sunilb20** [comment]
Yeah

**Comment by sunilb20** [comment]
Okay, We have zeroed in on Oauth2 policy instead of API key. 
Thanks...

**Comment by brasseld** [comment]
Good choice!
