### ISSUE TITLE
API(s) missing in user management API screen

### ISSUE THREAD

**Issue by bkhadige** [gravitee-io/issues#1408]
API(s) missing in user management API screen

### Current Behavior

A user creates an publishes an API (having the role API_PUBLISHER)
the API is created, deployed and started
the API is missing in the API management view (only the API_ADMIN sees the API)

### Steps to Reproduce (for bugs)

1. Made an upgrade from 1.16.0 to 1.18.0
2.
3.
4.

### Your Environment

* Version used: 1.18.0
* Browser Name and version: chrome 67.0
* Operating System and version: fedora 28

**Comment by aelamrani** [comment]
Hi,

i think you are facing a bug fixed in 1.18.1 : https://github.com/gravitee-io/issues/blob/master/CHANGELOG.adoc#1181-2018-07-26

**Comment by bkhadige** [comment]
Ok thanks for the answer, i will upgrade and give feedback

**Comment by aelamrani** [comment]
Ok please let us know

**Comment by bkhadige** [comment]
The upgrade to 1.18.1 solved the problem, thanks again
