### ISSUE TITLE
How is version field utilized ?

### ISSUE THREAD

**Issue by sunilb20** [gravitee-io/issues#1418]
I haven't seen much documentation details for version text field present on API creation wizard.
There are 2 options to create achieve versioning: 
Option 1: using version text field in API creation wizard - Will need 2 separate api's
1. Where do you use version for an API ?
2. Can I implement versioning using this field i.e. context path : /path and version changed from v1 to v2.
and final path would be /path/v1 and /path/v2 for 2 different api's.

Option 2: Dynamic Routing - Single API will cater different versions
1. I have created 2 routings for the same api and it serves the purpose of api versioning.
2. Now the query is : if I have to implement JSON to JSON transformation for each version, Is it possible ?
Transformation policy is applicable per api and it seems it can not be linked with versioning created using dynamic routing for same API.

What do you think about this ?

Please try to answer all of queries.

**Comment by brasseld** [comment]
Hi @sunilb20 

About option 2, you can create a path per version from the policy screen.
This way, you will be able to implement json to json transformation for each version.

**Comment by sunilb20** [comment]
This looks good. Works well.
