### ISSUE TITLE
[policy] [dynamic-routing] Regex naming group

### ISSUE THREAD

**Issue by lusoalex** [gravitee-io/issues#142]
Hello,
When using (standard) regex, it is usefull to use group naming in order to reuse "business" name instead of groups + position.

Example : 
```
Regex : \/api\/(?<version>v[0-9]+)\/stores\/(?<store>[0-9]+)(?<path>[^0-9]*)
Test url : http://domain/app/api/v1/stores/118/toto
````

Regex matching : 
version	[22-24]	`v1`
store	[32-35]	`118`
path	        [35-40]	`/toto`

used for : 
{#properties[${version}+'-'+${store}]}/api/${version}/stores/${store}${path}
==> We have a properties key="v1-118", value="http://mydomain.com"

Regards,
Alexandre.

**Comment by brasseld** [comment]
Hi @lusoalex,

To preserve general coherency of Expression language syntax, it would be better to not use backward reference (${version}) but use group names using expression language variables.

This way, you will be able to access your capture group by name with the following syntax:
```
{#properties[#groupName['version']+'-'+#groupName['store']]}/api/#groupName['version']/stores/#groupName['store']#groupName['path']
```

WDYT ?
