### ISSUE TITLE
[portal] [analytics] Refresh button on dashboard and analytics page

### ISSUE THREAD

**Issue by hanuman1988** [gravitee-io/issues#1420]
### Expected Behavior
separate refresh button on dashboard and  analytics page. 

### Current Behavior
currently there is no option to refresh (apart from clicking time frame  default time "1 D") but sometime user might think  refreshing the page by pressing  F5 or F6+Enter but it shows old data.

### Possible Solution
so if we could provide separate refresh thus user will click on refresh button to view update.

### Steps to Reproduce (for bugs)

1. configure the API
2. Hit by postman
3. come back to dashboard screen refresh the page by F5 , it should show hit count 1
4. but nothing will be there, now click on time interval now we can see the hit count 1

### Context
i have been giving demo to team member we hits the API from Postman but no increment in hit count every time we refreshed by F5 then later we moved to some other menu item and came to dashboard i got the hit count update.

### Your Environment

* Version used: 1.18.1
* Browser Name and version: chrome : Version 68.0.3440.84 (Official Build) (64-bit)
* Operating System and version: windows -10

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/issues/issues/1421
