### ISSUE TITLE
Doc issue on gravitee-policy-xml-json

### ISSUE THREAD

**Issue by fmercier-almerys** [gravitee-io/issues#1424]
seems to have a doc error on the readme https://github.com/gravitee-io/gravitee-policy-xml-json
its describes the action onRequest but in the policy it is onRequestContent

**Comment by fmercier-almerys** [comment]
https://github.com/gravitee-io/gravitee-policy-xml-json/pull/9

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/gravitee-policy-xml-json/commit/25649745303c2eaca59c101237cec5ad682f88ad
