### ISSUE TITLE
[management] Plan screen in API wizard does not have all security types.

### ISSUE THREAD

**Issue by sunilb20** [gravitee-io/issues#1430]
Plan screen in API wizard does not have all security types.
It shows only 2 : API Key and Keyless 
Whereas while adding new plan under API properties(After creating API), It shows 4 : API key, Keyless, JWT and Oauth2

Question1 : Which plan screen should we use ? 
Question2: Since only one type is allowed to be selected out of the four , that means either We should use API key or Oauth2 but not both
Question3: How Plan security different than the Oauth2 policy.

Out of the three places, which one we should use and in what scenario ?

Current version 1.16.3

**Comment by brasseld** [comment]
Hi

At this time, we didn't move the plan wizard into the API wizard to keep the latest as simple as possible. As you said, the drawback is that not all security types are available from the API wizard...

Q1: The best is to use the plan wizard which is slightly more complete, including policy configuration.

Q2: if you need both (but I don't see any reason), you can define an api-key plan and drag and drop the oauth2 policy

Q3: If you define an oauth2 plan, it is exactly the same as the policy configuration. The only thing which is changing is that application must have a `client_id` define to be able to subscribe to an oauth2 plan (or JWT plan).

Is this clear for you ?

**Comment by sunilb20** [comment]
Yeah a bit,
2 more questions : 
1. Which one should I use : A plan with Oauth2 security type where users subscribe in portal or Keyless plan with Oauth2 policy where user just pass the token (No portal user registration and subscription required)
2. If I go with Plan with Oauth2 security type, and need to have transformation, Can I have separate transformation for each plan ?

**Comment by brasseld** [comment]
Q1: it depends on the security you want to add. IMHO, oauth2 plan is the best choice if you have a running authorization server.

Q2: not at this time.

**Comment by sunilb20** [comment]
Without this linking, I think creating multiple plans isnt effective.
For instance, for each plan I may add additional policies and add paths for each plan.

If I choose the key less plan and then add policy for Oauth2, then Statistics like Top Applications, top plans are not useful .
Ideally there should be a linking or else I dont see effective use of it.

**Comment by sunilb20** [comment]
Also , If I go with keyless plan and Oauth2 policy, my clients will never need any subscription but just have to pass oauth token . There should not be a subscription options for such plans. 
A better way is to have a plan-less api where I opt for higher API security like Oauth2 and there is no plan for subscription.

**Comment by brasseld** [comment]
Do you mean that you would like to deploy and expose API without having to create a plan ?

**Comment by sunilb20** [comment]
I had mentioned a scenario where "If I go with keyless plan and Oauth2 policy, my clients will never need any subscription but just have to pass oauth token . "

Whats the use of plan in that case. The clients will just have to pass the token and not have to subscribe to the plan. I dont  see the real time usage of this plan.

**Comment by brasseld** [comment]
Yah, you're right in your case....

But some others users doesn't want pass-trough plan because they want to apply strict security.

**Comment by sunilb20** [comment]
Okay, Since the feature to test the Oauth2 plan is not working(Refer https://github.com/gravitee-io/issues/issues/1433), Shall I assume that it will need subscription to work with those plans.
Keyless plans with Oauth2 policies does not need a subscription though.

**Comment by brasseld** [comment]
Yah, for api-key / oauth2 and JWT plan, you need a subscription to work with them.

**Comment by sunilb20** [comment]
Cool. api-key / oauth2 and JWT plan make more sense than keyless plan and Oauth2 policy and We can see appropriate statistics like top applications/ Plans etc which in other case would always show Unknown application. But as you mentioned , Its up to the client requirement how tightly we want to secure the API.

**Comment by brasseld** [comment]
That's exactly the point!

So, is there any reason to keep this issue as opened ?

**Comment by sunilb20** [comment]
Closing this now. Thanks!!!
