### ISSUE TITLE
[policy] Working with custom Policy

### ISSUE THREAD

**Issue by girishmanwani** [gravitee-io/issues#1434]
I am using the default blank template for writing custom policy available at 
https://docs.gravitee.io/apim_devguide_policies.html

I have modified the onRequest method to include the following:

    	request.headers().set("Access-Control-Allow-Origin", "*");
    	request.headers().set("Access-Control-Allow-Methods","GET, OPTIONS, HEAD, PUT, POST");
    	request.headers().set("X-Gravitee-Api-Key","e78b76d7-36ab-4fe3-b745-43f9c0eaa9ea");

I am able to deploy the policy and apply it on myFirstApi - the sample API for echo providee by Gravitee.
When testing REST Client -I do see the onRequest and onResponse methods being accessed. 

However when I try to access the "myfirstapi" url via springboot restTemplate - it give me 401 error
restTemplate.getForObject("http://localhost:8082/myfirstapi", String.class);
I am not passing the X-Gravitee-Api-Key over here as I am setting the same in policy request header.

Pl. advice

Rgds
Girish

**Comment by NicolasGeraud** [comment]
hi,

What do you want to achieve exactly ?
Because if you want to set headers, we already have a policy for that purpose.

**Comment by girishmanwani** [comment]
Hi @Nicolas
I want to achieve: 
1) set the headers
2) enable CrossOrigin access - I want to access http://localhost:8082/myfirstapi via an external application using spring boot resttemplate.

pl. advise.

**Comment by NicolasGeraud** [comment]
ok.
1. We already have a policy for that: https://docs.gravitee.io/apim_policies_transform_headers.html
2. We already have the CORS features: https://docs.gravitee.io/apim_publisherguide_configuring_cors.html
CORS is under the proxy configuration menu of your API

**Comment by girishmanwani** [comment]
Hi @NicolasGeraud 
I have enabled both Policy and CORS(pl. see. atchd images).

Now when I call 
String str = restTemplate.getForObject("http://localhost:8082/myfirstapi", String.class);
It still gives me 401-Unauthorized.

If I try curl without passing header - since it is now configured in the policy(pl. see. atchd image) - it still shows 401 Unauthorized.
curl -v http://localhost:8082/productsapi

I want to access the gateway api url - http://localhost:8082/productsapi via an external application from where I call the restTemplate.I assume the policy will provide the APIKEY and CORS will be taken care in Proxy config.Is this approach correct.
Is there something missing that needs to be configured or corrected.

Regards
Girish

![proxy-cors](https://user-images.githubusercontent.com/1228635/44442910-82354d00-a5f2-11e8-9fe4-d473e7097c73.PNG)
![policy](https://user-images.githubusercontent.com/1228635/44442911-82cde380-a5f2-11e8-8f32-38a86ed826a1.PNG)

**Comment by brasseld** [comment]
No, it's  not the correct approach. If you choose to create an apikey plan, it is the responsibility of the consumer to provide its own apikey provided when he subscribe to the plan.

If you don't want the consumer to pass an apikey then you have to create a keyless (pass-through) plan.

**Comment by girishmanwani** [comment]
Ok thanks for the inputs.
