### ISSUE TITLE
[management-api] Programmatic access to Gravitee

### ISSUE THREAD

**Issue by girishmanwani** [gravitee-io/issues#1437]
Hi Folks,
A bit new to the gravitee platform - I had a question:

Can I request subscription access for a particular Gravitee API through an external Java class and in return get a API-KEY from Gravitee as response.

or

Step 1 - to subscribe to a particular Gravitee API via a Java Class and get Success message.
Step 2 - fetch api-key from gravitee mongodb database(if it contains api-key data)

Rgds
Girish

**Comment by brasseld** [comment]
Hi @girishmanwani 

You can call the Management API to do what ou want:
See the API documentation: https://docs.gravitee.io/apim/api/1.17/#operation/listApiSubscriptions

**Comment by NicolasGeraud** [comment]
Sure, you must use our API.
https://docs.gravitee.io/apim/api/1.17/#operation/createSubscription

**Comment by girishmanwani** [comment]
For creating a new subscription - what should be the request parameter:
Example -
Endpoint:
/applications/SampleAPP/subscriptions

{
"application": "SampleAPP",
"plan": "FirstAPIPlan",
"request": "string"
}

But it fails - as I may not be passing the correct request string.

Pl. advise.

**Comment by brasseld** [comment]
The request parameter is just a simple string value which is given by the consumer while subscribing to the plan and which is indicating what are the reason of the subscription, you can leave it empty.

**Comment by girishmanwani** [comment]
I get the error pl. see atch.

![subscription_new](https://user-images.githubusercontent.com/1228635/44455921-ea992400-a61c-11e8-8f36-fe9378f77796.PNG)

**Comment by girishmanwani** [comment]
I do see a note at https://docs.gravitee.io/apim/api/1.17/#operation/createSubscription
stating that "User must have the MANAGE_PLANS permission to use this service"
Also the error is - pl. see atchd.

![subscription_new](https://user-images.githubusercontent.com/1228635/44456191-86c32b00-a61d-11e8-9cc8-eac2f5fb1ec3.PNG)

**Comment by brasseld** [comment]
Sorry but I'm not sure that `SampleAPP` is a valid identifier, it must be a UUID.

**Comment by girishmanwani** [comment]
Hi @brasseld 
I tried the same using the application id and planid - but still get the same error.

**Comment by brasseld** [comment]
Ok, I will have a look

**Comment by brasseld** [comment]
Please try with:

POST http://localhost:8083/management/applications/0194bf0c-3ca2-4571-94bf-0c3ca2f571df/subscriptions?plan=ab8945e9-42c1-4a67-8945-e942c1aa673b

Request body (optional)

{
	"request": "I need to subscribe to this API plan"
}

**Comment by girishmanwani** [comment]
Hi @brasseld - this creates the subscription with the subscriptionid - but the status is PENDING.
Is there some way it can be auto accepted and we get a API-KEY as response to the above request.

**Comment by brasseld** [comment]
Yes, you just have to change a property on your plan named "auto-validation".

See https://docs.gravitee.io/apim_publisherguide_plans_subscriptions.html#approving_subscriptions

**Comment by girishmanwani** [comment]
Thanks - this works !
