### ISSUE TITLE
[service] [discovery] Use separated consul config for each group

### ISSUE THREAD

**Issue by zhendongli** [gravitee-io/issues#1439]
when use consul to discovery the endpoints of the backend service, currently, Gravitee only support consul service discovery for the default group(enabled group), but I wish to use different backend endpoints in different groups. There are two approachs in my mind. 

1. use separated consul config for each group (I preferred)

2. allow to use consul tags in the current global consul config

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/issues/issues/1701
