### ISSUE TITLE
External client access - values not fetched

### ISSUE THREAD

**Issue by girishmanwani** [gravitee-io/issues#1441]
I have an API deployed(uses APIKEY for token) in Gravitee and testing via REST client.

If I access the gateway directly from Rest Client for the url http://localhost:8082/greetingapi 
I get the correct response.

If I access an external jquery client like http://localhost:7777 which internally calls
http://localhost:8082/greetingapi?api-key=MYAPIKEY
I get a 401 Unauthorized error.

Do I need to unable some more settings for access via "external" consumer such as jquery or angular.

Regards
Girish Manwani

**Comment by brasseld** [comment]
Sorry @girishmanwani but I don't understand what is the issue with Gravitee here.

It should work in the same way if the api-key is valid.

**Comment by girishmanwani** [comment]
Hi @brasseld - you are right.
This works on my linux system - i am assuming it is network/firewall or OS related.
We can close the issue.

Rgds
Girish
