### ISSUE TITLE
[management-api] Creating application from jquery : Full authentication is required to access this resource

### ISSUE THREAD

**Issue by girishmanwani** [gravitee-io/issues#1448]
I am using a POST request in jquery to create an application.I get an error "401 (Full authentication is required to access this resource".Which parameters should I pass for authentication and how.
I have not created any users and groups.The stuff works fine from REST Client - but gives error when calling from jquery.

	    $.ajax({
	          url: "http://SERVER:PORT/management/applications/",
	          type: "POST",
	          data: {name: "App Name", description: "Dynamic Greeting", type: "web" },
	          dataType: "json",
	          beforeSend: function(x) {
	            if (x && x.overrideMimeType) {
	              x.overrideMimeType("application/j-son;charset=UTF-8");
	            }
	          },
	          success: function(result) {
	        	  $('.app-id').append(result.id);
	          }
	});

**Comment by brasseld** [comment]
You must have to pass an authorization header.

For example, using the admin:admin default account:

`Authorization: Basic YWRtaW46YWRtaW4=`

**Comment by brasseld** [comment]
Hi @girishmanwani,

Any news about this issue?

**Comment by girishmanwani** [comment]
Yes this works - The issues is/can be closed.
