### ISSUE TITLE
[portal] Add versioning on documentation pages

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#146]
It could be useful to add versioning on api documentation pages

**Comment by sunilb20** [comment]
Any update in documentation ?
I am not getting the use of version parameter when creating api.

I see that I can not create an api by changing only the version and all other parameters like context path etc same. 

It complains that the context path already exists. Ideally version should be appended to context path.

**Comment by brasseld** [comment]
Not sure that you're talking about the same thing.
Initial issue was about adding versioning at the documentation pages level.
You want to create a new API but preserve the same context path as you have earlier for the same API but only the version field has been changed. By doing this, you are right, the best would be to append the version to the context path. So  in that case, why you didn't do it manually, I mean,  by appending the version to the path by yourself while registering the API ?

**Comment by sunilb20** [comment]
No the version should come from the version input text.
But I have another solution for API versioning : https://github.com/gravitee-io/issues/issues/1185

I will be using Dynamic routing to implement API versioning. I have some more queries on top of the , I am going to ask in the same issue.
