### ISSUE TITLE
[repository] [mongodb] Add mongodb repository TLS/SSL CA trusted compatibility

### ISSUE THREAD

**Issue by fmercier-almerys** [gravitee-io/issues#1460]
Currently the mongodb supports only SSL mode self signed certificate that encrypt communication between gravitee and the replicaSet.
To follow production recommandation gravitee needs to support CA client

http://mongodb.github.io/mongo-java-driver/3.4/driver/tutorials/ssl/

*  javax.net.ssl.keyStore The path to a key store containing the client’s TLS/SSL certificates
*  javax.net.ssl.keyStorePassword The password to access this key store

Include new mongodb options into https://github.com/gravitee-io/gravitee-repository-mongodb/blob/b66db093dc07e705587b5b1b2c95273b9d9706b9/src/main/java/io/gravitee/repository/mongodb/common/MongoFactory.java

SSLContext seems to be a good candidate to manage keystore

CA client might be added into the keystore before and we can just import the keystore into SSLContext

**Comment by fmercier-almerys** [comment]
https://github.com/gravitee-io/gravitee-repository-mongodb/pull/83

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/gravitee-repository-mongodb/pull/83/commits/49937cf6a4865c73ada25971fad43e415bd6dade
