### ISSUE TITLE
Is there any minimum hardware config requirement for Gravitee components

### ISSUE THREAD

**Issue by sunilb20** [gravitee-io/issues#1461]
Hi,
To deploy the Gravitee gateway components in customer integration env, please suggest minimal hardware configuration requirement for Gravitee gateway components.

**Comment by brasseld** [comment]
It depends on the number of APIs, HA or not, number of calls, ...

**Comment by sunilb20** [comment]
will start with 5 API's and no high availability. Just one server for gateway.
So : 
1. What is the minimum config required for gateway, portal and API management components
2. Even with HA, do you recommend Portal GUI and Management api to be deployed in the same machine ?

**Comment by brasseld** [comment]
For the portal, it is just about static HTML files
For the gateway, the more CPU you have, the more you are able to manage concurrent requests. 512 Mo with 4 CPU is ok
For management-api, JVM with 512 Mo and 2 CPU is sufficient.

**Comment by sunilb20** [comment]
Since my second question is still unanswered, So
1. Can we deploy Portal GUI and Management API in the same machine ?
2.  Can we load balance the portal app and Management api component separately or how do we do that.

**Comment by brasseld** [comment]
1. yes
2. these components are not critical, no reason for HA and LB.
