### ISSUE TITLE
[gateway] Request not logged when X-Forwarded-For header contains host with port number

### ISSUE THREAD

**Issue by sahlex** [gravitee-io/issues#1468]
We noticed recently that a request sent through an azure web appliction gateway does not appear in the logs. However, when we send an identical request directly to the gateway directly it is logged perfectly. So it seems that the app gateway is adding something to the request that causes the behavior. 

Further investigations turned out that azure's application gateway tends to deliver not only the client's IP address but a combination of IP:PORT in the X-Forwarded-For (XFF) header which is not the case when we send the request to the gateway directly using postman. Gravitee's implementation seems to have trouble using this as no logs appear in elasticsearch when a request comes in through an azure app gateway.

The Headers which are added by the gateway are:

      Max-Forwards: 10
      X-FORWARDED-PROTO: https
      X-FORWARDED-PORT: 443
      X-ORIGINAL-HOST: some.host.name
      SEC-WEBSOCKET-EXTENSIONS:
      X-Original-URL: /Test/Coupons
      X-Forwarded-For: 1.2.3.4:51008
      X-ARR-SSL: (removed)
      X-ARR-LOG-ID: b5eda9fb-b48a-45a3-818d-63d35ad1d1d6

However, the request is processed nevertheless.

### Expected Behavior
A message should be logged in elasticsearch when sent through azure's web application gateway.

### Current Behavior
A message is not logged in elasticsearch when sent through azure's web application gateway. No exception is thrown in the gravitee logback system.

### Possible Solution
Gravitee should be able to deal with the format IP:PORT for components in XFF header.

### Steps to Reproduce (for bugs)
1. pick any API on gravitee and set proxy log on for client and proxy
2. add an X-Forwarded-For header with dummy value (like 1.2.3.4:56000) to the request (did it with postman)
3. verify that no message is logged

### Context
Gravitee behind an azure application gateway.

### Your Environment
Gravitee 1.18.1 on docker 18.06 on CentOS 7.4

**Comment by brasseld** [comment]
I looked around for standards stating that XFF must/should contain an optional port, but did not find any. I am thinking the XFF is governed more by convention than standard; correct me if I am wrong.

There is an applicable standard here: RFC7239. But this standard is not in wide use as far as I can tell. And Gravitee.io does not support it today, as far as I know.

**Comment by sahlex** [comment]
@brasseld, that's ablolutely correct. XFF is a de-facto standard that was introduced by squid proxy. So it's not standardized. Unfortunately, Microsoft uses it nevertheless the way they do ;-) (Wouldn't be the first non-standard thing for them). RFC7239 mentions it for a **Forwarded** header and does not seem to be applicable for XFF.

Nevertheless, it wouldn't hurt to make gravitee able to cope with it!

Best regards,
Alexander

**Comment by brasseld** [comment]
Don't worry, it is already fixed and the fix will be available with the next version 1.19, scheduled for next tuesday.

Regards,

**Comment by sahlex** [comment]
Thank you very much!

**Comment by NeubauerJohannes** [comment]
This is somehow affecting version 1.30 now again. Can you please check?
