### ISSUE TITLE
[rest] Page ids don't have to contain the page title

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#148]
Page id is compound of the api id + page title.

But the title could be changed (and not the page id).
It's better to use an UID for the page id.

**Comment by brasseld** [comment]
And it is exactly the same for API where its name can be changed....

**Comment by NicolasGeraud** [comment]
and Application to ?
I'll remove the IdGenerator.

Ok with that?

**Comment by brasseld** [comment]
👍

**Comment by NicolasGeraud** [comment]
done, you can review it
