### ISSUE TITLE
[plugin] A plugin may provide its own logo / icon

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#149]
Plugins like fetchers (and I think policies and resources could need it to) must provide their logo (encoded in base64 I think).

With this feature, we don't ever have to commit new logos in the webUI

**Comment by brasseld** [comment]
👍

**Comment by brasseld** [comment]
@NicolasGeraud Why not putting the logo / icon in the final zip assembly as it's already done for schema ? We do not need to encode it in base64 anymore.

**Comment by NicolasGeraud** [comment]
because, the restapi will provide a way to get the plugin logo, I think a base64 value is more "rest" than a binary value.

**Comment by brasseld** [comment]
Should be closed by https://github.com/gravitee-io/issues/issues/3895
