### ISSUE TITLE
[policy][transform headers] apply order

### ISSUE THREAD

**Issue by bcollard** [gravitee-io/issues#1493]
In this policy, it looks like the adding part is done before the removing part.
The UI show the "remove" part before the "add" part.

Can you either change the UI or explain why you made this choice?

This problem is that you can't remove a header and add it again (in order to overwrite its value) in the same policy. If you try this, the header will be deleted.

**Comment by bcollard** [comment]
ok, I thought the header would be added twice. I didn't notice "update".
Thanks.

**Comment by brasseld** [comment]
Ok so we can close this issue ?

**Comment by brasseld** [comment]
IMHO, you do not have to know about the execution order.

Since you are now able to update properly an HTTP header, I'm closing this issue.
Feel free to reopen it if you think something should be resolved.
