### ISSUE TITLE
How can I enable a policy?

### ISSUE THREAD

**Issue by danlange** [gravitee-io/issues#1494]
I am trying unsuccessfully to add a policy plugin to my deployment.  It seems like there is some configuration step that is missing from the documentation.

I successfully built a new plugin using the instructions at:
https://docs.gravitee.io/apim_devguide_policies.html
I copied the plugin into the plugins directory and restarted the server.
Based on the gravitee.log, the plugin appears to have successfully deployed:
19:13:44.307 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - Loading plugin from /opt/graviteeio-gateway/plugins/gateway-url-transform-policy-1.0.0-SNAPSHOT.zip
19:13:44.308 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl - A plugin manifest has been loaded from: /opt/graviteeio-gateway/plugins/.work/gateway-url-transform-policy-1.0.0-SNAPSHOT/gateway-url-transform-policy-1.0.0-SNAPSHOT.jar
19:13:44.324 [gravitee] [] INFO  i.g.p.c.internal.PluginRegistryImpl -  > gateway-url-transform-policy [1.0.0-SNAPSHOT] has been loaded
19:13:48.424 [gravitee] [] INFO  i.g.p.p.internal.PolicyPluginHandler - Register a new policy: gateway-url-transform-policy [com.polycom.apigateway.GatewayUrlTransformPolicy]

However, the plugin does not appear to ever actually be used.  It is supposed to set a header in the request, and I don't see that happening.  It is supposed to log whenever the configuration class is instantiated, and I don't see that happening.

Am I supposed to add something to gravitee.yml?
I tried adding 
gateway-url-transform-policy:
  stringParam: override
or
policy:
  gateway-url-transform-policy:
    stringParam: override
but neither of those did anything.
I tried adding "gateway-url-transform-policy" as a metadata to the API I am using, but that did not do anything.

I haven't been able to enable any of the pre-defined policies either.  Those policies very confusing, because the documentation includes json snippets to configure the policy, but there is no obvious place where these json snippets are supposed to go.

Is there anywhere that I can find an example of configuring a policy?

**Comment by brasseld** [comment]
Hello @danlange 

I think you have implemented a custom policy, which sounds good.

Now you have to deploy it in the `plugins` directory of both the gateway *and* the Management API.

Then, to ask the gateway to use this policy, you have to drag and drop it from the `policies` screen.

Finally, deploy the API after the changes and try to call your API.

**Comment by danlange** [comment]
My custom policy does not show up on the policies screen.

**Comment by brasseld** [comment]
most probably because you did not deploy it inside the `plugins` folder of the management-api ?

**Comment by danlange** [comment]
Nevermind that last.  I deployed the plugin to the management-ui rather than the management API.
Now that I have it deployed to the right place, it is killing the management-api:
local_managementapi_1  | 20:32:04.451 [gravitee] INFO  i.g.p.c.internal.PluginEventListener - Installing SERVICE plugins...
local_managementapi_1  | 20:32:04.451 [gravitee] INFO  i.g.m.s.plugins.ServicePluginHandler - Register a new service: localregistry [io.gravitee.gateway.services.localregistry.LocalApiDefinitionRegistry]
local_managementapi_1  | java.lang.reflect.InvocationTargetException
local_managementapi_1  |        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
local_managementapi_1  |        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
local_managementapi_1  |        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
local_managementapi_1  |        at java.lang.reflect.Method.invoke(Method.java:498)
local_managementapi_1  |        at io.gravitee.management.standalone.boostrap.Bootstrap.start(Bootstrap.java:157)
local_managementapi_1  |        at io.gravitee.management.standalone.boostrap.Bootstrap.main(Bootstrap.java:166)
local_managementapi_1  | Caused by: java.lang.NoClassDefFoundError: io/gravitee/gateway/handlers/api/definition/Api
local_managementapi_1  |        at java.lang.Class.getDeclaredMethods0(Native Method)
local_managementapi_1  |        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
local_managementapi_1  |        at java.lang.Class.getDeclaredMethods(Class.java:1975)
local_managementapi_1  |        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:612)
local_managementapi_1  |        at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:524)
local_managementapi_1  |        at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:510)
local_managementapi_1  |        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:243)
local_managementapi_1  |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1074)
local_managementapi_1  |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1047)
local_managementapi_1  |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
local_managementapi_1  |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
local_managementapi_1  |        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
local_managementapi_1  |        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
local_managementapi_1  |        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
local_managementapi_1  |        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
local_managementapi_1  |        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:751)
local_managementapi_1  |        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
local_managementapi_1  |        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
local_managementapi_1  |        at io.gravitee.plugin.core.internal.PluginContextFactoryImpl.create(PluginContextFactoryImpl.java:59)
local_managementapi_1  |        at io.gravitee.plugin.core.internal.PluginContextFactoryImpl.create(PluginContextFactoryImpl.java:73)
local_managementapi_1  |        at io.gravitee.management.services.plugins.ServicePluginHandler.handle(ServicePluginHandler.java:58)
local_managementapi_1  |        at io.gravitee.plugin.core.internal.PluginEventListener.lambda$null$2(PluginEventListener.java:108)
local_managementapi_1  |        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
local_managementapi_1  |        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
local_managementapi_1  |        at java.util.Iterator.forEachRemaining(Iterator.java:116)
local_managementapi_1  |        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
local_managementapi_1  |        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
local_managementapi_1  |        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
local_managementapi_1  |        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
local_managementapi_1  |        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
local_managementapi_1  |        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
local_managementapi_1  |        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
local_managementapi_1  |        at io.gravitee.plugin.core.internal.PluginEventListener.lambda$deployPlugins$3(PluginEventListener.java:106)
local_managementapi_1  |        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
local_managementapi_1  |        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
local_managementapi_1  |        at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1625)
local_managementapi_1  |        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
local_managementapi_1  |        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
local_managementapi_1  |        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
local_managementapi_1  |        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
local_managementapi_1  |        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
local_managementapi_1  |        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
local_managementapi_1  |        at io.gravitee.plugin.core.internal.PluginEventListener.deployPlugins(PluginEventListener.java:103)
local_managementapi_1  |        at io.gravitee.plugin.core.internal.PluginEventListener.deployPlugins(PluginEventListener.java:92)
local_managementapi_1  |        at io.gravitee.plugin.core.internal.PluginEventListener.onEvent(PluginEventListener.java:63)
local_managementapi_1  |        at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:44)
local_managementapi_1  |        at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:36)
local_managementapi_1  |        at io.gravitee.plugin.core.internal.PluginRegistryImpl.init(PluginRegistryImpl.java:105)
local_managementapi_1  |        at io.gravitee.plugin.core.internal.PluginRegistryImpl.doStart(PluginRegistryImpl.java:81)
local_managementapi_1  |        at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
local_managementapi_1  |        at io.gravitee.common.node.AbstractNode.doStart(AbstractNode.java:53)
local_managementapi_1  |        at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
local_managementapi_1  |        at io.gravitee.management.standalone.Container.start(Container.java:104)
local_managementapi_1  |        ... 6 more
local_managementapi_1  | Caused by: java.lang.ClassNotFoundException: io.gravitee.gateway.handlers.api.definition.Api
local_managementapi_1  |        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
local_managementapi_1  |        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
local_managementapi_1  |        at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
local_managementapi_1  |        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
local_managementapi_1  |        ... 59 more

**Comment by brasseld** [comment]
Ok, can you tell me which version of gravitee you are using ?
Also, it seems that you're running Gravitee using Docker / docker-compose, please confirm.
If I am right, please tell me how you deploy your custom plugin inside the container.

**Comment by danlange** [comment]
I am using gravitee 1.18.2.  I am using via docker-compose.
I copied the plugins from the gateway container, added my plugin, and mounted the directory as a volume.
It broke when I attempted to mount the same directory as a volume in the management-api container.
I am fixing it now...

**Comment by brasseld** [comment]
Oh, yes. Please do not share the plugins directory because plugins are unpacked to create plugin's classloader.

**Comment by danlange** [comment]
I was able to deploy it.  Now it is failing at execution time because it is unable to find the PolicyScope class:
local_gateway_1        | Caused by: java.lang.NoClassDefFoundError: Lio/gravitee/policy/transformheaders/configuration/PolicyScope;
local_gateway_1        |        at java.lang.Class.getDeclaredFields0(Native Method)
local_gateway_1        |        at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
local_gateway_1        |        at java.lang.Class.getDeclaredFields(Class.java:1916)
local_gateway_1        |        at com.fasterxml.jackson.databind.util.ClassUtil.getDeclaredFields(ClassUtil.java:937)
local_gateway_1        |        at com.fasterxml.jackson.databind.introspect.AnnotatedClass._findFields(AnnotatedClass.java:817)
local_gateway_1        |        at com.fasterxml.jackson.databind.introspect.AnnotatedClass.resolveFields(AnnotatedClass.java:583)
local_gateway_1        |        at com.fasterxml.jackson.databind.introspect.AnnotatedClass.fields(AnnotatedClass.java:353)
local_gateway_1        |        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addFields(POJOPropertiesCollector.java:368)
local_gateway_1        |        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:301)
local_gateway_1        |        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getPropertyMap(POJOPropertiesCollector.java:266)
local_gateway_1        |        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getProperties(POJOPropertiesCollector.java:158)
local_gateway_1        |        at com.fasterxml.jackson.databind.introspect.BasicBeanDescription._properties(BasicBeanDescription.java:144)
local_gateway_1        |        at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findProperties(BasicBeanDescription.java:219)
local_gateway_1        |        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._findCreatorsFromProperties(BasicDeserializerFactory.java:332)
local_gateway_1        |        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:314)
local_gateway_1        |        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:253)
local_gateway_1        |        at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:219)
local_gateway_1        |        at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:141)
local_gateway_1        |        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:403)
local_gateway_1        |        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
local_gateway_1        |        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
local_gateway_1        |        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
local_gateway_1        |        at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
local_gateway_1        |        at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:476)
local_gateway_1        |        at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3899)
local_gateway_1        |        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3794)
local_gateway_1        |        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842)
local_gateway_1        |        at io.gravitee.gateway.policy.impl.PolicyConfigurationFactoryImpl.create(PolicyConfigurationFactoryImpl.java:46)
local_gateway_1        |        at io.gravitee.gateway.policy.impl.CachedPolicyConfigurationFactory.create(CachedPolicyConfigurationFactory.java:43)
local_gateway_1        |        at io.gravitee.gateway.policy.impl.DefaultPolicyManager.create(DefaultPolicyManager.java:214)
local_gateway_1        |        at io.gravitee.gateway.policy.AbstractPolicyChainResolver.create(AbstractPolicyChainResolver.java:56)
local_gateway_1        |        at io.gravitee.gateway.handlers.api.policy.api.ApiPolicyChainResolver.lambda$calculate$1(ApiPolicyChainResolver.java:53)
local_gateway_1        |        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
local_gateway_1        |        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
local_gateway_1        |        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
local_gateway_1        |        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
local_gateway_1        |        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
local_gateway_1        |        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
local_gateway_1        |        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
local_gateway_1        |        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
local_gateway_1        |        at io.gravitee.gateway.handlers.api.policy.api.ApiPolicyChainResolver.calculate(ApiPolicyChainResolver.java:55)
local_gateway_1        |        at io.gravitee.gateway.policy.AbstractPolicyChainResolver.resolve(AbstractPolicyChainResolver.java:44)
local_gateway_1        |        at io.gravitee.gateway.policy.impl.RequestPolicyChainProcessor.execute(RequestPolicyChainProcessor.java:53)
local_gateway_1        |        at io.gravitee.gateway.policy.impl.RequestPolicyChainProcessor.lambda$execute$0(RequestPolicyChainProcessor.java:57)
local_gateway_1        |        at io.gravitee.gateway.policy.NoOpPolicyChain.doNext(NoOpPolicyChain.java:41)
local_gateway_1        |        at io.gravitee.gateway.policy.impl.RequestPolicyChainProcessor.execute(RequestPolicyChainProcessor.java:63)
local_gateway_1        |        at io.gravitee.gateway.policy.impl.RequestPolicyChainProcessor.lambda$execute$0(RequestPolicyChainProcessor.java:57)
local_gateway_1        |        at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:76)
local_gateway_1        |        at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:51)
local_gateway_1        |        at io.gravitee.policy.keyless.KeylessPolicy.onRequest(KeylessPolicy.java:39)

**Comment by danlange** [comment]
I generated my plugin using the archetypeVersion 1.2.0.  Should I have used archetypeVersion 1.3.0 with gravitee.io 1.18.2?

**Comment by brasseld** [comment]
Can you share your plugin ?

I don't understand why and from where you take this `io/gravitee/policy/transformheaders/configuration/PolicyScope`

**Comment by danlange** [comment]
[plugin-src.zip](https://github.com/gravitee-io/issues/files/2372721/plugin-src.zip)

**Comment by brasseld** [comment]
Ok, I think you have issues because of the previous deployment problem. Please try to delete the `.work` folder in `plugins` for the API gateway. Just to make sure to start again with a correct environment.

Thanks.

**Comment by danlange** [comment]
Thanks!  It is working now.
You should consider updating the documentation at: https://docs.gravitee.io/apim_policies_overview.html
There is no mention that there is a policies screen that needs to be used to configure policies.
In fact, the reason that I started developing a custom policy was that I concluded from the existing documentation that there was no way to configure the existing policies for differently for each API.  I thought that the only way to configure them was in gravitee.yml.

**Comment by brasseld** [comment]
There is a section in the documentation explaining each of the policies provided in the default bundle: https://docs.gravitee.io/apim_policies_overview.html
