### ISSUE TITLE
Socket-io Policy/Plugin

### ISSUE THREAD

**Issue by DominikSammerLocoso** [gravitee-io/issues#1502]
I would like to create a possibility to get notifications from a backend service by some sort of web socket. Therefore I am planning to create a plugin that is able to handle socket.io requests. It seems that there is no documentation how to create a plugin for gravitee.io. Can anybody tell me how I can do that? Is there some maven-archetype like for plugins? Or would it be possible to create a plugin that runs in the backend and wait for clients to connect via web socket?

**Comment by brasseld** [comment]
Hi @DominikSammerLocoso 

I don't understand all the parts of your use-case.
Do you mean that you have to create a new websocket handler to manage notifications ? But what's next, what do you want to do with these notifications ?

**Comment by DominikSammerLocoso** [comment]
> Do you mean that you have to create a new websocket handler to manage notifications ? But what's next, what do you want to do with these notifications ?
I have clients that are interested in changes done by a backend service. So if the backend service did some work it will send out a notification message. Since backend service should not send messages directly to the clients (for security reasons) it would be fantastic to route these notifications through the gateway to the client. That is why I need some sort of possibility to connect to the gateway via web socket technology.
For example you have a list of people that is managed by a backend service. Getting these people is possible with a rest interface. But as a client you are interested in changes done in your list of people. If somebody is changing a person a notification about that change should be sent to everybody. 

On the client side we have a web client that will connect to this web socket using socket.io. To handle socket.io connections I found a java library that can be found under https://github.com/mrniko/netty-socketio. This framework would be able to do alle the work neccessary. To include that library in my gateway I need some plugin or whatever that implements that library.

**Comment by brasseld** [comment]
Ok so in that case, you can create a new service for the gateway.

There is a maven archetype for service:

https://docs.gravitee.io/apim_devguide_policies.html#policy_skeleton_generation

And replace policy with service.

**Comment by DominikSammerLocoso** [comment]
Thanks! That helped a lot. The created zip can be moved into the plugins folder and by doing so it will be deployed, am I correct?

**Comment by brasseld** [comment]
You're absolutely right!

**Comment by DominikSammerLocoso** [comment]
Thanks!
