### ISSUE TITLE
json-schema-generator-maven-plugin crashes on recursive data structure

### ISSUE THREAD

**Issue by sylvaingaudan** [gravitee-io/issues#1504]
When generating a JSON Schema based on a Java class that has a recursive data straucture, the maven json-schema-generator-maven-plugin crashes with a java.lang.StackOverflowError

### Expected Behavior

The plugin generates one schema for the class with a recursive reference inside the definition

### Current Behavior

The json-schema-generator-maven-plugin crashes because it follows recursively the structure. It should check whether the class was already visited or not.

### Possible Solution

It should check whether the class was already visited or not.

### Steps to Reproduce (for bugs)

Apply the plugin on
```java
package my.package;

import java.util.List;

public class Node {
    public String name;
    public List<Node> kids;
}
```
With the plugin:
```xml

        <plugin>
            <groupId>io.gravitee.maven.plugins</groupId>
            <artifactId>json-schema-generator-maven-plugin</artifactId>
            <version>1.3.0</version>
            <executions>
                <execution>
                    <phase>prepare-package</phase>
                    <goals>
                        <goal>generate-json-schemas</goal>
                    </goals>
                    <configuration>
                        <includes>
                            <include>my/package/Node.class</include>
                        </includes>
                        <buildDirectory>${project.build.outputDirectory}</buildDirectory>
                        <outputDirectory>${project.build.outputDirectory}/schemas</outputDirectory>
                    </configuration>
                </execution>
            </executions>
        </plugin>
```

### Context

I am trying to generate a JSON Schema for a recursive data structure. 

### Your Environment

Java 1.8

```xml
            <groupId>io.gravitee.maven.plugins</groupId>
            <artifactId>json-schema-generator-maven-plugin</artifactId>
            <version>1.3.0</version>
```

**Comment by NicolasGeraud** [comment]
hi @sylvaingaudan 
Do you want to provide a fix ?

**Comment by sylvaingaudan** [comment]
Can't soon. Working hard on our OS project. Sorry.

**Comment by gaetanmaisse** [comment]
Closing the issue as this project has moved to https://github.com/gravitee-io-community/json-schema-generator-maven-plugin
