### ISSUE TITLE
Associate a client_id from a 3rd party automatically

### ISSUE THREAD

**Issue by paulossjunior** [gravitee-io/issues#1506]
#### Improvement.
When we create a new application it is necessary to inform the client_id. This valeu could be informed by 3rd party automatically. For instance, I have a Identity Server (.net) and I would like to create a new application in Gravitee and "auto-magically" receive the client_id and secret_id from my Identity Server. 

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Version used:
* Browser Name and version:
* Operating System and version:

**Comment by brasseld** [comment]
Be careful @paulossjunior 
I have a copyright on the word "auto-magically" ;)

**Comment by brasseld** [comment]
An issue has been created.

See https://github.com/gravitee-io/issues/issues/1580

**Comment by paulossjunior** [comment]
Let's share The copyright? :)

Em Qua, 19 de set de 2018 11:12, Brassely David <notifications@github.com>
escreveu:
