### ISSUE TITLE
Repeated calls to management API 

### ISSUE THREAD

**Issue by girishmanwani** [gravitee-io/issues#1507]
I have the management api url http://localhost:8083/management/ wrapped behind the gateway so that it is accessible from the url http://localhost:8082/mgmtwrapper/

I have a microservice(also wrapped behind the gateway) that makes calls to http://localhost:8082/mgmtwrapper/

The first call after I start my microservice( running on tomcat,and registered as a gateway url) is successful - but subsequent calls fail with 500 Internal Server error and the following response

{
    "timestamp": 1537512816129,
    "status": 500,
    "error": "Internal Server Error",
    "exception": "org.springframework.web.client.HttpClientErrorException",
    "message": "400 Bad Request",
    "path": "/gravitee-api-service/publishApi"
}

What can I do to avoid this.
My calls to the Management API for programmatically creating the API.

**Comment by brasseld** [comment]
It is a response from your own microservice, and this is not relative to gravite.
