### ISSUE TITLE
Not all Gravitee repositories have issues enabled

### ISSUE THREAD

**Issue by tobiasvl** [gravitee-io/issues#1509]
### Expected Behavior
The `README.md` in this repository asys the following:

> If the issue is specific to a repository please use the GitHub issues in that repository instead.

Therefore, I would expect the other gravitee-io repositories to accept issues. Several of them do not.

### Current Behavior

The following repositories do not have issues enabled:

* gravitee-io/gravitee-gateway
* gravitee-io/gravitee-management-rest-api
* gravitee-io/gravitee-management-webui

The remaining two do have issues enabled:

* gravitee-io/gravitee-docs
* gravitee-io/graviteeio-access-management

### Possible Solution

Two possible solutions:

* Change the `README.md` to say that issues pertaining to repositories that do not have issues enabled, are welcome in this repository.
* Enable issues on all repositories.

### Steps to Reproduce (for bugs)

1. Go to https://github.com/gravitee-io/issues and read that you should go to the specific repositories to open issues there
2. Go to a specific repo like for example https://github.com/gravitee-io/gravitee-management-webui to open an issue there
3. See that there is no "Issues" tab or other way to open issues

### Context

I wanted to open an issue for the Management web UI, but I'm unsure where to open it. (I will probably open it in this repo.)

**Comment by brasseld** [comment]
Hi @tobiasvl 

Good point, we will update README to specify that issues must be created from the `issues`repository as explained in its specific README file: https://github.com/gravitee-io/issues/blob/master/README.md
