### ISSUE TITLE
Some strings in the Management web UI are shown as placeholders

### ISSUE THREAD

**Issue by tobiasvl** [gravitee-io/issues#1510]
### Expected Behavior

All strings in the Management web UI should be translated and not be displayed as placeholder strings.

### Current Behavior

Some strings are displayed erroneously as placeholders. An example is the "Subscribe" page:

![image](https://user-images.githubusercontent.com/80824/45878928-1a198880-bda3-11e8-9552-55f41deaea17.png)

The HTML element for the H1 title looks like this in the source:

    <h1 translate="api.subscription.step1.title" class="ng-scope">api.subscription.step1.title</h1>

This occurs in our setup of both Gravitee 1.13.3 (pictured above) and 1.18.3 (which we just tested to see if it was fixed).

### Steps to Reproduce (for bugs)

1. Go to API Gallery
2. Select an API
3. Click "Subscribe"
4. Select a plan

### Context

Looks like some localization gone awry?

I have no idea if this is a Gravitee bug or an error in our configuration.

### Your Environment

* Version used: 1.13.3 / 1.18.3
* Browser Name and version: Chrome 68.0.3440.106
* Operating System and version: Windows 10 / Fedora 28

**Comment by NicolasGeraud** [comment]
hi @tobiasvl ,
what are the languages configured in your browser ?

**Comment by tobiasvl** [comment]
@NicolasGeraud Good question. My main browser language was Norwegian. I just changed it to English, though, and experience the same issues. (Other people on my team, with different browsers and probably different languages configured in them, are also experiencing the same issues.)

**Comment by NicolasGeraud** [comment]
same behavior on https://demo.gravitee.io ?

**Comment by NicolasGeraud** [comment]
because I've just tried on the demo with chrome and only one language configured (norvégien bokmål) and the fallback to English works well

**Comment by tobiasvl** [comment]
The demo works fine for me. I assume there's something in our setup then... But I have no idea what could cause the fallback to not work (or fall back to the placeholder strings). Are there any configuration options here I'm not aware of?

**Comment by tobiasvl** [comment]
I'm not seeing any request for `nb.json`, so maybe it's not using my browser language after all.

`en.json` is successful though.

![image](https://user-images.githubusercontent.com/80824/45881821-995f8a00-bdac-11e8-963b-79e9c14c7db8.png)

**Comment by NicolasGeraud** [comment]
i just try to connect to https://api.uio.no/ with a chrome with only norvegian language and my devtools show this : 

<img width="415" alt="capture d ecran 2018-09-21 14 48 30" src="https://user-images.githubusercontent.com/1028285/45882110-6a95e380-bdad-11e8-8f5b-938cd9c47f97.png">

can you share your browser languages ?

**Comment by NicolasGeraud** [comment]
ok, as @brasseld told you, you have probably overriden the translations.
Compare your en.json (https://api.uio.no/portal/i18n/en.json) and the official one in release 1.13.3 (https://raw.githubusercontent.com/gravitee-io/gravitee-management-webui/1.13.3/src/portal/i18n/en.json)

**Comment by tobiasvl** [comment]
All right, perfect! Thanks a lot, I'll look into what has happened here.
