### ISSUE TITLE
[management-ui] Failed CSS loader at yarn run serve:demo with Windows 7

### ISSUE THREAD

**Issue by SergeiP87** [gravitee-io/issues#1512]
### Expected Behavior
Expected behavior would be yarn run serve:demo running without erros and displaying the local URL as in 'localhost:3000' .

### Current Behavior
Executing yarn run serve:demo throws the following error.

```
ERROR in ./src/index.scss 3:0
Module parse failed: Unexpected character '@' (3:0)
You may need an appropriate loader to handle this file type.
| $backgroundColor: rgb(45, 50, 62);
|
> @import '~angular-loading-bar/build/loading-bar.css';
| @import '~angular-material/modules/scss/angular-material.scss';
| @import '~angular-material-data-table/dist/md-data-table.css';
 @ ./src/index.ts 23:0-23

```
`
npm install --global --production windows-build-tools ` has been executed as described in the readme before running `yarn install`
### Steps to Reproduce (for bugs)
1. Clone https://github.com/gravitee-io/gravitee-management-webui.git
2. Install http://nodejs.org[nodejs], it comes with http://npmjs.org[npm]
    Install https://yarnpkg.com[yarn]
3. run `npm install --global --production windows-build-tools`
4. run `yarn install`
5. run `yarn run serve:demo`

### Your Environment
* Version used: WebUI 1.19
* Operating System and version: Windows 7 64Bit

**Comment by NicolasGeraud** [comment]
hi @SergeiP87 ,
what is your yarn/node/npm version ?

**Comment by SergeiP87** [comment]
Hi,

Yarn version is 1.9.4
Node version is 10.10.0
NPM version is 6.4.1

I have also found a workaround to get it working by deleting the following part of the code from conf/webpack.conf.js

```
include: [
          path.resolve(__dirname, '..') + '/src/index.scss'
        ]

```

**Comment by netfreeperson** [comment]
hasn't the problem been solved yet?

**Comment by brasseld** [comment]
I don't know, did you check it ?

**Comment by brasseld** [comment]
What is the status of this issue?

**Comment by quangvm97** [comment]
> Hi,
> 
> Yarn version is 1.9.4
> Node version is 10.10.0
> NPM version is 6.4.1
> 
> I have also found a workaround to get it working by deleting the following part of the code from conf/webpack.conf.js
> 
> ```
> include: [
>           path.resolve(__dirname, '..') + '/src/index.scss'
>         ]
> ```

Thank you so much, it's work for me
