### ISSUE TITLE
[gateway] Gateway select first endpoint for dynamic routing

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#1515]
When I'm using dynamic routing and set an undefined endpoint in the target URI, I'm always redirected to the first endpoint.

The gateway must return a 5xx status code (502 / 503).

**Comment by vdusauto** [comment]
This was considered as a feature by some companies. Make sure the error code is explicit enough to allow debugging. Please also add it explicitly as a breaking change, even if it's a fix.
