### ISSUE TITLE
[management-api] Use login of a third party oauth2 server

### ISSUE THREAD

**Issue by rlvillacarlos** [gravitee-io/issues#1516]
Hi I would like to know how to make gravitee use the existing login page of an existing third party oauth2 server. I cannot seem to find an example of it in the documentation.

What I want to be able to do is to use the oauth2 login page for SSO.

**Comment by brasseld** [comment]
Hi @rlvillacarlos 

Here is an example between Gravitee.io APIM and Gravitee.io AM:

* Management-API configuration:

https://github.com/gravitee-io/gravitee-docker/blob/master/platform/docker-compose.yml#L93

* UI configuration:

https://github.com/gravitee-io/gravitee-docker/blob/master/platform/gio_apim/portal/constants.json

**Comment by brasseld** [comment]
Hi @rlvillacarlos 

Is this ok ?
