### ISSUE TITLE
 Property [localLoginDisabled] is not recognized as a valid property

### ISSUE THREAD

**Issue by jotamorais** [gravitee-io/issues#1518]
### Expected Behavior
Hiting the Save button should save changes without issues.

### Current Behavior
When trying to save Portal Settings on the UI (even when nothing has been changed in any field) an error notification pops up stating:

`Property [localLoginDisabled] is not recognized as a valid property`

### Possible Solution
Aparently Angular binding is not correct.

### Steps to Reproduce (for bugs)
![gravitee_settings_issues](https://user-images.githubusercontent.com/5201388/46120607-0bcdd100-c1d6-11e8-8570-65a8708678e7.gif)

![image](https://user-images.githubusercontent.com/5201388/46120638-2142fb00-c1d6-11e8-87f2-b9d163578029.png)

### Context
Experienced the issue when trying to save Portal Settings on the UI (even when nothing has been changed in any field). It's impacting any operation in the Portal Settings as changes are not saved as one would expect.

### Your Environment

* Version used: 
Gravitee (Gateway, API and UI) 1.19.3
MongoDB 3.6
Elasticsearch 6.4.0
* Browser Name and version: 
Chrome Version 69.0.3497.100 (Official Build) (32-bit) 
Firefox Quantum 60.2.0esr (64-bit)
* Operating System and version:
Windows 10 Pro
CentOS 7

**Comment by NicolasGeraud** [comment]
hi,

I just try on a fresh 1.19.3 and i'm not able to reproduce this issue.
Can you share the content of the POST ?

**Comment by brasseld** [comment]
Hello @jotamorais 

I did not see the PR you're speaking about.

Did you create it ?

**Comment by jotamorais** [comment]
Sorry @brasseld,
I got distracted by other priorities. I just [submitted a PR](https://github.com/gravitee-io/gravitee-kubernetes/pull/2).
I will shortly submit another one with samples on how to setup Gravitee on GKE (Google Kubernetes Engine).
After that, I will submit a third one on how to setup on Amazon's EKS.

**Comment by brasseld** [comment]
No problem @jotamorais, don't be sorry!

We already have someone who is writing a blog post for AKS (Azure).
Perhaps we may have three different blog posts for each platform ?

**Comment by jotamorais** [comment]
Yes, I'm writing a [Medium](https://medium.com/) post to be the companion tutorial for the GKE Sample.
Do you want me to share the draft and you post in [https://medium.com/graviteeio](https://medium.com/graviteeio)?

**Comment by brasseld** [comment]
I can add you as a writer on graviteeio if you want ?

**Comment by jotamorais** [comment]
Even better :-)
Thanks!
