### ISSUE TITLE
Connecting Plans to policies/auth-data

### ISSUE THREAD

**Issue by ejerpseth** [gravitee-io/issues#1521]
This is a request for new functionality.

We want to be able to connect policies to plans
### Current Behavior
Auth-data can only be assigned to policies, not plans.

### Possible Solution
One way we see how this can be done is by connecting policies to plan instead of url-tree.
A middle way out would be to be able to connect only auth-info to plans, and not all policies. As plans already offer "Propagate API Key to upstream API", there seems to exist some forwarding functionality.

### Context
Today our data owners have to publish their APIs several time to distinguish which application that has consumed or delivered data. Typically IT-Security demands logs from the API that shows who the consumer are (they do not want to combine logs from API Manager and API), and the API belongs to a SaaS a service in the cloud, so we can not add columns to the logs. 

### Your Environment
Tested most major versions from 1.13.x up to 1.19

**Comment by brasseld** [comment]
Hi @ejerpseth 

Even if the UI doest not reflect that point, the gateway is executing policies in 3 steps:
1) Security chain: apply an 'auth' policy such as api-key / jwt / oauth2
2) Plan chain: apply policies such as rate-limit / quota / resource-filtering / (it can be others)
3) Api chain: apply policies you have defined from the policy / url-tree view

My question is:
What would you like to add in the plan chain ? What would be the purpose of the policies added to the chain ? Is it policies provided by Gravitee or your own ?

**Comment by ejerpseth** [comment]
We use `Transform Header`-policies for basic auth from Gravitee to API. Connecting individual API-system-users to Plans would make it possible for us to us different API-system-users and then better authorization and accountability in API logs. Today consumers are getting data from some, but not all, url-trees, and we cannot read from the API log which consumer is getting what data.

So if auth-data optionally could be connected to plan instead of policy, that would solve the “all plans/consumers looks the same, seen from the API”-issue.

**Comment by brasseld** [comment]
In that case, you have two solutions:

1) Wait until we are allowing API publishers to define policy at the plan level (not an high priority for us).
2) Call the management-api by your own to include a new policy in the plan's definition (look at the path property in the below definition):


```json
...
   {
      "id": "ab8945e9-42c1-4a67-8945-e942c1aa673b",
      "name": "Bronze Plans",
      "description": "Bronze",
      "validation": "AUTO",
      "security": "API_KEY",
      "securityDefinition": "{\"propagateApiKey\":false}",
      "type": "API",
      "status": "PUBLISHED",
      "apis": [
        "4e0db366-f772-4489-8db3-66f772b48989"
      ],
      "order": 1,
      "characteristics": [
        "read-only",
        "5req/s",
        "1000/month"
      ],
      "created_at": 1479627041690,
      "updated_at": 1521801415823,
      "published_at": 1479627047222,
      "paths": {
        "/": [
          {
            "methods": [
              "GET",
              "POST",
              "PUT",
              "DELETE",
              "HEAD",
              "PATCH",
              "OPTIONS",
              "TRACE",
              "CONNECT"
            ],
            "rate-limit": {
              "async": false,
              "addHeaders": false,
              "rate": {
                "periodTime": 1,
                "periodTimeUnit": "SECONDS",
                "limit": 5
              }
            },
            "enabled": true
          },
          {
            "methods": [
              "GET",
              "POST",
              "PUT",
              "DELETE",
              "HEAD",
              "PATCH",
              "OPTIONS",
              "TRACE",
              "CONNECT"
            ],
            "quota": {
              "quota": {
                "limit": 1000,
                "periodTime": 1,
                "periodTimeUnit": "HOURS"
              },
              "addHeaders": true,
              "async": false
            },
            "enabled": true
          },
          {
            "methods": [
              "GET",
              "POST",
              "PUT",
              "DELETE",
              "HEAD",
              "PATCH",
              "OPTIONS",
              "TRACE",
              "CONNECT"
            ],
            "resource-filtering": {
              "whitelist": [
                {
                  "pattern": "/**",
                  "methods": [
                    "GET"
                  ]
                }
              ],
              "blacklist": []
            },
            "enabled": true
          }
        ]
      },
      "excluded_groups": []
    }
...
```

**Comment by brasseld** [comment]
Defining policies at the plan level is available since Gravitee.io APIM 1.23.x
