### ISSUE TITLE
Caching JWTs on behalf of User

### ISSUE THREAD

**Issue by ejerpseth** [gravitee-io/issues#1522]
This is request for new functionality

Unless API are published several times, the APIs logs (using default logformat) do not distinguish the consuming services. Gravitee handling JWTs on behalf of user (user never receives JWT) will solve the problem.

### Expected Behavior
We have found no function in Gravitee for handling the JWT on behalf of the user. 

### Current Behavior
As Gravitee cannot handle the JWT on behalf of the consuming system, the consumer must receive the JWT-token. When the client helds the JWT it is possible for the consumer to bypass Gravitee and ask for more information than intended by plan. 

### Possible Solution
A plug-in that can map JWT to Gravitee api-key

### Context
Some of our APIs use JWTs for authorization. Typically first a /token endpoint is pulled with user/pass and a JWT is returned. Unless we publish the API many times, we have to use the same user/pass for all consuming services. If the API is a cloud-service,we cannot lock it down with firewalls or other (which is ultimately a bad solution anyway)

**Comment by brasseld** [comment]
Hi @ejerpseth 

I'm not sure that being able to map a JWT to an api-key will solve your issue.
I have an additional question:

Instead of defining api-key plan, why not defining JWT plan (if you want to call APIs with a JWT token ?)

**Comment by ejerpseth** [comment]
Interesting. I was not aware that you could validate JWT on a plan-only level. I thought we needed to define an Oauth2.0 resource to do that (still working on that).
If the API itself can validate JWTs, are there any way to enforce use of Gravitee except use of firewall?

**Comment by brasseld** [comment]
There are many way to enforce usage of gravitee.

1) Use a firewall (not in your case as far as I understand your previous comment)
2) Client authentication using SSL certificates
3) Don't use gateway :-P

**Comment by brasseld** [comment]
Hi @ejerpseth 

May I close this issue?

**Comment by ejerpseth** [comment]
You may close it for now. We will contact you again if we still want this feature and got a money for funding.
