### ISSUE TITLE
[management-ui] CORS cant save customer Access-Control-Allow-Headers,for excample X-Gravitee-Api-Key.

### ISSUE THREAD

**Issue by catchUheart** [gravitee-io/issues#1524]
### Expected Behavior

how can i save the X-Gravitee-Api-Key in Access-Control-Allow-Headers.

### Your Environment

* Version used:1.19.3
* Browser Name and version:
* Operating System and version:win10

**Comment by brasseld** [comment]
Hi @catchUheart 

I just had a try and was able to reproduce.

I think this is because you did not enable CORS at the top of page.
One CORS is enabled, you can define and save all the form's fields.

I keep this issue to disabled fields when CORS is disabled.

**Comment by catchUheart** [comment]
The CORS is in active.
In Access-Control-Allow-Headers,it seems that can only save the headers which is in the drop down list,
like Content-type,Cache-control and so on.But,cant save the X-Gravitee-Api-Key which is not in the drop down list.

**Comment by brasseld** [comment]
Ok, I think this is dure to the material design.

When you type X-Gravitee-Api-Key, you must have to press enter key to take care of the new header.

Please let us know.

Regards,

**Comment by catchUheart** [comment]
OK,it comes to work.
Thank you!

**Comment by brasseld** [comment]
Thanks for your feedback @catchUheart

So, IMHO, user should not be able to define CORS if this latest is inactive.
