### ISSUE TITLE
[policy] [request-content-limit] Request Content Limit Policy does not support transfer-encoding

### ISSUE THREAD

**Issue by briankrug** [gravitee-io/issues#1547]
The Request Content Limit Policy requires the Content-Length header to be present in the request. There are two scenarios where a request will fail but should not:
1. If the request uses transfer-encoding (as in the case when content is compressed or chunked)
2. If the request uses a method that typically does not have a body (such as GET)

### Possible Solution
The Request Content Limit Policy should handle requests that use transfer-encoding. More specifically, in RequestContentLimitPolicy, the onRequest() method should be altered to not throw an Exception when the Content-Length header is present and it a method annotated with @OnRequestContent should be added which checked for the transfer-encoding header and wraps the ReadWriteStream and throws and exception when the content limit is reached.

### Context
In its current implementation, not all client requests are supported

### Your Environment
* Version used: Gravitee 1.18.1

**Comment by brasseld** [comment]
Hi @briankrug 

Yes, we are already aware of this issue.

I agree with the first point but not with the second. As per the [RFC](https://tools.ietf.org/html/rfc7231#section-4.3.1):
```
A payload within a GET request message has no defined semantics; sending a payload body on a GET request might cause some existing implementations to reject the request.
```
In other words, it's not forbidden, but it's undefined behavior and should be avoided.

**Comment by jahlborn** [comment]
I agree that the rfc discourages a body for GET, but i feel like this is something that happens in the world today (whether or not we agree with it).  by not supporting it, you exclude gravitee from being used with apis which use it.

**Comment by brasseld** [comment]
I agree. And that's the reason I said that it should be the responsibility of the API Owner to define the policy per verbs for such case.

I have in mind the case of Elasticsearch where you can search for documents by posting a query using a GET...

**Comment by briankrug** [comment]
My concern is if a client decides to send a large payload with a GET request (regardless of whether the backend API supports it or not), I still want to be able to limit the size of that payload at the Gateway to protected the Gateway and the backend from content that is too big. If the policy can't handle a request without a Content-Length, then I can't put it on GET requests and thus protect against large payloads.

**Comment by brasseld** [comment]
And I fully understand your concern, I will take care of this issue.
Chunk transfer encoding is already supported by the policy... in my laptop... I did not take the time to push it in repository.
