### ISSUE TITLE
[management] add options when created apis from swagger

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#1566]
- create paths must be optional
- create a swagger page must be optional

**Comment by brasseld** [comment]
We can also create path-mapping for analytics

**Comment by gs11** [comment]
As discussed on Gitter...
I wish for functionality to update an API by re-importing a Swagger/OpenAPI-spec. The UI Import button is there but currently causes an "[object Object]" error message in the UI and an NPE in the Management API.

Expected to happen upon re-import:
Perform delta upgrade to remove/add operations based on previous API specification and new one.

This way we wouldn't lose Policies, Plans, Config, Subscriptions, API Keys etc upgrading an API.

**Comment by NicolasGeraud** [comment]
@gs11 I've created a dedicated issue to your request : #1777
