### ISSUE TITLE
Align root log level of both Management API and gateway component

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#1574]
The root log level is different between both components, we should provide coherency

**Comment by brasseld** [comment]
The biggest problem is about the criticality and the impact of the logs on the component's performances.

From the gateway POV, it doesn't make sense to have a fine log level and logging may have an impact on request handling.

From the management-api POV, it may make sense to have a fine log level.

**Comment by aelamrani** [comment]
Agreed with that point. 

But maybe we should adopt a different approach => override the packages which should be logged as info

The main problem today is that for a same plugin deployed on both components, we may have different logging, so it can be confusing.
