### ISSUE TITLE
[gateway] Multi-tenant management

### ISSUE THREAD

**Issue by lusoalex** [gravitee-io/issues#158]
Hello,

**Context :** 
We expect to have a unique entry point (api.myCompany.com) pointing on all our datacenters (Europe, Asia, India, etc...). When an application do an API call, the user is geolocated and then redirect to the nearest gateway. 

**Need :**
Now if i have an API with exactly the same data available in europe, asia, india... 

Ex : products catalog is exactly the same in each country
- https://api.myCompany.eu/api/v1/products
- https://api.myCompany.in/api/v1/products
- https://api.myCompany.cn/api/v1/products

I'd like redirect the API call to the local API address. 
To do that, i need to "tag" the gateway with an tenant id, and then be able to access to this tenant in the dynamic policy rule.

That way, if the user is in geolcated in india : https://api.myCompany.com/api/v1/products will be redirected to the indian gateway, and i expect the indian gateway to redirected the api call to  https://api.myCompany.in/api/v1/products.

Could you manage this tenant id in a futur release?
Regards,
Alexandre.

**Comment by brasseld** [comment]
It can be implemented easily thanks to issue gravitee-io/issues#242

**Comment by lusoalex** [comment]
Hello,

For the implementation, we will need to : 

1. add the tenant_id into the gateway settings & set it into the instance payload.
2. add a tenant_id field into the endpoints declaration (on the web UI, gateway settings)
3. add a checkbox "enable tenants" into the web UI (gateway settings) 
4. Into the gateway, if tenants are enabled, then use the backend target url linked to the gateway tenants.

As for the sharding tags or groups, it would be great to have a dedicated menu to set the tenant list. That way we will avoid entry errors when adding a new target endpoints.

It would be great also to manage this tenant id as a filter on the main dashboard & the API analytics.

Do you agree?
Regards,
Alexandre.

**Comment by brasseld** [comment]
Hello @lusoalex 

1. What about loadbalancing if there are multiple endpoints for the same tenant id ?
2. Tenant can be determined by the tenant id defined in the gateway settings but can also be determined by checking the ip of the incoming request. Wdyt ?
3. For analytics, it means that we have to store the tenant used for each request.

Regards,

**Comment by lusoalex** [comment]
Hello @brasseld 

1. If multiple endpoints are set to same tenant and tenant is enabled, then use the loadbalancing rules on them.
2. Tenant should be determined only by the gateway settings. Your request will arrive to the gateway following your load balancing rules (and sharding tags).
3. Yes, for each request, it would be great to add the tenant information in order to be able to make some analytics on. Ex, we may see that all the errors for one API are coming from the same tenant (that may be linked to a firewall problem).

Regards,
