### ISSUE TITLE
[management] Add support for Dynamic Client Registration

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#1580]
The purpose of this issue is to let the management-api invoke an OIDC endpoint to create OIDC client when creating a new application.

Application must support new field for redirect_uris (mandatory for DCR).

**Comment by n2ygk** [comment]
I imagine this is already well understood, but, in case it helps, here is what I would need in order to make this feature work with my OAuth2/OIDC AS (PingFederate 9.1 specifically but I assume any standard  OIDC AS would work):
- AS: Enable Dynamic Client Registration:
  - Configure the AS to require a Bearer Token with a specific scope (e.g. `client_creator`) for "dynamic provisioning clients" that are permitted to do so.
- AS: Provision client credentials for the APIM provisioning client with restricted scope (`client_creator`)
- APIM: use the client_id and client_secret from above with the Client Credentials flow to get an Access Token with that specific scope (`client_creator`).
- APIM: POST to the OIDC `registration_endpoint` with header "Authorization: Bearer _access_token_" with a body something like this:
```json
{
  "redirect_uris": [
    "http://localhost:8002",
  ],
  "client_name": "dynamic_client_3",
  "response_types": ["code", "token", "id_token"],
  "token_endpoint_auth_method": "client_secret_basic",
  "scope":"<list of restricted scopes>",
  "grant_types":[
    "authorization_code",
    "implicit"
  ],
  "logo_uri": "https://www.columbia.edu/content/themes/custom/columbia/favicon-crown.png"
}
```
and get a response like this:
```
{
    "client_id": "dc-vlq6aFt77gXd6MIpKSgkTH",
    "client_name": "dynamic_client_3",
    "redirect_uris": [
        "http://localhost:8002"
    ],
    "token_endpoint_auth_method": "client_secret_basic",
    "grant_types": [
        "implicit",
        "authorization_code"
    ],
    "client_secret": "7UehninDtpifn1sID4OyMz",
    "client_secret_expires_at": 0,
    "logo_uri": "https://www.columbia.edu/content/themes/custom/columbia/favicon-crown.png",
    "scope": "<list of restricted scopes>",
    "response_types": [
        "code",
        "token",
        "id_token"
    ],
    "validate_using_all_eligible_atms": false,
    "refresh_token_rolling_policy": "server_default",
    "persistent_grant_expiration_type": "server_default",
    "grant_access_session_revocation_api": false
}
```

Notably, you cannot set the `client_id` or `client_secret`: they are automatically generated and associate with the `client_name`. And, those client names are not unique, so it would be up to APIM to keep track of the names. OR, leave it out; if `client_name` is omitted from the request, then it is system-generated and is the same as `client_id`.

Also, just to complicate things, this particular AS allows provisioning of multiple dynamic provisioning clients that can implement various policies, such as limiting which restricted scopes might be allowed for clients that they create. I don't think I would need that level of complication just yet;-)

Please let me know how I can help implement this feature.

**Comment by n2ygk** [comment]
PS: It would be really helpful for APIM to (optionally?) automatically add the `redirect_uris` that it needs for Swagger UI, etc. I've found through experimentation that these are:
`GRAVITEE_APIM/swagger-oauth2-redirect.html` for swagger "Try it out" (e.g. http://localhost:8002/swagger-oauth2-redirect.html` when running docker local).

**Comment by brasseld** [comment]
Hi @n2ygk 

This is exactly were we are going.

I've just one concern about the response payload: according to the [specification ](https://openid.net/specs/openid-connect-registration-1_0.html#RegistrationResponse) response may contain some additional properties:
- registration_access_token
- registration_client_uri

But you didn't have such properties using PingFederate 9.1, or perhaps you remove some parts of the response?

> I imagine this is already well understood, but, in case it helps, here is what I would need in order to make this feature work with my OAuth2/OIDC AS (PingFederate 9.1 specifically but I assume any standard OIDC AS would work):
> 
> * AS: Enable Dynamic Client Registration:
>   
>   * Configure the AS to require a Bearer Token with a specific scope (e.g. `client_creator`) for "dynamic provisioning clients" that are permitted to do so.
> * AS: Provision client credentials for the APIM provisioning client with restricted scope (`client_creator`)
> * APIM: use the client_id and client_secret from above with the Client Credentials flow to get an Access Token with that specific scope (`client_creator`).
> * APIM: POST to the OIDC `registration_endpoint` with header "Authorization: Bearer _access_token_" with a body something like this:
> 
> ```json
> {
>   "redirect_uris": [
>     "http://localhost:8002",
>   ],
>   "client_name": "dynamic_client_3",
>   "response_types": ["code", "token", "id_token"],
>   "token_endpoint_auth_method": "client_secret_basic",
>   "scope":"<list of restricted scopes>",
>   "grant_types":[
>     "authorization_code",
>     "implicit"
>   ],
>   "logo_uri": "https://www.columbia.edu/content/themes/custom/columbia/favicon-crown.png"
> }
> ```
> 
> and get a response like this:
> 
> ```
> {
>     "client_id": "dc-vlq6aFt77gXd6MIpKSgkTH",
>     "client_name": "dynamic_client_3",
>     "redirect_uris": [
>         "http://localhost:8002"
>     ],
>     "token_endpoint_auth_method": "client_secret_basic",
>     "grant_types": [
>         "implicit",
>         "authorization_code"
>     ],
>     "client_secret": "7UehninDtpifn1sID4OyMz",
>     "client_secret_expires_at": 0,
>     "logo_uri": "https://www.columbia.edu/content/themes/custom/columbia/favicon-crown.png",
>     "scope": "<list of restricted scopes>",
>     "response_types": [
>         "code",
>         "token",
>         "id_token"
>     ],
>     "validate_using_all_eligible_atms": false,
>     "refresh_token_rolling_policy": "server_default",
>     "persistent_grant_expiration_type": "server_default",
>     "grant_access_session_revocation_api": false
> }
> ```
> Notably, you cannot set the `client_id` or `client_secret`: they are automatically generated and associate with the `client_name`. And, those client names are not unique, so it would be up to APIM to keep track of the names. OR, leave it out; if `client_name` is omitted from the request, then it is system-generated and is the same as `client_id`.
> 
> Also, just to complicate things, this particular AS allows provisioning of multiple dynamic provisioning clients that can implement various policies, such as limiting which restricted scopes might be allowed for clients that they create. I don't think I would need that level of complication just yet;-)
> 
> Please let me know how I can help implement this feature.

**Comment by brasseld** [comment]
So, without the registration_access_token and registration_client_uri, it means that the application may not be updatable from APIM.

**Comment by n2ygk** [comment]
@brasseld I guess that's also in [RFC 7592](https://tools.ietf.org/html/rfc7592). [RFC 7591](https://tools.ietf.org/html/rfc7591) only specifies dynamic client **creation** and it appears they haven't caught up with RFC7592 yet.  They have a proprietary [API](https://documentation.pingidentity.com/pingfederate/pf92/index.shtml#adminGuide/usingTheApiInteractiveDocumentation.html) that predates OIDC and supports POST and PUT for client registrations. It's what I've been using so far.

I can submit a support ticket and ask if and when they plan to support RFC 7592. Unfortunately the RFC status is Experimental... They tend to follow the Standards Track RFC's.

Perhaps a hook can be provided for proprietary endpoints?

Worst case, each update can POST a new dynamic client and throw the old one away... (ugh.)

I would be OK with switching to an OSS OIDC provider as well, but PF is what we have in production right now.

**Comment by lusoalex** [comment]
> OIDC provider as well, but PF is what we ha

Hello n2ygk,

The [specification](https://openid.net/specs/openid-connect-registration-1_0.html#AccessURL) says that client should not construct/form the url and use the **_registration_client_uri_**.  
But in the meantime they _recommend that this endpoint URL should be formed through the use of a server-constructed URL string which combines the Client Registration Endpoint's URL and the issued Client ID for this Client_. So you may use the registration_endpoint from oidc discovery.

Gravitee AM offer PATCH (as well as a PUT endpoint in a coming release), which take the same payload than the original POST /register endpoint. Unfortunately you still need to consume these endpoint with the **registration_access_token**.

PingFederate is in the certified list, they should manage it...
https://openid.net/certification/#OPs

Regards,
Alexandre.
