### ISSUE TITLE
[gateway] OpenTracing support

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#1581]
https://opentracing.io/

**Comment by Frintrop** [comment]
.. is support integrated?

**Comment by macwitte** [comment]
Any news or ideas here? Would it be an idea to integrate it as a policy which adds opentracing support?

**Comment by brasseld** [comment]
We were looking for Vert.x 4 to be release which is available since last December.

We are planning to work on adding opentracing support for 3.10 (june)

**Comment by fmercier-almerys** [comment]
Hi recently Opentracing merge to Opentelemetry do you keep your target on opentracing or do you think to jump directly on the Opentelemetry standard ?

**Comment by macwitte** [comment]
Hi, currently we are using Opentracing. Because OpenTelemetry is new, we have no experiences about compatibility. But we do not stuck on Opentracing. As long as the trace data can be sent to zipkin or jaeger we are satisfied.
