### ISSUE TITLE
[management-api] Generated swagger describes date-time fields as strings, but they serialize as longs

### ISSUE THREAD

**Issue by isorashi** [gravitee-io/issues#1593]
When I grab the swagger.json from the management-rest-api, it has various fields that are declared as strings with a format of "date-format".  Swagger.io says this should match RFC 3339's section 5.6.  However, when I hit an end-point that returns that data, I get what looks like a Java timestamp as a long.  This is supported by io.gravitee.definition.jackson.datatype.GraviteeMapper, which includes the line (in both 1.12.0 and 1.13.0-SNAPSHOT):
```
        this.enable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
```

### Expected Behavior
Expected behavior is to receive a string matching RFC 3339's format for date-time for JSON fields like UserEntity's "created_at".  (Or alternately, the expected behavior is that the swagger defines the affected fields as int64 integers.)  Example output:

```
curl --user admin:admin http://localhost:18077/management/users/3df0677c-425b-46b4-b067-7c425bb6b48e
{
  "id" : "3df0677c-425b-46b4-b067-7c425bb6b48e",
  "username" : "api1",
  "roles" : [ {
    "name" : "API_PUBLISHER",
    "scope" : "management",
    "permissions" : {
      "ROLE" : [ "R" ],
      "GROUP" : [ "R" ],
      "APPLICATION" : [ "C", "R", "U", "D" ],
      "API" : [ "C", "R", "U", "D" ],
      "TAG" : [ "R" ],
      "VIEW" : [ "R" ],
      "TENANT" : [ "R" ]
    }
  }, {
    "name" : "USER",
    "scope" : "portal",
    "permissions" : {
      "DOCUMENTATION" : [ "R" ],
      "APPLICATION" : [ "C", "R", "U", "D" ]
    }
  } ],
  "source" : "memory",
  "sourceId" : "api1",
  "lastConnectionAt" : 1539869638503,
  "displayName" : "api1",
  "created_at" : 1539024488848,
  "updated_at" : 1539869638503
}
```
The matching swagger definition for this is:
```
    "UserEntity" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "firstname" : {
          "type" : "string"
        },
        "lastname" : {
          "type" : "string"
        },
        "username" : {
          "type" : "string"
        },
        "password" : {
          "type" : "string"
        },
        "email" : {
          "type" : "string"
        },
        "roles" : {
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "$ref" : "#/definitions/UserRoleEntity"
          }
        },
        "picture" : {
          "type" : "string"
        },
        "source" : {
          "type" : "string"
        },
        "sourceId" : {
          "type" : "string"
        },
        "lastConnectionAt" : {
          "type" : "string",
          "format" : "date-time"
        },
        "created_at" : {
          "type" : "string",
          "format" : "date-time"
        },
        "updated_at" : {
          "type" : "string",
          "format" : "date-time"
        }
      }
    }
```

### Current Behavior

Current behavior is that the date-time is output as a milliseconds-since-the-epoch timestamp.

### Possible Solution

Suggested fixes are to either output the affected values as a RFC 3339 date-time string; or to change the swagger generation so that it describes the fields as integers with an int64 format.

### Context

My use case is that I am using the swagger to generate overlays to use with GWT.  It's easy to work around the discrepancy, but ideally the output would match the swagger.

### Your Environment

* Version used: Gravitee 1.18.1 (I think it still does this as of 1.19.3)

**Comment by brasseld** [comment]
Hi @isorashi 

I've just push a [fix](https://github.com/gravitee-io/gravitee-management-rest-api/commit/e8195f015dfce6ef0d20e68b0f6d9cc20d00c9e0) for this issue.

Perhaps you can have a try with it ?
