### ISSUE TITLE
[gateway] Virtual hosting support

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#1594]
As per https://github.com/gravitee-io/issues/issues/503#issuecomment-378639399

Should also resolve:
- https://github.com/gravitee-io/issues/issues/503
- https://github.com/gravitee-io/issues/issues/1252
- https://github.com/gravitee-io/issues/issues/1445

**Comment by sahlex** [comment]
+1

**Comment by NeubauerJohannes** [comment]
+1
