### ISSUE TITLE
Configure SMTP details through helm chart values file

### ISSUE THREAD

**Issue by gs11** [gravitee-io/issues#1600]
### Expected Behavior
The helm chart values file would have an SMTP section to allow this configuration as part of initial deploy.

### Current Behavior
SMTP configuration is a manual post-step requiring editing of configmap + recreating API Pod.

### Possible Solution
SMTP server details are read from a section in the values file.

### Steps to Reproduce (for bugs)
1. Install helm chart
2. Edit API configmap
3. Delete API Pod to have a new one using the updated configuration

### Context
Would like to minimize configuration in the kubernetes environment and rather rely on helm chart values only.

### Your Environment
* Version used: 1.20.0
* Browser Name and version: Firefox 62
* Operating System and version: Linux / Kubernetes

**Comment by brasseld** [comment]
Perhaps you can contribute to support this?

**Comment by gs11** [comment]
Absolutely, I'd also like the admin password to be overrideable from the deployment
