### ISSUE TITLE
[management] Can't save Portal settings in Web UI

### ISSUE THREAD

**Issue by gs11** [gravitee-io/issues#1609]
### Expected Behavior
Pressing Save button updates the portal settings

### Current Behavior
A popup error states "Property [portalTitle] is not recognized as a valid property "

### Possible Solution
The request to the API contains **portalTitle** in the body which is rejected by the management API.
### Steps to Reproduce (for bugs)
1. Navigate to the UI -> Settings
2. Edit some value(s)
3. Press Save button
4. Observe error message popup

### Context
-

### Your Environment
* Version used: 1.20.0
* Browser Name and version: Firefox 62
* Operating System and version: Windows 10 (client), Linux (server)

**Comment by brasseld** [comment]
I'm not able to reproduce.

Is there any other way to observe this behavior?

**Comment by aelamrani** [comment]
@gs11 seems you have a `portalTitle` key in your constants.json file.

You probably missed this step: https://docs.gravitee.io/apim_installguide_migration.html#upgrade_to_1_16_0

**Comment by gs11** [comment]
Thanks, wasn't aware of that @aelamrani.

**Comment by gs11** [comment]
Thanks @aelamrani . Indeed I missed that in the helm chart.
