### ISSUE TITLE
[portal] Not implemented change settings of internal logging in management portal

### ISSUE THREAD

**Issue by Renso** [gravitee-io/issues#1624]
In version 1.20 not implemented UI for change logging  settings for API
in 1.19 version this setting could be change on API level from proxy screen

![image](https://user-images.githubusercontent.com/871749/47671643-0c84c900-dbc1-11e8-8ff8-f75cffb47094.png)

* Version used: 1.20.1

**Comment by brasseld** [comment]
The logging configuration has been moved to the logs view.
Click the link next to the view title

**Comment by Renso** [comment]
Thanx. **Analytics - Logs - Configure the logging** link
![image](https://user-images.githubusercontent.com/871749/47674591-b6b41f00-dbc8-11e8-83cb-6935a3dbdceb.png)
