### ISSUE TITLE
[policy] Improved error handling for invalid policies

### ISSUE THREAD

**Issue by danlange** [gravitee-io/issues#1632]
I implemented a policy plugin with two classes that implement the PolicyConfiguration interface.
When instantiating the policy, the gateway sometimes uses one as the constructor parameter to the policy and sometimes uses the other.  When it uses the wrong one, calls to APIs using the policy fail.

### Expected Behavior
Either determine what class is expected by the constructor, and use that class as the PolicyConfiguration
or 
When scanning the plugin, fail because multiple classes implement PolicyConfiguration and only one is allowed to.

### Current Behavior
Sometimes the gateway works fine, and other times all APIs that use the plugin throw an exception:
Caused by: java.lang.IllegalArgumentException: argument type mismatch at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) 
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) 
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
at io.gravitee.gateway.policy.impl.PolicyFactoryImpl.createPolicy(PolicyFactoryImpl.java:86) 
at io.gravitee.gateway.policy.impl.PolicyFactoryImpl.create(PolicyFactoryImpl.java:57) 

### Context
I recognize that this was caused by a mistake on my part, but it took a very long time to track it down, because of the intermittent nature of the failure, and the unhelpful error message.  I am suggesting an improvement to stop others from going down this path.

How I accidentally created two classes that implement PolicyConfiguration:  My policy takes a complex configuration object (It is a recursive tree structure.)  When I tried to use this, I discovered that the management_ui can't handle configuration objects this complex.  So, I created a new PolicyConfiguration implementation that just contains a single string with an escaped version of the original structure.  The policy constructor unescapes and deserializes the string into the complex tree structure.  But I forgot to remove the PolicyConfiguration tagging interface from the complex tree structure.

**Comment by brasseld** [comment]
Hi @danlange ,

Can you share your complex PolicyConfiguration to understand why the UI is not able to handle it ? Or perhaps you can share a link to a git repository with the policy implementation ?

**Comment by danlange** [comment]
My policy plugin allows me to support a set of requirements:
1) Each version of each resource must be implemented as a separate endpoint.
2) The API URLs may include path parameters
3) Resource versions are represented as URL parameters

So, for example:
/countries?version=1 maps to one endpoint
/countries/{countryId}/states?version=1 maps to a second endpoint
/countries/{countryId}/states/{stateId}/cityList?version=1 maps to a third endpoint
/countries/{countryId}/states/{stateId}/cityList?version=2 maps to a fourth endpoint


Here is an example configuration document (context path = "/countries"):
{
  "versions": {
    "1": {
      "implementation": "http://10.48.2.190:8765/countries_v1"
    }
  },
  "pathParam": "countryId",
  "paramChild": {
    "versions": {
      "1": {
        "implementation": "http://10.48.2.190:8765/countries_v1/{countryId}"
      }
    },
    "children": {
      "states": {
        "versions": {
          "1": {
            "implementation": "http://10.48.2.190:8765/countries/{countryId}/states_v1"
          }
        },
        "pathParam": "stateId",
        "paramChild": {
          "versions": {
            "1": {
              "implementation": "http://10.48.2.190:8765/countries/{countryId}/states_v1/{stateId}"
            }
          },
          "children": {
            "cityList": {
              "versions": {
                "1": {
                  "implementation": "http://10.48.2.190:8765/countries/{countryId}/states/{stateId}/cityList_v1"
                }
              }
            }
          }
        }
      }
    }
  }
}

Here is the configuration schema:
{
  "type" : "object",
  "id" : "urn:jsonschema:com:polycom:apigateway:urltree:UrlTreePolicyConfiguration",
  "properties" : {
    "pathParam" : {
       "type" : "string"
    },
    "paramChild": {
       "type": "object",
       "$ref": "#"
    },
    "children": {
       "type": "object",
       "additionalProperties": {
          "type": "object",
          "$ref": "#"
       }
    },
    "versions": {
       "type": "object",
       "additionalProperties": {
          "type": "object",
          "properties" : {
             "implementation" : {
                "type" : "string"
             }
          }
       }
    }
  }
}

**Comment by brasseld** [comment]
Hi @danlange 

Did you manage to make this policy works (with its complexe configuration)?

**Comment by danlange** [comment]
Not exactly.  I still have this complex configuration, but currently I represent it as a single string with the whole JSON object encoded in it.  I decode the string within the plugin, instead of using gravitee.io's capabilities to decode it.
It is a hack that I would love to clean up.
