### ISSUE TITLE
[portal] don't save label type fields 

### ISSUE THREAD

**Issue by Renso** [gravitee-io/issues#1636]
### Expected Behavior
don't save labels type  fields on portal, such as **api labels**, **CORS**, **plan characteristics**

### Possible Solution

Add values directly in mongoDB

### Steps to Reproduce (for bugs)

1. **API - Plans - Edit - Characteristics**
2. Type characteristics
3. Text is not identified as a label and is not saved
--
1. **API - Labels**
2. Type labels
3. Text is not identified as a label and is not saved

etc...

### Your Environment

* Version used: 1.20.3

**Comment by NicolasGeraud** [comment]
Hi @Renso it's probably due to the "chips" component in material design.
You have to press enter after each label to create a "chips"

**Comment by Renso** [comment]
Thanx, all work, sorry

**Comment by NicolasGeraud** [comment]
no problem, we know that this ui component is confusing and probably need to be replaced.
