### ISSUE TITLE
[management-api] Full export of an API, including members, pages, ...

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#164]
**Feature :**

    Add members and pages when exporting/importing an api.
    With this feature, an api configured on a staging environment, could be more easily promoted to production automatically.

**Question :**
Currently, the api is exported like this:
```
{
  "name": "test",
  "version": "1",
  "description": "my awesome api",
  "visibility": "PRIVATE",
  "tags": [],
  "proxy": { ... },
  "paths": { ... },
  "properties": {
    "prop1": "value1"
  },
  "services": {},
  "resources": [ ... ]
}
```

Members and pages should be added to the existing json like this : 
```
{
  "name": "test",
  "version": "1",
  "description": "my awesome api",
  "visibility": "PRIVATE",
  "tags": [],
  "proxy": { ... },
  "paths": { ... },
  "properties": { 
    "prop1": "value1"
  },
  "services": {},
  "resources": [ ... ],
  "members": [ ... ],
  "pages": [ ... ]
}
```
or in a new format : 
```
{
  "definition": {
    "name": "test",
    "version": "1",
    "description": "my awesome api",
    "visibility": "PRIVATE",
    "tags": [],
    "proxy": { ... },
    "paths": { ... },
    "properties": {
      "prop1": "value1"
    },
    "services": {},
    "resources": [ ... ]
  },
 "pages": [ ... ],
 "members": [ ... ]
}
```
With the first format, we don't break anything. What do you think ?

**Comment by helmuthva** [comment]
Hi,

I just started experimenting with gravitee but could not find a mention of the following behavior in issues or the documentation of the Mgmt. API:

When importing an api export when the resp. API already exists the following error is thrown:

`curl -uadmin:admin -d @api.json http://localhost:8005/management/apis/import
{
  "message" : "The api context path [/testauth/] already exists.",
  "http_status" : 400
`

- Is this intended  behavior?
- If so,  what is the recommended procedure to promote an update of an API definition e.g. from dev->test->staging->production?

Best

**Comment by brasseld** [comment]
Hi @helmuthva 

I think you're looking for this service: https://docs.gravitee.io/apim/api/1.17/#operation/updateWithDefinition

Using this one, you are able to update API definition from a previously exported definition, including pages, plans, members, ...
