### ISSUE TITLE
Web UI "settings" window too wide, hides features to the right of the screen

### ISSUE THREAD

**Issue by hfuru** [gravitee-io/issues#1640]
The API Management Web UI can push the right margin far to the right of the screen
and hide featues "outside" the screen by adding a lot of blank space in the middle.
If the help sidebar to the right is enabled, features can also hide unnecessarily under it.

One user could not find the "missing" features when he was exploring Gravitee.
He saw ordinary left-justified lists of stuff with blank space at the right.  It did
not occur to him to glance to the bottom of his screen for a scrollbar.

### Expected Behavior

Don't add that extra space.  Gravitee 1.13.3 didn't.

### Steps to Reproduce (for bugs)

1. Go to Administrations / Settings / Roles, or API Portal Headers (my screenshots)
2. Disable the help sidebar.
3. Drag the screen width back and forth, watch the scrollbar, watch things disappear to the right.
4. Toggle the help sidebar while watching the scollbar, with a too narrow screen.

### Context

Screenshots: https://folk.uio.no/hbf/gravitee-1.20.2.screenshots.zip

### Your Environment

* Version used: 1.20.2
* Browser Name and version: Firefox 60.0.2 @ Windows, 63.0 @ Fedora Linux
* Operating System and version: Linux, RHEL 7.5, x86_64

**Comment by gaetanmaisse** [comment]
Closing as outdated.
