### ISSUE TITLE
[gateway] 404 Not Found

### ISSUE THREAD

**Issue by rblundellSL** [gravitee-io/issues#1645]
I have hosted all three components of Gravitee and have been able to successfully create an API, plan, and application to consume the API. 

From the API Gallery I am provided the following;

curl -X GET "https://api.company.com/testone" -H "X-Gravitee-Api-Key: <MY KEY>"

When I test this from remotely (using the public IP of the machine) or locally using localhost (and changing https to http as 443 is not being listened to), I always get a 404 not found error. 

Please can you indicate why this may be the case?

**Comment by aelamrani** [comment]
Is your API deployed/started? Are you calling the gateway component (and not the management part)? Is the response body is "No context-path matches the request URI."? If not, you are not calling the gateway...

**Comment by rblundellSL** [comment]
Hi, It is deployed and started and I am pointing it at port 8083 (the
gateway). The response for that request when hitting it from postman is
also a 404 Not Found.

**Comment by rblundellSL** [comment]
The above response body is empty...looking at the logs it looks like it is potentially linked to MongoDB (which I have installed on the machine). Here is the gravitee.log from the gateway folder...

[gravitee.log](https://github.com/gravitee-io/issues/files/2557521/gravitee.log)

**Comment by brasseld** [comment]
You have an SSL issue.

What is your JDK version ?

**Comment by rblundellSL** [comment]
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) Client VM (build 25.191-b12, mixed mode)

**Comment by NicolasGeraud** [comment]
see #1638

**Comment by rblundellSL** [comment]
Thanks Nicolas - I stopped the java process for the gateway , changed the two lines noted and added the new jar to the boot directory, but still getting the same error after restarting the gateway. Any thoughts?

**Comment by NicolasGeraud** [comment]
hum, the only problems we have encountered that produce the stacktrace

```
java.lang.NoSuchFieldError: state
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:198)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:970)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:967)
```

are due to jdk versions Vs jnlp-agent versions.

**Comment by NicolasGeraud** [comment]
Can you double check on your gateway instance (through the management ui) the jdk used and the jnlp version ?

like that : https://demo.gravitee.io/#!/management/instances/6f9de089-3e8f-4907-9de0-893e8fa907d5/environment

<img width="974" alt="capture d ecran 2018-11-07 15 39 19" src="https://user-images.githubusercontent.com/1028285/48137913-606b6e00-e2a3-11e8-9ac1-fe220a84135d.png">
<img width="534" alt="capture d ecran 2018-11-07 15 40 10" src="https://user-images.githubusercontent.com/1028285/48137933-71b47a80-e2a3-11e8-8e6b-79542cd1326d.png">

**Comment by rblundellSL** [comment]
Thanks, Nicolas.

Here are the values for those fields...

java.class.path
/home/ec2-user/graviteeio-full-1.20.3/graviteeio-gateway-1.20.3/lib/gravitee-gateway-standalone-bootstrap-1.20.3.jar:/home/ec2-user/graviteeio-full-1.20.3/graviteeio-gateway-1.20.3/boot/jetty-alpn-agent-2.0.9.jar

java.runtime.name Java(TM) SE Runtime Environment
java.runtime.version 1.8.0_191-b12

Rory Blundell
Senior Solutions Engineer
rblundell@snaplogic.com
(+44) 7947 541 102 <(+44)+7947+541+102>


SnapLogic.com | We're Hiring! <https://www.snaplogic.com/about-us/jobs>



------------------------------

*SnapLogic Ltd | 20 Little Britain | London | EC1A 7DH
<https://maps.google.com/?q=20+Little+Britain+%7C+London+%7C+EC1A+7DH&entry=gmail&source=g>
|
United Kingdom *
This message is confidential. It may also be privileged or otherwise
protected by work product immunity or other legal rules. If you have
received it by mistake, please let us know by e-mail reply and delete it
from your system; you may not copy this message or disclose its contents to
anyone. The integrity and security of this message cannot be guaranteed on
the Internet.

**Comment by rblundellSL** [comment]
Hi All, after the update I restarted the gateway again and it seemed to work. Thanks for your help.

**Comment by YoganandChandran** [comment]
> Is your API deployed/started? Are you calling the gateway component (and not the management part)? Is the response body is "No context-path matches the request URI."? If not, you are not calling the gateway...

Hi aelamrani,

Hope you are doing well,

I want to integrate my kafka with gravitee.io could you please help me to do that, and I want to know how to create api.gravitee.io APIs like you guys created time APIs(i.e) whattimeisit. Please help me to do that 

Thanks you
