### ISSUE TITLE
[gateway] Stripping of context path

### ISSUE THREAD

**Issue by cermu** [gravitee-io/issues#1650]
woul like to have the stripping of context path included in the UI
### Expected Behavior

when creating an api, there should be an option to allow stripping of context path
### Current Behavior

i talked to one of you guys and he said it is there but not in the UI, if it makes any sense, would you consider to include it in the UI

**Comment by brasseld** [comment]
A simple question.

Currently, Gravitee is already doing stripping context path automatically, no ?

The API is exposed on Gravitee with the context-path /persons
The backend API is exposed on http://my_back_end/my-api/

If the API consumer calls http://api_gateway/persons/person1, the HTTP request will be redispatched to http://my_back_end/my-api/person1

Is it not what you're looking for ?

**Comment by brasseld** [comment]
Can I close the issue @cermu ?
