### ISSUE TITLE
[gateway] Chunked Encoding and empty get requests

### ISSUE THREAD

**Issue by aesteve** [gravitee-io/issues#1655]
We're facing a very weird use case with chunked encoding. I'm just reporting it because I'm wondering if this could not cause real issues in other cases.

Use-case : Client <-> Gateway <-> Server

The client sends a `GET` request, with no body, but a `Content-Type` header (hence the "weird use-case", it's clearly a bug on the client).

The Gateway receives the request see : https://github.com/gravitee-io/gravitee-gateway/blob/7e187037ff580db60f416618842880afa748c4e4/gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/VertxProxyConnection.java#L125-L130
Since the Content-Type header is set, but the Content-Length is not, the gateway assumes chunked encoding should be used (after all, `GET` requests could have a body according to the RFC, even though it's highly inadvisable, so why not)

The server (akka-http) receives a chunked-encoded request, ignores the request body, and sends the response, complaining with this message : https://github.com/akka/akka-http/blob/ff1258ec2be4d658f143d1b7dd95d70d31744d1e/akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala#L421-L424
```
Sending an 2xx 'early' response before end of request was received...
Note that the connection will be closed after this response. Also, many clients will not read early responses! Consider only issuing this response after the request data has been completely read!
```
According to the server, it is sending the response "too early" since the connection was marked as chunked but no chunk has been received.

In our very specific use-case, fixing the client (no Content-Type if no body) would make the problem vanish. 
But I'm wondering if this behaviour could not lead to weird issues, like setting a request as chunked and never closing it, or something weird like that ?
And also, is the condition : `Content-Type` header is set, and `contentLength() == -1` really the good one to set the request as chunked ?

Changes ?
Maybe the gateway could rely on `Transfer-Encoding: chunked` header instead ? 
Or maybe change the condition to : 
``` 
if (proxyRequest.isChunked()) {
  httpClientRequest.setChunked(true);
}
```
or  maybe just adding `!proxyRequest.isEnded()`

``` 
        long contentLength = headers.contentLength();
        if (contentLength > 0 || headers.contentType() != null) {
            if (contentLength == -1 && !proxyRequest.isEnded()) {
                // No content-length... so let's go for chunked transfer-encoding
                httpClientRequest.setChunked(true);
            }
        }
```

would fix the issue ?

What do you think ? 

Thank you.

**Comment by brasseld** [comment]
I don't want to rely on the `isEnded` method for such stuff.

IMHO, the best option, as you said, would be to relay on the `Transfer-Encoding` header.

So, I think the fix would results to this condition:

```java
        if (contentLength > 0 || headers.contentType() != null) {
            if (contentLength == -1 &&
                    (headers.getFirst(HttpHeaders.TRANSFER_ENCODING) != null
                            && headers.getFirst(HttpHeaders.TRANSFER_ENCODING).contains("chunked"))) {
                httpClientRequest.setChunked(true);
            }
        }
```

WDYT ?

**Comment by aesteve** [comment]
I think it's indeed better.

But then it doesn't cover the (still buggy) case where a client sends `Transfer-Enconding: chunked` then ends the requests without sending any chunk.
If you know the client's request is already terminated, and that `contentLength() == -1` you know for sure it doesn't have a body, hence chunking doesn't make sense.

But maybe there is an issue with the `isEnded` method I don't know about (not reliable ?).

Hard to tell, since we're talking about very marginal cases where the client sends inappropriate headers. We're currently designing a case where the gateway actually "fixes" a bad client request, so... The simpler the better.

Thanks for your answer.

**Comment by brasseld** [comment]
Hi @aesteve 

The `writeHeaders` (https://github.com/gravitee-io/gravitee-gateway/blob/7e187037ff580db60f416618842880afa748c4e4/gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/VertxProxyConnection.java#L116) method is called by an endHandler(), meaning that, at this moment, we are sure that we have received all the data / body content from the client. 

It's more or less the same results as the `isEnded` method but, as we are agnostic to Vertx, I don't want to add a new isEnded() method for now (and it doesn't make sense at the time of writing).

So, IMHO, checking that `contentLength == -1` and headers contains 'Transfer-encoding: chunked' is sufficient to say that chunked must be set.

**Comment by aesteve** [comment]
So if you are sure that you've received everything from the client, and that `contentLength == -1` there's no point in chunking ? Am I missing something ?

**Comment by brasseld** [comment]
But `contentLength == -1` with or without `Transfer-encoding: chunked` that's the reason why I propose to add a condition to test against the presence of this particular header from proxy request.

**Comment by brasseld** [comment]
After some private discussions with @aesteve on [Gitter](https://gitter.im/gravitee-io/gravitee-io) we conclude that the best solution is to verify and set the chunked mode only when the gateway is writing data to the upstream.

With the current version, we are doing it when writing HTTP headers to the upstream. It's not really accurate because the client can still send an empty body with a `transfer-encoding` header.

That's the reason why we choose to set it as soon as the gateway is writing the first packet to the upstream.

**Comment by brasseld** [comment]
@aesteve Please have a look to https://github.com/gravitee-io/gravitee-gateway/pull/322

We do not have to check the content-length > 0 anymore since we know for sure that something is going to be written to upstream (writeHandler).
