### ISSUE TITLE
[management-api] Create an API from a Swagger descriptor results in NullPointerException

### ISSUE THREAD

**Issue by lusoalex** [gravitee-io/issues#168]
Hello,
When i try to import swagger (2.0) json to create a new API, it result in a NullPointerException.

```
java.lang.NullPointerException: null
	at io.gravitee.management.service.impl.SwaggerServiceImpl.prepare(SwaggerServiceImpl.java:46)

```

By analyzing my json, i see i do not have "schemes" specified.
So i read the swagger specificiations : http://swagger.io/specification/
I see schemes is not required : 

> If the schemes is not included, the default scheme to be used is the one used to access the Swagger definition itself.

Now, if we were importing the swagger throught an http/https call, we would take the scheme used to access to the json. But currently, we import it throught an "upload file".

==> Could you manage it by giving the possibility to : 

- import json swagger documentation through a web link (and use the link scheme) or
- setting "https" as default value when the scheme is not present and json uploaded by file.

Regards,
Alexandre.

**Comment by brasseld** [comment]
Hi @lusoalex,

Please create an other ticket for this enhancement: _import json swagger documentation through a web link (and use the link scheme)_

Even if it can resolve your issue, this is an enhancement of the import using Swagger feature.

**Comment by brasseld** [comment]
Enhancement issue has been created there: https://github.com/gravitee-io/issues/issues/170
