### ISSUE TITLE
Add note in gravitee.yml on supported bcrypt revision(s)

### ISSUE THREAD

**Issue by gs11** [gravitee-io/issues#1687]
### Expected Behavior
Management API gravitee.yml mentions bcrypt being used the passwords but doesn't say which revisions are supported. The supported types are limited in spring-security and you'll get a "Encoded password does not look like BCrypt" if using e.g. $2y$. See more here https://github.com/spring-projects/spring-security/issues/4550
A small note could be added on the supported revision(s)

### Current Behavior
Seemingly only $2a$ is supported by the used springsecurity version. A hash with $2y$ will fail with the above error upon login attempt

### Possible Solution
Always use $2a$. Document requirement in config file

### Steps to Reproduce (for bugs)
1. Hash a password using htpasswd `htpasswd -bnBC 10 "" <password> | tr -d ':\n'`
2. Enter hash in gravitee.yml
3. Start management api
4. Attempt to login with the password

### Your Environment

* Version used: 1.20.6
* Browser Name and version: n/a
* Operating System and version: n/a

**Comment by brasseld** [comment]
Hi @gs11 

This is due to the fact that we are using Spring Security, and this later is only accepting hash starting with $2a$.

I will have a look to see if we can provide our own implementation of password encoder

**Comment by gs11** [comment]
Personally it doesn't matter what revision is supported but a note in the config file should be fine so the user uses the correct tool to generate the hash.  @brasseld

**Comment by gs11** [comment]
Added note in helm chart https://github.com/gravitee-io/gravitee-kubernetes/pull/4
