### ISSUE TITLE
Create a new API from an export

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#169]
With #164 , we will create a full export of an api.
It could be useful to create a api from this export.

Currently we only permit to update an existing api.

**Comment by brasseld** [comment]
@NicolasGeraud,

What is the difference with the "Import API definition" from the APIs screen ?

<img width="1381" alt="capture d ecran 2016-07-26 a 08 48 09" src="https://cloud.githubusercontent.com/assets/133094/17128541/b81a64d0-530d-11e6-85dc-ffb6f7e54d8c.png">

**Comment by NicolasGeraud** [comment]
you're write, I've refactored the code to create or update an api from a definition.
see #164
