### ISSUE TITLE
cant access Gravitee MGMT web page

### ISSUE THREAD

**Issue by hagay-david** [gravitee-io/issues#1694]
OS - Ubuntu 18.04.1 LTS
Docker version 18.06.1-ce
After a successful installation using Docker-compose from the following documentation guide --> https://docs.gravitee.io/apim_installguide_docker.html
I am unable to access the mgmt web site.
the first attempt has pop up a browser login window ,I used - admin : admin
but the page is responding with
{
"message" : "HTTP 404 Not Found",
"http_status" : 404
}
maybe I am doing something wrong but i tried several repos with the same results
any Idea ?
thank you

**Comment by hagay-david** [comment]
- OS - Ubuntu 18.04.1 LTS
- Docker version 18.06.1-ce
After a successful installation using Docker-compose from the following documentation guide -->  https://docs.gravitee.io/apim_installguide_docker.html
I am unable to access the mgmt web site.
the first attempt has pop up  a browser login window ,I used - admin : admin 
but the page is responding with 
{
  "message" : "HTTP 404 Not Found",
  "http_status" : 404
}
maybe I am doing something wrong but i tried several repos with the same results 
any Idea ?
thank you

**Comment by hagay-david** [comment]
Hi again,
I am also trying to access to Mgmt UI using port 8002 but I am getting the following error on 
my web page :
**Management API unreachable or error occurs, please check logs****

**Comment by hagay-david** [comment]
Hi 
Sure 👍 
curl -v http://localhost:8005/management/apis
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8005 (#0)
> GET /management/apis HTTP/1.1
> Host: localhost:8005
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Length: 3
< 
* Connection #0 to host localhost left intact

**Comment by NicolasGeraud** [comment]
ok, so the management-api works well. The result `[]` means that there is no api available.


Can you give the result of `curl http://localhost:8002/constants.json`?

**Comment by hagay-david** [comment]
Sure Nicolas,
curl http://localhost:8002/constants.json
{
  "baseURL": "http://localhost:8005/management/"
}

**Comment by NicolasGeraud** [comment]
Good.

now share your devtools console (screenshot) when you try to access http://localhost:8002

**Comment by hagay-david** [comment]
**by the way ,
This Ubuntu server is Google cloud instance.
I am using the external IP which provided by google cloud.**

![gravitee-capture](https://user-images.githubusercontent.com/44335715/48981231-9bf79c00-f0db-11e8-8ee7-eb36c772096e.PNG)

**Comment by NicolasGeraud** [comment]
I don't understand, are you running gravitee locally or on GCP ?

What is the details of the `/portal` call failing ?

**Comment by hagay-david** [comment]
The instance running gravitee is on GCP.
I am trying to access to web UI using the external IP provided to this instance,
![image](https://user-images.githubusercontent.com/44335715/48981390-753a6500-f0dd-11e8-8f9c-db0a6526bbc0.png)

**Comment by hagay-david** [comment]
I have checked all all containers logs,  looks good and no errors has been  prompted.
![image](https://user-images.githubusercontent.com/44335715/48981415-d2ceb180-f0dd-11e8-8ec8-47701e3b9458.png)

**Comment by NicolasGeraud** [comment]
hum, why `curl -v http://localhost:8005/management/apis` returns something if you have deployed on gcp ?

**Comment by NicolasGeraud** [comment]
so you have to change the constants.json file in your ui container to : 
```
{
"baseURL": "http://35.233.237.29:8005/management"
}
```

**Comment by hagay-david** [comment]
What are the ports which are are must to expose?
Meaning I can see that today 3 ports are exposed.

**Comment by NicolasGeraud** [comment]
Hi,
please create a dedicated issue to each question.
Is this one could be closed ?

(and yes, you can import a swagger instead of using the creation wizard)

**Comment by hagay-david** [comment]
Sure,
Thank you.

**Comment by ltcpereira** [comment]
Hi All,
I have a similar situation.
I can access http://localhost:8002/ but not http://localhost:8005/management

Can you helpme?

**Comment by ltcpereira** [comment]
Yes

**Comment by brasseld** [comment]
you're running locally ?

Please give the output of:

> curl -vvv -X GET http://localhost:8005/management/apis

**Comment by ltcpereira** [comment]
* About to connect() to localhost port 8005 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 8005 (#0)
> GET /management/apis HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8005
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Length: 3
< 
* Connection #0 to host localhost left intact

**Comment by brasseld** [comment]
ok, so you have a response from the server.

In that case, what is going wrong there ?

**Comment by ltcpereira** [comment]
When I access http://localhost:8005/management I am prompt for username and password and after the post I receive the following response:

message | "HTTP 404 Not Found"
http_status | 404

Isn't supposed to enter in the management console?

**Comment by brasseld** [comment]
Sorry, but there is no reason to access this path directly...

The management console is accessible from http://localhost:8002/

**Comment by ltcpereira** [comment]
Thanks.
I'm starting with Gravitee and I'm following an official guide but from a different version and I wasn't looking to  the flow correctly.

I'm now creating the API.

Thanks a lot for your time.

**Comment by db3net** [comment]
I'm having this problem too - I'm hosting the httpd service for the portal on the same machine as the management-api. I've tried changing the URL in constants.json to reflect the FQDN of my server but it isn't taking during the startup described in the instructions (python3 -m httpd.server). I'm guessing the advice above only works in a Docker container...not for running the web-server per the installation instructions. I've even tried curl posting the contents of constants.json into the Management API with the new values but I'm getting blocked by the authentication mechanism. Wish this was easier.
