### ISSUE TITLE
[management] First API returns 401 

### ISSUE THREAD

**Issue by hagay-david** [gravitee-io/issues#1695]
Hello Gravitee team,
Gravitee installed on Ubuntu at GCP.
just finished creating first API .

when hitting -- > http://35.233.237.29:8000/myfirstapi
I am getting  :
{
  "message" : "Unauthorized",
  "http_status_code" : 401
} 
when trying to reach the example API   
here are few snippets:
![image](https://user-images.githubusercontent.com/44335715/49003311-57ffa800-f16a-11e8-892b-536954f06b9a.png)

![image](https://user-images.githubusercontent.com/44335715/49003340-66e65a80-f16a-11e8-83d7-423d35cfbeb8.png)

![image](https://user-images.githubusercontent.com/44335715/49003450-9e550700-f16a-11e8-8abe-d5dc53d36ec6.png)

Thank you

**Comment by NicolasGeraud** [comment]
Hi,
Is your api started ?
Have you created a plan ?

**Comment by hagay-david** [comment]
Hi ,
Yes and yes :
![image](https://user-images.githubusercontent.com/44335715/49006031-cfd0d100-f170-11e8-9514-ad55cbae3dd2.png)

**Comment by NicolasGeraud** [comment]
Ok, so you also need a subscription to this plan in order to provide the apikey to your request.

Have you done that ?

**Comment by NicolasGeraud** [comment]
Ok, so you also need a subscription to this plan in order to provide the apikey to your request.

Have you done that ?

**Comment by brasseld** [comment]
Hi @hagay-david 

What is the status of this ticket?
