### ISSUE TITLE
[gateway] Using dictionaries in API-defined endpoints

### ISSUE THREAD

**Issue by tzepterbvv** [gravitee-io/issues#1696]
### General Summary
To avoid end point-specific specifications in an API definition, it is possible to use Dictionary entries in API properties. The same option would be useful for the use in endpoint definitions. 

### Expected Behavior

The expected behaviour is the possibility to use EL-terms like {#dictionaries['dic']['key']} in endpoint targets and paths and header values of the endpoint health check-configuration.

### Current Behavior

The goal is a Jenkins-based API-deployment through a APIM-systems landscape (dev/staging/prod) without touching the API definition. Currently the server-specific terms must be changed in API-definition before deploying it on the next level system within the landscape.

### Your Environment

* Version used: 1.20.4
* Browser Name and version: Google Chrome (current)
* Operating System and version: Windows Server 2013 with nginx

**Comment by lpulec** [comment]
Hi all, is there any progress with this issue? It would be very useful, when we could use "dictionaries" in endpoints. Now, it is working fine, when I use "properties" in API endpoint target's EL, but when I use "dictionaries", I get this error message in log:

`Illegal character in path at index 0: {#dictionaries['service-list']['service1']}`

**Working target's EL:**
`{#properties['my-property']}`

**Not working target's EL:**
`{#dictionaries['service-list']['service1']}`

Are there any plans with this issue? Thank you!

**Comment by tzepterbvv** [comment]
Hi folks,

we are just using a workaround: Jenkins exchanges the ip-addresses within the deployment pipelines. Works, but not more. My colleague who wanted to change your module is at a conference in the moment. That’s why I do not know the state of that change. Could be possible that we live with our workaround. @Marcus?

Best regards,
Tobi




Tobias Zepter
Diplom-Mathematiker
Aktuar DAV




phone:   +49 / 30 / 896 01-449
fax:     +49 / 30 / 896 01-215
email:   t.zepter@bvv.de


[cid:image4392c8.JPG@94000fb6.4b9f6c15]

BVV Versicherungsverein des Bankgewerbes a.G.
BVV Versorgungskasse des Bankgewerbes e.V.
BVV Pensionsfonds des Bankgewerbes AG
Kurfürstendamm 111 - 113  |  D- 10711 Berlin  |   Germany
www.bvv.de<http://www.bvv.de>


Please find the legal information on the BVV companies at http://www.bvv.de/pflichtangaben.
Von: lpulec <notifications@github.com>
Gesendet: Donnerstag, 7. November 2019 16:03
An: gravitee-io/issues <issues@noreply.github.com>
Cc: Zepter, Tobias <t.zepter@bvv.de>; Author <author@noreply.github.com>
Betreff: Re: [gravitee-io/issues] [gateway] Using dictionaries in API-defined endpoints (#1696)




==> Die Nachricht war weder verschluesselt noch digital unterschrieben



Hi all, is there any progress with this issue? It would be very useful, when we could use "dictionaries" in endpoints. Now, it is working fine, when I use "properties" in API endpoint target's EL, but when I use "dictionaries", I get this error message in log:

Illegal character in path at index 0: {#dictionaries['service-list']['service1']}

Working target's EL:
{#properties['my-property']}

Not working target's EL:
{#dictionaries['service-list']['service1']}

Are there any plans with this issue? Thank you!
