### ISSUE TITLE
Provide version in the UI (header or footer).

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#17]
_From @brasseld on February 23, 2016 13:58_

Currently, there is no information about the version of the webUI (or the global solution ?).
We have to provide this kind of information (also when user creating issues, the version must be required by them).

_Copied from original issue: gravitee-io/gravitee-management-webui#103_

**Comment by NicolasGeraud** [comment]
the version is now on the home page and we could find all plugins versions on each gateway instances
