### ISSUE TITLE
[portal] Create an API from a Swagger descriptor exposed through HTTP / HTTPS 

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#170]
Currently, user is able to create an API from a local Swagger descriptor.
The goal here is to be able to achieve the same action but by providing an URL to a Swagger descriptor instead of having to download it locally.

**Comment by NicolasGeraud** [comment]
what do you think about create a default swagger documentation page ?
New issue ?

**Comment by brasseld** [comment]
Yes, a new issue please

**Comment by NicolasGeraud** [comment]
#182
