### ISSUE TITLE
[portal] View response body in application logs ui

### ISSUE THREAD

**Issue by Renso** [gravitee-io/issues#1710]
application logs ui /#!/management/applications/[id]/logs/[id]
not show response body 
![image](https://user-images.githubusercontent.com/871749/49377765-13e94600-f71c-11e8-9a38-bc06566323a6.png)

though in management api response /management/applications/[id]/logs/[id] data is present

while

api logs ui /#!/management/apis/[id]/logs/[id]
show more complete data including body

### Your Environment

* Version used: 1.20.7
* Browser Name and version: Google Chrome 70.0.3538.110

**Comment by brasseld** [comment]
Hi @Renso 

That was a normal behavior until now.
API Consumer is not able to see the request body / response body.

Don't tell why, because honestly... I really don't know :)

**Comment by Renso** [comment]
ok, its not a bug, but would like to see the same data presentation in the log viewing interface for application and api owners, maybe except gateway logs for application log view. Especially since all the data in the management api are present

**Comment by brasseld** [comment]
👍
