### ISSUE TITLE
[expression-language] jayway jsonpath lib has issue for Cache

### ISSUE THREAD

**Issue by yinghe1** [gravitee-io/issues#1713]
### Expected Behavior
We intend to use jsonpath function like concat($a, 'sometext') to config gravitee properties. However the underlying lib used jayway jsonpath has a bug https://github.com/json-path/JsonPath/issues/491
Gravitee should probably switch to another jsonpath lib since jayway jsonpath cache has many open issues, make Cache unusable: https://github.com/json-path/JsonPath/issues?utf8=%E2%9C%93&q=cache

### Current Behavior
see https://github.com/json-path/JsonPath/issues/491 for details for the problem

### Possible Solution
Better switch to a better jsonpath lib.
Temp work around is to use the following before everything loads:
CacheProvider.setCache(new NOOPCache());

### Your Environment

* Version used: gravitee 1.18.x

**Comment by brasseld** [comment]
Hi @yinghe1 

Can you provide a simple API export to reproduce the problem ?

Thanks a lot

**Comment by yinghe1** [comment]
sorry for the late reply.  no sample for API export but as https://github.com/json-path/JsonPath/issues/491 shows, if you use any concat(\"/\", $.key) notation  to configure properties fields, you will run into this issue
