### ISSUE TITLE
[management] Can't see current security definition for JWT plan

### ISSUE THREAD

**Issue by gs11** [gravitee-io/issues#1724]
### Expected Behavior
I'd expect to see the correct JKWS resolver & resolver parameter for an already configured plan.

### Current Behavior
Currently, when editing an existing plan it'll always say GIVEN_KEY and empty resolver parameter.

### Possible Solution
I can see that the API response contains the correct(?) values:
`securityDefinition: {"signature":"RSA_RS256","publicKeyResolver":"JWKS_URL","extractClaims":false,"resolverParameter":"https://<redacted>/auth/realms/<redacted>/protocol/openid-connect/certs"}
`
The actual token validation also works just fine for the plan.

Issue in UI code?

### Steps to Reproduce (for bugs)
1. Create JWT Plan
2. Edit above plan
3. Inspect security settings

### Your Environment

* Version used: 1.21.1
* Browser Name and version:
* Operating System and version:

**Comment by brasseld** [comment]
I'm having a look to fix it in 1.21.2
