### ISSUE TITLE
[management] Imported Swagger documentation page is empty

### ISSUE THREAD

**Issue by gs11** [gravitee-io/issues#1725]
### Expected Behavior
Importing a swagger file for documentation renders correctly

### Current Behavior
Import is successful but only _No API definition provided._ can be seen.

### Steps to Reproduce (for bugs)
1. Create a new page (Swagger)
2. Provide a name like "Swagger"
3. Browse and choose a Swagger YAML file
4. Press Save

### Your Environment

* Version used: 1.21.1
* Browser Name and version: Firefox 63.0.3
* Operating System and version:

**Comment by brasseld** [comment]
Hi @gs11 

I'm not able to reproduce.

Do you have a specific swagger file ? How is it going with the well-known Petstore ?

**Comment by gs11** [comment]
Same result with Petstore swagger. Looking at the POST request in the network logs only show this body:
`{"type":"SWAGGER","name":"Swagger"}` Response code is 201

Same result in both Firefox & Chrome.

**Comment by gs11** [comment]
Some previous UI administration settings issues stemmed from me using the old helm chart with newer version of Gravitee API Management. I'd like to think that this shouldn't possibly affect/cause my issue but I'm not sure.

**Comment by aelamrani** [comment]
OK i'm able to reproduce, we will provide a fix on a 1.21.2 today

**Comment by n2ygk** [comment]
This seems to be happening with 1.24.0. A regression?
