### ISSUE TITLE
[alert] How to download alerts/notifiers plugins

### ISSUE THREAD

**Issue by Yomi-Xiong** [gravitee-io/issues#1730]
hi,
   i want to download alerts/notifiers plugins from https://download.graviteesource.com , but it need credentials, How can i get credentials?

**Comment by aelamrani** [comment]
Hi @Yomi-Xiong,

The Alert Engine is offered by GraviteeSource with professional support. 

Please send an email to contact (at) graviteesource (dot) com for more information.

I'm closing this issue.
