### ISSUE TITLE
docker-compose demo won't start elasticsearch due vm.max_map_count

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [gravitee-io/issues#1734]
Hi there!

When running the following demo:

```
# Download compose files
$ curl -L https://raw.githubusercontent.com/gravitee-io/gravitee-docker/master/environments/demo/common.yml -o "common.yml"
$ curl -L https://raw.githubusercontent.com/gravitee-io/gravitee-docker/master/environments/demo/docker-compose-local.yml -o "docker-compose-local.yml"

# (Optional step: pull to ensure that you are running latest images)
$ docker-compose -f docker-compose-local.yml pull

# And run...
$ docker-compose -f docker-compose-local.yml up
```

Elasticsearch will crash (in some linux) with the following error:
```
max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
```

They have a documentation regarding this situation: https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html

So I think the demo page could have some kind of warning regarding this configuration, because without this I was unable to run the demo and test gravitee.

**Comment by brasseld** [comment]
Hi @rafaelrenanpacheco 

Thanks for this feedback, we were aware of that point, and I think there is ticket about it.

Why not providing a PR including your recommandations ?

**Comment by rafaelrenanpacheco** [comment]
Done :smiley:
