### ISSUE TITLE
[plan] JWT authentification not working, is there any wrong?

### ISSUE THREAD

**Issue by majintao** [gravitee-io/issues#1741]
### Expected Behavior

authorized success .  and i can get the api info
### Current Behavior

jwt authorized  not working

### Steps to Reproduce (for bugs)

1. i make a plan config with jwt

Public key resolver
Select how public key is retrieved among : given key or gateway key settings...
Public key (ssh-rsa KEY xxx@yyy.zz) or expected issuers (name1|name2|...) 
Set the public key (GIVEN_KEY) or expected issuers (GIVEN_ISSUER) following selected resolver (support EL).

given key is:     this is a secret key

2. combind a application with the jwt plan
3. i request the api link this with post man
Authorization token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NDQ3ODY0MDMsImV4cCI6MTU0NDc4NjQxMywic3ViIjoiMTk5MzAzMTEiLCJpc3MiOiJodWFuIiwidXNlcl9pZCI6ImFkbWluIn0.21yq-BEWjEQwsCk9We-BiFZ-FG32X4B4uth1woImf78

4. but the result is fail   401,

### Your Environment

* Version used:
* Browser Name and version:
* Operating System and version:

**Comment by tcompiegne** [comment]
Hi @majintao , try with `Authorization Bearer (yourtoken)`

**Comment by majintao** [comment]
yes, but i try several times , it didnt work。

**Comment by majintao** [comment]
and i try with kong （other api gateway），work successfully

**Comment by brasseld** [comment]
Sorry, but we need to know how you configure the policy. If you're speaking about secret key, you have to work with hmac algorithm. Which version of gravitee are you using ?

**Comment by majintao** [comment]
https://github.com/majintao/problems/blob/master/gravitee-io/jwt/jwt-not-working.md

here is my step

**Comment by brasseld** [comment]
Hi @majintao 

Did you follow [this documentation](https://docs.gravitee.io/apim_publisherguide_plans_subscriptions.html#oauth_2_0_plan) ?

When defining an oauth2 or JWT plan, you need a subscription to the plan for the application.

**Comment by majintao** [comment]
Java code validate successfully. But gwio validate fail. I am sure that the client_id is right. And i had subscribed the application to the jwt plan.

here is my steps.
https://github.com/majintao/problems/blob/master/gravitee-io/jwt-rsa/jwt-rsa-not-working.md

**Comment by majintao** [comment]
my fault，i get the answer from here. 

https://github.com/gravitee-io/gravitee-policy-jwt

**Comment by majintao** [comment]
but another question， how to generate private_key.per ??

**Comment by brasseld** [comment]
What do you mean by `private_key` ?

And why do you need this private key ? How do you generate your JWT token ?

**Comment by majintao** [comment]
i use your test code  ->io.gravitee.policy.jwt.RSAJWTPolicyTest.getSigner()

**Comment by majintao** [comment]
private String getPublicKey() throws IOException {
        InputStream input = getClass().getClassLoader().getResourceAsStream("id_rsa.pub");
        BufferedReader buffer = new BufferedReader(new InputStreamReader(input));
        return buffer.lines().collect(Collectors.joining("\n"));
    }

    private PrivateKey getPrivateKey() throws Exception {
        File file = new File(getClass().getClassLoader().getResource("private_key.der").toURI());
        FileInputStream fis = new FileInputStream(file);
        DataInputStream dis = new DataInputStream(fis);
        byte[] keyBytes = new byte[(int) file.length()];
        dis.readFully(keyBytes);
        dis.close();

        PKCS8EncodedKeySpec spec = new PKCS8EncodedKeySpec(keyBytes);
        KeyFactory kf = KeyFactory.getInstance("RSA");

        return kf.generatePrivate(spec);
    }

**Comment by brasseld** [comment]
Ok let me ask the question another way:
Who will be responsible to generate the JWT token ?

**Comment by brasseld** [comment]
Sorry, but I didn't get you:

> the authentication server generate the JWT token

> i generate the jwt token with private_key.per

I = authentication server implementation ?

**Comment by brasseld** [comment]
Hi @majintao 

Whats is the status of this issue ?
