### ISSUE TITLE
[management-ui] Glitch in Resource Filtering

### ISSUE THREAD

**Issue by madoke** [gravitee-io/issues#1763]
Hi Team. @timigapa and I just found an issue, when creating resource filtering policies through the management UI: When clicking on the policy item in the list, an edit menu on the right opens, which automatically adds a whitelist policy without asking the user. If the policy is then saved (activate then deactivate) for example, the user will save a policy with a blank whitelist, which means blacklist every path on the api

### Expected Behavior

Blacklist and Whitelist should be Opt-In only in the edit menu

### Current Behavior

Empty Whitelist property is automatically added when editing a resource filtering policy

### Possible Solution

Don't add the whitelist nor the blacklist properties automatically to the resource filtering policy, just leave the +Add button in the edit screen

### Steps to Reproduce (for bugs)

1. Using an existing or new API with more than 1 endpoint (/health and /info for example)
2. Go to Administration -> Choose your API -> Click Design -> Click Policies
3. Add a new Resource Policy (Blacklist and Whitelist properties are automatically added)
4. Blacklist /your-api/health, Remove the Whitelist, save and deploy
5. Verify that /health  returns 403 and /info doesnt
6. Go back to the Policies, Click the Resource filtering policy added previously and verify that the whitelist property has been added
7. Click the ✓ checkmark to disable the policy then deploy your api, then click the || pause to re-enable the policy, then deploy again
8. Verify that all endpoints return 403 because an empty Whitelist property has been added to your policy and saved without explicitly clicking save

Video Demonstrating Steps:
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/185598/50293668-05b15e80-046c-11e9-8071-0e06ab2e47aa.gif)

### Context

I was trying to protect a single resource with gravitee and ended up blocking the entire API

### Your Environment

* Version used: Gravitee Management UI 1.18.1
* Browser Name and version: Firefox/Chrome Latest Versions
* Operating System and version: Mac OS

**Comment by brasseld** [comment]
Hello guys,

This has been already fixed by a previous issue: https://github.com/gravitee-io/issues/issues/1511

Closing it for duplicate.
