### ISSUE TITLE
[repository] [jdbc] Any Plan in Road-map to enable SQL Server support

### ISSUE THREAD

**Issue by Sudhanshus2020** [gravitee-io/issues#1772]
### Expected Behavior
Do you have any plan in Road-map to enable SQL Server support

### Current Behavior
As of now it is not supporting SQL Server

**Comment by brasseld** [comment]
Hi @Sudhanshus2020 

Sql server support must probably be part of jdbc repository.
Did you had a look to it ? Perhaps you can provide such support ?

**Comment by Sudhanshus2020** [comment]
HI @brasseld,

With existing JDBC component we are facing issues, main cause of issues with exiting code is, it is using key-words as columns name that's why component is not able to create Tables as well as not able to execute SQL.
Actually I am still not aware with the IMPACT of this change that's why I asked you guys about Road-Map.
If you guys can share the Schema/ER Diagram then we can figure out the impact and work out to enable SQL server support.

**Comment by brasseld** [comment]
Hi @Sudhanshus2020 

We are using Liquibase to manage the database schema.
Please have a look to https://github.com/gravitee-io/gravitee-repository-jdbc/tree/master/src/main/resources/liquibase

Perhaps you can share a stacktrace to see what are the reserved keywords for SQL server ?

**Comment by brasseld** [comment]
Hi @Sudhanshus2020 

Any news here ?

**Comment by Sudhanshus2020** [comment]
Hello @brasseld,
Apologies for late replay, here is the update...

I have gone through the code and DB Schema, we need to modify 3 things to enable SQL Server support:
 1.  Need to provide provision to warp `keywords` with the escape character as per the DB provider, in case of SQL Server it is `[]`.
2. As some of the column name is the keywords that's why Liquibase  is not able to create tables, so I have converted Liquibase file to SQL file and I am able to create require table.
3. One thing which again require manipulation in code is, SQL server doesn't have direct Boolean datatype so we need to modify below code but also need to check how it will support backward compatibility.
In below code we need to modify the where clause which is `where async = true` with `where async = 'true'`, however I didn't check will this work with MySQL or not, I hope it should. 

```
 //class JdbcRateLimitRepository
  public Iterator<RateLimit> findAsyncAfter(long timestamp) {
        final List<RateLimit> items = jdbcTemplate.query("select " + escapeReservedWord("key") + ", counter, last_request, reset_time, created_at, updated_at, async "
                        + " from ratelimit "
                        + " where async = true and updated_at > ?"
                , MAPPER
                , timestamp
        );
        return items.iterator();
    }
```

As of now after performing above modifications, I am able to consume the gateway, management-ui, management-core with SQL Server DB as well as Azure SQL Server.

Let me know what you thought, how we can implement these changes efficiently.

**Comment by brasseld** [comment]
Hi @Sudhanshus2020 

Can you tell us what are the keywords we have to protect ?
Did you try to update the `escapeReservedWord()` method to set the escape character for mssql? See https://github.com/gravitee-io/gravitee-repository-jdbc/blob/master/src/main/java/io/gravitee/repository/jdbc/common/AbstractJdbcRepositoryConfiguration.java#L108

About boolean column, and according to this [post](https://dba-presents.com/index.php/liquibase/29-liquibase-3-3-x-data-types-mapping-table), liquibase is using the bit field type to handle boolean values. Is it the case for you ? Why did you map it to a string (`'true'`)?
From my point of view (I do not know MSSQL very well) the mssql driver must handle and convert boolean column automatically to a bit column.

**Comment by brasseld** [comment]
Ok, I think the `findAsyncAfter()` method should be refactor to something like this:

```java
    @Override
    public Iterator<RateLimit> findAsyncAfter(long timestamp) {
        final List<RateLimit> items = jdbcTemplate.query("select " + escapeReservedWord("key") + ", counter, last_request, reset_time, created_at, updated_at, async "
                        + " from ratelimit "
                        + " where async = ? and updated_at > ?"
                , MAPPER
                , true
                , timestamp
        );
        return items.iterator();
    }
```

To let the driver doing its stuff (converting from boolean to bit).

WDYT ?

**Comment by Sudhanshus2020** [comment]
> Ok, I think the `findAsyncAfter()` method should be refactor to something like this:
> 
> ```java
>     @Override
>     public Iterator<RateLimit> findAsyncAfter(long timestamp) {
>         final List<RateLimit> items = jdbcTemplate.query("select " + escapeReservedWord("key") + ", counter, last_request, reset_time, created_at, updated_at, async "
>                         + " from ratelimit "
>                         + " where async = ? and updated_at > ?"
>                 , MAPPER
>                 , true
>                 , timestamp
>         );
>         return items.iterator();
>     }
> ```
> 
> To let the driver doing its stuff (converting from boolean to bit).
> 
> WDYT ?

Above recommendation will definitely work.

**Comment by Sudhanshus2020** [comment]
> Hi @Sudhanshus2020
> 
> Can you tell us what are the keywords we have to protect ?
> Did you try to update the `escapeReservedWord()` method to set the escape character for mssql? See https://github.com/gravitee-io/gravitee-repository-jdbc/blob/master/src/main/java/io/gravitee/repository/jdbc/common/AbstractJdbcRepositoryConfiguration.java#L108
> 
> About boolean column, and according to this [post](https://dba-presents.com/index.php/liquibase/29-liquibase-3-3-x-data-types-mapping-table), liquibase is using the bit field type to handle boolean values. Is it the case for you ? Why did you map it to a string (`'true'`)?
> From my point of view (I do not know MSSQL very well) the mssql driver must handle and convert boolean column automatically to a bit column.

Yes, we need to modify code as mentioned below:
**Previous Code:**
```
    private static char escapeReservedWordsChar = '`';

    public static String escapeReservedWord(final String word) {
        return escapeReservedWordsChar + word + escapeReservedWordsChar;
    }

    public static void setEscapeReservedWordFromJDBCUrl(final String jdbcUrl) {
        if (jdbcUrl != null && "postgresql".equals(jdbcUrl.split(":")[1])) {
            escapeReservedWordsChar = '\"';
        }
    }
```
**New Code:**
```
    private static char escapeReservedWordsPrefixChar = '`';    
    private static char escapeReservedWordsSufixChar = '`';
    
    public static String escapeReservedWord(final String word) {
        return escapeReservedWordsPrefixChar + word + escapeReservedWordsSufixChar;
    }

     public static void setEscapeReservedWordFromJDBCUrl(final String jdbcUrl) {
        if (jdbcUrl != null && "postgresql".equals(jdbcUrl.split(":")[1])) {
        	escapeReservedWordsPrefixChar = '\"';
        	escapeReservedWordsSufixChar = '\"';        	
        }else if (jdbcUrl != null && "sqlserver".equals(jdbcUrl.split(":")[1])) {
        	escapeReservedWordsPrefixChar = '[';
        	escapeReservedWordsSufixChar = ']';        	
        }
    }
```
In above recommendation, I have provisioned to escape reserve word if the prefix and suffix are distinct.

**Comment by brasseld** [comment]
So, with this change, it is working as expected?
Please confirm

**Comment by brasseld** [comment]
Sure, no problem @Sudhanshus2020 

Let's do that when you will be back!
Enjoy your holidays ;)

**Comment by Sudhanshus2020** [comment]
Hi @brasseld,
In testing I have got some issues, please find below list:
- There are 2 more keywords available in SQL which are `plan` & `view`, we also need to warp these keywords with `escapeReservedWord` method.

I have done above modification in my local code and after that, I am able to successfully validate end-2-end API configuration with OAuth2 using keycloak adapter and with keyless plan as well, in addition to this I have also applied `DYNAMIC_ROUTING` & `TRANSFORM_HEADER` policies in API.

Till now I have done 3 major modification in code, which are:
 1.  Updated `setEscapeReservedWordFromJDBCUrl` method as mentioned in above trail.
 2.  Updated `findAsyncAfter` as recommended by you
 3. Support `plan` & `view` keywords.

Should I send you merge request for above modification, WDYT ?
If there are any specific testcases you want me to execute let me know.

**Comment by brasseld** [comment]
Hi @Sudhanshus2020 

Please tell me what you've done for 3) I will update source code from my branch.

**Comment by Sudhanshus2020** [comment]
> Hi @Sudhanshus2020
> 
> Please tell me what you've done for 3) I will update source code from my branch.

I have modified 3 files which is attached in the below zip.

Below are the file names which exist at `\src\main\java\io\gravitee\repository\jdbc\management` :
 - JdbcApiKeyRepository.java
 - JdbcApiRepository.java
 - JdbcSubscriptionRepository.java

For changes refer here [ChangesForKeywords.zip](https://github.com/gravitee-io/issues/files/2732224/ChangesForKeywords.zip)

**Comment by brasseld** [comment]
Now the best would be to find an embedded version of SQLServer for Java to automatically run repository tests for sqlserver.

But I did not found any solution for this :(

**Comment by Sudhanshus2020** [comment]
> Now the best would be to find an embedded version of SQLServer for Java to automatically run repository tests for sqlserver.
> 
> But I did not found any solution for this :(

Even, I haven't found.

**Comment by brasseld** [comment]
Meaning that we will not being able to automatically test sqlserver support from our CI :(

**Comment by Sudhanshus2020** [comment]
> Meaning that we will not being able to automatically test sqlserver support from our CI :(

Have you merge the code in master ?

**Comment by NicolasGeraud** [comment]
hi @Sudhanshus2020 until we found a solution to be try sqlserver inside our build process, we are not able to merge this PR.

I include it in milestone 1.23 and add the label "in review". We will try to find a solution together.

**Comment by aelamrani** [comment]
I changed the status to `on hold` til we find a solution to really review with integrated tests

**Comment by brasseld** [comment]
One solution would be to play with https://www.testcontainers.org/ while running tests.

**Comment by Sudhanshus2020** [comment]
> One solution would be to play with https://www.testcontainers.org/ while running tests.

This is pretty cool 👍
