### ISSUE TITLE
[portal] Unable to authenticate an LDAP user

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#1782]
### Expected Behavior

we should be able to use `()` in user search filter
### Current Behavior
`java.lang.IllegalArgumentException: Cannot pass null or empty values to constructor` with the following config : 
```
user-search-filter: "(uid={0})"
```

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/issues/issues/1804
