### ISSUE TITLE
[portal] Creating a mocked API - Backend target is required

### ISSUE THREAD

**Issue by lusoalex** [gravitee-io/issues#179]
Hello,

I want to create an API into gravitee portal, which will be only used to mock a call.

So in this use case, i do not have a real backend to call, but when i want to create the API into gravitee, the backend is a mandatory field.
_Currently i input http://mock.com..._

How could we manage it?

**Comment by NicolasGeraud** [comment]
Hi,

Do you want to permanently call your mock or is it a temporary situation? (I hope it's temporary :) ).

In my point of view your way is ok, when your real api will be deployed you'll just have to register it as an endpoint.

Gravitee.io is a solution to manage your apis, so a backend will always be mandatory.

**Comment by lusoalex** [comment]
Yes that's a well a temp solution.
So that's not a problem to keep it like that.

Thanks ;)
