### ISSUE TITLE
[management ]/apis/_search : desynchronization between search indexes with management-API in multi-instances

### ISSUE THREAD

**Issue by sjoss** [gravitee-io/issues#1798]
### Expected Behavior

when we call /apis/_search, we expected to have always the same result, with one or many instances of 
management-API.

### Current Behavior

Actualy , if we have multi-instances of management-api on kubernetes, /apis/_search return a different result depending on the management-API instance

### Steps to Reproduce (for bugs)

1. use a env with multiple instances of management-API (2 instances)
2. Create an API and deploy it 
3. Go to search API (www.yourAPIUI.comI//#!/apis?view=results&q=test)
4. refresh the page:  search not return the same result

### Context

we use this resource for an admin job => actualy we replace it with findAll and a post filter.

### Your Environment

* Version used: 1.20.9
* Browser Name and version: chrome
* Operating System and version: Linux

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/issues/issues/2166
