### ISSUE TITLE
[management-ui] Fix menu display issue

### ISSUE THREAD

**Issue by GGui** [gravitee-io/issues#1799]
When we resize the browser window, we can note a display issue of the admin menu

**Comment by brasseld** [comment]
Hi @GGui 

Can you explain what is the issue here ? I'm not able to reproduce....

**Comment by GGui** [comment]
When the horizontal is appear in the menu, the menu is displayed like this:

![image](https://user-images.githubusercontent.com/2779595/50935212-8f50bc80-146b-11e9-871f-c21a09f3be01.png)
