### ISSUE TITLE
[management-api] UPPERCASE file extension rejected when trying to import it from documentation page

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#18]
_From @M3lkior on February 11, 2016 15:16_

.MD, .RAML file extension impossible to import from documentation page

The web-ui only accept lowercase extension, without displaying message to user.
The browser console show the error : 

The document extension is not managed:MD

_Copied from original issue: gravitee-io/gravitee-management-webui#93_

**Comment by aelamrani** [comment]
Not reproductible on version 1.6
