### ISSUE TITLE
[management-api] Fine-grained rights management

### ISSUE THREAD

**Issue by lusoalex** [gravitee-io/issues#180]
Hello,

In order to be smoother on user rights management, what do you think about managing Group API permissions instead of managing them one by one.

Here's some explanations :

APIs
=================== 

Considering we have several APIs

| API      |
| :------- |
| Product catalog |
| Price & Stock|
| Order |
| Payment|
| Production|
| Transport|
| Turnover|

API Grouping
=================== 
I expect to group several API into groups

| GROUP      | API             |
| :-------   | :----           | 
| E-commerce | Product Catalog | 
| E-commerce | Price & Stock   | 
| E-commerce | Order           |
| E-commerce | Payment         |
| Supply     | Order           |
| Supply     | Production      |  
| Supply     | Transport       |  
| BI         | Product Catalog |  
| BI         | Turnover        |

Role creations
=================== 
Now i want to create a role which will be composed of permissions :

 **E-commerce API consumer role** giving access to :

| GROUP         | Scope        | Create | View | Edit | Delete
| :-------         | :---            | :---      | :---   | :---  | :---
| E-commerce| API             | no       | yes    | no    | no
| E-commerce| Members   | no       | no     | no    | no
| E-commerce| Dev Portal | no       | no     | no    | no
| E-commerce| Analytics   | no       | no     | no    | no
| E-commerce| Api Key      | no       | no     | no    | no

**E-commerce API admin role** giving access to :

| GROUP         | Scope        | Create | View | Edit | Delete
| :-------         | :---            | :---      | :---   | :---  | :---
| E-commerce| API             | yes      | yes    | yes  | yes
| E-commerce| Members   | yes      | yes    | yes  | yes
| E-commerce| Dev Portal | yes      | yes    | yes  | yes
| E-commerce| Analytics   | yes      | yes    | yes  | yes
| E-commerce| Api Key      | yes      | yes    | yes  | yes
| BI                  | API             | no       | yes    | no   | no 
| BI                  | Dev Portal | no       | yes    | no   | no 

**Please note that if an API is public, it must be considered as viewable by everyone. So the view permission has sense only for private API**

etc...

User role
===================
Now we just need to give roles to our users

| USERS      | ROLE            |
| :-------   | :----           | 
| User A     | E-commerce API consumer role | 
| User B     | E-commerce API consumer role | 
| User B     | Supply API consumer role    | 
| User C     | Supply API admin role    | 

etc...

**Comment by NicolasGeraud** [comment]
Hi,

Create custom roles is definitily a a good idea. The permissions system has been developed to allow that.

Another approach would be to manage access like [Bitbucket](https://confluence.atlassian.com/bitbucket/grant-users-and-groups-access-243335345.html) : 
you create groups : 
 - _Ecommerce Api consumers_ with user A and B
 - _Supply API consumers_ with user B
 - _Supply API admins_ with user C

You add the group _Ecommerce Api consumers_ with role _API consumer_ on each ECommerce APIs

This way, I think we could easily create a global _API Admins_ , _API consumers_ without having to group your API.

Wdyt ?

**Comment by lusoalex** [comment]
Hi,

I think that's a better way to manage it.
Look like linux user's groups.

We manage group of user and give roles to group.
It will be easier to manage, because closer to human organization.

So to resume : 

- We create groups of users (eg E-commerce API consumer)
- An user can belong to several grousp _(in case of permission conflicts, the higher level should be kept)_
- We give API permission to a group

That's it?

How do you expect to manage ADMIN Group?
I think each time a new API is created, it will be boring to add "admin role" on the new API.

Alex.

**Comment by NicolasGeraud** [comment]
Perhaps we could have checkbox `default`on group, if checked, you choose a role and after that, this group with this role will be added every time you create a new API/Application ?

**Comment by lusoalex** [comment]
Hello,

Yes de default checkbox is needed to ease management of APIs.

I was playing with my Synology NAS, and i looked how rights were managed.
There's an online demo here : https://a91.demo.synology.de:5001/

We can first create groups rights : 
<img width="1000" alt="capture d ecran 2016-07-29 a 16 21 22" src="https://cloud.githubusercontent.com/assets/16895682/17251584/b4b804a2-55a9-11e6-848f-cc1b3d627474.png">

**_Note that there's several tabs to manage differents kind of rights._**

Then you can create an user and set him one or more groups : 
<img width="1102" alt="capture d ecran 2016-07-29 a 16 22 31" src="https://cloud.githubusercontent.com/assets/16895682/17251624/db1a8444-55a9-11e6-8265-97e456a2737a.png">

And finally, you can override some permissions to your user : (should not be often used) 
<img width="1106" alt="capture d ecran 2016-07-29 a 16 22 44" src="https://cloud.githubusercontent.com/assets/16895682/17251666/006e3150-55aa-11e6-992d-e91257dd8f2b.png">

**_Note that the user rights management screen are the same than the group..._**

Finally we can imagine the same thing, create a group "E-commerce" and having a tab : 

- To give create/edit/view/delete rights on APIs
- To give create/edit/view/delete on some Applications
- To give permissions on "deploy" button?
- etc...

Wdyt?

**Comment by lusoalex** [comment]
A feature which is not available into this demo but well in my current NAS : 
we can select an user and ask to see applicated rights. (Usefull when we have some doubts between group/user rights).

**Comment by NicolasGeraud** [comment]
Hum ...

This means manage permissions by usergroup ?

  - I think a usergroup must be associated with a role on each api (and a default role).
So we need a screen where you could create usergroup (add user to a group) and define a default role for this group.
  - Another screen when you can create roles

And thats all. In the member section of api and application, you could search group and user, and override their default role.

@tcompiegne @brasseld  ?

**Comment by lusoalex** [comment]
Hello,
Yes so in group screen you have a tab to select roles.
And that means another screen to manage role permissions.
