### ISSUE TITLE
[reporter] [kafka] reporter dont work if configuration is not in  gravitee.yml

### ISSUE THREAD

**Issue by sjoss** [gravitee-io/issues#1803]
### Expected Behavior

we want configure kafka whith environement var for Kubernetes like : 
```
gravitee_reporters_kafka_topic: "topicName"
gravitee_reporters_kafka_hosts_0: "host"
gravitee_reporters_kafka_type_0: "log"
gravitee_reporters_kafka_type_2: "request"
gravitee_reporters_kafka_settings_acks: "1"
gravitee_reporters_kafka_settings_security.protocol: "SASL"
gravitee_reporters_kafka_settings_sasl.mechanism: "PLAIN"
gravitee_reporters_kafka_settings_sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule required xxxxxxx;"
```

### Current Behavior

if we use gravitee.yml, we can configure the kafka settings in the  reporter
if we use envvar like `gravitee_reporters_kafka_settings_sasl.mechanism: "PLAIN"` , we cannot : gravitee_reporters_kafka_settings_.... is not in env

### Steps to Reproduce (for bugs)

1.install plugin
2. use envvar without gravitee.yml

### Context

We cannot use the reporter : all configuration is in envvar
### Your Environment

* Version used: 1.20.9
* Browser Name and version: chrome
* Operating System and version: Linux

**Comment by sjoss** [comment]
in the PR https://github.com/gravitee-io/gravitee-reporter-kafka/pull/5, I have a error 
`security/snyk - pom.xml (gravitee.io) — 7 new vulnerable dependency paths`
when I follow the link , snyk say : `Unable to display this organisation`

**Comment by brasseld** [comment]
Fixed by https://github.com/gravitee-io/gravitee-reporter-kafka/pull/5
