### ISSUE TITLE
[gateway] API is down when a healthcheck failed

### ISSUE THREAD

**Issue by kevinimbrechts** [gravitee-io/issues#1807]
Hi,
I think there is a problem with Gravitee when a healthcheck failed. In fact, when a healthcheck is down, the API return 503 error. If I disable or if I fix healthcheck, API works again.

Also, it would be interesting to send a mail when a healthcheck is failing. I think this is exist (cf https://github.com/gravitee-io/issues/issues/822) but I didn't find the "ALERTS" section like here https://medium.com/graviteeio/gravitee-io-alert-engine-ae-is-out-f735ea9b6686

### Expected Behavior
If a healthcheck failed, an email is sent and the API MUST continue to work properly.

### Current Behavior
If a healthcheck failed, API return 503 error when I call her with a REST client.

### Steps to Reproduce (for bugs)
1. Configure healthcheck with a bad assertion
2. Try to call the API with a REST client
3. API return a 503 error

### Your Environment
* Version used: 1.21.2 with Docker (comes from Docker Hub)

Thank you ! And I wish you all a happy new year.

**Comment by brasseld** [comment]
Hi Kevin,

Yes, active health-check is used to manage load-balancing algorithm for a group of endpoints.
If health-check is failing for X consecutive times, the endpoint is excluded from the group.
If you have a single endpoint and HC fails, that's the reason why you get a 503 from the API gateway.

**Comment by brasseld** [comment]
For alerting, it is an additional addon provided by Graviteesource within support subscription.

**Comment by brasseld** [comment]
And happy new year 🎆

**Comment by brasseld** [comment]
Hi @kevinimbrechts 

Is this clear for you ?

**Comment by kevinimbrechts** [comment]
Hi @brasseld, yeah it's clear for me. Thank you :)
