### ISSUE TITLE
[gateway] Unable to get the client IP address

### ISSUE THREAD

**Issue by Sudhanshus2020** [gravitee-io/issues#1816]
### Expected Behavior
API Gateway should share the client/caller ip address.

### Current Behavior
We are not able to get the client original ip address in the API, we are always getting the IP address of API gateway. 

### Possible Solution
We can provide the client IP address in any header.
May be gravitee has some inbuilt feature for this, please share if gravitee have such feature. 

### Context

Actually we are auditing all the incoming request, so we want the client/caller IP address.

**Comment by brasseld** [comment]
Hi @Sudhanshus2020 

Is there any X-Forward-* header send by consumers or by reverse proxy / load-balancer in front of gateway ?

**Comment by Sudhanshus2020** [comment]
> > Hi @Sudhanshus2020
> > Is there any X-Forward-* header send by consumers or by reverse proxy / load-balancer in front of gateway ?
> 
> Hi @brasseld ,
> No we are not sending any such headers, it is the end customer which is sending the request.
> Below snippet demonstrate request origin.
> ![image](https://user-images.githubusercontent.com/1983474/51255321-07b60100-19c9-11e9-84c8-d6b20aedb934.png)

Hi @brasseld,
I didn't receive any response, so I'd like to make sure that you have seen my notification.
Your response will really help us.

**Comment by brasseld** [comment]
The API Gateway does not support correctly X-Forward headers.

I assume that the API Gateway must have to put its IP address in the X-Forwarded-For header before dispatching the request to the backend.

Then the backend must have a look to this X-Forwarded-For request header and select the first IP in the list (which should be the client IP).

Any pull request for this is welcomed.

WDYT ?

**Comment by Sudhanshus2020** [comment]
> The API Gateway does not support correctly X-Forward headers.
> 
> I assume that the API Gateway must have to put its IP address in the X-Forwarded-For header before dispatching the request to the backend.
> 
> Then the backend must have a look to this X-Forwarded-For request header and select the first IP in the list (which should be the client IP).
> 
> Any pull request for this is welcomed.
> 
> WDYT ?

I am getting below headers in my backend API if it is forward via API Gateway

=== Headers ===
content-type = application/json
cache-control = no-cache
postman-token = 58d5cf5a-621a-439e-81a3-7df6fd7d751b
user-agent = PostmanRuntime/7.6.0
accept = */*
host = 172.30.40.85:3001
accept-encoding = gzip, deflate
content-length = 2
x-gravitee-transaction-id = d67d523f-d3c1-447d-bd52-3fd3c1947da8
=== End Headers ===

**Can I use Transform Header policy by any chance to pass the client IP to my backend API ?**

**Comment by brasseld** [comment]
No way, we are not providing client IP from execution context.

**Comment by brasseld** [comment]
The gateway must add or update the `X-Forwarded-For` header to include its own IP and the list of IPs provided by the incoming HTTP header.

**Comment by brasseld** [comment]
{#request.remoteAddress} should provide the client IP.

**Comment by Sudhanshus2020** [comment]
> {#request.remoteAddress}

Hello @brasseld ,
In which version this feature is available ?
