### ISSUE TITLE
[management] Duplicated users after upgrading to 1.21.x

### ISSUE THREAD

**Issue by philippej13** [gravitee-io/issues#1828]
After upgrading from 1.20.3 to 1.21.2, when authenticating on the UI, Graviteeio don't recognize the LDAP users already registered. So, a new user is created with the same email.

**Comment by NicolasGeraud** [comment]
Can you please share your ldap config ?

**Comment by philippej13** [comment]
- type: ldap
      context-source-username: "XXXX"
      context-source-password: "XXXX"
      context-source-url: "ldap://localhost:389"
      context-source-base: "OU=SOC,DC=company,DC=interne,DC=fr" # the context source base
      user-dn-patterns: "mailNickname={0}"
      user-search-base: ""
      user-search-filter: "sAMAccountName={0}"
      user-search-objectclass: "user"

**Comment by satare** [comment]
Hello, 
Same Thing here. 
BTW, First name & Last Name were reversed on previous versions (my first name was on the lastName field), but are now the right way.

**Comment by philippej13** [comment]
It seems that it happens only with LDAP users who have an email with mixed letters case (ex: laurent.BLANC, Jean.Dupont ...)

**Comment by NicolasGeraud** [comment]
fixed by #2091 

I close this issue.
