### ISSUE TITLE
[am-gateway] Cannot access the /oidc for Admin security domain.

### ISSUE THREAD

**Issue by charleech** [gravitee-io/issues#1830]
As mention at [Admin security domain](https://docs.gravitee.io/am/2.x/am_userguide_admin_domain.html) as 

> a default security domain called `admin` security domain

When access to `https://my-host:port/am/admin/oidc/.well-known/openid-configuration` , it give a 404.

```bash
curl -X GET -v -k \
https://my-host:port/am/admin/oidc/.well-known/openid-configuration

< HTTP/1.1 404 Not Found
< Server: nginx/1.15.8
< Date: Fri, 18 Jan 2019 02:00:22 GMT
< Content-Type: text/html;charset=iso-8859-1
< Content-Length: 0
< Connection: keep-alive
< Cache-Control: must-revalidate,no-cache,no-store
```
The `am-management-api` is behind the `nginx` by following the [gravitee-docker/platform/nginx/nginx.conf](https://github.com/gravitee-io/gravitee-docker/blob/master/platform/nginx/nginx.conf).

``` Nginx
  upstream gio-am-gateway {
    server gio-am-gateway:8092;
  }

  upstream gio-am-mgmt-api {
    server gio-am-mgmt-api:8093;
  }

  upstream gio-am-portal {
    server gio-am-portal:80;
  }
  server {
    location /am/ui/ {
      proxy_pass http://gio-am-portal/;
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header   X-Forwarded-Host $server_name;
      sub_filter '<base href="/"' '<base href="/am/ui/"';
      sub_filter_once on;
    }

    location /am/management/ {
      proxy_pass http://gio-am-mgmt-api/management/;
      proxy_redirect http://$host:$server_port/management/ /am/management/;
      proxy_cookie_path /management /am/management;
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header   X-Forwarded-Host $server_name;
    }

    location /am/admin/ {
      proxy_pass http://gio-am-mgmt-api/admin/;
      proxy_redirect $scheme://$http_host/admin/ $scheme://$http_host/am/admin/;
      proxy_cookie_path /admin /am/admin;
      proxy_set_header   Host $http_host;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Forwarded-Server $host;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header   X-Forwarded-Host $http_host;
      proxy_set_header   X-Forwarded-Proto $scheme;
    }

    location /am/ {
      proxy_pass http://gio-am-gateway/;
      proxy_redirect $scheme://$http_host/apim/ $scheme://$http_host/apim/;
      proxy_redirect $scheme://$http_host/ $scheme://$http_host/am/;
      proxy_cookie_path / /am;
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Forwarded-Server $host;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header   X-Forwarded-Host $http_host;
      proxy_set_header   X-Forwarded-Proto $scheme;
      proxy_set_header   X-Forwarded-Path /am;
    }
}
```

### Expected Behavior
The system should return the `OpenID Connect endpoints`.

### Current Behavior
It give a 404.

### Possible Solution
N/A

### Steps to Reproduce (for bugs)
1. Start the `am-gateway`, `am-management-api` and `am-management-ui` with default configuration.
2. Access the `https://my-host:port/am/admin/oidc/.well-known/openid-configuration`.

### Context
I've tried to login as admin to get the `access-token` and evaluate the [Management API](https://docs.gravitee.io/am/2.x/am_management_api_documentation.html)

### Your Environment
* Version used: 
  The docker tag `2` for all of AM component
  * graviteeio/am-gateway:2
  * graviteeio/am-management-api:2
  * graviteeio/am-management-ui:2
* Browser Name and version: 
  * cURL
* Operating System and version:
  * Based on the docker image with command inside the running container  `cat /etc/*release`
  ```
  3.8.1
  NAME="Alpine Linux"
  ID=alpine
  VERSION_ID=3.8.1
  PRETTY_NAME="Alpine Linux v3.8"
  HOME_URL="http://alpinelinux.org"
  BUG_REPORT_URL="http://bugs.alpinelinux.org"
  ```

**Comment by brasseld** [comment]
Hi @charleech 

There are good chance you're hitting this issue: https://github.com/gravitee-io/graviteeio-access-management/issues/488

Also referenced from https://github.com/gravitee-io/graviteeio-access-management/issues/495

We are releasing AM 2.2. This version is including a fix to this issue.

**Comment by charleech** [comment]
Hi @brasseld 

Thank you for quick response. I'm looking forward to using the latest and greatest version.

**Comment by brasseld** [comment]
Ok, I'm closing the issue since it's a duplicate

**Comment by charleech** [comment]
I apologize for disturbing you. 

I've pulled the `graviteeio/am-gateway:2`, `graviteeio/am-management-api:2` and `graviteeio/am-management-ui:2` which is a latest version as `2.2`

```bash
REPOSITORY                   TAG  IMAGE ID      CREATED       SIZE
graviteeio/am-management-ui  2    b4b673442d9c  15 hours ago  29MB
graviteeio/am-management-api 2    5e148886e4e6  15 hours ago  174MB
graviteeio/am-gateway        2    8687de4fec48  15 hours ago  151MB
```

When access to `https://my-host:port/am/admin/oidc/.well-known/openid-configuration` , it still give a `404`. Could you please help to advise further?

**Comment by charleech** [comment]
Hi @tcompiegne ,

Thank you for your quick response. I'm cleared now.
