### ISSUE TITLE
[management] Add pagination to /apis/:id/events

### ISSUE THREAD

**Issue by vdusauto** [gravitee-io/issues#1835]
Without pagination, APIs modified a certain number of times become difficult to render in UI/audits/history tab as there are a lot of JSON definition to render 

### Expected Behavior
Allow retrieval of latest 10 changes for instance

### Current Behavior
No pagination

### Possible Solution
Add pagination

### Context
Impossible to rollback due to inability to display previous versions

**Comment by aelamrani** [comment]
Duplicate of https://github.com/gravitee-io/issues/issues/1184
