### ISSUE TITLE
[analytics] Show end-user information in API logs

### ISSUE THREAD

**Issue by saraAlizadeh** [gravitee-io/issues#1836]
### Current Behavior
Currently API usage logs shows only the plan and application that access is done via them. (in Analytics  => Logs menu)

### Expected Behavior
It is good to know which user (in IDP linked to a security domain client) has created the request.

**Comment by brasseld** [comment]
It may be done only for grant flows for which the end-user / resource owner is involved into (authorization-code, implicit grant).

We can get the 'user info' from multiple places:
* When doing token introspection, retrieve  the `username` property from introspection response.
* By applying the UserInfo policy and get the `sub` claim
* Read the `sub` claim from any incoming token (JWT).

**Comment by saraAlizadeh** [comment]
> It may be done only for grant flows for which the end-user / resource owner is involved into (authorization-code, implicit grant).
> 
> We can get the 'user info' from multiple places:
> 
>     * When doing token introspection, retrieve  the `username` property from introspection response.
> 
>     * By applying the UserInfo policy and get the `sub` claim
> 
>     * Read the `sub` claim from any incoming token (JWT).

thanks. I got it and I'll close this issue.

**Comment by brasseld** [comment]
I reopen this issue to make it more integrated

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/issues/issues/1948
