### ISSUE TITLE
[management-api] generate api descriptor with swagger

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#184]
- use swagger to document gravitee api
 - generate descriptor during build
 - allow users to download this descriptor from website (using bintray ?)
 - generate postman collection with this descriptor
 - allow users to download this collection from website (using bintray?)

**Comment by tcompiegne** [comment]
That will be useful to generate the API AsciiDoc documentation : 

https://github.com/Swagger2Markup/swagger2markup

**Comment by brasseld** [comment]
Does it mean that we have to generate README.adoc using this plugin ?

**Comment by tcompiegne** [comment]
Maybe an API.adoc that we can deploy to : 

https://docs.gravitee.io/api

**Comment by NicolasGeraud** [comment]
+1 for an api.adoc 

But the goal is to release the api.adoc with the management-api repo, right ?
And include this .adoc into the actual documentation website or into a new one.

**Comment by brasseld** [comment]
👍 for api.adoc

But, IMHO, it should not be included in documentation website. We must provide a dedicated and versioned page for it.
