### ISSUE TITLE
[gateway] Stronger client_secret (and other tokens)

### ISSUE THREAD

**Issue by zdenda-online** [gravitee-io/issues#1847]
Access Management currently uses UUID (custom implementation based on Faster XML) which may not be "strong" enough from a security point of view (even it uses SecureRandom). There is a good article about [UUID strength](https://neilmadden.blog/2018/08/30/moving-away-from-uuids/).

### Expected Behavior
More bits of entropy for client_secret and other tokens. 

### Current Behavior
122 bits of entropy (if understood correctly) current implementation

### Possible Solution
something like (based on article from above)
```
import java.security.SecureRandom;
import java.util.Base64;

public class SecureRandomString {
    private static final SecureRandom random = new SecureRandom();
    private static final Base64.Encoder encoder = Base64.getUrlEncoder().withoutPadding();

    public static String generate() {
        byte[] buffer = new byte[20];
        random.nextBytes(buffer);
        return encoder.encodeToString(buffer);
    }
}
```

### Steps to Reproduce (for bugs)
Create AM client (and let secret be generated) or request auth code (in OAuth2 code grant flow)

### Context
Considering Gravitee.io for PSD2 use-cases which handles bank accounts so security is a big topic.

**Comment by brasseld** [comment]
Hi @zdenda-online 

`RandomBasedGenerator` from FasterXML is based, more or less, on the same algorithm you've shared in your comment, so I'm not sure about the problem here...

**Comment by zdenda-online** [comment]
Hi @brasseld,

my concern was mainly UUID entropy which is 122 bits (128 bits from 16 random bytes lowered by 6 due to fixed variant). [OAuth2 spec says that it must be 128bits (and should be 160bits)](https://tools.ietf.org/html/rfc6749#section-10.10). 

You are right that the algorithm itself of `RandomBasedGenerator` is the same but still uses only 16 bytes. I'm looking at this [source code](https://jar-download.com/artifacts/com.fasterxml.uuid/java-uuid-generator/3.1.4/source-code/com/fasterxml/uuid/impl/RandomBasedGenerator.java).

It is not a big deal for most of the use-cases but when it comes to our use-case with money transfer between banks, we are just kind of paranoid :-)
