### ISSUE TITLE
[portal] Czech localization

### ISSUE THREAD

**Issue by zdenda-online** [gravitee-io/issues#1853]
We need have portal in Czech language. 

### Possible Solution
Implement Czech language (will do it via pull request? ;) )

**Comment by brasseld** [comment]
We are waiting for you ;)

**Comment by zdenda-online** [comment]
I'm on it ;)

**Comment by brasseld** [comment]
Hey @zdenda-online 

Any news about this translation?

Cheers,

**Comment by zdenda-online** [comment]
I'm probably the worst open source contributor of all times. I'm sorry but this is still very low on my priority list :( Hope that gets changed soon. Please let it open and one day it gets done.

**Comment by zdenda-online** [comment]
Hey and it took only half year to add that one file :-)

**Comment by aelamrani** [comment]
Hi @zdenda-online,

We are finalizing the brand new portal and we may need you to review the Czech translation before to validate it. Will you have some time for this? Here the translated file: https://github.com/gravitee-io/gravitee-portal-webui/blob/master/src/assets/i18n/cs.json

Thanks

**Comment by zdenda-online** [comment]
Hi Elamrani, sure I can review. 
I will go through JSON and for the best quality, it would be the best to review it also in the application itself as sometimes some English words may be translated multiple ways and their translation is context-dependent.

Is new portal available on some nighlty deploy so I can also check there? If you don't want to publihs that URL, ask please @brasseld as he can send me directly in Slack message.

**Comment by zdenda-online** [comment]
I see that over time, there were some older fixes that already brought in a few "funny" translations :-) I will fix it all but will need a fully running application itself.

**Comment by aelamrani** [comment]
@zdenda-online here our nightly env: https://v3.nightly.gravitee.io/

Thanks
