### ISSUE TITLE
[general] Basic Authentication

### ISSUE THREAD

**Issue by FerdinaKusumah** [gravitee-io/issues#1870]
(A) -> (B) -> (C)
A is client (Just http GET No validation here)
B is Gravitee (Setup HTTP GET Basic Auth to C)
C is Another backend (Recieved Authorization from B)

How i can implement this model ?

**Comment by brasseld** [comment]
You can do it at endpoint level (C):

<img width="540" alt="capture d ecran 2019-01-29 a 18 43 26" src="https://user-images.githubusercontent.com/133094/51928266-cd4f5980-23f5-11e9-951b-0d3db78808da.png">

**Comment by FerdinaKusumah** [comment]
<img width="676" alt="screen shot 2019-01-30 at 10 49 23" src="https://user-images.githubusercontent.com/19812460/51957073-bef85080-247c-11e9-9b42-243942211f43.png">

But there is no setting headers authorization like that,
am i wrong in configuration ?

Sorry my english is bad

**Comment by brasseld** [comment]
Hi @FerdinaKusumah 

I suppose you're running an old version of gravitee.
Default HTTP headers per endpoint have been releases in 1.22

The other solution in your case is to put the Transform HTTP Headers policy into API's policies.

**Comment by FerdinaKusumah** [comment]
Hi @brasseld,
but currently im running with docker from [this](https://docs.gravitee.io/apim_installguide_docker.html) tutorial

am i wrong get an tutorial ?

**Comment by FerdinaKusumah** [comment]
Hi @brasseld 
now i had an error like this, after updated images in docker hub

<img width="1437" alt="screen shot 2019-01-30 at 22 19 56" src="https://user-images.githubusercontent.com/19812460/51991275-55f4f500-24dd-11e9-9e23-94ac7bc7c449.png">

**Comment by FerdinaKusumah** [comment]
am i missed something ??

**Comment by brasseld** [comment]
do you have any logs ?

**Comment by FerdinaKusumah** [comment]
no, im sorry thats my wrong configuration ..

but can you update latest ui to docker hub ?
i do not receive your new update about this features

![screen shot 2019-01-30 at 23 29 12](https://user-images.githubusercontent.com/19812460/51996219-e3891280-24e6-11e9-9f6f-8eb07f313001.png)

**Comment by brasseld** [comment]
Hi @FerdinaKusumah 

Images are up to date, did you apply a force pull ?

We communicate about this feature through our blog: https://medium.com/graviteeio/first-release-apim-of-the-year-is-here-please-welcome-1-22-fd81d92bf89f

**Comment by brasseld** [comment]
Hi @FerdinaKusumah 

We had some issues while pushing images to docker hub.
It must be good now, please have a try.

Regards,
