### ISSUE TITLE
[am] 403 status code with admin/adminadmin login

### ISSUE THREAD

**Issue by thenapoleon** [gravitee-io/issues#1871]
Using docker example from documentation, when accessing am ui and entering admin/adminadmin login credentials, page is redirected to http://localhost/am/admin/login with 403 http status code (see below response).

HTTP/1.1 403 Could not verify the provided CSRF token because your session was not found.
Server: nginx/1.15.8
Date: Tue, 29 Jan 2019 22:37:20 GMT
Content-Type: text/html;charset=iso-8859-1
Content-Length: 0
Connection: keep-alive
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Pragma: no-cache
X-Frame-Options: DENY
Set-Cookie: JSESSIONID=6gwseprpj72t2mfq3cuxmwjp;Path=/am/admin
Cache-Control: must-revalidate,no-cache,no-store

### Your Environment
* Version used: as per https://docs.gravitee.io/am/2.x/am_installguide_docker.html#gravitee-quickstart
* Browser Name and version: chrome
* Operating System and version: macosx

**Comment by tcompiegne** [comment]
Hi @thenapoleon , how did you launch AM ? with docker-compose ?

**Comment by thenapoleon** [comment]
Yes.

**Comment by brasseld** [comment]
Hi @thenapoleon 

I just had by following https://docs.gravitee.io/am/2.x/am_installguide_docker.html#running_am_in_a_single_line and it works like a charm!

Can you have a try:
1) In private mode (chrome)
2) To delete existing cookies ?

**Comment by thenapoleon** [comment]
ah yep, looks like this was it... thanks!
