### ISSUE TITLE
[portal] Non-localized strings

### ISSUE THREAD

**Issue by zdenda-online** [gravitee-io/issues#1875]
There are few strings that should be localized but are hard-coded (english) within HTML templates. These are:
- "Send a comment to the API Owner" when subscribing application to API (api-subscribe.html)
- "No Documentation. Come back soon." when navigating from top navbar to Documentation
- "All" in API Gallery page (when showing all APIs)

### Expected Behavior
All described texts are localized (localizable)

### Context
Translating portal to CZ but found out that some text is not within .json language definition.
I could partially fix it on my own but I'm not able to provide all translations.

**Comment by brasseld** [comment]
I understand, please fork and fix missing strings (for EN and CZ ).

Let me know when it's done, I will help you to provide translations for FR

**Comment by aelamrani** [comment]
Hi @zdenda-online any news there?

**Comment by zdenda-online** [comment]
> Hi @zdenda-online any news there?

Hi, yes I have on my local computer :-) I'm now kind of "busy' but will do pull request as soon as I have that little time for it :) Hopefully, this week.

**Comment by zdenda-online** [comment]
Im finally finishing cz localization and noticed that this has been already fixed. You are free to close this one
