### ISSUE TITLE
Ask Context path

### ISSUE THREAD

**Issue by FerdinaKusumah** [gravitee-io/issues#1878]
How to add <id> in context path routing,
and how to write it down on a backend path route.

<img width="680" alt="screen shot 2019-01-31 at 16 12 20" src="https://user-images.githubusercontent.com/19812460/52043887-5b9d1a00-2573-11e9-8bf9-207a4d750a73.png">
<img width="725" alt="screen shot 2019-01-31 at 16 14 40" src="https://user-images.githubusercontent.com/19812460/52043889-5c35b080-2573-11e9-9065-3e9659970e2d.png">

thanks in advance

**Comment by aelamrani** [comment]
Hi @FerdinaKusumah 

Why not defining the context path to `/role` here?

**Comment by FerdinaKusumah** [comment]
im sorry what do you mean ?
can i write {id} in sub path route model ?

**Comment by aelamrani** [comment]
I suppose your API here is about role.

So by defining the gateway context path to `/role` you will be able to access to {gateway_host}/role/:id/permissions
