### ISSUE TITLE
[management-api] LDAP users with ADMIN role can't modify all APIs

### ISSUE THREAD

**Issue by bcollard** [gravitee-io/issues#188]
Hello,

Using version 0.17.1
When I am logged in as a ADMIN user, via LDAP mapping, I don't see the the cog-wheel icon on all of the APIs.
Let me know if you need more information or if it is a normal behavior..

**Comment by tcompiegne** [comment]
Hello bcollard,

Can you try the following URL : 

> curl -X GET -H "Authorization: Basic (ldap-user:ldap-password)" "http://localhost:8083/management/user/"

and tell me if the response contains the following authorities : 

> {
>   ...
>   "authorities": [
>     {
>       "authority": "ADMIN"
>     }
>   ],
>   ...
> }

Regards

**Comment by bcollard** [comment]
Yes, it does.

 ```
"authorities" : [ {
    "authority" : "ADMIN"
  } ],
```

**Comment by bcollard** [comment]
I can send you more details like a HAR or any logs, but privately please (working with David B. @AECF)

**Comment by tcompiegne** [comment]
Ok I got my memory back :)

In 0.17.1 only the primary owner and owners can manage their API, so yes it's the normal behavior.

It has changed in version 0.18.0 with the following commit :

[feat(security): Improve permission management](https://github.com/gravitee-io/gravitee-management-rest-api/commit/01fbd73bcba7b636175b59df45d9f65a6c5dbb7f)

In 0.18.0, admin users can now manage all APIs.

Titouan

**Comment by bcollard** [comment]
Ok, thanks. I will test this version from tomorrow.

**Comment by bcollard** [comment]
Yes, it's much better with this latest release. Thanks.
