### ISSUE TITLE
[question] Ask Merge API from multiple endpoint

### ISSUE THREAD

**Issue by FerdinaKusumah** [gravitee-io/issues#1881]
Can we implement merge API from 2 service to one endpoint ?
This platform is awesome
thankyou 😊

**Comment by brasseld** [comment]
You just to define multiple endpoints in your API inside gravitee, and then apply dynamic-routing policy to forward to one or another endpoint.

**Comment by FerdinaKusumah** [comment]
ohh yaa, ok ok 
thank you @brasseld 
😄 👍
