### ISSUE TITLE
[management] Missing option for adding new user

### ISSUE THREAD

**Issue by mknair75** [gravitee-io/issues#1889]
Tried to add a new user through the Gravitee UI and found that only search option available, no add option. This is observed in docker based installation with docker-compose. 

### Expected Behavior
Ability to add a new user and attach to a group. 

### Current Behavior
![image](https://user-images.githubusercontent.com/6468268/52256445-b8664f00-293c-11e9-829f-833602295479.png)

### Possible Solution
Add new users, group users, define roles for users - Associate user with APIs

### Steps to Reproduce (for bugs)
Docker based installation of Gravitee platform 

### Context
Usability

**Comment by brasseld** [comment]
Hi @mknair75 

We are not providing such feature for now. Only available options are:
- Create in-memory users (see `gravitee.yml`)
- Register new users through portal registration page
- Plug authentication to LDAP / AD
- Social authentication (google, github, gravitee AM, ....)

**Comment by mknair75** [comment]
Thank you. Is it possible to integrate AM with API Management? If I understand correctly AM and APIM are two independent modules. How can I use AM capabilities with APIM ?

**Comment by brasseld** [comment]
Sure it's possible.

You just need to create an AM `authentication provider` in APIM (settings > auth provider). Then, you can manage all the users from AM.

**Comment by mknair75** [comment]
Cool ! Thanks !

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/issues/issues/1505
