### ISSUE TITLE
[management-api] The username name is 'undefined' when adding a LDAP user to the API members

### ISSUE THREAD

**Issue by bcollard** [gravitee-io/issues#189]
Hello,

Using version 0.17.1
The username name is 'undefined' when adding a LDAP user to the API members.
See example below:

![2016-08-08 10_42_20-gravitee io portal](https://cloud.githubusercontent.com/assets/9626829/17476198/1197a170-5d5f-11e6-8175-02ef50285e33.png)
![2016-08-08 10_42_32-gravitee io portal](https://cloud.githubusercontent.com/assets/9626829/17476200/160584f2-5d5f-11e6-8f72-f0f4a73e0248.png)
![2016-08-08 10_42_53-nouvelle notification](https://cloud.githubusercontent.com/assets/9626829/17476207/1b2f1f7e-5d5f-11e6-9cfb-c67316ed46dd.png)

**Comment by bcollard** [comment]
And why is the username surrounded by brackets in the 1st popin? is it a mark for LDAP users?

**Comment by tcompiegne** [comment]
Hello bcollard,

It seems to be a bad LDAP attributes mapping. The 1st poping must display : 

> username* (lastname*)

- username : default **uid** ldap field
- lastname : default **sn** ldap field

**Comment by brasseld** [comment]
Please have a try with 0.18

Should be better.

**Comment by bcollard** [comment]
Yes, it's much better with this latest release. Thanks.
