### ISSUE TITLE
[management] Ability to easily put an endpoint in backup mode

### ISSUE THREAD

**Issue by Produits** [gravitee-io/issues#1890]
### Expected Behavior
I would like to be able to easily change the status of an endpoint by API: backup or not, in order to perform maintenance operations on an endpoint without having a service interruption. This mechanism works well but implementation is not simple

### Current Behavior
Currently, I have to:
- retrieve all API information
- change the status of the endpoint
- remove keys that are not accepted by the PUT
- make my call

### Possible Solution
It would be interesting to be able to make a call like this:
PATCH management/apis/:id_api/id_endpoint?backup=true/false

**Comment by Produits** [comment]
The "Out of sync" information is also missing in the GET management/apis/:id_api
This is interesting information since it is necessary to re-deploy the API when the status of the endpoint is changed.

**Comment by Produits** [comment]
Thank you for the answer. It works fine but in the documentation, the response is the same as for a get whereas in fact the response contains just the id and the key is_synchronized.
I think that it ould be better if the is_synchronized key was added in the standard json response

**Comment by brasseld** [comment]
ok, the doc is wrong, the response contains api_id and state property.
