### ISSUE TITLE
[management] After login it does not redirect to the dashboard page.

### ISSUE THREAD

**Issue by charleech** [gravitee-io/issues#1894]
I've pulled the `graviteeio/am-gateway:2`, `graviteeio/am-management-api:2` and `graviteeio/am-management-ui:2` which is a latest version as `2.2`. 

After login it does not redirect to the dash board page.

### Steps to Reproduce
1. Visit `https://host:port/am/ui/`
2. The browser redirect to the `login page`.
3. Enter username/password as `admin/adminadmin.`
4. Click the `login` button.
5. It still at the `login page`.

Note: 
1. I've seen that the cookie named `Auth-Graviteeio-AM` is stored at the browser via the developer tool.
2. I open new tab and visit `https://host:port/am/ui/`, it redirect to the dashboard.
3. I've a chance to debug the network traffic and found that the `POST` to `/am/admin/login` return `302`
<details><summary>Log information</summary><pre>

Request URL: https://<my_host>:<my_port>/am/admin/login
Request method: POST

Request headers: 
Host: <my_host>:<my_port>
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en,th;q=0.7,en-US;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://<my_host>:<my_port>/am/admin/login
Content-Type: application/x-www-form-urlencoded
Content-Length: 131
Connection: keep-alive
Cookie: JSESSIONID=1rnpgkjwuhp53g4wo42slizp2
Upgrade-Insecure-Requests: 1

Response headers: 
HTTP/1.1 302 Found
Server: nginx/1.15.8
Date: Fri, 25 Jan 2019 14:58:16 GMT
Content-Length: 0
Connection: keep-alive
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Thu, 01 Jan 1970 00:00:00 GMT
X-Frame-Options: DENY
Set-Cookie: JSESSIONID=1q8hpx6a4vaed1f6yd94qnnrpr;Path=/am/admin
Set-Cookie: Auth-Graviteeio-AM="Bearer ....";Version=1;Path=/am/management;Expires=Fri, 01-Feb-2019 14:58:16 GMT;Max-Age=604800;Secure;HttpOnly
Location: https://<my_host>:<my_port>/am/admin/authorize?redirect_uri=https://<my_host>:<my_port>/am/ui/login/callback
</pre></details>

### Your Environment
* Version used: 2.2
* Browser Name and version:
  * Firefox 64.0.2 (64-bit) 
  * Chrome Version 71.0.3578.98 (Official Build) (64-bit) 
* Operating System and version: Docker

**Comment by charleech** [comment]
Thank you very much for your help, especially for your time. The latest docker compose works properly.

I also have a chance to investigate further via the browser web developer (the F12) and found that

1. After click the login button, it POST to `/admin/login`.
2. The server response as
    * HTTP status `302` with Location: `.../admin/authorize?redirect_uri=.../ui/login/callback`
    * There are 2 cookies as `JSESSIONID` and `Auth-Graviteeio-AM`
3. The browser redirect to the `.../admin/authorize?redirect_uri=.../ui/login/callback` with GET
    * At this point if the cookie path for the `Auth-Graviteeio-AM` 
       * is a `/`, it is passed via the HTTP request header. The dashboard page display properly.
       * is a `/management`, it is not passed. The login screen has been shown again.

I'm not sure if it is a trouble about my web browser or not. Here is my testing environment: -

1. Linux
   * CentOS Linux release 7.4.1708 (Core) 
   * Firefox 60.4.0esr (64-bit)
2. Windows
   * Windows 10 Home 64 bits
   * Firefox 65.0 (64-bit)
   * Chrome 72.0.3626.81 (Official Build) (64-bit)

I hope this information may be useful.

**Comment by brasseld** [comment]
Hi @charleech 

Does it mean that now everything is working properly?

**Comment by charleech** [comment]
I apologize for the confusion. I would like to confirm that the latest docker compose works perfectly.

Thank you very much. 😃
