### ISSUE TITLE
[management][logs] Unable to locate logs

### ISSUE THREAD

**Issue by nicolasvo** [gravitee-io/issues#1905]
Hi,

I would like to know where the API logs are stored.

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/32842375/52556168-15a24a80-2dec-11e9-9d7c-fa65676216a5.png">

I tried looking into the MongoDB and the ElasticSearch without success.
My temporary solution:
- request API logs in order to get log IDs: http://localhost:8005/management/apis/API-ID/logs?size=200&page=1&from=FROM&to=TO&
- get actual logs with the IDs: http://localhost:8005/management/apis/API-ID/logs/LOG-ID

### Context
My endgoal is to extract the data and use it in Python.

### Your Environment

* Version used: 1.21.2 (latest)
* Browser Name and version: Firefox
* Operating System and version: MacOS High Sierra, Docker Version 2.0.0.2 (30215)

**Comment by brasseld** [comment]
Hi,

Logs are stored in ES within its own index gravitee-logs-yyyyMMdd (something like that ;) )

**Comment by nicolasvo** [comment]
I called the ES API with the gravitee-yyyy.MM.dd index: `curl http://localhost:9200/gravitee-2019.02.11/_search\?q\=\*\&pretty` (i.e. https://www.elastic.co/guide/en/elasticsearch/reference/1.4/_the_search_api.html). Unfortunately, the output is not what I am looking for:
```
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 5436,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "gravitee-2019.02.11",
        "_type" : "monitor",
        "_id" : "AWjbt5lvTvoIaHx1lzDh",
        "_score" : 1.0,
        "_source" : {
          "os" : {
            "cpu" : {
              "percent" : 1,
              "load_average" : {
                "1m" : 3.37,
                "5m" : 2.83,
                "15m" : 1.21
              }
            },
            "mem" : {
              "total_in_bytes" : 2095575040,
              "free_in_bytes" : 83456000,
              "used_in_bytes" : 2012119040,
              "free_percent" : 4,
              "used_percent" : 96
```

I would like to obtain the following:

```
{'id': 'b8d1f9b2-7f91-4020-91f9-b27f91902032',
 'timestamp': 1549877828955,
 'transactionId': 'b8d1f9b2-7f91-4020-91f9-b27f91902032',
 'uri': '/myfirstapi?q=wavy',
 'path': '/myfirstapi',
 'method': 'get',
 'status': 200,
 'responseTime': 1659,
 'apiResponseTime': 1369,
 'requestContentLength': 0,
 'responseContentLength': 605,
 'apiKey': 'ea2a8115-e582-4170-b2de-cb52abddb05c',
 'plan': '7f79b3c5-2b93-43a0-b9b3-c52b9323a09c',
 'application': '5ec480af-5f9d-41a7-8480-af5f9d91a753',
 'localAddress': '172.20.0.5',
 'remoteAddress': '172.20.0.1',
 'endpoint': 'https://api.gravitee.io/echo?q=wavy',
 'gateway': '2be01fb4-d855-4408-a01f-b4d855e408c0',
 'subscription': 'b0c842b7-2442-40bf-8842-b7244260bfdb',
 'metadata': {'2be01fb4-d855-4408-a01f-b4d855e408c0': {'hostname': 'demo-gateway',
   'ip': '172.20.0.5'},
  '5ec480af-5f9d-41a7-8480-af5f9d91a753': {'name': 'Test'},
  '7f79b3c5-2b93-43a0-b9b3-c52b9323a09c': {'name': 'Test'}},
 'host': 'localhost:8000'}
```

At the moment, I could obtain the above by requesting `localhost:8005/management/apis/API-ID/logs/LOG-ID`. If possible, I wish to fetch it directly from a database. Is it in the ES or the MongoDB?

**Comment by brasseld** [comment]
As I said from my previous comment, these data are stored in ES:

> Logs are stored in ES within its own index gravitee-logs-yyyyMMdd (something like that ;) )

You shared a link for ES 1.4, does it mean that you're using this version of ES ?

**Comment by nicolasvo** [comment]
I found them! The previous output had `_type: "monitor"` (the index mostly contains such documents, therefore I mistakenly thought they were the only ones). This time, I called `http://localhost:9200/gravitee-2019.02.11/_search?q=_type:request` in order to fetch requests.

My output:

```
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 101,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "gravitee-2019.02.11",
        "_type" : "request",
        "_id" : "b8d1f9b2-7f91-4020-91f9-b27f91902032",
        "_score" : 1.0,
        "_source" : {
          "gateway" : "2be01fb4-d855-4408-a01f-b4d855e408c0",
          "@timestamp" : "2019-02-11T09:37:08.955Z",
          "transaction" : "b8d1f9b2-7f91-4020-91f9-b27f91902032",
          "method" : 3,
          "uri" : "/myfirstapi?q=wavy",
          "status" : 200,
          "response-time" : 1659,
          "api-response-time" : 1369,
          "proxy-latency" : 1660,
          "request-content-length" : 0,
          "response-content-length" : 605,
          "api-key" : "ea2a8115-e582-4170-b2de-cb52abddb05c",
          "plan" : "7f79b3c5-2b93-43a0-b9b3-c52b9323a09c",
          "api" : "8151b1a2-1c49-4590-91b1-a21c4905905f",
          "application" : "5ec480af-5f9d-41a7-8480-af5f9d91a753",
          "local-address" : "172.20.0.5",
          "remote-address" : "172.20.0.1",
          "endpoint" : "https://api.gravitee.io/echo?q=wavy",
          "path" : "",
          "host" : "localhost:8000"
        }
      },
```

Thanks for the quick answers! Have a good day :)
