### ISSUE TITLE
[identity-provider] [ldap] "Invalid or unknown user" while requesting for a new token

### ISSUE THREAD

**Issue by kgladosz** [gravitee-io/issues#1907]
Hello.
I have a problem regarding LDAP provider in Gravitee.io Access Management 2.2.0.

I am trying to get an access token using LDAP provider. 
I made the same configuration (URL, username, password) as in my Spring Boot application (so I assume it is fine).
I am requesting for a token via postman : http://{gravitee_api_am_host}/{domain}/oauth/token?client_id=client_id&client_secret=client_secret&grant_type=password&username=John Doe&password=admin&scope=openid 
All the time I am getting 
{
    "error": "invalid_grant",
    "error_description": "Invalid or unknown user"
}
I am not sure what is wrong. I assume that this is not a connection problem.
When it comes to configuration, I am thinking about 'User search filter' - I am not really sure what I should put there.
This is my example LDIF file:

# Organizational Units
dn: ou=groups,dc=example,dc=org
objectclass: top
objectclass: organizationalUnit
ou: groups

dn: ou=people,dc=example,dc=org
objectclass: top
objectclass: organizationalUnit
ou: people

# Create People
dn: uid=john,ou=people,dc=example,dc=org
objectclass: top
objectclass: person
objectclass: organizationalPerson
objectclass: inetOrgPerson
cn: John Doe
sn: John
uid: john
userPassword: admin

dn: uid=jihn,ou=people,dc=example,dc=org
objectclass: top
objectclass: person
objectclass: organizationalPerson
objectclass: inetOrgPerson
cn: Jihn Die
sn: Jihn
uid: jihn
userPassword: admin

dn: uid=jahn,ou=people,dc=example,dc=org
objectclass: top
objectclass: person
objectclass: organizationalPerson
objectclass: inetOrgPerson
cn: Jahn Dae
sn: Jahn
uid: jahn
userPassword: admin

# Create Groups
dn: cn=developers,ou=groups,dc=example,dc=org
objectclass: top
objectclass: groupOfUniqueNames
cn: developers
ou: developer
uniqueMember: uid=john,ou=people,dc=example,dc=org
uniqueMember: uid=jihn,ou=people,dc=example,dc=org

dn: cn=managers,ou=groups,dc=example,dc=org
objectclass: top
objectclass: groupOfUniqueNames
cn: managers
ou: manager
uniqueMember: uid=jahn,ou=people,dc=example,dc=org

I am using Apache Directory Studio.
I will just add, that everything works correctly while I am requesting for a token via my spring boot app.
Can you help me with the user search filter issue? Or you can tell me that something else is wrong?
Thanks inadvance!

**Comment by guddutopper** [comment]
is your ssl disbaled in keycloak ? you should disable ssl from th e keycloak portal

**Comment by guddutopper** [comment]
or maybe this client was created in a different realms and there was no user on it ?

**Comment by tcompiegne** [comment]
Hello @kgladosz,

Can you try with this username : `john` instead of `John Doe` ?

@guddutopper, no Keycloak involved here, @kgladosz is using Gravitee.io AM solution.

**Comment by kgladosz** [comment]
I am not using keycloak. I am just getting knowledge about Gravitee, so I have one domain and one client within it. But just right now I saw that I had enabled three providers, so I have changed it only for ldap provider 
![obraz](https://user-images.githubusercontent.com/14069909/52563392-90299500-2e01-11e9-9000-7e520e2ccfca.png)
And now request body looks like this:
{
    "error": "invalid_grant",
    "error_description": "Unable to validate credentials. The user account you are trying to access may be experiencing a problem."
} 
Same for username John Doe/john

**Comment by kgladosz** [comment]
But can you tell me how user search filter should look like? Now I have the default 
![obraz](https://user-images.githubusercontent.com/14069909/52563507-e72f6a00-2e01-11e9-86a2-a04347b02574.png) but I am not sure whether it is correct.

**Comment by tcompiegne** [comment]
According to this message : 

```
{
"error": "invalid_grant",
"error_description": "Unable to validate credentials. The user account you are trying to access may be experiencing a problem."
}
```
You should have some error logs, can you show me your `gravitee.log` file (gateway part) ?

**Comment by kgladosz** [comment]
I am using Docker. 
This is the whole log after requesting for a token:
[api_logs.txt](https://github.com/gravitee-io/issues/files/2851082/api_logs.txt)

**Comment by tcompiegne** [comment]
ok, so your AM gateway docker cannot reach your LDAP server (localhost), you should set LDAP server URL to the IP address of the Docker host.

```
12:48:46.559 [vert.x-eventloop-thread-3] [] ERROR i.g.a.i.l.a.LdapAuthenticationProvider - An error occurs during LDAP authentication
org.ldaptive.provider.ConnectionException: javax.naming.CommunicationException: localhost:389 [Root exception is java.net.ConnectException: Connection refused (Connection refused)]
```
