### ISSUE TITLE
[management] Instances management screen not accessible sometimes

### ISSUE THREAD

**Issue by vmbaaboghe** [gravitee-io/issues#1908]
### Expected Behavior

In the management screen, I should be able to access screen with all instances (<gravitee-ui)/#!/management/instances/ ).

### Current Behavior

Currently I can't access to the management instance screen in one my gravitee installation due to a MongoQueryException. 

### Possible Solution

Missing or insufficient indexes on events collection. 
Currently the request : db.events.find({ "type": { $in: [ "GATEWAY_STOPPED", "GATEWAY_STARTED" ] } } ).count() => 
3548 

### Steps to Reproduce (for bugs)

1. Login to administration
2. Click on gateways
3.
4.

### Your Environment

* Version used: 1.19.2
* Browser Name and version: On all browsers
* Operating System and version:

**Comment by brasseld** [comment]
Hi @vmbaaboghe 

You can apply indexes from https://raw.githubusercontent.com/gravitee-io/gravitee-repository-mongodb/master/src/main/resources/scripts/create-index.js

Regards,

**Comment by brasseld** [comment]
Hi 

Is it ok for you ?

**Comment by vmbaaboghe** [comment]
Hello, 
Thank you for your reply.  We ran the script but our gravitee instance seems slower.  The  instances management screen is still unavailable but it's now due to a timeout.

**Comment by brasseld** [comment]
What do you mean by "we ran the script"? 
Which script are talking about?

**Comment by vmbaaboghe** [comment]
This one => https://raw.githubusercontent.com/gravitee-io/gravitee-repository-mongodb/master/src/main/resources/scripts/create-index.js

**Comment by brasseld** [comment]
Can you tell us which version of MongoDB you're using ?

**Comment by brasseld** [comment]
Ok, got the issue!
We will have a look.

**Comment by vmbaaboghe** [comment]
Thank you !
