### ISSUE TITLE
[gateway] HTTP2 requests are not well handled

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#1913]

**Comment by guddutopper** [comment]
let me explain why this issue has been raised, I have deployed an API over HTTPS on api gateway and i was not able to access it from any browser but I was able to hit the gateway from POSTMAN, to resolve this i set the 'http_alpn' variable to 'false', earlier it was true, now I am able to hit the gateway from both chrome and postman, So I think when both HTTPS and HTTP/2 are enabled them gateway doesnt handle it correctly
