### ISSUE TITLE
[management] [policy] Allow Drag and Drop Copy of Polices between path

### ISSUE THREAD

**Issue by pixelbaker** [gravitee-io/issues#1916]
Hi there,

I am missing the possibility to copy a policy which I have attached to a path to another path.
UX-vise I would love to hold CTRL while dragging a policy over to another path.

Is this something you could implement?

Thanks,
André

**Comment by pixelbaker** [comment]
Thx for the trust. No time. Sorry.

**Comment by brasseld** [comment]
Should be closed by #3895
