### ISSUE TITLE
[management] Group Member Management

### ISSUE THREAD

**Issue by noob3lite** [gravitee-io/issues#1923]
Is there an API Endpoint in Accessmanagement to add and remove User from a group?
The only thing i found so far is to make a request to group update Enpoint with all Userids in the Members Part of the request. 
In you have a lot of users 20.000+ this request is not the best way in my opinion. 
It would be nice to have an endpoint with group Id and userid to add or remove just one user

**Comment by brasseld** [comment]
Swagger for docs.gravitee.io must be updated

**Comment by tcompiegne** [comment]
PR created : https://github.com/gravitee-io/gravitee-docs/pull/173
