### ISSUE TITLE
Lack of documentation on handling global properties from Policy code 

### ISSUE THREAD

**Issue by mknair75** [gravitee-io/issues#1931]
Appreciate if more information is provided for setting and getting global properties from Policy code.

**Comment by aelamrani** [comment]
Please explain what is the goal of this issue.

From what i understand you want to be able to define global properties. This is something already available on the settings menu and called `dictionaries` that can be used in EL like here: https://docs.gravitee.io/apim_policies_assign_content.html#description

Is that what you are looking for?

**Comment by mknair75** [comment]
I am building a policy chain for the api and want to set a temporary property to set the context while the call flow moves from one policy to other.  It will also be useful if we can find a mechanism to store the temporary property in Redis or the Mongo DB (available in Gravitee) .

**Comment by aelamrani** [comment]
What about https://github.com/gravitee-io/gravitee-policy-assign-attributes?

**Comment by mknair75** [comment]
For the subject of this issue .. This is quite useful. Please close the issue.
