### ISSUE TITLE
[gateway] store contextual information about the current authentication transaction

### ISSUE THREAD

**Issue by SPLAYER-HD** [gravitee-io/issues#1933]
Hello guys,

I am developing a custom provider which consumes my own WSDL to validate user and password, I can get the `authentication.getPrincipal ()` and `authentication.getCredentials ()` but when I try to get `authentication.getAdditionalInformation ()` always is null

My WSDL need some additional parameters like IP an document type, I have tried to send this parameter by different ways but `authentication.getAdditionalInformation ()` keep it null in all request.

Please, Could you give a clue to achieve this?

**Comment by tcompiegne** [comment]
Hi @SPLAYER-HD,

How did you retrieve your "document type" ? from request query parameters ? from the custom provider configuration ?

**Comment by SPLAYER-HD** [comment]
Hello @tcompiegne,

Thanks for your attention,

**Document type** should come from request query parameters, so I have tried send something like this `"http://localhost:8092/com.test/oauth/token/?grant_type=password&scope=openid&username=80830680&password=f1t1d34s&**documentType**=1"`

Also I tried send document type in the body by a json or by form-data.

**Comment by tcompiegne** [comment]
Currently you can't have access to the original request made for authenticate the user.

This is a really nice feature, we should store contextual information about the current authentication transaction such as the HTTP request (hostname, query params, IP address, etc ...) to use it during identity provider's authentication process.

**Comment by rotparmna** [comment]
Thank you very much for the reply @tcompiegne 

I have a question about the `authentication.getAdditionalInformation()` method, currently the Github provider uses it to get the REDIRECT_URI parameter, if you can not get additional information about the request, how do you get that value? And in what part of the request does that value come?

**Comment by tcompiegne** [comment]
We get the value from the "social login" callback URL parameters (i.e `/login/callback?providerId=&redirect_uri=`)

We must apply the same principle (capture request params) for requests that require user authentication like : 

- `/oauth/authorize`
- `/oauth/token?grant_type=password`

**Comment by rotparmna** [comment]
Right!

And in the provider we want to do we can not use that same principle? Or is it a tare that does the CORE of GraviteeIO AM and we can not modify it?

**Comment by tcompiegne** [comment]
Yes it's part of Gravite.io AM core system. We have to do some modifications to export execution context at identity provider level.
