### ISSUE TITLE
[plugin] IllegalStateChangeException after loading a Policy 

### ISSUE THREAD

**Issue by mknair75** [gravitee-io/issues#1952]
Loaded a new test Policy under plugins folder in Gateway and management-api. After activating the Policy in API found the following exception. 

### Current Behavior
local_gateway_1        | java.lang.IllegalStateException: Policy [foo-content-check-policy] can not be found in policy registry
local_gateway_1        |        at io.gravitee.gateway.policy.impl.DefaultPolicyManager.lambda$initialize$2(DefaultPolicyManager.java:110)
local_gateway_1        |        at java.lang.Iterable.forEach(Iterable.java:75)
local_gateway_1        |        at io.gravitee.gateway.policy.impl.DefaultPolicyManager.initialize(DefaultPolicyManager.java:106)
local_gateway_1        |        at io.gravitee.gateway.policy.impl.DefaultPolicyManager.doStart(DefaultPolicyManager.java:72)
local_gateway_1        |        at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
local_gateway_1        |        at io.gravitee.gateway.handlers.api.ApiReactorHandler.doStart(ApiReactorHandler.java:335)
local_gateway_1        |        at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
local_gateway_1        |        at io.gravitee.gateway.reactor.handler.impl.DefaultReactorHandlerRegistry.prepare(DefaultReactorHandlerRegistry.java:61)
local_gateway_1        |        at io.gravitee.gateway.reactor.handler.impl.DefaultReactorHandlerRegistry.create(DefaultReactorHandlerRegistry.java:44)
local_gateway_1        |        at io.gravitee.gateway.reactor.impl.DefaultReactor.onEvent(DefaultReactor.java:113)
local_gateway_1        |        at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:44)
local_gateway_1        |        at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:36)
local_gateway_1        |        at io.gravitee.gateway.handlers.api.manager.impl.ApiManagerImpl.deploy(ApiManagerImpl.java:67)
local_gateway_1        |        at io.gravitee.gateway.services.sync.SyncManager.lambda$computeApiEvents$11(SyncManager.java:242)
local_gateway_1        |        at java.util.HashMap.forEach(HashMap.java:1289)
local_gateway_1        |        at io.gravitee.gateway.services.sync.SyncManager.computeApiEvents(SyncManager.java:211)
local_gateway_1        |        at io.gravitee.gateway.services.sync.SyncManager.synchronizeApis(SyncManager.java:152)
local_gateway_1        |        at io.gravitee.gateway.services.sync.SyncManager.refresh(SyncManager.java:100)
local_gateway_1        |        at io.gravitee.gateway.services.sync.ScheduledSyncService.run(ScheduledSyncService.java:87)
local_gateway_1        |        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
local_gateway_1        |        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
local_gateway_1        |        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
local_gateway_1        |        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
local_gateway_1        |        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
local_gateway_1        |        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
local_gateway_1        |        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
local_gateway_1        |        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
local_gateway_1        |        at java.lang.Thread.run(Thread.java:748)

### Your Environment
Gravitee gateway 1.22.1

**Comment by mknair75** [comment]
This happens when the Policy zip file is recopied after some update on to gateway and management-api docker containers.

**Comment by aelamrani** [comment]
Please provide logs from the start of the gateway

**Comment by mknair75** [comment]
We are not able to reproduce this scenario. Please close the issue. Will update in the comments if we encounter this again.
