### ISSUE TITLE
[service-discovery] [consul] Undeploy all endpoints when unregister event from consul 

### ISSUE THREAD

**Issue by vanackgpro** [gravitee-io/issues#1961]
I have 3 servers. On each server, consult v1.4 and a deployed API.
The 3 consul instances communicate together to provide information related to API service. (ip, port, service name, healthcheck ...)
On gravitee, gateways are set automatically with CONSUL. (Consul.io URL: http: // localhost: 8500 for each gateway)

The problem I encounter is the following:
When I delete an API on one of the servers, the gateway receives an UNREGISTER event from consul, but all the endpoints for that service are disabled.
Then when I want to use the API, it returns the code 503 from http gravitee,
until the new REGISTER event is received by GATEWAY from the consul.

### Steps to Reproduce (for bugs)
1. n servers / 1 service on each server
2. Setup service discovery with consul 
3. Test api with gravitee - 200 OK 
4. delete just one service on one server --> Unregister event into gateways
5. Test api with gravitee - 503 Service Unavalaible 

### Your Environment
* Version used: 1.22.2

**Comment by brasseld** [comment]
Hi @vanackgpro 

Did you set any health-check rule in Gravitee ?

**Comment by vanackgpro** [comment]
No, healthcheck rules disabled and failover disabled
just service discover enabled with consul setup

**Comment by vanackgpro** [comment]
the problem occurs only when the service id on is the same on the consul instances

**Comment by brasseld** [comment]
Why is the service id the same on consul instances?

**Comment by vanackgpro** [comment]
on a springboot app, it is possible to configure instance id in a bootstrap.yml file.

cf: https://cloud.spring.io/spring-cloud-consul/single/spring-cloud-consul.html#_making_the_consul_instance_id_unique

By default is an application that is registered with an application that is equal to its current version of the application name: $ {spring.application.name}: comma, separated, profiles: $ {server.port }. 

this configuration causes the deletion of all the services identified by the same identifier.
UNREGISTER event does not provide host on which the service is removed

To work around the problem I added a random element on the instance that allows to identify the services differently.
