### ISSUE TITLE
can't access to my api 

### ISSUE THREAD

**Issue by nesryn** [gravitee-io/issues#1964]
### Expected Behavior
http://localhost:8082/gateway context path
{
  "headers" : {
    "Host" : "api.gravitee.io",
    "User-Agent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36",
    "Accept" : "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
    "Accept-Encoding" : "gzip, deflate, br",
    "Accept-Language" : "fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7",
    "Cookie" : "_ga=GA1.2.1742497942.1549833586; _gid=GA1.2.521813084.1550939248",
    "Referer" : "https://docs.gravitee.io/apim_quickstart_publish.html",
    "Upgrade-Insecure-Requests" : "1",
    "X-Forwarded-For" : "102.157.121.227",
    "X-Forwarded-Host" : "api.gravitee.io",
    "X-Forwarded-Port" : "443",
    "X-Forwarded-Proto" : "https",
    "X-Forwarded-Server" : "2190b6ef1a19",
    "X-Real-Ip" : "102.157.121.227"
  },
  "query_params" : { }
}

### Current Behavior
No context-path matches the request URI.

11:10:15.051 [sync-1] INFO  i.g.m.services.sync.ApiManager - Deployment of ApiEntity{id='76763388-249c-415c-b633-88249c915c9f', name='my first api', version='2.0.0', description='my first api', proxy=io.gravitee.definition.model.Proxy@1e5f327f, paths={/=io.gravitee.definition.model.Path@44f2073b}, createdAt=Sun Feb 24 11:10:05 WAT 2019, updatedAt=Sun Feb 24 11:10:10 WAT 2019, visibility=PRIVATE, state=STARTED, primaryOwner=io.gravitee.management.model.PrimaryOwnerEntity@2822e3a6, tags=[], view=null, groups=null, pathMappings=[]}
11:10:19.030 [sync-1] INFO  i.g.m.s.d.DynamicPropertiesService - Dynamic properties service is disabled for: my first api [2.0.0]

### Steps to Reproduce (for bugs)
* Create API
* Use Backend API: https://api.gravitee.io/echo
* Deploy and start API

### Trace of API Management
10:42:20.227 [sync-1] INFO  i.g.m.s.d.DynamicPropertiesService - Dynamic properties service is disabled for: try&fit [4]
11:10:15.051 [sync-1] INFO  i.g.m.services.sync.ApiManager - Deployment of ApiEntity{id='76763388-249c-415c-b633-88249c915c9f', name='my first api', version='2.0.0', description='my first api', proxy=io.gravitee.definition.model.Proxy@1e5f327f, paths={/=io.gravitee.definition.model.Path@44f2073b}, createdAt=Sun Feb 24 11:10:05 WAT 2019, updatedAt=Sun Feb 24 11:10:10 WAT 2019, visibility=PRIVATE, state=STARTED, primaryOwner=io.gravitee.management.model.PrimaryOwnerEntity@2822e3a6, tags=[], view=null, groups=null, pathMappings=[]}
11:10:19.030 [sync-1] INFO  i.g.m.s.d.DynamicPropertiesService - Dynamic properties service is disabled for: my first api [2.0.0]

### Your Environment

* Version used: 1.22.1
* Browser Name Google Chrome

**Comment by aelamrani** [comment]
Do you have a published plan? Please provide an export of your API

**Comment by nesryn** [comment]
Yes, I have a published plan

**Comment by aelamrani** [comment]
`Please provide an export of your API`

**Comment by nesryn** [comment]
![image](https://user-images.githubusercontent.com/27787599/53300486-3a64dc00-3848-11e9-875f-94171caff8ef.png)
![image](https://user-images.githubusercontent.com/27787599/53300491-5799aa80-3848-11e9-855c-d339be8c4d77.png)

**Comment by aelamrani** [comment]
can you please click on the export button (second screen) and put here the file?

**Comment by nesryn** [comment]
{
  "name": "my first api",
  "version": "2.0.0",
  "description": "my first api",
  "visibility": "PRIVATE",
  "paths": {
    "/": []
  },
  "resources": [],
  "members": [
    {
      "source": "memory",
      "sourceId": "admin",
      "role": "PRIMARY_OWNER"
    }
  ],
  "pages": [],
  "plans": [
    {
      "id": "b71587af-f537-46c0-9587-aff53796c01d",
      "name": "free",
      "description": "free",
      "validation": "AUTO",
      "security": "KEY_LESS",
      "type": "API",
      "status": "PUBLISHED",
      "apis": [
        "76763388-249c-415c-b633-88249c915c9f"
      ],
      "order": 0,
      "characteristics": [],
      "created_at": 1551003007792,
      "updated_at": 1551003007792,
      "paths": {
        "/": []
      },
      "comment_required": false
    }
  ],
  "path_mappings": [],
  "proxy": {
    "context_path": "/echo",
    "strip_context_path": false,
    "groups": [
      {
        "name": "default-group",
        "endpoints": [
          {
            "name": "default",
            "target": "https://api.gravitee.io/echo",
            "weight": 1,
            "backup": false,
            "type": "HTTP",
            "http": {
              "connectTimeout": 5000,
              "idleTimeout": 60000,
              "keepAlive": true,
              "readTimeout": 10000,
              "pipelining": false,
              "maxConcurrentConnections": 100,
              "useCompression": true,
              "followRedirects": false
            }
          }
        ],
        "load_balancing": {
          "type": "ROUND_ROBIN"
        }
      }
    ]
  }
}

**Comment by aelamrani** [comment]
As the configured context path is `/echo`, why are you trying to call `http://localhost:8082/gateway` and not `http://localhost:8082/echo`?

**Comment by nesryn** [comment]
i tried http://localhost:8082/echo
![image](https://user-images.githubusercontent.com/27787599/53300851-9a5d8180-384c-11e9-810e-0d3f2e6294a2.png)

**Comment by aelamrani** [comment]
Sorry but seems there is an issue on your environnement and without logs of the gateway (that i already asked you in private message) is difficult for us to help you... 

Anyway, i just tried to simply import your API on our environnement of demo and it works perfectly => https://demo.gravitee.io/gateway/echo (https://demo.gravitee.io/#!/management/apis/c7cf44d3-e2de-4256-8f44-d3e2dea256eb/portal)

**Comment by nesryn** [comment]
sorry i didn't see your message
[gravitee.log](https://github.com/gravitee-io/issues/files/2898113/gravitee.log)

**Comment by aelamrani** [comment]
You have some issues with your mongodb connection i see some read tiemout errors

**Comment by nesryn** [comment]
Should I reinstall it???

**Comment by aelamrani** [comment]
Before to reinstall anything, you should check your mongoDB installation/logs...

**Comment by wenwenbaba** [comment]
Um... I ran into the same problem.
I created APIs and Applications, as well as publish and subscribe, in accordance with official documentation.
My mongodb is connected normally.

This is the content of the API file I exported.
{
  "name": "My First API",
  "version": "1",
  "description": "Gravitee.io Echo API Proxy",
  "visibility": "PRIVATE",
  "paths": {
    "/": []
  },
  "resources": [],
  "members": [
    {
      "source": "memory",
      "sourceId": "admin",
      "role": "PRIMARY_OWNER"
    }
  ],
  "pages": [],
  "plans": [
    {
      "id": "6c2f45b1-735a-4d70-af45-b1735a9d70b6",
      "name": "My Plan",
      "description": "Unlimited access plan",
      "validation": "MANUAL",
      "security": "API_KEY",
      "securityDefinition": "{\"propagateApiKey\":false}",
      "type": "API",
      "status": "PUBLISHED",
      "apis": [
        "51546e0f-df27-48c9-946e-0fdf27c8c99d"
      ],
      "order": 1,
      "characteristics": [],
      "created_at": 1557383032739,
      "updated_at": 1557383060297,
      "published_at": 1557383060297,
      "paths": {
        "/": []
      },
      "excluded_groups": [],
      "comment_required": false
    }
  ],
  "path_mappings": [],
  "proxy": {
    "context_path": "/myfirstapi",
    "strip_context_path": false,
    "groups": [
      {
        "name": "default-group",
        "endpoints": [
          {
            "name": "default",
            "target": "https://api.gravitee.io/echo",
            "weight": 1,
            "backup": false,
            "type": "HTTP",
            "inherit": true,
            "tenants": []
          }
        ],
        "load_balancing": {
          "type": "ROUND_ROBIN"
        },
        "http": {
          "connectTimeout": 5000,
          "idleTimeout": 60000,
          "keepAlive": true,
          "readTimeout": 10000,
          "pipelining": false,
          "maxConcurrentConnections": 100,
          "useCompression": true,
          "followRedirects": false
        }
      }
    ]
  }
}

**Comment by brasseld** [comment]
Please provide gateway logs.

**Comment by wenwenbaba** [comment]
Thank you for your prompt reply.
I am very happy to tell you that it is working.

There are a lot of plugins missing in the folder plugins, which leads to this situation.
Because I am compiling and running the source code.
