### ISSUE TITLE
[portal] Menu selection issue when first item is a folder

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#1967]
Please note the vertical bar (blue) when first item in the menu is a folder.

<img width="390" alt="capture d ecran 2019-02-24 a 21 50 52" src="https://user-images.githubusercontent.com/133094/53305167-4f5c6200-387e-11e9-988c-76bc19f21a3d.png">

When it is a file:

<img width="292" alt="capture d ecran 2019-02-24 a 21 50 56" src="https://user-images.githubusercontent.com/133094/53305168-51262580-387e-11e9-843b-25b05e2cb045.png">

**Comment by phiz71** [comment]
Can't reproduce in 1.25.5
