### ISSUE TITLE
[gateway] Access api but return "Unauthorized"

### ISSUE THREAD

**Issue by hjoru** [gravitee-io/issues#1977]
When I use jwt, but the result of the api always return "Unauthorized". What the token of the api should be put if I use RSA-256 for public key?
1. the config of jwt policy
![image](https://user-images.githubusercontent.com/40157987/53380919-00abe680-39aa-11e9-86fb-a2c81a1aad8d.png)

 2. the jwt token
![image](https://user-images.githubusercontent.com/40157987/53380871-d9551980-39a9-11e9-9648-03727341fd23.png)

### Your Environment

* Version used: 1.21.2
* Browser Name and version: 72.0.3626.109
* Operating System and version: centos 7

**Comment by brasseld** [comment]
Can you provide here the JWT token and the public key (ssh-rsa).

**Comment by hjoru** [comment]
JWT token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJHcmF2aXRlZS5pbyBBTSIsInN1YiI6IjEyMzQ1Njc4OTAiLCJuYW1lIjoiYWRtaW4iLCJhZG1pbiI6dHJ1ZX0.Xu-zvsJ_Iiwh6B_IA6jBfXRynsA6klNb58twCLJsuaJwQDIZFJHpJwp6yqVNswOKr_f2pXE5pjsZvvQG4Gr12Muiz2KqqR26EtJKYAETE0386cinOsVqa_1uP4pDHd6zMy4Zxo0VqGaAD4q61zJI2ZGd1a05GLH91nisAquReG4
public key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDdlatRjRjogo3WojgGHFHYLugd
UWAY9iR3fy4arWNA1KoS8kVw33cJibXr8bvwUAUparCwlvdbH6dvEOfou0/gCFQs
HUfQrSDv+MuSUMAe8jzKE4qW+jK+xQU9a03GUnKHkkle+Q0pX/g6jXZ7r1/xAK5D
o2kQ+X5xK9cipRgEKwIDAQAB

**Comment by brasseld** [comment]
Which kind of plan did you set?
