### ISSUE TITLE
[tools] Set up a new sub-domain to download bundles

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#198]
Currently, all bundles are available from [Bintray](https://bintray.com/gravitee-io/release/distribution/view) using https://bintray.com/gravitee-io/release/distribution/view.

It would be great to share a simple and intuitive url like https://downloads.gravitee.io or https://dl.gravitee.io

**Comment by NicolasGeraud** [comment]
https://dl.gravitee.io
