### ISSUE TITLE
oAuth client credential flow 401 unauthorized

### ISSUE THREAD

**Issue by johankumps** [gravitee-io/issues#1981]
Hi all,

I'm using Gravitee to secure my APIs. I use the oauth 2 client credential flow. Gravitee receives a response (status 200) from the token introspection endpoint. The consumer application calling the api on Gravitee receives a 401 status code. So something goes wrong within Gravitee. In the logging I can't see what. (Log see below).

What can I do to get more information of the steps performed by Gravitee and what can be wrong?

17:27:56.889 [vert.x-eventloop-thread-3] [] DEBUG i.g.g.reactor.impl.DefaultReactor - Receiving a request 63e6a509-8f3d-42cd-a6a5-098f3da2cd88 for path /echo
17:27:56.889 [vert.x-eventloop-thread-3] [] DEBUG i.g.g.r.h.i.DefaultReactorHandlerResolver - Returning the first handler matching path /echo/ : ApiReactorHandler{contextPath=/echo}
17:27:56.889 [vert.x-eventloop-thread-3] [] DEBUG i.g.g.s.c.SecurityPolicyChainResolver - Security provider [oauth2] has been selected to secure incoming request 63e6a509-8f3d-42cd-a6a5-098f3da2cd88
17:27:56.891 [vert.x-eventloop-thread-3] [] DEBUG i.g.g.policy.impl.PolicyFactoryImpl - Create a new policy instance for io.gravitee.policy.oauth2.Oauth2Policy
17:27:56.891 [vert.x-eventloop-thread-3] [] DEBUG i.g.g.policy.impl.PolicyFactoryImpl - Looking for a constructor to inject policy configuration
17:27:56.892 [vert.x-eventloop-thread-3] [] DEBUG i.g.g.p.impl.DefaultPolicyManager - Policy oauth2 has been added to the policy chain
17:27:56.892 [vert.x-eventloop-thread-3] [] DEBUG i.g.policy.oauth2.Oauth2Policy - Read access_token from request 63e6a509-8f3d-42cd-a6a5-098f3da2cd88
17:27:56.894 [vert.x-eventloop-thread-3] [] DEBUG i.g.r.o.g.OAuth2GenericResource - Introspect access token by requesting https://myserver.com/token_info [POST]
17:27:56.895 [vert.x-eventloop-thread-3] [] DEBUG i.g.r.o.g.OAuth2GenericResource - Set client authorization using HTTP header Authorization with value Basic <CREDENTIALS>
17:27:57.010 [vert.x-eventloop-thread-3] [] DEBUG i.g.r.o.g.OAuth2GenericResource - Introspection endpoint returns a response with a 200 status code
17:27:57.606 [rate-limit-poller] [] DEBUG i.g.g.s.ratelimit.RateLimitPoller - Refresh rate-limits from repository
17:27:58.043 [gateway-monitor] [] DEBUG i.g.g.s.hearbeat.HeartbeatThread - Run monitor for gateway at Tue Feb 26 17:27:58 CET 2019
17:27:58.043 [gateway-monitor] [] DEBUG i.g.g.s.hearbeat.HeartbeatThread - Sending an heartbeat event

Thank you for helping me out!
Johan

**Comment by brasseld** [comment]
Hi @johankumps 

Did  you define an oauth 2 plan ?

**Comment by johankumps** [comment]
Hi @brasseld ,

Yes I did referring to my oauth2 resource.

Johan,

**Comment by brasseld** [comment]
Did you subscribe to the plan using one of your application?

**Comment by johankumps** [comment]
Yes.

**Comment by brasseld** [comment]
Ok, so I suppose you've set a client_id to your application.

Can you provide me with the result of the call to the introspection endpoint ? Perhaps a required information is missing from the payload.

**Comment by johankumps** [comment]
Yes there is a clientId in the application.

This is the response of the introspection endpoint:

{
    "jti": "c522d5dd-b65e-43bf-9ccb-a104cc279b73",
    "iss": "https://acompany.com/v2/sjcpupog/oidc/idp",
    "sub": "u1foh0sads7ybbptp6v1fcl6pxbc078l",
    "apiuser": true,
    "aud": [
        "12345678-2222-7263-2533-332221111111",
        "sjcpupog",
        "7108246465"
    ],
    "exp": 1551266099,
    "iat": 1551262499,
    "active": true,
    "scope": "project.edit"
}

**Comment by brasseld** [comment]
ok, so there is no client_id from the introspection endpoint.
Please see https://tools.ietf.org/html/rfc7662#section-2.2

What is your auth server ?

**Comment by johankumps** [comment]
The auth server has been implemented within our company bound to our own IDP.
As the client_id is optional in the spec this, the fact that our auth server does not provide that field should not post a problem in the API gateway I suppose?

Kind regards,

**Comment by brasseld** [comment]
it is, because we don't know to which client the token is depending.

The other option would be to rely on the `aud` field as a fallback to a missing client_id.

**Comment by johankumps** [comment]
Can I do something from my end?

**Comment by brasseld** [comment]
`sub` must be used to identify end-user, not the client itself....

**Comment by brasseld** [comment]
Any news here ?

**Comment by johankumps** [comment]
By having the value of the sub attribute as clientid it all works. I now
have to see how we can adapt the response of our auth server. Maybe by
adding a proxy on the gateway transforming the response.

Thanks for your help.

Johan,

Op di 5 mrt. 2019 15:17 schreef Brassely David <notifications@github.com>:

**Comment by brasseld** [comment]
Ok cool... but I'm can't help you on such thing. The best would be to adapt your auth server... and be more compliant with specifications ;)

May I close this issue ?

**Comment by johankumps** [comment]
You are right. I will discuss this internally. You can close the issue now.

Thanks for your help.

Johan

Op do 7 mrt. 2019 10:27 schreef Brassely David <notifications@github.com>:
