### ISSUE TITLE
Access Management download bundle linking to a folder

### ISSUE THREAD

**Issue by CrustyJew** [gravitee-io/issues#1991]
Going to this url: https://gravitee.io/downloads/am/index.html  , the download link takes you to a directory viewer instead of downloading a bundle of the relevant zip files.
### Expected Behavior

Click download, be given a download of all 3 components in a single zip
### Current Behavior

Click download, be taken to a directory listing of all versions inside of individual component folders

**Comment by tcompiegne** [comment]
Since AM 2.4, a zip distribution bundle is provided.
