### ISSUE TITLE
[portal] Impossible to login when login form is hidden and no idp define

### ISSUE THREAD

**Issue by db3net** [gravitee-io/issues#2007]
#### Expected Behavior
Expecting the admin UI portal to present either a login pane (or be 100% authenticated when setting http auth to none). Image attached.

#### Current Behavior
The login pane is blank (no username / password fields) and looking at the development inspector for the page, it's showing that management/user is unable to load.

```
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (user, line 0)
http://fqdn_to_server:8083/management/user

```
### Solution
Not sure how to get around this. 

### Steps to Reproduce (for bugs)
1. Follow the instructions for installing entire platform - gateway, mgmt-api, ui on a remote server (not local...not a docker container)
2. Set the baseURL in constants.json to the fully-qualified domain name
3. Run all 3 services per instructions (after successfully getting Mongo and Elasticsearch running)
4. Browse to the url:port
5. Click "Login" & view inspector to see error

### Context
We're evaluating various API Gateways and this looks promising with it's admin UI. 

### Your Environment
CentOS7
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

#Elastic Search Config
http.port: 9200
network.host: 0

![alt text](https://i.imgur.com/uzIxVQA.png)

**Comment by brasseld** [comment]
The only way to get an empty login form is by configuring "authentication" from settings:

<img width="1086" alt="capture d ecran 2019-03-06 a 07 22 32" src="https://user-images.githubusercontent.com/133094/53860252-b0073f80-3fe0-11e9-947d-dff70871cd58.png">

`Show login form` must be checked.

I suppose you've done something here...

**Comment by aelamrani** [comment]
We keep this issue opened to make impossible to be in this state

**Comment by db3net** [comment]
@brasseld, where is this screen you've attached? This appears nowhere in the portal - I assume one needs to be authenticated to see this?

**Comment by brasseld** [comment]
@db3net don't know which version of gravitee you're running but this screen is available since 1.21.x and is accessible from Settings > Authentication

Yes it is equivalent to the old config file for oauth2 security provider but now you can manage them from UI / API and you can add as many oauth provider as you need.

**Comment by db3net** [comment]
Maybe I'm misunderstanding something, but what screen contains 'Settings > Authentication' ? I'm not seeing this anywhere.

**Comment by brasseld** [comment]
Here are some screenshots, hope it helps!

<img width="728" alt="Capture d’écran 2019-03-12 à 18 04 30" src="https://user-images.githubusercontent.com/133094/54220318-6becd100-44f1-11e9-90cd-5b459253e6e7.png">


<img width="438" alt="Capture d’écran 2019-03-12 à 18 04 39" src="https://user-images.githubusercontent.com/133094/54220321-6d1dfe00-44f1-11e9-9431-4bcec65239a7.png">


<img width="1272" alt="Capture d’écran 2019-03-12 à 18 04 45" src="https://user-images.githubusercontent.com/133094/54220324-6ee7c180-44f1-11e9-83c1-c9f826d2b046.png">

**Comment by db3net** [comment]
Did you miss the point that I can't log in because I'm missing username and password fields? If you click "Sign Out" then pretend you don't have username and password fields to log back in. You'll likely be seeing what I'm seeing.

**Comment by brasseld** [comment]
Yes, I've missed it.... too much issues and comments...

You didn't have any login form because you configure settings to not "Show login form" in the past.

Now, the workaround to escape from this is to update MongoDB to enable again the "Show login form" flag.

**Comment by brasseld** [comment]
Hi @db3net 

Any news here?
