### ISSUE TITLE
Run Gravitee in Restricted OpenShift security context

### ISSUE THREAD

**Issue by ejerpseth** [gravitee-io/issues#2008]
We did some changes to your docker image to get it to run in a restricted context under Openshift. Our security department do only allow restricted and nonroot context. The changes are posted in the diff-Dockerfiles file. I apologize for the raw format. The changes have not been very thorough; especially true for the chmod 777. We would like you to implement changes according to our changes so the helm installation runs in a restricted context.

### Expected Behavior
Running unprivileged

### Current Behavior
Need root privileges

### Possible Solution
Docker images that do not need root to run.

### Our changes

[diff-Dockerfiles.txt](https://github.com/gravitee-io/issues/files/2935525/diff-Dockerfiles.txt)

**Comment by ejerpseth** [comment]
The latest version of graviteeio/management-api works in restricted/nonroot context (as mongo requires nonroot I have not tried restricted).  graviteeio/management-ui does still need a more priviliged security context running in openshift.

**Comment by brasseld** [comment]
Hi @ejerpseth 

Latest images are working for non-root context.

For UI, the problem is coming from nginx which is used internally because nginx is trying to use TCP 80 port and TCP 443 port by default.

You can override these values by setting other values using envvar: HTTP_PORT / HTTPS_PORT.

**Comment by ejerpseth** [comment]
Sorry, you are right. Thanks for help.
