### ISSUE TITLE
[kubernetes] Helm chart: oauth config in values.yaml 

### ISSUE THREAD

**Issue by ejerpseth** [gravitee-io/issues#2009]
There has been some changes to your helm chart so we can no longer configure our OpenID Connect login in the values.yaml file, but have to to it through the UI. Because we are planning to deliver som many instances of Gravitee, this is very inconvenient for us.

### Expected Behavior
Oauth could be configured in yaml, no UI-logon required

### Current Behavior
Can´t get oauth to work without config through UI

**Comment by brasseld** [comment]
Hi @ejerpseth 

This has been done as part of this issue: https://github.com/gravitee-io/issues/issues/2031

Helm chart must be updated to reflect these configuration within the `gravitee.yml` file.

Regards,
