### ISSUE TITLE
Swagger Import : Root context path not mapped correctly

### ISSUE THREAD

**Issue by mknair75** [gravitee-io/issues#2010]
I am trying to load the swagger json available here - https://github.com/tmforum-apis/TMF641_ServiceOrder/blob/master/Service_Ordering_Management.regular.swagger.json
After I import the json, my expectation is that the context path in the plan is by default /tmf-api/serviceOrdering/v3/ as given in the swagger
But gravitee converts this to /apiserviceordering as context root
I tried changing this back to what is there in swagger in UI / Plan for the API but I am not able to invoke either of the paths
i.e <IP:8000>/apiserviceordering/serviceOrder OR <IP:8000>/tmf-api/serviceOrdering/v3/serviceOrder

Checked with @brasseld . He confirmed that this is a valid issue 

Using 1.22.3 of APIM

**Comment by mknair75** [comment]
@brasseld is there any workaround we can use to rectify this ?

**Comment by brasseld** [comment]
Would say, download the file, update the name and import the file....

**Comment by mknair75** [comment]
You mean update the name without "-". Is that causing the issue ? If we change the context root to following will that be ok (without "-")? 
tmfapi/serviceOrdering/v3/serviceOrder
