### ISSUE TITLE
[management] error "Transition is superseded" on analytics

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#2041]
### Steps to Reproduce (for bugs)

1. display the api analytics overview
2. select a top app => no log error
3. show logs
4. go back to overview
5. select a top app => `Transition Rejection($id: 4 type: 2, message: The transition has been superseded by a different transition, detail: Transition#10(`

### Your Environment

* Version used: 1.20.x

**Comment by gaetanmaisse** [comment]
Closing as this bug isn't present anymore (in 3.10+).
