### ISSUE TITLE
[policy] Response content not been updated on Plan Policies

### ISSUE THREAD

**Issue by slaguiar** [gravitee-io/issues#2043]
When polices tha update the response are added inside the plan configuration, they are not executed at all.
- URL Rewriting
- Groovy

### Expected Behavior
Policies should behave equals when added into paths or plan configurations

### Current Behavior
Policies updating response contents works only in paths.
Policies updating response contents added into plan configurations are not executed 

### Steps to Reproduce (for bugs)

1. Create a Groovy policy in Plan configuration
1.1. On-response content script
`return '{"name":"John Doe","age":42,"URL":"https://my.domain.com/person/John"}'`
2. Create a URL Rewrite policy in Plan configuration
2.1. Check Flag 'Rewrite HTTP response body'
2.2. URL pattern expressions: https?://[^\/]*\/((.*|\/*))
2.3. Replacement value: https://api.mydomain.com/{#group[0]}

### Context
The same policies are executed if applied in paths and the response is:
`{"name":"John Doe","age":42,"URL":"https://api.mydomain.com/person/John"}`

### Your Environment

* Version used: 1.23.0

**Comment by brasseld** [comment]
Hi @slaguiar 

Yes, the main reason is that policies at the plan level are only executed during the `OnRequest` phase.

**Comment by brasseld** [comment]
API Gateway have been improved for 1.24, we will be able to handle such case really soon (perhaps for 1.25).

I've tried on my current dev branch ans I was able to make it works.... but need more considerations and tests before going ahead!

**Comment by slaguiar** [comment]
So, There is any way to filter attributes from payload that are ellegible only for a suitable plan?
**For example.** 
Some clients will receive as response:
`{
    "a":"valuea",
    "b":"reserved_b"
}`
and others will receive
`{
    "a":"valuea"
}`
based on Plan signed.

**Comment by brasseld** [comment]
The problem I'm seeing there is that policy at the plan level are applied for all HTTP calls, whereas policies at the API level are defined for a given path and / or verb(s).

You have a use-case where you want to apply the same policy at the plan level for all the HTTP responses?

**Comment by slaguiar** [comment]
Yes. 
For URL rewrite i need to rewrite all links in the response of the api to point to gravitee and not to backend.
For groovy, no matter the path, some information that is retrieved in all paths are too sensive and must be restrict to a group of clients.
However, if its possible to achieve this requisite without a policy at the plain level, i would like to know how to do.

**Comment by brasseld** [comment]
I would say that you can manage it from API policies, for example using the groovy onResponseContent and add a if condition to check the plan used to process the request.

But it's more a workaround and would not be optimal for your consumers.

The best would be to wait for 1.25.x.

WDYT ?

**Comment by slaguiar** [comment]
I agree. If necessary before 1.25.x, i will use the workaround you suggested.

**Comment by brasseld** [comment]
Using groovy policy, you should be able to apply such condition (I didn't check the syntax, be careful):

```
import groovy.json.JsonSlurper
import groovy.json.JsonOutput

if(context.getAttribute('plan') == 'plan_id') {
	// Here return filtered content
	def jsonSlurper = new JsonSlurper()
	def content = jsonSlurper.parseText(response.content)
	content.remove('confidential-data')
	return JsonOutput.toJson(content)
}

return response.content
```

**Comment by slaguiar** [comment]
Hi, any updates on where this feature will be avaiable?

**Comment by brasseld** [comment]
Hi @slaguiar 

No update for now.
This is still part of the backlog.
