### ISSUE TITLE
Management API unreachable or error occurs

### ISSUE THREAD

**Issue by comply-online** [gravitee-io/issues#2061]
When loading the /management ui, I get a "Management API unreachable or error occurs, please check logs" error.

### Steps to Reproduce (for bugs)
1. Clone https://github.com/gravitee-io/gravitee-kubernetes
2. Change the hosts entries in values.yaml to point to my URL (ssl enabled)
3. Deploy using kubernetes helm chart with `helm install --name gravitee . --set ui.ingress.enabled=false --set gateway.ingress.enabled=false --set api.ingress.enabled=false` (I create the ingresses myself using cert-manager to create let's encrypt certificates)
4. Load the main URL

This is when I get the error. Console log shows:

```
Blocked loading mixed active content “http://gravitee.comply-online.com/portal/”
Possibly unhandled rejection: {"data":null,"status":-1,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"https://gravitee.comply-online.com/management/portal","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"","xhrStatus":"error"}
```

It looks like it's trying to call the site using `http` and NOT `https`. I tried to update `ui-configmap.yaml` on line #25 to add `https` to the `entrypoint` but that did not change it.

Help? Is there anywhere else where `https` has to be specified?

### Your Environment
* Minikube 0.35.0 (latest version)

**Comment by brasseld** [comment]
Hello @comply-online 

So you're right, the issue here is that the Portal is exposed in HTTP and is trying to access the management API through HTTPS.

I would advice you to expose both in HTTPS to be sure that everything is working as expected.

Regards,

**Comment by comply-online** [comment]
I would love to do it but even after trying to do it myself, it still tries to use HTTP instead of HTTPS.

Where do I specify that HTTPS should be used?

**Comment by brasseld** [comment]
Hi @comply-online 

You should access the portal using the https url, not the http.
This, will resolve your issue.
