### ISSUE TITLE
Request will not be logged if api key is invalid

### ISSUE THREAD

**Issue by Frintrop** [gravitee-io/issues#2062]
After upgrading to lastest gravitee gateway we don´t see full logs for request with invalid or missing api key.  There is only a 401 response seen in logs but no request or response body

it´s difficult to help customers / api consumers what they did wrong. we must guess now.
( wrong api key, missing api key, wrong header .......)

### Expected Behavior

see full request and response body with enabled logging also for wrong/missing api-keys

### Steps to Reproduce (for bugs)
1. enable logging in proxy.
2. send request to api with wrong or missing api key

**Comment by brasseld** [comment]
This can not be done.

As the api-key can not be validated, the request content is not transferred to the target endpoint, thus, the gateway does not handle it and so is not able to log it.
