### ISSUE TITLE
[portal] API metadata must in the same line as the title

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#2077]
Currently, metadata seems to be centered according to the height of the API description

<img width="1214" alt="Capture d’écran 2019-03-21 à 22 57 46" src="https://user-images.githubusercontent.com/133094/54787705-e2de4400-4c2c-11e9-9bba-de12d6f46f2d.png">

**Comment by romsalto** [comment]
Hello @brasseld,

If a user scrolls the page, the metadatas should be still visible or not ?

![screen_metas](https://user-images.githubusercontent.com/12186878/54817363-06d66f80-4c97-11e9-837d-1107a1c9a83a.png)

**Comment by brasseld** [comment]
Hi @romsalto 

Yes, metadata should still be visible, that's not the problem here.

The problem is that when the API description is very long (see my screenshot), metadata are going down because they are centered according to the height of the API description. IMHO, API Metadata must be at the same level of the beginning of thez API description.

Do you get me?

**Comment by romsalto** [comment]
Perfectly, I understood the bug but I wasn't sure about the metas visibility.
Fix is done on my side I'll send the PR this weekend.

**Comment by brasseld** [comment]
Oh cool! That's really nice!

Just a bit late for 1.24.0 ;)
