### ISSUE TITLE
[kubernetes] Any plan to support Kubernetes for Gravitee AM similar to Gravitee APIM?

### ISSUE THREAD

**Issue by AmreeshTyagi** [gravitee-io/issues#2080]
Any plan to provide kubernetes support to Gravitee AM similar to Gravitee APIM [gravitee-kubernetes](https://github.com/gravitee-io/gravitee-kubernetes)?

I was thinking to create one for AM. Curious to know, if someone has tried for the same, please let me know feasibility & challenges, if any before I proceed.

**Comment by brasseld** [comment]
Yes, we  will provide it soon.

**Comment by brasseld** [comment]
hi,

Already available: see https://github.com/gravitee-io/helm-charts
