### ISSUE TITLE
Context path for API should support subpaths

### ISSUE THREAD

**Issue by mknair75** [gravitee-io/issues#2085]
Trying to onboard a new API with different version from Gravitee UI 

I already have an API with context path e.g serviceordering/
I am trying to add a new version of api with the version field in the context path - serviceordering/v3.0.1

Gravitee API management UI complains the context path already exists. 

Expect the validation of context path should not limit to verification of root context (/serviceordering) but should cover the sub paths (/serviceordering/vx.x.x/xxxx) 

APIM version 1.22.x

**Comment by brasseld** [comment]
You will be able to manage these context-paths thanks to virtual-host feature in Gravitee 1.29
