### ISSUE TITLE
[gateway] ERROR JWTPolicy - Cannot schedule a timer with delay < 1 ms

### ISSUE THREAD

**Issue by johnlithgow88** [gravitee-io/issues#2092]
From time to time, the JWTPolicy seems to get in a state where it cannot retrieve the JWTPolicy correctly, and throws back a 401 unauthorized.  It shows that the eventloop thread cannot schedule a timer. 

Restarting the gateway does not help.  The only resolution i could find was to delete the API from the Gravitee Gateway, then import it back in.  Once freshly imported, it works again.

19:55:29.727 [vert.x-eventloop-thread-1] [] ERROR io.gravitee.policy.jwt.JWTPolicy - Cannot schedule a timer with delay < 1 ms
19:55:30.714 [vert.x-eventloop-thread-0] [] ERROR io.gravitee.policy.jwt.JWTPolicy - Cannot schedule a timer with delay < 1 ms
19:55:30.823 [vert.x-eventloop-thread-3] [] ERROR io.gravitee.policy.jwt.JWTPolicy - Cannot schedule a timer with delay < 1 ms

### Expected Behavior
I would expect that the JWTPolicy be able to retrieve the data from the database without error.

### Current Behavior
Periodically, an API will be unable to properly retrieve the JWT policy, and throw a 401 Unauthorized back to the client.

19:55:30.823 [vert.x-eventloop-thread-3] [] ERROR io.gravitee.policy.jwt.JWTPolicy - Cannot schedule a timer with delay < 1 ms

### Possible Solution
Unclear.  Perhaps an issue with mongoDB?

### Steps to Reproduce (for bugs)

1. create an API with a JWT policy and a public key
2. let it run for a long time, and the issue could occur.  (but very inconsistent)
3.
4.

### Context

It prevents all users from using the API that require JWT authentication. the service needed to be removed and added back. 

### Your Environment

* Version used: 120.3
* Browser Name and version: Chrome 73.0
* Operating System and version: Mac OS

**Comment by brasseld** [comment]
Hi @johnlithgow88 

The log has nothing to do with the JWT policy, I'm a bit surprised!
Can you share your API definition to see if there is something special there ?

**Comment by johnlithgow88** [comment]
Hi @brasseld 

thanks for looking at this. I attached the .json below for the API definition (but had to rename as .txt).  I also cleansed it a bit to change public keys, etc. 

[FORCE-API-QA-1-3-14.txt](https://github.com/gravitee-io/issues/files/3018568/FORCE-API-QA-1-3-14.txt)

**Comment by brasseld** [comment]
Hi @johnlithgow88 

For now, I'm not sure this message is relative to the JWT policy.

A few questions:
* Do you have only one API in the API gateway?
* Are you using JWKS resolver?
* Why defining the JWT policies for most of the paths? Why not doing it at the plan level ?

**Comment by johnlithgow88** [comment]
Hi @brasseld 

see below : 

- Yes, I have multiple APIs in the gateway
- Not using JWKS resolver
- No reason in particular.  JWT at plan level seems it would be a better approach, i'll will update this in the future.

**Comment by brasseld** [comment]
Hi @johnlithgow88 

Any news on this ?
