### ISSUE TITLE
[docker] Lightweight images

### ISSUE THREAD

**Issue by Blake-Lead** [gravitee-io/issues#211]
Hello,

Docker images could be lighter using : 
- busybox-based java8 image for management-api & gateway
- alpine-based nginx image for management-ui

Here are a comparison of current VS proposed images sizes :

|  | Gravitee | Leansys | Shrinked by |
| --- | --- | --- | --- |
| gateway | 689.4 MB | 276.4 MB | 60 % |
| management-api | 676.4 MB | 269.9 MB | 60 % |
| management-ui | 272.8 MB | 65.11 MB | 76 % |

Adel

**Comment by brasseld** [comment]
Hi @Blake-Lead,

Can you provide us with the gain / benefit in terms of image size ?

Thanks

**Comment by Blake-Lead** [comment]
Hi @brasseld, added a table resuming gain in size.

**Comment by Blake-Lead** [comment]
Hello,

I switched busybox for alpine in the Java8 image. Gateway and Management Api are now a little bit heavier but this solution has the advantage of being futureproof.

|                | Gravitee | Leansys  |
|----------------|----------|----------|
| gateway        | 689.4 MB | 285.6 MB |
| management-api | 676.4 MB | 279.0 MB |
| management-ui  | 272.8 MB | 65.11 MB |

Adel

**Comment by brasseld** [comment]
10 Mo for each image ! We can still live with this additional weight ;-)

Thanks a lot @Blake-Lead !

**Comment by brasseld** [comment]
The doc hasn't been updated with according changes:
- base image => alpine instead of centos
- we are not using httpd anymore (nginx)
- add a documentation part about docker-compose and how to start quickly with it
