### ISSUE TITLE
Cassandra  support

### ISSUE THREAD

**Issue by topkool** [gravitee-io/issues#2118]
Cassandra plugin does not work

### Expected Behavior
Use Cassandra a repository (instead of MongoDB)

### Current Behavior
Cassandra plugin does not work. Once installed, several issues occur (CQL script is wrong, Gravitee fails at launch...)

### Steps to Reproduce (for bugs)
Install the Cassandra plugin

### Your Environment
Debian 9.6 + Gravitee APIM 1.2.4

**Comment by brasseld** [comment]
Cassandra plugin is no more supported because this one was not really used by gravitee users.

As we are not contributing anymore to the repository, it's quite normal that it does not work as expected.

**Comment by NicolasGeraud** [comment]
@topkool If you need cassandra, you can fill the gap between the current version of the plugin (gravitee v1.12) and the current version of gravitee (v1.24).

To do that, clone the cassandra repositoy (https://github.com/gravitee-io-community/gravitee-repository-cassandra/blob/master/pom.xml) and upgrade step by step the dependencies `gravitee-repository` and `gravitee-repository-test`

We can help you to configure your dev environment.
