### ISSUE TITLE
[am][jwt][roles] Unable to see mapped roles in the id_token (JWT)

### ISSUE THREAD

**Issue by gigo1980** [gravitee-io/issues#2127]
We try to access the "roles" that we have setup in gravitee access manager inside our application.

But the provided Json Web Token (JWT) does not provide this information. 
We only can get the following pieces of information.

```json
{
  "sub": "b99515c4-b731-4352-9515-c4b73123526f",
  "aud": "test",
  "iss": "http://gravitee.am",
  "name": "Max Mustermann",
  "exp": 1554734232,
  "given_name": "Max",
  "iat": 1554719832,
  "family_name": "Mustermann",
  "email": "max.mustermann@test.com"
}
```
We expect to have the role inside the JWT Token, also the "userinfo" Endpoint does not provide this informations.

**Comment by brasseld** [comment]
This is now possible thanks to the custom claims feature in AM 2.8.x

See: https://docs.gravitee.io/am/2.x/am_quickstart_tokens_custom_claims.html
