### ISSUE TITLE
Gravitee API Gateway timeout 504  error - when an underlying api takes approx 10 - 30 seconds to respond, gateway is returning 504 error

### ISSUE THREAD

**Issue by hatimjohar** [gravitee-io/issues#2129]

**Comment by hatimjohar** [comment]
This is what I see in the logs

04:37:36.517 [sync-1] [94ce01e2-91b0-4f09-8e01-e291b07f09be] INFO  i.g.g.http.connector.VertxHttpClient - 	HTTP {ConnectTimeout='5000', KeepAlive='true', IdleTimeout='60', MaxChunkSize='8192', MaxPoolSize='100', MaxWaitQueueSize='-1', Pipelining='false', PipeliningLimit='10', TryUseCompression='true'}

**Comment by brasseld** [comment]
Not an issue: you must define the correct timeout at the endpoint level.

**Comment by hatimjohar** [comment]
My underlying api are working as expected, when I make call to my api without gravitee api gateway the response is received.

We receive 504 gateway timeout error when api is created behind gravitee api gateway, please suggest

**Comment by Vikash2402** [comment]
Well, I am also facing same issue. 
Whenever i am accessing the rest api directly i am getting my response properly.
However when i configured it into gravitee it is showing 504 gateway time out error whenever the response time reaches to 10 sec or more.

@brasseld It would be great if you can point out where can we define/configure the timeout.
Thanks.

**Comment by brasseld** [comment]
Did you try to curl from the api gateway ?

**Comment by Vikash2402** [comment]
@brasseld Thankyou!
this issue was with timeout duration. I updated that in gravitee value from 10 sec to 1 min. Now its working as expected. :)

**Comment by hatimjohar** [comment]
> Not an issue: you must define the correct timeout at the endpoint level.

Thank you @brasseld, I was able to find out timeout settings in the endpoint section of gravitee api gateway and were able to increase the timeout. We are observing the behavior and will update with our findings shortly. Thanks for helping us. Good day

**Comment by lwatzon** [comment]
I have set all the timeouts as described above.
But if i call we webservice that returns chuncked XML that takes more than 30 seconds to return and i have the XML to JSON Policy Gravitee returns a 504 after 30 seconds.
If i remove the XML to JSON policy it returns after the full response comes back as expected.
is there a way to handle this situation?

**Comment by brasseld** [comment]
Hi @lwatzon 

Do you have any logs from the gateway ?

**Comment by johaneg** [comment]
Where do you set this timeout? I need to increase it but can't find where to do it.

**Comment by yalva** [comment]
> Where do you set this timeout? I need to increase it but can't find where to do it.

Endpoint management -> HTTP configuration

**Comment by j0nimost** [comment]
This is a design flaw though. APIs on the local network are returning responses sub 100ms but gravitee times out. Hope we get an update for this.

**Comment by attiqmscs004** [comment]
I am facing the same issue. I have the deployed the Gravitee on kubernetes. How can I update the gateway timeout values in values.yaml @hatimjohar . If you could help me with that.
