### ISSUE TITLE
[management-api] Logout button does not close OIDC provider session

### ISSUE THREAD

**Issue by kanischev** [gravitee-io/issues#2137]
When user is authenticated with external oauth provider the session in this provider does not close on user logout from API Management portal
### Expected Behavior

User's session in OIDC should be closed on logout from API Management portal

### Current Behavior

User is logged out from portal but then is automatically authorized with former credentials without login-password form when clicking auth with previous OIDC provider

### Steps to Reproduce (for bugs)

1. Configure Keycloak as OAuth2 provider for portal users
2. Login to portal via OIDC Keycloak-provided user
3. Logout from APIM Portal
4. Click Login again and select Auth with configured Keycloak
5. You won't be asked for login and password and will be automatically authorized with previous user.

### Your Environment

* Version used: All up to 1.24
* Browser Name and version: All
* Operating System and version: All

P.S. Have fix and will provide PR

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/gravitee-management-rest-api/commit/1a6f18098e0ecca7e2b402633546394da75e23a2
