### ISSUE TITLE
Support all json schema features on plugins web confuguration forms

### ISSUE THREAD

**Issue by brightlizard** [gravitee-io/issues#2140]
### Expected Behavior
There are web forms on Developer's Web UI, for example for policies and resources configuration, that builds on the basis of jsonschema received from management REST API. 

It would be great to support some jsonschema things like string "format", schema dependencies, combining schemas and so on...

It would be usable for masking a password, set required properties on the basis of enum value and so on...

For example there are some js libs that generates HTML forms from json schemas.  

### Current Behavior
"type": "string", "format": "password" - does not work as expected

### Possible Solution
For example there are some js libs that generates HTML forms from json schemas.  

### Context
I wrote custom resource on the basis of "Generic OAuth2 Authorization Resource" to add the ability of two factor TLS between gateway and authorization server but it's impossible to mask for example jks password in resource configuration form.

**Comment by aelamrani** [comment]
According to what i understand, it is already possible. Please take a look at https://github.com/gravitee-io/gravitee-resource-auth-provider-inline/blob/b9a53e5963c1eabe33078012ca093e4c726a9b16/src/main/resources/schemas/schema-form.json#L19

**Comment by aelamrani** [comment]
Is that what you were looking for?

**Comment by brightlizard** [comment]
I tried to rename property according to example, but field still remains unmask on webform.
Another thing is - what if I need several password fields on webform?

**Comment by aelamrani** [comment]
Sorry, i did not send u a correct example. What about this: https://github.com/gravitee-io/gravitee-fetcher-bitbucket/blob/2552ad527034b9c616d6a6225b25c4c12467c7f9/src/main/resources/schemas/schema-form.json#L47

**Comment by brightlizard** [comment]
Now it works. Thanks.
Is it possible to set up jsonschema dependensies out-of-the-box https://json-schema.org/understanding-json-schema/reference/object.html#dependencies

Something like this:
"anyOf": [
  {
    "properties": {
      "serverSslType": { "enum": ["PEM"]}
    },
    "required": [ "pemServerCertPath", "pemServerKeyPath" ]
  },
  {
    "properties": {
      "serverSslType": { "enum": ["JKS"]}
    },
    "required": [ "jksServerCertPath", "jksServerCertPassword" ]
  },
  {
    "properties": {
      "serverSslType": { "enum": ["PKCS12"]}
    },
    "required": [ "pkcs12ServerCertPath", "pkcs12ServerCertPassword" ]
  },
  {
    "properties": {
      "clientSslType": { "enum": ["PEM"]}
    },
    "required": [ "pemClientCertPath", "pemClientKeyPath" ]
  },
  {
    "properties": {
      "clientSslType": { "enum": ["JKS"]}
    },
    "required": [ "jksClientCertPath", "jksClientCertPassword" ]
  },
  {
    "properties": {
      "clientSslType": { "enum": ["PKCS12"]}
    },
    "required": [ "pkcs12ClientCertPath", "pkcs12ClientCertPassword" ]
  }
],

**Comment by aelamrani** [comment]
Never tested yet. What about testing it and give us a feedback?

**Comment by brightlizard** [comment]
Already. It does'n work )) 

Here is the full schema:
{
  "type": "object",
  "id": "urn:jsonschema:net.brightlizard:apim2:plugins:resources:oauth2:configuration:OAuth2ResourceConfiguration",
  "properties": {
    "authorizationServerUrl": {
      "title": "Authorization server URL",
      "description": "URL of the authorization server",
      "type": "string",
      "default": "https://authorization_server"
    },
    "introspectionEndpoint": {
      "title": "Token introspection endpoint",
      "description": "Path which is used to introspect an incoming access token (must start with '/').",
      "type": "string",
      "default": "/oauth/check_token"
    },
    "introspectionEndpointMethod": {
      "title": "Token introspection method",
      "description": "HTTP method used to introspect the access token.",
      "type": "string",
      "enum": [
        "GET",
        "POST"
      ],
      "default": "GET"
    },
    "scopeSeparator": {
      "title": "Scope separator",
      "description": "Separator used to separate scopes for token introspection (default is a whitespace)",
      "type": "string",
      "default": " "
    },
    "userInfoEndpoint": {
      "title": "Userinfo endpoint",
      "description": "Path which is used to get userinfo using incoming access token (must start with '/').",
      "type": "string",
      "default": "/userinfo"
    },
    "userInfoEndpointMethod": {
      "title": "Userinfo  method",
      "description": "HTTP method used to get userinfo.",
      "type": "string",
      "enum": [
        "GET",
        "POST"
      ],
      "default": "GET"
    },
    "clientId": {
      "title": "Client Id",
      "description": "The client identifier used for token introspection.",
      "type": "string"
    },
    "clientSecret": {
      "title": "Client Secret",
      "description": "The client secret used for token introspection.",
      "type": "string"
    },
    "useClientAuthorizationHeader": {
      "title": "Use HTTP header for client authorization",
      "description": "To prevent token scanning attacks, the endpoint MUST also require some form of authorization to access this endpoint. In this case we are using an HTTP header for client authentication.",
      "type": "boolean",
      "default": true
    },
    "clientAuthorizationHeaderName": {
      "type": "string",
      "title": "Authorization header.",
      "default": "Authorization"
    },
    "clientAuthorizationHeaderScheme": {
      "type": "string",
      "title": "Authorization scheme.",
      "default": "Basic"
    },
    "tokenIsSuppliedByQueryParam": {
      "title": "Use a query parameter to supply access token",
      "description": "Access token is passed to the introspection endpoint using a query parameter.",
      "type": "boolean",
      "default": true
    },
    "tokenQueryParamName": {
      "title": "Token query param name",
      "description": "Query parameter used to supply access token.",
      "type": "string",
      "default": "token"
    },
    "tokenIsSuppliedByHttpHeader": {
      "title": "Use an HTTP header to supply access token",
      "description": "Access token is passed to the introspection endpoint using an HTTP header.",
      "type": "boolean",
      "default": false
    },
    "tokenHeaderName": {
      "title": "HTTP header name",
      "description": "HTTP header used to supply access token.",
      "type": "string"
    },
    "tokenIsSuppliedByFormUrlEncoded": {
      "title": "Use application/x-www-form-urlencoded form to send access token",
      "description": "Send access token in application/x-www-form-urlencoded form.",
      "type": "boolean",
      "default": false
    },
    "tokenFormUrlEncodedName": {
      "title": "Form param name",
      "description": "Name of the form param in case of application/x-www-form-urlencoded.",
      "type": "string",
      "default": "token"
    },
    "userClaim": {
      "title": "User claim",
      "description": "User claim field used to store end user on log analytics",
      "type": "string",
      "default": "sub"
    },
    "trustAll": {
      "title": "Trust all server certificates",
      "description": "Trust all server certificates",
      "type": "boolean",
      "default": "false"
    },
    "verifyHostname": {
      "title": "Verify hostname",
      "description": "Verify hostname",
      "type": "boolean",
      "default": "false"
    },
    "serverSslType": {
      "title": "Type of trust store",
      "description": "Type of trust store",
      "type": "string",
      "enum": [
        "NONE",
        "JKS",
        "PEM",
        "PKCS12"
      ],
      "default": "NONE"
    },
    "pemServerCertPath": {
      "title": "pemServerCertPath",
      "description": "pemServerCertPath",
      "type": "string"
    },
    "jksServerCertPath": {
      "title": "jksServerCertPath",
      "description": "jksServerCertPath",
      "type": "string"
    },
    "jksServerCertPassword": {
      "title": "jksServerCertPassword",
      "description": "jksServerCertPassword",
      "type": "string",
      "x-schema-form": {
        "type": "password"
      }
    },
    "pkcs12ServerCertPath": {
      "title": "pkcs12ServerCertPath",
      "description": "pkcs12ServerCertPath",
      "type": "string"
    },
    "pkcs12ServerCertPassword": {
      "title": "pkcs12ServerCertPassword",
      "description": "pkcs12ServerCertPassword",
      "type": "string",
      "x-schema-form": {
        "type": "password"
      }
    },
    "clientSslType": {
      "title": "Type of client store",
      "description": "Type of client store",
      "type": "string",
      "enum": [
        "NONE",
        "JKS",
        "PEM",
        "PKCS12"
      ],
      "default": "NONE"
    },
    "pemClientCertPath": {
      "title": "pemClientCertPath",
      "description": "pemClientCertPath",
      "type": "string"
    },
    "pemClientKeyPath": {
      "title": "pemClientKeyPath",
      "description": "pemClientKeyPath",
      "type": "string"
    },
    "jksClientCertPath": {
      "title": "jksClientCertPath",
      "description": "jksClientCertPath",
      "type": "string"
    },
    "jksClientCertPassword": {
      "title": "jksClientCertPassword",
      "description": "jksClientCertPassword",
      "type": "string",
      "x-schema-form": {
        "type": "password"
     }
    },
    "pkcs12ClientCertPath": {
      "title": "pkcs12ClientCertPath",
      "description": "pkcs12ClientCertPath",
      "type": "string"
    },
    "pkcs12ClientCertPassword": {
      "title": "pkcs12ClientCertPassword",
      "description": "pkcs12ClientCertPassword",
      "type": "string",
      "x-schema-form": {
        "type": "password"
      }
    },
    "connectionTimeout": {
      "title": "connectionTimeout",
      "description": "connectionTimeout",
      "type": "integer",
      "default": 10000
    },
    "idleTimeout": {
      "title": "idleTimeout",
      "description": "idleTimeout",
      "type": "integer",
      "default": 60
    },
    "maxPoolSize": {
      "title": "maxPoolSize",
      "description": "maxPoolSize",
      "type": "integer",
      "default": 50
    }
  },
  **"anyOf": [
    {
      "properties": {
        "serverSslType": { "enum": ["PEM"]}
      },
      "required": [ "pemServerCertPath", "pemServerKeyPath" ]
    },
    {
      "properties": {
        "serverSslType": { "enum": ["JKS"]}
      },
      "required": [ "jksServerCertPath", "jksServerCertPassword" ]
    },
    {
      "properties": {
        "serverSslType": { "enum": ["PKCS12"]}
      },
      "required": [ "pkcs12ServerCertPath", "pkcs12ServerCertPassword" ]
    },
    {
      "properties": {
        "clientSslType": { "enum": ["PEM"]}
      },
      "required": [ "pemClientCertPath", "pemClientKeyPath" ]
    },
    {
      "properties": {
        "clientSslType": { "enum": ["JKS"]}
      },
      "required": [ "jksClientCertPath", "jksClientCertPassword" ]
    },
    {
      "properties": {
        "clientSslType": { "enum": ["PKCS12"]}
      },
      "required": [ "pkcs12ClientCertPath", "pkcs12ClientCertPassword" ]
    }
  ],**
  "required": [
    "authorizationServerUrl",
    "introspectionEndpoint",
    "introspectionEndpointMethod",
    "clientId",
    "clientSecret"
  ]
}

**Comment by aelamrani** [comment]
Ok i just had a try and this is not supported at this day by the dependency we use. We should be able to do such a thing by using a directive.
