### ISSUE TITLE
Gravitee API Gateway is not returning response when response time is more than 1 minutes

### ISSUE THREAD

**Issue by hatimjohar** [gravitee-io/issues#2156]
We have configured Gravitee api gateway over https (with valid certificate).

When request takes a longer time (more than a minute approx) to return the response Gateway does not return any response to the client, instead it shows (Could not get any response error in Postman), however when response time is less than it returns a 200 response.

Also we have set alpn as false i.e. we are not using http2.

Another thing we observed from API Analytics logs is that the request is logged successfully and it states 200 response code but client does not receive any response

### Expected Behavior
Client application should receive the response even if it takes more than minute to respond

### Current Behavior
Client applications are receiving no response,
1. Postman - Could not get any response
2. Javascript - net::ERR_EMPTY_RESPONSE

Please help us in resolving  this issue. 

Are there any timeouts for response that we need to update ? or are we missing any configuration ?

**Comment by brasseld** [comment]
Did you try to curl ?

Which version of gravitee ?

**Comment by hatimjohar** [comment]
Version: 1.21.2

**Comment by brasseld** [comment]
Did you try to curl ?

**Comment by hatimjohar** [comment]
No, My request body is of large size therefore not able to check with Curl. I have written a javascript program to make call to the api but it returns net::ERR_EMPTY_RESPONSE.

When checked logs in API Gateway Management portal,
API > Analytics > logs
I was able to see the request logged with 200 status and the response time was in minutes

**Comment by hatimjohar** [comment]
@brasseld -- If you could suggest any settings to try, please share it with us

**Comment by brasseld** [comment]
Perhaps you can try to provide a reproducible test-case using our demo environment ?

https://demo.gravitee.io/

**Comment by hatimjohar** [comment]
Thanks @brasseld for sharing your demo environment. However I cannot directly publish our api over this environment as they are hosted on a machine that is not present on public IP (internal machine).

We have further investigated over this issue and according to me API Gateway is able to return the response but Firewall or Proxy server is dropping the request when response time is in minutes.

I will keep you posted with our finding. Thanks for the help

**Comment by hatimjohar** [comment]
Thanks @brasseld for your help. We were able to identify the root cause it was with the HAProxy where the timeout was of 30 seconds, we increased that and then we were able to get the response.
