### ISSUE TITLE
Support Pure SOAP APIs and Integrations

### ISSUE THREAD

**Issue by j0nimost** [gravitee-io/issues#2158]
I would like to know if Gravitee API Manager supports legacy SOAP APIs and SOAP integrations with out converting SOAP WS to REST API?

**Comment by brasseld** [comment]
Hi @j0nimost 
Yes you can do it by using policies like "rest-to-soap" or "assign-content", etc....

**Comment by j0nimost** [comment]
`rest-to-soap` means that I need an already existing REST API to convert JSON to XML. My question is can I retain my soap API XML in XML out....

**Comment by brasseld** [comment]
Yes, sorry I've misread  your comment.
So you can expose anything on top of http protocol without the need to transform to an appropriate format.

**Comment by j0nimost** [comment]
Thank you
