### ISSUE TITLE
Fail to connect to the default repository management at startup

### ISSUE THREAD

**Issue by abourdon** [gravitee-io/issues#216]
Hi all,

I'm following the instructional steps to start the gateway:

<img width="1131" alt="screen shot 2016-09-08 at 00 34 52" src="https://cloud.githubusercontent.com/assets/1511715/18330987/1b05074c-755c-11e6-9c63-3e2c227db2a7.png">

and when I starting it by using the `bin/gravitee` script then I got the following error:

<img width="1247" alt="screen shot 2016-09-08 at 00 21 08" src="https://cloud.githubusercontent.com/assets/1511715/18330721/87b74ae6-755a-11e6-9a6f-e88889b7aead.png">
 
By looking more deeper, I can see from the `config/gravitee.yml` file that mongodb is the default repository management:

<img width="890" alt="screen shot 2016-09-08 at 00 25 26" src="https://cloud.githubusercontent.com/assets/1511715/18330782/defb11d4-755a-11e6-9e67-72e914d2e720.png">

But maybe gateway could use an embedded repository management to fix this issue and let user try the gateway without any additional configuration?

Cheers,
Aurélien

**Comment by brasseld** [comment]
Hi @abourdon,

It's nice to read you 😉 !

I think there isn't added value to provide an "embedded" repository connector. 
For sure, we have to improve the _Installation Steps_ documentation to inform user that he must have a MongoDB instance installed (and also an Elasticsearch instance).

We also have to add a link to the _Installation Guide_ from the _Downloads_ page.

Finally, you may probably know that the gateway can run with a local registry which is able to read API definition file (json) from the filesystem, but I'm not sure that it's a good option when you want to try all the pretty good features provided by Gravitee.io 😉 

Regards,

**Comment by abourdon** [comment]
Hi @brasseld,

Nice to see Gravitee.io is reaching its first major version!

Thanks for your reply, this issue is more oriented to a new user who wish to play with Gravitee by following the installation steps page.
As you said, a simple improvement of the installation steps page would be nice ;-)

Good job guys!

A+
Aurélien

**Comment by brasseld** [comment]
And, just for your pleasure, [Downloads](https://gravitee.io/downloads/full-stack/latest/) page has been updated !
