### ISSUE TITLE
[management-ui] unpublished documentation only visible for admin

### ISSUE THREAD

**Issue by radicarl** [gravitee-io/issues#2164]
User different from admin with admin rights in Management and Portal can create pages/folders under Settings > Portal > Documentation but can not see them afterwards. With the default admin user I can see those pages and folders and after publishing them I can also see them with my personal user.

### Expected Behavior
The user who creates documentation pages/folders should be able to see/edit/publish unpublished documenation pages/folders. At least those pages/folders he created.

### Current Behavior
Users can create documentation pages/folders but aren't able to see/edit/publish them until the admin user published them.

### Your Environment
Gravitee.io Developers portal
Version: 1.24.0

Access Manager 2.4.0

**Comment by aelamrani** [comment]
I think this has been fixed as part of https://github.com/gravitee-io/issues/issues/2087

**Comment by radicarl** [comment]
Hello,
I will try the new version and give here feedback.
Thanks for the fast reply.

**Comment by aelamrani** [comment]
👍 Ok i keep this issue opened as we wait for your feedback.

**Comment by radicarl** [comment]
Works in 1.25. Thank you
