### ISSUE TITLE
[elasticsearch] Elastic 7.x support

### ISSUE THREAD

**Issue by Produits** [gravitee-io/issues#2165]
Elastic 7 is currently not supported by Gravitee

Is the support of this version planed ?

Thx

**Comment by brasseld** [comment]
Hello @Produits 

Can you explain why you're already looking for ES 7.x support?
You're using a specific feature of ES 7.x?

**Comment by alexwinston** [comment]
For myself I just downloaded the newest version thinking it would work, wasn't paying close enough attention to the docs saying 5.x.  I can certainly use an older version but it would be nice to keep the external dependencies on the newest versions.  Additionally it looks like v5 is almost 3 years old now.

**Comment by brasseld** [comment]
Hi @alexwinston 

We support all ES versions from 2.x to 6.x

ES 7.x has been released 3 weeks ago... we need more time to ensure that our connector is working quite nicely with this version.

**Comment by alexwinston** [comment]
@brasseld Great to know.  Might want to update the docs cause it says 5.x right now.  There is a NPE with 7 it appears.  Didn't realize 7 was released so recently.  Testing Gravitee and it is great so far!

**Comment by brasseld** [comment]
Ok, will update the doc, thanks for pointing !
I already had a try with a local build (and some small changes) and everything goes well so I suppose connector will be updated soon!

**Comment by barrycheng** [comment]
@brasseld
Will it be released in the next version?

**Comment by michaelsogos** [comment]
Dear @aelamrani ,

We are installing gravitee in these days, but we already have an working cluster in ES 7.1.
Unfortunately, when the GATEWAY starts it logs that the version 7 of ES is not supported.

Also i saw that you commited a new gravitee-elasticsearch (v1.28?), is possible to download the updated plugin already built? (the JAR i mean)

**Comment by aelamrani** [comment]
I can provide you a snapshot version if you want

**Comment by aelamrani** [comment]
Copy the plugin `gravitee-repository-elasticsearch-1.29.0-SNAPSHOT.zip` in the `{MGMT_HOME}/plugins` directory.

Copy the plugin `gravitee-reporter-elasticsearch-1.29.0-SNAPSHOT.zip` in the `{GATEWAY_HOME}/plugins` directory.

Do not forget to remove older versions of these plugins.

[gravitee-repository-elasticsearch-1.29.0-SNAPSHOT.zip](https://github.com/gravitee-io/issues/files/3460626/gravitee-repository-elasticsearch-1.29.0-SNAPSHOT.zip)
[gravitee-reporter-elasticsearch-1.29.0-SNAPSHOT.zip](https://github.com/gravitee-io/issues/files/3460627/gravitee-reporter-elasticsearch-1.29.0-SNAPSHOT.zip)
