### ISSUE TITLE
add nl translation to portal i18n

### ISSUE THREAD

**Issue by kurtvm** [gravitee-io/issues#2167]
The portal comes with several UI translations out-of-the-box (french, english,...)
There is currently no dutch translation file available.
### Expected Behavior

UI items should also be available in dutch.

### Current Behavior

Dutch language falls back to english.

### Possible Solution

Translate items within en.json into dutch, generating a new translation file nl.json

### Steps to Reproduce (for bugs)

Add dutch as primary browser language (accept-language: nl)

### Context

Dutch customers are sensitive to language issues

### Your Environment

* Version used: 1.24
* Browser Name and version:
* Operating System and version:

**Comment by kurtvm** [comment]
pull request
https://github.com/gravitee-io/gravitee-management-webui/pull/900/commits/5b23610a283dfc74be5e02407d216bad80402fc6

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/gravitee-management-webui/pull/900/commits/5b23610a283dfc74be5e02407d216bad80402fc6

**Comment by brasseld** [comment]
Thanks a lot @kurtvm!
