### ISSUE TITLE
Gravitee AM based Login to Gravitee Portal , UI remains in Login screen 

### ISSUE THREAD

**Issue by mknair75** [gravitee-io/issues#2169]
Tried to follow the documentation here https://docs.gravitee.io/apim_installguide_authentication_graviteeam.html

Created Client in AM 
Created Users 
![image](https://user-images.githubusercontent.com/6468268/56741986-8c1adb80-6791-11e9-9db8-dfbacf1fa8e0.png)
![image](https://user-images.githubusercontent.com/6468268/56742028-a2c13280-6791-11e9-81a1-ab0cecbb22f7.png)

In APIM added new provider 
![image](https://user-images.githubusercontent.com/6468268/56742167-da2fdf00-6791-11e9-8044-6c3f7dccb2a2.png)
with user profile mapping as follows 
![image](https://user-images.githubusercontent.com/6468268/56742241-f895da80-6791-11e9-9d7d-9acf068808a2.png)

Tried to login to Gravitee APIM portal as follows 
![image](https://user-images.githubusercontent.com/6468268/56742327-25e28880-6792-11e9-8e78-aecba91d6f47.png)
Clicking on the Login with AM returns back to the same screen

AM log shows the following 
gio_am_nginx  | 192.168.1.7 - - [25/Apr/2019:14:12:27 +0000] "GET /am/netcracker/oauth/authorize?response_type=code&client_id=apim-gw&redirect_uri=http://192.168.1.87:8002&scope= HTTP/1.1" 302 0 "http://192.168.1.87:8002/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"

No logs in APIM 

### Expected Behavior
Able to login to Gravitee APIM portal based on the user id configured in AM 

### Current Behavior
Clicking on the Login with AM with user credentials configured in AM returns back to the same login screen

### Your Environment
APIM 1.24.x
AM 2.x 
All docker containers

**Comment by tcompiegne** [comment]
In the `User profile mapping`, replace `mknair@gmail.com` by `sub`.

**Comment by tcompiegne** [comment]
You can find a example of the Gravitee.AM Login based here : 

https://demo.gravitee.io
https://auth.gravitee.io

**Comment by mknair75** [comment]
Thanks. I guess we need to populate the fields with default value . It started working after that 
![image](https://user-images.githubusercontent.com/6468268/56791556-f29d0980-6824-11e9-87c5-bcdc1ecdef70.png). Also the demo and auth websites are quite useful.

**Comment by brasseld** [comment]
> Thanks. I guess we need to populate the fields with default value . It started working after that
> ![image](https://user-images.githubusercontent.com/6468268/56791556-f29d0980-6824-11e9-87c5-bcdc1ecdef70.png). Also the demo and auth websites are quite useful.

https://github.com/gravitee-io/issues/issues/2170
