### ISSUE TITLE
[oidc][dcr] Manage id_token encryption

### ISSUE THREAD

**Issue by lusoalex** [gravitee-io/issues#2174]
This is a feature for the Access Management, we need to handle id_token encryption response.

### Expected Behaviour
According to the [specification](https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata), client may require to encrypt the id_token response with a specific algorithm
To do so, it fill theid_token_encrypted_response_alg & id_token_encrypted_response_enc property.

**Comment by tcompiegne** [comment]
closed by https://github.com/gravitee-io/graviteeio-access-management/commit/b8fe616a978b2e5f66517235601d046a4ffcec82
