### ISSUE TITLE
[oidc] [dcr] Manage request_object signature

### ISSUE THREAD

**Issue by lusoalex** [gravitee-io/issues#2181]
This is a feature for the Access Management, we need to handle request_object signature.

### Expected Behaviour
According to the [specification](https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata), client may require to sign the request_object sent to the Openid Provider.  All Request Objects from this Client MUST be rejected, if not signed with this algorithm.
To do so, it fill the equest_object_signing_alg property.

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/issues/issues/3615
