### ISSUE TITLE
[management-ui] Domain 'undefined' while setting a client to a user

### ISSUE THREAD

**Issue by wenwenbaba** [gravitee-io/issues#2183]
environment: settings->users->action(anyone user)->edit client_id;
issue: /management/domains/undefined/clients?q=xxxxx
cause: file->select-clients.component.ts->ngOnInit():
this.domainId = this.route.snapshot.parent.parent.params['domainId'];

ps: I think this is just a clerical error.

**Comment by tcompiegne** [comment]
@wenwenbaba : Indeed ! Thanks for pointing out !
