### ISSUE TITLE
[oidc] [dcr] Open DCR is not working anymore

### ISSUE THREAD

**Issue by lusoalex** [gravitee-io/issues#2198]
Since gateway refactoring (through plugins), open dynamic client registration does not work anymore. 

### Expected Behavior
We should be able to use DCR in an open (non authenticated) mode, required by OpenID certifications.

### Current Behavior
Even if we enable open DCR, client registration ends up to a 401

### Steps to Reproduce (for bugs)
1. Enable DCR & OPEN DCR
2. Register a client without an Authorization header.

**Comment by lusoalex** [comment]
@tcompiegne 
Fixed through PR #575 on Access Management

**Comment by brasseld** [comment]
bad link ?

**Comment by lusoalex** [comment]
> bad link ?

No, on the plugin management commit (#2185) , a generic Oauth2AuthHandler has been created to handle authentication.
This handler force the use of an authorization header and has been applied to the /register endpoint.
But in case of open DCR, there's no authorization header, so it was always falling in 401.
OIDC certification tools use the open mode, so it was blocking to run them.

**Comment by brasseld** [comment]
> @tcompiegne
> Fixed through PR #575 on Access Management

So the good link for the PR is: https://github.com/gravitee-io/graviteeio-access-management/pull/575 :)
