### ISSUE TITLE
[policy][rate-limit] can not work correctly

### ISSUE THREAD

**Issue by zhoumingjun** [gravitee-io/issues#2206]
Current the rate-limit policy works as following
1. read the key
2. check limitExceed
2. save the key 

load/save does not in a transaction, so rate limit can be excceeded.
e.g.
if we set the rate limit as 10 per second
```bash
# access the api for 10 seconds
hey -z 10s -c 4 http://localhost:8082/sampleapi
```
the successful request will be large then  10*10, but it should be 100

**Comment by brasseld** [comment]
Hi @zhoumingjun 

You're right, and we are currently working on a new way to manage counters:

https://github.com/gravitee-io/gravitee-policy-ratelimit/pull/26/files#diff-db2db331cdf5803db1e04bdfb46ceb60R96

But it still depends on the storage you choose... No way to do it quite nicely using MongoDB, but using redis we can ensure to not exceed the counter.

**Comment by brasseld** [comment]
Rate-limit has been fully rewritten thanks to this issue https://github.com/gravitee-io/issues/issues/2570
