### ISSUE TITLE
[gateway] Response templates improvement

### ISSUE THREAD

**Issue by brightlizard** [gravitee-io/issues#2208]
### Expected Behavior
It would be great if you will add a failure thats using response templates keys into gravitee-policy-oauth2.
It also be very useful to replace all _...failWith(PolicyResult.failure..._ to response template version on gateway component (https://github.com/gravitee-io/gravitee-gateway). It will allow to customize responses for all these cases.

And finally, response templates can be more flexible if you add the ability to set them by http-code. The simple example to illustrate this idia is modify the beggining of _ResponseTemplateBasedFailureProcessor.handleFailure_ method like this:
**...
String key = failure.key() != null ? failure.key() : Integer.toString(failure.statusCode());
        if (key != null) {
            ResponseTemplates responseTemplates = templates.get(key);
            ...**

### Current Behavior
It's not able to modify gravitee-policy-oauth2 failures
It's not able to modify gravitee-gateway failures
It's not able to modify failures by http code

### Possible Solution
see above

### Context
Response templates mechanism can be more flexible and universal

**Comment by brasseld** [comment]
Ok, so I'm waiting for your PR and it will be a pleasure to review and merge it :)

**Comment by brightlizard** [comment]
Yes, sure, we can modify oauth2 and jwt policy and make pull request according CONTRIBUTING.adoc
I think we will have time next week.

Also we can modify all ...failWith(PolicyResult.failure... in gateway component. It occurs in the code only 8 times. It gives the ability to modify response in cases like for example in SecurityPolicyChainResolver.class [line:57] 
Could you, please, confirm that you aggree with this.

Applying response template per http status code may be usefull then, for example, there is a need to transform all responses with particular code to one template. If I think up other useful example I will leave the comment here )

**Comment by brasseld** [comment]
Hi here,

Very nice job @MariaPushkin.

This will be part of 1.27.x scheduled for next month (mid-june).
