### ISSUE TITLE
[am] fix java 11 support

### ISSUE THREAD

**Issue by lusoalex** [gravitee-io/issues#2217]
The current release does not support Java 11 since JWE support feature.

### Current Behavior
JWEEllipticCurveTest introduces the use of **sun.security.ec** java package which is not part of java11 anymore.

### Possible Solution
Generate keys through nimbus dependency.

### Steps to Reproduce (for bugs)
run unit tests on AM.

### Your Environment
* Version used: master release
* Java version: 11.0.2

**Comment by tcompiegne** [comment]
closed by https://github.com/gravitee-io/graviteeio-access-management/commit/38a379a36ac89205300df308f0ed64d0486d1b57
