### ISSUE TITLE
[gateway] Allow endpoints to specify "MaxWaitQueueSize"

### ISSUE THREAD

**Issue by VitalyShachkov** [gravitee-io/issues#2218]
Vert.x http client has a property "MaxWaitQueueSize". Endpoint configuration shoud allow to set the value of this property.
I've executed several tests with diferent values of this property to show why we need it.
Let's assume that we have a service with 1000ms response time that we woud like to expose through the gateway.
I've created an API with the following endpoint configuration:
![image](https://user-images.githubusercontent.com/50508531/57565751-4d219280-73ed-11e9-9209-d84c85d3c477.png)
I got 1 core CPU, it has 2 event loops.
This configuration allows to handle 2 * 10 = 20 requests / sec.
I've executed the following test plan in jmeter:
 - 11 requests / sec during the first minute of a test;
 - 22 requests / sec later.
It provided me with the following results:
![image](https://user-images.githubusercontent.com/50508531/57565659-d0da7f80-73eb-11e9-82c4-b9cb741e3ab9.png)
![image](https://user-images.githubusercontent.com/50508531/57565809-4f382100-73ee-11e9-8394-2e0a60895b41.png)

### Expected Behavior
Wait queue should be limited (different limits are expected for different APIs).

### Current Behavior
Unlimited queue leads to undesired behaviour under pressure.

### Possible Solution
Endpoint configuration shoud allow to set the value of the property "MaxWaitQueueSize".

### Steps to Reproduce (for bugs)
1. Create an API (pipe-lining = off);
2. Calculate it's maximum performance: "event loops" * "Max concurrent connections" / "API response time";
3. Overload the API (more requests/sec than it's maximum performance).

### Context
Overloaded gateway shoud be able to handle the expected amount of requests and respond with an error code to the rest.
Timeout increasement caused by the presence of a queue should be limited.

### Your Environment
* Version used: 1.24.0

**Comment by brasseld** [comment]
Hi @VitalyShachkov 

That's a really nice analysis, thank you very much !

So your expectation would be to define the maxWaitQueue for the HTTP client. Do you think it would be preferable to let the API owner to define himself the correct value (I'm not those peoples can understand this...) or use some pre-defined values as you did (0 / max_conn / max_conn x 2 / unlimited) ?

Again, thanks a lot!

**Comment by VitalyShachkov** [comment]
Hi @brasseld 

Thanks for your reply.

I think it would be preferable to let the API owner to define himself the correct value.

The rule of thumb is: after a request have left the queue it still should have enough time to execute before "read timeout" occurs.
If not, it will be terminated due to timeout.

I think the API owner should calculate it based on formula:
maxWaitQueue = max_conn * maxAllowedTimeInQueue / endpointAverageResponseTime,
where maxAllowedTimeInQueue + endpointAverageResponseTime < ReadTimeout + someConstantForSafetyReasons

Since the API owner is the only one who knows "endpointAverageResponseTime" and "maxAllowedTimeInQueue ", he is the only one who can calculate the correct value.

0 - is a bad choice. Queue helps to smooth out local maxima.
unlimited - is a bad choice. During long overload it leads to the situation where most of the requests are terminated due to timeout.

**Comment by brasseld** [comment]
My only concern about this is the ability of the API owner for being able to define such technical value...
