### ISSUE TITLE
[portal] Try-it for anonymous user

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#222]
It seems that the try-it is enabled for all users including anonymous (non-authenticated) user.
According to me, it shouldn't be the case for security reason.

WDYT ?

**Comment by NicolasGeraud** [comment]
i'm agree,
so we need to remove the button and override the host included in the swagger.json...
Otherwise, users just have to try the api with curl.

Perhaps we have to implement the visibility of the documentation.

**Comment by brasseld** [comment]
According to me, we just have to remove or disable the "Try-it" button.

Documentation's visibility will be a new feature in Gravitee.io v4.5.4-build#1421
