### ISSUE TITLE
[gateway] Assign tags to API Key

### ISSUE THREAD

**Issue by adubreuiltk** [gravitee-io/issues#2224]
We would like to be able to apply routing rules, policies and permissions based on the API key.

### Possible Solution
Assign tags to the API key

### Context
That will allow to have a single frontend (ex: https://api.mydomain.com  and dispatch the requests to dev or production according to the API key

### Your Environment
APIM = 1.25.0

**Comment by brasseld** [comment]
Hi @adubreuiltk 

An api-key is associated to a plan, and you can add the dynamic-routing policy at the plan level.

Wouldn't be sufficient for your need ?
