### ISSUE TITLE
[users] I am able to update user via any access token

### ISSUE THREAD

**Issue by tyagiamreesh** [gravitee-io/issues#2229]
I tried to update user using PUT `http://localhost/management/domains/<mydomain>/users/28cc8331-87ca-4ecd-8c83-3187ca1ecdcf` request.

Authentication was failed, so I generated one access token using password grant by passing client credentials & user password of non admin user. I got one JWT access token & passed it to about PUT request.

It updated the user's data, which seems security thread to me.
 
### Expected Behavior
Above PUT request should only work for either client credential generated access token or a token of any admin user with admin role or user with admin scope.

It will protect other tokens to update any user's data using their access token, if they anyhow manage to get other user id.

### Current Behaviour
I am able to update user's data using password grant token generated for non-admin user with dummy scope also. 

### Context
Access management user update API.

### Your Environment
* Version used: Access management 2.4.0
* Browser Name and version: Chrome Version 73.0.3683.103 (Official Build) (64-bit)
* Operating System and version: Macbook Pro

**Comment by tcompiegne** [comment]
Hi @tyagiamreesh , same as https://github.com/gravitee-io/issues/issues/1893

Currently any users connected to the Management API have admin access.

Permissions and ACL are in our short term backlog

**Comment by tcompiegne** [comment]
duplicate #1893

**Comment by AmreeshTyagi** [comment]
@tcompiegne I think, ticket #1893 is about admin domain. I have observed it for all other domains created in AM.
For example, if I create demo.com domain & create oauth token for any user in demo.com domain, then also, I am able to access all users of this domain. `http://localhost/management/domains/demo.com/users` 

Thoughts?

**Comment by tcompiegne** [comment]
Hello @AmreeshTyagi ticket #1893 will be applied to all domains, I'm working right now on this topic. 

Here is a sneak peek : 

<img width="1678" alt="Capture d’écran 2019-12-10 à 11 59 07" src="https://user-images.githubusercontent.com/1927438/70524060-aea50d80-1b44-11ea-863d-60d6011c5a41.png">

**Comment by AmreeshTyagi** [comment]
@tcompiegne Thanks. It's really a needed feature in terms of security.
