### ISSUE TITLE
[portal] Show the number of APIs per view

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#223]
It could be very useful to print the number of APIs next to the view name.

<img width="506" alt="capture d ecran 2016-09-13 a 18 14 27" src="https://cloud.githubusercontent.com/assets/133094/18481811/f0c7844c-79dd-11e6-9151-b2dc913bf02d.png">

**Comment by NicolasGeraud** [comment]
are you sure ?
how does it help the developer ?

**Comment by brasseld** [comment]
I'm closing this because it does help developer to know the number of APIs per view.
