### ISSUE TITLE
[policies] HTTP Header Validation - Dynamic Value

### ISSUE THREAD

**Issue by GL-Gravitee2** [gravitee-io/issues#2233]
Validating Header values :

We have custom headers being sent by client and values of these headers are static in some cases
Like Basic Auth  and Dynamic in  X-ProfileSign ( timespecific ).

Is there a way , i can evaluate these headers before forwarding the call to backend.

For Basic Auth - want to store value in Gravitee.
For  X-ProfileSign - Need to call backend api to get the current value, validate incoming header with this , if they match pass the call to backend.

Thank you

**Comment by brasseld** [comment]
For the Basic auth validation, I think `Validate Request` policy is a good candidate: https://docs.gravitee.io/apim_policies_request_validation.html

For X-ProfileSign, the best would be to develop your own policy to handle your use-case (your case is technically similar to what we achieved to validate OAuth2 access_token).

**Comment by brasseld** [comment]
For the X-ProfileSign, you can also rely on the HTTP callout policy:
https://docs.gravitee.io/apim_policies_callout_http.html

This will enable you to invoke something (HTTP-based), get the result and put it as a variable in the request execution request.

Then, you can compare the value to the one provided by the API consumer by using the `Request Validation` in the same way you'll do for Basic Auth.

**Comment by GL-Gravitee2** [comment]
Hi David , Appreciate your suggestions and Validating Basic auth worked well for me.

I have one more quick question here -

Can I have a generic gateway context path?  something like  /app/v1/* .
I have read through Dynamic back end routing, but my question is on incoming.

**Comment by brasseld** [comment]
Hi,

As far as I remember, you can put regex in the context path.

**Comment by brasseld** [comment]
Is this ok for you ?

**Comment by GL-Gravitee2** [comment]
Hello David,
Thank you for your time. I looked through all the options of setting the context path while creating the API. It does not accept regular expressions.  Its really hectic to create 100 of APIs though Policies, backends are all same.

**Comment by brasseld** [comment]
Hi @GL-Gravitee2 

Why not defining a template of an API (json) and writing a script to create your 100 Apis automatically ?

**Comment by GL-Gravitee2** [comment]
Yes, Definitely  will do that. My point was from the administration point
of view.

Shilpa Sabade | Dev Ops Lead
GlobalLogic
P +1.913.315.3147  M +x.xxx.xxx.xxxx  S shilpa.sabade
www.globallogic.com
<http://www.globallogic.com/>
http://www.globallogic.com/email_disclaimer.txt

**Comment by brasseld** [comment]
Yes, I understand well.

There was an issue in the past to create some kind of API templates directly in Gravitee and then, apply one of them while creating an API.

But the issue is not part of the backlog for now...

**Comment by brasseld** [comment]
May I close this issue ?

**Comment by GL-Gravitee2** [comment]
Thank you David.
