### ISSUE TITLE
[management] Support of AsyncAPI documentation

### ISSUE THREAD

**Issue by adubreuiltk** [gravitee-io/issues#2234]
Swagger/OpenAPI is agreat tool to write API documentation, but it lacks a good support of websocket-based API.

[AsyncAPI](https://www.asyncapi.com) seems a good candidate to fit that need.

**Comment by brasseld** [comment]
Hi @adubreuiltk 

What would you like to see from this kind of support within Gravitee ?

**Comment by adubreuiltk** [comment]
Exactly the same integration as Swagger, in addition to the support of Markdown and Swagger.

**Comment by brasseld** [comment]
Do you know if there is any Java-based parser for AsyncAPI descriptor ?

**Comment by phiz71** [comment]
I think https://github.com/CreditMutuelArkea/asyncapi-parser could be a good candidate

**Comment by phiz71** [comment]
For this issue, we will only focus on the documentation and the possibility to edit and display AsyncAPI documentation.

Maybe we could have a look at these libraries:
**Console:**
 - https://github.com/asyncapi/playground

**Portal:**
  - https://github.com/asyncapi/generator
  - https://github.com/asyncapi/html-template

**Comment by ibahloul** [comment]
Topic covered in this US: https://github.com/gravitee-io/issues/issues/5575
