### ISSUE TITLE
Export of API does not export the plugin configurations 

### ISSUE THREAD

**Issue by mknair75** [gravitee-io/issues#2244]
Noted that currently exporting a particular API just writes the Plans, Groups, Members and Pages. It will be convenient if there is option given to export the Plugins and their configurations also. Is there any migration options supported ?

**Comment by aelamrani** [comment]
What do you mean by plugins? Policies?

**Comment by mknair75** [comment]
Yes policies.

**Comment by aelamrani** [comment]
IMHO, policies/resources are already part of export function...

**Comment by mknair75** [comment]
Yes . Could see the policy configuration as well being exported.
