### ISSUE TITLE
[management] Is there any endpoint to update Swagger documentation

### ISSUE THREAD

**Issue by kevinimbrechts** [gravitee-io/issues#2246]
Hi !
I don't think there is an endpoint to doing this, but I think it would be nice to update the Swagger documentation of an API from a Gravitee API endpoint. I use Jenkins CI/CD to deploy my APIs on servers, and I wish to automatically update the documentations.

What do you think ?

**Comment by brasseld** [comment]
I think you have to call an endpoint on the management-api !

Swagger are documentation pages and can be updated from your CI.

See https://docs.gravitee.io/apim/api/1.25/#operation/updatePage

**Comment by kevinimbrechts** [comment]
Thanks @brasseld.
I'll look at this.
One precision : I am using API Platform and the Swagger documentation is automatically generated from "www" external source like https://myserver/myservice/v1/docs.json.

**Comment by brasseld** [comment]
So you can't update the content of a page which is bind to an external source.
If you want to "refresh" the content according to the external source, you can invoke this service: https://docs.gravitee.io/apim/api/1.25/#operation/fetchPage

**Comment by kevinimbrechts** [comment]
Per-fect !
Thanks @brasseld ! I had missed this endpoint #rtfm ...

Last question : can we use an API name and a page name instead of IDs ?

I share this example : 
```
{
  "configuration": {
    "tryIt": "true",
    "displayOperationId": "true",
    "enableFiltering": "true",
    "showExtensions": "true",
    "showCommonExtensions": "true"
  },
  "homepage": true,
  "name": "Documentation",
  "order": 1,
  "published": true,
  "source": {
    "type": "http-fetcher",
    "configuration": {
      "useSystemProxy": false,
      "url": "http://ms-affaires/affaires/v1/docs.json"
    }
  }
}
```

Don't forget to put your credentials with basic auth.

**Comment by brasseld** [comment]
> can we use an API name and a page name instead of IDs ?

No, you can't but you can create a new issue to ask for user-friendly identifier :)
