### ISSUE TITLE
Use a user-friendly identifier instead of ID for Gravitee API

### ISSUE THREAD

**Issue by kevinimbrechts** [gravitee-io/issues#2250]
To follow up the issue #2246, it would be great to use user-friendly identifiers instead of ID for Gravitee API : `/apis/{api_name}/pages/{page_name}/_fetch`.

### Expected Behavior
Use `/apis/{api_name}/pages/{page_name}/_fetch` instead of `/apis/{api_id}/pages/{page_id}/_fetch`.

### Possible Solution
Use the name of the service, or a simple identifer (configurable field ?).
Example : 
`/apis/myapi/pages/mydocumentation/_fetch.`

Thanks.

**Comment by aelamrani** [comment]
Hi @kevinimbrechts,

We will work on the portal's URLs to provide user/SEO friendly URLs.

But in the REST APIs we will keep the IDs on the resources because the name can change but the ID not.
