### ISSUE TITLE
version 1.25.3 doesn't work 

### ISSUE THREAD

**Issue by kratosmat** [gravitee-io/issues#2257]
Hi all, I am newbie about gravitee and so the problem should be my lack of knowledge.

### Expected Behavior
I would like to publish the petstore api as described on docs.

### Current Behavior

I have installed on an ubuntu 16 the gateway, api management and ui on an apache2.
I have installed an mongodb and elasticsearch 5.6 on the same machine.
Reading the documentation, I have deployed the petstore api by importing the swagger url, but I am not able to see the methods and I am not able to subscribe an application on a plan for that api.

### Your Environment

* Version used: 1.25.3
* Browser Name and version: both chrome and firefox
* Operating System and version: ubuntu 16.04

**Comment by brasseld** [comment]
Did you create a plan ?

If so, which kind of plan ?

Also, did you start the API ?

**Comment by kratosmat** [comment]
Hi David,
sorry, it was my fault, I have created a keyless plan for that API, and so
it doesn't need the subscription, isn't it?.

Anyway, I have changed it in api key and I was able to create a
subscription.
However, I don't see the methods of petstore swagger as documented here
https://docs.gravitee.io/apim_publisherguide_manage_apis.html.

Do you know why?

Matteo Cusmai

**Comment by brasseld** [comment]
That's right, a keyless plan does not require any subscription, it is a simple pass-through plan

**Comment by brasseld** [comment]
May I close this issue ?

**Comment by kratosmat** [comment]
Hi David,
I would know if there is a way to see the resources that I have imported
with swagger.

Thanks a lot.

**Comment by brasseld** [comment]
By `resources`, you mean ?

The documentation page ?

**Comment by kratosmat** [comment]
I mean the methods inside api as showed in the figure 5

https://docs.gravitee.io/apim_publisherguide_manage_apis.html

**Comment by brasseld** [comment]
Yes, doc must be updated to follow the UI.
