### ISSUE TITLE
Oauth2 3d party

### ISSUE THREAD

**Issue by kratosmat** [gravitee-io/issues#2259]
Integration gratvitee apim with WSO2 Identity Server

### Expected Behavior
I am trying to use WSO2 IS as OAUTH2 Authorization Server.
### Current Behavior
When I configure the oauth2 resource I need to specify the basic auth credential (username and password) but there isn't way to do it.

### Your Environment
* Version used: 1.25.3
* Browser Name and version: chrome and firefox
* Operating System and version: ubuntu 16 and wso2 is 5.7

**Comment by brasseld** [comment]
There is an option to configure client credentials for a generic oauth2 resource, so I don't understand the purpose of this issue.

**Comment by kratosmat** [comment]
Sorry for my English, I don't see where I can specify the user name and
password to call the introspection endpoint of the 3d am.

**Comment by brasseld** [comment]
For a client, it is the client id and client secret

<img width="544" alt="Capture d’écran 2019-05-19 à 23 59 19" src="https://user-images.githubusercontent.com/133094/57988762-23720680-7a92-11e9-8fa1-6c6ed303d9f2.png">

**Comment by kratosmat** [comment]
OK, thanks, now it is working.

Matteo.
