### ISSUE TITLE
[management] Cannot open/access an application with a custom type

### ISSUE THREAD

**Issue by srulandhs** [gravitee-io/issues#2270]
1. Log into the portal
2. Go to the application screen
3. Create an application. Assign name, description and type: abc123
4. Click create.
5. Go back to the application list screen.
6. Click the newly create application to view it.

A red popup box displays in the lower right corner that says:
  Cannot convert [abc123] to enum of type class io.gravitee.repository.management.model.ApplicationType

The change below appears to have added an enum for ApplicationType. It attempts to parse whatever value is in the type field whenever it reads an application. This is seen in both the portal and direct API calls.

https://github.com/gravitee-io/gravitee-repository/commit/5817664f45028d951b9cdbe49f6f174a5451899d

**Comment by brasseld** [comment]
Hi @srulandhs 

I'm not able to reproduce the issue.

Can you indicate:
- The version of gravitee you are using
- The repository type you are using (mongo, postgres, ...)

Thanks

**Comment by srulandhs** [comment]
The devops team finally confirmed that they were running a mixture of 1.25.3 & 1.24.1.

Just tested locally with 1.26.0 and the issue seems to be gone.
Thanks
