### ISSUE TITLE
Migration issue from 1.25.0 to 1.26.0

### ISSUE THREAD

**Issue by adubreuiltk** [gravitee-io/issues#2276]
In addition to #521, an upgrade guide should be provided

### Expected Behavior
Whenever a new version is available, an upgrade guide would help users to upgrade to a newer version without missing any key step, including the datamodel upgrade for the databases officially supported.

### Current Behavior
Only the "**Installation guide**" is provided, but nothing about upgrade.

### Possible Solution
Update the documentation by adding a chapter "Upgrade guide" describing all the steps to migrate the app

### Steps to reproduce
- shutdown the app
- unzip the latest version of Gravitee
- updated the config/gravitee.yml with the same settings
- restarted Gravitee

I seemed to work until I tried to update an API

Here is what I see when a create a new API:
![image](https://user-images.githubusercontent.com/5410883/58151001-a947aa80-7c68-11e9-9607-6a579a7e308e.png)

Here is an API created with the previous version of Gravitee:
![image](https://user-images.githubusercontent.com/5410883/58151047-cc725a00-7c68-11e9-869b-0ea12d09d75d.png)

Moreover, when I click on "**Make public**", I get the error "**must not be null**".

### Your Environment
- Upgrading APIM from 1.25.0 to 1.26.0
- Debian 9.8
- Chrome 74

**Comment by brasseld** [comment]
Hi @adubreuiltk 

What about this ? https://docs.gravitee.io/apim_installguide_migration.html#upgrade_to_1_26_0

**Comment by adubreuiltk** [comment]
I'm really sorry, I missed it :-(
The scripts works fine. Thank you
