### ISSUE TITLE
[management] When the user registers, the mailbox returns click and I continue to register the path.

### ISSUE THREAD

**Issue by wutongan** [gravitee-io/issues#2279]
### Expected Behavior
When the user registers, we should send a valid confirmation password link to the user's designated mailbox. For example http://localhost/!#/registration/confirm/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5NDQwMTI5MEBxcS5jb20iLCJmaXJzdG5hbWUiOiJhbmFuIiwiaXNzIjoiZ3Jhdml0ZWUtbWFuYWdlbWVudC1hdXRoIiwiZXhwIjoxNTU4Njc2MjQ2LCJpYXQiOjE1NTg1ODk4NDYsImVtYWlsIjoiOTQ0MDEyOTBAcXEuY29tIiwianRpIjoiYzE2OTA4NTktZDJiMS00ZDcxLWFiNmMtYWE5NTBhMDA0YTRhIiwibGFzdG5hbWUiOiJ3dSJ9.Y_P7-WloaAJo07PSZPt03apA7-IkBO3cBAr5z0OBsmc

### Current Behavior
The current link for the x-webdoc://804A1B61-5FB6-4CB9-BB01-A2D7F263C556/null/!#/registration/confirm/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5NDQwMTI5MEBxcS5jb20iLCJmaXJzdG5hbWUiOiJhbmFuIiwiaXNzIjoiZ3Jhdml0ZWUtbWFuYWdlbWVudC1hdXRoIiwiZXhwIjoxNTU4Njc2MjQ2LCJpYXQiOjE1NTg1ODk4NDYsImVtYWlsIjoiOTQ0MDEyOTBAcXEuY29tIiwianRpIjoiYzE2OTA4NTktZDJiMS00ZDcxLWFiNmMtYWE5NTBhMDA0YTRhIiwibGFzdG5hbWUiOiJ3dSJ9.Y_P7-WloaAJo07PSZPt03apA7-IkBO3cBAr5z0OBsmc!

### Environment
* Version used: 1.20.4
* Browser Name and version:chrome 76.0.3800.0
* Operating System and version: mac10.14.4

**Comment by brasseld** [comment]
Hi @wutongan 

Please configure this property from the management-api:
https://github.com/gravitee-io/gravitee-management-rest-api/blob/master/gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml#L304

It should do the trick.

Regards,

**Comment by wutongan** [comment]
thank you very much

**Comment by brasseld** [comment]
May I close the issue?
