### ISSUE TITLE
[management] [documentation] Do not display issues after the document is uploaded

### ISSUE THREAD

**Issue by wutongan** [gravitee-io/issues#2280]
We created a new API and did not upload the document. After the creation was successful, we tried to add the document, showing that the addition was successful, but no document was displayed.

**Comment by NicolasGeraud** [comment]
hi @wutongan ,


what type of document have you tried to upload ? Is there any stacktrace on the rest-api ?

**Comment by wutongan** [comment]
I uploaded the markdown document. After uploading, I found that the uploaded markdown document content is not displayed. I don't have a stack trace, just a simple run based on the run package provided by the platform.

**Comment by NicolasGeraud** [comment]
Ok, I'm able to reproduce and include this issue in the 1.25.x backlog
