### ISSUE TITLE
[management] Partial restrictions to API

### ISSUE THREAD

**Issue by pal012** [gravitee-io/issues#2281]
Hi,
This is regarding a query on providing API restrictions. So the question is how we can provide partial restrictions to API?

Like for example, there are two clients (client 1 & client 2) who access the "/api/users" API, the response of the API will contain all fields for client 1, but few fields will be hidden for client 2.
How to solve this problem?

**Comment by brasseld** [comment]
What do you mean by client ? end-user or api consumer ?

**Comment by pal012** [comment]
API consumer.

**Comment by kurtvm** [comment]
We have the same problem.
We will use the json to json policy and make this policy conditional based on an EL expression that uses  claims of the jwt token.
I reckon we can filter out json fields with a jolt transformation. 
Another solution would be to transform json to xml in response and use an xlst and transform the response back to json.

I would be a good idea to make *all* policies conditional based on EL expressions but i've heard this feature request already exists ;-)

**Comment by brasseld** [comment]
An other option would be to use the [assign-content policy](https://docs.gravitee.io/apim_policies_assign_content.html#description).

Much more simpler than relying on jolt transformation or adding a step to transform from json to xml...
