### ISSUE TITLE
[api] TypeError: Cannot read property 'enabled' of undefined

### ISSUE THREAD

**Issue by gianx89** [gravitee-io/issues#2296]
Fresh installation of api manager 1.26. Can't see sync and start and stop button in api inside webui. When I open an Api I get this error inside the console:

TypeError: Cannot read property 'enabled' of undefined

Canìt update an api after first publication.

Running on docker

**Comment by brasseld** [comment]
Are you using a fresh MongoDB installation also or a previous one?

**Comment by gianx89** [comment]
Fresh one

**Comment by gianx89** [comment]
Docker was downloading the "wrong latest": 1.26.0 for the ui, 1.25.3 for other components. In common.yml modified every "latest" references to 1.26.0.

All it's working like a chram.
