### ISSUE TITLE
[gateway][dcr] A redirect_uri is required even if the client is created for the client_credentials flow

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#2297]
I'm creating a client with the grant client_credentials through the registration endpoint.

I got an issue with a message saying that a redirect_uris is required.

**Comment by lusoalex** [comment]
Working on it!

**Comment by tcompiegne** [comment]
closed by https://github.com/gravitee-io/graviteeio-access-management/commit/bd47839f42011fe88eef9aada14aeace8c59f014 with https://github.com/gravitee-io/gravitee-docs/commit/45a4779f9a10f563ae7976eb115771b4fe1e892e
