### ISSUE TITLE
[management] User registration fail with some characters

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#2299]
A user with special characters in his email can create an account but can't sign in.

### Additional info
- Click on Sign in
- Enter your email with a '+', for example: foo.bar+test@gmail.com
- Create a password
- Try to connect => KO

### Environment 
Reproduce in 3.10.x + (mongodb + JDBC?)

**Comment by gaetanmaisse** [comment]
Closing as everything is working fine now with `+` in email
