### ISSUE TITLE
Requirement small server

### ISSUE THREAD

**Issue by RemDav** [gravitee-io/issues#2308]
Hello everybody,

I will can use Gravitee community edition for my project. I will use between 10 and 20 epa and Kong will be my gateway epa. My serveur dispose of 2 cpu and 4 gb of Ram. There is 3000 request by minutes. Think this conf ?

**Comment by brasseld** [comment]
Hello,

You've asked the same question for Kong: https://github.com/Kong/kong/issues/4651

And you've missed to replace all Kong replace in your message.

And we don't know what is `epa`

**Comment by RemDav** [comment]
Yes i write this issue for kong but i had discover Gravitee wich match in the meantime.
Gravitee match me more.
But i had a little server.
Do you think my server will be good enough with Gravitee?
EPA = API

**Comment by brasseld** [comment]
yes, it will be ok.
