### ISSUE TITLE
[policy][oauth2] Add a cache at the policy level

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#2319]
The best practice fo oauth2 is to use an jwt plan if you don't want to request the AS on every request.

Some AS could not provide a transparent jwt token, so users must configure an oauth2 plan and call the introspection endpoint on each request.

This issue is to provide a configurable cache on the resource to cache introspection responses.

**Comment by aelamrani** [comment]
Duplicate of https://github.com/gravitee-io/issues/issues/2298
