### ISSUE TITLE
gravitee-reporter-elasticsearch should override canHandle(...) method 

### ISSUE THREAD

**Issue by VitalyShachkov** [gravitee-io/issues#2320]
We want to implement a custom Reporter & Reportable.
We don't want gravitee-reporter-elasticsearch to handle our custom Reportable, because it fails and prints a lot of errors to log.

### Expected Behavior
gravitee-reporter-elasticsearch shoud ignore Reportable-s it can not handle. 

### Current Behavior
gravitee-reporter-elasticsearch tries to handle all Reportable-s it receives. 

### Possible Solution
gravitee-reporter-elasticsearch shoud override default method canHandle(...), that always returns "true" with:
@Override
public boolean canHandle(Reportable reportable) {
   return reportable instanceof Metrics ||
         reportable instanceof EndpointStatus ||
         reportable instanceof Monitor ||
         reportable instanceof Log;
}

### Steps to Reproduce (for bugs)
1. Implement custom Reportable;
2. Report it to reportService.

### Context
We have implemented a custom Reporter & Reportable.
To use it were have to disable gravitee-reporter-elasticsearch.

### Your Environment
* Version used: 1.25.0

**Comment by brasseld** [comment]
Hi @VitalyShachkov 

Perhaps you can provide a PR ?

**Comment by VitalyShachkov** [comment]
Hi @brasseld 
I have created the PR:
https://github.com/gravitee-io/gravitee-elasticsearch/pull/53

About Reporter - it's just a custom reporter that logs into a custom logging system.
About Reportable - currently, there is no way to send results of policy execution to the Reporter.
But I am required to do this. A custom reportable surves for this purpose.

BTW, will be great if Metrics.Log will provide a way for policies to save some information into it.

**Comment by brasseld** [comment]
Hi @VitalyShachkov 

Just validated it, thanks ! 

About the ability to extend log, is it only for metrics log or request metrics ? Because metrics log mean that log must be enabled to store additional informations.

**Comment by brasseld** [comment]
Hi @VitalyShachkov 

> BTW, will be great if Metrics.Log will provide a way for policies to save some information into it.

Please fill a new issue if you think it's a missing feature.
