### ISSUE TITLE
[gateway] How can api server get caller's application name

### ISSUE THREAD

**Issue by zhaomoon** [gravitee-io/issues#2322]
### Expected Behavior

We want our api server knows which application makes the current request , so that when something goes wrong, we can log the details and inform the caller's owner。

**Comment by brasseld** [comment]
You just have to use a policy to propagate the application ID.

For example, using the transform-headers policy.

**Comment by zhaomoon** [comment]
@brasseld Thanks for your prompt reply。
Should the caller put their application ID in the header or the gateway does the work  automatically?
Thanks again!

**Comment by brasseld** [comment]
In my previous comment, I told you that you will have to attach a transform-headers policy to add the header with the app ID.

See: 
* https://docs.gravitee.io/apim_policies_transform_headers.html
* https://docs.gravitee.io/apim_publisherguide_expression_language.html#attributes

**Comment by zhaomoon** [comment]
@brasseld Worded well, Thanks。
