### ISSUE TITLE
[am][postman] dynamic client registration nrt failing

### ISSUE THREAD

**Issue by lusoalex** [gravitee-io/issues#2325]
The default [certification feature](https://github.com/gravitee-io/graviteeio-access-management/commit/fb008168f13c1fa25898480eb4e97ed1f499c7f8) has introduced a bug in the dcr postman collection.

One test is failing because it was expecting "myTestKey" as kid of the generated JWT while now it is retrieving the "default" key.  
This seems to happen randomly, as keys are not sorted, it fails only when the default key is sorted before the expected one.

### Possible Solution
In the postman collection, in the prepare folder, add a step to delete the default certificate as we are adding a custom one.

### Steps to Reproduce (for bugs)
1. make install ; make a run
2. make postman or : newman run postman/collections/graviteeio-am-openid-dcr-collection.json -e postman/environment/dev.json --ignore-redirects --insecure --bail

### Your Environment

* Version used: latest (master) on June 1st 2019.
* Operating System and version: MacOs with all latest updates.

**Comment by tcompiegne** [comment]
closed by https://github.com/gravitee-io/graviteeio-access-management/commit/89a1689d197cefe1f8029eec498ef21b078acc27
