### ISSUE TITLE
How can i create an API without any authentication?

### ISSUE THREAD

**Issue by blackstrip** [gravitee-io/issues#2333]
### Expected Behavior
Can i just make a public API, without any auth type. like a weather service.

### Your Environment
* Version used: 1.25.2
* Browser Name and version: Google Chrome
* Operating System and version: Fedora 28 Workstation

**Comment by NicolasGeraud** [comment]
hi @blackstrip ,

you have to choose the "keyless" security type on a new plan.

**Comment by blackstrip** [comment]
Cool, it's work. thx. @NicolasGeraud @aelamrani
