### ISSUE TITLE
[management] Issue while  login to Access Management UI 

### ISSUE THREAD

**Issue by geohuz** [gravitee-io/issues#2336]
### Expected Behavior

After provide the admin/adminadmin pair in the login form we should be redirected to the homepage. 

### Current Behavior

The url in the browser address bar changed to: http://localhost:4200/login/callback, and I'm getting the page shows:

```
This site can’t be reached localhost refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
```

But the homepage shows up if I continue to manually change the address to: http://localhost

The logout page has the similar problem: redirected to localhost:4200/logout/callback
 and same error page shows up.

### Steps to Reproduce (for bugs)

1. Install the lasted access management package(graviteeio-am-full-2.6.0)
2. setup the nginx page rewrite as per the document
3. open the browser
4. http://localhost:(the port number setup in nginx)

### Your Environment

* Version used: graviteeio-am-full-2.6.0
* Browser Name and version: Chrome 74
* Operating System and version: macOS mojave

**Comment by brasseld** [comment]
Are you exposing only the UI within Nginx ?

I suppose you're not exposing Nginx on the 4200 port ? Did you update the configuration (`constants.json`) to reflect that change ?

**Comment by geohuz** [comment]
@brasseld , I just followed the document, as below:

```
server {
    server_name my-app;

    index index.html;

    root /path/to/app;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
```

I just changed the root path and adding the listen xxxx; I don't know if I should exposing some other ports. Do you know if there are any other ports should I open in ngnix?

**Comment by brasseld** [comment]
No, my question was just if you change the default port or not. If not, yours is exposed over 80.

But, if the UI is expose on port 80, you must have to update the `constants.json` to reflect the port change.

Regards,

**Comment by geohuz** [comment]
My nginx default port is 7070, I have tried port 80 but the same issue arise.

**Comment by brasseld** [comment]
ok, last time I'm asking the question:

> Did you update the configuration (constants.json) to reflect that change ?

> you must have to update the constants.json to reflect the port change.

**Comment by geohuz** [comment]
Oh yeah! I changed my constants.json to following:

```
{
  "portalTitle": "Access Management",
  "baseURL": "http://localhost:8093/management",
  "authentication": {
    "domainId": "admin",
    "authorize": "http://localhost:8093/admin/authorize",
    "redirectUri": "http://localhost:7070/login/callback",
    "logoutUri": "http://localhost:8093/admin/logout?target_url=http://localhost:7070/logout/callback"
  }
}
```

And it works like a charm! 

Thanks!
