### ISSUE TITLE
[management] Lifecycle state is required when updating an API

### ISSUE THREAD

**Issue by fmercier-almerys** [gravitee-io/issues#2337]
I move to 1.26.0 and I have an error on the UI/REST API of APIM 

the UI and REST API return me error 500 "can't be null update.arg1.lifecycleState" when I want to modify any information about API.

Json payload used is extracted from api export endpoint but the endpoint response does not include the field lifecycle_state whereas for /put api/:id this key is mandatory.
Should the export endpoint include lifecycle_state in the json response to solve this issue ?

**Comment by brasseld** [comment]
Seems that you did not run the MongoDB script.

Regards,

**Comment by fmercier-almerys** [comment]
checked : Mongo upgrade script was correctly executed. I update the first description to add more information about my analysis
