### ISSUE TITLE
Add more API quality rule

### ISSUE THREAD

**Issue by fmercier-almerys** [gravitee-io/issues#2339]
* Plan must be described
* Support must be activated for the API (email defined)
* Failover activated
* XML/Json schema policy activated
* At least one Oauth2 Authenticated Plan published
* API uses service discovery

you could also create categories for rules :
* Mandatory rules
* recommanded rules
* Information rules

No consequence about quality percentage result but just for information (in the main api admin page when you list failed rule you can distinct mandatory and other rules with differents color)

**Comment by brasseld** [comment]
Support is enabled globally :)

**Comment by fmercier-almerys** [comment]
Ok I would like to said define mail contact for the api
