### ISSUE TITLE
Management API - Post page content - page created but not visible and exising also

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#234]
I created a page with this call:
Post http://xxxxx:8083/management/apis/articles-api-igr-/pages
body:
{
  "name": "api-igr-core-user-guide",
  "content": "API IGR User Guide\n==================\n\nGeneral Overview on API IGR\n----------------------------------\n\n###Specify at least one search filter\nIf you specify several filters, then you will get products that match every specified filter\n\n- For example : `cui=A0220110705000409234&soms=TAX&parent=false`  (Response Content Type= text/plain)\n- Response will be : only de block 'TAX' without their parent block 'RIN' for the product whose cui is 'A0220110705000409234'\n\nPlease note that you can use | (pipe) character to find objects matching one value or others\n\n- For example: to find all products that are in the family 8803 or 8178, then use \n`enc=8803|8178`\n- For example: to find many products then use : `cui=A0220110705000409234|A0220160331000464299`\n - Reponse will be : the 2 products sheets in the same response\n\nResponse Content Type\n----------------------\n\nYou can choose between 3 content types :\n\n1. application/xml\n\n\tResponse content is the same as IGR relational generated XML message.\n\n    The 'data' block of XML response respect exactly the data interface contract generated by relational IGR (This contracts can be consulted form the IGR editor wiki)\n\n2. application/json\n\n\tThe 'data' block of JSON response content is similar as 'data' block of XML response. You can find sames attributes that you can find in an XML interface contract.\n \n3. text/plain\n\n\tResponse content is the same as IGR relational generated file. \n\n\tThis Flat format response respect the data interface contract generated by relational IGR (This contracts can be consulted form the IGR editor Wiki) \n\n#(Get) v`<x>`/`<OGM>` #\n\nQuery parameters detail\n-----------------------\n\n###`format_version` (Query param)###\n\nFormat version, e.g PRDI42. If not specified, then the latest version of the format is used\nExample :\n`format_version=PRDI32`\n\nExample : 2 possibles choices for 'products':\n \n- PRDI32 ('product' interface contract : I32)\n- PRDI42 ('product' interface contract : I42)\n\n###`modified_since_ogm_version` (Query param) ###\n\n\nReturns only the OGMs that have a newer version than this one\n\nThe `ogm_version` is an number given by relational IGR during data integration\n\n - Where can i find the `ogm_version` of an OGM (Business Object) ?\n  - When you ask 'JSON' or 'XML' response Content Type, you can find the `ogm_version` in `meta` block at the end of each OGM sheet\n \nSo you can register this number version in order to use it during the next API call on the OGM \n\nThe aim is to manage the data freshness in your application when you request data by the way of API\n\n**For example :** \n\n\n- First call by 'products' API \n\n\t\thttp://backend_IP:8080/v0/products?cui=A0220110705000409234\n\nReponse\n\n\t...\n\t\"meta\":{\n     \"ogm_version\": 48932,\n     \"format_version\": \"PRDI32\",\n     \"id\": \"FR_BEN::PRD::10001100008\"\n    }\n    \nMy application must store \"ogm_version\": 48932 \n\n- Second call by 'products' API \n\n\t\thttp://backend_IP:8080/v0/products?`modified_since_ogm_version`=48932&cui=A0220110705000409234\n\nReponse\n\t\n\t ...\n\t \"meta\": {\n     \"ogm_version\": 48938,\n     \"format_version\": \"PRDI32\",\n     \"id\": \"FR_BEN::PRD::10001100008\"\n    }\n\nMy application must store \"ogm_version\": 48938\n\n- Third call by 'products' API \n\n\t\thttp://backend_IP:8080/v0/products?`modified_since_ogm_version`=48938&cui=A0220110705000409234\n\nResponse\n\n\t{\n\t    \"results\": []\n\t}\n\nIt means that It doesn't exist newest version (than : 48938) of this product in IGR repository.\n\nIt means the product sheet hasn't been modified since the version 48938.\n\n###`soms` (Query param) ###\n\nUse this parameter if you need a restricted response (partial response)\n\nGive a list of SOM separated by commas and as result, only these SOMs and their ancestors will be given. \n\nCommas separator must be only use for criteria list (only for `soms`)\n\nSee IGR contract interface to know the list of soms by OGM.\n\nExample: soms=RFR,TAX\n\n\thttp://backend_IP:8080/v0/products?soms=RFR,TAX\n\nResponse (blocks point of vue)\n \n\t  RIN\n        attr1\n        attr2\n        ...\n        + TAX\n        +---attr1\n\t\t+ RFR1\n\t\t+---attr1\n\t\t+ RFR2\n\t\t+---attr1\n        \n**important precision**:\n \n1. Response will **never give children** of filtered soms - \nReason : If `soms=RIN` you don't want to have all the product sheet but only the `RIN` block without their children blocks.\n\n2. By default, response will **give all the parents blocks** of filtered soms - Excepted if you use query param `parent` combine with `soms`(see it just after)\n\n###`parent` (Query param) ###\n\nIn combination with 'soms' parameter. \n\n**For content type = Text/plain:**\n\n  If `parent=false`, only selected soms are returned. \n\n  If `parent=true`, return selected soms and their hierarchy. \n\n  Default (=parent is not use in URL) is `true`.\n\n**For content type = application/json and application/xml**\n \n `parent=false` has no effect.\n  \n  Parents blocks (hierarchy) of filtered soms will always be given.\n\n  XML can't be use in an other way (hierarchy is mandatory)\n\n  Json principles are based on the same as XML for IGR API.\n\n\n###`range` (Query param) ###\n\nUse pagination (ex: 0-10).\n\nExample :\n\n\thttp://backend_IP:8080/v0/products?enc=6749&range=10-20\n\nResponse :\n\n\tProduct sheet from 10 to 20 in this search result.\n\n###Additional information\n\nhttp header response always display this 2 informations\n\n\tAccept-Ranges →products 1000\n\tContent-Range →10-20/224\n\n - Accept-Ranges is a server parameter set when API application start.\n\n   The aim of this parameter is to limit the max number of ogm sheet return by API response.\n\n - Content-Range display the information of max number sheets returned by result of current search or filter (ex: `224`)\n\n   `10-20` return the range of sheets currently display in API response.\n\n -  Default 'Content-Range' when the response hold multiple sheets and `range` query param isn't use in url is `0-49` (server parameter)\n\n - http return code is `206 - partial content`\n \n\n# (Get) v`<x>`/`<OGM>`/{id} #\n\n###`ID` (path) ###\n\nOGM ID, e.g FR::PRD::76156430999 \n\nThis is unique identifier for an OGM sheet in NoSQL database (Fastdata contener)\n\nThis unique number is composed as follow : \n\nFR is the country where IGR is instantiated\n\nPRD is the OGM type\n\n123456788... is the unique ID (equal to 'nsu_rin' in relational IGR for 'Product' OGM)\n\n###`If-Match`  (Request header) ###\n\nOGM version you have previously requested (integer).\n\nIf this is the latest version, then a 304 HTTP code and empty body will be returned.\n\n**Explanation** :\n\nIn each response when you request API by ID, you can find the last version number of the  OGM sheet in the http header response  (attribut : Etag).\n\nThis information is the same as `ogm_version` (latest ogm_version content by the NoSQL database)\n\n**Example (http header response)**:\n\n\tContent-Length →13834\n\tContent-Type →application/json;charset=UTF-8\n\tDate →Mon, 25 Apr 2016 12:06:12 GMT\n\tETag →48938\n\tServer →Apache-Coyote/1.1\n\tX-Application-Context →igrapi\n\nIf you use the Etag number content in your next query param request API by ID (header param : `if-Match`), the API try to match the number to the OGM version.\n\n**Example (http header request)** :\n\n\tAccept:application/json\n\tIf-Match:48938\n\nIf the number don't match to the latest version of OGM, then API return the lastest version OGM sheet.\n\nIf the number match to the latest version of OGM, then API return a 304 HTTP code (not modified) and empty body.\n\nSome application manage automatically the etag/if-Match.\n\n#(Get) v`<x>`/`<OGM>`/search #\n\nfull text search no allowed on each OGM\n\n\n              \n\n"
}

return is OK 201
{
  "id": "77c2f7a7-bf22-46ba-82f7-a7bf2206bad2",
  "name": "api-igr-core-user-guide",
....
  "order": 4,
  "lastContributor": "admin",
  "published": false,
  "lastModificationDate": 1475238428828,
  "contentType": "text/yaml"
}

but in portal, no document is visible any more.
get is KO 404
get http://xxxxxxx:8083/management/apis/articles-api-igr-/pages/articles-api-igr-77c2f7a7-bf22-46ba-82f7-a7bf2206bad2

and get on other page is OK 200
GET http://xxxxx:8083/management/apis/articles-api-igr-/pages/articles-api-igr-_articles-doc/

**Comment by brasseld** [comment]
You are not using the good path to get your page.

For your information, when you're creating a resource, there is location header in HTTP response after a successful POST. You can use the URI provided by this header to retrieve your created resource.

In your case, page must be accessible by calling: 

```
GET http://xxxxxxx:8083/management/apis/articles-api-igr-/pages/77c2f7a7-bf22-46ba-82f7-a7bf2206bad2
```
