### ISSUE TITLE
[management] Add metadata to a client

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#2342]
Add Client's multi key/value metadata to store custom information about an application.

Those information should be available in the OAuth 2.0 access token and OIDC ID Token JWT claims.

**Comment by szymonzo** [comment]
It would be a great idea to have this in access management, maybe not only for client_credentials flow but also for different flows as well. The token value should be customized on different levels like client or user. I am not talking about id tokens but also about access_tokens as well
