### ISSUE TITLE
[gateway] Service discovery eureka

### ISSUE THREAD

**Issue by barrycheng** [gravitee-io/issues#2354]
When I  set the backend services to a eureka service discovery, I see this log

04:04:20.531 [sync-1] [e3be00cd-0dd7-4a1a-be00-cd0dd7da1af7] INFO  i.g.g.s.s.SubscriptionsCacheService - Add a task to refresh subscriptions each 10000 MILLISECONDS for API id[test] name[e3be00cd-0dd7-4a1a-be00-cd0dd7da1af7]

10000 MILLISECONDS is so long, why health check interval can't be setting?

**Comment by brasseld** [comment]
Hi @barrycheng 

This log is not relative to SD eureka but subscriptions.

If you want to change it, you can do it from gravitee.yml (gateway) or using an env variable.

**Comment by barrycheng** [comment]
When I using a sevice discovery, the health check will no longer be checked?

**Comment by brasseld** [comment]
Health-check is still available for discovered endpoints.
You just have to configure health-check globally

**Comment by barrycheng** [comment]
Proxy ---> Backend services ---> Endpoints
When add a new goup, the Load balancing algorithm is required?
Not by applcation name from the eureka?
So I need to add at least one Endpoint?But the weight max value is 99,so at least two Endpoint?

**Comment by brasseld** [comment]
As far as I know you don't need any endpoint.

Just create an empty group and configure discovery for the group.

**Comment by barrycheng** [comment]
I add the following to graviteeio-gateway configuration file (gravitee.yml)

service-discovery:
  eureka:
    serviceUrl:
      default: http://192.168.2.43:8762/eureka

But it's not working properly, i get 502 Bad Gateway.

**Comment by barrycheng** [comment]
I add the following to graviteeio-gateway configuration file (gravitee.yml).

service-discovery:
  eureka:
    serviceUrl:
      default: http://192.168.2.43:8762/eureka

But it's not working properly,i get 502 Bad Gateway.

The log

22:46:55.661 [sync-1] [b2f20920-a2d5-428a-b209-20a2d5928a19] WARN  c.n.d.internal.util.Archaius1Utils - Cannot find the properties specified : eureka-client. This may be okay if there are other environment specific properties or the configuration is installed with a different mechanism.
22:46:55.673 [sync-1] [b2f20920-a2d5-428a-b209-20a2d5928a19] INFO  c.n.a.p.EurekaConfigBasedInstanceInfoProvider - Setting initial instance status as: STARTING
22:46:55.784 [sync-1] [b2f20920-a2d5-428a-b209-20a2d5928a19] INFO  c.netflix.discovery.DiscoveryClient - Initializing Eureka in region us-east-1
22:46:55.917 [sync-1] [b2f20920-a2d5-428a-b209-20a2d5928a19] INFO  c.n.d.p.DiscoveryJerseyProvider - Using JSON encoding codec LegacyJacksonJson
22:46:55.917 [sync-1] [b2f20920-a2d5-428a-b209-20a2d5928a19] INFO  c.n.d.p.DiscoveryJerseyProvider - Using JSON decoding codec LegacyJacksonJson
22:46:56.126 [sync-1] [b2f20920-a2d5-428a-b209-20a2d5928a19] INFO  c.n.d.p.DiscoveryJerseyProvider - Using XML encoding codec XStreamXml
22:46:56.126 [sync-1] [b2f20920-a2d5-428a-b209-20a2d5928a19] INFO  c.n.d.p.DiscoveryJerseyProvider - Using XML decoding codec XStreamXml
22:46:56.426 [sync-1] [b2f20920-a2d5-428a-b209-20a2d5928a19] INFO  c.n.d.s.r.aws.ConfigClusterResolver - Resolving eureka endpoints via configuration
22:46:56.451 [sync-1] [b2f20920-a2d5-428a-b209-20a2d5928a19] INFO  c.netflix.discovery.DiscoveryClient - Disable delta property : false
22:46:56.451 [sync-1] [b2f20920-a2d5-428a-b209-20a2d5928a19] INFO  c.netflix.discovery.DiscoveryClient - Single vip registry refresh property : null
22:46:56.451 [sync-1] [b2f20920-a2d5-428a-b209-20a2d5928a19] INFO  c.netflix.discovery.DiscoveryClient - Force full registry fetch : false
22:46:56.451 [sync-1] [b2f20920-a2d5-428a-b209-20a2d5928a19] INFO  c.netflix.discovery.DiscoveryClient - Application is null : false
22:46:56.451 [sync-1] [b2f20920-a2d5-428a-b209-20a2d5928a19] INFO  c.netflix.discovery.DiscoveryClient - Registered Applications size is zero : true
22:46:56.451 [sync-1] [b2f20920-a2d5-428a-b209-20a2d5928a19] INFO  c.netflix.discovery.DiscoveryClient - Application version is -1: true
22:46:56.451 [sync-1] [b2f20920-a2d5-428a-b209-20a2d5928a19] INFO  c.netflix.discovery.DiscoveryClient - Getting all instance registry info from the eureka server
22:46:56.637 [sync-1] [b2f20920-a2d5-428a-b209-20a2d5928a19] INFO  c.netflix.discovery.DiscoveryClient - The response status is 200
22:46:56.641 [sync-1] [b2f20920-a2d5-428a-b209-20a2d5928a19] INFO  c.netflix.discovery.DiscoveryClient - Not registering with Eureka server per configuration
22:46:56.645 [sync-1] [b2f20920-a2d5-428a-b209-20a2d5928a19] INFO  c.netflix.discovery.DiscoveryClient - Discovery Client initialized at timestamp 1560394016644 with initial instances count: 10
22:46:56.651 [sync-1] [b2f20920-a2d5-428a-b209-20a2d5928a19] INFO  i.g.g.s.e.d.v.EndpointDiscoveryVerticle - Receiving a service discovery event id[eureka:itsm-develop:uac:9000] type[REGISTER]
22:46:56.651 [sync-1] [b2f20920-a2d5-428a-b209-20a2d5928a19] INFO  i.g.g.c.e.l.i.EndpointGroupLifecycleManager - Create new endpoint: name[sd:eureka:itsm-develop:uac:9000] type[HTTP] target[http://itsm-develop:9000]
22:46:56.651 [sync-1] [b2f20920-a2d5-428a-b209-20a2d5928a19] INFO  i.g.g.c.e.f.s.SpringFactoriesEndpointFactory - Loading instances for type io.gravitee.gateway.core.endpoint.factory.EndpointFactory
22:46:56.652 [sync-1] [b2f20920-a2d5-428a-b209-20a2d5928a19] WARN  i.g.g.h.endpoint.HttpEndpointFactory - HTTP endpoint target URL is malformed for endpoint [sd:eureka:itsm-develop:uac:9000 - http://itsm-develop:9000]. Set default path to '/'
22:46:56.652 [sync-1] [b2f20920-a2d5-428a-b209-20a2d5928a19] INFO  i.g.g.http.connector.VertxHttpClient - Create HTTP Client with configuration: 
22:46:56.652 [sync-1] [b2f20920-a2d5-428a-b209-20a2d5928a19] INFO  i.g.g.http.connector.VertxHttpClient - 	HTTP {ConnectTimeout='5000', KeepAlive='true', IdleTimeout='60', MaxChunkSize='8192', MaxPoolSize='100', MaxWaitQueueSize='-1', Pipelining='false', PipeliningLimit='10', TryUseCompression='true'}
22:46:56.654 [sync-1] [b2f20920-a2d5-428a-b209-20a2d5928a19] INFO  i.g.g.s.s.SubscriptionsCacheService - Add a task to refresh subscriptions each 10000 MILLISECONDS for API id[UAC API] name[b2f20920-a2d5-428a-b209-20a2d5928a19]
22:51:56.453 [AsyncResolver-bootstrap-executor-0] [] INFO  c.n.d.s.r.aws.ConfigClusterResolver - Resolving eureka endpoints via configuration
22:54:15.006 [sync-1] [] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:9, serverValue:159}] to localhost:27017

**Comment by aelamrani** [comment]
Hi, 

The eureka service seems to be well registered. What about the health checks?

**Comment by barrycheng** [comment]
Health-check Configuration

Request
GET {endpoint}/actuator/info

The instance is http://itsm-develop:9000/actuator/info,the browser returns 200,but the  
sd:eureka:itsm-develop:uac:9000 	tradedev 	GET http://itsm-develop:9000/actuator/info 	503 | 7 ms

Assertion 	failed to resolve 'itsm-develop' after 2 queries

The instance is not registered by IP.

**Comment by aelamrani** [comment]
So i suppose `itsm-develop` is not reachable from the gateway?

**Comment by barrycheng** [comment]
Yes.I change the instance is registered by IP.It's working fine now.

**Comment by aelamrani** [comment]
Ok so i close this issue 👍
