### ISSUE TITLE
ParseException when evaluating EL in dynamic routing url

### ISSUE THREAD

**Issue by rtau-t24** [gravitee-io/issues#2359]
When setting up Dynamic Routing policy with "Redirect to" specified using SpEL, e.g. `{#endpoints['default']}/{#group[0]}/{'1','2','3'}.^[true]`, HTTP 500 is returned when request is processed through that policy.

### Expected Behavior
The request should get through instead.

### Current Behavior
HTTP 500 is returned from the gateway. The following was returned in HTTP response:
```
{"message":"io.gravitee.gateway.policy.PolicyException: java.lang.reflect.InvocationTargetException","http_status_code":500}
```

### Possible Solution
Check if https://github.com/gravitee-io/gravitee-expression-language/blob/57c086916e0619cabf76ac97f07bd954b4397eef/src/main/java/io/gravitee/el/spel/SpelTemplateEngine.java#L46 is necessary, and possibly other places as well.

In the SpEL shown above, the `{'1'` was replaced by `{'{'}'1`, rendering the SpEL invalid.

### Steps to Reproduce (for bugs)
1. On one of the endpoints, add a "Dynamic Routing" policy and specify `{#endpoints['default']}/{#group[0]}/{'1','2','3'}.^[true]` in "Redirect To".
2. Make a request to that endpoint
### Context
In the example above, I am trying to select one of the possible endpoints by SpEL Collection Selection, with the endpoints variations in Inline List.

### Your Environment

* Version used: 1.25.0
* Browser Name and version: Google Chrome 74.0.3729.169
* Operating System and version: Mac OSX 10.14.5

**Comment by brasseld** [comment]
Hi @rtau-t24 

What is the purpose of `{'1','2','3'}.^[true]` ?

**Comment by rtau-t24** [comment]
It is just an example to select the first element matching the `true` criteria. In real scenario, I would expect the `true` part to be replaced with some logic.

> Hi @rtau-t24
> 
> What is the purpose of `{'1','2','3'}.^[true]` ?

**Comment by brasseld** [comment]
I see.

Do you have any idea about what would be a better regex to substitute {} ?

**Comment by rtau-t24** [comment]
The line in src/main/java/io/gravitee/el/spel/SpelTemplateEngine.java mentioned above comes from the following commits:
1. https://github.com/gravitee-io/gravitee-expression-language/commit/c899096a2bfb7c9d3014485c0afa8f9ea5b474ea
2. https://github.com/gravitee-io/gravitee-gateway/commit/1ca3b354d859a9bd6144fa033db0d0dcdcae6a29

**Comment by rtau-t24** [comment]
May I know why do you need to substitute that? I am puzzled by the purpose of that.
> I see.
> 
> Do you have any idea about what would be a better regex to substitute {} ?

**Comment by rtau-t24** [comment]
For the example shown above, `{#endpoints['default']}/{#group[0]}/{'1','2','3'}.^[true]`, I could workaround the problem by enclosing the constant immediately following `{` with '()', i.e. `{#endpoints['default']}/{#group[0]}/{('1'),'2','3'}.^[true]`

**Comment by rtau-t24** [comment]
@brasseld for your reference, here is how the regex works like:

https://regex101.com/r/l3YodO/1

**Comment by brasseld** [comment]
I'm bit worried because I don't remember exactly why do we have to apply this substitution.... :( :( :(

**Comment by rtau** [comment]
No worry, does https://github.com/gravitee-io/gravitee-gateway/commit/1ca3b354d859a9bd6144fa033db0d0dcdcae6a29 help you remember that?

**Comment by brasseld** [comment]
Hi @rtau-t24 

I had a try by changing the REGEX to something like `\{([^#|T|(|'|a-z|A-Z])` 
But I still have an error from Spring even if the expression seems to be better now...

**Comment by gaetanmaisse** [comment]
Closing as I think it has been fixed with the recent improvements we did on `gravitee-expression-language`, for instance: https://github.com/gravitee-io/issues/issues/8217
