### ISSUE TITLE
[APIM][1.26.1] Configure health-check

### ISSUE THREAD

**Issue by julienfradillon** [gravitee-io/issues#2360]
When I configure the health-check globally for an API, the configuration is applied only to the endpoint if it is unique.
https: // <env> / # / management / apis / <my_api> / healthcheck / configure
=> remain empty
https: // <env> / # / management / apis / <my_api> / groups / default-group / endpoints / default / healthcheck
=> is filled
This also leads to a miscalculation of the score of the API because we put the health-check in pre-requisite.

**Comment by brasseld** [comment]
Please provide an export.
I did not understand well the issue here.

**Comment by julienfradillon** [comment]
Hear the export :
{
  "name": "my.api",
  "version": "1.0",
  "description": "APIAPIAPIAPIAPIAPIAPIAPI",
  "visibility": "PRIVATE",
  "paths": {
    "/": []
  },
  "resources": [
    {
      "name": "GraviteeAM-Distrib",
      "type": "oauth2-am-resource",
      "enabled": true,
      "configuration": {
        "version": "V2_X",
        "serverURL": "http://p00030600.april.interne.fr:8092",
        "securityDomain": "distrib",
        "clientId": "di_apim",
        "clientSecret": "di_apim_s",
        "userClaim": "sub"
      }
    }
  ],
  "views": [
    "emprunteur"
  ],
  "members": [
    {
      "source": "memory",
      "sourceId": "admin",
      "role": "PRIMARY_OWNER"
    }
  ],
  "pages": [],
  "plans": [],
  "path_mappings": [
    "/distribution/v1/referentiel/professions",
    "/distribution/v1/referentiel/professions/:code",
    "/"
  ],
  "proxy": {
    "context_path": "/my/api",
    "strip_context_path": false,
    "logging": {
      "mode": "CLIENT_PROXY",
      "condition": "#request.method == 'GET'"
    },
    "groups": [
      {
        "name": "default",
        "endpoints": [
          {
            "name": "default1",
            "target": "http://localhost:8080",
            "weight": 1,
            "backup": false,
            "type": "HTTP",
            "healthcheck": {
              "enabled": true,
              "trigger": {
                "rate": 1,
                "unit": "MINUTES"
              },
              "steps": [
                {
                  "name": "default-step",
                  "request": {
                    "path": "/health",
                    "method": "GET",
                    "fromRoot": true
                  },
                  "response": {
                    "assertions": [
                      "#response.status == 200"
                    ]
                  }
                }
              ],
              "inherit": false
            },
            "http": {
              "connectTimeout": 5000,
              "idleTimeout": 60000,
              "keepAlive": true,
              "readTimeout": 60000,
              "pipelining": false,
              "maxConcurrentConnections": 100,
              "useCompression": true,
              "followRedirects": false
            },
            "proxy": {
              "enabled": false,
              "host": "null",
              "port": 0,
              "type": "HTTP"
            },
            "ssl": {
              "trustAll": true,
              "hostnameVerifier": false
            }
          }
        ],
        "load_balancing": {
          "type": "ROUND_ROBIN"
        },
        "services": {
          "discovery": {
            "enabled": false
          }
        },
        "http": {
          "connectTimeout": 5000,
          "idleTimeout": 60000,
          "keepAlive": true,
          "readTimeout": 10000,
          "pipelining": false,
          "maxConcurrentConnections": 100,
          "useCompression": true,
          "followRedirects": false
        }
      }
    ]
  }
}
You can see that the health-check is configured on the end point and not on the API.

Before the 1.26.1, see a sample : 
{
  "name": "API Test (NE PAS SUPRIMER)",
  "version": "1.0",
  "description": "API pour les tests de performance",
  "visibility": "PRIVATE",
  "paths": {
    "/": []
  },
  "services": {
    "health-check": {
      "enabled": true,
      "trigger": {
        "rate": 10,
        "unit": "SECONDS"
      },
      "steps": [
        {
          "name": "default-step",
          "request": {
            "path": "/healthcheck",
            "method": "GET",
            "fromRoot": true
          },
          "response": {
            "assertions": [
              "#response.status == 200"
            ]
          }
        }
      ]
    }
  },...............

**Comment by julienfradillon** [comment]
Corrected with the version 1.27.1
