### ISSUE TITLE
[management] Enable/Disable users not working with external identity providers

### ISSUE THREAD

**Issue by jaimesf** [gravitee-io/issues#2361]
When use "Enable User" switch from user screen, this action is not updating its status on database, and user mantains old status enable or disable, if user provider is LDAP.

### Expected Behavior
Clicking on "**Enable User**" must be enable or disable user if user provider is LDAP.

### Current Behavior
Clicking on "**Enable User**" remains old status enable or disable after use the switch and refresh page.

### Possible Solution
Add an "**Update**" button on user screen, like mongodb user providers, to commit the enable/disable internal status.

### Steps to Reproduce (for bugs)
1. Create and configura an LDAP user provider, and assign to client
2. Login on any application using user and password from LDAP
3. Go to Users screen.
4. Edit the LDAP user.
5. Click on "Enable User" to disable user.
6. Refresh page to check not saved change.

### Context
You can not disable users from LDAP from UI.

### Your Environment
* Version used: 2.6.0
* Browser Name and version: Chrome, latest version
* Operating System and version: Windows 10

**Comment by tcompiegne** [comment]
Hi @jaimesf , indeed !

Currently Enable/Disable user switch work only for users create from the user management and not from the external identity providers (LDAP, inline, ...)

Should be fixed in the next 2.7.0 version
