### ISSUE TITLE
Gravitee AM - Docker Compose - NGINX Permission Denied

### ISSUE THREAD

**Issue by rotparmna** [gravitee-io/issues#2366]
I'm uploading Gravitee AM with Docker Compose, and doing pull NGINX is giving me permission denied

Output console:
`[emerg] 1#1: open() "etc/nginx/nginx.conf" failed (13: Permission denied)`

SO: Fedora 30

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/issues/issues/2438
