### ISSUE TITLE
[management] Unable to fetch API doc from URL

### ISSUE THREAD

**Issue by adubreuiltk** [gravitee-io/issues#2371]
We have an app publishing a swagger doc via a URL https://fqdn:4443/v2/api-docs

Gravitee is unable to fetch the content from that URL.

### Expected Behavior
Save the URL and fetch the content.

### Current Behavior
When saving the URL (**_< APIS >_ > Documentation > Pages > _< page >_ > External Source**), the following error is displayed:

> io.gravitee.fetcher.api.FetcherException: Unable to fetch Http content (Unable to fetch Http content 'https://fqdn:4443/v2/api-docs': no content)

If I copy-paste the URL in my browser or If I run `curl https://fqdn:4443/v2/api-docs`, the content is properly fetched.
The website is using a Let's Encrypt certificate.

The test work with other URLs.

### Steps to Reproduce (for bugs)
1. Add a new page to any API
2. Set **External Source** = https://fqdn:4443/v2/api-docs
3. Click on **Save**

### Your Environment
* Version used: 1.26.0
* Browser Name and version: Chrome 74
* Operating System and version: Win10 + Linux Debian 9

**Comment by brasseld** [comment]
Hi 

What is the jdk version ?

**Comment by adubreuiltk** [comment]
> Hi
> 
> What is the jdk version ?

Sorry, I missed that information. Here it is:

openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-2~deb9u1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)

Gravitee is running on Linux (Debian 9)

**Comment by barrycheng** [comment]
I had the same problem, the doc need [title]  [description]  [version].Without these properties, null Pointers may appear.You need to look the logs.

**Comment by aelamrani** [comment]
Please share logs

**Comment by brasseld** [comment]
That's not the same issue here...

**Comment by brasseld** [comment]
@adubreuiltk 

Do you have a stack trace from Management API logs ?

**Comment by adubreuiltk** [comment]
Here are the logs: [Gravitee.log](https://github.com/gravitee-io/issues/files/3302617/Gravitee.log)

I've just replaced the orginal URL by <MY-URL>.

**Comment by adubreuiltk** [comment]
We've upgrade to the latest version 1.27.1, but the issue is still there (see [new logs](https://github.com/gravitee-io/issues/files/3363870/logs-1.27.1.log))

What's wrong? Any idea?

The URL is reachable from Chrome and from the server where Gravitee is installed (via curl `https://api.<DOMAIN>:20026/v2/api-docs`)

**Comment by brasseld** [comment]
Did you try to tcpdump to see how Gravitee is trying to access page and what is the response ?

**Comment by adubreuiltk** [comment]
I used `tcpflow` and I got some interesting information:
- First, the content was fetched (see the end of the
- Then, there is an HTTP error 500

```
...
<truncated content>
...
showExtensions":"true","showCommonExtensions":"true"},"excluded_groups":["f8baf4eb-670a-4dd9-baf4-eb670abdd9c9","d84597a5-0df1-4c90-8597-a50df1ec9043","25c65d5e-3385-44fc-865d-5e338504fccc"]}
192.168.009.228.43986-091.134.125.059.20026: ]BT1u'] !*b7V$(=&*kj
598#'<%)g@/32,+0.2/-1b

api.<DOMAIN>
0J10UUS10Uif0b0J$$@)nb092.168.009.228.43986: ]YV1s7
0H0903133139Z0 10Uapi.<DOMAIN>0"0X30
t8O
=\k"3Xb@=+)gD#d/+>.1lDwGg'.nn_V{3?60"vd,WO)9:ps9kg\#IvZ)\%HXN~RB@}7>}E=(bLyObLLM{i"%
F't)bOyN9Wk_&69 6j0f0U0U%0++0U00Usttn,z,z00U#0Jjc}9Ee0o+c0a0.+0"http://ocsp.int-x3.letsencrypt.org0/+0#http://cert.int-x3.letsencrypt.org/0 U0api.<DOMAIN>0LU E0C0g07+0(0&+http://cps.letsencrypt.org0
vH0F!A'Qwk(ycT6XS
{`v0q~;JQ$gq2.B@*w6}f2 ?+9BX#wlLYU "fZ?~`'5;"~VZG*b%IiLF&j))|aqPR{4nS[hjlO%Fd(i&mAzX3/IRifkENOc};2%2oMIAJz!T1gDP}'<YF'$V
r,vK;'|jcU.(hCR+KYP*&Y tgq9Pu{J.&xdULy
192.168.009.228.43986-091.134.125.059.20026: FBA@nJH{i)=<ekr>8Z=RliHxT@xt(O:/e^E_.a)L%|?
ZMlZ9"";;I`,}R,%HY&Zd90wu+F@4xU}wyTm>7/^7dY]w4Te(xOtk}_K_8fBKE(=ZBe]~UX{9c-/xE\E^O *
091.134.125.059.20026-192.168.009.228.43986: KE(z~@vZa
192.168.009.228.43986-091.134.125.059.20026: kY|~u:U)QSifHTs<mrCBVSi~<d
0Pm PN&uh,vBGPo
192.168.009.228.43986-091.134.125.059.20026: 9*6H)~c
192.168.009.228.08083-192.168.009.254.48932: HTTP/1.1 500 Internal Server Error
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Access-Control-Allow-Origin: https://portal.oonacloud.com
Access-Control-Expose-Headers: ETag
Access-Control-Allow-Credentials: true
Content-Type: application/json
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Length: 211

{
  "message" : "An error occurs while trying to fetch content. Unable to fetch Http content (Unable to fetch Http content 'https://api.<DOMAIN>:20026/v2/api-docs': no content)",
  "http_status" : 500
}
192.168.009.228.56620-192.168.009.225.08080: GET /api/workflow HTTP/1.1
host: www2.app.aavaservices.com:8080
accept-encoding: deflate, gzip
connection: close
```

**Comment by brasseld** [comment]
Sorry but I need a complete tcpdump to understand what's going wrong there.

> tcpdump -i network_interface port 20026 -s 0 -A

**Comment by brasseld** [comment]
shit, it's an https URL.... so I can't see anything from the tcpdump :(

**Comment by adubreuiltk** [comment]
right :-(
How can I help?

**Comment by brasseld** [comment]
That's a pretty good question...

**Comment by aelamrani** [comment]
@adubreuiltk do you have any configured HTTP proxy?

**Comment by brasseld** [comment]
@adubreuiltk do we need some authentication / credentials to access the swagger from the management-api ?

**Comment by adubreuiltk** [comment]
@aelamrani ,
Yes, Gravitee is behind HA Proxy (acting as reverse proxy and ssl offload)

@brasseld ,
No. The Swagger spec is published via a simple url, but it is hosted out of our network. For security reasons, The swagger remote host can only be reached from our network (whitelisted IP address).

No auth/credential is required.

**Comment by brasseld** [comment]
I don't see any reason for which gravitee is not able to get the content of the swagger...

The best would still be to get the tcpdump content between gravitee and the swagger server...
