### ISSUE TITLE
[am][ui] On saving Oauth2 settings for a client "Missing or invalid redirect_uris" always displayed

### ISSUE THREAD

**Issue by jaimesf** [gravitee-io/issues#2375]
On saving Oauth2 settings for a client "Missing or invalid redirect_uris" always displayed even field its filled.

### Expected Behavior
On save Oauth2 settings for a client, must be save settings even field "Redirect URIs" its filled or not (Not mandatory field)

### Current Behavior
On saving Oauth2 settings for a client, "Missing or invalid redirect_uris" message always shown even field its filled.

### Steps to Reproduce (for bugs)
1. Create a security domain
2. Create a client
3. Go yo client settings/Oauth2 tab
4. Click on Save button

### Your Environment
* Version used: 2.7
* Browser Name and version: Chrome, latest version
* Operating System and version: Windows 10 pro

**Comment by brasseld** [comment]
Did you press "enter" when filling "Redirect URIs" field ?

You have to do so before saving client settings.

**Comment by jaimesf** [comment]
It's required on this version?

> Did you press "enter" when filling "Redirect URIs" field ?
> 
> You have to do so before saving client settings.

**Comment by brasseld** [comment]
Redirect URIs are required depending on the grant types associated to the client.

**Comment by jaimesf** [comment]
And now, http scheme it's mandatory? For developers on local environments it's a hard way...

**Comment by jaimesf** [comment]
if it's so, we need to use 2.6 for now... :(

> And now, https scheme it's mandatory? For developers on local environments it's a hard way...

**Comment by brasseld** [comment]
https schema is mandatory by default (because of the oauth2 / oidc specifications).
you can still revert back this configuration from security domain configuration (allows http, allow localhost, ...)

**Comment by jaimesf** [comment]
And where can i revert this config? It's possible set it through UI?

> https schema is mandatory by default (because of the oauth2 / oidc specifications).
> you can still revert back this configuration from security domain configuration (allows http, allow localhost, ...)

**Comment by brasseld** [comment]
https://auth.gravitee.io/domains/gravitee/settings/openid/clientRegistration

**Comment by jaimesf** [comment]
Thanks for your time. Closing the issue.

> https://auth.gravitee.io/domains/gravitee/settings/openid/clientRegistration
