### ISSUE TITLE
[portal] : Add application analytics

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#238]
Currently there is no analytic for an application/consumer.

We have to display the following data, according to the selected application : 

- Top APIs
- Response Status
- Global response times
- Hits by APIs

The user will be able to filter by API and select timeframe and a specific date.

**Comment by NicolasGeraud** [comment]
how could we display Plans on this dashboard ?

**Comment by brasseld** [comment]
@NicolasGeraud do you think there is sense to show Plans on this "dashboard" ?
According to me, it should be available only at the "API" level, no ?
