### ISSUE TITLE
[policy] [callout-http] Calls are not reaching when no variable is defined

### ISSUE THREAD

**Issue by GL-Gravitee2** [gravitee-io/issues#2383]
Below is the design i tried to set up.

/hmac/v1/validation call gets triggered, which has  HTTP callout. If HTTP call out results in HTTP 200, call need to proceed and hits the endpoint.
HTTP callout is not being called out. ( no API calls)

HTTP callout  [HmacValidate_keyManager_API ]

[export.zip](https://github.com/gravitee-io/issues/files/3303463/export.zip)

 /km/v1/validate is a  Mock API, which just validates incoming query param and returns the response.
When I call HTTP callout APIs /km/v1/validate like  /km/v1/validate?token=1C3BD5KT6DT007111 from browser it works as expected.

Attaching API exports for your reference.

**Comment by brasseld** [comment]
Do you mean that the callout is never run ?

**Comment by GL-Gravitee2** [comment]
> Do you mean that the callout is never run ?

Yes , i dnt see  HTTP callout being made.

**Comment by GL-Gravitee2** [comment]
Hi David ,

Any suggestions to make this work?

**Comment by brasseld** [comment]
Which version ?

**Comment by GL-Gravitee2** [comment]
1.22.1

**Comment by brasseld** [comment]
So, according to the documentation: https://docs.gravitee.io/apim_policies_callout_http.html

`If no variable has been configured the result of the callout will not be available anymore.`

This statement is very clear because the callout policy is not run if no variable is defined...

I suppose it makes sense to run the callout policy event if there is no variable defined because you're expecting no response content from the target endpoint?

**Comment by GL-Gravitee2** [comment]
Yes, am not expecting response body content but looking for HTTP response code. 
Am using ,
"errorCondition": "{#calloutResponse.status >= 400 and #calloutResponse.status <= 599}",
isnt the  calloutResponse variable here?

**Comment by brasseld** [comment]
It is. But to run the policy you must have  to define, at least, one variable.
If you do not,  the http callout will not be done.

So, as a workaround, please set a dummy variable.

**Comment by brasseld** [comment]
Is it ok for you with this workaround ?

**Comment by GL-Gravitee2** [comment]
Hi David, 

Yes workaround did help. I have one question here though. Where can i see callout related logs ( API request and response )?

**Comment by brasseld** [comment]
Hi @GL-Gravitee2 

You can't get callout related logs.

We have a "tracing" topic in the backlog, I'm sure that such logs should have their place in it.

**Comment by brasseld** [comment]
I'm renaming the issue.
