### ISSUE TITLE
[question] Request validation Policy

### ISSUE THREAD

**Issue by barrycheng** [gravitee-io/issues#2387]
I want to validate the name parameter.
![1](https://user-images.githubusercontent.com/8085838/59841223-7b987300-9386-11e9-8946-34f0adef93d0.png)

![2](https://user-images.githubusercontent.com/8085838/59841287-9a970500-9386-11e9-9b7f-e71c6c7de004.png)

What the rule need to fill in?What the rule and parameters mean?

**Comment by aelamrani** [comment]
The `field value` must be defined using expression language: https://docs.gravitee.io/apim_publisherguide_expression_language.html

As described on the field's hint, the parameter must be defined with min/max/pattern, so not with the NOT_NULL constraints which it makes no sense.

Cf https://docs.gravitee.io/apim_policies_request_validation.html

Is it clearer to you?

**Comment by barrycheng** [comment]
OK, THX !

**Comment by barrycheng** [comment]
Rule
{#request.params['name']}
Constraint
NOT_NULL

The response data.
{
    "message": "{\"message\":\"Request is not valid according to constraint rules\",\"constraints\":[\"'null' can not be null.\"]}",
    "http_status_code": 400
}

The name property value is not retrieved.

**Comment by brasseld** [comment]
It should be something like `{#request.params['name'][0]}` because you can have multiple values for a single param name.

**Comment by barrycheng** [comment]
@brasseld
The params description is request query parameters, looks like http://192.168.2.40:8082/uac/syetem/user/add?**name=111**

#request.params can't get the request body.

{#request.params['name'][0]} cause a exception.
org.springframework.expression.spel.SpelEvaluationException: EL1012E: Cannot index into a null value

**Comment by barrycheng** [comment]
@brasseld
I debug the plugin logs.

05:20:41.375 [vert.x-eventloop-thread-13] [] INFO  i.g.p.r.RequestValidationPolicy - request ---> io.gravitee.gateway.reactor.handler.http.ContextualizedHttpServerRequest@1b9d3a03
05:20:41.375 [vert.x-eventloop-thread-13] [] INFO  i.g.p.r.RequestValidationPolicy - content ---> name=1222

{#request.content[0]} can get, but the index can't hard-coded.

**Comment by brasseld** [comment]
Sorry, but I don't understand what you're looking for.

Are you trying to valide the content of the request body ?
If yes, you have to configure the policy to bind it to the REQUEST_CONTENT scope.
Then, the content of the body will be available from `{#request.content}`

**Comment by barrycheng** [comment]
@brasseld
REQUEST_CONTENT scope has been configured.
{#request.content} how to get the name properties in the body.Look at the picture on the first floor.

**Comment by brasseld** [comment]
something like `{#request.content.split("=")[1]}` ?

**Comment by barrycheng** [comment]
@brasseld
If i have more than one property, this is not correct.

![123](https://user-images.githubusercontent.com/8085838/60311033-f0237100-9987-11e9-9a4a-d2f3deb1a34e.png)

**Comment by brasseld** [comment]
so you have to search for the correct code (regex).
you ask me for one property, I gave you an example for this property.
