### ISSUE TITLE
[policy] [xslt] EL support for XSL stylesheet parameters

### ISSUE THREAD

**Issue by sjanssens1977** [gravitee-io/issues#2393]
It would be convenient to have SpEL support for the XSL stylesheet parameters.

### Expected Behavior
A parameter value would be evaluated by the SpEL engine and the result is used a the parameter value for the XSL transformation.

### Current Behavior
At present it is only possible to use fixed text as a parameter value.
When EL support is added it becomes possible to inject the result of any SpEL expression into the XLS transformation as a parameter value.

### Possible Solution
Enhance the current implementation.

### Steps to Reproduce (for bugs)
n.a.

### Context
I want to be able to inject a context attribute as a XSL stylesheet parameter.

### Your Environment
n.a.

**Comment by brasseld** [comment]
Thanks for the PR @sjanssens1977 !
