### ISSUE TITLE
[am] After create an association group-role, authentication stop working

### ISSUE THREAD

**Issue by jaimesf** [gravitee-io/issues#2395]
With a new domain and new client, after create an association group-role on identity provider, authentication fails. It happens when user logged in, is not a member of all groups associated to roles

No logs on console indicating that login fail.

Only fails if group (Linked to role through identity provider) has no members.

### Expected Behavior
Create an association group-role with empty groups must works after users log in

### Current Behavior
Login fail with no logs, after creating new scopes, groups, roles, and association on identity providers, with empty groups

### Possible Solution
¿?

### Steps to Reproduce (for bugs)
1. Create a scope
2. Create a role, and add the scope
3. Create a group
4. Create association group-role on identity provider
5. Create new user on identity provider (i.e. Mongo provider)
6. Activate identity provider on client
7. Try to log in
8. Fails silently

### Context
Create new scopes, roles and groups must not affect to the system

### Your Environment
* Version used: 2.6.0 and 2.7.0
* Browser Name and version: Chrome, latest version
* Operating System and version: Windows 10 pro

**Comment by jaimesf** [comment]
Conflict with share database, nevermind.

**Comment by jaimesf** [comment]
The only visible trace is 
`
Caused by: com.mongodb.MongoBulkWriteException: Bulk write operation error on server mongodb:27017. Write errors: [BulkWriteError{index=0, code=11000, message='E11000 duplicate key error collection: gravitee-am.reporter_audits_synopsis index: _id_ dup key: { : "c9b80cf2-77c7-4d1e-b80c-f277c79d1e39" }', details={}}]. 
`
but just first time we try log in

**Comment by jaimesf** [comment]
Using command line to get token via grant type password, the result is:
`{
  "error" : "invalid_grant"
}`
Adding the user to a group, it works, and removing, stop working.

Test it with docker-compose from official docs.

**Comment by tcompiegne** [comment]
Hi @jaimesf seems related to https://github.com/gravitee-io/issues/issues/2073

**Comment by jaimesf** [comment]
> Hi @jaimesf seems related to #2073

yes, same behavior
