### ISSUE TITLE
The gravitee-reporter-kafka has NOT been started.

### ISSUE THREAD

**Issue by fabiopskock** [gravitee-io/issues#2398]
The gravitee-reporter-kafka has NOT been started.
I can not use this plugin. I put it in the configuration file (gravitee.yml), but It is not loading in Gravitee’s initialization.

` 
23:37:43.539 [graviteeio-node] [] INFO  i.g.p.c.internal.PluginRegistryImpl - Loading plugin from /root/API-MG/graviteeio-full-1.27.0/graviteeio-gateway-1.27.0/plugins/gravitee-reporter-kafka-master.zip
… 
`

`
23:37:43.738 [graviteeio-node] [] INFO  i.g.p.c.internal.PluginRegistryImpl - List of available reporter:
23:37:43.739 [graviteeio-node] [] INFO  i.g.p.c.internal.PluginRegistryImpl -   > elastic [1.27.0] has been loaded
23:37:43.740 [graviteeio-node] [] INFO  i.g.p.c.internal.PluginRegistryImpl -   > file [1.5.0] has been loaded
23:37:43.740 [graviteeio-node] [] INFO  i.g.p.c.internal.PluginRegistryImpl - List of available service:
....
`

gravitee.yml -> 
...
reporters:
  kafka:
    enabled: true
    hosts:
      - localhost:9092
    topic: test
    type:
      - log
      - monitor
    settings:
      acks: 1
...

**Comment by fabiopskock** [comment]
Follow mor information:

Gravitee: 1.27.0
gravitee-reporter-kafka: the last
Mongo: 3.2.11



[gravitee.log](https://github.com/gravitee-io/issues/files/3319039/gravitee.log)

[gravitee.yml.txt](https://github.com/gravitee-io/issues/files/3319042/gravitee.yml.txt)

**Comment by aelamrani** [comment]
Where the plugin come from?

**Comment by fabiopskock** [comment]
Follow the plugin link:  https://github.com/gravitee-io/gravitee-reporter-kafka

**Comment by aelamrani** [comment]
Ok so that's the problem.

You should download the plugin from either Maven central or https://download.gravitee.io/graviteeio-apim/plugins/ not from the sources

**Comment by fabiopskock** [comment]
It's working now. 
Thanks.
