### ISSUE TITLE
[apim][portal] Unable to access API picture behind proxy on url subcontext

### ISSUE THREAD

**Issue by jaimesf** [gravitee-io/issues#2400]
API picture url is not generated correctly. If you put APIM behind nginx with subcontext ( /apim/management i.e.) url is refered to root (/management)

### Expected Behavior
API picture urls must referer to relative url to generate a good url picture.

i.e **http://host/subcontext/management/apis/XXXXXX-XXXXXX-XXXXXX-XXXX/picture** instead **http://host/management/apis/XXXXXX-XXXXXX-XXXXXX-XXXX/picture** 

### Current Behavior
URL is generating to root management: http://host/management/apis/XXXXXX-XXXXXX-XXXXXX-XXXX/picture

### Possible Solution
Use relatives URL to build url picture on portal

### Steps to Reproduce (for bugs)
1. Put APIM portal behind nginx on a subcontext
2. Create an API
3. Enter on API details
4. API picture is not showing

### Context
Affected to publish APIs with pictures

### Your Environment
* Version used: APIM 1.26.1
* Browser Name and version: Chrome latest stable
* Operating System and version: Windows 10 pro

**Comment by brasseld** [comment]
Hi @jaimesf 

Please check x-forward headers from nginx configuration.

**Comment by jaimesf** [comment]
What is the correct setup for x-forward headers?

This is my config

```
                        location /apim/portal/ {
			  proxy_pass http://managementui_apim/;
			  proxy_redirect $scheme://$host:$server_port/ $scheme://$http_host/apim/portal/;
			  proxy_set_header  Host $host;
			  proxy_set_header  X-Real-IP $remote_addr;
			  proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
			  proxy_set_header  X-Forwarded-Host $server_name;
			}

			location /apim/management/ {
			  proxy_pass http://managementapi_apim/management/;
			  proxy_set_header   Host $host;
			  proxy_set_header   X-Real-IP $remote_addr;
			  proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
			  proxy_set_header   X-Forwarded-Host $server_name;
			  proxy_set_header   X-Forwarded-Proto $scheme;
			}
```

**Comment by brasseld** [comment]
I suppose you have to add a proxy_redirect rule for /apim/management location to let nginx rewrite URLs.

**Comment by jaimesf** [comment]
Adding the rule
`
proxy_redirect $scheme://$host/management/apis/ $scheme://$http_host/apim/managements/apis/;
`
still not working. Any clue to make it work?

**Comment by aelamrani** [comment]
@jaimesf i think you have a typo `$scheme://$http_host/apim/managements/apis` instead of `$scheme://$http_host/apim/management/apis`

**Comment by jaimesf** [comment]
> @jaimesf i think you have a typo `$scheme://$http_host/apim/managements/apis` instead of `$scheme://$http_host/apim/management/apis`

It was a typo, but anyway, still does not working :(

**Comment by jaimesf** [comment]
Finally i solved it with a workaround:
`
location ~ ^/management/apis/(.*)/picture(.*)$ {
    proxy_pass http://managementapi_apim/management/apis/$1/picture$2;
    proxy_set_header   Host $host;
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Host $server_name;
    proxy_set_header   X-Forwarded-Proto $scheme;
}
`

**Comment by brasseld** [comment]
I'm not sure that it's the best to handle it because there are other resources for which a picture is associated (the user avatar for example) and in the future for application.

**Comment by jaimesf** [comment]
Probably not the best solution, but for now, it's a solution.
