### ISSUE TITLE
Can't make Oauth2 Authentication work

### ISSUE THREAD

**Issue by jonrmar** [gravitee-io/issues#2402]
Cannot call an endpoint from our backend using OAuth2 authentication strategy.

### Expected Behavior
Call backend through Gravitee API Gateway using oauth2 as authentication.

### Current Behavior
We successfully created a token using endpoint: _**"/am/ubotsexternal/oauth/token"**_. But when we try to use this token to call mocked\real backend  we receive a Unauthorized status code in response. In the logs we saw that access management return 200 for token introspection **_"/check_token"_**, but after that no call is made in backend and no log shows any more information. Trying calling the backend using a keyless plan works fine.

### Steps to Reproduce (for bugs)
1. Install API Management and Access Management through docker-compose files (got from documentation)
1. Create a Gravitee Access Management client domain.
2. Create a client for that domain, assign a clientId, enable Default Identity Provider.
3. In Oauth2 tab select Credentials as Grant type.
4. In Gravitte API Management: Import an existing API from a swagger descriptor.
5. Mock an endpoint in API > Design > Policies.
6. Create a Resource in Design > Resource. Select Gravitee.io AM Authorization Server Resource, fill Server URL with AM URL. Fill domain, clientId and clientSecret with values created in previous steps.
6. Create a OAuth2 plan and set resource with the one created. Plublish the plan.
7. Create an Application. In Oauth2 Integration Section fill clientId with the one created in AM.
8. Subscribe application to API using oauth2 plan.
9. Call the mocked\real backend. 

### Context
I our company we began evaluating Gravitee API Gateway and one of the requirements is to have OAuth2 as authentication to call our APIs. We followed the documentation but couldn't make it work. We tried calling the API using a keyless plan and it works, but when we try to make a call using oauth2 we receive an Unauthorized status response and the following response header **WWW-Authenticate →Bearer realm="gravitee.io", error="invalid_client", error_description="No client_id was supplied"**, we tried to set logs as DEBUG and saw that AM logs shows that endpoint _**"/check_token"**_ returns **200**, but after that nothing is logged in AM or API Management. 

### Your Environment
* Version used: 1.27.0
* Browser Name and version: Chrome,  72.
* Operating System and version: Ubuntu, 16.04

**Comment by marcelocure** [comment]
Facing the same issue here, can we give some priority here? thanks in advance

**Comment by brasseld** [comment]
Hi @jonrmar @marcelocure 

You have a description to the error : `No client_id was supplied` 
Which version of AM are you using ? And also, which kind of oauth2 resource did you define from APIM ?

**Comment by brasseld** [comment]
Hi @marcelocure you had asked us to give some priority to this issue, but you didn't respond to our questions.

May we close the issue?
