### ISSUE TITLE
[management] APIM portal not sending scope as param on request to Gravitee AM configured as identity provider

### ISSUE THREAD

**Issue by jaimesf** [gravitee-io/issues#2407]
Error trying authentication on api manager, with Gravitee AM as identity provider.

The request url to AM, is not including scope parameter even scope are set on identity provider config page,

URL request is `/am/synopsis/oauth/authorize?response_type=code&client_id=client-id&redirect_uri=https://host/portal/&scope=`

### Expected Behavior
Clicking on "Signin with Gravitee" button, must show login page

### Current Behavior
Clicking on "Signin with Gravitee" button, try to open login page, but close it inmediately, redirecting to url `/portal/?client_id=client-id&error=invalid_scope&error_description=Invalid+parameter%253A+scope+must+not+be+empty`

### Possible Solution
Include the scope value on url request

### Steps to Reproduce (for bugs)
1. Configure Gravitee AM as identity provider on API manager, (Setting up scope correctly. i.e.: openid)
2. Log out
3. Try to log in with Gravitee AM

### Your Environment
* Version used: AM 2.7.0, APIM 1.26.1
* Browser Name and version: Chrome latest stable
* Operating System and version: Windows 10 pro

**Comment by jaimesf** [comment]
It works again with no reason...

**Comment by aelamrani** [comment]
I keep this issue opened as it seems the UI has to be refreshed to take care of configuration of scopes, and this is a bug

**Comment by jaimesf** [comment]
> I keep this issue opened as it seems the UI has to be refreshed to take care of configuration of scopes, and this is a bug

Yeah, it is the problem, i needed refresh landing page to make it works
