### ISSUE TITLE
AM docker demo fails, nginx issue

### ISSUE THREAD

**Issue by pvdh** [gravitee-io/issues#2422]
I try to follow https://docs.gravitee.io/am/2.x/am_installguide_docker.html, but don't get an operational demo environment.

### Expected Behavior
Accessing http://localhost:80 should return a login form

### Current Behavior
Accessing http://localhost:80 returns 404

Docker logs show:
gio_am_nginx  | 2019/07/02 11:49:53 [error] 8#8: *1 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost"
gio_am_nginx  | 172.21.0.1 - - [02/Jul/2019:11:49:53 +0000] "GET / HTTP/1.1" 404 555 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"

### Steps to Reproduce (for bugs)
1.curl -L http://bit.ly/graviteeio-am | bash
2.google-chrome http://localhost:80/

### Context
I'm trying to get a demo and try quickstart.

### Your Environment
Ubuntu 18.04 LTS

**Comment by brasseld** [comment]
According to the documentation: 

http://localhost:80/am or http://localhost:80/am/ui

**Comment by pvdh** [comment]
Those URLs work, thank you. But where am I supposed to find them in the documentation? Quickstart guide at https://docs.gravitee.io/am/2.x/am_quickstart_register_app.html clearly refers to http://localhost without "/am" and the docker instructions do not point out that docker installs to a different endpoint.

Something like "quickstart guide refers to http://host/ but with docker you need to use http://host/am instead" would be a nice addition.

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/gravitee-docs/commit/1b2afcede4aadcde7da7a40020e684f029d0c1fe
