### ISSUE TITLE
Subscriber area on API portal for analytics exposition

### ISSUE THREAD

**Issue by fmercier-almerys** [gravitee-io/issues#2423]
Hi

My api consumers want some metrics but currently I have to send them by mail
I created a SUPERVISOR_ROLE for management api but I restrict this role for internal use only because management area is too critical
even with a role dedicated to analytrics some internal data are exposed
For now api catalog is only a catalog but It could provide more data specific to each subscription
allowing subscribers to get alone lot of information
as a personal space for apis usage etc...

**Comment by brasseld** [comment]
No more relevant with v3
