### ISSUE TITLE
[feature][policy] way to conditionally activate different policies

### ISSUE THREAD

**Issue by chicco785** [gravitee-io/issues#2433]
suppose you have two policies that should be alternatively activated based on some conditions (e.g. on the existence of a given header attribute). is there an easy way to achieve that?

**Comment by brasseld** [comment]
Hi @chicco785 

There is currently no way to achieve such thing.
We have an (very) old issue about conditional policies: https://github.com/gravitee-io/issues/issues/60

**Comment by aelamrani** [comment]
Duplicate of https://github.com/gravitee-io/issues/issues/60
