### ISSUE TITLE
[portal] API Key not passed when click on "Try it out" with API key

### ISSUE THREAD

**Issue by adubreuiltk** [gravitee-io/issues#2437]
After configuring an Open API 3 documentation, the feature "Try it out" does not work when an api-key is mandatory (and properly configured).

![image](https://user-images.githubusercontent.com/5410883/60769340-b4e31980-a0ce-11e9-87ca-7641e590e1ae.png)

Note: We use a _custom APK key_.

### Expected Behavior
The "**Try it out**" feature fails

### Current Behavior
The API key is not properly passed in the header.

### Possible Solution
Parameter missed when the function _Try it out_ is triggered?

### Steps to Reproduce (for bugs)
1. Create an OpenAPI 3 documentation
2. Enable the API key auth
3. Click on _Try it out_
4. check the trace in Chrome/Firefox
![image](https://user-images.githubusercontent.com/5410883/60769396-66824a80-a0cf-11e9-8e91-48a6a75e406e.png)

Trace from Chrome:
![image](https://user-images.githubusercontent.com/5410883/60769441-ef00eb00-a0cf-11e9-8e5c-152d038796c0.png)

### Context
- The API has been renamed
- The API key is mandatory (only one plan configured)

The http error 400 might be related to https://github.com/gravitee-io/issues/issues/2435, but when fixing it manually via cURL, we have a http 401 error because of the lack of the API key.

### Your Environment
* Version used: 1.27.1
* Browser Name and version:
* Operating System and version: Debian 9

**Comment by brasseld** [comment]
@adubreuiltk can you share a light swagger with api-key sec definition to make it much simpler for us to (try) reproduce the issue.

Thanks.

**Comment by rhaezebrouck** [comment]
See the enclosed swagger to reproduce the issue:

[openapi.tar.gz](https://github.com/gravitee-io/issues/files/3668149/openapi.tar.gz)

**Comment by brasseld** [comment]
Hi @rhaezebrouck 

Seems that the archive is corrupted.

**Comment by rhaezebrouck** [comment]
Hi @brasseld 

You should be able to reproduce with the following spec.
Same as @adubreuiltk - I'm able to key in the API key but it is not sent to the API when "trying it" 

openapi: 3.0.0
info:
  title: Sample API
  version: '1.0'
servers:
  - url: 'https://api.gravitee.io'
paths:
  /echo:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
      security:
        - API Key: []
      requestBody: {}
    parameters: []
components:
  schemas: {}
  securitySchemes:
    API Key:
      name: x-api-key
      type: apiKey
      in: header

**Comment by rhaezebrouck** [comment]
Or in case the inline yaml is also corrupted, this one should work :)
[openapi.yaml.zip](https://github.com/gravitee-io/issues/files/3673356/openapi.yaml.zip)

**Comment by brasseld** [comment]
That's ok with both! 

We'll have a look.

Thanks!

**Comment by brasseld** [comment]
:fu: bot

**Comment by brasseld** [comment]
Hi @adubreuiltk / @rhaezebrouck 

I had a quick look to this issue... and there is no problem at all.

@adubreuiltk according to your screenshot, we are in the context of a preflight request (CORS), so there is no need for an api-key there.

The issue I'm seeing is that CORS is not / not well configured.

Here is a typical CORS example with the OAI provided by @rhaezebrouck:

![Capture d’écran 2019-10-29 à 13 51 18](https://user-images.githubusercontent.com/133094/67768631-3fbb9b80-fa53-11e9-8ce7-7cd9e587b9b3.png)

**Comment by phenompavan** [comment]
Hi,

I just setup the 3.3.3 version of Gravitee and I don't see the **try it out** option. Can someone help me to find that option in developer portal please?

**Comment by aelamrani** [comment]
Hi @phenompavan ,

You have to configure it on your page. By default the try it is not enabled.

**Comment by phenompavan** [comment]
Thank you @aelamrani . I enabled it, but where do I see that option in developer portal?
