### ISSUE TITLE
Management : Option to disallow the api-key in query params

### ISSUE THREAD

**Issue by Gwalchmei** [gravitee-io/issues#2446]
As an administrator, I don't want my clients to pass their api keys in the query params `?api-key` but only in the HTTP Header.

### Expected Behavior

 Add a parameter in the global settings to allow/disallow keys in query params. If the `?api-key` is not allowed, the gateway could return a 400 Bad Request

### Steps to Reproduce (for bugs)

1. Create an API with a plan secured with ApiKey
2. Subscribe to the plan and retrieve the key
3. Hit the API with the key passed in the query params

### Context

The keys in the query params are always readable but the http headers are encrypted when sent over SSL.

**Comment by aelamrani** [comment]
Hi @Gwalchmei you can already do it by defining an empty configuration:

```
policy:
  api-key:
    param:
```

I keep this issue open as we should do something, at least document it.
