### ISSUE TITLE
[am] [dcr] Manage templating

### ISSUE THREAD

**Issue by lusoalex** [gravitee-io/issues#2454]
Target is to be able to specify a client as a template for the dynamic client registration endpoint.

### Expected Behavior
By specifying a client as a template, we do not need to specify all the metadata (as they will be copied from the template).
The metadata from the request will override the template original values.
Sensible content from the template such as client_secret should be erased before the copy.
Non DCR content such as email and forms are expected to be copied from the template.

### Possible Solution
The template will be based on the software_id metadata.
Only on the client registration (creation), not for update/patch.

**Comment by tcompiegne** [comment]
Some UI/UX tweaks will be done for the 2.8.1 AM version
