### ISSUE TITLE
[policy] [mock] Form post params in body

### ISSUE THREAD

**Issue by GL-Gravitee2** [gravitee-io/issues#2457]
Hi ,

Can you please suggest , which policy to use and how to handle  payload data which of below format 

'NotificationId=CCCDHHEHKLFCLIGGFVZ6AGHSIFDITD&ProcessorId=282-01&TransactionType=MPS&MerchantId=abdc'

am looking to extract each of these name-value fields.

**Comment by GL-Gravitee2** [comment]
This is the API am trying to build,

the incoming body will be of the for  'NotificationId=CCCDHHEHKLFCLIGGFVZ6AGHSIFDITD',  i have to pass this as query param in outbound call,

i tried  https://xxxx?{#request} using dynamic routing , and dnt see query parameter coming through.

**Comment by GL-Gravitee2** [comment]
This is the api i have tried so far, with no luck.

{
  "name": "awsMarketPlacec",
  "version": "v1",
  "description": "curiosity_lite",
  "visibility": "PUBLIC",
  "paths": {
    "/": [
      {
        "methods": [
          "CONNECT",
          "DELETE",
          "GET",
          "HEAD",
          "OPTIONS",
          "PATCH",
          "POST",
          "PUT",
          "TRACE"
        ],
        "policy-assign-attributes": {
          "scope": "REQUEST",
          "attributes": [
            {
              "name": "inRequest",
              "value": "{#request}"
            }
          ],
          "headers": []
        },
        "description": "Description of the Assign attributes Policy",
        "enabled": true
      },
      {
        "methods": [
          "CONNECT",
          "DELETE",
          "GET",
          "HEAD",
          "OPTIONS",
          "PATCH",
          "POST",
          "PUT",
          "TRACE"
        ],
        "mock": {
          "headers": [
            {
              "name": "Location",
              "value": "https://xxxxxxxxxxxxxxxxxx?{#context.attributes['inRequest']}"
            }
          ],
          "status": "302"
        },
        "description": "Description of the Mock Gravitee Policy",
        "enabled": true
      }
    ]
  },
  "resources": [],
  "members": [
    {
      "source": "memory",
      "sourceId": "admin",
      "role": "PRIMARY_OWNER"
    }
  ],
  "pages": [],
  "plans": [
    {
      "id": "67ca0437-f950-4562-8a04-37f9500562b7",
      "name": "test",
      "description": "test",
      "validation": "AUTO",
      "security": "KEY_LESS",
      "type": "API",
      "status": "PUBLISHED",
      "apis": [
        "93da28f7-e307-49c9-9a28-f7e30719c9bd"
      ],
      "order": 0,
      "characteristics": [],
      "created_at": 1562866201216,
      "updated_at": 1562866201216,
      "paths": {
        "/": []
      },
      "comment_required": false
    }
  ],
  "path_mappings": [],
  "proxy": {
    "context_path": "/awsmarketplace",
    "strip_context_path": false,
    "groups": [
      {
        "name": "default-group",
        "endpoints": [
          {
            "name": "default",
            "target": "https://api.gravitee.io/echo",
            "weight": 1,
            "backup": false,
            "type": "HTTP",
            "inherit": true
          }
        ],
        "load_balancing": {
          "type": "ROUND_ROBIN"
        },
        "http": {
          "connectTimeout": 5000,
          "idleTimeout": 60000,
          "keepAlive": true,
          "readTimeout": 10000,
          "pipelining": false,
          "maxConcurrentConnections": 100,
          "useCompression": true,
          "followRedirects": false
        }
      }
    ]
  },
  "response_templates": {}
}

**Comment by brasseld** [comment]
There is no way to convert a body payload to a query param because the api gateway is doing point to point communication and the request is already sent to the backend before streaming content through the gateway.
