### ISSUE TITLE
Shows Deprecated methods

### ISSUE THREAD

**Issue by tkmramesh** [gravitee-io/issues#2480]
"Methods .handler() shows deprecated."
I downloaded HttpCallout Proxy code from Git and trying to add some business logic in the response handler.

httpClient.requestAbs(convert(configuration.getMethod()), url).handler(new Handler<HttpClientResponse>() {

"The method handler(Handler<HttpClientResponse>) in the type HttpClientRequest is not applicable for the arguments (new Handler<HttpClientResponse>(){})"

Which Vertx version i have to use?

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Installed Gravitee version - Version: 1.24.1
* Google Chrome
* Ubuntu16, Docker Instance

**Comment by brasseld** [comment]
Hi @tkmramesh 

Gravitee.io is based on Vert.x 3.7.x

You can't do anything for the moment, just wait for Vert.x 4.x...

**Comment by tkmramesh** [comment]
Thank you Brassely.

--
Regards,
Ramesh
