### ISSUE TITLE
[gateway] HTTP 500 when call API with wrong context path

### ISSUE THREAD

**Issue by MariaPushkin** [gravitee-io/issues#2504]
Our API has base path and only 2 context paths, but when we call API with any wrong subpath right after base path like _/basepath/wrongpath/correctpath1_ we get the following error:

`{"message":"io.gravitee.gateway.policy.PolicyException: java.lang.reflect.InvocationTargetException","http_status_code":500}`

Calls to the paths like this - _/basepath/correctpath1/wrongpath_ works okay and return HTTP 404, possibly because it firstly matches the _/basepath/correctpath1_. So, if I add root path(/) into api-definition this exceprion disappear, but this API has no logic for the root url, so I dont see any reason it should be there.

### Expected Behavior
Any more meaningful description in the returned response for this case.

### Current Behavior
_io.gravitee.gateway.policy.PolicyException: java.lang.reflect.InvocationTargetException_ when call API with wrong path.

### Steps to Reproduce (for bugs)
1. Create an API
2. Remove root path from api-definition if present
3. Add any amount of context paths
4. Deploy and start API
5. Make call with wrong subpath the way it explained before

### Your Environment

* Version used: 1.27.0

**Comment by brasseld** [comment]
So as far as I understand, not having a root path ( / ) ends always with an Exception, right?

**Comment by MariaPushkin** [comment]
> So as far as I understand, not having a root path ( / ) ends always with an Exception, right?

Yes, we think that gateway understands which API was called because of correct base path, but then it cannot find proper continuation in io.gravitee.gateway.handlers.api.path.impl.AbstractPathResolver#resolve method and fail with NPE in io.gravitee.gateway.handlers.api.policy.api.ApiPolicyChainResolver.java:48

**Comment by brasseld** [comment]
Can you share an export of such API please?

I will have a look.

Thanks

**Comment by MariaPushkin** [comment]
> Can you share an export of such API please?
> 
> I will have a look.
> 
> Thanks

Of course, here it is
```json
{
  "name": "PathTest",
  "version": "1.0.0",
  "description": "path tests",
  "visibility": "PRIVATE",
  "tags": [
    "dev62",
    "rest",
    "gw-dev"
  ],
  "paths": {
    "/sendText": [],
    "/getUpdates": []
  },
  "resources": [],
  "groups": [
    "Admin Group"
  ],
  "members": [
    {
      "source": "memory",
      "sourceId": "admin",
      "role": "PRIMARY_OWNER"
    }
  ],
  "pages": [],
  "plans": [
    {
      "id": "61dc54f8-59be-4f41-9c54-f859be8f41f5",
      "name": "Test 2",
      "description": "test",
      "validation": "AUTO",
      "security": "KEY_LESS",
      "securityDefinition": "{}",
      "type": "API",
      "status": "PUBLISHED",
      "apis": [
        "754f0867-41c2-4c65-8f08-6741c22c6569"
      ],
      "order": 2,
      "characteristics": [],
      "tags": [],
      "created_at": 1563970573910,
      "updated_at": 1564396753250,
      "published_at": 1563970578194,
      "paths": {
        "/sendText": []
      },
      "excluded_groups": [],
      "comment_required": false
    },
    {
      "id": "2c025521-149b-4f24-8255-21149b2f2480",
      "name": "Test plan",
      "description": "test",
      "validation": "AUTO",
      "security": "API_KEY",
      "type": "API",
      "status": "PUBLISHED",
      "apis": [
        "754f0867-41c2-4c65-8f08-6741c22c6569"
      ],
      "order": 1,
      "characteristics": [],
      "tags": [],
      "created_at": 1563969851935,
      "updated_at": 1564396753267,
      "published_at": 1563969880622,
      "paths": {
        "/": []
      },
      "excluded_groups": [],
      "comment_required": false
    }
  ],
  "path_mappings": [],
  "proxy": {
    "context_path": "/pathtest/v1",
    "strip_context_path": false,
    "groups": [
      {
        "name": "default-group",
        "endpoints": [
          {
            "name": "default",
            "target": "http://test-route.ru/pathtest/v1",
            "weight": 1,
            "backup": false,
            "type": "HTTP",
            "inherit": true
          }
        ],
        "load_balancing": {
          "type": "ROUND_ROBIN"
        },
        "http": {
          "connectTimeout": 5000,
          "idleTimeout": 60000,
          "keepAlive": true,
          "readTimeout": 10000,
          "pipelining": false,
          "maxConcurrentConnections": 100,
          "useCompression": true,
          "followRedirects": false
        }
      }
    ]
  },
  "response_templates": {}
}
```
