### ISSUE TITLE
[gateway] response body truncated

### ISSUE THREAD

**Issue by vanackgpro** [gravitee-io/issues#2506]
in some cases, gateways' response is truncated when I loop through an API.

On my example, the returned json suddenly stops with the following text
4 buttons "," longWebL

In order to isolate the component, I mass-tested the live microservice, and then the gateway
My problem seems to come from a break in the return of the json only when I use the gateway

I put the log of the gateway in debug mode and I find this element in the log "..2000 .."

| 00004a70 | 70 72 6f 64 75 63 74 4c 61 62 65 6c 22 3a 22 47 | productLabel ":" G |
| 00004a80 | 41 52 59 20 6d 61 6e 74 65 61 75 20 70 61 72 64 | ARY coat pard |
| 00004a90 | 65 73 73 75 73 20 6b 72 6f 20 34 20 62 6f 75 74 | essus kro 4 tips |
| 00004aa0 | 6f 6e 73 22 2c 22 6c 6f 6e 67 57 65 62 4c 0d 0a | ons "," longWebL .. |
| 00004ab0 | 32 30 30 30 0d 0a 61 62 65 6c 50 72 6f 64 75 63 | 2000..abelProduc |
| 00004ac0 | 74 22 3a 22 6d 61 6e 74 65 61 75 20 70 61 72 64 | t ":" coat pard |
| 00004ad0 | 65 73 73 75 73 20 c3 a0 20 63 61 72 72 65 61 75 | essus .. tile |

this break appears many times but randomly, it cuts the answer.
the weight of the json in return is 630Ko

this corresponds to 1 call on about 200 on my API
and this is the only API that is massed called 
with a json weight greater than 500 kb
Call of type GET, random problem whatever the parameter passed.
it returns the header part, I have a http code 200
but the body part is truncated
The call stops as if everything was OK (code http 200 in severity)
the gateway calls the microservice directly (after application of the LB)
there is no intermediate reverse proxy
on the consumer side, a new connection is established for each call

### Steps to Reproduce (for bugs)
In production 
1. loop call for 200-300 times the same API with changing parameters (called in java httpclient)
In staging
1. loop call for 200-300 times the same API with changing parameters (called in curl on the same url same parameters on 1 shell)
2. launch several session of the shell at same time

### Context
default Gateway configuration

### Your Environment
* Version used: 1.27.1
* Operating System and version: debian 9 - java 8

**Comment by vanackgpro** [comment]
In 1.29.5, 
Issue resolved by increasing the "Maximum concurrent connection" setting and disabling "Enable persistence".

**Comment by vanackgpro** [comment]
... and disabling "Enable keep-alive"

**Comment by brasseld** [comment]
The issue has already been fixed in a later version of gravitee (1.29.x) without having to change maximum concurrent connection.
