### ISSUE TITLE
502 Bad Gateway when trying to reach API endpoints in other networks

### ISSUE THREAD

**Issue by graviteeLover3000** [gravitee-io/issues#2515]
### Expected Behavior

Gravitee Gateway should pass my request to the API endpoints that are outside of my local network without responding with `502 Bad Gateway` error.

### Current Behavior

At first, I couldn't connect to the API endpoint through Gravitee Gateway (`502 Bad Gateway` response), but when I tried to hit the API endpoint using `curl` from the Gravitee gateway `Docker` container it got through and I received the correct response. Also after connecting to that API endpoint with `curl`, I could connect and receive the correct response when using Postman and hitting the Gravitee Gateway context to that API. It looks like Gravitee Gateway has started passing the connection to that API endpoint. It happens with all of the endpoints outside my local network I tried, the ones in my local network work fine all the time. 

### Possible Solution

I have no clue.
### Steps to Reproduce (for bugs)

1. Create an API
2. Create a keyless plan in that API
3. Started, published and deployed API
4. Connect to the API endpoint through correct API's context set on Gravitee Gateway (using Postman)
5. Receive a 502 Bad Gateway response

### Context

I use docker containers to run all of the Gravitee components. I tried to disable the  windows firewall, manually assign a DNS server in docker settings. 

### Your Environment

* Version used: 1.28.0
* Browser Name and version: Mozilla/Chrome
* Operating System and version: Windows 10 Pro
* Postman
* Docker 18.09.2

**Comment by brasseld** [comment]
You're probably trying to access an https endpoint.
if so, you must have to enable SSL Trust from endpoint configuration (at endpoint level or group level).

**Comment by graviteeLover3000** [comment]
> 
> 
> You're probably trying to access an https endpoint.
> if so, you must have to enable SSL Trust from endpoint configuration (at endpoint level or group level).

Tha'ts not it. I tried accessing http endpoints and the result is the same.

**Comment by brasseld** [comment]
Did you check API logs to see what's going wrong ?

**Comment by graviteeLover3000** [comment]
![obraz](https://user-images.githubusercontent.com/53569905/62311930-2d01ec80-b48d-11e9-8f10-1f8104aeb766.png)
I don't see anything interesting in there. Only this line when deploying API.

**Comment by brasseld** [comment]
I mean... in the UI.

Select your API > Analytics > Logs

**Comment by GL-Gravitee2** [comment]
Hi ,

Any headway here ?  I have same issue .

Version | 1.27.1 (build: 544)
On endpoints Trust is enabled.

Backend API works fine , while called from postman/sopaui etc. 

Analytics call shows :
![image](https://user-images.githubusercontent.com/50599427/62383494-87469000-b515-11e9-83fe-525d74cf5f89.png)

**Comment by aelamrani** [comment]
The error seems to be answered by the backend, maybe you can have a look to the logs on it?

**Comment by GL-Gravitee2** [comment]
> The error seems to be answered by the backend, maybe you can have a look to the logs on it?

Checked at the backend. We dnt see any incoming calls.

**Comment by graviteeLover3000** [comment]
> > The error seems to be answered by the backend, maybe you can have a look to the logs on it?
> 
> Checked at the backend. We dnt see any incoming calls.

It seems like a Gravitee has problem with resolving domain names, because if I try to use IP address, instead of name of domain, everything works fine.

**Comment by graviteeLover3000** [comment]
![gravitee 502 issue log](https://user-images.githubusercontent.com/53569905/62522301-b15bc300-b831-11e9-9617-1aefdf71118d.png)

That's what the problem seems to be that it can't resolve the names of endpoints. Any possible solutions to this?

**Comment by NicolasGeraud** [comment]
hi, can you try the endpoint from inside your container ?

**Comment by graviteeLover3000** [comment]
It gets through like it should without any problems. 

![obraz](https://user-images.githubusercontent.com/53569905/62705326-77cfb700-b9ed-11e9-9beb-904184102337.png)

**Comment by PaloSanto5482** [comment]
Hi,
I have the same problem with Gravitee. It seems like it doesn't resolve DNS names. Probably Gravitee checks only the first DNS server and if there is more than one the connection cannot be established. If I provide a DNS resolver at `C:\Windows\System32\drivers\etc\hosts` everything works fine.

**Comment by PaloSanto5482** [comment]
@brasseld @NicolasGeraud any idea?

**Comment by brasseld** [comment]
Did you try to disable vertx dns resolver and use the Java one instead?

**Comment by PaloSanto5482** [comment]
It works! Thank you :)

**Comment by graviteeLover3000** [comment]
It works very nice. Thank you very much for help. Best regards
