### ISSUE TITLE
[question] The api context path [/] already exists. 

### ISSUE THREAD

**Issue by barrycheng** [gravitee-io/issues#2517]
import API definition or your Swagger descriptor file

Import from link
http://192.168.2.46:8098/v2/api-docs

Swagger / OpenAPI

Swagger import configurations:
Create documentation
Create the path-mapping for analytics
Create policies on paths

I hava already import a spring boot service. Need I to change some swagger config?

**Comment by brasseld** [comment]
we are calculating the context-path of the API based on the swagger definition.
it seems that you've imported two swagger which are based on the same path.

**Comment by barrycheng** [comment]
![123](https://user-images.githubusercontent.com/8085838/62351031-07c9b880-b537-11e9-821f-62d51372dbf6.png)

Is it the basePath properties?

**Comment by brasseld** [comment]
yes

**Comment by barrycheng** [comment]
@brasseld Ok, Thx !

**Comment by barrycheng** [comment]
@brasseld What's the relationship between the gateway content path and the service servlet context-path and the swagger base path ?
It the gateway content only for routing identification ?The real request will discard this ?

**Comment by brasseld** [comment]
there is no "relation" between GW context-path and service context-path.
what we are doing is just to extract the path from the swagger to create the API, but as you are exposing service on the / path you're encountering the "The api context path [/] already exists".

In the next version of gravitee, we have added support for virtual-host, so you may be able to have the same context-path for different API by using a Host header.

**Comment by barrycheng** [comment]
@brasseld 
I take your words in this way.
The GW content-path, like '/A' only routing for the service name 'Service-A' on the Eureka ( I used).
It's right ?

**Comment by brasseld** [comment]
exact!

**Comment by barrycheng** [comment]
I hava i service (used Eureka), the real url is http://192.168.2.46:9000/mbc/system/login.
The swagger base path is /mbc. When import from link, the gateway context path get /mbc.
But when i use gateway to route.
http://192.168.2.40:8082/mbc/system/login get 404.
http://192.168.2.40:8082/mbc/mbc/system/login get
{
    "message": "io.gravitee.gateway.policy.PolicyException: java.lang.reflect.InvocationTargetException",
    "http_status_code": 500
}
What's correct access url?

**Comment by brasseld** [comment]
Hi @barrycheng 

I don't know what is the URL you get from Eureka.
If Eureka is providing only a host, port, so yes, you will have to call `http://192.168.2.40:8082/mbc/mbc/system/login` 

For the exception, it would be easier for us to get the complete stack trace for a better understanding.

**Comment by frederic-gendebien** [comment]
Same question, same problem, but I cannot modify the swagger.
