### ISSUE TITLE
Deploy Management UI in OpenShift

### ISSUE THREAD

**Issue by CDPrete** [gravitee-io/issues#2520]
Hi all!
After a long fighting, I've been able to put somehow up the API, Gateway Elasticsearch and Mongo in OpenShift.
What I'm still missing is the UI because it complains with issues like "cannot bind 0.0.0.0 on 80/443"  or so.

Do you have any idea how can fix it and make the UI accessible outside?

**Comment by brasseld** [comment]
Hi, 

This is due to security restriction for nginx not using ports like 80 and 443 
You can override this by setting your own HTTP_PORT or HTTPS_PORT env var.

**Comment by CDPrete** [comment]
How is that supposed to work since in the nginx config there is hardcoded the value 80?

**Comment by brasseld** [comment]
It is handle by the ui docker image itself.

**Comment by CDPrete** [comment]
OK, I'll try setting those env variables and I let you know.

**Comment by brasseld** [comment]
We are using conf.d for ui image.
See template: https://github.com/gravitee-io/gravitee-docker/blob/master/images/management-ui/config/templates/default.conf.tmpl#L2

**Comment by CDPrete** [comment]
That works like a charm, but I've other issues with the readiness and liveness. Should I open another issue?

**Comment by brasseld** [comment]
No, please explain here

**Comment by CDPrete** [comment]
I'm using the endpoint `/_node/health` for checking such values, but the pod is not able to reach them, in fact it returns 404

**Comment by brasseld** [comment]
For which container ? The ui ?
There isn't such endpoint for the UI, only for gateway and mgmt-api

**Comment by CDPrete** [comment]
No, for the gateway and the API. For the UI I'm just using the `/` as endpoint

**Comment by NicolasGeraud** [comment]
hi, you know that `/_node/health` is exposed by default on another port?

**Comment by CDPrete** [comment]
Ehm no :)
Which one is the default port?

**Comment by aelamrani** [comment]
18082 for the gateway and 18083 for the mgmt by default

**Comment by toastbrotch** [comment]
i'm trying to do the same, is there any information/documentation/deploymentconfig ? could not find up-to-date information for openshift 3.11. thanx!
