### ISSUE TITLE
All gravitee in the same port

### ISSUE THREAD

**Issue by ouah12** [gravitee-io/issues#2521]
i want to start gravitee and gravitee management api in the same port, to deploy juste one application in one port, because one more port means one more bill
any held please ?

i am not using docker, ils normal deployment in unix vm.

**Comment by ouah12** [comment]
thanks for advance

**Comment by NicolasGeraud** [comment]
why not using a reverse proxy ?

**Comment by ouah12** [comment]
the infra is delegated to another compagny, and creating a new ports to depoy gravitee is not for free :)  
for this reason i want to combine gravitee gateway and management in the same application to deploy it in just one port.
 using a reverse proxy is not free eather

**Comment by NicolasGeraud** [comment]
So you have to choose the cheaper one because management API, management web UI and gateway are 3 different components.
