### ISSUE TITLE
[gateway] Set-Cookie is not applied correctly

### ISSUE THREAD

**Issue by cdprete** [gravitee-io/issues#2522]
Hi!
Seems like that the gateway (1.28.0) somehow ignores the `Set-Cookie` header additional values (expiration and age).

Example:
Set-Cookie: Authorization=`<auth-token>`; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT

In particular, the header is passed as response header in a 302 response, so it should delete the cookie while following the redirect, but the next call has still the authorization token as cookie.

Expectation: the cookie is deleted since it's expired.

**Comment by CDPrete** [comment]
After further investigation, seems like that if no `path` is present in the cookie, the gateway is adding as path the target endpoint path, causing the `Set-Cookie` to set a second cookie since the first one was explicitly set using `/` as path.

Is this expected?

**Comment by brasseld** [comment]
Hi @CDPrete 

Sorry for the delay.

I don't understand this issue. Seems that you're talking about the API Gateway (1.28.0). By default, the gateway does not change any HTTP headers so why are you assuming that the cookie should be deleted because of its expiration value?

**Comment by CDPrete** [comment]
Hi @brasseld
If the gateway should not delete the cookie, then it should send the cookie untouched to the browser when responding.
Instead, for some reason, it's adding the target endpoint as path.
