### ISSUE TITLE
[gateway] cookie web sessions

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#2523]
We should be able to store the web sessions into the repository to enable clustered sessions without configure sticky sessions for your load balancer.

**Comment by lazki** [comment]
Note: You can't use JSESSIONID to configure StickySessions with Apache httpd.

You must use de ROUTEID and Set-Cookie Way.

Reference: http://docs.motechproject.org/en/latest/deployment/sticky_session_apache.html
