### ISSUE TITLE
Multiple Instances of Gravitee

### ISSUE THREAD

**Issue by GL-Gravitee2** [gravitee-io/issues#2529]
Hi  @brasseld

Am planning to run to two instances of gravitee with F5 as LB. From gravitee point of view do i have to install and run all three components   API Gateway, Mgmt and portal?

Is it possible to use one instance of the portal to manage two API gateways?

As portal constants.json has only one entry 

{
  "baseURL": "gravitee_management_api_url"
}

**Comment by brasseld** [comment]
If by two instances you mean two gateway instances, you can have a single portal and single management api for the number of gateway you would need. So you can have one portal (and mgmt-api) for X instances of api gateway.

It's up to you !

**Comment by GL-Gravitee2** [comment]
Thank you for the details . Closing this issue
