### ISSUE TITLE
[gateway] Generate token - password credentials - CORS issue

### ISSUE THREAD

**Issue by rotparmna** [gravitee-io/issues#2535]
Hi guys, I am using Gravitee AM 2.2 and I am having CORS issues when making a token creation request (http://localhost:8092/webtransaccional.accion.com.co/oauth/token?grant_type=password&scope=openid&username=900236747&password=48282f1768b8b2a1339680d5e95478b4), from a client that is on a machine other than Gravitee AM.

Please your help, thanks.

**Comment by brasseld** [comment]
By a machine, you mean a browser ?

If so, I'm pretty sure that using the resource_owner_password_credentials flow from a browser app is recommended (for security reasons).

**Comment by rotparmna** [comment]
Thanks @brasseld  by your answer. 

We send a POST request from the browser as you indicate, but we get CORS. What additional information do you need?
