### ISSUE TITLE
[gateway] 502 Bad Gateway while calling backend

### ISSUE THREAD

**Issue by GL-Gravitee2** [gravitee-io/issues#2541]
Hi 

Continuing #2515 here as the previous issue is closed.

In my case issue is still not resolved even after addressing DNS as stated in #2515.

I get a partial response from the backend  whicle called through gravitee with 502 ( from other clients API works fine )

![image](https://user-images.githubusercontent.com/50599427/63462579-dd299c00-c420-11e9-8459-064e5d78ecd2.png)

I have adjusted HTTP timeout, readtimeout. Response body is not big its 1.6kb. Is any other parameters to be adjusted?

**Comment by aelamrani** [comment]
Hi @GL-Gravitee2 

Which version of g.io? Is others calls are handled correctly?

**Comment by GL-Gravitee2** [comment]
Hi @aelamrani , @brasseld 

Its 
Version | 1.27.1 (build: 544) revision#a11e087b0863201e127ae5468545a28b4fbe4f90.

Yes , other APIs are working fine. The issue is specifically with APIs of particular backend.

**Comment by aelamrani** [comment]
Ok so i think you can have a look to this parameter: https://github.com/gravitee-io/gravitee-gateway/blob/master/gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml#L22

**Comment by GL-Gravitee2** [comment]
> Ok so i think you can have a look to this parameter: https://github.com/gravitee-io/gravitee-gateway/blob/master/gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml#L22

Request timeout and read time out is already adjusted. Do i need any updates on 
 #  maxHeaderSize: 8192
#  maxChunkSize: 8192

as these are the only HTTP related attributes in gravitee.yml

**Comment by aelamrani** [comment]
I'd say yes, to `maxChunkSize`

**Comment by GL-Gravitee2** [comment]
> I'd say yes, to `maxChunkSize`

Chagned maxChunkSize: 8192  to maxChunkSize: 16000 , still resulting in 502 with partial response,

**Comment by brasseld** [comment]
Are you able to provide a reproducer using an api sample in java or in js?

**Comment by GL-Gravitee2** [comment]
@brasseld ,  I need to work on some access management to get the client. I will get that done by tomorrow. Thank you for checking on this.

**Comment by brasseld** [comment]
Hello @GL-Gravitee2 

What's the status of this issue?

**Comment by GL-Gravitee2** [comment]
Hello @brasseld  ,

The issue is still there. every time truncated response with 502.

**Comment by brasseld** [comment]
What about a reproducer ?

**Comment by GL-Gravitee2** [comment]
> What about a reproducer ?

Am not able to create a viable reproducer due to security creds. For now i will close the issue, reopen it ,once i have the producer ready

**Comment by snehalshinde25** [comment]
Does this issue resolved? I am facing similar issue
