### ISSUE TITLE
[policy] [callout-http] Context variable not accessible 

### ISSUE THREAD

**Issue by GL-Gravitee2** [gravitee-io/issues#2542]
Hi , 

Looking for assistance on how to access context variable set at HTTP call out.

Here is api structure :
On incoming call,  Input headers are extracted  and  used in HTTP call out  [ this is working ]op

The response header from HTTP call out is extracted into a variable 

X-token-Variable   :  {#jsonPath(#calloutResponse.content, '$.headers.X-Access-Token')}

Next step , i have a Transform header policy to add a header :   [ Not working ]

**### x-access-token  :  {#ctx.getVariable('X-token-Variable')}    -  Is this syntax correct?**
**

> is Context - Variable set in HTTP Callout will be available at next policy @ HTTP Header Transform?

**

{
  "name": "DEV_CIA_PROXY",
  "version": "v1",
  "description": "curiosity_lite incident management adapter",
  "visibility": "PRIVATE",
  "paths": {
    "/": [
      {
        "methods": [
          "CONNECT",
          "DELETE",
          "GET",
          "HEAD",
          "OPTIONS",
          "PATCH",
          "POST",
          "PUT",
          "TRACE"
        ],
        "policy-http-callout": {
          "scope": "REQUEST",
          "method": "POST",
          "exitOnError": true,
          "errorCondition": "{#calloutResponse.status != 200}",
          "errorStatusCode": "401",
          "headers": [
            {
              "name": "User-Id",
              "value": "{#request.headers['User-Id']}"
            },
            {
              "name": "Password",
              "value": "{#request.headers['Password']}"
            }
          ],
          "variables": [
            {
              "value": "{#jsonPath(#calloutResponse.content, '$.headers.X-Access-Token')}",
              "name": "X-token-Variable"
            }
          ],
          "url": "https://xxxxxx/rest/useradministration/login",
          "body": "{\n    \"userId\": \"tetsr\",\n    \"password\": \"St\"\n}",
          "errorContent": "unauthorized"
        },
        "description": "Description of the CalloutHttp Gravitee Policy",
        "enabled": true
      },
      {
        "methods": [
          "CONNECT",
          "DELETE",
          "GET",
          "HEAD",
          "OPTIONS",
          "PATCH",
          "POST",
          "PUT",
          "TRACE"
        ],
        "transform-headers": {
          "scope": "REQUEST",
          "removeHeaders": [],
          "addHeaders": [
            {
              "name": "x-access-token",
              "value": "{#ctx.getVariable('X-token-Variable')}"
            }
          ],
          "method": "GET",
          "exitOnError": false,
          "errorCondition": "{#calloutResponse.status >= 400 and #calloutResponse.status <= 599}",
          "errorStatusCode": "500",
          "headers": [],
          "variables": []
        },
        "description": "Description of the Transform Headers Gravitee Policy",
        "enabled": true
      }
    ]
  },
  "resources": [],
  "members": [
    {
      "source": "memory",
      "sourceId": "admin",
      "role": "PRIMARY_OWNER"
    }
  ],
  "pages": [],
  "plans": [
    {
      "id": "09f3ed10-8311-4e4a-b3ed-1083118e4a19",
      "name": "xx",
      "description": "API key plan for New york",
      "validation": "AUTO",
      "security": "API_KEY",
      "type": "API",
      "status": "PUBLISHED",
      "apis": [
        "772174fb-7444-4c63-a174-fb74446c63db"
      ],
      "order": 0,
      "characteristics": [],
      "created_at": 1566509969170,
      "updated_at": 1566509969170,
      "paths": {
        "/": []
      },
      "comment_required": false
    }
  ],
  "path_mappings": [],
  "proxy": {
    "context_path": "/cia-srvc",
    "strip_context_path": false,
    "logging": {
      "mode": "CLIENT_PROXY",
      "condition": "#request.method == 'POST'"
    },
    "groups": [
      {
        "name": "default-group",
        "endpoints": [
          {
            "name": "default",
            "target": "http://1xxx/cia-srvc",
            "weight": 1,
            "backup": false,
            "type": "HTTP",
            "inherit": true
          }
        ],
        "load_balancing": {
          "type": "ROUND_ROBIN"
        },
        "http": {
          "connectTimeout": 5000,
          "idleTimeout": 60000,
          "keepAlive": true,
          "readTimeout": 10000,
          "pipelining": false,
          "maxConcurrentConnections": 100,
          "useCompression": true,
          "followRedirects": false
        }
      }
    ],
    "cors": {
      "enabled": true,
      "allowCredentials": false,
      "allowOrigin": [
        "*"
      ],
      "allowHeaders": [
        "content-type",
        "api-key",
        "user-id",
        "password"
      ],
      "allowMethods": [
        "POST",
        "GET",
        "PUT"
      ],
      "exposeHeaders": [],
      "maxAge": -1
    }
  },
  "response_templates": {}
}

**Comment by aelamrani** [comment]
The syntax should be something like: `{#context.attributes['X-token-Variable']}`

**Comment by GL-Gravitee2** [comment]
> The syntax should be something like: `{#context.attributes['X-token-Variable']}`

No Luck Still .

**X-token-Variable : {#jsonPath(#calloutResponse.content, '$.headers.X-Access-Token')}  - Any inputs here ?**

**Comment by GL-Gravitee2** [comment]
There header value being assigned is of length  1150 bytes . Is this could be causing any issues? gravitee.yml   has  maxHeaderSize: 8192 .

I also tried  assigning the value of the header with  http callout context, still not working

 x-access-token  = {#jsonPath(#calloutResponse.content, '$.headers.X-Access-Token')}

**Comment by brasseld** [comment]
Hi @GL-Gravitee2 

According to the jsonPath expression, you're getting X-Access-Token header from the callout response payload? Is that correct ?

IMHO, you're looking to extract this header value from callout response headers so the correct syntax must be `{#calloutResponse.headers['X-Access-Token'][0]}`

**Comment by GL-Gravitee2** [comment]
Worked!
