### ISSUE TITLE
[management] New user registration cannot receive mail

### ISSUE THREAD

**Issue by jinshuchu** [gravitee-io/issues#2543]
hi，How to configure email using docker-compose deployment

**Comment by jinshuchu** [comment]
![image](https://user-images.githubusercontent.com/11752171/63577360-cae66400-c5c0-11e9-80ee-f4a2fde1facd.png)

**Comment by jinshuchu** [comment]
![image](https://user-images.githubusercontent.com/11752171/63586396-cc6d5780-c5d3-11e9-9605-deb066eab828.png)
lia
连接超时

**Comment by brasseld** [comment]
Hi @jinshuchu 

I suppose that your container does not have access to these smtp.
Seems to be more relative to a network issue that a Gravitee one.
