### ISSUE TITLE
[gateway][oidc] retrieve groups and roles on userinfo endpoint

### ISSUE THREAD

**Issue by rhuanbarreto** [gravitee-io/issues#2544]
# Expected Behavior

I'm connecting Gravitee AM to my LDAP and I want to retrieve user Groups and Roles on the oidc/userinfo call. I can't find any documentation on it. How can I do it?

### Your Environment
* Version used: `2.8.3`
* Operating System and version: Docker

**Comment by 0xC4N1** [comment]
The [documentation](https://docs.gravitee.io/am/2.x/am_quickstart_profile_information.html#custom_claims) gives some info about custom claims in the `/oidc/userinfo` endpoint but I couldn't figure out how to connect it with roles either. However you can [add a `group=group-name` mapping for your role to your identity provider](https://docs.gravitee.io/am/2.x/am_userguide_identity_provider_mapping.html#role_mappers_and_dynamic_oauth2_scopes) and [add a custom claim to the ID token](https://docs.gravitee.io/am/2.x/am_quickstart_tokens_custom_claims.html) with a `claim value` of `{#context.attributes['user'].roles}` in each clients OAuth 2.0 settings.

**Comment by rhuanbarreto** [comment]
Thanks for the info! I will try some things here and get back next week.
Maybe it could be good if someone from Gravitee Source make like a video tutorial to help newcomers like me. Looks like all the functionality is there developed but not with a step by step procedure. I would love to help into improving the documentation if I could figure out 100% about this configuration process.

**Comment by brasseld** [comment]
Hi @rhuanbarreto 

You can create pull requests to improve documentation once you find your solution to put groups and roles into userinfo response payload 

Repository: https://github.com/gravitee-io/gravitee-docs

**Comment by rhuanbarreto** [comment]
Thanks @brasseld! Do you have any tips for it? I'm on vacations this week, so I will only touch on this next week.

**Comment by brasseld** [comment]
Enjoy your vacations for now and let's discuss this when you'll be back!

**Comment by rhuanbarreto** [comment]
@brasseld I'm back! How can we discuss?

**Comment by brasseld** [comment]
https://gitter.im/gravitee-io/gravitee-io

**Comment by tcompiegne** [comment]
Hi @rhuanbarreto ,

Currently you can't retrieve both user roles and groups from the UserInfo Endpoint. 

We only display the standard OpenID Connect claims https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims.

But we should add those information, flag this issue to "new feature".

**Comment by rhuanbarreto** [comment]
Thanks for the answer @tcompiegne. This is critical for me once my client applications need this to implement roles and groups access control and information scoping. In one case a Rails API that will use this information to set the application policies using Pundit gem. Or even React frontends that will show or hide UI based on this info.

For now I can see that Keycloak has this and will move on with it. Unfortunately I can't help too much on programming as I don't have too much Java experience, but if you implement I would love to work on the documentation. Gravitee AM is very lightweight and can empower lot's of applications not only the API management.
