### ISSUE TITLE
[management] Permission on SETTINGS does not give access to all views the permission affects

### ISSUE THREAD

**Issue by manuelottlik** [gravitee-io/issues#2556]
If a user has the READ permission on SETTINGS in the scope PORTAL he is allowed to see setting values. The views that have settings that are affected by this permission are only accessable when you have the READ permission for the resource managed in this view. On the other hand, these settings are also visible when the user has READ permissions on the resource handled in this view but no READ permissions on SETTINGS. This affects settings that are **not** located in the "settings" menu item.

### Expected Behavior
Settings that are distributed over several views should always be visible when the READ permission for SETTINGS is set and not be visible when the READ permission for SETTINGS is not set (scope: PORTAL).

### Current Behavior
Settings in other views depending on the SETTINGS permission are only accessible with additional permissions and not hidden when the SETTINGS permission is not granted. 

### Possible Solution
Looks like the criteria to open the view is not based on its single view-components but bound to a single permission. Also, there does not seem to be an extra authorization to display components inside a view.

### Steps to Reproduce (for bugs)
please refer to [this video](https://github.com/gravitee-io/issues/files/3551567/Bildschirmvideo.aufnehmen.2019-08-28.um.17.08.57.mov.zip)

### Context
I was trying to setup roles for our company giving no permissions to the user at all and then starting to add permission by permission to see how they affect the possibilities the user has.

### Your Environment
* Version used: 1.28.1
* Browser Name and version: Chrome 76.0.3809.100
* Operating System and version: macOS 10.14.6

**Comment by manuelottlik** [comment]
Is there any update on this issue? It would improve the UX and make the UI more understandable.

**Comment by aelamrani** [comment]
ATM there is no issue here as the `Client registration provider` role is not a part of the role `Settings`, this is two different roles.

**Comment by brasseld** [comment]
I assume that the issue there is because user should not be able to see the `Configuration` section since he does not have `settings` permissions.

Can you confirm @manuelottlik?
