### ISSUE TITLE
[portal] How to reference API endpoint in API documentation

### ISSUE THREAD

**Issue by handsomeyang** [gravitee-io/issues#2558]
${portal.entrypoint} does not work.

**Comment by brasseld** [comment]
Hi @handsomeyang 

It will be easier to get them starting with Gravitee.io 1.29 since you'll get entrypoints as part of the API payload:

```
  "entrypoints" : [ {
    "target" : "https://api.company.com/echo"
  } ],
```

So, ${api.entrypoints} will allow you to get these entrypoints.

Regards,

**Comment by aelamrani** [comment]
Closed by https://github.com/gravitee-io/issues/issues/1594
