### ISSUE TITLE
[kubernetes] Config file override theme values stored in mongodb

### ISSUE THREAD

**Issue by chicco785** [gravitee-io/issues#2564]
It seems to me that themes parameters in the constants.json have always priority on the db records. is that correct? in which case we should remove them from the helm chart:

https://github.com/gravitee-io/gravitee-kubernetes/blob/master/gravitee/templates/ui-configmap.yaml

### Expected Behavior
If i set an icon in the ui, it is used not only in the current sessions but also in any other session.

### Current Behavior
Configuration in the db seems to be ignored.

**Comment by brasseld** [comment]
Hi @chicco785 

Yes you're correct!
