### ISSUE TITLE
[portal] Applications menu item visible even though no permission is granted

### ISSUE THREAD

**Issue by manuelottlik** [gravitee-io/issues#2565]
The menu item "Applications" is visible in the user menu in the top right corner and the menu inside the management view even though the user does not have the permission to manage applications.

### Expected Behavior
The user does not have any CRUD permission on APPLICATIONS in the scope PORTAL nor MANAGEMENT, so there should be no menu items linking to that view.

### Current Behavior
Even when a user has no CRUD permissions on APPLICATIONS in the scope PORTAL or MANAGEMENT the menu item for applications in shown in the user menu in the top right and the management menu.

### Possible Solution
i have no idea

### Steps to Reproduce (for bugs)
please refer to [this video](https://github.com/gravitee-io/issues/files/3565600/Bildschirmvideo.aufnehmen.2019-09-02.um.12.16.58.mov.zip)

### Context
I was trying to setup roles for our company giving no permissions to the user at all and then starting to add permission by permission to see how they affect the possibilities the user has.

### Your Environment
* Version used: 1.28.1
* Browser Name and version: Chrome 76.0.3809.100
* Operating System and version: macOS 10.14.6

**Comment by manuelottlik** [comment]
Is there any update on this issue? Its not a big deal, just improves the UX.

**Comment by aelamrani** [comment]
Thanks for the report, for the moment a fix/improvment is not planned for this, but a PR would be welcome.
