### ISSUE TITLE
Why did I get the default Bearer Token

### ISSUE THREAD

**Issue by jinshuchu** [gravitee-io/issues#2571]
this
![image](https://user-images.githubusercontent.com/11752171/64259340-7a292080-cf5b-11e9-95ef-f666d05d6cbd.png)

but I want to get it.
![image](https://user-images.githubusercontent.com/11752171/64259468-b197cd00-cf5b-11e9-916b-f174396ecab1.png)
What should I do?
I need your help
thank you!

**Comment by brasseld** [comment]
your access_token is ok, it's just a plain JWT format.

**Comment by jinshuchu** [comment]
How do I choose JWT format and Oauth2 format? What are the differences between the two formats? Just the difference in format? If I want Oauth2 format, how do I configure it? Thank you

**Comment by brasseld** [comment]
You don't have to choose, both format are OK.

**Comment by jinshuchu** [comment]
ok.thank u.
