### ISSUE TITLE
JWT  Groups : API access

### ISSUE THREAD

**Issue by GL-Gravitee2** [gravitee-io/issues#2575]
Hi ,

In JWT tokens , we have
{
  "sub": "a7a69597-afb2-4660-a4bf-f8f68591a768",
  **"cognito:groups": [
    "admin"**
  ],
  "event_id": "7e9d6b7b-7dd4-4a80-b82c-2b22bb59cb5b",
  "token_use": "access",
-
-
-}

I am trying to control api access ( use/execution)  to based on  congnito:group .  How to implement this?

In JWT plan , i dnt see any viable options.

**Comment by GL-Gravitee2** [comment]
Hi @brasseld ,

Any thoughts here?

**Comment by aelamrani** [comment]
Hi @GL-Gravitee2,

First of all, you have to configure your JWT plan to extract claims on the execution context.

Once done, you can add a policy [Validate Request](https://github.com/gravitee-io/gravitee-policy-request-validation) (either on the plan or on the API level) to check the incoming calls.
