### ISSUE TITLE
[policy] [cors] Access-Control-Allow-Origin parameter ignored

### ISSUE THREAD

**Issue by CracouTech** [gravitee-io/issues#258]
Hello,

When using the CORS policy, it seems that the "Access-Control-Allow-Origin" attribute is ignored, whether "Access-Control-Allow-Credentials" attribute is active or not.

When "Access-Control-Allow-Credentials" is not checked, the "Access-Control-Allow-Origin" header sent in response has always "*" value. That's OK, IMHO.
But, when it's checked, whatever the value set in "Access-Control-Allow-Origin" field (in the portal), the gateway always sends in the responses an "Access-Control-Allow-Origin" header containing the value of the request's "Origin" header.
Which means that there's no control.

The header "Access-Control-Allow-Origin" of the response should be set with the "Origin" header of the request only if the Origin belongs to a white list (set in the "Access-Control-Allow-Origin" parameter of the CORS policy).

For browsers compatibility (some don't like values separated with commas in "Access-Control-Allow-Origin" header) and user comfort, I suggest to replace the text field in the portal (CORS policy settings) by a list of values (just as the "Access-Control-Allow-Headers" field).

Best regards,

Arnaud

**Comment by brasseld** [comment]
Hello @CracouTech,

As far as I understand your issue, you're doing a simple request (not a preflight request).
And you're absolutely right that, in that case, we have to check the `Origin` header with the `Access-Control-Allow-Origin`provided in CORS policy configuration.

But, I'm not agree with your second point:
```
The header "Access-Control-Allow-Origin" of the response should be set with the "Origin" header of the request only if the Origin belongs to a white list (set in the "Access-Control-Allow-Origin" parameter of the CORS policy).
```

According to the [CORS specification](https://www.w3.org/TR/cors/#resource-preflight-requests):
```
If the resource supports credentials add a single Access-Control-Allow-Origin header, with the value of the Origin header as value, and add a single Access-Control-Allow-Credentials header with the case-sensitive string "true" as value.

Otherwise, add a single Access-Control-Allow-Origin header, with either the value of the Origin header or the string "*" as value.

The string "*" cannot be used for a resource that supports credentials.
```

**Comment by CracouTech** [comment]
Hi @brasseld,

Following our conversation about simple requests, there's a step 2 before the step 3 you quoted :
> If the value of the Origin header is not a case-sensitive match for any of the values in list of origins,
> do not set any additional headers and terminate this set of steps.
So I think that, as for preflight requests, the header "Access-Control-Allow-Origin" should only be added to the response (with the request's Origin value) if the Origin belongs to the white-list.

Could you fix it for both requests ?
Thanks.
