### ISSUE TITLE
[management] User friendly URLs on portal/management UI

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#2583]
We should find a way to display user friendly URLs based on the name of the entity and a UUID.

Example: http://apim.host/#!/management/settings/views/my_amazing_view.2106a1af-aba8-4fa0-86a1-afaba8efa054

**Comment by brasseld** [comment]
Duplicate of https://github.com/gravitee-io/issues/issues/2250 ?

**Comment by aelamrani** [comment]
Yes
