### ISSUE TITLE
[management] Admin group should not be removed from API´s

### ISSUE THREAD

**Issue by gigo1980** [gravitee-io/issues#2604]
If I have an admin group this will be assigned to each API / Application. The Owner of this Group should not be able to remove this admin group. Otherwise, some API´s out of scope from the admins of the API platform.

### Expected Behavior
We expect, that the user can see the group, but is not able to delete that group. 

### Current Behavior
An API owner can remove this group, and that the API is possible out of scope for the admins.

### Possible Solution
As discussed with @brasseld there could be an additional setting on the "associate to new API / application" events.

**Comment by manuelottlik** [comment]
Is there any update on this issue?

**Comment by NicolasGeraud** [comment]
hi @manuelottlik,

no it's currently not in the next release.

**Comment by manuelottlik** [comment]
Hey @NicolasGeraud,

any plans to integrate this in one of the next releases? It would be a game changer in production!
