### ISSUE TITLE
[management] Deleting tenants that are linked to endpoints is not well handled

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#2607]
I got some JS errors (see attachments)
<img width="1593" alt="Capture d’écran 2019-09-12 à 17 50 24" src="https://user-images.githubusercontent.com/1580262/64799932-f3d99380-d585-11e9-939a-4b4e028c3a5a.png">
<img width="1915" alt="Capture d’écran 2019-09-12 à 17 51 12" src="https://user-images.githubusercontent.com/1580262/64800002-11a6f880-d586-11e9-895b-dadfbf1e6a26.png">

**Comment by gaetanmaisse** [comment]
Closing as the bug isn't present anymore (at least on APIM 3.10+)
