### ISSUE TITLE
[documentation] swagger.json contains incorrect model definitions

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#2610]
The swagger generator mix `ApplicationListItemSettings` and `ApplicationSettings` for attribute `settings` in `ApplicationListItem`.

### Your Environment

* Version used: 1.25.10

**Comment by gaetanmaisse** [comment]
Closing as a huge work has been done in https://github.com/gravitee-io/gravitee-api-management/pull/1318 to clean the models and migrate to OpenAPI spec.
