### ISSUE TITLE
View plan policies and standard policies in the policies menu

### ISSUE THREAD

**Issue by Produits** [gravitee-io/issues#2611]
### Expected Behavior
In the policies menu, I would like to see the policies I have configured in a plan.

### Current Behavior
Policies configured in a plan are not displayed in the policies menu.

### Possible Solution
It could be interresting to show all policies in the policies menu and distinguish between the two types. It could be usefull too to show to what plan the policy is linked

Thx

**Comment by brasseld** [comment]
Should be closed by #3895
