### ISSUE TITLE
Re-using single client query to multiple Backend endpoints

### ISSUE THREAD

**Issue by riosje** [gravitee-io/issues#2615]
Hi guys, i'm testing your solutions a few days ago and it's awesome the simplest way to configure everything, congrats.

i'm trying to GET data from 2 backend API's in a single API in gravitee, i've read the documentation about attributes and dynamic routing and i've tried to understand as much as possible, but is not clear end off.

## SCENARIO

Currently i'm trying to configure the following api design with policies.
I have 2 API's in the backend:

### BACKEND
http://clients.backend.com/api/systemA
PARAMS:
id
type

http://clients.backend.com/api/systemB
PARAMS:
id
type

### API GATEWAY
I have created an API in gravitee API management:
URL: http://apigateway.com/clients
GRAVITEE API CONTEXT:"/clients"
GRAVITEE API BACKEND:"http://clients.backend.com/api"

this gives me a single point to query and it is usefull for me, but i want to reuse the user query params to give him data from both backend API's with a single query..

![DIAGRAM](https://user-images.githubusercontent.com/55195249/64897014-7b3b0b80-d647-11e9-8c0d-d4974d3fc265.png)

Is there any way to do this?

**Comment by kennylam91** [comment]
Looking for this solution too, anyone can help?

**Comment by riosje** [comment]
Ey I could solve this by using the HTTP Callout policy.https://docs.gravitee.io/apim/1.x/apim_policies_callout_http.html
