### ISSUE TITLE
[management] Gravitee am Forget password

### ISSUE THREAD

**Issue by muthukrishnan-g** [gravitee-io/issues#2622]
Want some clarification for Forget password in Gravitee AM
In our Application we are using Gravitee. So for login the user will give mobile number as username and a password to get the token.
For example : https://am-gateway/{domain}/oauth/token?grant_type=client_credentials&scope=openid&client_id={CLIENT_ID}&client_secret={client_secret}&username={username}&password={password}
Response:
{
"access_token": "***********####**********",
"token_type": "bearer",
"expires_in": 1799,
"scope": "openid",
"id_token": "***********####**********"
}

With the access token we call verify user token to get user sub ID as follows
https://am-gateway/am/{domain}/oidc/userinfo

{
"sub": "XXXXXX-XXXXX-XXXX-XXX-XXXXXX",
"updated_at": XXXXXXXXXXX,
"mobile": "+971**",
"useraccountid": "**",
"preferred_username": "**",
"email": "**"
}

So we tried Reset password in gravitee using the above sub ID as follows
https://am-gateway/management/domains/{domain}/users/{usersubid}/resetPassword

So here comes my Question
We have a scenario in our Application as Forgot password where the user will provide only the username ( in our application it is mobile number), So I want to know how can I Change the password without having user sub ID. Can anyone explain this scenario.

**Comment by tcompiegne** [comment]
Hi @muthukrishnan-g,

There are two ways to reset a password : 

1. Administrators can change the password via the following URL : https://am-management-api/management/domains/{domain}/users/{usersubid}/resetPassword or by using the Administration UI

2. User can reset password after clicking on the `Forgot password` link presents in the login form. The user will received an email asking to reset its password. 

Currently there is no way to directly reset a password with a username.

**Comment by muthukrishnan-g** [comment]
@tcompiegne   Thank you very much :+1: 
 https://am-management-api/management/domains/{domain}/users?q=yourUsername
worked well in my case...
