### ISSUE TITLE
View Logs Gravitee API/Gateway Management

### ISSUE THREAD

**Issue by muthu-krishnan-g** [gravitee-io/issues#2630]
I'm using multiple layers in my Application that goes through the gravitee gateway. So I want to view the logs of each layer I successfully pass by. Is there any way to watch/track the log of gravitee API/gateway and also want to know in detail about gravitee API routing.
(i.e.,how the routing is done when a resource api call flows through the gravitee API) .

**Comment by NicolasGeraud** [comment]
hi,

what layers are you talking about ?

**Comment by muthukrishnan-g** [comment]
we have layer like,
NgInx server -> Node -> Gravitee APi -> Kafka Gateway.

So we want to make sure that Gravitee API propagated request to Kafka gateway or not. Want to see the header and body details like how GAPI propagates request.

**Comment by NicolasGeraud** [comment]
in the gateway we have the following option : 
```
handlers:
  request:
    transaction:
      header: X-Gravitee-Transaction-Id
```

it allows you to fix the name of an header that contains an Id that allow you to track a request accross all your layer.
But Gravitee's logs can only contains the request received/send by the gateway, not the nginx logs.

You can also configure a verbose mode for logs : go to your api, Analytics>Logs>Configure the logging.

Select `Client and Proxy` mode and `true` for the condition.

Gravitee will log everything (be careful of the diskspace of Elasticsearch)

**Comment by muthukrishnan-g** [comment]
Hii @NicolasGeraud ,
As you said,  Gravitee's logs can only contains the request received/send by the gateway,
How can i step up the log configurations?

**Comment by NicolasGeraud** [comment]
As I said : 
You can configure a verbose mode for logs : 
 - go to your api, Analytics>Logs>Configure the logging.
 - select Client and Proxy mode and true for the condition.

Gravitee will log everything (be careful of the diskspace of Elasticsearch)

**Comment by muthukrishnan-g** [comment]
@NicolasGeraud ,
How to clear the logs

**Comment by muthu-krishnan-g** [comment]
closed
