### ISSUE TITLE
Rectriction of Access Token Authenticaion for each domain and client

### ISSUE THREAD

**Issue by muthukrishnan-g** [gravitee-io/issues#2631]
I have created two domains in gravitee AM with a client under each of them.Also created two apis in gravitee API.
I got the access token with the unique credentials of the two domains from the gravitee AM.
When i passed the access tokens to the api's created in Gravitee API,there is no restrictions for the token against the separate domains.
For Example:
I have created a domain named **customer** and a client named **employee** with client_id **employeeid**,client_secret **employee_secret**.
and also another domain named **users**  and a client named **user** with client_id **userid**,client_secret **user_secret**.
So i can get two different access tokens with the above two domains.
Similarly, I created two apis in gravitee API.one with the context path as **/employee** and another as **/user** and configured oauth2 with respective Gravitee AM domains.
When i used the access token from **customer** domain with its client_id and client_secret and used as **bearer token** and access the api resource with context path **/user**.But the token was authenticated and verified successfully even though I used the token from another AM domain credentials which should not be verified and must show error.
Hence give me a explanation for this issue and tell me how to restrict the access token to access the api resource against the AM credentials configured in Gravitee API --> Design -->Resources
-->Gravitee.io AM Authorization Server Resource .

**Comment by 0xC4N1** [comment]
I didn't very this but I think the gateway shouldn't accept tokens from other domains. However each token has an issuer claim `iss`. Even when the gateway rejects access tokens from other domains you should teach your application to deny tokens that are issued by wrong issuers.

**Comment by muthukrishnan-g** [comment]
Issue Closed..Thank you for the solution
