### ISSUE TITLE
[gateway] API Policy Path is not handled

### ISSUE THREAD

**Issue by tnus** [gravitee-io/issues#2632]
### Expected Behavior
In the design menu of an Api an additional path "/test" is added. A Mock Policy is added to this path which should return "test". To the root path a mock policy is added which returns "root".

When the api is called with the "/" path "root" should returned, if it is called with "/test" "test" should be returned.

### Current Behavior
The api always returns "root", also when it is called with the "/test" path.

### Steps to Reproduce (for bugs)
1. Go to design menu of an api
2. Add the mock policy to the root path and put "root" in the content parameter
3. Add a new path "/test"
4. Add a new mock policy to the test path and put "test" in the content parameter

### Context
I migrated from Gravitee 1.28 to 1.29 and now my existing apis are not working, because i use these path values.

### Your Environment

* Version used: 1.29.0
* Browser Name and version: Google Chrome 76.0.3809.132 
* Operating System and version: Windows 10
![bug-gravitee-01](https://user-images.githubusercontent.com/10140974/65223125-c4181780-dac0-11e9-9528-42106b4dcc6a.JPG)
![bug-gravitee-02](https://user-images.githubusercontent.com/10140974/65223126-c4181780-dac0-11e9-8757-bcda8d754a03.JPG)

**Comment by NicolasGeraud** [comment]
hi @tnus 
so you mean this works in 1.28 and not anymore in 1.29 ?

can you export your api and share it here ?

**Comment by tnus** [comment]
Yes it worked in the version before (1.28.1). I just created a test api to reproduce it.


[BUG-2632-1-0.zip](https://github.com/gravitee-io/issues/files/3630039/BUG-2632-1-0.zip)

**Comment by tnus** [comment]
Used the wrong button, sorry for closing this issue. The bug still exists.
