### ISSUE TITLE
[gateway] remove the legacy mode for url encoding

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#2634]
remove the legacy mode introduced by #2557

**Comment by brasseld** [comment]
https://github.com/gravitee-io/gravitee-gateway/blob/master/gravitee-gateway-http/src/main/java/io/gravitee/gateway/http/connector/VertxHttpClient.java#L136

The property encodeUri must also be removed from definition:
https://github.com/gravitee-io/gravitee-definition/blob/master/model/src/main/java/io/gravitee/definition/model/HttpClientOptions.java#L42

Must be removed also from Management UI
