### ISSUE TITLE
Manually Expire a Access Token

### ISSUE THREAD

**Issue by muthukrishnan-g** [gravitee-io/issues#2636]
Hi Team,

In Gravitee AM I have set time duration for the token expiration.
Now i need a feature to expire a token manually.Since i have login and logout functionality in my application,once i click the logout button i want to expire the access token.
So kindly suggest a way to implement this feature.

**Comment by tcompiegne** [comment]
Hi @muthukrishnan-g,

You can take a look at the OAuth 2.0 Revocation Endpoint : 

https://docs.gravitee.io/am/2.x/oauth2/index.html#tag/OAuth-2.0%2Fpaths%2F~1revoke%2Fpost

**Comment by muthukrishnan-g** [comment]
Dear @tcompiegne 
I posted as
