### ISSUE TITLE
[gravitee-policy-request-validation] Support order of rules

### ISSUE THREAD

**Issue by brightlizard** [gravitee-io/issues#2666]
We are trying to group several rules(conditions) inside one “Validate Request Policy” to reduce quantity of policies in UI view and expecting that the order of rules will be the same as defined in UI/API_definition.
For example:
1.	Constraint / Type = NOT_NULL
2.	Constraint / Type = PATTERN
.. and so on
But unfortunately the order is not guaranteed because of this line of code -> “Set<ConstraintViolation> violations = new HashSet<>();”
It would be great to change HashSet structure to LinkedHashSet or ArrayList.
We can make PR if you want.

**Comment by brasseld** [comment]
PR would be really welcomed :)

**Comment by brightlizard** [comment]
Please check the PR, all checks seems to be passed and conflicts resolved.

**Comment by brasseld** [comment]
Hi @brightlizard 

We will. I've associated the issue to 1.29.x to make it available within the next minor release
