### ISSUE TITLE
[gateway] Does Gravitee API Gateway support mutual authentication?

### ISSUE THREAD

**Issue by wishkres** [gravitee-io/issues#2668]
Does Gravitee API Gateway support mutual authentication/authentication of users with client certificates? I haven't found anything concrete in the documentation that says it does.

I would be very interested in having this feature, if it does not already exist. I would like to be able request a client certificate from the user using the browser, then be able to do some configurable or programmatic behavior. Some of the options I would like to see is the ability to run the certificate through OCSP to verify the certificate is valid, as well as parsing the subject and issuer of the certificate in order to look the certificate's user in an LDAP server.

**Comment by ssoogur** [comment]
we have backend API which is protected with username/password , how do I pass username/password to backend api  through policies in Gravitee api gateway

**Comment by ssoogur** [comment]
we have backend API which is protected with username/password , how do I pass username/password to backend api  through policies in Gravitee api gateway

**Comment by brasseld** [comment]
@ssoogur please ask your question from a dedicated issue and not by using an other one without any link.

**Comment by ssoogur** [comment]
I am new to this process, how would I create new thread . we are working on implementing this solution in our org with proper support  and for that I have to show this solution work by demoing an  backend api which is protected with user/password

**Comment by YoranSys** [comment]
Linked to : https://github.com/gravitee-io/issues/issues/3160 ?

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/issues/issues/3160
