### ISSUE TITLE
[portal] Change oauth2 library satellizer

### ISSUE THREAD

**Issue by l-lin** [gravitee-io/issues#2672]
Gravitee is using the authentication module [satellizer](https://github.com/sahat/satellizer) for OAuth2 but it is not maintained anymore and contains bugs. Please consider forking the library or change to an alternative authentication module.

### Context

I have a Spring Boot 2 web application which is my OAuth2 authentication server.
My authentication server can isolate the users by "workspace", and it's translated in the URL by an additional query parameter `?workspace=whatever`.

So what I put in the `authorization endpoint` in Gravitee is: https://localhost/auth/oauth/authorize?workspace=cats

### Expected Behavior

When I'm signing in via the popup login form, the popup should close and I should be authenticated in Gravitee like the other authentication services (e.g. Github, Twitter, ...).

The redirect URL should be https://localhost/auth/oauth/authorize?workspace=cats&response_type=code&client_id=oodrive&redirect_uri=http://localhost:8002&scope=

Notice the `&` after my custom query parameter `workspace`.

### Current Behavior

After signing in, the popup is not closed and I'm not authenticated in Gravitee.

The issue comes from the fact the redirect URL is https://localhost/auth/oauth/authorize?workspace=cats?response_type=code&client_id=oodrive&redirect_uri=http://localhost:8002&scope=

Notice the `?` after my custom query parameter `workspace`.

Thus, after signing in, it does not take into account all the parameters.

### Possible Solution

The issue comes from this line: https://github.com/sahat/satellizer/blob/master/src/oauth2.ts#L83

It does not parse the `authorizationEndpoint` and consider as an URL without query parameters.

Please consider forking the authentication module to have a fix (the author of satellizer does not seem to maintain the project anymore) or change to another up-to-date authentication module (which I think is unlikely as Gravitee management UI is still in AngularJS).

### Steps to Reproduce (for bugs)

1. Have a custom OAuth2 authorization server in Spring Boot 2
2. Add a new identity provider with this authorization server
3. Try to sign in with the new identity provider
4. The popup login form is not closed and you are not authenticated in Gravitee Management

### Your Environment

* Version used: 
  * Gravitee: 1.29.0
  * Spring Boot: 2.0.X
* Browser Name and version: not relevant
* Operating System and version: not relevant

**Comment by brasseld** [comment]
Hi @l-lin @adriengibrat 

We'll bring a new portal for the end of the year.
Please stay tune :)

**Comment by brasseld** [comment]
No more relevant with v3
