### ISSUE TITLE
[portal] Authenticate with 3rd party identityProvider with openID connect 

### ISSUE THREAD

**Issue by ssoogur** [gravitee-io/issues#2681]
I have requirement where use can login to Gravitee Management  portal with 3rd party Identity provider using OpenID connect , i created profile not sure where the group/role assignment happen is that with in Identity provider or Gravitee repository and also user login is not happening with 3rd party identity provider . It always looks for local Gravitee repository for authentication to loginto portal     
![image](https://user-images.githubusercontent.com/55739704/65716969-32834980-e06e-11e9-89c1-695fc3661908.png)
![image](https://user-images.githubusercontent.com/55739704/65717228-ce14ba00-e06e-11e9-953e-a30b76d9acb4.png)
![image](https://user-images.githubusercontent.com/55739704/65717718-010b7d80-e070-11e9-914d-ba370e6c3d54.png)
![image](https://user-images.githubusercontent.com/55739704/65717791-24cec380-e070-11e9-981d-991ab7408344.png)
![image](https://user-images.githubusercontent.com/55739704/65717846-4039ce80-e070-11e9-9843-3afb9a636808.png)

**Comment by brasseld** [comment]
Here is an example of a condition:

`{#jsonPath(#profile, '$.identity_provider_id') == 'idp_5' && #jsonPath(#profile, '$.job_id') != 'API_BREAKER'}`

so we are extracting the `identity_provider_id` property from the `profile` and check that its value is equals to `idp_5` , ...

`#profile` represents the output of the UserInfo OIDC endpoint.

If it's not clear enough, please provide a userinfo response example, and what you're looking for in terms of condition, and I will try to help / guide you.

**Comment by ssoogur** [comment]
here is the output of userinfo 

{"sub":"xxxx.xxxx@xxx.com"}

**Comment by aelamrani** [comment]
@ssoogur seems you should define more scopes (at least openid)

**Comment by ssoogur** [comment]
I updated with scope still same think , not able to login to management portal with third party identity provider

What would be values in map and roles if my userinfo returns
{"sub":"xxx.xxx@xxxx.com"}


[cid:image001.png@01D57944.E1F16B90]

**Comment by brasseld** [comment]
You must receive more information from userinfo, that's the reason why it doesn't work.

Also, if you don't need role mapping, just remove the line and save.

**Comment by ssoogur** [comment]
Thanks

I need role mapping , what would the value for that

I changed scope to profile and I get following values in userinfo

{"sub":"xxxx.xxxxx@xxxxx.com","name":"XXXXXXX","given_name":"XXXXX","family_name":"XXXX"}

Still I am  not able to login to Management console with thirdparty provider ID

Thanks
Shashi

**Comment by brasseld** [comment]
ok, did you have a try without any group or role mapping ?

**Comment by ssoogur** [comment]
Yes I did ….I get username/password not valid

**Comment by ssoogur** [comment]
Screenshot what I have in my auth profile

[cid:image001.png@01D579D5.91193180]

**Comment by aelamrani** [comment]
Seems you need another scope to get the user's email... Maybe `email`?

**Comment by ssoogur** [comment]
Don’t think so , email is same as sub in our case

**Comment by aelamrani** [comment]
Ok so you have to adapt the user profile mapping above. I think you should have `email` bind to the `sub` so..

**Comment by ssoogur** [comment]
Yep it was mapped email to sub

[cid:image001.png@01D579EC.C389D310]

**Comment by aelamrani** [comment]
Please come to attach your files in GitHub directly (and not by email) as i am not able to see anything...

**Comment by ssoogur** [comment]
![image](https://user-images.githubusercontent.com/55739704/66216092-d3878b00-e692-11e9-9d18-97535508df1c.png)

**Comment by ssoogur** [comment]
attached image in github as per your request .

**Comment by aelamrani** [comment]
OK LGTM
So what's the problem now? Do you have an error or exception to share?

**Comment by ssoogur** [comment]
I et wrong user/password when I try to login to management portal

**Comment by ssoogur** [comment]
WARN  i.g.m.s.l.AuthenticationFailureListener - Authentication failed event for: xxxx@xxxx.com - IP: xxx

**Comment by aelamrani** [comment]
So you are using the login Gravitee. Can you try the login with your Identity Provider?

**Comment by ssoogur** [comment]
How would I do that to get into grvaitee management portal ?

**Comment by ssoogur** [comment]
how would i do it to get into Gravitee Management Portal

**Comment by aelamrani** [comment]
You should have a new button under the login form for your OIDC auth.

**Comment by ssoogur** [comment]
thanks , looks like its a blank button
![openid_log](https://user-images.githubusercontent.com/55739704/66223934-b064d780-e6a2-11e9-8faf-0dce50698a07.PNG)

also can you tell me what should i be doing to give logged in user default "user" role

**Comment by aelamrani** [comment]
You should apply a color

**Comment by ssoogur** [comment]
Thanks that helped , able to login now but some how logout url is not constructed properly. It is constructing as shown below and getting page not found  

https://xxxxxxxxxx/oauth2/connect/endSessionhttp%3A%2F%2FGravityURL.xxxx.com

**Comment by aelamrani** [comment]
maybe you should change the user logout endpoint of your identity provider to something like: `https://xxxxxxxxxx/oauth2/connect/endSession?redirect_url=http%3A%2F%2FGravityURL.xxxx.com`?

**Comment by ssoogur** [comment]
I get this error "The endSession endpoint requires an id_token_hint parameter" , how would I pass that value

**Comment by aelamrani** [comment]
According to the documentation the parameter is: `post_logout_redirect_uri `

http://docs.identityserver.io/en/latest/endpoints/endsession.html

**Comment by ssoogur** [comment]
questions is where do I get that id_token_hint value , logout url is constructed dynamically

**Comment by aelamrani** [comment]
As far as I know, this is an optional **parameter** to bypass the logout confirmation screen.

**Comment by ssoogur** [comment]
unfortunately its a mandatory field as part of our Identity Provider is  concerned, any way we can pass that value in logout url

**Comment by aelamrani** [comment]
OK so may i close this issue?

**Comment by ssoogur** [comment]
still logout is not working , I need help with regard to it . I keep getting "The endSession endpoint requires an id_token_hint parameter". Please let me know how to pass id_token_hint during logout

**Comment by aelamrani** [comment]
According to me there is no way for now to pass this parameter. Again, it seems this parameter is optional: https://openid.net/specs/openid-connect-basic-1_0.html

**Comment by ssoogur** [comment]
hmmm, it becomes showstopper to go with this product . I have to demo this product to management with proper working condition . Any way I can get quick fix for it

**Comment by aelamrani** [comment]
Maybe you can try to disable it from IdentityServer no?

**Comment by ssoogur** [comment]
I tried it , there is no option given to disable it .

**Comment by ssoogur** [comment]
any way you can help providing quick patch for logout issue

**Comment by brasseld** [comment]
Unfortunately, we didn't store / keep the id_token from your identity server so there is no chance for us to provide it back while the user logout...

Did you see the `EnableSignOutPrompt` configuration from IdentityServer ?
https://identityserver.github.io/Documentation/docsv2/configuration/authenticationOptions.html
