### ISSUE TITLE
[management] Cannot validate JSON body schema of API policy update request

### ISSUE THREAD

**Issue by fmigneault** [gravitee-io/issues#2682]
Schema validation of APIM seem to mismatch it's actual behaviour.

Referencing issues posted on other repo here:

https://github.com/gravitee-io/gravitee-docs/issues/167
https://github.com/gravitee-io/gravitee-docs/issues/162

**Comment by brasseld** [comment]
Hi @fmigneault 

Thanks a lot for contributing these issues.

I fully understand your concern and that's really a pain that you can't do what you're looking for with our schema.

The problem we are encountering (and that makes this issue can't be treated easily) is that our API model (the `definition`: https://github.com/gravitee-io/gravitee-definition) is provided with its own set of Jackson serializers and deserializers.

Unfortunately, the Swagger descriptor you're talking about in your issues has been generated by Swagger tools from https://github.com/gravitee-io/gravitee-management-rest-api/tree/master/gravitee-management-api-rest

As this tool does not take care of custom Jackson serializers and deserializers, we are not able to provide you with a "valid" model definition to represent an API definition.

The only solution I'm seeing there would be to rewrite the Swagger descriptor manually.

That's what we're doing for the new version of the API portal. We have adopted the contract-first approach, so the OAI descriptor is written before the Java implementation: https://github.com/gravitee-io/gravitee-management-rest-api/blob/v3/gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml

For now, this is concerning only the Portal API and not the Management API.

But if you know a simple way to "override" the swagger descriptor, I will be more than happy to look into it.

Regards,

**Comment by fmigneault** [comment]
@brasseld 
This is not currently "blocking" for me, I'm able to do a few manual validations in the meantime.
Unfortunately, I'm not familiar enough with the auto-gen mechanism to know how to override it.
I will wait for your updates for eventual APIM OpenAPI definition.
