### ISSUE TITLE
[Gateway] PUT request with file authorization failure

### ISSUE THREAD

**Issue by MatProv** [gravitee-io/issues#2688]
When we attach a file to a PUT request, the request is delivered to the target endpoint event if our authorization policy says the operation is not granted and stops the policy chain.

### Expected Behavior
 - Request blocked since authorization plugin stops denies access

### Current Behavior
 - The request is sent to the target endpoint
 - Our authorization plugin confirms that access should be denied (expected behaviour)
 - Our authorization plugin stops the policy chain but file is already uploaded
 - GET requests are correctly blocked by the authorization plugin, not PUT ones

### Possible Solution
Would it be possible that PUT action using a file as parameter is processed event if policy chain blocks the action?

### Steps to Reproduce (for bugs)
1. Send a PUT request with a file attached to it to a file server
2. In gravitee, make the policy chain fail
3. File is present on the file server even after policy chain failure

### Context
It affects us in a way that we could block file upload to our storage service using our authorization mechanism.

### Your Environment
* Version used: 1.25.0
* Browser Name and version: Chrome
* Operating System and version: Ubuntu

**Comment by brasseld** [comment]
You're running your own custom policy ?

**Comment by MatProv** [comment]
Thanks for the fast reply.

The issue was on our side, in specific case the policy chain was continued even if authorization wasn't given. The binary is not uploaded if auth fails, which was the expected behaviour.
