### ISSUE TITLE
[portal] Allow a user to login

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#2725]
As a consumer of APIs, i want to be able to login in the portal.
I should be able to log in with multiple identity providers like social (GitHub / Google) or OAuth2/OIDC.
Once logged my user information are retrieved and displayed.

For registration, see #2810

**Comment by aelamrani** [comment]
- An input field text
(- An input field password)
- Notifications (errors, success...)
- Icons (GH, google...)

1. Login
- Integrate these components in the login screen
- Call the REST API to login
- Redirect to home
- Get/display user info

2. Register
- Create the registration API
- Generate webclient
- Integrate these components in the register screen
- Call the REST API to register
- Redirect to login
- Conditional

**Comment by phiz71** [comment]
Registration part has been moved to #2810
