### ISSUE TITLE
 Unable to get a connection to Elasticsearch

### ISSUE THREAD

**Issue by jinshuchu** [gravitee-io/issues#2730]
docker-compose  start service  get  Unable to get a connection to Elasticsearch
![image](https://user-images.githubusercontent.com/11752171/66477887-b2c49880-eacb-11e9-9030-f716db7e4b5d.png)

**Comment by adamczi** [comment]
Can you make sure your elasticsearch container is running? I had the same issue - had to increase vm.max_map_count on host system as in [this article](https://ynuxtechblog.wordpress.com/2016/01/05/getting-your-system-parameters-right-in-dockered-elasticsearch/#vm.max_map_count), after that it was okay.
