### ISSUE TITLE
[portal] how to control the login buttons to display

### ISSUE THREAD

**Issue by l-lin** [gravitee-io/issues#2731]
I want to have control over what login buttons to display depending of a query parameter in the URL.

### Context

I have a Spring Boot 2 web application which is my OAuth2 authentication server.
My authentication server can isolate the users by "workspace", and it's translated in the URL by an additional query parameter ?workspace=whatever.

So what I put in the authorization endpoint in Gravitee is: https://localhost/auth/oauth/authorize?workspace=cats

Depending of the workspace, the authentication type is different (basic login/password, LDAP, ...).

Thus, if I want to enable Gravitee for all my clients, I must configure as much identity provider as the number of workspaces I have (which is a lot). Without considering the fact it's not safe for a client A to know there is another workspace named 'B', it's not user-friendly to have hundred login buttons in the login page.

### Question

Is it possible to filter the list of identity provider returned by the endpoint `/management/portal/identities` depending of the query parameter `workspace`?

If not, is it possible to mitigate this issue from Gravitee, i.e. without touching my authentication server?

### Your Environment

* Version used: 1.29.0

**Comment by brasseld** [comment]
There is no easy way to do this actually as part of Gravitee.

The best you can do is to extend gravitee to take care of the additional query-parameters.

**Comment by l-lin** [comment]
I see, that's too bad :disappointed:

**Comment by brasseld** [comment]
I know, but this issue really depends on your context.

So, IMHO, one option is to :
- Manage query-parameters from the login view and be able to send them as part of the authorization endpoint (it can be done with a simple PR for webui module)

**Comment by l-lin** [comment]
But, as you mentioned in this [comment](https://github.com/gravitee-io/issues/issues/2672#issuecomment-534700932), a brand new portal will be released at the end of the year, so I guess if I add this feature, it will not be present in the new portal.

I was hoping something like a plugin that could extend/override gravitee features.

**Comment by brasseld** [comment]
> But, as you mentioned in this comment, a brand new portal will be released at the end of the year, so I guess if I add this feature, it will not be present in the new portal.

You're right, and mostly because we'll change the module we are using to manage oauth2 authentication.
