### ISSUE TITLE
[management] Could not connect to SMTP host: smtp.163.com, port: 465, response: -1

### ISSUE THREAD

**Issue by jinshuchu** [gravitee-io/issues#2734]
hello this is my gravitee.yml config

# SMTP configuration used to send mails
email:
  enabled: true
  host: smtp.163.com
  subject: "[Gravitee.io] %s"
  port: 465
  from: apimservice@163.com
  username: apimservice@163.com
  password: ygyw5899
  properties:
    auth: true
    starttls.enable: true
    ssl.trust: smtp.163.com

# Mail templates
templates:
  path: ${gravitee.home}/templates

the error log is 
![image](https://user-images.githubusercontent.com/11752171/66634459-b8db8600-ec3f-11e9-9d0b-8e0b26947c33.png)
What should I do? thanks

**Comment by NicolasGeraud** [comment]
Hi @jinshuchu 

Have to verify that the host/port is reachable from the gravitee rest-api host (and in the container if you use docker) ?
