### ISSUE TITLE
Rewriting POST content based on URI (or query string)

### ISSUE THREAD

**Issue by GroundTruthNZ** [gravitee-io/issues#2739]
We've been using Dynamic Routing to pass an API key to a Geoserver instance as a parameter.

**E.g. Match expression** 
/(\w+)/(\w+)/([0-9]+)

**Redirect to** 
http://xxx.xxx.xxx:8080/geoserver/{#group[0]}/{#group[1]}/{#group[2]}?viewparams=apikey:{#group[1]}

However, this will only work for GET requests.  Geoserver ignores the query parameters if it is an http POST and instead expects the parameter to be in the request body.

e.g:
`<?xml version='1.0' encoding='utf-8'?>`
`<GetFeature `
` wfs:viewParams='apikey:XYZ'`
` .`
` .`
` .`
`</GetFeature>`

Is it possible to pull something out of the URL and insert it into the body?   I've tried playing around with assigning attributes and content but can't figure out to make this work.

Any help greatly appreciated!

**Comment by GroundTruthNZ** [comment]
I've managed to get something working using a Groovy policy.  Not sure if it is the best way of doing things but it works:  

**On-request content script**
`def newpath = request.getPath();`
`def paths = newpath.split('/');`
`return request.content.replace('<GetFeature', '<GetFeature\n wfs:viewParams=\'apikey:' +  paths[4] +  '\'' );`

**Comment by brasseld** [comment]
Hey @GroundTruthNZ 

What about using the https://docs.gravitee.io/apim_policies_assign_content.html policy ?

**Comment by GroundTruthNZ** [comment]
Thanks @brasseld 

Can you provide an example of how you might achieve the same result with the Assign Content Policy?  I couldn't figure out how to access the parts of the request path and insert them into the body content. The documentation is a bit sparse (not complaining though - Gravitee is awesome)...
