### ISSUE TITLE
[management] Provide an access token to the management-api for each API for CI/CD purposes

### ISSUE THREAD

**Issue by manuelottlik** [gravitee-io/issues#2749]
To make changes on an API via CI/CD there should be an access token (for the gravitee management API) known to the owner of the API (PRIMARY_OWNER for example) that is scoped to making changes on this API only.

### Expected Behavior
When an API is created it also generates an access token for the gravitee management API that can be used to makes changes on the API via CI/CD.

### Current Behavior

If you want to make changes to an API in CI/CD via the gravitee management API you need to create a technical user with permissions scoped to that specific API only, because the pipeline could otherwise be misused to manipulate other APIs. This does not scale very well and therefore makes it hard to version changes of the API documentation in a git repo.

### Possible Solution

As stated already, implement access tokens for each API. The token could be shown one single time at creation. It could also be accessible by the PRIMARY_OWNER of the API. Maybe you might even want a workflow that enables the owner to generate a new access token or scope different tokens to different actions.

### Context

We are using git repos to version changes of the openapi-specification, the api documentation etc. The corresponding pipeline pushes these files into gravitee via the management api. To use this API, a user with a password has to be provided. If you would want to ensure that the pipeline cannot change the content of other APIs, each API would need its own technical user with permissions to its API. Instead, we propose to implement an access token per API that can be used as a secret in pipelines.

**Comment by manuelottlik** [comment]
What do you think of this feature request?

**Comment by adubreuiltk** [comment]
We have a similar need for CI/CD purposes.
The UI is fine and required for development purposes but once there are many API with complex settings (docs, user groups, endpoints...), the API must be automated.

The use of tokens that could configurable (access, permissions, api...) would be helpful.

**Comment by brasseld** [comment]
@manuelottlik it is a brilliant idea !

The only thing we have to think about is the audit. When using such token, who (physical person) is responsible and logged into the audit? The primary_owner who has the responsibility of the API?

I'm just asking myself if it the token should be provided as a per-API basis or if it is relative to a user account (in that case, the token will have exactly the same access and rights as the user). The problem with this solution is that we'll still rely on a user and not a "technical" account...

Also, if we are provided a per-API token, I assume it should be done also for applications, in a very similar way...

**Comment by adubreuiltk** [comment]
We are interested in such a feature. Please find hereafter a non exhaustive list of ideas about how to manage such tokens:
- **Personal Token**
    * Created by a real user
    * The tokens inherits all the user permissions
    * The user can restrict the permissions
- **Global Token**
    * Created by an admin user
    * Can access anything but to used as a restricted token (API, application, group...)
    * Such a token should have a short description (similar to a username) to be displayed in the logs instead of the admin username

**Comment by manuelottlik** [comment]
When talking about audit, I think it is sufficient to use the token itself as an actor on the platform including the owner of that token. If tokens are created and scoped to permissions by the PRIMARY_OWNER of an API or application, it is his responsibility to not give this token to other people.
If you use the token in CI/CD for example, it would never be exposed to developers using the pipeline that has the secret injected, but you could always see who actually modified & triggered the pipeline.

Regarding your point of API tokens vs. user tokens: I think it is important to be able to create tokens that are scoped to **one** API / application.  Inheriting the user permissions would simply provide another way to authenticate an user on the API while scoping a token to **one** object would enable the PRIMARY_OWNER to create a token that his team can use in CI/CD etc.

When talking about tokens, we might also consider providing tokens on a global scope to edit parameters / configuration / content of the platform. This might be a seperate feature request / issue though. If you wish, I will create one.
