### ISSUE TITLE
[gateway] Separate contents of Log from Metrics.Log in a reporter plugin

### ISSUE THREAD

**Issue by mgoblin** [gravitee-io/issues#2751]
### Issue Context
Reporter is able to do its job on report(Reportable reportable) method call. io.gravitee.reporter.api.Reportable has subclasses:

* io.gravitee.reporter.api.log.Log for API call detailed logging
* io.gravitee.reporter.api.http.Metrics for aggregated details of API call

io.gravitee.reporter.api.http.Metrics has log field.

### Current Behavior
Currently filling of Log and Metrics.log fields are tightly coupled. Changing log depth level by API Admininstrator affect to both Log and Metrics.Log fields content.
By default detailed API call logging is disabled and Metrics.log is null.

If Metrics will be used to audit API calls API Adminstrator currently able to disable or hide important details from auditing.

### Expected Behavior
Log depth and fields content configuration not changed, it would be configured and filled the same way as now.

Metrics.log field should not be null. Metrics.log instance fields will be filled regardless of Log fields.
Metrics.log instance fields content will be configured via gravitee.yaml. 
On the future configuration of Metrics.log could have Web UI that will be accessible to MANAGEMENT.ADMIN role.

**Comment by kanischev** [comment]
Hi, @brasseld!
WDYT will be the best way of solving this issue without much breaking changes?
One approach I've already tried - is to make those logging feature configurable on the whole gateway level. Changes are not large and default config can leave the behaviour unchanged as a plus. The thing I don't like - UI on API management becomes confusing. Fields with logging expressions and mode should become optionally editable - and that will make APIM and gateway more tightly coupled.
The other way of solving could be making optional auditing service/configuration/plugins with logging info doubling (separate request Processor) or LoggableRequestProcessor adding to ProcessorChain basing on auditing gw configuration.
Or, maybe, we can add configuration on auditing separately. Still fill Log object, and then audit it with separate Reportable class?

**Comment by brasseld** [comment]
As far as I understand the issue, it is just a matter of removing the log field from metrics and use a dedicated way to manage Log for a given request.

Right ?

**Comment by kanischev** [comment]
Hi @brasseld!
Not exactly. The key problem to solve here is not just extracting Log object from metrics but that we need to have full gw request-response cycle audit not tied with concrete API Log configuration. We want to provide API publisher with the ability to manage API, but support team should in any case get full audit on requests-response handled by gw-s. Isn't it, @mgoblin Michael?

**Comment by mgoblin** [comment]
Hi guys

At my point of view the main problem is with mixing logging and audit.

Logging targeting to support team and doesnt have any security sensitive info as OAuth2 tokens, passwords, credit card numbers and etc. Support team members may change log depth and cant disable or affect on depth of audit. 

Security audint should have security sensitive info. 

Now logging and audit closely coupled. The ways of logging and audit should be separated at my point of view.

**Comment by brasseld** [comment]
Hello @mgoblin  @kanischev 

By `audit`, I assume you mean `request metrics`, right ?

IMHO, logging is also be used by the API publisher, in case of request errors, debugging (when playing with policies), ...

Also, from the management-api and UI point of view, log and "audit" are managed by different set of permissions so I assume that's not an issue with managing access to these data.

So I'm probably a bit stupid here, but again it seems to me just a problem of mixin between logging and audit. Or perhaps, I'm missing the main point of the issue?

**Comment by mgoblin** [comment]
We discuss this issue with Albert deeper

- Reporter Metrics object should be configurable at Gateway config file. (How to fill metrics fields)
- Reporter Log object  should be configurable at Gateway config file and this config is default to all API (how to fill log fields by default)
- API administrator can configure API logging and this config has higher priority than the gateway level config (how to to fill log fields of Reporter.log for particular API)

At implementation level for resource consumption optimization duplication of Log objects could be avoided.

@brasseld - your undestanding of main point is right and @kanischev concerns is about simple and optimal implementation.

**Comment by brasseld** [comment]
> At implementation level for resource consumption optimization duplication of Log objects could be avoided.

I'm still interested by this since I do not see where Log objects are duplicated.
For me, there is a single Log instance associated to the Metrics, so they are sharing the same reference.

Anyway, before going ahead on this, I think the first thing to achieve, IMHO, is to remove dependency between `request metrics` and `log`.

**Comment by kanischev** [comment]
@brasseld ok, I understand the concept with Metrics.Log object separation - that's all right.
But the key need we want to achieve - is to have smth like { Metrics + Log } object configured on the gateway level without the ability to change that on per-API level to be used for GW request-response handling audit.
Duplication can arise if we decide to make this object fully separate from existing Metrics and Log (doesn't matter nested or separate). I've proposed few concepts to implement this above.

**Comment by brasseld** [comment]
Ok, I think we are more or less aligned on these topics.

FYI, `request metrics` can not be configured, neither from the gateway nor on a per-API level.

IMHO, the ability to configure something makes sense only in the case of Log (that's what you've done already with SSL support).

WDYT?
