### ISSUE TITLE
Swagger exposed is not valid : extra fields 'originalRef'

### ISSUE THREAD

**Issue by deka** [gravitee-io/issues#2755]
Le fichier swagger exposé par l'option 'Show the URL to download the content' (configuration de la doc) n'est pas bon.

### Expected Behavior

Obtenir le vrai fichier swagger présent dans la page 'Page' de la documentation

### Current Behavior
Des champs supplémentaires sont ajoutés. Le fichier n'est plus un fichier swagger valide.
Champ ajouté : 'originalRef'

### Possible Solution
Lié à ce bug ? 
https://github.com/springfox/springfox/issues/2917#issuecomment-470568394

### Context
Objectif : avoir un fichier swagger valide pour de la génération de code (Autorest)

**Comment by brasseld** [comment]
Bonjour, 

Pouvez-vous fournir le swagger initial et le swagger modifié afin que l'on puisse fair un diff des deux.

Merci
