### ISSUE TITLE
Connection refused got on gateway tests

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#276]
I got a connection refused on the gateway's tests, launching from my machine.

OS : MacOSX Sierra

**Comment by brasseld** [comment]
When you request a hostname, the JDK resolves it to IP addresses. It then tries a reverse lookup of those addresses and checks that at least one of the results maps back to the input host name. It's this reverse lookup that's slow. The slowness isn't limited to the JVM. Anything on the OS that tries to perform such a reverse lookup will be slow without appropriate configuration in /etc/hosts.

Please have a look to : [java.net.InetAddress: getLocalHost() slow after MacOS Sierra upgrade?](https://thoeni.io/post/macos-sierra-java/)
