### ISSUE TITLE
Swagger documentation page use current URL

### ISSUE THREAD

**Issue by AudricCh** [gravitee-io/issues#2770]
Hi,

After I've created a documentation's page for my API and configure it, we've got the "Try it" mode on the right of the parameter page.

But when I execute an endPoint, the requested URL is the API Manager's one, and not the real API endpoint.

I've tryed on the API documentation page directly, and it work perfectly.

Example :
I'm on https://mycompany.api-manager.fr (locale URL) that contains the Gravitee API manager solution.
And on https://mycompany.apis.fr (locale URL too) I've got the published APIs.

### Expected Behavior

It should work as the API documentation page, call the good URL and not the API management one.

### Current Behavior
![image](https://user-images.githubusercontent.com/25503027/67389525-14d8cf80-f59b-11e9-953f-36a8fd1d462d.png)

We can see on the called URL that's the wrong URL which is call.
Should be https://mycompany.apis.fr/myEndPoint instead of https://mycompany.api-manager.fr/myEndPoint

### Context
It should be the exact same swagger than the API documentation page.

### Your Environment

* Version used: 1.25.10
* Browser Name and version: Chrome 77.0.3865.120
* Operating System and version: Windows 10

**Comment by aelamrani** [comment]
Hi @AudricCh 

I'm not sure if this feature should be available on the management part.

I think the try it feature can/have to be used in the portal by the API consumers and by the API publisher before to publish the page.

WDYT?

**Comment by AudricCh** [comment]
So why let you the user to be able to do it ? If it's not working properly ?

In my opinion, if we have the "Try it" button, it should work.
But as you're saying, it's not a required feature, it can be suppress if you think there is no added value.
Or maybe just don't let the "Try it" button but let the swagger page on the right.

**Comment by aelamrani** [comment]
IMHO this should not be part of the page in the management part but only on the portal.

So i agree with you, we have to remove the button in that case.
