### ISSUE TITLE
how to download and build the gravitee-policy-rest-to-soap

### ISSUE THREAD

**Issue by Skyrioca** [gravitee-io/issues#2771]
### Expected Behavior

I has download the gravitee-policy-rest-to-soap plug-in to see the code, I download eclipse and open the project in eclipse.

I would like build local the plugin and test if the chenge solve my problem, remove the header content type text/xml fixed in the code, 

but the eclipse report a error in pom.xml below

[INFO] Scanning for projects...
[INFO] Downloading from : https://repo.maven.apache.org/maven2/io/gravitee/gravitee-parent/15/gravitee-parent-15.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for io.gravitee.policy:gravitee-policy-rest-to-soap:1.7.0-SNAPSHOT: Could not transfer artifact io.gravitee:gravitee-parent:pom:15 from/to central (https://repo.maven.apache.org/maven2): Failed to connect to repo.maven.apache.org/151.101.204.215:443 and 'parent.relativePath' points at wrong local POM @ line 30, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project io.gravitee.policy:gravitee-policy-rest-to-soap:1.7.0-SNAPSHOT (C:\Users\lumello\Downloads\gravitee-policy-rest-to-soap-master\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for io.gravitee.policy:gravitee-policy-rest-to-soap:1.7.0-SNAPSHOT: Could not transfer artifact io.gravitee:gravitee-parent:pom:15 from/to central (https://repo.maven.apache.org/maven2): Failed to connect to repo.maven.apache.org/151.101.204.215:443 and 'parent.relativePath' points at wrong local POM @ line 30, column 13: Connection refused: connect -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

### Steps to Reproduce (for bugs)

1.in a machine with windows 7 install jdk8, download eclipse and the plugin gravitee-policy-rest-to-soap
2. import the folder as eclipse project
3. in eclipse try build
4. see the error in pom.xml

### Context

the component keep fix the header text/xml e this header broke the soap api, I need remove this content-type header but it is hard code in the plugin

I already locate the line code with these content type fix and need remove e build and test if these solution will work.

### Your Environment

* Version used:
* Browser Name and version:
* Operating System and version:

windows 7
jdk 8
eclipse
no other java tools or utillities (here we not use java)

thank you

**Comment by NicolasGeraud** [comment]
The answer is in the question : 
`Failed to connect to repo.maven.apache.org/151.101.204.215:443 and 'parent.relativePath' points at wrong local POM @ line 30, column 13: Connection refused: connect`
