### ISSUE TITLE
[AM] Delete role assigned to user, not remove role array from user profile

### ISSUE THREAD

**Issue by jaimesf** [gravitee-io/issues#2775]
At the moment of delete a role, that has users assigned, role from user profile (/management/domains/<domain-name>/users/<id-user>) obtained through api management (UI use this api) is not removed from roles array. 

This assigned role persist on user info in the database after delete the role.

### Expected Behavior
Delete a role, must be removed from role array user profile obtained via API management.

### Possible Solution
Delete role assignment on cascade on users role

### Steps to Reproduce (for bugs)
1. Create a role
2. Create a user
3. Assign role to user
4. Delete role
5. Get user profile from API management
6. Role id it's still on roles array

### Your Environment
* Version used: 2.9.2
* Browser Name and version: Chrome stable version
* Operating System and version: Windows 10 pro

**Comment by lazki** [comment]
I can confirm this issue is fixed in AM 2.10.13.
@brasseld perhaps someone should close it.

**Comment by tcompiegne** [comment]
👍
