### ISSUE TITLE
[portal] Use firstname and lastname for each user instead of the member's ID

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#28]
Currently, the API owner and the members are print using the user ID.
Please change this to use their firstname, lastname and, if possible, their mail address.

**Comment by aelamrani** [comment]
Is this issue is still relevant? If yes, on which part?

**Comment by brasseld** [comment]
YEs it !

API > History
API > Events
API > Members
API Header

Application Header
Application > Members
