### ISSUE TITLE
[management] Pod management-api fall in status CrashLoopBackOff with PostgreSQL

### ISSUE THREAD

**Issue by yoba730** [gravitee-io/issues#2801]
### Current Behavior

I'm having some troubles with the version 1.25.11 of gravitee, I deployed gravitee on Openshift with the postgreSQL:9.6 instead of mongoDB no problems so far. But since I made the update from version 1.22.1 to version 1.25.11 it happens very often that the pod of management API fall in status CrashLoopBackOff.I find in the gravitee database the table databechangeloglock (used by the luiquidebase) which is note emty. I have to clean the table in order for the pod to run again.
### Your Environment

* Version used: gravitee1.25.11
* OpenShift version: v3.10.0 OKD 
* Postgresql version: 9.6

**Comment by brasseld** [comment]
> The root cause was that some changesets with some sql statements took a very long time for execution and was accidentaly aborted. Then on the next time when liquibase was to execute the same changesets, the previous lock was held.

You probably have had some issues while upgrading from 1.22.x to 1.25.x?

**Comment by yoba730** [comment]
I was in version 1.22.1 with mongoDB then I started from scratch with the version 1.25.11 and postgresql 9.6 instead of mongo with an empty database.

**Comment by brasseld** [comment]
Hi @yoba730 

You can disable liquibase while starting the management-api to avoid such issue.
