### ISSUE TITLE
JWT http_status_code:401

### ISSUE THREAD

**Issue by ipirva** [gravitee-io/issues#2807]
### Expected Behavior
JWT successful verification

### Current Behavior
I would need your help to figure out what is happening on my environement.

I have an API with a Plan Authentication JWT / RS512 / GIVEN_KEY / Resolver parameter= ssh-rsa xxx a@b:
curl -i https://host/track -H "Authorization: Bearer ${token}"
always gives http_status_code:401 I am able to verify the signature of the JWT token on jwt.io

If I change the claims inside the JWT token, like for example "exp" , Gravitee Logs traps this => "Expired JWT"

If I use a Keyless Plan
curl -i https://host/track -H "Authorization: Bearer ${token}"  will give http_status_code:401
curl -i https://host/track will succeed

http_status_code:401 is sent by Gravitee, I get no access/error logs on the backend

### Your Environment
Docker / Gravitee:latest

**Comment by aelamrani** [comment]
@ipirva Did you subscribe to this plan? If yes, can you share an example of a valid JWT?

**Comment by ipirva** [comment]
Hi @aelamrani  yes, I did subscribe to the plan. 
I would expect Gravitee to validate this JWT and to access the backend.
Here is a valid JWT:
`eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJzdWIiOiJlbmRwb2ludCIsImNsaWVudF9pZCI6ImVuZHBvaW50IiwiaXNzIjoiand0IHByb3h5IiwiYXVkIjoid3NnaSBwcm94eSIsInJvbGVzIjpbInB1Ymxpc2hlciJdLCJpYXQiOjE1NzIxOTc2MDksIm5iZiI6MTU3MjE5NzU3OSwiZXhwIjoxNTcyMTk3OTA5LCJqdGkiOiJlMzkxODk0Yy1mOGRmLTExZTktYjk1MS0wMjQyMGFmZjAyNGQifQ.ZGu1X4K76HvD5CTo8LHy8mP3TniVII4AUe0VD9UstLMxmVWFMLas2BgDEQ-hy8Slj8lqQlBrgzywcGWD0kas_YuK-7QIF__gUVghvVbd0UYNIdZPvD0488FyKT0J2IVXOSk2WuepVkz3M0nd44usWNCLK2snPOwJihm5GPurYSaC9SNr-MUCvkessuIvLYXu5zUyjdUldbpTdvL2BlSbvLNLthqZzVoJ-Yv0CttT7hmHYYRWUpdFjCpdwIxy3Nh_-7-gVEnI6LMqNbmEMTr32SeXyzP24vlAFeQBHp3F_CPCbroYL4uicFD0BHaYwNqF3cYtZg8Fm4oJpONGcb9nQaKT_Ee7BpAXC_y3dbG35B4T72yABpweRKKm6jwcWhP-s79ITtfrSBNO8ruVxIVjG0wYFMi23NI_XCkdMSepsjmZvpMUpJrlLgtSXDBC8P1XcIm86QViEOFEMA_2dj7gYD4ebN46fNjWC9dVNeKhXeBuZi3MSEE29m178-0C6GT1w98qXsGHrpl-Ua4xzK2B5ZWaNDM9kS_KvWrpcz-wdjDcrDJQj6LImjOXYum0phH5cxLpaBCu2Vn3Q0n-DnNCM0cAC8d-i7Dk6CTLgrj1feAbQdFOD7PhGVtWhK4_xdkAYPZSvkWpDE1Jp4rD3NM4prDpxYjM4SLuXVVEGIAd47c`

**Comment by aelamrani** [comment]
Is the client ID configured on your application 'wsgi proxy'?

**Comment by ipirva** [comment]
Yes, under the application's "OAuth2 Integration" section, "Client ID" is set to "endpoint". "Subscribe to APIs" correctly shows my API and its JWT Plan

**Comment by aelamrani** [comment]
Ok, can you please try to change the client id configured on this application to « wsgi proxy »

**Comment by ipirva** [comment]
Thank you @aelamrani , it worked w\ « wsgiproxy », no space. Thank you for your help!
