### ISSUE TITLE
[kubernetes] Expose Gravitee.io repository for Helm charts

### ISSUE THREAD

**Issue by achaussier** [gravitee-io/issues#2808]
### Request
Expose an Helm repository for Gravitee charts to have an easier management for them.

### Current workaround
Need to clone repository or link it to a custom one.

### Possible solution
Use Github pages to provide a repository, see [this article](https://medium.com/@mattiaperi/create-a-public-helm-chart-repository-with-github-pages-49b180dbb417).

Thanks

**Comment by brasseld** [comment]
https://helm.gravitee.io

**Comment by achaussier** [comment]
Thanks,

Quick deployment and working well ;)

Have a nice day

**Comment by brasseld** [comment]
Great, thanks for your feedback !
