### ISSUE TITLE
[gateway] Fail to maintain websocket connection working with socket.io

### ISSUE THREAD

**Issue by jaimesf** [gravitee-io/issues#2812]
Working with socket.io, gateway can not manage connections

Client can connect, but not maintain connection, if request to gateway it's wss and endpoint is ws, adding Upgrade, and Connection headers to ws endpoint.

### Expected Behavior
Maintain connection with websocket

### Current Behavior
Websocket connection cat not transfer any data

**Comment by brasseld** [comment]
Not able to reproduce after https://github.com/gravitee-io/issues/issues/2811
