### ISSUE TITLE
[management] Analytics filters not preserved when filtering on specific values

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#2814]
Filter on host `127.0.0.1:8082`

![Capture d’écran 2019-10-28 à 17 14 33](https://user-images.githubusercontent.com/133094/67696553-645a3980-f9a7-11e9-93cf-6e71913614a3.png)

Refresh the page, `127.0.0.1:8082` is now `127.0.0.1`

![Capture d’écran 2019-10-28 à 17 14 44](https://user-images.githubusercontent.com/133094/67696562-67edc080-f9a7-11e9-8094-7bb0f2307284.png)

**Comment by gaetanmaisse** [comment]
Closing as the bug looks to be fixed in the current version.
