### ISSUE TITLE
[gateway] WebSocket opening handshake timed out

### ISSUE THREAD

**Issue by adrien-thebault** [gravitee-io/issues#2818]
I need to access a websocket through Gravitee which, according to recent patch notes, should work but I can't make it work. 

With version 1.28.4 I faced an exception so I upgraded to 1.29.5 (and then to nightly) where it still does not work but doesn't give an error either, the handshake between my front application and the gateway times out.

I tried with a ws:// endpoint, a http:// endpoint, I tried multiple versions of Gravitee, I enabled websockets in gravitee.yml but still, while Gravitee's web UI reports that it's working correctly
![image](https://user-images.githubusercontent.com/13251250/67794126-6d690a80-fa7c-11e9-937c-6dd19fbdfaba.png)
Google Chrome does not agree
![image](https://user-images.githubusercontent.com/13251250/67794182-883b7f00-fa7c-11e9-9269-a503be7a754b.png)
And I'm not receiving any data from the websocket

### Expected Behavior
My application should be able to connect to a websocket through Gravitee.

### Current Behavior
Handshake between my application and gravitee times out.

### Steps to Reproduce (for bugs)
1. Have a websocket (mine is a Springboot Websocket)
2. Expose it through Gravitee
3. Try to connect using any websocket client (I tried with StompJS and with a Google Chrome extension called WebSocket Test Client)
4. Wait for the handshake timeout

[TEST-WS-1-0.txt](https://github.com/gravitee-io/issues/files/3785135/TEST-WS-1-0.txt)

### Your Environment

* Version used: 1.29.5 / nightly
* Browser Name and version: Google Chrome 77.0.3865.120 / Firefox Quantum 69.0.2 (64 bits)
* Operating System and version: Windows 10 64bits

 Maybe I'm missing something, like a checkbox somewhere ?

**Comment by brasseld** [comment]
Hey @adrien-thebault 

May I ask you to share a sample spring boot based sample ? I will give a try.

Also, van you confirm that you're not consuming a wss endpoint.

Cheers,

**Comment by jaimesf** [comment]
Same error as https://github.com/gravitee-io/issues/issues/2812 #2812

**Comment by brasseld** [comment]
@jaimesf Not sure you're able to, but did you have a try with the fix provided for https://github.com/gravitee-io/issues/issues/2811 ?

**Comment by adrien-thebault** [comment]
> 
> 
> Hey @adrien-thebault
> 
> May I ask you to share a sample spring boot based sample ? I will give a try.
> 
> Also, can you confirm that you're not consuming a wss endpoint.
> 
> Cheers,

I can confirm it is not a wss endpoint. I'll provide a springboot sample, meanwhile you can try with the sample `TEST-WS-1-0.txt` provided which will use ws://demos.kaazing.com/echo as the endpoint.

**Comment by jaimesf** [comment]
> @jaimesf Not sure you're able to, but did you have a try with the fix provided for #2811 ?

This fix is included in last version released 1.29.5? I'll test it when available.

**Comment by brasseld** [comment]
It will be available as part of the next 1.29.5, right.

**Comment by adrien-thebault** [comment]
https://github.com/adrien-thebault/sample-springboot-ws
Here you can find a quick (and mostly dirty) sample of a Springboot websocket and two NodeJS clients (one is consuming the websocket directly, the other through gravitee).

**Comment by brasseld** [comment]
I just had a try and sounds ok for me....

**Comment by adrien-thebault** [comment]
> 
> 
> @adrien-thebault
> 
> I had a try and it works well, so I'm pretty sure websocket support is not enabled for the gateway:
> 
> Please check https://github.com/gravitee-io/gravitee-gateway/blob/master/gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml#L35

So I tried from a fresh install and now everything works, looks like it was indeed on my end. Sorry!

**Comment by brasseld** [comment]
No worries !

Thanks a lot for your feedback!
