### ISSUE TITLE
[gateway] Policy OAuth2 in new path don't work?

### ISSUE THREAD

**Issue by Archi-Blair** [gravitee-io/issues#2823]
Hello!
Cannot apply policy OAuth2 when adding a new path for a service other than the root path.

![image](https://user-images.githubusercontent.com/46163949/67927486-c4c8c100-fbc9-11e9-8436-85d5be8041e1.png)

Or am I setting it up wrong?

**Comment by brasseld** [comment]
Please provide more info about the context you're running.

Gravitee.io version
JDK
....

**Comment by brasseld** [comment]
There were an issue in 1.29.0 which have been fixed in 1.29.1 (https://github.com/gravitee-io/issues/issues/2632) 

Please move to an higher version (latest is 1.29.5)

**Comment by Archi-Blair** [comment]
Thanks a lot!

**Comment by brasseld** [comment]
ok, looking for your feedback once you test it.

**Comment by Archi-Blair** [comment]
Hello!
Everything works perfectly! Thanks again!
