### ISSUE TITLE
[portal] Advanced search on APIs

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#2839]
### Expected Behavior

On the `category` screen, I want to search apis.
I want to add filters to my search.
The result should be the list of apis matching the research.

I should use advanced search as `filter: my_filter,` (github behavior). 
I should be able to use `AND` or `OR` operators in my search.

_Example : 
If i want to search for supply category and john ownership, I'll search for `categories: supply AND ownerName: john` and get all the APIs owned by John in the supply category_

An hint is to display below the search bar to empower users. 

### Filters : 
- name
- categories
- labels
- ownerName 
- description

**Comment by aelamrani** [comment]
The need here is to search on a specific category.

We could add the possibility to add filters on search as categories, labels..

**Comment by RubenMMSantos** [comment]
bug raised as part of testing 
https://github.com/gravitee-io/issues/issues/6264#issue-1009703950
