### ISSUE TITLE
[gateway] Improve SSL connection info reporting

### ISSUE THREAD

**Issue by kanischev** [gravitee-io/issues#2841]
This is a proposal for reporting improvement.
There are 2 interactions on API call via API Gateway (with client and with API Provider). Each may come through SSL/TLS connection. There should be the way to log info about SSL Session to reporting.

**Comment by brasseld** [comment]
As far as I understand, the idea here is to report additional data relative to the SSL session.

The best (IMHO) would be to configure the additional attributes (from the ssl session) to report from the `gravitee.yml`

For me, there is absolutely no reason to have a distinct configuration for each API.

WDYT?

**Comment by kanischev** [comment]
Hi, @brasseld!
I'm absolutely support your opinion. SSL-specific reporting should be optional and IMHO is not API-specific.

**Comment by kanischev** [comment]
Hi, @brasseld. I suppose, I'm done. Made 5 PRs to repos:
gravitee-common
gravitee-reporter-api
gravitee-repository
gravitee-elasticsearch
gravitee-gateway

**Comment by brasseld** [comment]
Nice job @kanischev!

I've added some comments to PRs.

I have an additional question: for the moment, SSL session informations will only be available when logging is enable.
I'm just thinking if it make senses to put some of these information into the `Request reportable` element for the incoming request without having to enable logging feature.
I'm thinking about local-principal, peer-principal and protocol.

WDYT?

**Comment by kanischev** [comment]
Thank you, @brasseld 
Will check comments today (already, huh)
I'm afraid there is a big peace of work to be done on audit (#2751 issue) and all that info should be in audit record. Wouldn't it be a better solution? WDYT?

**Comment by brasseld** [comment]
Sorry, but I did not get you about #2751 issue.

This is not relative to the current issue, or I'm missing something?

**Comment by kanischev** [comment]
I suppose,  #2751 issue relates to your previous question. It suggests to split Log and Audit information of the whole request-response gateway lifecycle. Ssl connection info is about audit I suppose - I'd put it there. And it looks like I'll work on this issue in the nearest future as it is quite critical for us. WDYT?

**Comment by brasseld** [comment]
By Audit, you mean request metrics ?

**Comment by brasseld** [comment]
Let's think this way: if you put ssl informations into request metrics, you'll be able to create a new analytics dashboard / widget.
It would not be possible is you're relying on log.

Do you see what I mean?

**Comment by kanischev** [comment]
Ok. I see what you mean. Will update PRs.

**Comment by brasseld** [comment]
I don't pretend I'm right :)

And perhaps it's more easier to store all SSL infos within the `Logs` instead of `Request metrics`.

But by storing into logs, you will not being able to use analytics dashboards for SSL info

**Comment by kanischev** [comment]
Added info to metrics. Added LogConfig builder. Fixed mappings and templates for Elastic records.

**Comment by brasseld** [comment]
@kanischev I've done the latest reviews for common and rest-api.

All is working fine.

Just to be sure: there is no PR for webui, am I right?
