### ISSUE TITLE
[repository] [redis] dictionary properties not saved

### ISSUE THREAD

**Issue by loriepisicchio** [gravitee-io/issues#2845]
### Expected Behavior
When saving properties to a dictionary, the properties should be saved and displayed in the UI

### Current Behavior
When adding properties, they are well listed in the Properties field, but as soon as we click on "Save Properties" button, the properties disappear and they are not saved in the database.
This behavior also impacts dynamic dictionaries, as properties are not saved by triggered action either.

### Possible Solution
No idea how to fix, but as suggested by @aelamrani adding a test for property saving in [DictionaryRepositoryTest](https://github.com/gravitee-io/gravitee-repository-test/blob/1e33b173e7393246d6478afbcdd36ca5f6bd4e82/src/test/java/io/gravitee/repository/DictionaryRepositoryTest.java#L30) might be a good idea

### Steps to Reproduce (for bugs)
1. Install gravitee with gravitee-repository-redis plugin
2. Configure gravitee to use redis for persistence
3. Start gravitee full
4. Go to management ui
5. Create a new manual dictionary
6. Create a new property in this dictionary
7. Click on "SAVE PROPERTIES" button

### Context
I was trying to create a dynamic dictionary and didn't get why my properties were not saved. So I tried to create a manual one, and found out that behavior was the same

### Your Environment
* Version used: graviteeio-full-1.29.5 | gravitee-repository-redis-1.29.1
* Browser Name and version: Chromium Version 77.0.3865.90 
* Operating System and version: Fedora 29

**Comment by tzepterbvv** [comment]
Problem occurs also in full 1.30.8. Work-around is remove the attribute and create it new. Not nice.

**Comment by brasseld** [comment]
Hi @tzepterbvv 

You're running Redis repository also ?

**Comment by tzepterbvv** [comment]
No, of course not. Sorry! I use mongodb.
So the problem seems to be database agnostic?

**Comment by gaetanmaisse** [comment]
Closing as this bug looks to be fixed in the current version of APIM
