### ISSUE TITLE
Problem with assign content policy

### ISSUE THREAD

**Issue by fborghi** [gravitee-io/issues#2858]
After dynamic routing response i cant't take response fields to create the xml response

### Steps to Reproduce (for bugs)
1.Make a post request with json response
2.Try to use the response to build an xml response using `<#assign body = response.content?eval >`

When i try to use the response body with `${body.userId}` i get the error: `Unable to assign body content: The following has evaluated to null or missing:\n==> body.userId  [in template \"1b5f8188acfd83437f1fe2591227338440589f73\" at line 4, column 15]\n\n----\nTip: It's the step after the last dot that caused this error, not those before it.\n----\nTip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??\n----\n\n----\nFTL stack trace (\"~\" means nesting-related):\n\t- Failed at: ${body.userId}  [in template \"1b5f8188acfd83437f1fe2591227338440589f73\" at line 4, column 13]\n----`

**Comment by aelamrani** [comment]
@fborghi Did you have a check to documentation ? https://docs.gravitee.io/apim_policies_assign_content.html
