### ISSUE TITLE
Assign attributes doesn't work

### ISSUE THREAD

**Issue by fborghi** [gravitee-io/issues#2861]
The assign attribute policy seems doesn't work

### Expected Behavior
using 
`"assign-attributes": {
    "attributes": [
        {
            "name": "id,
            "value": "{#request.headers['id']}"
        }
    ]
}`

I'm try to use `context.attributes['id']` as body parameter in assign content but it hasn't the expected value

**Comment by aelamrani** [comment]
Hello @fborghi, you mix 2 policies: `Assign Attributes` and `Assign Content`

Attention, the first is used to assign attributes in the execution context (to be used later in another policy) and the second is useful to provide a template on the contents of request / response.

So, if I understand correctly, you are trying to put a header in the payload content of the request.

To do this, you must use the `Assign Content` policy and set the configuration below:

```
<#assign id = request.headers.id[0]>
{
"id": "${id}"
}
```

I hope it's useful.

**Comment by fborghi** [comment]
Maybe i don't expose you the problem properly.
I've to get a path value to use in another request body

**Comment by aelamrani** [comment]
Ok give an complete example with the URL called and the expected body i will provide the solution here.

**Comment by aelamrani** [comment]
Anyway, if you need to get path data the principle is the same:
```
<#assign path = request.paths[1]>
{
  "path": "${path}"
}
```

You can take a look at the documentation to get the correct syntax: https://docs.gravitee.io/apim_publisherguide_expression_language.html
