### ISSUE TITLE
Gravitee Access Management Server Error

### ISSUE THREAD

**Issue by Ic3p3ak** [gravitee-io/issues#2864]
I started nginx, gateway and api management and I connect to the ui. But when the Website is loaded i get an "Server Error" Message and infinite loading circles.
Or Internet Explorer/Edge i just see a dark screen with the Gravitee Logo.
How can i Fix this?

### Your Environment

* Version used: 2.9.2
* Browser Name and version: Chrome, Internet Explorer/Edge and Firefox
* Operating System and version: CentOS 7

**Comment by tcompiegne** [comment]
Hi @Ic3p3ak , did you update the `constants.json` file to set the API Management url ? (default is localhost:8093/management)
