### ISSUE TITLE
After upgrading to 1.29.6 from 1.29.5 I can't see any API details

### ISSUE THREAD

**Issue by yazalulloa** [gravitee-io/issues#2871]
After I upgraded Gravitee APIM to 1.29.6 I can't see the details of any API I created before I upgraded, the http request returns Internal Server Error.

The gateway works fine though

I'm running Gravitee APIM 1.29.6 with MongoDB 3.4 and Elasticsearch 5.4.3 in docker

Here's the log:

[gravitee.log](https://github.com/gravitee-io/issues/files/3838712/gravitee.log)

Here's the look from the UI
![image](https://user-images.githubusercontent.com/33322056/68720457-aa0d2980-0585-11ea-8608-761ad0329c0c.png)

**Comment by aelamrani** [comment]
Hi @yazalulloa 

According to the logs, you are trying to start a 1.25.x on a database which has been started on a highest version. That's why this is not working properly.

**Comment by yazalulloa** [comment]
> Hi @yazalulloa
> 
> According to the logs, you are trying to start a 1.25.x on a database which has been started on a highest version. That's why this is not working properly.

Sorry I messed up the title, I upgraded Gravitee APIM from 1.29.5 to 1.29.6

**Comment by aelamrani** [comment]
I don't understand, you are starting a version 1.25.x of Gravitee.io according to your log file...

**Comment by yazalulloa** [comment]
Well I pulled the latest docker image, could it be that the image has the wrong version

**Comment by yazalulloa** [comment]
I think the latest docker image for the management-api is not the 1.29.6

![image](https://user-images.githubusercontent.com/33322056/68768240-8c2cdc80-05f8-11ea-917c-3d4d51be9536.png)

**Comment by yazalulloa** [comment]
I specified the 1.29.6 version and everything worked fine, thanks

**Comment by aelamrani** [comment]
Thanks for reporting this, it should be OK now
