### ISSUE TITLE
Validate request 

### ISSUE THREAD

**Issue by aliFetvaci61** [gravitee-io/issues#2872]
Is there any example validate Request uri param  max character parameters? @aelamrani

**Comment by aelamrani** [comment]
Hi @aliFetvaci61 

You will find documentation about the use of this policy here: https://docs.gravitee.io/apim_policies_request_validation.html

More information about expression language here: https://docs.gravitee.io/apim_publisherguide_expression_language.html

So, your need is to check the size of a path parameter. 

Let's check that the first path param's length is between 0 and 10:

<img width="637" alt="Capture d’écran 2019-11-13 à 08 33 56" src="https://user-images.githubusercontent.com/1580262/68742508-a1057200-05f0-11ea-9683-1d85beada231.png">
