### ISSUE TITLE
API call resolved-path using in groovy script

### ISSUE THREAD

**Issue by aliFetvaci61** [gravitee-io/issues#2873]
How can I use resolved path in request context at groovy script @aelamrani

**Comment by aelamrani** [comment]
Hi @aliFetvaci61 

You should be able to access to the path by using `request.path` in your groovy script.

**Comment by aliFetvaci61** [comment]
I want to get red part in the paths when API call in groovy Script .
request.path is like that    /1234/transactionId/45621 
But I want this path  -->>   /:accountId/transactions/:transactionId  I can not Find in groovy script

**Comment by aelamrani** [comment]
This information is not available on the execution context
