### ISSUE TITLE
How can I validate request body (JSON) 

### ISSUE THREAD

**Issue by aliFetvaci61** [gravitee-io/issues#2874]
Validate Request Policy Definition

![image](https://user-images.githubusercontent.com/16122994/68759538-f22d5a00-0620-11ea-96bd-1033f1ba96e8.png)

Request Body

{"isExistingNextPage":"false","date":"10/10/2019"}

**Comment by aliFetvaci61** [comment]
![image](https://user-images.githubusercontent.com/16122994/68763093-ada5bc80-0628-11ea-91e0-9a621123122c.png)

**Comment by aliFetvaci61** [comment]
![image](https://user-images.githubusercontent.com/16122994/68763139-c910c780-0628-11ea-8e8c-76e4eaa0bc87.png)

**Comment by aelamrani** [comment]
Hi @aliFetvaci61 

Another solution would be to use the JSON Validation Policy https://docs.gravitee.io/apim_policies_json_validation.html

For your example, you would define something like this:

```
{
  "properties" : {
    "isExistingNextPage" : {
      "type" : "string",
      "enum" : [ "true", "false" ]
    },
    "date" : {
      "type": "string",
      "pattern": "^([0-2][0-9]|(3)[0-1])(\/)(((0)[0-9])|((1)[0-2]))(\/)[0-9]{4}$"
    }
  }
}
```

**Comment by aliFetvaci61** [comment]
Thanks @aelamrani nice Solution

**Comment by aelamrani** [comment]
You are welcome.
The schema is based on JSON schema spec: https://json-schema.org/.

There is some tools online to test your schema with your inputs like:
- https://www.jsonschemavalidator.net/
- https://json-schema-validator.herokuapp.com/
