### ISSUE TITLE
API input transfer from JSON to JSON with XML

### ISSUE THREAD

**Issue by Subbu0117** [gravitee-io/issues#2876]
The application is posting JSON object which I need to convert to XML and then add to "ReqBody" in JSON as given below in a sample. is there any option in Gravitee to convert input JSON before posting to endpoint? Here is an example:

Input:
```

{

  "DocumentSummary": {
     "IssuedDateTime": "29012017204104"
  }
}
```

Output to be posted to end point:
```

{
"ReqHeader": {
"Channel_ID": "ABX",
"Service_ID": "10111",
"Request_ID": "233111222",
"Request_Date": "20190423"
},
"ReqBody": {
"XML": "
<?xml version="1.0" encoding="UTF-8"?>
<DocumentSummary>
<IssuedDateTime>29012017204104</IssuedDateTime>
</DocumentSummary>"
}
}
```

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Version used:
* Browser Name and version:
* Operating System and version:

**Comment by aelamrani** [comment]
Hi @Subbu0117 

You should be able to do such thing with the Assign Content Policy: https://docs.gravitee.io/apim_policies_assign_content.html

According to your example, this should work:

```
<#assign body = request.content?eval >
{
    "ReqHeader": {
        "Channel_ID": "ABX",
        "Service_ID": "10111",
        "Request_ID": "233111222",
        "Request_Date": "20190423"
    },
    "ReqBody": {
        "XML": "<?xml version="1.0" encoding="UTF-8"?>
        <DocumentSummary>
          <IssuedDateTime>${body.DocumentSummary.IssuedDateTime}</IssuedDateTime>
        </DocumentSummary>"
    }
}
```

**Comment by Subbu0117** [comment]
Thank you @aelamrani . Let me give a try and get back.

**Comment by Subbu0117** [comment]
@aelamrani,  Above your suggestion helped when we have a simple transformation of the request body. but I checked a few requests which are having complex XML with repeated XML child tags. Please suggest how to achieve such a scenario.

example:
```
<XML>
  <DocumentExchangeDetails>
         <ReceivingPartyDetails>
            <ReceivingParty>a</ReceivingParty>
            <ReceivingParty>a</ReceivingParty>
         </ReceivingPartyDetails>
         <NotifyPartyDetails>
            <NotifyParty>a</NotifyParty>
            <NotifyParty>a</NotifyParty>
         </NotifyPartyDetails>
  </DocumentExchangeDetails>
  <DocumentDetails>
      <ContainersDetails>
         <Container>
            <VCN>a</VCN>
            <IMONumber>a</IMONumber>
            <CallSign>a</CallSign>
		</Container>
		  <Container>
            <VCN>b</VCN>
            <IMONumber>a</IMONumber>
            <CallSign>a</CallSign>
		</Container>
		  <Container>
            <VCN>c</VCN>
            <IMONumber>a</IMONumber>
            <CallSign>a</CallSign>
		</Container>
		  <Container>
            <VCN>d</VCN>
            <IMONumber>a</IMONumber>
            <CallSign>a</CallSign>
		</Container>
	 </ContainersDetails>
    </DocumentDetails>
</XML>
```

Thank you

**Comment by aelamrani** [comment]
Please give a complete example with the input and the expected output.

**Comment by Subbu0117** [comment]
Actually we have many API which we need to transform both for request and response . Here is an example for posting body to  Endpoint . same need to transformed for response .
```
{
  "ReqHeader": {
    "Channel_ID": "IndianPCS",
    "Service_ID": "1172",
    "Request_ID": "233111111",
    "Request_Date": "20190423"
  },
  "ReqBody": {
<?xml version="1.0" encoding="UTF-8"?>
<ContainerreportDetails>
   <DocumentHeader>
      <DocumentReference>
         <DocumentType>COEDOR</DocumentType>
         <DocumentName>Containe Stock Report</DocumentName>
         <DocumentNumber>343434</DocumentNumber>
         <CommonRefNumber>20070708121</CommonRefNumber>
         <MessageType>9</MessageType>
         <SenderID>ptuser10</SenderID>
      </DocumentReference>
      <DocumentExchangeDetails>
         <ReceivingPartyDetails>
            <ReceivingParty>a</ReceivingParty>
            <ReceivingParty>a</ReceivingParty>
         </ReceivingPartyDetails>
         <NotifyPartyDetails>
            <NotifyParty>a</NotifyParty>
            <NotifyParty>a</NotifyParty>
         </NotifyPartyDetails>
      </DocumentExchangeDetails>
   </DocumentHeader>
   <DocumentDetails>
      <ContainersDetails>
         <Container>
            <VCN>a</VCN>
            <IMONumber>a</IMONumber>
            <CallSign>a</CallSign>
            <VoyageNumber>a</VoyageNumber>
            <EquipmentStatusCode>a</EquipmentStatusCode>
            <IGMNumber>1</IGMNumber>
            <IGMDate>01011800</IGMDate>
            <IGMLineNo>1</IGMLineNo>
            <IGMSubLineNo>1</IGMSubLineNo>
            <RotationNumber>1</RotationNumber>
            <RotationNumberDate>01011800</RotationNumberDate>
            <CACode>a</CACode>
            <ContLineCode>a</ContLineCode>
            <CFSPortCode>aaaaa</CFSPortCode>
            <DestinationCode>aaaaa</DestinationCode>
            <ReportReceiptDate>01011800</ReportReceiptDate>
            <ContainerNumber>a</ContainerNumber>
            <ContISOCode>a</ContISOCode>
            <ContClassificationCode>a</ContClassificationCode>
            <ReceiptDateTime>01011800:00:00</ReceiptDateTime>
            <ArrivalDateTime>01011800:00:00</ArrivalDateTime>
            <ContPendingDays>a</ContPendingDays>
            <YardLocation>a</YardLocation>
            <ContainerBay>a</ContainerBay>
            <ContainerRow>a</ContainerRow>
            <ContainerStack>a</ContainerStack>
            <Tier>a</Tier>
         </Container>
         <Container>
            <VCN>a</VCN>
            <IMONumber>a</IMONumber>
            <CallSign>a</CallSign>
            <VoyageNumber>a</VoyageNumber>
            <EquipmentStatusCode>a</EquipmentStatusCode>
            <IGMNumber>1</IGMNumber>
            <IGMDate>01011800</IGMDate>
            <IGMLineNo>1</IGMLineNo>
            <IGMSubLineNo>1</IGMSubLineNo>
            <RotationNumber>1</RotationNumber>
            <RotationNumberDate>01011800</RotationNumberDate>
            <CACode>a</CACode>
            <ContLineCode>a</ContLineCode>
            <CFSPortCode>aaaaa</CFSPortCode>
            <DestinationCode>aaaaa</DestinationCode>
            <ReportReceiptDate>01011800</ReportReceiptDate>
            <ContainerNumber>a</ContainerNumber>
            <ContISOCode>a</ContISOCode>
            <ContClassificationCode>a</ContClassificationCode>
            <ReceiptDateTime>01011800:00:00</ReceiptDateTime>
            <ArrivalDateTime>01011800:00:00</ArrivalDateTime>
            <ContPendingDays>a</ContPendingDays>
            <YardLocation>a</YardLocation>
            <ContainerBay>a</ContainerBay>
            <ContainerRow>a</ContainerRow>
            <ContainerStack>a</ContainerStack>
            <Tier>a</Tier>
         </Container>
		 
      </ContainersDetails>
   </DocumentDetails>
   <DocumentSummary>
      <IssuedDateTime>01011800000000</IssuedDateTime>
   </DocumentSummary>
</ContainerreportDetails>
}
}
```

**Comment by aelamrani** [comment]
Please provide input...

**Comment by Subbu0117** [comment]
Actually We have many APIs which is having a similar conversion for request and response with different values. kindly help with a solution in gravitee.   Thank you!

Here is on input JSON for the API:

{
 "ReqHeader": {
    "Channel_ID": "IndianPCS",
    "Service_ID": "1172",
    "Request_ID": "233111111",
    "Request_Date": "20190423"
  },
   "ContainerreportDetails": {
      "DocumentHeader": {
         "DocumentReference": {
            "DocumentType": "COEDOR",
            "DocumentName": "Containe Stock Report",
            "DocumentNumber": "343434",
            "CommonRefNumber": "20070708121",
            "MessageType": "9",
            "SenderID": "ptuser10"
         },
         "DocumentExchangeDetails": {
            "ReceivingPartyDetails": {
               "ReceivingParty": [
                  "a",
                  "a"
               ]
            },
            "NotifyPartyDetails": {
               "NotifyParty": [
                  "a",
                  "a"
               ]
            }
         }
      },
      "DocumentDetails": {
         "ContainersDetails": {
            "Container": [
               {
                  "VCN": "a",
                  "IMONumber": "a",
                  "CallSign": "a",
                  "VoyageNumber": "a",
                  "EquipmentStatusCode": "a",
                  "IGMNumber": "1",
                  "IGMDate": "01011800",
                  "IGMLineNo": "1",
                  "IGMSubLineNo": "1",
                  "RotationNumber": "1",
                  "RotationNumberDate": "01011800",
                  "CACode": "a",
                  "ContLineCode": "a",
                  "CFSPortCode": "aaaaa",
                  "DestinationCode": "aaaaa",
                  "ReportReceiptDate": "01011800",
                  "ContainerNumber": "a",
                  "ContISOCode": "a",
                  "ContClassificationCode": "a",
                  "ReceiptDateTime": "01011800:00:00",
                  "ArrivalDateTime": "01011800:00:00",
                  "ContPendingDays": "a",
                  "YardLocation": "a",
                  "ContainerBay": "a",
                  "ContainerRow": "a",
                  "ContainerStack": "a",
                  "Tier": "a"
               },
               {
                  "VCN": "a",
                  "IMONumber": "a",
                  "CallSign": "a",
                  "VoyageNumber": "a",
                  "EquipmentStatusCode": "a",
                  "IGMNumber": "1",
                  "IGMDate": "01011800",
                  "IGMLineNo": "1",
                  "IGMSubLineNo": "1",
                  "RotationNumber": "1",
                  "RotationNumberDate": "01011800",
                  "CACode": "a",
                  "ContLineCode": "a",
                  "CFSPortCode": "aaaaa",
                  "DestinationCode": "aaaaa",
                  "ReportReceiptDate": "01011800",
                  "ContainerNumber": "a",
                  "ContISOCode": "a",
                  "ContClassificationCode": "a",
                  "ReceiptDateTime": "01011800:00:00",
                  "ArrivalDateTime": "01011800:00:00",
                  "ContPendingDays": "a",
                  "YardLocation": "a",
                  "ContainerBay": "a",
                  "ContainerRow": "a",
                  "ContainerStack": "a",
                  "Tier": "a"
               }
            ]
         }
      },
      "DocumentSummary": {
         "IssuedDateTime": "01011800000000"
      }
   }
}

**Comment by aelamrani** [comment]
Ok now i understand well your need, and you will not be able to do such things with the Assign Content Policy.

**Comment by Subbu0117** [comment]
is there any alternative?  I see an option called Groovy.   Not sure it will solve our purpose.

**Comment by brasseld** [comment]
@Subbu0117 the easiest way to go for you would be to implement your own policy.

**Comment by Subbu0117** [comment]
@aelamrani , @brasseld , Thank you for the suggestion.

**Comment by aelamrani** [comment]
You are welcome
