### ISSUE TITLE
[management] Bug during saving API policy in UI

### ISSUE THREAD

**Issue by brightlizard** [gravitee-io/issues#2881]
### Expected Behavior
Fields should not be mixed up among policies in api definition json.

### Current Behavior
For example given two policies, A and B with some scopes of fields in each other.
There are possible situations then policy B fields goes to policy A and saves into api definition json.

### Possible Solution
On your discretion

### Steps to Reproduce (for bugs)
1. Open "Policies" section in UI.
2. Click on policy A.
3. Change some field.
4. Click on policy B without saving.
5. Click back on policy A and save it.
6. Check api definition. Policy B will have fields from policy A inside api definition json.

### Context
Management UI - 1.27.1

### Your Environment
Firefox 65.0.1 and more
Yandex Browser 18.3.1.1220
didn't check in other browsers

**Comment by brightlizard** [comment]
Hi. What do you think about it?

**Comment by brightlizard** [comment]
@NicolasGeraud what do you thing about it?

**Comment by brasseld** [comment]
Are policy A and policy B the same ?

**Comment by brightlizard** [comment]
Hi!
No, they are different.

**Comment by brasseld** [comment]
I'm not able to reproduce.

May I ask you to record a screencast explaining how you reproduce ? (and show the api definition).

Thanks a lot.

**Comment by brightlizard** [comment]
Sure, but it wil take some time )
