### ISSUE TITLE
Resource Authorization server URL is case sensitive

### ISSUE THREAD

**Issue by bisonfoutu** [gravitee-io/issues#2884]
### Expected Behavior

Resources' authorization server URLs should not be case sensitive

### Current Behavior

Resources' authorization server URLs are case sensitive.
This leads to JWT bearer tokens being processed as invalid (`{"active": false}`) if the URL in the token does not have the same case as the one set in Gravitee.

### Possible Solution

When comparing both URLs, maybe transform both to lower case or upper case to avoid case sensitivity

### Steps to Reproduce (for bugs)

1. Set a resource authorization server URL in upper case
2. Call your Keycloak API with a lower case URL
3. Call your API with the returned JWT as Bearer token

### Context

I was playing with my first API on our Gravitee setup, and trying to call a simple GET endpoint. 
It took me a few hours to find out why my tokens would not be validated when my coworkers could call the API without any issue.

### Your Environment

* Version used: 1.27.0
* Browser Name and version: Google Chrome 78.0.3904.97 (64 bits)
* Operating System and version: Windows 10 Professional build 18362

**Comment by brasseld** [comment]
Hi @bisonfoutu 

I'm not sure we are comparing both URL, I think it's been done by keycloak itself...

**Comment by bisonfoutu** [comment]
Yeah I thought so as I was writing it... Might be worth checking out though.
If you think of anything I could do to at my level to further identify the source of the issue, kindly let me know, I'll be happy to help 😃

**Comment by brasseld** [comment]
Are you asking your Keycloak resource to validate the token locally or remotely ?

**Comment by bisonfoutu** [comment]
I'm not sure of the answer to this question.
Our Keycloak instance is on a separate machine which URL is provided in the resource config.
If you are talking about something else, how can I check it ?

**Comment by brasseld** [comment]
Ok, can you provide an export of your API?

I will have a look.
Also, please let me know about the version of keycloak plugin you're using.

**Comment by bisonfoutu** [comment]
Here's my API's export: [EIM_API-1-0-0.json](https://github.com/gravitee-io/issues/files/3850535/EIM_API-1-0-0.json.txt)

I just had a look through our installed plugins and did not see anything keycloak-related.
From my understanding, we set up a resource using Keycloak as a generic OAuth2 Auth Server Resource.

**Comment by brasseld** [comment]
In that case, it would be likely easier for you to manage your Keycloak Oauth2 resource using a dedicated plugin: https://download.gravitee.io/graviteeio-apim/plugins/resources/gravitee-resource-oauth2-provider-keycloak/

**Comment by bisonfoutu** [comment]
I now have a working setup using this plugin, but I am facing the exact same URL case issue.

So I guess, as you previously said, that the issue is on the Keycloak side.

**Comment by brasseld** [comment]
What I do not understand is why is your URL case-sensitivity different.

I mean, you are exposing keycloak on a given URL, so I would expect to use the same within Gravitee configuration....

**Comment by bisonfoutu** [comment]
It is not an actual technical constraint of any sort, just different developers with different habits. Some of us write URLs in caps, some others don't.

Our internal DNS also allows accessing a machine with or without specifying `.intra` at the end of the URL.

Therefore you could access a same machine by:
- http://dri-dv-app-iam.intra
- http://DRI-DV-APP-IAM.INTRA
- http://dri-dv-app-iam
or any other combination. It gets resolved to the same IP in the end.

I get this is a pretty specific situation, but I'm pretty sure we will not be the only ones facing it.

**Comment by brasseld** [comment]
I would day that, currently, you are.

The "problem" is relative to Keycloak, and not Gravitee itself.
When you're introspecting an endpoint using the check token endpoint from Keycloak, this later is looking into the `Host` header which have to match the one used to generate the initial access_token.
So if you try to check a token from Keycloak using a curl command, and by specifying a given Host, I'm pretty sure you'll face the same behavior :)
