### ISSUE TITLE
Add backend request-time to Metrics

### ISSUE THREAD

**Issue by MariaPushkin** [gravitee-io/issues#2894]
We use Metrics information to log gateway events (client requests, backend requests, backend responses and client responses). And now as I understand Metrics object has no information about backend request time. There is `ApiResponseTimeMs` field, which filld with current time in [ApiReactorHandler.java:handleProxyInvocation](https://github.com/gravitee-io/gravitee-gateway/blob/master/gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java) (probably backend call time?): 

```java
context.request().metrics().setApiResponseTimeMs(System.currentTimeMillis());
```

but after that it replaced by:

```java
context.request().metrics().setApiResponseTimeMs(System.currentTimeMillis() -
                        context.request().metrics().getApiResponseTimeMs());
```

So, we cant know actual backend call time, because it was erased and also backend response time, because `ApiResponseTimeMs` contains only difference beetween erased backend request time and response time, which was not saved anywhere.
So, it would be great to save that value in separate variable (ex: `backendRequestTimeMs`), so we can use it for backend requests time and calculate backend response time with it and `ApiResponseTimeMs`).

Thanks in advance.

**Comment by brasseld** [comment]
Hi @MariaPushkin 

You have `responseTime` (global latency) and `apiResponseTime` (backend latency).

Is it what you're looking for ?

**Comment by MariaPushkin** [comment]
Hi @brasseld 
No, I am looking for request processing latency (time elapsed from receiving request from user to sending the request to API backend) or something which will help to calculate that.

**Comment by brasseld** [comment]
Sorry but I didn't get you.

You're looking to the time took to process request without the time used to process the response ?

**Comment by MariaPushkin** [comment]
Oh, sorry for my confusing explanations, but yes I need time took only to process request on gateway.

**Comment by brasseld** [comment]
I'm probably misunderstanding something here...

We are giving the complete backend processing time, from sending request to backend to getting complete response from it.

So I'm really sorry but I'm still did not get you. Perhaps you can provide a schema to explain a bit more the purpose of the issue?

Thanks

**Comment by MariaPushkin** [comment]
Okay, I will try to explain. We provide detailed logs of 4 events on gateway: 
1. Moment of getting client request 
2. Moment of sending request to backend 
3. Moment of getting response from backend 
4. Moment of sending response back to client 
And our logs should provide time when every event was happen. For the 1 we get timestamp from Metrics, for the 4, we get timestamp in milliseconds + global response time, but time of events 2 and 3 is unknown. 
That's why we need either full datetime of event 2 or request processing time in milliseconds, so we can add it to timestamp and get what we actually need.

**Comment by MariaPushkin** [comment]
Hello, I am just wondering if there any progress with this issue. 
I do not insist, but we need some your desidion to understand whether to wait for one of the future releases with this enhancement or to work on a solution on our side.

**Comment by brasseld** [comment]
Hi Maria,

Sorry for being late on this. I understand the purpose. Unfortunately I would have time to work on this soon as we are already working on other topics.
Also, one of the hot topics for 2020 is to add tracing capabilities to the gateway, so I'm pretty sure it'll cover your need.

**Comment by MariaPushkin** [comment]
Thanks for the answer, I get you.
