### ISSUE TITLE
[management-api] Set log level for LDAP provider

### ISSUE THREAD

**Issue by rannox** [gravitee-io/issues#2908]
Hello,

i am trying to configure the LDAP authentification in the Management API  component and it would be really helpful if i could increase the log level from INFO to DEBUG/TRACE.
I couldn't find any information about increasing the log level in the documentation and setting the JAVA_OPTS to either

- -Dlogging.level.org.springframework.security=TRACE
or
- -Dlogging.level.io.gravitee.rest.api.idp=TRACE

didnt work. 

Best regards

**Comment by brasseld** [comment]
Hi @rannox 

You can still add new logger in logback.xml :
https://github.com/gravitee-io/gravitee-management-rest-api/blob/master/gravitee-rest-api-management/gravitee-rest-api-management-standalone/gravitee-rest-api-management-standalone-distribution/src/main/resources/config/logback.xml#L44

Regards,

**Comment by rannox** [comment]
Thanks! It worked! :)

**Comment by brasseld** [comment]
Ok, may I close the issue ?

**Comment by rannox** [comment]
Yes, you can close the issue :)

**Comment by greg42300** [comment]
Hi,
I would be interested in the answer however the link is dead
Best Regards
