### ISSUE TITLE
[portal] API / application analytics

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#291]
Currently, response time are provided in a classical line chart.
It would be great to use a stacked chart (as its done for response status) to show the gateway overhead vs the API latency.

<img width="690" alt="capture d ecran 2016-11-02 a 15 23 39" src="https://cloud.githubusercontent.com/assets/133094/19932419/62488c16-a110-11e6-9669-874f4ec719c4.png">

**Comment by brasseld** [comment]
Should be fixed after migration to Highcharts : #341

**Comment by aelamrani** [comment]
Closed by https://github.com/gravitee-io/issues/issues/341
