### ISSUE TITLE
Is it possible to have several JWT plans for one API ?

### ISSUE THREAD

**Issue by ftorchet** [gravitee-io/issues#2918]
Hello, here what I try to do :
- I want some suscribers not have access all the paths of my API protected by JWT

I created two JWT plans : one default with no specific policy.
And another with path authorizations.

For test purpose : 2 Applications with a different plan subscription.

The problem : only the first plan seems to be active. 
It seems Gravitee try to use only the first created plan, I a have "invalid signature" for the requests trying to reach my API with the second subscriber (I changed client_id and token signature obviously).
I test to change algorithm to distinguish some stuff : "Another algorithm expected"...

So... Finally, is it possible to have several JWT plans for one API ?

**Comment by aelamrani** [comment]
Hi @ftorchet did you try to use plan's selection to select the correct plan based on a claim?

**Comment by ftorchet** [comment]
Thanks for help !

I effectively tried to add a selection rule based on a claim (sub claim actually) without any effect.

**Comment by brasseld** [comment]
It's a bit hard to manage JWT plan based on the `sub` claim, because it mainly depends on the number of end-users.

Why are you looking to define selection rule based on this user claim ?

**Comment by ftorchet** [comment]
I agree, It was just a test to see if I could force the plan selection.
I would prefer not to add such a selection rule. The fact is even with this selection rule, Gravitee never chose the second plan...

I don't know if I was clear : I have 2 JWT plans (with 2 secrets), 2 applications and each application subscribed on a single plan (Application A subscribed to plan 1, Application B subscribed to plan 2)
Plan 1 was created first. No problem for application A, access granted to my API.
No way for application B : 401 (invalid signature in the logs). 

I've made an other test : same secret on the 2 plans... Yes !!! OK, Gravitee not complain about invalid signature and recognize the good plan and filter the paths !

So the point is : I must define the same secret on the two JWT plans... Not a really good news for security. What did I miss ?

**Comment by brasseld** [comment]
If you have multiple JWT plans, the only way to go is by defining `selection rule`.

We are using them for many use-cases without problem.

**Comment by ftorchet** [comment]
Hmm, OK, I think, my mistake was a selection rule defined only on the plan 2 !

If I define a selection rule on the 2 plans I haven't invalid signature anymore.
However I can't acces my API yet... Probably a problem on the rule syntax. 
{#context.attributes...} or #context.attributes ?

In any case, thanks for your help ! 
(Change algorithm will be my next step...)

**Comment by brasseld** [comment]
`{#context.attributes['']}`
