### ISSUE TITLE
[gateway] Allow empty value for domain path

### ISSUE THREAD

**Issue by JulienFauvel** [gravitee-io/issues#2921]
### Expected Behavior
I would be able be able to have a "root" domain, without a domain in the routes.
This means the `Domain path` field should be optional.

### Current Behavior
The field is required, but if an empty value is set and we bypass the form validation it works.

### Possible Solution
Make the field optional

### Steps to Reproduce (for bugs)
1. Set domain path to an empty value
2. Inspect button, remove disabled attribute
3. Save
4. You can access your domain without specifying one in the url

### Your Environment
* Version used: 2.9.3

**Comment by brasseld** [comment]
So it means that AM  will be able to handle a single domain only?

**Comment by JulienFauvel** [comment]
It currently does work that way. Is there a solution for handling that case and still being able to handle other domains ?

**Comment by brasseld** [comment]
Yeah, by implements more or less the same principles we have with Virtual Host in APIM

**Comment by tcompiegne** [comment]
Closed by https://github.com/gravitee-io/issues/issues/3199

VHost mode let you use `/` as domain path.
