### ISSUE TITLE
[apim] Redoc support

### ISSUE THREAD

**Issue by l-lin** [gravitee-io/issues#2922]
Add support to another OpenAPI renderer, [Redoc](https://github.com/Redocly/redoc).

### Expected Behavior

When creating a new API, it would be nice to be able to choose another API doc generator than Swagger UI.

### Current Behavior

By default, when adding an OpenAPI spec file, the portal renders the API documentation with Swagger UI. It's not possible to use another OpenAPI doc generator.

### Context

Swagger UI is fine, but I find Redoc more "stylish" and offers some neat functionalities that Swagger UI doesn't have, like displaying multiple examples with their corresponding label.

### Your Environment

* Version used: 1.29.0
* Browser Name and version: N/A
* Operating System and version: N/A

**Comment by brasseld** [comment]
Would you like to contribute to?

**Comment by l-lin** [comment]
Sure :)

**Comment by l-lin** [comment]
It looks like you are doing a big refactoring (moved maven projects, UI revamp, portal-api-standalone can't start because of some NPE...).
As I'm not too familiar with Gravitee projects, I will wait until the refactoring is finished before contributing :/

**Comment by brasseld** [comment]
Yes, we are working on the new version of the portal.

But you can still have a try with the 1.30.x branch (which is the latest 1.x).

**Comment by aelamrani** [comment]
Closed by https://github.com/gravitee-io/issues/issues/3039 and available on the v3
