### ISSUE TITLE
Custom Policy Plug-in for request body change

### ISSUE THREAD

**Issue by Subbu0117** [gravitee-io/issues#2929]
Dear Gravitee Team, 
I need to transform API request body to custom . so as suggested by Gravitee team, I am writing plug-in to read request body and modify the content and set it back to request. but I am getting compiler error request.body().get() and set() . please share us plug-in request and response object methods for body get and set . 

Thanks,
Subbu

**Comment by brasseld** [comment]
Hi @Subbu0117 

Please have a look to the assign content policy to get an example about how to get the request body:

https://github.com/gravitee-io/gravitee-policy-assign-content/blob/master/src/main/java/io/gravitee/policy/assigncontent/AssignContentPolicy.java#L64

**Comment by Subbu0117** [comment]
Thank you
