### ISSUE TITLE
[repository] [test] Some data persist throughout tests, causing potential test failure if database is not cleaned before each test

### ISSUE THREAD

**Issue by Blake-Lead** [gravitee-io/issues#293]
Testing could be done more efficiently if data were independent from test to test for the same repository class.

I found that some data are persistent across tests and raise test failures when database is not dropped between tests.

For example, when running ApplicationRepositoryTest, createTest create a base entry with id 'created-app'. It is fine when testing application creation, but for the other tests, this entry should not exist. Thus subsequent tests fail because they test for the presence of 4 elements, but find 5 (4 + 'created-app').

Hope I have been clear enough

Adel

**Comment by aelamrani** [comment]
Hello Adel,

The repository test provide a contract (TestRepositoryInitializer) which allows to implement a setup and a tearDown methods. These methods allows to initialize ur storage. Each implementation of gravitee-repository must have its own way to setup/tearDown..

Azize
