### ISSUE TITLE
Analytics Request and Response date range is different FROM   November 19 --> November 18

### ISSUE THREAD

**Issue by aliFetvaci61** [gravitee-io/issues#2932]
management/applications/c299033e-653e-43b4-9903-3e653e13b4a8/analytics?type=date_histo&field=api&aggs=field:api&interval=86400000&from=1574110800000&to=1574197199099

•	Request:
o	From:  1574110800000 (Tuesday, **November 19**, 2019 12:00:00 AM GMT+03:00)
o	To:         1574197199099 (Tuesday, November 19, 2019 11:59:59.099 PM GMT+03:00)
•	Response:
o	From: 1574035200000 (Monday, **November 18**, 2019 3:00:00 AM GMT+03:00)
o	To:    1574121600000 (Tuesday, November 19, 2019 3:00:00 AM GMT+03:00)

**Comment by aelamrani** [comment]
@aliFetvaci61 from where did you get the response timestamps ?
