### ISSUE TITLE
HOST control and change endpoint in dynamic routing policy 

### ISSUE THREAD

**Issue by aliFetvaci61** [gravitee-io/issues#2970]
Can we define expression language In Dynamic Routing Policy rules like this.  #request.headers[#properties['HOST'].contains("prep") 

@brasseld @NicolasGeraud @aelamrani

**Comment by NicolasGeraud** [comment]
No, it only works on matching the path of your request and the expression.

**Comment by aelamrani** [comment]
@aliFetvaci61 here's what you are looking for: https://github.com/gravitee-io/issues/issues/60
