### ISSUE TITLE
I want to add a column in Application collection at mongo Repository. Is this Possible ? 

### ISSUE THREAD

**Issue by aliFetvaci61** [gravitee-io/issues#2974]
This definition is 

        <dependency>
            <groupId>io.gravitee.repository</groupId>
            <artifactId>gravitee-repository</artifactId>
        </dependency>

but I can not change dependency all projects

**Comment by aelamrani** [comment]
@aliFetvaci61 Can you explain first what is your need here?

**Comment by aliFetvaci61** [comment]
For Example I need new collections or new column in some collections but I can not edit this serializable POJO class. Is it possible ?

**Comment by aelamrani** [comment]
Yes, I understood that this is what you want to do.

What I want to know to provide the best answer is: what for? What is your final need?

**Comment by aliFetvaci61** [comment]
This is an Open Source Project and I need to customize it according to my architecture. "gravitee-repository"  depends all over the project. How can I customize gravitee-repository.

**Comment by aelamrani** [comment]
OK, seems you are doing secret things :)

The goal of my questions was to find out common needs or existing solution... Anyway.

You have just to fork some project: gravitee-repository, gravitee-repository-mongodb, gravitee-management-rest-api and/or (depending on your needs) gravitee-gateway.

To add a column to a collection, you can add a field in https://github.com/gravitee-io/gravitee-repository/blob/master/src/main/java/io/gravitee/repository/management/model/Application.java and adapt the mongodb implementation and the callers (rest-api / gateway).

You can add tests on the project gravitee-repository-test to validate the modifications on the implementation.

Is that what you were looking for?
