### ISSUE TITLE
[elasticsearch] Add rules to handle ILM for logs in elastic

### ISSUE THREAD

**Issue by michaelsogos** [gravitee-io/issues#2975]
Hi @graviteeio 

We have a pre-production installation which has log activated for testing and debug purpose. 
We notice that for each day a new index will be created for "-log", "-manage", "-request" in elastic, but nothing will delete older indexes.
A good idea could be to configure the ILM in order to delete indexes older than x days; in order to not fulfil disk space. Better if the ILM strategy can be configured from UI or at least from gravitee. yml.

**Comment by brasseld** [comment]
Hi @michaelsogos 

Nice avatar, is it sangria?

Did you have a look to https://docs.gravitee.io/apim_installguide_repositories_elasticsearch.html#index_management_with_es_curator ?

**Comment by michaelsogos** [comment]
Hi @brasseld 

Of course it is sangria 😜. 

Elastic curator has been deprecated long time ago, and since ES 6.7 has been introduce ILM in substitution of curator.

Actually we are using ES 7.1 and we plan to update to ES 7.4 in January. 
In every our Saas developed by us, ES cover a central role (not just for logs of course), and that's one of the reason we choose gravitee as our Api gateway.

I missing something?

**Comment by michaelsogos** [comment]
Hi There,

Any news?

**Comment by brasseld** [comment]
Hi there,

What are you looking for exactly ?

Managing ILM within Gravitee (and create policies), or just enable the policies while pushing index templates ? (or both)

**Comment by michaelsogos** [comment]
Hi,

The best option is to configure ILM policy for hot, warm, cold, delete stages directly in yaml config of gravitee.
Alternatively, is ok to leave gravitee to PUT an template as you thing and based on index name pattern create new indexes. In this way the ILM policy can be handle directly by our self from kibana.

In both way gravitee can use index alias to access logs and metrics without care about real index name. 

Make sense?

The target is to not let an elastic service be fulfilled by gravitee indexes and automatically handle both log rotate and retention of indexes thanks by ILM.

**Comment by MLukman** [comment]
Hi,

I too am looking for this feature. I would like to suggest you add into configuration something like:

```
reporters:
  elasticsearch:
    index_lifecycle_policies:
      monitor: retain-24h
      health: retain-2d
      log: retain-7d
      request: retain-30d
```
And what it does is simply adding into the index templates (for example https://github.com/gravitee-io/gravitee-elasticsearch/blob/master/gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-monitor.ftl):

```
<#ftl output_format="JSON">
{
    "index_patterns": ["${indexName}-*"],
    "settings": {
        <#if (lifecycle.monitor)??>
        "index.lifecycle.name": "${lifecycle.monitor}",
        </#if>
        "index.number_of_shards":${numberOfShards},
        "index.number_of_replicas":${numberOfReplicas},
        "index.refresh_interval": "${refreshInterval}"
    },
    "mappings": {
            "properties": {
                "gateway": {
                    "type": "keyword"
                },
                "hostname": {
                    "type": "keyword"
                }
            }
    }
}
```

I do have some Java skillset so I might be able to raise a pull request myself but I'm bad with unit testings so I might need someone else to assist me on that.

**Comment by brasseld** [comment]
Hi @MLukman 

I'll be more than happy to assist you this and work on the unit tests part.

Regards,

**Comment by MLukman** [comment]
Hi @brasseld,

I've raised pull request https://github.com/gravitee-io/gravitee-elasticsearch/pull/88

**Comment by MLukman** [comment]
Hi @brasseld, please kindly review my pull request. I've modified as per your requests.

**Comment by brasseld** [comment]
Done!

Thanks a lot @MLukman

**Comment by michaelsogos** [comment]
Dear @brasseld and @MLukman,

Great Job. It will be my pleasure to test changes in our pre-prod environment.
Which version should I install?
