### ISSUE TITLE
[gateway] do not log stream event requests

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#2976]
### Steps to Reproduce (for bugs)

1. create an api on an sse server and enable CLIENT/PROXY logs
2. open an SSE connection with datas sent by the server
3. wait
4. you will reach the limit of ES

### Your Environment

* Version used: <= 1.25.16

**Comment by abourdon** [comment]
Hello, only if the [reporters.logging.max_size](https://github.com/gravitee-io/gravitee-gateway/blob/master/gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml#L121) isn't set isn't it?

**Comment by NicolasGeraud** [comment]
No, we will not store response payload because the risk is that all your requests will store the `max_size` and this may causes issues in your elasticsearch.

**Comment by aelamrani** [comment]
We should add the content-type here: https://github.com/gravitee-io/gravitee-gateway/pull/481/files#diff-84b31520e4f04d2db4a5bd3d72b7e8bfR38
