### ISSUE TITLE
Path not used with the management bridge http

### ISSUE THREAD

**Issue by Tsuna77** [gravitee-io/issues#2992]
### Expected Behavior
I try to create a system with an hybrid deployement for gravitee.
As shown in the documentation, I follow this picture https://docs.gravitee.io/images/installation/hybrid/hybrid_deployment_architecture.png

I put a loadbalancer between my two parts configured this way : 
- "/bridge" goes to gravitee tech gateway with bridge module
- "/elastic" goes to elasticsearch
- "/" goes to forbiden access

What I expect is the gateway using my context path "/bridge" when calling the loadbalancer.

### Current Behavior
The gateway is calling the loadballancer with /
It does not used the path I set in the configuration file (url : https://<server>/bridge)

### Possible Solution
To use the path in th url in the configuration file

### Steps to Reproduce (for bugs)

1. Activate bridge server side
2. Put a HAproxy with a context-path to head to the bridge
3. Activate bridge client side with the context-path

### Context
See Expect behavior

### Your Environment
* Version used: 1.25.14
* Browser Name and version: N/A
* Operating System and version: RHEL 7.7

**Comment by brasseld** [comment]
Hi @Tsuna77 

Thanks for sharing issue. We'll have a look soon and provide a fix as part of an upcoming 1.25.x release.
