### ISSUE TITLE
[gateway] AWS Ligthsail Loadbalancer check a status of server by URL 

### ISSUE THREAD

**Issue by humblemh** [gravitee-io/issues#2993]
### Expected Behavior
I want to respond with  200 status code when requesting a specific path to Gateway.
because AWS Ligthsail Loadbalancer check health of server by URL 

[AWS Ligthsail Loadbalance heath check](https://lightsail.aws.amazon.com/ls/docs/en_us/articles/understanding-lightsail-load-balancer-health-checking)

ex) http://gateway/health
response -> 200OK

### Current Behavior
N/A

### Possible Solution
N/A

**Comment by brasseld** [comment]
Hi @humblemh,

IMHO the best is to check the technical API of the gateway: https://docs.gravitee.io/apim_installguide_gateway_technical_api.html#api

**Comment by humblemh** [comment]
Thanks!
