### ISSUE TITLE
[management] error when using a 3rd party OIDC server

### ISSUE THREAD

**Issue by bcollard** [gravitee-io/issues#2998]
Hello,

I'm facing some issues with a third party OIDC server with the APIM portal, version 1.30

I would like my users connect to the APIM mgmt-ui through our enterprise openID server.
I configured the following identity provider:

```
{
  "id" : "onelogin",
  "name" : "OneLogin",
  "description" : "************",
  "type" : "oidc",
  "enabled" : true,
  "configuration" : {
    "scopes" : [ "email", "profile", "openid", "SCO_*****" ],
    "clientId" : "*********",
    "tokenEndpoint" : "https://***/as/token.oauth2",
    "tokenIntrospectionEndpoint" : "https://***/as/introspect.oauth2",
    "authorizeEndpoint" : "https://***/as/authorization.oauth2",
    "userInfoEndpoint" : "https://***/idp/userinfo.openid",
    "userLogoutEndpoint" : "https://***/as/revoke_token.oauth2",
    "color" : "#f33434",
    "clientSecret" : "**************"
  },
  "userProfileMapping" : {
    "id" : "preferred_username",
    "firstname" : "given_name",
    "lastname" : "family_name",
    "email" : "email",
    "picture" : ""
  },
  "emailRequired" : false,
  "created_at" : 1575040167793,
  "updated_at" : 1575407257810
}
```

### 1st issue
When clicking the "OneLogin" button on the portal connection page, I'm redirected to the AS but the **redirect_uri** is not the one expected / allowed by the AS. 
There is a trailing slash missing.

Generated URL: 
`https://***/as/authorization.oauth2?response_type=code&client_id=*******&redirect_uri=https://***&scope=email%20profile%20openid%20SCO_******`

I would like this URL instead: 
`https://***/as/authorization.oauth2?response_type=code&client_id=*******&redirect_uri=https://***`**/**`&scope=email...`

Where does this **redirect_uri** parameter come from? 
FYI, in my constants.json, the `.portal.entrypoint` attribute is well formed with this trailing slash being present.

### 2nd issue
Once authenticated against my AS, I'm redirected to the login page of the APIM portal (for that to work, I forced the `redirect_uri` in the URL above)
But I get an **401** error when the angular JS is triggering the call the token exchange endpoint: `POST https://<APIM>/auth/oauth2/onelogin`
Payload: 
`{"code":"l-IIxqMh_iO1Uihvrsfag4-L-Z1IpNgriognzf8AAADI","clientId":"CLI_***","redirectUri":"https://<APIM portal home page>"}`

Is this controller subject to authentication? I think it should not.

**Comment by brasseld** [comment]
Hi @bcollard 

1) redirect_uri is defined according to the current window URI. See https://github.com/gravitee-io/gravitee-management-webui/blob/1.30.x/src/services/authentication.service.ts#L57

2) Don't understand your question `Is this controller subject to authentication?`. The UI redirects the user to the login page. Once logged in, the UI gets an authorization code from the AS, and invoke the `https://<APIM>/auth/oauth2/onelogin` endpoint to exchange AS bearer token to a gravitee one.

**Comment by bcollard** [comment]
1. so any trailing slash is forcibly stripped out. Ok, I'll change the redirect_uri allowed by our AS.

2. Problem solved thanks to the point above.
