### ISSUE TITLE
[policy] [generate-jwt] The header x5c is not available in policy

### ISSUE THREAD

**Issue by ingvarbs** [gravitee-io/issues#2999]
We would like to connect to an external API (via our API manager) that requires us to authenticate with a JWT that is signed with an enterprise certificate. We need to apply the certificate chain in the header 'x5c' in order to do that

### Expected Behavior
Have a field called x5c where we can either paste b64-encoded certificate chain or write the path to our certificate

### Current Behavior
No such field exist

### Possible Solution
There is an example program doing that here: https://github.com/difi/jwt-grant-generator/blob/fb042acbdd83f9bbc065237370b0f0682f1bc5b5/src/main/java/no/difi/oauth2/utils/JwtGrantGenerator.java#L40

### Context
We have several applications that need to connect to an external API. The external API requires  authentication through "Maskinporten" (an OIDC provider), which handles authentication through validating a JWT that is signed with an enterprise certificate and then supplies us with a time-limited token. This is also called “2-legged Oauth” and  is also described in https://difi.github.io/felleslosninger/oidc_protocol_jwtgrant.html 

We think we can do this in Gravitee using the policies Generate JWT, HTTP callout and Transform headers. (Two-legged) oauth. We need to apply the certificate chain in the header 'x5c' in order for the JWT to be validated.

### Your Environment

* Version used: 1.29.4
* Browser Name and version: Firefox 68.2 esr 
* Operating System and version: Centos 7

**Comment by brasseld** [comment]
Hi @ingvarbs 

I believe that the only missing point is coming from the Generate JWT policy ?

Why not just providing a new configuration option to add certificate chain management there: https://github.com/gravitee-io/gravitee-policy-generate-jwt/blob/master/src/main/java/io/gravitee/policy/generatejwt/GenerateJwtPolicy.java#L93 ?

**Comment by erlendfg** [comment]
I have created a pull request, but not sure how to link it to this issue.
https://github.com/gravitee-io/gravitee-policy-generate-jwt/pull/10
