### ISSUE TITLE
[DOC] move all url to https

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#3]
https://docs.gravitee.io display ssl error because some resource are not behind https protocol

<img width="550" alt="capture d ecran 2016-06-17 11 15 19" src="https://cloud.githubusercontent.com/assets/1028285/16146174/05748530-347d-11e6-8d93-9fc1599dd2a5.png">

**Comment by brasseld** [comment]
@NicolasGeraud We just have to update docs to point to https://ci.gravitee.io instead of http://build.gravitee.io. It may resolve a big part of the issue.

**Comment by NicolasGeraud** [comment]
Yes, and link to our logo with an https url
