### ISSUE TITLE
[management-api] OIDC identity provider should consume the id_token returned at first

### ISSUE THREAD

**Issue by bcollard** [gravitee-io/issues#3000]
### Expected Behavior
When a user authenticates over an OIDC Identity Provider, after the login on the AS, the mgmt-ui gets the auth code to exchange. This code is posted to the management-api :
https://github.com/gravitee-io/gravitee-management-rest-api/blob/1.30.x/gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/OAuth2AuthenticationResource.java#L185

The mgmt-api then exchange this auth code for an access_token. But, because, in this context, we are targeting an OIDC server, that server also returns directly an 'id_token' (the 'openid' scope should be enforced if not already done).

See this specification, both 'access_token' and 'id_token' must be returned by the AS: https://openid.net/specs/openid-connect-basic-1_0.html#TokenOK

So it would be quicker and more natural to consume directly this id_token in the code, rather than sending the access_token again to the AS on the UserInfo endpoint, in order to get again the user profile.
See: https://github.com/gravitee-io/gravitee-management-rest-api/blob/1.30.x/gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/resource/auth/OAuth2AuthenticationResource.java#L227

Your thoughts?

* Version used: 1.30

**Comment by brasseld** [comment]
Hey @bcollard 

Would say that it may depends on the AS you're using.

In your case, it seems that the id_token contains more or less the same set of data you can get from the userinfo endpoint, but I assume it's not always true.

Perhaps a nice alternative would be to add a new option for the OIDC provider to consume claims from id_token instead of the userinfo profile.

WDYT?

**Comment by bcollard** [comment]
Yes, that sounds to be a great option. 

Unfortunately, I'm not able to contribute to this kind of code (front or back), so I'll wait for someone to take care of it. Not blocking on my side.

Thanks.
