### ISSUE TITLE
[gateway] Support for Stomp-js

### ISSUE THREAD

**Issue by xgy2000** [gravitee-io/issues#3026]
stomp.js:463 WebSocket connection to 'ws://**********:8082/gateway--ws' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received

**Comment by xgy2000** [comment]
![image](https://user-images.githubusercontent.com/13026673/71084693-d0e7fc80-21d0-11ea-8694-abb694f97052.png)
I have to comment on this code

**Comment by brasseld** [comment]
Can you provide a JS reproducer I may use with my own gateway?

**Comment by xgy2000** [comment]
https://cdn.bootcss.com/stomp.js/2.3.3/stomp.js

**Comment by brasseld** [comment]
This is not a reproducer.
