### ISSUE TITLE
Can I add separately swagger documentation for all resolved path at APIs

### ISSUE THREAD

**Issue by aliFetvaci61** [gravitee-io/issues#3028]
Can I add separately swagger documentation for all resolved path at APIs
This is resolved Path 
![image](https://user-images.githubusercontent.com/16122994/70974932-f9310780-20b9-11ea-9fd6-0c9ef2af78c2.png)
Separately swagger documentation or different solutions.

**Comment by aelamrani** [comment]
@aliFetvaci61 I'm sorry but i do not understand what do you want to do here...

Do you want to import multiple swagger pages on a single API?

**Comment by ibahloul** [comment]
Hello @aliFetvaci61,
We still haven't understood the need and the ticket remains unanswered by you so I'm closing it.
