### ISSUE TITLE
[policy] [mock]  JSON schema - duplicate items on status property

### ISSUE THREAD

**Issue by MariaPushkin** [gravitee-io/issues#3029]
Policy Mock schema-form.json file has two duplicate "302 error status code" that causes schema validation errors like it was in [request validation policy (issue-2355)](https://github.com/gravitee-io/issues/issues/2355) and [callout http policy (issue-2324)](https://github.com/gravitee-io/issues/issues/2324).

**Comment by NicolasGeraud** [comment]
thanks @MariaPushkin
