### ISSUE TITLE
If mongodb requires password, gateway reports "command createIndexes requires authentication" while starting up

### ISSUE THREAD

**Issue by sanigo** [gravitee-io/issues#3032]
Even if i have created the mongodb user for gravitee apim 1.30.0, gateway reports "command createIndexes requires authentication" while starting up. It seems that the password setting in yaml file is not considered while createIndex.
The Exception: 

> 3:25:20.489 [Thread-12] [] ERROR org.mongodb.driver.client - Callback onResult call produced an error
> reactor.core.Exceptions$ErrorCallbackNotImplemented: org.springframework.data.mongodb.UncategorizedMongoDbException: Command failed with error 13 (Unauthorized): 'command createIndexes requires authentication' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "command createIndexes requires authentication", "code" : 13, "codeName" : "Unauthorized" }; nested exception is com.mongodb.MongoCommandException: Command failed with error 13 (Unauthorized): 'command createIndexes requires authentication' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "command createIndexes requires authentication", "code" : 13, "codeName" : "Unauthorized" }
> Caused by: org.springframework.data.mongodb.UncategorizedMongoDbException: Command failed with error 13 (Unauthorized): 'command createIndexes requires authentication' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "command createIndexes requires authentication", "code" : 13, "codeName" : "Unauthorized" }; nested exception is com.mongodb.MongoCommandException: Command failed with error 13 (Unauthorized): 'command createIndexes requires authentication' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "command createIndexes requires authentication", "code" : 13, "codeName" : "Unauthorized" }
> 	at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:138)
> 	at org.springframework.data.mongodb.core.ReactiveMongoTemplate.potentiallyConvertRuntimeException(ReactiveMongoTemplate.java:2588)
> 	at org.springframework.data.mongodb.core.ReactiveMongoTemplate.lambda$translateException$66(ReactiveMongoTemplate.java:2571)
> 	at reactor.core.publisher.Flux.lambda$onErrorMap$24(Flux.java:6140)
> 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88)

**Comment by brasseld** [comment]
Hi @sanigo 

May I ask you which products are you talking about: APIM or AM ?

**Comment by sanigo** [comment]
It is APIM.

**Comment by brasseld** [comment]
Did you set the same mongo URL for both the management and the rate-limit part ?
