### ISSUE TITLE
Get gravitee listed on https://landscape.cncf.io/

### ISSUE THREAD

**Issue by rtau** [gravitee-io/issues#3034]
### Expected Behavior
Gravitee.io, as an opensource API gateway product, should deserve to be listed on https://landscape.cncf.io/.

### Current Behavior
Gravitee is missing.

### Possible Solution
Open a pull request on GitHub to get it listed.

**Comment by aelamrani** [comment]
https://landscape.cncf.io/?license=apache-license-2-0&organization=gravitee-io&selected=gravitee-io
