### ISSUE TITLE
Traefik flag error when running platform/docker-compose.yml

### ISSUE THREAD

**Issue by adamczi** [gravitee-io/issues#3043]
### Expected Behavior
The platform should get up and running

### Current Behavior
Receiving error:
`command traefik error: flag needs an argument: -docker`
from traefik container. Traefik container then exits. This way none of the other containers can communicate (or at least they report that cannot connect to elasticsearch and they restart indefinitely.

### Steps to Reproduce
Following the article here: https://medium.com/graviteeio/fastest-way-to-manage-and-secure-your-apis-6c35a7ebab47
just run `curl -L http://bit.ly/graviteeio-platform | bash`

### Your Environment
* Docker version 19.03.5, build 633a0ea838
* docker-compose version 1.23.2, build 1110ad01
* Ubuntu 18.04

**Comment by brasseld** [comment]
Hi @adamczi 

Can you have a try by fixing the version of Traefik to a 1.x tag?

https://github.com/gravitee-io/gravitee-docker/blob/master/platform/docker-compose.yml#L11

Thanks for your feedback.

Regards,

**Comment by adamczi** [comment]
Hi, this error is gone, but now I get:

```
elasticsearch_1    | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.           
elasticsearch_1    | [2019-12-19T16:46:32,235][INFO ][o.e.n.Node               ] [] initializing ...                                                                     
elasticsearch_1    | [2019-12-19T16:46:32,270][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]                                
elasticsearch_1    | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment                                    
elasticsearch_1    |    at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:140) ~[elasticsearch-6.3.1.jar:6.3.1]                                       
elasticsearch_1    |    at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.3.1.jar:6.3.1]                                    
elasticsearch_1    |    at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.3.1.jar:6.3.1]                       
elasticsearch_1    |    at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.3.1.jar:6.3.1]                                 
elasticsearch_1    |    at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.3.1.jar:6.3.1]                                                      
elasticsearch_1    |    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.3.1.jar:6.3.1]                                        
elasticsearch_1    |    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) ~[elasticsearch-6.3.1.jar:6.3.1]                                        
elasticsearch_1    | Caused by: java.lang.IllegalStateException: Failed to create node environment                                                                       
elasticsearch_1    |    at org.elasticsearch.node.Node.<init>(Node.java:273) ~[elasticsearch-6.3.1.jar:6.3.1]                                                            
elasticsearch_1    |    at org.elasticsearch.node.Node.<init>(Node.java:252) ~[elasticsearch-6.3.1.jar:6.3.1]                                                            
elasticsearch_1    |    at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.3.1.jar:6.3.1]                                           
elasticsearch_1    |    at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.3.1.jar:6.3.1]                                              
elasticsearch_1    |    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) ~[elasticsearch-6.3.1.jar:6.3.1]                                               
elasticsearch_1    |    at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.3.1.jar:6.3.1]                                       
elasticsearch_1    |    ... 6 more                                                                                                                                       
elasticsearch_1    | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes                                                                 
elasticsearch_1    |    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]                                                                 
elasticsearch_1    |    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]                                                                  
elasticsearch_1    |    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]                                                                  
elasticsearch_1    |    at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:385) ~[?:?]                                                     
elasticsearch_1    |    at java.nio.file.Files.createDirectory(Files.java:682) ~[?:?]
elasticsearch_1    |    at java.nio.file.Files.createAndCheckIsDirectory(Files.java:789) ~[?:?]
elasticsearch_1    |    at java.nio.file.Files.createDirectories(Files.java:775) ~[?:?]
elasticsearch_1    |    at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:203) ~[elasticsearch-6.3.1.jar:6.3.1]
elasticsearch_1    |    at org.elasticsearch.node.Node.<init>(Node.java:270) ~[elasticsearch-6.3.1.jar:6.3.1]
elasticsearch_1    |    at org.elasticsearch.node.Node.<init>(Node.java:252) ~[elasticsearch-6.3.1.jar:6.3.1]
elasticsearch_1    |    at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.3.1.jar:6.3.1]
elasticsearch_1    |    at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.3.1.jar:6.3.1]
elasticsearch_1    |    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) ~[elasticsearch-6.3.1.jar:6.3.1]
elasticsearch_1    |    at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.3.1.jar:6.3.1]
elasticsearch_1    |    ... 6 more
```

(these are complete logs from elasticsearch container). I see some "AccessDenied" - I run this docker-compose in a folder in a home dir on my laptop with Ubuntu 18.04, with no SELinux-like things enabled. I'm also using my everyday user, permissions are just as they normally are for home dir, no ACLs and things like that.

**Comment by adamczi** [comment]
Ok, I changed the elasticsearch volume to anonymous and it went up.

Now I'm facing 404s on links like: https://apim.gravitee.io/app-7b12964d4116c289cc68.js (after adding apim.gravitee.io and am.gravitee.io to /etc/hosts), even though the main /portal route works - just cannot load JS/CSS: "No context-path matches the request URI.". But I think it's another story.

**Comment by brasseld** [comment]
Did you try `https://apim.gravitee.io/portal` to reach the UI ?

**Comment by brasseld** [comment]
Can you try by accessing `https://apim.gravitee.io/portal/` ?

**Comment by adamczi** [comment]
This worked, many thanks :) But I cannot access AM service - all requests return 200, but there seems to be a front-end issue:

![image](https://user-images.githubusercontent.com/15002570/71255868-71543300-232f-11ea-8e48-a904f737502d.png)


(no other errors except for the one above, repeating 5 times) After accessing https://am.gravitee.io it redirects to https://am.gravitee.io/dashboard and I see what is on above picture. Actually  My /etc/hosts is like below in case it helps:
```
127.0.0.1       localhost
127.0.0.1       apim.gravitee.io
127.0.0.1       am.gravitee.io
```

After accessing https://am.gravitee.io I see I'm logged in (or at least there is an option to log out in top right menu), after logging out I get another error - `ERROR Error: "Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'admin/logout'`. I didn't change anything in docker-compose or Traefik routes except for passing `v1.7` to Traefik image version.

**Comment by adamczi** [comment]
Thanks, I can confirm your fixes work.

Things to keep in mind though, are that Elasticsearch needs special settings in order to run:
1) increased vm.max_map_count value: https://stackoverflow.com/questions/51445846/elastic-search-max-virtual-memory-areas-vm-max-map-count-65530-is-too-low-inc
2) permissions to write it's data: for a quick fix I made the volume which exposes `/usr/share/elasticsearch/data` anonymous, could also remove volume binding or just set up correct permissions in the host destination location.

Without these fixes the oneliner command won't work.

Thanks Gravitee Team for your support and fixes! :thumbsup:
