### ISSUE TITLE
[gateway] WebSocket response headers are not forwarded

### ISSUE THREAD

**Issue by hujin-sh** [gravitee-io/issues#3051]
Hi, when using WebSocket connection, the gateway does not forward the response header, for example: Sec-WebSocket-Protocol

**Comment by adubreuiltk** [comment]
Hi,

We use STOMP-over-websocket through Gravitee, and we have issues with some clients that are unable to connect because some response headers are missing:

![image](https://user-images.githubusercontent.com/5410883/73223119-544c2480-4165-11ea-93ff-4e6989b9537a.png)

Everything works fine if the clients connect directly to the STOMP server.

Why only the HTTP status code is passed back to the client?

**Comment by brasseld** [comment]
Hi,

As we don't know when the websocket connection will be released (by consumer and/or backend) and can be maintained for a long time, all the websocket logs are indexed when gateway succeed to connect to the upstream.

**Comment by hujin-sh** [comment]
Hi,
I noticed that versions of vertx before 3.8.2 did not return a WebSocket request header, and vertx 3.8.2 has fixed this problem. https://github.com/eclipse-vertx/vert.x/pull/3107

**Comment by hujin-sh** [comment]
I tried to modify the io.gravitee.gateway.http.connector.VertxHttpClient related source code and it works normally...

<img width="858" alt="WeChata0cb7f296b34f856215a7593eb51d8f7" src="https://user-images.githubusercontent.com/29949867/74724752-bf29e080-5277-11ea-9961-c2a056da03c3.png">

**Comment by brasseld** [comment]
Nice shot.

So it implies to upgrade to Vertx 3.8.2

I did not already have a look to the impact of such upgrade...
Did you check your side ?

**Comment by hujin-sh** [comment]
I just merged this PR of vertx 3.8.2 into the 3.7.2 version, and then compiled, but did not upgrade vertx to 3.8.2

**Comment by adubreuiltk** [comment]
Hi,
Has Gravitee been upgraded to a newer version of Vertx?

**Comment by brasseld** [comment]
Hey @adubreuiltk 

I've missed that one.

Gravitee 3.x is based on Vert.x 3.8.5

**Comment by gianx89** [comment]
Maybe related to this one? https://github.com/gravitee-io/issues/issues/4060

**Comment by brasseld** [comment]
Fixed by https://github.com/gravitee-io/issues/issues/4060

**Comment by adubreuiltk** [comment]
> Hey @adubreuiltk
> 
> I've missed that one.
> 
> Gravitee 3.x is based on Vert.x 3.8.5

Great, thank you
