### ISSUE TITLE
[management] Add custom info to applications

### ISSUE THREAD

**Issue by MariaPushkin** [gravitee-io/issues#3058]
Hello!
We need to add some special field to application data and check that info at the request stage. I know that there is `metadata` for Application in db, where custom fields can be stored, but it is impossible to send custom info through REST. Maybe you can you advice something here.

One other problem here is that we dont want to make requests to database on every client request to check that additional info. Is there any proper way to make applications info cached on gateway?

**Comment by brasseld** [comment]
Hello @MariaPushkin 

The problem I'm seeing currently is that the gateway is never relying on any field from application. Perhaps it will have more sense to attach these `metadata` to the subscription object?

Do you have any example about fields you're looking to attach to an application and which are required while processing API requests?

**Comment by MariaPushkin** [comment]
Hello @brasseld!

Sorry for such a slow reply. Yes, the main problem in that. Adding this info to subscribtion can be the decision or perhaps workaround, but, as I understand, Subscribtion class does not have any `metadata` field ([Subscription.java](https://github.com/gravitee-io/gravitee-repository/blob/master/src/main/java/io/gravitee/repository/management/model/Subscription.java)).

According to the requirements for some of our APIs clients should have list of uris (of the front systems) from which the call of these APIs is possible. So, with every request client should send uri and gateway need to check allowed it or not.

**Comment by brasseld** [comment]
I understand your concern but in that case, why not defining a plan for each of your API client to configure whitelist / blacklist of uris?

**Comment by brasseld** [comment]
Or you mean the URI from the front, so maybe by using the Referer HTTP header ?

**Comment by MariaPushkin** [comment]
Yes, these uris have no relation to request uri, it is just info sent in request body and used more at the back system. But event if we will use header (I am not sure that this uri is true referer, but as I understand API provider, something close) the main problem still is that list of allowed uris is unique to the client.

**Comment by akm4** [comment]
My vote for this feature. There are several use-cases where the application metadata is extremely helpful in runtime. The main case in my opinion is the alternative application ids and other metadata, that can be mapped on the gateway and send to the backend. Imagine translation from client_id to backend application id or partner id. 

Another one is external data (like callback URL in Maria's example) came with the request that should be analyzed/matched with application-specific data stored in API Management.

**Comment by MariaPushkin** [comment]
Hello there! Just wondering if there any updates on that issue?

**Comment by brasseld** [comment]
My only concern here is about the fact that the gateway does never rely on the application concept. So, before going ahead on such issue, I need a clear understanding about the purpose and what would be the best way to handle it.
I don't want to mount all the applications into the API gateway to play with their respectives metadata / properties.
That's the reason why, IMHO, the best is to rely on the subscription object. But not sure it's a solution for you.

**Comment by MariaPushkin** [comment]
Okay, I understand your concern here. Bur what about just providing possibility to add some kind of custom fields to application through REST-service? It can be stored in application_metadata <key, value> map, which is already exist in Application object.

**Comment by brasseld** [comment]
When you say "rest-service", are you talking about the management-api ?
Because, in that case, the metadata will not available from the gateway, and I was thinking it's the goal...

**Comment by MariaPushkin** [comment]
Yes, I am talking about management-api. Availability application data from the gateway is the goal, but I see that you didn't appreciate that idea, so we are working on some side solitions here. But the first part of the problem is the possibility just to store that custom data in Application entity.

**Comment by brasseld** [comment]
Storing metadata in application entity looks a good idea.
I'm asking myself if we should follow the same principle as API metadata (if you already played with them).

**Comment by MariaPushkin** [comment]
I see the main important point here in providing opportunity to add metedata through create application request and making possible to search applications by metadata fields. But the rest I think may follow the same principle as API metadata.

**Comment by brasseld** [comment]
Hi @MariaPushkin 

Hope you're doing well.

I'm just thinking that making use of an applications dictionary can do the trick.
What do you think?

See https://github.com/gravitee-io/issues/issues/3296

**Comment by MariaPushkin** [comment]
Hi @brasseld 

Sounds nice, but as the number of applications grows, system load will increase. So, I think this will necessarily require creating a filter by the last update time and/or some other fields of the application or smth like this. The same is true for the new application_metadata. But the idea is definitely worth the attention!

**Comment by brasseld** [comment]
Yes,

This was just a kind of workaround to go ahead..

To avoid system load, the only solution would be to get application's info on a per call basis to enable lazy loading (probably with the help of a caching system also)
