### ISSUE TITLE
[gateway] [oauth2] Migration issue with scope AM v1 to v2

### ISSUE THREAD

**Issue by hqrd** [gravitee-io/issues#3059]
I migrated from AM v1 to AM v2 but there is something I can't figure out.
I was not passing any scope to my token requests (/oauth/token) and my AM was working and filling the scopes automatically configured in the client.
But now when I ask for a token, the AM responds "Invalid parameter: scope must not be empty"
I'm using OAuth2 with password grant_type.

How can I make AM returns tokens from a request with no scope provided ?

### Expected Behavior
Passing a request for a token with no scope should not always respond an error.

### Current Behavior
A token request with an empty scope returns "Invalid parameter: scope must not be empty"

### Steps to Reproduce
1. Create client with OAuth2, with grant types refresh token and password
2. Call for token endpoint /oauth/token, request's body has an empty scope parameter and a grant_type password

### Your Environment
* Version used: AM 2.10.4

**Comment by tcompiegne** [comment]
Hi @hqrd ,

You have this error because you request an access token with an empty scope parameter : `scope=&grant_type=password`, since AM v2 we now check for empty query parameter. 

Can you try by removing the scope parameter ?

**Comment by hqrd** [comment]
It works when no scope parameter is provided indeed. 
But some of my apps were calling it with an empty scope so I'd like to avoid changing this code. Is there a way to avoid this empty check for the scope parameter ?

**Comment by hqrd** [comment]
It works when no scope parameter is provided indeed.
But some of my apps were calling it with an empty scope so I'd like to avoid changing this code. Is there a workaround to avoid this empty check for the scope parameter ?

**Comment by tcompiegne** [comment]
Hi @hqrd ,

To be honest, I don't remember why we had this extra check ... I need to verify if we still passed the OIDC certification tests without it, to be sure that we can remove this part.
