### ISSUE TITLE
Custom policy not showing up in UI

### ISSUE THREAD

**Issue by andy-22** [gravitee-io/issues#3063]
I am not a java developer. I am coming from a C# world. But looking at the architecture of gravitee.io impressed me so much and forced me to learn bit more about it.
I am trying to create a custom policy to use redis cache (please let me know if it already exists so that I don't have to re-invent the wheel)
I generated sample policy using the command:
`mvn archetype:generate -DarchetypeGroupId=io.gravitee.maven.archetypes -DarchetypeArtifactId=gravitee-policy-maven-archetype -DartifactId=redis-cache-policy -DgroupId=io.gravitee.policy.redis -Dversion=1.0.0 -DpolicyName=RedisCache`

and added some schema fields.
I packaged and deployed zip in plugins directory in gateway. When I restart gateway service, I see in logs that plugin is loaded just fine and I also see that it is extracted in work directory.
When I login to UI and go to the design view of existing API, i can't see my policy in the list of other policies.
Do I have to do anything special for it to show up?

**Comment by brasseld** [comment]
Hi @andy-22 

You have to deploy the plugin under the management api also.

Regards,
