### ISSUE TITLE
APIM Management API fails to start if MongoDB is not yet available

### ISSUE THREAD

**Issue by adubreuiltk** [gravitee-io/issues#3069]
If MongoDB is not yet available when APIM Management API  starts, and, even if Mongo is OK  few seconds after, then Management API fails forever with that error:

```
Jan 05 23:12:45 gravitee.server[2331]: 23:12:45.001 [refresher-1] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
Jan 05 23:12:45 gravitee.server[2331]: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'graviteeTransactionManager' available: No matching PlatformTransactionManager bean found for qualifier 'graviteeTransactionManager' - neither qualifier match nor bean name match!
```

### Expected Behavior
Once MongoDB is up, then Management API should work.

### Current Behavior
Management API fails and must be restarted.

### Possible Solution
Apply the same logic as for the Gateway

### Steps to Reproduce (for bugs)
1. Stop MongoDB and Management API
2. Stop Management API
3. Start Management API and wait until the error occurs in the log
4. Start MongoDB

### Context
Synchronize the start of MongoDB and Gravitee makes the infra administration muche more complex.

### Your Environment
* Version used: 1.29.1
* Operating System and version: Debian 9.11

**Comment by brasseld** [comment]
Hi @adubreuiltk 

Fixed in 1.25.x and 1.30.1: see https://github.com/gravitee-io/gravitee-management-rest-api/commit/73f560c3d18b3b80ecbb01fc77f74479dcb003a9

**Comment by adubreuiltk** [comment]
Thanks, I upgraded to 1.30.1

**Comment by mo-x** [comment]
I use 1.3. X branch code also has this problem, mongodb status is normal, can you solve it?
