### ISSUE TITLE
Gravitee - ManagementAPI crashes constantly and restarts itself

### ISSUE THREAD

**Issue by IvoIlic95** [gravitee-io/issues#3075]
Hello

First of all, I want to install Gravitee in Openshift. But unfortunately the ManagementAPI is throwing a error.

Here is the Problem:
My ManagementAPI is throwing an error repeatedly every time after it restarts itself.
In addition to that this message comes up "_The container management-api is crashing frequently. It must wait before it will be restarted again._" (This message appears where I can see my pod that is running).

Here are my Environment Variables that I use:
  GRAVITEE_MANAGEMENT_MONGODB_URI = 
  mongodb://XXXXX:XXXXXX@mongodb:27017/mongodb-gravitee
  GRAVITEE_RATELIMIT_MONGODB_URI = 
  mongodb://XXXXX:XXXXXX@mongodb:27017/mongodb-gravitee
  GRAVITEE_ANALYTICS_ELASTICSEARCH_ENDPOINTS_0 = http://klusa1008.infineon.com:9200/

At the end of the log it tells me to change the jwt secret. But where do I have to change it? In Elasticsearch?

I don't know if this message means "I am okey and running".

I would be very pleased if someone could help me to figure out what the problem is and how it can be solved.

Kind regards,
Ivo Ilic

**Comment by aelamrani** [comment]
Hi @IvoIlic95 could you please upload the log to a file instead of directly into the issue in order to make easy the read of your comments here.
Thanks.

**Comment by IvoIlic95** [comment]
[Gateway.txt](https://github.com/gravitee-io/issues/files/4034726/Gateway.txt)
[ManagementApi_Error.txt](https://github.com/gravitee-io/issues/files/4034727/ManagementApi_Error.txt)

Hello

Sorry my fault this will not happen again.

I have uploaded a .txt File for the MangementAPI Error and a .txt File for the Gateway.
The reason of uploading the Gateway .txt File is to get a message from you if the Gateway is running by reading the log file, because I didn't see any error in it. So probably the Gateway is running in my opinion.

I would be very happy if you can help me.

Kind regards,
Ivo Ilic

**Comment by aelamrani** [comment]
Seems the logs are truncated?
For the management logs, nothing after 10:08:25.905 ?

**Comment by IvoIlic95** [comment]
No it just stops there and then after some time it restarts the pod.

Should I send you the the Environment Variables for the Gateway, ManagementAPI and the ManagementUI? Maybe there is a configuration error?

**Comment by brasseld** [comment]
@IvoIlic95 

How did you size your pods ?

**Comment by IvoIlic95** [comment]
Each pod runs one image from Gravitee: Gateway, ManagementUI, ManagementApi, MongoDB

**Comment by brasseld** [comment]
what in terms oc cpu / mem ?

**Comment by IvoIlic95** [comment]
Resource Type | Used | Max
-- | -- | --
CPU (Request) | 600 millicores | 2 cores
Memory (Request) | 2 GiB | 4 GiB
CPU (Limit) | 1200 millicores | 2 cores
Memory (Limit) | 2 GiB | 4 GiB
Pods | 4 | 20
requests.nvidia.com/gpu | 0 | 0

They are fine, they get never maxed out.

**Comment by IvoIlic95** [comment]
Here are the Environment Variables for each Gravitee service if they are helpful.

Gateway Environment Variables
GRAVITEE_MANAGEMENT_MONGODB_URI
mongodb://XXXX:XXXXXX@mongodb:27017/mongodb-gravitee

GRAVITEE_RATELIMIT_MONGODB_URI
mongodb://XXXX:XXXXXX@mongodb:27017/mongodb-gravitee

GRAVITEE_REPORTERS_ELASTICSEARCH_ENDPOINTS_0
http://XXXXXXXX.infineon.com:9200/

ManagementAPI Environment Variables:
GRAVITEE_MANAGEMENT_MONGODB_URI
mongodb://xxxxx:xxxxxx@mongodb:27017/mongodb-gravitee

GRAVITEE_RATELIMIT_MONGODB_URI
mongodb://xxxxx:xxxxxxx@mongodb:27017/mongodb-gravitee

GRAVITEE_ANALYTICS_ELASTICSEARCH_ENDPOINTS_0
http://xxxxxxx.infineon.com:9200/

ManagementUI Environment Variables:
HTTP_PORT
8080

HTTPS_PORT
8443

MGMT_API_URL
http://management-api:8083

**Comment by IvoIlic95** [comment]
Good morning guys :)

Is there a possible solution to my problem?
I have created a external route in openshift for the management-ui: Route management-ui, target port 8080-tcp. 

If I click on this external route this happens:

![image](https://user-images.githubusercontent.com/59047274/72048686-a06e1c80-32bd-11ea-86c9-26aa42171a16.png)

Now is my question: Is the problem located in the ManagementApi and/or Management-ui?

Kind regards,
Ivo Ilic

**Comment by IvoIlic95** [comment]
Good morning again

Could someone help me, my company needs this product running so that it can be evaluated.

Kind regards,
Ivo Ilic

**Comment by aelamrani** [comment]
Hi, 

I would say that either the server is not reachable or did not start correctly.

You can: 
- Check the network tab on your browser's console
- Check the logs on the management API

**Comment by IvoIlic95** [comment]
[ManagementAPI_ErrorLog.txt](https://github.com/gravitee-io/issues/files/4052568/ManagementAPI_ErrorLog.txt)

Hello

Well if I open the DevWindow in Chrome I'm getting this error:

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "templates.template.openshift.io \"jenkins-pipeline-example\" is forbidden: User \"system:anonymous\" cannot get templates.template.openshift.io in the namespace \"openshift\": no RBAC policy matched",
  "reason": "Forbidden",
  "details": {
    "name": "jenkins-pipeline-example",
    "group": "template.openshift.io",
    "kind": "templates"
  },
  "code": 403
}

Kind regards,
Ivo Ilic

**Comment by IvoIlic95** [comment]
Hello and good morning

Do someone know what this means: no RBAC policy matched","reason": "Forbidden"?

All of my services are running but it only displays this message if i want to open the Management-UI: Management API unreachable or error occurs, please check logs.

Why could be the error?

Kind regards,
Ivo Ilic

**Comment by brasseld** [comment]
Hi there,

Is this issue still relevant?

Regards,
