### ISSUE TITLE
[management] Provide domain analytics

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#3077]
AM Management API should be able to provide the following analytics for a security domain : 

- Logins activity
- Sign ups activity
- Top applications
- Inactive users

Others issues will be created to get analytics for a specific application and specific user.

Community and @gravitee-io/developers please update this ticket to add what you would like to see in terms of analytics.

**Comment by bkhadige** [comment]
nice to have :
- average time between for signup
- average time between signup and first login
- top login succes (users)
- top login failed (users)
- top login number (users)
