### ISSUE TITLE
[management] Order is not handled correctly into folders

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#3080]
When adding a new page, the new order is global max size.

### Expected Behavior
We should get the max size of the current folder.

### Current Behavior
When adding a new page, the new order is global max size.

### Possible Solution
Get the max size of the current folder.

**Comment by mouligno** [comment]
isn't that link to https://github.com/gravitee-io/issues/issues/6652 ?

**Comment by gaetanmaisse** [comment]
Closing as it was discussed with https://github.com/gravitee-io/issues/issues/6652 and is now tracked in a feature request
