### ISSUE TITLE
Register and login with email address instead of username

### ISSUE THREAD

**Issue by bereketbeyt** [gravitee-io/issues#3084]
Current version forces user to create a username and provides validity and uniqueness with it. 
### Expected Behavior
A user should be able to pick his/her email address instead of username. Forms for registration and login could be generated.

### Current Behavior
Standard login and registration pages forces username fields. There is not any option to modify behaviour on the admin panel. If they are deleted from custom forms 500 internal server error occurs.

### Possible Solution
Either username or email address should define uniqueness and validity

### Context
Email addresses are used on authentication process instead of username in the most of the applications in real life. Nobody wants to remember and make up another username

### Your Environment

* 2.10.4
*  All browsers:
* All OS:

**Comment by tcompiegne** [comment]
Hi @bereketbeyt ,

What about create your own custom registration template page ? You can hide the `username` field and use the `email` field to fill both `email` and `username` values (via javascript for example).

**Comment by bereketbeyt** [comment]
@tcompiegne yes it could be done. However, I don’t think it resolves this issue permanently, which results duplicate emails on admin panel.

**Comment by tcompiegne** [comment]
If the email is set as the username, the uniqueness will be preserved.

**Comment by tcompiegne** [comment]
Hi @bereketbeyt can we close the issue ?

**Comment by bereketbeyt** [comment]
Hi @tcompiegne, yes, we can close this issue. Thanks
