### ISSUE TITLE
Must login twice to use the swagger documentation

### ISSUE THREAD

**Issue by lcofre** [gravitee-io/issues#3085]
Our instance of gravitee is configured to login with our Identity server. Even when logged in this way, I have to click in the Authorize button inside the swagger documentation for the endpoints to allow the Try it out functionality.

### Expected Behavior
That the login to the UI allows to execute the endpoints of the swagger documentation

### Current Behavior
Login needs to be done twice, in gravitee first and then in the swagger documentation.

### Your Environment
* Version used: 1.24.1
* Browser Name and version: Chrome 79
* Operating System and version: Windows 10

**Comment by brasseld** [comment]
Hi @lcofre 

Swagger-UI has been upgraded in latest 1.30.x version.

Is this issue still relevant?

**Comment by lcofre** [comment]
Hi @brasseld,

We are stuck in 1.24.1 sadly. We should rewrite our app to upgrade to the latest gravitee.

I attach a screenshot this time to explain it a bit better:
![image](https://user-images.githubusercontent.com/1630156/83500433-ac4dbb80-a4b6-11ea-85f3-83ee0531f2f6.png)

In the top right gravitee is logged in, but the API in the bottom left is not.
Can you think of any workaround?

Thanks very much for your help!

**Comment by brasseld** [comment]
Ok, I think I have a better understanding now.

Can you explain me a bit about `We should rewrite our app to upgrade to the latest gravitee.` ?

So, we are not reusing end-user authentification for swagger because, most of the time, the call is not relative to the user, and you should have to go through a specific oauth flow.

Which security type are you using from your swagger?

**Comment by lcofre** [comment]
Thanks for your help!

I can't find the breaking changes that stop us from upgrading above 1.24 (I was told only we cannot upgrade) It may be the new OpenID configuration introduced in 1.25: https://docs.gravitee.io/apim/1.x/apim_installguide_migration.html#application_management

In any case, we also have a migration project that wraps the Gravitee endpoints to create the API and related objects in Gravitee, so we should change it accordingly if we upgrade to the latest version.

We are using the Implicit Grant Flow from swagger. I guess the Code Grant didn't work on swagger on that version.
