### ISSUE TITLE
[management-ui] CORS error with gravitee UI 

### ISSUE THREAD

**Issue by jerome25000** [gravitee-io/issues#3092]
When installing the gravity docker demo (https://docs.gravitee.io/apim_installguide_docker.html), on my machine let's say : myserver.com

If locally I try to access to the GUI via uri : http://myserver.com:8002, 
I have an error on the page : "Management API unreachable or error occurs, please check logs"

On the console logs I have the following CORS error :+1: 

Failed to load resource: the server responded with a status of 503 (Service Unavailable)
(index):1 Access to XMLHttpRequest at 'http://myserver.com:8005/management/portal' from origin 'http://myserver.com:8002' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

In the file gravitee.yml of the local_managementapi docker image (/opt/graviteeio-management-api/config). I see that :

cors:
    # Allows to configure the header Access-Control-Allow-Origin (default value: *)
    # '*' is a valid value but is considered as a security risk as it will be opened to cross origin requests from anywhere.    
    #allow-origin: * 
    # Allows to define how long the result of the preflight request should be cached for (default value; 1728000 [20 days])
    #max-age: 864000
    # Which methods to allow (default value: OPTIONS, GET, POST, PUT, DELETE)
    allow-methods: 'OPTIONS, GET, POST, PUT, DELETE'
    # Which headers to allow (default values: Cache-Control, Pragma, Origin, Authorization, Content-Type, X-Requested-With, If-Match)
    #allow-headers: 'X-Requested-With'

So it seems here, by default "Access-Control-Allow-Origin" header is by default "*"

If I try to change it to other value, if never works. In the browser I see no such response header.

How to setup the CORS correctly to have gravitee ui reachable from something else than local?

**Comment by brasseld** [comment]
Hi @jerome25000 

How did you change the value for cors origin?

**Comment by jerome25000** [comment]
If I change something in the gravitee.yml file, or let as it, it is not working. Is there an option somewhere to enable this CORS functionnality?

**Comment by brasseld** [comment]
When you say, changing something in gravitee.yml, you mean mounting the gravitee.yml within a volume to take car of the changes in the docker container?

**Comment by jerome25000** [comment]
Yes

**Comment by jerome25000** [comment]
But by default, it seems that CORS config is not enabled at all. How to enable it?

**Comment by brasseld** [comment]
CORS is enabled by default and is set with `*` as allowed origin.

**Comment by brasseld** [comment]
FYI, you've got a 503 response status code, so I'm not sure the management-api has been reached.

**Comment by jerome25000** [comment]
Yes, but I have this answer also :

Access to XMLHttpRequest at 'http://myserver.com:8005/management/portal' from origin 'http://myserver.com:8002' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

If I from myserver, I try this : wget http://localhost:8005/management/portal 

it works fine. So service is running.

Here problem is that CORS management is not enabled in gravitee. Any idea how to enable it?

**Comment by jerome25000** [comment]
> FYI, you've got a 503 response status code, so I'm not sure the management-api has been reached.

My bad : It is a 403 I obtain :

GET http://myserver.com:8005/management/portal 403 (Forbidden)

Access to XMLHttpRequest at 'http://myserver.com:8005/management/portal' from origin 'http://myserver.com:8002' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by brasseld** [comment]
Hi @jerome25000 

Is this issue still relevant?

**Comment by jerome25000** [comment]
@brasseld  no you can close it. For some reason, it works fine now...

**Comment by brasseld** [comment]
Ok, thanks for your feedback.

Regards,
