### ISSUE TITLE
[gateway] Accept backends/entrypoints supporting only HTTP/2

### ISSUE THREAD

**Issue by adubreuiltk** [gravitee-io/issues#3105]
If the backend only accepts HTTP/2, the connection fails with the error:
```
Unknown ALPN Protocol, expected `h2` to be available.
If this is a HTTP request: The server was not configured with the `allowHTTP1` option or a listener for the `unknownProtocol` event.
```

### Expected Behavior
Gravitee should be able to connect to a backend using HTTP/1.1 or HTTP/2.

### Current Behavior
If the backend only supports HTTP/2, then the API call fails.

### Possible Solution
Either offer an option at the entrypoint-level to define the preferred HTTP version it both are supported by the backend, or apply an default rule (i.e. HTTP/2 with failover on HTTP/1.1)

### Steps to Reproduce (for bugs)
1. Enable **only** HTTP/2 on the backend server
2. Call an API

### Your Environment
* Version used: 1.30.1
* Browser Name and version: curl 7.58
* Operating System and version: Ubuntu 18.04

**Comment by brasseld** [comment]
Hi @adubreuiltk 

HTTP/2 (and gRPC) support will be provided in 3.0

**Comment by adubreuiltk** [comment]
Thanks!!!
