### ISSUE TITLE
oAuth 401 unauthorized issue

### ISSUE THREAD

**Issue by deepak21singh** [gravitee-io/issues#3106]
I have created an oauth plan and attached the resources with this plan and after this created the application and subscribed the api but when i am making request i am getting 401 unauthorized issue.

* Version used: 1.29.5 for Gateway and 2.9.3 for AM
* Browser Name and version: latest Firefox 
* Operating System and version: window 7
![image](https://user-images.githubusercontent.com/57327730/72659760-d496bb00-39ea-11ea-9b03-a91ce2451cf9.png)
![Issue](https://user-images.githubusercontent.com/57327730/72659768-f132f300-39ea-11ea-8656-bd439c14948b.png)

**Comment by brasseld** [comment]
Hi there,

It is a preflight request so you probably have to enable and configure CORS settings for the signinTest API.

**Comment by deepak21singh** [comment]
i tried with CORS settings too but with this i am getting 400 bad request error...
Please see both the screenshot... I am struggling on this issue from last 3/4 days
![image](https://user-images.githubusercontent.com/57327730/72665695-eef38780-3a30-11ea-96ae-157c9ff6acc4.png)
![image](https://user-images.githubusercontent.com/57327730/72665719-00d52a80-3a31-11ea-912b-9fc2656306d9.png)

**Comment by brasseld** [comment]
Please check the browser console for a more understandable message to see what's wrong here.

**Comment by deepak21singh** [comment]
i have see the following on console...is this OK ? if not how to correct this... when i am hitting api directly then i have no issue... but when i m using gateway i have issues
![image](https://user-images.githubusercontent.com/57327730/72666056-8b6b5900-3a34-11ea-838d-a208d791d8c5.png)

**Comment by brasseld** [comment]
Can you provide the complete OPTIONS request done by the browser ?

**Comment by deepak21singh** [comment]
I have enabled CORS on gateway as shown above... following is the complete OPTIONS request shown on the browser 
![image](https://user-images.githubusercontent.com/57327730/72666372-8956c980-3a37-11ea-8378-225c0efe267d.png)

**Comment by deepak21singh** [comment]
It seems i am missing something on the gateway...

**Comment by brasseld** [comment]
Don't know how you configure / send the request from your app but it seems to be wrongly done...

No need for allow-credentials in access-control-request-headers...

**Comment by deepak21singh** [comment]
I tried with all option but no luck....following is the code... 
const loginRequest = { 				        
usernameOrEmail : loginRequest1.usernameOrEmail,
password : password,
}
						
var headers1 = {
'Accept': 'application/json',
'Content-Type':'application/json',					
'Authorization': 'Bearer eyJraWQiOiJkZWZhdWx0LWdyYXZpdGVlLUFNLWtleSIsImFsZyI6IkhTMjU2In0.eyJzdWIiOiJBZGl0eWFCaXJsYUNsaWVudElkIiwiYXVkIjoiQWRpdHlhQmlybGFDbGllbnRJZCIsImRvbWFpbiI6ImFkaXR5YWJpcmxhZG9tYWluIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDkyL2FkaXR5YWJpcmxhZG9tYWluL29pZGMiLCJleHAiOjE1NzkzNjcyOTksImlhdCI6MTU3OTM2MDA5OSwianRpIjoib201cXlGS2x3YnI5RkhESlpHZldtbm9US093In0.8eKUu-g-3gyCqhN8I7cO1WVBwn9ULbDKmcPeBNdxPTg',
'crossOrigin': true,
'Access-Control-Allow-Origin': '*',						
'Access-Control-Allow-Methods': 'HEAD,OPTIONS,GET,POST,PUT,PATCH,DELETE',
'Access-Control-Allow-Headers':'Authorization,X-Requested-With,Origin,Content-Type, Accept, x-device-user-agent, Content-Type',
						//'Access-Control-Allow-Credentials': true,
}
axios.post(API_BASE_URL_GATEWAY + "/signinTest",loginRequest,{headers:headers1})
             .then(response => {

**Comment by brasseld** [comment]
Please remove those headers cause they are useless and it's up to the browser to ask for them.

* crossOrigin
* Access-Control-Allow-Origin
* Access-Control-Allow-Methods
* Access-Control-Allow-Headers
* Access-Control-Allow-Credentials

**Comment by deepak21singh** [comment]
Removed but still the same error... :(

var headers1 = {
						'Accept': 'application/json',
						'Content-Type':'application/json',					
						'Authorization': 'Bearer eyJraWQiOiJkZWZhdWx0LWdyYXZpdGVlLUFNLWtleSIsImFsZyI6IkhTMjU2In0.eyJzdWIiOiJBZGl0eWFCaXJsYUNsaWVudElkIiwiYXVkIjoiQWRpdHlhQmlybGFDbGllbnRJZCIsImRvbWFpbiI6ImFkaXR5YWJpcmxhZG9tYWluIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDkyL2FkaXR5YWJpcmxhZG9tYWluL29pZGMiLCJleHAiOjE1NzkzNjcyOTksImlhdCI6MTU3OTM2MDA5OSwianRpIjoib201cXlGS2x3YnI5RkhESlpHZldtbm9US093In0.8eKUu-g-3gyCqhN8I7cO1WVBwn9ULbDKmcPeBNdxPTg',
						//'crossOrigin': true,
						//'Access-Control-Allow-Origin': '*',						
						//'Access-Control-Allow-Methods': 'HEAD,OPTIONS,GET,POST,PUT,PATCH,DELETE',
						//'Access-Control-Allow-Headers':'Authorization,X-Requested-With,Origin,Content-Type, Accept, x-device-user-agent, Content-Type',
						//'Access-Control-Allow-Credentials': true,
					}		
				axios.post(API_BASE_URL_GATEWAY + "/signinTest",loginRequest,{headers:headers1})
				
                .then(response => {

![image](https://user-images.githubusercontent.com/57327730/72666641-71347980-3a3a-11ea-9ac6-a4917abe5457.png)

**Comment by deepak21singh** [comment]
preflight request is not going through...it seems to me that Gateway is not sending the right response to preflight request...please see this in gateway context too...

**Comment by brasseld** [comment]
Please provide an export of the api

**Comment by deepak21singh** [comment]
how to export...please suggest

**Comment by deepak21singh** [comment]
This is sorted out... closing the issue
