### ISSUE TITLE
Allows to override the claim to read for the log of the end user not released in 1.30.x

### ISSUE THREAD

**Issue by DaspawnW** [gravitee-io/issues#3120]
### Expected Behavior
The frontend should show in plans secured by JWT a field called userClaim to overwrite the user claim, as implemented in #2741

### Current Behavior
This field is not visible and the version seems to be before the feature.

### Possible Solution
Upgrade the plugin and add it to the releases.

### Steps to Reproduce (for bugs)
1. Create a plan click through it until you arrive at "Secure" tab
2. there select "JWT" as Authentication type, you should see now a field called User Claim

### Context
The feature was implemented as already mentioned in  #2741 and officially released in 1.30.0 as described in the Changelog https://github.com/gravitee-io/issues/blob/master/CHANGELOG.adoc
```
Policy
    [jwt] Allows to override claim to read for the log of the end user #2741
```
In the "plugins" directory for the management-api docker image there is the zip file in version gravitee-policy-jwt-1.13.0.zip available. This one was generated before the feature implementation.

### Your Environment

*Docker image: graviteeio/management-api:1.30.2

**Comment by NicolasGeraud** [comment]
Hi, indeed there was an error during the release.

I'm going to add it in the next 1.30.3
