### ISSUE TITLE
Analytics for API shows no data | Message: no data to display

### ISSUE THREAD

**Issue by IvoIlic95** [gravitee-io/issues#3127]
Hello

I have a issue:

I have created a API by using a Swagger descriptor. Then I created a API plan and subscribed to it with my application. After that I clicked on the analytics button from the imported API. And it only shows me this (either nothing (no graphs) or no data to display):

![image](https://user-images.githubusercontent.com/59047274/72875672-124e5900-3cf5-11ea-8512-92958e7e401c.png)

Could it be that the API is doing nothing, and because of that it can't show me anything in the analytics panel or is there a another cause for it? But the API is getting requests but not frequently.

The Management-Api is throwing this error in the log:

[Management_Api_Log.txt](https://github.com/gravitee-io/issues/files/4096433/Management_Api_Log.txt)

Update: I looked into my Elasticsearch and there were many indices available. Is it possible that Gravitee.io gets confused with so many indices so that it can't calculate the analytics?

![image](https://user-images.githubusercontent.com/59047274/72879926-2cd90000-3cfe-11ea-896d-6e7d0667f757.png)

Kind regards,
Ivo Ilic

**Comment by aelamrani** [comment]
Hi @IvoIlic95 

Do you have errors on the startup logs?

**Comment by IvoIlic95** [comment]
Well on the startup there are no errors.
The only errors that I am getting are these and the errors from the previous file that I attached to my issue:
[Management_Api_Log.txt](https://github.com/gravitee-io/issues/files/4096599/Management_Api_Log.txt)

It says that there is a error with the freemarker template.

**Comment by aelamrani** [comment]
If you don't have calls on your API, it's normal not to have data. But the error here is strange.

**Comment by IvoIlic95** [comment]
One of my colleagues said to me, that the API that I have included is only getting new requests, if any. 
But these requests should get visualized by the Gravitee.io analytics tool or not? I set the time for the past 90 days so that any log data could be found.

Which error:  The freemarker template error or the unable to search error or retrieve logs error (Elasticsearch) ? :)

**Comment by aelamrani** [comment]
I meant the first logs: `io.gravitee.repository.analytics.AnalyticsException: Impossible to perform log request...`

**Comment by IvoIlic95** [comment]
I think this error occured because my Elasticsearch and Kibana crashed. I had to restart it and therefore, the possibility is high that this error comes from this cause.

What is this freemarker template error?

**Comment by aelamrani** [comment]
ATM, you have no data on your dashboards because you do not have requests passing through the API Gateway. The configuration of ElasticSearch seems to be OK as i can see gravitee-monitor* data. But you should have data on the indice gravitee-request* for your requests and according to your screenshot that's not the case.

**Comment by IvoIlic95** [comment]
Hmm okey, but after looking at my Elasticsearch indices I can't see any "gravitee-request" which you mentioned me. How can I get this indice or does Elasticsearch create automatically this indice?

**Comment by brasseld** [comment]
You already asked the same question in your previous issue.

This log is not relevant and we probably have to change the log level to DEBUG.
