### ISSUE TITLE
[portal] Position of the plus sign on the policies page

### ISSUE THREAD

**Issue by AnselmeDewavrin** [gravitee-io/issues#314]
I think the plus sign that allows to add a context path would be better understood if placed in the center part of the page, in the context path zone

Yours,
Anselme

**Comment by NicolasGeraud** [comment]
Something like that ?
<img width="1905" alt="capture d ecran 2016-11-14 16 51 53" src="https://cloud.githubusercontent.com/assets/1028285/20271337/c200668c-aa8a-11e6-8262-ef42550d8346.png">

Hum ... i'm not sure it's better. (but it's only my pov)

**Comment by brasseld** [comment]
On which button should I click when the screen is containing so many buttons ?

<img width="495" alt="capture d ecran 2016-11-14 a 16 57 43" src="https://cloud.githubusercontent.com/assets/133094/20272654/e155f304-aa8e-11e6-9ba3-99b1dc35f3a2.png">

**Comment by NicolasGeraud** [comment]
do you want to save the configuration, add a new header or add a new path ?

just kidding, I'm agree.

But i'm not sure that moving the (+) button will resolve the problem.

**Comment by brasseld** [comment]
Should be closed by https://github.com/gravitee-io/issues/issues/3895
