### ISSUE TITLE
[elasticsearch] retention period

### ISSUE THREAD

**Issue by tpenne** [gravitee-io/issues#3151]
Hi, I don't have any issue but just a simple question regarding elasticsearch repository.

What is the retention period defined by gravitee (after how much time does gravitee remove old data), if any ?

Thank you in advance
Kind regards

Thomas

**Comment by brasseld** [comment]
Please have a look to:

* https://docs.gravitee.io/apim_installguide_repositories_elasticsearch.html#index_management_with_es_curator
* https://github.com/gravitee-io/issues/issues/2975

**Comment by tpenne** [comment]
Thank you for the pointers. 
If I understand your documentation correctly, it means that gravitee will never remove anything from elasticsearch unless I install curator, right ?

If that's the case, that's fine by me as I need to keep at least one year of history and I can manage "manual" removal after this period.

Thank you

**Comment by kevinimbrechts** [comment]
Hi @tpenne. Yes, you're right.
Gravitee doesn't remove anything from ES.

**Comment by brasseld** [comment]
As you have the other pointers (issue ref + docs), may I close the issue ?

**Comment by tpenne** [comment]
Hi @brasseld, 
as @kevinimbrechts confirmed my thoughts you can indeed close this issue.
Kind regards
