### ISSUE TITLE
[management][identity-provider] Improve IdentityProvider CRUD in administration UI

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#3155]
- [x] Allow the creation of new types of IdP in the UI and not only with gravitee.yml : Memory, LDAP, Gravitee
- [x] If defined in gravitee.yml, new IdP should be created in database at startup (like other types and with the same rules).
- [x] Order providers list
- [ ] When created in the UI, new kinds of IdP should be dynamically loaded. 
- [ ] Add a "Test connection" button for LDAP provider (nice to have)

**Comment by phiz71** [comment]
PRs are dependant of #3973, #3976 and #3963

**Comment by aelamrani** [comment]
It could be good to have some explanations about how the ldap auth is working internally in our documentation: 

- When creating an account, the role (here ADMIN) will be searched for in the Organization scope, and it exists for the user. Then the same research will be carried out on the Environment scope. If a role with this name exists, it will be assigned to the user. It is not possible to manage the organization and the environment separately. (It is still possible to create ad hoc roles in the targeted areas to obtain the desired rights).

- If the setting is changed in the yaml, the change will impact 'new' users (those who are connecting for the first time). The change will not be retroactive for users who have already logged in.
