### ISSUE TITLE
[gateway] Support for Stomp-js

### ISSUE THREAD

**Issue by adubreuiltk** [gravitee-io/issues#3163]
Stomp.js is unable to connect to a stomp server if located behind Gravitee (may be related to #3026 and #3051)

### Expected Behavior
Any STOMP-over-websocket client should be able to connect to the server through Gravitee.

### Current Behavior
Unable to properly open a STOMP connection.

### Steps to Reproduce (for bugs)
1. Install a STOMP server (ex : [ActiveMQ Artemis](https://activemq.apache.org/components/artemis/download/))
2. Enable STOMP-over-websocket (see [here](https://activemq.apache.org/components/artemis/documentation/latest/stomp.html))
3. Run the node.js test application (update first the URL)
[gravitee-ws.zip](https://github.com/gravitee-io/issues/files/4125430/gravitee-ws.zip)

If it can help, I can grant you a private and temporary access to our stomp server.

### Your Environment
* Version used: 1.30.1
* Browser Name and version: n/a
* Operating System and version: Debian 10

**Comment by brasseld** [comment]
Hi @adubreuiltk 

Thanks for the reproducer.

For sure if you can provide a temporary access to your stomp server, it would be easier to reproduce the issue (and hopefully, to fix it).

Can you send me an email to david.brassely (at) graviteesource.com with all the required informations ?

**Comment by gianx89** [comment]
I have the same problem with the latest version of stom.js (5.4 I think) and stomp server implemented with Spring Boot 2.3.0

**Comment by brasseld** [comment]
Fixed by https://github.com/gravitee-io/issues/issues/4060
