### ISSUE TITLE
[Api-management] no data to display in gateway monitoring and no more api logs

### ISSUE THREAD

**Issue by OlivierFt** [gravitee-io/issues#3172]
Bonjour,
depuis cette nuit (à partir de 1:00) nous n'avons plus de logs de nos APIS affichés dans le portail api management. Nous avons accès aux logs antérieurs par contre.
De plus, dans la partie Gateway monitoring, il n'y a aucun indicateur, pourtant la passerelle est bien démarrée et marquée active.

Nous avons redémarré aussi bien la passerelle, que l'api management ainsi que l'elastic search. Rien n'y change!

Version 1.25.10 / Centos

**Comment by brasseld** [comment]
Any logs from the management-api or the gateway here ?

**Comment by aelamrani** [comment]
I close this ticket because we discovered that the problem was due to insufficient space on the machine hosting Elasticsearch
