### ISSUE TITLE
[management] [dcr] Unable to change app info with using DCR

### ISSUE THREAD

**Issue by MariaPushkin** [gravitee-io/issues#3180]
Hello again! I'v created a client with the grant client_credentials through the registration endpoint. Then I wanted to change some info about application, but got HTTP-500 error. Research showed that keycloak verify client_id from PUT-request uri (`registration_client_uri` from registration response) and client_id in request-body, but gravitee does't put client id into the update request.

### Possible Solution
Add client_id of current client to body of update request.

### Steps to Reproduce (for bugs)
1. Add registration provider
2. Create client through the registration endpoint
3. Try to change client info 

### Your Environment
* Version used: 1.30.2

**Comment by brasseld** [comment]
Hi @MariaPushkin 

Which version of keycloak?

**Comment by MariaPushkin** [comment]
As I understand we use versions from 4.7.0 to 4.8.3. Depends on environment.

**Comment by MariaPushkin** [comment]
Hi @brasseld 
Just wondering if here any updates.
According to [RFC-7592](https://tools.ietf.org/html/rfc7592#page-7) (section 2.2.  Client Update Request): 

> The client MUST include its "client_id" field in the request, and it
>    MUST be the same as its currently issued client identifier.

So, I think it anyway makes sense to add client_id to the request.
