### ISSUE TITLE
[policy] [cache] Path and cache policy for GET method

### ISSUE THREAD

**Issue by AudricCh** [gravitee-io/issues#3183]
Hello there,

We are trying to use the cache policy on some GET endpoints but we've got some questions.
Imagine that we have an endpoint GET with two parameters : paramA and paramB which are integers at the endpoint called "myEndpoint".

I don't understand why when we put a the key parameter at a simple string value like this
![image](https://user-images.githubusercontent.com/25503027/73549511-02e0b580-4443-11ea-9820-719180d0b3a3.png)

In this case, the cache doesn't depends of the paramA and paramB parameters, but the URL is unique because of them -> "http://myUrl.com/myEndpoint?paramA=1&paramB=2"

So it's should be logical that automatically, when the endpoint is used with different parameters, the cache system store in function of the differents parameters

### Expected Behavior
- GET cache should automatically understand that if we have a different parameter from the cache, that's not the same cache

### Current Behavior
If I put in the key parameter "toto", there is what is going to be :
"http://myUrl.com/myEndpoint?paramA=1&paramB=2" -> OK return the good data and store it in cache
"http://myUrl.com/myEndpoint?paramA=2&paramB=2" -> NOK, return the data in cache but parameters are differents
"http://myUrl.com/myEndpoint?paramA=4&paramB=5" -> NOK, return the data in cache but parameters are differents

So to do this works, I need to precise in the key all my params on it.
The key looks like : 

> {#request.params['paramA']}{#request.params['paramB']}

Now imagine that we have 20 possible parameters, or we change the API signature and forget to change the cache key..

### Possible Solution
It's evident that a GET method with differents parameters should not be store at the same place in the cache system, isn't ?

### Context
Create a resource
Create a policy
Put a "toto" string in key parameter of the cache
Call the API endpoint GET with differents parameters

It's more a question than a bug or something else by the way.
Thanks 👍

**Comment by brasseld** [comment]
If you need such behavior, just leave the key empty :)

Cheers,

**Comment by AudricCh** [comment]
Hum, I just tried and that's not correct.
It seems like it the same case that my "Current Behavior" test explanation before.

With no key, the first call send me the good information depending of my given parameters, then the next call with different parameters send me previous data which depend of the first call parameters and not the second ones...

**Comment by brasseld** [comment]
yes, correct

**Comment by AudricCh** [comment]
I'm confused, what is the solution then ?

**Comment by brasseld** [comment]
The only one is to managed query-parameters individually.

The policy should be improved to take care about all the parameters and not only the path.

**Comment by AudricCh** [comment]
Ok, well, what's the maximum length of the key then ?

Because if the only way is to have all GET parameters on it, and we have frequently more than 5-6 parameters, I want to be sure that's possible and the length is sufficiant to do like this (for example in GET method of car object) :

`{#request.params['model']}-{#request.params['brand']}-{#request.params['power']}- {#request.params['seats']}-{#request.params['color']}-{#request.params['isAutomatic']}`

The other way I understand with your message is that I have to create a cache policy for each parameter ? I think I misunderstand you but if it's that you told me, then I guess it will work only if the parameters are not combinable, and that's not my case (like the car example).

Thanks

**Comment by AudricCh** [comment]
> Ok, well, what's the maximum length of the key then ?
> 
> Because if the only way is to have all GET parameters on it, and we have frequently more than 5-6 parameters, I want to be sure that's possible and the length is sufficiant to do like this (for example in GET method of car object) :
> 
> `{#request.params['model']}-{#request.params['brand']}-{#request.params['power']}- {#request.params['seats']}-{#request.params['color']}-{#request.params['isAutomatic']}`
> 
> The other way I understand with your message is that I have to create a cache policy for each parameter ? I think I misunderstand you but if it's that you told me, then I guess it will work only if the parameters are not combinable, and that's not my case (like the car example).
> 
> Thanks

Hi, do you have some answers for me according to my last post ?
Thanks
