### ISSUE TITLE
Hi @IvoIlic95

### ISSUE THREAD

**Issue by Maurotezzzt** [gravitee-io/issues#3194]
Hi @IvoIlic95 

> But I still can't come to the Portal UI where I can login into the Gravitee Tool.

What is the issue exactly ?
Blank screen
Screen a red message
Not able to connect...

_Originally posted by @brasseld in https://github.com/gravitee-io/issues/issues/3101#issuecomment-575168513_

Hello @IvoIlic95, in my case, that the black screen remains, with red letters and with the gravitee-management-api service with problems when uploading "JVM Runtime does not support Modules"
I have java 1.8 installed
I am upgrading from 1.27 to 1.30.1

20:46:23.621 [graviteeio-node] INFO  i.g.m.s.impl.UpgraderServiceImpl - Running upgrader io.gravitee.management.service.impl.upgrade.DefaultApiHeaderUpgrader
20:46:23.628 [graviteeio-node] INFO  i.g.m.s.impl.UpgraderServiceImpl - Running upgrader io.gravitee.management.service.impl.upgrade.IdentityProviderUpgrader
20:46:23.629 [graviteeio-node] INFO  i.g.m.standalone.node.ManagementNode -     Starting component: AlertTriggerProviderManager
20:46:23.629 [graviteeio-node] INFO  i.g.common.service.AbstractService - Initializing service Alert Engine - Trigger provider manager
20:46:23.629 [graviteeio-node] INFO  i.g.p.a.i.AlertTriggerProviderManagerImpl -        There is no trigger provider to start
20:46:23.629 [graviteeio-node] INFO  i.g.m.standalone.node.ManagementNode -     Starting component: AlertEventProducerManager
20:46:23.629 [graviteeio-node] INFO  i.g.common.service.AbstractService - Initializing service Alert Engine - Event producer
20:46:23.629 [graviteeio-node] INFO  i.g.p.a.i.AlertEventProducerManagerImpl -  There is no event producer to start
20:46:23.630 [graviteeio-node] INFO  i.g.m.standalone.node.ManagementNode - Gravitee.io - Management API id[4c0b361e-f904-4299-8b36-1ef904e29914] version[1.30.1] pid[10124] build[662#32022c2fbf98ef140de6755f50c578122f23fc5a] jvm[Oracle Corporation/OpenJDK 64-Bit Server VM/25.212-b04] started in 67039 ms.
20:46:30.769 [gravitee-listener-57] INFO  org.eclipse.jetty.util.TypeUtil - JVM Runtime does not support Modules
20:49:54.564 [graviteeio-finalizer] INFO  i.g.m.standalone.ManagementContainer - Shutting-down Gravitee.io - Management API...
20:49:54.564 [graviteeio-finalizer] INFO  i.g.m.standalone.node.ManagementNode - Gravitee.io - Management API is stopping
20:49:54.568 [graviteeio-finalizer] INFO  i.g.m.standalone.node.ManagementNode -        Stopping component: AlertEventProducerManager
20:49:54.568 [graviteeio-finalizer] INFO  i.g.common.service.AbstractService - Destroying service Alert Engine - Event producer
20:49:54.568 [graviteeio-finalizer] INFO  i.g.m.standalone.node.ManagementNode -        Stopping component: AlertTriggerProviderManager
20:49:54.568 [graviteeio-finalizer] INFO  i.g.common.service.AbstractService - Destroying service Alert Engine - Trigger provider manager
20:49:54.568 [graviteeio-finalizer] INFO  i.g.m.standalone.node.ManagementNode -        Stopping component: InitializerService

**Comment by brasseld** [comment]
Hi @Maurotezzzt 

What's the purpose of this issue?

**Comment by Maurotezzzt** [comment]
Hi @brasseld 
the purpose was to update my gravitee
the purpose was to update my gravitee

update the gravitee version from 1.27 to 1.30.1.

You know why this error occurs

**Comment by brasseld** [comment]
No issue here, closing the issue.
