### ISSUE TITLE
[management] After creating an application its possible to list all users

### ISSUE THREAD

**Issue by afasseco** [gravitee-io/issues#3197]
When giving an authenticated user the right to create an application the user will be granted the PRIMARY_OWNER role on that application. The PRIMARY_OWNER has all rights to that application including adding members and transferring ownership. Those two functions allow searching the users which allows the user to enumerate all users by id and name.

Since the management of members of an application stems from being PRIMARY_OWNER and that it is not possible to change the permissions on the PRIMARY_OWNER role then the MEMBER permission cannot be removed.

### Expected Behavior
That it should be possible to restrict seeing the usernames of other users in the system.

### Current Behavior
Its possible to search the all the users and see the usernames.

### Possible Solution
Would expect that it is either possible to remove the MEMBER permission from the PRIMARY_OWNER role OR that the search function can be disabled (maybe adding users by id only?)

### Steps to Reproduce (for bugs)
1. Create application
2. Click members
3. type a letter in transfer membership box or add a user and type a letter
4. Users beginning with that letter are shown

### Context
Usernames are as such not private but being able to search across the user base might reveal information that API producer does not want shared. If gravitee is being used by an API producer then it can be the case that the API producer does not want the API consumers to be able to list all other users (that can either be subscribed or not)

### Your Environment
* Version used: 1.30.2
* Browser Name and version: n/a
* Operating System and version: n/a

**Comment by brasseld** [comment]
Hi @afasseco 

Here is a short description of what we have in mind for this issue.

We'll had a new option at the group level to enable / disable user search.
Users from this particular group will be able to search for the others only if search option is enabled.

It means also that you have to manage correctly groups within Gravitee.

What do you think?

**Comment by afasseco** [comment]
Hi @brasseld 

Thanks for getting back to me.

I think your suggestion would work fine - its similar to the "Allows invitation via user search" role there already?

Our use case is that customers are signing up for private api-key and that each customer should not be able to see the other customers. Therefore both the transfer ownership and add member scenarios do not make sense to us.

On api level I think this access right should be tied to the /management/search/users/ endpoint, right? We had to close off access to this endpoint on the network level to work-around not being able to close off this access to users.

**Comment by brasseld** [comment]
> I think your suggestion would work fine - its similar to the "Allows invitation via user search" role there already?

Yes, exactly

> Our use case is that customers are signing up for private api-key and that each customer should not be able to see the other customers. Therefore both the transfer ownership and add member scenarios do not make sense to us.

Yes, but even if transfer ownership and add member scenarios are not allowed to the application's primary owner, the API still permits to search for users...

> On api level I think this access right should be tied to the /management/search/users/ endpoint, right? We had to close off access to this endpoint on the network level to work-around not being able to close off this access to users.

Great, I got your point, thanks for sharing.
