### ISSUE TITLE
[gateway] Virtual host support

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#3199]

**Comment by jhaeyaert** [comment]
Reminder:
- [ ] Manage path and virtual host mode switch in a dedicated UI screen (like APIM does). [UI]
- [ ] Adapt domain modelisation to handle path and vhost mode. [API/Model]
- [ ] Handle domain virtual hosts at routing level. [Gateway]
- [ ] Make sure that all plugins handle virtual host.
- [ ] Adapt redirections when virtual host is used. [Gateway]
- [ ] Adapt Cookie path when virtual host is used. [Gateway]
