### ISSUE TITLE
[WEB UI] Quality checks are confusing

### ISSUE THREAD

**Issue by RTabary** [gravitee-io/issues#3201]
A passed check is striped, i could means that it's not passed.

### Expected Behavior
Clearly identify a passed check or a failed one

### Current Behavior
A passed check is striped

### Possible Solution
Add icon instead of current behavior

### Your Environment
* Version used: gravitee 1.30.2

**Comment by romsDKT** [comment]
Here is the result

![image](https://user-images.githubusercontent.com/47742357/73931449-9ea57200-48d8-11ea-8efa-8c8540b92423.png)

**Comment by NicolasGeraud** [comment]
hi @RTabary 
sorry for this loooooong review 👍
