### ISSUE TITLE
Gravitee JWT authentication is not working

### ISSUE THREAD

**Issue by yogeshgarg1904** [gravitee-io/issues#3202]
Hi,
We have created the application and subscribed to the plan, but the token is not validating.
Please help

![image](https://user-images.githubusercontent.com/15274040/73912639-08bf1680-48db-11ea-8392-fd98578a7eed.png)

![image](https://user-images.githubusercontent.com/15274040/73912559-cbf31f80-48da-11ea-89a6-ced6694ba4f9.png)

![image](https://user-images.githubusercontent.com/15274040/73912702-3310d400-48db-11ea-961a-c4bbd633424b.png)

**Comment by romsDKT** [comment]
Hi, 
Bearer is case sensitive.

**Comment by yogeshgarg1904** [comment]
HI,
I tried with authorization tab but result is still the same.
![image](https://user-images.githubusercontent.com/15274040/74122041-d28dd980-4bef-11ea-87b5-d13176980691.png)

**Comment by aelamrani** [comment]
Please use a longer secret

**Comment by yogeshgarg1904** [comment]
Hi,

We have used the longer secret key bu the result is same.

![image](https://user-images.githubusercontent.com/15274040/74138956-860ac400-4c18-11ea-93b2-4fefd790bda9.png)

**Comment by aelamrani** [comment]
Can you please try to reproduce on the demo env?

https://demo.gravitee.io (admin/admin)

**Comment by yogeshgarg1904** [comment]
We have configured the EmployeeAPI on Demo env, but while accessing the api it showing access denied error.
Please help and let me know where I am going wrong

![image](https://user-images.githubusercontent.com/15274040/74147735-dd656000-4c29-11ea-921a-0de27586672d.png)

![image](https://user-images.githubusercontent.com/15274040/74147876-21586500-4c2a-11ea-93ad-1b66990a6ff4.png)

**Comment by aelamrani** [comment]
I just had a try and everything is working as expected.

How did you generate your token?

Here is the mine.
<img width="1288" alt="Capture d’écran 2020-02-10 à 14 00 20" src="https://user-images.githubusercontent.com/1580262/74152050-c57fe300-4c0d-11ea-9cab-4c2990d683fe.png">

**Comment by Ritubansal123** [comment]
It is resolved.
Thank you so much !

**Comment by aelamrani** [comment]
You are welcome
