### ISSUE TITLE
[management] Widget timeline does not display the API names correctly

### ISSUE THREAD

**Issue by djo54150** [gravitee-io/issues#3205]
Lors que nous essayons d’agréger les temps de réponses d'api, nous avons bien les courbes agréger et de couleur. Mais la légende les appellent tous API.

### Expected Behavior
Avoir les nom des APIS

### Current Behavior
Tous le Nom API mais de couleur différente

### Possible Solution
Je ne sais pas

### Steps to Reproduce (for bugs)
Creer 2 /3 apis , faire des hits. 
Ensuite créer un dashboard en ligne pour la latency  et par API

### Context
Ce graphe est important afin de pouvoir monitorer tous les API d'un seul regard et voir laquelle est la moins performante.

![image](https://user-images.githubusercontent.com/22770478/73981864-7a2ab380-4933-11ea-85da-fa8d1d6040fe.png)
![image](https://user-images.githubusercontent.com/22770478/73981980-b5c57d80-4933-11ea-8984-32cbf9faa02f.png)

**Comment by brasseld** [comment]
Did you manage to reproduce the issue on demo env ?

https://demo.gravitee.io/

**Comment by djo54150** [comment]
Bonjour , 

Tu peux regarder le Dashboard issue 3205 dans l'env démo.


bàt,
Jonathan
