### ISSUE TITLE
[expression-language] Add support of XPath for internal expression language

### ISSUE THREAD

**Issue by faraday-m** [gravitee-io/issues#3211]
This time there is a support of JsonPath in gravitee-expression-language plugin. 
With spring-integration-xml library, XPath expressions can be integrated as xpath function. 
I suppose it can be implemented with adding one line to SpelTemplateContext class, something like:
`context.registerFunction("xpath", BeanUtils.resolveSignature("evaluate", XPathUtils.class));`
and adding a dependency for Spring Integration library. 

More info: https://docs.spring.io/spring-integration/reference/html/xml.html#xml #

**Comment by brasseld** [comment]
Hi @faraday-m 

Do you want to provide a PR ?

**Comment by faraday-m** [comment]
Up

**Comment by brasseld** [comment]
Will be part of the next 1.30.6

Thanks for your contrib!
