### ISSUE TITLE
[policy] [jwt] sub claims is mandatory

### ISSUE THREAD

**Issue by djo54150** [gravitee-io/issues#3218]
Bonjour, 

Contexte: 
j'ai ajouté la policy JWT à une API. 
![image](https://user-images.githubusercontent.com/22770478/74339285-14f81780-4da4-11ea-8929-63b74268bf70.png)

J'ai bien alimenté la clé et cela fonctionne sans problème avec un JWT avec un claim sub.

Par contre si j’enlève ce claim ou si je met `sub : "" `, j'obtiens un 401. 

Normalement le subject dans le JWT n'est pas obligatoire. 

Je pense qu'il s'agit d'un bug.

Procédure de reproduction; 

Ajouté sur une api la policy JWT. 
Faire un call avec un JWT sans le claims sub.

Réponse reçue: 
401

Réponse souhaitée:
Le call fonctionne

WA possible: 
Ajouter un sub dans le JWT. 
LE problème est que ça impact les clients.

Solution possible: 
Rendre le claim sub non obligatoire.

Merci,
Jonathan

**Comment by brasseld** [comment]
The sub is not required.

You get a 401 because you don't have a subscription to the plan for the given sub, azh or client_id.

**Comment by djo54150** [comment]
Hello , 

I have a KEYLESS Plan.  So we don't need a subscription.

Regards,
Jonathan
