### ISSUE TITLE
[management] Is there any information about the API lifecycle?

### ISSUE THREAD

**Issue by IvoIlic95** [gravitee-io/issues#3219]
Hello

As in the title mentioned: Is there any information about the Gravitee.io API lifecycle?
It would be cool if someone of the developers, could provide a description or an illustration about the Gravitee.io API lifecycle.

Kind regards,
Ivo Ilic, BSc

**Comment by brasseld** [comment]
The state are as follow:

CREATED, PUBLISHED, UNPUBLISHED, DEPRECATED, ARCHIVED
