### ISSUE TITLE
[management-api] Create api from a WSDL

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#322]
Allow to create an api with views

**Comment by brasseld** [comment]
In a more global way, I think we have to review the "creation" process where we must being able to provide all the "major configuration" of an API through several creation steps.

This process will be called for these scenario: 
* New API from scratch
* Import Swagger 
* Import existing definition
* Import a WSDL (?)

The steps would be as follow:
* General information (name, version)
* Gateway information (context-path, default target)
* Plans (to create an initial plan)
* Members (if we are importing an existing definition, select members to import)
* Documentation (if we are importing an existing definition, select pages to import / if we are importing a Swagger, create the swagger page)

**Comment by deka** [comment]
+1 pour l'import wsdl

**Comment by bielesibub** [comment]
Hi there, are there any plans on implementing a SOAP WSDL based API to gravitee? I acknowledge that this comes with a multitude of complexities, not least of which my least favourite WS-Security!
In addition do you have a features/enhancements road map?
Thanks in advance,

**Comment by brasseld** [comment]
Hi @bielesibub 

The goal here is mainly to automatically transform a given WSDL (imported WSDL) to a restful API.

**Comment by brasseld** [comment]
What is missing:
* Transform xml to json on the response
* Detect correct verb (post / put / get). For example, if the operation starts with `get` or `find` we can assume a GET method. If the operation starts with `update`, we can assume a PUT, etc...
