### ISSUE TITLE
Where to get performance test report for Gateway?

### ISSUE THREAD

**Issue by kitepad** [gravitee-io/issues#3236]
I want to propose Gavitee to customer and they want to know performance of gateway, but I cann't find about it.

### Expected Behavior

Provide performance test report or test project which run by developer.

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Version used:
* Browser Name and version:
* Operating System and version:

**Comment by brasseld** [comment]
Hi @kitepad 

Unfortunately we are not providing any performance test report.
You can assume that you can manage up to 1.000 -> 10.000 requests per second depending on:
1) server sizing
2) performance of your backend apis.

Regards,
