### ISSUE TITLE
socket

### ISSUE THREAD

**Issue by vinothrichard** [gravitee-io/issues#3241]
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Version used:
* Browser Name and version:
* Operating System and version:

**Comment by brasseld** [comment]
Hey @vinothrichard 

Seems that some parts are missing there.

Please complete the issue.

**Comment by vinothrichard** [comment]
I do not know how is this created. May be a glitch in my computer. sorry for the incovenience caused
