### ISSUE TITLE
io.gravitee.gateway.policy.PolicyException: java.lang.reflect.InvocationTargetException on Oauth implentation

### ISSUE THREAD

**Issue by mehul1992** [gravitee-io/issues#3251]
Steps to regenerate the issue

1. Created client in Gravitee Access Management
2. Added user in Gravitee Access Management
3. Created API in Gravitee API management
4. Added Resource as oauth-am
5. Created PLAN with security type OAUTH
6. Got access token with the Access Management API /services/oauth/token?grant_type=password
7. Using the access token in the API it gives
{
    "message": "io.gravitee.gateway.policy.PolicyException: java.lang.reflect.InvocationTargetException",
    "http_status_code": 500
}

**Comment by aelamrani** [comment]
Can you please provide the stack trace on the API Gateway log file?
