### ISSUE TITLE
API key doesn't read the X-Gravitee-Api-Key when using with the OAuth policy 

### ISSUE THREAD

**Issue by ganesh993** [gravitee-io/issues#3252]
My Api key plan is working fine but as soon as i enable the oauth policy in the same Api 
I'm getting this error 

Code       |           Details
401                    Error: Unauthorized
                          Response headers: content-length: 0

To remove this error when i enable the api key policy in the same Api 
The error modify into 
{
"message": "No API Key has been specified in headers (X-Gravitee-Api-Key) or query parameters (api-         key).",
"http_status_code": 401
}

To remove this error i'm adding 
Transform Headers
Name: X-Gravitee-Api-Key
Value: api-key

but still the error is same

### Expected Behavior
X-Gravitee-Api-Key should be allowed and the Oauth2 policy should be added within the same api
without getting the 401 error.

### Current Behavior
Getting the error whenever i enable the OAuth2 policy for the Api that has already Api-Key plan.

### Steps to Reproduce (for bugs)
1.  Make a request by adding the X-Gravitee-Api-Key, this results in 401.

### Context
I want to use both Api-Key and the Oauth2 security within the same Api

### Your Environment
* Version used: 1.30.1
* Browser Name and version: Postman
* Operating System and version: Windows 10

**Comment by aelamrani** [comment]
Hi @ganesh993 
May i ask you to try to reproduce on the demo env? https://demo.gravitee.io (admin/admin)

Thanks

**Comment by ganesh993** [comment]
Error Solved...
Actually i was applying the Oauth2 policy  insteas of Oauth2 plan..
Thanks for help....
