### ISSUE TITLE
[gateway] Adding multiple APIs with same context path

### ISSUE THREAD

**Issue by IvoIlic95** [gravitee-io/issues#3258]
Hello 

Lets go right to my question: Is it possible to add multiple APIs with the same context-path but with different endpoints when creating an API from scratch. I tried to add two APIs with different endpoints (with the _from scratch_ editor) but with equal context-paths, unfortunately this resulted into a context-path already existing warning/error. 

Background info: I know from the Gravitee.io documentation that Gravitee.io creates the context-paths based on the swagger files. 

I would be happy if a possible solution exists.

Kind regards,
Ivo Ilic, B. Sc.

**Comment by brasseld** [comment]
Hi @IvoIlic95 

You can create multiple APIs based on the same context-path by using the virtual hosting feature.

For the moment, the `scratch editor` does not take care of this.
If you want to setup virtual-hosting, go to your API > Proxy > Entrypoints

**Comment by IvoIlic95** [comment]
Many thanks for the fast response!
