### ISSUE TITLE
[management-api] [fetcher] GitLab - access to non public project

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#326]
In documentation, i want to make a link to gitlab, but my project needs an authentification

**Comment by brasseld** [comment]
Some words about your need:

You want to create a new documentation page which is based on a GitLab repository (project) but this one needs an authentication (internal / private project).

Two options here:
* Use a technical account to clone the Git repository and use provided credentials
* Use a technical account to invoke the GitLab API to retrieve a single document (by using a path reference).

**Comment by NicolasGeraud** [comment]
I think we have to provide a gitlab fetcher. But where may we provide credentials ?
 - In the fetcher configuration 
   PROS : fine grained authorization
   CONS: we store sensitive datas, user must configure credentials on each page
- in the gravitee.yml
  PROS: used in all page, user don't have to give his credentials
  CONS: need a technical account on gitlab

I prefer the second solution, it will be mush easier to publish documentation pages

**Comment by vdelattre** [comment]
I add my comment:
If credential is store in gravitee.yml, it means that this technical account have access to all projects in gitlab.
If credential is in the fetcher, it can be different by project or groups in gitlab

**Comment by brasseld** [comment]
I'm agree with the second solution.

An other one would be to use define and user the concept of environnement and a hierarchy of "configuration" / "system properties"  around them.

Global configuration
 | - Properties
 | - Qualif env.
    | - Resources
    | - Properties
 | - Prod env.
    | - Resources
    | - Properties

In this cas, credentials can be part of Global configuration > Properties

**Comment by NicolasGeraud** [comment]
@vdelattre wdyt
<img width="505" alt="capture d ecran 2016-12-01 22 58 11" src="https://cloud.githubusercontent.com/assets/1028285/20814414/cd151a94-b819-11e6-968f-321cfe6c7a10.png">
