### ISSUE TITLE
[AM UI] unable to create an OIDC IdP

### ISSUE THREAD

**Issue by bcollard** [gravitee-io/issues#3261]
AM version: 2.10.9

When creating an OIDC IdP (/domains/{domain}/settings/providers/new), I cannot validate the form, even with all the fields having some value. The "CREATE" button stays disabled:

![image](https://user-images.githubusercontent.com/9626829/75385130-7d381480-58df-11ea-8915-6aaa602b8762.png)

**Comment by tcompiegne** [comment]
Hi @bcollard, yes OIDC provider is a bit tricky, especially with the JSON schema module : 

```
"oneOf":[
    {
      "required": [
        "wellKnownUri"
      ]
    },
    {
      "required": [
        "userAuthorizationUri",
        "accessTokenUri",
        "userProfileUri"
      ]
    }
  ],
  "if": {
    "properties": {
      "responseType": { "const": "code" }
    }
  },
  "then": { "required": ["clientSecret"] }
```

So if you have a well-known endpoint just set up the `Client ID`, `Client Secret` and `Well-Known Endpoint` and it should be OK.

**Comment by bcollard** [comment]
OK, got it, thank you!

**Comment by brasseld** [comment]
Hi @bcollard 

May we close this issue?

**Comment by bcollard** [comment]
yes, I guess :) thx
