### ISSUE TITLE
Changing the reset password link localhost:3000 

### ISSUE THREAD

**Issue by IvoIlic95** [gravitee-io/issues#3262]
Hello guys

My problem is as follows: I have configured a SMTP server to send reset password links and this kinda stuff. Unfortunately, the link that gets send is not valid [http://localhost:3000/#!/resetPassword/...], more precisely the **localhost:3000** is not valid so I have to change it manually every time which is quite cumbersome.  

Now the question is: Where do I can change this localhost:3000 default configuration?

Kind regards,
Ivo Ilic, B.Sc.

**Comment by IvoIlic95** [comment]
The issue was solved here: https://gitter.im/gravitee-io/gravitee-io?at=5df2f7edac14cc652c741185

**Comment by linhktqd** [comment]
> The issue was solved here: https://gitter.im/gravitee-io/gravitee-io?at=5df2f7edac14cc652c741185

pls help me to resolve it?
