### ISSUE TITLE
Gravitee API context-path / (without path) requested

### ISSUE THREAD

**Issue by MarkusNeviadomski** [gravitee-io/issues#3268]
I have an application that needs to provide an path <mydomain.com>/apple-app-site-association** available for apple deep linking is working.
Currently i use gravitee to secure and enable different API versions /clinet/v1, /client/v2, ... that works very smooth, but i havent't  found a solution

All is running in Kubernetes, so there is no possibility for me to seperate the traffic with any path to gravitee and the traffic without path to another workload providing necessary app site association files.

### Expected Behavior
Gravitee API contect / should be possible.

### Current Behavior
Gravitee Contect Path needs /xyz with minimum amount of 3 characters.

### Context
We provide currently 1, later different API's for a mobile solution that runs on iOS and Android devices. We use deep linking and in iOS Context, in domain root several files with base name apple-app-site-association must be available.

**Comment by pf-mike-breaton** [comment]
We encountered a similar scenario and resolved it by using another host name and using a request path rewriter in front of Gravitee to add the context prefix to the path.

`<myappsitedomain.com>/apple-app-site-association` => `<mydomain.com>/context/apple-app-site-association`

I think it would be useful if Gravitee could add 2 features:
1. `/*` context for handling all unknown requests
2. filtering for allowing reuse of the context path based on host name

**Comment by brasseld** [comment]
Hello guys,

> 1. `/*` context for handling all unknown requests

This is managed via a NOT_FOUND api handler and stored into metrics for reporting.

> 2. filtering for allowing reuse of the context path based on host name

This is already doable by using Virtual-Hosting at the API level.

**Comment by pf-mike-breaton** [comment]
> Hello guys,
> 
> > 1. `/*` context for handling all unknown requests
> 
> This is managed via a NOT_FOUND api handler and stored into metrics for reporting.
But is this exposed where it can be overridden and configured as an API?
> 
> > 1. filtering for allowing reuse of the context path based on host name
> 
> This is already doable by using Virtual-Hosting at the API level.
I did not know this, thanks!

**Comment by brasseld** [comment]
> > Hello guys,
> > > 1. `/*` context for handling all unknown requests
> > 
> > 
> > This is managed via a NOT_FOUND api handler and stored into metrics for reporting.
> 
> But is this exposed where it can be overridden and configured as an API?

What would you like to override ?

> 
> > > 1. filtering for allowing reuse of the context path based on host name
> > 
> > 
> > This is already doable by using Virtual-Hosting at the API level.
> 
> I did not know this, thanks!

You're welcome :)

**Comment by pf-mike-breaton** [comment]
> > > Hello guys,
> > > > 1. `/*` context for handling all unknown requests
> > > 
> > > 
> > > This is managed via a NOT_FOUND api handler and stored into metrics for reporting.
> > 
> > 
> > But is this exposed where it can be overridden and configured as an API?
> 
> What would you like to override ?
> 

an API to catch NOT_FOUND so plans can be applied and a default endpoint

**Comment by MarkusNeviadomski** [comment]
I found another workaround for the apple-app-site-association problem. Apple documentation tells me, that apple-app-site-association can be placed at / OR at /.well-know/ path.
https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html

So i did:
- create a workload with apple-app-site-association in root folder
- Create App in Gravitee with /.well-known as context
![image](https://user-images.githubusercontent.com/6367277/75772249-df63a000-5d4b-11ea-8bf1-584aa391dd97.png)

**Comment by brasseld** [comment]
👍 

can we consider this issue as closed ?

**Comment by MarkusNeviadomski** [comment]
@brasseld  For my requirements everything is working now. But @pf-mike-breaton  needs a explicit API listening on / without additional context i think.

**Comment by brasseld** [comment]
> > What would you like to override ?
> 
> an API to catch NOT_FOUND so plans can be applied and a default endpoint

So, as far as I understand, for all unmapped (unknown) requests (requests which don't match any context-path / virtual hosts), you're looking to apply a plan and call a default endpoint ? What would be the purpose of the endpoint in that case?

**Comment by pf-mike-breaton** [comment]
yes. depending on the requested path we will route to the appropriate service.

**Comment by brasseld** [comment]
Sorry, but I really don't understand.

Let's say you have 2 APIs defined:
- Api A listening on path `/apia`
- Api B listening on path `/apib` 

As far as I understand, you are receiving calls to `/unknown-api` and you're looking to apply plans and call default endpoint for this path, am I wrong ?

**Comment by pf-mike-breaton** [comment]
for calls to `/unknown-api` we'd just define a public (keyless) plan and forward to `http://legacy-services/*`

**Comment by brasseld** [comment]
But what's the purpose of `http://legacy-services/*` ?

**Comment by pf-mike-breaton** [comment]
That's our older environment that needs to handle non-standard paths still in use by external customers - things like `/<customer_id>/users`, where the context is non-deterministic without consulting business rules.

**Comment by pf-mike-breaton** [comment]
BTW, I'm not asking for a feature enhancement, just asking if it were possible. We do have workarounds. 

Thanks for the help!

You can close this issue if it were just my concerns keeping it open...
