### ISSUE TITLE
[management] Allow Only Code Grant For DC

### ISSUE THREAD

**Issue by zdenda-online** [gravitee-io/issues#3269]
We are using Gravitee for the PSD2 use-case (banking industry) and the only allowed flow is Code Grant (Authorization Code + Refresh Token). Currently, there are 5 types of applications that can be configured for DCR in Gravitee API Management. The closest one is Web (that we are using right now) but that would allow users to create an application also with Implicit which is not suitable for PSD2

### Possible Solution
Add application type (something like Secure Web) that would allow only Authorization Code and Refresh Token (not Implicit)
-or-
Allow creating custom type for DCR in administration - you can choose your own set of rules (ideally with possibility whether each item is selected by default or not)

**Comment by brasseld** [comment]
Hi @zdenda-online 

Given the fact that implicit grant flow is now considered as "deprecated", shouldn't it be better to say that Web application should be based on Auth Code by default (+ PKCE) ?

**Comment by zdenda-online** [comment]
Yep, that makes sense to remove implicit for Web actually.
However, I would probably suggest allowing Implicit grant in some other "backward compatibility" type of app = maybe add 6th application type called just "Implicit" with some warning if you choose it. I can imagine that there will be cases where Gravitee clients may want that.

PKCE is not necessary now I think :-)

**Comment by zdenda-online** [comment]
@brasseld Are there any plans in close future for this? Maybe I can try to contribute if you tell me in what repo I need to change that.
