### ISSUE TITLE
[management] APIM webui: adding members to APIs fails

### ISSUE THREAD

**Issue by tapiiron** [gravitee-io/issues#3271]
### Expected Behavior
When searching for user in API members tab I can add members to API.

### Current Behavior
The user base is from openid logins.
1) In API Members tab, click (+) and start typing member name.
2) Member is shown in list, click it
3) [object Object] is returned to text field and add button is grayed out

### Possible Solution
-

### Steps to Reproduce (for bugs)
1) In API Members tab, click (+) and start typing member name.
2) Member is shown in list, click it
3) [object Object] is returned to text field and add button is grayed out

### Context
Can not add members to APIs

### Your Environment
* Version used: 1.30.5
* Browser Name and version: Firefox Developer version, Chrome 80
* Operating System and version: Windows and Linux, service is on Linux

**Comment by brasseld** [comment]
HI @tapiiron 

What is your OpenID provider?

**Comment by tapiiron** [comment]
Hey,
Seems like in test environment the gravitee user list acts the same. Can not add gravitee users to api members either. We got internal openid provider.

**Comment by tapiiron** [comment]
Anything on this issue?

**Comment by tapiiron** [comment]
Using dev console got error: 
md-autocomplete: Could not resolve display value to a string. Please check the `md-item-text` attribute.

When selected someone from the list.

**Comment by brasseld** [comment]
Did you setup some profile mapping for your openid provider configuration ?

**Comment by tapiiron** [comment]
Basic profile mapping:
ID
sub
First name
given_name
Last name
family_name
Email
email
Picture
picture

only picture is never given by openid provider.

**Comment by tapiiron** [comment]
Searched for logs and found this when trying to add member. All secrets are 32 chars(256 bits).

ERROR i.g.m.i.c.a.i.CompositeIdentityManager - An error occurs while serializing user reference
com.nimbusds.jose.KeyLengthException: The secret length must be at least 256 bits
   at com.nimbusds.jose.crypto.MACProvider.<init>(MACProvider.java:118)
   at com.nimbusds.jose.crypto.MACSigner.<init>(MACSigner.java:127)

**Comment by tapiiron** [comment]
Seems like minimum is 33 chars and when used 32 chars it caused the problem. Problem is solved.
