### ISSUE TITLE
[platform] LDAP configuration using environment variables 

### ISSUE THREAD

**Issue by IvoIlic95** [gravitee-io/issues#3274]
Hello guys

I have a question regarding the LDAP configuration by using the environment variables. It was not possible for me to find a thread on how the environment variables look like for the LDAP configuration. 

I need the environment variables for the following properties:
 - URL = Host + Port
 - Attribute
 - Base

Furthermore, I know how the environment variables are built for Gravitee.io, but in this case I really don't know on how to construct the environment variables for the properties that are listed above.

In addition to that I have another question: 
Which variables are mandatory to get LDAP running in Gravitee.io?

I would appreciate it if someone could help me

Kind regards,
Ivo Ilic, B.Sc.

```
security:
  type: basic
  providers:
    - type: ldap
      context:
        username: "uid=admin,ou=system"
        password: "secret"
        url: "ldap://localhost:389/dc=gravitee,dc=io"
        base: "c=io,o=gravitee"
      authentication:
        user:
          base: "ou=people"
          filter: "uid={0}"
        group:
          base: "o=authorization groups"
          filter: "member={0}"
          role:
            attribute: "cn"
            mapper: {
              GRAVITEE-CONSUMERS: API_CONSUMER,
              GRAVITEE-PUBLISHERS: API_PUBLISHER,
              GRAVITEE-ADMINS: ADMIN,
              GRAVITEE-USERS: USER
            }
      lookup:
        user:
          base: "ou=people"
          filter: "(&(objectClass=myObjectClass)(|(cn=*{0}*)(uid={0})))"
```

**Comment by brasseld** [comment]
Did you have a try using something like this:

```
gravitee_security_providers_0_type=ldap
gravitee_security_providers_0_context_username="uid=admin,ou=system"
...
```

**Comment by IvoIlic95** [comment]
Good morning @brasseld 

Yeah I have seen this in the Gravitee.io documentation but how do I build the environment variables for these properties: URL, Base and Attribute? For the attribute property I tried this: GRAVITEE_SECURITY_PROVIDERS_0_AUTHENTICATION-SOURCE-GROUP-ROLE-ATTRIBUTE. 

I have done this structure with the other properties ... take a look:

![image](https://user-images.githubusercontent.com/59047274/75853983-6f0e5a80-5def-11ea-9899-4fd11ab75f98.png)

After building these environment variables and starting my application again, it will throw a error inside the log screen where it says that I have to supply a LDAP URL (I will add the log file to this comment). In addition to that, the obligatory Gravitee.io error screen comes up (Management API unreachable or error occurs, please check logs).

I know this error comes from the environment variables that I have build for the LDAP configuration. So now I don't know what is wrong with my environment variables.

Kind regards,
Ivo Ilic B.Sc.

[error.txt](https://github.com/gravitee-io/issues/files/4285712/error.txt)

**Comment by IvoIlic95** [comment]
Hello 

I changed some things in the meanwhile. As you can see in this picture below I changed some of the  information:
![image](https://user-images.githubusercontent.com/59047274/75882162-e8727100-5e20-11ea-80e6-f0fdda5b4a4b.png)

But sadly this doesn't work either and it throws new errors inside my logging window. I will provide you the error file:

Error file: 
[error.txt](https://github.com/gravitee-io/issues/files/4287393/error.txt)

I have tested if my LDAP is even working and I can guarantee it works just fine. 

So now I am even more confused about the error. What could it be? It would be cool if you could help me considering this problem. 

Kind regards,
Ivo Ilic, B.Sc.

**Comment by IvoIlic95** [comment]
Good morning

I would be pleased if some could provide a solution to my problem. At this point I don't know what causes such a error, when I am configuring my LDAP with my URL.

Kind regards,
Ivo Ilic, B.Sc.

**Comment by aelamrani** [comment]
Hello,

I think you are still on the old format. Take a look at: https://docs.gravitee.io/apim_installguide_migration.html#upgrade_to_1_24_0

So you should change `gravitee_security_providers_0_context-source-username` by `gravitee_security_providers_0_context_username` ...etc

**Comment by IvoIlic95** [comment]
Hello 

And how do I write the env var for the 

Group
   Role
      Attribute

I tried this GRAVITEE_SECURITY_PROVIDERS_0_AUTHENTICATION-SOURCE-GROUP-ROLE-ATTRIBUTE (Now I know that the word SOURCE is invalid). How do I write this env var in the correct way?

Kind regards,
Ivo Ilic, B.Sc.

**Comment by aelamrani** [comment]
>How do I write this env var in the correct way?
GRAVITEE_SECURITY_PROVIDERS_0_AUTHENTICATION_GROUP_ROLE_MAPPER.GRAVITEE_E_Admins=ADMIN

**Comment by IvoIlic95** [comment]
Hello 

Now it works without any errors.
As I have seen in the Gravitee.io documentation (https://docs.gravitee.io/am/2.x/am_userguide_create_identity_provider.html#ldap_identity_provider) I can create a "new provider" but in my Gravitee I can't find this menu?! Does the new version of Gravitee above 1.24 have this menu?

**Comment by aelamrani** [comment]
May i ask you to create a dedicated issue as this is about AM (Access Management) and not APIM?
Thanks
