### ISSUE TITLE
[kubernetes] APIM doc: remove --name parameter from helm install 

### ISSUE THREAD

**Issue by crisog** [gravitee-io/issues#3276]
helm install no longer supports --name parameter and it's still on APIM documentation.

**Comment by brasseld** [comment]
Hi @crisog 

I understand your point about Helm 3.

Unfortunately, most of the people are still considering Helm 2 to install charts. That's the reason why the documentation does not reflect this.

I will ass a note in the doc.

**Comment by brasseld** [comment]
Some notes have been added about Helm 3.

https://github.com/gravitee-io/helm-charts/commit/0ba68fec9571ef421dfb66ec30b0045ede3ce6ce
