### ISSUE TITLE
[policy] [request-validation] Validate not required field

### ISSUE THREAD

**Issue by ElementalArchmage** [gravitee-io/issues#3283]
### Expected Behavior
policy-request-validation has checkbox in rule Required\Not Required or
text field with EL condition.
### Current Behavior
If field is present in rule of policy-request-validation
and not present in request,
validate return false.
### Possible Solution
1. Add checkbox in rule Required\Not Required in rule.
Rule will execute, if set Required.
Default is required
2. Add text field with EL condition in rule. 
Rule will execute, if EL condition is true.
Default is true.
### Context
Some header and query parameter is not required,
but they have pattern. They must be validated, if they
are present in request.
### Your Environment
* Version used: Gateway and APIM v 1.30.2
* Browser Name and version: Yandex 17.7.1.791
* Operating System and version:  Ubuntu 16.04.3

**Comment by brasseld** [comment]
Just to confirm I have a good understanding.

You are looking to check the pattern of an input only if this one is present in the request, right ?

**Comment by ElementalArchmage** [comment]
> Just to confirm I have a good understanding.
> 
> You are looking to check the pattern of an input only if this one is present in the request, right ?
Yes. But I want check the pattetn always for some input fields.
I have two types of input field (header, query and etc): required and not required.
1. Not required.  Check the pattern of an input only if this one is present in the request
2. Required. Check the pattern always. Validate will return false, if value does not present in request.(Current Behavior)
So I suggest add checkbox Required\Not Required.

**Comment by brasseld** [comment]
Get it, thanks for your feedback.

**Comment by ElementalArchmage** [comment]
Hello. When can I expect this feature?
Do you need more information?

**Comment by brasseld** [comment]
This is still part of the backlog.

If you need it quickly, you can submit a PR I would be happy to review.

**Comment by ElementalArchmage** [comment]
Ok, I do. But lets's coordinate changes.
I will add checkbox in rule Required\Not Required.Default is required

**Not required.** Check the pattern of an input only if this one is present in the request
**Required.** Check the pattern always. Validate will return false, if value does not present in request.(Current Behavior)

**Comment by brasseld** [comment]
Looks great!

Don't forget to set as `Required` as default value (to keep the same behavior as today by default).

**Comment by ElementalArchmage** [comment]
Hello!
I made pr https://github.com/gravitee-io/gravitee-policy-request-validation/pull/16

**Comment by ElementalArchmage** [comment]
Please, answer the question in pr. If You don't agree with me, I do, how we write.

**Comment by ElementalArchmage** [comment]
I fixed pr. Please, check it.

**Comment by ElementalArchmage** [comment]
Hello. I squash commits in pr. Please, check it.
