### ISSUE TITLE
[management] add user analytics

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#3291]
For each user, we should be able to see its activity such as : 

- last login
- last reset password
- last update 
- and so on

**Comment by gaetanmaisse** [comment]
The goal is to add an `Analytics` tab in the user details page: 

![image](https://user-images.githubusercontent.com/4112568/103996549-4fc42480-519a-11eb-87a4-ddf6cd5d903d.png)

This tab will contain both:
 - Information currently display in the `User Activities` section
![image](https://user-images.githubusercontent.com/4112568/103996565-55216f00-519a-11eb-9ecf-3f02e1bb038a.png)
 - The audit log as displayed in `settings > audits` but filtered for the selected user 
![image](https://user-images.githubusercontent.com/4112568/103996531-45a22600-519a-11eb-9801-4bed9fefb736.png)
