### ISSUE TITLE
[service-discovery] Consul service discovery plugin doesn't have a way of knowing whether it's SSL

### ISSUE THREAD

**Issue by Impakt** [gravitee-io/issues#3294]
it's possible that this applies to the eureka plugin also

**Comment by brasseld** [comment]
Hi @Impakt 

What's the best way to know if endpoint is ssl or not (from Consul) ?

**Comment by Impakt** [comment]
The only way i can see would be to add a key/value pair with a specific key and value to the metadata map. For example:

`metadata.put( "ssl", "true" );`
