### ISSUE TITLE
[gateway] Retrieve authenticated application name from context attributes

### ISSUE THREAD

**Issue by tpenne** [gravitee-io/issues#3296]
Hi, 
I am currently using the Transform Query Parameters Policy to add a query parameter based on context attribute and this is quite straightforward :

![image](https://user-images.githubusercontent.com/7067461/75889065-9d5e5b00-5e2c-11ea-8d33-df554acd435c.png)

The resulting added parameter contains the id of the authenticated application : ...&partenaire=2aa4a85e-e2e7-49ff-a4a8-5ee2e799ff71

As this is not exactly what I need, I would like to know if there is any solution for me to retrieve the authenticated application name instead of its id ?

Thank you in advance
Kind regards

Thomas

**Comment by brasseld** [comment]
Hi @tpenne 

There is no way to get the application's name from the gateway for now.

**Comment by tpenne** [comment]
Hi @brasseld 
I tried to find a workaround and got a serious lead but I encountered a wall.

I configured the dynamic properties service to fetch properties from MANAGEMENT_API_HOST_AND_PORT/management/applications
with this JOLT Specification : 
`[
  {
    "operation": "shift",
    "spec": {
      "*": {
        "id": "[&1].key",
        "name": "[&1].value"
      }
    }
  }
]`

This could allow me to then retrieve the application name from the properties based on the application id from the context attributes.

Unfortunately it does not seem to work and don't really know why. Do you have any insight ?

Thank you in advance
Thomas

**Comment by brasseld** [comment]
Instead of, I would recommend you to use dictionaries at the platform level, because the same dictionary could be reused by multiple APIs.

**Comment by tpenne** [comment]
To complete what I mentioned previously, using https://jolt-demo.appspot.com/ on the json provided by _MANAGEMENT_API_HOST_AND_PORT/management/applications_ and applying the JOLT Spec I provided I get :
`
[ {
  "key" : "8c81007b-2a7e-4a99-8100-7b2a7e6a992d",
  "value" : "PARTENAIRE-1"
}, {
  "key" : "2aa4a85e-e2e7-49ff-a4a8-5ee2e799ff71",
  "value" : "Temp"
} ]
`
which seems to correspond with the expected output.

I also declared a a static property :
![image](https://user-images.githubusercontent.com/7067461/75967877-c33b3c80-5ecc-11ea-8cb5-8b191e0224c4.png)

and in the transform query parameters policy I tried :

![image](https://user-images.githubusercontent.com/7067461/75967997-f67dcb80-5ecc-11ea-8b41-a1adc79a9989.png)

but here is what I get :
...&partenaire=2aa4a85e-e2e7-49ff-a4a8-5ee2e799ff71&tata=titi

I wil try the same with dictionaries at the platform level right away.
Thank you

**Comment by tpenne** [comment]
Hi @brasseld,

It is not working either with dictionary.

![image](https://user-images.githubusercontent.com/7067461/75968787-3c875f00-5ece-11ea-8a0f-978c4e4517ae.png)

![image](https://user-images.githubusercontent.com/7067461/75968899-69d40d00-5ece-11ea-9009-ee497f16fac7.png)

It seems dictionary is started but not fetching anything.
In the logs I get the same line every 5 seconds :

> 09:45:25.009 [sync-1] INFO  i.g.m.s.dictionary.DictionaryService - Add a scheduled task to poll dictionary provider each 1 MINUTES
  | 09:45:30.008 [sync-1] INFO  i.g.m.s.dictionary.DictionaryService - Add a scheduled task to poll dictionary provider each 1 MINUTES
  | 09:45:35.008 [sync-1] INFO  i.g.m.s.dictionary.DictionaryService - Add a scheduled task to poll dictionary provider each 1 MINUTES
  | 09:45:40.007 [sync-1] INFO  i.g.m.s.dictionary.DictionaryService - Add a scheduled task to poll dictionary provider each 1 MINUTES
  | 09:45:45.008 [sync-1] INFO  i.g.m.s.dictionary.DictionaryService - Add a scheduled task to poll dictionary provider each 1 MINUTES
  | 09:45:50.007 [sync-1] INFO  i.g.m.s.dictionary.DictionaryService - Add a scheduled task to poll dictionary provider each 1 MINUTES
  | 09:45:55.008 [sync-1] INFO  i.g.m.s.dictionary.DictionaryService - Add a scheduled task to poll dictionary provider each 1 MINUTES
  | 09:46:00.009 [sync-1] INFO  i.g.m.s.dictionary.DictionaryService - Add a scheduled task to poll dictionary provider each 1 MINUTES

**Comment by brasseld** [comment]
Ok, I'll have a try later this morning

**Comment by brasseld** [comment]
I think the issue is due to the fact that call the /applications requires authentication.

And we're currently providing no way to add HTTP headers to dictionary nor dynamic properties.

**Comment by tpenne** [comment]
:sob:

**Comment by brasseld** [comment]
That's the shame... I know :(

**Comment by tpenne** [comment]
And is this expected to be added soon ?
Or automatically providing authentication information for local (management-api) endpoints ?
