### ISSUE TITLE
Publish sources on maven-central

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#33]
_From @M3lkior on June 13, 2016 12:18_

Unable to get gravitee-repository-test sources from maven-central.

_Copied from original issue: gravitee-io/gravitee-repository-test#4_

**Comment by gaetanmaisse** [comment]
Closing as it has been fixed: https://search.maven.org/search?q=gravitee-repository-test
Also the artefact has been renamed: https://search.maven.org/search?q=gravitee-apim-repository-test
