### ISSUE TITLE
[policy] [jwt] JWT authentication using RSA signature not working

### ISSUE THREAD

**Issue by hasable** [gravitee-io/issues#3306]
Hi, 

I created on the demo environment an API in order to test RS256 signed JWT token.

1. First, I created on my workspace public & private keys using ssh-keygen : 
```
$ ssh-keygen -t rsa -q -C client -f bapicli.rsa
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
```
Please find attached generated file : [rsa.zip](https://github.com/gravitee-io/issues/files/4298044/rsa.zip)

Openssl compatible key can be extracted as follows : 
```
$ ssh-keygen -f bapicli.rsa.pub -e -m pem
-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEA9mllUdaZtIld0aeARp2+stpDr/sOEnzMXP2hra9yu95ncKqZN2h/
+miIEnuIokZDLFxUtn/OJl40rGoDy8Mi01QKqiFptYW2FdmQvpuOxZE8o9dJDsIf
yelve5xFiZU1iqF+ddPvONWUGecr1aPleW3dbFUmG0ogWQ8OoHlRP9nKUwXC97ez
MtjvtdNCv8LBpkroVANK8KYL2CTzsOsr5IMPGvNqigIZ5lQivBZo62VuAowkv12J
5ucrl4hBOQpZmzdj8xajm/nmpH0CZv7fInbzcrKuWHwVzXHNOE5poCMOVhCzzzOC
fXwJWkcCwAnuNosEBRzEj91E7gWTAt8WWQIDAQAB
-----END RSA PUBLIC KEY-----
```
2. Then I created JWTApi on your demo environment, using [jsonplaceholder](jsonplaceholder.typicode.com) as a backend

3. I created a public plan, in order to verify that everything is ok, then I deleted it

4. I created **JWT Secure Plan**, using **RS256 - RSA  Signature with SHA-256** , using the previously generated ssh public key :
![image](https://user-images.githubusercontent.com/24457211/76080004-41b7dd00-5fa6-11ea-84a4-dbd385f61c99.png)

5. I created **JWTClient** application, using **client_id=client**, and subscribed to **JWT Secure Plan**

6. Using [jwt.io](jwt.io), I prepared my JWT token :
![image](https://user-images.githubusercontent.com/24457211/76080410-21d4e900-5fa7-11ea-9565-b62d8495368e.png)

- I used the previously created private key to sign the token
- I used extracted public key to check signature
- I added *kid* and *client_id* in both *header* and *payload* (actually I tried everything...)

7. I send a query using REST Client
![image](https://user-images.githubusercontent.com/24457211/76080577-79735480-5fa7-11ea-9f61-df23516ee4e6.png)

### Expected Behavior
Obviously, I am expecting a HTTP 200 return code

### Current Behavior
Whatever I tried, I always get HTTP 401.

### Steps to Reproduce (for bugs)
You can use provided keys and application configured in your demo env. 

Thanks your for your help and support. 

Thomas.

**Comment by aelamrani** [comment]
Hi @hasable 

Thanks for this detailed issue.

The policy is looking for a client ID on the payload as follow:
- First on the `azp` claim
- Then on the `aud` claim
- Finally on the `client_id` claim

So in your case, you should define the client id `API1` on the application.

**Comment by hasable** [comment]
Hi @aelamrani, 

Thanks for your quick answer which actually solved the problem. 

However maybe you should update [online documention](https://docs.gravitee.io/apim_publisherguide_plans_subscriptions.html) as per now it states that only **client_id** is used :
> JWT defines some registered claim names including subject, issuer, audience, expiration time, and not-before time. In addition to these claims, the inbound JWT payload MUST contains the client_id claim to make the connection between the JWT and the Gravitee.io application’s subscription.

**Comment by aelamrani** [comment]
Done
