### ISSUE TITLE
Adding a identity provider in Gravitee.io APIM

### ISSUE THREAD

**Issue by IvoIlic95** [gravitee-io/issues#3316]
Hello guys

I managed to configure LDAP in Gravitee.io API Management. My problem is that I can't find the menu to add a identity provider like in this link (https://docs.gravitee.io/am/2.x/am_userguide_create_identity_provider.html#ldap_identity_provider)

I know that this is the Gravitee.io Access Management but do I need this tool to run LDAp in GRavitee.io API-Management? 

Kind regards,
Ivo Ilic, BSc

**Comment by aelamrani** [comment]
Hello @IvoIlic95,

I don't understand what you are trying to achieve here.

So you have configured the login with your LDAP directly on APIM. And now you are talking about adding a new Identity Provider LDAP but in the Access Management?

What is your need exactly?

Either you configure the LDAP in APIM (what you already have done), or you configure it on a third party module (AM for example) and in APIM you will have to configure this 3rd party service (and not the ldap directly).

**Comment by IvoIlic95** [comment]
Well to be more specific: Do I need Access Management to run LDAP so that I can LogIn in the APIM Tool or do I just need to configure LDAP in APIM (which I did) so that I can LogIn with my LDAP data in APIM?

What I have read APIM and AM are not dependent on each other? Or are they?

**Comment by aelamrani** [comment]
> Do I need Access Management to run LDAP so that I can LogIn in the APIM Tool or do I just need to configure LDAP in APIM (which I did) so that I can LogIn with my LDAP data in APIM?

No, you can configure your LDAP in APIM and login / search.

> What I have read APIM and AM are not dependent on each other? Or are they?

Not dependent.

Maybe this is a misconfiguration of the LDAP. You can add more logs to check what's going wrong by adding these lines on your logback.xml file:

```XML
    <logger name="org.springframework.security.ldap" level="DEBUG" />
    <logger name="org.springframework.ldap" level="DEBUG" />
```

**Comment by IvoIlic95** [comment]
> You can add more logs to check what's going wrong by adding these lines on your logback.xml file:
> 
>     <logger name="org.springframework.security.ldap" level="DEBUG" />
>     <logger name="org.springframework.ldap" level="DEBUG" />

To do this I have to write my admin in the company because I have no extended admin rights due to security reasons ... sadly... but I am going to do this. 
 
Can you please look at my configuration: Is something wrong with it? Am I missing something? 
![InkedLDAP_GRAVITEE_LI](https://user-images.githubusercontent.com/59047274/76214233-99578200-620c-11ea-8dba-d8fcd868a4e3.jpg)

**Comment by aelamrani** [comment]
Not sure about your group role attribute. We usually have `cn` as value.

Can you try by removing the DCs from the URL? => `ldaps://XXXX.XXXX.infineon.com:XXXX`

**Comment by IvoIlic95** [comment]
I modified the information based on your response and now I am getting this kind of LOG information:


```
13:56:39.037 [graviteeio-node] INFO  i.g.m.s.c.BasicSecurityConfigurerAdapter - Loading authentication providers
--
  | 13:56:39.235 [graviteeio-node] INFO  i.g.m.s.c.BasicSecurityConfigurerAdapter - Loading authentication identity providers for Basic authentication
  | 13:56:39.235 [graviteeio-node] INFO  i.g.m.s.c.BasicSecurityConfigurerAdapter - Loading authentication provider of type ldap at position 0
  | 13:56:39.635 [graviteeio-node] INFO  o.s.s.l.DefaultSpringSecurityContextSource -  URL 'ldaps://XXXX.XXXX.infineon.com:XXXX', root DN is ''
  | 13:56:39.636 [graviteeio-node] DEBUG o.s.l.c.s.AbstractContextSource - AuthenticationSource not set - using default implementation
  | 13:56:39.637 [graviteeio-node] DEBUG o.s.l.c.s.AbstractContextSource - Using LDAP pooling.
  | 13:56:39.637 [graviteeio-node] DEBUG o.s.l.c.s.AbstractContextSource - Trying provider Urls: ldaps://XXXX.XXXX.infineon.com:XXXX
  | 13:56:39.830 [graviteeio-node] INFO  i.g.m.i.l.lookup.LdapIdentityLookup - User search is based on DN [DC=infineon,DC=com]
  | 13:56:39.831 [graviteeio-node] INFO  i.g.m.i.l.a.LdapAuthenticationProvider - Configuring an LDAP Identity Provider
  | 13:56:39.838 [graviteeio-node] INFO  o.s.s.l.DefaultSpringSecurityContextSource -  URL 'ldaps://XXXX.XXXX.infineon.com:XXXX', root DN is ''
  | 13:56:39.838 [graviteeio-node] DEBUG o.s.l.c.s.AbstractContextSource - AuthenticationSource not set - using default implementation
  | 13:56:39.838 [graviteeio-node] DEBUG o.s.l.c.s.AbstractContextSource - Using LDAP pooling.
  | 13:56:39.926 [graviteeio-node] DEBUG o.s.l.c.s.AbstractContextSource - Trying provider Urls: ldaps://XXXX.XXXX.infineon.com:XXXX/DC=infineon,DC=com
  | 13:56:39.930 [graviteeio-node] INFO  o.s.s.l.u.DefaultLdapAuthoritiesPopulator - groupSearchBase is empty. Searches will be performed from the context source base


```

The LogIn with my LDAP data sadly doesn't work again.

**Comment by IvoIlic95** [comment]
Hello and good morning

Does the added DEBUG information provide more information or better to say does it help you?

Kind regards,
Ivo Ilic, BSc

**Comment by lazki** [comment]
Not a bug, should be closed. @brasseld
