### ISSUE TITLE
[AM] [gateway] ConcurrentModificationException when deleting / recreating a domain with same name

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#3322]
### Expected Behavior

When running postman tests, a `ConcurrentModificationException` may occurs on the AM gateway.
Postman tests are executed sequentially and when a test case ends, the created domain is deleted. When the next scenario starts, a new domain with the same name is sometime created.

### Current Behavior

The management api emits events to signal to the gateway to refresh its current state (undeploy a domain, deploy a new domain, ...). Events are processed every 5s by the gateway (default behavior).

Postman sometimes deletes a domain and recreates a new one with the same name during the same time window. When the gateway starts to process the events, there are both DEPLOY and UNDEPLOY events for the same domain. This behavior is very tricky to reproduce and leads to inconsistent states in the gateway side.

### Possible Solution

A possible solution could be to user technical id for domain identifiers (eg: uuid). So deleting a 'test' domain and recreating it will result in 2 different domain identifiers. This should be sufficient enough to avoid concurrent event processing.

### Steps to Reproduce (for bugs)

The simple way (but not predictable):
1. Starts AM management and gateway
2. Run make postman
3. Retry until you get an error in the gateway logs

Also, it is possible to process this way (a bit more predictable...):
1. Create a domain with many identity providers
2. Start the domain
3. Wait for the domain to be started on the gateway
4. Pause the gateway SyncManager (using a breakpoint)
5. Delete the domain
6. Create the domain again, with same name and multiple identity providers (to increase to probability to get concurrent modifications)
7. Start the domain
8. Release the break point on the gateway.

### Your Environment

* Java v11.0.5
* Postman v7.18.0
* MacOS Catalina (10.15.2)
* Gravitee AM 3.0.0-SNAPSHOT

**Comment by tcompiegne** [comment]
closed by https://github.com/gravitee-io/issues/issues/3386
