### ISSUE TITLE
[gateway] [identity-provider] OIDC provider - encode the redirect URI

### ISSUE THREAD

**Issue by bcollard** [gravitee-io/issues#3324]
### Expected Behavior
When using an OIDC provider, the redirect URI added by the AM gateway should be URL encoded

### Current Behavior
URI is not URL encoded

### Possible Solution
encode URI

### Steps to Reproduce (for bugs)
The OIDC server cannot determine where this redirect_uri ends, because there are other parameters appended at the end, like the scopes. Example: The AM call this OIDC server like this : 

> https://mycompany.com/as/authorization.oauth2?client_id=CLIENT-ID&redirect_uri=https://GRAVITEE-AM/gateway/MY-DOMAIN/login/callback?provider=c003187a-f894-41c4-8318-7af89471c4a8&response_type=code&scope=openid%20SCOPE2%20SCOPE3%20SCOPE4%20SCOPE5

so the 

> redirect_uri + &response_type=code&scope=openid%20SCOPE2%20SCOPE3%20SCOPE4%20SCOPE5

 is not valid according to the AS

**Comment by tcompiegne** [comment]
Hi @bcollard, I'm not sure that AS will accept an encoding URI against its decoded value, maybe the simple way is to put the `redirect_uri` parameter at the end, WDYT ?

**Comment by bcollard** [comment]
Yes indeed, it's a better option in case the AS doesn't support encoded URL.
thanks!

**Comment by bcollard** [comment]
Actually, no, in my case, there is still a confusion of the parameters sent to the OpenID Provider even when the redirect_uri is the last parameter (AS is pingfederate). It works when the redirect_uri is url-encoded. Maybe it should be an option in order to be backward-compatible with already existing configurations?

**Comment by tcompiegne** [comment]
Yes seems legit, can you confirm that the following scenario is working ?

Ping federate whitelist callback : `https://client.example.com/cb `
Current redirect_uri : `https%3A%2F%2Fclient%2Eexample%2Ecom%2Fcb` 

no need to encode the URL in the ping federate configuration ?

**Comment by bcollard** [comment]
yes, it's the case!
