### ISSUE TITLE
[oauth2] Log in when behind a loadbalancer isn't always working

### ISSUE THREAD

**Issue by oyviaase** [gravitee-io/issues#3329]
### Expected Behavior
Authentication through a 3rd party oauth service should alway be able to log you into the api-manager regardles of how you started the log in process

### Current Behavior
Trying to log in with oath2 when it's the only authentication method isn't always working. Generally when accessing the api-manager directly the log in is working correctly while log in through the loadbalancer is not working. Sometimes it's the reverse that log in through the load balances works but accessing it directly does not work. Showing the login promt where users can select which login provider to use seems to fix the issue.

### Possible Solution
The bug seems to be that api-manager isn't always seting the `state` parameter in it's request to the authentication solution for example we keep seeing this: `https:<auth-provider>/oauth/authorization?response_type=code&client_id=<client id>&redirect_uri=https://<api-manager url>&scope=<scopes to get>&state=null`

### Steps to Reproduce (for bugs)

1.  Install api-manager
2. Configure a loadbalancer in front of the api-manager
3. Add an oauth2 authentication provider and remove all other log in methods
4. In a private window or different browser try to log in to api-manager

### Context
We want our users to be able to log in to gravitee without having to select the authentication solution to use as we are anyways just using one authentication providers for all logins.

### Your Environment

* Version used: 1.30.5 running on openshift 3.11
* Browser Name and version: Firefox 73.0.1 and Vivaldi 2.11.1811.47 
* Operating System and version: Fedora 31

**Comment by brasseld** [comment]
Why do you think the issue is coming from api-manager and not the load balancer ?

Which component did you set up behind LB : UI, API, GW ?

**Comment by oyviaase** [comment]
We've been running api-manager 1.29.5 and when we tried to upgrade to 1.30.5 the oath2 log in started to fail. The setup is completely the same with one exception that we are using the 1.30.5 images instead of the 1.29.5 images. 

All three components are running behind LB, it's also worth mentioning that we're using an extarnal LB in addition to the one built into openshift.

**Comment by brasseld** [comment]
As far as I know, this url is called by the browser when you press "log in with XXXX" from the log in form:

https:<auth-provider>/oauth/authorization?response_type=code&client_id=<client id>&redirect_uri=https://<api-manager url>&scope=<scopes to get>&state=null

What I do not understand is why the state is null... and who is setting this parameter to null...

Here is the job done by the UI: https://github.com/gravitee-io/gravitee-management-webui/pull/1125/files#diff-3f694ee7467708de76e53617fc227eacR55

The nonce is always calculated and passed to the authentication layer:

https://github.com/gravitee-io/gravitee-management-webui/pull/1125/files#diff-348ff91386b7d7af9127b5c9d9a378e8R56

And it doesn't make sense that the UI is defining the state a null value, as it is javascript, so the value would be `undefined` instead...

**Comment by oyviaase** [comment]
The problem doesn't occur when pressing "log in with XXX" on the login form, we are only experiencing it when we only have one authentication provider and disables local user login, and thereby bypassing the log in form completely. 

It might be that this bypass also bypasses the generation of the state token and that the browser then fills in the missing information with null. This is however pure guesswork on my side

**Comment by brasseld** [comment]
Ok, now I have a better understanding :)

I'll have a try.

**Comment by brasseld** [comment]
Hi @oyviaase 

Thanks for reporting this issue.
PR is under review, fix will be available in v1.30.6
