### ISSUE TITLE
Possible license/copyright issue?

### ISSUE THREAD

**Issue by EricWittmann** [gravitee-io/issues#333]
Hey guys.  Just recently discovered this project and it looks really great, although somewhat...familiar. :)

Perusing the gravitee documentation, it seems that at least *some* portions of it have been taken from APIMan documentation and then modified.  My understanding is that this is perfectly fine, although you may need to include an attribution of some kind, or at least a notice that "You changed the files" (see below for details).

The Apache License does require that: " You must cause any modified files to carry prominent notices stating that You changed the files". It also requires that "You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works".

Derivative Work:
https://docs.gravitee.io/#gravitee-introduction

Original:
http://www.apiman.io/latest/user-guide.html#_what_is_api_management

Also, since the APIMan docs are licensed under Apache v2 (indicated in the footer), I suspect you would need to include a link to the license in the footer of your documentation as well.

Best of luck with the project!

**Comment by brasseld** [comment]
Hi Eric,

We've just discovered your message, where we fully understand your concerns and we have to admit that we are feeling ashamed with this situation.

Initially, this documentation was written by an external people of the actual team and was not checked against copy from an other website or an other solution. It's our fault. Also, and even if APIMan documentations were licensed under Apache v2 and even if the project is now under maintenance mode, this is not an option for us to keep such part of the documentation. It was not our primary intention and it will be safe for both to remove and rewrite this part. In any case, we take into account your last sentence where you advise us to include a link to the Apache v2 license.
This is the best thing we can do in a very short time. So we will close this issue and create a new one (and refers to the current) to rewrite introduction. 

Finally, we would like to thank you for your feedback and your recommandations. You have done an amazing work with APIMan project and we would like to say that we are not sure it was a good option for red hat to put such a project into maintenance mode and switch to a new model. But we are sure we will be surprised with next API Management solution from the company.

Wish you all the best !

The Gravitee.io Team

**Comment by EricWittmann** [comment]
OK that sounds like a good resolution.

We're going to be doing some work in the API design space going forward - perhaps there will be opportunities for integration in the future.  I'll keep an eye on gravitee!  :)

**Comment by brasseld** [comment]
Sounds good !

You're talking about apiman studio, right ?

**Comment by EricWittmann** [comment]
Yep.  We're still just exploring ideas at the moment.  So we'll see where it ends up going and what it ends up being called. :)
