### ISSUE TITLE
[APIM] OpenID authentication - internal server error

### ISSUE THREAD

**Issue by IvoIlic95** [gravitee-io/issues#3333]
Hello

I need help considering my problem. To authenticate users I am using OpenID. The configuration was done via the Gravitee UI. In the begging the authentication for MY USER was working with some side effects.

After clicking on iAuth a window pops up:
![image](https://user-images.githubusercontent.com/59047274/76765945-85c19380-6797-11ea-8f30-590f0844f9a1.png)

After that I clicked on "Allow" which grants me to use the Gravitee with my OpenID Profile. Nevertheless, I am getting a error even if the authentication is working. 
```
`13:59:31.135 [gravitee-listener-27] ERROR i.g.m.r.r.a.OAuth2AuthenticationResource - Using mapping: "", no fields are located in {"sub":"XXXXXXX@infineon.com","email_verified":false,"gender":"male","name":"Ilic Ivo (IFKL IT OS DC IHW MA)","preferred_username":"XXXXXXX@infineon.com","given_name":"Ivo","family_name":"Ilic","email":"XXXXXXX@infineon.com"}
 `
```
What irritates me more inside this error is this line: "email_verified":false.

Moreover, if another users decides to LogIn with his OpenID Profile a another error occurs:

[OpenId_error.txt](https://github.com/gravitee-io/issues/files/4338595/OpenId_error.txt)

The main error that shows up every time is the:
```
13:45:40.535 [gravitee-listener-30] ERROR i.g.m.rest.provider.ThrowableMapper - Internal error
javax.ws.rs.ProcessingException: java.io.IOException: Error writing to server
```
To be said the OpenID Identity provider works fine as my administrator showed me. He gets a request and all the other necessary information. This means that the error can't be from their side.

Do I need to configure LDAP? It possibly could be a error from this side or am I wrong.

I really hope if someone could response to this issue even if Europe is in a difficult situation right now. 

With kind regards,
Ivo Ilic

**Comment by brasseld** [comment]
```json
{"sub":"XXXXXXX@infineon.com","email_verified":false,"gender":"male","name":"Ilic Ivo (IFKL IT OS DC IHW MA)","preferred_username":"XXXXXXX@infineon.com","given_name":"Ivo","family_name":"Ilic","email":"XXXXXXX@infineon.com"}
```

Is the content from your ID provider.

Seems that you have an issue with mapping for your OIDC provider.
