### ISSUE TITLE
[policy] [xml-to-json] 504 from API Gateway with policy

### ISSUE THREAD

**Issue by lwatzon** [gravitee-io/issues#3348]
When calling a SOAP web service from Gravitee that takes longer than 30 seconds to return, and the XML to JSON Policy is applied the platform returns a 504 after 30 seconds but the call completes as shown in the logs

### Expected Behavior
Once the data has been returned from the SOAP call the Gravitee API should return a JSON version of the XML to the client

### Current Behavior
If the underlying call takes longer than 30 seconds, gravitee returns a 504

### Possible Solution
I have tried changing all the timeouts in the HTTP Configuration of the Endpoint
I have tried adding a Latency Policy 

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Context
We have a need to call an external SOAP web service and would prefer to work with JSON result rather than the XML currently provided

### Your Environment

* Version used:1.30.5
* Browser Name and version: Google Chrome 80.0.3987.132
* Operating System and version: Windows 10

**Comment by brasseld** [comment]
Can you tell me what kind of configuration you've set for the endpoint  (I mean timeouts..)

**Comment by lwatzon** [comment]
I have the following

Connection timeout (ms) : 600000
Read timeout(ms): 300000
Idle timeout (ms): 600000

**Comment by brasseld** [comment]
Hi @lwatzon 

Seems that the gateway is looking for more content than the one received from SOAP endpoint.

Can you tell me if the soap endpoint responds with a Content-length or a Transfer-encoding header ?

**Comment by lwatzon** [comment]
@brasseld 
So on the calls that 'fail' I don't get the gateway information in the logs screen of gravitee. 
If i call the same endpoint with parameters that return a smaller payload i see

Content-Length | 572

Content-Type | text/xml; charset=utf-8
Transfer-Encoding | chunked

**Comment by brasseld** [comment]
Perhaps you can tcpdump between gateway and backend service ?

**Comment by lwatzon** [comment]
I will have to ask for help, our gateway is hosted as a container in a hosting environment. I don't think it would be possible for me to do.

**Comment by brasseld** [comment]
I think you can still tcpdump from host, even id you are running container.

**Comment by brasseld** [comment]
Hi @lwatzon 

Any news here ?
