### ISSUE TITLE
[docker] More information or description in docker-compose repository

### ISSUE THREAD

**Issue by IOhacker** [gravitee-io/issues#3352]
### Expected Behavior
It would be helpful to have more information about the files that are located in the environments/demo for this repository https://github.com/gravitee-io/gravitee-docker

### Current Behavior
it only contains $ curl -L http://bit.ly/graviteeio-apim | bash but there is not information about what to do after that or how to use Gravitee after that.

### Possible Solution
At least improve the information in the README.adoc or any other location.

### Steps to Reproduce (for bugs)

1. Go to https://github.com/gravitee-io/gravitee-docker and clone the repo
2. Follow the instructions for installing Gravitee
3. Then... ? (add missing information how to login to each component and default username and password

### Context
I am trying Gravitee for evaluation.

### Your Environment
* Version used: Master branch of https://github.com/gravitee-io/gravitee-docker 
* Operating System and version: Linux 16.04 LTS

**Comment by rjacobs91** [comment]
The `readme.md` file also initiates an install of the components using completely different versions from those in the repository. One example is that the elasticsearch container version is 5.4.3 when running curl command, but when running launch.sh the container version is 6.3.1.

**Comment by brasseld** [comment]
Hi @IOhacker 

Please have a look to docs from https://docs.gravitee.io/apim_installguide_docker.html#docker_compose

@rjacobs91 
I don't understand. According to the docker file, ES version should be 5.4.3 https://github.com/gravitee-io/gravitee-docker/blob/master/environments/demo/common.yml#L22

**Comment by rjacobs91** [comment]
Apologies, I was referring to the docker-compose file in the platform directory not demo directory. I originally assumed that it would be valid to run either `launch.sh` or `docker-compose` from there.
I suspect that is not the case.

**Comment by brasseld** [comment]
No worries @rjacobs91 

Here is a blog post you can consider: https://medium.com/graviteeio/5-minutes-to-secure-an-api-with-the-gravitee-ios-stack-34203620eadc
