### ISSUE TITLE
[portal] Analytics API - Hit by applications not shown

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#336]
I go to api and analytics menu, i don't see call by application. 
Error is diplayed with insufficient privilege

**Comment by brasseld** [comment]
Hi @vdelattre,

For your first comment, you have no dashboard at all because you are a simple user of the platform and not an administrator, that's the reason why you didn't see the _dashboard_ menu.

Your second issue seems to be due to an issue with privileges on applications.

**Comment by vdelattre** [comment]
I'm owner of one application calling api and i'm owner of api.
So i can't see who call my apis

And for first comment, without this menu, i have to go to each api to see it's analytics, there is no synthese

**Comment by brasseld** [comment]
I've updated the issue according to our conversation

**Comment by tcompiegne** [comment]
Review in progress : missing API names for the events table inside dashboard page.
