### ISSUE TITLE
[docker] gravitee project won't run

### ISSUE THREAD

**Issue by rjacobs91** [gravitee-io/issues#3361]
When trying to run this repository (through `launch.sh` file) the elasticsearch container fails, which in turn blocks a vert.x thread on the gateway container.

### Expected Behavior
All containers run without exception.

### Current Behavior
Elasticsearch container keeps throwing this exception.
```
elasticsearch_1    | [2020-03-23T16:10:46,911][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
elasticsearch_1    | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
elasticsearch_1    |    at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:140) ~[elasticsearch-6.3.1.jar:6.3.1]
elasticsearch_1    |    at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.3.1.jar:6.3.1]
elasticsearch_1    |    at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.3.1.jar:6.3.1]
elasticsearch_1    |    at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.3.1.jar:6.3.1]
elasticsearch_1    |    at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.3.1.jar:6.3.1]
elasticsearch_1    |    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.3.1.jar:6.3.1]
elasticsearch_1    |    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) ~[elasticsearch-6.3.1.jar:6.3.1]
elasticsearch_1    | Caused by: java.lang.IllegalStateException: Failed to create node environment
elasticsearch_1    |    at org.elasticsearch.node.Node.<init>(Node.java:273) ~[elasticsearch-6.3.1.jar:6.3.1]
elasticsearch_1    |    at org.elasticsearch.node.Node.<init>(Node.java:252) ~[elasticsearch-6.3.1.jar:6.3.1]
elasticsearch_1    |    at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.3.1.jar:6.3.1]
elasticsearch_1    |    at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.3.1.jar:6.3.1]
elasticsearch_1    |    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) ~[elasticsearch-6.3.1.jar:6.3.1]
elasticsearch_1    |    at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.3.1.jar:6.3.1]
elasticsearch_1    |    ... 6 more
elasticsearch_1    | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
elasticsearch_1    |    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
elasticsearch_1    |    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
elasticsearch_1    |    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
elasticsearch_1    |    at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:385) ~[?:?]

```

### Possible Solution
Potentially this is an issue with later versions of docker or elasticsearch.

### Steps to Reproduce (for bugs)
1. Clone the repository
2. Navigate to platform directory
3. ./launch.sh

### Context
I want to evaluate the product. Obviously cannot do so if the local demo won't run.

### Your Environment
* Version used: gravitee-docker commit id: 18449570
* Browser Name and version: Not applicable
* Operating System and version: Ubuntu 19.10

**Comment by brasseld** [comment]
Hi @rjacobs91 

The issue is due to a file access denied error for Elasticsearch.
This is because the docker container is creating a volume on your host.

To go ahead, you may have to change the local path.
See https://github.com/gravitee-io/gravitee-docker/blob/master/environments/demo/docker-compose-local.yml#L25

Regards,

**Comment by rjacobs91** [comment]
Hi @brasseld 
There is progress that I no longer get a access denied error but I'm now getting DNS resolution errors for the elasticsearch container.

`
local_managementapi_1  | java.net.UnknownHostException: failed to resolve 'demo-elasticsearch' after 2 queries 
local_managementapi_1  |        at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:877)
local_managementapi_1  |        at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:838)
local_managementapi_1  |        at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:333)
local_managementapi_1  |        at io.netty.resolver.dns.DnsResolveContext.onResponse(DnsResolveContext.java:520)
local_managementapi_1  |        at io.netty.resolver.dns.DnsResolveContext.access$400(DnsResolveContext.java:63)
local_managementapi_1  |        at io.netty.resolver.dns.DnsResolveContext$3.operationComplete(DnsResolveContext.java:377)
`
Any suggestions?
Thanks

**Comment by rjacobs91** [comment]
Resolved my issues by running the following command  `sudo sysctl -w vm.max_map_count=262144`. The enables the elasticsearch container to start properly. Perhaps something to put in the readme as a potential requiremen?.

**Comment by brasseld** [comment]
Hi @rjacobs91 

It is already explained from documentation: https://docs.gravitee.io/apim/1.x/apim_installguide_docker_compose.html#docker_compose

Regards,
