### ISSUE TITLE
[portal] Unable to login

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#3363]
I've put my credential, but I'm not able to click on the `sign in` button.
Press `Enter` key is working well.

<img width="557" alt="Capture d’écran 2020-03-24 à 08 21 03" src="https://user-images.githubusercontent.com/133094/77398830-80240900-6da8-11ea-8e5c-80223c4e2431.png">

Browser: Chrome 80

**Comment by brasseld** [comment]
Same for the registration form

<img width="511" alt="Capture d’écran 2020-03-24 à 08 22 46" src="https://user-images.githubusercontent.com/133094/77398920-ab0e5d00-6da8-11ea-8a6d-fec04f50d006.png">

**Comment by phiz71** [comment]
"Login" issue has been fixed in #3357.
"Registration" issue has been fixed in #2822 .
