### ISSUE TITLE
[portal] Missing label in user form

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#3365]
Label is missing for `USER.CHANGE_PICTURE`

<img width="552" alt="Capture d’écran 2020-03-24 à 08 25 37" src="https://user-images.githubusercontent.com/133094/77399150-1eb06a00-6da9-11ea-97d9-abedcb0e7a09.png">

**Comment by aelamrani** [comment]
Closed by https://github.com/gravitee-io/issues/issues/2805
