### ISSUE TITLE
[portal] Labels are missing for application

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#3366]
<img width="1106" alt="Capture d’écran 2020-03-24 à 08 27 25" src="https://user-images.githubusercontent.com/133094/77399280-61724200-6da9-11ea-8821-61f93fbf4507.png">

Also, `Général` should be replace with `General`

**Comment by aelamrani** [comment]
Closed by https://github.com/gravitee-io/issues/issues/2805
