### ISSUE TITLE
[portal] Analytics API - dashboard owner

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#337]
It will be nice to have a dashboard owner with a view of all apis i'm owner.
To avoid to go to each api analytics.

**Comment by brasseld** [comment]
Currently, `dashboard` is only accessible to admin users.

It would be nice to have such dashboard for all users, but must be restricted only to user's application and api accessible to this user.

**Comment by brasseld** [comment]
Closes as part of https://github.com/gravitee-io/issues/issues/1442
