### ISSUE TITLE
[node] [health-check] API Gateway _node/health reports HTTP 500 - even though all services are healthy

### ISSUE THREAD

**Issue by kdandersen** [gravitee-io/issues#3382]
Upgraded to version 1.30.6. All is Docker container based.

Problem is that the /_node/health API returns the HTTP status code 500 (Internal Server Error) despite the services appearing healthy.

### Expected Behavior
API Gateway health check should return HTTP 200 when all modules report they are healthy.
This has been the behavior up until v. 1.30.5.

### Current Behavior
Output from curl against health API:

```
# curl -v -u admin:xxxxxxxxxxxxxxxxx http://10.33.xx.xxx:18082/_node/health
* About to connect() to 10.33.xx.xxx port 18082 (#0)
*   Trying 10.33.xx.xxx...
* Connected to 10.33.xx.xxx (10.33.xx.xxx) port 18082 (#0)
* Server auth using Basic with user 'admin'
> GET /_node/health HTTP/1.1
> Authorization: Basic XXXXXXXXXXXXXXXXXXXXXXXXX
> User-Agent: curl/7.29.0
> Host: 10.33.xx.xxx:18082
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json
< transfer-encoding: chunked
< 
{
  "ratelimit-repository" : {
    "healthy" : true
  },
  "management-repository" : {
    "healthy" : true
  },
  "http-server" : {
    "healthy" : true
  }
* Connection #0 to host 10.33.xx.xxx left intact
```
The HTTP 500 status makes our monitoring assume there is an issue/problem with the gateway.
There are no indications in the Docker logs/gateway log file that something isn’t OK.

### Steps to Reproduce (for bugs)
Regular upgrade/switch of docker image with exact same execution parameters as previous.

### Context
Monitoring is in alarm, since health check is reporting failure.

### Your Environment
Centos 7.7.1908 (Core)
Docker Community edition 19.03.8 (containerd: 1.2.13, runc: 1.0.0-rc10, docker-init: 0.18.0)

**Comment by brasseld** [comment]
Clones by https://github.com/gravitee-io/issues/issues/3400
