### ISSUE TITLE
[API Manager portal] Hard delete api feature

### ISSUE THREAD

**Issue by fmercier-almerys** [gravitee-io/issues#3395]
Hi

Deleting an api is tedious using the UI because all plans must be closed before .
Providing a new endpoint or UI button to destroy directly the api should be convenient

**Comment by aelamrani** [comment]
Hi @fmercier-almerys,

Sorry for the delay on that one.

May I ask you, what is the use case here? Is it for debugging purpose? In production? Or for a special user?

Thanks
