### ISSUE TITLE
[gateway] [extension-grant] mapped claims from Ldap IDP and from JWT Bearer claim mapper are neither merged nor returned at all

### ISSUE THREAD

**Issue by bcollard** [gravitee-io/issues#3397]
When using the JWT Bearer grant flow and a LDAP IDP, claims are not merged together.

### Expected Behavior
Given you use the JWT Bearer extension grant and therefore you pass a JWT with some claims (the assertion) ;
Given you check the option "Check user" (extension grant page); (and BTW, that should disable the option above named "User creation", otherwise, the condition is never met [in the code](https://github.com/gravitee-io/graviteeio-access-management/blob/a2ebe399beeff6dfe9cba383959285479ad8bb7a/gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/extensiongrant/ExtensionGrantGranter.java#L101)) ;
Given you use the claim mapper in order to copy some claims from the assertion to the returned token ;
Given, in the LDAP IDP config, you use the user mapper feature and role mapper feature;
Given the JWT Bearer request contains the "openid" scope;

Then, the response should contain both an access_token and an id_token - OK
Then, the returned Id_token should contain the claims mapped from the assertion - KO
Then, the returned Id_token should contain the claims mapped from the IDP mappers - KO

### Current behavior
Big picture workflow :
```
TokenEndpoint.handle()
  --> AbstractTokenGranter.grant()
    --> ExtensionGrantGranter.resolveResourceOwner() 
       --> (A) JWTBearerExtensionGrantProvider.grant()
         --> returns a User with the mapped claims from the assertion
       --> (B) IDP.loadbyusername()
         --> LdapAuthenticationProvider.loadUserByUsername() --> return User with mapped claims from user mapper and group mapper
            --> LdapAuthenticationProviderConfiguration() --> return LdapEntry
```

1. Claims from (A) and (B) are not merged. (B) looks to have precedence
2. None of the claims returned by (B) are present in the returned id_token

### Your Environment
* Version used: 2.10.9

### Other
Also, it would be great to let the user choose which claim from the JWT Bearer represents the user ID. The current logic is to pick the "preferred_username" by default, if present. If not present, the "sub" claim. 
I can post another issue for this request.

**Comment by bcollard** [comment]
Maybe I'm misusing the product but I've the same issue when using the "custom claims" for another AM Client (in another domain using an OIDC server as the IdP).

So, these custom claims are not appended to, in my case, the id_token:
![image](https://user-images.githubusercontent.com/9626829/78148971-c2e38200-7435-11ea-8cb6-040572beaeb0.png)

Returned id_token:
```
{
    "sub": "51b48c61-a667-4de0-b48c-61a6672de006",
    "aud": "PROJ-APIM-DEV",
    "iss": "https://auth.dev.proj.mycompany.com/gateway/apim-portal-domain/oidc",
    "preferred_username": "bcollard",
    "exp": 1585766541,
    "iat": 1585752141,
    "nonce": "tihl0j2a9ps"
  }
```

These claims exist in the users collection in mongo:
```
{
	"_id" : "51b48c61-a667-4de0-b48c-61a6672de006",
	"accountNonExpired" : true,
	"accountNonLocked" : true,
	"additionalInformation" : {
		"email_mapped" : "me@mycompany.com",
		"sub" : "me@mycompany.com",
		"given_name_mapped" : "b",
		"auth_time" : NumberLong(1585750976),
		"preferred_username" : "bcollard",
		"preferred_username_mapped" : "bcollard",
		"department_mapped" : "my_department_name"
	},
	"client" : "PROJ-APIM-DEV",
	"createdAt" : ISODate("2020-03-31T11:54:04.948Z"),
	"credentialsNonExpired" : true,
	"domain" : "apim-portal-domain",
	"enabled" : true,
	"externalId" : "me@mycompany.com",
	"internal" : false,
	"loggedAt" : ISODate("2020-04-01T14:22:56.761Z"),
	"loginsCount" : NumberLong(7),
	"preRegistration" : false,
	"registrationCompleted" : false,
	"roles" : [
		"f55fe510-8d97-4156-9fe5-108d9761566a"
	],
	"source" : "c003187a-f894-41c4-8318-7af89471c4a8",
	"updatedAt" : ISODate("2020-04-01T14:22:56.761Z"),
	"username" : "bcollard"
}
```

Please, notice that, this time, with a OIDC IdP, the user mapper and group mapper are working fine.

**Comment by tcompiegne** [comment]
Hi @bcollard ,

For the custom claims try with this syntax : 

pref1 => `{#context.attributes['user']['claims']['preferred_username']}`

**Comment by bcollard** [comment]
Great, that helped: 
> pref1 => `{#context.attributes['user']['claims']['preferred_username']}`

I will have a second look at my initial issue because this can help also, in part.

**Comment by bcollard** [comment]
So, yes regarding the problem annotated "1.", that still looks to be the case. [See here](https://github.com/gravitee-io/graviteeio-access-management/blob/2.10.x/gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/extensiongrant/ExtensionGrantGranter.java#L107)
I think we can keep this ticket opened in this regard.

For the second point, I solved it by using [OIDC standards claim names and scopes](https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims).

For the following notices:
> and BTW, that should disable the option above named "User creation", otherwise, the condition is never met in the code

> Also, it would be great to let the user choose which claim from the JWT Bearer represents the user ID. The current logic is to pick the "preferred_username" by default, if present. If not present, the "sub" claim.

I can post 2 new tickets

**Comment by bcollard** [comment]
So, finally, this issue in not a big deal for me. As I was able to get the requested claims from my IdP, thanks to the user mapper. 
Feel free to close it.

**Comment by bcollard** [comment]
This issue became too messy.

I created new ones with dedicated topics
https://github.com/gravitee-io/issues/issues/3530 <-- Role mapping with LDAP
https://github.com/gravitee-io/issues/issues/3531 <-- Management UI UX in the JWT Bearer extensio, with User lookup VS User creation
https://github.com/gravitee-io/issues/issues/3532 <-- JWT bearer: claim to use for user lookup
