### ISSUE TITLE
[management] admin role in ldap not mapped to management:admin or portal:admin

### ISSUE THREAD

**Issue by sfreard** [gravitee-io/issues#3407]
roles inherited from ldap are not mapped to management or portal role in gravitee
### Expected Behavior

admin role in ldap should management:admin and portal:admin role in gravitee

### Current Behavior

admin role in ldap provide admin role in gravitee but gives no rigths to user with that role

### Steps to Reproduce (for bugs)

create en GRAVITEE-ADMIN group in ldap, add user1 as member of this group
map GRAVITEE-ADMIN to ADMIN in management API configuration
log in as user1

### Your Environment

* Version used: Gravitee 1.3.5

**Comment by aelamrani** [comment]
@sfreard 

Is it still relevant? Can you give the exact version you were using? I think there is a typo on the version here.

**Comment by sfreard** [comment]
Gravitee 1.3.5 or 1.3.8
The configuration is :
- in ldap server : 4 groups named GRAVITEE-ADMINS,GRAVITEE-CONSUMERS,GRAVITEE-USERS,GRAVITEE-PUBLISHERS
- in gravitee api config : 
- role:
            attribute: "cn"
            mapper: {
              GRAVITEE-CONSUMERS: API-CONSUMER,
              GRAVITEE-PUBLISHERS: API-PUBLISHER,
              GRAVITEE-ADMINS: ADMIN,
              GRAVITEE-USERS: USER
In portal
users in group GRAVITEE-PUBLISHERS are granted [MANAGEMENT] USER - [PORTAL] USER
users in group GRAVITEE-ADMINS are granted [MANAGEMENT] USER - [PORTAL] USER

**Comment by aelamrani** [comment]
Sorry but the versions 1.3.5 or 1.3.8 does not exists. See https://download.gravitee.io/graviteeio-apim/distributions/

**Comment by sfreard** [comment]
1.30.5 and 1.30.8

**Comment by aelamrani** [comment]
Ok so you are running old versions. May I ask you to upgrade and try if it fix your problem? Last 1.30.x version is 1.30.31.

**Comment by sfreard** [comment]
Will install version 3 on next Tuesday.

De : Elamrani Azize
Envoyé : vendredi 19 février 2021 12:11
À : gravitee-io/issues <issues@noreply.github.com>
Cc : FREARD Stephane <Stephane.FREARD@loire-atlantique.fr>; Mention <mention@noreply.github.com>
Objet : Re: [gravitee-io/issues] [management] admin role in ldap not mapped to management:admin or portal:admin (#3407)


Ok so you are running old versions. May I ask you to upgrade and try if it fix your problem? Last 1.30.x version is 1.30.31.

-
