### ISSUE TITLE
[platform] [node] Technical API _node/configuration end-point doesn't resolve env variables

### ISSUE THREAD

**Issue by gasparir** [gravitee-io/issues#3419]
GET /_node/configuration
returns the content of the default gravitee.yml of the distribution, without any c

### Expected Behavior
As described here: https://docs.gravitee.io/apim/1.x/apim_installguide_management_api_technical_api.html
the end-point should also return the env vars

### Current Behavior
No env vars resolution

### Steps to Reproduce (for bugs)

1. on mgmt-api:  wget http://localhost:18083/_node/configuration

### Context
Trying to understand if all my env vars are correctly loaded.

### Your Environment

* Version used: 1.30.7, mgmt-api

**Comment by NicolasGeraud** [comment]
Indeed it's an error in the documentation, we only get the configuration file.

But you're right, we have to also get environment variables and system properties. The problem is that we have to manage the override ...

**Comment by NicolasGeraud** [comment]
@gasparir Hi,

we suggest to provide different query parameters to select which configuration you request (gravitee.yml, system properties, environment variables).
By default, we will return the gravitee.yml config.

**Comment by gasparir** [comment]
@NicolasGeraud Hi.

thank you for looking at this. Proposed solution with query parameters  would be fine for me.
