### ISSUE TITLE
[gateway] Compression must be enabled by default

### ISSUE THREAD

**Issue by smile59** [gravitee-io/issues#343]
By default Gzip and deflate compression are disabled. Consequently, It's impossible to read http-dump log with a cat/nano... 

Currently we can enable compression in api settings > gateway > endpoints settings

It could be interesting to activate this option by default.

[edit]
Without this option html to json can't work correctly

**Comment by brasseld** [comment]
Compression algorithm must be activated by default because it's the way to tell to the backend server that the gateway "understand" gzip or deflate content.
