### ISSUE TITLE
[management-api] Should jwt.secret be a required value

### ISSUE THREAD

**Issue by pf-mike-breaton** [gravitee-io/issues#3434]
Happened to find the following messages in my api logs and was wondering what its implications are:

```
23:17:03.904 [graviteeio-node] WARN  i.g.m.s.c.BasicSecurityConfigurerAdapter - ##############################################################
23:17:03.904 [graviteeio-node] WARN  i.g.m.s.c.BasicSecurityConfigurerAdapter - #                      SECURITY WARNING                      #
23:17:03.904 [graviteeio-node] WARN  i.g.m.s.c.BasicSecurityConfigurerAdapter - ##############################################################
23:17:03.905 [graviteeio-node] WARN  i.g.m.s.c.BasicSecurityConfigurerAdapter -
23:17:03.905 [graviteeio-node] WARN  i.g.m.s.c.BasicSecurityConfigurerAdapter - You still use the default jwt secret.
23:17:03.905 [graviteeio-node] WARN  i.g.m.s.c.BasicSecurityConfigurerAdapter - This known secret can be used to impersonate anyone.
23:17:03.905 [graviteeio-node] WARN  i.g.m.s.c.BasicSecurityConfigurerAdapter - Please change this value, or ask your administrator to do it !
```

It seems setting a `jwt.secret` cfg value resolves. 

### Expected Behavior
Shouldn't the absence of this variable force the api to exit initialization with an appropriate error message?

### Current Behavior
If default value is not overridden, only a warning is displayed in the logs

### Possible Solution
Cause the API to fail to start if an appropriate secret is not provided. 
Display appropriate reason on logs

### Your Environment
* Version used: 1.30.7
* Operating System and version: Docker/kubernetes

**Comment by brasseld** [comment]
Yes, `jwt.secret` is a required value.

So yes, it should force to exit, you are right!

**Comment by pf-mike-breaton** [comment]
Thanks, will this be addressed in a future release?
