### ISSUE TITLE
[management-ui] Client secret displaying coherency

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#3446]
From the `Overview` we can see the client_secret

![Capture d’écran 2020-04-07 à 12 10 02](https://user-images.githubusercontent.com/133094/78657309-dfb20680-78c8-11ea-9bea-9c8268f68542.png)

But not from `Settings`
![Capture d’écran 2020-04-07 à 12 10 06](https://user-images.githubusercontent.com/133094/78657312-e0e33380-78c8-11ea-8fb2-1330105a3a7f.png)

We should probably apply the same rule to access the client_secret.

IMHO, the best is the solution from Overview.

**Comment by jhaeyaert** [comment]
I think we can close this issue since #3438, sensitives data are now hidden. Overview and Settings are now aligned.

![image](https://user-images.githubusercontent.com/5955401/79353610-90f51400-7f3b-11ea-8f72-5042771c0f12.png)

**Comment by brasseld** [comment]
LGTM
