### ISSUE TITLE
[management-ui] Do not show client/app template from Applications list

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#3455]
![Capture d’écran 2020-04-07 à 14 23 32](https://user-images.githubusercontent.com/133094/78668713-6d96ed00-78db-11ea-8fbd-06b3e3278bbb.png)

We know client templates from Settings > Client Registration > Client Templates (tab)

**Comment by tcompiegne** [comment]
After some internal GS team discussions, this issue can be closed.
