### ISSUE TITLE
[portal] Others APIs

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#3474]
<img width="429" alt="Capture d’écran 2020-04-08 à 07 44 52" src="https://user-images.githubusercontent.com/133094/78748705-f6119e00-796c-11ea-82af-49c0b3d14822.png">

**Comment by phiz71** [comment]
Has been fixed in an other issue
![image](https://user-images.githubusercontent.com/13161768/79634676-51613e80-816c-11ea-9917-729b3c43cb92.png)
