### ISSUE TITLE
[portal] Navigate to a "connected" application

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#3482]
When I have an application linked to an API I'm looking on, I would like to quickly navigate to this one by clicking on it

<img width="571" alt="Capture d’écran 2020-04-08 à 07 57 55" src="https://user-images.githubusercontent.com/133094/78749521-b481f280-796e-11ea-9d22-c135513ed697.png">

**Comment by phiz71** [comment]
will be fixed with #3487
