### ISSUE TITLE
[portal] Subscription filter is not working

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#3485]
When I select a filter for my subscription, there is no result, but I know I have some subscription.

<img width="1270" alt="Capture d’écran 2020-04-08 à 08 03 03" src="https://user-images.githubusercontent.com/133094/78749883-65888d00-796f-11ea-81cc-0649e80aa3ea.png">

**Comment by aelamrani** [comment]
Closed by https://github.com/gravitee-io/issues/issues/3489
