### ISSUE TITLE
[portal] Subscribed APIs: navigate to API

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#3487]
I would like to click on API to navigate to it.

<img width="489" alt="Capture d’écran 2020-04-08 à 08 04 24" src="https://user-images.githubusercontent.com/133094/78750031-b8624480-796f-11ea-9f66-b8fc5e89c0c3.png">

**Comment by gcusnieux** [comment]
also fix gravitee-io/issues#3482 ?
