### ISSUE TITLE
[identityprovider] [ldap] Using LDAP and OAuth at the same time

### ISSUE THREAD

**Issue by IvoIlic95** [gravitee-io/issues#3503]
Hello

I hope all of you are doing well and stayed healthy during this difficult time!

Is it possible to use LDAP and OAuth2 simultaneously, because I don't know for what LDAP is used for in Gravitee APIM? Just for searching users and/or for authentication?! Because the authentication part is handled by OAuth2 in my case. So now I don't know the purpose of LDAP in this case.

I have the Problem when I am adding a user to a group I want to search this specific user by his name. After a while a message comes out in my log:

```
11:26:42.151 [gravitee-listener-33] DEBUG o.s.l.c.s.AbstractContextSource - Got Ldap context on server 'ldaps://XXX.XXX.XXX.com:1111'


11:26:46.562 [gravitee-listener-30] INFO i.g.m.i.l.lookup.LdapIdentityLookup - Too much results while searching for [Ivo]. Returns an empty list
```

I can only find the users who were logged in with OAuth2. But when I am searching for a user who wasn't logged in yet and who doesn't use OAuth2 I get the message from above. My gal is to search users by using LDAP so that I can add them to groups and kinda stuff.

I hope you can understand what I am looking for!

Kind regards,
Ivo

**Comment by brasseld** [comment]
Perhaps you can update the user search tree to avoid returning too much results?
