### ISSUE TITLE
[management-ui] should reject domain name with '/'

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#3507]
Currently, when creating a new domain, it is possible to define a name containing '/' character.
There are few things we can do to prevent this situation:
- limit accepted characters on the UI side
- rely on gravitee `Utils.generate (String)` method to generate a safer domain id

**Comment by brasseld** [comment]
https://github.com/gravitee-io/issues/issues/2921

**Comment by brasseld** [comment]
Virtual-Host would allow '/'

https://github.com/gravitee-io/issues/issues/3199
