### ISSUE TITLE
[management-api] We can create pages without type

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#351]
use docker 1.1.0
In portal, i create an api test, fill only mandatory fields.

in postman, i use get api to have id:
8083/management/apis

i keep id
use get api: 8083/management/apis/f68a7233-9784-4220-8a72-3397840220fd
return OK, status 200
use post pages api:  :8083/management/apis/f68a7233-9784-4220-8a72-3397840220fd/pages
body:
{
    "name": "produit-doc",
    "content": "json",
    "source": {
      "type": "http-fetcher",
      "configuration": {
        "url": "http://128.239.252.127:8080/v2/products/docs"
      }
    },
    "configuration": {
      "tryItURL": "http://128.239.252.127:8080/v2",
      "tryIt": true
    }
}

return OK with status 201 and body:
{
  "id": "0463176f-6803-42de-a317-6f6803b2de49",
  "name": "produit-doc",
  "content": "{\"basePath\":\"/v2\",\"paths\":{\"/products/search\":{\"get\":{\"summary\":\"Search for product ...
[{\"name\":\"Product\",\"description\":\"Search product\"}]}\n",
  "order": 1,
  "lastContributor": "admin",
  "published": false,
  "lastModificationDate": 1480606163747,
  "contentType": "application/json",
  "source": {
    "type": "http-fetcher",
    "configuration": {
      "url": "http://128.239.252.127:8080/v2/products/docs"
    }
  },
  "configuration": {
    "tryItURL": "http://128.239.252.127:8080/v2",
    "tryIt": true
  }
}

if i go to portal in this api document tab, i get popup error with http_status=500
and got the same with api get pages

if i delete pages with return id in creation, return is 204, and portal and get api are OK now

**Comment by NicolasGeraud** [comment]
hi @vdelattre , when you say
> if i go to portal in this api document tab, i get popup error with http_status=500

are you in configuration mode (you have clicked on the settings icon) or in view mode ?

**Comment by vdelattre** [comment]
popup is in view mode, but in configuration mode, it's the same

**Comment by NicolasGeraud** [comment]
your documentation is not published. You have to publish it in order to view it.
Do you navigate threw the documentation or do you fill the address bar of your browser ?

**Comment by NicolasGeraud** [comment]
And can you give us your logs form the rest-api container ?

**Comment by vdelattre** [comment]
i retry all
after post, i made put with published to true
but result is the same
in view mode, configuration mode and get pages api, error 500
i don't find any thing in container log, can you explain in which docker and path inside it to find log?

**Comment by NicolasGeraud** [comment]
`docker logs -f <MANAGEMENT_API_CONTAINER_NAME>`

and retry

**Comment by NicolasGeraud** [comment]
do you provide page type ? I don't see it in your POST

**Comment by NicolasGeraud** [comment]
if not, this is probably the cause of your problem (and it's a bug in the management api because we should not accept unknown page type)

**Comment by vdelattre** [comment]
you right, i forgot type
with type=swagger it's ok

**Comment by NicolasGeraud** [comment]
ok, good.
