### ISSUE TITLE
[management-api] allowed to set unknown group to an api

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#354]
I tried to create an api with post api.

**body**
```json
{
  "name": "products",
  "version": "v1",
  "description": "api igr product",
  "contextPath": "/v2/products",
  "endpoint": "http://128.239.252.99:8080/v2/products"
}
```

**response**: `404`
```json
{
  "message": "Group [IGR Owners] can not be found.",
  "http_status": 404
}
```

But now, in UI, on api tab, i have red popup error: `Group [IGR Owners] can not be found`

and in get list api, i have message :
```json
{
  "message": "Group [IGR Owners] can not be found.",
  "http_status": 404
}
```

How can i manage to delete this wrong api?

**Comment by NicolasGeraud** [comment]
What is the role of the user you use when you POST your api.
Is he member of the IGR Owners group ?

**Comment by vdelattre** [comment]
I didn't use authentification to post

Le 1 déc. 2016 6:00 PM, "Nicolas Géraud" <notifications@github.com> a
écrit :

**Comment by brasseld** [comment]
You must be authenticated to create an API.

If I run this curl command:
```shell
curl -vvv -H "Content-Type: application/json" -X POST -d '{"name": "products","version": "v1","description": "api igr product","contextPath": "/v2/products","endpoint": "http://128.239.252.99:8080/v2/products"}' http://localhost:8083/management/apis
```

I get an (expected) 401 status code:
```shell
> POST /management/apis HTTP/1.1
> Host: localhost:8083
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 152
>
* upload completely sent off: 152 out of 152 bytes
< HTTP/1.1 401 Full authentication is required to access this resource
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Headers: Cache-Control, Pragma, Origin, Authorization, Content-Type, X-Requested-With
< Access-Control-Allow-Methods: POST, PUT, GET, OPTIONS, DELETE, X-XSRF-TOKEN
< Access-Control-Max-Age: 1209600
< WWW-Authenticate: Basic realm="Gravitee.io Management API"
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Pragma: no-cache
< X-Frame-Options: DENY
< Cache-Control: must-revalidate,no-cache,no-store
< Content-Type: text/html;charset=iso-8859-1
< Content-Length: 0
```

So you have pass an authentification to create an API.

**Comment by NicolasGeraud** [comment]
are you using postman ?

**Comment by vdelattre** [comment]
i confirm
i used postman and i didn't send authentification

**Comment by brasseld** [comment]
Ok, so postman is using transparently cookies from your browser that's the reason why you did not need to set `authorization` headers.

So, it did not solve the issue anymore.

Can you provide us with a complete scenario to reproduce the issue, if you're able to.

**Comment by NicolasGeraud** [comment]
could you provide a dump of your datas ?

or at least the the api, users, groups, memberships

**Comment by vdelattre** [comment]
OK i deleted volume docker to start from crash
with postman, i call api with no authentification:
1) get http://192.168.175.43:8083/management/apis
return 200, no result

2) in UI, create group api named IGR owners

3) post http://192.168.175.43:8083/management/apis
header basic auth:
admin/xxxx
body: 
{
  "name": "products",
  "version": "v1",
  "description": "api igr product",
  "contextPath": "/v2/products",
  "group": "IGR Owners",
  "endpoint": "http://128.239.252.99:8080/v2/products"
}

return 404
{
  "message": "Group [IGR Owners] can not be found.",
  "http_status": 404
}

4) get http://192.168.175.43:8083/management/apis
error 404
{
  "message": "Group [IGR Owners] can not be found.",
  "http_status": 404
}

5) same as num 4


=> i think error is in group name or id, but no where i see id of group api

**Comment by brasseld** [comment]
Hi @vdelattre,

You're right, the issue is about group reference because you have to specify the group ID and not the group name. That's the reason why you got this error.

For your information, you can retrieve ID of your group by calling this service:
`http://192.168.175.43:8083/management/configuration/groups/`

And use the id in place of the group name.

**Comment by brasseld** [comment]
In any case, this issue is still valid because you should not be able to create an API with an invalid group reference.

**Comment by vdelattre** [comment]
For information, your swagger.json doesn't show configuration/groups

**Comment by brasseld** [comment]
Right, I'm creating an other issue to update Swagger descriptor.
