### ISSUE TITLE
[portal] API documentation is hidden by menu

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#3540]
![image](https://user-images.githubusercontent.com/13161768/79236948-e4992c00-7e6d-11ea-803e-4e3edc397f08.png)
![image (1)](https://user-images.githubusercontent.com/13161768/79236969-e9f67680-7e6d-11ea-96d4-c33035d193c2.png)

**Comment by aelamrani** [comment]
May have a link with https://github.com/gravitee-io/issues/issues/3495
May be due to https://github.com/gravitee-io/issues/issues/2982
