### ISSUE TITLE
[policy] [request-validation] support for type "ENUM"

### ISSUE THREAD

**Issue by aleksey1972** [gravitee-io/issues#3556]
### Expected Behavior

Refine policy-request-validation add verification type "ENUM"

### Current Behavior

Currently, it is not possible to check the input parameter for compliance with one of the values

### Possible Solution
Implement support of type ENUM.
I am ready to finalize the policy and make a pull request

### Steps to Reproduce (for bugs)
not

### Context

For example (fragment from Swagger);
      - name: "scope"
        type: "string"
        <b>enum:</b>
         - "openid"
         - "account_linking"
         - "token_exchange"

### Your Environment

Version used: Gateway and APIM v 1.30.5
Browser Name and version: Google Chrome 80.0.3987.163
Operating System and version: Ubuntu 16.04.3

**Comment by brasseld** [comment]
Hi @aleksey1972 

Looking forward to test your PR.

Let me know if you need help or if you have any implementation question.

Cheers

**Comment by aleksey1972** [comment]
Good day!
I see that my Pull Request (https://github.com/gravitee-io/gravitee-policy-request-validation/pull/19) is still in the status: Open. Please tell me, didn’t I finish something or forgot about something?

**Comment by aleksey1972** [comment]
Hi!
I have prepared Pull Request # 22

**Comment by brasseld** [comment]
Nice job @aleksey1972!

Thanks a lot,
