### ISSUE TITLE
[management] User avatar is not displayed anymore on the file upload component

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#3570]
![Capture d’écran 2020-04-16 à 10 41 25](https://user-images.githubusercontent.com/1580262/79434637-f514e800-7fce-11ea-8355-186bab4fc3ef.png)

**Comment by phiz71** [comment]
And there is a scale problem with vertical image
![image](https://user-images.githubusercontent.com/13161768/79540737-eee34200-8088-11ea-9902-708261bbd55c.png)

**Comment by phiz71** [comment]
Will be fixed with #3490
