### ISSUE TITLE
[management-api] Change password for default admin account

### ISSUE THREAD

**Issue by bat79a** [gravitee-io/issues#3575]
I can't see any option for changing the default password for the account admin (with the admin account), so I try to override the password with a variable in my kubernetes manifest (manual deployment).

### Expected Behavior
After overriding the variable : gravitee_security_providers_0_users_1_password (in my yml manifest because I'm deploying via kubernetes) with this hash value that I have found in your exemple : $2a$10$iXdXO4wAYdhx2LOwijsp7.PsoAZQ05zEdHxbriIYCbtyo.y32LTji (=> api1)
The default account is still admin with the password admin and not api1

I have try all this other variables : 
- gravitee_security_providers_0_users_0_password
- gravitee_security_providers_1_users_0_password
- gravitee_security_providers_1_users_1_password

### Current Behavior
The default account is still admin with the password admin and not api1 (=> $2a$10$iXdXO4wAYdhx2LOwijsp7.PsoAZQ05zEdHxbriIYCbtyo.y32LTji)

### Possible Solution
The variable is not overriding the default value ?

### Steps to Reproduce (for bugs)
1. Add a value to the variable gravitee_security_providers_0_users_1_password in my ConfigMap manifest (not the secret one because the secret manifest need a base64 encoded and the $ breaks this encoded value)
2. Start all containers (gateway, management-api, management-ui) with an empty mongoDB
3. Try to login with admin / admin
4. It works, but the password must be api1 not admin

### Context
Change the default admin password.

### Your Environment
* Version used: 1.30.8 for all containers/images
* Browser Name and version: Chrome
* Operating System and version: GKE on manual install of all the gravitee stack

**Comment by bat79a** [comment]
Petit up ;p
If someone has the same problem ?

**Comment by bat79a** [comment]
Tryed again without success.
kubectl exec echo of my variable respond the new value but doesn't override the default value.

So I have mount the gravitee.yml file and with this I can change the default value.

**Comment by aelamrani** [comment]
Hi @bat79a 

I'm closing this issue as there is already a related issue: https://github.com/gravitee-io/issues/issues/2680
