### ISSUE TITLE
[management] insufficient right after creating an api with default user 'api1'

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#3576]
After creating an api using the `api1` user, it is not possible to do anything else due to insufficient permission.

![image](https://user-images.githubusercontent.com/5955401/79459916-53a08d00-7ff4-11ea-8350-02714a18059e.png)

**Comment by phiz71** [comment]
Linked to #2984

**Comment by aelamrani** [comment]
Fixed by https://github.com/gravitee-io/issues/issues/3392
