### ISSUE TITLE
[oauth2] Error response

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#3577]
As per https://www.ietf.org/rfc/rfc6749.txt

4.1.2.1.  Error Response

```
state
         REQUIRED if a "state" parameter was present in the client
         authorization request.  The exact value received from the
         client.
```

**Comment by tcompiegne** [comment]
Seems to be part of the `Authorization` flow (Code and Implicit) since there is no `state` parameter for the Token Endpoint requests.

Already done for the Authorization Endpoint.

**Comment by brasseld** [comment]
Hum, ok.

I was drunk :)

We can close it
