### ISSUE TITLE
[management-ui] multiple update user roles requests when just displaying a user

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#3586]
When clicking on a user from the user list screen, 2 calls are made to update the user's roles

![image](https://user-images.githubusercontent.com/5955401/79478957-54ddb400-800c-11ea-8239-583cef736b5c.png)

The consecutive calls are very close (role ids are just inverted):

![image](https://user-images.githubusercontent.com/5955401/79479263-cd447500-800c-11ea-981d-c1a82093d3cc.png)

![image](https://user-images.githubusercontent.com/5955401/79479301-daf9fa80-800c-11ea-8a24-e5a1b6db1023.png)

**Comment by phiz71** [comment]
https://github.com/angular/material/issues/6778
