### ISSUE TITLE
[portal] Indefinite loading

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#3606]
https://v3.nightly.gravitee.io/catalog/api/770bbd70-516d-42d1-8bbd-70516d42d1dd/doc.  

<img width="1554" alt="Capture d’écran 2020-04-18 à 07 56 11" src="https://user-images.githubusercontent.com/133094/79629440-2108a880-814a-11ea-8e3b-ce5c343414d5.png">

**Comment by phiz71** [comment]
Duplicate #3469
