### ISSUE TITLE
[portal] Duplicate end of subscription

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#3608]
The end of subscription is shown twice (top and bottom)

<img width="355" alt="Capture d’écran 2020-04-18 à 08 09 55" src="https://user-images.githubusercontent.com/133094/79629718-13542280-814c-11ea-8240-f56977068eda.png">

**Comment by aelamrani** [comment]
Will be fixed by https://github.com/gravitee-io/issues/issues/3542
