### ISSUE TITLE
[management] Cannot update an API with pages anymore

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#3618]
Probably since this [commit](https://github.com/gravitee-io/gravitee-management-rest-api/commit/b6f3c148c887880a2766bb1c39e2dfb63327b53f), we cannot update an API with pages. We get an error: `Not able to identify the page to update: blabla. Too much page with the same name`

This commit has added ids on pages when exporting.

We need to handle the case when an API has multiple pages with same name / type.

Maybe we should prevent from creating pages with same name / type on the same directory?

We have also to handle cases without ids for those who are updating from CI/CD (without ids).

**Comment by gaetanmaisse** [comment]
Closing as it has been fixed by https://github.com/gravitee-io/gravitee-management-rest-api/pull/982 but the issue hasn't been closed
