### ISSUE TITLE
[platform] APIM nightly not working with platform docker-compose

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#3620]
APIM is not working anymore when running with the platform [docker-compose](https://github.com/gravitee-io/gravitee-docker/blob/master/platform/docker-compose.yml) and nightly version (v3).

Other components seems working well.

![image](https://user-images.githubusercontent.com/5955401/79769423-5ff65400-832c-11ea-9ee0-ab93366f48b2.png)

### Expected Behavior

The whole nightly Gravitee stack should work when starting a fresh installation (no previous database, no previous container, latest nightly build, ...).

### Current Behavior

All components including APIM are booting well but when trying to authenticate on the APIM management portal with the default admin user, there is an unexpected error.

Docker logs show there is a problem with DB indexes :
```
apim_management_1  | 15:05:30.083 [gravitee-listener-43] WARN  org.eclipse.jetty.server.HttpChannel - /management/organizations/DEFAULT/environments/DEFAULT/user/login
apim_management_1  | org.springframework.dao.DuplicateKeyException: E11000 duplicate key error collection: gravitee.memberships index: _id.userId_1__id.referenceId_1__id.referenceType_1 dup key: { : null, : null, : null }; nested exception is com.mongodb.MongoWriteException: E11000 duplicate key error collection: gravitee.memberships index: _id.userId_1__id.referenceId_1__id.referenceType_1 dup key: { : null, : null, : null }
apim_management_1  | 	at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:101)
apim_management_1  | 	at org.springframework.data.mongodb.core.MongoTemplate.potentiallyConvertRuntimeException(MongoTemplate.java:2774)
......
org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
apim_management_1  | 	at java.lang.Thread.run(Thread.java:748)
apim_management_1  | Caused by: com.mongodb.MongoWriteException: E11000 duplicate key error collection: gravitee.memberships index: _id.userId_1__id.referenceId_1__id.referenceType_1 dup key: { : null, : null, : null }
apim_management_1  | 	at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:967)
apim_management_1  | 	at com.mongodb.client.internal.MongoCollectionImpl.executeInsertOne(MongoCollectionImpl.java:494)
apim_management_1  | 	at com.mongodb.client.internal.MongoCollectionImpl.insertOne(MongoCollectionImpl.java:478)
apim_management_1  | 	at com.mongodb.client.internal.MongoCollectionImpl.insertOne(MongoCollectionImpl.java:472)
apim_management_1  | 	at org.springframework.data.mongodb.core.MongoTemplate$6.doInCollection(MongoTemplate.java:1436)
apim_management_1  | 	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:538)
apim_management_1  | 	... 99 common frames omitted
```

### Possible Solution

Seems due to bad indexes on the memberships collection but even after removing and creating the right indexes (using this script : https://github.com/gravitee-io/gravitee-repository-mongodb/blob/master/src/main/resources/scripts/create-index.js), there is still an error.

### Steps to Reproduce (for bugs)

1. git clone git@github.com:gravitee-io/gravitee-docker.git
2. cd platform
3. APIM_VERSION=nightly AM_VERSION=nightly AM_MGT_API_BASE="\/" docker-compose pull
4. APIM_VERSION=nightly AM_VERSION=nightly AM_MGT_API_BASE="\/" docker-compose up
5. Wait few second (or a bit more)
6. go to https://apim.gravitee.io/portal (don't forget to set your /etc/hosts)
7. Try to authenticate as admin.
8. You should have an error and see errors in docker logs

### Context

Note that there is no problem when running APIM from master (== nightly) using IDE.

**Comment by aelamrani** [comment]
Not relevant anymore
