### ISSUE TITLE
Protected API with Gravitee

### ISSUE THREAD

**Issue by RemDav** [gravitee-io/issues#3623]
Hi everybody,

How protected my api with gravitee, because a hacker find my public address can use my API without user connection.

**Comment by brasseld** [comment]
Use different possibilities to filter:
- based on ip-filtering
- based on stronger authentication

**Comment by RemDav** [comment]
Thank for this but if a user find my public ip. My API not really protected. it is necessary this protected my API nodejs

**Comment by brasseld** [comment]
Sorry but we know nothing about your API, how it is protected, etc...  
So I'm not sure how we can help you

**Comment by RemDav** [comment]
I am currently in the process of an API with node. I don't want to protect her. I would like everything to go via gravity (jwt, refreshtoken) and keycloak

**Comment by brasseld** [comment]
So what's the problem if you are able to protect jwt and keycloak?

**Comment by RemDav** [comment]
The protection will therefore be done via keycloak?

**Comment by brasseld** [comment]
The "protection" will be done by both gravitee and keycloak.

Keycloak is used to generate access_token (JWT)
And Gravitee is used to validate these tokens when consuming APIs.

**Comment by RemDav** [comment]
Thank you, in a standard system I would have created my JWT and my refresh token and I would have protected my routes with these tocken. But there I will not protect my roads because I want it to be gravity which manages this security. So my roads are not directly protected. But if a user finds my ip, he can consume my API freely. Because gravitee only manages the domain name it knows

**Comment by brasseld** [comment]
why not setting up firewal restrictions to allow access to your API only from the gateway ?

**Comment by RemDav** [comment]
We don't have a firewall

**Comment by brasseld** [comment]
So I would say there is nothing more we can do here.

You have to put the right tools in place.

**Comment by RemDav** [comment]
I did several research. I saw with keycloak it is possible to protect its API, is it possible to protect its API only with keycloak without going through gravity?

**Comment by ptemplier** [comment]
@RemDav if your API is publicly available (no ip restriction) and not protected (no required auth) then you have multiple options : 

- Add authentication directly to your API (so you don't need Gravitee or Keycloak)
- Restrict access by IP so that only Gravitee can access it and require authentication to access it through Gravitee (you can do it simply requiring an api-key)
- You can go further by adding Keycloak and configure Gravitee to delegate authentication to Keycloak (Keycloak alone can't protect your API)

**Comment by RemDav** [comment]
Thank you for this return, so it is possible to protect our API from keycloak and gravity?

**Comment by ptemplier** [comment]
sure but you need to restrict access to your API first or Gravitee and Keycloak could be bypassed.

**Comment by RemDav** [comment]
For example, can I use docker or kubernetes for my APIs and expose just gravity? In addition, I saw that with keycloak it was possible to fully protect an API even if it was made public.

**Comment by RemDav** [comment]
is it safe to expose only gravity and that all my apis are not available? For example: I have an API in apiperso docker and when we do apiperso.com gravity redirects me to http: //apiperso.localhost

**Comment by brasseld** [comment]
Yes it is safe to do so.

**Comment by RemDav** [comment]
Or is it possible to pass through from gravity and protect APIs with keycloack directly by protecting the roads?

**Comment by brasseld** [comment]
if you want to ensure that your backends can not be reach directly without going through the gateway, you have two options:
- Network restrictions (FW)
- MTLS between gateway and backends.
