### ISSUE TITLE
[portal] Instance ip is not in the title anymore

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#363]
## Possible Solution

Change the police (white -> black)
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 1.1.0
* Browser Name and version: Chrome
* Operating System and version: mac os

**Comment by brasseld** [comment]
<img width="1031" alt="capture d ecran 2016-12-09 a 11 12 02" src="https://cloud.githubusercontent.com/assets/133094/21045366/57ef7e3e-be00-11e6-9ceb-c56be058f420.png">
