### ISSUE TITLE
[policy] [dynamic-routing] Two level dynamic routing

### ISSUE THREAD

**Issue by fmercier-almerys** [gravitee-io/issues#3631]
Use case :  
I have several plans and every plan is composed of a dynamic routing policy that route to a dedicated endpoint group:
```
Pattern: (.*)
Target: {#endpoints['default-group']}/{#group[0]}
```

But I have also in API Design area a dynamic policy applied on a endpoint. In this use case I have 2 level dynamic routing and according to @brasseld to fetch the current selected endpoint group the policy configuration is : 
```
Pattern: /messages/reply 
Target: {#context.attributes['gravitee.attribute.request.endpoint']}/messages/{#request.params['id']}/reply
```
It works nice. Might be more convenient to 
* get existing endpoint group in the context if not overrided
* get the first endpoint group if not specified ?

**Comment by brasseld** [comment]
`get the first endpoint group if not specified ?` 

That's already the case as of today.

The only think its that we didn't take care of a previous dynamic-routing result...

**Comment by brasseld** [comment]
Unless I'm wrong, I think this issue is no more relevant
