### ISSUE TITLE
[management-ui] I don't see logs and metrics in UI

### ISSUE THREAD

**Issue by Nmaw** [gravitee-io/issues#3635]
I don't see logs and metrics in UI from Application, API and Gateway.
I see all information in Elasticsearch.

<img width="1789" alt="Screenshot 2020-04-23 at 23 10 09" src="https://user-images.githubusercontent.com/3658835/80145118-597c0c80-85b8-11ea-952b-6ba8fde48068.png">
<img width="1778" alt="Screenshot 2020-04-23 at 23 10 45" src="https://user-images.githubusercontent.com/3658835/80145172-6dc00980-85b8-11ea-8134-199e8a73a7e9.png">
<img width="1778" alt="Screenshot 2020-04-23 at 23 11 04" src="https://user-images.githubusercontent.com/3658835/80145196-79133500-85b8-11ea-9b01-d7b1918ec56f.png">
<img width="1780" alt="Screenshot 2020-04-23 at 23 11 36" src="https://user-images.githubusercontent.com/3658835/80145215-83353380-85b8-11ea-8525-112fbfb394c2.png">

### Current Behavior
No logs, no metrics. 

### Your Environment

* Version used: 1.30.8
* Browser Name and version: Safari, Chrome, FireFox
* Operating System and version: Linux

**Comment by brasseld** [comment]
Looks like you have issue with Elasticsearch.

Please check your logs and ensure that both the gateway and the management-api are sharing the same ES.

**Comment by Nmaw** [comment]
@brasseld 

Configuration Elasticsearch was correct but have been mistake with non correct index in gravitee.yml for Management API. Thanks!
