### ISSUE TITLE
[repository] Upgrade Mongo driver to version 4.0

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#3661]
https://mongodb.github.io/mongo-java-driver/4.0/upgrading/
need upgrading Spring-data-mongodb too
https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#upgrading.2-3

**Comment by phiz71** [comment]
Needs #3926

**Comment by larsnaesbye** [comment]
This would be nice to get fixed. Currently we can't begin with a 4.x MongoDB setup, but need to start at 3.6.x.

**Comment by brasseld** [comment]
@larsnaesbye 

We are using our current distribution with Mongo 4.2 (Atlas) , no problem at all.

Do you have any particular issue ?

**Comment by larsnaesbye** [comment]
We found that if we created the DB using version 4.4.1 we couldn't get it to work  - it seems like the various components couldn't connect, whereas if we created it with the 3.6.x version it works fine.

This may of course be something in the mongo:4.4.1 docker image. I will look more into it.

**Comment by brasseld** [comment]
FYI, I just had a try with g.io 3.2 and Mongo 4.4 : no issue at all with our current driver.

**Comment by larsnaesbye** [comment]
Interesting! Thank you. I apologize - then there must be some other variable in play :-)

**Comment by YoranSys** [comment]
Hi ! 
Do you plan an update in the near future to comply with the official Mongo compatibility matrix?
 https://docs.mongodb.com/drivers/java/#mongodb-compatibility

**Comment by aelamrani** [comment]
Hi @YoranSys ,

Nothing planned on our side for the moment, you can refer to the matrix of supported version here.

Maybe you want to contribute? :)
