### ISSUE TITLE
[gateway] [question] Read only access to MongoDB for gateway users

### ISSUE THREAD

**Issue by Nmaw** [gravitee-io/issues#3667]
Hello,
I have a questions. I have administrator access to MongoDB and I create users accounts for API Management and API Gateway. What minimal right need for API Gateway accounts? API Gateway account read and write to MongoDB or only read configs from MongoDB?

### Your Environment

* Version used: 1.30.8
* Browser Name and version: Safari, Chrome, FireFox latests version
* Operating System and version: Linux

**Comment by brasseld** [comment]
https://docs.gravitee.io/apim/1.x/apim_installguide_repositories_mongodb.html

**Comment by Nmaw** [comment]
Wow! Thanks! 
I do not know what contain collection: "commands" and I do not find collection "events". I want have information about that for calculate risk.
