### ISSUE TITLE
When is necessary to deploy an API , the snack bar pass over

### ISSUE THREAD

**Issue by arnaudforaison** [gravitee-io/issues#367]
When import API or change API visibility, the top screen snack bar pass over the top of the screen
## Expected Behavior

The top of the API global settings must be under the top snack bar when API is out of sync
## Current Behavior

![gravitee_outofsync-issue](https://cloud.githubusercontent.com/assets/1309516/21012446/545e5ca4-bd56-11e6-85a1-ce5ad2666e98.png)

## Steps to Reproduce (for bugs)

1. Manage an API
2. Change API visibility and save

## Your Environment

* Version used: 1.1.0
* Browser Name and version: Chrome 55.0.2883.75
* Operating System and version: Ubuntu

**Comment by NicolasGeraud** [comment]
Hum ...  this will move all your page a few pixels down. I personally don't like that.
What do you think if the page does not fill all the page width?

**Comment by arnaudforaison** [comment]
Ok but your page have space to be few pixel down. My new idea / suggestion may be to have a low height for the snack bar because there are anything on the middle of the page. But the question is the same on other pages.
I think a fix is needed but which ? I discover gravitee and for the moment I can't propose the best solution.

**Comment by NicolasGeraud** [comment]
> Ok but your page have space to be few pixel down.
It's not about is there enough space or not, I don't like, when I click on a button (SAVE) and the button "move" few pixel down under my cursor. I prefer when the button stays on the same place even if the API needs to be deploy.

We have to look on all pages to find the better solution. You talk about the height. Are you sure you didn't want to talk about width ?

**Comment by arnaudforaison** [comment]
Yes , sorry I want to say width and not height. Another solution could be to have transparency

**Comment by brasseld** [comment]
No more relevant
