### ISSUE TITLE
[portal] API visibility icons aren't correctly separated

### ISSUE THREAD

**Issue by arnaudforaison** [gravitee-io/issues#368]
On Global Settings API, radio buttons icons for API visibility aren't correctly separated 

## Expected Behavior

Well separeted
## Current Behavior

![gravitee_outofsync-issue](https://cloud.githubusercontent.com/assets/1309516/21014417/3c57d984-bd5e-11e6-98da-fa98cd2c3c06.png)

## Steps to Reproduce (for bugs)

1. Manage an API
2. Go to Global Settings -> General

## Your Environment

* Version used: 1.1.0
* Browser Name and version: Chrome 55.0.2883.75
* Operating System and version: Ubuntu

**Comment by NicolasGeraud** [comment]
wdyt if api visibility radio buttons are displayed in column ?
<img width="1081" alt="capture d ecran 2016-12-09 14 03 09" src="https://cloud.githubusercontent.com/assets/1028285/21049997/6565396a-be18-11e6-98c4-ad96e386da84.png">

**Comment by brasseld** [comment]
Hum.... finally we have the choice between _public_ and _private_, so why not just a switch ?
https://material.angularjs.org/latest/demo/switch

**Comment by NicolasGeraud** [comment]
you're totally right.

**Comment by brasseld** [comment]
You mean, I'm totally write, right ?

**Comment by NicolasGeraud** [comment]
You're write

**Comment by NicolasGeraud** [comment]
<img src="https://media.giphy.com/media/1tHzw9PZCB3gY/giphy.gif">

**Comment by NicolasGeraud** [comment]
<img width="1272" alt="capture d ecran 2016-12-09 23 16 57" src="https://cloud.githubusercontent.com/assets/1028285/21074402/6a051162-bef8-11e6-87a5-a15ff86c14f6.png">

<img width="1268" alt="capture d ecran 2016-12-09 23 17 23" src="https://cloud.githubusercontent.com/assets/1028285/21074403/6edaf8d2-bef8-11e6-8546-026ca6d550c7.png">

wdyt ?

**Comment by brasseld** [comment]
Imho:
1. Lifecycle status, in admin mode, must be part of the header because we have currently no way to get this status  when we are in others screen. So why not having this status and the relative switch (or an icon) in the API header ?
2. Visibility is a concept mainly used to manage members. So why not moving the switch into the members screen ? Or perhaps simply change the switch for a select combobox because it is easier to understand ?

**Comment by NicolasGeraud** [comment]
Agree with your first point, disagree with the second.
For a new api publisher, I think it's not obvious to go to Members section to manage visibility of the API.

**Comment by NicolasGeraud** [comment]
> perhaps simply change the switch for a select combobox because it is easier to understand ?

this is a good idea, you have UX skills :)

**Comment by brasseld** [comment]
I'm still better to write java source code ;)

So do we need two different issues for those things ?

**Comment by brasseld** [comment]
@NicolasGeraud what is the status of this issue ?

**Comment by NicolasGeraud** [comment]
I haven't work on that since last message.
I'll try to make a PR tomorrow
