### ISSUE TITLE
[management] Live preview on markdown documents is broken

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#3681]
+ Not able to edit a page included in a folder
+ A page in a folder defined as homepage is not displayed on the portal
+ After moved a page from a directory to /, the list of files is not correctly updated with the moved page

**Comment by phiz71** [comment]
- [ ] Live preview on markdown documents is broken
- [x] Not able to edit a page included in a folder
- [x] A page in a folder defined as homepage is not displayed on the portal
- [x] After moved a page from a directory to /, the list of files is not correctly updated with the moved page
