### ISSUE TITLE
[docker] Updating Identity provider gives "Property [syncMappings] is not recognized as a valid property"

### ISSUE THREAD

**Issue by pf-mike-breaton** [gravitee-io/issues#3684]
Get the following error when saving an Authentication Identity:

> Property [syncMappings] is not recognized as a valid property

### Expected Behavior
no errors

### Current Behavior
after adding an external identity and selecting the below option, the above error occurs:

> Group and role mappings are computed during each user authentication. Platform administrators still have the ability to override mappings but those one will be refreshed after next user authentications.

### Context

We need to be able to use the above option in order to ensure access rules are granted and taken away based on the centralized user roles within the external identity provider.

### Your Environment
* Version used: 1.30.9
* Browser Name and version: Chrome 81.0.4044.129
* Operating System and version: Windows 10 2004

**Comment by brasseld** [comment]
Please indicate the repository you are using and its version.

Regards,

**Comment by pf-mike-breaton** [comment]
Docker containers:

- graviteeio/gatewy:1.30.9
- graviteeio/management-api:1.30.9
- graviteeio/management-ui:1.30.9

**Comment by brasseld** [comment]
Sorry, I was asking about the repository : mongo or jdbc

**Comment by pf-mike-breaton** [comment]
oh, sorry: mongo:4.0 (also docker)

**Comment by brasseld** [comment]
haha,

I mean the gravitee repository plugin.
So, you are using the mongodb-repository. Can you tell me which version of the plugin?
Are you running modified version of docker images?

**Comment by pf-mike-breaton** [comment]
All out-of-the-box - it's a local development environment

**Comment by brasseld** [comment]
Hi @pf-mike-breaton 

Can you check that your containers are up-to-date ?

Seems that your mgmt-api is not.

Jut have a try on our env demo, no problem at all: https://demo.gravitee.io/#!/management/settings/identities/am-test

Cheers,

**Comment by pf-mike-breaton** [comment]
Yes, that seems to be the issue, thanks for you time.
