### ISSUE TITLE
Content-Length matching payload not validated before processing POST

### ISSUE THREAD

**Issue by sekman99** [gravitee-io/issues#3685]
While testing the policy https://github.com/gravitee-io/gravitee-policy-request-content-limit I was trying to send in a Content-Length header with a value lower than defined for the policy but with an actual Payload size larger than specified.

For example:
Policy Limit 1000 bytes
Content-Length header set to 999 bytes but size of the Payload is 2500 bytes.

### Expected Behavior
A mismatch in the size of the body and value specified Content-Length header should generate an Error

### Current Behavior
The GW will process the message but cuts the message sent downstream after the specified bytes in the Content-Length header. I can see issues here being able to send incomplete messages by adjusting the content-length header wrongly.

### Steps to Reproduce (for bugs)
1. Setup API or use existing publish API
2. Send request with an payload with size of for example 1500 bytes with cUrl but the content-lenght set to 500:
curl -kv http://localhost:8082/api/test -H "Content-Type: application/json" -d "@payload1500bytes.json"  -H "Content-length: 500"
3. Gravitee will accept the call but will only send the first 500 bytes to downstream server

### Context
Security concerns:
1. Could crash downstream server by sending faulty messages - Does the JSON validator checks the first 500 bytes or all the full payload?

### Your Environment
* Version used: Docker version of 1.30.9
* Operating System and version: Docker version

**Comment by brasseld** [comment]
Hi @sekman99 

I don't see the issue here.

You are telling the gateway that you will send only 500 bytes because of the content-length header. So there is no reason at all to read the rest of data.
