### ISSUE TITLE
[portal] documentation page nav bar must be case sensitive for page name

### ISSUE THREAD

**Issue by arnaudforaison** [gravitee-io/issues#369]
When add / edit documentation page, the page name wasn't case sensitive into the left documentation page nav bar 
## Expected Behavior

Must be case sensitive
## Current Behavior

Documentation page name are on uppercase
## Steps to Reproduce (for bugs)

1. Manage API 
2. Go to Documentation
3. Add a new page MARKDOWN
4. Set a name of this page and save

## Your Environment

* Version used: 1.1.0
* Browser Name and version: Chrome 55.0.2883.75
* Operating System and version: Ubuntu

**Comment by brasseld** [comment]
Rework for page UI will be handle in 1.21

See https://github.com/gravitee-io/issues/issues/1564
