### ISSUE TITLE
[management] Default image invalid on theme part

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#3701]
We should display a message instead of a generated picture.
![Capture d’écran 2020-05-05 à 17 48 24](https://user-images.githubusercontent.com/1580262/81086420-c36dad80-8ef8-11ea-88af-9dc5778e555c.png)

+ Generated avatar is not rounded
![Capture d’écran 2020-05-05 à 17 50 42](https://user-images.githubusercontent.com/1580262/81086616-0a5ba300-8ef9-11ea-8bbf-5dcc8400f35d.png)

**Comment by phiz71** [comment]
REST API needs to be modified to share code between portal and management
