### ISSUE TITLE
[uma2] discovery endpoint

### ISSUE THREAD

**Issue by lusoalex** [gravitee-io/issues#3716]
https://docs.kantarainitiative.org/uma/wg/rec-oauth-uma-grant-2.0.html#as-config
https://docs.kantarainitiative.org/uma/wg/rec-oauth-uma-federated-authz-2.0.html#as-config

User-Managed Access (UMA) 2.0 contains these two specifications :
 - UMA 2.0 Grant for OAuth 2.0 Authorization
 - Federated Authorization for UMA 2.0

While the first one explains how to grant access, the second defines a means for AS & RS to be loosely coupled.  
Both require additional metadata attributes extending the original oauth2 provider configuration metadata.

UMA Grant requires : See [here](https://docs.kantarainitiative.org/uma/wg/rec-oauth-uma-grant-2.0.html#as-config)
 - claims_interaction_endpoint
 - uma_profiles_supported

Federated requires : see [here](https://docs.kantarainitiative.org/uma/wg/rec-oauth-uma-federated-authz-2.0.html#as-config). 
_They are part of the UMA2 AS **Protection API**_
 - permission_endpoint
- resource_registration_endpoint
- introspection_endpoint (already available in the oauth2 spec)

See Original Oauth2 metadata [here](https://tools.ietf.org/html/rfc8414#section-2)

**Comment by lusoalex** [comment]
@brasseld I am going further than just the discovery for this issue, as I put the resource_registration_endpoint, I am implementing it in the meantime.  
So this issue will contain resource_set & permission endpoint. (Protection API).

**Comment by tcompiegne** [comment]
closed by https://github.com/gravitee-io/graviteeio-access-management/commit/7ff3d5d372d8f30bcef33f03bdcc3d90f8918ed0
