### ISSUE TITLE
Whole API and Applications to be accessed only by admin. How can I create a scope to see Whole API and Applications like an ADMIN

### ISSUE THREAD

**Issue by aliFetvaci61** [gravitee-io/issues#3720]
I Created a management new Scope, the appliations and apis of the other user  is not showing In the Portal . The admin Scope see these applications and apis, but the new Scope is not seeing  . How can I define scope with roles like an admin?  all crud operations is selected but not showing.

**Comment by aelamrani** [comment]
You have to create a group and associate it to every new APIs / Apps. See the screenshot below:
![Capture d’écran 2020-05-07 à 08 51 02](https://user-images.githubusercontent.com/1580262/81263465-fff7f100-903f-11ea-891a-2145cd5e35e0.png)

Is that what you are looking for?

**Comment by aliFetvaci61** [comment]
Will I add a member this group or ?

Can't match any role? @aelamrani

**Comment by aelamrani** [comment]
Yes, you will have to add members on it.

>Can't match any role?
What do you mean?

A group is a set of members. A group can be attached to APIs / Apps. If a group is attached to an API, its member have access on it. And into the group you can specify in detail the roles on each and the default roles (for the new linked APIs / Apps).

![Capture d’écran 2020-05-07 à 10 37 20](https://user-images.githubusercontent.com/1580262/81273147-c2e72b00-904e-11ea-9bfe-6dbb2e9c474e.png)
