### ISSUE TITLE
[portal] Links to open API's redirects to the login page

### ISSUE THREAD

**Issue by oyviaase** [gravitee-io/issues#3721]
Following links sent to a public api page in gravitee redirects us to the login page if we're not logged in to gravitee. 

### Expected Behavior

That we're kept on the API site regardless if we're logged in or not

### Current Behavior

We're redirected to the login page when not logged in to gravitee

### Possible Solution

We're getting the "session expired, redirecting to home..." error message just as before we're redirected so it might be a cookie related issue.

### Steps to Reproduce (for bugs)
https://api-uio.intark.uh-it.no/#!/apis/02032a42-61cb-44e4-832a-4261cb54e45b/detail

Reproduce by
1. Create, publish and make public an API
2. Copy the link to the API from the API GALLERY page
3. Open the link in a private browser window or another browser

### Your Environment

* Version used: 1.30.8 and tested in 1.29.5
* Browser Name and version: Firefox 75 and Vivaldi 3.0.1874.33

**Comment by brasseld** [comment]
Hi @oyviaase 

I think you are redirected because, as an anonymous user, you don't have access to the API.

**Comment by oyviaase** [comment]
The anonymous user isn't trying to access or ask for access to the API, he's just trying to browse the publick information for an API he was sent a link to from someone else. Pushing the back button in the browser or asking the user to find it through the API gallery is he able to look at the same information that he was sent a link to. 

It's just that the link he tries to follow for some reason redirects him from the public (API GALLERY) API page to the login page for the api-manager.

**Comment by oyviaase** [comment]
This still happens with apim 1.30.21 a user tries to follow a link to the API GALLERY page for a publicly accesible API and they are redirected to the login page. Sending them instructions like go to this address <address> Press API GALERY and then select <API NAME> and they can see the information without any issue

**Comment by jhaeyaert** [comment]
Note: it happen on every public pages when an anonymous user accesses page using the url (`/pages`, `/apis`, `/apis/{public-api-id}`, ...).
When loading the application for the first time, the `/management/user` api route is called and a 401 status is returned (cause we are an anonymous user). The 401 is intercepted and the current behavior is to redirect the user to the login page.

We have to find a way to not redirect the anonymous user if he accesses to a public resource.
