### ISSUE TITLE
API gateway does not have the option to enable sticky load balancing

### ISSUE THREAD

**Issue by pohheemeng** [gravitee-io/issues#3735]
According to the description at https://gravitee.io/products/apim/, it's said that the API gw supports  "Round robin, random, sticky mode,". When checked against the admin tool, there's no option to activate the sticky mode.
![image](https://user-images.githubusercontent.com/61736442/81546837-85b3cd80-93ad-11ea-8370-abddd86ed977.png)

**Comment by mouligno** [comment]
Doc has been updated.
