### ISSUE TITLE
[components] Move gv-info from components to portal & fix display of URL

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#3760]
And remove unnecessary ratings from subscribing screen
![Capture d’écran 2020-05-11 à 18 55 36](https://user-images.githubusercontent.com/1580262/81690652-e3065800-945b-11ea-93de-93c58f157034.png)

**Comment by gcusnieux** [comment]
<img width="790" alt="Capture d’écran 2020-05-14 à 16 42 29" src="https://user-images.githubusercontent.com/1457497/81957939-8e0a4380-960d-11ea-9ba2-04ba8fd0bb94.png">
