### ISSUE TITLE
[management] Remove useless default option on views

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#3767]
![Capture d’écran 2020-05-12 à 18 11 35](https://user-images.githubusercontent.com/1580262/81718508-19ec6600-947c-11ea-9937-058fdb53f0cd.png)

**Comment by phiz71** [comment]
The ALL view can also be removed since it was only used in the legacy portal to display all APIs.
In the new portal, a menu has been added for this feature. (See #3743)
