### ISSUE TITLE
[portal] Redoc documentation not well displayed on first load

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#3805]
<img width="1662" alt="Capture d’écran 2020-05-18 à 22 07 12" src="https://user-images.githubusercontent.com/133094/82254897-faf64400-9953-11ea-9789-aa5cc2ee8a9f.png">

**Comment by aelamrani** [comment]
Will be fixed by https://github.com/gravitee-io/issues/issues/3808
