### ISSUE TITLE
[portal] Documentation issues

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#3808]
- [x] We should add some margin on multi level documentation tree view (currently this is flat)
- [x] Redoc documentation not well displayed on first load (https://github.com/gravitee-io/issues/issues/3805)
- [x] Redoc documentation not well displayed if defined as homepage (https://github.com/gravitee-io/issues/issues/3806)
- [x] JS errors while browsing documentation: 
```
ERROR Error: Uncaught (in promise): TypeError: Cannot set property 'active' of undefined
TypeError: Cannot set property 'active' of undefined
```
- [x] Menu Documentation on footer is hiding on scroll
- [x] Homepage should not appear on the footer menu when upgrading
- [x] Large image is not well displayed on markdown
- [x] Homepage has too much margin top
- [x] I have a title with 4 # which is not well displayed in my ToC
- [x] When I change a swagger to a redoc, the page is not displayed
![Capture d’écran 2020-05-19 à 11 46 29](https://user-images.githubusercontent.com/1580262/82311737-6678f980-99c6-11ea-9779-db9b26842338.png)
- [x] Cannot go to the last link https://v3.nightly.gravitee.io/catalog/api/0945b735-a595-4651-85b7-35a595e6516e/doc?page=c8aed0c1-8a83-487e-aed0-c18a83587eef#ins
- [x] links are not always formatted correctly in markdown
- [x] Remove useless properties of gv-tree and upgrade portal theme definition 
![Capture d’écran 2020-05-20 à 15 50 43](https://user-images.githubusercontent.com/1457497/82454290-dca65a80-9ab1-11ea-981c-097e40fc091e.png)

**Comment by YoranSys** [comment]
Hi, 
One little bug when we prefix title with a number and a dot the display is bad :  
`1. sample` will be displayed `sample .1`

* On management UI: 
![image](https://user-images.githubusercontent.com/11197007/82339316-2f1e4300-99ee-11ea-9ea3-1c47f23f8992.png)

* On the developer portal : 
![image](https://user-images.githubusercontent.com/11197007/82339459-583ed380-99ee-11ea-8413-4263e634b6b6.png)

https://v3.nightly.gravitee.io/documentation/root?page=d3520dad-feb2-40cd-920d-adfeb240cdd7

**Comment by phiz71** [comment]
@YoranSys : it will be fixed with https://github.com/gravitee-io/gravitee-ui-components/pull/171
