### ISSUE TITLE
[gateway] 504 Error from API gateway

### ISSUE THREAD

**Issue by j0nimost** [gravitee-io/issues#3815]
I have an API exposed through Gravitee Gateway which is timing out.

When I curl stats on the same API whilst in API Gateway I get the following stats
```
time_namelookup:  0.000s
       time_connect:  0.002s
    time_appconnect:  0.000s
   time_pretransfer:  0.002s
      time_redirect:  0.000s
 time_starttransfer:  13.110s
                    ----------
         time_total:  13.110s
time_namelookup:  0.000s
       time_connect:  0.000s
    time_appconnect:  0.000s
   time_pretransfer:  0.000s
      time_redirect:  0.000s
 time_starttransfer:  13.476s
                    ----------
         time_total:  13.476s
time_namelookup:  0.000s
       time_connect:  0.000s
    time_appconnect:  0.000s
   time_pretransfer:  0.000s
      time_redirect:  0.000s
 time_starttransfer:  12.979s
                    ----------
         time_total:  12.979s
time_namelookup:  0.000s
       time_connect:  0.000s
    time_appconnect:  0.000s
   time_pretransfer:  0.000s
      time_redirect:  0.000s
 time_starttransfer:  13.774s
                    ----------
         time_total:  13.774s
time_namelookup:  0.000s
       time_connect:  0.000s
    time_appconnect:  0.000s
   time_pretransfer:  0.000s
      time_redirect:  0.000s
 time_starttransfer:  19.677s
                    ----------
         time_total:  19.677s
time_namelookup:  0.000s
       time_connect:  0.000s
    time_appconnect:  0.000s
   time_pretransfer:  0.000s
      time_redirect:  0.000s
 time_starttransfer:  18.619s
                    ----------
         time_total:  18.619s
time_namelookup:  0.000s
       time_connect:  0.000s
    time_appconnect:  0.000s
   time_pretransfer:  0.000s
      time_redirect:  0.000s
 time_starttransfer:  20.350s
                    ----------
         time_total:  20.350s
time_namelookup:  0.000s
       time_connect:  0.000s
    time_appconnect:  0.000s
   time_pretransfer:  0.000s
      time_redirect:  0.000s
 time_starttransfer:  18.316s
                    ----------
         time_total:  18.316s
time_namelookup:  0.000s
       time_connect:  0.000s
    time_appconnect:  0.000s
   time_pretransfer:  0.000s
      time_redirect:  0.000s
 time_starttransfer:  19.972s
                    ----------
         time_total:  19.972s
time_namelookup:  0.000s
       time_connect:  0.000s
    time_appconnect:  0.000s
   time_pretransfer:  0.000s
      time_redirect:  0.000s
 time_starttransfer:  18.922s
                    ----------
         time_total:  18.922s

```
This is are not the statistics I'm getting when I curl the API from Gravitee.
### Expected Behavior

I expect to get API responses from Gravitee with approximately a similar response time.
### Current Behavior

The API always times out.
![image](https://user-images.githubusercontent.com/24381727/82341763-82e25980-99f9-11ea-8425-2193965ac533.png)

It has the below Failover configuration(which is pretty long).

![image](https://user-images.githubusercontent.com/24381727/82341906-ad341700-99f9-11ea-85be-ac4a4ad640be.png)
 

### Your Environment

* Version used: Gravitee 1.25
* Browser Name and version: Chrome 81.0.4044.138
* Operating System and version:  Ubuntu 16.04.6 LTS

**Comment by brasseld** [comment]
Can you tell what kind of request you are doing?
Did you have a try with 1.30.X?

**Comment by j0nimost** [comment]
I am performing only `GET` requests.
Unfortunately, no this is production.

**Comment by brasseld** [comment]
Hum.. strange.

Did you extend endpoint timeout from endpoints'configuration?

**Comment by j0nimost** [comment]
Yes, all API's are running on a minimum timeout time of 60 secs

**Comment by brasseld** [comment]
Hum ok,

What if you disable failover?

**Comment by j0nimost** [comment]
It completely times out. I noted this challenge occurs when there is a high number of requests

**Comment by brasseld** [comment]
Oh ok so you're not really able to reproduce on a per-call basis ?

**Comment by j0nimost** [comment]
Yes I witness this when there is a spike of requests

**Comment by brasseld** [comment]
Do you have this kind of error without the gateway?

**Comment by j0nimost** [comment]
No, not really.

**Comment by brasseld** [comment]
Is the response payload really big ?
Why does it take so much time for the backend to respond?

**Comment by j0nimost** [comment]
It's a complex data search so it's timely. Nevertheless, it works for now.

**Comment by brasseld** [comment]
Ok, I'm closing the issue, please re-open if issue occurs again.

regards,
