### ISSUE TITLE
[portal] Share some code about searching permissions

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#3816]
https://github.com/gravitee-io/gravitee-management-rest-api/blob/2c04f493ba8937795bbf6ad6975c27f8573bcd6d/gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApisResource.java#L133-L135

https://github.com/gravitee-io/gravitee-management-rest-api/blob/2c04f493ba8937795bbf6ad6975c27f8573bcd6d/gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApisResource.java#L260-L262

https://github.com/gravitee-io/gravitee-management-rest-api/blob/2c04f493ba8937795bbf6ad6975c27f8573bcd6d/gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/DashboardsResource.java#L52-L53

https://github.com/gravitee-io/gravitee-management-rest-api/blob/2c04f493ba8937795bbf6ad6975c27f8573bcd6d/gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/quality/QualityRulesResource.java#L57-L58

**Comment by aelamrani** [comment]
Will be closed by https://github.com/gravitee-io/issues/issues/3834

**Comment by phiz71** [comment]
Closed by #3834
