### ISSUE TITLE
[management][docker] Gateway monitoring shows NaN for JVM report

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [gravitee-io/issues#3826]
Hello!

I'm trying a fresh Gravitee 3.0 install through docker compose, and when viewing the gateway report it shows a few NaN for the JVM report:

![image](https://user-images.githubusercontent.com/12160864/82476997-2f2d4a00-9aa5-11ea-9d37-d7311a58b773.png)

As you can see, `Young pool *` and `Survivor pool *` are displaying `NaN undefined`.

**Comment by brasseld** [comment]
Thanks for your feedback @rafaelrenanpacheco 
Looks to be due to the base java image.

We'll have a look very soon.
