### ISSUE TITLE
JWT policy ignores client_id claim when aud is set, yet aud is NOT (always) client id

### ISSUE THREAD

**Issue by diopol** [gravitee-io/issues#3835]
JWT Policy now grabs the values for `client_id `from JWT claims in the following priority
1. `azp`
2. `aud`
3. `client_id`

There was an issue #1235 where the fallback behaviour (to `azp`/`aud `claims) was requested when the `client_id `claim is **NOT** present. Yet, the fix has pushed `azp`/`aud `claims to the top priority. So that `client_id `claim is now ignored when either `aud `or `azp `is present.

I use Identity Server 4 as a JWT token provider, and my `aud[0]` claim always contains openid resources url (like https://auth-server.ru/resources). So I always get 401 from JWT policy, because it tries to find an app with `client_id` = "https://auth-server.ru/resources". And even if I remove openid scope for the token, my aud claim value has the identifier of my api resource, and not the client id. 

### Expected Behavior
JWT Policy (when used in Plan with JWT Authentication type) works correctly with all possible JWT tokens issued by different Identity Servers.

### Current Behavior
JWT Policy (when used in Plan with JWT Authentication type) respects `aud[0]` if both `claim_id` and `aud` claims are present and returns 401 for JWT access tokens issued by Identity Server 4 (at least).

### Possible Solution
JWT Policy should grab the value for client_id from the `client_id` claim first. And only if it is not present, it should fallback to `azp` and `aud` claims. Which was also stated in issue #1235.

Yet, I'm not sure if the proposed behaviour is **always** correct. In particular, I'm not sure about the  priority of `client_id` above `azp`. So, another option is to specify the source claim (or source claims in priority order) in the policy settings to cover all possible cases.

### Steps to Reproduce (for bugs)
1. generate a valid jwt access token with different values in claims `client_id` and `aud`
2. create an api and a plan with jwt authentication type
3. subscribe to the api with an app with client_id equal to jwt token `client_id` claim
4. try to request any api resource with the generated token above

expected: request is propagated to the endpoint
actual: 401 response from gateway

### Context
Due to the issue I'm unable to use JWT Authentication type for my API plans, because tokens generated by our Identity Server (Identity Server 4) are always rejected by JWT Policy.

### Environment
* Version used: 1.30.10
* Browser Name and version: Chrome 81
* Operating System and version: macOS Mojave 10.14.5

**Comment by marcambier** [comment]
I close this ticket, as this use case can now be solved using the `clientIdClaim` parameter of the JWT policy ;
Which let you specify from which claim extract your client_id.
Introduced with this ticket : https://github.com/gravitee-io/issues/issues/4900
See documentation : https://docs.gravitee.io/apim/3.x/apim_policies_jwt.html#configuration
