### ISSUE TITLE
[AM] Management Token

### ISSUE THREAD

**Issue by gianx89** [gravitee-io/issues#3848]
I'm on gravitee AM 3.0.2 and, as I usually do, I'm trying to obtain a token with:

curl -X POST http://172.31.33.211/am/admin/token -H 'authorization: Basic YWRtaW46YWRtaW5hZG1pbg=='

I'm getting 

No security domain matches the request URI.

But I've alwayd done it this way. Something changed?

**Comment by tcompiegne** [comment]
Hi @gianx89 ,

Yes this URL does not exist anymore : 

https://docs.gravitee.io/am/current/am_breaking_changes_3.0.html

You should use this one instead : 

curl -X POST http://172.31.33.211/am/management/auth/token -H 'authorization: Basic YWRtaW46YWRtaW5hZG1pbg=='

**Comment by gianx89** [comment]
I've just found it. Thanks

**Comment by tcompiegne** [comment]
By the way I will update this documentation : 

https://docs.gravitee.io/am/current/am_management_api_documentation.html, still the old one
