### ISSUE TITLE
update in FROM clause Error in MySQL environment when use gravitee-repository-jdbc-3.0.0

### ISSUE THREAD

**Issue by leofyu333** [gravitee-io/issues#3853]
### Current Behavior
**When I replace MongoDB to mysql in 3.0.0 version, this error occurs when set up database**

07:03:02.315 [graviteeio-node] [] ERROR i.g.r.j.c.AbstractJdbcRepositoryConfiguration - Failed to set up database: 
liquibase.exception.MigrationFailedException: Migration failed for change set liquibase/changelogs/v3_0_0/schema.yml::3.0.0::GraviteeSource Team:
     Reason: liquibase.exception.DatabaseException: You can't specify target table 'rp' for update in FROM clause [Failed SQL: (1093) update role_permissions rp set role_scope = 'ENVIRONMENT' where rp.role_scope = 'MANAGEMENT' and rp.permission like '17%' and not exists (select * from role_permissions rp2 where rp2.role_scope = 'ENVIRONMENT' and rp2.permission like '17%' and rp2.role_name = rp.role_name)]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:646)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83)
	at liquibase.Liquibase.update(Liquibase.java:202)
	at liquibase.Liquibase.update(Liquibase.java:179)
	at liquibase.Liquibase.update(Liquibase.java:175)
	at io.gravitee.repository.jdbc.common.AbstractJdbcRepositoryConfiguration.runLiquibase(AbstractJdbcRepositoryConfiguration.java:159)

### Error Location
**it seems there are something wrongs in schema.yml update sql of gravitee-repository-jdbc-3.0.0, target file is gravitee-repository-jdbc-3.0.0\liquibase\changelogs\v3_0_0\schema.yml, keyword is `not exists`, such as line 48**

>sql: update role_permissions rp set role_scope = 'ENVIRONMENT' where rp.role_scope = 'MANAGEMENT' and rp.permission like '17%' and not exists (select * from role_permissions rp2 where rp2.role_scope = 'ENVIRONMENT' and rp2.permission like '17%' and rp2.role_name = rp.role_name)

![image](https://user-images.githubusercontent.com/54490950/83001220-06c1c480-a03e-11ea-9b03-c3499bf493c7.png)
![image](https://user-images.githubusercontent.com/54490950/83001269-180ad100-a03e-11ea-9a54-4c8fec75fc5c.png)

### Possible Solution
**Mysql don't support this and will have [1093] You can't specify target table 'xx' for update in FROM clause, we may be use `subquery` to fix it, For example:**

>update role_permissions rp set rp.role_scope = 'ENVIRONMENT' where rp.role_scope = 'MANAGEMENT' and rp.permission like '17%' and not exists (select * from (select rp2.* from role_permissions rp2,role_permissions rp3 where rp2.role_scope = 'ENVIRONMENT' and rp2.permission like '17%' and rp2.role_name = rp3.role_name and rp3.role_scope = 'MANAGEMENT' and rp3.permission like '17%') temp);

### My Environment
1.Linux Docker,  docker pull graviteeio/apim-gateway:3.0
2.mysql in 5.7.29

Please give me some advice, very thanks

**Comment by aelamrani** [comment]
Thanks for pointing this out, we will have a look to this.

**Comment by leofyu333** [comment]
@aelamrani **it seems there are other wrong format sql in mysql in MySQL environment**

**1.`key` need to use quotes in line 637**
>sql: delete from parameters where key = 'portal.devMode.enabled';

**update:**
>sql: delete from parameters where \`key\` = 'portal.devMode.enabled';

![2](https://user-images.githubusercontent.com/54490950/83110226-53b4a200-a0f5-11ea-946c-ce6a49dc429a.png)

**2.mysql does not support alias in delete sql, such as line 139**
>sql: delete from membership_roles mr where mr.reference_type = 'MANAGEMENT' and mr.role_scope = 'MANAGEMENT'

**update:**
>sql: delete from membership_roles  where reference_type = 'MANAGEMENT' and role_scope = 'MANAGEMENT'

Below is my updated version, it is ok when system init the gravitee DB, but I am not sure if it is totally right after I update it. 
[schema.txt](https://github.com/gravitee-io/issues/files/4693883/schema.txt)
