### ISSUE TITLE
APIM: 3.0.1 Portal-UI uri baseurl not configurable

### ISSUE THREAD

**Issue by tapiiron** [gravitee-io/issues#3883]
### Expected Behavior
Installing gravitee 3.0.1 () into nginx web root path /portal should appriciate its base path.

### Current Behavior
Installing gravitee 3.0.1 (graviteeio-portal-ui-3.0.1) into nginx web root path /portal is not possible in version 3 of gravitee. portal-ui loads its files from web root ( / ) even tho all files are installed in path /portal . (Management UI works)

### Possible Solution
Add configurable option to config.json about web path root or make the portal ui honour the web path.

### Steps to Reproduce (for bugs)
1. move graviteeio-portal-ui-3.0.1 directory to nginx_root/portal
2. browse to https://server/portal/ 
3. notice that all the files are loaded from https://server/

### Context
Linux RedHat 8, nginx with proxy from /portal/environment into management api but portal not.
Nginx config:
- / mapped to gw
- /portal mapped to web root in fileserver
- /portal/environment mapped to rest-api
- /management mapped to web root in fileserver
- /management/organizations mapped into rest-api

### Your Environment
* Version used: 3.0.1
* Browser Name and version: Chrome newest
* Operating System and version: Linux

**Comment by aelamrani** [comment]
@tapiiron you should be able to do such thing with sub_filter on your nginx conf.

Take a look at what we do here on Access Management: https://github.com/gravitee-io/graviteeio-access-management/blob/master/docker/compose/config/nginx.conf#L32

**Comment by tapiiron** [comment]
Hey, Thank you for hint on workaround. Seems like loading of /assets/i18n/en.json still loads directly from root and does not get /portal/ on the beginning. ManagementUI does work without workarounds.

**Comment by aelamrani** [comment]
That's not a work-around. Management UI is AngluarJS / Portal Angular, so there is no bug here...

**Comment by tapiiron** [comment]
Maybe not a bug but feature request that the base path could be configured. Mapped assets to root and portal works great.

**Comment by aelamrani** [comment]
ATM we won't do anything as it just a matter of configuration...

**Comment by tapiiron** [comment]
Alright. Any sub_filter to fix /assets/i18n/en.json load? Tried to replace all those in response but seems like it is in browser generated uri.

**Comment by aelamrani** [comment]
Can you share you nginx configuration? I will have a look to this soon.

**Comment by tapiiron** [comment]
nginx configuration atm of portal:
      
  location ^~ /portal {
          proxy_set_header   Host $host;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Host $server_name;
          proxy_set_header   X-Forwarded-Proto $scheme;
          sub_filter '<base href="/"' '<base href="/portal/"';
          sub_filter '/assets/i18n/en.json' '/portal/assets/i18n/en.json';
          sub_filter_once on;
          root /apiman/www;
    }

Everything else loads with this config from /portal except  /assets/i18n/en.json (used chrome dev tools to check that). If created file to root /assets/i18n/en.json portal loads perfectly with this nginx config.

**Comment by aelamrani** [comment]
Can you try to add this line on the portal conf: `try_files $uri$args $uri$args/ $uri $uri/ /index.html =404;`

And normally, you can remove the `sub_filter '/assets/i18n/en.json' '/portal/assets/i18n/en.json';`
