### ISSUE TITLE
[management] Notify consumer before the expiration of its subscription

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#3887]
# User Story

As an API consumer, I want to be notified in advance about the expiration date of my subscriptions, so that I can be proactive about their renewal and avoid service interruptions

# Further Information
- The frequency of notifications is configured in the "gravitee.yml" file (default value are 90/45/30 days)
- A user cannot configure their notifications to be notified on the day a subscription expires (0 in the yaml file)
- The user who made the subscription request receives a notification. If the primary owner of the application is a different user from the subscriber, he also receives a notification
- Notifications are made only by email
- Only `ACCEPTED` or `PAUSED` subscriptions with a defined expiry date are notified
- For plans that use api keys, the expiry date is the earlier of the api key expiry date and the subscription expiry date
- Renewing an API key does not trigger the expiration date check
- The notification template  must be customizable 

# Examples
#### gravitee.yml
![image](https://user-images.githubusercontent.com/4112568/119987372-3d217f00-bfc5-11eb-9571-f357b86e8282.png)

# Tests
## Configuration (gravitee.yml)
- [x] Given the following values `[367, 0]` set in the configuration file, when I start the APIM installation, then there is a warning in the logs
- [x] Given the following values `[366, 1]` set in the configuration file, when I start the APIM installation, then there is no warning in the logs
- [x] Given the following environment variable `preExpirationNotificationSchedule: 90, 45, 30`, when I start the APIM installation, then the environment variable value is taking into account
- [x] Given no environment variable set, when I start the APIM installation, then the default values are taking in account
- [x] Given the subscription service enabled, when I start the APIM installation, then the related CRON is running
- [ ] Given the subscription service disabled, when I start the APIM installation, then the related CRON is running

## User
- [x] Given a user who is neither the primary owner nor the subscriber, when the subscription is about to expire, then he does not receive any notification
- [x] Given the primary owner who has subscribed to an API, when the subscription is about to expire, then the primary owner receives only one notification
- [x] Given a user who is a subscriber but not the primary owner, when the subscription is about to expire, then the subscriber and the primary owner receive a notification

### Status
- [x] Given a subscription with a status !(`ACCEPTED` or `PAUSED`), when the subscription is about to expire, then no notification is sent
- [x] Given a subscription with a status `ACCEPTED` or `PAUSED`, when the subscription is about to expire, then a notification is sent

### Expiry Date
| Configuration | Time left before subscription expiration | Notification sent |
|:-:|:-:|:-:|
| `[30, 15, 1]` | [31, ...[ days | No |
| `[30, 15, 1]` | 30 days | Yes |
| `[30, 15, 1]` | [16, 29] days | No |
| `[30, 15, 1]` | 15 days | Yes |
| `[30, 15, 1]` | [2, 14] days | No |
| `[30, 15, 1]` | 1 day | Yes |
| `[30, 15, 1]` | ]0, 23] hours | No |

### Status
- [x] Given an API key with a status "revoked", when the API key is about to expire, then no notification is sent
- [x] Given an API key with a statut !"revoked", when the API key is about to expire, then a notification is sent

#### Subscription Expiry Date = API Key Expiry Date
| Configuration | Time left before expiration | Notification sent |
|:-:|:-:|:-:|
| `[30, 15, 1]` | [31, ...[ days | No |
| `[30, 15, 1]` | 30 days | Yes (only 1) |
| `[30, 15, 1]` | [16, 29] days | No |
| `[30, 15, 1]` | 15 days | Yes (only 1) |
| `[30, 15, 1]` | [2, 14] days | No |
| `[30, 15, 1]` | 1 day | Yes (only 1) |
| `[30, 15, 1]` | ]0, 23] hours | No |

#### Subscription Expiry Date > API Key Expiry Date
| Configuration | Time left before subscription expiration | Time left before API key expiration | Notification sent |
|:-:|:-:|:-:|:-:|
| `[30, 15, 1]` | [31, ...[ days | ]0, 23] hours <br> or [2, 14] days <br> or [16, 29] days | No |
| `[30, 15, 1]` | [31, ...[ days | 1 day <br> or 15 days <br> or 30 days | Yes (API key's expiry date is taken into account) |
| `[30, 15, 1]` | 30 days | ]0, 23] hours <br> or [2, 14] days <br> or [16, 29] days | Yes (subscription's expiry date is taken into account) |
| `[30, 15, 1]` | 30 days | 1 day <br> or 15 days | Yes (API key's expiry date is taken into account) |
| `[30, 15, 1]` | [16, 29] days | ]0, 23] hours <br> or [2, 14] days <br> or [16, 29] days | No |
| `[30, 15, 1]` | [16, 29] days | 1 day <br> or 15 days | Yes (API key's expiry date is taken into account) |
| `[30, 15, 1]` | 15 days | ]0, 23] hours <br> or [2, 14] days | Yes (subscription's expiry date is taken into account) |
| `[30, 15, 1]` | 15 days | 1 day | Yes (API key's expiry date is taken into account) |
| `[30, 15, 1]` | [2, 14] days | ]0, 23] hours <br> or [2, 14] days | No |
| `[30, 15, 1]` | [2, 14] days | 1 day | Yes (API key's expiry date is taken into account) |
| `[30, 15, 1]` | 1 day | ]0, 23] hours | Yes (subscription's expiry date is taken into account) |
| `[30, 15, 1]` | ]0, 23] hours | ]0, 23] hours | No |

### Form Validation
- [x] Given the alert template creation/update form, when I don't fill all the fields, then the button "Save" is disabled and an error message is displayed below the concerned fields

### Template customization
- [x] Given the alert template creation/update form, when "Override default template" switch is off, then the field "Title" and the field "Content" are in read-only mode
- [x] Given the alert template creation/update form, when "Override default template" switch is on, then I can modify "Title" ad "Content" values and save my changes

### Notifications
- [x] Given a template customized, when I select this template and a notification is sent by email, then the customized template is used
- [x] Given a template customized, when I select the default template and a notification is sent by email, then the default template is used
- [ ] Given 2 different organizations with 1 custom template each, when notifications are sent by email, then each notification uses the associated template with its organization

**Comment by gaetanmaisse** [comment]
@patelami @ibahloul some part of this issue won't be testable on nightly as we can't update the configuration and restart APIM easily. 

Note: The CRON sending the expiration email is running once per hour (and is not configurable, by design) and will process subscriptions expiring in [now + delay_set_in_conf; now + delay_set_in_conf +1h].
To simplify tests we can change this hardcoded value when running APIM from source code but it may have some impact on the interval describe above.

**Comment by patelami** [comment]
@ibahloul 

Currently, we have a misleading email subject when the user updates the Expiration of the API key, the owner will receive an email with the title "API key Expiration!". It should be updated to "API key Expiration Date Updated" 

cc: @gaetanmaisse

**Comment by patelami** [comment]
https://github.com/gravitee-io/issues/issues/5700#issue-916213709
