### ISSUE TITLE
Management API and Portal server 404 Not Found

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#3889]
OS: WIndows 10

I just stared to use Gravitee. and i have problem with some of the installation and I don't know what exactly could be cause this issue.
When I installed Management API on the command curl -X GET http://localhost:8083/management/apis/ i dont get [], there is basically nothing, and when i type URL i get 
{
  "message" : "HTTP 404 Not Found",
  "http_status" : 404
}
Because all of this i think the Portal is also not working properly.I used Node to run it and when i go to the URL is says that Server unavailable or connection lost. I can post screen shots though i don't know if i am allowed to.

I did not do any changes in the config file.

**Comment by brasseld** [comment]
Hi @marijatimovska 

How do you run the management-api ?

**Comment by marijatimovska** [comment]
Well its no longer management-api its graviteeio-rest-api-3.0.1 and I did, i run gravitee in cmd from bin and ofc ElasticSearch is also up since i need it.

**Comment by aelamrani** [comment]
Hi @marijatimovska 

As explained on the upgrade guide, there was some changes on this version, and one of them is about the rest API context path: https://docs.gravitee.io/apim/3.x/apim_installguide_migration.html#management_api

```
If you are using the REST API directly, please note that you will have to adapt the URL 
from https://host/management/ 
to https://host/management/organizations/DEFAULT/environments/DEFAULT/
```

**Comment by marijatimovska** [comment]
http://localhost:8083/management/organizations/DEFAULT/environments/DEFAULT/ gives
{
  "message" : "HTTP 405 Method Not Allowed",
  "http_status" : 405
}

but this does not resolve the problem on why the Portal UI is not working, it's Server unavailable or connection lost, there is GUI but nothing else works, i guess i need to change something somewhere. I literally just today started using it so can you be more specific. Even the doc. for the instalation has not been updated cus it says 

$ cd graviteeio-management-api-3.0.1
$ ./bin/gravitee

instead of 

graviteeio-rest-api-3.0.1

**Comment by marijatimovska** [comment]
![image](https://user-images.githubusercontent.com/57534152/83416162-8c6bb880-a420-11ea-8a81-c5bdefe61126.png)

**Comment by marijatimovska** [comment]
![image](https://user-images.githubusercontent.com/57534152/83416240-af966800-a420-11ea-850d-550dc81edfb5.png)

**Comment by brasseld** [comment]
`curl -X GET http://localhost:8083/management/organizations/DEFAULT/environments/DEFAULT/apis`

**Comment by marijatimovska** [comment]
damn i forgot to add that one at the end..thank you

**Comment by marijatimovska** [comment]
now just gotta try and fix the Portal UI..i am looking for the correct file.
