### ISSUE TITLE
[gateway] Bootstrap

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#3894]
Error: Could not find or load main class com.graviteesource.ae.standalone.boostrap.Bootstrap
Caused by: java.lang.ClassNotFoundException: com.graviteesource.ae.standalone.boostrap.Bootstrap

Cant run the AE get thie error, i pulled the git rep. if i need to change some jar files.

**Comment by brasseld** [comment]
The git repository for AE should not be accessible.
How did you get access to it ?

**Comment by marijatimovska** [comment]
I might have not said it correctly so sorry but i got access to this https://github.com/gravitee-io/gravitee-gateway...i did saw that there are same jars like in the AE...for example here https://github.com/gravitee-io/gravitee-gateway/tree/master/gravitee-gateway-standalone they are teh same as in the AE folder...i should have been more clear with what i have said and if this is not suppose to be public when now you know.

**Comment by marijatimovska** [comment]
I am trying to fix this all without anyone help so i am trying to work with everything I find

**Comment by brasseld** [comment]
Sorry, but I'm not sure to get you.

Can you tell me what you're looking to do exactly.

Sorry for misunderstanding.

**Comment by marijatimovska** [comment]
![image](https://user-images.githubusercontent.com/57534152/83454703-e25e5180-a45c-11ea-8f22-eda010a6c052.png)

this is the problem....can't run AE from cmd

**Comment by brasseld** [comment]
Hum that is quite strange as it seems to use the right classpath.

FYI, you may not be able to run AE as this one is requiring a license to start.

**Comment by marijatimovska** [comment]
Okay thank you very much for that info I guess I better tell my team we cant use it for now :P

**Comment by brasseld** [comment]
Haha yes !

Or you can buy license :)
