### ISSUE TITLE
add mirrors to download phantomjs binary 

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#39]
_From @NicolasGeraud on April 5, 2016 22:44_

because we have a lot of error when we build the webui, a solution could be to use a mirror to download phantomjs binary.

we have to export PHANTOMJS_CDNURL=http://cnpmjs.org/downloads npm install phantomjs to use an alternative mirror.

_Copied from original issue: gravitee-io/jenkins-scripts#20_

**Comment by gaetanmaisse** [comment]
Closing as `phantomjs` has been replaced by jest+jsdom in APIM Console.
