### ISSUE TITLE
I want to run gravitee-gateway from my IDE

### ISSUE THREAD

**Issue by monarchxx** [gravitee-io/issues#3903]
I want to run gravitee-gateway from my IDE
**What should I do**

Thanks

**Comment by leviet** [comment]
what your IDE?

**Comment by monarchxx** [comment]
> what your IDE?

IntelliJ IDEA 
I do not know how to specify  -Dgravitee.home

**Comment by leviet** [comment]
I don't use IntelliJ, this config on my eclipse
![alt text](https://i.ibb.co/7XTGpqr/07ac7ebd-7224-4d28-b549-27d2824c777f.jpg)

**Comment by aelamrani** [comment]
@monarchxx with IJ:

Main class: io.gravitee.gateway.standalone.GatewayContainer

VM options: -Dgravitee.home=/${your_path}/graviteeio-full/graviteeio-gateway-${version}

Replace `${your_path}` by the path of the full bundle and `${version}` by your Gravitee version.

**Comment by monarchxx** [comment]
> @monarchxx with IJ:
> 
> Main class: io.gravitee.gateway.standalone.GatewayContainer
> 
> VM options: -Dgravitee.home=/${your_path}/graviteeio-full/graviteeio-gateway-${version}
> 
> Replace `${your_path}` by the path of the full bundle and `${version}` by your Gravitee version.

The program is  running on my IJ
Thank you very much
