### ISSUE TITLE
Update from APIM Version 1.30.0 to 1.30.11

### ISSUE THREAD

**Issue by IvoIlic95** [gravitee-io/issues#3905]
Hello

I have a question regarding the newest version of the Gravitee.io APIM (1.30.11). Currently I am running the Version 1.30. Why should I update to the new Version 1.30.11? Could someone explain me what benefit I would get if I update it to the newer version? Is the installation and configuration completely different to the older version? Am I getting a boost in performance for example...

A brief explanation would be nice without mentioning the patch-notes (I have seen them already).

Kind regards,
II

**Comment by brasseld** [comment]
Hi there,

The main reason to upgrade to JDK11 would be that you did a JDK 8 upgrade quite recently.
In that case, some SSL features from latest JDK8 are no more compatible with gravitee.

Regards,
