### ISSUE TITLE
[policy] Using Data on gateway policy

### ISSUE THREAD

**Issue by The461** [gravitee-io/issues#3906]
Hello

### Context
This is a request to know how to store data on API.
Where, when I'm creating API / Plan, can I store data? And how can I use same data inside my policy? 
For exemple, can I store data on API properties object and use them from the "ExecutionContext" inside the policy?

### Your Environment
* Version used: 1.28

Thank you

**Comment by brasseld** [comment]
Hi @The461 

Sorry for misunderstanding, but can you explain your use-case ?
What do you mean by "storing data" ?

> For exemple, can I store data on API properties object and use them from the "ExecutionContext" inside the policy?

API Properties are available through execution context: `{#api.properties['my_prop']}`

**Comment by The461** [comment]
Thank you.
For more precisions, if I add a properties here:
![properties](https://user-images.githubusercontent.com/53151021/83743969-bbba3980-a65b-11ea-9882-7f67e6f825c2.png)

Where can I find, in my "ExecutionContext" structure, those properties during my policy execution?

**Comment by brasseld** [comment]
`ExecutionContext.getTemplateEngine().getTemplateContext().lookupVariable("properties")` ?
