### ISSUE TITLE
[kubernetes] helm installation fails on GKE

### ISSUE THREAD

**Issue by KobeTwo** [gravitee-io/issues#3907]
I tried to install the graviteeio helm chart on a gke kubernetes cluster. But got the following error:

`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec): unknown field "securityContext" in io.k8s.api.apps.v1.DeploymentSpec`

### Expected Behavior
helm chart should successfully apply and create all the resources.

### Current Behavior
Applying the helm chart fails

### Possible Solution
-

### Steps to Reproduce (for bugs)
1. Have a GKE kubernetes cluster (Version: 1.16.8-gke.15)
2. Add the graviteeio helm repo: helm repo add graviteeio https://helm.gravitee.io
3. Apply the helm chart:  helm install graviteeio-apim graviteeio/apim -n gravitee
4. Error is thrown
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec): unknown field "securityContext" in io.k8s.api.apps.v1.DeploymentSpec

### Context
I would like to test the tool and present it to a client

### Your Environment
* Version used: current helm chart version
* Browser Name and version: -
* Operating System and version: MacOS

**Comment by brasseld** [comment]
Hi @KobeTwo 

Can you try with this specific chart version: 1.29.3

Thanks for your feedback.

**Comment by brasseld** [comment]
Ok I had a new try.

Everything works well with GKE (Version: 1.14.10-gke.36)
I will have a try with your version.

**Comment by brasseld** [comment]
Hum, don't know what happens.

I have no issue at all also with 1.16.8-gke.15

**Comment by KobeTwo** [comment]
I tried chard version 1.29.3 and it worked.

Maybe the error is related to my helm version: 
helm version
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

**Comment by brasseld** [comment]
I run helm 2.16.
Not sure it may explain your issue as it looks to be relative to k8s and not helm...

**Comment by brasseld** [comment]
Hi @KobeTwo 

Ive pushed a new version of the APIM helm charts (1.29.5).

Can you have a try with this one please ?
