### ISSUE TITLE
APIM: JDBC database migration from 1.30 to 3.0 fails

### ISSUE THREAD

**Issue by tapiiron** [gravitee-io/issues#3908]
In Gravitee APIM rest-api jdbc-repository-3.0.1, JDBC database migration from 1.30.9 to 3.0.1 fails with error:
liquibase.exception.DatabaseException: ERROR: column "api" contains null values [Failed SQL: (0) ALTER TABLE public.plans ADD api VARCHAR(64) NOT NULL] 

### Expected Behavior
Migration from 1.30 series to 3 series should work with jdbc repository.

### Current Behavior
Tried installing 3 series Gravitee as upgrade to 1.30 . JDBC repository migration fails with
liquibase.exception.DatabaseException: ERROR: column "api" contains null values [Failed SQL: (0) ALTER TABLE public.plans ADD api VARCHAR(64) NOT NULL] 

### Possible Solution
Migration scripts should first fill the api-column and then add not null constraint.

### Steps to Reproduce (for bugs)
1. Install apim 1.30.9
2. Create some apis with plans
3. Stop services
4. Start apim 3.0.1 with plugin jdbc-repository-3.0.1 (and psql drivers)
5. Log shows liquibase.exception.DatabaseException: ERROR: column "api" contains null values [Failed SQL: (0) ALTER TABLE public.plans ADD api VARCHAR(64) NOT NULL]  and later the apim rest-api fails to load as missing required database structure.

### Context
Trying to migrate to 3-series but there seems to be some migration problems. Can work on 1.30 series and this has no production problems (only testing migration in dev environment)

### Your Environment
* Version used: 1.30.9 and then 3.0.1
* Operating System and version: Linux RedHat EL8, PostgreSQL 10, Java 11

**Comment by aelamrani** [comment]
Hi @tapiiron 

Can you try with the version 3.0.2?

**Comment by tapiiron** [comment]
Hey, Seems like jdbc-repository is not yet available:
wget https://download.gravitee.io/graviteeio-apim/plugins/repositories/gravitee-repository-jdbc/gravitee-repository-jdbc-3.0.2.zip
returns 404

**Comment by tapiiron** [comment]
Tried repository branch 3.0.x building and deploying. The same error occurs

**Comment by aelamrani** [comment]
Yes, seems to be another problem. Do you have logs at startup?

**Comment by tapiiron** [comment]
Hey,
Seems like I had old ui in browser cache which cause problems. The migration works almost ok.
New issues (different bugs)
1. When opening portal as not logged in user, getting browser error An unexpected error occurred and in the rest-api logs :
PreparedStatementCallback; SQL [select * from memberships where member_id = ? and member_type = ? and reference_type = ? ]; No value specified for parameter 3.; nested exception is org.postgresql.util.PSQLException: No value specified for parameter 3.

2. All migrated users are marked to be in ENVIRONMENT and can't login. Workaround:
update users set reference_type='ORGANIZATION';

**Comment by phiz71** [comment]
Hi @tapiiron,

> 1. When opening portal as not logged in user, getting browser error An unexpected error occurred and in the rest-api logs :
[gravitee-listener-23] ERROR i.g.r.a.s.impl.MembershipServiceImpl - An error occurs while trying to get memberships for null
io.gravitee.repository.exceptions.TechnicalException: Failed to find membership by user and membership type
PreparedStatementCallback; SQL [select * from memberships where member_id = ? and member_type = ? and reference_type = ? ]; No value specified for parameter 3.; nested exception is org.postgresql.util.PSQLException: No value specified for parameter 3.

=> #3913 

> 2. Logged in user can't get list of applications when subscibing:
[gravitee-listener-32] ERROR i.g.r.a.p.r.provider.ThrowableMapper - Internal error java.lang.ClassCastException: class io.gravitee.rest.api.model.application.ApplicationListItem cannot be cast to class java.lang.String (io.gravitee.rest.api.model.application.ApplicationListItem is in unnamed module of loader java.net.URLClassLoader @1be6f5c3; java.lang.String is in module java.base of loader 'bootstrap')

=> #3914

>3. In portal you can browse through from /portal address even to https://server/portal/applications/mine but when clicking browser refresh all but portal root return 404. No pages can be linked from outside portal application.

IMHO it's a nginx problem. This can be solve by adding this line in your portal location
`try_files $uri $uri/ /portal/index.html;`. (here /portal stands for baseHref)

>4. All migrated users are marked to be in ENVIRONMENT and can't login. Workaround:
update users set reference_type='ORGANIZATION';

=> #3912 

Thanks for your feebacks :)

**Comment by tapiiron** [comment]
The nginx configuration for issue 3 was indeed about this try_files. After setting that portal works with external links. Thank you for the instuctions.

**Comment by aelamrani** [comment]
Closed by https://github.com/gravitee-io/issues/issues/3912, https://github.com/gravitee-io/issues/issues/3913 and https://github.com/gravitee-io/issues/issues/3914
