### ISSUE TITLE
[repository][jdbc] in apim 3 requires super user privilege to gravitee user in postgresql

### ISSUE THREAD

**Issue by tapiiron** [gravitee-io/issues#3909]
JDBC-repository in apim 3 requires super user privilege to gravitee user in postgresql database

### Expected Behavior
Gravitee user should not have super user privilege.

### Current Behavior
Gravitee is creating uuid generator in postgresql database from extension (which in rhel 8 requires additional package postgresql-contrib). To do this the user creating the extension needs to have super user privilege.

### Possible Solution
To make repository creation possible we need to for example:
alter user gravitee with superuser;
and after repository installation revoke these .

### Steps to Reproduce (for bugs)
1. Clean install gravitee 3.0.1 with jdbc-repository-3.0.1
2. start the gravitee rest-api service
3. notice that logs report failure in repository uuid extension creation. 
4. rest-api wont start

### Context
No production effects. Only in dev environment.

### Your Environment
* Version used: 3.0.1
* Operating System and version: RedHat EL8, Postgresql 10

**Comment by aelamrani** [comment]
Thanks for reporting this, we will have a look on the next versions

**Comment by tapiiron** [comment]
As uuid generation is important maybe some documentation about this in jdbc-repo is only required

**Comment by aelamrani** [comment]
Yes, otherwise we will try to generate unique IDs without any dep.
