### ISSUE TITLE
[policy] [xml-json] Remove charset in content-type header

### ISSUE THREAD

**Issue by AnselmeDewavrin** [gravitee-io/issues#391]
### Expected Behavior
xml2json only replaces application/xml part by application/json in the content-type header, but leaves charset part untouched.

### Current Behavior
xml2json removes charset part of the content-type header

### Steps to Reproduce (for bugs)

1. have an xml backend not specifying the content-type charset
2. add a transform-header policy on the response scope, adding a content-type with charset=utf-8
3. add a xml2json policy

### Your Environment

* Version used: 1.1.0
* Browser Name and version: postman
* Operating System and version: win10

**Comment by brasseld** [comment]
According to the [RFC7158 Section 8.1](https://tools.ietf.org/html/rfc7158#section-8.1), the charset will be set to UTF-8 by default for both request and response content-type.
