### ISSUE TITLE
APIM: Management api views error message validation (1.30.11)

### ISSUE THREAD

**Issue by tapiiron** [gravitee-io/issues#3911]
XSS vulnerability in management api views (1.30.11)

### Current Behavior
Request: GET /management/apis/?view=<sCrIpT>alert(419319221)</sCrIpT>&portal=true HTTP/1.1
Response: {
"message" : "View [<sCrIpT>alert(419319221)</sCrIpT>] can not be found.",
"http_status" : 404
}
### Possible Solution
The input should be validated for output.

### Steps to Reproduce (for bugs)
1. curl "https://server/management/apis/?view=<sCrIpT>alert(419319221)</sCrIpT>\&portal=true"
2. get response {
"message" : "View [<sCrIpT>alert(419319221)</sCrIpT>] can not be found.",
"http_status" : 404
}

### Context
All input should be validated for output.

### Your Environment
* Version used: 1.30.11

**Comment by aelamrani** [comment]
Not relevant
