### ISSUE TITLE
[management] Creating plan with policy from REST request 

### ISSUE THREAD

**Issue by Babaz69** [gravitee-io/issues#3925]
Hello,
I'm trying to industrialize plan creation with a policy. 
So I won't use Gravitee management ui.

### Expected Behavior
When I'm using Gravitee Management ui, I can create a "generate JWT policy" easily. And if I check the Management API at "management/apis/[api-id]/plans/[plan-id]" URI, the result is fine:
`{
  "id" : "22ef731a-01b7-444b-af73-1a01b7744b6a",
  "name" : "Plan",
  "description" : "Desc",
  "validation" : "auto",
  "security" : "key_less",
  "securityDefinition" : "{}",
  "type" : "api",
  "status" : "staging",
  "apis" : [ "5690ee3e-ee80-4a7e-90ee-3eee809a7e2e" ],
  "order" : 0,
  "characteristics" : [ ],
  "created_at" : 1591459908064,
  "updated_at" : 1591459908064,
  "paths" : {
    "/" : [ {
      "methods" : [ "CONNECT", "DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT", "TRACE", "OTHER" ],
      "policy-generate-jwt" : {"signature":"RSA_RS256","keyResolver":"INLINE","issuer":"urn://gravitee-api-gw","expiresIn":30,"expiresInUnit":"SECONDS","audiences":[],"customClaims":[],"alias":"alias","storepass":"pass","keypass":"keypass","kid":"123456","id":"456789","subject":"MySub"},
      "description" : "Description of the Generate JWT Gravitee Policy",
      "enabled" : true
    } ]
  },
  "excluded_groups" : [ ],
  "comment_required" : false
}`

### Current Behavior
However, when I'm building a plan java object with same informations like that:

`			final NewPlanEntity newPlanEntity = new NewPlanEntity();
			newPlanEntity.setName("Plan");
			newPlanEntity.setDescription("Desc");
			newPlanEntity.setSecurity(PlanSecurityType.KEY_LESS);
			newPlanEntity.setSecurityDefinition("{}");
			newPlanEntity.setCharacteristics(new ArrayList<>());
			newPlanEntity.setExcludedGroups(new ArrayList<>());
			newPlanEntity.setCommentRequired(false);
			newPlanEntity.setApi(api.getId());
			newPlanEntity.setValidation(PlanValidationType.AUTO);
			newPlanEntity.setStatus(PlanStatus.STAGING);

			final Map<String, Path> paths = new HashMap<>();
			final Path path = new Path();
			final List<Rule> rules = new ArrayList<>();
			final Rule rule = new Rule();
			final Set<HttpMethod> methods = new HashSet<>();
			final Policy policy = new Policy();

			methods.add(HttpMethod.CONNECT);
			methods.add(HttpMethod.DELETE);
			methods.add(HttpMethod.GET);
			methods.add(HttpMethod.HEAD);
			methods.add(HttpMethod.OPTIONS);
			methods.add(HttpMethod.PATCH);
			methods.add(HttpMethod.POST);
			methods.add(HttpMethod.PUT);
			methods.add(HttpMethod.TRACE);
			methods.add(HttpMethod.OTHER);
			rule.setMethods(methods);
			rule.setDescription("Description of the Generate JWT Gravitee Policy");
			rule.setEnabled(true);
			policy.setName("policy-generate-jwt");

			final GenerateJwtPolicyConfiguration configuration = new GenerateJwtPolicyConfiguration();
			configuration.setAlias("alias");
			configuration.setAudiences(new ArrayList<>());
			configuration.setCustomClaims(new ArrayList<>());
			configuration.setExpiresIn(30);
			configuration.setExpiresInUnit(TimeUnit.SECONDS);
			configuration.setId("456789");
			configuration.setIssuer("urn://gravitee-api-gw");
			configuration.setKeyResolver(KeyResolver.INLINE);
			configuration.setKeypass("keypass");
			configuration.setKid("123456");
			configuration.setSignature(Signature.RSA_RS256);
			configuration.setStorepass("pass");
			configuration.setSubject("MySub");
			configuration.setX509CertificateChain(X509CertificateChain.NONE);
			final ObjectMapper mapper = new ObjectMapper();
			policy.setConfiguration(mapper.writeValueAsString(configuration));
			rule.setPolicy(policy);
			rules.add(rule);
			path.setRules(rules);
			path.setPath("/");
			paths.put("/", path);
			newPlanEntity.setPaths(paths);
			newPlanEntity.setExcludedGroups(new ArrayList<>());`

and making a REST call with this object, when I check the Management API at "management/apis/[api-id]/plans/[plan-id]" URI, all policy informations are missing (at "paths" variable):

`
{
  "id" : "cf8a42b4-4685-463e-8a42-b44685f63e9d",
  "name" : "Plan",
  "description" : "Desc",
  "validation" : "auto",
  "security" : "key_less",
  "securityDefinition" : "{}",
  "type" : "api",
  "status" : "staging",
  "apis" : [ "8db32006-f88b-40e6-b320-06f88be0e6cf" ],
  "order" : 0,
  "characteristics" : [ ],
  "created_at" : 1591460670239,
  "updated_at" : 1591460670239,
  "paths" : {
    "/" : [ ]
  }
,
  "excluded_groups" : [ ],
  "comment_required" : false
}`

Do you know if Management UI provides some additional data? Because at this point, I don't understand why my request creates plan but not policy.

Thank you by advance :)

### Your Environment
* Version used: 1.30.3

**Comment by brasseld** [comment]
Hi @Babaz69 

Did you check the request payload from your apps ?
Can you compare it to the one done by the management-ui ?

Regards,
