### ISSUE TITLE
Gateway problem

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#3928]
![image](https://user-images.githubusercontent.com/57534152/84044059-58a40c00-a9a7-11ea-887a-387f003161ac.png)
Can someone explain why am I not getting the same response from from the first command...i was expecting database data and not swagger data. I am still learning to use the tools so if someone can explain what am i missing in my config. of the API, is it some policy or do i need some gravitee dependencies in my java app. I was expecting data from 1 ID and not the type of the data.

**Comment by aelamrani** [comment]
Maybe you defined mocks policies on your design?

**Comment by marijatimovska** [comment]
![image](https://user-images.githubusercontent.com/57534152/84047288-65c2fa00-a9ab-11ea-8859-2a381a25e212.png)

I only have this...is there any other place I can check?

**Comment by aelamrani** [comment]
Please check the /v1/students/:id path, as it seems the one concerned by your calls

**Comment by marijatimovska** [comment]
yeah that was the problem and reopened my initial problem where i cant setup my paths for all the rest of the endpoints.I made an issue about that but i closed it, I will screen shot it so its better to understand.

![image](https://user-images.githubusercontent.com/57534152/84052524-fcde8080-a9b0-11ea-9f54-b8205a1ca3ac.png)
![image](https://user-images.githubusercontent.com/57534152/84052544-0536bb80-a9b1-11ea-84b9-a236a04da0f1.png)
![image](https://user-images.githubusercontent.com/57534152/84052573-0cf66000-a9b1-11ea-8fed-535c7863ce9e.png)
![image](https://user-images.githubusercontent.com/57534152/84052607-18e22200-a9b1-11ea-852a-98a0e4d670ff.png)
![image](https://user-images.githubusercontent.com/57534152/84052732-3adba480-a9b1-11ea-819e-05693f0299ca.png)
Swagger is at http://localhost:8080/api/v2/api-docs and the end point are from /api/v1/students...
I dont know how to set this up, I am learning all the the moment so if you have maybe a good example i could see how to set it up or you can tell me if its something small.
I can open a new issue as well so its not all mixed up here.
This was my bigges problem today since i did not know how to set up the paths so i could test my REST API

**Comment by marijatimovska** [comment]
![image](https://user-images.githubusercontent.com/57534152/84057400-e851b680-a9b7-11ea-91a6-fe775fc8908c.png)
This is my problem, no matter how i configure it the patch goes though the swagger and with my lack of experience i don't know how to fix this.I removed /v1 from the controler and now the swagger ui is on http://localhost:8080/api/swagger-ui.htm and the swagger it self is on http://localhost:8080/api/v2/api-docs
