### ISSUE TITLE
Management UI and Portal deployment

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#3931]
How exactly do I deploy Management UI and Portal on Apache web server, do i need to set up the Apache config and index file or just the config, i have not deployed anything though Apache so I could use some help.

I am guessing it has to be something like in here https://docs.gravitee.io/am/current/am_installguide_management_ui_install_zip.html
this id for Portal from the Access Management

**Comment by brasseld** [comment]
Hi @marijatimovska 

You can also use others HTTP servers like Nginx, http-server, ...

Let's use what you know, it doesn't matter.

**Comment by marijatimovska** [comment]
I haven't used Nginx aswell, i run the portal and management with nodejs with http-server command, but now i have to do it with Apache, i was looking for info and found 2 ways just dont know which one do i need...one is to config the Apache conf file and other is to make .htaccess file in the same dir as intex.html

**Comment by marijatimovska** [comment]
@brasseld I am sorry I really don't wanna bother you but this is important, I was trying to fix this since yesterday and only cot confused more, can you help me with the Apache?
