### ISSUE TITLE
Portal from API Management, server down

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#3938]
![image](https://user-images.githubusercontent.com/57534152/84249680-5d81d080-ab0b-11ea-9978-1ad4ade51abb.png)
![image](https://user-images.githubusercontent.com/57534152/84249697-6377b180-ab0b-11ea-900c-af11eb3fde90.png)
![image](https://user-images.githubusercontent.com/57534152/84250638-966e7500-ab0c-11ea-811f-f34a6b4e8a79.png)

Is Portal base url changed aswell as the Management UI, cus its not loading and no info in the migration guide.

**Comment by aelamrani** [comment]
Hi @marijatimovska 

No this has not been changed. Can you try to access the portal API directly? If not found, please check logs.

**Comment by marijatimovska** [comment]
Hi @aelamrani 
![image](https://user-images.githubusercontent.com/57534152/84369897-d5b5c800-abd7-11ea-81bc-00e6d27aced5.png)

**Comment by marijatimovska** [comment]
@aelamrani I also registered but did not get a mail afterwards

**Comment by aelamrani** [comment]
Can you check the logs of the management API?

**Comment by marijatimovska** [comment]
@aelamrani 
![image](https://user-images.githubusercontent.com/57534152/84373355-bec5a480-abdc-11ea-9ffd-27e6bbfa9726.png)

This ones?

**Comment by marijatimovska** [comment]
@aelamrani 
if you need this 
![image](https://user-images.githubusercontent.com/57534152/84374815-e0279000-abde-11ea-890b-2c9826ad05d4.png)

**Comment by aelamrani** [comment]
Ok so seems you are now able to login to the portal right?

So for the email issue, you have to configure your smtp server to be able to send emails: https://github.com/gravitee-io/gravitee-management-rest-api/blob/85ad3b7dfd9aa142a746dbc7eeeee396314f9045/gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml#L279

**Comment by marijatimovska** [comment]
@aelamrani I am logged in APIM UI with admin/admin...i registered twice for a new acc, but no confirmation mail was send...so for that i need to config SMTP in gravitee.yaml in the REST API folder?
![image](https://user-images.githubusercontent.com/57534152/84384288-0acd1500-abee-11ea-97d4-f286138baa42.png)
Is there a day to delete the acc info in the 
![image](https://user-images.githubusercontent.com/57534152/84384356-2a643d80-abee-11ea-9e1a-d965e58c4ad7.png)
I just need to know why is Portal UI down, is it that i dont have an acc...if that is the thing how can i get the username and pass for it cus i cant loging and i cant register again cus there is already info for that mail.

**Comment by marijatimovska** [comment]
@aelamrani Look I will be honest, I dont wanna bother you as much but i am aware that my company is a new partner of yours, i am new, junior lvl and my job is to make a project on all of the features, some thing i have to config are new to me i am left with only few unresolved things and i am done with all

**Comment by marijatimovska** [comment]
@aelamrani Okay i will be honest, as i am aware my company is new partner to yours, and my task as a new worker, junior lvl is to make a presentation for your platform. I am almost done with everything but i few more unresolved issues left. For now i want to know why does the Portal UI from APIM not work. I have an online published API so from what i do understand it should be up on the server. Can i see yours SMTP config?

**Comment by marijatimovska** [comment]
@aelamrani can you attach your smtp config?...i did configure it but still no mail.
I do remember from jenkins smtp config that there were problems with firewall and mail was not send cut of security.
I will be honest my company is new partner to your company and my talk as a fresh worker, jr lvl. is to make a presentation on your platform, I am almost done, few stuff were new to me so that is why i need help.

**Comment by marijatimovska** [comment]
![image](https://user-images.githubusercontent.com/57534152/84401997-365afa00-ac04-11ea-8518-c4eb2ab613fd.png)
![image](https://user-images.githubusercontent.com/57534152/84402045-4541ac80-ac04-11ea-8473-3baeb24f84d2.png)
![image](https://user-images.githubusercontent.com/57534152/84402099-54c0f580-ac04-11ea-8179-72af3f4a0cd6.png)
![image](https://user-images.githubusercontent.com/57534152/84402184-6c987980-ac04-11ea-9b83-f4359f4ab990.png)

@aelamrani @brasseld

**Comment by marijatimovska** [comment]
@aelamrani @brasseld 
![image](https://user-images.githubusercontent.com/57534152/84403869-76bb7780-ac06-11ea-88a0-0107464447c7.png)
![image](https://user-images.githubusercontent.com/57534152/84403894-80dd7600-ac06-11ea-9124-f45178cfbe2a.png)
![image](https://user-images.githubusercontent.com/57534152/84403937-8c30a180-ac06-11ea-992f-0c1b21f6c688.png)

Since it says that this is PortalURL, this has something to do with that fact that my PortaUI is down?

![image](https://user-images.githubusercontent.com/57534152/84404057-acf8f700-ac06-11ea-8eaf-7f950110f65a.png)

I use: http://192.168.0.18:8084/
