### ISSUE TITLE
APIM Portal and Registration mail confirmation 

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#3948]
I have problem with this for days, I have no reply from you. @brasseld @aelamrani @NicolasGeraud 
The APIM Portal UI is down and so is portal URL for mails http://localhost:3000/...i have configured what i think i shroud but nothing helped.
![image](https://user-images.githubusercontent.com/57534152/84488338-50e2b100-aca0-11ea-9e5b-0f954ef0705a.png)
I also enabled authentication using an LDAP/Active Directory. I have SMTP ofc i got the mail for teh confirmation. 
![image](https://user-images.githubusercontent.com/57534152/84488438-796aab00-aca0-11ea-8bcb-2127d244a5a6.png)
This is the only problem left I can't resolve. I do know all of the configuration of portal are in the Management UI. I want to know why is this down, do i have to enable it from the Man, UI. I honetsly cant find anything. I am using port 8084 for the Portal. I also checked if by any chance port 3000 for the emails is being used by something else, its not.

![image](https://user-images.githubusercontent.com/57534152/84488584-b6cf3880-aca0-11ea-9b2c-40d3a5fb2047.png)

**Comment by aelamrani** [comment]
Hi @marijatimovska 

Can you share your browser's console logs?

**Comment by marijatimovska** [comment]
This? @aelamrani 
![image](https://user-images.githubusercontent.com/57534152/84491543-00218700-aca5-11ea-8c1f-c2631952fe01.png)

**Comment by marijatimovska** [comment]
![image](https://user-images.githubusercontent.com/57534152/84491851-7cb46580-aca5-11ea-8afd-359b02422d43.png)

**Comment by aelamrani** [comment]
Are you running the rest API on the port 8084?
Can you try to reach it from you computer?
Can you tell me what is the content of the config.json on portal UI?

**Comment by marijatimovska** [comment]
![image](https://user-images.githubusercontent.com/57534152/84493250-c00fd380-aca7-11ea-844f-258f7e7e6df4.png)

By any chance do I have to disable CORS on my browser. I have the gateway with Rest API on 8082.

**Comment by marijatimovska** [comment]
![image](https://user-images.githubusercontent.com/57534152/84493610-5217dc00-aca8-11ea-885f-905251ec65f8.png)

**Comment by aelamrani** [comment]
The default port of the Gateway is 8082 and for the REST API is 8083.

So if you did not change anything you should have the following baseUrl defined: http(s)://your_host:8083/portal/environments/DEFAULT

**Comment by marijatimovska** [comment]
![image](https://user-images.githubusercontent.com/57534152/84494255-77591a00-aca9-11ea-90cb-5d1c1fc8e0f1.png)

**Comment by aelamrani** [comment]
?

So you are using http-server to deploy the portal UI:
- I don't think it will work with http-server (but works well for the mgmt UI) => maybe you will need something like angular-http-server, but for production env I will suggest another tool like Nginx or Apache.
- That means you are serving only static files on 8084, now you need to deploy the mgmt API somewhere, and change your configuration to point on it (see my previous comment)

**Comment by marijatimovska** [comment]
![image](https://user-images.githubusercontent.com/57534152/84496248-e7b56a80-acac-11ea-9758-9456dc1d6a9e.png)
Does not say i have to only deploy it like the AM Portal with virtual host with apache, i assumed I can run it like the Management UI. I will deploy now see what i can do.

**Comment by marijatimovska** [comment]
Same issue with Apache

**Comment by aelamrani** [comment]
Did you change the baseUrl?

**Comment by aelamrani** [comment]
Documentation is up to date now: https://docs.gravitee.io/apim/3.x/apim_installguide_portal_install_zip.html#or_run_it

**Comment by marijatimovska** [comment]
I think the whole problem is with CORS and because the Portal UI is down i assume that is why the Portal mail URL is not working( localhost:3000), this is from what i got in the logs.

**Comment by marijatimovska** [comment]
@aelamrani  do you know where you would have demo.gravitee.io...portal is redirecting me to demo.gravitee.io so I get CORS error, cant find the keyword anywhere.

**Comment by aelamrani** [comment]
Replace the baseUrl in the assets/config.json file to point to your rest api

**Comment by marijatimovska** [comment]
I honeslty have no idea i changed it to "baseURL": "http://localhost:8083/portal/environments/DEFAULT",

**Comment by aelamrani** [comment]
Please be careful to the case used => baseUrl (and not baseURL)

**Comment by marijatimovska** [comment]
Nothing really matters tbh, I honesty have no idea why is not working...I have no other choice but to redo everything

**Comment by marijatimovska** [comment]
@aelamrani I just redownloaded all because i had 3.0.1 and the files are all with baseURL not baseUrl

**Comment by marijatimovska** [comment]
![image](https://user-images.githubusercontent.com/57534152/84534290-f4a47f00-ace9-11ea-93d1-f9b04b4291b3.png)
![image](https://user-images.githubusercontent.com/57534152/84534311-fcfcba00-ace9-11ea-90c3-87e18d2e52f2.png)
I redid everything, nothing changed I for real have no clue
