### ISSUE TITLE
[management] Gravitee.io AM Admin UI automatically enables implicit grant on SPA applications

### ISSUE THREAD

**Issue by dozer75** [gravitee-io/issues#3962]
### Expected Behavior

Implicit grant is not recommended used in SPA applications (as with native apps) anymore (ref: https://oauth.net/2/grant-types/implicit/). The Gravitee.io AM should not enable this by default when creating a "Single-Page App", in addition the description in Settings -> OAuth 2.0 / OIDC should stop recommending Implicit flow for SPA applications.

### Current Behavior
Today, when creating a "Single-Page App", Implicit is enabled by default. 

In addition, the documentation text on Settings -> OAuth 2.0 / OIDC recommends Implicit flow:

```
authorization_code for server side applications (web) or native applications (then combined with PKCE).
implicit must be used for Single Page Applications.
```

### Possible Solution

Remove the Implicit as default type (but keep it for legacy), and update the comments.

### Steps to Reproduce (for bugs)

1. Create a new Single-Page app
2. Go to Settings -> OAuth 2.0 / OIDC 
3. Verify that both Authorization Code and Implicit is selected

### Context

It is a recommendation to NOT use Implicit anymore from SPA applications. It has been like this for quite a while now due to security issues and authentication interception. It is now recommended to only use authorization code with code grant. The Gravitee AM portal should encourage the same to aid inexperienced users to the correct grant type for SPA applications.

### Your Environment

* Version used: 3.0.x

**Comment by tcompiegne** [comment]
Hi @dozer75 ,

Yeah you are absolutely right. As you mentioned implicit flow was here for legacy purpose but now we have to update the commentary / overview sections and introduce a step by step guide to use PKCE.
