### ISSUE TITLE
[management] Two application with same client_id

### ISSUE THREAD

**Issue by ElementalArchmage** [gravitee-io/issues#3977]
If I create two application with same client_id  fast enough, 
then two application with same client_id will be created.

### Expected Behavior

Client id must be unique field.

### Current Behavior

Client id is not unique field.

### Steps to Reproduce (for bugs)

**Two thread or  two sequentially request in 300 ms**

POST  <gravitee url >/management/applications

with body:
{
  "settings": {
    "app": {
      "client_id": "1e3c69bb-ce03-4bce-8722-772f8eeeeee"
    }
  },
  "name": "Tech application",
  "description": "Application was created for tech user."
}

### Context

I got this bug, when I create application with rest api. 

### Your Environment

* Version used: 1.30.5
* Browser Name and version: Yandex 19.10.3.281
* Operating System and version: Windows 10

**Comment by gaetanmaisse** [comment]
Closing as the bug isn't present anymore in the last version, I tested it with multiple calls in less than 200ms and got the following error response: 
```json
{
  "message": "An application already exists with client_id [1e3c69bb-ce03-4bce-8722-772f8eeeeee]",
  "parameters": {
    "clientId": "1e3c69bb-ce03-4bce-8722-772f8eeeeee"
  },
  "technicalCode": "application.clientId.exists",
  "http_status": 400
}
```
