### ISSUE TITLE
Assistance - how to manage this use case

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#398]
I have 2 process
First, allow to create (PUT) or delete (DELETE) sites

I declared:
i declared first api ( create site) with context path : /v0/sites
backend:  192.xxx.xxx.AB.:9000/v0
it could also manage DELETE method, but title is not good

I want to declare second api: read sites
second api: allow to get (GET) sites
backend:  192.xxx.xxx.AB.:9002/v0
i want to declare new api but i can't declare context path: /v0/sites

How can i manage this use case ? i thought to dynamic routing but it's on uri and not on method ?

thanks for your advices

**Comment by brasseld** [comment]
Hi @vdelattre,

When you're applying policies, these policies are selected according:
1. To the path
2. To the HTTP method

What you need is to dispatch calls to one or another backend according to the HTTP method (or group of methods: read / write).

You can do that very easily using Gravitee.io APIM by filtering the execution of policies according to the HTTP method.

Please have a look to this example:

<img width="818" alt="capture d ecran 2017-01-06 a 16 11 11" src="https://cloud.githubusercontent.com/assets/133094/21721959/ceabb048-d42a-11e6-9ee7-68961f950409.png">

Is it ok for you?

**Comment by NicolasGeraud** [comment]
Why not 2 Plan (1 read, 1 create) on the same api ?

**Comment by vdelattre** [comment]
How do you manage routing to different backend ?

**Comment by NicolasGeraud** [comment]
Sorry, I misunderstood your use case.

David has right, you should configure only 1 api and use verb filtering on each policy configuration.

**Comment by vdelattre** [comment]
David, it works.
![image](https://cloud.githubusercontent.com/assets/22543323/21724739/e69bdb0a-d435-11e6-9188-43e81b921d73.png)


but in redirects to, i have to put backend IP.
How to use defined backend.
ex: 1st backend:  name =input
2nd backend:  name =output
![image](https://cloud.githubusercontent.com/assets/22543323/21724787/01fac136-d436-11e6-9d5c-6046e2f2efa6.png)


in redirect for get, i put:
http://192.168.175.33:9002/{#group[0]}

How to put : output ?

and more generally, how to know all variables like {#group[0]} ?

**Comment by vdelattre** [comment]
Hello,

with this configuration, does analityc will show different routing?

**Comment by brasseld** [comment]
The _final_ endpoint is stored in the analytics.

Can you tell me what you need exactly in terms of reporting ?

**Comment by vdelattre** [comment]
with this configuration, i defined only 1 api in gravitee, but i have 3 differents methods to call: GET, PUT, DELETE.
I want to be able to show in analytics data for each method

**Comment by brasseld** [comment]
I'm sorry, I've misses your previous message.
You can use the following syntax to get the endpoint you need: `{#endpoints['output']}/{#group[0]}`

Also, you can create a new issue to improve documentation about EL.

**Comment by brasseld** [comment]
Ok so your need is not to see the analytics per endpoint, but you want to be able to filter by HTTP method, right ?

**Comment by vdelattre** [comment]
exactly.
And may be, it can be fine to filter by routing policy

**Comment by brasseld** [comment]
It would be fine, yes.
But analytics don't know about policies, that's the reason why the _invoked_ endpoint is stored for each request. So we can imagine a filter by endpoint.

**Comment by brasseld** [comment]
Hi @vdelattre, can we close this issue ?

**Comment by brasseld** [comment]
May I ask you to create an other issue for this new feature ?
Just to avoid mixin between issue concerns.

Thanks.
