### ISSUE TITLE
[portal] Portal UI 3.0.2 non configurable ?

### ISSUE THREAD

**Issue by Emmanuel35** [gravitee-io/issues#3985]
A la suite d'une installation fraiche de la version 3.0.2. Le portail me présente le message

"Serveur indisponible ou connection perdu"

### Expected Behavior

Le portail aurait dû me présenter les API depuis l'API Management.

### Current Behavior

Depuis le navigateur, les URL demandées sont celles de http://demo.gravitee.io .Elles sont donc refusées en lecture.

### Steps to Reproduce (for bugs)
1. Installation Docker
2. Configuration du PORTAL UI avec les options:

```
PORTAL_API_URL=https://portal.$_DOMAIN,
MGMT_API_URL=https://management-api.$_DOMAIN/management/organizations/DEFAULT/environments/DEFAULT/
```

### Context
Google Cloud Run

### Your Environment
* Version used: 3.0.2
* Browser Name and version: Chrome
* Operating System and version: Windows 10

**Comment by aelamrani** [comment]
I confirm this is configurable this way.

Can you please check the content of the configuration file in the container? => assets/config.json

**Comment by Emmanuel35** [comment]
Content is:
```
{
  "baseUrl": "https://portal.formation.middleware-solutions.fr",
  "loaderUrl": "assets/images/gravitee-loader.gif",
  "pagination": {
    "size": {
      "default": 10,
      "values": [5, 10, 25, 50, 100]
    }
  }
}
```
In browser:
![image](https://user-images.githubusercontent.com/2102128/85017631-0fed0f80-b16c-11ea-8e57-b11e90a4c65d.png)

**Comment by aelamrani** [comment]
Mixed content => happens when you are trying to reach a https URL from a non secure (http) location.

**Comment by Emmanuel35** [comment]
HTTPs is added by my load balancer. 
All services are HTTPs.
I have done any change into HTTP configuration for Portal or Management.

There is a configuration to do in Gravitte APIM ?

**Comment by aelamrani** [comment]
Sorry I did not read correctly your screenshot and missed http://demo...

Well, can you check the network tab, you should have a get on the config => /assets/config.json

Seems this one is failing.

**Comment by aelamrani** [comment]
Also, can you try on private mode (browser)?

**Comment by Emmanuel35** [comment]
Same as previous.

![image](https://user-images.githubusercontent.com/2102128/85036891-f99f7d80-b184-11ea-9709-6b072e457add.png)

URL is also available: https://portal.formation.middleware-solutions.fr/

**Comment by aelamrani** [comment]
Your configuration seems not correct: 

```
PORTAL_API_URL=https://portal.$_DOMAIN,
MGMT_API_URL=https://management-api.$_DOMAIN/management/organizations/DEFAULT/environments/DEFAULT/
```

Should be `PORTAL_API_URL=https://portal-api.formation.middleware-solutions.fr/portal/environments/DEFAULT` no?

**Comment by Emmanuel35** [comment]
My variable $DOMAIN is transformed to have:

```
MGMT_API_URL=https://management-api.formation.middleware-solutions.fr/management/organizations/DEFAULT/environments/DEFAULT/
PORTAL_API_URL=https://portal.formation.middleware-solutions.fr
```

**Comment by aelamrani** [comment]
It seems to be invalid.

I just tried to reach the API there and this serve the portal UI...

You have to provide the portal API: https://management-api.formation.middleware-solutions.fr/portal/environments/DEFAULT

And if you want to split in multiple APIs (one for the portal and another for the management), you can just configure it here: https://github.com/gravitee-io/gravitee-management-rest-api/blob/370f924da64cd28373c19fbf2ed4eb85e6c39b76/gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/src/main/resources/config/gravitee.yml#L46

Is that clearer?

**Comment by Emmanuel35** [comment]
Thank you Azize.
It is work ! 

PS: Maybe you can update this page with you information. https://docs.gravitee.io/apim/3.x/apim_installguide_docker_images.html#graviteeioapim_portal_ui

Before
```
$ docker run \
        --publish 80:80 \
        --env MGMT_API_URL=http://localhost:81/management/ \
        --name portal-ui \
        --detach  \
        graviteeio/apim-portal-ui:latest
```

After
```
$ docker run \
        --publish 80:80 \
        --env PORTAL_API_URL=http://localhost:81/portal/environments/DEFAULT \
        --name portal-ui \
        --detach  \
        graviteeio/apim-portal-ui:latest
```

**Comment by aelamrani** [comment]
Done! Thanks for pointing this out.
