### ISSUE TITLE
[portal] Portal UI baseURL non configurable ?

### ISSUE THREAD

**Issue by edatei** [gravitee-io/issues#3997]
Bonjour, 
Je viens d'installer la version 3.0.2 de l'API Manager sur un serveur CentOS 7
Tous les composants sont installés sur la même VM. (10.100.43.151)

J'ai démarré la Portail comme indiqué dans la documentation par les commandes:
cd /opt/graviteeio-portal-ui-3.0.2
angular-http-server
Listening on 8080

La Gateway est lancée
Les Management API sont bien lancés également
L'interface de management fonctionne correctement

Lorsque depuis le navigateur j'accède au portail par l'URL:
http://10.100.43.151:8080

J'arrive sur la page d’accueil qui s'affiche avec le message :
"Serveur indisponible ou connection perdu"

Comme indiqué dans la documentation j'ai créé un fichier config.json dans le répertoire du portail
/opt/graviteeio-portal-ui-3.0.2

contenant:
{
  "baseURL": "http://10.100.43.151:8080/portal/environments/DEFAULT"
}

J'ai également essayé de le faire pointer sur les management API avec 
{
  "baseURL": "http://10.100.43.151:8083/portal/environments/DEFAULT"
}

J'ai toujours la même Erreur avec le message :
"Serveur indisponible ou connection perdu"

Quelle est la procédure pour configurer correctement le portail ?

**Comment by brasseld** [comment]
Hi @edatei 

Il semble que la casse de `baseURL` ne soit pas correcte: https://github.com/gravitee-io/gravitee-portal-webui/blob/master/src/assets/config.json#L2

Pouvez-vous changer en `baseUrl` plutôt ?

**Comment by brasseld** [comment]
Aussi, le fichier de config doit se trouver dans un répertoire `assets` (`/opt/graviteeio-portal-ui-3.0.2/assets/config.json`

**Comment by edatei** [comment]
Merci. Ca fonctionne.
Vous devriez indiquer dans la documentation que ce fichier config.json se trouve dans le répertoire assets et qu'il faut positionner l'URL des Management API sur le port 8083 et non pas le port 8080 du portail.

**Comment by brasseld** [comment]
Pouvez vous m'indiquer où avez vous trouvé référence au port 8080 ?

Merci d'avance
