### ISSUE TITLE
create milestone on all github repositories

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#40]
_From @NicolasGeraud on April 3, 2016 16:41_

All repositories must have a milestone called "next release". This milestone will be applied on each issue which will be part of the next gravity release.

We also must have a way to add a milestone with the name of the release.

With that, we could automatically add this milestone on each closed issue qith the milestone "next release"

_Copied from original issue: gravitee-io/jenkins-scripts#19_

**Comment by brasseld** [comment]
@NicolasGeraud : I think we do not need this anymore since we are now managing issues from a single repository. WDYT ?

**Comment by NicolasGeraud** [comment]
I'm agree
