### ISSUE TITLE
[docker] Cannot login, reset password or register from the Portal UI using the Docker Compose for Platform 

### ISSUE THREAD

**Issue by IOhacker** [gravitee-io/issues#4000]
Canot login, reset password or register from the Portal UI using the Docker Compose for Platform 

### Expected Behavior

The users can login using the login form, reset the password or register.

### Current Behavior

Canot login, reset password or register from the Portal UI using the Docker Compose for Platform 
Always we got 403 error, e xaple for reset password
{
"servlet":"org.glassfish.jersey.servlet.ServletContainer-40b2aae9",
"message":"Forbidden",
"url":"/portal/environments/DEFAULT/users/_reset_password",
"status":"403"
}

### Steps to Reproduce (for bugs)

1. Clone the https://github.com/gravitee-io/gravitee-docker/tree/master/
2. Run the docker compose https://github.com/gravitee-io/gravitee-docker/tree/master/platform/3.x
3. Enable the developer view in the browser
4. Try to login, reset or register any user (even default admin credentials)
6. Nothign happens in the browser, but errors appears in the Developer View
{
"servlet":"org.glassfish.jersey.servlet.ServletContainer-40b2aae9",
"message":"Forbidden",
"url":"/portal/environments/DEFAULT/users/_reset_password",
"status":"403"
}

### Context

Users cannot login, register, or reset the password

### Your Environment

* Version used:
https://github.com/gravitee-io/gravitee-docker/tree/master/
* Browser Name and version:
Any current chrome or firefox version
* Operating System and version:
Linux 18.04, MacOS Sierra

**Comment by aelamrani** [comment]
@IOhacker I am able to reproduce, I will check this.
