### ISSUE TITLE
[gateway] inject transaction id into the response

### ISSUE THREAD

**Issue by lusoalex** [gravitee-io/issues#401]
Hello,

Currently, a transaction id is generated on each request handled by the gateway.

### Expected Behavior
Regarding the previous issue [307](https://github.com/gravitee-io/issues/issues/307)
It would be useful to retrieve this transaction id through the response.
That way we can communicate this id for some support purpose.
_As if we were using an Application Performance Management tool..._

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/gravitee-gateway/commit/1d3daabcfc1c5afb592627d2f286fb544e9471e7
