### ISSUE TITLE
[portal] Add more filtering options for analytics

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#402]
### Expected Behavior
I have an api in which i defined 3 dynamic routing (by get, by put and by delete).
I also created 3 plans to authorize or path (GET, PUT, DELETE)
I'd like to see in analytics information by plan and/or by http method

### Your Environment
* Version used: 1.1

**Comment by brasseld** [comment]
Waiting for https://github.com/gravitee-io/issues/issues/430

**Comment by brasseld** [comment]
Closes as part of https://github.com/gravitee-io/issues/issues/430
