### ISSUE TITLE
[PORTAL][MANAGEMENT-UI][MANAGEMENT-API] Management ui and portal baseUrl

### ISSUE THREAD

**Issue by mvilche** [gravitee-io/issues#4022]
Hi.
I am using version 3.0.3 of api management.
The only way to connect the management ui with the management api was through this endpoint:
{
  "baseURL": "http://management-api-api.127.0.0.1.nip.io/management/organizations/DEFAULT/environments/DEFAULT/"
}

This is correct?
The documentation mentions using /management/portal but when configuring it like this I always get a 401.

The ui portal also failed to connect it to the endpoint indicated in the documentation in this case I always get a 404.
Currently the config.json of portal ui configure it like this:

{
  "baseURL": "http://management-api-api.127.0.0.1.nip.io/management/organizations/DEFAULT/environments/DEFAULT/portal"
}

To which endpoint of the managmenet api should I point it?

Thank you very much!

**Comment by aelamrani** [comment]
Hi @mvilche 

Can you point which documentation mention this?

>The documentation mentions using /management/portal but when configuring it like this I always get a 401.

You should have something like: `http://management-api-api.127.0.0.1.nip.io/portal/environments/DEFAULT`

**Comment by mvilche** [comment]
I am referring to this documentation https://docs.gravitee.io/apim/3.x/apim_installguide_management_ui_configuration.html

The url http://management-api-api.127.0.0.1.nip.io/portal/environments/DEFAULT
always returns 401 to me.

This is my management api url:

http://management-api-api.127.0.0.1.nip.io

My configuration for management ui is as follows:
constants.json {
  "baseURL": "http://management-api-api.127.0.0.1.nip.io/management/organizations/DEFAULT/environments/DEFAULT/"
}
With this configuration I can easily access the management ui but it is not clear to me if the url is correct.

As for the portal - ui what value should I add in the config.json:

config.json {
  "baseURL": "http://management-api-api.127.0.0.1.nip.io/portal/environments/DEFAULT"
}

This configuration does not work for me and I have tried several combinations but none have worked for me.

The portal always returns the message Server unavailable or connection lost.

I have used version 1 for a long time and it has worked excellent, it is a great application. But I couldn't get version 3 to work properly.

I take this opportunity to tell you that for version 1 I have a catalog for openshift in high availability that I would like to share with you if you wish.
I am trying to configure version 3 to also deploy it in openshift.
Thank you very much and I apologize for my English, I am from Uruguay.

**Comment by mvilche** [comment]
Hi.
Thank you very much.
I was able to solve the problem.
Using the following url http://management-api-api.127.0.0.1.nip.io/portal/environments/DEFAULT
I was able to access the ui portal.

The problem was in the gravitee.yaml, it had an incorrect configuration on the endpoints.

Thank you very much and sorry for the inconvenience

**Comment by brasseld** [comment]
Hey @mvilche,

Thanks for your feedback.

> I take this opportunity to tell you that for version 1 I have a catalog for openshift in high availability that I would like to share with you if you wish.
> I am trying to configure version 3 to also deploy it in openshift.

I'm interested by this. We have an existing openshift repositoy which is not up to date.
Maybe we can benefit of your work on 1.x and future work 3.x to update repository?

Feel free to contact me at david(at)graviteesource.com to discuss this.

Cheers,

**Comment by mvilche** [comment]
Thanks to you. Yes of course, I would love to contribute to you. I currently use v1 over openshift in various projects in production. I am working on v3 to implement it in a new project for the Uruguayan government and to propose deploying a microservices architecture using gravitee as managemnt api.

**Comment by brasseld** [comment]
Ok, let me know how we can work together to push your stuff on gravitee repository.
