### ISSUE TITLE
Can we link Gravitee.io to Postgresql repository ?

### ISSUE THREAD

**Issue by Sylverin7** [gravitee-io/issues#4037]
The default Gravitee.io's installation is using mangodb as repo. But we would prefer that it uses a postgresql database. The online documention seems to indicate that it may be but no more information about it. Can we do that ? can you ensure identical compatibility as mangodb ? How to do it ?

**Comment by tapiiron** [comment]
PostgreSQL repo can be used via JDBC Repository Plugin.
For management rest api and gateways do the following:
1) first get gravitee-repository-jdbc-version.zip and place it at plugins-folder
2) mkdir -p plugins/ext/repository-jdbc
3) copy postgresql jdbc driver to plugins/ext/repository-jdbc
4) edit gravitee.yml -file and use your postgresql-repo
management:
  type: jdbc
  jdbc:
    url: jdbc:postgresql://localhost/graviteedb
    username: databaseuser
    password: databasepassword

**Comment by brasseld** [comment]
https://docs.gravitee.io/apim/3.x/apim_installguide_repositories_jdbc.html

**Comment by Sylverin7** [comment]
Thanks!

**Comment by brasseld** [comment]
May we close the issue @Sylverin7 ?

**Comment by Sylverin7** [comment]
How doest it behave with elasticsearch ?
Yes you can close even I have not really tested yet. We may do that soon.

**Comment by brasseld** [comment]
Elasticsearch can't be replaced by Postgresql.

Ok waiting for your feedback on this.
