### ISSUE TITLE
[oauth2] refresh tokens must not be used after user consents revocation

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#4039]
Currently AM do that to check if a refresh token is still valid :

- the authorization server has revoked the refresh token
- the refresh token has expired

We should also check if : 

- the user has revoked their consent for authorization

**Comment by jhaeyaert** [comment]
After discussion, we agreed that when user revokes an application or a single permission (from Authorized apps screen), we will revoke both all the existing refresh_token and access_token.
