### ISSUE TITLE
[portal] Configure health-check depending on backend endpoints

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#405]
### Expected Behavior
because of 2 apis can't have same context path, api have to be configure with dynamic routing by http method by example.
ex: 1 api with 1 backend for GET method and 1 other backend for PUT method.
But this 2 backends may not have same health-check method.
I would be fine to can configure several health-check depending on backend

### Current Behavior
same health-check for all backends

### Your Environment
* Version used: 1.1

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/issues/issues/704
