### ISSUE TITLE
[policy] Add AM classes to Groovy whitelist

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#4050]
Since #3933, Groovy is sandboxed. AM rely on Groovy to create policy conditions to protect uma resources. At least, following classes should be whitelisted by default:

- `io.gravitee.am.gateway.handler.context.provider.UserProperties`
- `io.gravitee.am.gateway.handler.context.provider.DomainProperties`
- `io.gravitee.am.gateway.handler.context.provider.ClientProperties`
- `io.gravitee.am.model.uma.PermissionRequest`

**Comment by tcompiegne** [comment]
NOTE: we do not forget to update policy dependency version in pom.xml file.
