### ISSUE TITLE
[oauth2] Oauth2 Authentication of API Portal and API Management have not the same behavior

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4058]
When I am logging in on the console using an OIDC authent, the role mapping is correctly applied. 

That is not the case on the portal for the same authent. We should not have a difference.

Edit:
after this comment https://github.com/gravitee-io/issues/issues/4058#issuecomment-738710143
the purpose of this issue is to refactor Oauth2 resources of both APIs so they share code and have the same behavior

**Comment by jhaeyaert** [comment]
I'm not able to reproduce the described problem. However, I can reproduce a similar problem when I update the role mapping and select the option to rerun mapping each time the user login. 

![image](https://user-images.githubusercontent.com/5955401/101153301-87343400-3624-11eb-8ce3-a602d16a377a.png)

In that specific case, the roles are not updated when the user login on the portal but are well updated when the user login on the management console.

This behavior can be explained by the fact that there are  2 distinct implementations of the oauth authentication process, one for the portal, one for the management console. Even if they are close at first, it seems they have evolved differently over time and the portal authentication process doesn't take care of the role mapping synchronization process.

**Comment by aelamrani** [comment]
It seems you are reproducing the behavior here, we should not have this kind of difference between a login from the portal and from the console.

**Comment by leleueri** [comment]
Here is test cases I validated:

- create new user1 from console without GrpMapping/RoleMapping => user with default role on env & org
- create new user2 from portal without GrpMapping/RoleMapping => user with default role on env & org
- create new user3 from console with  GrpMapping/RoleMapping => user has role on env & org + is group member
- create new user4 from portal with  GrpMapping/RoleMapping => user has role on env & org + is group member
- Update role mapping & group mapping, connect user3 to console  => user has new roles on env & org + group member
- Update role mapping & group mapping, connect user4 to portal  => user has new roles on env & org + group member
- Add user3 & user4 to a group X using console UI, create a new group and update group mapping 
  -  connect user3 to console  => user has roles on env & org + is member of the new group and still member of the group X
  -  connect user4 to portal  => user has roles on env & org + is member of the new group and still member of the group X
- remove role & group mapping 
  -  connect user3 to console ==> user has default roles on env & org, only member of the group X
  -  connect user4 to portal ==> user has default roles on env & org, only member of the group X
