### ISSUE TITLE
[platform] Weak JDK dhparams

### ISSUE THREAD

**Issue by tapiiron** [gravitee-io/issues#4064]
APIM: Gateway has weak dhparams (1024)

### Expected Behavior
HTTPS service returns good dhparams.

### Current Behavior
DHParams lower than 2048 are considered weak. By default 1024 is used.

### Possible Solution
Add following lines to gateway/bin/gravitee :
JAVA_OPTS="$JAVA_OPTS -Djdk.tls.ephemeralDHKeySize=2048"

### Your Environment
* Version used: 3.0.4
* Browser Name and version: NA
* Operating System and version: RedHat 8, PostgreSQL repo, OpenJDK11

**Comment by tapiiron** [comment]
Same goes with management and portal rest api.

**Comment by brasseld** [comment]
Thanks for pointing this @tapiiron 

This should be done for all our server-side components.
