### ISSUE TITLE
[management] General Conditions of use (when subscribing to a plan)

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4068]
The idea here is to display a page of general conditions to the consumer at the plan level. 

A new step to be accepted in order so subscribe.

We should be able to audit the acceptation of these conditions.

**Comment by leleueri** [comment]
This feature allows to add a page of api documentation to a plan as general conditions.

Here is some management rules:
* plan can be published with a general condition page only if the page is published
* a page used as general condition can't be remove or unpublished if a published or deprecated plan use it as general condition
* a plan transfer can't be done toward a plan using general conditions

In the portal, if the plan has general conditions, these conditions must be accepted to finalize the subscription
