### ISSUE TITLE
[management] Custom user fields

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4070]
The idea is to customize user fields to be filled when registrating

**Comment by leleueri** [comment]
- [ ] Add a new environment role to grant access to user field definition
- [ ] In management console : create a page to display & edit the list of custom user fields (access restricted by the new role created) 
- [ ] Create a new repository to preserve the definition of the custom user fields
- [ ] Add a new role to grant access to user field definition
- [ ] Update login pages (mng & portal) to manage custom user fields
- [ ]  preserve values provided by the user into the Metadata repository (using a new RefType)
