### ISSUE TITLE
[Policy] [Gateway] OnActivation annotation

### ISSUE THREAD

**Issue by Madieso** [gravitee-io/issues#4076]
Hello,
policies use \@OnRequest and/or \@OnResponse annotation.
But what about \@OnActivation? Does methods with this annotation are launch when plan is created? Or at each new instance of policy?

Thank you by advance,

**Comment by brasseld** [comment]
Hey @The461 

Where do you see this `OnActivation` annotation?

**Comment by The461** [comment]
On "gravitee-policy-api-1.1.0-sources.jar" which contains "io.gravitee.policy.api.annotations.lifecycle.OnActivation" annotation.
I thought there is a link between this annotation and \@OnRequest annotation because they are on the same package, but maybe not :)

**Comment by brasseld** [comment]
Ok, this is mainly used starting with Gravitee 3.x

This is used sometime by policies. For example, the groovy policy: https://github.com/gravitee-io/gravitee-policy-groovy/blob/issues/%233933-sandbox-groovy/src/main/java/io/gravitee/policy/groovy/GroovyInitializer.java

The onActivation is called when you're deploying an API (the classloader is specific to this API), and, obviously, the onDeactivation is called when the API is undeployed. It's done only once, and not for each new instance.

It allows you to, maybe, share some information between multiple executions of the same policy, when you need to cache something for example, or if you want to manage a single HTTP client across all the policy instances.

(A point to know about is that a new instance of the policy is created each time the api gateway need it).

**Comment by The461** [comment]
Thank you for you answer.

Indeed, a new instance of the policy is created each time the api gateway need it but this is not the case for **policy configuration** which still the same instance.
So, can we add **onActivation** annotation in the main policy class (with **onRequest** annotation) to add data into **policy configuration** and reach it at **onRequest** after?
