### ISSUE TITLE
https://demo.gravitee.io seems to be down

### ISSUE THREAD

**Issue by larsnaesbye** [gravitee-io/issues#4082]
The site returns "Management API unreachable or error occurs, please check logs".

I was just trying to check out the demo :-)

**Comment by brasseld** [comment]
Hey @larsnaesbye we had some docker issues today. Sorry for that.

Looks good on my side. Can you try to refresh ?

**Comment by larsnaesbye** [comment]
@brasseld Yes now it works - merci beaucoup! :-)
