### ISSUE TITLE
[management] Sometimes "400 - Invalid Image Format" when updating a picture

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#4086]
It works with this image when creating or updating  a view or an API:
![gio logo](https://user-images.githubusercontent.com/13161768/87068290-a2d21480-c215-11ea-8998-a673463f007b.png)

It works with this image when **creating a view only. Not when updating a view or an API**:
![125-1251588_vector-rectangle-frames-gold-square-frame-png](https://user-images.githubusercontent.com/13161768/87068504-f17fae80-c215-11ea-88b5-0747ab9b363c.png)

**Comment by aelamrani** [comment]
Seems we are sending text/plain when we are expecting to send JSON

https://github.com/gravitee-io/gravitee-management-rest-api/blob/fcb883df5f601752f3f03561a3661d26a21df4d5/gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiResource.java#L233
