### ISSUE TITLE
[policy][rest-to-soap] Can not save the form after updating prefill soap envelope in some case

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#4087]
### Expected Behavior

Editing a policy field containing some data should enable the Save button

### Current Behavior

Editing a policy field containing some data doesn't always enable the Save button

### Possible Solution

[export.zip](https://github.com/gravitee-io/issues/files/4903588/export.zip)

### Steps to Reproduce (for bugs)

1. Go to the design view of your api
2. Select a existing Rest-to-Soap policy
3. Try to edit multiple time a field containing some data (like envelope)
4. The "Save" button is disabled
5. Edit the Charset field
6. Now the Save button is enabled

**Comment by aelamrani** [comment]
Due to the definition which contains invalid data: charset to null instead of ""

**Comment by aelamrani** [comment]
Seems to be an issue as the behavior has changed since the 1.30 and now we get this kind of error when we have `null` on a string value of a policy:

Example:

```
            {
                "methods": [
                    "GET"
                ],
                "mock": {
                    "status": "200",
                    "headers": [
                        {
                            "name": "Content-Type",
                            "value": "application/json"
                        }
                    ],
                    "content": null
                },
                "description": "Get all instances of entity",
                "enabled": false
            }
```

```
{
  "message" : "Invalid policy configuration : instance type (null) does not match any allowed primitive type (allowed: [\"string\"])",
  "http_status" : 400
}
```

Note: we cannot get this kind of configuration from the UI but with an external tool or a template.

**Comment by aelamrani** [comment]
Getting also: 

Invalid policy configuration : instance type (null) does not match any allowed primitive type (allowed: ["array"])

**Comment by leleueri** [comment]
**Note**: In the schema-form.json to authorize `null` as value for optional field, use the syntax
-      ` "type" : ["<expected-type>", "null"]`

ex : 
```
   "headers" : {
      "type" : ["array", "null"],
      "title": "Headers",
      ...
```
