### ISSUE TITLE
[platform] use same evaluable request and response objects for templating and scripting

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#4090]
Currently, there is multiple implementations of EvaluableRequest and EvaluableResponse which are injected to EL and Groovy context.
The idea is to get only one implementation of each of these objects and use them in all plugins. Some example of classes which are concerned:

- `io.gravitee.gateway.reactor.handler.context.EvaluableRequest`
- `io.gravitee.gateway.reactor.handler.context.EvaluableResponse`
- `io.gravitee.gateway.reactor.handler.context.EvaluableExecutionContext`
- `io.gravitee.gateway.handlers.api.processor.error.templates.EvaluableRequest`
- `io.gravitee.policy.assignattributes.EvaluableRequest`
- `io.gravitee.policy.assignattributes.EvaluableResponse`
- `io.gravitee.policy.callout.el.EvaluableRequest`
- `io.gravitee.policy.callout.el.EvaluableResponse`
- `io.gravitee.policy.callout.CalloutResponse`
- `io.gravitee.policy.mock.el.EvaluableRequest`
- `io.gravitee.policy.requestvalidation.EvaluableRequest`
- `io.gravitee.policy.rest2soap.el.ContentAwareEvaluableRequest`

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/issues/issues/4431
