### ISSUE TITLE
Create repository with all mandatory files and configuration

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#41]
_From @NicolasGeraud on February 22, 2016 10:28_

When we add a new repo, we must : 
-  add CONTRIBUTING.adoc
-  add README.adoc
-  update github issues labels
-  add .editorconfig
-  optionnaly update release.json
-  create the jenkins build job
-  add .gitignore
-  add LICENSE.txt
-  protect master branch
-  add repository into Waffle.io

_Copied from original issue: gravitee-io/jenkins-scripts#4_

**Comment by gaetanmaisse** [comment]
Closing as outdated, for instance:
  - Waffle.io isn't used anymore
  - Jenkins has been replaced by CircleCI
  - README AND CONTRIBUTING file will be reworked on many repo
