### ISSUE TITLE
[management] How changing SMTP server ?

### ISSUE THREAD

**Issue by Sylverin7** [gravitee-io/issues#4103]
The user creation does not work because it needs email validation. How configuring smtp server after docker-compose installation ? Does apim-Manager-UI manage that ?

### Expected Behavior
Create new user by apim-Manager-UI and configure new smpt server.

### Current Behavior
User creation requires an email validation but no smtp server is configured and no error is raised. We cannot modify the default password and log with the new user.

### Possible Solution
- allow admin to change default password
- allow apim-manager-ui settings to change smtp server
- log an error when an email is not sent

### Steps to Reproduce (for bugs)
Create new user without configuration of smtp server

### Your Environment
Installation with docker-compose

**Comment by Sylverin7** [comment]
Can we change the docker-compose like that ?
...
    container_name: graviteeio-demo-management_api-3
...
    environment:
...
      - gravitee.email.host=xxx
      - gravitee.email.port=xxx
      - gravitee.email.username=xxx
      - gravitee.email.paswword=xxx
      - gravitee.email.enable=true

**Comment by aelamrani** [comment]
Hi @Sylverin7 

Did you check the documentation here?

https://docs.gravitee.io/apim/1.x/apim_installguide_management_api_configuration.html#sending_emails

**Comment by Sylverin7** [comment]
Yes, I have checked this document before writting the issue. But does it really resolve my problem? May be about the installation. Do you see my comment above ?

**Comment by aelamrani** [comment]
You have a typo on password configuration => `paswword`

Please check the documentation to see how to configure env vars: https://docs.gravitee.io/pages/apim/3.x/installation-guide/partial/how-to-configure.html#environment_variables

**Comment by Sylverin7** [comment]
It's done, thanks! But it does not work. No mail is sent and no error is logged. I cannot connect with new user.

**Comment by aelamrani** [comment]
No log in your management API?

Normally, as an admin you should be able to reset password of the user. He will then receive an email to configure his password...etc

<img width="1014" alt="Capture d’écran 2020-07-16 à 13 55 32" src="https://user-images.githubusercontent.com/1580262/87668333-33f04080-c76c-11ea-84a5-0e2e98a598fe.png">
