### ISSUE TITLE
[management] Allows an admin to revert a deprecate state on a plan

### ISSUE THREAD

**Issue by insertmike** [gravitee-io/issues#4109]
### Problem Context

The current flow of the states of a plan for API in a Gravitee context is:

- **STAGING**: Allowed to PUBLISH and CLOSE

- **PUBLISHED**: Allowed to DEPRECATE and CLOSE

- **DEPRECATED**: Allowed to CLOSE

- **CLOSED**: Not allowed to change state

###  Behaviour
I can't find particular reason why Gravitee does not allow plans to be shifted from DEPRECATED back to STAGING and etc. There might be cases when this is required and at this point of time the only thing that can be done to achieve this is to:

1. Move the plan to CLOSED state
2. Re-create the plan from STAGING

Which process is itself redundant.

### Possible Solution
Allow shifting of plans back the chain ( E.G DEPRECATED -> PUBLISHED ) 

### Steps to Reproduce (for bugs)

1. Create an API
2. Add a plan
3. Experiment how the plan states can be changed according to the issue description

### Context

- Gravitee Version:  graviteeio-full-3.0.4

**Comment by vkopichenko** [comment]
Please count my vote for support of undoing plan deprecation.

**Comment by larsnaesbye** [comment]
Me too. Undoing plan deprecation seems a must-have.
