### ISSUE TITLE
[docker] URL provided in the documentation are not working after docker-compose up

### ISSUE THREAD

**Issue by loicdescotte** [gravitee-io/issues#4110]
After running docker-compose up, as explained in the documentation (https://docs.gravitee.io/am/2.x/am_installguide_docker.html), I'm opening the URLs provided in the documentation : 

  * http://localhost/am/
  * http://localhost/am/management
  * http://localhost/am/ui/

### Expected Behavior

This URL should display some content

### Current Behavior

  * http://localhost/am/ : An  error is displayed  : "No security domain matches the request URI." (404 HTTP error)
  * http://localhost/am/management/ : 404  HTTP error 
  * http://localhost/am/ui/ : An error is displayed : "Sorry, the page you are looking for is currently unavailable. Please try again later." (502 HTTP error)

### Steps to Reproduce (for bugs)
Runs steps from the gravitee docker documentaiton : 

```
$ mkdir -p config
$ curl -L -O https://raw.githubusercontent.com/gravitee-io/graviteeio-access-management/master/docker/compose/docker-compose.yml
$ curl -O https://raw.githubusercontent.com/gravitee-io/graviteeio-access-management/master/docker/compose/.env
$ cd config && { curl -O https://raw.githubusercontent.com/gravitee-io/graviteeio-access-management/master/docker/compose/config/nginx.conf ; cd -; }

# (Optional step: pull to ensure that you are running latest images)
$ docker-compose pull

# And run...
$ docker-compose up
```

### Context

The docker-compose up command runs successfully, no errors in the logs during the start of services.

I have this errors in the logs when I try to access to am ui : 

```
gio_am_nginx  | 2020/07/17 10:11:38 [error] 9#9: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /am/ui/ HTTP/1.1", upstream: "http://172.18.0.5:8080/", host: "localhost"
gio_am_nginx  | 172.18.0.1 - - [17/Jul/2020:10:11:38 +0000] "GET /am/ui/ HTTP/1.1" 502 494 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:78.0) Gecko/20100101 Firefox/78.0"
```

### Your Environment
Tried MacOS (Catalina) and on Windows 10 with Ubuntu shell on WSL

**Comment by brasseld** [comment]
Hi Loic,

It will be fixed once AM 3.1 is released.

That is a temporary collateral damage after https://github.com/gravitee-io/issues/issues/4094

Sorry about that.

**Comment by aelamrani** [comment]
Hi @loicdescotte 

Are you able to check now the 3.1 has been released?

Thanks

**Comment by loicdescotte** [comment]
@aelamrani I have another issue now when trying to log the AM ui.
There is a blank page with errors in the browser console : 
```
ERROR Error: Uncaught (in promise): TypeError: o.settings.authentication is undefined
e@http://xxx/am/ui/main.28cf5e465ac347cf499e.js:1:1494161
pg/t<@http://xxx/am/ui/main.28cf5e465ac347cf499e.js:1:408465
pg@http://xxx/am/ui/main.28cf5e465ac347cf499e.js:1:408699
cg@http://xxx/am/ui/main.28cf5e465ac347cf499e.js:1:407890
CcnG/Ag</e.prototype.get@http://xxx/am/ui/main.28cf5e465ac347cf499e.js:1:419309
nv@http://xxx/am/ui/main.28cf5e465ac347cf499e.js:1:423451
Qg@http://xxx/am/ui/main.28cf5e465ac347cf499e.js:1:422449
Zg@http://xxx/am/ui/main.28cf5e465ac347cf499e.js:1:421279
Dv@http://xxx/am/ui/main.28cf5e465ac347cf499e.js:1:432846
kv@http://xxx/am/ui/main.28cf5e465ac347cf499e.js:1:431635
Gv@http://xxx/am/ui/main.28cf5e465ac347cf499e.js:1:442354
CcnG/Cg</n.prototype.create@http://xxx/am/ui/main.28cf5e465ac347cf499e.js:1:410573
``

**Comment by loicdescotte** [comment]
seems ok now :)
