### ISSUE TITLE
APIM-Admin-3.0.4 - Logout fails with user from OpenID Connect provider

### ISSUE THREAD

**Issue by Sylverin7** [gravitee-io/issues#4125]
We cannot logout  an user when come from an OpenID Connect provider (APIM Admin version 3.0.4)

We configure logout link on OpenID Connect provider:
![logout bug](https://user-images.githubusercontent.com/67646393/88177959-ee2eee80-cc29-11ea-8c88-0e6ed6f31e50.PNG)

When we clic on "Deconnexion" button, we have :
Not Found
The requested URL /oauth2/logout/https://test-api-adm-ui.com. was not found on this server.

![logout bug 2](https://user-images.githubusercontent.com/67646393/88177956-ed965800-cc29-11ea-940e-cffdb9910d72.PNG)

The http link is wrong ! "https://test-api-adm-ui.com" is the APIM admin ui web site.

Regards,

**Comment by aelamrani** [comment]
Hi @Sylverin7 

Are you trying to login in the portal or the admin?

Can you share your OIDC config?

**Comment by Sylverin7** [comment]
Hi,

I tried to logout on the admin with an user from a OpenID provider. The login is ok.

I uploaded the logout config on the provider OpenID connect but the logout click do not send the good request and do not come back to the login page. But with an other user the logout is ok.

Regards,

De : Elamrani Azize <notifications@github.com>
Envoyé : mercredi 22 juillet 2020 16:03
À : gravitee-io/issues <issues@noreply.github.com>
Cc : PARMENTIER, SAMUEL <samuel.parmentier@atos.net>; Mention <mention@noreply.github.com>
Objet : Re: [gravitee-io/issues] APIM-Admin-3.0.4 - Logout fails with user from OpenID Connect provider (#4125)


Caution! External email. Do not open attachments or click links, unless this email comes from a known sender and you know the content is safe.

Hi @Sylverin7<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSylverin7&data=02%7C01%7Csamuel.parmentier%40atos.net%7C3e83b475aa8a4913e36108d82e480201%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637310234089439847&sdata=8pLHTlL5qVSy5ix4IJM6a%2FcZxgwFMGxYYPP2gsgPv4Q%3D&reserved=0>

Are you trying to login in the portal or the admin?

Can you share your OIDC config?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgravitee-io%2Fissues%2Fissues%2F4125%23issuecomment-662471522&data=02%7C01%7Csamuel.parmentier%40atos.net%7C3e83b475aa8a4913e36108d82e480201%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637310234089439847&sdata=28bjxhP1LElWc5go%2BCuBrXLoXLJF4TutRV3HKjp9e68%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQEDHOK22OBHL7MCBEOU37DR43WQFANCNFSM4PEVUZRA&data=02%7C01%7Csamuel.parmentier%40atos.net%7C3e83b475aa8a4913e36108d82e480201%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637310234089449839&sdata=5bewRjRe6sd3DTwq5jlBNDtG1EFcZ6u5LGP09OSwxjY%3D&reserved=0>.

Ce message et toutes les pièces jointes (ci-après le "message") sont établis à l’intention exclusive des destinataires désignés. Il contient des informations confidentielles et pouvant être protégé par le secret professionnel. Si vous recevez ce message par erreur, merci d'en avertir immédiatement l'expéditeur et de détruire le message. Toute utilisation de ce message non conforme à sa destination, toute diffusion ou toute publication, totale ou partielle, est interdite, sauf autorisation expresse de l’émetteur. L'internet ne garantissant pas l'intégrité de ce message lors de son acheminement, Atos (et ses filiales) décline(nt) toute responsabilité au titre de son contenu. Bien que ce message ait fait l’objet d’un traitement anti-virus lors de son envoi, l’émetteur ne peut garantir l’absence totale de logiciels malveillants dans son contenu et ne pourrait être tenu pour responsable des dommages engendrés par la transmission de l’un d’eux.

This message and any attachments (the "message") are intended solely for the addressee(s). It contains confidential information, that may be privileged. If you receive this message in error, please notify the sender immediately and delete the message. Any use of the message in violation of its purpose, any dissemination or disclosure, either wholly or partially is strictly prohibited, unless it has been explicitly authorized by the sender. As its integrity cannot be secured on the internet, Atos and its subsidiaries decline any liability for the content of this message. Although the sender endeavors to maintain a computer virus-free network, the sender does not warrant that this transmission is virus-free and will not be liable for any damages resulting from any virus transmitted.

**Comment by aelamrani** [comment]
Yes I wanted to say logout.

Well, what is the difference between the two users? Are you doing something more than the other one?

**Comment by Sylverin7** [comment]
The other user does not come from a provider openId connect and no logout path is configured

**Comment by aelamrani** [comment]
Oh OK, let me try to reproduce.

Can you share the configuration of your authentication? Especially the logout part.

**Comment by Sylverin7** [comment]
I have just configured my "User Logout Point" on my OpenID Connect provider edition page.

![logout bug](https://user-images.githubusercontent.com/67646393/88177959-ee2eee80-cc29-11ea-8c88-0e6ed6f31e50.PNG)

**Comment by aelamrani** [comment]
Ok so IMHO you just miss here the redirect uri.

Should something like: https://test-connexion/oauth2/logout?post_logout_redirect_uri=

**Comment by Sylverin7** [comment]
OK Merci

**Comment by aelamrani** [comment]
@Sylverin7 May I close this issue? Is it working on your side now?

**Comment by Sylverin7** [comment]
Yes it is. That's working !
