### ISSUE TITLE
[policy] [rate-limit] Increase configurability of the rate-limit policy

### ISSUE THREAD

**Issue by bursauxa** [gravitee-io/issues#4128]
First of all, hello Gravitee, thanks for your work :+1: Now on to the issue :wink: 

### Context

We have an API where users identify themselves by passing their ID as an URL parameter. For this API, we set up a keyless plan, as neither JWT not OAuth are applicable. We now want to apply per-user rate limiting.

In the case of keyless plans, the current rate-limiting mechanism defines an "user" as an IP address. This does not work for us, because our API is intended for robotic consumption, and some of our cloud-based users have hundreds of IPs from which they perform calls.

### Proposed solution

A generic and extensible solution would be to allow API publishers to define the rate-limit key themselves, instead of using the default (which is currently the plan-subscription pair, where plan = `1` and subscription = IP in the case of keyless plans).

More specifically, the following changes should be done:

- In the rate limit policy, add a field to allow API publishers to set a custom rate limit key
- At runtime, evaluate with SpEL the value of the key; in our context, we would read the ID in the URL parameter, but anything is possible
- In addition, make the limit value support SpEL: it makes sense as part of the general configurability improvement of this policy, and in our case would eventually allow us to set different limits per user
- Defining a custom key should not be mandatory: in case it is not defined, fall back to current behavior (plan-subscription pair)

### Additional notes

This looks related to #395 but that issue was over three years old, and I think we have a broader approach here.

We can work on this issue and hopefully provide a pull request, if the proposed solution is an approach that suits you.

**Comment by gaeljw** [comment]
@brasseld: do you confirm such a solution looks good to you? Just to be sure we don't start implementing something that wouldn't fit your expectations.

**Comment by brasseld** [comment]
Remembers me some discussions :)

> Defining a custom key should not be mandatory: in case it is not defined, fall back to current behavior (plan-subscription pair)

👍 

> In addition, make the limit value support SpEL: it makes sense as part of the general configurability improvement of this policy, and in our case would eventually allow us to set different limits per user

I'm a bit worried about this one. What is your use-case here ? Does it mean that, depending on the incoming request, the limit value would be / could be different?

**Comment by bursauxa** [comment]
> I'm a bit worried about this one. What is your use-case here ? Does it mean that, depending on the incoming request, the limit value would be / could be different?
Yes, that is the idea. The goal is not to look at the path per se (we would have different APIs for that case), but to use the key itself. This is the use case:

```
my.awesome.api/unicorns?userId=Alice
my.awesome.api/unicorns?userId=Bob
```

First we want to use userId as the rate-limit key (so Alice is not blocked if Bob spams the service). This is covered by the first points.

Second, we like Alice, so we want to give her 100 QPS, but we do not like Bob so we want to give him only 10 QPS. This means we need a configurable limit, where we will likely look up in a dictionary to find the corresponding value.

We have more modern APIs that use JWT authentication, and for them we intend to give different plans to Alice and Bob (by issuing them tokens with a different client ID, and thus different applications behind the scenes - which would translate into different subscriptions to different plans). But, that is not possible with keyless authentication.

**Comment by brasseld** [comment]
Ok, that makes more sense now.

Lucky Alice :)

**Comment by bursauxa** [comment]
Here is the merge request as promised, I posted it a few days ago but messed up the issue autolinking because it's not in the same repo :bulb:
