### ISSUE TITLE
[management] Use URLs of the portal and management from settings

### ISSUE THREAD

**Issue by YoranSys** [gravitee-io/issues#4144]
### Current Behavior

If we enable `Force authentication to access portal`  the registration form in the email link for new subscribed user is inaccessible and password protected. 

### Possible Solution
Disable protection for this link on the portal front.

### Steps to Reproduce (for bugs)
1. enable `Force authentication to access portal`
2. create an account
3.click on the link in your email (private browsing)
4.You will redirected to the login form

### Your Environment

* Version used: 3.1.1
* Browser Name and version: Firefox /Chrome

**Comment by aelamrani** [comment]
@YoranSys I just had a try and I am not able to reproduce.

Maybe you can share the link on the email?

**Comment by YoranSys** [comment]
@aelamrani there is the link  I receive :

https://**mydomain.com**/#!/registration/confirm/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwOWQ3YjFlNC02Nzg5LTQyOGQtOTdiMS1lNDY3ODk5MjhkYmIiLCJmaXJzdG5hbWUiOiJZb2hhbm4iLCJpc3MiOiJncmF2aXRlZS1tYW5hZ2VtZW50LWF1dGgiLCJhY3Rpb24iOiJVU0VSX0NSRUFUSU9OIiwiZXhwIjoxNTk2MTE4NTQwLCJpYXQiOjE1OTYwMzIxNDAsImVtYWlsIjoieW9oYW5uLmZhYnJpQHJjYS5mciIsImxhc3RuYW1lIjoiRmFicmkifQ.7tTxcsM7m4RgNsaDn1r2qsgrN6P-V8lLSZIfTPrnwVU

**Comment by aelamrani** [comment]
I am not able to reproduce.

May I ask you to try to reproduce in our nightly env?

https://nightly.gravitee.io

admin/admin

**Comment by aelamrani** [comment]
You can have a try with this link:

https://nightly.gravitee.io/#!/registration/confirm/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwN2M0MmY4Yi1lYmMzLTRlMzctODQyZi04YmViYzM5ZTM3YzAiLCJmaXJzdG5hbWUiOiJZb2hhbm4iLCJpc3MiOiJncmF2aXRlZS1tYW5hZ2VtZW50LWF1dGgiLCJhY3Rpb24iOiJVU0VSX0NSRUFUSU9OIiwiZXhwIjoxNTk2MTE4NTQwLCJpYXQiOjE1OTYwMzIxNDAsImVtYWlsIjoieW9oYW5uLmZhYnJpQHJjYS5mciIsImxhc3RuYW1lIjoiRmFicmkifQ.WlK513ie6_Qkw-Hcy4CSgib3QjZV7WKvSjtngWNHnxs

**Comment by YoranSys** [comment]
I forgot to mention, the domain **https://mydomain.com** stand for Portal Dev frontend.
Your link point to the admin portal, my generated link point to the portal dev frontend, I don't know why. 

But since the admin portal can be hidden from the web for security reason and the api server with `http:
  api.management.enabled: false` it's seem good for me, to be redirected to the portal. I'm right ?

In your platform my link would be : 
https://v3.nightly.gravitee.io/user/login?redirectUrl=%2F%23!%2Fregistration%2Fconfirm%2FeyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwN2M0MmY4Yi1lYmMzLTRlMzctODQyZi04YmViYzM5ZTM3YzAiLCJmaXJzdG5hbWUiOiJZb2hhbm4iLCJpc3MiOiJncmF2aXRlZS1tYW5hZ2VtZW50LWF1dGgiLCJhY3Rpb24iOiJVU0VSX0NSRUFUSU9OIiwiZXhwIjoxNTk2MTE4NTQwLCJpYXQiOjE1OTYwMzIxNDAsImVtYWlsIjoieW9oYW5uLmZhYnJpQHJjYS5mciIsImxhc3RuYW1lIjoiRmFicmkifQ.WlK513ie6_Qkw-Hcy4CSgib3QjZV7WKvSjtngWNHnxs

**Comment by YoranSys** [comment]
The password reset link is working but i think it bypass the front: /user/resetPassword/confirm/**KEY**

**Comment by aelamrani** [comment]
Oh, the link you have provided me first is about the management UI...

Well you probably have bad portal URL config:

https://nightly.gravitee.io/#!/settings/portal

**Comment by YoranSys** [comment]
After many try I find out where the problem come from. 
It's in the **gravitee.yml**

```
# The portal URL used in emails
portalURL: http://localhost:3000/
```
The name portaURL for me was portal developer : https://v3.nightly.gravitee.io/
If i set this value to  management UI: ** https://nightly.gravitee.io/** the link in email work good.

For v3 I think, the name of this variable is not good anymore  `Management UI` vs `Portal UI `.

Also with the split of UI in v3, we can protect the Management UI and management api (api.management.enabled: true) in internal network, but if the account registration links for the developer portal point to management UI we can't do it.

What do you think @aelamrani ?

**Comment by aelamrani** [comment]
Yes, the portalURL has not been changed to keep the compatibility with the previous version.

What we could do is to rely on the settings to get the portal / mgmt URL and not anymore on the gravitee.yml. And maybe use the old `portalURL` as a fallback value.

I don't know why we didn't do this with the add of the settings in the console...

What do you think?

**Comment by YoranSys** [comment]
Sounds good.
