### ISSUE TITLE
[management] Allow customization of the API documentation with a theme

### ISSUE THREAD

**Issue by YoranSys** [gravitee-io/issues#4148]
### Expected Behavior

Allow customization of the API documentation in Markdown with a theme:
- table
- header
- ...

### Your Environment

* Version used: 3.1.1

**Comment by aelamrani** [comment]
Closed by https://github.com/gravitee-io/issues/issues/4147

The table colors in markdown are based on the theme colors to keep a coherency on the portal.

![Capture d’écran 2020-08-06 à 10 44 54](https://user-images.githubusercontent.com/1580262/89511204-e3e82500-d7d1-11ea-852b-4e645d5913aa.png)
