### ISSUE TITLE
[management] When we import an api, documentation is broken: internal link, image, order of appearance

### ISSUE THREAD

**Issue by YoranSys** [gravitee-io/issues#4149]
### Expected Behavior
When we import an api, the documentation inside it need to be transportable:
- Internal link inside the same api
- Gravitee uploaded image
~~- Order of appearance in menu~~

### Current Behavior

When we import an api, the documentation inside is broken for this elements:
- Internal link inside the same api 
   - redirect to the old platform
~~- Order of appearance in menu~~
- Gravitee uploaded image
   - redirect to the old platform and not being exported with the API

### Possible Solution

- UUID of pages and API is present on the export, during the import we can remap to the new UUID in markdown link.
~~- "Order  of appearance" can be part of the export format~~
- Image can be included in a base64 with the UUID as is currently the case with the logo when we export

### Steps to Reproduce (for bugs)

1. Create an api with 3 mardown page
2. Order it, add image and make internal link
3. Export the API
4. Shutdown gravitee and make a fresh install
5. Import the API on this new env
6. All internal link, image ~~, and order of appearance is lose~~

### Context

> How has this issue affected you? 

When we prepare some update of our API on staging environment, we can't import our API, without manually editing it. 

### Your Environment

* Version used: 1.30.X and 3.X

**Comment by aelamrani** [comment]
@YoranSys we are not able to reproduce, can you provide an export of an API?

**Comment by YoranSys** [comment]
@aelamrani i made a mistake, the order of appearance in menu is already on the export.

On a v3.0.6 : 

For image and link you can find my api here : 
[Demo-1-0(1).zip](https://github.com/gravitee-io/issues/files/5040909/Demo-1-0.1.zip)

## Image 
On my apim the second page look like:
![image](https://user-images.githubusercontent.com/11197007/89638641-6fce7f80-d8ac-11ea-9f0d-7e58fbe7faa6.png)

The link of the image is :
- http://localhost:8083/management/organizations/DEFAULT/environments/DEFAULT/apis/9d1f7b00-798c-4cda-9f7b-00798c4cda13/media/10AFECF996BFDCC691D1DE8C7E2F451A


## Internal link on first page (homepage):

The internal link is : `/catalog/api/9d1f7b00-798c-4cda-9f7b-00798c4cda13/doc?page=c3d13e62-e20d-45d2-913e-62e20db5d278`

Two more questions : 
- When we delete an API image uploaded inside seem not to be delete, could you confirm ? 
- Why we use management api to serve portal image ?

**Comment by aelamrani** [comment]
> When we delete an API image uploaded inside seem not to be delete, could you confirm ?

I would say this is not normal, we should delete it.

> Why we use management api to serve portal image ?

To avoid to rely as much as possible on external links to serve a portal page.

**Comment by YoranSys** [comment]
@aelamrani for the order of page, it's the descriptor `.gravitee.json` that does not support it, for API and global documentation.

* https://github.com/gravitee-io/gravitee-management-webui/blob/f4176b1050c0808a85ce56b9d170843ad8d11c14/docs/management-configuration-portal-pages.md
* https://github.com/gravitee-io/gravitee-management-webui/blob/f4176b1050c0808a85ce56b9d170843ad8d11c14/docs/management-api-documentation.md
