### ISSUE TITLE
graviteeio/gateway v1.30.3 returning 404 on metrics

### ISSUE THREAD

**Issue by tru-cstavares** [gravitee-io/issues#4153]
Hi, 

I am running Gravitee v1.30.3 on K8S. Metrics were enable to be scraped by Prometheus. However, gravitee/gateway is returning a 404. 

### Expected Behavior
The curl http://127.0.0.1:18082/_node/metrics/prometheus returns 200OK with data.

### Current Behavior
The curl http://127.0.0.1:18082/_node/metrics/prometheus returns 404 not found.

### Steps to Reproduce
Inside docker container:
> /opt/graviteeio-gateway # curl -v -XGET http://127.0.0.1:18082/_node/metrics/prometheus
> Note: Unnecessary use of -X or --request, GET is already inferred.
>   Trying 127.0.0.1...
> TCP_NODELAY set
> Connected to 127.0.0.1 (127.0.0.1) port 18082 (#0)
> GET /_node/metrics/prometheus HTTP/1.1
> Host: 127.0.0.1:18082
> User-Agent: curl/7.61.1
> Accept: */*
>
> HTTP/1.1 404 Not Found
> content-length: 9
> 
> Connection #0 to host 127.0.0.1 left intact
> Not Found/opt/graviteeio-gateway #

and on gateway config:

    services:
      core:
        http:
          port: 18082
          host: 0.0.0.0
          authentication:
            # authentication type to be used for the core services
            # - none : to disable authentication
            # - basic : to use basic authentication
            # default is "basic"
            type: none
            users:
              user: passwd
        metrics:
          enabled: true
          prometheus:
            enabled: true

### Context
Get metrics from Prometheus

### Your Environment
* Version used: graviteeio/gateway:1.30.3
* Browser Name and version: curl 7.61.1 (x86_64-alpine-linux-musl) libcurl/7.61.1 LibreSSL/2.0.0 zlib/1.2.11 libssh2/1.9.0 nghttp2/1.39.2
* Operating System and version: Linux gravitee-apim-gateway-55df79f976-bb857 4.14.177-139.254.amzn2.x86_64 #1 SMP Thu May 7 18:48:23 UTC 2020 x86_64 Linux

**Comment by tru-cstavares** [comment]
The issue still occurs on lastest build: v1.30.17. Still receive the 404 Not Found

**Comment by aelamrani** [comment]
Hi @tru-cstavares 

What is the result of the below call:

```
curl -v -XGET http://127.0.0.1:18082/_node
```

**Comment by tru-cstavares** [comment]
Ho @aelamrani,

that returns a 200OK.

>/opt/graviteeio-gateway # curl -v -XGET http://127.0.0.1:18082/_node
>Note: Unnecessary use of -X or --request, GET is already inferred.
>*   Trying 127.0.0.1...
>* TCP_NODELAY set
>* Connected to 127.0.0.1 (127.0.0.1) port 18082 (#0)
> GET /_node HTTP/1.1
> Host: 127.0.0.1:18082
> User-Agent: curl/7.61.1
> Accept: */*
>
>< HTTP/1.1 200 OK
>< Content-Type: application/json
>< transfer-encoding: chunked
><
>{
>  "id" : "bee6012e-9942-48a7-a601-2e994278a755",
>  "name" : "Gravitee.io - API Gateway",
>  "metadata" : { },
>  "version" : {
>    "BUILD_ID" : "869",
>    "BUILD_NUMBER" : "869",
>    "MAJOR_VERSION" : "1.30.17",
>    "REVISION" : "1ff134c072c314d7f0465149d0580c4b51fd415d"
>  }
>* Connection #0 to host 127.0.0.1 left intact
>/opt/graviteeio-gateway #

But when I try 

curl -v -XGET http://127.0.0.1:18082/_node/metrics

or 

curl -v -XGET http://127.0.0.1:18082/_node/metrics/prometheus

both return 404 Not Found.

**Comment by aelamrani** [comment]
Strange, I am not able to reproduce at all.

Do you have stacktrace on your logs?

**Comment by tru-cstavares** [comment]
Just to update this issue, problem was related with wrong identation of this block

```
  # metrics service
  metrics:
    enabled: false
# default: local, http_method, http_code
#    labels:
#      - local
#      - remote
#      - http_method
#      - http_code
#      - http_path
    prometheus:
      enabled: true
```

 It was set under _services_>_core_ but should be only under _services_.

BR
