### ISSUE TITLE
[gateway] STOMP + Spring Boot + StompJs 5 + Large messages splitted in chunks: subscription doesn't work.

### ISSUE THREAD

**Issue by gianx89** [gravitee-io/issues#4156]
This is the setup:

- Gravitee AM 3.1.0 (running on docker)
- Gravitee APIM 3.1.1 (running on docker)
- Backend developed using Spring Boot + Websockets + STOMP
- Stomp client developed using StompJs 5.4.4

**I have no problems with smaller messages that are not divided into chunks** (Spring Boot requires it for bigger messages and, as it seems, is not a standard behaviour): my subscription callback is correctly fired:

```
stompClient.subscribe('/user/uploaded', function(file) {
     console.log(file);
     showFile(JSON.parse(file.body).name);
});
```

When I have to send **bigger messages**, I have to **turn on this option in the client**:

`splitLargeFrames: true`

Spring Boot has some trouble with larger messages and due to this it implements a non standard behaviour (only with text messages): **the message has to be divided into chunks**.

When it happens, my backend correctly sends the correct message to the right subscription queue:

![image](https://user-images.githubusercontent.com/733323/89211531-48349a00-d5c2-11ea-9de6-38d9cecc2db6.png)

**But my subscription callback is not fired.** _Then everything is broken: even shorter messages misbehave and I have to disconnect and reload the client to make it work again_.

**It all works fine if my client connects directly to "localhost"**. If I pass through Gravitee, I have this strange behaviour on larger splitted messaged. 

_Already debbuged it with the client lib developer, and it's not his fault._

I'm attaching:

- A demo project [stomp-larger.zip](https://github.com/gravitee-io/issues/files/5017525/stomp-larger.zip) which includes backend and client

- A couple of testing files [data.pdf](https://github.com/gravitee-io/issues/files/5017528/data.pdf)  [bigger_data.pdf](https://github.com/gravitee-io/issues/files/5017532/bigger_data.pdf) (Not valid pdf files, but good for testing)

- The Api definition [STOMP-API.zip](https://github.com/gravitee-io/issues/files/5017545/STOMP-API.zip)

You have just to:

1. import the json into APIM 
2. change the api endpoint IP and change the broker url inside stomp.js so you pass through Gravitee
3. launch the spring project
4. open localhost:8080
5. hit connect
6. choose the smaller file and send it (look ad the console, **it should print "CIAO"**)
7. choose the bigger file and send it (look at the console, **"CIAO" is not printed**)
8. **try all the steps with localhost without using Gravitee: it all works fine**.

It seems like Gravitee is stripping off something, but I don't know what.

Can you investigate @brasseld ?

Thanks in advance.

**Comment by gianx89** [comment]
Could be related @brasseld https://github.com/gravitee-io/issues/issues/4220 ?

**Comment by brasseld** [comment]
That could be.

Can you have a try ?
