### ISSUE TITLE
[gateway] APIM gateway 3.0.4 -> 3.0.6 causes WARN  No plan has been selected and apis does not work

### ISSUE THREAD

**Issue by tapiiron** [gravitee-io/issues#4169]
When using same gravitee.yml when updating to 3.0.6 from 3.0.4, no api work and getting warnings in log for each call:
WARN  i.g.g.h.a.p.plan.PlanPolicyResolver - No plan has been selected to process request 602b53b4-a2e1-4ad2-ab53-b4a2e11ad203. Returning an unauthorized HTTP status (401) 

### Current Behavior
APIs stop working if updating to gw 3.0.6. No other warnings or errors are shown in gravitee logs.

### Steps to Reproduce (for bugs)
1. Create API with plan and deploy it to 3.0.4 gateway
2. Test the api and see it works
3. Update to 3.0.6 gateway
4. Test the api and it logs warning and returns 401

### Context
Cannot update gateway nodes to 3.0.6 but management node is up and running with newer version.

### Your Environment
* Version used: 3.0.4 and 3.0.6
* Browser Name and version: NA
* Operating System and version: RHEL8, OpenJDK11, jdbcrepo 3.0.4(newest 3.0 series) in postgresql

**Comment by aelamrani** [comment]
Hi @tapiiron do you have startup logs to share on the gateway?

**Comment by tapiiron** [comment]
Sure, will send them in your email

**Comment by aelamrani** [comment]
@tapiiron ok thanks for reporting this.

I am now able to reproduce I will provide a fix on the next 3.0.7.
