### ISSUE TITLE
[management-api] Create Subscription not returning subscription keys

### ISSUE THREAD

**Issue by insertmike** [gravitee-io/issues#4171]
### Summary
There is an issue with the [Create Subscription Endpoint](https://docs.gravitee.io/apim/3.x/portal-api/3.1/#operation/createSubscription) from the Gravitee Docs which makes simply subscribing to an api plan inadequate.

### Expected Behavior
Expected Behavior is that the endpoint: 
`http://localhost:8083/portal/environments/{envId}/subscriptions`
would return the subscription details as well as the KEY for the subscription when successful.

### Current Behavior
The endpoint returns the subscription details but no keys in the response. The consumer needs to make another api call to:
`https://docs.gravitee.io/apim/3.x/portal-api/3.1/#operation/getSubscriptionById` to get the `keys`. 

Current Sample Response for successful subscription:
```
{
"id": "string",
"api": "string",
"application": "string",
"plan": "string",
"request": "string",
"reason": "string",
"created_at": "2019-08-24T14:15:22Z",
"processed_at": "2019-08-24T14:15:22Z",
"start_at": "2019-08-24T14:15:22Z",
"end_at": "2019-08-24T14:15:22Z",
"paused_at": "2019-08-24T14:15:22Z",
"closed_at": "2019-08-24T14:15:22Z",
"subscribed_by": "string",
"status": "PENDING",
}
```

### Possible Solution
Add `keys` to response message.

### Your Environment
Gravitee Version: Gravitee 3.X

**Comment by insertmike** [comment]
Get Subscription By ID does not return the keys too, opposite as stated in the documentation: https://docs.gravitee.io/apim/3.x/portal-api/3.1/#operation/getSubscriptionById

**Comment by jhaeyaert** [comment]
Hi @insertmike, I'll add the subscription keys to the create endpoint as you suggested it. Also, for the get subscription endpoint, did you noticed that keys are not returned by default and you have to specify the query parameter `include=keys` ?
