### ISSUE TITLE
[Kubernetes] Fail to download graviteeio/am3

### ISSUE THREAD

**Issue by ThomAille** [gravitee-io/issues#4173]
### Expected Behavior
The command `helm install --name graviteeio-am graviteeio/am3` must install access Management 3.X

### Current Behavior
After launching the following command: `helm repo add graviteeio https://helm.gravitee.io` 
I try to install access management by launching this command: `helm install graviteeio-am graviteeio / am3`
this returns me the following error message: `Error: failed to download "graviteeio / am3" (hint: running `helm repo update` may help)`

I run the update repo command by running the following command: `helm repo update` which returns me this message: 

```
Hang tight while we grab the latest from your chart repositories ...
... Successfully got an update from the "graviteeio" chart repository
Update Complete. ⎈ Happy Helming! ⎈
```

After I restart the access management installation command and I get the same errors.

I specify that I was able to install api management without worry by running the following command: `helm install graviteeio-apim3x graviteeio / apim3`

### Possible Solution
The following url: https://helm.gravitee.io/index.yaml shows that am3 is missing in your chart
You must add the am3 repository

### Steps to Reproduce (for bugs)
1. Launch `helm repo add graviteeio https://helm.gravitee.io`
2. Launch `helm install graviteeio-am graviteeio/am3`
3. Launch `helm repo update`
4. Launch `helm install graviteeio-am graviteeio/am3`

### Context
I am looking to install the access management and api management suite using kubernetes

### Your Environment
Minikube : 

```
minikube version: v1.12.1
commit: 5664228288552de9f3a446ea4f51c6f29bbdd0e0
```

Helm : 
`version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}`

Kubectl : 

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Docker : 
`Docker version 19.03.12, build 48a66213fe`

**Comment by brasseld** [comment]
graviteeio/am3 does not exist, you should use `graviteeio/am` instead.
