### ISSUE TITLE
[Kubernetes] graviteeio-apim3x-api not start because dial tcp 172.18.0.3:8083 connection refused

### ISSUE THREAD

**Issue by ThomAille** [gravitee-io/issues#4174]
### Expected Behavior
After the repo install command I should have api management deployed and operational.

### Current Behavior

![Capture d’écran 2020-08-07 à 17 46 04](https://user-images.githubusercontent.com/3932739/89663632-1ed38100-d8d6-11ea-9519-b8379efcc62e.png)

### Possible Solution
Maybe a bad configuration in the repository or in my kubernetes

### Steps to Reproduce (for bugs)
1. Launch `helm repo add graviteeio https://helm.gravitee.io`
2. Launch `helm install graviteeio-apim3x graviteeio/apim3`

### Context
I am looking to install the access management and api management suite using kubernetes

### Your Environment
Minikube : 

```
minikube version: v1.12.1
commit: 5664228288552de9f3a446ea4f51c6f29bbdd0e0
```

Helm : 
`version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}`

Kubectl : 

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Docker : 
`Docker version 19.03.12, build 48a66213fe`

**Comment by brasseld** [comment]
Hi @ThomAille 

Is this issue still relevant?

Regards,
