### ISSUE TITLE
[management] Importing theme with images fails

### ISSUE THREAD

**Issue by prutsert** [gravitee-io/issues#4179]
Gravitee APIM 3.1.2 (docker image)

Importing a theme with large images (logo and optionalLogo) in the API Management UI, fails with error: `Theme "gv-theme-1597131439680.json" exceeds the maximum authorized size (undefined)`. The theme is never posted to the API, the error is generated in the UI itself, it seems. The exported theme file is a json file of 1.3MB (yeah, I should reconsider using an animated gif for a logo). I can't find an option to increase the maximum upload size for themes in the management UI.

It is still possible to import a smaller theme file in the management ui.

It is also possible to upload the large theme to the API directly. However, during the export, the `"enabled": true` property+value are omitted, so the uploaded theme is never enabled when uploading with the API. Neither is it visible in the management-ui, so there's no way to enable it.
The APi documentation, by the way, doesn't describe this operation properly. It's called 'update_26' instead of 'Update theme': https://docs.gravitee.io/apim/3.x/management-api/3.1/#operation/update_26

Workarounds:
- Resize logo images so the exported theme is less than the authorized number (how much is that?) bytes.
- Use the API, but manual add `"enabled": true` to the exported theme, before doing so.

**Comment by phiz71** [comment]
Hi @prutsert, actually the limit for theme files is 1MB and it is hardcoded in the form. I will modify this to use the `Max size upload file` parameter that you can find in Settings menu.
![image](https://user-images.githubusercontent.com/13161768/99811485-86d86b00-2b45-11eb-8ea6-048e0bc91db5.png)

For the `"enabled": true`, it can be added in the exported file, but IMHO the import should ignore it and let the user saves and enables the imported theme. However, you could still use the API to import and enable your theme automatically.
