### ISSUE TITLE
[gateway] Enabling HTTP compression on an endpoint interferes with client-requested compression

### ISSUE THREAD

**Issue by bursauxa** [gravitee-io/issues#4185]
When HTTP compression is enabled on an endpoint, the gateway will decompress response data returned to the client. This happens even if the client requested compression, which considerably increases outgoing bandwidth.

### Expected Behavior

1. With HTTP compression enabled

Client sends request with `Accept-Encoding: gzip`
Gateway forwards request with `Accept-Encoding: gzip`
Server sends response with `Content-Encoding: gzip`
Gateway forwards response with `Content-Encoding: gzip`

Client sends request without `Accept-Encoding`
Gateway forwards request with `Accept-Encoding: gzip`
Server sends response with `Content-Encoding: gzip`
Gateway forwards response without `Content-Encoding`

2. With HTTP compression disabled

Client sends request with `Accept-Encoding: gzip`
Gateway forwards request with `Accept-Encoding: gzip`
Server sends response with `Content-Encoding: gzip`
Gateway forwards response with `Content-Encoding: gzip`

Client sends request without `Accept-Encoding`
Gateway forwards request without `Accept-Encoding`
Server sends response without `Content-Encoding`
Gateway forwards response without `Content-Encoding`

### Current Behavior (in bold, the problematic part)

1. With HTTP compression enabled

Client sends request with `Accept-Encoding: gzip`
Gateway forwards request with `Accept-Encoding: gzip`
Server sends response with `Content-Encoding: gzip`
**Gateway forwards response without `Content-Encoding`**

Client sends request without `Accept-Encoding`
Gateway forwards request with `Accept-Encoding: gzip`
Server sends response with `Content-Encoding: gzip`
Gateway forwards response without `Content-Encoding`

2. With HTTP compression disabled

Client sends request with `Accept-Encoding: gzip`
Gateway forwards request with `Accept-Encoding: gzip`
Server sends response with `Content-Encoding: gzip`
Gateway forwards response with `Content-Encoding: gzip`

Client sends request without `Accept-Encoding`
Gateway forwards request without `Accept-Encoding`
Server sends response without `Content-Encoding`
Gateway forwards response without `Content-Encoding`

### Possible Solution

When proxying a request, the gateway should not use an HTTP client with compression enabled (`options.setTryUseCompression(endpoint.getHttpClientOptions().isUseCompression());` in `AbstractConnector.java` and `HttpEndpointRuleHandler.java`) if the incoming request already contains a compression header.

### Steps to Reproduce (for bugs)

Set up an endpoint where the server supports compression and try sending a curl request to the gateway with `Accept-Encoding: gzip`

### Context

A workaround is to disable HTTP compression on all endpoints, which has two problems:
- painstaking to do as it must be done in every API, and is enabled by default
- lose the benefits of compression between gateway and server when the client requests uncompressed data

### Your Environment
1.29.5 and 3.1.2 both have this issue

**Comment by brasseld** [comment]
Hi @bursauxa 

Sorry for being late on this one.

Just to be align with all the information you provided:

Did you set this flag for the API Gateway: https://github.com/gravitee-io/gravitee-gateway/blob/master/gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml#L20

**Comment by bursauxa** [comment]
Hi @brasseld , we did not change that part of the configuration file, so lines 14 to 39 are all commented out as they are in your repository.

When I said "with HTTP compression enabled/disabled", I was referring to the endpoint-specific setting : API > Proxy > Endpoints > default-group. Sorry, that was not completely clear.

**Comment by brasseld** [comment]
Ok so can you have a try by enabling compression at the gateway (server) level ?

**Comment by bursauxa** [comment]
I'll see if I can set up an API to test this, I don't have one available right now on my dev instances due to the Gravitee 3 switch.

Note that even if it functionally works, I suspect there would be a significant performance hit from decompressing the response from the backend (due to `HttpOptions.setTryUseCompression()`) and then compressing back to the client (due to gateway-level compression). The responses we are handling on this particular endpoint range in the hundreds of megabytes, so that would be a drawback worse than the workarounds described in the original post.

**Comment by bursauxa** [comment]
Hi @brasseld 

I just performed a few tests on an instance of Gravitee 1.29.5, and my hypothesis was confirmed: enabling compression at server level makes things "work", but the CPU cost is massive (the process is at 2% when idle, ~10% when serving an uncompressed request, ~65% when serving a compressed request).

Thanks to your question, I have a better understanding of the whole chain, and will probably look at enabling that setting for some of our very legacy APIs whose backends do not support compression. However, in the case of this issue, adding a decompression-into-recompression stage in the gateway simply makes no sense when the backend is already capable of serving compressed content by itself.

**Comment by brasseld** [comment]
> Thanks to your question, I have a better understanding of the whole chain, and will probably look at enabling that setting for some of our very legacy APIs whose backends do not support compression. However, in the case of this issue, adding a decompression-into-recompression stage in the gateway simply makes no sense when the backend is already capable of serving compressed content by itself.

Totally agree.

In fact, the use-compression may have sense in multiple scenario: 
- when you are logging data, you would certainly want to see uncompressed data.
- in some case, you have to apply policies based on the response payload, in that case, if you want to parse or transform, I'm sure you understand that it is more simpler if it's based on uncompressed data :)

**Comment by bursauxa** [comment]
I see what you mean about those scenarios. It's probably better to leave things as they are to cover them properly. Instead, I would suggest renaming the "HTTP compression enabled" option to clarify its consequences.

From the client's perspective, what is being enabled is in fact **de**compression (which may then be substituted by re-compression of the response going out of the gateway). I believe something like "Enable decompression of endpoint responses by the gateway" is clearer. It also fits very well with the logging and policy scenarios you described.

**Comment by brasseld** [comment]
That makes sense. 

Keep this issue open to rename the compression field label from endpoint's configuration.
