### ISSUE TITLE
[management-ui] Provide a way to reorder policies in a plan

### ISSUE THREAD

**Issue by bursauxa** [gravitee-io/issues#4198]
In the API management UI, when editing a plan's policies, it is only possible to add policies at the end of the chain, and policies can not be reordered.

### Expected Behavior

Policies can be reordered

### Current Behavior

Policies can not be reordered and new policies are always added at the end

### Context

Sometimes policies depend on the execution of a previous policy (assign-attributes necessarily, but sometimes headers or URL rewrites as well).

The only workaround is to delete all the policies after the place where you want to perform the insertion, add the new policy, and then recreate all the policies that were just deleted.

### Your Environment

Gravitee 3.1.2

**Comment by brasseld** [comment]
Hi @bursauxa 

I know that is painful but the workaround you are describing is the only one for now.

Also, we wouldn't do anything here for a good reason. We are working on a new Policy design studio for Gravitee 3.4 and 3.5 (november~december) which would allow you to do more than you can think.

If you are interested in, we can setup a call and give you some demonstration about that one.

Sorry for not doing more on that one but unfortunately we have a new priority to handle it.

Hope you're understanding.

Cheers,

**Comment by bursauxa** [comment]
Hi @brasseld 

I understand your reasoning about this. November-december seems far away for me, so in the meantime I will look into calling the API directly by reordering the JSON array in a text editor (which is also a workaround, but not doable with the UI itself).

I am interested in a demonstration indeed, I will PM you about that. Thanks!

**Comment by bursauxa** [comment]
Fixed with Design Studio :tada:
