### ISSUE TITLE
[management-ui] Do not treat rate-limit or quota as special-case policies

### ISSUE THREAD

**Issue by bursauxa** [gravitee-io/issues#4199]
Rate-limit policies being treated as special-case policies in the UI causes issues with the policy chain's execution order.

### Current Behavior

In Gravitee 3, we can set a rate-limit policy in the normal "policies" section of API plans instead of using the dedicated "restrictions" tab (this was not possible in Gravitee 1, at least not in 1.29.5). After setting such a policy, we can save and the rate-limit policy will be executed in proper order.

The problem is, when we return to the plan later, the policy settings are displayed in the dedicated "restrictions" tab and not visible in the general "policies" section any longer. It is visually impossible to know what is the order of the rate-limit policy within the chain.

Further, if we save the plan at that point, even without making any actual changes, then the rate-limit policy will be pushed to the front of the policy chain,. This can not be solved in any way other than deleting all the policies and recreating them all each time we want to make a change (#4198 is related but would not solve this issue).

### Expected Behavior

When I set a rate-limit policy in the normal "policies" section, it stays here forever.

Probably it would be more consistent to remove the rate-limit tab in plans completely, so there are not two different ways to do the same thing, but that is not strictly required as long as the previous requirement is met.

### Context

The order of the rate-limit policy is probably irrelevant for most people, but in some cases we want to reject calls (e.g. from a specific client) and the corresponding validation policy should be executed before any rate-limit considerations happen.

More importantly, with #4128, we want to get some information from the context to define the rate-limit, and that is not possible if the rate-limit policy is executed before everything else.

### Your Environment

Gravitee 3.1.2

**Comment by brasseld** [comment]
Note: The issue is not proper to 3.x and can also be reproduced with 1.30.x

**Comment by aelamrani** [comment]
As a workaround, you can define your RL / quota on the policies screen instead of the restrictions.

**Comment by bursauxa** [comment]
> As a workaround, you can define your RL / quota on the policies screen instead of the restrictions.

Unfortunately, that is not possible, because the rate-limit policy gets pushed to the front of the policy chain even when doing that.

**Comment by aelamrani** [comment]
IMHO it should not and as far as I know there is no such rule in the gateway.

Maybe, you have a mix of `request` based policies and `request content`. And in this case the request based policies are executed first (including rate limit policy) then the `request content` based. We have here 2 policy chains.

**Comment by bursauxa** [comment]
We do not have any response-based policies so far, only request-based.

The problem is not in the gateway itself, it is the management UI that performs the reordering when we open a plan with rate-limit policy.

**Comment by aelamrani** [comment]
Sorry but I did not talked about response based policy, but anyway I understand your issue and I was just proposing a workaround not a final solution.

**Comment by bursauxa** [comment]
Sorry I meant content-based, not response based. This particular API is GET only so there will never be any content to inspect.

**Comment by aelamrani** [comment]
I just had a try with a very simple API with a keyless plan (without any restrictions or policies) and 2 policies on the design screen: Transform headers and Rate Limit.

And the order is well preserved in this simple test.

**Comment by bursauxa** [comment]
Our experience was that the order is preserved the first time, but lost when returning to the plan a second time and saving again.

**Comment by aelamrani** [comment]
Ok strange, maybe we can fix this as part of a dedicated issue? As it seems not really related to this one and sounds like a UI issue, wdyt?

**Comment by bursauxa** [comment]
Sounds good to me 👍

**Comment by bursauxa** [comment]
Fixed by upgrading to Design Studio.
