### ISSUE TITLE
[management] unable to delete the homepage background

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#4213]
I'm not able to delete a setted homepage background image.

### Steps to Reproduce (for bugs)

1. change a background image in `Theme`
2. save and enable your theme
3. click on delete
4. nothing happened

### Your Environment

* Version used: Tested in 3.1 but perhaps also in 3.0

**Comment by jhaeyaert** [comment]
A JS error appears in console when trying to delete the background image
![image](https://user-images.githubusercontent.com/5955401/95175633-0986b000-07bc-11eb-8900-0f920f417304.png)
