### ISSUE TITLE
Request validation JSON based on Swagger/Open API definition

### ISSUE THREAD

**Issue by sekman99** [gravitee-io/issues#4222]
### Expected Behavior
Feature request
Many other API platforms have support for request (and response) validation based on the Swagger/Open API definition

There should be controls as be able to control how strict the validation should be. For example, if allowing additional values not defined or strict mode. 
Some validators will convert a string with just numbers to a number format and that should be configurable also.

Example policies from other API management system:
https://docs.akana.com/ag/policies/policy_op_http_message_validation.htm

Validating in Spring:
https://springframework.guru/using-swagger-request-validator-to-validate-spring-cloud-contracts/

### Context
I am contracting with larger enterprise customers helping them with API Management and this functionality is one the biggest asked for functions to easily protect backend services.

**Comment by aelamrani** [comment]
Hi @sekman99 

We will integrate a feature based on Swagger / OAI to generate dynamically JSON validation policies while creating / updating APIs as part of the release 3.3. See https://github.com/gravitee-io/issues/issues/4293

Is that what you are looking for?
