### ISSUE TITLE
{#request.remoteAddress} is empty in SpEL evaluations

### ISSUE THREAD

**Issue by bursauxa** [gravitee-io/issues#4243]
When using `{#request.remoteAddress}` in SpEL expressions, it evaluates to an empty result. This is particularly weird because `request.getRemoteAddress()` calls in code should be strictly equivalent, but those work.

### Expected Behavior
`{#request.remoteAddress}` evaluates to the caller's IP. This follows the answer on #1816 and is also based on the `EvaluableRequest` class, even though it is not mentioned in [the docs](https://docs.gravitee.io/apim/1.x/apim_publisherguide_expression_language.html#properties_2).

### Current Behavior
`{#request.remoteAddress}` is empty when evaluated

### Steps to Reproduce (for bugs)
This can be reproduced and tested with just Gravitee and a browser:

1. set up an API, let's call it `/test-back`, set the endpoint to www.whatever.com (not important because endpoint will never be called)
2. add an IP-filtering policy to that API, with `X-Forwarded-For` checkbox enabled, and declare that the only IP allowed is `1.2.3.4`
3. call `/test-back` in your browser, you will be rejected with a message saying that [your actual IP] is not allowed
:arrow_right: this proves that the remote address is well-defined in `Request` objects as used in Java code

4. set up a second API, let's call it `/test-front`, set the endpoint to `http://localhost:8082/test-back`
5. call `/test-front` in your browser, you will be rejected with a message saying that 127.0.0.1 is not allowed, which makes sense due to the localhost call
6. now add a transform-headers policy to that API to add a `X-Forwarded-For` header on outgoing requests, with value `5.6.7.8`
7. call `/test-front` in your browser, you will be rejected with a message saying that 5.6.7.8 is not allowed
:arrow_right: this proves that the `X-Forwarded-For` header is properly taken into account when present

8. modify the transform-headers policy so the value of the `X-Forwarded-For` header is now `{#request.remoteAddress}`
9. call `/test-front` in your browser, you will be rejected with a message saying that 127.0.0.1 is not allowed
:arrow_right: this proves that the `X-Forwarded-For` header was not defined, because `{#request.remoteAddress}` evaluated to empty

### Context
We need this to properly set up the `X-Forwarded-For` header, although arguably the gateway could do it natively along with `X-Forwarded-Host` but I'm fine with doing it myself... as long as it works!

### Your Environment
Gravitee 1.29.5 and 3.1.3 both have the issue

**Comment by aelamrani** [comment]
Will be closed by https://github.com/gravitee-io/issues/issues/4431

**Comment by bursauxa** [comment]
Sorry for late reply @aelamrani but I do not see the relation between the issue here and the one you linked. Remote address is a metadata of the request itself, it is not a path parameter. Am I missing something?

**Comment by aelamrani** [comment]
No problem.

We have made some changes on this issue (refactoring) to expose the same EvaluableRequest / Response everywhere (remote address also https://github.com/gravitee-io/gravitee-gateway-api/pull/59/files#diff-1acd9f2d6bfd9867d11b68b732d81efebe1ee0912c424aa9df2f66e50ee445a3R100)

Regards,
Azize

**Comment by bursauxa** [comment]
I see, that looks good, thanks for the heads-up. Will keep you posted when we can test it 👍

**Comment by aelamrani** [comment]
Closed by https://github.com/gravitee-io/issues/issues/4431
