### ISSUE TITLE
[reporter]  Add referer to Reporter metrics

### ISSUE THREAD

**Issue by larsnaesbye** [gravitee-io/issues#4245]
The Metrics class (/gravitee-reporter-api/blob/master/src/main/java/io/gravitee/reporter/api/http/Metrics.java) does not seem to be able to gather the 'referer' request header.

This would be quite nice to know for statistics purposes, e.g. "how many are calling our APIs via a particular web site?".

**Comment by larsnaesbye** [comment]
On another note, X-Forwarded-For also comes to mind for these same reason.

**Comment by larsnaesbye** [comment]
Ah sorry - it would appear it's available through `metrics.getLog().getClientRequest().getHeaders().get("REFERER");`

**Comment by brasseld** [comment]
> Ah sorry - it would appear it's available through `metrics.getLog().getClientRequest().getHeaders().get("REFERER");`

Yeah, but in that case, you will have to enable logging on the API.

**Comment by larsnaesbye** [comment]
I think that's OK. The current in-house solution we have logs a big bunch of information from all requests so the Business Analytics folks can feast.

Example:
```
2020-07-17 16:02:40.32 USERID="669" USERNAME="KFcomeon" USER-AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36" REFERER="null" REQUESTURL="http://api-gateway.org/?servicename=RestGeokeys_v2&method=kommune&regkode=1085&login=KFcomeon&" IP="0:0:0:0:0:0:0:1" XFF="null" SUCCESS="1" SERVICEID="130" SERVICENAME="RestGeokeys_v2" SERVICETYPE="GEO" CODEPATH="" HTTPMETHOD="GET" BACKENDURL="http://random.tld/restgeokeys/resources/geokeys/kommune?regkode=1085" WORKHORSETIME="359" GATEWAYTIME="5" TOTALTIME="364" ANSWERSIZE="4132" WORKHORSE="716" SWITCHBOARD="C1709697" INFO="" CASE="" WIDTH="0" HEIGHT="0"
```

**Comment by larsnaesbye** [comment]
Wait, am I misunderstanding the architecture? Is the Reporter API for gateway logging, while the Log API is for request logging?

**Comment by brasseld** [comment]
No, everything is going through the reporter API, so both request metrics and gateway node metrics.

**Comment by larsnaesbye** [comment]
So it would in fact be a good thing to allow access to some headers through the Metrcics API?

**Comment by brasseld** [comment]
I would say that it would probably be a good thing.
The challenge here is too define what would be the relevant headers for that purpose.

**Comment by larsnaesbye** [comment]
Exactly. I see REFERER and X-Forwarded-For as the two most obvious for usage analytics, but there may be others.

**Comment by brasseld** [comment]
`X-Forwarded-For` is already represented as the `remoteAddress` in request Metrics

**Comment by brasseld** [comment]
Good point for the Referer

**Comment by larsnaesbye** [comment]
Could/should we document what the fields in the Metrics class correspond to? I had not guessed that remoteAddress was X-Forwarded-For.

**Comment by brasseld** [comment]
Good point, would be great to have a doc page about that.

**Comment by larsnaesbye** [comment]
This issue can be closed since referer is apparently in the dump of headers in the current version :-)
