### ISSUE TITLE
[portal] in Prod mode, folders in documentation can not be expanded

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#4275]
https://v3.nightly.gravitee.io/documentation/root?page=22722d1f-b2cd-449f-b22d-1fb2cda49f7f

![image](https://user-images.githubusercontent.com/13161768/92901460-ca657900-f420-11ea-9f29-aed61e4e454f.png)

No problem when running portal in dev mode.

**Comment by jhaeyaert** [comment]
Doesn't work for me in dev mode.
