### ISSUE TITLE
Helm charts - Tied too closely to ingress

### ISSUE THREAD

**Issue by DarkBlaez** [gravitee-io/issues#4278]
This is a philosophical issue versus an actual issue. The helm charts have tied their dependancies too closely to an ingress to function in a decoupled manner through exposure way with a LoadBalancer. Many have bountiful access to private net LoadBalancers to seek decoupling. Using this tight coupling to an ingress for functional success in the current helm charts is frowned upon. Something to consider going forward. As an example you the Management UI is tied to the MGMT_API_URL which is exposed in the deployment as an ENV but pulling from the ingress mapping. This is a hard tie which should be decoupled and specified in the values.yaml not assumed to come from ingress exposure.

DB

**Comment by aelamrani** [comment]
Hi @DarkBlaez 

Does it mean you would double the hosts configuration in the values.yaml?
