### ISSUE TITLE
[portal] too much space in plan menu

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#428]
because we cannot use angular material correctly, the menu has too much padding.

<img width="612" alt="capture d ecran 2017-01-29 23 41 30" src="https://cloud.githubusercontent.com/assets/1028285/22408646/9e78ea80-e67c-11e6-82b1-e748a474af63.png">

instead of

<img width="501" alt="capture d ecran 2017-01-29 23 43 19" src="https://cloud.githubusercontent.com/assets/1028285/22408662/c6a3f32e-e67c-11e6-99b0-1398408027ea.png">

see https://material.angularjs.org/latest/demo/menuBar

**Comment by brasseld** [comment]
This menu does not exist anymore starting from 1.13
