### ISSUE TITLE
[Question AM/APIM] What are the deltas

### ISSUE THREAD

**Issue by DarkBlaez** [gravitee-io/issues#4280]
When reviewing AM/APIM and what they install pertaining to the helm chart I see both install similar components. However, when installing the helm charts for both, AM does not seem to install within nginx (ingress) as one would expect. Can these both be bundled (AM/APIM) in to one helm chart as a comprehensive solution?

Also, the tie to the ingress, in this case nginx is a bit too sticky. Any decoupling or exposure through a Load Balancer for specifically API/API UI breaks since the deployment yaml specifies attributes specifically referenced within the ingress. Moving these to the values.yaml and testing for their presence is perhaps the better way to go. 

I suppose I can rewrite sections of the helm charts.

Please clarify if these two deployments AM & APIM can be condensed to a holistic set of helm charts for a comprehensive solution

Thanks
DB

**Comment by aelamrani** [comment]
Hi @DarkBlaez 

And what about people who just want to deploy only one product?
