### ISSUE TITLE
[gateway] [register] Internal Server Error (500) if an user uses the default Gravitee registration form

### ISSUE THREAD

**Issue by gianx89** [gravitee-io/issues#4284]
I'm running the **latest** version of **Gravitee AM** (3.1.2) on Docker using your docker-compose file.

I've always registered users using management api though my backend. It works fine.

**Now I'm trying to register a user using default Gravitee form**.

So I've enabled registrations, compiled and submitted the form:

![image](https://user-images.githubusercontent.com/733323/93136879-f2810080-f6dc-11ea-8c6e-4552ae833721.png)

**I always get Internal server error**. Can't find anything useful in the response or in the logs.

![image](https://user-images.githubusercontent.com/733323/93136959-0c224800-f6dd-11ea-9240-8b016b7dab51.png)

How can I solve it?

Thank you so much

**Comment by tcompiegne** [comment]
Hi @gianx89 ,

Do you have some error logs from the gateway ?

**Comment by jhaeyaert** [comment]
Hi @gianx89,

I'm able to reproduce the issue and there is indeed a little problem with **user accounts data**. Fortunately, there is a workaround you can try (before we can definitively solve the problem).

Could you try the following steps and tell me if it does the job:

First, make sure you enabled an identity provider on the application settings

![image](https://user-images.githubusercontent.com/5955401/93176403-7ebd1300-f731-11ea-9d61-c16de4b9be8e.png)

Then, go to User Accounts under the domain settings and just **enable** brut force, **save**, **disable** brute force and **save** again (this will just initialize data properly in database and will allow to get around the encountered issue).

![image](https://user-images.githubusercontent.com/5955401/93178475-99dd5200-f734-11ea-8e5d-3685009374d9.png)

Finally, try to register a new user again. It should work now.
