### ISSUE TITLE
[policy][json-validation] Integration with swagger / OpenAPI

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4293]
While creating or updating an API with a swagger / OAI, we should propose to dynamically add the payload validations on the paths according to the rules described in the descriptor.

Maybe we should refacto to add the possibility to simply add a policy in the UI. And also, handle the case when the policy has been removed from the plugins.

**Comment by akm4** [comment]
What do you think about using validating against generic swagger/openapi (not schema) using the projects like that% https://github.com/openapi4j/openapi4j ?

**Comment by aelamrani** [comment]
The purpose of this issue is to rely on the [existing policy](https://github.com/gravitee-io/gravitee-policy-json-validation) which is based on a JSON schema to validate a payload.

So basically, when you will create an API in gravitee using a swagger / OAI descriptor, you will have a new option to generate automatically these policies with a JSON schema on each path. This feature will also be proposed on update.

As far as I understand from your request, that won't change anything as the framework seems also based on JSON schema. See https://www.openapi4j.org/schema-validator.html#openapi-schema-object-validator
