### ISSUE TITLE
[management] Support for custom Swagger tags to define API's information

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4295]
For the moment, sometimes we have to build these information from the information available in the descriptor. So the idea here is to keep this default behavior and add new custom fields to provide the ability to create a finalized version of an API in one shot.
 
We should propose to configure at least important options in the swagger descriptor to handle:
- context-path
- backend endpoints
- labels
- categories
- plans?
- ...?

Maybe we should add a prefix to avoid collision with the future versions of OAI format.
See OAI extensions https://swagger.io/docs/specification/openapi-extensions/

**Comment by phiz71** [comment]
For Swagger 2.0 and OAI 3.0 versions, we can user vendor extensions. So I will add a `x-gravitee` extension at the root level.

In this extension, user will be able to configure these fields : 
- `categories` : String[]
- `contextPath` : String
- `groups` : String[]
- `labels` : String[]
- `metadata` : [ {key, value} ]
- `picture` : String
- `pictureURL` : String
- `properties` : [ {key, value} ]
- `tags` : String[]
- `visibility` : Enum (PRIVATE or PUBLIC)

**Comment by phiz71** [comment]
Here is the json schema for the extension
[openapiGraviteeExtension.txt](https://github.com/gravitee-io/issues/files/5291894/openapiGraviteeExtension.txt)

**Comment by brasseld** [comment]
IMHO, it should be better to manage `virtual-hosts` instead of `context-path`.
Plain `context-path` are deprecated now.

**Comment by phiz71** [comment]
The JSON Schema for the extension can be found here :
[openapiGraviteeExtension.txt](https://github.com/gravitee-io/issues/files/5293128/openapiGraviteeExtension.txt)

**Comment by phiz71** [comment]
this issue (#4349) in 1.30.23 will slightly change the swagger import. I will wait for backport before going further.

**Comment by phiz71** [comment]
Final JsonSchema is 
https://github.com/gravitee-io/gravitee-management-rest-api/blob/issues/%234295-Gravitee-extension-for-swagger/gravitee-rest-api-service/src/main/resources/schema/xGravitee.json
