### ISSUE TITLE
portalUI : no login pane

### ISSUE THREAD

**Issue by xavier-braive** [gravitee-io/issues#4302]
when accessing portalUI "connect" link (http://localhost:8085/user/login),
a bold title says "identifiez-vous" (login / connect), but input fields are absent.

Console shows a JS error in:
main-es2015.747c1666644e84eca75c.js:1:556488
starting with :
ERROR Error: Uncaught (in promise): S: {"headers":{"normalizedName (i don't paste the whole text to avoid overflow)

### Expected Behavior
should be a login and password fields

### Current Behavior
 login and password fields are not present.

### Possible Solution
maybe a config problem or something missing in documentation (prerequisites ?)

### Steps to Reproduce (for bugs)
browse to http://localhost:8085/user/login

### Context
trying to setup a local playground to test the solution.
I could follow and setup the "publish your first API" section.
I am stuck with "consume an API" section.

### Your Environment
windows 10 pro
zip archives downloaded from website
gravitee-standalone-distribution-3.1.3

browsers : chrome, edge, firefox (current versions)

Thank you for your help !

**Comment by aelamrani** [comment]
Hi @xavier-braive 

How are you running the portal? Do you have any problem with the console?

**Comment by xavier-braive** [comment]
Hi,
i run Portal (unzipped from zip archive), direct from console (cmd, admin mode). Not installed as service. 
No problem with console.
Portal works fine (displays API catalog), except it is not possible to login (hence to subscribe etc.)

**Comment by phiz71** [comment]
Hello @xavier-braive, 
did you configure your portal with the right `baseURL` ?
https://docs.gravitee.io/apim/3.x/apim_installguide_portal_ui_configuration.html#requirements

**Comment by xavier-braive** [comment]
Hello @phiz71 ,

thank you !

i had configured base url as gravitee_portal_api_url = http://host:port,
but had omitted to concatenate what is described in next section (/portal/environments/DEFAULT)

i had forgotten that restAPI serves both ManagementAPI and PortalAPI, so indeed it makes sense to give PortalUI full and explicit path to PortalAPI.

Thanks again for you help, have a nice day !
