### ISSUE TITLE
[portal] Access to Portal_UI from the Management_UI and the other way around

### ISSUE THREAD

**Issue by DanielBo** [gravitee-io/issues#4322]
I am trying to create an automated setup using environment variables to fully automate the setup process of whole gravitee package.

I tried the docker-compose approach outline in the docs.

`
# Download docker-compose file
$ curl -L https://raw.githubusercontent.com/gravitee-io/gravitee-docker/master/apim/3.x/docker-compose.yml -o "docker-compose.yml"

# (Optional step: pull to ensure that you are running latest images)
$ docker-compose pull

# And run...
$ docker-compose up
`

### Expected Behavior

I run the docker-compose up command and am able to access the management-ui. Once i click on the Developers Portal button in the upper left corner of the Management-ui i am redirected to http://localhost:4100. 

I found the option to reconfigure this using the management ui via "settings/settings/Portal UI" however i am unable to find an option to configure this using an environmentvariable like, for example "MGMT_API_URL" for the managementui.

### Possible Solution

As already mentioned i am looking for an option to change this configuration using the environment. I don't know if this is already possible, if so, I'd appreciate it if somebody pointed me to the proper documentation.

### Context

Trying to create a fully configurable setup that doesn't need userinteraction to be ready to use. This in the current state, would only be possible if i create a script that mimics the call of the managementui against the management API.

### Your Environment

* Version used: 3.1.2
* Environment: 
    - Docker-Compose for testing
    - Open-shift

**Comment by aelamrani** [comment]
Hi @DanielBo 

Can you have a try on the latest 3.2?

**Comment by DanielBo** [comment]
Hi again,

I have tested the latest Version 3.2 - You resolved the issue, by removing easy access from the ManagementUI to the PortalUI. That is a fix sort of ...

**Comment by aelamrani** [comment]
Hi,

We changed the default values (localhost) which are not correct most of the time.

But you can still define correct values in the Settings menu (portal URL and management URL). And if defined, you will find the links appeared and correct.

Waiting for your feedback.

**Comment by DanielBo** [comment]
Yes, but that has worked previously as well.

I am looking for an option to predefine those values as an environment variable, so i can deploy the whole application preconfigured and don't have to deal with setting it up myself.

**Comment by aelamrani** [comment]
So this is not possible for the moment as we are looking for moving some configuration from the static gravitee.yml to the database in order to prepare multi tenancy / environment.

So we will provide certainly a solution to configure all the DB settings with env var, but currently there is now way with envvar.

What about a post deploy action to update settings through the REST API?

**Comment by DanielBo** [comment]
"What about a post deploy action to update settings through the REST API?" - that came to mind when i was browsing through the code of the management api, however felt like less of a good idea due to issues of timing.

For example: When is the System up and ready to be configured? Potentially results in a race condition. - We'll have to discuss this internally, if this is a viable option, or if we are waiting for the ability to configure the DB with statics. - Which tbh shouldn't be much of an issue.

There is a "Key" Class, that contains all your defaults. - From my point of view all that needs to be done is make management_api process these Keys. And while processing check for matching values in the yml, to override the default. Or am i wrong?

**Comment by aelamrani** [comment]
Yes it is the kind of solution we will implement, with adding the environment to the syntax.

**Comment by aelamrani** [comment]
Maybe we can close this issue and open a dedicated one for this feature?

**Comment by DanielBo** [comment]
Sound good to me.

**Comment by aelamrani** [comment]
Cool thanks, waiting for this issue then!
