### ISSUE TITLE
[console] Default Endpoint Group is Selected by Index

### ISSUE THREAD

**Issue by insertmike** [gravitee-io/issues#4328]
### Summary
The Default Endpoint Group for an API is getting selected by its index. Only a dynamic routing policy can select different one.

### Expected Behavior

A default endpoint group is selected by the default name 'Default Endpoint Group' or other dedicated [documented] way. 

### Current Behavior

A default endpoint group is selected by the first index of the groups. That can lead to misbehaviour of an API as keeping track of which endpoint group is at index 0 is not a job of the API Publisher.

At the moment only a dynamic routing policy can select different groups and cope with this issue.

### Possible Solutions

- A default endpoint group is selected by the default name - if not present, index or other dedicated way.
- Possibly introducing interface to cope with default endpoint group.

### Steps to Reproduce (for bugs)

1. Create an API
2.Add an endpoint group with name `1`
3.Remove default endpoint group
4.Add an endpoint group with name `Default Endpoint Group`
5.Check which group is selected as default by calling the API.

### Your Environment

* Version used: 3.1.4

**Comment by brasseld** [comment]
To avoid misunderstanding, we should add a label / note within the first group saying that this one will be implicitely choose by the load-balancer to process requests if there are no routing rules defined.

**Comment by insertmike** [comment]
Hello, my proposal is to make the default behavior select default group by default name ( e.g "default" ) and if not present then to take first index. This will make the selection process transparent to the API gateway users and will avoid overhead with using policies just to select default group. Let me know if I have understood something wrong. Thanks!

**Comment by brasseld** [comment]
I'm not sure that defining a default group based on its name is a good idea.
I would tend to add a new boolean property, a checkbox, to choose the right default group, no matter its index in the list.

**Comment by insertmike** [comment]
That's now a design decision. Solving the issue with convention or by introducing a feature. Convention would be much more easy to introduce and maintain compared to the feature idea.
