### ISSUE TITLE
Not able to login at Portal UI - missing elements

### ISSUE THREAD

**Issue by insertmike** [gravitee-io/issues#4329]
### Summary

It's not possible to login in the Portal UI - the forms and buttons are missing at "page_box":

![image](https://user-images.githubusercontent.com/45242072/93904901-03e09300-fd03-11ea-87cd-3c139b081c2b.png)

HTML Code:
```html
<div _ngcontent-ghb-c69="" class="page__box">
      <div _ngcontent-ghb-c69="" class="page__box-title">
              <h3 _ngcontent-ghb-c69="" class="ng-star-inserted">Who are you ?</h3>
              <!---->
        </div>
       <div _ngcontent-ghb-c69="" class="page__box-footer form__actions form__actions-column"></div>
       <!----><!----><!----><!---->
</div>
```
### Steps to Reproduce (for bugs)

1. Try logging into Portal UI with gravitee version 3.1.4

### Your Environment

* Version used: 3.1.4

**Comment by aelamrani** [comment]
Hi 

Do you have errors in your console's log?
