### ISSUE TITLE
[portal] Duplicate an api to create a new version of the API

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#433]
In managing life cycle of my api, i have to create a new api for next version. And keep going with actual version

### Expected Behavior
it will be nice to have a duplicate button to create new instance of api, and just modify version and backends

### Your Environment
* Version used: 1.2.0

**Comment by NicolasGeraud** [comment]
Hi @vdelattre ,

We currently think about api versioning in Gravitee. 

What are the differences between the 2 versions of your api from a Gravitee point of view ? 
  * you want to preserve policies configuration from v1 ?
  * you want to preserve plans configurations from v1 ?
  * you want to automaticaly create a subscription to the consumers of the v1 ?
  * what do you expect in analytics ?

**Comment by vdelattre** [comment]
Hello,

For me, difference is in the context path (v1 or v2 by example)
I want to preserve policies and plans from v1
I think that keeping subscriptions is optional for me, but sometimes it can be useful.

and no particular need for analytics

**Comment by brasseld** [comment]
I really think it's not a good idea to keep subscriptions between two versions of the API.

**Comment by vdelattre** [comment]
I 'm agreed with you but may be some times it could be useful.
I think if an api has a lot of applications subscribed, it can be useful to recopy them. Maybe in pending... Or possibility to select which subsciption to copy...

**Comment by brasseld** [comment]
Ok, but in this case, it means that you have also to recreate plan from previous version....

Actually, using Gravitee.io APIM, a new version of the API is a completely new API. We are currently thinking about versioning with Gravitee.io to keep things as simple as possible so your feedback and your proposals could be really helpful !

**Comment by Frintrop** [comment]
versioning and also cloning may very useful, if you have multiple environments to manage ( quality,test,production , production-for-enterprise-A, production-for-enterprise-B, sandboxes )

**Comment by netfreeperson** [comment]
is there a sandbox plan?
