### ISSUE TITLE
[management] Import of OpenAPI/Swagger containing path definition with parentheses and url parameters failed

### ISSUE THREAD

**Issue by macwitte** [gravitee-io/issues#4336]
### Expected Behavior
The API import in the gravitee management ui should work without any issue for the attached yaml file (sample-v1.yaml) which is inside [sample-v1.zip](https://github.com/gravitee-io/issues/files/5281314/sample-v1.zip). 
The yaml file contains path definitions with parentheses and parameters which should be importable.
This is how the API looks like. Take a look at the path definition in line 21:
![editor](https://user-images.githubusercontent.com/29895533/94241182-9c019680-ff14-11ea-984c-c5cf63055c1c.png)

### Current Behavior
The import fails in the user interface with an error message shown in the attached picture
![ui](https://user-images.githubusercontent.com/29895533/94241139-8f7d3e00-ff14-11ea-8bd7-2de2052d6df2.png)

Stacktrace: rest-api:
![stacktrace](https://user-images.githubusercontent.com/29895533/94402802-ca79ae80-016c-11eb-8e63-efc9239a17e2.png)

### Possible Solution
The class io.gravitee.rest.api.service.impl.swagger.converter.api.OAIToAPIConverter (graviteeio\gravitee-management-rest-api\gravitee-rest-api-service\src\main\java\io\gravitee\rest\api\service\impl\swagger\converter\api\OAIToAPIConverter.java) contains a bug in a regular expression:

In line 93 there is  following expression: path.setPath(entry.getKey().replaceAll("\\\\{(.[^/]*)\\\\}", ":$1"));
This expression matches each parameter template in the path and does some syntax conversion on it. Unfortunately, the expression matches the outermost token, so if you have the following path:
(summandA={summandA},summandB={summandB})
then the first and the last bracket {} character of the whole path do match.

to fix this, it is required to exclude the bracket itself from the regular expression group.

The content of line 93 must be:
**path.setPath(entry.getKey().replaceAll("\\\\{(.[^/\\\\}]*)\\\\}", ":$1"));**

### Steps to Reproduce (for bugs)
1. Open Gravitee.io Management UI in browser
2. Select APIs from left Menu
3. Press (+) plus button in bottom right to add a new API
4. Select IMPORT FILE and select the attached file (sample-v1.yaml) which is inside [sample-v1.zip](https://github.com/gravitee-io/issues/files/5281314/sample-v1.zip)
5. Press IMPORT button.
6. The error message is shown in the browser window

### Context
We are currently evaluating Gravitee to use as the API Gateway for our next product line. 
The GK SOFTWARE SE is one of the leading retail companies Worldwide.
We are not able to integrate existing large Master-Data service API into Gravitee, which prevents us from using Gravitee.

### Your Environment
* Version used : 3.1.4, 3.2.0
* Browser Name and version: Firefox 79.0 (32-Bit)
* Operating System and version: Windows 10 (1809 Build 17763.1457)
* Gravitee started from command line

**Comment by cpuydebois** [comment]
We have the same problem importing an API from a swagger V2 spec file (json format) with a path like : 
```
/documents/{name}.{ext}
```
@macwitte's solution does the trick, but by modifying the `SwaggerV2ToAPIConverter` class in our case.

**Comment by macwitte** [comment]
@cpuydebois I have locally committed both source code changes. 
@brasseld I have to wait for repository push authorization.

**Comment by brasseld** [comment]
Hi @macwitte 

No nee for push authz. You just have to clone the repository, create a branch from your clone, and then create a PR to our repository.

Regards,

**Comment by leleueri** [comment]
Thanks you for your contribution !
