### ISSUE TITLE
[management-api] Closing and deletion of API in quick succession leads to unauthorized 401 error

### ISSUE THREAD

**Issue by Samaruq** [gravitee-io/issues#4338]
I noticed that if an already deleted API is recreated with the same name. A simple GET request results in:
`{"message":"Unauthorized","http_status_code":401}`

The API is deleted using a simple Python script using the REST api. In pseudocode:
```
delete_api(name) {
    api_id = get_api_id(name)
    close_api_plans(api_id)
    delete_api_pages(api_id)
    close_api(api_id)
    delete_api(api_id
}
```

### Expected Behavior
I should be able to recreate an already deleted API with the same name without having request issues.

### Current Behavior
Unauthorized message when sending a request to said recreated API. Logs do not mention this event as far as I could tell.

### Possible Solution
There are two options:
1. Restarting all pods in our `gravitee` namespace resolved the issue, this is only a temporary solution though..
2. I noticed that if I manually executed the requests instead of using the Python script, the unauthorized issue did not arise. This together with option 1, got me thinking it might be a **timing/caching** problem. And after some more testing I was able to get it to work with the Python script by adding a delay:
```diff
delete_api(name) {
    api_id = get_api_id(name)
    close_api_plans(api_id)
    delete_api_pages(api_id)
    close_api(api_id)
+    sleep(10s)
    delete_api(api_id
}
```
In essence, you need to wait a few seconds between **closing** and **deleting** an API. Ten seconds did the trick for me reliably. At five seconds, it mostly worked but not all the time.

### Steps to Reproduce (for bugs)
1. Use a script to delete an API with all steps in quick succession, **without** any delays
2. Create an API with the same name as the one you deleted.
3. Try to send a request to it. (Postman or `curl`, same result)

### Context
We use Gravitee api management in combination with our FaaS platform to manage the access to those functions.

### Your Environment
* Version used: API management 1.30.5
* Browser Name and version: n.a.
* Operating System and version: n.a.

**Comment by brasseld** [comment]
Hi @Samaruq 

Asking myself if it is not the same issue as: https://github.com/gravitee-io/issues/issues/4130

This one has been fixed as part of 3.1.4

**Comment by Samaruq** [comment]
Hi @brasseld,
Well, it sure seems the behavior described in #4130 is similar to what I am experiencing.
Unfortunately, that issue did not show up when researching the behavior I had...

This issue can be closed then.
Apologies for any inconvenience and thanks for the redirect!

**Comment by brasseld** [comment]
No worries,

Let us know if it makes sense (at least for you) to merge the fix into the next 1.30.x

**Comment by Samaruq** [comment]
This would indeed be preferred instead of migrating to 3.x, which I assume has some breaking changes? (I am not that familiar with gravitee.. yet!)

What are the longterm plans for version 1.x? Because if that version will get cycled out eventually, we should probably try to migrate to 3.x anyway?

**Comment by brasseld** [comment]
> This would indeed be preferred instead of migrating to 3.x, which I assume has some breaking changes? (I am not that familiar with gravitee.. yet!)

There is not really breaking changes. The only things to consider is to run some scripts to upgrade (only if the case of MongoDB).

> What are the longterm plans for version 1.x? Because if that version will get cycled out eventually, we should probably try to migrate to 3.x anyway?

1.x will be no longer supported around june ~ july next year.
