### ISSUE TITLE
[portal] No error when defining duplicated endpoint's name

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#436]
### Current Behavior
when i define backend, i can define new backend with existing name. No error is shown.
In list, both are shown, but when i open one, it 's always the same is opened.

In document for Expression Language, for endpoints it's written thant endpoint name have to be unique

### Your Environment
* Version used: 1.2.0

**Comment by NicolasGeraud** [comment]
hi @vdelattre , this bug will be fixed in the next release. 
Do you know how to fix data in your database ?

**Comment by vdelattre** [comment]
i renamed endpoint and it solved problem
thanks

**Comment by brasseld** [comment]
@NicolasGeraud, I think you also have to upgrade definition dependency for both gateway and rest-api.

**Comment by NicolasGeraud** [comment]
@brasseld done
