### ISSUE TITLE
Management API unreachable or error occurs

### ISSUE THREAD

**Issue by kumarjitu21** [gravitee-io/issues#4367]
I've deployed gravitee using helm in my Kubernetes cluster. 

For mongodb and elasticsearch i've deployed separately in the same namespace and used their endpoints as an arguments while creating helm-chart, but when i try to access UI it is giving **Management API unreachable** errors. 

I've checked all the containers logs, it is not showing any errors. also I've curl the API services to check the connectivity from UI as well as Portal container (curl -v http://apim-apim3-api:83/management/organizations/DEFAULT/environments/DEFAULT/apis) I'm getting OK response so looks fine there.

Now I'm not able to understand how to debug and resolve my issues. **Please help me.**

**Helm Chart Creation Command:**

Step 1: Checkout the code from: https://github.com/gravitee-io/helm-charts/tree/master/apim/3.x 
Step 2: updated portal/portal-deployment.yaml and ui/ui-deployment.yaml using below values respectively

`-` name: PORTAL_API_URL
  value: "http://apim-apim3-api:83/portal/"
  
`-` name: MGMT_API_URL
  value: "http://apim-apim3-api:83/management/"

Step 3: Modified values.yaml: https://gist.github.com/kumarjitu21/c918d8c3495b0f85ec5af4bfdafdd5df

Step 4: Installed helm using 
            $ helm install apim apim3/ -f apim3/values.yaml -n test

**$ vi elasticsearch.yaml**

`---`
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: test
  labels:
    component: elasticsearch
spec:
  type: ClusterIP
  selector:
    component: elasticsearch
  ports:
  `-` name: http
    port: 9200
    protocol: TCP
  `-` name: transport
    port: 9300
    protocol: TCP

`---`
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es
  namespace: test
  labels:
    component: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      component: elasticsearch
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      serviceAccount: elasticsearch
      containers:
      `-` name: es
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
        env:
        `-` name: discovery.type
          value: "single-node"
        ports:
        `-` containerPort: 9200
          name: http
          protocol: TCP
        `-` containerPort: 9300
          name: transport
          protocol: TCP
        resources:
          limits:
            memory: "2Gi"
            cpu: "2"
          requests:
            memory: "1Gi"
            cpu: "1"
        volumeMounts:
        `-` mountPath: /data
          name: storage
      volumes:
      `-` name: storage
        emptyDir: {}

**$ vi mongo.yaml**

`---`
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: test
  labels:
    name: mongo
spec:
  selector:
    role: mongo
  type: ClusterIP
  ports:
  `-` port: 27017
    targetPort: 27017
    protocol: TCP

`---`
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: test
spec:
  selector:
    matchLabels:
      role: mongo # has to match .spec.template.metadata.labels
  serviceName: "mongo"
  replicas: 1
  template:
    metadata:
      labels:
        role: mongo # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      `-` name: mongo
        image: mongo
        ports:
        `-` containerPort: 27017
          name: mongoport
        volumeMounts:
        `-` name: mongo-persistent-storage
          mountPath: /data/db
        resources:
          limits:
            memory: "2Gi"
            cpu: "2"
          requests:
            memory: "1Gi"
            cpu: "1"
  volumeClaimTemplates:
  `-` metadata:
      name: mongo-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi

**Comment by brasseld** [comment]
Can you provide logs for the management-api pod please ?

**Comment by kumarjitu21** [comment]
> 
> 
> Can you provide logs for the management-api pod please ?

https://gist.github.com/kumarjitu21/a80036f7b372288cbd67860496a6e26f

**Comment by kumarjitu21** [comment]
@brasseld any thought on this ?

**Comment by brasseld** [comment]
Hey @kumarjitu21 

It is your browser which is doing the call to the management-api.

So the base URL must be an URL exposed by an Ingress to access the management-api outside k8s cluster.

**Comment by kumarjitu21** [comment]
@brasseld Thanks for reply. now i could see the portal is working fine but still UI is giving the same error.

**Comment by aelamrani** [comment]
Hi @kumarjitu21 

>now i could see the portal is working fine but still UI is giving the same error.

Wdym by portal is working and UI is giving the same error? What the difference here between portal and UI? Which error you are getting?

**Comment by kumarjitu21** [comment]
> 
> 
> Hi @kumarjitu21
> 
> > now i could see the portal is working fine but still UI is giving the same error.
> 
> Wdym by portal is working and UI is giving the same error? What the difference here between portal and UI? Which error you are getting?

@aelamrani I'm using API Management 3.x which is creating portal and UI pod along with API and gateway. as described in the issues i was replacing the custom values for PORTAL_API_URL and MGMT_API_URL in portal/portal-deployemnt.yaml and ui/ui-deployment.yaml respectively. after getting @brasseld response i replaced the URL which is reachable through browser. now I'm able to get the response for portal service url which was giving "Server unavailable or connection lost" but still UI service is throwing the same error "Management API unreachable or error occurs".

**Comment by aelamrani** [comment]
This produces when your browser is not able to reach the management API (baseURL defined in the constants.json).

Please check the value is correctly defined there. Note that in 3.x version the baseURL has changed. More info here: https://docs.gravitee.io/apim/3.x/apim_installguide_migration.html#upgrade_to_3_0_0

**Comment by kumarjitu21** [comment]
@

> 
> 
> This produces when your browser is not able to reach the management API (baseURL defined in the constants.json).
> 
> Please check the value is correctly defined there. Note that in 3.x version the baseURL has changed. More info here: https://docs.gravitee.io/apim/3.x/apim_installguide_migration.html#upgrade_to_3_0_0

@aelamrani am i following the wrong helm chart as i don't have any constants.json file in that. could you please tell me where it should be ?

**Comment by aelamrani** [comment]
You are following the good one and it is about the MGMT_API_URL
