### ISSUE TITLE
Management-webui scss parsing issue

### ISSUE THREAD

**Issue by kyew4u** [gravitee-io/issues#4368]
When trying to start the webui component with the command "npm run serve" i get the following error: 

ERROR in ./src/index.scss 1:18
Module parse failed: Unexpected character '#' (1:18)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> $backgroundColor: #fdfdfd;
|
| @import '~angular-gridster/dist/angular-gridster.css';
 @ ./src/index.ts 20:0-23

My first thought is that the error is due to Windows-build-tools, as stated in the according readme-file. I installed the module, but the error still persists. Maybe something about my installation is wrong or it could be something else, that i couldn't find out.

### Expected Behavior
I expected the script to run and work without errors. Since any other configurations weren't neccessary.

### Current Behavior
The bug 

### Possible Solution
I don't really have any clue how to resolve that.

### Steps to Reproduce (for bugs)
1. download the management-webui from: https://github.com/gravitee-io/gravitee-management-webui/tree/3.2.x
2. npm install on the module 
3. npm install --global --production windows-build-tools 
4. restart pc
5. npm install

### Context
I am currently trying to setup a development environment (in eclipse). The gateway and rest api are already working but with the webui i continue to have the issue.

### Your Environment

* Version used: 3.2
* Browser Name and version: opera GX
* Operating System and version: Windows 10 Enterprise, 1909
My PC is owned by the Company i work for so i don't have unlimited rights.

**Comment by aelamrani** [comment]
Seems to be the same kind of problem than in the issue https://github.com/gravitee-io/issues/issues/1512

@kyew4u are you able to try the fix proposed there?
