### ISSUE TITLE
Error on TransFormHeader policy

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#437]
I added policy transformheader:
name=X-Process-App
value={#context['application']}

In log, i have this error:
org.springframework.expression.spel.SpelEvaluationException: EL1027E:(pos 8): Indexing into type 'io.gravitee.gateway.reactor.handler.el.EvaluableExecutionContext' is not supported
        at org.springframework.expression.spel.ast.Indexer$PropertyIndexingValueRef.getValue(Indexer.java:576)
        at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:88)
        at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:131)
        at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:299)
        at io.gravitee.gateway.el.SpelTemplateEngine.convert(SpelTemplateEngine.java:39)
        at io.gravitee.policy.transformheaders.TransformHeadersPolicy.lambda$transform$0(TransformHeadersPolicy.java:73)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
   

But call is OK, just i don't have my new header param.
If i put  {#request.id}  in value, no error, and param header is added

is it good syntax for context ? i take it in doc page

### Your Environment
* Version used: 1.2.0

**Comment by brasseld** [comment]
Hum,

I think there is a typo on the documentation. Can you have a try with:
`{#context.attributes['application']}`

And let us know.

Thanks !

**Comment by vdelattre** [comment]
OK it's better like that.
but application and plan attribute return id.
How to get label?

**Comment by brasseld** [comment]
Actually, there is no way to retrieve application or plan name.

Why do you need this attribute ? You can still get the information using the management API, no ?

**Comment by vdelattre** [comment]
In my update api, i want to store user and application who called api.
I have header param: X-Process-App and X-Process-User
In term, informations should take in OAuth. Now, i keep only application in gravitee

**Comment by brasseld** [comment]
The problem with your solution is that the application name can be subject to changes.
By storing only the application identifier, you are certain that it is always the same application.

In a (near :wink: ) future, if you talk about OAuth, you will be able to get the user-id and the clientId from token introspection and push them to your backend by using HTTP headers.

**Comment by brasseld** [comment]
Documentation has been fixed: https://docs.gravitee.io/apim_publisherguide_expression_language.html

Thanks for your contribution.

**Comment by vdelattre** [comment]
You're right but problem with id is that it's technical id and known only by gravitee....

**Comment by brasseld** [comment]
And it's the only way to be sure that we are always talking about the same application... 

When you get this information from your backend, what are you doing with it ?

**Comment by vdelattre** [comment]
For now, these informations are stored in metadata block.
Aim is by example to show in GUI who send or update informations

**Comment by brasseld** [comment]
Ok I understand but, in your previous message, you were mentioning OAuth.
And even with OAuth, you will not being able to get these kind of information and you will be limited to user_id and client_id which are technical identifiers...

**Comment by vdelattre** [comment]
OK i didn't know that.
By the way, i think that this functionnlity (get name) could be usefull.

Thanks for your help ;)

**Comment by brasseld** [comment]
Ok, I'm closing this issue because the initial problem has been resolved.

Feel free to create a new ticket for the second one.
