### ISSUE TITLE
[management] Alert's template must be considered as enabled

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#4374]

**Comment by aelamrani** [comment]
Not fixed, here the step to reproduce:

1 - I create a new alert and I check "Enable this alert"
2 - I check "Define as template" and I finalize the creation
3 - I create a new alert without checking "Enable this alert"
4 - I check "Define as template" and I finalize the creation
5 - The list displays the 2 templates, the first in blue, the other in gray
