### ISSUE TITLE
[docker] Update to newer AdoptJDK in Docker image

### ISSUE THREAD

**Issue by larsnaesbye** [gravitee-io/issues#4375]
There's a newer AdoptJDK base image (11.0.8)

Linked to https://github.com/gravitee-io/gravitee-management-rest-api/pull/1191
Linked to https://github.com/gravitee-io/gravitee-gateway/pull/587

**Comment by brasseld** [comment]
May I ask you to do the same for the management-api ?

Thanks a lot,

**Comment by larsnaesbye** [comment]
Sure. It's here: https://github.com/gravitee-io/gravitee-management-rest-api/pull/1191

**Comment by brasseld** [comment]
👍

**Comment by larsnaesbye** [comment]
Any chance it makes its way into the 3.3.0 images? Because if not, then I will just update the PR when 11.0.9 gets released on October 20 :-)

**Comment by leleueri** [comment]
Thanks you for your contribution ;)
