### ISSUE TITLE
[portal] Align EN translations for rating

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4388]
https://github.com/gravitee-io/gravitee-portal-webui/blob/11893aa2e98b91ee0d5140c185490b2b3d40d751/src/assets/i18n/en.json#L42

Response / Answer => Answer
Opinion / Review / Advice => Review

**Comment by tcompiegne** [comment]
Fixed by https://github.com/gravitee-io/issues/issues/4383
