### ISSUE TITLE
[portal] Suggestion: repo for themes

### ISSUE THREAD

**Issue by larsnaesbye** [gravitee-io/issues#4393]
Just a thought, maybe a crazy one: what about a gravitee-io/portal-themes repository so we can have more themes to choose from ?

**Comment by aelamrani** [comment]
Interesting one, we already had some discussions about allowing to provide a set of themes.

**Comment by larsnaesbye** [comment]
It would be a good showcase of the customization possibilities if there were 2-3 different themes to choose from. And maybe the community can provide them :)
