### ISSUE TITLE
Missing mapping for orgId and envId in swagger definition generated for management Rest-API

### ISSUE THREAD

**Issue by Andy2003** [gravitee-io/issues#4394]
The swagger definition generated by the management-api is invalid. The following errors exists:

* defined paths are not accessible for:
  * `/notifiers`
  * `/notifiers/{notifier}/schema`
  * `/notifiers/{notifier}`
* missing path params for `orgId` and `envId`
* `MembershipListItem` has 2 different class representations in java but only one in the swagger definition

**Comment by Andy2003** [comment]
@aelamrani the generated swagger doc is still invalid b/c of the highly customized `ObjectMapper`. So for example the generated definition of `ApiEntity` is:

```yaml
  ApiEntity:
    type: "object"
    required:
      - "proxy"
    properties:
      id:
        type: "string"
        example: "00f8c9e7-78fc-4907-b8c9-e778fc790750"
        description: "API's uuid."
      paths:
        type: "object"
        description: "a map where you can associate a path to a configuration (the\
          \ policies configuration)"
        additionalProperties:
          $ref: "#/definitions/Path"
### many other properties
```

and Path:

```yaml
  Path:
    type: "object"
    properties:
      path:
        type: "string"
      rules:
        type: "array"
        items:
          $ref: "#/definitions/Rule"
```

But when I query `GET /organizations/{orgId}/environments/{envId}/apis/{api}`, The following will be returned:

```json
{
  "id": "123",
  "paths": {
    "/xxx": [
      {
        "methods": [
          "POST"
        ],
        "dynamic-routing": {
          "rules": [
            {
              "pattern": "/xxx",
              "url": "/yyy"
            }
          ]
        },
        "enabled": true
      }
    ]
  }
 // many other properties
}
```

This does not match the spec, since the paths values are expected to be object and not array.
As a result the generated swagger java-client (`jersey2`) throws an `APIExceptions` since jackson is not able to serialize the array to object.

**Comment by Andy2003** [comment]
As I understood so far, the reason for customizing the 'ObjectMapper' is to support different versions of the Gravitees' management API, is that correct?

**Comment by aelamrani** [comment]
Yes mainly for this.

**Comment by Andy2003** [comment]
I would suggest to write a model for each version as a maven artifact. Something like `gravitee-rest-api-model-v1`, `gravitee-rest-api-model-v2` and so on, each with its own versioned package.
Then we can import all supported models in parallel and use a mapping framework like [mapstruct](https://mapstruct.org/) to map each version to the current internal representation.
So we can:
* Get rid of the customizations of the object mapper
* Provide a valid swagger definition for all endpoints
* Make things more explicit in terms of  where things happen. Currently it's hard to understand where e.g. `plans` get serialized. It took me quite a while until I found the `ApiSerializer`

Please tell me what do you think about this idea.

**Comment by aelamrani** [comment]
Sounds good, I just need to check the others reasons we did it like this. But yes that is sure we need to make things clearer and split things.

**Comment by aelamrani** [comment]
Maybe we can track this on a dedicated issue?

**Comment by phiz71** [comment]
PR merged.
Thanks you @Andy2003  !

**Comment by Andy2003** [comment]
@phiz71 @aelamrani 
There is still work to do for the 3.1. and 3.2 branch.
Thare are stale merge branches for [3.1 ](https://github.com/Andy2003/gravitee-management-rest-api/tree/bugfix/missing-params-in-swagger-definition_3.1) and [3.2](https://github.com/Andy2003/gravitee-management-rest-api/tree/bugfix/missing-params-in-swagger-definition_3.2) in my repo. Please tell me when I should rebase these branches
