### ISSUE TITLE
[management] import of an existing api fail since 3.2

### ISSUE THREAD

**Issue by YoranSys** [gravitee-io/issues#4397]
### Current Behavior

Can't update an API from WebUI and with API call. 
On the swagger of management API we can see that the verb change from POST(v3.1) to PUT (v3.2).
However, none of his two verbs work.

* https://docs.gravitee.io/apim/3.x/management-api/3.1/#operation/updateWithDefinition
* https://docs.gravitee.io/apim/3.x/management-api/3.2/#operation/updateWithDefinition

### Steps to Reproduce (for bugs)

1. Export an API
2. Import the json
3. You will see an error "405 Method Not Allowed"

> http call  **POST**  **/apis/UUID/import**

### Your Environment
* Version used: 3.2.1

**Note:** the problem is absent on 3.3 nightly

**Comment by aelamrani** [comment]
Since 3.0.8 and 3.2.1 actually.

We have to insure the retro compatibility.
