### ISSUE TITLE
[management] add HTTP proxy configuration for the OAuth2AuthenticationResource

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#4398]
The HTTP client used to exchange an OAuth 2 code for a Access Token does not use the following common configuration : 

```
# global configuration of the http client
httpClient:
timeout: 10000 # in milliseconds
proxy:
type: HTTP #HTTP, SOCK4, SOCK5
http:
host: # host
port: # port
https:
host: # host
port: # port
```

**Comment by jhaeyaert** [comment]
See also #4728

**Comment by brasseld** [comment]
@leleueri what's the reason for `changes required` status ?

**Comment by leleueri** [comment]
@brasseld According to my tests, SOCKS5 proxy using login/pwd doesn't work.

**Comment by leleueri** [comment]
I have just updated the PR to handle the SOCK authentication case.
