### ISSUE TITLE
[management] As standard user i see an administration link on portal UI

### ISSUE THREAD

**Issue by YoranSys** [gravitee-io/issues#4399]
### Expected Behavior

As standard users the administration link and access to the old user interface is confusing. 
Can we disable the visibility of this link for non API-PUBLISHER and admin users?

![image](https://user-images.githubusercontent.com/11197007/95316574-4e7e1580-0894-11eb-90fe-d7d07b1d78f6.png)

**Comment by aelamrani** [comment]
Hi @YoranSys 

By default a simple USER have no access to this link.

If this user has at least a role (with writer permissions) defined on at least an API, he will get this link in the menu as he should be able to access to it to perform modifications.

So I suppose your user has some rights on at least an API?

**Comment by YoranSys** [comment]
Hi @aelamrani 

There is my user attributs : 

![image](https://user-images.githubusercontent.com/11197007/95328503-ed5f3d80-08a5-11eb-81a5-f7185c00be1c.png)
-----------------------------------
![image](https://user-images.githubusercontent.com/11197007/95328973-8c843500-08a6-11eb-9f33-032038083eb2.png)
![image](https://user-images.githubusercontent.com/11197007/95329001-96a63380-08a6-11eb-9cb1-68129737c40e.png)

## And the group config: 

![image](https://user-images.githubusercontent.com/11197007/95328656-28617100-08a6-11eb-87dd-f96fa89de43a.png)

![image](https://user-images.githubusercontent.com/11197007/95328717-4038f500-08a6-11eb-9ce1-e49e36e37f33.png)

![image](https://user-images.githubusercontent.com/11197007/95328792-4dee7a80-08a6-11eb-9529-ad9daaafdc4c.png)

![image](https://user-images.githubusercontent.com/11197007/95328876-69598580-08a6-11eb-80d6-302953199679.png)

**Comment by aelamrani** [comment]
Alright, I am able to reproduce on master branch.
