### ISSUE TITLE
[Swagger] Error in swagger Management API some array items type

### ISSUE THREAD

**Issue by GGui** [gravitee-io/issues#4405]
In swagger file of Management API, the format for some array like "tags", "categories", "groups" are not correct.

In the current swagger file, you have:
"tags": {
                    "type": "array",
                    "example": "public, private",
                    "description": "the list of sharding tags associated with this API.",
                    "items": {
                        **"type": "object"**
                    }
                }

The correct format should be:
"tags": {
                    "type": "array",
                    "example": "public, private",
                    "description": "the list of sharding tags associated with this API.",
                    "items": {
                        **"type": "string"**
                    }
                }

**Comment by aelamrani** [comment]
See also https://github.com/gravitee-io/issues/issues/4406

**Comment by GGui** [comment]
error is still there in the swagger of version 3.3
https://docs.gravitee.io/apim/3.x/management-api/3.3/swagger.json

**Comment by aelamrani** [comment]
Not yet merged from the 1.30.x...

**Comment by aelamrani** [comment]
Not yet merged from the 1.30.x...

**Comment by GGui** [comment]
Oh sorry, i thought the fix has been applied in version 3.3. I probably have to wear glasses
It has been applied in version 1.30.24, right?

In the page of apim doc (https://docs.gravitee.io/apim/1.x/apim_installguide_management_api_documentation.html), the swagger is still linked to the version 1.30.15

**Comment by aelamrani** [comment]
You are right, just updated it!
