### ISSUE TITLE
[Swagger] Error in swagger Management API for "paths" object

### ISSUE THREAD

**Issue by GGui** [gravitee-io/issues#4406]
In swagger file of Management API, the format for "paths" object is not correct.

In the current swagger file, you have:
"paths": {
                    "type": "object",
                    "description": "a map where you can associate a path to a configuration (the policies configuration)",
                    "additionalProperties": {
                        **"$ref": "#/definitions/Path"**
                    }
                },

The correct format should be:

"paths": {
            "type": "object",
            "additionalProperties": {
              **"type": "array",
              "items": {
                "$ref": "#/components/schemas/Path"**
              }
            },

**Comment by aelamrani** [comment]
Closing this one as it will be fixed by https://github.com/gravitee-io/issues/issues/4405

**Comment by leleueri** [comment]
Hi,

Since the swagger.json uses the version 2.0 of the specification, the generated value you mentioned is correct.
Here is the java code: 
```

    @ApiModelProperty(
            value = "a map where you can associate a path to a configuration (the policies configuration)")
    private Map<String, Path> paths = new HashMap<>();

```
In this case, we want an object with additional properties of type "Path".
So the following value is correct (map of Path with a reference to the path definition that follows the v2.0 of the specification)

```
"paths": {
"type": "object",
"description": "a map where you can associate a path to a configuration (the policies configuration)",
"additionalProperties": {
"$ref": "#/definitions/Path"
}
}
```

**Comment by GGui** [comment]
Hi Eric,

You're right. I made a mistake but i think the schema does not match with API object.

ex:
```
"paths" : {
    "/" : [ {
      "methods" : [ "CONNECT", "DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT", "TRACE" ],
      "cache" : {"timeToLiveSeconds":600,"useResponseCacheHeaders":false,"scope":"APPLICATION"},
      "description" : "Description of the Cache Gravitee Policy",
      "enabled" : true
    }, {
      "methods" : [ "CONNECT", "DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT", "TRACE" ],
      "ip-filtering" : {"matchAllFromXForwardedFor":false,"whitelistIps":[],"blacklistIps":[]},
      "description" : "Filter IPs from remote address or X-Forwarded-For header with blacklist or whitelist",
      "enabled" : true
    }, {
      "methods" : [ "CONNECT", "DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT", "TRACE" ],
      "html-json" : {"selectors":[]},
      "description" : "The HTML to JSON Transformation Gravitee Policy allows to get a json by parsing an html content",
      "enabled" : true
    }, {
      "methods" : [ "CONNECT", "DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT", "TRACE" ],
      "key-less" : {},
      "description" : "Description of the Keyless Security Gravitee Policy",
      "enabled" : true
    } ]
  },
```

It's look like a map with key=path and value=list of Rule, isn't it?

"Path" is an object and not an array, it defines like this:

```
"Path": {
        "type": "object",
        "properties": {
          "path": {
            "type": "string"
          },
          "rules": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Rule"
            }
          }
        }
      }
```

I based on "UpdateApiEntity" to validate API config object. It may not be the right object

**Comment by leleueri** [comment]
Hi,

Your are right, I was focused on the swagger definition based on the UpdateApiEntity bean, but indeed there are a jackson mapper that translate the array to a map.

Thank you for highlighting that point.

I will fix it.

**Comment by leleueri** [comment]
OK, PR for #4405 updated to fix this one.
