### ISSUE TITLE
[management] Management-API does not accept uppercase ENUM tokens

### ISSUE THREAD

**Issue by insertmike** [gravitee-io/issues#4413]
### Summary
The management-api does not return enum tokens as uppercase but accepts them.

### Expected Behavior
The `status` enum token in the response body of management-api is lowercase. For example for subscription status:
```
{
   response:status = "accepted"
}
```
### Current Behavior
The `status` enum token in the response body of management-api is lowercase
```
{
   response:status = "ACCEPTED"
}
```

### Possible Solution
- Be consistent on how enum tokens are accepted. Allow uppercase and possibly deprecate lowercase.

### Steps to Reproduce (for bugs)

- Add a subscription to a plan.
- Get subscription and check status is lowercase.

### Your Environment

Version used: 3.1.4

**Comment by aelamrani** [comment]
Hi @insertmike 

Not sure I get you. You are pointing a path (/_close => post action to close a plan) and you are talking about ENUMs, so maybe you can point us to some code or documentation to understand what do you want us to change?

Thanks

**Comment by insertmike** [comment]
Hello @aelamrani,

I have updated the context of the issue. Now it has more appropriate information regarding the issue. 

Thanks

**Comment by insertmike** [comment]
This example in the issue is valid for all other :state variables too.

**Comment by aelamrani** [comment]
OK thanks now I got you, we will check this.

**Comment by leleueri** [comment]
Hi,

Your are right enum are returned in an inconsistent way.

For example:
* in subscription bean the status is in lower case into response bodies but when specify in query parameter for the portal api only upper case is authorized. (it is ok in management api)
* Application status is UpperCase in response body
* ...

We delay the resolution of this issue to avoid the introduction of regressions in a maintenance release.
