### ISSUE TITLE
[gateway] fail if dynamic routing is not found

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#442]
when we use dynamic routing  and want to select an endpoint, if this selection failed, the gateway does not return an error an select an endpoint. I think It could be useful to allow users to choose the gateway behavior in this case : return an error (502 or 503) or use loadbalancing to select an endpoint

**Comment by brasseld** [comment]
Duplicate of https://github.com/gravitee-io/issues/issues/1515
