### ISSUE TITLE
Is there any idempotency control in APIGW ? 

### ISSUE THREAD

**Issue by aliFetvaci61** [gravitee-io/issues#4421]
Is there any idempotency control in APIGW ?

**Comment by aelamrani** [comment]
Hi @aliFetvaci61 

What do you mean by `idempotency control in APIGW`?

**Comment by aliFetvaci61** [comment]
The API supports idempotency for safely retrying requests without accidentally performing the same operation twice. This is useful when an API call is disrupted in transit and you do not receive a response. For example, if a request to create a charge does not respond due to a network connection error, you can retry the request with the same idempotency key to guarantee that no more than one charge is created.

https://stripe.com/docs/api/idempotent_requests @aelamrani

**Comment by aelamrani** [comment]
Quite interesting, did not know about this. 

So no, for the moment we do not have such support about generation of this kind of header based on the request elements.

 Why not base this id on the `X-Gravitee-Transaction-Id`? It means that the consumer have to retry in the same "transaction".
