### ISSUE TITLE
API consume user creation with multiple API endpoints

### ISSUE THREAD

**Issue by mmanoj** [gravitee-io/issues#4429]
How to create a user in Gravitee and assign multiple APIs to that user with a single API key
However, we notice the email not sending as expected.
Ref Guide:
https://docs.gravitee.io/apim/3.x/apim_adminguide_users_and_groups.html

### Expected Behavior
Send email from Gravitee to the mentioned email address

### Current Behavior
email is not sent to the user to complete the profile section

### Steps to Reproduce (for bugs)
Same as the guide.

### Context
We required to create the API consumer user as explain in the above summary section and assign multiple API endpoints to him with a single API key to the consume the API. Please let us know any workaround to do it if the email feature not working.So we can create users & API key manually and assign it to the required API endpoints.

### Your Environment
We use docker-compose 3.x version

**Comment by aelamrani** [comment]
Hi @mmanoj 

So as far as I understand, multiple requests here: 

1. "How to create a user in Gravitee"

You can enable self registration or as an administrator create a user.
See https://docs.gravitee.io/apim/3.x/apim_adminguide_users_and_groups.html

2. "assign multiple APIs to that user with a single API key"

Not possible for the moment, seems related to this issue: https://github.com/gravitee-io/issues/issues/2213

3. "However, we notice the email not sending as expected"

You have to configure your SMTP server to be able to send emails.
See https://docs.gravitee.io/apim/3.x/apim_installguide_rest_apis_configuration.html#sending_emails

**Comment by mmanoj** [comment]
@aelamrani 

Thanks for the quick reply, Point #2 noted. Will check the SMTP configuration and update you ASAP.

**Comment by aelamrani** [comment]
Ok, waiting for your feedback then.

**Comment by mmanoj** [comment]
[1:19 PM, 10/12/2020] Sauthith TSD: management_api:
    image: graviteeio/apim-management-api:${APIM_VERSION:-3}
    container_name: gio_apim_management_api
    restart: always
    ports:
      - "8083:8083"
    links:
      - mongodb
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    volumes:
      - ./logs/apim-management-api:/opt/graviteeio-management-api/logs
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_analytics_elasticsearch_endpoints_0=http://elasticsearch:9200
      - TZ=Asia/Colombo
      - gravitee_email_enabled=true
      - gravitee_email_host=smtp.gmail.com
      - gravitee_email_port=587
      - gravitee_email_from=myem…
[1:19 PM, 10/12/2020] Sauthith TSD: this is in docker-compose file
[1:20 PM, 10/12/2020] Sauthith TSD: suggested by @brasseld
