### ISSUE TITLE
Can not create custom healthceck

### ISSUE THREAD

**Issue by Frintrop** [gravitee-io/issues#443]
While trying to define a custom healthcheck for an api,  timeunit combobox and http method combobox would show the right items, but we can no select any of them. 

There custom healthcheck is not configurable. Tried with ie,firefox and chrome.

Did we forget something or is there a workaroud via direct api calls ?

![image](https://cloud.githubusercontent.com/assets/6286770/22865445/0b12c574-f165-11e6-8ae4-53ccf095c4bc.png)

**Comment by NicolasGeraud** [comment]
Indeed, this is a bug.

the bug is in the UI, the value you select is not shown but if you fill the form, save it and loog into your devtools, you can see that the value you select is sent to the server.

**Comment by NicolasGeraud** [comment]
this is already fixed in the next release
https://github.com/gravitee-io/gravitee-management-webui/pull/318/commits/d7a28462ea7b00f8f5895056d70e34b93fdc095e#diff-189be665b539c7a9ce5291722270e123R122

Final release is scheduled to tuesday.

I close this issue

**Comment by NicolasGeraud** [comment]
hi @Frintrop we have shipped Gravitee.io v1.3.0 including this fix.
