### ISSUE TITLE
[gateway] Support for path-named parameters in Expression Language (EL)

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4431]
Currently, an API publisher is able to define path named params in the policy design screen.

The goal here is to be able to use these parameters at the runtime level using [EL](https://docs.gravitee.io/apim/3.x/apim_publisherguide_expression_language.html).

Example:

Given this path:

```
/products/:productId
```

We should be able with the following expression to get 123 for this call: `/products/123`

```
#request.pathParams['productId']}
```

**Comment by ytvnr** [comment]
juste a suggestion on https://github.com/gravitee-io/gravitee-gateway/pull/589
but looks good to me
