### ISSUE TITLE
[policy] [api-key] Customize api-key header

### ISSUE THREAD

**Issue by Frintrop** [gravitee-io/issues#444]
Is it possible to rename api key header X-Gravitee-Api-Key like X-Gravitee-Transaction-ID header?

**Comment by NicolasGeraud** [comment]
No,

but this could be a useful feature.

**Comment by Frintrop** [comment]
Yes. While migration from another thirdparty api management solution and keep all clients unchanged...!

**Comment by NicolasGeraud** [comment]
This is what you want to test with Gravitee.io ?

Please let us know, there 's a company behind Gravitee.io (https://graviteesource.com/) that could provide professional support.

**Comment by Frintrop** [comment]
Many thx. We have clients using X-API-KEY header now. if we can define our gravitee header ourself we don´t need to rewrite it with mod_rewrite ...

**Comment by Frintrop** [comment]
Maybe there is a workaround with transform-header-policy ?

**Comment by brasseld** [comment]
Unfortunately, there is no workaround using transform-header policy.

The reason for this is simple: when handling a request, three policy chains are executed:
1) Security policy chain : security
2) Plan policy chain : policies relative to the plan itself : rate-limit / quota, resource filtering, ...
3) API policy chain : policies you are managing through the UI.

So, for sure, we have to implement a new feature to:
1) Set a custom `X-Api-Key` header for all the APIs
2) Be able to customize the `X-Api-Key` header on a per-api or per-plan basis.

**Comment by brasseld** [comment]
This PR allows to set a custom Api key header / query parameter for all APIs / plans.
