### ISSUE TITLE
[management] Allows to restore an archived application

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4453]
It can be useful to restore an application archived previously (by inattention / error) and its subscriptions.

Regarding the memberships and the notifications config, they will be lost (a note will be added to the archiving) and when the application (and subscriptions) is restored, the new Primary Owner will be the one that will have done the action.

**Acceptance Criteria:**
As a user with the role ADMIN, I should be able to restore an archived application

Given I have restored an  archived application 
And the application had **memberships**
Then I can not restore the membership

Given I have restored an  archived application 
And the application had a **notification config**
Then I can not restore the notification config.

Given a user has restored an application
Then the user will be the primary owner of the restored application 

Given an application that is archived
Then every operation in the APIM API on this application, except restoration, should return a 404 HTTP error.

Given an application that is archived
And the user is not ADMIN
When the user calls [management-api]/organization/{orgId}/environments/{envId}/applications/{appId}/_restore
Then the APIM API should return a 403 HTTP Error

Given an application that is not archived
And the user is not ADMIN
When the user calls [management-api]/organization/{orgId}/environments/{envId}/applications/{appId}/_restore
Then the APIM API should return a 403 HTTP Error

Given an application that is archived
And the user is ADMIN
When the user calls [management-api]/organization/{orgId}/environments/{envId}/applications/{appId}/_restore
Then the APIM API should do the restoration

Given an application that is not archived
And the user is ADMIN
When the user calls [management-api]/organization/{orgId}/environments/{envId}/applications/{appId}/_restore
Then the APIM API should return a 400 HTTP Error

Given a user who is ADMIN
When the user calls [management-api]/organization/{orgId}/environments/{envId}/applications?status=ARCHIVED
Then the APIM API should return the list of ARCHIVED applications sorted by closed date descending

Given a user who is not ADMIN
When the user calls [management-api]/organization/{orgId}/environments/{envId}/applications?status=ARCHIVED
Then the APIM API should return a 403 HTTP Error

Given a user who is ADMIN
When the user goes to the applications list page in APIM Console
Then it should be able to switch between active and archived applications
And archived applications can't be clicked to see any detail
And a button is available to restore the application

**Edit 2021-04-02**
When the USER click on RESTORE button
- a message is displayed to inform him that all the subscriptions will be restored, and that he have to validate them manually.
- the user is redirected to the subscriptions page of the application

**Comment by patelami** [comment]
This feature is not currently ready to test on nightly.

**Comment by patelami** [comment]
As a user with the role ADMIN, I should be able to restore an archived application **PASS**

Given I have restored an  archived application 
And the application had **memberships**
Then I can not restore the membership **PASS**

Given I have restored an  archived application 
And the application had a **notification config**
Then I can not restore the notification config. **PASS**

Given a user has restored an application
Then the user will be the primary owner of the restored application **PASS**

Given a non-admin user can not see the archive application tab **PASS**

Given an application that is archived
Then every operation in the APIM API on this application, except restoration, should return a 404 HTTP error. **PASS**

Given an application that is archived
And the user is not ADMIN
When the user calls [management-api]/organization/{orgId}/environments/{envId}/applications/{appId}/_restore
Then the APIM API should return a 403 HTTP Error **PASS**

Given an application that is not archived
And the user is not ADMIN
When the user calls [management-api]/organization/{orgId}/environments/{envId}/applications/{appId}/_restore
Then the APIM API should return a 403 HTTP Error 
**PASS**

Given an application that is archived
And the user is ADMIN
When the user calls [management-api]/organization/{orgId}/environments/{envId}/applications/{appId}/_restore
Then the APIM API should do the restoration
**PASS**

Given an application that is not archived
And the user is ADMIN
When the user calls [management-api]/organization/{orgId}/environments/{envId}/applications/{appId}/_restore
Then the APIM API should return a 400 HTTP Error **PASS**


```
Given a user who is ADMIN
When the user calls [management-api]/organization/{orgId}/environments/{envId}/applications?status=ARCHIVED
Then the APIM API should return the list of ARCHIVED applications sorted by closed date descending

current result:
The order does not match with what we have in APIs console
```

```
Given a user who is not ADMIN
When the user calls [management-api]/organization/{orgId}/environments/{envId}/applications?status=ARCHIVED
Then the APIM API should return a 403 HTTP Error 

current result:
I am getting empty array[] and not 403 HTTP Error

```

Given a user who is ADMIN
When the user goes to the applications list page in APIM Console
Then it should be able to switch between active and archived applications
And archived applications can't be clicked to see any detail
And a button is available to restore the application PASS
