### ISSUE TITLE
[gateway] Platform policies

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4460]
The goal is to create policies (ratelimit, ipfiltering...) at the platform level (for a specific sharding tag), to be executed for any APIs instead of having to duplicate the same configuration for each of the APIs.

**Console:**
Add a policies entry in the organization settings menu (under Gateway).
This studio will be used to edit tags and platform flows.

![image](https://user-images.githubusercontent.com/13161768/120777025-262edf80-c525-11eb-949a-0c72dc599149.png)

We should not be able to create any resource or configuration. So we should make policies that use resource unusable.

Definitions of flows should be stored in a specific “Flows” collection. This collection should be generic enough to maybe add plan and API flows one day.

Alert API Publisher in the API design studio that a platform configuration exists. When the API publisher clicks on the yellow banner to deploy its API, a warning message is displayed in the confirmation window if platform policies are defined.
This message is:
Some policies are defined on the platform and may conflict with your design. Contact your administrator for more information.

When saving platform policies, the user is asked for a confirmation. Once he has accepted, the policies must be deployed to gateways.

**Gateway:**
Load accurate flows at startup and apply them before API policies on each call.
Load policies configuration on deployment event.
Execute request policies before API policies and response policies after.

**Comment by patelami** [comment]
Env: nightly
@gcusnieux 
cc: @phiz71 

We should not be able to create any resource or configuration. So we should make policies that use resource unusable. FAIL - We are still seeing the oAuth2 policy on the platform level

Definitions of flows should be stored in a specific “Flows” collection. This collection should be generic enough to maybe add plan and API flows one day: Not working as expected. 

Add links in the sharding tags screen to navigate to the design studio: Can not see this implemented 

Alert API Publisher in the API design studio that a platform configuration exists (at least a message, but it may be interesting to have read-only access) Can not see this implemented 

We should have the same behaviour regarding the deployment of the policies configuration as it is done for API policies deployment. Unclear

**Comment by phiz71** [comment]
@patelami 
> We should not be able to create any resource or configuration. So we should make policies that use resource unusable. **FAIL - We are still seeing the oAuth2 policy on the platform level**

Fix with https://github.com/gravitee-io/gravitee-policy-oauth2/pull/39

> Definitions of flows should be stored in a specific “Flows” collection. This collection should be generic enough to maybe add plan and API flows one day: **Not working as expected**

I don't get your point. What is not working ?

> Add links in the sharding tags screen to navigate to the design studio: **Can not see this implemented**

IMHO this rule can be removed since the platform policies screen and the sharding tags screen are accessible from the same menu. It was not the case when the issue was created.
![image](https://user-images.githubusercontent.com/13161768/120776176-398d7b00-c524-11eb-9696-052ed632b991.png)

> Alert API Publisher in the API design studio that a platform configuration exists (at least a message, but it may be interesting to have read-only access): **Can not see this implemented**

Currently working on it

> We should have the same behaviour regarding the deployment of the policies configuration as it is done for API policies deployment. **Unclear**

When platform policies are modified, they are automatically deployed on gateways. So we don't need to have a "yellow banner" asking the user to deploy the modifications.
