### ISSUE TITLE
[management] Add version for ApiEntity and UpdateApiEntity

### ISSUE THREAD

**Issue by GGui** [gravitee-io/issues#4468]
Hi,

is it possible to add version for for ApiEntity and UpdateApiEntity?
Like OAS, ApiEntity and UpdateApiEntity could include a version 

It could be gio_apim: 3.0 or apiVersion: gio_apim/3.0.

This version would also allow to easily identify that the object corresponds to an gravitee schema of the apim module in order to apply an automatic validation.

Thak you

**Comment by aelamrani** [comment]
Hi @GGui 

Sorry but I did not get the purpose of this version.

Why do you want to push an API version while updating an API? Which kind of automatic validation do you want us to do?
