### ISSUE TITLE
Invalid swagger definition generated for management Rest-API (Part 2)

### ISSUE THREAD

**Issue by Andy2003** [gravitee-io/issues#4475]
As pointed out in #4394 the generated swagger doc is invalid b/c of the highly customized `ObjectMapper`. So for example the generated definition of `ApiEntity` is:

```yaml
  ApiEntity:
    type: "object"
    required:
      - "proxy"
    properties:
      id:
        type: "string"
        example: "00f8c9e7-78fc-4907-b8c9-e778fc790750"
        description: "API's uuid."
      paths:
        type: "object"
        description: "a map where you can associate a path to a configuration (the\
          \ policies configuration)"
        additionalProperties:
          $ref: "#/definitions/Path"
### many other properties
```

and Path:

```yaml
  Path:
    type: "object"
    properties:
      path:
        type: "string"
      rules:
        type: "array"
        items:
          $ref: "#/definitions/Rule"
```

But when I query `GET /organizations/{orgId}/environments/{envId}/apis/{api}`, The following will be returned:

```json
{
  "id": "123",
  "paths": {
    "/xxx": [
      {
        "methods": [
          "POST"
        ],
        "dynamic-routing": {
          "rules": [
            {
              "pattern": "/xxx",
              "url": "/yyy"
            }
          ]
        },
        "enabled": true
      }
    ]
  }
 // many other properties
}
```

This does not match the spec, since the paths values are expected to be object and not array.
As a result the generated swagger java-client (`jersey2`) throws an `APIExceptions` since jackson is not able to serialize the array to object.

My suggestion to resolve this issue is to write a model for each version as a maven artifact. Something like `gravitee-rest-api-model-v1`, `gravitee-rest-api-model-v2` and so on, each with its own versioned package.
Then we can import all supported models in parallel and use a mapping framework like [mapstruct](https://mapstruct.org/) to map each version to the current internal representation.
So we can:
* Get rid of the customizations of the `ObjectMapper`
* Provide a valid swagger definition for all endpoints
* Make things more explicit in terms of  where things happen. Currently it's hard to understand where e.g. `plans` get serialized. It took me quite a while until I found the `ApiSerializer`

**Comment by Andy2003** [comment]
I locally refactored the project to fix this issue, but there is a really big amount of work to get an usable auto-generated swagger definition:

1. We need to get rid of the custom de-/serializer in https://github.com/gravitee-io/gravitee-definition so the swagger definitions are generated from the types correctly
2. since we use polymorphism for several types (`Endpoint`, `KeyStore`, `TrustStore`) and these type will be determined by a discriminator (`type`) which does not match the `simpleClassName`, we need to migrate to open-api definitions.
    -  swagger 2.0 does not support custom discriminator mapping, but open-api 3.x does (https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/)
3. The mapping of the `Rule`'s `policy` is tricky to map with the current format. To simplify this, we should wrap it in a custom property.

**Comment by phiz71** [comment]
@Andy2003 for the second point, it is planned for the 3.5.0
https://github.com/gravitee-io/issues/issues/4120#issuecomment-714380531
See #4120

**Comment by Andy2003** [comment]
[There is a branch](https://github.com/Andy2003/gravitee-management-rest-api/tree/bugfix/fix-model-types) in my repo having applied all the changes required to generate a clean open-api definition:

1. using https://github.com/gravitee-io/gravitee-definition/pull/83
2. having https://github.com/gravitee-io/gravitee-management-rest-api/pull/1240 applied
3. using the changed definitions (from point 1) and fixed all failing tests

How can I push forward this topic so we have a clean open-api definition matching the actual implementation?

**Comment by phiz71** [comment]
For this release and in this issue, we will focus on the gravitee-definition modification.
We have to work from the branch of @Andy2003.
The remaining tasks are:
 - rebase on master
 - move all the validation rules to a dedicated package or module.

**Comment by aelamrani** [comment]
When I publish an undeployed API, the API becomes out of sync => publish status should not have an impact on the deployment
