### ISSUE TITLE
Impossible to add Transform Headers policy

### ISSUE THREAD

**Issue by insertmike** [gravitee-io/issues#4479]
With the 3.3.0 Release of Gravitee it is no longer possible to create transform-headers policy.
Gravitee does not function for this kind of policy with not-adequate response:
```
Server Unreachable
```
### Your Environment

* Gravitee Version used: 3.0.0

**Comment by aelamrani** [comment]
Hi,

I am not able to reproduce.

Are you able to check if your server is available?
