### ISSUE TITLE
[management web-ui] Add Danish (da) i18n

### ISSUE THREAD

**Issue by larsnaesbye** [gravitee-io/issues#4484]
It would be nice for Danish-speaking users to have a Danish language version.

Pull request supplied.

**Comment by aelamrani** [comment]
Hi @larsnaesbye 

We are planning to remove completely the (poor) i18n support on the management UI.

**Comment by larsnaesbye** [comment]
Ah OK, not replace it with anything better but just remove it?

**Comment by aelamrani** [comment]
Yes, we were thinking about a full support or nothing, and we chose the simplest :D 

Seriously, no there is no users asking for this kind of full support on the management side (full support on the portal makes a lot of sense by the way).

**Comment by larsnaesbye** [comment]
Yeah, I was just thinking on making it for the entire Gravitee portfolio, but start out with the smallest.

**Comment by larsnaesbye** [comment]
Closing this issue now.

**Comment by aelamrani** [comment]
PRs are welcomed on the portal webui :)
