### ISSUE TITLE
[management] Remove i18n support on the management UI

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4485]
EN only

**Comment by leyvReyn** [comment]
@aelamrani good day, Elamrani. 
1. can you please explain why you decide to make management Web UI English only? 
2. if somebody will create a pull request with this library and support for english and russian languages, are there any chance that you will accept such pull request?
if my questions should be discussed somewhere else, please, guide me

**Comment by aelamrani** [comment]
Hi @leyvReyn 

The i18n support has been removed since it was used in the old portal (part of the mgmt web UI), so it was not necessay to keep modules related to translation. We feel like in this kind of admin console, the translation is not necessary that's why we have chosen to keep EN only (we suppose that tech persons understand the english).

However, the portal is fully translated and PRs are welcomed :)
