### ISSUE TITLE
[management] make portal/settings saving buttons sticky

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#4487]
## Problem

As the Portal/settings page is very long, it is not obvious that we have to save our changes.

## What to do ?

Make the Save & Reset buttons sticky so we always see them in the page
![image](https://user-images.githubusercontent.com/47851994/96455283-4bccda00-121d-11eb-80ab-499f218753f6.png)

**Comment by gaetanmaisse** [comment]
Closing as it will be fixed when this screen will be migrated to Angular and so will use the save bar implemented for the organization settings screens.
