### ISSUE TITLE
[portal] [chore] update parent

### ISSUE THREAD

**Issue by larsnaesbye** [gravitee-io/issues#4500]
Update the portal's gravitee-parent dependency to version 19 for fixes and improvements.

**Comment by aelamrani** [comment]
Hi @larsnaesbye 

May I ask you what do you fix/improve here?

**Comment by larsnaesbye** [comment]
Primarily the Jackson dependency goes from 2.9.8 to 2.10.3. 2.9 branch is described as being a maintenance branch with only minor security issues fixed, and [it closes by December 2020](https://github.com/FasterXML/jackson/wiki/Jackson-Releases).

**Comment by aelamrani** [comment]
But we do not use this dependency in the portal UI...

**Comment by larsnaesbye** [comment]
Ah, you're right! So sorry, I must have switched project windows at some point.

It's not that important after all. Only thing that has changed else is a little configuration of the Maven GPG-plugin.

So I guess it doesn't matter, but doesn't hurt. We can close or merge, it makes no difference.

**Comment by aelamrani** [comment]
I do prefer to manage this more globally when we will upgrade or by opportunity (to fix / improve things). Here, as we are not in that cases I do prefer to not upgrade for the moment.

Thanks
