### ISSUE TITLE
[swagger] only validate swagger content on create/update

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#4506]
Because of #4349 some existing swagger pages are no longer displayed.

The idea is to only check the content when we create/update the page and not when we render it.

----
### Update for 1.30.25 release
We have decided that illicit swagger descriptions should always be displayed and must always be imported as well.

But there must be a visible warning message about the file defects

**Comment by aelamrani** [comment]
@NicolasGeraud why closing it?
