### ISSUE TITLE
[gateway] [feature] Reload certificates without restarting Gravitee

### ISSUE THREAD

**Issue by larsnaesbye** [gravitee-io/issues#4508]
It would be nice to have Gravitee reload certificates from the certificate store. This way, certificates, e.g. from Lets' Encrypt can be renewed without having to restart Gravitee.

### Expected Behavior
Gravitee could reload the assigned certificates at a configurable interval, or triggered through a REST management interface trigger.

### Current Behavior
If a certificate is renewed in the certificate store, Gravitee does not discover it until after a restart. In the case of a long period without restarts, some expired certificates might be used long after new ones are available in the certificate store.

**Comment by brasseld** [comment]
Indeed!

**Comment by aelamrani** [comment]
Duplicate of https://github.com/gravitee-io/issues/issues/5888
