### ISSUE TITLE
Endpoint Names must be unique over all groups

### ISSUE THREAD

**Issue by insertmike** [gravitee-io/issues#4510]
### Abstract

Gravitee requires endpoint names to be unique over all endpoint groups. The context of an endpoint is it's endpoint-group so there is no need to be unique in name over all groups but within it's own group only.  
### Expected Behavior

Endpoint name to be unique over it's own endpoint group only.
### Current Behavior

Endpoint name should be unique over all endpoint groups. 
### Possible Solution

Make endpoint names unique over their own context - their endpoint-group.
### Steps to Reproduce (for bugs)

1. Create endpoint-group-1 and endpoint-group-2 
2. Try to add the same endpoint names in both groups.

### Your Environment

* Gravitee Version used: 3.2.0

**Comment by aelamrani** [comment]
Hi @insertmike 

Actually, the names has to be unique to be selected as part of the expression language.

Take a look at https://docs.gravitee.io/apim/3.x/apim_publisherguide_expression_language.html#endpoints

Azize

**Comment by insertmike** [comment]
Hello Azize @aelamrani,

Thanks for the fast response. It might be stupid question but what is the ratio behind using the name to retrieve the name from EL? Why the ID is not used instead? 

Mihail

**Comment by aelamrani** [comment]
Hi @insertmike 

We are exposing the endpoints and the endpoint groups through the exact same syntax to make things easier: `{#endpoints['default']}`

So `default` can be an endpoint (named default) or a group of endpoint. And this later is useful when you want to select a group of endpoints and take the benefits of load balancing / HTTP configuration etc...

Is that clearer?
