### ISSUE TITLE
[question][gateway] Merge JSON Body from multiple endpoint

### ISSUE THREAD

**Issue by FeyverkSoft** [gravitee-io/issues#4517]
Can we implement merge JSON body from 2 service to one endpoint? 
for example
Endpoints
[GET] /test1  `{"props1":"value1"}`
[GET] /test2  `{"props2":"value2"}`
Entrypoints
/gravitee/demo
Responce
`{"props1":"value1, "props2":"value2"}`

Your Environment
Gravitee Version used: 3.3.0 (build: 941) revision#4bddd5960584dfc75912fa3e738fafe0e8784fc5

thank you

**Comment by aelamrani** [comment]
Hi @FeyverkSoft 

As far as I understand your need, you want to mashup (merge) multiple responses to a single one and send it to your consumer.

One way to do it, is to make the use of the [HTTPCallout policy](https://docs.gravitee.io/apim/3.x/apim_policies_callout_http.html), then get the responses into the execution context.

This context can be accessed then in the [Groovy policy](https://docs.gravitee.io/apim/3.x/apim_policies_groovy.html) where you can aggregate these responses.

Another solution would be to develop a [custom policy](https://docs.gravitee.io/apim/3.x/apim_devguide_policies.html).

Hope it helps,
Azize

**Comment by FeyverkSoft** [comment]
thanks for answer.
