### ISSUE TITLE
[management] Code input is not rendering all the content sometimes

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4539]
The user have to click on the input to see everything.

![Capture d’écran 2020-11-03 à 08 41 34](https://user-images.githubusercontent.com/1580262/97959797-6623bd80-1db0-11eb-94ce-06b6e703961d.png)
![Capture d’écran 2020-11-03 à 08 41 20](https://user-images.githubusercontent.com/1580262/97959799-6754ea80-1db0-11eb-802e-90527c0ed493.png)

**Comment by jhaeyaert** [comment]
I think this is a duplicate of #4473

**Comment by aelamrani** [comment]
Alright
