### ISSUE TITLE
[management] swagger vendor extensions are never shown

### ISSUE THREAD

**Issue by jeremy-dubus** [gravitee-io/issues#4556]
The 'x-' vendor extensions in a swagger descriptor file are never shown in the final page, whether the adequate configuration option is checked or not

### Expected Behavior
When you check the "Display vendor extension (X-) fields and values for Operations, Parameters, and Schema" option, the vendor extensions should be displayed in the swagger page rendering

### Current Behavior
Vendor extensions are never displayed

**Comment by leleueri** [comment]
Not reproduced in 3.0.x.
Tested in using Firefox and Chrome. (Using the console UI and portal UI)

Vendor extensions are displayed at Operation level, Parameter level and ObjectSchema level.

![image](https://user-images.githubusercontent.com/3110552/106874648-1d90de80-66d6-11eb-8686-4cd358493804.png)
![image](https://user-images.githubusercontent.com/3110552/106874686-297ca080-66d6-11eb-85e8-cbebafc7dbe2.png)
![image](https://user-images.githubusercontent.com/3110552/106874737-35686280-66d6-11eb-9f16-45612089fdd6.png)
