### ISSUE TITLE
[management] Not able to create an API from scratch with domain restrictions

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4564]
Linked to https://github.com/gravitee-io/issues/issues/4308

![Capture d’écran 2020-11-05 à 08 43 36](https://user-images.githubusercontent.com/1580262/98211875-03aef680-1f43-11eb-9c5b-08ec84e77775.png)

**Comment by phiz71** [comment]
Will only happen in a multienv context *and* with domain restrictions.

**Comment by aelamrani** [comment]
Yes but we should handle this use case
