### ISSUE TITLE
[management-api] Error An API must have, at least, one path defined (default is /*)

### ISSUE THREAD

**Issue by anchsu** [gravitee-io/issues#457]
### Current Behavior
Creating an API :
- use Create an API from scratch ...
- General : fill all the fields -> next
- Gateway : fill the backend -> next
- Plan :  Fill the mandatory fields
- Doc : Skip
- CREATE AND START

Result : 
io.gravitee.gateway.handlers.api.validator.ValidationException: An API must have, at least, one path defined (default is /*)

### Possible Solution
I think that the he field Gateway context path isn't used when create an API from scratch.

### Your Environment
Version 1.3.0

**Comment by brasseld** [comment]
I'm closing this ticket.
Already resolved by https://github.com/gravitee-io/issues/issues/451

Fix included in 1.3.3 (scheduled for today).
