### ISSUE TITLE
[management] Avoid use of popup on OAuth2 login

### ISSUE THREAD

**Issue by oyviaase** [gravitee-io/issues#4579]
When only providing oauth for loging into gravitee are users unable to login to gravitee from iOS devices, they press the login button and nothing happens. If the user turns of "Block pop-up..." in safari are they able to login to gravitee using oauth

### Expected Behavior

The user should be shown the login form from the oauth provider regardless of their browser, device or settings

### Current Behavior

The user is shown nothing when using certain browsers, devices and settings

### Possible Solution

Certain browser, device and settings combinations, disables pop-up windows so the best solution is to not use pop-up windows when login in. If that's not possible then an error message or warning should be provided to the user to why they are unable to login to gravitee using an oauth provider.

### Steps to Reproduce (for bugs)

1. Configer an oauth provider
2. Try to login with safari on an iOS device (or probably another browser blocking pop-up windows)

### Context

We would like our users to use whatever devices and browsers that they want to use.

### Your Environment

* Version used: 1.30.24
* Browser Name and version: Safari 
* Operating System and version: iOS 14.2

**Comment by aelamrani** [comment]
Hi @oyviaase 

I think we have already spoken about getting the user redirected to the login page and not use a popup for such thing.
