### ISSUE TITLE
[portal] Health-check settings panel (request URI)

### ISSUE THREAD

**Issue by anchsu** [gravitee-io/issues#458]
### Current Behavior
In the Health-check settings panel, when we set the request URI with and absolute path e.g., http://ip/path, the health check is always KO. 
There is no information that he URI does not math the wanted pattern.

### Possible Solution
Add a documentation, such as it is done with the expectation field.

### Your Environment
* Version used: 1.3.0

**Comment by brasseld** [comment]
Hi @anchsu,

Yes you're right. It's because this input is waiting for a path only and not a complete URI.
The complete URI is based on:
1) Endpoints declared in gateway > endpoint
2) The path specified in health-check.

Is it ok for you ?

**Comment by anchsu** [comment]
Hi,

It's ok, a little icon (I) with an information message such as it is done with the expectation field would be nice, isn't it?

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/issues/issues/704
