### ISSUE TITLE
[service][health-check] Health-check default expectation behavior

### ISSUE THREAD

**Issue by anchsu** [gravitee-io/issues#459]
### Expected Behavior
When we configure an health check with no Expectation, we want that the health check success when the http response code is 2xx.

### Current Behavior
If the response code is 204, the health check failed. 

### Possible Solution
One solution is to document the default expectation behavoir is to check that the response code is equals to 200.
Second solution is to check by default all 2xx codes.

### Your Environment
* Version used:1.3.0

**Comment by brasseld** [comment]
Hi @anchsu,

By default, is there is no expectation, we are associating a default expectation which is checking that the response code is equals to 200.

Do you have a concrete case where you need that this default expectations is equals to 2xx ?

**Comment by anchsu** [comment]
Hi,

We use a supervision rest service ("/supervision/ping") which answers us an http response code 204 no content if everything is ok.

**Comment by brasseld** [comment]
Ok, we have to provide an information to specify that the default expectation is to check response code == 200

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/issues/issues/704
