### ISSUE TITLE
[management] Default admin can't see/go to the dashboard and settings menu

### ISSUE THREAD

**Issue by yoga-v** [gravitee-io/issues#4591]
In a fresh install of the APIM v3.1.3 the default admin can't access the menu: Dashboards and settings

### Expected Behavior

The default admin who is [ENVIRONMENT] ADMIN -
[ORGANIZATION] ADMIN can see the dashboard and settings menu.

**Config in gravitee.yml:**
-user:
          username: admin
          #firstname:
          #lastname:
          # Password value: admin
          password: $2a$10$Ihk05VSds5rUSgMdsMVi9OKMIx2yUvMz7y9VP3rJmQeizZLrhLMyq
          roles: ORGANIZATION:ADMIN,ENVIRONMENT:ADMIN
          #email:

### Current Behavior

The menu is not visible when logged in as default admin.

### Steps to Reproduce (for bugs)

1. Create a fresh Install v3.1.3
2. Log in with the admin account
3. Try to access the dashboard and settings menu

 
### Context

Connect to dashboard page and settings page in a fresh install

### Your Environment

* Version used: v3.1.3
* Browser Name and version: Chrome
* Operating System and version: Ubuntu 18.04

![image](https://user-images.githubusercontent.com/24449733/98943067-f2eb1b80-2514-11eb-9206-7726cfbedf17.png)

**Comment by aelamrani** [comment]
Hi @yoga-v 

Is it a fresh installation from docker or zip or other?

**Comment by yoga-v** [comment]
Hi @aelamrani - It was a fresh install from zip.

**Comment by aelamrani** [comment]
Backport 3.3.x (at least)
