### ISSUE TITLE
Can we run command "npm run serve" without  windows-build-tools  at management UI 3.3.3 version 

### ISSUE THREAD

**Issue by aliFetvaci61** [gravitee-io/issues#4616]
I can not install  windows-build-tools 

npm run serve on CMD

ERROR in ./src/index.scss 1:18
Module parse failed: Unexpected character '#' (1:18)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> $backgroundColor: #fdfdfd;
|
| @import '~angular-gridster/dist/angular-gridster.css';
 @ ./src/index.ts 20:0-23

Can we run command "npm run serve" without  windows-build-tools  at management UI 3.3.3 version

**Comment by aelamrani** [comment]
Seems to be the same kind of issue as here: https://github.com/gravitee-io/issues/issues/1512
