### ISSUE TITLE
[policy] [jwt] Couldn't find clear doc to use JWT predefined policy

### ISSUE THREAD

**Issue by sakthi-raman** [gravitee-io/issues#462]
Hi Team,

I am new to this gravitee.io framework. I am trying to change the configuration to switch the API key policy to JWT policy. This is the link for the doc https://docs.gravitee.io/apim_policies_jwt.html

### Context
In this document, I couldn't find / understand where to configure the JWT configurations (such as "publicKeyResolver", .., ,,), how to switch to JWT token in the management API web page instead of API key in the API creation. If you could, provide the policy switch document similar to the API consumer doc (https://docs.gravitee.io/apim_publisherguide_manage_apis.html). I know it will take some time.

For now, can you share me the steps to change the config and switch to JWT policy instead of API key policy ?

### Your Environment
* Version used: 1.2.0
* Browser Name and version: chrome V 56.x
* Operating System and version: Debian Linux, custom version

Thanks in advance.

**Comment by aelamrani** [comment]
Hi Sakthiraman,

The api key is a kind of low level of security as we use it to know which application calls a given API. This informations are collected and used to provide dashboard analytics. If you don't use api key, we cannot identify the caller application.

Since the version 1.2, we introduced keyless plans, which allows you to bypass the apikey policy check, in order to open your API or applying a higher level of security (oAuth2, jwt...). So by adding a keyless plan and the policy JWT, it should run as you expect...

Is it ok for you?

**Comment by sakthi-raman** [comment]
Hi Aelamrani,

Thanks for the reply first.

My intention is to use the JWT for the higher level security. I am not much worried about keyless or with key plan. If api key is only parameter to identify for the caller application, I am ok with it.

I need all the current gracvity functionality with tracking like rate limit, request status tracking, etc., which are all currently available and also JWT security. If gravitee needed, we can use the API key also for the current tracking. 

So, I hope I explained you clearly what's my expectation is. So, Can you guide me how to do it ?

**Comment by brasseld** [comment]
Hi @sakthi-raman,

Were you able to create an API ?
If not, I advise you to read the quickstart guide: https://docs.gravitee.io/apim_quickstart_publish.html
Note that the doc is not yet up-to-date since 1.3.x version but concepts remain the same.
When your first API is ready, you can configure policies from the policies view (API > policies in left menu). There, you can attach the JWT policy to the root path ('/') and configure the policy (by clicking the policy). You can also follow documentation for JWT policy from: https://docs.gravitee.io/apim_policies_jwt.html

Hope it helps you. In any case, feel free to ask us. If you're not able to do follow this, it means probably that something is missing in the documentation.

**Comment by sakthi-raman** [comment]
Hi @brasseld,

Thanks.

I have created API as you mentioned in the publish and consume doc. That why I can test the end to end flow through API key default policy.

I got your point to configure the JWT in the API > policies in the left menu. Yes, I tried that. In the polices page, I can see many pre-defined policies, But, I couldn't configure anything related to the JWT. It seems to be all the policies buttons are disabled. Just I can create some paths similar to the root path which is predefined one by using the + button in the bottom right side. 

I believe some configuration / something needs to change for enabling it. But, I don't know how to change that.

Can you help me ?

**Comment by brasseld** [comment]
You must have something like this:
<img width="1626" alt="capture d ecran 2017-02-21 a 08 34 39" src="https://cloud.githubusercontent.com/assets/133094/23154946/a5dc91dc-f810-11e6-8adc-0685f24bd7ac.png">

If it's not your case, can you share with us a screenshot of policies view ?

**Comment by sakthi-raman** [comment]
![jwt policy](https://cloud.githubusercontent.com/assets/7996380/23155099/15ab1256-f837-11e6-8f50-0582a873be08.jpeg)

I am getting the same screen without JWT policy. Here I attached for your reference. But, I couldn't configure JWT here.

**Comment by brasseld** [comment]
Because you did not drag'&drop the JWT policy from the list of policies to the root path.

No ?

**Comment by sakthi-raman** [comment]
Thanks Brasseid. I tired to click and also other possible options to add. But, I missed the drag and drop option.

I can see it now.

Few more query in the JWT configuration.

We have 3 options such as,
GIVEN_KEY, GIVEN_ISSUER, GATEWAY_KEYS

1) While choosing GIVEN_KEY - we have to give the public key in the next text box. Do we need to give the commend to create the public key or we can give my generated public key in my Linux machine using openssl command ?

2) In the GIVEN_ISSUER and GATEWAY_KEYS, we need to give issuer name which we mention in the gravity.yaml config file. the only difference is to give kid for the GATEWAY_KEYS right ? If no, what is the difference in between that ?

sample jwt yaml config.
--------------------------
policy:
  jwt:
    issuer:
      sakthiserver:
        default: ssh-rsa <-?-myValidationKey- ?---> sakthi.raman@xxx.com
        kid-2016: ssh-rsa <-?-myValidationKey- ?---> sakthi@xxx.com


Can I give my pub key which I generated using openssl command like this or any length restriction is there ?

        default: ssh-rsa <-my pub key which is generated using openssl---> sakthi@xxx.com
        kid-2016: ssh-rsa <-my pub key which is generated using openssl---> sakthi@xxx.com

3) Can I give the public key file key.pub instead in the ssh-rsa command instead of direct key ?

I am new to RSA algorithm also. If my question doesn't make any sense ot totally wrong in that, Kindly let me know. I am sorry for that.

Thanks in advance.

**Comment by brasseld** [comment]
You're welcome @sakthi-raman !

About your questions:
1. You can give your generated public key
2. Yes, you have to provide a public key for issuer / kid couple
3. Actually no, but it is a really good idea. I propose you to create an other issue to add this feature in JWT policy.
4. If you set keyless security type for your plan, you would not be able to know which application is calling your API. I would recommend to create an api_key plan just to authenticate HTTP calls for a better analytics report. But you're right, if you use a keyless security type, you do not have to pass any other query-param.

Now, how to pass your JWT token:
1) You can use the Authorization header like this:
`Authorization: Bearer your_jwt_token_value`
2) You can pass an access_token query-param as follow:
`http://domain/gravitee-uri/myapi?access_token=your_jwt_token_value`

**Comment by sakthi-raman** [comment]
Hi Brasseid,

I have done some study. These are my doubts.

General doubt about the usage ssh-rsa in the JWT
-------------------------------------------------------
ssh-rsa <key> <username>@<host-ip / name
- Is to authenticate the access of our server which is servicing our REST service right ?

Gravity flow doubt
---------------------
1) Consider we have created gravitee api called http://localhost:8083/xxx and it is mapped for our http://localhost:8080/yyy.
2) Created plan with key less plan.

As you said in the last comment. I will send the request like this.
http://localhost:8083/xxx?access_token=your_jwt_token_value

If my understanding correct,
1) gravitee first authenticate the server with ssh-rsa command which we give. 
2) Then it should send the request to the mapped service url with the access token.
     http://localhost:8080/yyy?access_token=your_jwt_token_value
3) Then jwt token is decoded in the service layer and get the encoded user info(JWT payload data) to process and then send back the response to gravitee.
4) Then it will received in the consumer side.

Am I right or am I missing something here ?

My Intention to ask,
1) I have done the JWT implementation separately. I just trying to understand the flow sequence.
2) To confirm our JWT access token sent to my REST service layer or not ? I have few details in my JWT token. I need to access it. That's the original intention of the JWT token ?
3) As we discussed earlier, consumer API couldn't be tracked in the key less plan. Because of this tracking missing, do we miss any analytics report or any gravity functionality part ?

Can you confirm this plz ?

**Comment by brasseld** [comment]
Hi @sakthi-raman,

## General doubt about the usage ssh-rsa in the JWT
> Yes, absolutely !

## Gravity flow doubt
1. First, gateway is authenticating the incoming call using the provided JWT token (from query parameter or from header) by decoding it.
2. Then, gateway is dispatching the request to your API / backend / mapped service. The JWT token is propagated to your backend.
3. Then, your own service is also decoding the token to access JWT claims and send back the response to the gateway.
4. Initial consumer receives the response.

1. No problem
2. Yes
3. All calls are still tracked by the gateway. The only thing you miss is the ability to associate a consuming application to the incoming request. But you still have analytics at the API level : HTTP status, Application repartition, gateway response-time, api response-time, ...

Finally, I have just confirm all your assumptions ;)

**Comment by sakthi-raman** [comment]
Hi @brasseld,

Regarding the ssh-rsa last query:
If my gravitee and reset service are running in the same server, Is it mandatory to give ? If yes, why do we need ?

**Comment by brasseld** [comment]
Hi @sakthi-raman,

I don't what you're doing with the JWT token in your mapped service.
The gateway is responsible of authorizing the incoming HTTP request by validating the provided JWT token. If not valid, the request is not dispatched to your service.
Now, if your mapped service needs some information (claims) from the JWT token, it is better to extract these data from it in the mapped service side. If you don't need it and if your mapped service is only exposed to and for the gateway, so yes, you don't have to do at the service side.

Hope it helps.

**Comment by sakthi-raman** [comment]
Hi @brasseld,

Question 1:
Yes, I got your point very clear that gateway is the responsible one for the validate and authorize the incoming request and dispatch to the service.

My question is different. we are configuring public key in the JWT policy right ? It is to authenticate the server which we deploy our rest. It means gravitee shall be in one server and service shall be in the another server. So that, we are configuring the below ssh-rsa in the public key field when public key resolver is given_key.

`ssh-rsa <--pub key--> <--username@(host ip / name)-->`

If we run gravitee and service in single machine, Do we need to validate the server by this rsa public key ?

Question 2:
> Now, if your mapped service needs some information (claims) from the JWT token, it is better to extract these data from it in the mapped service side.

Based on your statement, I am getting one more doubt. If you suggest to extract the data from the mapped service side, how to do it ? Is it possible to extract the data in the gravity gateway and send it to the service layer using EL / something other similar to that  ?

**Comment by anujgandharv** [comment]
A small question. I have a case where my RSA Public Key for JWT validation resides at a separate URL: https://[base-server-url]/jwks.json that returns me a list of keys in JSON format. The JSON format returned looks like this: https://static.javadoc.io/com.nimbusds/nimbus-jose-jwt/2.21/com/nimbusds/jose/jwk/JWKSet.html
Is there a way to tell JWT Policy to grab the list of Keys from a URL or do I need to write my custom JWT Validator Policy?

**Comment by brasseld** [comment]
Hi @anujgandharv 

I would say that the best would be to improve JWT policy by providing a new public-key resolver instead of writing your own policy.

WDYT ?

**Comment by anujgandharv** [comment]
Thats even better IMO as I have to write less code :).
Can you point me to the JWT policy code so that I can have a look at it.

**Comment by brasseld** [comment]
Sure!

https://github.com/gravitee-io/gravitee-policy-jwt/blob/master/src/main/java/io/gravitee/policy/jwt/JWTPolicy.java

If you need some help, we will be happy to discuss with you on gitter channel: https://gitter.im/gravitee-io/gravitee-io

**Comment by NicolasGeraud** [comment]
moved to gravitee-io/gravitee-docs#71
