### ISSUE TITLE
[portal] image links are broken on portal documentation

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#4620]
it's ok for api documentation.

**Comment by phiz71** [comment]
Backport to 3.0.x & 3.3.x

**Comment by mdz0r** [comment]
not fixed in 3.4 :

management-ui :
`![image.png](https://ip:8083/management/organizations/DEFAULT/environments/DEFAULT/portal/media/F7B41FA44DE31592E2A6CABCE6DF4207)`
portal-ui :
![image](https://user-images.githubusercontent.com/42241744/100342671-9bea4980-2fde-11eb-968f-d8c6ffefa8d1.png)

**Comment by aelamrani** [comment]
Seems good to me...

**Comment by phiz71** [comment]
@mdz0r, depending on the portal configuration this URL can work, that's why we didn't see the pb.
But you're are right, it should be, `[baseURL]/media/F7B41FA44DE31592E2A6CABCE6DF4207`, where baseURL is what you have configured in your `assets/config.json`.

**Comment by mdz0r** [comment]
@phiz71 my baseURL is http://ip:8083/portal/environments/DEFAULT so i dont think it could work either, there's no reference to the management path

**Comment by phiz71** [comment]
it will work with  https://ip:8083/portal/environments/DEFAULT/media/xxxxxx.

Your Portal UI uses portal API, whose baseURL is https://ip:8083/portal/environments/DEFAULT
Your Management UI (aka Console)  uses management API, whose baseURL id https://ip:8083/management/organizations/DEFAULT/environments/DEFAULT

But both portal and management API have the `/media` resources and they are connected to the same database.
