### ISSUE TITLE
Keycloak login issue

### ISSUE THREAD

**Issue by pavanelthepumisc** [gravitee-io/issues#4634]
Unable to login with Keycloak with a fresh installation

### Steps to Reproduce (for bugs)
1. Download zip file
2. Extract it
3. Run all 4 components
4. Update the mongo to postgres
5. Add JDBC plugin and postgres driver
6. Start all components and configure keycloak as per https://docs.gravitee.io/apim/1.x/apim_installguide_authentication_keycloak.html
7. Logout and try to login with keycloak

It gives following error:

![image](https://user-images.githubusercontent.com/29723106/99778316-8c2fb880-2b39-11eb-95cf-d72a7fd3c9bc.png)

And console log:
![image](https://user-images.githubusercontent.com/29723106/99778429-b08b9500-2b39-11eb-943e-5fd3f10ccccb.png)

### Your Environment

* Version used: 3.3.3
* Browser Name and version: Chrome 79.0.3945.130 (Official Build) (64-bit)
* Operating System and version: MacOS Catalina 10.15.6

**Note:** Everything works great with normal login. Issue is only with keycloak login

**Comment by phiz71** [comment]
backport to 3.3.x
