### ISSUE TITLE
[plan][jwt] The application is categorized as an unknown application when the jwt has expired

### ISSUE THREAD

**Issue by djo54150** [gravitee-io/issues#4637]
Hello, 

With a JWT plan ,the consumer is categorized as an unknown application when the jwt has expired. 

### Expected Behavior
I think we should log the application that makes the call through the JWT plan.

### Current Behavior
Application is categorized as an unknown application 

### Steps to Reproduce (for bugs)
1. Create an API with  JWT plan 
2. Create an application  and subscribe to the JWT plan to the API created in step 1
3. Call the API with a expired JWT

### Context

This is problematic because we cannot know who is trying to call us with a wrong JWT.

### Your Environment

* Version used: APIM 3.3.3 
* Operating System and version: CENTOS 7 

Regards,
Jonathan

**Comment by aelamrani** [comment]
Hi @djo54150 

Yes you are right, sounds better.
