### ISSUE TITLE
Add an API from another docker-compose stack than the Gravitee one

### ISSUE THREAD

**Issue by alchy58** [gravitee-io/issues#4640]
Hi there,

I just discovered Gravitee, thank you for your huge work ! All Gravitee components seems to work well, I can get the management UI and I try to add a first API.
I manage to try it using the docker-compose stack and I would like to add an API which is handled by another docker-compose stack on my local host. This first API can be accessed on https://my-api.localhost/api/v1.

To have both stacks talking to each other, I created an external network
`docker network create gravitee-devstack`

Then I added the network to the Gravitee gateway service and on the Nginx reverse-proxy on the second stack
```
networks:
     [...]
      gravitee-devstack:
          external: true
[...]
services:
  gateway:
     [...]
    networks:
     [...]
      - gravitee-devstack
```
And on the docker-compose concerning API
```
networks:
     [...]
      gravitee-devstack:
          external: true
[...]
services:
  nginx:
     [...]
    networks:
     [...]
      - gravitee-devstack
```

For Gravitee to know where is located https://my-api.localhost, I retrieved the internal IP of the Nginx container and added an entry into the /etc/hosts of the gateway container
```
docker-compose exec gateway sh
# echo '172.30.0.2 my-api.localhost' >> /etc/hosts
```
```
docker-compose exec management_api sh
# echo '172.30.0.2 my-api.localhost' >> /etc/hosts
```

Pinging my-api.localhost is working from the gateway container, `wget https://my-api.localost` give me an error (ssl_client: my-api.localhost: certificate verification failed: unable to get local issuer certificate) but the API is reachable using `--no-check-certificate` argument. Should it be the issue ?

### Expected Behavior
When importing a new API by URL, putting https://my-api.localhost/api/v1/doc/ leads to the API successfully added

### Current Behavior
When importing by URL https://my-api.localhost/api/v1/doc/, I get the following error message :
`io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: my-api.localhost/127.0.0.1:443 `

### Steps to Reproduce (for bugs)
Probably depends on my local configuration and not on Gravitee so thank you in advance for your reply.

### Your Environment
Ubuntu 18.04.5 LTS
Docker version 19.03.13
docker-compose version 1.23.2
Gravitee 3 from https://docs.gravitee.io/apim/3.x/apim_installguide_docker_compose.html
Firefox 82.0.3

**Comment by aelamrani** [comment]
Hi @alchy58 

You add to add the host entry to the management API container also.

**Comment by alchy58** [comment]
> Hi @alchy58
> 
> You add to add the host entry to the management API container also.

I added the /etc/hosts entry on management_api container too. I can wget my API with success, but I have to use --no-check-certificate also.
The issue remain the same, I cannot import the API.

Does Gravitee support importing an API using a self-signed certificate ?

**Comment by aelamrani** [comment]
It seems that it is about host verification.

Will provide a fix soon.

**Comment by aelamrani** [comment]
Backport 1.30
