### ISSUE TITLE
cannot delete background image in Settings/Theme/Homepage

### ISSUE THREAD

**Issue by McFoggy** [gravitee-io/issues#4689]
### Expected Behavior
In Setting/Theme : you can delete the background image

### Current Behavior
Clicking on delete link under the Homepage image in Homepage section leads in a JS error
![image](https://user-images.githubusercontent.com/1119660/100591066-88e4bb80-32f5-11eb-9ebe-ec05f40acd29.png)

### Steps to Reproduce (for bugs)
1. Go to admin-ui / Settings / Theme
2. In Homepage section, set an image as background
3. Save and activate the theme
4. Click on delete link under the background image, nothing happens from user perspective, opening the JS console reveals an erro

### Your Environment
3.3.0 gravitee installation

**Comment by aelamrani** [comment]
Has been fixed by https://github.com/gravitee-io/issues/issues/4213

Will be fix on the next 3.3.4.

Feel free to re-open if not.
