### ISSUE TITLE
[management] improve attach media feature

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#4702]
There are some issues on the attach media feature when using jdbc:

- The creation date doesn't keep hour, only the date at midday is retained
- There is a 500 error when trying to upload the same file multiple times
- There is a 500 error when, after adding a file, the page is refreshed and a new file is uploaded (java.lang.UnsupportedOperationException when invoking a toInstant on an java.sql.Date).

More globally, the behavior of the deletion is odd (jdbc or mongodb). It seems that the UI doesn't send the right request body and keep track of previous attachments (multiple imports, addition of new attachements then re-imports have been made consecutively).

![image](https://user-images.githubusercontent.com/5955401/100639668-c5380c00-3335-11eb-8551-3ef30b0264fa.png)

**Comment by phiz71** [comment]
I was not able to reproduce all the problems you mentioned. However I've fixed some of them.
