### ISSUE TITLE
[management] cannot exclude myself from application group

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#4709]
As an application creator, if I am in a group with "admin" role on this group, I should not be allowed to disable the admin role for myself

![image](https://user-images.githubusercontent.com/47851994/100757785-11935280-33ef-11eb-8735-df3b6a19cfdd.png)

More over, there is an error when trying to disable it
![image](https://user-images.githubusercontent.com/47851994/100757905-37205c00-33ef-11eb-86ab-91590b60817d.png)

```
{
  "message" : "Invitation system is forbidden for group [3291a878-0866-4dde-91a8-7808665dde97]",
  "http_status" : 404
}
```

**Comment by phiz71** [comment]
There is others pb on this page link to the "group admin" role. We need to fix the entire screen and not only the check box.
I move this issue to 3.0.x (probably 3.0.15)
