### ISSUE TITLE
 "No context-path matches the request URI." 

### ISSUE THREAD

**Issue by selmath** [gravitee-io/issues#471]
I have set the cache policy and tried to call the API but I am getting a message "No context-path matches the request URI." 
### Possible Solution
First have to define your cache configuration from Resources  then link this to a caching policy

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Version used:1.2.0
* Browser Name and version: Chrome
* Operating System and version:linux

**Comment by brasseld** [comment]
Documentation has been improved:
https://docs.gravitee.io/apim_resources_cache.html
