### ISSUE TITLE
[management] Manage AsciiDoc pages

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4717]
# User Story
As an API publisher, I want to write documentation in AsciiCode, so that I can benefit from its advantages over Markdown

# Further Information
- The toolbar is removed
- The "WYSIWYG" mode is removed

# Examples
#### Preview OK
![AsciiDoc preview OK](https://user-images.githubusercontent.com/82866977/121857524-01412600-ccf6-11eb-873b-660bf8b3641e.PNG)

#### Preview KO
![AsciiDoc preview KO](https://user-images.githubusercontent.com/82866977/121857673-29308980-ccf6-11eb-863b-6b7d9d4ef47a.PNG)

# Tests
#### Documentation Pages Creation
- [ ] Given a page defined with the [file: Markdown Template.txt](https://github.com/gravitee-io/issues/files/6457963/Markdown.Template.txt), when I browse the page creation form (platform level), then the syntax is not interpreted and the text is displayed as is, without rendering preview
- [ ] Given a page defined with the [AsciiDoc Article Template](https://asciidoctor.org/docs/asciidoc-article/), when I browse the page creation form (platform level), then the preview is displayed

#### Translations
- [ ] Given the page defined with the [file: Markdown Template.txt](https://github.com/gravitee-io/issues/files/6457963/Markdown.Template.txt), when I add a translation (without inheriting the content), then the syntax is not interpreted and the text is displayed as is, without rendering preview
- [ ] Given the page defined with the [AsciiDoc Article Template](https://asciidoctor.org/docs/asciidoc-article/), when I add a translation (without inheriting the content), then the preview is displayed

#### Documentation Pages Creation
- [ ] Given a page defined with the [file: Markdown Template.txt](https://github.com/gravitee-io/issues/files/6457963/Markdown.Template.txt), when I browse the page creation form (API level), then the syntax is not interpreted and the text is displayed as is, without rendering preview
- [ ] Given a page defined with the [AsciiDoc Article Template](https://asciidoctor.org/docs/asciidoc-article/), when I browse the page creation form (API level), then the preview is displayed

#### Translations
- [ ] Given the page defined with the [file: Markdown Template.txt](https://github.com/gravitee-io/issues/files/6457963/Markdown.Template.txt), when I add a translation (without inheriting the content), then the syntax is not interpreted and the text is displayed as is, without rendering preview
- [ ] Given the page defined with the [AsciiDoc Article Template](https://asciidoctor.org/docs/asciidoc-article/), when I add a translation (without inheriting the content), then the preview is displayed

#### Cross Version Support
 - [ ] Import an API with an Asciidoc page in a pre-3.10 APIM and it should be ignored (with no error)

#### Homepage
- [ ] Given the homepage defined with the [file: Markdown Template.txt](https://github.com/gravitee-io/issues/files/6457963/Markdown.Template.txt), when I browse the following URL https://v3.nightly.gravitee.io/, then no rendering is displayed
- [ ] Given the homepage defined with the [AsciiDoc Article Template](https://asciidoctor.org/docs/asciidoc-article/), when I browse the following URL https://v3.nightly.gravitee.io/, then the rendering is displayed and corresponds to the preview 

#### Documentation Pages
- [ ] Given the page defined with the [file: Markdown Template.txt](https://github.com/gravitee-io/issues/files/6457963/Markdown.Template.txt), when I browse the following URL https://v3.nightly.gravitee.io/documentation/root, then no rendering is displayed
- [ ] Given the page defined with the [AsciiDoc Article Template](https://asciidoctor.org/docs/asciidoc-article/), when I browse the following URL https://v3.nightly.gravitee.io/documentation/root, then the rendering is displayed and corresponds to the preview

##### Homepage
- [ ] Given an english version of the homepage defined with the [file: Markdown Template.txt](https://github.com/gravitee-io/issues/files/6457963/Markdown.Template.txt), when I browse the following URL https://v3.nightly.gravitee.io/ in english, then no rendering is displayed
- [ ] Given an english version of the homepage defined with the [AsciiDoc Article Template](https://asciidoctor.org/docs/asciidoc-article/), when I browse the following URL https://v3.nightly.gravitee.io/ in english, then the rendering is displayed and corresponds to the preview 

##### Documentation Pages
- [ ] Given an english version of the page defined with the [file: Markdown Template.txt](https://github.com/gravitee-io/issues/files/6457963/Markdown.Template.txt), when I browse the following URL https://v3.nightly.gravitee.io/documentation/root in english, then no rendering is displayed
- [ ] Given an english version of the page defined with the [AsciiDoc Article Template](https://asciidoctor.org/docs/asciidoc-article/), when I browse the following URL https://v3.nightly.gravitee.io/documentation/root in english, then the rendering is displayed and corresponds to the preview

#### Homepage
- [ ] Given the homepage defined with the [file: Markdown Template.txt](https://github.com/gravitee-io/issues/files/6457963/Markdown.Template.txt), when I browse the "Informations générales" section, then no rendering is displayed
- [ ] Given the homepage defined with the [AsciiDoc Article Template](https://asciidoctor.org/docs/asciidoc-article/), when I browse the "Informations générales" section, then the rendering is displayed and corresponds to the preview

#### Documentation Pages
- [ ] Given the page defined with the [file: Markdown Template.txt](https://github.com/gravitee-io/issues/files/6457963/Markdown.Template.txt), when I browse the "Documentation" section, then no rendering is displayed
- [ ] Given the page defined with the [AsciiDoc Article Template](https://asciidoctor.org/docs/asciidoc-article/), when I browse the "Documentation" section, then the rendering is displayed and corresponds to the preview

##### Homepage
- [ ] Given an english version of the homepage defined with the [file: Markdown Template.txt](https://github.com/gravitee-io/issues/files/6457963/Markdown.Template.txt), when I browse the "Informations générales" section in english, then no rendering is displayed
- [ ] Given an english version of the homepage defined with the [AsciiDoc Article Template](https://asciidoctor.org/docs/asciidoc-article/), when I browse the "Informations générales" section in english, then the rendering is displayed and corresponds to the preview

##### Documentation Pages
- [ ] Given an english version of the page defined with the [file: Markdown Template.txt](https://github.com/gravitee-io/issues/files/6457963/Markdown.Template.txt), when I browse the "Documentation" section in english, then no rendering is displayed
- [ ] Given an english version of the page defined with the [AsciiDoc Article Template](https://asciidoctor.org/docs/asciidoc-article/), when I browse the "Documentation" section in english, then the rendering is displayed and corresponds to the preview

**Comment by gaetanmaisse** [comment]
@ibahloul please update the screenshots

**Comment by patelami** [comment]
created a ticket to address the bug around access control is showing env role instead of API role: https://github.com/gravitee-io/issues/issues/5789
