### ISSUE TITLE
[resource] [keycloak] OAuth2 with Keycloak returns 400 Bad Request

### ISSUE THREAD

**Issue by dmilcevski** [gravitee-io/issues#4735]
I am trying to use Keycloak as `Generic OAuth2 Authorization Server` resource for an API. The `Keycloak` server version is `8.0.0`.
When I try the introspect endpoint with CURL or Postman it returns the result. However, the gateway returns this debug output:

```
15:21:45.781 [vert.x-eventloop-thread-1] [] DEBUG i.g.r.o.g.OAuth2GenericResource - Introspect access token by requesting https://localhost:8080/auth/realms/apim/protocol/openid-connect/token/introspect [POST]
15:21:45.781 [vert.x-eventloop-thread-1] [] DEBUG i.g.r.o.g.OAuth2GenericResource - Set client authorization using HTTP header Authorization with value Basic MTkzMGQ0MzMtODk4NS00M2M1LTkzNDktMzU0ODU3MjlmYzEzOjUzNzE0YjUzLTA3MmEtNGE4Ny1iNWE0LWE4YTI3ODlhNjM4YQ==
15:21:45.795 [vert.x-eventloop-thread-1] [] DEBUG i.g.r.o.g.OAuth2GenericResource - Introspection endpoint returns a response with a 400 status code
```
I cannot see more logs to debug the issue. 
I cannot change the Keycloak version, since it is a service mantained by somebody else.

### Expected Behavior
Successful authorization of the API

### Current Behavior
The gateway response with:
```
<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx/1.17.8</center>
</body>
</html>
```

### Context

Trying to use OAuth2 client credential flow.

### Your Environment

* Version used: 3.4.0
* Browser Name and version: Safari
* Operating System and version: MacOS 10.15.7

Does anybody can help me debug the issue or how to solve it?

Thank you in advance!

**Comment by brasseld** [comment]
Hi @dmilcevski 

For your information, we are providing a dedicated keycloak plugin: 
https://download.gravitee.io/graviteeio-apim/plugins/resources/gravitee-resource-oauth2-provider-keycloak/gravitee-resource-oauth2-provider-keycloak-1.8.0.zip

Regards,

**Comment by dmilcevski** [comment]
@brasseld,

Thank you for the fast response.
I already tried with this provider but it didn't work. Do I need to included it in the `gateway` and `api` container?
I will try once again and get the logs in case it doesn't work.

**Comment by brasseld** [comment]
Yes, you have to put it in both gateway and api.

Maybe we should have to rebuild the plugin for your specific keycloak version.

**Comment by dmilcevski** [comment]
Thanks a lot for your help. Configuring the Keycloak plugin solved my issue. I had to uncheck `Local token validation`, but the rest worked nicely.
