### ISSUE TITLE
[portal] how to customize the management_url ?

### ISSUE THREAD

**Issue by jbouchery** [gravitee-io/issues#4739]
I'm actually using Gravitee APIM in Kubernetes and exposing the APIM Console behind a custom URL (https://my.awesome.url/console/) but i can't find where to configure my Portal to use this URL when i click on the Administration button.

### Expected Behavior
Going to https://my.awesome.url/console/ instead of https://my.awesome.url/

### Current Behavior
Going to https://my.awesome.url/ instead of https://my.awesome.url/console/

**Comment by brasseld** [comment]
From Console > Settings > Settings > Management URL

I think. there is something to do here, to configure it automatically from the helm chart.

**Comment by jbouchery** [comment]
Thanks @brasseld i thought this URL was the management API

Yes, i would like to override it in your Helm Charts. Where can i override it? In which Configmap?

Currently i have to override it with a modified curl call because of this issue: #4682

**Comment by brasseld** [comment]
No it is the URL of the Management Console, which is used by the portal for the Administration link.

To be tested, but I think you can add an `url` property within the `management` one:
https://github.com/gravitee-io/helm-charts/blob/master/apim/3.x/templates/ui/ui-configmap.yaml#L26

Let me know, or best, please provide a PR  once validated :)

**Comment by jbouchery** [comment]
Yup, i'll try it ! thank you :)

I'll definitely send a PR if this works !

**Comment by jbouchery** [comment]
Just tested to add my console URL in the UI configmap to test but doesn't work : 

```
"management": {
    "title": "{{ .Values.ui.managementTitle }}",
    "url": "https://my.awesome.url/console/"
}
```

**Comment by jbouchery** [comment]
Tested with 3.4.0, 3.3.4, 3.3.3 and 3.0.13 but doesn't change anything, the URL is good in the settings panel but i have to pretend to modify it then save it to work.

**Comment by brasseld** [comment]
ok let me check

**Comment by brasseld** [comment]
Ok, my bad,

Can you try with an envvar in 3.4 for the mgmt-api pod:

`gravitee.management.url=https://my.awesome.url/console/`

**Comment by jbouchery** [comment]
Working on 3.4 but not in 3.3.4.

Working when adding my url in the configmap (Locking it in the Settings panel).

Do you want me to make a PR with this URL in the configmap and the upgrade to 3.4.0?

**Comment by brasseld** [comment]
> Is it also possible to have this feature backported to 3.0.x for the LTS support? :)

Unfortunately, no. But it'll be part of the next LTS 3.5, end of next week.

**Comment by jbouchery** [comment]
> > Is it also possible to have this feature backported to 3.0.x for the LTS support? :)
> 
> Unfortunately, no. But it'll be part of the next LTS 3.5, end of next week.

Great news ! until that i'll do the PR to customize the console URL in the configmap.

Thanks !
