### ISSUE TITLE
[management] Dictionary start/stop API fails in case of empty Accept header

### ISSUE THREAD

**Issue by bursauxa** [gravitee-io/issues#4740]
The start/stop API for dictionaries fails when there is no Accept header on the POST.

### Expected Behavior

If there is no Accept header then the server should return whatever it wants.

As an extreme measure, the server could fail with HTTP 406 (content negotiation failed).

### Current Behavior

If there is no Accept header then the server returns HTTP 500, even though the start/stop operation is properly performed.

This behavior is not encountered on other APIs that I have noticed.

Relevant piece of stack trace:

```
Caused by: org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyWriter not found for media type=application/x-www-form-urlencoded, type=class io.gravitee.rest.api.model.configuration.dictionary.DictionaryEntity, genericType=class io.gravitee.rest.api.model.configuration.dictionary.DictionaryEntity.
```

### Steps to Reproduce (for bugs)

1. Set up: create a dynamic dictionary with name `testdict`
2. The following POST operation fails with HTTP 500:
```
curl -X POST http://gateway-url:8083/management/organizations/DEFAULT/environments/DEFAULT/configuration/dictionaries/testdict?action=START -H "Authorization: [omitted]"
```
3. Do the same curl a second time, you get HTTP 400 instead (this proves the dictionary was properly started, so the START action is not valid anymore)
4. The following POST operation succeeds:
```
curl -X POST http://gateway-url:8083/management/organizations/DEFAULT/environments/DEFAULT/configuration/dictionaries/testdict?action=STOP -H "Authorization: [omitted]" -H "Accept: application/json"
```

### Your Environment

Gravitee version 3.2.1

**Comment by gcusnieux** [comment]
Can't synchronise dynamic properties.
`ERROR i.g.r.a.s.d.DictionaryRefresher - [testdict] Unexpected error while getting dictionary’s properties from provider: custom`

**Comment by gcusnieux** [comment]
Ok, fix with https://github.com/gravitee-io/issues/issues/4535
We need to merge the 1.30.29 tag
