### ISSUE TITLE
[reporter][elasticsearch] Auto-enable geo-ip, user-agent when Elasticsearch >= 7.x

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4744]
From ES 7, the ingest plugins are bundled in the installation so we should enable the pipeline creations by default.

The configuration remains useful for the previous versions.

**Comment by aelamrani** [comment]
Could be interesting to have a note on the migration guide to inform of this change, wdyt?

**Comment by ytvnr** [comment]
> Could be interesting to have a note on the migration guide to inform of this change, wdyt?

Are you talking about adding a note [here](https://github.com/gravitee-io/release/tree/master/upgrades/3.x/3.5.0) ? or at another place ?

**Comment by aelamrani** [comment]
Yes but 3.6 not 3.5
