### ISSUE TITLE
[management] Console dashboard page

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4747]
The idea here is to provide a dashboard page to users on the console to provide widgets contextualized to the connected user.

Proposition of the dashboard page:
- Widget deploy events
- Widget API numbers
- Widget req / s ; avg ; ./.. (existing widget)
- Chart with requests on the last day
- Widget API quality 
- Widget status workflow

Statistics for the last 5 minutes?

If possible, we should replace existing widgets with WebComponents widgets

**Comment by phiz71** [comment]
missing release.json modification
