### ISSUE TITLE
[management] Analysis of missing components

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4748]
The goal here is to analyze the missing components to create in our library: https://components.gravitee.io/

The missing components has to be listed in this issue in comments.

**Comment by gaetanmaisse** [comment]
Closing this one as we now have 2 UI libs, the end goal will be to provide:
 - a UI toolkit with Gravitee branding for the consoles app - https://github.com/gravitee-io/gravitee-ui-particles

 - a Gravitee agnostic set of component for APIM Dev Portal - https://github.com/gravitee-io/gravitee-ui-components
