### ISSUE TITLE
[portal] Flag an app as deleted instead of delete it

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#475]
delete an app generates errors if a subscription exists.

### Possible Solution

do not physically delete the app, prefer flag the app as archived.

### Steps to Reproduce (for bugs)

1. create an api, an app, a plan and a subscription between the app and the api
2. delete the app
3. got to subscriptions menu -> error
4. try to close the plan -> error

### Your Environment

* Version used: 1.3.3

**Comment by brasseld** [comment]
See https://github.com/gravitee-io/issues/issues/185
