### ISSUE TITLE
[policy] [oauth2] Protect backend endpoints by proxying the call through gateway and enforce Oauth policy

### ISSUE THREAD

**Issue by kkatta** [gravitee-io/issues#476]
Usecase: Protect backend endpoints by proxying the call through gateway and enforce Oauth policy.

Installed the gravitee oauth authorization server.
Trying out client_credentials scenario. I am able to get an access token. using /oauth/token
Now I wanted to check the token validation by using /oauth/check_token
I have passed "token=7af3a7a9-4c16-4c43-a110-de3ac82e76c8" (request body)
Also, passed Authorization header "Basic dGVzdDp0ZXN0" (basically base64 encoded client:secret which I used in /oauth/token api call)

I get a 403 {
  "error": "access_denied",
  "error_description": "Access is denied"
}

Am I using the right api and steps?

Thanks
Kishore

**Comment by brasseld** [comment]
Hi @kkatta,

One question: did you configure an OAuth2 resource to be used by the OAuth2 policy ?
If yes, how did you configure it ?

Can you share with us an export of your API ?

Thanks,

**Comment by brasseld** [comment]
Also, we are on the way to write tutorials about OAuth2 / JWT integration using our new Gravitee.io Access Management (oauth2, openid connect core, jwt, ...)  with Gravitee.io API Management

**Comment by kkatta** [comment]
Hi Brassel,

I haven't configured a resource yet. Firstly, I wanted to try out the authorization server endpoints to acquainted with. So, I can leverage them in my usecase.

Do you have anything which I missed. I am not sure if I made it clear.

Thanks
Kishore

**Comment by brasseld** [comment]
Did you have a try by passing this header instead?
`Authorization: Basic cmVzb3VyY2UxOnJlc291cmNlMQ==`

**Comment by tcompiegne** [comment]
Hi @kkatta,

We enforce access controls to the `check_token`endpoint to allow only oauth client with `RESOURCE_SERVER` role to validate an access token.

`<intercept-url pattern="/oauth/check_token" access="hasRole('ROLE_RESOURCE_SERVER')" />`

You can use the following oauth client to check your access token validation : 

`<oauth:client client-id="resource1" secret="resource1" authorized-grant-types="client_credentials" authorities="ROLE_RESOURCE_SERVER" scope="read,write" autoapprove="true" />`

As @brasseld said, the https://github.com/gravitee-io/gravitee-oauth2-server is just for testing purpose for our internal scenario. Stay tuned for the `Gravitee.io Access Management`project.

Regards

**Comment by kkatta** [comment]
Hi @tcompiegne @brasseld  ,

Thanks for the tip. I was able to verify the 'check_token' individually and I see a 200 OK which is good.

Now, going a bit ahead I have now created an oauth2 type resource and I am referring the same within the Oauth policy. Now, when I invoke my api with the token passed I get a 401 Unauthorized.

Request: GET http://localhost:8082/graviteepetstore/pet/1000?token=e44eee27-ce2f-4e35-915b-f279976131c0
Response: {
  "message": "Unauthorized",
  "http_status_code": 401
}

Attached is my api project. Can you please help out. Also, where I can see the http wire information captured to introspect my payload and headers that are getting used after enforcement of every policy in the policy chain.
Note: I created api using a swagger file
Thanks
Kishore
[petstoreAPI.zip](https://github.com/gravitee-io/issues/files/819229/petstoreAPI.zip)

**Comment by tcompiegne** [comment]
Hi @kkatta ,

I see that you are using an `API Key Plan`, did you set the `X-Gravitee-Api-Key' HTTP header ?

Regards

**Comment by kkatta** [comment]
oops..!! Thanks for pointing. Not sure how I missed that.

**Comment by brasseld** [comment]
Hi @tcompiegne,

Is it ok for you ? Were you able to configure your API with OAuth2 ?

Regards,

**Comment by kkatta** [comment]
Yes, I was able to secure the api with oauth2. Just tried out the client credentials grant type.

Thanks for your help.
Kishore

**Comment by brasseld** [comment]
You're welcome @kkatta,

What was the difficult part of the configuration according to you ?
We know that we have to improve documentation, etc, ... but do you see something else to improve ?

Thanks for your feedback !

**Comment by kkatta** [comment]
@brasseld ,
The difficult part was to figure out what values I should provide when configuring oauth resource. Some hints near the resource configuration text boxes should help user understand a bit better.

Also, I didn't find oauth server api request/response (headers+paylaod) logged anywhere. I believe it is important especially when we talk to third party authorizaton servers as each oauth servers impl spec might be a bit different.

Thanks
Kishore

**Comment by tcompiegne** [comment]
Hi @kkatta very appreciate your feedback.

Thanks !

**Comment by NicolasGeraud** [comment]
moved to gravitee-io/gravitee-docs#70
