### ISSUE TITLE
[management][multi-env]Default application creation

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#4776]
In a multi-environment context, when a user signs in the console, he can access more than one environment.
So the rule for default application creation is a problem since we don't know on which environment the application has to be created.

With this issue, we want to move the creation of the default application only after a first login on a portal.

**Comment by ytvnr** [comment]
As discussed with @aelamrani  and @phiz71 , a default application will be created on the first user's connection for all environment on which he has a role
