### ISSUE TITLE
Client ID and Client Secret are not shown in developer portal

### ISSUE THREAD

**Issue by pavanelthepumisc** [gravitee-io/issues#4779]
Client ID and Client Secret are not shown in developer portal

### Expected Behavior
Client ID and Client Secret should be shown in developer portal so that they can autorize the API

### Current Behavior
Client ID and Client Secret are not shown in developer portal

### Steps to Reproduce (for bugs)
1. Add and API and create a Plan with oauth2 (keycloak adapter)
2. Subscribe to the API
3. In developer portal, client id and secret are not visible on the API instead some random api key is showing

![image](https://user-images.githubusercontent.com/29723106/101879519-77ce6100-3bb7-11eb-9284-3e1321785fa3.png)

### Your Environment

* Version used:
* Version used: 3.4.0
* Keycloak version: 11.0.2
* Browser Name and version: Chrome Version 87.0.4280.88 (Official Build) (x86_64)
* Operating System and version: macOS Catalina

**Comment by aelamrani** [comment]
Are you able to show us the subscription on the console side?

**Comment by pavanelthepumisc** [comment]
This is the plan:

![image](https://user-images.githubusercontent.com/29723106/101881260-2a9fbe80-3bba-11eb-847b-c77ddfbd93dc.png)

This is the subscription :aelamrani 

![image](https://user-images.githubusercontent.com/29723106/101881329-430fd900-3bba-11eb-82c2-899885006902.png)

**Comment by aelamrani** [comment]
I don't understand the purpose of this issue actually.

You are talking about un plan OAuth2 and you are looking for client credentials on the subscription?

The client infos are defined at the application level, not the subscription level, so what would you expect there?

**Comment by pavanelthepumisc** [comment]
@aelamrani I've a plan with keycloak as identity provider. I need to give the client id and client secret to developer so that he can try my API. How would I give the client id and client secret to the developer o developer portal?

**Comment by aelamrani** [comment]
They can access it in their application no?

**Comment by phiz71** [comment]
In Portal, you can access client ID and client secret in the detail page of your application.
However, for the moment, this is not possible for Simple Application. So we are going to fix it, since a simple application can have a client id

**Comment by pavanelthepumisc** [comment]
In which release this bug will be fixed. I can see that 3.5 version is released but this is not fixed yet.

**Comment by phiz71** [comment]
Hi @pavanelthepumisc , this issue will be fixed in the next [3.4.3](https://github.com/gravitee-io/issues/milestone/327) version and then merged into upper versions: 3.5.1 and 3.6
