### ISSUE TITLE
How to call external SOAP/REST API?

### ISSUE THREAD

**Issue by kkatta** [gravitee-io/issues#478]
Hi,

I am trying to design a mashup scenario where I need to call out a SOAP and a REST API outside gateway.

Do, we have any sample groovy script to call out REST API from groovy. I tried using import groovyx.net.http.RESTClient but it is throwing a groovy runtime startup error. Probably the specific package is not supported. Alternatively, I didn't find any service callout policy is there an equivalent.

Any suggestions/thoughts?

Thanks
Kishore

**Comment by brasseld** [comment]
Hi @kkatta,

I need to understand what you want to achieve exactly:
* Calling a SOAP WS or Rest API from a policy? Invoked endpoint (API's gateway configuration) is not one of them ?
* Calling a SOAP WS or Rest API and apply transformation (rest-to-soap, ...) ? 

About your groovy error, please provide a stacktrace in an other issue specific to the groovy policy.

Thanks a lot.

**Comment by kkatta** [comment]
Hi @brasseld ,

Yeah, I need to call both SOAP WS and a REST API. Get the response from these API calls compose a payload and finally prepare a json. Invoked endpoints are not part of gateway configuration. Basically, a composition of services and enrichment pattern.

Will raise a different issue for groovy.

Thanks
Kishore

**Comment by brasseld** [comment]
Ok, I have a better understanding of your concerns.
So, actually, we do not provide a callout policy. The only policy we are providing to do such thing is the groovy policy (and we are also thinking about a JS policy).
Do you think a callout policy will be accurate ? What will be the purpose of such policy and how to configure it, do you have any clue ?

**Comment by kkatta** [comment]
I believe a JS policy would be a more convenient way to consume external REST api, Basically, callout meaning ability to write a script and call external api.

**Comment by brasseld** [comment]
Ok I'm closing this issue and create a new one for policy-javascript implementation
