### ISSUE TITLE
[management] default resource icon

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#4789]
### Expected Behavior
we need a default icon for resources

<img width="956" alt="Capture d’écran 2020-12-13 à 17 36 52" src="https://user-images.githubusercontent.com/1028285/102017940-2adebc00-3d6a-11eb-9bdf-ba799c7bcb3e.png">

### Your Environment

* Version used: 3.4.1

**Comment by leleueri** [comment]
Default Icon was added in the HEAD of master branch for the inline authentication provider.
Is it the purpose of this issue or do you expect the display of a default icon if the plugin doesn't embed one (whatever if it is a resource or a policy) ?

**Comment by NicolasGeraud** [comment]
Perfect. We now just have to release this resource.

**Comment by aelamrani** [comment]
It could be interesting to handle legacy resource plugins and display a default logo as we do on custom policies without logo.
