### ISSUE TITLE
[management] [jdbc] better way to manage connection pools

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#4793]
Since 3.6.x version, it seems that the max open connection is reached very often and no more SQL requests can be done via the REST-API.

We must find a way to shared resources (connection pool) between repository/reporter/identity provider if they use the same database.

**Comment by leleueri** [comment]
I have change the default values to set a minimum connection in the pool to 0 with a TTL of 30s.
Providing  a dedicated pool for each domain seems a good thing to guarantee a fair access to the DB.
