### ISSUE TITLE
[management] Access-Control-Allow-Origin regex fail and do not conform with rfc6454 and rfc3986

### ISSUE THREAD

**Issue by YoranSys** [gravitee-io/issues#4796]
### Expected Behavior

The Access-Control-Allow-Origin have to conform with rfc3986 if we refer to the [rfc6454 section-7.1] (https://tools.ietf.org/html/rfc6454#section-7.1) but the current 3.4.X regex break this : 

https://github.com/gravitee-io/gravitee-management-rest-api/blob/3.4.x/gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java#L127

```java
    private static final Pattern CORS_REGEX_PATTERN = Pattern.compile("^(?:(?:[htps\\(\\)?\\|]+):\\/\\/)*(?:[\\w\\(\\)\\[\\]\\{\\}?\\|.*-](?:(?:[?+*]|\\{\\d+(?:,\\d*)?\\}))?)+(?:[a-zA-Z0-9]{2,6})?(?::\\d{1,5})?$");
```

A regex based on the [rfc3986 regex example](https://tools.ietf.org/html/rfc3986#appendix-B) will be like this:
```regex
(^(([^:\/?#]+):)?(\/\/([^\/?#]*))?)
```

This will allow ionic and other scheme used by framework on mobile apps for CORS 'allow origin' value :  
- https://ionicframework.com/docs/troubleshooting/cors#ionic-webview-3-x-plugin-on-cordova
![image](https://user-images.githubusercontent.com/11197007/102197603-a901a680-3ec1-11eb-94bb-5f278095eba6.png)
![image](https://user-images.githubusercontent.com/11197007/102197642-b0c14b00-3ec1-11eb-8aaa-646a2dd7c6f8.png)

A second problem is at import time the check pass with an invalid regex (the current one) and when we import on an already created API check failed, same if we modify the API. Tests and checks as to be the same as the import time and update time.

### Current Behavior
I can import an API definition with CORS alllow origin with this scheme : 
> ionic://myapp 

But i can't export and update it without having an error 400 with the message: 
> ionic://myapp is not valid as an 'allow origin' value

### Steps to Reproduce (for bugs)

1. Configure CORS
2. Allow-origin: `ionic://localhost`
3. Export and import API
4. You will have an update/import error 

### Your Environment
* Version used: APIM 3.4.2

**Comment by YoranSys** [comment]
It seem to be this regex : 
- https://github.com/gravitee-io/gravitee-management-rest-api/blob/3.4.x/gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java#L127

**Comment by YoranSys** [comment]
PR: https://github.com/gravitee-io/gravitee-management-rest-api/pull/1340

**Comment by brasseld** [comment]
Hi @YoranSys 

Your PR looks good to me, thanks for it.
But according to what I've seen from the code, you should face the same kind of issues on the UI side. did you check it ?

**Comment by YoranSys** [comment]
Hi @brasseld , 
Nope, I will check that, thank you.

**Comment by YoranSys** [comment]
Here are both PR :
- https://github.com/gravitee-io/gravitee-management-webui/pull/1440
- https://github.com/gravitee-io/gravitee-management-rest-api/pull/1340

**Comment by YoranSys** [comment]
Hi, @brasseld  when do you think it will be integrated to gravitee ?

**Comment by leleueri** [comment]
Thanks you for your contribution :)
