### ISSUE TITLE
[management] An api-key can not be reactivated for a closed plan

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#4798]
When re-activating an api-key for a closed plan, consumer can still call the API

**Comment by phiz71** [comment]
Not reproductible in 3.5.x

**Comment by phiz71** [comment]
Actually, I managed to reproduce it but I had a keyless plan on the API, so it's not a bug.
However, it should not be possible to reactivate an apikey on a closed subscription/plan.
