### ISSUE TITLE
[management]invalid policy configuration error when migrate from policy design v1 to v2

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#4805]
Migration to policy studio failed with the error 'invalid policy configuration" (see attached image).
The problem here is related to the json-validation policy. (may there are the same issue wit others policies)

In attachment an export of my API to reproduce the issue.
[Swagger-Petstore-1-0-0.txt](https://github.com/gravitee-io/issues/files/5695343/Swagger-Petstore-1-0-0.txt)
![design-v1-to-v2](https://user-images.githubusercontent.com/3110552/102207282-26331880-3ece-11eb-9a98-13b0b7bf43e6.png)

**Comment by phiz71** [comment]
pb with the version of the plugin and the database.
