### ISSUE TITLE
[question] Does the gateway component run standalone when backend failed?

### ISSUE THREAD

**Issue by samatthias** [gravitee-io/issues#4838]
Dear Gravitee Team,

many thanks for such a great piece of software. I really enjoy working with gravitee.
According to this question here, about clustering gravitee: https://github.com/gravitee-io/issues/issues/1227, my questions goes in a similar direction: When the backend component fails - this means jdbc database / redis / mongodb - is the gateway component able to run standalone (without the backend) for a certain amount of time (let's say till the backend is fully restored , recovered and online again)?

Our scenario will be like this: We want to scale out just the gateway component i.e. spread across our datacenters, but just one backend component, one api management component, one ui  component - so there is no high availability jdbc database cluster like oracle/sqlserver/mariadb/mysql, no mongodb cluster, no redis cluster. Is this scenario feasible respectively is this a good way to go? Is this a proper use case of gravitees component architecture?

Thanks for answering my questions.

Best regards
Matt

**Comment by brasseld** [comment]
Hi @samatthias 

Thanks for your kind comment.

Regarding your question, can you tell me what are you calling the "backend" ?
If it is the backend API (ie. an endpoint within Gravitee), the gateway is still operating,

> Our scenario will be like this: We want to scale out just the gateway component i.e. spread across our datacenters, but just one backend component, one api management component, one ui component - so there is no high availability jdbc database cluster like oracle/sqlserver/mariadb/mysql, no mongodb cluster, no redis cluster. Is this scenario feasible respectively is this a good way to go? Is this a proper use case of gravitees component architecture?

It mainly depends what you're doing with Gravitee. If you're looking to apply some rate-limit or quota restrictions, you would need a datastorage to persist counters. If not, the gateway can live by itself.

Regards,

**Comment by samatthias** [comment]
Dear @brasseld 

I refer to "Configure Repositories" (https://docs.gravitee.io/apim/3.x/apim_installguide_repositories.html) as "backends". Sorry for messing up terminologies - my fault.

What happens if there is a rate limit / quote and the "repository" like mongodb is not running? Does the request fail? 

Best regards
Matt

**Comment by brasseld** [comment]
> What happens if there is a rate limit / quote and the "repository" like mongodb is not running? Does the request fail?

Yes the request fail. But it could be a nice enhancement to continue request processing if the repository is down for rate-limit/ quota.

That would probably be an option at the gateway level, and not at the policy level.

Wdyt ?

Regards,

**Comment by samatthias** [comment]
It would make sense for high availability scenarios, so you don't have to recover the "repository" as fast as possible for normal operating. It would be a nice feature if you could keep all data in memory on the gateway side.

best regards
Matt

**Comment by brasseld** [comment]
@samatthias you can still rely on the "async" mode for such purpose.
Counters are then stored locally and sync with repository (if possible) each X seconds.
