### ISSUE TITLE
[console][analytics] JS error on platform dashboards

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#4841]
As user `api1`, when clicking on "Dashboard" then I get this error
It happens only for 'global dashboard`: not for 'geo dashboard' neither 'user dashboard'.
It is due to the first widget.
There is a difference between running from source or running from dist.

On nightly:
![image](https://user-images.githubusercontent.com/13161768/102903302-6c5d1e80-4470-11eb-9ba1-76332d05262e.png)

On localhost:
![image](https://user-images.githubusercontent.com/13161768/102903414-9adaf980-4470-11eb-82a9-b2f39e99e6c9.png)

**Comment by mouligno** [comment]
Couldn't reproduce anymore
