### ISSUE TITLE
Gravitee APIM multiple Oauth2 plan doesn't work

### ISSUE THREAD

**Issue by arnaudtardy** [gravitee-io/issues#4849]
Hello,
I'm trying to add to 2 or more Oauth2 plans and I'm having trouble with it
 
### Expected Behavior
I was expecting to  add another keycloak resource (other realm, on the same keycloak) to my api, create another plan with this new resource.
And then to validate as usual, by subscribing on the plan associated to each realm

### Current Behavior
Adding the new resource and the plan is not a problem.
But it doesn't work at all ...
 - With the keycloak adapter, validation of the initial plan is still working fine. but on the new plan, the gateway is trying to validate the public key of the other realm, every call is redirected to the first realm.
Event :
(23-12-2020 09:06:15.663 [vert.x-eventloop-thread-0] [] ERROR o.k.a.rotation.AdapterTokenVerifier - Didn't find publicKey for kid: wymGNEUnHH...)
- I have also tried, with the Generic Oauth2 resource, it's worse, the first plan doesn't validate anymore. 

### Steps to Reproduce (for bugs)
1. Within a same keycloak, create two separate realms.
2. add a resource for each realm to an API.
3. activate a plan Oauth2 for each,
4. subscribe an application from each realm on those two plans.
5. test, You should like me, have one application, which doesn't get validation and an error with realm public key

### Context
My Goal is to set at least for 4 resources (4 realms) to most of my APIs, and to manage a keycloak federated environment, and APIs consumed by applications from those 4 realms.

### Your Environment
* APIM 1.30.29 with keycloak adapter: 1.8.0
* keycloak : 11.0.3
Both installed with helm charts on a kubernetes cluster.

**Comment by brasseld** [comment]
Hi @arnaudtardy 

Keycloak adapter 1.8.0 as been built for Keycloak 4.6.0.Final
The best is to checkout the module, change the version and build the plugin specifically for your keycloak version.

Unfortunately, the keycloak adapter provided by the keycloak team is not compatible with different versions.

Regards,

**Comment by arnaudtardy** [comment]
Hi @brasseld, 

I tried to rebuild it with 9.0.3 it doesn't change anything for me. I will also try with 11.0.3 and will let you know.
And has mentioned, I've also tried to use the Oauth2 generic adapter, with almost the same result in the end.

Regards

**Comment by aelamrani** [comment]
Are you defining selection rules in your plans?

**Comment by arnaudtardy** [comment]
Hi @aelamrani,

No, with 1 plan, it wasn't useful, and when I tried to add the other, I was thinking it's the same keycloak instance so the issuer, 
but it's not.
You might right, I will try and let know

Best Regards

**Comment by arnaudtardy** [comment]
Hi again, 

Indeed selection rules did the trick.
Sorry for the bother.

Best Regards
