### ISSUE TITLE
apim-management-ui 3.4.2: Error Property [Flows] is not recognized as a valid property

### ISSUE THREAD

**Issue by soridis-dev** [gravitee-io/issues#4851]
I've just download the APIM 3.4.2 version
I dropped the gravitee mongo db before starting management-rest-api.

From the management-ui, I create a test API and a plan.
The creation of the plan is OK but when i want to update it, i've always the following error:
Property [Flows] is not recognized as a valid property
 
### Expected Behavior
I expect an update of the plan without error

### Current Behavior
Error "Property [Flows] is not recognized as a valid property"
When i update a plan.
 
### Possible Solution
Using the 3.4.0 version of management-ui

### Steps to Reproduce (for bugs)

creating an api plan and update it

### Context
I simply want to update an api plan

### Your Environment
Windows 10 pro
Mogo DB 4.4
Openjdk 11

**Comment by phiz71** [comment]
hi @soridis-dev, it is a known issue : #4761. It has been fixed in 3.5 and will be backport in 3.4.3 (#4783)
