### ISSUE TITLE
[Management] Unable to finalize user invitation

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#4858]
If a user click on the registration link send by email thanks to group invitation, the form isn't properly displayed.

![image](https://user-images.githubusercontent.com/3110552/103341876-53fc8d80-4a88-11eb-88b5-0db095ae3522.png)

### Steps to Reproduce (for bugs)
1. Create a group
2. Invite a user by email
3. click on the registration link received by email

### Your Environment
* Version used : 3.0.x & 3.4.x

**Comment by tcompiegne** [comment]
Some notes : 

- If the account doesn't exist and if the password does not comply with the password policy, the user is still created with the invitation
- To assign a user to a group, we check if the user already exist via its email thanks to the search engine, but for security reason we cannot search by email, so the invitation email is always sent
