### ISSUE TITLE
[portal] Deleting an application with subscription breaks an API's subscription list

### ISSUE THREAD

**Issue by alessandrousseglioviretta** [gravitee-io/issues#486]
### Current Behavior
Deleting an application to which a subscription is linked breaks the API's subscription link: 

`/apis/<api_id>/settings/subscriptions`

The issue can be noticed when clicking on the `Subscriptions` button of an API after deleting an application that has a subscription to one of the API's plan. In this case, the red (error) toast will display a message like this one "_Application [3fbbe4da-684f-4eeb-bbe4-da684f3eebc7] can not be found_".

### Expected Behavior
I assume that deleting applications should _never_ result in breaking links or corrupting databases.

### Possible solution
Unlinking the subscription from the plan to be deleted might help.

**Comment by brasseld** [comment]
Hi @alessandrousseglioviretta,

This will be fix in next release (scheduled for next tuesday) thankks to https://github.com/gravitee-io/issues/issues/185.

Thanks

**Comment by ufukg** [comment]
I think it is still an issue, not resolved yet. 
I've deleted an application successfully but now while I try to get into subscription menu of the related API it says "An error occurs while trying to find an application using its ID 495ec14f-22ff-48f4-9ec1-4f22ffd8f464".

**Comment by brasseld** [comment]
Hi @ufukg 

Can you give us more clue about your context / environment / version / ...

**Comment by ufukg** [comment]
Hi @brasseld
My Gravitee.io version is "1.21.2". We're running the Gravity on Linux.

**Comment by ufukg** [comment]
Hi @brasseld
My Gravitee.io version is "1.21.2". We're running the Gravity on Linux.
