### ISSUE TITLE
[policy] [rest-to-soap] do not override request path info

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#4860]
With the new concept of Flow, we rely on the request path info to select the correct flow to execute the policy chain.

Unfortunately the rest to soap policy remove the request path to avoid 404 response from the backend.

https://github.com/gravitee-io/gravitee-policy-rest-to-soap/blob/master/src/main/java/io/gravitee/policy/rest2soap/RestToSoapTransformerPolicy.java#L148

We should rely on the `ExecutionContext.ATTR_REQUEST_ENDPOINT` attribute (like the dynamic policy) instead of the request object.

https://github.com/gravitee-io/gravitee-policy-dynamic-routing/blob/master/src/main/java/io/gravitee/policy/dynamicrouting/DynamicRoutingPolicy.java#L121

**Comment by leleueri** [comment]
there are also an issue during the WSDL import, xml-to-json policy is defined in the request step of the flow. (it should be in response step)

**Comment by NicolasGeraud** [comment]
I've created a dedicated issue for this one
see #4879
