### ISSUE TITLE
[management] Display groups in user account information

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4870]
Display the user groups to the user on his screen:

![Capture d’écran 2021-04-09 à 13 59 40](https://user-images.githubusercontent.com/1580262/114176756-e4762400-993b-11eb-9449-ade7d9c50994.png)

Tests:

- [ ] Groups of the user are correctly displayed

**Comment by patelami** [comment]
@aelamrani: I can see the user detail in A, but I don't see any user group detail in B. is this expected? 

<img width="1425" alt="Screenshot 2021-04-09 at 15 43 37" src="https://user-images.githubusercontent.com/14215437/114198178-f3b09e00-994a-11eb-832f-9979d95dc60d.png">

**Comment by aelamrani** [comment]
@patelami yes it is, meaning you don't have any groups attached to your user

**Comment by patelami** [comment]
env: nightly

As a user, I should be able to see groups assigned to the user in the user information section. PASS

https://github.com/gravitee-io/issues/issues/5401#issue-855873211

https://github.com/gravitee-io/issues/issues/5402#issue-855901647


https://github.com/gravitee-io/issues/issues/5401#issue-855873211
