### ISSUE TITLE
[management] Allow to navigate to previous / next log

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4871]
When selecting a log, we want to be able to navigate on previous / next log without going back in the list of logs.

![Capture d’écran 2021-04-09 à 13 56 04](https://user-images.githubusercontent.com/1580262/114176404-6154ce00-993b-11eb-8695-e0c4c84f44ca.png)

Tests:

- [ ] We should be able to navigate on previous / next logs from the detail of a log
- [ ] The button should be disabled when navigation is not possible

**Comment by patelami** [comment]
env: nightly 

As a user, I should be able to move to the next and previous page in the logs. PASS

As a user, I should see the button should get greyed out when I am on the end of the page PASS
