### ISSUE TITLE
[management-api] Response templates are ignored when importing API

### ISSUE THREAD

**Issue by nkilian-inv** [gravitee-io/issues#4884]
### Expected Behavior
We upgraded from v3.3 to v3.4.2. Before the upgrade, response templates were properly imported when performing an import of a previously exported API (using the "Import" button in Management Console).

### Current Behavior
After the upgrade, response templates are still part of the export, but are ignored during an import. Instead, all previously configured response templates are being deleted during the import (although the imported JSON file describing the API contains them and has been exported using the same version of Gravitee).

### Steps to Reproduce (for bugs)
1. Export and existing API with response templates configured
2. Import the exported JSON file again
3. The response templates are gone

### Context
I was trying to backup an API and imported the backed up API again.

### Your Environment
Gravitee APIM 3.4.2

**Comment by phiz71** [comment]
Hi @nkilian-inv, I'm not able to reproduce your problem.
I created an API, added 2 response templates, then I exported the API and re-imported it. The response templates have not been deleted.
Could you try again and check if you have some error in logs ?
Maybe, you could share an export ?
