### ISSUE TITLE
[console] change event name in API audit history

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#4886]
On APIM Console, in API audit history, PUBLISH_API stands for "the API has been deployed on the gateway".
But to publish an API means: "make the API available on APIM Portal".

As it can be confusing, we should change the history screen to display DEPLOY_API instead of PUBLISH_API.
![image](https://user-images.githubusercontent.com/13161768/104042930-5d4dce80-51db-11eb-931e-268947fbd9d7.png)

**Comment by brasseld** [comment]
Can be fixed as part of https://github.com/gravitee-io/issues/issues/4749 ?
