### ISSUE TITLE
[management] Dashboard of all alerts

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4892]
As a user with the Alert-READ permission, I want to have a specific dashboard to display some information about my alerts.
This dashboard should appear on the main page.
![image](https://user-images.githubusercontent.com/13161768/110959012-8f9bb980-834d-11eb-862e-cf4bffe9b349.png)

This dashboard should display :
 - number of alerts by severity. 
 - number of alerts by alert trigger.
 - number of alerts by type & group by severity

On alert triggers, it should be possible to navigate to the alert history
![image](https://user-images.githubusercontent.com/13161768/110958558-1e5c0680-834d-11eb-8ea3-1f70f08d6072.png)

Note: How to create an alert documentation: https://docs.gravitee.io/ae/apim_api.html 

**Acceptance Criteria:**
1. As a user, I should be able to get the platform level alerts on the alert dashboard.
List an example of platform level alerts below. 

2. As a user, the alert dashboards is static and the user is not able to customise the dashboard

3. As an Alert, I should have one of the following severity type assigned to me 
```
1. critical  
2. warning
3. info
```

4. As a user, I should be able to see the alert by its trigger type:
Example: 
If a user has created an alert named "Yann Alert",  then we should be able to see how many times the "Yann Alert" has occurred on the dashboard

5. As a user, the alerts I see on the dashboard are grouped by their type and severity 
Example: 
health check type alerts are grouped
show user maximum 48 alerts of status 404 not found

6.As a user, I should be able to delete an alert.

**Comment by patelami** [comment]
Questions: 

- To be able to test this, How will we create an alert? 
- How many maximum numbers of alerts we will show per page? (Pagination will not implemented)
- What is a platform level alert?

**Comment by patelami** [comment]
Env: Local (master)

As a user, I should be able to get the platform level alerts on the alert dashboard.

As a user, the alert dashboards is static and the user is not able to customise the dashboard **PASS**

As an Alert, I should have one of the following severity type assigned to me

1. critical  
2. warning
3. info

As a user, I should be able to see the alert by its trigger type:
Example:
If a user has created an alert named "Yann Alert", then we should be able to see how many times the "Yann Alert" has occurred on the dashboard

As a user, the alerts I see on the dashboard are grouped by their type and severity
Example:
health check type alerts are grouped
show user maximum 48 alerts of status 404 not found

6. As a user, I should be able to delete an alert: **Pass**
7. As a user, I should be able to delete an alert created as a templet: **Pass**

**Comment by aelamrani** [comment]
@patelami can you please give an update of the status of this US?

**Comment by patelami** [comment]
This has tested on local dev env and it is good to go live. We are unable to test this on nightly.
