### ISSUE TITLE
[management] Private page

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4893]
It should be interesting to provide an easy way to have the concept of "private" on a page.
Currently, we have to define groups to handle this simple use case and hide some pages to anonymous users.

As a documentation writer, I want to be able to easily hide a page from anonymous users.
On the creation page, we should have a checkbox, selected by default, with the label "allow access to anonymous user".
On the edition page, in the configuration tab, we should have a checkbox, selected by default, with the label "allow access to anonymous user".

If the checkbox is selected, the current behavior remains the same.
If the checkbox is not selected, then the page should not be displayed on the APIM Portal for anonymous users.

On the APIM Management side, we should add an icon in the pages list, as it is done for APIs:
- a lock for private page
- an earth for public page

In this issue, we only focus on Markdown pages and Swagger pages.

**Comment by gcusnieux** [comment]
This feature need new functionnal review witth https://github.com/gravitee-io/issues/issues/4563
