### ISSUE TITLE
[policy] [generate-http-signature] Genrate HTTP Signature policy

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4899]
# User Story

# Expected behavior

- Be able to choose the signature scheme
    - Signature HTTP Header will add a header to the request: `Signature: signature-content`
    - Signature HTTP Authentication scheme will add an authorization header: `Authorization: Signature signature-content`
- keyId and secret used to sign the signature content
- Algorithm choice (in HMAC algorithms)
- Be able to use specific headers to sign
- Be able to include created timestamp. It will add the `created` field to the signature, the `(created)` headers to the list, and be used to sign
- Be able to include expires timestamp. It will add the `expires` field to the signature, the `(expires)` headers to the list, and be used to sign
- Be able to define a validity duration for the signature if `expires` is set to true

# Further Information
- When it's impossible to generate a signature from the configuration: then fail with 400 - Bad request
- policy category: Security

# Tests

## Design studio

- [ ] When `expires` is set to true, then validity duration input should be displayed

### Scheme
- [ ] Signature HTTP Header will add a header to the request: `Signature: signature-content`
- [ ] Signature HTTP Authentication scheme will add an authorization header: `Authorization: Signature signature-content`

### Headers
- [ ] When adding a header, if it is present in the request, we should not have error. (insensitive case)
- [ ] When adding a header absent from the request, then we should have a 400 error

### Created and Expires
- [ ] When activating those options, then the created or expires should be added to the fields and headers of the signature

### API Properties & EL
- [ ] I can use a property for `secret` and retrieve it from Expression language
- [ ] I can use an encrypted property for `secret` and retrieve it from Expression language

**Comment by LiliaEn** [comment]
The following scenarios were performed on nightly environment using a Keyless plan and an API Key Plan (separately)

- “Signature" HTTP Authentication Scheme + HMAC_SHA256 
- “Signature" HTTP Authentication Scheme + HMAC_SHA256 + Header: Host
- “Signature" HTTP Authentication Scheme + HMAC_SHA1
- “Signature" HTTP Authentication Scheme + HMAC_SHA384
- “Signature" HTTP Authentication Scheme + HMAC_SHA512
- “Signature" HTTP Authentication Scheme + HMAC_SHA512 + Header: Path
- “Signature" HTTP Authentication Scheme + HMAC_SHA512 + Header: Digest
- "Signature" HTTP Header + HMAC_SHA1
- "Signature" HTTP Header +HMAC_SHA256
- “Signature" HTTP Header +HMAC_SHA384
- “Signature" HTTP Header +HMAC_SHA512
- “Signature" HTTP Header +HMAC_SHA512
- “Signature" HTTP Header +HMAC_SHA512 + Header: Path
- Disabled “created” timestamp to check it's not displayed in the signature
- Disabled “expires” timestamp to check it's not displayed in the signature and also Validity duration field was hidden
- Configured a Template Response for the error key available checked that the response configured is returned under the conditions specified
- Added HTTP Signature Policy
      - Configured the same secret key
      - Added a different algorithm than Generate policy has to check that an error is displayed
- In HTTP Signature Policy 
       - Added the same algorithm as for Generate policy 
       - Configured a different secret key to check that an error is displayed
- In HTTP Signature Policy
       - Configured the same secret key
       - Added 2 algorithms one of them being the same as for Generate HTTP Signature policy 
 cc: @RubenMMSantos @patelami
