### ISSUE TITLE
[policy] [jwt] Allows to configure the client id claims

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4900]
## How to test ?
- Create an API and a plan
- Add the **JSON Web Tokens** policy. You can use HS256, GIVEN_KEY and use jwt.io to generate a token. You have to had the custom claim client id in it. Do not forgot to use the signature into the "Resolver parameter" field. Finally, add the claim you want to test in "Client ID claim". For this test we assume it is `client_id_testing`
![image](https://user-images.githubusercontent.com/47851994/112605226-5bc59700-8e17-11eb-9152-5752119d0ef6.png)
![image](https://user-images.githubusercontent.com/47851994/112605347-7f88dd00-8e17-11eb-872c-4226e10f1587.png)

- Now, add a **Assign Content policy** on the response to fetch the context attribute with the EL `"${context.attributes['oauth.client_id']}"`
![image](https://user-images.githubusercontent.com/47851994/112605308-739d1b00-8e17-11eb-9c1e-4668c6563ce1.png)

- Make a call to your API using the token.
You should have a response like this:
`{
  "testing": "testingclientid"
}`

**Comment by patelami** [comment]
Env: nightly

As a user, I should be able to claim client if I have jwt policy in request and assign content in response **PASS**

**Comment by aelamrani** [comment]
@patelami can you please give an update on the status of this US?

**Comment by patelami** [comment]
This has been verified on nightly and it is good to go live

following issues are raised while testing this issue: 

https://github.com/gravitee-io/issues/issues/5386#issue-854547789
https://github.com/gravitee-io/issues/issues/5387#issue-854554485
