### ISSUE TITLE
[policy] [json-to-json] Content-length header not updated according to the transformation final length

### ISSUE THREAD

**Issue by CracouTech** [gravitee-io/issues#491]
When using the "JSON to JSON Transformation" policy, it appears that the "Content-Length" header from the original request is not updated.
So the transformed request content doesn't match the "Content-Length" header, leading to unexpected behaviours of the target API.

### Expected Behavior
Pre-conditions : 
* Set a JOTL policy generating a bigger content than the original request content.

On each request : 
* The JOTL policy is applied to the original content.
* The "Content-Length" header is set with the length of the transformed content.

### Current Behavior
Pre-conditions : 
* Set a JOLT policy generating a bigger content than the original request content.

On each request : 
* The JOLT policy is applied to the original content.
* The "Content-Length" header is sent to the target API with the original request value.
** As the transformed content is bigger than the header's value, the target API may truncate it (and the JSON content isn't parsable anymore).

*JOLT specification example :*
```
[
  {
    "operation": "shift",
    "spec": {
      "email": ["user.username", "user.email"],
      "title": "user.title",
      "firstname": "user.firstname",
      "lastname": "user.lastname",
      "postalcode": "user.addressPostalCode",
      "city": "user.addressCity"
    }
  },
  {
    "operation": "default",
    "spec": {
      "partner": {
        "partnerKey": "{#properties['partnerKey']}",
        "partnerPassword": "{#properties['partnerPassword']}"
      },
      "user": {
        "password": "my_password",
        "birthdate": "01/01/1900",
        "addressStreet": "Rue generique",
        "addressCountry": "FRANCE"
      }
    }
  }
]
```

*JSON content example :*
```
{
	"title": "1",
	"email": "chien@test.org",
	"firstname": "Dodo",
	"lastname": "LeChien",
	"postalcode": "59000",
	"city": "Lille"
}
```

**Comment by brasseld** [comment]
This issue is happening because request HEAD (contains all the request headers) are transmitted before the request content, and before transformation result.
That's the reason why, even if the content-length is calculated (see https://github.com/gravitee-io/gravitee-gateway-api/blob/master/src/main/java/io/gravitee/gateway/api/http/stream/TransformableRequestStream.java#L46), this new length is not transmitted to the backend.

**Comment by blackfich** [comment]
Hi,

My project requires transforming inputs from exotic formats to some common internal format. I'm facing the same issue, any workaround or solution for this ?

Thanks

**Comment by blackfich** [comment]
Actually I found a workaround:

Use the `Transform Headers` policy to remove the `Content-Length` header **AND** set the `Transfer-Encoding` to `chunked`

This can also be done in the `onRequest` method in the transformer

You can also change the `Content-Type` at this point if your tranformer changes it (ie in my case from CSV to JSON)

**Comment by brasseld** [comment]
Hi @blackfich,

This is an interesting workaround, thanks for sharing.
Anyway, this issue is critical and must be fixed as soon as possible.

**Comment by brasseld** [comment]
Will be partially fixed thanks to https://github.com/gravitee-io/issues/issues/657
