### ISSUE TITLE
[Export API] The life of an API from the dev environment to the production

### ISSUE THREAD

**Issue by bameur** [gravitee-io/issues#4932]
Hello.

Exporting an API through the Gravity API works fine. On the other hand, the need to move from one environment to another requires the modification of the latter's variables in the Json, which is normal. Is there a possibility to extract all the variables and turn them into properties by the export API? (Endpoint, key, ...)
This will make it easier to change from one environment to another.

Target example :
------------------
{
    "name": "OPS-MyTest-API",
    "version": "1.0",
    "description": "dev-ops /  MyTest",
    "visibility": "PUBLIC",
    "paths": {
        "/projects/:id": [],
        "/": []
    },
    "resources": [],
    "properties": [
        **{
            "key": "ENDPOINT_URL",
            "value": "https://myapi.fr/api/v4"
        },
        {
            "key": "OPS_DEPLOY",
            "value": "true"
        },**
…..
"proxy": {
        "virtual_hosts": [
            {
                "path": "/ops/api"
            }
        ],
        "strip_context_path": false,
        "preserve_host": false,
        "logging": {
            "mode": "CLIENT_PROXY",
            "condition": "#context.plan == 'e335873c-fe3d-40ab-b587-3cfe3dd0ab66'"
        },
        "groups": [
            {
                "name": "default-group",
                "endpoints": [
                    {
                        "name": "default",
                        **"target": "{#properties['ENDPOINT_URL']}",**
                        "weight": 1,
                        "backup": false,
                        "type": "HTTP",
                        "inherit": true
                    }
                ],
.....
}

Thanks for your help

**Comment by aelamrani** [comment]
Hi @bameur 

This feature is part of our backlog: https://github.com/gravitee-io/issues/issues/4693

Is that the kind of feature you are looking for?

**Comment by bameur** [comment]
Hi @aelamrani 
Thank you for your reply.
Yes, it is this functionality that I am looking for.
I started to investigate the possibility of loading the json in bean-java and changing the serialization function to json (of the gravitee-api project) to regenerate the json in the format I sent you in my previous message.
Do you think this is feasible? while waiting for the function.
Thank you

**Comment by aelamrani** [comment]
You can define properties in your API design, and the export them into the JSON.

So yes you can handle it like this.

**Comment by bameur** [comment]
I have a legacy of multiple APIs across multiple environments. Reverse engineering is necessary with the risk of errors. I would like to automate the generation of properties after export

**Comment by aelamrani** [comment]
Why not define Dictionaries to handle your environments values? Settings > Dictionaries

**Comment by bameur** [comment]
For information, I noticed that on version 3.5 we cannot use the expression of a property for the ENDPOINT {#properties ['ENDPOINT_URL']} during the first phase of creating an API. The protocol is mandatory.
You had to fill in a banal value [(http / https): //toto.fr] then modify it by assigning the property {#properties ['ENDPOINT_URL']} after creation.

**Comment by bameur** [comment]
The dictionary can meet my need. First I need to start by modifying the legacy APIs. I think modifying apis is cheaper than modifying code 😊
Thank you for your listening and your reactivity.
Ameur.

**Comment by aelamrani** [comment]
You are welcome, so closing this issue.

May I ask you to create a dedicated one for your comment above?

Thanks!
