### ISSUE TITLE
Gravitee 3.5.1 (Linux) | Gravitee not accessible from different computer 

### ISSUE THREAD

**Issue by IvoIlic95** [gravitee-io/issues#4938]
Hello

I installed Gravitee by following the RedHat and CentOs installation guide (Used the full APIM Stack install option).
I can access the Gravitee APIM Homepage with the internal Linux Browser; in my case the Firefox browser.

Due to reasons I need to make Gravitee available to other users. This means that the user can access Gravitee from a Windows Pc by using the Chrome browser for example. In conclusion Gravitee should run on a Linux Server but should be accessible from a different PCs (Windows) using their own browser. 

I tried to paste the URL into Google Chrome on my company laptop but the browser returns the following error:

 "Management API unreachable or error occurs, please check logs"
 
Now I know something is not correctly configured in the gateway or rest-api config file. But I could not figure out what the problem actually is. It is also possible that something else is not correctly configured.

I would appreciate your help!

Kind regards,
Ivo

**Comment by IvoIlic95** [comment]
Good morning

This problem is still there and I hope for help.
I can not quite solve the problem regarding my issue.

I would appreciate if someone could response to my problem.

Kind regards,
Ivo

**Comment by aelamrani** [comment]
Hi @IvoIlic95 

Did you check the logs as suggested?

**Comment by IvoIlic95** [comment]
Yeah, the logs are fine. No errors or something like that.
I can access Gravitee from the internal Linux browser (firefox) without any problem.

But accessing it from a different computer on a different browser (example Chrome) results into the common Gravitee error message: "Management API unreachable or error occurs, please check logs"

**Comment by IvoIlic95** [comment]
A curl on my route results into this:

curl -v http://xxxx.xxx.infineon.com:xxx/constants.json
*   Trying xxxxxxx...
* TCP_NODELAY set
* Connected to xxxxxxx.xxxx.infineon.com (xxxxxxxx) port 8084 (#0)
> GET /constants.json HTTP/1.1
> Host: xxxxxxxx.xxxxxx.infineon.com:8084
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.16.1
< Date: Mon, 08 Feb 2021 07:24:00 GMT
< Content-Type: application/json
< Content-Length: 95
< Last-Modified: Wed, 13 Jan 2021 21:23:02 GMT
< Connection: keep-alive
< ETag: "5fff64b6-5f"
< Accept-Ranges: bytes
<
{
  "baseURL": "http://localhost:8083/management/organizations/DEFAULT/environments/DEFAULT"
}

**Comment by aelamrani** [comment]
Ok so you have to change the baseURL in this `constants.json` file.

Otherwise, your local browser will try to reach the API locally, and I am sure that's not what you want to do here.

**Comment by IvoIlic95** [comment]
Many thanks this worked like a charme!

Kind regards,
Ivo

**Comment by aelamrani** [comment]
You are welcome
