### ISSUE TITLE
[Management/repsoitory JDBC] Implement missing part for Cockpit integration

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#4939]
- [ ] Implement InstallationRepository
- [ ] Permission Migration (Beware: liquibase script if we have to backport to 3.5.x)
- [ ] Addition of HRID in Env & Org repository resource (Beware: liquibase script if we have to backport to 3.5.x)
- [ ] Add cockpit connector plugin to AM bundle by default

**Comment by tcompiegne** [comment]
closed by #4597
