### ISSUE TITLE
[repository][jdbc] Add ability to set db schema name 

### ISSUE THREAD

**Issue by MariaPushkin** [gravitee-io/issues#4940]
Hi! Due to some security requirements, we cannot use postgres public schema. It would be great to be able to specify the db schema name. 

### Possible Solution
Add in https://github.com/gravitee-io/gravitee-repository-jdbc/blob/master/src/main/java/io/gravitee/repository/jdbc/common/AbstractJdbcRepositoryConfiguration.java#L104 something like:
```java
dsConfig.setSchema(readPropertyValue("jdbc.schema", String.class, DEFAULT_SCHEMA));
```
And set DEFAULT_SCHEMA as 'public'.

I think it makes sense to add to both 1.30.x and 3.x. What do you think?

**Comment by aelamrani** [comment]
Hi @MariaPushkin 

The version 1.30.x is not anymore officially supported. 

See https://docs.gravitee.io/ee/ee_version.html

But it can be added to 3.0.x yes, as it is a minor improvement not breaking anything.

Why not providing a pull request?

**Comment by MariaPushkin** [comment]
@aelamrani okay, I can do this

**Comment by leleueri** [comment]
Hi @MariaPushkin 

Thanks you for you contribution.
Is it possible to rebase your change on the 3.0.x branch ?
Currently, your PR target the master branch and we would like to integrate it in the 3.0.x.

**Comment by leleueri** [comment]
Thanks you @MariaPushkin
