### ISSUE TITLE
[management] Allows to use Expression Language in health check configuration

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4943]
# User Story
As a user allowed to configure healthchecks, I want to access the values defined in my dictionaries (thanks to ELs), so that I can do it dynamically

# Further Information
- In the healthcheck configuration forms (global and endpoint), the form field "Header value" must also support Expression Language (with auto completion)
- If the EL does not correspond to any value (or an empty string), the header is still added without any value

# Example
 ![el](https://user-images.githubusercontent.com/82866977/116822482-46166080-ab7f-11eb-86ab-d659d3dc29db.png)

# Tests
- [x] Given the dictionary "kube-tokens" defined with the following property : `{name: 'test_appli', value: 'token'}` and the form field "Header value" filled with `"{#dictionaries['kube-tokens']['test_appli']}"`, when I check my healthcheck call, then the header = "token" 
- [x] Given the following dynamic property : `{name: 'test_appli', value: 'token'}` and the form field "Header value" filled with `"{#properties['test_appli']}"`, when I check my healthcheck call, then the header = "token" 
- [x] Given the form field "Header value" filled with `"token"`, when I check my healthcheck call, then the header = "token"

**Comment by patelami** [comment]
env: nightly 
PASS

Given the dictionary "kube-tokens" defined with the following property : {name: 'test_appli', value: 'token'} and the form field "Header value" filled with "{#dictionaries['kube-tokens']['test_appli']}", when I check my healthcheck call, then the header = "token" **PASS**

Given the following dynamic property : {name: 'test_appli', value: 'token'} and the form field "Header value" filled with "{#properties['test_appli']}", when I check my healthcheck call, then the header = "token" **PASS**


Given the form field "Header value" filled with "token", when I check my healthcheck call, then the header = "token" **PASS**
