### ISSUE TITLE
[management] Allow to re-open a closed subscription

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#4946]
# User Story
As an API publisher, I want to reopen a closed subscription,so that I can avoid an interruption of service in case I make a mistake

# Further Information
- Reopening a subscription is only available at the API level (not at the application level)
- Reopening a subscription requires a confirmation
- A closed subscription cannot be transferred from one plan to another, nor can it be paused. Its expiry date cannot be changed either
- 1 new event to be added:  `SUBSCRIPTION_REOPENED` (and it must be also added to the filter list)
- 1 new notification type (with template)

# Examples
#### Portal notifications (application)
![image](https://user-images.githubusercontent.com/82866977/120244648-197f6280-c26b-11eb-843e-e72069dee7b9.png)

#### Portal notifications (API)
![image](https://user-images.githubusercontent.com/82866977/120244900-d07bde00-c26b-11eb-9be2-8888fa2dbec2.png)

#### Portal notifications (portal)
![image](https://user-images.githubusercontent.com/82866977/120245289-02da0b00-c26d-11eb-9703-8881653d992c.png)

# Tests
## Notifications
- [ ] Given a closed subscription with an outdated date of expiry, when I reopen the subscription, then the expiry date is not set
- [ ] Given a closed subsciption with a not outdated date of expiry, when I reopen the subscription, then the expiry date is set with the old value
- [ ] Given a closed subscription with an expiry date and API keys, when I reopen the subscription, then 
- [ ] Given a closed subscription with API keys but no expiry date, when I reopen the subscription, then 

### Events
- [ ] Given a reopened subscription, when I browse the environment "Audit" section, then a `SUBSCRIPTION_REOPENED` event is logged and appears in the list
- [ ] Given a reopened subscription, when I browse the API "Audit" section, then a `SUBSCRIPTION_REOPENED` event is logged and appears in the list

### Filters
- [ ] Given the "Events" field in the environment/API "Audit" section, when I scroll the list of filters, then the new event `SUBSCRIPTION_REOPENED` is present 
- [ ] Given the "Events" field in the environment/API "Audit" section, when I select the `SUBSCRIPTION_REOPENED` event, then only reopenings of subscriptions are displayed

### Form Validation
- [ ] Given the form for creating/updating the subscription reopening template, when I don't fill all the fields, then the button "Save" is disabled and an error message is displayed below the concerned fields

### Template customization
- [ ] Given the form for creating/updating the subscription reopening template, when "Override default template" switch is off, then the field "Title" and the field "Content" are in read-only mode
- [ ] Given the form for creating/updating the subscription reopening template, when "Override default template" switch is on, then I can modify "Title" ad "Content" values and save my changes

### Notifications
- [ ] Given a template customized, when I select this template and a notification is added to the list/sent by email, then the customized template is used
- [ ] Given a template customized, when I select the default template and a notification is added to the list/sent by email, then the default template is used
- [ ] Given 2 different organizations with 1 custom template each, when notifications are added to the list/sent by email, then each notification uses the associated template with its organization

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Please reopen if not implemented (and disable that abysmal bot).
