### ISSUE TITLE
Dynanic routing transform POST to GET

### ISSUE THREAD

**Issue by smile59** [gravitee-io/issues#495]
Send a POST request is modified to GET request because of Dynamic Routing. In fact I can't see log because it's on another server that I can't access but the response code is 405 (Method not allowed). In the header response I can read only POST method is accepted.

### Expected Behavior
Send a post request from Postman to the gravitee gateway.
```
GET /product/chocolat HTTP/1.1
Host: my-host.com:8082
X-Gravitee-Api-Key: GRAVITEE-KEY
Cache-Control: no-cache
Postman-Token: POSMTAN-TOKEN

```

 Gravitee gateway redirect my request to the server X. The server X send me a response. 
```
Connection →Keep-Alive
Content-Type →application/json
Date →Sat, 11 Mar 2017 15:41:42 GMT
Keep-Alive →timeout=15, max=100
Server →Apache
Transfer-Encoding →chunked
Vary →Accept-Encoding
X-Gravitee-Transaction-Id →GRAVITEE-TRANSACTION-ID
```

### Current Behavior
Send a post request from Postman to the gravitee gateway. 
```
GET /product/chocolat HTTP/1.1
Host: my-host.com:8082
X-Gravitee-Api-Key: GRAVITEE-KEY
Cache-Control: no-cache
Postman-Token: POSMTAN-TOKEN
```
Gravitee gateway redirect my request to the server X. The server X return an error 405 (Method not allowed). 

```
Allow →POST,OPTIONS
Connection →Keep-Alive
Content-Length →0
Date →Sat, 11 Mar 2017 15:59:11 GMT
Keep-Alive →timeout=15, max=100
Server →Apache
````

### Possible Solution

* Allow user to define the method on dynamic routing
* Keep the same method if nothing is define on the dynamic routing
* Provice log access for API publisher directly on Gravitee (option like : follow that request, as debugger) 

### Steps to Reproduce
1. Create an API that only accept POST request (in php / ruby or other language)
2. Host it on apache
2. Create a new API on Gravitee
3. Redirect request to the API define in the first step by Dynamic Routing
4. Send a POST request from Postman

### Context
I have to connect a lot of external and internal services. To improve the Gravitee use, I group many API to one Gravitee API to reduce the number of api-key. For example, You have CRUD for product (contain on the server A) and a Search Context (define on another server). So I have a dynamic routing for allowing 1 API for 2 servers.

The second server (which have the problem), the request only accept HTTPS and the request is send in http from the POSTMAN. I don't think it is the problem because I fix the problem of the SSL security on request and redirection (I don't remember exactly the error message). I also try the request with HTTPS access and nothing change.

### Your Environment
Mac / Linux / Windows.
Postman

**Comment by brasseld** [comment]
Your issue is pretty amazing because, as far as I know, the HTTP method can not be changed because of dynamic-routing policy. Did you try to enable "Dump HTTP" in your gravitee API and have a look to gateway logs ?

**Comment by smile59** [comment]
Ok I have read the dump log (sorry I did know the url rewriting is log on it). In fact, this is not a Gravitee problem, just the the server X that redirect my request. It's strange because the same url work on my browser...

No problem so, I'm sorry for my long issue, everything is okay for Gravitee :)

**Comment by ruslanashaari** [comment]
Hi @Matsa59 

I recently encountered the same issue as you did. Can you please explain more on what you did to fix it?

What do you mean by "server X that redirect my request and don't redirect the request elements"?

Your help is very much appreciated. Thanks

**Comment by Matsa59** [comment]
@ruslanashaari what an old issue lmao. Dunno what I meant... As far as I remember, the server X is the "final endpoint". 

Client <-> gateway <-> "final endpoint" 

So the problem is 100% on the api (aka my final endpoint). 

You should take the http request out from gravitee and send it using postman directly on your api.

**Comment by ruslanashaari** [comment]
Haha apologies @Matsa59 

I checked when I call directly my api without gravitee (gateway), it works fine. I received the body request, and it stayed on POST. 

Does this mean my issue is on the gateway server instead?

**Comment by Matsa59** [comment]
What does the api received when you pass through the gateway?
