### ISSUE TITLE
[management] API State pie chart in home dashboard is wrong

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#4951]
I have 2 started & published APIs
![image](https://user-images.githubusercontent.com/13161768/105365250-57ee7c00-5bfe-11eb-9c49-f6844162269f.png)

But my home dashboard shows me that 100% of my APIS are stopped and only created
![image](https://user-images.githubusercontent.com/13161768/105365143-38575380-5bfe-11eb-80fb-ec4cefcc2442.png)

**Comment by phiz71** [comment]
May be fixed with #4769 (https://github.com/gravitee-io/gravitee-management-webui/pull/1437)

**Comment by gaetanmaisse** [comment]
I have some weird behavior locally (on `master`) but not the same as some API are well considered as published in the API Lifeycycle State graph 🤔

**Comment by gaetanmaisse** [comment]
I'm closing this as it looks like you were right, with an up to date master I have the correct charts:
![image](https://user-images.githubusercontent.com/4112568/106617284-c45a6b00-656e-11eb-8bda-22e4d229f202.png)

Feels free to reopen it if you face the issue again.
