### ISSUE TITLE
History preview not always on read only

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4955]
<img width="1600" alt="Capture d’écran 2021-01-21 à 16 55 31" src="https://user-images.githubusercontent.com/1580262/105376029-98072c00-5c09-11eb-8deb-a723901d005f.png">

**Comment by aelamrani** [comment]
<img width="1604" alt="Capture d’écran 2021-01-21 à 16 57 24" src="https://user-images.githubusercontent.com/1580262/105376178-c2f18000-5c09-11eb-81dd-61a9fee1945e.png">

**Comment by gaetanmaisse** [comment]
Fixed with version `1.0.18`+ of `@gravitee/ui-components`
