### ISSUE TITLE
[docker] [gateway] [management-rest] Update to newer AdoptJDK in Docker images

### ISSUE THREAD

**Issue by larsnaesbye** [gravitee-io/issues#4964]
There are new AdoptOpenJDK images out (11.0.10) for the gateway and management rest API docker files.

PRs: https://github.com/gravitee-io/gravitee-gateway/pull/624 and https://github.com/gravitee-io/gravitee-management-rest-api/pull/1351

**Comment by brasseld** [comment]
👍
