### ISSUE TITLE
[gateway] Allow to use ProxyProtocol

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#4972]
It could be useful to handle the ProxyProtocol in the gateway.
https://www.haproxy.org/download/2.0/doc/proxy-protocol.txt

This can be done after upgrading the Vert.X version

**Comment by gaetanmaisse** [comment]
We miss some info about this one, maybe to rediscuss.

**Comment by bobbyben** [comment]
It may be useful for us to detect source ip while protecting gravitee behind haproxy.
Currently, we only have ip from haproxy server in gravitee analytics.
