### ISSUE TITLE
[doc] document cockpit multi-env support

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#4986]
AM now support multi-env. We have to document these features and evolutions :

- Change all screenshots
- Explain how to switch environment
- Explain how to access organization settings (previously 'global settings')
- Explain how to connect Cockpit ?
- Doc migration (sql, mongo script, configuration yaml) 
- ... to be defined

**Comment by leleueri** [comment]
Need to add a breaking change and change one sentence.
