### ISSUE TITLE
[management] embed cockpit connector plugin in the distribution

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#4993]
We need to embed the cockpit connector plugin by default in the APIM distribution

**Comment by aelamrani** [comment]
Depends on https://github.com/gravitee-io/gravitee-cockpit/issues/301

**Comment by aelamrani** [comment]
Closed by https://github.com/gravitee-io/jenkins-scripts/commit/311b49265fe5f37114a80aae839d129b992d6e92
