### ISSUE TITLE
APIs Health check: API's version is not separated to the name

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#5012]
- Title should be: APIs Status
- Version should be displayed in parenthesis like in other screens
- We can remove the message: Availability on last minute (as we already have the info globally)

![Capture d’écran 2021-02-04 à 15 54 14](https://user-images.githubusercontent.com/1580262/106910268-56927880-6701-11eb-9bcf-26875c259889.png)

**Comment by ytvnr** [comment]
Also fixed: the API image generated was not the same as in API list.
