### ISSUE TITLE
Problem with the healthcheck screen of an API

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#5020]
When accessing the healthcheck page of an API, it is broken and we have a JS error log:
![image](https://user-images.githubusercontent.com/13161768/107053747-78f2c780-67cf-11eb-970f-03494402f86a.png)

**Comment by ytvnr** [comment]
💡 it is due to the deletion of ChartService in https://github.com/gravitee-io/gravitee-management-webui/commit/a0245b6eb0ac4f7978fcdc5af1ebd6cf7de46466

delete ChartService injection in healthcheck.controller.ts
