### ISSUE TITLE
[repository][mongodb] missing index createion

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#5021]
one index is missing: https://github.com/gravitee-io/graviteeio-access-management/blob/9ffd39090b768bfb7066236aa180986df66ddc2d/gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoCredentialRepository.java#L53

**Comment by tcompiegne** [comment]
👍
