### ISSUE TITLE
[policy] [assign-content] Template Injection

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#5033]

**Comment by gcusnieux** [comment]
[WARNING] Missing header in: /usr/src/giomaven_project/src/main/java/io/gravitee/policy/assigncontent/freemarker/LegacyDefaultMemberAccessPolicy.java
[WARNING] Missing header in: /usr/src/giomaven_project/src/test/java/io/gravitee/policy/assigncontent/AssignContentPolicyTest.java
