### ISSUE TITLE
[management] [multi-env] apis and application should not be accessible from another environment

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#5038]
### Current Behavior

Currently, if I change environment when consulting the detail of an API or an Application, the detail is still accessible.

For example here, on environment `dev` for API `Test API2`

![image](https://user-images.githubusercontent.com/47851994/107347117-c4ee8680-6ac5-11eb-8a03-b50ea9b13329.png)

When changing to environment `dev2`, I have still the access to `Test API2`. (entering directly the URL allows to consult the API too)

![image](https://user-images.githubusercontent.com/47851994/107347251-e9e2f980-6ac5-11eb-962d-58b1f4872563.png)

### Expected behavior

We should have a 404 from the backend when consulting an API or application that does not belong to the current environment.

**Comment by aelamrani** [comment]
From the UI perspective, do you think we should be redirected to the APIs page?

**Comment by aelamrani** [comment]
I am fine with both, I just wanted to avoid to display a 404 page here :)

**Comment by ytvnr** [comment]
@aelamrani , I was wrong, we are not silently redirected to home for this kind of error.

So, I redirected to 'APIs list' (and 'Applications list')
