### ISSUE TITLE
[APIM3x] Null pointer exception on API when installing with the chart 

### ISSUE THREAD

**Issue by etiennejournet** [gravitee-io/issues#5047]
Hi Guys,

I've got a null pointer exception on the api component when I setup APIM3x using the helm chart.

`helm upgrade -i graviteeio-apim3x graviteeio/apim3 -n graviteeio -f apim.yml --version 3.0.19`

`k logs graviteeio-apim3x-api-ddf45b67f-4hvsl -n graviteeio -f`
> 10:21:31.703 [graviteeio-node] DEBUG i.g.r.m.m.MongoPageRepository - Search Pages by criteria
> 10:21:31.807 [graviteeio-node] DEBUG i.g.r.m.m.MongoPageRepository - Search Pages by criteria. Count=3 - Done
> 10:21:31.995 [graviteeio-node] DEBUG i.g.r.m.m.MongoPageRepository - Search Pages by criteria
> 10:21:32.001 [graviteeio-node] DEBUG i.g.r.m.m.MongoPageRepository - Search Pages by criteria. Count=0 - Done
> 10:21:32.002 [graviteeio-node] DEBUG i.g.r.m.m.MongoPageRepository - Search Pages by criteria
> 10:21:32.006 [graviteeio-node] DEBUG i.g.r.m.m.MongoPageRepository - Search Pages by criteria. Count=0 - Done
> 10:21:32.006 [graviteeio-node] DEBUG i.g.r.m.m.MongoPageRepository - Search Pages by criteria
> 10:21:32.008 [graviteeio-node] DEBUG i.g.r.m.m.MongoPageRepository - Search Pages by criteria. Count=0 - Done
> 10:21:32.009 [graviteeio-node] DEBUG i.g.r.m.m.t.NoTransactionManager - Initiating transaction commit
> 10:21:32.009 [graviteeio-node] INFO  i.g.r.a.s.impl.UpgraderServiceImpl - Running upgrader io.gravitee.rest.api.service.impl.upgrade.DefaultEnvironmentUpgrader
> 10:21:32.009 [graviteeio-node] DEBUG i.g.r.m.m.t.NoTransactionManager - Creating new transaction with name [io.gravitee.rest.api.service.impl.EnvironmentServiceImpl.findAll]: PROPAGATION_REQUIRED,ISOLATION_DEFAULT; 'graviteeTransactionManager',+io.gravitee.rest.api.service.exceptions.AbstractManagementException
> 10:21:32.009 [graviteeio-node] DEBUG i.g.r.a.s.i.EnvironmentServiceImpl - Find all environments
> 10:21:32.095 [graviteeio-node] DEBUG i.g.r.m.m.t.NoTransactionManager - Initiating transaction commit
> 10:21:32.096 [graviteeio-node] INFO  i.g.r.a.s.impl.UpgraderServiceImpl - Running upgrader io.gravitee.rest.api.service.impl.upgrade.DefaultDashboardsUpgrader
> 10:21:32.096 [graviteeio-node] DEBUG i.g.r.m.m.t.NoTransactionManager - Creating new transaction with name [io.gravitee.rest.api.service.impl.DashboardServiceImpl.findAll]: PROPAGATION_REQUIRED,ISOLATION_DEFAULT; 'graviteeTransactionManager',+io.gravitee.rest.api.service.exceptions.AbstractManagementException
> 10:21:32.096 [graviteeio-node] DEBUG i.g.r.a.s.impl.DashboardServiceImpl - Find all dashboards
> 10:21:32.097 [graviteeio-node] DEBUG i.g.r.m.m.MongoDashboardRepository - Find all dictionaries
> 10:21:32.202 [graviteeio-node] DEBUG i.g.r.m.m.MongoDashboardRepository - Find all dictionaries - Done
> 10:21:32.205 [graviteeio-node] DEBUG i.g.r.m.m.t.NoTransactionManager - Initiating transaction commit
> 10:21:32.205 [graviteeio-node] INFO  i.g.r.a.s.impl.UpgraderServiceImpl - Running upgrader io.gravitee.rest.api.service.impl.upgrade.DefaultRolesUpgrader
> 10:21:32.206 [graviteeio-node] DEBUG i.g.r.m.m.t.NoTransactionManager - Creating new transaction with name [io.gravitee.rest.api.service.impl.RoleServiceImpl.findAll]: PROPAGATION_REQUIRED,ISOLATION_DEFAULT; 'graviteeTransactionManager',+io.gravitee.rest.api.service.exceptions.AbstractManagementException
> 10:21:32.206 [graviteeio-node] DEBUG i.g.r.a.service.impl.RoleServiceImpl - Find all Roles
> 10:21:32.497 [graviteeio-node] DEBUG i.g.r.m.m.t.NoTransactionManager - Initiating transaction rollback
> 10:21:32.500 [graviteeio-node] ERROR i.g.r.a.s.node.GraviteeApisNode - An error occurs while starting component InitializerService
> java.lang.NullPointerException: Name is null
> 	at java.base/java.lang.Enum.valueOf(Unknown Source)
> 	at io.gravitee.repository.management.model.RoleScope.valueOf(RoleScope.java:22)
> 	at io.gravitee.repository.mongodb.management.MongoRoleRepository.map(MongoRoleRepository.java:136)
> 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
> 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
> 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
> 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
> 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
> 	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
> 	at io.gravitee.repository.mongodb.management.MongoRoleRepository.findAllByReferenceIdAndReferenceType(MongoRoleRepository.java:175)
> 	at io.gravitee.rest.api.repository.proxy.RoleRepositoryProxy.findAllByReferenceIdAndReferenceType(RoleRepositoryProxy.java:64)
> 	at io.gravitee.rest.api.service.impl.RoleServiceImpl.findAllByOrganization(RoleServiceImpl.java:93)
> 	at io.gravitee.rest.api.service.impl.RoleServiceImpl.findAll(RoleServiceImpl.java:87)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
> 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
> 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
> 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
> 	at com.sun.proxy.$Proxy48.findAll(Unknown Source)
> 	at io.gravitee.rest.api.service.impl.upgrade.DefaultRolesUpgrader.upgrade(DefaultRolesUpgrader.java:52)
> 	at io.gravitee.rest.api.service.impl.UpgraderServiceImpl.lambda$doStart$0(UpgraderServiceImpl.java:54)
> 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
> 	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
> 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
> 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
> 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
> 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
> 	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
> 	at io.gravitee.rest.api.service.impl.UpgraderServiceImpl.doStart(UpgraderServiceImpl.java:52)
> 	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
> 	at io.gravitee.node.container.AbstractNode.doStart(AbstractNode.java:74)
> 	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
> 	at io.gravitee.node.container.AbstractContainer.doStart(AbstractContainer.java:89)
> 	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at io.gravitee.rest.api.standalone.boostrap.Bootstrap.start(Bootstrap.java:162)
> 	at io.gravitee.rest.api.standalone.boostrap.Bootstrap.main(Bootstrap.java:171)
> 10:21:32.501 [graviteeio-node] ERROR i.g.r.a.s.GraviteeApisContainer - An unexpected error occurs while starting Gravitee.io - Rest APIs
> java.lang.NullPointerException: Name is null
> 	at java.base/java.lang.Enum.valueOf(Unknown Source)
> 	at io.gravitee.repository.management.model.RoleScope.valueOf(RoleScope.java:22)
> 	at io.gravitee.repository.mongodb.management.MongoRoleRepository.map(MongoRoleRepository.java:136)
> 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
> 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
> 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
> 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
> 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
> 	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
> 	at io.gravitee.repository.mongodb.management.MongoRoleRepository.findAllByReferenceIdAndReferenceType(MongoRoleRepository.java:175)
> 	at io.gravitee.rest.api.repository.proxy.RoleRepositoryProxy.findAllByReferenceIdAndReferenceType(RoleRepositoryProxy.java:64)
> 	at io.gravitee.rest.api.service.impl.RoleServiceImpl.findAllByOrganization(RoleServiceImpl.java:93)
> 	at io.gravitee.rest.api.service.impl.RoleServiceImpl.findAll(RoleServiceImpl.java:87)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
> 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
> 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
> 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
> 	at com.sun.proxy.$Proxy48.findAll(Unknown Source)
> 	at io.gravitee.rest.api.service.impl.upgrade.DefaultRolesUpgrader.upgrade(DefaultRolesUpgrader.java:52)
> 	at io.gravitee.rest.api.service.impl.UpgraderServiceImpl.lambda$doStart$0(UpgraderServiceImpl.java:54)
> 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
> 	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
> 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
> 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
> 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
> 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
> 	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
> 	at io.gravitee.rest.api.service.impl.UpgraderServiceImpl.doStart(UpgraderServiceImpl.java:52)
> 	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
> 	at io.gravitee.node.container.AbstractNode.doStart(AbstractNode.java:74)
> 	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
> 	at io.gravitee.node.container.AbstractContainer.doStart(AbstractContainer.java:89)
> 	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at io.gravitee.rest.api.standalone.boostrap.Bootstrap.start(Bootstrap.java:162)
> 	at io.gravitee.rest.api.standalone.boostrap.Bootstrap.main(Bootstrap.java:171)
> 10:21:32.502 [graviteeio-node] INFO  i.g.r.a.s.GraviteeApisContainer - Shutting-down Gravitee.io - Rest APIs...
> 10:21:32.502 [graviteeio-node] INFO  i.g.r.a.s.node.GraviteeApisNode - Gravitee.io - Rest APIs is stopping
> 10:21:32.506 [graviteeio-node] INFO  i.g.r.a.s.node.GraviteeApisNode - 	Stopping component: ReporterManager
> 10:21:32.506 [graviteeio-node] INFO  i.g.common.service.AbstractService - Destroying service Reporter service
> 10:21:32.510 [graviteeio-node] INFO  i.g.r.a.s.node.GraviteeApisNode - 	Stopping component: ManagementService
> 10:21:32.510 [graviteeio-node] INFO  i.g.common.service.AbstractService - Destroying service Node Management API service
> 10:21:32.510 [graviteeio-node] INFO  i.g.r.a.s.node.GraviteeApisNode - 	Stopping component: ServiceManager
> 10:21:32.511 [graviteeio-node] INFO  i.g.common.service.AbstractService - Destroying service Plugins - Services Manager
> 10:21:32.511 [graviteeio-node] INFO  i.g.common.service.AbstractService - Destroying service Search Indexer Service
> 10:21:32.511 [graviteeio-node] INFO  i.g.common.service.AbstractService - Destroying service Subscriptions Refresher Service
> 10:21:32.511 [graviteeio-node] INFO  i.g.common.service.AbstractService - Destroying service Node Health-check service
> 10:21:32.511 [graviteeio-node] INFO  i.g.common.service.AbstractService - Destroying service Dynamic Properties Service
> 10:21:32.511 [graviteeio-node] INFO  i.g.common.service.AbstractService - Destroying service Sync Service
> 10:21:32.511 [graviteeio-node] INFO  i.g.n.s.monitoring.MonitoringService - Stop node monitor
> 10:21:32.511 [graviteeio-node] INFO  i.g.common.service.AbstractService - Destroying service Monitoring Service
> 10:21:32.511 [graviteeio-node] INFO  i.g.n.s.monitoring.MonitoringService - Stop node monitor : DONE
> 10:21:32.511 [graviteeio-node] INFO  i.g.common.service.AbstractService - Destroying service Dictionary Service
> 10:21:32.513 [graviteeio-node] INFO  i.g.r.a.s.node.GraviteeApisNode - 	Stopping component: PluginRegistry
> 10:21:32.513 [graviteeio-node] INFO  i.g.common.service.AbstractService - Destroying service io.gravitee.plugin.core.internal.PluginRegistryImpl
> 10:21:32.591 [graviteeio-node] INFO  i.g.r.a.s.node.GraviteeApisNode - 	Stopping component: PluginEventListener
> 10:21:32.592 [graviteeio-node] INFO  i.g.common.service.AbstractService - Destroying service io.gravitee.plugin.core.internal.PluginEventListener
> 10:21:32.592 [graviteeio-node] INFO  i.g.r.a.s.node.GraviteeApisNode - Gravitee.io - Rest APIs stopped
> 10:21:32.602 [vert.x-eventloop-thread-1] DEBUG i.g.n.r.v.verticle.ReporterVerticle - Reporter publisher has been closed successfully.

Here is my config :
 
```
api:
  logging:
    debug: true
  ingress:
    management:
      enabled: true
      ...
    portal:
      enabled: false
      ...

mongo:
  auth:
    enabled: false
  servers: |
    - host: mongodb-headless.mongodb
      port: 27017
  dbname: gravitee
```

Mongo is installed "as is" with :

`helm install mongodb bitnami/mongodb --set architecture=replicaset --set auth.enabled=false -n mongodb --version 10.6.2
`
(auth.enabled=false for test purposes obviously...)

Would you have any idea of why ? It didn't seems obvious to me If there was any "Name" parameter missing from the helm chart.
Thanks a lof for any of your insights.

Etienne

**Comment by aelamrani** [comment]
Hi @etiennejournet 

Are you upgrading Gravitee.io or is it a fresh install?

**Comment by etiennejournet** [comment]
Hi,

It is a fresh install.


Le mer. 10 févr. 2021 à 12:27, Elamrani Azize <notifications@github.com> a
écrit :

**Comment by brasseld** [comment]
Hello @etiennejournet 

We are using helm charts every day so we are a bit surprised.
(Most of the time we are not using Mongo and ES embedded, we are using external services).

Can you have a try with an other dbname ? Just to ensure that we are starting from a fresh DB ?

Thanks for your feedback.

Regards,

**Comment by etiennejournet** [comment]
Hi ! 

I did delete all releases and related PVC to ensure starting from a fresh DB and it works. Could it be related to the fact that I was testing the AM setup too, and they use the same database name as default ? (Should they use the same database at all ?)

Another issue I must report is with the UI Container: confd doesn't seem to be able to write the nginx files when using the UID provided in the chart (101). I've got something which looks like this in AM and APIM:

```
2021-02-10T13:11:33Z graviteeio-apim3x-ui-5b966d6df5-gb25j /bin/confd[6]: INFO Backend set to env
2021-02-10T13:11:33Z graviteeio-apim3x-ui-5b966d6df5-gb25j /bin/confd[6]: INFO Starting confd
2021-02-10T13:11:33Z graviteeio-apim3x-ui-5b966d6df5-gb25j /bin/confd[6]: INFO Backend source(s) set to 
2021-02-10T13:11:33Z graviteeio-apim3x-ui-5b966d6df5-gb25j /bin/confd[6]: INFO /usr/share/nginx/html/constants.json has md5sum d32017cf30a1b5ad5895b229a83ca173 should be 5bac32fe16d74ccdf81097319407ec18
2021-02-10T13:11:33Z graviteeio-apim3x-ui-5b966d6df5-gb25j /bin/confd[6]: INFO Target config /usr/share/nginx/html/constants.json out of sync
2021-02-10T13:11:33Z graviteeio-apim3x-ui-5b966d6df5-gb25j /bin/confd[6]: ERROR open /usr/share/nginx/html/constants.json: read-only file system
2021-02-10T13:11:33Z graviteeio-apim3x-ui-5b966d6df5-gb25j /bin/confd[6]: INFO /etc/nginx/conf.d/default.conf has UID 101 should be 0
2021-02-10T13:11:33Z graviteeio-apim3x-ui-5b966d6df5-gb25j /bin/confd[6]: INFO /etc/nginx/conf.d/default.conf has md5sum 411a0b28ff9b21a1cd94a6cb2ae2217d should be 32f9f14968ac47f311aaa48c98c991bf
2021-02-10T13:11:33Z graviteeio-apim3x-ui-5b966d6df5-gb25j /bin/confd[6]: INFO Target config /etc/nginx/conf.d/default.conf out of sync
2021-02-10T13:11:33Z graviteeio-apim3x-ui-5b966d6df5-gb25j /bin/confd[6]: INFO Target config /etc/nginx/conf.d/default.conf has been updated
2021-02-10T13:11:33Z graviteeio-apim3x-ui-5b966d6df5-gb25j /bin/confd[6]: FATAL open /usr/share/nginx/html/constants.json: read-only file system
```

In AM I was able to solve this issue by setting an empty map in `ui.securityContext` variable, so that it uses the user configured in Dockerfile (root).
In APIM the same action did not work and eventhough the container can get to Running state (not the case in AM), i've got a "Serveur indisponible ou connexion perdue" error in the UI.

Thanks for your answers so far anyway :)

**Comment by brasseld** [comment]
Oh yes, it's better not to use the same database as they are sharing some collections name by default.

"Serveur indisponible ou connexion perdue" means that the UI can't reach the API.
Can you have a look to constants.json from dev tools, the base URL should be something like `https://domain/management/organizations/DEFAULT/environments/DEFAULT/`

**Comment by etiennejournet** [comment]
Hi,

I just checked and the URL is good. I tried accessing (curl -I -L) to it, it returns 401. But UI not working.

I'm a little bit confused because it looks like the ingress is eventually leading me to the portal container, but then can't access to some of his own data/assets (Example : http://localhost:8083/portal/environments/DEFAULT/apis?size=-1&filter=FEATURED, or : http://localhost:8083/portal/environments/DEFAULT/configuration/links)

I left every "svc.ingress.path" by default and gave the same domain url for the 4 of them (api, portal, mgmt, gateway).

Thanks,

**Comment by brasseld** [comment]
Can you try to open `https://apim.example.com/console/` to access the console ?

(see the final slash in the URL).

Regards,

**Comment by etiennejournet** [comment]
It works, thanks !

I got myself messed up between APIM and AM (where you can access the UI on domain.com/) ...

**Comment by brasseld** [comment]
No problem,

I have to admit that it's not really easy with the different URLs....

Can we close the issue?

**Comment by etiennejournet** [comment]
Yes you can close the issue, thanks for your help
