### ISSUE TITLE
[service] Best way to proxy in front of Docker Swarm services?

### ISSUE THREAD

**Issue by Yaytay** [gravitee-io/issues#505]
Hi,

We want to run Gravitee in front of a number of services hosted in Docker Swarm, which means (with our setup) that we don't know up front what their endpoints are going to be.
We can determine the endpoints programatically at any time, or we can monitor Docker and make changes when the service changes.

What would you recommend as the best approach for proxying these services?
Two approaches come to mind:
1. Write a plugin like the Dynamic Routing plugin.
This looks like the simplest approach and avoids too much coupling between Docker and Gravitee, but I think it would lose the benefits of Health Monitoring and persistent connections.
2. Monitor Docker and use the Gravitee Management API to change the service API whenever things change.
This would result in services being republished when their configuration (as understood by a user) hasn't changed.

Thanks for your recommendation.

**Comment by brasseld** [comment]
Hi @Yaytay,

IMHO, the best option is 2).

One way to achieve this:
1. Associate a docker label to a Gravitee API (using API properties or, later, API metadata ?)
2. Create a new service plugin DockerBackendUpdaterService which is used to check a docker container filtered by the label define in 1). This service runs under the scope of the management-api.
3. Each time the service detect a backend change, republish automatically the API and store an audit event to trace changes.

**Comment by NicolasGeraud** [comment]
@brasseld the service (DockerEndpointUpdaterService no?) needs to call with multiple docker daemon. wdyt ?

Your approach with metada is a cool one, this makes me think of Træfik. We could probably autoconfigure apis with metadata.

**Comment by brasseld** [comment]
> @brasseld the service (DockerEndpointUpdaterService no?) needs to call with multiple docker daemon. wdyt ?

Why do we need to "communicate" multiple docker daemon ?

Finally, I don't think either `DockerBackendUpdaterService` or `DockerEndpointUpdaterService` are good names for this kind of stuff. The need is to auto-configure endpoints according to one or more associated (by a label) Docker containers. So it's more about a `DockerEndpointDiscoveryService`.

> Your approach with metada is a cool one, this makes me think of Træfik. We could probably autoconfigure apis with metadata.

That's exactly the point!

**Comment by NicolasGeraud** [comment]
> Why do we need to "communicate" multiple docker daemon ?

You could have multiple swarm/docker to to monitor

**Comment by NicolasGeraud** [comment]
@Yaytay currently I suggest you to do your 2nd suggestion via an external script

**Comment by NicolasGeraud** [comment]
And you can share this script to the Gravitee.io community :)

**Comment by Yaytay** [comment]
Thank you both, I'll take a look at handling this externally for now.
I may have to support multiple load balancers, not just gravitee, so not sure how much I'll be able to share, but I'll keep you informed.

**Comment by brasseld** [comment]
The best here would be to provide a new Docker service discovery plugin as we're already doing for consul.io / eureka.
