### ISSUE TITLE
[management-api] OAuth authentication : use http[s] proxy : nonProxyHosts

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#5051]
Since https://github.com/gravitee-io/issues/issues/4398

OAuth authentication can use an HTTP proxy to perform requests between the management-api and the identity provider.

By default, proxy configuration is based on `-Dhttp.proxyHost=xxxxxxx -Dhttp.proxyPort=xxxx -Dhttps.proxyHost=xxxxxxxxx -Dhttps.proxyPort=xxxx`

We should extend the behavior to also consider `-Dhttp.proxyUser=xxxxx -Dhttp.proxyPassword=xxxxxxxx -Dhttp.nonProxyHosts="localhost|127.0.0.1|*.xxxxx.com"` to configure proxy

**Comment by aelamrani** [comment]
We have added this in gravitee.yml only and we can still rely on system props
