### ISSUE TITLE
[gateway] Rpc support

### ISSUE THREAD

**Issue by linking12** [gravitee-io/issues#506]
Can gravitee support rpc like grpc? is any suggestion to support?

**Comment by brasseld** [comment]
Hi @linking12,

Gravitee.io dos not support gRPC currently.
But! Our stack is mainly based on [Vert.x](http://vertx.io/) and Vert.x community is already providing gRPC support:
* https://github.com/vert-x3/vertx-grpc
* https://github.com/vert-x3/vertx-examples/tree/master/grpc-examples

If you want to provide gRPC support to Gravitee.io, I will be glad to help you on such integration.

**Comment by linking12** [comment]
@brasseld 
thanks, i think about the solutions carefully about how to do this integration.
gprc stub is a difficulty point，how does gateway do not stop and support redirect to grpc server is my desired

**Comment by brasseld** [comment]
You're right, stubbing is a difficult point!

I have to take a look to think about the simplest to integrate grpc support.
If you have any clue....

**Comment by linking12** [comment]
yes，I have a solution,if user upload proto file,we can parse this Porto to call remote service,can you agree this solution?

**Comment by brasseld** [comment]
Sounds good to me.

Do you think we can have multiple proto files for a given API or only one ?

**Comment by linking12** [comment]
I think rest api and proto file is one to one relationship
but must cache the result of proto file's parse

parse proto file can use protoc-jar

                <dependency>
			<groupId>com.github.os72</groupId>
			<artifactId>protoc-jar</artifactId>
			<version>3.1.0.1</version>
		</dependency>

if gravitee-io provider upload proto file and save api and proto file relation into database, I think i can do some thing

**Comment by ydbondt** [comment]
Any updates on this ?

**Comment by brasseld** [comment]
Hi @ydbondt 

I would say that it would depends on your expectations for GRPC support.

Are you looking for stub support, or only a pass-through support (and so, HTTP/2 is sufficient) ?

**Comment by ydbondt** [comment]
Hey @brasseld, I basically want to send and receive data from my microservices using a RabbitMQ queue.

**Comment by brasseld** [comment]
Perhaps I'm missing something, but as I far as I know, RabbitMQ is not supporting GRPC ? https://www.rabbitmq.com/protocols.html

**Comment by ydbondt** [comment]
I'm actually not talking about gRPC (which is a framework), but rpc in general.
You can do RPC with a message queue like RabbitMQ in the background (like this f.e.: https://www.rabbitmq.com/tutorials/tutorial-six-spring-amqp.html)

**Comment by brasseld** [comment]
Ok, sorry for the misunderstanding but all the previous comments were talking about gRpc...

**Comment by niusha-paks** [comment]
> Hi @ydbondt
> 
> I would say that it would depends on your expectations for GRPC support.
> 
> Are you looking for stub support, or only a pass-through support (and so, HTTP/2 is sufficient) ?

Hi @brasseld ,

Do you mean there is already a way to expose a simple raw gRPC endpoint ?

Also I'm excited to see that gRPC feature is in your short-mid term roadmap ! Any forecast of release ?

**Comment by brasseld** [comment]
Hi @niusha-paks 

Sorry I've missed your message.

Yes, since 3.1 you can gateway is supporting raw grpc.

regards,
