### ISSUE TITLE
[management] JS error when trying to add application metadata

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#5065]
On v3.5.2, there is a JS error when trying to add an application metadata:

![image](https://user-images.githubusercontent.com/5955401/107748032-b5b34700-6d18-11eb-9609-91db0b21cc2c.png)

**Comment by tcompiegne** [comment]
Seems that the metadata are not well refresh when we switch between application section : 

1. Add a metadata and press SAVE
2. Go to General section
3. Go back to metadata section, my new metadata is not visible (but well stored in the database)
