### ISSUE TITLE
[management] [jdbc] Migration issue 3.5 to 3.6

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#5071]
Migration from 3.5 to 3.6. (AM isn't linked with cockpit, it is a standard AM installation)

Dataset 1 : 
* One domain with one app. with one user
* Admin user
* User1 user with APPLICATION_USER on app (Role DOMAIN_USER isn't set)

Dataset 2 : 
* One domain with one app. with one user
* Admin user
* User1 user with APPLICATION_USER on app and Role DOMAIN_USER on domain

With Both dataset :
* In 3.5, the user User1 can see the app overview and endpoints page
* In 3.6 after startup, the user1 see the 'no environment available' page

Test should also be done using mongodb, maybe there are the same problem.

![image](https://user-images.githubusercontent.com/3110552/107789688-33e00f80-6d52-11eb-8c9b-1d3a1dd86a1c.png)

**Comment by tcompiegne** [comment]
Seems ok with MongoDB. I think it's missing the "assign ENVIRONMENT_USER role" liquibase script for JDBC.
