### ISSUE TITLE
[portal] Customize informations display in public view

### ISSUE THREAD

**Issue by geraudmasson** [gravitee-io/issues#509]
Hi,

I would like to know if it's possible to hide the owner of the api ?

Currently, on the apis's public view, we can see the owner on the top right corner and it seems impossible to remove it.

I use the version 1.2.0

Thanks

Géraud
![gravitee](https://cloud.githubusercontent.com/assets/26602276/24203855/1f7f9f62-0f17-11e7-9812-e78cd80852df.png)

**Comment by NicolasGeraud** [comment]
Hi @geraudmasson currently the only way to do that is to clone the repository, remove it, and build your own version of gravitee.io
https://github.com/gravitee-io/gravitee-management-webui/blob/1.2.0/src/app/api/apisList.html#L77

Is there other informations you want to hide in public view ?

**Comment by brasseld** [comment]
This is no more available from the portal view.
Also, from 1.20, you are able to manage and customize API's informations shown from the API general page.
