### ISSUE TITLE
[reporter] Metrics do not expose timestamp for formatters

### ISSUE THREAD

**Issue by larsnaesbye** [gravitee-io/issues#5097]
The Filereporter does not serialize the timestamp because Metrics doesn't expose its timestamp through an accessor.

Adding a simple getTimestamp() accessor will make the timestamp available for JSON formatter in the FileReporter.

**Comment by phiz71** [comment]
Hi @larsnaesbye, thank you for your contribution. I think it should be better to add the getter function in the 
AbstractMetrics class, where the `timestamp` variable is defined, so the serialization could also works for `Logs`, `Monitor` and `EndpointStatus` classes.
WDYT ?

**Comment by larsnaesbye** [comment]
Hi @phiz71 you have a good point there. I will change it and squash the commit.

**Comment by larsnaesbye** [comment]
@phiz71 Is the patch looking better now? :)
