### ISSUE TITLE
[gateway] Helm chart broken - invalid types for comparison error when installing

### ISSUE THREAD

**Issue by Harjot1Singh** [gravitee-io/issues#5098]
### Expected Behavior
Helm install command works successfully.

### Current Behavior
`helm install graviteeio-apim3x graviteeio/apim3` results in:

```
Error: template: apim3/templates/gateway/gateway-deployment.yaml:53:13: executing "apim3/templates/gateway/gateway-deployment.yaml" at <ne .Values.gateway.image.tag "nightly">: error calling ne: incompatible types for comparison
```

### Possible Solution
https://github.com/gravitee-io/helm-charts/commit/6237c4f65806775594c7a2a78f13107117ee8b1f#diff-8f87b20a84a846ce208848f61f8e12d5e738457f11554fbad7170e4d502bd2f3R46 causes this.

If I had to hazard a guess, I suspect this https://github.com/gravitee-io/helm-charts/blob/6237c4f65806775594c7a2a78f13107117ee8b1f/apim/3.x/values.yaml#L606 is unintentional, and the lack of definition resolves the property `.Values.gateway.image.tag` to `nil`, which is not a compatible type with `"nightly"`.

To workaround, I suspect I can just define the value myself when deploying the chart.

### Steps to Reproduce (for bugs)

1. Run `helm install graviteeio-apim3x graviteeio/apim3`
2. Profit $$$

### Context
Trying to install Gravitee with Helm.

### Your Environment
Helm v3, Chart

**Comment by brasseld** [comment]
Hi,

Latest version of the chart (3.1.0) is fixing the issue.

Regards,
