### ISSUE TITLE
[management] Bad permissions in applications role_permission

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#5099]
https://github.com/gravitee-io/gravitee-management-rest-api/blob/1.30.x/gravitee-management-api-model/src/main/java/io/gravitee/management/model/permissions/RolePermission.java#L79-L80

APPLICATION_ALERT & APPLICATION_METADATA role permissions should be bound to `ApplicationPermission` enum instead of `ApiPermission`

**Comment by gaetanmaisse** [comment]
After a discussion with @phiz71 it looks like this issue is still in the code base (as of APIM 3.15.x).
Wildy changing the enum can cause some functional troubles, based on that and the fact it's _only_ a technical improvement we decided to close this issue for now.
