### ISSUE TITLE
[management] Cannot delete a deprecated API anymore

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#5113]
![Capture d’écran 2021-02-22 à 11 24 29](https://user-images.githubusercontent.com/1580262/108695404-8c589f00-7500-11eb-8622-0d74edd8a2c1.png)

**Comment by NicolasGeraud** [comment]
from #5169 
It is not possible to delete a deprecated api in v2.

Steps to Reproduce (for bugs)
Create a v2 api with a plan (or create with plan in v1, then migrate to v2)
Deprecate the api -> it will change its lifecycle state to DEPRECATE and update plans to DEPRECATED status
Delete the API -> not possible, there is a bug
Possible Solution
When updating an API to deprecate it, all plans in status STAGING or PUBLISHED are deprecated.
But, the API definition (v2) is not updated with new plans status.

So, when searching for the api to delete, the definition is used to get the plans, which are still in PUBLISHED, making impossible to delete the API
