### ISSUE TITLE
[management] Error configuring information

### ISSUE THREAD

**Issue by fernandopasse** [gravitee-io/issues#5116]
### Expected Behavior

The schema is defined as a number, but it must be an integer.

### Current Behavior

Don't let the plugin's configuration change

### Possible Solution

Change number to integer in the schema.

### Steps to Reproduce (for bugs)

1. https://github.com/gravitee-io/gravitee-policy-circuit-breaker/blob/master/src/main/resources/schemas/schema-form.json
2.
3.
4.

### Context

I am trying to use the circuit breaker.

### Your Environment

* Version used: 3.6
* Browser Name and version:
* Operating System and version:

**Comment by aelamrani** [comment]
Closed by https://github.com/gravitee-io/gravitee-policy-circuit-breaker/pull/5

**Comment by aelamrani** [comment]
Thanks for the contribution @fernandopasse
