### ISSUE TITLE
[management] unable to save an api:  Cron expression must consist of 6 fields (found 0 in \"\")

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#5118]
### Expected Behavior
my api should works as previously

### Current Behavior
When I save the API : 
```
{
  "message" : "java.lang.IllegalArgumentException: Cron expression must consist of 6 fields (found 0 in \"\")",
  "http_status" : 400
}
```
### Possible Solution
Check if you use dynamic properties and change the cron expression

### Steps to Reproduce (for bugs)

1. migrate an env from 3.5 to 3.6 with an api with dynamic properties

### Your Environment

* Version used: 3.6.0

**Comment by NicolasGeraud** [comment]
In fact it's not related to dynamic properties but to a disabled healthcheck with an empty value : 
```"health-check": {
      "enabled": false,
      "schedule": ""
    },``` 

The workaround is to export the api, remove this config and reimport it.

**Comment by fabMrc** [comment]
Hi I have the same pb with auto fetch in documentation pages . I have to give 6 fields

**Comment by jhaeyaert** [comment]
Related to #5042. 

The old format of health check definition is not well handled and generated an empty schedule field when health check is disabled and has no rate or unit value. The empty schedule field is then rejected when updating the api definition.
