### ISSUE TITLE
[portal] Dasboard list have wrong style

### ISSUE THREAD

**Issue by gcusnieux** [gravitee-io/issues#5121]
Since v1.0.24 of ui-components the list in the header is blue, she should be white.

![Capture d’écran 2021-02-23 à 11 58 11](https://user-images.githubusercontent.com/1457497/108835148-5b936b00-75cf-11eb-9cd2-d6562ed35b9c.png)
 
Related with https://github.com/gravitee-io/gravitee-ui-components/commit/c039b88dc2fb02585af6bd7a564f6cc4980f5714

Related issue in ui-components to be resolved for this to be fixed: https://github.com/gravitee-io/gravitee-ui-components/issues/284

**Comment by leleueri** [comment]
Need merged of https://github.com/gravitee-io/issues/issues/4635 to be reproduced
