### ISSUE TITLE
[Documentation] Explain Plans and Subscriptions feature

### ISSUE THREAD

**Issue by capaca** [gravitee-io/issues#514]
The plans and subscriptions page is empty when the url https://docs.gravitee.io/apim_publisherguide_plans_subscriptions.html is accessed.

I'd like to know about the field "Path authrorization" when creating a new Plan.

**Comment by NicolasGeraud** [comment]
Hi @capaca 
We have a lot of work on documentation for sure.

Path authorization allows you to constraint acces to a subset of the api resources.

If you want to only allow the http verb `GET` on `/products` you have to configure like this : 
![capture d ecran 2017-03-23 17 03 33](https://cloud.githubusercontent.com/assets/1028285/24257277/b5a3c850-0fea-11e7-830c-49158fc7e4db.png)

We use ant pattern. If the path match, the request is authorized.

**Comment by NicolasGeraud** [comment]
moved to gravitee-io/gravitee-docs#66
