### ISSUE TITLE
iAuth Error | Unable to call the remote service

### ISSUE THREAD

**Issue by IvoIlic95** [gravitee-io/issues#5149]
Hello

Currently I am running Gravitee APIM v3.5.x on a Linux Server. 
I wanted to have iAuth as a LogIn option for Gravitee. 
Unfortunately I am getting an error after configuring it.
As you can read in the title I am getting this error after 
trying to login with iAuth. The error shows up in the right 
corner of the title screen and the Gravitee is loading forever
after that.

In the console itself I am not getting any error message.
What could be possible wrong with iAuth?

For further information I will respond as soon as possible.

Thank you for your help and kind regards,
Ivo Ilic, B.Sc.

**Comment by aelamrani** [comment]
Hi, 

Are you on a fresh DB? Did you already manage to log in with that user?

**Comment by IvoIlic95** [comment]
Good morning

Well I used the iAuth config data from a previous Gravitee version (v1.3).
In Gravitee v1.3 the iAuth worked pretty well, without any problems.

I can LogIn BUT after pressing the iAuth login button the error as mentioned before
pops up in the bottom right corner and then I need to reload the page. 

After that I am logged in but Gravitee keeps on loading as you can see in the picture below:

![Capture](https://user-images.githubusercontent.com/59047274/109468092-671de080-7a6c-11eb-9ca7-c2551557ec96.PNG)

**Comment by aelamrani** [comment]
Can you check the user created on database and share it here (by anonymizing it)?

**Comment by IvoIlic95** [comment]
Do you mean this ?

WARN  i.g.r.a.m.r.r.a.OAuth2AuthenticationResource - Using mapping: "picture", no fields are located in {"sub":"Ivo.xxxxx@xxxx.com","email_verified":true,"gender":"male","profile":"Ivo.xxxxx@xxxx.com","name":"xxxx Ivo (xxxxxxxxxx)","realm":"INT","preferred_username":"Ivo.xxxxx@xxxxxx.com","given_name":"Ivo","family_name":"xxxxxxx","client_id":"gravitee","email":"Ivo.xxxxx@xxxxxxx.com"}

Otherwise if this is not what you wanted, then I need to ask a guy from an other department in my company that manages the authentication.

**Comment by aelamrani** [comment]
No, I meant what is really stored in database in order to understand the problem with that user.

Other users can connect without issue?

**Comment by IvoIlic95** [comment]
No all of the users are affected by this issue.

I installed Gravitee on Linux is it possible that the needed information is on a database that was installed simultaneously with Gravitee? In which database is this information stored?

**Comment by aelamrani** [comment]
MongoDB by default.

**Comment by IvoIlic95** [comment]
Good morning 

What I have found is this MongoDB service called mongod.
As seen in the Gravitee installation guide for Linux based systems,
MongoDB (mongod) is automatically installed with Gravitee.

So I think this might be the MongoDB log that you requested:

```
mongod.service - MongoDB Database Server
   Loaded: loaded (/usr/lib/systemd/system/mongod.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2021-02-04 22:57:49 UTC; 3 weeks 3 days ago
     Docs: https://docs.mongodb.org/manual
 Main PID: 9309 (mongod)
   CGroup: /system.slice/mongod.service
           `-9309 /usr/bin/mongod -f /etc/mongod.conf

Feb 04 22:57:47 xxx systemd[1]: Starting MongoDB Database Server...
Feb 04 22:57:48 xxx mongod[9305]: about to fork child process, waiting until server is ready for connections.
Feb 04 22:57:48 xxx mongod[9305]: forked process: 9309
Feb 04 22:57:49 xxx mongod[9305]: child process started successfully, parent exiting
Feb 04 22:57:49 xxx systemd[1]: Started MongoDB Database Server.
```

**Comment by aelamrani** [comment]
Hi @IvoIlic95 

I am still not able to reproduce locally.

Are you able to share the user in DB?

```
use gravitee

db.users.find({email: "Ivo.xxxxx@xxxxxxx.com"})
```

Thanks

**Comment by IvoIlic95** [comment]
Sorry I am not that advanced with Linux. I am still in the learning phase :)

Is this some kind of command? I tried to run it in Linux but nothing is happening.

The funny thing is that when I try to logIn with iAuth and then refresh the browser, Gravitee loads a blank page and starts loading again while displaying the same error as mentioned.

Logging in as a admin works  fine, and when I am checking which user has an account in Gravitee, I can see myself who logged in with iAuth. So basically Gravitee made an account for me when trying to connect with iAuth.

**Comment by aelamrani** [comment]
The command shared below has to be ran in your MongoDB instance.

Before you need to install mongo CLI, then connect by typing `mongo ...`

Here the documentation: https://docs.mongodb.com/manual/mongo/

**Comment by IvoIlic95** [comment]
Here is the result to your request:
`
{ "_id" : "xxxxxxxx-884e-xxxxx-ab45-xxxxxxxxxx", "organizationId" : "DEFAULT", "email" : "Ivo.xxxxx@xxxxxx.com", "firstname" : "Ivo", "lastname" : "Ilic", "source" : "iauth-20-test", "sourceId" : "Ivo.xxxxx@xxxxx.com", "status" : "ACTIVE", "lastConnectionAt" : ISODate("2021-03-03T08:59:22.971Z"), "loginCount" : NumberLong(16), "firstConnectionAt" : ISODate("2021-02-10T14:51:45.005Z"), "newsletterSubscribed" : true, "createdAt" : ISODate("2021-02-10T14:51:44.961Z"), "updatedAt" : ISODate("2021-03-03T08:59:22.971Z"), "_class" : "io.gravitee.repository.mongodb.management.internal.model.UserMongo" }
`

**Comment by phiz71** [comment]
Hello @IvoIlic95
Could you tell me the exact version of APIM you are running?
Do you have the same problem if you log in with the form instead of your identity provider?

You have said:
> Well I used the iAuth config data from a previous Gravitee version (v1.3).
- I guess you meant 1.30 and not 1.3 😉  ?
- How did you configure your iAuth identityProvider (idp) int his new installation?
  - did you upgrade Gravitee from 1.30.x to 3.5.y ?
  - did you install a new Gravitee APIM and declare the iAuth idp ?

Sorry for all these questions but it is necessary for me to understand 😄 .

**Comment by IvoIlic95** [comment]
Hello :)

The version is 3.5.1.
Logging in with the Name: admin, Password: admin works perfect.

Yeah, I forgot the zero ^^

The iAuth information is from an other department in my company, but I configured iAuth inside Gravitee (Organization settings -> ...)

Nope, the 3.5.1 version is a fresh install.

Yes, Gravitee APIM was newly installed but the iAuth data - that I used in Gravitee 1.30 - is from a previous version.

**Comment by phiz71** [comment]
Thank you for your answers.
First of all, is it possible for you to upgrade to the 3.5.5 version of APIM ? Or maybe 3.6.0 ?

And if you enable the iAuth IDP on the portal, do you have the same issue when connecting to the portal UI ?

**Comment by IvoIlic95** [comment]
No problem!

Theoretically yes but in reality no. It would take days to upgrade due to company related reasons.
I would like to stick around with v3.5.5. Is there something fixed which is related to my issue?

iAuth is enabled all the time:
![Capture](https://user-images.githubusercontent.com/59047274/110282750-4fe87100-7fdf-11eb-96d5-bc640b794f56.PNG)

**Comment by IvoIlic95** [comment]
Hello

Is there a possible solution for this?

Kind regards,
Ivo

**Comment by IvoIlic95** [comment]
Hello

Did anyone forgot this issue? ^^

I can't figure out what causes this "unable to call remote service" problem.

Any help would help!

Kind regards,
/Ivo

**Comment by IvoIlic95** [comment]
Hello

Do you have any ideas that might help to fix this issue?

> Thank you for your answers.
> First of all, is it possible for you to upgrade to the 3.5.5 version of APIM ? Or maybe 3.6.0 ?
> 
> And if you enable the iAuth IDP on the portal, do you have the same issue when connecting to the portal UI ?
