### ISSUE TITLE
[management] User search is not accurate

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#5150]
Dataset used to reproduce: 

1. Create 7 users with the same first name: 
```
curl 'http://localhost:8083/management/organizations/DEFAULT/users/' \
  -H 'Authorization: Basic YWRtaW46YWRtaW4=' \
  -H 'Content-Type: application/json' \
  -d '{"firstname":"Grégory","lastname":"Marchand","email":"gregory.marchand@gravitee.io"}'

curl 'http://localhost:8083/management/organizations/DEFAULT/users/' \
  -H 'Authorization: Basic YWRtaW46YWRtaW4=' \
  -H 'Content-Type: application/json' \
  -d '{"firstname":"Grégory","lastname":"Martin","email":"gregory.martin@gravitee.io"}'

curl 'http://localhost:8083/management/organizations/DEFAULT/users/' \
  -H 'Authorization: Basic YWRtaW46YWRtaW4=' \
  -H 'Content-Type: application/json' \
  -d '{"firstname":"Gregory","lastname":"Martinez","email":"gregory.martinez@gravitee.io"}'

curl 'http://localhost:8083/management/organizations/DEFAULT/users/' \
  -H 'Authorization: Basic YWRtaW46YWRtaW4=' \
  -H 'Content-Type: application/json' \
  -d '{"firstname":"Grégory","lastname":"Test","email":"gregory.test@gravitee.io"}'

curl 'http://localhost:8083/management/organizations/DEFAULT/users/' \
  -H 'Authorization: Basic YWRtaW46YWRtaW4=' \
  -H 'Content-Type: application/json' \
  -d '{"firstname":"Gregory","lastname":"Hidden","email":"gregory.hidden@gravitee.io"}'

curl 'http://localhost:8083/management/organizations/DEFAULT/users/' \
  -H 'Authorization: Basic YWRtaW46YWRtaW4=' \
  -H 'Content-Type: application/json' \
  -d '{"firstname":"Grégory","lastname":"Caché","email":"gregory.cache@gravitee.io"}'

curl 'http://localhost:8083/management/organizations/DEFAULT/users/' \
  -H 'Authorization: Basic YWRtaW46YWRtaW4=' \
  -H 'Content-Type: application/json' \
  -d '{"firstname":"Grégory","lastname":"Dos","email":"gregory.dos@gravitee.io"}'
```

2. Search with the first name => OK

<img width="957" alt="Capture d’écran 2021-02-26 à 13 33 44" src="https://user-images.githubusercontent.com/1580262/109300781-4456b680-7837-11eb-93f3-3766075b25ec.png">

3. Search now with the first name and a part of the last name => KO

<img width="740" alt="Capture d’écran 2021-02-26 à 13 34 23" src="https://user-images.githubusercontent.com/1580262/109300972-8a137f00-7837-11eb-97d7-687053d67445.png">
<img width="959" alt="Capture d’écran 2021-02-26 à 13 35 32" src="https://user-images.githubusercontent.com/1580262/109300976-8aac1580-7837-11eb-91fb-d3bcdc624cef.png">
<img width="958" alt="Capture d’écran 2021-02-26 à 13 35 14" src="https://user-images.githubusercontent.com/1580262/109300977-8b44ac00-7837-11eb-910a-e22d9d1cbf9c.png">
<img width="956" alt="Capture d’écran 2021-02-26 à 13 35 08" src="https://user-images.githubusercontent.com/1580262/109300978-8b44ac00-7837-11eb-8312-f87be58d562e.png">
<img width="958" alt="Capture d’écran 2021-02-26 à 13 34 43" src="https://user-images.githubusercontent.com/1580262/109300980-8bdd4280-7837-11eb-9edd-e062ad43ffec.png">

**Comment by leleueri** [comment]
Problem comes from the Term transformation, all element preserve the accent for example that's why only two result are provided when the query contains "gregory m".
In the commit c71d048  some change have been done to analyze firstname/lastname and displayname but research don't restrict the result when typig the lastname in addition of the firstname.
