### ISSUE TITLE
text overlap on description for mandatory fields

### ISSUE THREAD

**Issue by patelami** [gravitee-io/issues#5156]
As a user, I should see the error messages when I move to the next step on the create API form 

### Steps to Reproduce (for bugs)
1. Go to APIM console > APIs > Create

### Current Behavior
Currently, the error checking is done at the time of field selection and 
We are seeing the _error message_ appears on the same line as the _description_.
![Screenshot 2021-03-02 at 11.05.28.png](https://images.zenhubusercontent.com/6037d57eba9d3cc0b0412549/f7ddbd69-55ac-4045-94ac-f2debe023c20)

<img width="863" alt="Screenshot 2021-03-02 at 12 16 51" src="https://user-images.githubusercontent.com/14215437/109647543-52674880-7b51-11eb-97ec-ada7ac711769.png">

### Expected  Behavior
1. 
Given I am on create API page
AND I enter the text in the  _field name_
AND I select _field name_ to enter the text
Then I should see the description under the text field

2. 
Given I am on create API page
AND I don't enter the text in the  _field name_
And I click on the different field 
Then I should see the error message after the description 

|field name|description|error message|
|Name|API Name|API Name is required
|Version|API Version (ex: 1.0)|API Version is required|
|Description|Provide a description of your API, what it does, ...|API Description is required|
|Context-path|Path where API is exposed, must start with a '/' and must contain any letter, capitalize letter, number, dash or underscore.|Context path is required|

### Possible Solution
- Error checking should be done when the user clicks on the Next button
OR
- The error message should appear before/after the description to be able to see the error message or description

### Environment
* Version used: 3.6.0
* Browser Name: chrome

**Comment by gaetanmaisse** [comment]
Closing as it has been fixed in APIM 3.10+
