### ISSUE TITLE
The Curl command on the bottom of the page is out of screen

### ISSUE THREAD

**Issue by patelami** [gravitee-io/issues#5158]
As a user, I should be able to copy the curl command from my subscription page

### Steps to Reproduce (for bugs)
1. Go to APIM Portal > [My Subscription](http://localhost:8085/applications/subscriptions)

### Current Behavior
Currently, the curl command is appearing outside the clipboard
<img width="1845" alt="Screenshot 2021-03-02 at 12 42 21" src="https://user-images.githubusercontent.com/14215437/109652336-8e051100-7b57-11eb-988e-b1df350c8cd8.png">

* Version: 3.6.0
* Browser Name: Chrome

**Comment by phiz71** [comment]
Duplicates #5103

**Comment by aelamrani** [comment]
Fixed by https://github.com/gravitee-io/issues/issues/5103
