### ISSUE TITLE
[portal] inconsistent display in Portal search box

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#5160]
### Expected Behavior
Have the same display in search box whatever the browser window size excluding the display of labels

### Current Behavior
Labels are displayed or hided when the window is resized

<img width="1352" alt="Capture d’écran 2021-03-03 à 17 10 30" src="https://user-images.githubusercontent.com/79909781/109844081-106efd00-7c4c-11eb-8a03-17883e777f73.png">
<img width="1426" alt="Capture d’écran 2021-03-03 à 17 11 02" src="https://user-images.githubusercontent.com/79909781/109844096-14028400-7c4c-11eb-8fe3-8105c158ece0.png">

### Steps to Reproduce (for bugs)
1. Create an API in Console
2. Add some Labels
3. Publish it in Portal
4. In the Catalog Tab, resize the browser window

Only reproducible in 3.5.x and not in 3.0

### Your Environment
* Version used: 3.5.x
* Browser Name and version: N/A
* Operating System and version: N/A

**Comment by leleueri** [comment]
Solved in [3.5.8](https://github.com/gravitee-io/issues/milestone/355) thanks to the upgrade of ui-components. 
See #5234 and #5233
