### ISSUE TITLE
[management] not possible to delete a deprecated v2 api

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#5169]
It is not possible to delete a deprecated api in v2.

### Steps to Reproduce (for bugs)
1. Create a v2 api with a plan (or create with plan in v1, then migrate to v2)
2. Deprecate the api -> it will change its lifecycle state to `DEPRECATE` and update plans to `DEPRECATED` status
3. Delete the API -> not possible, there is a bug

### Possible Solution
When updating an API to deprecate it, all plans in status `STAGING` or `PUBLISHED` are deprecated.
But, the API definition (v2) is not updated with new plans status.

So, when searching for the api to delete, the definition is used to get the plans, which are still in `PUBLISHED`, making impossible to delete the API

**Comment by NicolasGeraud** [comment]
duplicate #5113
