### ISSUE TITLE
[portal] Application menu disappear when login with user

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#518]
I migrate in 1.4.1
i executed migration script.
All is OK
When loggued with admin user, all is OK and shown.
I created a new api, and i suscribed existing applications on this api.
When user of this application want to see his subscription keys, application menu is not shown. So he can't know his api keys

### Your Environment
* Version used: 1.4.1, 1.4.0-SNAPSHOT

**Comment by brasseld** [comment]
Hi @vdelattre,

I didn't get you.
What is the profil of the user ? (you can click on the gravitee.io icon at the top-left corner):
<img width="1603" alt="capture d ecran 2017-03-29 a 14 16 31" src="https://cloud.githubusercontent.com/assets/133094/24453987/41763860-148a-11e7-91fa-2a3a65652182.png">

**Comment by vdelattre** [comment]
in your image, it's shown user, for me, it's empty

**Comment by brasseld** [comment]
From where does your user come from ? LDAP, created from portal, inmemory ?

**Comment by vdelattre** [comment]
from LDAP, created from portal

**Comment by brasseld** [comment]
Did you try to refresh your browser ?

**Comment by vdelattre** [comment]
here is json user:

{
  "firstname": "DELATTRE",
  "lastname": "VINCENT",
  "username": "xfr2347001",
  "email": "xxxxx",
  "roles": [
    "API_CONSUMER"
  ],
  "source": "ldap",
  "sourceId": "uid=XFR2347001,ou=AUCHAN-FR,ou=users,dc=auchan,dc=local",
  "lastConnectionAt": 1490789834268,
  "created_at": 1490779244643,
  "updated_at": 1490789834268
}

**Comment by vdelattre** [comment]
yes i try

**Comment by vdelattre** [comment]
another user:
{
  "firstname": "DELOBEL",
  "lastname": "JEAN-MARIE",
  "username": "FRA0044237",
  "email": "xxxx",
  "roles": [
    "API_CONSUMER"
  ],
  "source": "ldap",
  "sourceId": "uid=FRA0044237,ou=AUCHAN-FR,ou=users,dc=auchan,dc=local",
  "lastConnectionAt": 1490788780169,
  "created_at": 1490774177000,
  "updated_at": 1490788780169
}

**Comment by brasseld** [comment]
If you're trying to access /#!/user by adding it at the end of your http://host:port, is it working ?

Something like http://host:port/#!/user

**Comment by vdelattre** [comment]
yes:
![image](https://cloud.githubusercontent.com/assets/22543323/24454352/cf009134-148b-11e7-8339-c724258aa8c7.png)

**Comment by brasseld** [comment]
Is it a fresh install ?

**Comment by vdelattre** [comment]
Je suis en réunion David
Non c'est une base migrée créer en version 1.2 je crois

Le 29 mars 2017 2:30 PM, "Brassely David" <notifications@github.com> a
écrit :

**Comment by vdelattre** [comment]
Je peux te répondre mais pour l'instant je suis sur mon tél et je n'ai pas
acces à l'appli

Le 29 mars 2017 2:34 PM, "delattre vincent" <vdelattre.partner@gmail.com> a
écrit :

**Comment by vdelattre** [comment]
when loggued with inmemory user (user, api1) there is no problem.

{
  "username": "api1",
  "roles": [
    "API_CONSUMER"
  ],
  "source": "memory",
  "sourceId": "api1",
  "lastConnectionAt": 1490858987672,
  "created_at": 1490858986572,
  "updated_at": 1490858987672
}


{
  "firstname": "DELATTRE",
  "lastname": "VINCENT",
  "username": "xfr2347001",
  "email": "vdelattrexxxxx",
  "roles": [
    "API_CONSUMER"
  ],
  "source": "ldap",
  "sourceId": "uid=XFR2347001,ou=AUCHAN-FR,ou=users,dc=auchan,dc=local",
  "lastConnectionAt": 1490789834268,
  "created_at": 1490779244643,
  "updated_at": 1490789834268
}

For information, in ldap, users are not defined in Gravitee Application. May be it's that?
here ldap config:

- type: ldap
      context-source-username: "cn=SVCGRAVITEE,ou=servicesaccounts,dc=auchan,dc=local"
      context-source-password: "xxxxx"
      context-source-url: "ldap://a3d.fr.xxxxxx"
      context-source-base: "dc=auchan,dc=local" # the context source base
      user-search-base: "ou=users"
      user-search-filter: "uid={0}"
      group-search-base: "ou=GRAVITEE,ou=AUCHAN-FR,ou=applications"
      group-search-filter: "member={0}"
      group-role-attribute: "cn"
      role-mapping: true
      role-mapper: {
         API_CONSUMER: API_CONSUMER,
         API_PUBLISHER: API_PUBLISHER,
         ADMIN: ADMIN,
         USER: USER
      }
