### ISSUE TITLE
Failed at the @gravitee/ui-components@1.3.2 postinstall script on Windows 10

### ISSUE THREAD

**Issue by aliFetvaci61** [gravitee-io/issues#5195]
In gravitee-management-webui-3.6.0 version 

run "npm install" script from CMD.  rm -rf node_modules/codemirror/mode/rpm/changes has PROBLEM. How can I solve this problem. I think This problem is windows platform based.

> @gravitee/ui-components@1.3.2 postinstall C:\Users\alife\Desktop\gravitee-management-webui-3.6.0\node_modules\@gravitee\ui-components
> rm -rf node_modules/codemirror/mode/rpm/changes

'rm' is not recognized as an internal or external command,
operable program or batch file.
npm WARN gravitee-management-webui@3.6.0 No repository field.
npm WARN gravitee-management-webui@3.6.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\webpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\karma\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @gravitee/ui-components@1.3.2 postinstall: `rm -rf node_modules/codemirror/mode/rpm/changes`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @gravitee/ui-components@1.3.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\alife\AppData\Roaming\npm-cache\_logs\2021-03-12T08_58_44_311Z-debug.log

**Comment by NicolasGeraud** [comment]
hi @aliFetvaci61 can you try to remove those 2 lines ?
https://github.com/gravitee-io/gravitee-ui-components/blob/cea379f563dc77a730ace1a2314019f4952553e4/package.json#L28
https://github.com/gravitee-io/gravitee-ui-components/blob/cea379f563dc77a730ace1a2314019f4952553e4/package.json#L29
