### ISSUE TITLE
[portal] context path not shown for user

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#520]
a user who suscribe an api can't show context path to use

when loggued with admin user, when i click on an api, conext path is shown at top right corner

### Your Environment
* Version used: 1.4.1

**Comment by brasseld** [comment]
@vdelattre do you mean that is was possible to have a look to context-path with previous version ?

or is it something new ?

**Comment by vdelattre** [comment]
It was possible with admin login but notre possible with user login

Le 29 mars 2017 2:36 PM, "Brassely David" <notifications@github.com> a
écrit :

**Comment by brasseld** [comment]
Ok, so this issue will be resolved with Gravitee.io APIM 1.5 where we are adding a new API portal.

Ref: https://github.com/gravitee-io/issues/issues/517

**Comment by brasseld** [comment]
Closed since version 1.5
