### ISSUE TITLE
[Management] Swagger editor truncated

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#5200]
As a API Publisher, when I import a swagger the textarea/codemirror area is small and the scroll drifts.

### Expected Behavior

All document (or at least more lines) is displayed and the scroll doesn't drift.

### Current Behavior
Only few lines displayed and scroll drifts

![image](https://user-images.githubusercontent.com/3110552/110950022-9f160500-8343-11eb-91c3-d6a53e7681d4.png)

### Steps to Reproduce (for bugs)

1. import https://petstore.swagger.io/v2/swagger.yaml
2. try to edit the swagger 

### Your Environment
* Version used: 3.6.0 
* Browser Name and version: Firefox & Chrome
* Operating System and version: Ubuntu

**Comment by gaetanmaisse** [comment]
Closing as it has been fixed in the latest version of APIM + UI components
