### ISSUE TITLE
[FR] Allow creation of APIs with same context-path while they are on different shards 

### ISSUE THREAD

**Issue by DarthSlider** [gravitee-io/issues#5208]
We have a multitenant installation of gravitee and each team (and each environment) have their own deployment of gateway separated with a unique sharding tag.
Any team might want to publish their own /api/ (as an example) which is completely fine and now they must publish it like /teamname-api/ which looks weird.

**Comment by brasseld** [comment]
Why not using virtual-hosting in that case ? It will allow you to have multiple APIs with the same context-path.

**Comment by DarthSlider** [comment]
Hmm, totally miss this option.
Thanks for the solution!

I think this issue might be closed then.
