### ISSUE TITLE
[gateway] [management] upgrade to Vert.x 4

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#5220]
https://vertx.io/blog/from-vert-x-3-to-vert-x-4/

**Comment by larsnaesbye** [comment]
I did start suggestion moving to Vert.x 3.9.x (see https://github.com/gravitee-io/gravitee-parent/pull/19) before upgrading to 4.x. Might that be something we can achieve in between? It would fix a bunch of CVEs and include newer Netty and Jackson versions.
