### ISSUE TITLE
[management] Using the right naming convention

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#5235]
According to our internal convention, `management UI`, `console`, or `Administration portal` should be replaced by `APIM Console`.
Example here, the sign in form of the console.

![image.png](https://images.zenhubusercontent.com/601c1f2212e54321cef611f9/3dd2b647-8b07-4326-86bc-9bc6030d7e57)

https://docs.google.com/spreadsheets/d/1RzE439odTCteX9ODZFweV3YQolWaHx_fM8ehSp3XE7A/edit?ts=604f80f6#gid=0

**Comment by plsstephenson** [comment]
The naming convention was not up to date - please use APIM Console instead of APIM Management
