### ISSUE TITLE
[portal] error on swagger and try-it when yaml document

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#524]
I added swagger document page on api.
My document is yaml format:
ex:
swagger: '2.0'
info:
  description: Referential functional-settings apis
  version: 0.1-SNAPSHOT
  title: Functional-settings API
tags:
  - name: functional-settings
    description: functional-settings
basePath: /v0
paths:
  /functional-settings:
    get:
      tags:
        - functional-settings
      summary: Get functional-settings
      operationId: getAll
      consumes:
        - application/json
      produces:
        - application/json
        - application/xml
      parameters:
        - name: entity
          in: query
          description: filter entity value
          required: false
          type: string
        - name: typeCode
          in: query
          description: filter typeCode value
          required: false
          type: string
        - name: applicationDate
          in: query
          description: filter applicationDate greater or equal value
          required: false
          type: string
        - name: endDate
          in: query
          description: filter endDate lower or equal value
          required: false
          type: string
      responses:
        '200':
          description: OK
        '206':
          description: 'Partial response, use pagination'
        '400':
          description: bad criteria specified

I check only tryit mode in cofiguration
My page is shown OK:
![image](https://cloud.githubusercontent.com/assets/22543323/24498665/6fbd343e-153f-11e7-8d7b-ce53bd132836.png)

When i put url in tryit config path, document is not shown.
![image](https://cloud.githubusercontent.com/assets/22543323/24498700/92b19a16-153f-11e7-882e-8612d1aac092.png)

I configure the same way (tryit mode and path) but with json document format, swagger is shown OK

### Your Environment
* Version used: 1.4.1

**Comment by brasseld** [comment]
Hi @vdelattre,

It seems to be an issue with the angular module we are using: https://github.com/Orange-OpenSource/angular-swagger-ui

We are looking to find an alternative to support this kind of feature from Gravitee.io
