### ISSUE TITLE
[gateway] [management] upgrade to Vert.x 3.9.x

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#5241]

**Comment by larsnaesbye** [comment]
Awesome to get Vert.X upgraded - a lot of really nice things are coming in 4.x

I did this PR a while ago :) 

https://github.com/gravitee-io/gravitee-parent/pull/19

**Comment by phiz71** [comment]
Closing this issue since it duplicates #4095.

Thank you @larsnaesbye, we will look at your PR soon.

**Comment by larsnaesbye** [comment]
@phiz71 
Should we go for 3.9.6 in the PR right away? (I will just change it and squash commits)
Also, since 3.9.1 and newer reference a newer Netty version (4.1.49.Final), should we upgrade to this version too so they are in sync?
