### ISSUE TITLE
[visual issue] selecting policies are pushing the menu right side

### ISSUE THREAD

**Issue by patelami** [gravitee-io/issues#5242]
### Expected Behavior
As a user, when I select some policies, I should still see the scroll bar and menu on the right

### Current Behavior
Selecting `generate JWT policy` and `Rest to Soap Policy` will push the menu and screen on the right.
- the menu will cut from the right side
- the scroll for the policy menu will disappear 
![Screenshot 2021-03-16 at 10.53.24.png](https://images.zenhubusercontent.com/6037d57eba9d3cc0b0412549/926a999d-cba5-4b7b-8b45-ff4233fac7c7)
![Screenshot 2021-03-16 at 10.52.35.png](https://images.zenhubusercontent.com/6037d57eba9d3cc0b0412549/dbe9af90-1253-403a-a46b-a45b0c83a541)
### Steps to Reproduce (for bugs)
1. select an API
2. go to the design studio
3. create and select a design flow
4. select `generate JWT policy`
5. select`Rest to Soap Policy`

### Your Environment

* Version used: nightly and local

**Comment by aelamrani** [comment]
I am wondering if it is really a UAT or a bug already existing in a previous version

**Comment by patelami** [comment]
I am not sure how can i check on other versions? Which versions should I check it on?

**Comment by aelamrani** [comment]
The new Design Studio has been introduced in 3.4. But as this version is not supported anymore, we may have to fix something in 3.5 (as it seems to be unrelated to any dev in the current sprint).

**Comment by phiz71** [comment]
OK on 3.5.x environment
