### ISSUE TITLE
[visual issue] portal category has some dummy text 

### ISSUE THREAD

**Issue by patelami** [gravitee-io/issues#5243]
### Expected Behavior
As a user, when I want to select portal categories, I should see a category name with short description

### Current Behavior
Currently, the following categories have dummy text  :

- store
- suppliers
- machine learning
- open data
- stock

![Screenshot 2021-03-16 at 13.13.23.png](https://images.zenhubusercontent.com/6037d57eba9d3cc0b0412549/1f43695b-7b8e-4f00-804a-5493394cddd8)

### Steps to Reproduce (for bugs)

1. select an API
2. Go to portal > details > portal categories

### Your Environment

* Version used: nightly

**Comment by aelamrani** [comment]
It is about sample data you can change here: https://nightly.gravitee.io/#!/environments/DEFAULT/settings/categories

But maybe we should improve the display of this description.

**Comment by patelami** [comment]
ok, all the items in category portal is test data and it is customisable. Please feel free to delete this issue.

**Comment by phiz71** [comment]
I think we can keep this issue to improve description rendering as @aelamrani said.
