### ISSUE TITLE
[management] [portal] unable to logout with OIDC provider

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#5247]
When using OIDC provider to sign-in,  I'am able to sign-out from APIM portal/console but not from the OIDC provider.

**Comment by tcompiegne** [comment]
Must check the consequences about this one : https://github.com/gravitee-io/issues/issues/4975

**Comment by RachidKelidou** [comment]
The bug is still present in the console side

**Comment by RachidKelidou** [comment]
another strange behavior : if you disconnect from the console, you are disconnected from the console **but not from the portal**.

**Comment by jhaeyaert** [comment]
FYI: seems really close to an old issues https://github.com/gravitee-io/issues/issues/4532 (but inverted).

**Comment by menloperk** [comment]
This is working for me on the portal. However, this is not working on the console!

**Comment by RachidKelidou** [comment]
> This is working for me on the portal. However, this is not working on the console!

in which version you are ? this issue was fixed on 3.5
today we're in 3.19 and I think it's something fixed on both side now
