### ISSUE TITLE
[portal] split configuration menu

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#525]
Currently, the `Configuration` menu manages views, sharding tags, tenants, and groups.
With #468 an other configuration item will appears.

It can be useful to split the config menu between portal configuration and platform configuration.

Platform Cfg :
 - sharding tags
 - tenants

Portal Cfg : 
 - views
 - groups
 - pages

**Comment by brasseld** [comment]
Duplicate of #1101
