### ISSUE TITLE
[management] As a simple USER I can see the Analytics dashboard but I have a permission error

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#5251]
![Capture d’écran 2021-03-17 à 10 05 36](https://user-images.githubusercontent.com/1580262/111442157-588c2600-8708-11eb-9256-7f116f1343e2.png)

**Comment by aelamrani** [comment]
Probably because of this permission: https://github.com/gravitee-io/gravitee-management-webui/pull/1483/files#diff-1ef27266ab6ba1ce2308ac08cf2e79a295533c5891496b6b8d6574b762b5e52fL139

This is well handled for menu items (hidden or not) but most probably not well handled on the tabs.

**Comment by jhaeyaert** [comment]
The opened Pull Request (https://github.com/gravitee-io/gravitee-management-webui/pull/1525) restore the previous behavior checking that the use has the `environment_platform` read permission. However, we have to open another issue I encountered when I fixed this one (some particular cases can still produce an insufficient permission error).
