### ISSUE TITLE
[management] Disable an endpoint of an API

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#5258]
It should be possible to disable an endpoint to prevent load-balancer to send requests to it.

![image](https://user-images.githubusercontent.com/13161768/111510806-6a90b780-874e-11eb-9711-ad620842cb1f.png)

**Comment by fabMrc** [comment]
Hi is it different to set endpoint in maintenance mode ?

**Comment by aelamrani** [comment]
What do you mean by maintenance mode?

**Comment by fabMrc** [comment]
Disabled as a backup node

**Comment by aelamrani** [comment]
Ok so now the secondary endpoint is used as a fallback endpoint in case no primary endpoint is up.

So this is a different need here

**Comment by fabMrc** [comment]
Ok A kind a second level of failover, nice

**Comment by aelamrani** [comment]
To be clear here, the secondary endpoint is already available as part of the product.
