### ISSUE TITLE
[portal] Quickly know who is the app owner

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#526]
When loggued with admin user, i see all applications.
But all applications have same name : 'Default application'. I think this application is created at first login of a user.
I will be better to have another name: like '<login user> : default application'
ex: for user xfr2347001
application name: 'xfr234701 : default application'

### Your Environment
* Version used: 1.4.1

**Comment by NicolasGeraud** [comment]
Hi @vdelattre 
As an admin, why do you want to see userid in the application name ? 

Currently, if you fill the search input with the userid, we filter the list

**Comment by vdelattre** [comment]
yes you're right, i didn't think to use this field. ;)
but when all applications are shown, it could be usefull to see rapidly who own this application
Or shown who created applications

**Comment by NicolasGeraud** [comment]
We are working on the developer portal, and management screens will be adapted for admin/support purpose.

We will take account of your suggestion.

Thanks.

**Comment by brasseld** [comment]
Application's primary-owner has been added to the applications table.
