### ISSUE TITLE
[cicd] Gravitee Managent Web UI Maven License Plugin Configuration

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [gravitee-io/issues#5263]
For https://github.com/gravitee-io/gravitee-management-webui , the "Nexus Staging" Process is a maven build, and it fails because some files, if not all, in the `node/` folder do not have the license header expected by the maven license plugin configuration.

### Expected Behavior

While running the "Nexus staging" Process in the new CICD, the maven build should not fail becasue of missing headers in files located in the `node` folder.

### Current Behavior

The Nexus Staging fails because of the above descirbed issue

### Possible Solution

I have fixed the issue on git branch `3.5.x`, by adding the ccc exclude filter in the `pom.xml`, see [here](https://github.com/gravitee-io/gravitee-management-webui/blob/98fa8f40d92fcb11894cf528447348e9833b058d/pom.xml#L92). 

This exclude filter should be added on all git branch, at least on support branch for versions higher than 3.6.0 : so at least on `3.6.x` branch. 

I believe it would not hurt anything, to add this exclude filter on all git branches.

### Steps to Reproduce (for bugs)
* **VERY IMPORTANT: DO NOT TRY AND REPRODUCE THIS BUG WITHOUT CONTACTING DEVOPS TEAM : THIS OPERATION IMPACTS IMMUTABLE NEXUS PUBLIC SERVICE GRAVITEE PRODUCTS**
* You must be a gravitee Team member
* log into Circle CI Web UI with Github auth
* Go to your Circle CI User Settigns menu
* Create a "Personal API Token
* Execute this : 

```bash
export CCI_TOKEN=<you circle ci token>
export ORG_NAME="gravitee-io"
export REPO_NAME="gravitee-gateway"
export BRANCH="3.5.x"
export GIO_RELEASE_VERSION="3.5.8"
export JSON_PAYLOAD="{

    \"branch\": \"${BRANCH}\",
    \"parameters\":

    {
        \"gio_action\": \"nexus_staging\",
        \"secrethub_org\": \"graviteeio\",
        \"secrethub_repo\": \"cicd\",
        \"s3_bucket_name\": \"prepared-nexus-staging-gravitee-apim-3_5_8\",
        \"maven_profile_id\": \"gravitee-release\"
    }

}"

curl -X GET -H 'Content-Type: application/json' -H 'Accept: application/json' -H "Circle-Token: ${CCI_TOKEN}" https://circleci.com/api/v2/me | jq .
curl -X POST -d "${JSON_PAYLOAD}" -H 'Content-Type: application/json' -H 'Accept: application/json' -H "Circle-Token: ${CCI_TOKEN}" https://circleci.com/api/v2/project/gh/${ORG_NAME}/${REPO_NAME}/pipeline | jq .

```

### Your Environment

* Version used: `3.5.8-SNAPSHOT`
* Browser Name and version: N/A
* Operating System and version: docker container base image `maven:3.6.3-openjdk-11`

**Comment by gaetanmaisse** [comment]
Close as outdated.
