### ISSUE TITLE
[management] Duplicate tooltip on main menu 

### ISSUE THREAD

**Issue by patelami** [gravitee-io/issues#5265]
Currently, when we are hovering on the menu, we are seeing duplicate tool tip
![Screenshot 2021-03-18 at 11.06.31.png](https://images.zenhubusercontent.com/6037d57eba9d3cc0b0412549/bb2443b4-db15-4a49-bdf0-8be1addc1ad6)

### Possible Solution
We actually don't need a tooltip on the menu, because it does not add any value. 

### Steps to Reproduce (for bugs)

1. Go to APIM
2. Hover on the main menu on left side

### Context
A tooltip is a brief, informative message that appears when a user interacts with an element in a graphical user interface (GUI).  At the moment we are just providing the same information on the hover, so it does not actually add any value. 

### Your Environment

* Version used: local

**Comment by gaetanmaisse** [comment]
Closing as it has been fixed (everything fine on 3.10+)
