### ISSUE TITLE
[Portal] impossible to change group of application

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#527]
when loggued in admin user, and editing an application (old or just created), i can't change group.
only existing group or none label is available.
Maybe linked to #518 

### Your Environment
* Version used: 1.4.1

**Comment by vdelattre** [comment]
so it's imposssible to inherite of group members

**Comment by brasseld** [comment]
Fix has been loosed when accepting this commit: https://github.com/gravitee-io/gravitee-management-webui/commit/51fafa85c01fb20b7154f74d0b579a76d1173a73

**Comment by NicolasGeraud** [comment]
re fixed in #555
