### ISSUE TITLE
[management] dates are not updated when create/update a category

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#5275]
At least with a jdbc provider. Not tested with mongodb

### Steps to Reproduce (for bugs)

1. Create a category and look at the db: 
2. -> created_at and updated_at are null
3. Add a picture to the category and look at the DB:
4. -> created_at and updated_at are null
5. -> not able to display categories anymore

### Your Environment

* Version used: 3.5.7

**Comment by patelami** [comment]
A similar issue is also happening when trying to access APIs.
