### ISSUE TITLE
[gateway] Update reporter-api

### ISSUE THREAD

**Issue by larsnaesbye** [gravitee-io/issues#5279]
reporter-api should get updated to the 1.20.0 version to roll fixes into the main distribution.

PR: https://github.com/gravitee-io/gravitee-gateway/pull/646

**Comment by ytvnr** [comment]
Tested locally, timestamp is present
![image](https://user-images.githubusercontent.com/47851994/114018252-516eb880-986d-11eb-8da7-71c0e29706ae.png)


Thank you @larsnaesbye !

**Comment by larsnaesbye** [comment]
Perfect :) Thank you for merging, @ytvnr  !
