### ISSUE TITLE
incompatible types error when helm installing

### ISSUE THREAD

**Issue by elijahomolo** [gravitee-io/issues#5283]
I've run the following using helm 3 as per the installation docs:

```
helm repo add graviteeio https://helm.gravitee.io
helm install graviteeio-apim3x graviteeio/apim3
```
The installation fails with:

`Error: template: apim3/templates/gateway/gateway-deployment.yaml:53:13: executing "apim3/templates/gateway/gateway-deployment.yaml" at <ne .Values.gateway.image.tag "nightly">: error calling ne: incompatible types for comparison`

kubernetes version 1.20.2

Am I missing something in the installation?

**Comment by TomSearcher** [comment]
Same issue here. Did you find a workaround?
Thx

**Comment by ghabarid** [comment]
Same issue her!

**Comment by brasseld** [comment]
Hi there,

I'v just published a new version of the chart (3.1.4) which is fixing this issue.

Sorry for the inconvenience.

Regards,

**Comment by ghabarid** [comment]
Hi, 
Thx for ur quick answer. 
The downloaded version works fine. Alle the pods started fine, except the api. It complains about elastic, even though I had disabled it, at es.enable: false; and es.enable: false; elasticsearch.enable: false;
The error:
vert.x-eventloop-thread-0] ERROR i.g.e.client.http.HttpClient - Unable to get a connection to Elasticsearch: failed to resolve 'graviteeio-apim-elasticsearch-client.default.svc.cluster.local' after 2 queries
Is it a misunderstood?

**Comment by brasseld** [comment]
Hi,

Yea, the management API is requiring a connection to an ES. As you disable embedded ES from the chart, there is no way for the Mgmt-api to gain an access to ES. Reason why you are getting this log.

**Comment by ghabarid** [comment]
Super, 
And I guess it s the same for Mongodb. We need to have an instance running, no way for in memory test db?

**Comment by brasseld** [comment]
No, unfortunately there is no way for in-memory db at this time.

**Comment by MLukman** [comment]
This issue still happens with 3.1.27
