### ISSUE TITLE
API page can not found

### ISSUE THREAD

**Issue by patelami** [gravitee-io/issues#5286]
Given I have created alerts 
And I go to APIs
I should be able to see the list of APIs
This is an intermittent issue and I can not reproduce this error every time.

https://images.zenhubusercontent.com/61280156/c8787704-8808-4080-a517-9bfc0ee6aceb/apis_can_not_find_error.mov

**Comment by aelamrani** [comment]
It seems you have a sync pb between your UI and your API. Is that possible that you have switched from a version A to a version B and you have not refreshed your browser?

**Comment by patelami** [comment]
@aelamrani : 

So I have: 
(1) Rerun the config for gravitee-management-rest-api and gravitee-gateway.
(2) Restarted the chrome

I am still seeing the same error.

**Comment by patelami** [comment]
This was a issue with rebase. This is now working fine.
