### ISSUE TITLE
Rename gravitee-repository to gravitee-repository-api

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#53]
_From @brasseld on March 1, 2016 7:45_

Just to maintain the coherence with others API modules (gravitee-policy-api, gravitee-gateway-api, ...)

_Copied from original issue: gravitee-io/release#27_

**Comment by gaetanmaisse** [comment]
Closing as it has been done during the APIM monorepo migration, see https://github.com/gravitee-io/gravitee-api-management/tree/master/gravitee-apim-repository.
