### ISSUE TITLE
[management] Unable to use default image on API

### ISSUE THREAD

**Issue by patelami** [gravitee-io/issues#5303]
### Expected Behavior
Given I have updated the API image
And I want to restore to the default image
Then I should be able to see the default image

### Current Behavior
unable to save default image after saving the image
https://images.zenhubusercontent.com/61280156/d5306058-19a0-4cac-b822-953f70fecc2c/use_default_image.mov

### Steps to Reproduce (for bugs)
1. select an API and got to details 
2. update the image
3. click on use default 

### Your Environment

* Version used: 3.5.x

**Comment by apoddany** [comment]
This is also true for background picture. When clicking on "Use default", it is not possible to revert back to default background.
The previous updated background remains.
