### ISSUE TITLE
[management] Allow policies modification when editing a plan

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#5315]
Since the introduction of the design studio, it is not possible to change the configuration of policies when editing a plan. However, it is still possible to create these policies.
Changing these policies is only possible in the design studio.

It should be possible to change the configuration of policies when editing a plan, as was the case before the design studio.

⚠️ If a plan has been modified in the studio (flows added, with quota or rate limit on each, etc) it becomes difficult to know which policy to update.

**Comment by ibahloul** [comment]
@marcambier @gaetanmaisse @phiz71 @ytvnr Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Graviteeio---API-Management-601c1f73be51260015c7bb26/issues/gravitee-io/issues/5315?planning-poker)
