### ISSUE TITLE
[gateway] Update Gateway API to add an access to the SSLSession

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#5322]
It could be useful to get the data from SSL certificate using an EL syntax like `{#request.ssl.attibutes['']}`

**Comment by larsnaesbye** [comment]
That would indeed be very useful.

**Comment by ibahloul** [comment]
Hello @larsnaesbye,
Could you please tell us how this could be very useful? It could be interesting to have a real use case :)

**Comment by larsnaesbye** [comment]
> Hello @larsnaesbye,
> Could you please tell us how this could be very useful? It could be interesting to have a real use case :)

Well, since we have multiple domains leading to the same gateway, we have had cases where it could be interesting to know which domain the user accessed.

**Comment by gcusnieux** [comment]
Maybe the AM team is interested ? @tcompiegne @leleueri

**Comment by RubenMMSantos** [comment]
Ticket tested using docker image of nightly, confirmed outcome with Florent and working as expected.
