### ISSUE TITLE
list of application drop down is pushed to the end

### ISSUE THREAD

**Issue by patelami** [gravitee-io/issues#5327]
### Expected Behavior
the drop-down with a list of application should open near `application` section

### Current Behavior
currently, the dropdown list is pushed to the end

![Screenshot 2021-03-31 at 11.44.42.png](https://images.zenhubusercontent.com/6037d57eba9d3cc0b0412549/c473fcc0-907a-40fd-95fe-5b32a8c89cbc)

**Comment by aelamrani** [comment]
Already been fixed
