### ISSUE TITLE
[portal] display view name on the api card

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#533]
We could display views names in the api card.

like this : 
<img width="586" alt="capture d ecran 2017-04-10 10 58 01" src="https://cloud.githubusercontent.com/assets/1028285/24853830/9c81db32-1ddc-11e7-99bf-680a709c92e1.png">

a click on the view badge could redirect user on the api gallery filtered by the clicked view

**Comment by brasseld** [comment]
I think that, instead of displaying views name, we must display labels associated to the API.
See https://github.com/gravitee-io/issues/issues/617

WDYT ?

**Comment by brasseld** [comment]
Ok, let's display view name only since we can have too many labels for an API.
