### ISSUE TITLE
Gravitee.io Helm chart for Access Management version 1.0.13 ingress parsing throws an error

### ISSUE THREAD

**Issue by TomSearcher** [gravitee-io/issues#5330]
### Expected Behavior
The latest helm chart version 1.0.13 does not deploy (for me :-)). 

Here for 1.0.12 it works:
helm install am --namespace test  graviteeio/am --version 1.0.12
NAME: am
LAST DEPLOYED: Wed Mar 31 17:50:42 2021
NAMESPACE: test
STATUS: deployed
REVISION: 1
TEST SUITE: None

### Current Behavior
ingress definition for /management throws an error when using latest version:

helm install am --namespace test  graviteeio/am --version 1.0.13

Error: Ingress.extensions "am-management-api" is invalid: spec.rules[0].host: Invalid value: "map[host:am.example.com paths:[/management /admin]]": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') 

Tested on Google Kubernetes Engine node version: 1.19.8-gke.1600 and 1.18.12-gke.1210.

### Possible Solution
It's the only ingress definition in the helm values file, using an array of hosts.

### Steps to Reproduce (for bugs)
see above using 1.0.12 and 1.0.13 for deployment

**Comment by tcompiegne** [comment]
Hi @TomSearcher 

Thanks for pointing this out.

Will be fixed via the https://github.com/gravitee-io/issues/issues/5312 issues

**Comment by tcompiegne** [comment]
closed by #5312 (available in the 1.0.14 helm chart version)
