### ISSUE TITLE
API Design Cannot save and deploy policy more than once

### ISSUE THREAD

**Issue by idkw** [gravitee-io/issues#5336]
When using the API Design section and editing policies, I can only save a policy and deploy once.
After that any change that I make never gets saved and I have to refresh the page before editing again or I will lose all my work.

### Expected Behavior

The save button should continue to work after deploying and I should not have to refresh the page

### Current Behavior

The save button only works once.

### Possible Solution

No idea, I'm just a user

### Steps to Reproduce (for bugs)

See the video : 

https://user-images.githubusercontent.com/7012331/113318159-75337b00-9310-11eb-977f-52af1d629bdd.mp4

### Context

I was editing policies and was in a sort of  trial and error process.
I wanted to edit the policies and deploy the API, try some requests with postman, edit again etc ...

### Your Environment

* Version used: Using the docker compose at https://raw.githubusercontent.com/gravitee-io/gravitee-docker/master/apim/3.x/docker-compose.yml
* Browser Name and version: Brave Version 1.21.77 Chromium: 89.0.4389.90 (Official Build) (64-bit)
* Operating System and version: Linux Mint 20

**Comment by NicolasGeraud** [comment]
The current workaround is to change the description of the policy.
