### ISSUE TITLE
[portal] Allow to define alerts for a consumer

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#5341]
# User Story
As an API consumer, I want to be able to define alerts to be notified by email when some events occur on my application, so that I can be proactive on the management of errors & response times of the APIs I consume and provide service with as little interruption as possible.

# KPI
For each API consumed, since they have defined at least an error alert or a response time alert, the service interruption time has been reduced by X%.

# Further information
- Alerts are defined at the application level
- The definition of an alert is shared with all members of an application
- Alerts are only notified by email
- Alert notifications all use the same default template
- There is no history of alerts

# Examples
![consumer alerts](https://user-images.githubusercontent.com/82866977/119409325-6bfad500-bce7-11eb-9917-036bba983666.png)

# Tests
## Configuration
- [x] Given the Alert Feature is disabled when I select an application, then the entry "Alerts" is not displayed in the menu  - **PASS**
- [x] Given the Alert Feature is enabled, when I select an application, then the entry "Alerts" is displayed in the menu  - **PASS**
- [x] Given the Alert Feature is enabled and the Alert Engine Plugin is not installed and connected as an application member, when I browse the alerts section, then the alert creation form is not available and the following message is displayed: "Please contact your admin before being able to define alert rules."  - **PASS**
- [x] Given the Alert Feature is enabled and the Alert Engine Plugin is installed, when I browse the alerts section, then the alert creation form is available  - **PASS**
- [x] Given the Alert Feature is enabled and the Alert Engine Plugin is installed, when I browse the analytics section, then a link is displayed on the board "Response Status" and the board "Response Time" - **PASS**

##  API Consumer Permission
- [x] Given an application member allowed to read alerts when I browse the alerts section, then the component that lists alerts is displayed - **PASS**
- [x] Given an application member allowed to create an alert when I browse the alerts section, then the component that allows me to add an alert is displayed - **PASS**
- [x] Given an application member allowed to update an alert when I browse the alert's detail, then I can modify form values and save my changes - **PASS**
- [x] Given a application member allowed to delete an alert, when I browse the alert's detail, then the button "Delete" is enabled - **Not Tested**
- [x] Given a application member not allowed to read alerts, when I browse the alerts section, then the component that lists alerts not displayed and the following message is displayed : "" : - **Not Tested**
- [x] Given a application member not allowed to create an alert, when I browse the alerts section, then the component that allows me to add an alert is not displayed - **PASS**
- [x] Given a application member not allowed to update an alert, when I browse the alert's detail, then the form is in read-only mode - **PASS**
- [x] Given a application member not allowed to delete an alert, when I browse the alert's detail, then the button "Delete" is disabled - **Not Tested**

## Email configuration - **Not Tested**
- [ ] ~~Given an API consumer allowed to define alerts with no email configured, when I browse the alerts section, then the following message is displayed "No email is configured. Please configure your email before being able to define alert rules."~~
- [ ] ~~Given an API consumer allowed to define alerts with a configured email, when I browse the alerts section, then the following message is displayed "All your alerts will be notified by email on the address ..."~~

=> Display the following message instead: "Each member of the application **who has configured his email address** will receive a notification."

- [ ] Givan an alert defined by an application member who does not have a configured email, when I add a new member to this application with a configured email, then he receives an email (when the alert is triggered)

## Form Validation
- [x] Given the error/response time alert creation/update form, when I don't fill all the fields, then the button "Create/Update" is disabled and an error message is displayed below the concerned fields **FAIL**: No error message is displayed. The add an alert button is disabled

### Error Alert
- [x] Given the percent field, when I set a value < 0 or > 100, then the button "Create/Update" is disabled and an error message is displayed - **FAIL**: We can see the button is disabled but the error message is not displayed 
- [x] Given the status code field, when I set a value < 100 or > 599, then the button "Create/Update" is disabled and an error message is displayed - **Not Tested**: This is a drop-down and the user is not allowed to specify value
- [x] Given the period field, when I set a value < 1 or > 55 or %5 != 0, then the button "Create/Update" is disabled and an error message is displayed - **Not Tested**: This is a drop-down and the user is not allowed to specify a value
- [x] Given the error alert creation/update form, when I set a percent value >= 0 and <= 100 and a status code value >= 100 and <= 599 and a period value >= 1 and <= 55 and %5 = 0, then the button "Create/Update" is enabled - **Not Tested**: This is a drop-down and the user is not allowed to specify a value

### Response Time Alert
- [x] Given the average response time field, when I set a value < 1 or > 100000, then the button "Create/Update" is disabled and an error message is displayed - **PASS**
- [x] Given the period field, when I set a value < 1 or > 55 or %5 != 0, then the button "Create/Update" is disabled and an error message is displayed - **Not Tested**: This is a drop-down and the user is not allowed to specify a value
- [x] Given the response time alert creation/update form, when I set an average response time value >= 1 and <= 100000 and a period value >= 1 and <= 55 and %5 = 0, then the button "Create/Update" is enabled
- **PASS**

## List of alerts
- [x] Given no defined alert, when I browse the alerts section, then the following message "" is displayed- **Not Tested**
- [ ] ~~Given an error alert defined with these parameters (), when I create a new alert with the same parameters, then the following message is displayed "" and the alert is not created~~ - **FAIL**: We are able t create a duplicate alert 
- [ ] 
- [x] Given [1, 9] defined alert(s), when I create a new alert with valid parameters, then the alert is added to the list(a.k.a user is able to create 10 alerts) - **PASS**
- [x] Given 10 alerts defined, when I browse  the alerts section, then the component that allows me to add an alert is disabled and the following message "" is displayed - **PASS**: No Error message is displayed

### Error Alert - **Not Tested**
- [ ] Given an error alert defined with these parameters (), when I do this call on my API, then an alert is generated and I receive an email
- [ ] Given an error alert defined with these parameters (), when I do this call on my API, then no alert is generated

### Response Time Alert - **Not Tested**
- [ ] Given a response time alert defined with these parameters (), when I do this call on my API, then an alert is generated and I receive an email
- [ ] Given a response time alert defined with these parameters (), when I do this call on my API, then no alert is generated

#### Portal
- [x] Given an application with defined alerts, when a new user is added to the list of members, then he is also added to the mailing list and receives notifications
- [ ] Given an application with defined alerts, when a user is removed from the list of members, then he is also removed from the mailing list and no longer receive notifications

#### Console - **Not Tested**
- [x] Given an application with defined alerts, when a new user is added to the list of members, then he is also added to the mailing list and receives notifications
- [x] Given an application with defined alerts, when a user is removed from the list of members, then he is also removed from the mailing list and no longer receive notifications
- [x] Given a user group attached to an application with defined alerts, when a new user is added to the user group, then he is also added to the mailing list and receives notifications
- [x] Given a user group attached to an application with defined alerts, when a user is removed from the user group, then he is also removed from the mailing list and no longer receive notifications

### User Groups - **Not Tested**
- [x] Given an application with defined alerts, when a user group is attached to the application, then each member of the group is added to the mailing list and receives notifications
- [x] Given a user group attached to an application with defined alerts, when the user group is detached from the application, then every members of the groupe are removed from the mailing list and no longer receive notifications

## User deletion - **Not Tested**
- [ ] Given a user, when the user is removed from the organization, then the alert for this user is no longer generated

## Application archiving -  **Not Tested**
- [x] Given a defined alert, when I archive the related application, then the alert is no longer generated
- [x] Given a archived application with defined alert, when I restore this application, then I have to define my alerts again

**Comment by patelami** [comment]
Moving this ticket back in progress while trying to figure out, the env setup to test this.

**Comment by patelami** [comment]
@ytvnr : created ticket for the UI issue related to the dropdown: https://github.com/gravitee-io/issues/issues/5653#issue-905183144

**Comment by patelami** [comment]
Following issues are raised while testing this story:
https://github.com/gravitee-io/issues/issues/5666#issue-909309776
https://github.com/gravitee-io/issues/issues/5657#issue-908232406
https://github.com/gravitee-io/issues/issues/5667#issue-909352762

@ibahloul
