### ISSUE TITLE
[management] Migrate a screen with material components to ui-components

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#5347]
The goal of this issue is to replace the components of the following screen, with our ui-components in order to validate the complexity of migrating the components.

![Capture d’écran 2021-04-12 à 17 05 08](https://user-images.githubusercontent.com/1580262/114416720-41c6db00-9bb1-11eb-9d7a-d37a9940297b.png)

The components [cron](https://components.gravitee.io/?path=/story/molecules-gv-cron-editor--simple) have to be updated to allow to hide some part: second, minutes, Xly.

**Comment by gaetanmaisse** [comment]
Closing this issue because we are now migrating to Angular + Angular Material.
