### ISSUE TITLE
[management] flow duplication

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#5366]
Currently there is no existence check when we create an AM flow. 

If a flow with the same type (i.e LOGIN) already exist, instead of updating this one, we create a new one.

**Comment by leleueri** [comment]
We should also fixe an issue in UI part that as fixed in #4764 
https://github.com/gravitee-io/graviteeio-access-management/pull/1001/files#diff-50320cd100b97a18bdf9165c31215be7f36328ae18083bac3bc6a8981b705607R86

**Comment by tcompiegne** [comment]
@leleueri Just updated the PR.
