### ISSUE TITLE
High bandwitdth usage between management API and Mongo

### ISSUE THREAD

**Issue by hjdr4** [gravitee-io/issues#538]
Bandwitdth usage between management API and Mongo backend is high.

### Expected Behavior
Low bandwidth usage.

### Current Behavior
High bandwitdth usage.

### Steps to Reproduce (for bugs)
Start management API component and look at the bandwitdth (iftop).

### Context
Mongo database on datacenter A (3 nodes).
Already running production setup on datacenter A with multiple APIs defined.
Unloaded gateway+api+ui on datacenter B. Available bandwidth between A and B is low (~15Mb/s).

Unloaded stack on datacenter A makes 150Mb/s bursts every few seconds.
Unloaded stack on datacenter B tries to do the same, saturating the link between datacenters.

### Your Environment
* Version used: 1.3.3
* Operating System and version: Debian Jessie

**Comment by brasseld** [comment]
Hi @hjdr4,

This should be resolved in release 1.5 scheduled for next tuesday.
Please have a look to #504
