### ISSUE TITLE
Update ui-component library to 2.3.1

### ISSUE THREAD

**Issue by RachidKelidou** [gravitee-io/issues#5384]

**Comment by tcompiegne** [comment]
Close this one because the 3.5.x version of AM uses a good version of ui-components (without the gv-select bug).

**Comment by tcompiegne** [comment]
Re-open for the 3.7.x version which has the bad version of ui-components (with the gv-select bug).

**Comment by tcompiegne** [comment]
Closed by https://github.com/gravitee-io/graviteeio-access-management/commit/b195cfd4dbbe7bef806d1e616ca4b9fc6026e75d
