### ISSUE TITLE
[management] unable to scroll in the dropdown of the signature field to see all the values in json web token policy

### ISSUE THREAD

**Issue by patelami** [gravitee-io/issues#5386]
**Steps to reproduce:** 
1. Select Json Web Token policy in API design
2. Click the dropdown to select signature 

**Actual Result:** 
The dropdown will open towards the end of the page and not next to the signature field.
This behaviour makes the feature very difficult to select the signature from the dropdown 

Expected Result: 
As a user, I should be able to see all the values of the signature dropdown when I click on the dropdown
https://drive.google.com/file/d/1vqTsYWycvBicL6Rx3Smhi9UJei7zrV6e/view?usp=sharing

### Your Environment

* Version used:
* Browser Name and version:
* Operating System and version:

**Comment by phiz71** [comment]
Linked to https://github.com/gravitee-io/gravitee-ui-components/pull/322
