### ISSUE TITLE
[management] redirect to  internal/external provider depending on the account/username

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#5388]
Use case : SSO requirements for e-commerce website.

The target would be to have : 
- 1 internal provider for the user/mdp stored locally
- N external providers for clients who wish to delegate authentication to their IDP

Currently on the AM login form, this results in a login/mdp form for the first point and N buttons for the 2nd point.
This means that all the clients of the site would see all the providers, and should click on the button corresponding to their provider.

Compared to what is done with other providers (MS/Google), the authentication is done in 2 steps:

1. Enter the username which is an email address in a 1st form, then depending on the domain, either:
2. It is an internal MS/Google account and you enter the password in a 2nd form
2 It is an external account and MS/Google redirects user to the external provider

**Comment by famaridon** [comment]
:+1:

**Comment by patelami** [comment]
Env: Nightly

Given I have a domain
And I have an application
And I created a provider
When I initiate login
And the username dose not match the domain
Then I am redirected to the password page

Given I have a domain
And I have an application
And I created a provider
When I initiate login
And the username matches the domain
Then I am redirected to the identity providers

Given I have a domain
And I have an application
And I created a provider
When I initiate login
And the username matches the domain
Then I am redirected to the identity providers

Given I have a domain
And I have an application
And I created a provider
When I initiate login
And the username matches the domain
Then I am redirected to the identity providers
And I enter correct username and password
Then I am redirected to the application/domain
