### ISSUE TITLE
[cockpit] Connector must send the node version as part of the HelloCommand

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#5392]
https://github.com/gravitee-io/gravitee-cockpit/issues/534

**Comment by jhaeyaert** [comment]
This has been handled by the cockpit connector (see https://github.com/gravitee-io/gravitee-cockpit-connectors/pull/17).
You should use gravitee-cockpit-connector-ws plugin v1.3.0

**Comment by patelami** [comment]
@jgiovaresco : Please can you provide more detail on what information should I see in logs? 

also, from where can I download get gravitee-cockpit-connectors-ws-1.3.0 ? I could not find this in https://dist.gravitee.io/

**Comment by brasseld** [comment]
@Jean-Baptiste-Lasselle from where can we get bundle for the different plugins?

**Comment by patelami** [comment]
normally we get it from here: https://dist.gravitee.io/master/

but gravitee-cockpit-connectors-ws-1.3.0 is not available there.

**Comment by Jean-Baptiste-Lasselle** [comment]
@brasseld @patelami :
* there are 2 places where we can find Gravitee bundles (zipped) : 
  * https://dist.gravitee.io
  * https://download.gravitee.io
* as of today, all bundles prensent in either of those 2, are there if and only if they were released either with `Gravitee AM`, or with `Gravitee APIM`
* and I think that `gravitee-cockpit-connectors` has not yet , ever been released with `Gravitee APIM`, see https://github.com/gravitee-io/release/search?q=gravitee-cockpit-connectors : it has only been released "alone"  
* and for any `Gravitee AM` release, the resulting, published bundles did not bundle `gravitee-cockpit-connectors` "alone" : last week I automated gravtiee AM bundle , and I can state for sure that `Gravitee AM` release builds no zip "just for `gravitee-cockpit-connectors`"

In our case, I fixed a few issues about artifactory with @jhaeyaert last week, and @jhaeyaert will confirm : 
* `gravitee-cockpit-connectors` 1.3.0 has been released "alone" ( @patelami  `gravitee-cockpit-connectors-ws` is released by `gravitee-cockpit-connectors` ) : so no way you can find its bundles on https://download.gravitee.io or https://dist.gravitee.io
* never the less, in the mean time @patelami , you will be able to download your zip from https://repo1.maven.org/maven2/io/gravitee/cockpit/gravitee-cockpit-connectors-ws/1.3.0/  (the public nexus aka "maven central")

**Comment by Jean-Baptiste-Lasselle** [comment]
ps confirmed : lorie released `gravitee-cockpit-connectors` "alone"

**Comment by patelami** [comment]
@brasseld @jhaeyaert:

 Please can you provide more information on what can I see in logs as part of Hello Command? 

currently, I am only seeing the following:
```

08:46:25.911 [vert.x-eventloop-thread-10] INFO  i.g.n.m.h.v.e.ManagementEndpointManagerImpl - Register a new endpoint for Management API: GET /configuration [io.gravitee.node.management.http.configuration.ConfigurationEndpoint]
08:46:25.911 [vert.x-eventloop-thread-10] INFO  i.g.n.m.h.v.v.ManagementVerticle - HTTP listener for Node Management bind to port TCP:18083
08:46:26.282 [vert.x-eventloop-thread-9] INFO  i.g.c.c.ws.WebSocketCockpitConnector - Channel is now connected to Cockpit Controller through websocket from io.gravitee.cockpit.connectors.ws.endpoints.WebSocketEndpoint@735f7fea/ws/controller
08:46:26.445 [vert.x-eventloop-thread-11] INFO  i.g.c.c.ws.WebSocketCockpitConnector - Discovery mode is enabled, listening for cockpit instances...
08:46:26.586 [vert.x-eventloop-thread-9] INFO  i.g.c.c.ws.channel.ClientChannel - HelloCommand replied with status [SUCCEEDED]
08:46:30.013 [cockpit-monitoring-collector-1] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task
```

detailed logs can be found here: https://gist.github.com/9119712534ee02fe28ab8bca134dbf14

**Comment by aelamrani** [comment]
finally the connection will always be accepted (until 3.10.x)

**Comment by aelamrani** [comment]
We should send the version to cockpit on a patch release to detect if an install is compatible or not
