### ISSUE TITLE
[management] Associate sharding tags and tenants to organization

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#5396]
A sharding tag should be linked to a specific organization.

A tenant should be linked to a specific organization.

**Edit 2021-04-16**

- [x] Deprecate `/organizations/:orgId/environments/:envId:/configuration/tags` and `/organizations/:orgId/environments/:envId:/configuration/tenants`
- [x] Create `/organizations/:orgId/configuration/tags` and `/organizations/:orgId/configuration/tenants`
- [x] Create `RolePermission.ORGANIZATION_TAG` and `RolePermission.ORGANIZATION_TENANTS`
- [x] Manage referenceType `ORGANIZATION` and referenceId in services + modify informations in DB
- [x] UI: disable permissions for tags and tenant in scope `ENVIRONMENT`
- [x] UI: Add permissions for tags and tenant in scope `ORGANIZATION`
- [x] UI: Move Sharding tags and Tenants menus from Environment>Settings to Organization>Settings
- [x] Release note: announce depreciation of these permissions for scope `ENVIRONMENT`

**Edit 2021-04-19**

- [x] Run migration scripts locally
- [x] create `organizations/:orgId/groups` to get groups belonging to an organization
- [x]  Deprecate `/organizations/:orgId/environments/:envId:/configuration/entrypoints`
- [x] Create `/organizations/:orgId/configuration/entrypoints`
- [x] UI: disable permissions for entrypoints in scope `ENVIRONMENT`
- [x] UI: Add permissions for entrypoints in scope `ORGANIZATION`

## How to test

- [x] Sharding tags and Tenants menu entries are still present but indicates that the page has been moved
![image](https://user-images.githubusercontent.com/47851994/116099634-71dfa500-a6ac-11eb-8d4e-ca9831500794.png)

- [x] Sharding tags and Tenants menu entries are present in Organization Settings
![image](https://user-images.githubusercontent.com/47851994/115401491-c08fc980-a1ea-11eb-9388-6ee2db9d6b6d.png)

- [x] Sharding tags, Tenants and Entrypoint permissions are readonly for scope ENVIRONMENT, with a tooltip indicating there are deprecated
![image](https://user-images.githubusercontent.com/47851994/115401611-e1581f00-a1ea-11eb-89ef-17ef82a763cd.png)

- [x] Sharding Tags, Tenants and Entrypoint permissions are editable for scope ORGANIZATION
![image](https://user-images.githubusercontent.com/47851994/115401553-cf767c00-a1ea-11eb-9af0-cfa6d2a1f8df.png)

- [x] You are able to create, edit and delete Sharding tags, entrypoints and tenants

**Comment by patelami** [comment]
@ytvnr : 
Re. 

- [ ] Sharding tags, Tenants and Entrypoint permissions are read-only for scope ENVIRONMENT, with a tooltip indicating there are deprecated. 

The tooltip would appear in the area marked in the red box and if we hoover on the actual checkbox, the tooltip is disappeared. 
It is not a great user experience. ideally, we should show the tooltip when the user hovers on the checkbox. Can we address this change as part of this story or shall I create a new issue with the enhancement label? 
<img width="1212" alt="Screenshot 2021-05-06 at 13 54 04" src="https://user-images.githubusercontent.com/14215437/117304060-40699500-ae75-11eb-96d0-35a91415039f.png">
