### ISSUE TITLE
[policy] [api-key] Propagate api-key value to backend service

### ISSUE THREAD

**Issue by wahmedswl** [gravitee-io/issues#540]
Applying Api Key policy with ```Propagate API Key to upstream API``` only works with ```X-Gravitee-Api-Key``` and doesn't work with ```api-key``` query parameter
### Expected Behavior

```
{
  "headers": {
    "Host": "api.gravitee.io",
    "User-Agent": "PostmanRuntime/3.0.11-hotfix.2",
    "Accept": "*/*",
    "Accept-Encoding": "gzip, deflate",
    "Cache-Control": "no-cache",
    "Postman-Token": "415ac899-e2fc-40a0-a8fd-4caffd1296c9",
    "X-Forwarded-For": "221.120.235.86",
    "X-Forwarded-Host": "api.gravitee.io",
    "X-Forwarded-Proto": "https",
    "X-Forwarded-Server": "105b278a9e17",
    "X-Gravitee-Transaction-Id": "e15a795a-016c-4714-9a79-5a016cd71481",
    "X-Traefik-Reqid": "245524"
  }
}
```
### Current Behavior

```
{
  "message": "No API Key has been specified in headers (X-Gravitee-Api-Key) or query parameters (api-key).",
  "http_status_code": 401
}
```
### Steps to Reproduce (for bugs)

1. Deploy Api
2. Policies > Api Key > It will work with both ```X-Gravitee-Api-Key``` and ```api-key```
3. Check ```Propagate API Key to upstream API```
4. ```API out of sync, deploy your API```, click deploy and after that 401 will be returned

### Context

```X-Gravitee-Api-Key``` and ```api-key``` both should be supported in Api Key policy and should work as expected.
### Your Environment

* Version used: 1.4.1 (build: 153) revision#8a39080e8f756736fe2a98781b5673df956d9dd0
* Browser Name and version: PostmanRuntime/3.0.11-hotfix.2
* Operating System and version: Windows 10, Dockerized Gravitee

**Comment by brasseld** [comment]
Hi @wahmedswl,

Does it mean that you're looking for a propagated `api-key` query parameter or you want to propagate it using an HTTP header ?

Regards,

**Comment by brasseld** [comment]
One more thing: what do you need to have an apikey policy in Api > Policies ?
The apikey policy is already executed when you're using a plan with an `api-key` security type.

Thanks for your feedback.

**Comment by wahmedswl** [comment]
@brasseld yeah, i want to propagate ```api-key``` query parameter. Yeah, you are right, i shouldn't need that but i only need that for propagation and i am just looking into it so was kinda having Hello World in Gravitee.

Also, is there any documentation about the Policies?

Thanks so much for your quick response, really appreciate that.

**Comment by brasseld** [comment]
Ok, so you want to propagate the query parameter value.
IMHO, you do not have to add an `apikey` policy from the policies screen.

If you want to add the api-key used by your consumer, you can add the policy transform_headers / transform_query_parameters and add a rule as follow:

<img width="1097" alt="capture d ecran 2017-04-18 a 14 51 13" src="https://cloud.githubusercontent.com/assets/133094/25131571/7e95c000-2446-11e7-8511-d0bc46272d95.png">

You can have a look to policies documentation from: https://docs.gravitee.io/apim_policies_overview.html

Also, take a look to documentation about EL expression:
https://docs.gravitee.io/apim_publisherguide_expression_language.html

Hope I'm clear enough.
Feel free to ask if you have any question (or remark).

Regards,

**Comment by wahmedswl** [comment]
@brasseld thanks so much, gonna close this ticket 👍

**Comment by brasseld** [comment]
Perfect @wahmedswl, thanks for your feedback !
