### ISSUE TITLE
[portal] do not display "Create an Application" in Portal if user has insufficient privileges

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#5403]
If a user has insufficient privileges to create an Application, the "Create an Application" action should not be displayed in Portal (Dashboard and Applications Tabs)
If the user try despite all to initiate the creation of an Application, he will be able to do so but will hopefully fail at the last stage with an error to inform him that he has insufficient privileges.

### Steps to Reproduce (for bugs)
1. In the Console, create or change existing Role at the Environment scope with "Create" unchecked for Application parameter
2. When logged in Portal, this user can still initiate the creation of an Application in Dashboard and Applications Tabs

* Version used: 3.5.x

**Comment by NicolasGeraud** [comment]
Despite the description, the fix is only done  in the App list and not in the Dashboard.
