### ISSUE TITLE
[management] A Membership for member : USER and ref : GROUP already exists.

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#5413]
If a social/OIDC user is already a member of group and if the OIDC group mapping set the same group for this authenticated user, I've got the following error when the user sign in : 

```
{
"errors":[
{
"status":"400",
"message":"A Membership for member : USER xxx and ref : GROUP xxx already exists.",
"code":"errors.api.exists",
"parameters":{
"referenceType":"GROUP",
"memberType":"USER",
"referenceId":"xxx",
"memberId":"xxxx"
}
}
]
}
```

**Comment by apoddany** [comment]
Reopening as issue still reproducible in 3.5.10.

**Comment by MehrCurry** [comment]
I am facing this error with APIM 3.8.1.

**Comment by vmargerin** [comment]
Like MehrCurry, I've a similar issue on ref: ORGANIZATION with 3.8.1 version.

`A Membership for member : USER <user id> and ref : ORGANIZATION DEFAULT already exists`
