### ISSUE TITLE
[management] Manage an empty state when no API

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#5418]
Instead of an empty list when there is no API, we should have an empty state screen, like on applications list screen.
![image.png](https://images.zenhubusercontent.com/601c1f2212e54321cef611f9/188735e8-e3d6-443a-b8fa-8aa6609624db)![image.png](https://images.zenhubusercontent.com/601c1f2212e54321cef611f9/1111e3bd-ef5c-45dc-8e3c-ada8d34162ea)

**Comment by gaetanmaisse** [comment]
Closing as it will be fixed during Angular migration of this screen
