### ISSUE TITLE
[console] Support webhook on API update event

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#5426]
### Global behavior

As a user, I want to be notified on API Update event. 

### Implementation plan

1. We should add new events to subscribe for APIs.
This events would be "API Updated" and "API Deployed" and would be emitted each time an API is updated or deployed. (**TBD**)

![Capture d’écran 2021-04-14 à 15 47 46](https://user-images.githubusercontent.com/13161768/114721066-dad42e00-9d38-11eb-9567-4be3f392093b.png)

2. If the notifier is a webhook one, then the payload should be consistent with other events notification.
(**TBD**: only for this new event or for all API events)

### Testing scenario

- Create an API 
- Add an alert on API Update event
- Mail alert should be sent
- Webhook call should same API info than others events.

You can use https://webhook.site/ to have a fake webhook

A real life example would be to integrate with a CI tool for example.

**Comment by aelamrani** [comment]
👍🏼 but not sure it has to be added on the Lifecycle part

**Comment by RubenMMSantos** [comment]
Ticket tested using provided website (https://webhook.site/) to check new events
New events triggered across APIM with specific actions
Covered notifications templates by overriding default templates with custom ones (for email comms only)
Events triggered successfully and in accordance with performed action
Events successfully registered in "Audit" with correct information
