### ISSUE TITLE
[management] remove tags and tenants permissions scoped to ENVIRONMENT

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#5440]
In 3.9 version of APIM, `TAGS` and `TENANTS` permissions have been moved to `ORGANIZATION` scope.

We have to delete the code related to those permissions for `ENVIRONMENT` scope.

- [ ] Delete `TagsResource`, `TenantsResource` and `EntrypointsResource` entries from `EnvironmentConfigurationResource`
- [ ] Modify `TagsResource`, `TenantsResource` and `EntrypointsResource` to only accept `RolePermission.ORGANIZATION_TAG, `RolePermission.ORGANIZATION_TENANT` and `RolePermission.ORGANIZATION_ENTRYPOINT`
- [ ] Delete `RolePermission.ENVIRONMENT_TAG` and `RolePermission.ORGANIZATION_TAG` (and same for TENANTS and ENTRYPOINTS)
- [ ] UI: Delete permissions line for `TAGS`, `TENANTS` and `ENTRYPOINTS` in Organization Settings > Roles > scope: ENVIRONMENT
- [ ] UI: Delete temporary redirecting screens from environment settings for sharding tags and tenants

Implied by https://github.com/gravitee-io/issues/issues/5396

**Comment by ppgravitee** [comment]
@mouligno can you review this?
