### ISSUE TITLE
[portal] Filter on users

### ISSUE THREAD

**Issue by geraudmasson** [gravitee-io/issues#545]
Hello,

I use the version 1.3.3 and I would like to know if it was possible to filter on users and know on wich apis was this user with his rights.
It could be more easy to change his rights or remove him than to go on every single apis and check on it.

**Comment by brasseld** [comment]
Best way to manage rights is to use Groups.

**Comment by NicolasGeraud** [comment]
is it ok for you ?

**Comment by geraudmasson** [comment]
yes, thanks
