### ISSUE TITLE
[Portal] documentation not available

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#546]
I migrate to 1.5.0
apis have existing  swagger documentation:
![image](https://cloud.githubusercontent.com/assets/22543323/25229118/54325582-25cf-11e7-969d-575cf502126f.png)

but, in user mode, or consult mode, documentation is unavailable:
![image](https://cloud.githubusercontent.com/assets/22543323/25229144/770f0d02-25cf-11e7-8a20-8b8b4683d8d7.png)

### Your Environment

* Version used: 1.5.0

**Comment by NicolasGeraud** [comment]
hi @vdelattre the mongodb script to update your database is missing.

I have pushed it :
https://github.com/gravitee-io/release/blob/master/upgrades/1.5.0/mongodb/2-update-pages.js

**Comment by vdelattre** [comment]
OK after executing migration script

**Comment by brasseld** [comment]
FYI, we have a migration guide:
https://docs.gravitee.io/apim_installguide_migration.html#upgrade_to_1_5_0

I'm closing this ticket
