### ISSUE TITLE
[management] Default Schema is now set to "public" for jdbc

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#5468]
In 3.7.1, DEFAULT_SCHEMA is now named "public". see 
https://github.com/gravitee-io/gravitee-repository-jdbc/blob/aa7d77a1366d667fff29d78931a155f018cc5084/src/main/java/io/gravitee/repository/jdbc/common/AbstractJdbcRepositoryConfiguration.java#L74
This breaking change needs to be specified in the Changelog.

**Comment by aelamrani** [comment]
Maybe better to not set a default value on our side to avoid a BC on a patch release
