### ISSUE TITLE
[Portal] private apis not visible for members

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#547]
private api are invisible for members:
![image](https://cloud.githubusercontent.com/assets/22543323/25229283/f1065052-25cf-11e7-8aa0-2aae0e4e02b9.png)

![image](https://cloud.githubusercontent.com/assets/22543323/25229301/fd4f3b1c-25cf-11e7-8f54-144a408d3322.png)

### Your Environment

* Version used: 1.4.1, 1.5.0

**Comment by NicolasGeraud** [comment]
your ldap is different : XFR / xfr

Our login is case sensitive.

I close this ticket  ( -> #548 )
