### ISSUE TITLE
gRPC flow is broken if logging mode is "Proxy logging" or "Client & Proxy" 

### ISSUE THREAD

**Issue by YoranSys** [gravitee-io/issues#5476]
# Current Behavior

On a working API, if we enable logging mode: "Proxy logging" or "Client & Proxy"

The client fails to receive a response with an error like :

<pre>grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:

  status = StatusCode.UNKNOWN

  details = "Stream removed"

  debug_error_string = "

 {"created":"@1619126545.998580211","description":"Error received from peer ipv4:172.25.0.2:8082","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Stream removed","grpc_status":2} 

</pre>

On the Gravitee logging screen we see all the flow and a 200 response code

You can find the client and server used here: [https://grpc.io/docs/languages/python/quickstart/](https://grpc.io/docs/languages/python/quickstart/)

# Your Environment

*   Version used: 3.6.3

**Comment by grignix** [comment]
Bug still exists, checked in versions 3.5.30 & 3.15.4

**Comment by grignix** [comment]
up

**Comment by grignix** [comment]
up
