### ISSUE TITLE
[console] Custom templates for alert notifications (HTTP Status Code and Average Response Time)

### ISSUE THREAD

**Issue by ibahloul** [gravitee-io/issues#5481]
# User Story
As an administrator, I want to customize the content of the emails sent regarding error and response time alerts, so that the emails are as appropriate in content (all the information needed by API consumers) and form (specific language, branding, ...) as possible

# Further Information
- A new section "Template for alerts" added with 2 lines: HTTP Status Code and Average Response Time
- Parameters available to enrich the content of an email (see https://docs.gravitee.io/ae/apim_notification_request.html)

# Tests
## Configuration
- [x] Given the Alert Feature is disabled when I browse the templates section, then the "Templates for alerts" section is not displayed - **PASS**
- [x] Given the Alert Feature is enabled, when I browse the templates section, then the "Templates for alerts" section is ~~not~~  displayed - **PASS**
- [ ] Given the Alert Feature is enabled and the Alert Engine Plugin is not installed and connected as a user with Notification Templates permission, when I browse the template's detail, then the template creation form is not available and the following message is displayed: "No alert plugin is installed. Please install a plugin before being able to define alert rules." - **PASS**

- [x] Given the Alert Feature is enabled and the Alert Engine Plugin is installed, when I browse the template's detail, then the template creation form is available  - **PASS**

## Form Validation
- [ ] Given the alert template creation/update form, when I don't fill all the fields, then the button "Save" is disabled and an error message is displayed below the concerned fields - **Not Tested: unable to test this locally as Template for Alert is not visible on the local dev version** 

## Template customization
- [x] Given the alert template creation/update form, when the "Override default template" switch is off, then the field "Title" and the field "Content" are in a read-only mode  -  **PASS**
- [x] Given the alert template creation/update form, when the "Override default template" switch is on, then I can modify "Title" ad "Content" values and save my changes  -  **PASS**

## Notifications
 **Not Tested: unable to test this locally as Template for Alert is not visible on the local dev version** 
- [x] Given a defined alert, when I customize the template and create a new alert, then the template is used for both alerts
- [x] Given a defined alert, when I select the default template and create a new alert, then the default template is used for both alerts
- [ ] Given 2 different organizations with 1 custom template each, when alerts are sent by email, then each alert uses the associated template with its organization **Not Tested: unable to test this locally as it requires integration with cockpit** 

-----------------------------------------------------------------------------------------------------------------------------

We should describe on the contextual documentation of the console how to use the alert parameters (see https://docs.gravitee.io/ae/apim_notification_request.html)
We should update the documentation of the configuration of notifications to add a part about Alerts notifications (API Management > Configuration Guide > Configure Notifications).

The email subject should be: "Alert reached for the application XXX". Where XXX is the name of the application.

The email body should be as the following example:

```
Date

5xx over 10% during 5 minutes.
```

The template of the body must be changed on the console > Organization Settings > Templates. A new section **TEMPLATES FOR ALERTS** will be added with a template for these 2 alerts:

- HTTP status code
- Average response time

**Comment by patelami** [comment]
This is not yet deployed on nightly and this can only be tested once https://github.com/gravitee-io/issues/issues/5341#issue-849030021 is finished.

**Comment by patelami** [comment]
Moving this ticket back in progress while trying to figure out, the env setup to test this.

**Comment by patelami** [comment]
@ibahloul : the following case is not working: 

Given the Alert Feature is enabled 
And the Alert Engine Plugin is not installed 
And connected as Application User
 Ahen I browse the template's detail
 Then the template creation form is not available and the following message is displayed: "No alert plugin is installed. Please install a plugin before being able to define alert rules."
