### ISSUE TITLE
[management] Plan id not preserved on API import

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#5489]
### Expected Behavior
Preserve Plan Id on export/import of API

### Current Behavior
New id is created for the Plan on API import

### Steps to Reproduce (for bugs)
1. Create an API with a Plan and check the associated id for this Plan
2. Export the API and associated Plan
3. Re-Import the API in same environment or Import in new environment
4. Check the id of the Plan, it is not the same as at creation
5. This will result in error as "Plan [XXXX] can not be found" while calling the API and 502 errors
6. The API Analytics will also show "Deleted Plan" for each call.

### Your Environment

* Version used: 3.5.10 and above
* Browser Name and version: N/A
* Operating System and version: N/A

**Comment by YoranSys** [comment]
Hi,
@phiz71and @gcusnieux  we seem to have the same issue for pages, ids is not preserved.
