### ISSUE TITLE
[portal] User with `owner` role is not able to create a new documentation page

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#549]
When logged with owner user, 
![image](https://cloud.githubusercontent.com/assets/22543323/25231665/f3d5b0a8-25d8-11e7-8e1c-852bc6c30fc6.png)

i can't add documentation pages
![image](https://cloud.githubusercontent.com/assets/22543323/25231714/24e1afc6-25d9-11e7-9187-a79268ac5c99.png)

but it's possible with admin user (i transfered ownership from admin to XFR)

### Your Environment
* Version used: 1.5.0

**Comment by brasseld** [comment]
Ok it seems to be an old issue since it was already the case for all previous gravitee.io versions...
