### ISSUE TITLE
Update Docker images to AdoptOpenJDK 11.0.11

### ISSUE THREAD

**Issue by larsnaesbye** [gravitee-io/issues#5491]
Gateway and Management REST API Docker images can get updated to 11.0.11

PRs:

https://github.com/gravitee-io/gravitee-gateway/pull/663
https://github.com/gravitee-io/gravitee-management-rest-api/pull/1460
https://github.com/gravitee-io/graviteeio-access-management/pull/1173
https://github.com/gravitee-io/gravitee-docker/pull/55

**Comment by larsnaesbye** [comment]
@phiz71 Do you think these could be reviewed? It usually isn't a big deal to have the images updated to new versions.

**Comment by aelamrani** [comment]
@larsnaesbye can we update AM images as well as part of this issue? https://github.com/gravitee-io/graviteeio-access-management/tree/master/docker

And other images used for our nightly / demo / EE versions? https://github.com/gravitee-io/gravitee-docker

**Comment by larsnaesbye** [comment]
Sure. I'll make pull requests for them too later today. 

It's just that I don't use the AM so technically I don't test them.

**Comment by aelamrani** [comment]
Thanks. No worries we will test it before merging.

**Comment by larsnaesbye** [comment]
@aelamrani it should be done now :)

**Comment by aelamrani** [comment]
Thanks @larsnaesbye
