### ISSUE TITLE
[gateway][apim] gRPC in Server streaming mode the call is never close

### ISSUE THREAD

**Issue by YoranSys** [gravitee-io/issues#5494]
### Expected Behavior
gRPC have four modes, we need to validate each of them with client or server termination.

The RPC termination can come from client or server https://grpc.io/docs/what-is-grpc/core-concepts/#rpc-termination : 

```
RPC termination

In gRPC, both the client and server make independent and local determinations of the success of the call, and their conclusions may not match. This means that, for example, you could have an RPC that finishes successfully on the server side (“I have sent all my responses!") but fails on the client side (“The responses arrived after my deadline!"). It’s also possible for a server to decide to complete before a client has sent all its requests.
```

### Current Behavior
With APIM gateway and gRPC in Server streaming mode, the call is never close when close from server. 

From the wireshark point of view, the last HEADERS packet with the header grpc-status = 0  (grpc-status ok code) is missing.

- https://grpc.github.io/grpc/core/md_doc_statuscodes.html

With Gravitee :
![with gravitee](https://user-images.githubusercontent.com/11197007/116110157-b9b6fa00-a6b5-11eb-8461-0faf8955800f.png)

Whitout Gravitee : 
![without gravitee](https://user-images.githubusercontent.com/11197007/116110168-bcb1ea80-a6b5-11eb-888e-7e0a20920a5d.png)

### Possible Solution

Add more test on gateway to check all types of call and close from client and server

### Steps to Reproduce (for bugs)

You can check with example  from grpc.io helloworld.

There is also three excellents tools for grpc 
- curl like but for grpc : https://github.com/fullstorydev/grpcurl 
- postman like : https://github.com/uw-labs/bloomrpc
- Karate test for grpc: https://github.com/pecker-io/karate-grpc

### Your Environment
* Browser Name and version: 3.6.X

**Comment by brasseld** [comment]
Should be tested with APIM 3.10
