### ISSUE TITLE
[management] Lifecycle - allows to deprecate an API

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#55]
_From @brasseld on May 4, 2016 13:44_

As an API publisher, I would like to set an API (_for which I'm one of the owner or primary owner_) as deprecated.

Marking an API as deprecated involve that:
- Consumer are not able to generate or re-generate API Keys
- Current API keys will be automatically set with an expiration date (define by the API publisher)
- Send an email to all consumer to inform them about the state of the API.

_Copied from original issue: gravitee-io/release#37_

**Comment by NicolasGeraud** [comment]
We should call it _archived_

 - API must also be undeployed. 
 - No one except the admin can access to the API. 
 - Admin could _Unarchived_ the API

**Comment by aelamrani** [comment]
We should allow to deprecate an API. 
This action will deprecate all the linked plans and a notification will be sent to all consumers.
The API will be unpublished and the publish action will be forbidden.
