### ISSUE TITLE
[portal] Display a customizable endpoint for APIs

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#550]
In ui, when i suscribed to an api, a new screen show me my apikey and url i have to use with curl command

but port(8082) is missing in url

### Your Environment
* Version used: 1.5.0

**Comment by brasseld** [comment]
Yes, because we have no clue about your installation meaning that perhaps you're exposing your API on a domain like https://api.mycompany.com

**Comment by NicolasGeraud** [comment]
@vdelattre do you think it could be useful to add an extra config entry (in the config.json) to set the default domain of your api gateway ?

**Comment by vdelattre** [comment]
yes i can be useful.
and also port to call api

thanks

**Comment by NicolasGeraud** [comment]
The idea is to add a new parameter in the config.json of the UI.
Something like `"gateway-endpoint": "https://api.mycompany.com"`
This new parameter will be concatenate to the context-path of an api in the API headear of the portal and in the message displayed after a subscription.
