### ISSUE TITLE
[management] disabling Newsletter does not disable bottom right Pop-in 

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#5502]
Disabling Newsletter in rest api gravitee.yml does not disable bottom right Pop-in but only the first central Pop-in at first connection.

### Steps to Reproduce (for bugs)
1. Edit the rest api gravitee.yml and disable Newsletter as : 
```
newsletter:                  
  enabled: false
```
2. Connect to Console as new user : Central Newsletter Pop-in has been correctly removed
3. Try to reconnect later on (7 days ?) : The bottom right Pop-in remains present
<img width="536" alt="Capture d’écran 2021-04-28 à 13 16 49" src="https://user-images.githubusercontent.com/79909781/116395191-1a644500-a824-11eb-9d48-92ec472d40d1.png">

### Your Environment

* Version used: 3.5.10
* Browser Name and version: N/A
* Operating System and version: N/A

**Comment by leleueri** [comment]
Addition of the configuration key to define the absolute path to the PNG file: 

*configuration.default-icon

If present, the targeted PNG image will be returned if the API doesn't have image.
If missing, an API without image will receive a random icon
