### ISSUE TITLE
[management api] default_api_logo.png can not be overriden 

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#5524]
### Current Behavior
In 1.30.x, it is possible to override the default_api_logo.png  in management api.
The new overriden logo will be correctly displayed in management ui.
This is no more possible in 3.5.x.

### Steps to Reproduce (for bugs)

1. Set a custom default_api_logo.png by overwriting the existing one in the /assets folder
2. Check in Console, the default logo is not overriden (generated picture instead)

### Your Environment

* Version used: 3.5.10
* Browser Name and version:
* Operating System and version:

**Comment by leleueri** [comment]
Addition of the configuration key to define the absolute path to the PNG file:

configuration.default-icon

If present, the targeted PNG image will be returned if the API doesn't have image.
If missing, an API without image will receive a random icon

**Comment by apoddany** [comment]
Reopening as the custom default api logo now works for newly created APIs but it still does not override for existing/formerly created APIs (random logo still in use).
