### ISSUE TITLE
Accepting/Rejecting an API promotion request

### ISSUE THREAD

**Issue by ibahloul** [gravitee-io/issues#5528]
# User Story
As a API publisher, I want to accept or reject API promotion requests, so that I can keep control of the APIs in my environment

# Further Information
- Both actions require confirmation
- Once the promotion request has been accepted, a message is displayed to indicate if the operation was successful or if there were any errors
- Uniqueness checking must be done on the context path of an API
- The user who has requested for an API promotion is **not notified** of its acceptance or rejection

# Tests
## Accepting
- [x] Given an API promotion request task, when I click on the "ACCEPT" button and cancel the action, then the API is not created/updated on the environment, the promotion status = `TO_BE_VALIDATED`, and the task remains in the list
- [x] Given an API promotion request task, when I click on the "ACCEPT" button and confirm the action, then the API is created/updated on the environment, the following message "API has been created/updated successfully." is displayed, the promotion status = `ACCEPTED`, and the task is removed from the list
- [ ] ~~Given an API promotion request task and ???, when I click on the "ACCEPT" button and confirm the action, then the API is not created/updated on the environment, the following message "" is displayed, the promotion status = `TO_BE_VALIDATED`, and the task remains in the list~~

## Rejecting
- [x] Given an API promotion request task, when I click on the "REJECT" button and cancel the action, then the promotion status = `TO_BE_VALIDATED`, and the task remains in the list
- [x] Given an API promotion request task, when I click on the "REJECT" button and confirm the action, then the API is not created/updated on the environment, the promotion status = `REJECTED`, and the task is removed from the list

### No Virtual Host
- [x] Given the context path is already defined for an other API of the target environment, when I click on the "ACCEPT" button and confirm the action, then the following error message is displayed "Another API is already using this context path." and the task remains in the list

### Virtual Host
- [x] Given both context path and virtual host are already defined for an other API of the target environment, when I click on the "ACCEPT" button and confirm the action, then the following error message is displayed "Another API is already using this context path." and the task remains in the list
- [x] Given the context path is already defined for an other API of the target environment but the virtual host is not the same, when I click on the "ACCEPT" button and confirm the action, then then the following message is displayed "API has been created/updated successfully." and the task is removed from the list

## API review
- [x] Given the API review enabled on the target environment, when the API is promoted, then the API status (on the target environment) is `DRAFT`

## API deprecated
- [x] Given the promotion of a deprecated API on the target environment, when I accept the promotion, then the following error message is displayed: "Updating a deprecated API is not allowed."

**Comment by patelami** [comment]
How can I test the promotion `status = TO_BE_VALIDATED `?
