### ISSUE TITLE
[management] Can't import new page

### ISSUE THREAD

**Issue by YoranSys** [gravitee-io/issues#5540]
### Expected Behavior

Import API and included pages 

###  Current Behavior

First import is working, next import a new version with a new page fail with `{"http_status":404,"message":"Page [729cb496-7a4a-4d7b-9cb4-967a4a3d7bb5] can not be found."}`

### Steps to Reproduce (for bugs)

 * Create an API 
 * Export the API 
 * Import in new environment
 * Update the API : add a page
 * Export
 * Import on the new environment 
 * This will result in error as "Page [XXXX] can not be found" while calling the API and PUT 404 errors

### Your Environment

* Version used: 3.5.12 and above

**Comment by YoranSys** [comment]
Hi @mouligno, 
What type of information do you need?

**Comment by mouligno** [comment]
Do you still have the issue ? I couldn't reproduce.

**Comment by YoranSys** [comment]
Hi @mouligno,
on 3.5.23 the issue it's still there :(

**Comment by marijatimovska** [comment]
Issue is replicated on my side.
 
1. Import an API and Export the same API on 3.5.22.
2. Import the same API on 3.5.23
3. Created a page in 3.5.22 and Export the API.
4. Imported the same API from 3.5.22 to 3.5.23.
