### ISSUE TITLE
[management] Unable to display scopes since pagination

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#5549]
Find scope now return a page of scopes.

The following pages need to handle this new data structure : 

- "domains > ${domainName} > applications >${AppName} > settings > oauth2" 
- "domains > ${domainName} > settings > roles > new 
- "domains > ${domainName} > settings > roles > ${roleId} 
- "domains > ${domainName} > settings > Client Registration > Default scopes
- "domains > ${domainName} > settings > Client Registration > Allowed scopes

Beware to request all the scopes by performing multiple find until the page contains less value than the page size.

**Comment by tcompiegne** [comment]
Same thing for the role's permissions which are based on scopes.

**Comment by tcompiegne** [comment]
> Beware to request all the scopes by performing multiple find until the page contains less value than the page size.

Maybe we can rely on the mat-autocomplete component combine with the search feature to reduce the list
