### ISSUE TITLE
[Console] Error when adding a user to a group not yet created

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#5555]
As Admin, when I want to add a user to a group not yet created there are an exception in the UI:

![image.png](https://images.zenhubusercontent.com/6026363e864bfc6af2b3aa2c/143af609-6420-47f8-b4a9-3d92225c2160)

# Step to reproduce:

* go to create group page
* open the dev console of the browser
* fill the group name
* click on add member, there are an exception 

# Environment:

* version : 3.8.1

**Comment by aelamrani** [comment]
Duplicate of https://github.com/gravitee-io/issues/issues/5402 ?

**Comment by mouligno** [comment]
Since it's duplicate, we'll follow up on #5402
