### ISSUE TITLE
[management] Cannot ask for review anymore

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#5558]
When I ask for a review on an API, I get a 500 error.
In API logs, there is this stacktrace
```
18:50:41.987 [gravitee-listener-2213] ERROR i.g.r.a.m.r.provider.ThrowableMapper - Internal error
java.lang.NullPointerException: null
	at io.gravitee.rest.api.service.impl.ApiServiceImpl.findAllReviewersEmail(ApiServiceImpl.java:3047)
	at io.gravitee.rest.api.service.impl.ApiServiceImpl.updateWorkflowReview(ApiServiceImpl.java:2993)

```

**Comment by gaetanmaisse** [comment]
Issue can be reproduced after having created an API with an import definition file.

**Comment by patelami** [comment]
env: nightly

As a user, When the changes is been requested, the owner should be able to ask for the reviews **PASS**
