### ISSUE TITLE
[portal] user can't create api

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#556]
when logged with user role, i can't create new api. '+' button now available
OK with admin user

![image](https://cloud.githubusercontent.com/assets/22543323/25335975/a109a4d6-28f5-11e7-92e3-b3eeed916b24.png)

![image](https://cloud.githubusercontent.com/assets/22543323/25335957/8e897d86-28f5-11e7-809a-e93b689000b6.png)

### Your Environment
* Version used: 1.5.0

**Comment by NicolasGeraud** [comment]
Hi @vdelattre 

a consumer can't create an api. A publisher can.

**Comment by NicolasGeraud** [comment]
ok for you ?

**Comment by vdelattre** [comment]
Yes, it's ok
is there several way to give publisher right? or only by configuring ldap? is admin can give this right?

**Comment by NicolasGeraud** [comment]
Currently, you have to configure the user in your ldap

**Comment by NicolasGeraud** [comment]
I close this issue, reopen it if it's not ok for you.
