### ISSUE TITLE
[management] check existance of confirmUrl

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#5567]
Since gravitee-io/issues#5450, a null confirmationUrl may lead to a NullPointerException 
https://github.com/gravitee-io/gravitee-management-rest-api/blob/3.5.x/gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/sanitizer/UrlSanitizerUtils.java#L35 

We should test the parameter before going further and return with 400 status

## How to reproduce 

Run the POSTMAN test : gio_portal_business_errors

**Comment by patelami** [comment]
Env: nightly

1. As a user, I should be able to register to the APIM using web UI FAIL
- Currently, when I am trying to register a new user, I do not receive the activation email. 
<img width="1335" alt="Screenshot 2021-05-18 at 10 15 03" src="https://user-images.githubusercontent.com/14215437/118625518-ff9d4480-b7c1-11eb-850f-20624c92648d.png">

2. Run the POSTMAN test : gio_portal_business_errors **PASS**
<img width="1438" alt="Screenshot 2021-05-18 at 10 11 58" src="https://user-images.githubusercontent.com/14215437/118624970-83a2fc80-b7c1-11eb-8afa-1d231bbdf162.png">

**Comment by patelami** [comment]
We are unable to test the user registration on nightly because SMTP is not configured on nightly.
