### ISSUE TITLE
HC cannot be inherited anymore

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#5572]
<img width="1920" alt="Capture d’écran 2021-05-14 à 11 30 58" src="https://user-images.githubusercontent.com/1580262/118251466-e9cd0e00-b4a7-11eb-81f0-0d7175f3a003.png">

**Comment by patelami** [comment]
env: nightly

As a user, I should be able to inherit configuration endpoint to the group and vice versa  **PASS**
