### ISSUE TITLE
[management][am] Helm install fails to login

### ISSUE THREAD

**Issue by gustavovalverde** [gravitee-io/issues#5573]
### Expected Behavior
Login to the AM should make the callback to the actual host defined on the YAML

### Current Behavior
The callback is being done to 
`https://<HELM_HOST>:80/management/auth/authorize?redirect_uri=http://localhost:4200/login/callback`

### Steps to Reproduce (for bugs)
1. Install AM with helm
2. Login for the first time

### Your Environment

* Version used: 3.7.1
* Browser Name and version: Chrome

**Comment by gustavovalverde** [comment]
This is because `constants.json` is not being completely overwritten with Helm

```json
  "portalTitle": "Access Management",
  "baseURL": "http://localhost:8092/management",
  "authentication": {
    "oauth2": {
      "authorize": "http://localhost:8092/admin/oauth/authorize",
      "userInfo": "http://localhost:8092/admin/userinfo",
      "clientId": "admin",
      "redirectUri": "http://localhost:4200/oauth/callback",
      "logoutUri": "http://localhost:8092/admin/logout?target_url=http://localhost:4200/logout/callback"
    }
  }
}
```

From the whole file, just baseURL is changed.

**Comment by tcompiegne** [comment]
Hi @gustavovalverde ,

It is the expected behavior.

AM `constants.json` file only contain the `baseURL` : https://github.com/gravitee-io/graviteeio-access-management/blob/master/gravitee-am-ui/constants.json

I close this one, we are looking for the other one : #5574

**Comment by gustavovalverde** [comment]
@tcompiegne is this issue also related?
![image](https://user-images.githubusercontent.com/16890942/119047724-48a0f480-b98c-11eb-8a9d-0e03f92a2cbd.png)

**Comment by gustavovalverde** [comment]
@tcompiegne do you know where to find documentation regarding the last screenshot sent here? Is this `:80` port also modified with the `constants.json` ?

**Comment by gustavovalverde** [comment]
@tcompiegne I still can't find information on how to modify the `constants.json` when deploying with **Helm**

**Comment by tcompiegne** [comment]
Hi @gustavovalverde , for AM or APIM ?
