### ISSUE TITLE
[management][am] Helm install rewrites management URL wrongly

### ISSUE THREAD

**Issue by gustavovalverde** [gravitee-io/issues#5574]
### Expected Behavior
First login shouldn't throw a 404

### Current Behavior
The console shows it's trying to log to `https://<HOST>/management/management/organizations/DEFAULT/environments`
management is duplicated in the URL

If I try to remove one of the duplicated `management` it throws the error: `An error occurs while trying to find roles by ids`

### Steps to Reproduce (for bugs)
1. Install with Helm
2. Login with admin

### Your Environment

* Version used: 3.8.1
* Browser Name and version: Chrome
* Operating System and version: Helm

**Comment by gustavovalverde** [comment]
This might have been introduced in this commit https://github.com/gravitee-io/helm-charts/commit/5980baefc5fdc5564bf7d23afeba9c80ef08370f

**Comment by gustavovalverde** [comment]
This is because `constants.json` is not being completely overwritten

```json
  "portalTitle": "Access Management",
  "baseURL": "http://localhost:8092/management",
  "authentication": {
    "oauth2": {
      "authorize": "http://localhost:8092/admin/oauth/authorize",
      "userInfo": "http://localhost:8092/admin/userinfo",
      "clientId": "admin",
      "redirectUri": "http://localhost:4200/oauth/callback",
      "logoutUri": "http://localhost:8092/admin/logout?target_url=http://localhost:4200/logout/callback"
    }
  }
}
```

From the whole file, just baseURL is changed.

**Comment by gustavovalverde** [comment]
This issue was introduced here: https://github.com/gravitee-io/helm-charts/commit/5980baefc5fdc5564bf7d23afeba9c80ef08370f

**Comment by tcompiegne** [comment]
Hi @gustavovalverde ,

Indeed the default `values.yaml` is wrong. 

You can quickly fix that by modifying the ingress path section of the api. 

We will fix that in the next helm chart version.
