### ISSUE TITLE
Write documentation with AsyncAPI

### ISSUE THREAD

**Issue by ibahloul** [gravitee-io/issues#5575]
# User Story
As an API publisher, I want to write specification with AsyncAPI, so that I can describe and document asynchronous APIs (e.g., AMQP, MQTT, WebSockets, Kafka, STOMP, HTTP, etc)

# Further Information
- The toolbar is disabled (or removed ?)
- The "WYSIWYG" mode is disabled (or removed ?)
- Example content: https://playground.asyncapi.io/

# Tests
#### Documentation Pages Creation
- [ ] Given a page defined with the [external source: Swagger Petstore](https://petstore.swagger.io/v2/swagger.json), when I browse the page creation form (platform level), then no preview is displayed
- [ ] Given a page defined with the [external source: AsyncAPI example](https://raw.githubusercontent.com/asyncapi/asyncapi/master/examples/2.0.0/simple.yml), when I browse the page creation form (platform level), then the preview is displayed

#### Translations
- [ ] Given the page defined with the [external source: Swagger Petstore](https://petstore.swagger.io/v2/swagger.json), when I add a translation (without inheriting the content), then no preview is displayed
- [ ] Given the page defined with the [external source: AsyncAPI example](https://raw.githubusercontent.com/asyncapi/asyncapi/master/examples/2.0.0/simple.yml),  when I add a translation (without inheriting the content, then the preview is displayed

#### Page creation
- [ ] Given a page defined with the [external source: Swagger Petstore](https://petstore.swagger.io/v2/swagger.json), when I browse the page creation form (API level), then no preview is displayed
- [ ] Given a page defined with the [external source: AsyncAPI example](https://raw.githubusercontent.com/asyncapi/asyncapi/master/examples/2.0.0/simple.yml), when I browse the page creation form (API level), then the preview is displayed

#### Translations
- [ ] Given the page defined with the [external source: Swagger Petstore](https://petstore.swagger.io/v2/swagger.json), when I add a translation (without inheriting the content), then no preview is displayed
- [ ] Given the page defined with the [external source: AsyncAPI example](https://raw.githubusercontent.com/asyncapi/asyncapi/master/examples/2.0.0/simple.yml),  when I add a translation (without inheriting the content, then the preview is displayed

#### Homepage
- [x] Given the homepage defined with the [external source: Swagger Petstore](https://petstore.swagger.io/v2/swagger.json), when I browse the following URL https://v3.nightly.gravitee.io/, then no rendering is displayed
- [x] Given the homepage defined with the [external source: AsyncAPI example](https://raw.githubusercontent.com/asyncapi/asyncapi/master/examples/2.0.0/simple.yml), when I browse the following URL https://v3.nightly.gravitee.io/, then the rendering is displayed and corresponds to the preview

#### Documentation Pages
- [x] Given the page defined with the [external source: Swagger Petstore](https://petstore.swagger.io/v2/swagger.json), when I browse the following URL https://v3.nightly.gravitee.io/documentation/root, then no rendering is displayed
- [x] Given the page defined with the [external source: AsyncAPI example](https://raw.githubusercontent.com/asyncapi/asyncapi/master/examples/2.0.0/simple.yml), when I browse the following URL https://v3.nightly.gravitee.io/documentation/root, then the rendering is displayed and corresponds to the preview

##### Homepage
- [x] Given an english version of the homepage defined with the [external source: Swagger Petstore](https://petstore.swagger.io/v2/swagger.json), when I browse the following URL https://v3.nightly.gravitee.io/ in english, then no rendering is displayed
- [x] Given and english version of the homepage defined with the [external source: AsyncAPI example](https://raw.githubusercontent.com/asyncapi/asyncapi/master/examples/2.0.0/simple.yml), when I browse the following URL https://v3.nightly.gravitee.io/ in english, then the rendering is displayed and corresponds to the preview

##### Documentation Pages
- [x] Given an english version of the page defined with the [external source: Swagger Petstore](https://petstore.swagger.io/v2/swagger.json), when I browse the following URL https://v3.nightly.gravitee.io/documentation/root in english, then no rendering is displayed
- [x] Given an english version of the page defined with the [external source: AsyncAPI example](https://raw.githubusercontent.com/asyncapi/asyncapi/master/examples/2.0.0/simple.yml), when I browse the following URL https://v3.nightly.gravitee.io/documentation/root in english, then the rendering is displayed and corresponds to the preview

#### Homepage
- [ ] Given the homepage defined with the [external source: Swagger Petstore](https://petstore.swagger.io/v2/swagger.json), when I browse the "Informations générales" section, then the no rendering is displayed
- [ ] Given the homepage defined with the [external source: AsyncAPI example](https://raw.githubusercontent.com/asyncapi/asyncapi/master/examples/2.0.0/simple.yml), when I browse the "Informations générales" section, then the rendering is displayed and corresponds to the preview

#### Documentation Pages
- [ ] Given the page defined with the [external source: Swagger Petstore](https://petstore.swagger.io/v2/swagger.json), when I browse the "Documentation" section, the no redering is displayed
- [ ] Given the page defined with the [external source: AsyncAPI example](https://raw.githubusercontent.com/asyncapi/asyncapi/master/examples/2.0.0/simple.yml), when I browse the "Documentation" section, then the rendering is displayed and corresponds to the preview

##### Homepage
- [ ] Given an english version of the homepage defined with the [external source: Swagger Petstore](https://petstore.swagger.io/v2/swagger.json), when I browse the "Informations générales" section in english, then no rendering is displayed
- [ ] Given an english version of the homepage defined with the [external source: AsyncAPI example](https://raw.githubusercontent.com/asyncapi/asyncapi/master/examples/2.0.0/simple.yml), when I browse the "Informations générales" section in english, then the rendering is displayed and corresponds to the preview

##### Documentation Pages
- [ ] Given an english version of the page defined with the [external source: Swagger Petstore](https://petstore.swagger.io/v2/swagger.json), when I browse the "Documentation" section in english, then then no rendering is displayed
- [ ] Given an english version of the page defined with the [external source: AsyncAPI example](https://raw.githubusercontent.com/asyncapi/asyncapi/master/examples/2.0.0/simple.yml), when I browse the "Documentation" section in english, then the rendering is displayed and corresponds to the preview

**Comment by ibahloul** [comment]
Related to this US : https://github.com/gravitee-io/issues/issues/2234

**Comment by gaetanmaisse** [comment]
https://github.com/asyncapi/asyncapi-react/tree/next#using-in-other-technologies

**Comment by patelami** [comment]
We can improve the description about `Documentation`, @tiffanymarchi Please can you review the section available [here](https://nightly.gravitee.io/#!/environments/DEFAULT/settings/pages?parent=
)? 

[screencapture-nightly-gravitee-io-2021-08-10-11_16_36.pdf](https://github.com/gravitee-io/issues/files/6960814/screencapture-nightly-gravitee-io-2021-08-10-11_16_36.pdf)


cc: @marcambier @gaetanmaisse

**Comment by patelami** [comment]
Env: Nightly
Result: PASS

**Comment by tiffanymarchi** [comment]
@patelami I've made a few changes, but need to get together with Marc to ask a couple of questions to clarify things further (I'll make additional edits to clarify after I speak with him). Thanks!
