### ISSUE TITLE
[management] gravitee_http_cors_alloworigin environment variable setting not reflected in UI

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#5583]
While setting Environment variable for CORS (Allow-Origin), it is not reflected in UI.

### Steps to Reproduce (for bugs)
1. Set gravitee_http_cors_alloworigin to a value other than default (*) in the management api starting script as
`export gravitee_http_cors_alloworigin=http://toto.com
`
2. Restart the management api
3. Check the Console settings : Settings -> Settings -> CORS
4. The Allow-Origin parameter remains to the default (*)
<img width="824" alt="Capture d’écran 2021-05-17 à 14 53 41" src="https://user-images.githubusercontent.com/79909781/118491945-cad8b100-b71f-11eb-8aca-f87b5ed86ad9.png">

### Your Environment

* Version used: 3.5.x
* Browser Name and version:
* Operating System and version:

**Comment by phiz71** [comment]
Since 3.5.0 and #4642, cors configuration has been splitted in two parts. One for the console and one for the portal. So to override these values with env var, the keys are:
- console : gravitee_console_http_cors_allow-origin
- portal : gravitee_portal_http_cors_allow-origin
