### ISSUE TITLE
[management-api] Allows to search and filter APIs

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#561]
(already talked with david)

In continuous delivery, i create or update api definition in gravitee with rest api.
i use api /management/apis/verify to check if context-path is available
but when i have to update existing api, i can't get id with one query, i have to parse all result from get /management/apis

it should be great to have query param to restrict data set (example: by context-path, by name)

it should be useful for all your api to have query param to search
examples: 
- pages by type
- group by name
- views by name
etc...

### Your Environment
* Version used: 1.5.0

**Comment by aelamrani** [comment]
The query params available on /apis route:
- view
- group
- top
- context-path
- label
- state
- visibility
- version
- name
- tag
