### ISSUE TITLE
[management] [gateway] activate flow condition

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#5610]
Description: 
Have the ability to create a flow at the domain or application level that is triggered under certain conditions and not systematically.

Use case: 
Flow activated according to the type of provider that initiates the login.

The current workaround would be to use ternary operators in the fields of the current flows (which is not a sustainable solution)

Expected target date:  Beginning of September.

**Comment by leleueri** [comment]
This issue implement the flow condition. If the condition evaluation is missing or returns "true", the flow is executed. The creation of additional flows is related to #5646
