### ISSUE TITLE
Class io.gravitee.rest.api.standalone.ManagementContainer doesn't exist in gravitee-management-rest-api

### ISSUE THREAD

**Issue by alirezakhtm** [gravitee-io/issues#5624]
when I want to start application from source code and I use this command (according to ReadMe.adoc)
` mvn clean compile exec:java -Pdev -pl gravitee-rest-api-standalone/gravitee-rest-api-standalone-container`
I receive this Exception:
`An exception occured while executing the Java class. io.gravitee.rest.api.standalone.ManagementContainer`
in this package there is a runner class that named `GraviteeApisContainer` but in POM main class set as follow:
`<mainClass>io.gravitee.rest.api.standalone.ManagementContainer</mainClass>`
I change this class with `GraviteeApisContainer` (according to gravitee-gateway) but it doesn't work!
I think, the class `ManagementContainer` is not committed on this git repository.

**Comment by brasseld** [comment]
Hi @alirezakhtm 

Indeed, the container class is not the good one.

Can you replace with https://github.com/gravitee-io/gravitee-management-rest-api/blob/master/gravitee-rest-api-standalone/gravitee-rest-api-standalone-container/src/main/java/io/gravitee/rest/api/standalone/GraviteeApisContainer.java 

And maybe provide a PR ?

**Comment by alirezakhtm** [comment]
Hi @brasseld 

Thank you so much,
I'm working on it now, and I will make a PR as soon as possible and mention PR number under this issue.

**Comment by alirezakhtm** [comment]
Dear @brasseld,

I sent a PR to solve this issue [https://github.com/gravitee-io/gravitee-management-rest-api/pull/1507](https://github.com/gravitee-io/gravitee-management-rest-api/pull/1507)

**Comment by brasseld** [comment]
Yes, thanks for the PR.

I just merged into master.

**Comment by alirezakhtm** [comment]
Thanks so much.
