### ISSUE TITLE
[console] User Information - Label display problem

### ISSUE THREAD

**Issue by ibahloul** [gravitee-io/issues#5625]
### Steps to Reproduce
1. In the console, go to "My account"
2. Fill and save the form

### Expected Behavior
The labels are correctly positioned above the fields concerned

### Current Behavior
The labels are badly positioned:

![User Informations Labels](https://user-images.githubusercontent.com/82866977/119339741-d84ae980-bc91-11eb-8445-f6726ad9376c.PNG)

**Comment by apoddany** [comment]
Still in 3.1.3.3 and 3.14

**Comment by LiliaEn** [comment]
Tested on the 3.10.x environment version 3.10.11
Browser: Chrome Version 95.0.4638.69, macOS Big Sur v11.6
Works as expected
![Screenshot 2022-01-31 at 11 34 43](https://user-images.githubusercontent.com/49516050/151786980-c89ad48e-290c-4b4b-9230-7c8dfc38bfdc.png)
