### ISSUE TITLE
An exception occured while executing the Java class. null

### ISSUE THREAD

**Issue by alirezakhtm** [gravitee-io/issues#5635]
Hi @brasseld,

I found other exception when I run source of gravitee-management-api  as follow:

`[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:java (default-cli) on project gravitee-rest-api-standalone-container: An exception occured while executing the Java class. null: InvocationTargetException: Error creating bean with name 'properties' defined in io.gravitee.rest.api.portal.rest.spring.RestPortalConfiguration: Unsatisfied dependency expressed through method 'properties' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException ...`

that is occurred because `gravitee.yml` doesn't exist.

**Comment by alirezakhtm** [comment]
Dear @brasseld ,

I send a PR to solve this problem. Could you please merge this? Thanks in advance.

[https://github.com/gravitee-io/gravitee-management-rest-api/pull/1509](https://github.com/gravitee-io/gravitee-management-rest-api/pull/1509)

**Comment by brasseld** [comment]
Thanks for this one @alirezakhtm 

Appreciate it!

**Comment by alirezakhtm** [comment]
Thank you so much.

**Comment by alirezakhtm** [comment]
Thank you so much.
