### ISSUE TITLE
Encrypt API properties

### ISSUE THREAD

**Issue by ibahloul** [gravitee-io/issues#5638]
# User Story
As an API publisher, I want to encrypt some of my API properties so that I can comply with my company's security rules

# Further information
- Once encrypted, the value of the property is hidden from the user
- The property is also encrypted when stored in the database
- Expert mode does not support encrypted properties

# Tests
### Adding new properties
- [x] Given a defined property with the encryption mode enabled, when I click on the `SAVE` button, then the property value is encrypted (read-only), it is hidden (e.g, "******"), and stored in the database
- [x] Given a defined property, when I disable the encryption mode, then the value is reset
- [x] Given a defined property with the encryption mode disabled, when I click on the "Save" button, then the property value is not encrypted, it is not hidden, and stored in the database

### Existing properties
- [x] Given an encrypted property, when I disable the encryption mode, then the value is reset
- [x] Given an encrypted property with the encryption mode disabled, when I set a new value and I click on the "Save" button, then the property is stored in the database with the new value but not longer encrypted

### Expert mode
- [x] Given a encrypted property, when I switch to "expert" mode, then this property is not displayed
- [x] Given a encrypted property, when I switch to "simple" mode, then this property is displayed
- [x] Given a list of properties, when I edit properties and I switch back to the "normal" mode, then the list of properties has been updated

## API Logs
- [x] Given an API with encrypted properties, when I look at the logs (audit table) of this API, then the values of these properties do not appear in clear.

**Comment by patelami** [comment]
env: nightly
Result: PASS

Given I have added an encrypted property to the mock policy 
And I save the policy 
Then I should see the property-key NOT encrypted in request header
And I should see it encrypted in response body

Example: value of google-cloud-key is visible in request header but encrypted in response body 

<img width="349" alt="Screenshot 2021-08-31 at 16 37 42" src="https://user-images.githubusercontent.com/14215437/131533023-5646bb64-b943-433c-bbe9-8e04e32b2985.png">
<img width="807" alt="Screenshot 2021-08-31 at 16 38 00" src="https://user-images.githubusercontent.com/14215437/131533028-712ea3f5-bb82-4592-b545-4f4e649bbcde.png">
