### ISSUE TITLE
[v3.8.1] Environment Settings - Deleting the last property of a dictionary is not working

### ISSUE THREAD

**Issue by ibahloul** [gravitee-io/issues#5643]
### Steps to Reproduce
1. Go to the environment settings
2. Go to Dictionaries section
3. Add a manual dictionary
4. Add a new property
5. Save properties
5. Select the new property
6. Delete the new property
7. Save properties

### Expected Behavior
The property has been deleted and the list of properties is empty

### Current Behavior
The property has not been deleted and the property remains in the list of properties

**Comment by grignix** [comment]
The problem of not being able to delete Properties in the dictionary is still not fixed, tested in versions 3.15.8 & 3.17.3

**Comment by mouligno** [comment]
Closing as it would be fixed in next versions. Duplicate of https://github.com/gravitee-io/issues/issues/6996
