### ISSUE TITLE
[management] [gateway] create new flow

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#5646]
With the introduction of condition flow (#5610), we must be able to create new flows in AM. 

- Gateway, REST-API and data storage should be OK
- UI part must be rework

**Comment by leleueri** [comment]
Depends on  gravitee-io/gravitee-ui-components#349
Depends on  gravitee-io/gravitee-ui-components#350

Now it is possible to add & remove a flow. 
The flow type is editabled only during flow creation, during an update this field is disabled
