### ISSUE TITLE
[portal] API / application management submenu is not shown 

### ISSUE THREAD

**Issue by geraudmasson** [gravitee-io/issues#565]
I have made the migration of gravitee 1.2.0 to 1.5.0 and after a restart, I had some problems to see the management pannel (I mean the pannel with Policies, Ressources ...) on some api's. Indeed, I must have all rights on the api's manager and I had those rights on 1.2.0 but since the migration I do not have them anymore on each apis. There are 2 apis "detected" on wich I can't see the pannel. How can I fix this?

Thanks

**Comment by NicolasGeraud** [comment]
hi @geraudmasson can you export the api definition with members for this 2 apis and share them ?

what was your role and membership on version 1.2.0 ?

**Comment by geraudmasson** [comment]
Hi,
How can I export to you those informations ? 
I can share to you our dump mongo... but privatly
I am an admin by the repository user ldap

**Comment by NicolasGeraud** [comment]
you can go to our gitter channel https://gitter.im/gravitee-io/gravitee-io and send me privately your mongodump if it's not to much heavy

**Comment by geraudmasson** [comment]
Hi @NicolasGeraud 
I have sent the dumps to you.

**Comment by aelamrani** [comment]
Hi @geraudmasson,

It has been fixed and merged, so it will be available on next release 1.5.1

Thx,
Azize
