### ISSUE TITLE
[gateway] liquibase should be disabled by default in the gateway configuration

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#5650]
It appears that liquibase is run at startup for both management and gateway. We should disable liquibase by default on the gateway and let the administrator decide whether it should be enabled or not.

Same as for AM https://github.com/gravitee-io/issues/issues/4997

Should also inform the users in the upgrade guide.

**Comment by phiz71** [comment]
Nothing to be tested here. It's just configuration and documentation.
