### ISSUE TITLE
The dropdown will appear in towards the end of the screen

### ISSUE THREAD

**Issue by patelami** [gravitee-io/issues#5653]
All the dropdowns on the alert page in the portal would open towards the lower end. 

![Screenshot 2021-05-28 at 11.59.29.png](https://images.zenhubusercontent.com/6037d57eba9d3cc0b0412549/e86cd9d6-4347-45df-922f-6f1cf51e80c6)

**Comment by gaetanmaisse** [comment]
Closing as it has been fixed.
