### ISSUE TITLE
[portal] Dynamic properties - missing output expected example

### ISSUE THREAD

**Issue by lusoalex** [gravitee-io/issues#566]
### Expected Behavior
When going to the Dynamic Properties, in order to add one, i clicked on the "Information" part to see the expected output value.

![capture d ecran 2017-04-27 a 14 53 48](https://cloud.githubusercontent.com/assets/16895682/25484977/69b1a81c-2b5c-11e7-8622-e3a95d3fbdae.png)

Before release 1.5.0 i used to have this : 
![capture d ecran 2017-04-27 a 14 57 35](https://cloud.githubusercontent.com/assets/16895682/25484990/763d14e0-2b5c-11e7-80db-8927dae8088a.png)

### Current Behavior
But now, nothing appear : 
![capture d ecran 2017-04-27 a 14 58 32](https://cloud.githubusercontent.com/assets/16895682/25485003/7ea3d1c8-2b5c-11e7-8082-c03e582be89f.png)

### Your Environment
* Version used: 1.5.0
* Browser Name and version: Chrome 57
* Operating System and version: Mac / Sierra

**Comment by NicolasGeraud** [comment]
hi @lusoalex , there's a bug with codemirror, you have to click inside the textarea to display the content
