### ISSUE TITLE
[portal] Scopes (Available Authorizations) can't be displayed in API Documentation (swagger)

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#5661]
In Portal, Scopes (Available Authorizations) can't be displayed in API Documentation (swagger).
They are correctly displayed on the Console

### Steps to Reproduce (for bugs)

1. In Console, import an API from swagger as : https://petstore.swagger.io/v2/swagger.json
2. Check the API swagger Page Documentation 
3. Try to open the Scope pop-up by clicking on the padlock of an API flow : 
<img width="594" alt="Capture d’écran 2021-06-01 à 18 47 12" src="https://user-images.githubusercontent.com/79909781/120361275-f35ccf80-c309-11eb-8fcf-c818e1dcbae6.png">
4. The Available Authorizations pop-up will be displayed : 
<img width="647" alt="Capture d’écran 2021-06-01 à 18 48 52" src="https://user-images.githubusercontent.com/79909781/120361452-21daaa80-c30a-11eb-9301-bfc114f04e43.png">

5. Publish the API and access its Documentation in Portal
6. Try to open the Scope pop-up by clicking on the padlock of an API flow

<img width="1303" alt="Capture d’écran 2021-06-01 à 18 52 17" src="https://user-images.githubusercontent.com/79909781/120361858-a9c0b480-c30a-11eb-9703-7696de828a81.png">
7. No pop-up raised for Available Authorizations scopes as in Portal.

### Your Environment

* Version used: 3.5.6 / 3.5.12
* Browser Name and version:
* Operating System and version:

**Comment by leleueri** [comment]
This behavior has been introduced by #5100

**Comment by phiz71** [comment]
By enabling the try-it mode, the `Authorize` button is displayed and the popup with scopes can be viewed.
