### ISSUE TITLE
[management] API_REVIEW_* Audit Event filters are missing in the scrolling list (API and Global Levels)

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#5673]
When trying to filter Audit Events at the API Level or at the Global Level for API_REVIEW_* Events, these Events are missing in the Events scrolling list.

![mceclip0](https://user-images.githubusercontent.com/79909781/120504560-89553080-c3c4-11eb-9da3-ec4ae8e08501.png)

### Your Environment

* Version used: 3.5.12 / 3.8

**Comment by phiz71** [comment]
Don't forget the PR on https://github.com/gravitee-io/release to change the version of gravitee-repository
