### ISSUE TITLE
Refresh token endpoint logged in another account

### ISSUE THREAD

**Issue by NitnekB** [gravitee-io/issues#5687]
Currently working for an APIZR customer as a developer, I discovered an annoying bug regardless Access Manager refresh token endpoint. 

Using Gravitee Access Manager 2.8.2.
Also using grant types `REFRESH TOKEN`, `PASSWORD` and `CLIENT_CREDENTIALS`.

There's a custom Identity Provider behind that connect to customers Oracle database.

When I remove and create a new Identity Provider from AM interface, the bug disappears. But it comes back randomly with time.

It seems Gravitee generate a custom field `preferred_username` into user JWT and this one is used over the standard `email` field whenever we call `/CLIENT/oauth/token` endpoint.

Here's a JWT example:

```json
{
  "sub": "SUB_ID",
  "aud": "AM_CLIENT",
  "iss": "OIDC_PATH",
  "customerId": CUSTOMER_ID,
  "email": "qbuirette@apizr.fr",
  "preferred_username": "nitnekb@gmail.com",
  ...
}
```

I already tried to override this field without any success.
I also took a look behind the custom Identity Provider, but can't find anything related to this `preferred_username` field.

### Expected Behavior

Login with a customer must not generate `preferred_username` field into JWT.

### Current Behavior

As seen above, a random behaviour generate an unwanted field into customer JWT

### Possible Solution

I'll take a way to override this field if that's a simple fix

### Steps to Reproduce (for bugs)

I'm afraid I can't provide you any way to reproduce.

### Context

We cannot use refresh token endpoint as it is a major security issue for our customer.

### Your Environment

* Version used: AM 2.8.2
* Operating System and version: Runing on

**Comment by brasseld** [comment]
Hi @NitnekB 

We are not supporting AM 2.8.x anymore.

Could you have a try using one of the latest 3.9.x ?

**Comment by NitnekB** [comment]
It was a plugin issue, we can close this now
