### ISSUE TITLE
[management] flows property not accepted in request payload for Update Plan 

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#5694]
When trying to update a Plan trough the APIs (Design Mode), the "flows"property is not recognized as a valid property.
This property is retrieved from the GET but not accepted from the PUT.
When trying to update the Plan through the 'paths' attribute (as in "Path Based" mode), the "flows" property is not updated and the UI continues to display old values.
This impacts the ability to automate the creation/update of APIs/Plans.

### Steps to Reproduce (for bugs)

1. In the Console, create an API with a Plan that has Flows defined in it.
2. In Postman, GET the Plan from the Management API.
3. Change some properties of the Plan and try to update (PUT) the Plan from Postman
4. You will receive an error as
```
{
  "message" : "Property [flows] is not recognized as a valid property",
  "http_status" : 400
}
```

### Your Environment

* Version used: 3.5.8 / 3.5.12
* Browser Name and version: N/A
* Operating System and version: N/A

**Comment by leleueri** [comment]
This issue isn't a bug IMHO, we need to discuss to know if the flow related to a plan can be updated using this method. Currently the way to update a flow, what ever is its scope, is through the update API.

**Comment by leleueri** [comment]
As discussed with APIM team, the UpdatePlan should accept flows and update them.
Flows is now required when the API is using the ApiDefinition in V2 (PolicyStudio)
