### ISSUE TITLE
[gateway] [auto-discovery] Endpoints auto-discovery

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#57]
Actually, the API publisher must set the list of endpoints available for an API when configuring the gateway behavior. The major issue with this way to work is that when an endpoint is added / updated or deleted, it involves an "out-of-service" delay while re-deploying the API configuration.

One of the solution is to provide a way to discover endpoints automatically by invoking an "endpoint provider".
We must provide an "endpoints auto-discovery service" which takes the lead on the way to register / unregister endpoints by invoking the "endpoint provider". By doing so, API publisher just have to configure the auto-discovery service instead of declaring static endpoints.

An endpoint provider can be one of these solutions: Netflix Eureka, Consul.io, Etcd, ....

**Comment by blackfich** [comment]
Hi,

is there a roadmap for this feature. My company is willing to take gravitee.io as its API Gateway, but we need to have service discovery. I know this can be archived by using a policy based on the DynamicRoutingPolicy, but we would prefer to have it out-of-the-box.

Regards,

Marc Fichant / almerys

**Comment by brasseld** [comment]
Hi @blackfich,

FYI, I've edited your comment to remove the name of your company.

About this feature, I'm agree with you and it would be part of the product out-of-the-box without the need to twist policy usage. Can you tell us which `provider` you want to use for discovery ?

**Comment by blackfich** [comment]
Hi @brasseld,

Thx, for your quick answer. We need to use Eureka as it is the one we have selected for information system.

**Comment by anujgandharv** [comment]
@brasseld just wanted to get some update on this issue. Is it still a high priority And will be implemented?

**Comment by NicolasGeraud** [comment]
see #843
