### ISSUE TITLE
[management] wrong Units for Request/Response Content length in Analytics Dashboards

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#5706]
When adding, in Analytics Dashboard, a widget for "Request Content length" and/or "Response Content length", the displayed values will show results in ms instead of bytes.

### Steps to Reproduce (for bugs)
1. Create an API with Plan and Application to subscribe to it
2. Generate some activity on it
3. Create a Dashboard for this Application
4. Add 2 "stats" widgets for "Request Content length" and/or "Response Content length".
5. Check the Dashboard results : ms are displayed instead of bytes

<img width="1427" alt="Capture d’écran 2021-06-10 à 10 08 15" src="https://user-images.githubusercontent.com/79909781/121488940-d8f2b800-c9d3-11eb-855a-225c1c43b9e7.png">

### Your Environment

* Version used: 3.5.10 3.5.12
* Browser Name and version: N/A
* Operating System and version: N/A

**Comment by gaetanmaisse** [comment]
Notes for testers: Widgets need to be deleted and readded to a dashboard to fix the unit issues.

**Comment by mouligno** [comment]
LGTM
