### ISSUE TITLE
[portal] When login is required on portal, an error is displayed

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#5727]
![Capture d’écran 2021-06-16 à 09 57 06](https://user-images.githubusercontent.com/1580262/122181260-7e50d480-ce89-11eb-81f2-f130c8c0835d.png)

**Comment by mouligno** [comment]
Backport of #6203

**Comment by mouligno** [comment]
Still got the issue when i try to reach : [Portal_root_url] but not on [Portal_root_url]/user/login?redirectUrl=%2F

**Comment by mouligno** [comment]
LGTM
