### ISSUE TITLE
[management] search API should keep the search score order

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#5744]
When we search API in the "view APIs" pages, found APIs are not sorted by the search score provided by lucene. Order was preserved in previous version (3.4.x and earlier)

### Expected Behavior
Apis should be displayed based on the lucene score (higher scope on top)

### Current Behavior
Apis are sorted by name

### Possible Solution

Adapt the sorting methods introduced by 
* gravitee-io/issues#5150 : line 80 of the AbstractDocumentSearcher (this sort will put the Highest score at the end)
* gravitee-io/issues#5045 : sortAndPaginate of ApiServiceImpl

### Steps to Reproduce (for bugs)
See dataset provided by support team.

**Comment by gaetanmaisse** [comment]
@marcambier and I didn't find any simple business case that could highlight the fixed order, to test this issue we started the Rest API in debug mode and checked the order of APIs returned to the frontend was exactly the same one as returned to the ElasticSearch query. Without additional context + repro values the QA won't be able to validate anything, so I'm moving this issue to Ready to release myself.
