### ISSUE TITLE
[repository] [redis] events are not well managed

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#576]
### Events are not correctly deleted
As we can see here : https://github.com/gravitee-io/gravitee-repository-redis/blob/master/src/main/java/io/gravitee/repository/redis/management/internal/impl/EventRedisRepositoryImpl.java#L153

We don't delete redis set for update date and properties. 
This not causing bugs, bug thisleave orphan datas.

### Events are not correctly updated
When we update an event we don't remove old entry for properties that have been updated or removed. This could cause bugs for the heartbeat.

**Comment by aelamrani** [comment]
Same problem for Memberships and Metadata i guess
