### ISSUE TITLE
[portal] long paths/names are not well displayed in Analytics and Logs widgets

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#5767]
With requests with a long path or API with long names, the widget are not well displayed

<img width="535" alt="Capture d’écran 2021-06-21 à 23 48 38" src="https://user-images.githubusercontent.com/1028285/122832160-3ef01100-d2eb-11eb-96c5-357de74f3925.png">
<img width="1362" alt="Capture d’écran 2021-06-21 à 23 50 50" src="https://user-images.githubusercontent.com/1028285/122832506-b9209580-d2eb-11eb-9742-1a2812abd20f.png">

Widgets to fix:
 - [ ] top path
 - [ ] top mapped path
 - [ ] logs
 - [ ] top apis
 - [ ] top failed apis

### Your Environment

* Version used: 3.5.x

**Comment by phiz71** [comment]
After the fix:
![image](https://user-images.githubusercontent.com/13161768/133471617-17bddacf-c0d3-4eb7-8fef-1b06aef25559.png)
