### ISSUE TITLE
Frozen duplicate collapsible in application custom claims

### ISSUE THREAD

**Issue by JesusTheHun** [gravitee-io/issues#5775]
### Steps to Reproduce (for bugs)

Using GIO AM, select you application, visit `Settings >> OAuth 2.0 / OIDC`. In the section `Custom claims`, add a custom claim for `ACCESS_TOKEN`. Save and reload the page. Now add a new custom claim for `ACCESS_TOKEN`.

### Expected Behavior

The new custom claim should appear in the same collapsible span.

### Current Behavior

The new custom claim appears in a new collapsible span, which is collapsed and cannot be open.

### Your Environment

* Version used: GIO AM 3.9.0
* Browser Name and version: Safari 14.1.1
* Operating System and version: MacOS Big Sur 11.4

**Comment by tcompiegne** [comment]
Hey @JesusTheHun , it's fixed in the 3.9.1.

https://github.com/gravitee-io/issues/issues/5750
