### ISSUE TITLE
[management] Cannot save a plan with enabled restrictions

### ISSUE THREAD

**Issue by dwarce** [gravitee-io/issues#5776]
When creating a new plan, after setting the restrictions, such as Rate Limiting, Quota and Resource Filtering, the SAVE button is no longer working. It only works when all the boxes are not ticked.

### Expected Behavior
Clicking the "SAVE" button should create plan with current settings.

### Current Behavior
When clicking the "SAVE" button, nothing happens in UI, but in developers console, an error shows:
TypeError: Cannot read property 'title' of undefined.

### Possible Solution
The error in developers console is most likely a javascript (angular) error, 

### Steps to Reproduce (for bugs)
1. Start creating a plan
2. Fill the first two steps of the procedure (Define, Secure)
3. In the "Restrictions" step, select one of restrictions (e.g. Quota)
4. Click "SAVE" button

### Your Environment
* Version used: 3.9.0, installed with zip on centOS 8
* Browser Name and version: Chrome 91.0.4472.106 (Official Build) (64-bit)
* Operating System and version: Windows 10

**Comment by mvahanen** [comment]
I have this same problem. Any news about it?

**Comment by dwarce** [comment]
Seems to be working on version 3.9.2, just tried it
