### ISSUE TITLE
[v3.5.X] Pressing tab in a field that supports ELs does not allow moving between fields

### ISSUE THREAD

**Issue by ibahloul** [gravitee-io/issues#5779]
### Steps to Reproduce
1. Select an API
2. Go to the Design Studio
3. Design a new flow
4. Add the Dynamic Routing Policy
5. Add a new rule in the configuration of the policy
6. Press tab in the "Match expression" field

### Expected Behavior
Pressing tab allows me to move to the next field ("Redirect to")

### Current Behavior
Pressing tab does not allow me to move to the next field, and worse, the tab is interpreted in the EL (and it is not visible)!

**Comment by gaetanmaisse** [comment]
Closing as it has been fixed 🚀
