### ISSUE TITLE
add documentation about the new ilm config

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#5784]
### Expected Behavior
There's a new configuration introduced by this PR https://github.com/gravitee-io/issues/issues/5551
We have to add documentation.

**Comment by RachidKelidou** [comment]
As an environment variable or in the gravitee.yml of the management API, it's sufficient to configure the ILM mode by adding this line : 

`gravitee.analytics.elasticsearch.index_mode=ilm
`

It allows to not include date as part of the index name for ILM managed indices.
