### ISSUE TITLE
API promotion testable on Nightly

### ISSUE THREAD

**Issue by ibahloul** [gravitee-io/issues#5786]
We should be able to run 2nd console/rest API/GW:
- docker compose update
- conf traefik to make it accessible on `http://apim-nightly.cloud.gravitee.io/`
- Optional: Create a second bud-domain: `http://apim-nightly-2.cloud.gravitee.io/`

Mongo DB:
- Use mongoatlas 
- Hide credentials in Jenkins env var --> send them to docker compose
 
Cockpit : 
 - Create "Gravitee Nightly" 
 - Create users for APIM dev, PO, QA on cockpit nightly
 - Get certificate -> copied into `/opt/certs` (on Jenkins machine)

**Comment by gaetanmaisse** [comment]
This will be reworked after migrating APIM nightly to Azure cluster and CircleCI deployment.
