### ISSUE TITLE
[v3.9.1] The "Access control" tab of a documentation page does not return the correct list of roles

### ISSUE THREAD

**Issue by ibahloul** [gravitee-io/issues#5789]
### Steps to Reproduce 
1. Select an API
2. Select/Create a documentation page
3. Go to "Access control" tab
4. Enable the "private mode"
5. Display the list of roles

### Expected Behavior
The list of roles contains all the roles in the API scope

### Current Behavior
The list of roles contains all the roles in the ENVIRONMENT scope

**Comment by phiz71** [comment]
LGTM for the management UI part, but I wonder if there is something to do in the portal. I will check

**Comment by phiz71** [comment]
> LGTM for the management UI part, but I wonder if there is something to do in the portal. I will check

It's OK :)

**Comment by patelami** [comment]
env: nightly
result: pass

<img width="1122" alt="Screenshot 2021-07-27 at 23 08 48" src="https://user-images.githubusercontent.com/14215437/127233956-d6c81c7a-1935-45f2-9279-58d801b6b975.png">
