### ISSUE TITLE
[Management] user logout should be traced

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#5799]
As an ORGANIZATION_OWNER or ORGANIZATION_PRMIARY_OWNER user, when a user logout from the console I can't see the auditLog related to this action.

**Comment by leleueri** [comment]
Because the logout is performed by SpringSecurity layer, we don't have access to organization information to create the entry in the right place... close this ticket.

**Comment by tcompiegne** [comment]
Are you sure about it ? 

```
     .logout()
                .logoutRequestMatcher(new AntPathRequestMatcher("/auth/logout"))
                .logoutSuccessHandler(new CustomLogoutSuccessHandler())
                .addLogoutHandler(cookieClearingLogoutHandler())
```

Seems we can do something around here (successHandler)

**Comment by leleueri** [comment]
You are right! We have access to the cookie in this Handler :+1:
