### ISSUE TITLE
[portal] User information card

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#58]
_From @brasseld on May 4, 2016 13:58_

Currently, in the WebUI, we can only see user id.

The idea here is to provide more user information by clicking on their ID.
At least, we must be able to consult firstname / lastname / mail address, gravitee profil (api publisher, consumer, simple suer, admin....)

Also, it would be nice to see information for the logged in user by clicking on his picture / id in the top left menu.

_Copied from original issue: gravitee-io/release#40_

**Comment by brasseld** [comment]
What is the state of this issue ?

**Comment by brasseld** [comment]
@aelamrani what is the state of this feature ?

**Comment by aelamrani** [comment]
It's closed by this commit : https://github.com/gravitee-io/gravitee-management-webui/commit/7cffbd00f8bd05821d22b551b69836509b983f7c

**Comment by brasseld** [comment]
Ok, cool !

Do you think it's possible to show user's information when clicking on the user Id (in the members view for example) ?

**Comment by aelamrani** [comment]
Ah! Just forgot this part, yes i'll do it...

**Comment by brasseld** [comment]
No more relevant with v3
