### ISSUE TITLE
[management] Plan Flows get lost on updating an API with an existing API definition (updateApiWithDefinition)

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#5820]
When using the Management API to update an API with an existing API definition (https://docs.gravitee.io/apim/3.x/management-api/3.5/#operation/updateWithDefinitionPUT),
the Flows defined on a Plan get lost.

### Steps to Reproduce (for bugs)

1. Create a API by importing an API definition by using the attached echo.json as : 
POST http://localhost:8083/management/organizations/DEFAULT/environments/DEFAULT/apis/import
2. Check the content of the Flows in the Console (1 Flow is defined for the Plan)
<img width="449" alt="Capture d’écran 2021-07-05 à 18 49 52" src="https://user-images.githubusercontent.com/79909781/124501436-d2ccdd00-ddc1-11eb-95ff-32cf11fb672c.png">

3. Update the API by using Management API with updateWithDefinitionPUT
PUT http://localhost:8083/management/organizations/DEFAULT/environments/DEFAULT/apis/api-id/import
4. Check the content of the Flows in the Console (the Flow of the Plan is missing)
<img width="432" alt="Capture d’écran 2021-07-05 à 18 54 26" src="https://user-images.githubusercontent.com/79909781/124501765-774f1f00-ddc2-11eb-89dc-bf67b482227c.png">

### Your Environment

* Version used: 3.5.10 3.5.16
* Browser Name and version:
* Operating System and version:

**Comment by apoddany** [comment]
echo.txt -> echo.json

[echo.txt](https://github.com/gravitee-io/issues/files/6765583/echo.txt)

**Comment by leleueri** [comment]
This issue isn't a bug IMHO, we need to discuss to know if the flow related to a plan can be updated using this method. Currently the way to update a flow, what ever is its scope, is through the update API.

**Comment by leleueri** [comment]
also fixe gravitee-io/issues#5694
