### ISSUE TITLE
[v3.5.10/3.5.12] OAuth2 plan parsing must accept tokens other than JWT (example 1)

### ISSUE THREAD

**Issue by ibahloul** [gravitee-io/issues#5828]
## Steps to Reproduce
1. Create an OAuth2 plan with the following selection rule: `#context.attributes['jwt'].claims == null`
2. Create a JWT plan with the following selection rule: `#context.attributes['jwt'].claims['iss'] == 'my-issuer'`
3. Restart the GW => Make a call with an opaque token then a JWT token => Check the API logs to see which plan was tested first

#### OAuth2 plan tested first
👍 Parsing = OK => claims != null => `(#context.attributes['jwt'].claims == null) = FALSE` => Test JWT plan => `(#context.attributes['jwt'].claims['iss'] == 'my-issuer') = TRUE` ? JWT plan is selected : No plan is selected

#### JWT plan tested first
Parsing = ERROR => claims == null => Test OAuth2 plan => `(#context.attributes['jwt'].claims == null) = TRUE` => OAuth2 plan is selected

#### OAuth2 plan tested first
Parsing = OK => claims != null => `(#context.attributes['jwt'].claims == null) = FALSE` => Test JWT plan => `(#context.attributes['jwt'].claims['iss'] == 'my-issuer') = TRUE` ? JWT plan is selected : No plan is selected

#### JWT plan tested first
Parsing = OK => claims != null => `(#context.attributes['jwt'].claims['iss'] == 'my-issuer') = TRUE` ? JWT plan is selected : Test OAuth2 plan => `(#context.attributes['jwt'].claims == null) = FALSE` => No plan is selected

#### OAuth2 plan tested first
👎 Parsing = ERROR => claims == null => Test JWT plan => `(#context.attributes['jwt'].claims['iss'] == 'my-issuer') = FALSE` => No plan is selected

#### JWT plan tested first
Parsing = ERROR => claims == null => Test OAuth2 plan => `(#context.attributes['jwt'].claims == null) = TRUE` => OAuth2 plan is selected

#### OAuth2 plan tested first
Parsing = OK => claims != null => `(#context.attributes['jwt'].claims == null) = FALSE` => Test JWT plan => `(#context.attributes['jwt'].claims['iss'] == 'my-issuer') = TRUE` ? JWT plan is selected : No plan is selected

#### JWT plan tested first
Parsing = OK => claims != null => `(#context.attributes['jwt'].claims['iss'] == 'my-issuer') = TRUE` ? JWT plan is selected : Test OAuth2 plan => `(#context.attributes['jwt'].claims == null) = FALSE` => No plan is selected

**Comment by apoddany** [comment]
To be handled together with 5829
