### ISSUE TITLE
[v3.5.10/3.5.12] OAuth2 plan parsing must accept tokens other than JWT (example 2)

### ISSUE THREAD

**Issue by ibahloul** [gravitee-io/issues#5829]
## Steps to Reproduce
1. Create an OAuth2 plan without selection rule
2. Create a JWT plan with the following selection rule: `#context.attributes['jwt'].claims['iss'] == 'my-issuer'`
3. Restart the GW => Make a call with an opaque token then a JWT token => Check the API logs to see which plan was tested first

#### OAuth2 plan tested first
👍 Parsing = OK => OAuth2 Plan is selected (because there is no selection rule)

#### JWT plan tested first
Parsing = ERROR => claims == null => Test OAuth2 plan => `(#context.attributes['jwt'].claims == null) = TRUE` => OAuth2 plan is selected

#### OAuth2 plan tested first
Parsing = OK => OAuth2 Plan is selected (because there is no selection rule)

#### JWT plan tested first
Parsing = OK => claims != null => `(#context.attributes['jwt'].claims['iss'] == 'my-issuer') = TRUE` ? JWT plan is selected : OAuth2 Plan is selected (because there is no selection rule)

#### OAuth2 plan tested first
👎 Parsing = ERROR => claims == null => Test JWT plan => `(#context.attributes['jwt'].claims['iss'] == 'my-issuer') = FALSE` => No plan is selected

#### JWT plan tested first
Parsing = ERROR => claims == null => Test OAuth2 plan => `(#context.attributes['jwt'].claims == null) = TRUE` => OAuth2 plan is selected

#### OAuth2 plan tested first
Parsing = OK => OAuth2 Plan is selected (because there is no selection rule)

#### JWT plan tested first
Parsing = OK => claims != null => `(#context.attributes['jwt'].claims['iss'] == 'my-issuer') = TRUE` ? JWT plan is selected : OAuth2 Plan is selected (because there is no selection rule)

**Comment by apoddany** [comment]
To be handled together with 5828

**Comment by marcambier** [comment]
As discussed with @phiz71, I close this ticket cause the described "current behavior" is wrong.
When Oauth2 plan without selection rule is tested first, the token isn't parsed as there is no selection rule.
So there isn't any parsing error, and Oauth2 plan is selected.
