### ISSUE TITLE
Handle `pages` during API Promotion

### ISSUE THREAD

**Issue by gaetanmaisse** [gravitee-io/issues#5841]
### User story

As an APIM user, when I promote an API to another environment I want the documentation pages to be promoted too.

#### Creation case:
1. Select an API (that was never promoted before)
2. Create a documentation page at the root: `Rootpage`
3. Create a folder: `Doc folder`
4. Create a documentation page inside the just created folder: `Subpage`
5. Promote the API to another env
6. Accept the Promotion 
7. Check the documentation pages of the API created by the promotion, it should be the same as the one of the source API

#### Update case:
1. Select the previous API (the one the promotion is based on)
2. Update its documentation (update names, content and/or add pages)
3. Promote the API to the same env as the previous promotion
4. Accept the Promotion
5. Check the documentation pages of the API updated by the promotion, it should be the same as the one of the source API

Notes: If you remove a doc page and promote an API then the page will not be removed in the promotion target API (to have a behavior consistent with the export/import feature)

### Technical side notes

- Replace use of `GraviteeContext.getCurrentEnv`

Use IntelliJ refactoring feature: cmd+option+p to introduce parameters

**Comment by patelami** [comment]
env: local
result: pass
