### ISSUE TITLE
[gateway] Add missing implementations in Http repositories

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#5846]
New repository methods has been introduced by the ability to link a gateway to organization and environment. [issue here](https://github.com/gravitee-io/issues/issues/5357)

the repository gateway bridge http has not been updated with these changes, making impossible to use the gateway in bridge mode.

We have to update this repository to be up to date with the others. (see SyncManager and SyncService)

**Comment by patelami** [comment]
@ytvnr: Please can you close/move this ticket to ready to release if it is a technical task and does not require testing.
