### ISSUE TITLE
Lost documentation pages when duplicating an API

### ISSUE THREAD

**Issue by gaetanmaisse** [gravitee-io/issues#5849]
### Steps to Reproduce 
1. Select an API
2. Create a documentation page at the root: `Rootpage`
3. Create a folder: `Doc folder`
4. Create a documentation page inside the just created folder: `Subpage`
5. Duplicate the API
6. Check the documentation pages of the API created by the duplication 

### Expected Behavior
The documentation should contain exactly the same pages: 
``` 
---- Rootpage
---- Doc folder
  |------ Subpage
```
### Current Behavior
The pages contained in a folder are lost: 
```
---- Rootpage
---- Doc folder
```

**Comment by patelami** [comment]
env: nightly

Given I have created a page inside the folder
And I duplicate the API
Then I should see the page created inside the folder in duplicated API 

FAIL

**Comment by patelami** [comment]
env: nightly

Given I have selected an API
And I am on the root folder of `pages`(documentation)
And I create a folder named intro at the root folder
Then I click on the `Documentation > Pages` from the left menu
And I am unable to navigate back to the root folder of documentation 

Currently, we are unable to navigate back to the root folder by clicking on `Pages`.
To navigate back on the root folder of `Pages` we have to click on any other menu item (like metadata) and click back to the `Pages` to be able to navigate to the root folder

**Comment by patelami** [comment]
env: nightly 
PASS
