### ISSUE TITLE
[management] [gateway] manage ssl connections for backend

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#5856]
Currently, there are no configuration capabilities to customize SSL/TLS connection settings for Reporters/Repositories using relational databases.

The MongoDB settings are not properly manage either.

**Comment by omatthewsgravitee** [comment]
Ask Arnaud about time commitments on this one

**Comment by leleueri** [comment]
List of documentation to enable SSL on JDBC & R2DBC drivers 

 
- https://github.com/mirromutth/r2dbc-mysql/blob/main/README.md
- https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-using-ssl.html
 	
- https://github.com/pgjdbc/r2dbc-postgresql/blob/main/README.md
- https://jdbc.postgresql.org/documentation/head/ssl-client.html
 
- https://github.com/mariadb-corporation/mariadb-connector-r2dbc
- https://mariadb.com/kb/en/using-tls-ssl-with-mariadb-java-connector/
 
- https://github.com/r2dbc/r2dbc-mssql
- https://docs.microsoft.com/fr-fr/sql/connect/jdbc/connecting-with-ssl-encryption?view=sql-server-ver16

**Comment by ashraf706** [comment]
Closing this issue for releasing change log. We need to make sure the helm chart is merged.
