### ISSUE TITLE
login page issue

### ISSUE THREAD

**Issue by FourTimes** [gravitee-io/issues#5880]
HI. i try to login the gravity portal.

![image](https://user-images.githubusercontent.com/57703276/126220121-87854e81-89c2-4603-899e-5e3b87c0cf0c.png)

console.log

![image](https://user-images.githubusercontent.com/57703276/126220246-362571f2-573a-4e05-9f5b-5c8a252253d1.png)

**Comment by aelamrani** [comment]
Hi @FourTimes 

It looks to be due to your management REST API.

Can you check the logs?
