### ISSUE TITLE
[management] impossible to import API from URL.

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#5881]
It is impossible to import an API from a URL

### Expected Behavior
Be able to do it

### Steps to Reproduce (for bugs)
Try to import an API by URL using https://api.gravitee.io/api-echo.json

**Comment by patelami** [comment]
I am unable to test this because it is not been deployed on nightly yet.

**Comment by patelami** [comment]
This is not working on nightly at the moment: 

refactor done on plans for API promotion caused a little regression that's visible when importing an API by URL https://github.com/gravitee-io/issues/issues/5881
In this case, we do not have a plan type causing an NPE

![image (1)](https://user-images.githubusercontent.com/14215437/126985498-0c6879c0-149c-462d-9529-95a4e0cf2c4c.png)

**Comment by patelami** [comment]
env: nightly
Result: PASS

As a user, I should be able to import an API from the link(Tested only on `API definition) PASS
