### ISSUE TITLE
[ratelimit] Rate limiting not working with Redis

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#5882]
The rate limiting policy has no effect if "redis" is configured as rate limiting resource but works fine with mongodb.

Test done using redis connector 3.2.0 and APIM 3.9.3 & redis 6.2.4.

Configuration APIM:
```
gravitee_ratelimit_type=redis
gravitee_redis_host=xxx
gravitee_redis_port=6379
gravitee_redis_password=xxx
gravitee_redis_timeout=2000
```

**Comment by ytvnr** [comment]
@leleueri the configuration you use is wrong, it should be:

gravitee_ratelimit_type=redis
gravitee**_ratelimit**_redis_host=xxx
gravitee**_ratelimit**_redis_port=6379
gravitee**_ratelimit**_redis_password=xxx
gravitee**_ratelimit**_redis_timeout=2000

I updated the documentation and added a docker-compose to be able to test it easily
