### ISSUE TITLE
[platform] Auto-renew certificates

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#5888]
Instead of having to restart the HTTP server nodes to handle certificate renewal, it would be better to add listeners for automatic certificates reload.

This is true when:
- The truststore / keystore is / are based on a file from the filesystem
- The truststore / keystore are based on kubernetes secrets / TLS (thanks to https://github.com/gravitee-io/issues/issues/5887)

**Comment by larsnaesbye** [comment]
Seems to be a general version of https://github.com/gravitee-io/issues/issues/4508 ?
