### ISSUE TITLE
[reporter-file] [reporter-tcp] manage user-agent in the elasticsearch output

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#5893]
When request even are ingested into ES using logstash, user-agent always send with empty string. https://github.com/gravitee-io/gravitee-reporter-tcp/blob/master/src/main/resources/elasticsearch/index/request.ftl#L54
This may generates some error at logstash level if pipeline using "user agent" is defined.

# Possible solution

* Always send the user-agent value
OR
* Introduce a settings to set the value

**Comment by leleueri** [comment]
The user-agent field must be sent in any case.

**Comment by RachidKelidou** [comment]
need the same fix for index gravitee-health
