### ISSUE TITLE
[gateway] possible performance issue

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#5897]
When we have an API to transfer a file, download time maybe twice longer than the donwload duration if we request directly the source.

Version: 3.5.17 & 3.0.9

Using Postman, we can see for a download of 44MB file:
* Directly on nginx: Total time of 61ms with Tansfert Start around 1 or 2ms and download time around 56ms
* GW in front of nginx: Total time around 176 ms with Tansfert Start around 5ms (up to 20ms) and download time around 160ms

We should study how to improve these duration.

**Note:** Ask support team for API definition.

# How to reproduce

* Start Nginx and put a file around 40MB in the html directory
* Download the file using Postman
* Look at the detail duration information
* Create a API on APIM using the API definition to access the nginx
* Download the file from GW using Postman
* Look at the detail duration information (transfert start and download are much more important)

Here after an output of async-profiler 

The "Transfert start" duration isn't always high but the "download" is always at least twice![gw-download.svg](https://images.zenhubusercontent.com/6026363e864bfc6af2b3aa2c/b4f3a3d4-32bd-45f6-8f77-b05aa082d9f2) the nginx download time

**Comment by jhaeyaert** [comment]
NGINX |   | Gateway
-- | -- | --
  |   |  
http_code:  200       http_connect:  000       num_connects:  1      num_redirects:  0      size_download: 46905776        size_header:  247       size_request: 86        size_upload: 0     speed_download:  71502707,000       speed_upload:  0,000    time_namelookup:  0,001019s       time_connect:  0,001235s    time_appconnect:  0,000000s   time_pretransfer:  0,001258s      time_redirect:  0,000000s time_starttransfer:  0,003740s<br/><br/>----------         time_total:  0,656514 |   | http_code:  200       http_connect:  000       num_connects:  1      num_redirects:  0      size_download: 46905776        size_header:  373       size_request: 81        size_upload: 0     speed_download:  59752580,000       speed_upload:  0,000    time_namelookup:  0,001102s       time_connect:  0,001260s    time_appconnect:  0,000000s   time_pretransfer:  0,001281s      time_redirect:  0,000000s time_starttransfer:  0,009171s<br/><br/>----------         time_total:  0,785864
  |   |  
http_code:  200       http_connect:  000       num_connects:  1      num_redirects:  0      size_download: 46905776        size_header:  247       size_request: 86        size_upload: 0     speed_download:  68776797,000       speed_upload:  0,000    time_namelookup:  0,000984s       time_connect:  0,001191s    time_appconnect:  0,000000s   time_pretransfer:  0,001233s      time_redirect:  0,000000s time_starttransfer:  0,003960s<br/><br/>----------         time_total:  0,682849 |   | http_code:  200       http_connect:  000       num_connects:  1      num_redirects:  0      size_download: 46905776        size_header:  373       size_request: 81        size_upload: 0     speed_download:  68979082,000       speed_upload:  0,000    time_namelookup:  0,001092s       time_connect:  0,001264s    time_appconnect:  0,000000s   time_pretransfer:  0,001285s      time_redirect:  0,000000s time_starttransfer:  0,005356s<br/><br/>----------         time_total:  0,680076
  |   |  
http_code:  200       http_connect:  000       num_connects:  1      num_redirects:  0      size_download: 46905776        size_header:  247       size_request: 86        size_upload: 0     speed_download:  74335619,000       speed_upload:  0,000    time_namelookup:  0,001084s       time_connect:  0,001305s    time_appconnect:  0,000000s   time_pretransfer:  0,001329s      time_redirect:  0,000000s time_starttransfer:  0,004003s<br/><br/>----------         time_total:  0,631175 |   | http_code:  200       http_connect:  000       num_connects:  1      num_redirects:  0      size_download: 46905776        size_header:  373       size_request: 81        size_upload: 0     speed_download:  71721370,000       speed_upload:  0,000    time_namelookup:  0,001152s       time_connect:  0,001393s    time_appconnect:  0,000000s   time_pretransfer:  0,001460s      time_redirect:  0,000000s time_starttransfer:  0,007396s<br/><br/>----------         time_total:  0,654754
  |   |  
http_code:  200       http_connect:  000       num_connects:  1      num_redirects:  0      size_download: 46905776        size_header:  247       size_request: 86        size_upload: 0     speed_download:  64431010,000       speed_upload:  0,000    time_namelookup:  0,001430s       time_connect:  0,001811s    time_appconnect:  0,000000s   time_pretransfer:  0,001848s      time_redirect:  0,000000s time_starttransfer:  0,004804s<br/><br/>----------         time_total:  0,728862 |   | http_code:  200       http_connect:  000       num_connects:  1      num_redirects:  0      size_download: 46905776        size_header:  373       size_request: 81        size_upload: 0     speed_download:  65694364,000       speed_upload:  0,000    time_namelookup:  0,000914s       time_connect:  0,001084s    time_appconnect:  0,000000s   time_pretransfer:  0,001105s      time_redirect:  0,000000s time_starttransfer:  0,004716s<br/><br/>----------         time_total:  0,714405
  |   |  
http_code:  200       http_connect:  000       num_connects:  1      num_redirects:  0      size_download: 46905776        size_header:  247       size_request: 86        size_upload: 0     speed_download:  61234694,000       speed_upload:  0,000    time_namelookup:  0,000843s       time_connect:  0,001009s    time_appconnect:  0,000000s   time_pretransfer:  0,001034s      time_redirect:  0,000000s time_starttransfer:  0,003132s<br/><br/>----------         time_total:  0,766055 |   | http_code:  200       http_connect:  000       num_connects:  1      num_redirects:  0      size_download: 46905776        size_header:  373       size_request: 81        size_upload: 0     speed_download:  61475460,000       speed_upload:  0,000    time_namelookup:  0,000988s       time_connect:  0,001189s    time_appconnect:  0,000000s   time_pretransfer:  0,001217s      time_redirect:  0,000000s time_starttransfer:  0,004744s<br/><br/>----------         time_total:  0,763710
  |   |  
http_code:  200       http_connect:  000       num_connects:  1      num_redirects:  0      size_download: 46905776        size_header:  247       size_request: 86        size_upload: 0     speed_download:  66438776,000       speed_upload:  0,000    time_namelookup:  0,001004s       time_connect:  0,001187s    time_appconnect:  0,000000s   time_pretransfer:  0,001210s      time_redirect:  0,000000s time_starttransfer:  0,003730s<br/><br/>----------         time_total:  0,706107 |   | http_code:  200       http_connect:  000       num_connects:  1      num_redirects:  0      size_download: 46905776        size_header:  373       size_request: 81        size_upload: 0     speed_download:  64431010,000       speed_upload:  0,000    time_namelookup:  0,001085s       time_connect:  0,001335s    time_appconnect:  0,000000s   time_pretransfer:  0,001390s      time_redirect:  0,000000s time_starttransfer:  0,005946s<br/><br/>----------         time_total:  0,728970
  |   |  
http_code:  200       http_connect:  000       num_connects:  1      num_redirects:  0      size_download: 46905776        size_header:  247       size_request: 86        size_upload: 0     speed_download:  72497335,000       speed_upload:  0,000    time_namelookup:  0,000888s       time_connect:  0,001086s    time_appconnect:  0,000000s   time_pretransfer:  0,001128s      time_redirect:  0,000000s time_starttransfer:  0,003577s<br/><br/>----------         time_total:  0,647791 |   | http_code:  200       http_connect:  000       num_connects:  1      num_redirects:  0      size_download: 46905776        size_header:  373       size_request: 81        size_upload: 0     speed_download:  72385456,000       speed_upload:  0,000    time_namelookup:  0,000918s       time_connect:  0,001108s    time_appconnect:  0,000000s   time_pretransfer:  0,001130s      time_redirect:  0,000000s time_starttransfer:  0,004381s<br/><br/>----------         time_total:  0,648581

**Comment by aelamrani** [comment]
Not to be closed
