### ISSUE TITLE
confusion in the icons for activating/deactivating alerts

### ISSUE THREAD

**Issue by RachidKelidou** [gravitee-io/issues#5903]
From the configuration page of an API, in the Alerts menu, the alerts for that API are listed.

However, the direction of the icons to enable/disable the alert is misleading.

![mceclip0](https://user-images.githubusercontent.com/79910027/126773040-51caca41-e1e9-4755-bb0f-03f55e13d8a0.png)

The icon :white_check_mark: is used to deactivate the alert and the :no_entry_sign: icon is used to activate the alert.

This is more of a status icon than an action icon.

To avoid any confusion, it would be interesting to change the way it works.

**Comment by gaetanmaisse** [comment]
It has been closed as this screen will be reworked during the Angular migration, UI/UX will take care of improving that particular point.
