### ISSUE TITLE
Importing swagger does produce working api

### ISSUE THREAD

**Issue by jfmonteil** [gravitee-io/issues#5906]
Hello,

I have installed Gravitee on a AWS VM

I have created my first API using gravitee relying on an endpoint and it works just fine (/jfmcustomers)

Now if I import a swagger (OASV3) it does not work.

If I call `myIpadfress//services/hubcustomerjfm/Customer?id=84` it says `404 No context-path matches the request URI.`

![image](https://user-images.githubusercontent.com/8617022/126800206-9bfec086-359e-4151-b6c4-9ba395cfb4d4.png)

Swagger is added here

`{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Customers_API_Complete_Demo",
    "description" : "Allows you to retrieve customer information.",
    "contact" : {
      "name" : "cclement",
      "email" : "cclement"
    },
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "http://XX.XX.XX.XX:8040/services",
    "description" : "Server simulation"
  }, {
    "url" : "https://l9r0hdl.us.api-mocks.com",
    "description" : "This is your API mock endpoint. When called, it will simulate the behavior of your API."
  } ],
  "paths" : {
    "/Customer" : {
      "get" : {
        "summary" : "Customer",
        "description" : "Cette API permet de récupérer les informations d'un client sur la base de son identifiant",
        "parameters" : [ {
          "name" : "id",
          "in" : "query",
          "required" : true,
          "description" : "query",
          "schema" : {
            "type" : "integer",
            "format" : "int32",
            "description" : "query"
          },
          "example" : 12
        } ],
        "responses" : {
          "200" : {
            "description" : "Cela correspond à une réussite de l'appel à l'API",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Client"
                }
              }
            }
          }
        }
      },
      "put" : {
        "summary" : "UpdateCustomer",
        "description" : "Cette API permet de faire un update du numéro de téléphone d'un client. Le code pays du client est obligatoire, dans le but de formater le numéro de téléphone à un format international. \n\nCette opération est réalisée par un composant Talend de mise en qualité des données, facilitant l'intégration de cette information dans le reste du système d'information.",
        "parameters" : [ {
          "name" : "id",
          "in" : "query",
          "required" : true,
          "description" : "query",
          "schema" : {
            "type" : "integer",
            "format" : "int32",
            "description" : "query"
          },
          "example" : 12
        }, {
          "name" : "phone",
          "in" : "query",
          "required" : true,
          "description" : "Il s'agit du numéro de téléphone du client. Talend va reformater le numéro de téléphone au standard international",
          "schema" : {
            "type" : "string",
            "description" : "Il s'agit du numéro de téléphone du client. Talend va reformater le numéro de téléphone au standard international"
          },
          "example" : "0476640447"
        }, {
          "name" : "ISO2",
          "in" : "query",
          "required" : true,
          "description" : "Il s'agit du code ISO (code Pays) sur 2 caractères",
          "schema" : {
            "type" : "string",
            "description" : "Il s'agit du code ISO (code Pays) sur 2 caractères"
          },
          "example" : "FR"
        } ],
        "responses" : {
          "200" : {
            "description" : "Status 200"
          }
        }
      },
      "post" : {
        "summary" : "CreateCustomer",
        "description" : "Cette API permet la création d'un client dans la base client.\n\nLa création utilise le format Json.",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "type" : "object",
                "properties" : {
                  "NOM" : {
                    "type" : "string",
                    "description" : "Nom de la personne",
                    "example" : "Clement"
                  },
                  "PRENOM" : {
                    "type" : "string",
                    "description" : "Prénom de la personne",
                    "example" : "Clement"
                  },
                  "MAIL" : {
                    "type" : "string",
                    "description" : "Email de la personnes",
                    "example" : "cclement@talend.com"
                  },
                  "TELEPHONE" : {
                    "type" : "string",
                    "description" : "Téléphone de la personne",
                    "example" : "0476640447"
                  },
                  "NUMERO_DE_RUE" : {
                    "type" : "string",
                    "description" : "Numéro de la rue de la personne",
                    "example" : "24"
                  },
                  "VILLE_FORMATE" : {
                    "type" : "string",
                    "description" : "Nom de la ville de la personne",
                    "example" : "Lyon"
                  },
                  "REGION" : {
                    "type" : "string",
                    "description" : "Région de la personnes",
                    "example" : "Rhone-Alpes"
                  },
                  "DEPARTEMENT" : {
                    "type" : "string",
                    "description" : "Département de la personne",
                    "example" : "Rhône"
                  },
                  "PAYS" : {
                    "type" : "string",
                    "description" : "Pays de la personne",
                    "example" : "France"
                  },
                  "CODE_POSTAL" : {
                    "type" : "string",
                    "description" : "Code postal de la ville de la personne",
                    "example" : "69006"
                  }
                }
              },
              "example" : "{\n  \"Customer\":[\n    {\n\t\t\"NOM\": \"Julien\",\n\t\t\"PRENOM\": \"Nathan\",\n\t\t\"MAIL\": \"Julien.Nathan@hotmail.com\",\n\t\t\"TELEPHONE\": \"03 32 12 12 40\",\n\t\t\"NUMERO_DE_RUE\": 52,\n\t\t\"VILLE_FORMATE\": \"Bordeaux\",\n\t\t\"REGION\": \"Aquitaine\",\n\t\t\"DEPARTEMENT\": \"Gironde\",\n\t\t\"PAYS\": \"France\",\n\t\t\"CODE_POSTAL\": 33000,\n    }\n    ]\n}"
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "Création du client OK. Pour le verifier vous pouvez utiliser le l'API GET en utilisant l'identifiant."
          }
        }
      },
      "delete" : {
        "summary" : "DeleteCustomer",
        "description" : "Permet de supprimer un utilisateur à partir de son ID.",
        "parameters" : [ {
          "name" : "id",
          "in" : "query",
          "required" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int32"
          },
          "example" : 23453
        } ],
        "responses" : {
          "200" : {
            "description" : "Status 200"
          }
        }
      }
    },
    "/SalesPoint" : {
      "description" : "Client by Point of sales",
      "get" : {
        "summary" : "SalesPoint",
        "description" : "Permet de récupérer tous les clients rattachés à un magasin. Pour des raisons de GDPR, un traitement d'anonymisation est réalisé en back-office. Les valeurs \"personally identifying information\" (PII) sont donc échangées avec de fausses valeurs. Cela est réalisé par un composant de notre outil de gestion des API Talend.  ",
        "parameters" : [ {
          "name" : "SalesPoint",
          "in" : "query",
          "required" : true,
          "description" : "query",
          "schema" : {
            "type" : "integer",
            "format" : "int32",
            "description" : "query"
          },
          "example" : 1
        } ],
        "responses" : {
          "200" : {
            "description" : "Status 200"
          }
        }
      }
    },
    "/Customers" : {
      "get" : {
        "summary" : "Customers",
        "description" : "List all customers",
        "responses" : {
          "200" : {
            "description" : "Result OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Clients"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "Client" : {
        "type" : "object",
        "required" : [ "ID_CLIENT" ],
        "properties" : {
          "ID_CLIENT" : {
            "type" : "integer",
            "format" : "int32",
            "description" : "1"
          },
          "NOM" : {
            "type" : "string",
            "example" : "Clement"
          },
          "PRENOM" : {
            "type" : "string",
            "example" : "Charles"
          },
          "MAIL" : {
            "type" : "string",
            "example" : "cclement@talend.com"
          },
          "ID_MAGASIN" : {
            "type" : "string",
            "example" : "1"
          },
          "VILLE_MAGASIN" : {
            "type" : "string",
            "example" : "Lyon"
          },
          "ID_VENDEUR" : {
            "type" : "string"
          },
          "TELEPHONE" : {
            "type" : "string",
            "example" : "0659678061"
          },
          "ADRESSE_FORMATE" : {
            "type" : "string"
          },
          "NUMERO_DE_RUE" : {
            "type" : "string"
          },
          "VILLE_FORMATE" : {
            "type" : "string"
          },
          "REGION" : {
            "type" : "string"
          },
          "DEPARTEMENT" : {
            "type" : "string"
          },
          "PAYS" : {
            "type" : "string"
          },
          "CODE_POSTAL" : {
            "type" : "string"
          },
          "lat" : {
            "type" : "number"
          },
          "lng" : {
            "type" : "number"
          },
          "status" : {
            "type" : "string"
          },
          "ADRESSE_ORIGINE" : {
            "type" : "string"
          }
        }
      },
      "Clients" : {
        "type" : "array",
        "items" : {
          "$ref" : "#/components/schemas/Client"
        }
      }
    },
    "responses" : {
      "ID_CLIENT" : {
        "description" : "ID_CLIENT",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : "string"
            }
          }
        }
      },
      "NOM" : {
        "description" : "NOM",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : "string"
            },
            "example" : "Clement"
          }
        }
      }
    },
    "parameters" : {
      "Clients" : {
        "name" : "Clients",
        "in" : "path",
        "required" : true,
        "schema" : {
          "type" : "string"
        }
      },
      "Client" : {
        "name" : "Client",
        "in" : "path",
        "required" : true,
        "schema" : {
          "type" : "string"
        }
      }
    }
  }
}`

Any help welcome cheers

**Comment by brasseld** [comment]
Hi @jfmonteil 

Do you have a plan defined for this API ?

**Comment by jfmonteil** [comment]
nope, is it mandatory ?

**Comment by brasseld** [comment]
Yes it is.

**Comment by jfmonteil** [comment]
oups, I will check tomorrow, it's a bit late in France.
I was wondering where in the documentation is a checklist ?
Many thanks,
JFM

**Comment by brasseld** [comment]
No problem, I understand (coming from France as well).

Regarding the documentation best is to have a look to https://docs.gravitee.io/apim/3.x/apim_publisherguide_plans_subscriptions.html

**Comment by jfmonteil** [comment]
Ok so now I have a plan (Keyless), the API is published, started and made public and I still have the same message : `No context-path matches the request URI.`
The endpoint is good because when I create a new API from scratch it works fine.

**Comment by jfmonteil** [comment]
Ok I can close, you have to re-deploy (from the orange bar) once the plan is created. Cheers,

**Comment by jfmonteil** [comment]
Ok I can close, you have to re-deploy (from the orange bar) once the plan is created. Cheers,
