### ISSUE TITLE
UX improvement: Missing error message when user is trying to delete the API without depricating 

### ISSUE THREAD

**Issue by patelami** [gravitee-io/issues#5907]
Given I have created and published the API
And I delete the API
Then I should see a feedback message: "deprecate the API to be able to delete it "

Actual behaviour: 
User is not allowed to delete the published API, but we do not provide any feedback message to indicate the API is not deleted because it published

**Comment by aelamrani** [comment]
@patelami just to be sure we are on the same page, are you talking about this section?

<img width="1003" alt="Capture d’écran 2021-08-17 à 21 22 34" src="https://user-images.githubusercontent.com/1580262/129787709-77958d8e-68ce-461f-a7a4-182ed6068c7c.png">

If yes, there is a message saying "A running or published API cannot be deleted", so maybe the issue is more about having a better way to display this information and not having the information?

**Comment by patelami** [comment]
@aelamrani : in Delete API feature there are two areas we can improve user experience:

---------------------------------------------------------------------------------
[1]
---

In case if API is NOT started/published, and API has active plans / subscription, user is allowed to delete the API and user won't see the message `A running or published API cannot be deleted`. This message would dynamically appear only when the delete button is inactive(i.e grey), API is started/published. 

<img width="949" alt="Screenshot 2021-08-17 at 22 49 44" src="https://user-images.githubusercontent.com/14215437/129805338-4920bf72-c436-4fb3-a951-d6bd262864d0.png">

An error message saying `plans/subscription must be closed to deleted` in a quick  popup will appear on bottom of the screen if user tries to delete the API which has status:unpublished /status: stopped. (This requires better user experience)


------------------------------------------------------------------
[2]
---
Following are the two different ways user is allowed to delete API

1. User can delete API only if all of the following conditions are met

- API is stopped
- API is unpublished 
- API has no published plans(all the plans are closed or deprecated)
- No active subscriptions

**OR**

2. A user can delete API if API is deprecated 

But it is not obvious in current UI.
