### ISSUE TITLE
[console] custom claims display issue

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#5912]
When I have some clustom claims (for IDToken or AuccessTocken). If I want to add a new claims, the accesstoken list is diplayed twice (same for id-token)

![image.png](https://images.zenhubusercontent.com/6026363e864bfc6af2b3aa2c/2c0b2889-e88a-498f-a5f4-dea52c1da86a)

**Comment by tcompiegne** [comment]
I think it's here since the beginning.

Not sure we can do much about this one (it seems tricky).
