### ISSUE TITLE
[policy] [dynamic-routing] Routing is not working as expected

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#5915]
Since https://github.com/gravitee-io/issues/issues/4943

Dynamic routing is not working anymore.

The expression language is no longer interpreted in the routing rules.

For testing, just use EL in a rule. 

- Add endpoint and/or group 
- Add rule on dynamic policy
- Call the api

You can find an example in the documentation: https://docs.gravitee.io/apim/3.x/apim_policies_dynamic_routing.html

**Comment by patelami** [comment]
env: nightly
result: PASS
