### ISSUE TITLE
[certificate] avoid code duplication

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#5925]
PKCS12 & JKS provider use the same methods implementation. (excepted for the afterPropertiesSet that parse the cert according to the format managed by the provider).

A refactor to make this code common to the both implementation may be useful.

**Comment by patelami** [comment]
Env: Nightly
Result: PASS

As an admin I should be able to upload PKCS certificate
As an admin I should be able to upload java keystore certificate
