### ISSUE TITLE
[management] API creation documentations improvments

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#5941]
Issues detected in step 4 of the "API creation" flow :

### Adding mutliple documents
- import a file
- import another file
- in next step "deployment", click "create the api without deploying it"
--> a Mongo error "duplicate key" is shown, API is created without the second document

### Adding mutliple documents with same filename
- import a file
- import another file with the same filename
--> second document is not added in the list

### Deleting a document
When clicking on the delete button, the popup shows an empty "warning" :
![image](https://user-images.githubusercontent.com/87964124/127664018-e8494431-b2e8-4b4a-8782-e4a151c7b773.png)
If this popup is useless, it could be removed to improve UX.

**Comment by gaetanmaisse** [comment]
> Adding mutliple documents with same filename
import a file
import another file with the same filename
--> second document is not added in the list

It will be handled in another issue and backported to older versions.
