### ISSUE TITLE
deleted plan is not removed from design studio

### ISSUE THREAD

**Issue by patelami** [gravitee-io/issues#5942]
**Steps to reproduce:**
1. Create an API using import feature: 
[ap_acmetravel-0-1.json.zip](https://github.com/gravitee-io/issues/files/6908336/ap_acmetravel-0-1.json.zip)
2. Create a plan > the plan will appear in the design studio(flows)
3. Delete the plan 
** PS: This issue is only on import API feature. The plan will be deleted from design studio if the API is created from scratch**  

**Actual Result:** 
The plan still appears in the flow in design studio

**Expected Result:** 
The plan should disappear from the flow
<img width="757" alt="Screenshot 2021-07-30 at 15 41 50" src="https://user-images.githubusercontent.com/14215437/127671797-2ef0d724-987f-424f-8b8f-04e24dfcf5fa.png">

**Comment by phiz71** [comment]
Not able to reproduce it in 3.5.20
