### ISSUE TITLE
Javascript policy

### ISSUE THREAD

**Issue by ibahloul** [gravitee-io/issues#5948]
- no available by default (check with @gcusnieux how to make it available on nightly)
- you can use JS code to manage your request/response/ & request content/response content

# Tests
- ask gravitee community to help us to create JS script
- http call out from JS policy

**Comment by aelamrani** [comment]
Missing a pull request on repo docs

**Comment by gcusnieux** [comment]
Missing a pull request on `release` ?

**Comment by patelami** [comment]
This is test comment

**Comment by patelami** [comment]
env: nightly
Result: PASS

Tested this policy with basic Javascript script to add the header in echo api.
Advance http call options are not tested
[NordLB-AsciiDoc-Demo-1-0-javascript-policy.json.zip](https://github.com/gravitee-io/issues/files/7085090/NordLB-AsciiDoc-Demo-1-0-javascript-policy.json.zip)
