### ISSUE TITLE
Management of Designer Model Commands

### ISSUE THREAD

**Issue by ibahloul** [gravitee-io/issues#5954]
- Implement command handler (received command should do the same as `POST /apis/import/swagger`)
- Should it be upgraded to new swagger import version? (api designer vs policy studio)

**Comment by loriepisicchio** [comment]
For information, here is the current API Designer implementation for model creation: https://github.com/gravitee-io/autoswagger/blob/develop/api/src/services/gravitee/api.service.js#L72

**Comment by marcambier** [comment]
@ibahloul , is this ticket always relevant ?
If so, can you please clarify your need ?
