### ISSUE TITLE
[platform] node stop event are not well propagated when node is stopped

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#5966]
The `NODE_STOPPED` event is sent by the `NodeMonitorService` when the current instance is stopped (https://github.com/gravitee-io/gravitee-node/blob/master/gravitee-node-monitoring/[…]ava/io/gravitee/node/monitoring/monitor/NodeMonitorService.java).

This event is then propagated an `EventProducer` which send it to an external point (for instance AE). This event producer is unfortunately stopped before the `NodeMonitorService` send the event. This is why the node stopped event is never propagated to the external system.

We need to find a way to orchestrate the services stop to be able to postpone the `EventProducer` stop process.

**Comment by phiz71** [comment]
A PR on release repository is missing

**Comment by ytvnr** [comment]
Need a fix on  gravitee-node `ReporterManagerImpl#doStop`

We have three `for` looping through reporters but the three call `.stop() `method
It should be `preStop()`, `stop()` and `postStop()`
