### ISSUE TITLE
Close dist.gravitee.io

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#597]
https://dist.gravitee.io is a hack developed when bintray was freezed.

We now have new https://download.gravitee.io where all items are stored.

We need to move to this new web site, this means : 
 - update our docker images
 - update release scripts
 - communicate over twitter for users who already use dist.gravitee.io for their CI
 - update documentation

**Comment by gaetanmaisse** [comment]
Closing as it looks like https://dist.gravitee.io/ is finally closed.
