### ISSUE TITLE
API scope ALERT read permission doesn't activate API alert detail

### ISSUE THREAD

**Issue by RachidKelidou** [gravitee-io/issues#5974]
A user with ALERT read permission at API scope is not able to see the alert details of the API : 

![image](https://user-images.githubusercontent.com/79910027/128546884-6d044311-dc1a-44fa-892b-21b86e407fd3.png)

The link on the alert name is missing. Also, the name and description values are reversed : 

![image](https://user-images.githubusercontent.com/79910027/128546945-7da9bdc8-3c78-4c3b-bdaf-5a002b10976d.png)

**Comment by mouligno** [comment]
Tested during review.
