### ISSUE TITLE
[management-ui] how is the "instances" menu populated?

### ISSUE THREAD

**Issue by bcollard** [gravitee-io/issues#598]
Hi,

How is this populated? 
`/management/instances/`

Is there any concept of "clustering" in the gravitee API Management?

**Comment by NicolasGeraud** [comment]
When a gateway starts, it log an event in the event repository.
`management/instances` shows those events.

The clustering concept is based on the cluster mode of the repository (mongo, redis, ...)

**Comment by brasseld** [comment]
I'm not fully agree with @NicolasGeraud.

**There is no clustering support for gateway instances.** What @NicolasGeraud says is that there is an underlying hearbeat system where each gateway instance send a status event into the repository.
Then, the management-api is looking into the repository to 'discover' gateway instances.

Are you looking for a way to 'group' gateway instances ? If so, for which purpose ?

**Comment by bcollard** [comment]
Thank you for your responses.
It was just a question and maybe a requirement for my other request #599
