### ISSUE TITLE
[management] Enable to sync APIs due to NPE

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#5980]
We have an NPE here
https://github.com/gravitee-io/gravitee-management-rest-api/blob/7e47c5c0024ea4f6c734c01423722a8bfcbf7a25/gravitee-rest-api-services/gravitee-rest-api-services-sync/src/main/java/io/gravitee/rest/api/services/sync/SyncManager.java#L354

if the event's payload doesn't contain an environmentId (apis published in v1.30)

2 options I think : 
 - create a script to update the event's payload
 - add the default envId in ApiDeserializer to manage this legacy
 
### Your Environment

* Version used: since 3.6

**Comment by gcusnieux** [comment]
Please fix https://github.com/gravitee-io/issues/issues/6077 and revalidate all TestContainer before merge
