### ISSUE TITLE
[policy] [cache] Support of cache replication across an APIM cluster

### ISSUE THREAD

**Issue by bcollard** [gravitee-io/issues#599]
Hi,

If there is some concept of clustering in Gravitee APIM (see #598), could you help us deploying a L2 cache over local ehcache instances?
The goal is to have a cluster-wide caching policy.

At this time, we don't mind about the solution you would choose among Terracotta, Jgroups, hazelcast, etc.

**Comment by brasseld** [comment]
Hi @bcollard,

There is actually no thinking about supporting an other cache provider but, imho, we would not support commercial product like Terracotta unless a user / customer is looking for it. In any case this will not be done under the scope of OSS project.

So options for us are only about JGroups and Hazelcast support.

**Comment by NicolasGeraud** [comment]
And be aware that in addition to the technical part, replication must take care of sharding tags and tenant to not replicate on each gateway.

**Comment by bcollard** [comment]
@brasseld : TC is also a open-source software : http://terracotta.org/downloads/open-source/catalog , isn't it?

@NicolasGeraud : that's why it's better if some of you guys do it :p

Anyway, it would be great - in some future - to have a cluster-wide caching policy.
Let's wait for your big clients to ask for it.

**Comment by brasseld** [comment]
There is not such need from our current customers so there is no chance to find this kind of feature in next versions of Gravitee APIM (roadmap is already defined until Gravitee.io APIM 1.9)

If you need it absolutely, you can:
* ask the company behind Gravitee to develop it,
* develop it by your own by using the underlying plugin system,
* wait for a volunteer from the community,
* you're a lucky guy 'cause someone has already implemented it (imho you can forget this option).

Regards,

**Comment by bcollard** [comment]
Great! 😉
