### ISSUE TITLE
[management] logging is enabled on the wrong api

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#5991]
In the current development version (3.11), it seems to be a problem regarding the logging feature.
When I try to enable the logging on an api and make some call on it, no log appears. However, I noticed that another of my apis have logs while the logging feature is disabled for it 🧐

Logging is disabled
![image](https://user-images.githubusercontent.com/5955401/129314248-0bc99019-a83d-49f9-8114-8a0aa74f64d7.png)

Log appears
![image](https://user-images.githubusercontent.com/5955401/129314286-f528b8a9-2057-4fda-aef5-41f1336e0e7e.png)

By the way, if I try to enable the logging on the api and want to customize the logging behavior, it has not effect at all (but maybe it could impact another api ?).

**Comment by marcambier** [comment]
As discussed with @jhaeyaert , I close this issue.

The observed behavior is OK : with logging configuration disabled, API calls are displayed, but there is no detail inside :
![image](https://user-images.githubusercontent.com/87964124/129725920-5d8b96ed-d3f3-467d-ae8d-d1bf25a61d3e.png)

There is also another issue about logs not send to ES when using IPV6 address : https://github.com/gravitee-io/issues/issues/5664
