### ISSUE TITLE
[gateway] make sure the gateway support multi organizations

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#5992]
Reading the code, I'm wondering how things work when dealing with multiple organizations 🧐 : https://github.com/gravitee-io/gravitee-gateway/blob/master/gravitee-gateway-platform/src/main/java/io/gravitee/gateway/platform/manager/impl/OrganizationManagerImpl.java#L48-L59

It appears that a `currentOrganization` is maintained by the `OrganizationManager`. The `currentOrganization` is replaced each time an organization is deployed (understand: organization's flow is updated). 

From my understanding, it means that it is a `last come, first served` behavior and it can potentially impact all deployed apis, even those not belonging to the same organization.

Can someone have a look and check if my understanding is right (and change the status to bug if applicable) ?

**Comment by gaetanmaisse** [comment]
## How to test

 - Cockpit
 - 2 organizations 
 - 1 single installation = 1 gateway

----> APIM Master env have this setup
 
To reproduce:
 - Using cockpit login to APIM Console Org A
 - Setup platform policies
 - Setup an API and send a call --> platform policies are applied
 - Using cockpit login to APIM Console Org B
 - Setup an API and send a call --> platform policies of Org A are applied 😱 ⚠️  they shouldn't
 - Setup platform policies on Org B
 - Using cockpit login to APIM Console Org A
 - Send a call on an API Org A --> platform policies of Org B are applied 😱 🙀

**Comment by ppgravitee** [comment]
Duplicate from #7432

**Comment by jhaeyaert** [comment]
This issue should not be ignored.

**Comment by mouligno** [comment]
indeed
