### ISSUE TITLE
[repository] search apis paginated may return wrong count and page size

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#5993]
At least from 3.5.x, implementations of `ApiRepository` apply a filter in memory.
Basically, the following steps are executed:

1. query the database with filters to count the total of apis
2. query the database with filters and apply pagination to limit results to a subset of apis
3. apply api path filter on the api page 
4. return the page result

There are multiples side effets that could occur because of the step 3:

- the number of total apis can be wrong because the path filter has not been applied when counting
- the page size may be wrong too because some apis may be removed after the path filter has been applied
- this can lead to pagination problem and apis may be skipped or appear on multiple pages.

We should find a way to avoid filtering in memory because it could lead to unwanted side effects. One of the possible tracks could be to normalize the api path in order to be able to directly filter on the database side (normalize == extract the information from the api definition and add a regular database field).

**Comment by mouligno** [comment]
Is it still accurate in 3.10+ ?

**Comment by gcusnieux** [comment]
Fix with https://github.com/gravitee-io/issues/issues/6254
