### ISSUE TITLE
Improve documentation for logging

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#6]
_From @aelamrani on February 26, 2016 13:56_

Add some doc to explain how to add logback configuration.

_Copied from original issue: gravitee-io/gravitee-gateway#62_

**Comment by brasseld** [comment]
@aelamrani: What do you need exactly ? A simple reference to SLF4J documentation is not sufficient ?

**Comment by brasseld** [comment]
_From @aelamrani on March 2, 2016 9:34_

I do not need, but the future users does :)
Not about how to write it, but where to put it...

**Comment by bcollard** [comment]
:+1: to add some doc about the logging policy :)
My need would be to see all of the HTTP headers in requests & responses while this plugin is active.

**Comment by bcollard** [comment]
inbound & outbound requests
inbound & outbound responses

**Comment by brasseld** [comment]
Hi @bcollard,

You can activate HTTP dump for an API from the gateway configuration. This will log the HTTP call to the backend.

<img width="853" alt="capture d ecran 2016-08-31 a 11 39 41" src="https://cloud.githubusercontent.com/assets/133094/18123759/a2d43276-6f6f-11e6-88e6-eaf16b611735.png">

Logs are written into a dedicated log file: _${gravitee.home}/logs/gravitee-httpdump.log_

Logging policy is used to track the content between each policy execution. By using the logging policy you can have a look to content transformation and so on...

**Comment by bcollard** [comment]
Perfect, thanks.

**Comment by brasseld** [comment]
Logging policy is no more available.
In the same way, `gravitee-httpdump` does not exist, all logs are written into ES
