### ISSUE TITLE
[gateway] Fine-grained conditional policies

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#60]
_From @brasseld on May 4, 2016 14:18_

Currently, policies are defined by path / HTTP methods.

Even if it sounds to be sufficient for a great majority of use case, it would be useful to define a more fine-grained condition to apply a policy.

For example:
Publisher wants to expose its API in XML and JSON but backend is only exposing data as XML. One condition to apply XML to JSON policy transformation will be that request HTTP headers have an _Accept_ header with an _application/json_ value

Example of conditions to apply a policy
- Use an HTTP headers or HTTP query parameters
- Use the user (remote) IP
- Define time slots
- .... 

_Copied from original issue: gravitee-io/release#42_

**Comment by brasseld** [comment]
Provide a way to copy and paste a policy from a path to an other one.

**Comment by aelamrani** [comment]
Interpreter EL
