### ISSUE TITLE
Mixing versions

### ISSUE THREAD

**Issue by hjdr4** [gravitee-io/issues#600]
I have 3 nodes running 1.3.3.
I want to upgrade to 1.5.1 doing a rolling upgrade.

This migration needs playing 4 database update scripts.

Do I have to play the scripts before or after upgrading the nodes ?

**Comment by brasseld** [comment]
Generally, you have to execute scripts before upgrading the nodes.
If by `node` you mean `gateway`, in this particular case (1.3.3 -> 1.5.1) you can execute scripts after upgrading gateway nodes.
The four scripts you're talking about are mainly written for management purpose and not runtime (gateway) itself.

**Comment by hjdr4** [comment]
Thank you.

In my setup, node means gateway+api+ui.

Just to be clear, that means I can :
1. Upgrade each node to 1.5.1
At this time nodes are running 1.5.1 runtime with 1.3.3 database

2. Play the database maintenance scripts while nodes are running

3. Maybe restart components after ?

My intention is to perform live upgrade on production without any downtime, so I prefer to triple check the procedure.

Thank you.

**Comment by brasseld** [comment]
Best is to avoid big jump between versions to insure a soft upgrade without any downtime.

Again, for this particular upgrade (1.3.3 to 1.5.1) you can execute scripts safely without the need to restart components.

Regards,

**Comment by aelamrani** [comment]
FYI, since this week the version 1.6 has been released

**Comment by brasseld** [comment]
Hi @hjdr4,

We can close this issue ?
