### ISSUE TITLE
[management UI]Documentation dose not disappear from modal 

### ISSUE THREAD

**Issue by patelami** [gravitee-io/issues#6004]
Irrespective of which page we are, every-time we click on ❓, `Documentation` will appear on the modal. 

![Screenshot 2021-08-17 at 22.18.17.png](https://images.zenhubusercontent.com/6037d57eba9d3cc0b0412549/93e53028-96f4-43f4-b947-8253e25068fb)

**Comment by gaetanmaisse** [comment]
Closing as it's the correct behavior as `Documentation` is the title of this right pane
