### ISSUE TITLE
Step 1: Database refactoring

### ISSUE THREAD

**Issue by ibahloul** [gravitee-io/issues#6005]
### Step 1 : Database refactoring
**This step is a technical prerequisite for other steps: refactor the database, separating the id from the key.
There is no functional change, applications with still work like before**
	
Database: 
- add new keys.key (string), equals to `id` for already existing records
- add new keys.api (string), equals to subscription.api for already existing records
- JDBC: add a liquibase script
- MongoDB: add js migration script

Model impacts :
- `ApiKey` -> add id and api
- `ApiKeyEntity` -> add id and api

Repositories impacts :
- `JdbcApiKeyRepository.getId`: return id instead of key
- `ApiKeyMongo`: add id and set `@Id` on it instead of key
- `ApiKeyRepository.findById`: now, it really finds by id, not by key (update parameter name)

Service impacts :
- `ApiKeyServiceImpl.generateForSubscription`: generate new key id via `UuidString.generateRandom` and set apiKey.api too.
- `ApiKeyServiceImpl.convert`: add 'id' and 'api' mapping

_If we want step 1 to work without step 2,
Implement `ApiKeyRepository.findByKey`, replace all calls to `ApiKeyRepository.findById` by `ApiKeyRepository.findByKey` (which returns the first found)_

# Tests 

- [ ] new subscriptions
- [ ] existing subscriptions
- [ ] custom api key (with the same uniqueness check)
- [ ] notification & expiration services

**Comment by marcambier** [comment]
As discussed with @jhaeyaert, I updated the above investigation : we will add the api Id in the keys table.
Database migration will be a bit trickier, but it simplifies the api key retreival.
