### ISSUE TITLE
Step 2: Handle duplicate API keys

### ISSUE THREAD

**Issue by ibahloul** [gravitee-io/issues#6006]
# Investigation Result
**This step permits to use the same API key for multiple subscriptions of the same application.
There is no change of the frontend behaviour, so there are some limits:**
- 'custom api key' setting should be enabled, as users can set api keys
- user has to copy/paste an api key in order to reuse it when creating a new one (for example on subscription validation, or renewal)
- All renew/revoke/update actions on API keys are still unitary. For example, the user will have to revoke X times the same API key in front.

Repository impacts :
- add `ApiKeyRepository.findByKeyAndApi`: optional, return first (should be one only)
- add `ApiKeyRepository.findByKey`: returns a list

Service impacts :
- `ApiKeyServiceImpl.exists(key)`
It actually checks if this key already exists.
Change it to `ApiKeyServiceImpl.canCreate(key, application)`
Returns `true` if key doesn't yet exists for another application, using `ApiKeyRepository.findByKey`
Callers have to provide application too on `ApikeysResource.verifyApiKeyAvailability` & `SubscriptionService.process`

- `ApiKeyServiceImpl.findByKey(key)`
Change it to `findByKeyAndApi(key, api)`
all callers should provide api too

- all callers of `ApiKeyServiceImpl.revoke` should provide api
1 call from `ApiKeysResource`, 1 call from `ApiSubscriptionResource`, 1 from `ApplicationSubscriptionResource`, 1 from `SubscritionServiceImpl`

- all callers of `ApiKeyServiceImpl.reactivate` should provide api
 1 call
	 
- `ApiKeyServiceImpl.update` : still calling `apiKeyRepository.findById`, but change parameter to use `apiKeyEntity.getId()` instead of key
all callers already call it with entity containing id

- `ApiKeyServiceImpl.updateDaysToExpirationOnLastNotification`, still calling `apiKeyRepository.findById`, but change parameter to use `apiKeyEntity.getId()` instead of key
all callers already call it with entity containing id
	
- `ApiKeyServiceImpl.search`: not impacted
	
Gateway impacts :

Actually, gateway caches API keys in a Map, by keys : Map<String, ApiKey> cache.
Now, the key of this map will be a concatenation of key+apiId.

- ApiKeyRefresher : Adapt the cache handling in "saveOrUpdate" function, to use key+api for the map key.

- ApiKeyRepositoryWrapper : findByKeyAndApi implementation now returns key from cache using key+api as map key. no more used implementations throws IllegalStateException()

- ApiKeyPolicy : Actual apiKey retreival is by id : executionContext.getComponent(ApiKeyRepository.class).findById(requestApiKey);
Now, we have to search it using findByKeyAndApi (api is available in executionContext)

- Implement findByKeyAndApi in HTTP bridge

# Tests
### Subscription Creation
- [ ] Given an API with an API key plan, when I create a subscription with a custom API key that is already used in a subscription of another application, then the following error message "" is displayed and the subscription is not created
- [ ] Given an API with an API key plan, when I create a subscription with a custom API key that is not used in a subscription of another application, then the subscription is created

### Subscription Validation (auto validation subscription disabled at plan level)
- [ ] Given a subscription request, when I accept this subscription with a custom API key that is already used in a subscription of another application, then the following error message "" is displayed and the subscription is not created
- [ ] Given a subscription request, when I accept this subscription with a custom API key that is not used in a subscription of another application, then subscription is created

### Subscription Paused
- [ ] Given an API with an API key plan, when I create a subscription with a custom API key that is already used in a paused subscription of another application, then the following error message "" is displayed and the subscription is not created
- [ ] Given an API with an API key plan, when I create a subscription with a custom API key that is not used in a paused subscription of another application, then the subscription is created

### Subscription Closing
- [ ] Given a subscription with a custom API key, when I close this subscription, then its custom API key can be used in a subscription of another application

### API Key Renewal
- [ ] Given a subscription, when I renew this subscription with a custom API key that is already used in a subscription of another application, then the following error message "" is displayed and the subscription is not created
- [ ] Given a subscription, when I renew this subscription with a custom API key that is not used in a subscription of another application, then the subscription is created
- [ ] Given a subscription, when I renew this subscription with a custom API key whose value is equal to the old one, then the following error message "" is displayed
- [ ] Given a subscription, when I renew this subscription with a custom API key whose value is different from the old one, then the API key is renewed

### API Key Revocation
- [ ] Given a subscription with a custom API key, when I revoke this API key, then this custom API key can't be used in a subscription of another application

### Subscription creation
- [ ] Given an API with at least 2 API key plans, when I create a subscription with a custom API key that is already used in another subscription of this API, then the following error message "" is displayed and the subscription is not created
- [ ] Given an API with at least 2 API key plans, when I create a subscription with a custom API key that is not used in another subscription of this API, then the subscription is created

### Subscription validation (auto validation subscription disabled at plan level)
- [ ] Given a subscription request, when I accept this subscription with a custom API key that is already used in another subscription of the related API, then the following error message "" is displayed and the subscription is not created
- [ ] Given a subscription request, when I accept this subscription with a custom API key that is not used in another subscription of the related API, then subscription is created

### Subscription paused
- [ ] Given an API with at least 2 API key plans, when I create a subscription with a custom API key that is already used in another paused subscription of this API, then the following error message "" is displayed and the subscription is not created
- [ ] Given an API with at least 2 API key plans, when I create a subscription with a custom API key that is not used in another paused subscription of this API, then the subscription is created

### Subscription closing
- [ ] Given an API with at least 2 API key plans, when I close the subscription of the first plan, then its custom API key can be used in a subscription of the other plan

### API Key Renewal
- [ ] Given a subscription, when I renew this subscription with a custom API key that is already used in another subscription of another plan of the same API, then the following error message "" is displayed and the subscription is not created
- [ ] Given a subscription, when I renew this subscription with a custom API key that is not used in another subscription of another plan of this API, then the subscription is created

### API Key Revocation
- [ ] Given an API with at least 2 API key plans, when I revoke the API key of the subscription of the first plan, then its custom API key can be used in a subscription of the other plan

**Comment by marcambier** [comment]
As discussed with @jhaeyaert, I updated the above investigation to improve the way gateway caches api keys.

**Comment by LiliaEn** [comment]
Env: nightly
Result: PASS
All test scenarios mentioned above were covered plus some more exploratory testing was performed.
cc: @RubenMMSantos @patelami

**Comment by RubenMMSantos** [comment]
Not tested with JDBC due to existing issue, there is a ticket already created to address this and it will be fixed/tested after the 3.12 release
