### ISSUE TITLE
[console] APIs with subfolders in Documentation pages can not be deleted "Unable to remove the folder"

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#6019]
While trying to delete an API that contains subfolders in the Documentation pages, it can not deleted as is but needs subfolders to be removed first.

### Steps to Reproduce (for bugs)

1. In UI Console, create an API with Documentation subfolders or import attached API
[APIsubfoldersDoc-1.txt](https://github.com/gravitee-io/issues/files/7014463/APIsubfoldersDoc-1.txt)

2. Try to delete the API. The following error will be raised : 
"Unable to remove the folder. It must be empty before being removed."
![image5](https://user-images.githubusercontent.com/79909781/130071203-47b30f71-deff-4fef-b714-b22c3dcb5db7.png)
3. You need to navigate in the Documentation Pages to manually delete the subfolders before being able to delete the API

### Your Environment

* Version used: 3.5.6, 3.5.18
* Browser Name and version:
* Operating System and version:

**Comment by phiz71** [comment]
It's not a bug, it is working like this.
Maybe it can be improve.
cc @mouligno
