### ISSUE TITLE
[portal] display of Applications may take too long and should be paginated

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#6020]
When many Applications have been created in Portal (over 900 in current use case), when clicking on the Applications menu, it can take time (up to 2 or 3 mins in the use case) to display all of them or even lead to timeout.
The display should be paginated to avoid this latency and Applications accessed with a search option.

### Your Environment

* Version used: 3.10.0
* Browser Name and version:
* Operating System and version:

**Comment by jhaeyaert** [comment]
See also https://github.com/gravitee-io/issues/issues/5045 which is about the same kind of performance problems.

**Comment by mouligno** [comment]
An epic has been created for this performance improvements : #6257

**Comment by mouligno** [comment]
Done in 3.15
