### ISSUE TITLE
[portal] Subscriptions menu should not be displayed if user does not have access rights on Applications subscriptions

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#6021]
If a user does not have roles permissions to access Subscriptions at the Application level, the "Subscriptions" sub-menu should not be displayed for an Application

### Steps to Reproduce (for bugs)

1. In Console, create an Application Role as below and setup a user with this role 

![read only](https://user-images.githubusercontent.com/79909781/130103592-8c1029ba-9d0f-4b7e-aed6-0e5f633e1d5d.PNG)

2. In Portal, with this user, browse the list of Applications and try to access to the Subscriptions of an Application, the following error will display : "You do not have sufficient rights to perform this action" 

![souscription application](https://user-images.githubusercontent.com/79909781/130103643-4b456e81-d68b-4c17-86d8-a49e9066a271.PNG)

A 403 error will be raised on https://localhost:8083/portal/environments/DEFAULT/subscriptions?applicationId=xxx&statuses=ACCEPTED&size=-1

3. The Subscriptions sub-menu should not be displayed in this case

### Your Environment

* Version used: 3.10.0
* Browser Name and version:
* Operating System and version:

**Comment by NicolasGeraud** [comment]
Those bugs also exist in 3.5

**Comment by apoddany** [comment]
In addition, if we remove the Subscription Read access in the Application Role, the following error will be displayed in the Portal while accessing the Dashboard : 
"Une erreur est survenue pendant de le chargement de l'API".
<img width="814" alt="Capture d’écran 2021-09-21 à 09 03 00" src="https://user-images.githubusercontent.com/79909781/134126502-810d3651-c352-4b1c-9955-4eee63ff959c.png">

**Comment by RubenMMSantos** [comment]
Issue verified and confirmed as fixed.
Issue verified on https://apim-3-10-x-console.cloud.gravitee.io/#!/environments/DEFAULT/applications/ & https://apim-3-10-x-portal.cloud.gravitee.io

![Screenshot 2021-12-07 at 14 09 16](https://user-images.githubusercontent.com/14939456/145044164-5467426d-1996-4051-821f-89e57d2c65fb.png)
/
