### ISSUE TITLE
List all APIM screens and T-Shirt size them

### ISSUE THREAD

**Issue by gaetanmaisse** [gravitee-io/issues#6022]
**Description**

To be able to have an overview of the migration progress and needed effort it should be great to have a listing of all the screens available in APIM and a T-Shirt sizing regarding the complexity of migration, proposed rating: 
 - `XS`: Super basic screen or popup without any AngularJS services nor AngularMaterial Layout
 - `S`: Simple screen using basic AngularJS services ($http, $timeout, $interval) and some Angular Material Layout + components 
 - `M`: Screen with AngularJS services like `$scope`, `$rootScope` and a non-simplistic UI. OR Screen still based on controllers/function instead of components
 - `L`: Screen containing a lot of conditional behaviour and/or a complex UI
 - `XL`: Super complex screen due to deeply linked components and/or services, router interactions etc

Do not forget the menu + header etc

**Expected Output**

 - Google Sheet with all screens + T-Shirt sizing + UX/UI migration or not
 🔗  -> [List all APIM screens](https://docs.google.com/spreadsheets/d/1sFd0B1a6PQTasLsgjps16ItNUTeNjnsdq-VORawZOmw/edit?usp=sharing)

**Comment by ThibaudAV** [comment]
Sheet : https://docs.google.com/spreadsheets/d/1sFd0B1a6PQTasLsgjps16ItNUTeNjnsdq-VORawZOmw/edit?usp=sharing

**Comment by gaetanmaisse** [comment]
The list is available [here](https://docs.google.com/spreadsheets/d/1sFd0B1a6PQTasLsgjps16ItNUTeNjnsdq-VORawZOmw/edit?usp=sharing). 

T-Shirt sizing rules have been updated and @ThibaudAV and I have estimated the screen related to Organization settings. The other one will be done after the migration of a few screens to ensure estimated values are ok.
