### ISSUE TITLE
API Analytics - An entry in the menu appears wrongly

### ISSUE THREAD

**Issue by ibahloul** [gravitee-io/issues#6026]
### Steps to Reproduce
1. Go to Organization Settings
2. Enable Alerts
3. Select an API
4. Go to Analytics

### Expected Behavior
The menu contains 3 entries: Overview, Logs, Path mappings

### Current Behavior
The menu contains an Alert entry

![Image d’iOS](https://user-images.githubusercontent.com/82866977/130614586-65cac027-ed0f-42ac-a260-07e8791ea0ef.jpg)

**Comment by mouligno** [comment]
fixed
