### ISSUE TITLE
[gateway] announce change on default value for bridge service enabled

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#6029]
Currently, Bridge Service is enabled by default.

### Expected Behavior
- We should add a log indicating that it will not be enable by default in the next version (3.13)
- We should add a note in release repository updates folder to announce this future breaking change.

⚠️ One missing line in release/upgrades, to complete before release

**Comment by brasseld** [comment]
FYI, I just had a look to our Helm Charts.
There is nothing to do from that side.
