### ISSUE TITLE
[gateway] change default value for bridge service enabled

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#6030]
Change on default value `enabled` for Bridge Service has been announced in 3.12

### Expected Behavior
- Remove the log line
- change the default value to `false`
- There is a place with `services.bridge.enabled` and another with `services.bridge.http.enabled`. We should harmonize this property. As discussed during workshop, keep `services.bridge.*` and apply it to other properties
- Announce breaking change in gravitee release repository updates folder
- do not forget to update the documentation "guides" with the new value (https://docs.gravitee.io/apim/3.x/apim_installguide_hybrid_deployment.html)

**Comment by mouligno** [comment]
Any doc associated ?
