### ISSUE TITLE
[console] Logo disappeared after migration to 3.10

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#6038]
I have migrated an installation from 3.9.x to 3.10.0 and the logo disappeared (using a PostgreSQL DB)

![image](https://user-images.githubusercontent.com/1580262/130926321-dcb05678-8193-4817-9be9-f9019aa6391f.png)

Seems we miss a migration step

![image](https://user-images.githubusercontent.com/1580262/130926425-c8495866-1d1a-41ac-989f-31f537e7a020.png)

Since https://github.com/gravitee-io/gravitee-management-rest-api/pull/1522/commits/8d9f49f7331aa6236ad772f420be9acd0d74bee9

**Comment by gcusnieux** [comment]
https://github.com/gravitee-io/gravitee-management-rest-api/pull/1522/commits/8d9f49f7331aa6236ad772f420be9acd0d74bee9
