### ISSUE TITLE
Link to Primary Owner Group broken in blog post for APIM 3.7

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6041]
The link to documentation for Primary Owner Groups is broken (404) on the APIM 3.7 announcement post [https://www.gravitee.io/post/gravitee-io-api-platform-3-7](https://www.gravitee.io/post/gravitee-io-api-platform-3-7)

[https://docs.gravitee.io/apim/3.x/apim_publisherguide_api_primaryoner_mode.html](https://docs.gravitee.io/apim/3.x/apim_publisherguide_api_primaryoner_mode.html)
and should be
[https://docs.gravitee.io/apim/3.x/apim_adminguide_users_and_groups.html](https://docs.gravitee.io/apim/3.x/apim_adminguide_users_and_groups.html)

**Comment by tiffanymarchi** [comment]
Done!
