### ISSUE TITLE
[management] Can't update a dynamic dictionary

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#6043]
It seems impossible to update a dynamic dictionary after it has been created. The update button remains disabled.

### Expected Behavior
It should be possible to update the dictionary.

### Current Behavior
The update button remains disabled.

![image](https://user-images.githubusercontent.com/5955401/131084476-0f7c5588-2974-4f95-bcc2-e2ce3353c255.png)

### Steps to Reproduce (for bugs)

Create a dynamic dictionary, save it, browse to another page (like home page for instance) then go back to the dictionary you created. Make a change and try to update.

### Your Environment
* Version used: 3.10.1 (3.10.x branch)

**Comment by LiliaEn** [comment]
Tested on 3.10.x
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Works as expected.
