### ISSUE TITLE
[management] Wrong log audit date for refresh dictionary events

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#6045]
The date of the log generated for each refresh of a dynamic dictionary seems not good.

### Expected Behavior
The log date should correspond to the date of the refresh of the dynamic dictionary.

### Current Behavior
The same log date is reused each time the dictionary is refreshed.

![image](https://user-images.githubusercontent.com/5955401/131088811-8ad33476-2ea5-45f4-bf96-e6012b111bc5.png)

### Possible Solution
Use the date of the dictionary refresh as log date.

### Steps to Reproduce (for bugs)
Create a dynamic dictionary with the following information:

1. - Http url: https://api.gravitee.io/echo
2. - Jolt transformation: 

```json
[
  {
    "operation": "shift",
    "spec": {
      "headers": {
        "*": {
          "$": "[#2].key",
          "@": "[#2].value"
        }
      }
    }
  }
]
```
3. Start the dictionary.
4. Go to the environment audits and check the log dates.

### Your Environment
* Version used: 3.10.1 (3.10.x branch)

**Comment by LiliaEn** [comment]
Tested on 3.10.x
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Works as expected.
