### ISSUE TITLE
[Investigation] - log system for policies and flow

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6049]
### Data to log
- request (header/body/path/method)
- flows executed - input/output
- policies executed - input/output

### Questions to investigate
- where should we store logs for this specific need ? 
- What's retention duration ? 
- Can user clear logs from UI ? 
- Logs export mode ? 
- Which filters are needed ?

### UX perspective ?
- How could we present them ? 
- How should we present them : specific colored theme for flows/policies ?

**Comment by marcambier** [comment]
I close this ticket as this has been implemented with "debug mode" feature
