### ISSUE TITLE
[policy] [jwt] [gateway] [management-ui] [management-api] Should be able to administrate gateway keys from UI

### ISSUE THREAD

**Issue by blackfich** [gravitee-io/issues#605]
It should be possible to administrate the gateway keys for JWT policy from the management UI rather than using the gravity.yml file

### Expected Behavior
Management UI should offer a global admin page (like the one for gateway metadata) to administrate the gateway keys. This would avoid having to manage the YAML file as well

### Current Behavior
Currently gateway keys are stored in the gravity.yml file, which makes it harder to maintain, especially when the gateway is clustered.

### Possible Solution
Provide a page to administrate the gateway keys, on the same level and idea of the metadata page.

### Context
We are going to have several instances of the gateway in production behind a load balancer, and we would like to avoid to have to maintain duplicated gravity.yml, especially if we need to add new keys.

### Your Environment
* Version used: 1.6.1
* Browser Name and version: Firefox 53.0.2
* Operating System and version: CentOS 7

**Comment by brasseld** [comment]
Hi,

You can put public key in the JWT policy itself:

<img width="587" alt="capture d ecran 2017-05-23 a 14 19 44" src="https://cloud.githubusercontent.com/assets/133094/26353918/de79964e-3fc2-11e7-8a73-bf2c5c5fab3d.png">

An other options is to use API properties:

<img width="583" alt="capture d ecran 2017-05-23 a 14 20 45" src="https://cloud.githubusercontent.com/assets/133094/26353984/0cb9d30c-3fc3-11e7-93a0-a5eb453c7b7a.png">

<img width="1430" alt="capture d ecran 2017-05-23 a 14 21 21" src="https://cloud.githubusercontent.com/assets/133094/26353990/11eef1ae-3fc3-11e7-8522-cb57b54e5299.png">

**Comment by blackfich** [comment]
Hi,

yes I know that I can use the GIVEN_KEY, but as we are planning to have many API exposed, we would rather use the GATEWAY_KEY to avoid retyping them.

The second option is nice indeed and is quite close to the enhancement proposal. Maybe we could do the same with the metadata, that way we would have keys at gateway level (with something like `{#metadata['key-name']}`

Regards

**Comment by brasseld** [comment]
The problem with metadata is that they were initially provided only for `portal` purpose.

You can imagine that `metadata` are entities only for management / portal where `properties` are defined for gateway runtime.

I understand your concern. Finally, we should have to provide some kind of general properties globally scoped and not only properties at a single API level.

Right ?

**Comment by blackfich** [comment]
Yes, that's exactly what I had in mind

**Comment by mikexd91** [comment]
hi i am still not very clear what does metadata actually do in the portal, can somebody enlighten me, thanks

**Comment by NicolasGeraud** [comment]
hi @mikexd91 

metadata provide a way to inject key/value in the portal. Currently you can add metadata in your documentation.

A use case is a homepage template using metadata. You can administrate those metada globally or per api.

we plan to also display metadatas in the portal.

**Comment by NicolasGeraud** [comment]
it's a little bit hidden, but it's in the documentation 😄 
https://docs.gravitee.io/apim_publisherguide_publish_documentation.html

```
You can access to your api data on your api’s documentation by doing so: ${api.name} or ${api.metadata['foo-bar']}
```

**Comment by mikexd91** [comment]
@NicolasGeraud  oh i see. I think it should be helpful for others to note that you can only see the output when you navigate to the API gallery, choose your API and click on the documentation. Because even after previewing and saving the document it wont reflect the value of the metadata.
<img width="909" alt="screenshot" src="https://user-images.githubusercontent.com/12381541/27952791-2260d920-633c-11e7-8744-25954a0c3ef3.png">


<img width="844" alt="screenshot" src="https://user-images.githubusercontent.com/12381541/27952804-29febb16-633c-11e7-81e1-1a0f4d0b2a47.png">


<img width="1128" alt="screenshot" src="https://user-images.githubusercontent.com/12381541/27952825-3f635278-633c-11e7-82f3-d76fa58a01ad.png">

**Comment by brasseld** [comment]
IMHO, this is an issue and you must be able to see metadata at the management side also.

**Comment by NicolasGeraud** [comment]
I'm agree with @brasseld . 

@mikexd91 could you please report this as a bug ?

**Comment by brasseld** [comment]
No more relevant
