### ISSUE TITLE
[Console] 500 error when importing definition of an API, null pointer exception

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#6052]
When the API provided from customer, tried to import in the gravitee console, there were issues with the "flow_mode" field, below is how to overcome them:

Steps to Reproduce (for bugs)
remove/change the value in the "flow_mode" to uppercase;
import the API;
import the API in the API console;
open the management API CLI, and get the logs from the gravitee.log, where we can see the null pointer exception the customer explained in the ticket;

[export api supervision-gateway rec (4).txt](https://github.com/gravitee-io/issues/files/7067957/export.api.supervision-gateway.rec.4.txt)

Stacktrace, from the issue:
[stacktrace.txt](https://github.com/gravitee-io/issues/files/7068006/stacktrace.txt)

Your Environment
Version used: 3.5.10 and 3.5.18
Browser Name and version: Chrome
Operating System and version: Windows10 , Docker Desktop

**Comment by phiz71** [comment]
Not able to reproduce in 3.5.20.
