### ISSUE TITLE
[management] Remove GraviteeContext from services

### ISSUE THREAD

**Issue by gcusnieux** [gravitee-io/issues#6071]
Since we add multi-env features, we use an GraviteeContext based on a thread local variable

Since the multi-env feature, we use the "GraviteeContext" class based on a thread local variable to pass the organization id, the environment id....

For example
- when we synchronize an API we must load the context from the API.
- apis are not well indexed 
- subscriptions never closed

**Comment by marcambier** [comment]
command used for GraviteeContext usages list : `grep -Ril --include \*.java graviteecontext * | grep "src/main" | grep -v "rest/resource"`

**Comment by ppgravitee** [comment]
@LiliaEn & @RubenMMSantos I closed this one has it needs a full non regression test that will be done before the release with regression pack, be careful (same for #6666)
