### ISSUE TITLE
[management] use liquibase to run mongo scripts

### ISSUE THREAD

**Issue by gcusnieux** [gravitee-io/issues#6075]
The goal is to used liquibase to manage mongodb migration scripts.

 - Improve scripts management
 - Have informations when we have customers with migrations errors
 - Simplify migration guide

Ask cockpit team, it seems to be already integrated 

TODO:

- [ ] Validate the non conflict with the [upgrader framework under development](https://github.com/gravitee-io/gravitee-api-management/pull/1407)
- [ ] Check that time consuming scripts will not cause problems with kube deployments
- [ ] Work on setup (liquibase+mongo)
- [ ] Validate that what cannot be done with an upgrader, can be done with the future json syntax
- [ ] Migrate th scripts already on master for next versions
- [ ] Analyze the behavior with documentdb

**Comment by Okhelifi** [comment]
✅ Work on setup (liquibase+mongo)
We have something working on the branch `spike/liquibase-mongodb`

**Comment by Okhelifi** [comment]
❌  Migrate the scripts already on master for next versions
- I tried to migrate `audit-set-environmentId-organizationId.js` in a liquibase changeset and I'm not sure that it would be so easy. 
- Running the script from a liquibase changeset is not something possible and I'm even not sure that it's a good idea.
- I think that liquibase is a good solution for the simple changes. If we want to do multidocument queries using aggregations or something else I would keep using the js scripts.

**Comment by Okhelifi** [comment]
❌ Check that time consuming scripts will not cause problems with kube deployments

NB: I followed this [slab page](https://gravitee.slab.com/posts/how-to-test-and-deploy-apim-on-minikube-kubernetes-7kauhtjx) to run locally APIM using kubernetes.
If you want to do it you will just have to build locally the docker images 
Then you can add a pullPolicy with never in your values.yml 
Finally you can copy the image in minikube using `minikube image load graviteeio.azurecr.io/apim-management-api:liquibase` and start APIM.

Conclusion: 
If we decide to integrate liquibase to the application start we will have some problems.

![Screenshot 2022-05-30 at 11 10 33](https://user-images.githubusercontent.com/25704259/170962651-8d7c16bf-47ea-40df-82b7-c0fe242e263b.png)

![Screenshot 2022-05-30 at 11 04 53](https://user-images.githubusercontent.com/25704259/170962847-737b45a6-cdbb-4591-84ec-fb4d94b47e53.png)

![Screenshot 2022-05-30 at 11 09 26](https://user-images.githubusercontent.com/25704259/170962725-4476bc7c-4f6a-426e-9708-459c2e81334d.png)

We will certainly have to find a solution to run liquibase in a dedicated init container 🤷🏼

**Comment by Okhelifi** [comment]
Analyze the behavior with documentdb

--> If we decide to add liquibase in APIM I would like that this point is checked in a dedicated subtask. I don't have access to documentdb for the moment.

**Comment by Okhelifi** [comment]
Liquibase will not be the good tool to run our database update. Maybe we can check if it's possible to run mongo scripts from an upgrader.
