### ISSUE TITLE
[Cockpit] Invalid CA on UI can't register new installation

### ISSUE THREAD

**Issue by YoranSys** [gravitee-io/issues#6086]
When I follow cockpit guide register a new instance, my AM instance failed to communicate with cockpit :

```java
gio_am_management | Caused by: sun.security.validator.ValidatorException: TrustAnchor with subject "CN=cockpit-controller.gravitee.io" is not a CA certificate
```
It's seem that the provided CA (left) from UI is not the good one, the real CA chain is different (right).
![image](https://user-images.githubusercontent.com/11197007/131968652-82cecc6a-4423-4b9b-bd5f-7a0e73a538ad.png)

**Comment by brasseld** [comment]
Hi @YoranSys 

Can you try by adding this env variable:

```
    - name: JAVA_OPTS
      value: "-Djdk.security.allowNonCaAnchor=true"
```

Regards,

**Comment by YoranSys** [comment]
Hi @brasseld ,
With `allowNonCaAnchor` it's work like a charm, it would be cool to have this trick on Cockpit UI 
Thank you,

**Comment by brasseld** [comment]
Hi @YoranSys 

We have updated the certificate on the server. Could you have an other try by removing this env var ?

Regards,

**Comment by YoranSys** [comment]
@brasseld it's ok with the updated certificate and without the env var  :tada: 
Regards,
