### ISSUE TITLE
[portal] Simplify the navigation

### ISSUE THREAD

**Issue by lauthieb** [gravitee-io/issues#609]
Simplify the navigation and internal links by removing the hash prefix "#!" in URLs.

### Expected Behavior

When we navigate to a page, we don't have the hash prefix.

### Current Behavior

We have the hash prefix in URLs.

### Possible Solution

Remove the HTML5 mode in management and portal modules.

**Comment by brasseld** [comment]
Hi @lauthieb what about this issue ?

**Comment by lauthieb** [comment]
Hi, I think it will be difficult to simplify the navigation because of the route url "/management" and the endpoint "/management" for the rest API...
