### ISSUE TITLE
docs: add how to configure a production-ready AM environment

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#6106]
With security best practices same as : 

https://docs.gravitee.io/apim/3.x/apim_how_to_configuration.html

**Comment by leleueri** [comment]
You may have to mention settings introduced by this issue https://github.com/gravitee-io/issues/issues/6121

**Comment by leleueri** [comment]
Review OK, but we should wait the release of AM 3.10.3 before merging to avoid publication of this documentation that contains description of the #6121 as the rebase branch is master
