### ISSUE TITLE
[console] Organization Settings get reinitialized after changing Authentication configuration.

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#6114]
Changing Authentication configuration as enabling/disabling "Show login form on management console", Organization -> Settings got reinitialized

### Steps to Reproduce (for bugs)

1. In UI Console, in Organization Settings, add a new Authentication provider (ie keycloak)
2. In Organization Settings -> Settings , change any value and save
3. Revert back to Organization Settings -> Authentication , and disable "Show login form on management console"
4. Revert back to Organization Settings -> Settings , all changed fields got reinitialized

Linked to https://github.com/gravitee-io/issues/issues/6009

### Your Environment

* Version used: 3.10.1
* Browser Name and version:
* Operating System and version:

**Comment by RubenMMSantos** [comment]
Issue confirmed as fixed.

- [ ] Steps to reproduce were followed and issue could not be reproduced. 
- [ ] As extra testing, various values were changed in settings in order and issue was not reproducible
- [ ] Several combinations of values were changed in settings in order and issue was not reproducible
