### ISSUE TITLE
[gateway][oauth-am-resource] memory leak

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#6119]
In APIM 3.10, when a OAuth2 plan use the AM resource, there is a memory leak due to this line : 

https://github.com/gravitee-io/gravitee-resource-oauth2-provider-am/blob/master/src/main/java/io/gravitee/resource/oauth2/am/OAuth2AMResource.java#L164

It seems that the hashCode of Verts.currentContext() changes between two calls.

**Comment by phiz71** [comment]
Will be closed with #6176
