### ISSUE TITLE
[policy][data-logging-masking] datas are no longer masked

### ISSUE THREAD

**Issue by RachidKelidou** [gravitee-io/issues#6122]
Since APIM 3.10, a bug has been introduced by #1581 

https://github.com/gravitee-io/gravitee-policy-data-logging-masking/blob/b7f9cab6a734586b9782ea2f58ec4f06c414036e/src/main/java/com/graviteesource/policy/dataloggingmasking/DataLoggingMaskingPolicy.java#L178 

It's always false, so we are never masking anything

**Comment by RubenMMSantos** [comment]
Hey @marcambier any info if this ticket can be test and how? thanks

**Comment by LiliaEn** [comment]
@aelamrani @mouligno This ticket cannot be tested in 3.10.x environment since it is related to EE policies. Moving it to blocked until a we will decide how to proceed.
