### ISSUE TITLE
[management] migrate postman to cypress

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#6141]
We have some postman tests in APIM [see here](https://github.com/gravitee-io/gravitee-api-management/tree/master/gravitee-apim-rest-api/postman)

The idea is to migrate them (at least the most relevant) to cypress.

## Subject to discuss:
- Mutualize some functions ? -> Maybe create *Actions class to have simple actions like ApiAction.createApi()
- Mutualize data ? -> Maybe create a data folder with some json

We may not necessarily migrate tests case on a one to one basis but the idea is to bring real value. (and not having the same result as postman)
I propose to start with APIs test suite (create, delete, update)
so the next will be an e2e one to be able to test the gateway too

**Comment by RubenMMSantos** [comment]
have a meeting scheduled with QA team on 23rd of November to discuss this ticket

**Comment by mouligno** [comment]
Moved to ready to release since no decision made yet from QA team
