### ISSUE TITLE
[management] remove ApiKeys deprecated endpoints

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#6144]
API keys endpoints located in ApiKeysResource.java are deprecated since 3.12.

And some other endpoints located in : ApiSubscriptionResource & ApplicationSubscriptionsResource.

See 3.12 update note : https://github.com/gravitee-io/release/tree/master/upgrades/3.x/3.12.0

Now they can be removed.

**Comment by mouligno** [comment]
LGTM
