### ISSUE TITLE
[management ui] Documentation page configuration imported from external source can not be edited 

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#6149]
When creating a Documentation page as imported from external source such as GitLab or GitHub, it is no more possible to edit the initial configuration as from "External Source" in 3.10. compared to 3.5.

## Edit 2021-10-27

There are two bugs:
- when setting an external source, if you navigate to another page, then come back to your fetch, form is not displayed
- if you set a fetcher, then click an another one, come back to the configured fetcher will display an empty form (also present in 3.5.x)

3.10.1 : 
<img width="1515" alt="Capture d’écran 2021-09-10 à 18 48 46" src="https://user-images.githubusercontent.com/79909781/132890330-ac148cfa-420d-4b89-a642-d0c299b49740.png">

3.5.18 : 
<img width="1474" alt="Capture d’écran 2021-09-10 à 18 52 31" src="https://user-images.githubusercontent.com/79909781/132890524-21e3f45c-4436-46ae-8ee3-8fbf2eddd273.png">

### Steps to Reproduce (for bugs)

1. In UI Console, create a Documentation page as imported from external source such as GitLab or GitHub and save
2. Go to "EXTERNAL SOURCE", you need to set the whole configuration again as the previous configuration is no more visible/editable
3. In 3.5.18, the initial configuration is correctly displayed

### Your Environment

* Version used: 3.10.1 
* Browser Name and version:
* Operating System and version:

**Comment by mouligno** [comment]
LGTM
