### ISSUE TITLE
chore(deps): Security upgrade gravitee-bom from 1.0 to 2.0

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#6153]
See https://github.com/gravitee-io/issues/issues/6151

**WARNING : We can't update the gravitee bom version directly, some code changes must be done**

- Update SecurityConfiguration with setAllowedOriginPattern : 
```
When allowCredentials is true, allowedOrigins cannot contain the special value \"*\" " +
							"since that cannot be set on the \"Access-Control-Allow-Origin\" response header. " +
							"To allow credentials to a set of origins, list them explicitly " +
							"or consider using \"allowedOriginPatterns\" instead.
```
- Upgrade Spring-R2DBC to the latest 1.3.x (some code changes may be done)
- It seems to have an issue with the classloader of Thymeleaf
- ...

**Comment by leleueri** [comment]
As BOM as been upgraded thanks to #6695 and #6696, this issues only deal with the upgrade of spring data r2dbc to 1.4.0
