### ISSUE TITLE
[console] Portal Settings get reinitialized after changing Portal Authentication configuration

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#6154]
Changing Portal Authentication configuration as enabling/disabling "Force authentication to access portal",  makes Portal Settings get reinitialized

### Steps to Reproduce (for bugs)

1. In UI Console Settings -> Settings (Portal), change any value (ie "Company name") and Save
2. Go to Settings -> Authentication , and enable/disable "Force authentication to access portal"
3. Revert back to Settings -> Settings , all changed fields got reinitialized

linked to #6009 and #6114 

### Your Environment

* Version used: 3.10.1
* Browser Name and version:
* Operating System and version:

**Comment by mouligno** [comment]
This behavior can also be reproduced on all autosave checkbox in UI Console > Settings 
- Client registration
- API Portal informations

**Comment by LiliaEn** [comment]
Tested in 3.10.X env version 3.10.4
Browser: Chrome Version 94.0.4606.81, macOS Big Sur v11.6
Checked if Portal Settings updates are correctly displayed after enabling/disabling autosave checkboxes from:
 - Authentication
 - Client registration
 - API Portal informations
