### ISSUE TITLE
[management-api] Jetty server should be set to http, https or both via yml file

### ISSUE THREAD

**Issue by blackfich** [gravitee-io/issues#616]
Jetty server should be more configurable than it is now. One should be able to enable http only, https only, http and https. Each port should be configurable. Also for https the keystore and truststore should be configurable via the gravitee.yml file (along with passwords)

### Expected Behavior
All settings for jetty should be exposed in the gravity.yml file. Also it should be possible to specify if the server should handle only http, only https or both simultaneously

### Current Behavior
Currently only a few settings are exposed in the gravity.yml. For instance the secure port is hardcoded in `JettyServerFactory` (`httpConfig.setSecurePort(8443);`)

### Possible Solution
Expose more settings in the gravity.yml file. Map them in the `JettyConfiguration` class.
Maybe we could use a list of keys matching the `ServerConnector`
```yml
jetty:
  connectors:
    - http:
      port: 8080
    - https:
      port: 443
```
`ServerConnector` could then be created and added only if present, thus covering the http only, https only, or http and https simultaneously.

### Context
We have to deploy gravitee.io in an environement where https only is enforced between VMs

### Your Environment
* Version used: 1.6.1
* Browser Name and version: Firefox
* Operating System and version: CentOS 7

**Comment by brasseld** [comment]
Management-api supports both HTTP and HTTPS
