### ISSUE TITLE
[Portal] Application Metadata Format dropdown menu

### ISSUE THREAD

**Issue by patelami** [gravitee-io/issues#6168]
The dropdown for the Application Metadata is hidden and not very easy to scroll 

### Expected Behavior
I should see the dropdown in the form when I click on the Format dropdown

### Current Behavior
Currently, User have to scroll at a specific place to see all the value in the dropdown 

https://user-images.githubusercontent.com/14215437/133161834-dc21a00f-d79c-4df7-ade0-569fae88382e.mov

**Comment by gaetanmaisse** [comment]
Closing as it has been fixed for a couple of months
