### ISSUE TITLE
Packaging improvements

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6170]
As a developer, I want to be able to package and deploy any branch (APIM / Gateway) in order to test specific versions.

### Technical steps 
- Package APIM & Gateway branch using MAven
- Build Docker images with required plugins
- Deploy on Azure using CI
- Install this images on cluster

**Comment by brasseld** [comment]
@phiz71 could we reuse this for creating a specific version of the gateway?

For example, bridge gateway does not require any of the policies, resources, ... so I would like to build a new docker image, something like 

`graviteeio/apim-gateway-bridge:3.15.x` or `graviteeio/apim-gateway:3.15.x-bridge`
