### ISSUE TITLE
Missing feedback error message on UI when updating context path

### ISSUE THREAD

**Issue by patelami** [gravitee-io/issues#6171]
### Expected Behavior
As a user, I should see error message when I try to edit context path which already exists

### Current Behavior
We do not see any error message when we try to replace context path with already existing context path

### Steps to Reproduce (for bugs)
prerequisite: Search and  verify on the nightly environment there is pre-existing API with context path `/echo `

1. Go to API page and select API
2. Go to Proxy > Endpoint > General (gateway context path)
3. Update the context path to /echo

https://drive.google.com/file/d/13msZujO3Wbl630kon2ScfTCTfVBhCHaG/view?usp=sharing

**Comment by mouligno** [comment]
Not a bug, context-path is the entrypoint
