### ISSUE TITLE
I added a new path to the API. For example /monthly-payments. Even if I call it with {domain}/api/monthly-paymentsXXXXX it takes the request in. Why are these paths pretending to be equal? (monthly-paymentsXXXXX, monthly-payments). Shouldn't it give an error when I use monthly-paymentsXXXXX?

### ISSUE THREAD

**Issue by aliFetvaci61** [gravitee-io/issues#6177]
I added a new path to the API. For example /monthly-payments. Even if I call it with {domain}/api/monthly-paymentsXXXXX it takes the request in. Why are these paths pretending to be equal? (monthly-paymentsXXXXX, monthly-payments). Shouldn't it give an error when I use monthly-paymentsXXXXX?
@brasseld @NicolasGeraud @aelamrani

**Comment by brasseld** [comment]
Hi @aliFetvaci61 ,

First, please do not ping everyone when you are submitting an issue.

Regarding your question, can you tell me if you're running the new Design Studio to define your path ?
If that is the case, from the flow's property, you can change the operator and move from `starts_with` to `equals`  

<img width="1420" alt="Capture d’écran 2021-09-22 à 09 02 23" src="https://user-images.githubusercontent.com/133094/134297694-3f1e4f61-172b-43f4-91a6-083c5042b5ba.png">

**Comment by aliFetvaci61** [comment]
I am not using design studio. I am using path based. Where is similar to this feature you specified at path based style? Or does not  path based have this feature?

**Comment by gaeljw** [comment]
I'm having a similar scenario, using design policy (Gravitee 3.15.5), where having a plan with a flow for `/xxx` still allow clients to call `/yyy` and bypass all the policies.
