### ISSUE TITLE
[APIM - APIs -  Plans] Unable to add "Rate Limiter" when creating a plan within API details page

### ISSUE THREAD

**Issue by RubenMMSantos** [gravitee-io/issues#6196]
User is unable to add "Rate Limiter" policy when creating a new plan from the API details page. There is also an error in the console but not sure if it is related to the issue.

### Expected Behavior
User should be able to apply "Rate Limiter" policy to the plan when creating it via API details page

### Current Behavior
User is unable to apply "Rate Limiter" policy to the plan when creating it via API details page

### Steps to Reproduce (for bugs)
Please watch the following video:

https://user-images.githubusercontent.com/14215437/133782474-5b8cac0c-d6eb-4893-b323-6f5a0dee7b57.mov

If the video does not 

work, please use the following link:
https://drive.google.com/file/d/1Wu_3Pz4nSpmJWgwZyyUNBQHYoJmrsmXJ/view?usp=sharing

### Context
Trying to apply "Rate Limiter" when creating the actual plan since the option to do so is displayed in the journey

### Your Environment
Version used: nightly envir v3.12.0
Browser Name and version: Google Chrome, v93.0.4577.82
Operating System and version: MacOS BigSur, v11.5.2 (20G95)

**Comment by mouligno** [comment]
@RubenMMSantos still accurate in 3.15+ ?
