### ISSUE TITLE
[management] Environments independants API Keys

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#6199]
Currently, when an API Key is used in one environment, it can't be used nomore in another environment.
We have to make it environment independant.

For example :
On environnement "ENV1", application "APP1" has subscribed to Api "API1" with Api Key "my-custom-api-key"
On environnement "ENV2", application "APP2" **CAN** subscribe to Api "API2" with Api Key "my-custom-api-key"

**Comment by gaetanmaisse** [comment]
Closing since the original ticket has been closed after a discussion with the customer.
