### ISSUE TITLE
[portal] URL for API's pictures should not contain protocol, hostname and port

### ISSUE THREAD

**Issue by blackfich** [gravitee-io/issues#620]
URL for API's pictures should not contain the hostname and port.

When behind an reverse proxy (NGINX) we actually see the local url of the image instead of the external one.

```html
<img ng-src="http://localhost:9001/management/apis/3e0e10aa-71f0-4b6f-8e10-aa71f0fb6f4a/picture?hash=-1874166308" alt="api-logo" src="http://localhost:9001/management/apis/3e0e10aa-71f0-4b6f-8e10-aa71f0fb6f4a/picture?hash=-1874166308">
```

### Expected Behavior
```html
<img ng-src="/management/apis/3e0e10aa-71f0-4b6f-8e10-aa71f0fb6f4a/picture?hash=-1874166308" alt="api-logo" src="/management/apis/3e0e10aa-71f0-4b6f-8e10-aa71f0fb6f4a/picture?hash=-1874166308">
```

### Current Behavior
```html
<img ng-src="http://localhost:9001/management/apis/3e0e10aa-71f0-4b6f-8e10-aa71f0fb6f4a/picture?hash=-1874166308" alt="api-logo" src="http://localhost:9001/management/apis/3e0e10aa-71f0-4b6f-8e10-aa71f0fb6f4a/picture?hash=-1874166308">
```

### Possible Solution
Images URL should use the `baseURL` as defined in the constants.json

### Steps to Reproduce (for bugs)
1. in `/etc/hosts` associate gravitee-ui to 127.0.2.1
2. Install management-ui and management-rest-api on the same machine
3. Install NGINX and set it up to serve the management-ui pages for 127.0.2.1 and server_name gravitee-ui and RP /management/ to the rest api
4. Connect to gravitee-ui/ and check any API image, URL is pointing to localhost, where it should be without hostname, port and protocol.

### Context
We want to secure connection to the management-rest-api with HTTPS. For this we put it behind a reverse proxy (namely NGINX). The management-rest-api is only binded to localhost and the reverse proxy routes all requests to /management/... to it.

### Your Environment
* Version used: 1.6.1
* Browser Name and version: Firefox
* Operating System and version: CentOS 7

**Comment by brasseld** [comment]
Hi @blackfich,

I suppose you are using proxy_pass module from nginx.
We are looking for x-forwarded-xxxx headers to rebuild final URL.
Did you have a try to set them using nginx configuration ? something like:
```
proxy_set_header X-Forwarded-For $remote_addr;
```

**Comment by blackfich** [comment]
Hi @brasseld,

after fidling a lot with Nginx settings, I found this solution to work : 

```
location /management/ {
        proxy_pass              http://localhost:9001/management/;
        proxy_set_header        Host                    $host:443;
        proxy_set_header        X-Forwarded-Proto       https;
}
``` 

Note : it won't work with `X-Forwarded-Host $host:443` as in this case the value is **URLEncoded** in the src and ng-src attributes of the image :

```html
<img ng-src="https://gexgwyui%3A443:443/management/apis/3e0e10aa-71f0-4b6f-8e10-aa71f0fb6f4a/picture?hash=-1874166308" alt="api-logo" src="https://gexgwyui%3A443:443/management/apis/3e0e10aa-71f0-4b6f-8e10-aa71f0fb6f4a/picture?hash=-1874166308">
```

**Comment by brasseld** [comment]
Sounds good as per:

https://github.com/gravitee-io/gravitee-management-rest-api/blob/master/gravitee-management-api-rest/src/main/java/io/gravitee/management/rest/provider/UriBuilderRequestFilter.java#L36

URL encoding is probably done by underlying component used by the management-api : Jersey

Can we consider this issue as closed ?

**Comment by blackfich** [comment]
Yes

**Comment by syedhassan** [comment]
@blackfich can you paste your configuration? How are you able to access gravitee behind nginx?

**Comment by syedhassan** [comment]
@blackfich I was able to solve my issue at https://github.com/gravitee-io/issues/issues/1292
