### ISSUE TITLE
[portal] Error message on login page

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#6203]
When using the force authentication setting:

![image](https://user-images.githubusercontent.com/89140082/133806890-567979ea-94a5-4fa7-9c73-1cf7348ba110.png)

from the console, and then trying to login from the portal, we are getting the following message as a response:

![image](https://user-images.githubusercontent.com/89140082/133805578-8b65eff1-f8bd-41b9-b40f-3414ca3ee497.png)

* Version used:
Your Environment
Version used: 3.10.0 
Browser Name and version: Chrome
Operating System and version: Windows10 , Docker Desktop

**Comment by mouligno** [comment]
LGTM
