### ISSUE TITLE
ApiKeyRepositoryWrapper does not implement all methods of ApiKeyRepository

### ISSUE THREAD

**Issue by alirezakhtm** [gravitee-io/issues#6208]
There is a problem when we compile Gravitee-Gateway project. This problem is about a class that named `ApiKeyRepositoryWrapper` this class does not implement all functions of interface `ApiKeyRepository`

This problem causes as follows error in compile process

````
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project gravitee-gateway-services-sync: Compilation failure
[ERROR] /mnt/00A4D2D2A4D2C974/vasl/gravitee-gateway/gravitee-gateway-services/gravitee-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/apikeys/repository/ApiKeyRepositoryWrapper.java:[31,7] error: ApiKeyRepositoryWrapper is not abstract and does not override abstract method findByKeyAndApi(String,String) in ApiKeyRepository
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :gravitee-gateway-services-sync
````

**Comment by alirezakhtm** [comment]
Hi @brasseld 

I found this bug on gravitee-gateway. The Gravitee Team added two functions into interface class `ApiKeyRepository` but the implemented class `ApiKeyRepositoryWrapper` didn't implement these two method, therefore in compile time we have problem. 

These methods are:

```
public List<ApiKey> findByKey(String s) throws TechnicalException { }

public Optional<ApiKey> findByKeyAndApi(String s, String s1) throws TechnicalException { }
```

I solved them temporary to make code to work. It is available in PR [https://github.com/gravitee-io/gravitee-gateway/pull/752](https://github.com/gravitee-io/gravitee-gateway/pull/752)

**Comment by brasseld** [comment]
I just ask the team to review the PR.

We will get back to you asap.

**Comment by alirezakhtm** [comment]
Thank you

**Comment by marcambier** [comment]
On master branch, ApiKeyRepositoryWrapper already implements findByKey and findByKeyAndApi.
We don't need to change those implementations, as it fits the new keys behavior, which has been recently refactored.

Maybe you should try to compile again, using the "-U" maven argument, to ensure your dependencies are up to date.

**Comment by marcambier** [comment]
I close the ticket as @alirezakhtm confirmed it's fixed
