### ISSUE TITLE
[ratelimit policy] Error 429 is being returned while using two Rate Limit Policies.

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#6218]
-Description
An API has the following policies setup:
A Rate Limit is defined at the path level / (Strict mode, 10000 Max requests (static) / 1min)
A Rate Limit at the Plan level (Non-Strict mode, 300000 Max requests (static) / 15 mins)
A Quota at the Plan level (Non-Strict mode, 6,000,000 Max requests (static) / 1 day) 

- Current Behavior
After testing the Rate Limit Policy in JMeter the error 429 is returned at range of around 4000-6000 requests.

- Expected Behavior
Error 429 should be returned only after reaching 10000 request/1 minute and not below.

- Steps to Reproduce (for bugs)
*Echo API is used for testing purposes. The zip file includes the JMeter test and the export of the text Echo API  [Echo 429 Error.zip](https://github.com/gravitee-io/issues/files/7196713/Echo.429.Error.zip)

1. Import the attached API.
2. In Design check the two policies (Rate Limit and Quota) on the Plan level and one Rate Limit Policy for the whole API Flow Level.
3. Run the JMeter Script which is in the attached zip file (Infinite number of calls for the duration of 60 seconds).

![image](https://user-images.githubusercontent.com/57534152/134028489-03d3e297-2189-41bc-a2c2-46e70f43a9a7.png)

![image](https://user-images.githubusercontent.com/57534152/134028532-afbf4a28-d983-4b09-94e8-fcbbce778155.png)

4. When you disable the Rate Limit Policy at the Flow Level and run the test again there is no 429 error.

- Environment
Version used: Gravitee 3.5.18, Gravitee is installed in Docker

**Comment by ytvnr** [comment]
To resovle this, you can just add a `key` in your Rate Limit configuration. 

If `key` is not specified, the rate limiting counter will be indentified by the plan/subscription pair only. So the counter is shared across both policies. ([see documentation](https://docs.gravitee.io/apim/3.x/apim_policies_rate_limiting.html#rate_limit))
