### ISSUE TITLE
Multiple Dependencies in POM.xml (gravitee-gateway-standalone-container)

### ISSUE THREAD

**Issue by alirezakhtm** [gravitee-io/issues#6220]
There are some multiple dependencies in pom.xml file of gravitee-gateway-standalone-container. These dependencies are:

```
<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-transport-native-epoll</artifactId>
    <classifier>linux-x86_64</classifier>
</dependency>

<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-transport-native-kqueue</artifactId>
    <classifier>osx-x86_64</classifier>
</dependency>
```

These repeated dependencies make problems when we want to run the application in Debug mode.

**Comment by brasseld** [comment]
Hi @alirezakhtm 

Why those are making difficult to run in debug mode ?

Can you explain a bit please.

Regards,

**Comment by alirezakhtm** [comment]
Hi @brasseld 

when I want to run application in debug mode, I receive this message and process stopped:

```
Some problems were encountered while building the effective model for io.gravitee.gateway.standalone:gravitee-gateway-standalone-container:jar:3.12.0-SNAPSHOT
'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: io.netty:netty-transport-native-epoll:jar:linux-x86_64 -> duplicate declaration of version (?) @ line 389, column 21
'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: io.netty:netty-transport-native-kqueue:jar:osx-x86_64 -> duplicate declaration of version (?) @ line 395, column 21
It is highly recommended to fix these problems because they threaten the stability of your build.
For this reason, future Maven versions might no longer support building such malformed projects.

```

**Comment by brasseld** [comment]
Hum.... I'm wondering why we do not encounter this issue from our CI.

Can you tell me:
- Branch you are building
- Maven version
- JDK version
- OS

**Comment by alirezakhtm** [comment]
I'm working on master branch, maven version is 3.6.3, JDK 11, OS Ubuntu 20.04

**Comment by alirezakhtm** [comment]
I sent a PR to solve this problem. 
[https://github.com/gravitee-io/gravitee-gateway/pull/758](https://github.com/gravitee-io/gravitee-gateway/pull/758)

**Comment by alirezakhtm** [comment]
Dear @brasseld
 
Indeed, I found another bug and want to register the other issue, but if you have enough time now, we can speak about it here. 
This problem is about `ApiKeyRepository` class.

**Comment by brasseld** [comment]
My problem with the proposed PR is that if we are removing those libraries, they would not be included anymore in the Gateway package, and we need them. So I'm sure the issue from somewhere else.

**Comment by alirezakhtm** [comment]
I don't think so. Because these dependencies twice repeated in this POM file. You can find them on 223-234 (line number) and 388-400 (line number). If we remove them from one place, it makes no difference for application. By the way, we have these dependencies in application.

**Comment by alirezakhtm** [comment]
Hi @brasseld,
I'm looking forward to hearing from you. Did you check it ?

**Comment by brasseld** [comment]
Hi @alirezakhtm 

Sorry for being late, and thanks for chasing.

you were right, I don't know how this move outside our radar.

Just accepted the PR, many thanks 👍

**Comment by alirezakhtm** [comment]
Merci beaucoup
