### ISSUE TITLE
[management] Cannot change logging configuration in some case

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#6221]
![Capture d’écran 2021-09-21 à 09 03 26](https://user-images.githubusercontent.com/1580262/134126234-fa3590d9-abed-4ae6-92f2-2fc10dd5a0cb.png)

### Steps to Reproduce (for bugs)

1. Configure logging on an API & save & deploy
2. Change the mode => Save button remain disabled
3. Update the condition and remove it & save => the changes are not saved despite the success message
4.

Version 3.10.3

**Comment by RachidKelidou** [comment]
duplicate #6282
