### ISSUE TITLE
[management] implement the same behavior on jdbc and mongo side for event properties

### ISSUE THREAD

**Issue by gcusnieux** [gravitee-io/issues#6229]
### Current Behavior
Currently when we `search` for an event with two properties :
 - on the mongo side it uses an `AND` between the properties
 - on the jdbc side it uses an `OR`

### Possible Solution
Choose same for both

**Comment by marcambier** [comment]
@mouligno We flagged this ticket as a "bug" ; can you prioritize it in the support backlog ?

**Comment by omatthewsgravitee** [comment]
Antoine said use Mongo behavior

**Comment by ThibaudAV** [comment]
see with @guillaumelamirand this bug is no longer relevant we can close
