### ISSUE TITLE
[Settings - Metadata] Unable to update an existing metadata value

### ISSUE THREAD

**Issue by RubenMMSantos** [gravitee-io/issues#6234]
When trying to update the value of an existing metadata, a CORS error is thrown (browser console displays a 403 error)

### Expected Behavior
I should be able to successfully update the value of an existing metadata

### Current Behavior
When trying to update the value of an existing metadata an error is displayed and i am sent to dashboard page with the "update metadata" popup displayed on top of the dashboard page

### Steps to Reproduce (for bugs)
Please refer to the video below
https://images.zenhubusercontent.com/61280156/29ab345a-62c6-4424-9789-0dff1b468987/screen_recording_2021_09_22_at_16_02_15.mov

if the above video does not work please refer to the following URL:
https://drive.google.com/file/d/1T1uWj8CTcXtnAX5hYGTq2elnSFc_TAOS/view?usp=sharing

### Context
I was trying to update the value of an existing metadata and was unable to.

### Your Environment

* Version used: "3.12.0-SNAPSHOT"
* Browser Name and version: google chrome, v93.0.4577.82
* Operating System and version: macOS Big Sur, v11.5.2

**Comment by mouligno** [comment]
@RubenMMSantos still accurate in 3.15+ ?

**Comment by mouligno** [comment]
couldn't reproduced in 3.15
