### ISSUE TITLE
[portal] "page not found" after Google authentication

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#6235]
When logging in, using the Google authentication service, this is the error:
"Oops, page not found" when authenticating, tries to login with google authentication, and after clicking on the logo on the left of the page, it works as expected (authenticated with the google acc.). 

Steps to Reproduce (for bugs)
Installing required docker version (tried with 3.10.3 and 3.5.18);
Setup the google authentication to try the issue;
When logged out from the portal, on the login page, this is the message:
![image](https://user-images.githubusercontent.com/89140082/135992359-f4e6663e-5ea6-4384-a724-1ec5e34b3a11.png)

After it, when authenticating with google acc. this is the error message:
![image](https://user-images.githubusercontent.com/89140082/134382667-fdb3c81f-b74e-4df7-91b2-fa169a73f5a5.png)

And finally, when clicked the logo button in the left corner of the page user redirected as expected (logged in in the portal):
![image](https://user-images.githubusercontent.com/89140082/134382992-747cb2b8-be46-4693-aaa9-44efe35c5c3f.png)

Version used: 3.10.3 and 3.5.18
Browser Name and version: Chrome
Operating System and version: Windows10 , Docker Desktop

**Comment by mouligno** [comment]
LGTM
