### ISSUE TITLE
Some color options that are difficult to click

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#6237]
There is a situation, when in settings->theme, and trying to pick/change color, the palettes in the menu are not shown properly:

![image](https://user-images.githubusercontent.com/89140082/134636629-bac9be9a-35ed-4a7f-b850-253d16c6dc27.png)

![image](https://user-images.githubusercontent.com/89140082/134636719-842eaa6d-1253-478d-af8b-36f4c82b1175.png)

Also, what I've noticed is that when changed the display (on a bigger monitor, the color palettes are shown as expected), no issue there:

![image](https://user-images.githubusercontent.com/89140082/134637022-741d3080-103e-40ed-8311-3fe63bbbffa0.png)

Version used:
Your Environment
Version used: 3.10.0
Browser Name and version: Chrome
Operating System and version: Windows10 , Docker Desktop

**Comment by gaetanmaisse** [comment]
Closing as it will be handled during the migration of this screen to Angular
