### ISSUE TITLE
Anonymize & Sanitize data dump

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6250]
The data dump use for performance testing and development should be anonymized first.

### Should contains : 
- 500+ APIs
- 1000+ Applications
- logs & analytics related to that kind of use

### Format
- MongoDB
- JDBC

### Anonymize 
- user info
- settings 
- dictionnaries

**Comment by phiz71** [comment]
Need to be discussed with @jgiovaresco and @gcusnieux
