### ISSUE TITLE
[Portal] API page list performance improvements

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6254]
Link to #5045

With a user having a lot of apis, the api list page can suffer of timeouts for the following reasons:
- The rest api offer a pagination mechanism but on the server side all apis (and all data around) are loaded, filtered in memory and then paginated.
- Some part of the code executed by the filteringService can be improved.
-- Ex: `filteringService.getTopApis` takes an api list in parameter but makes a `topApiService.findAll()`. Furthermore, the `topApiService.findAll()` method takes a mapper and a filter which both trigger a call to `apiService.findById()` for each api.
- On the api listing page, the UI makes several calls to /apis route:
-- `/apis?size=1&filter=ALL&promoted=true`
-- `/apis?size=4&-filter=ALL`
-- `/apis?page=1&size=6&filter=ALL&promoted=false`
-- `/apis?size=-1&filter=ALL`
- As the pagination is made in memory, with a lot of apis, these calls can be quite time consuming and resource intensive.

**Comment by LiliaEn** [comment]
Tested on the default environment version 3.15.0
Browser: Chrome Version 95.0.4638.69, macOS Big Sur v11.6

- [ ] Checked if All APIs page is loading in an appropriate time;
- [ ] Checked if Featured APIs page is loading in an appropriate time;
- [ ] Checked if Trending APIs page is loading in an appropriate time;
- [ ] Checked pagination on all pages;
- [ ] Navigated through different APIs pages and checked if the APIs list loads in an appropriate time;
- [ ] Exploratory testing;
