### ISSUE TITLE
[Portal] Category page list performance improvements

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6255]
Link to #5045

Portal categories page also suffers of latencies. The main reason is that all apis of the user are first retrieved (with all data, api by api) just to be able to calculate the number of apis for each category.
- A quick solution could be to retrieve the categories and then invoke a `apiService.countPublishedByUser(criteria)` method with category id in criteria (to be develop).

**Comment by marcambier** [comment]
@RubenMMSantos @LiliaEn 
Quick note on what can be impacted, for non-regression tests :
- in portal, categories page list display, and categories detail display
- apis in categories are visible according to :
  - connected user permissions
  - api published state
  - api public/private state
- apis count in the category card always match the number of apis displayed in the category

**Comment by LiliaEn** [comment]
Tested on the release-test environment version 3.14.0
Browser: Chrome Version 95.0.4638.69, macOS Big Sur v11.6
The following scenarios were covered:
- [ ] Create new categories and check that they are displayed in Portal
- [ ] Category page loads correctly
- [ ] Category details page loads correctly
- [ ] Add Apis to a certain category and check that they are displayed correctly in Portal
- [ ] Add unpublished APIs in a category and check they are not displayed in Portal
- [ ] Add multiple APIs in a category and check they are all displayed
- [ ] Remove an API from a category and check it is not displayed anymore
