### ISSUE TITLE
[Portal] Application page list performance improvements

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6256]
Link to #5045

Application page has difficulties to load when a user has lot of applications (note: at first glance this case is less likely).
- There is no pagination on this page
- A big amount of data is fetch for each application and contributes to bad performances when the user has permissions on a lot of applications (these are the same data loaded when accessing a single application : owner, group, ...).
- For each application the user has permission on, a rest call is made to get the number of subscriptions but a lot of data is retrieved to calculate this counter (api, plan, user, ...) and few of them are really useful

**Comment by LiliaEn** [comment]
[6953](https://github.com/gravitee-io/issues/issues/6953)
