### ISSUE TITLE
[APIM - Advanced search on APIs] No results when searching with categories that have at least 2 words

### ISSUE THREAD

**Issue by RubenMMSantos** [gravitee-io/issues#6264]
Given the new search functionality i should be able to search APIs by categories, but when doing so with any category that has at least 2 words (like "Showcase APIs" or "Open Data") does not return any results

### Expected Behavior
When searching for APIs by categories, i should get API results for any that have the category used for search.

### Current Behavior
when searching for APIs by categories, any categories with at least 2 words does not return any results

### Steps to Reproduce (for bugs)
1. go to https://nightly.gravitee.io/#!/environments/DEFAULT/apis/
2. click on any API
3. change the Portal categories to include one that has at least 2 words (like "Showcase APIs" or "Open Data") and SAVE your changes
4. go back to https://nightly.gravitee.io/#!/environments/DEFAULT/apis/
5. using the search bar type categories: Showcase APIs or categories: Open Data
6. notice there are no results displayed

### Your Environment
* Version used: 3.12.0-SNAPSHOT
* Browser Name and version: Google Chrome v93.0.4577.82
* Operating System and version: macOS Big Sur, v11.5.2 (20G95)

**Comment by RubenMMSantos** [comment]
issue re-tested and confirmed as fixed on APIM console

**Comment by LiliaEn** [comment]
tested and confirmed in APIM Portal
