### ISSUE TITLE
Advanced Search -> Name and Description are case sensitive

### ISSUE THREAD

**Issue by LiliaEn** [gravitee-io/issues#6265]
Steps to Reproduce 

Precondition: Add an API with the name "Echo Lilia" and description "This is a test API"

1. Go to https://nightly.gravitee.io/#!/environments/DEFAULT/apis/ or https://v3.nightly.gravitee.io/catalog/categories
2. Enter the following filter in the search field: `name: "echo lilia" `
3. Enter the following filter in the search field: `name: "Echo Lilia"`
4. Enter the following filter in the search field: `description: "this is a test api"`
5. Enter the following filter in the search field: `description: "This is a test API"`

Expected Behaviour
Name and Description should be case insensitive. Results should display for steps 2,3,4,5

Current Behaviour
Name and Description are case sensitive. Results are not displayed for steps 2 and 4.

Your Environment
Version used: 3.12.0-SNAPSHOT
Browser Name and version: Google Chrome v91.0.4472.114
Operating System and version: macOS Big Sur, v11.5
#2839

**Comment by RubenMMSantos** [comment]
issue re-tested and confirmed as fixed on APIM console

**Comment by LiliaEn** [comment]
tested an confirmed on APIM Portal
