### ISSUE TITLE
Getting internal endpoint in policy plugin

### ISSUE THREAD

**Issue by pmatulionis** [gravitee-io/issues#628]
Hello,

I am trying write my own policy plugin in gravity to support dynamic routing without specifying a host.
Basically my requirements are to be able to do this:
Match expression:
/instance/(.*)/(.*)

Redirect to:
/instance/{#group[0]}/{#group[1]}

So for e.g. I go to url: 

http://my-gravity-url/my-api-path/instance/b31593e6-dde2-4621-819f-dc1c2b1f6e03/en-GB

and it has to go to:

http://my-internal-endpoint/some-path/instance/b31593e6-dde2-4621-819f-dc1c2b1f6e03/en-GB
This endpoint is configured in gravity gateway: http://my-internal-endpoint/some-path/ 

What I can’t figure out is how to get internal endpoint in the plugin, doing this:
Object endpointAttr = executionContext.getAttribute(ExecutionContext.ATTR_REQUEST_ENDPOINT);
returns null. Can’t find any other way.

Is this possible to get it in the custom plugin somehow?

Thank you.

**Comment by brasseld** [comment]
Hi @pmatulionis,

If your endpoint is configured under gravitee endpoints, you give it a name (default is `default`)
What you can do from dynamic-routing policy is to reference this endpoint to build complete URI, something like:
```
{#endpoints['default']}/instance/{#group[0]}/{#group[1]}
```

So, according to me, you do not have to write a custom policy for such need.

**Comment by pmatulionis** [comment]
Hi @brasseld,

Great, that seems to be working. 

Thanks very much :)

**Comment by brasseld** [comment]
Ok cool.

I'm closing this ticket.
