### ISSUE TITLE
[management] not possible to change the logs configuration

### ISSUE THREAD

**Issue by RachidKelidou** [gravitee-io/issues#6282]
Tested on APIM 3.10.0 & 3.10.3 (CE)

After creating an API : enable and configure the logs _Analytics > Logs > Configure the logging_

Save.

We have here 2 problems : 
- the config is not saved
- it's no longer possible to update it, the save button is disabled

![image](https://user-images.githubusercontent.com/79910027/135244894-eaa5aac4-715b-4742-a9e1-f63ede6f0a62.png)

No error on the console (browser) and no logs on the Management.

**Comment by ytvnr** [comment]
maybe something related to the event used in `GvModelDirective`

we only rely on `component:input` but in case of gv-option it should be `component:select`

https://github.com/gravitee-io/gravitee-api-management/blob/33f9188fa7455290a01afac817790713c0fab9dd/gravitee-apim-console-webui/src/libraries/gv-model.directive.ts#L39

**Comment by phiz71** [comment]
Tested on 3.10.x environment (My great API (1.0))
