### ISSUE TITLE
[Portal] Advanced search results contains unpublished APIs

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6285]
When i use advanced search, i get results containing unpublished results.

### Expected Behavior

I should only get published APIs results.

### Steps to Reproduce (for bugs)

1. create an API using `admin` account and name it `Search` / do not publish it
2. Go to portal, search for `search` => you shouldn't get any results
3. same field, search for `ownerName:admin` => you can see your Search API
4. Click on the Search API, 404

### Your Environment

* Version used: 3.12.0
* Browser Name and version: Chrome
* Operating System and version:

**Comment by LiliaEn** [comment]
tested and confirmed in APIM Portal
