### ISSUE TITLE
[console] Quality Metrics lost after upgrade 

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#6290]
There is an issue, with the quality metrics, when migrated from 3.8.7 to 3.10.3

Replication steps:
Imported a mongodb dump file, exported from 3.8.4, with previously defined API's.
In 3.8.4 the tester API was showing 20% quality:

![image](https://user-images.githubusercontent.com/89140082/135308548-d0452689-912f-4aeb-b445-8dde5fab56d0.png)

and then when the same dump file was imported in 3.10.3, it was showing 100% quality, nothing from the other preferences changed:

![image](https://user-images.githubusercontent.com/89140082/135308719-9a4b1e84-fd59-4909-a7f3-496b4615bcae.png)

Version used:
Your Environment
Version used: 3.10.3
Browser Name and version: Chrome
Operating System and version: Windows10 , Docker Desktop

**Comment by marcambier** [comment]
**How to reproduce ?**

Actual behavior, on 3.10.3 :
- In Settings > API quality, check  "Enable API Quality Metrics", and enter some weights
- Create an API
- Look at this API quality note : it's always 100%

Expected behavior :
- API quality note should depends on weights

**Comment by mouligno** [comment]
LGTM
