### ISSUE TITLE
Alerting

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#63]
Providing a global alerting system for:
- Inform consumer that he is reaching a percentage of the rate-limit configuration.
- Inform API Publisher that an endpoint has been unregistered because health-check service was not able to check endpoint for X times.
- Inform administrator that one of the gateway instance is consuming more than XX % of heap or XX % oc CPU
- ....

**Comment by aelamrani** [comment]
This close #1548 and #1551
