### ISSUE TITLE
[Console] Search functionality with weird behavior

### ISSUE THREAD

**Issue by RubenMMSantos** [gravitee-io/issues#6315]
Search functionality is applying case sensitive criteria and word search criteria inconsistently

### Expected Behavior
When searching for an API, user should get results in a consistent way

### Current Behavior
Search functionality is not returning results consistently

### Steps to Reproduce (for bugs)
video of issue:
https://drive.google.com/file/d/1KeG2uaaxzWYqYSUagDtkXTpLi9W3Kodv/view?usp=sharing

### Your Environment
* Version used: nightly "3.12.0-SNAPSHOT"
* Browser Name and version: google chrome v94.0.4606.61
* Operating System and version: macOS Big Sur v11.5.2 (20G95)

**Comment by gcusnieux** [comment]
Certainly corrected with https://github.com/gravitee-io/issues/issues/6565

**Comment by LiliaEn** [comment]
Tested on the 3.13.x environment version 3.13.4 Snapshot
Browser: Chrome Version 95.0.4638.69, macOS Big Sur v11.6
Works as expected.
