### ISSUE TITLE
[portal] error on user subscription

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#632]
when logged with 'user' login
i try to suscribe to public api
i select plan an application to suscribe
![image](https://user-images.githubusercontent.com/22543323/26922529-afe70b98-4c3f-11e7-9709-af9b2588b764.png)

when i click on 'souscrire' button:
first popup message is green and second is red
![image](https://user-images.githubusercontent.com/22543323/26922611-e8a2709e-4c3f-11e7-84b7-bd763aae0468.png)

api key is create well and is pending but message shown is wrong ({{$ctrl.getSampleCall()}}):
![image](https://user-images.githubusercontent.com/22543323/26922665-09dd490a-4c40-11e7-90c1-be2abb1d77bc.png)

### Your Environment
* Version used: 1.6.3

**Comment by brasseld** [comment]
I'm not able to reproduce issues.

A quick question: is your constants.json file up-to-date with the version of Gravitee ? It seems that you're using an old file with a new version of Gravitee....
