### ISSUE TITLE
[Console] Customize HTTP_SIGNATURE_INVALID_SIGNATURE response template

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6320]
As a user, I want to be able to customize the response template for HTTP_SIGNATURE_IMPOSSIBLE_GENERATION.  (Policy `Generate HTTP Signature`)

 Update documentation for override policy errors key
https://docs.gravitee.io/apim/3.x/apim_publisherguide_response_templates.html#policy_error_keys_you_can_override

**Comment by phiz71** [comment]
Fixed with https://github.com/gravitee-io/issues/issues/6511
