### ISSUE TITLE
MySQL cluster environment requires Primary Key on all tables

### ISSUE THREAD

**Issue by itemco** [gravitee-io/issues#6323]
**Background/Description:**
We got a problem with Gravitee when DBA enforced STRICT-mode in Percona-cluster.
I'm not a DBA myself but from what I understand v5.7 and later requires that every table has a Primary Key defined.
Ref: https://www.percona.com/blog/2018/07/26/tuning-innodb-primary-keys/
In short: "That means a primary key is mandatory with InnoDB. You should always define explicit primary keys on your tables."

### Error
org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException; SQL state [HY000]; error code [1105]; Percona-XtraDB-Cluster prohibits use of DML command on a table (gravitee.node_monitoring) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER; nested exception is java.sql.SQLException: Percona-XtraDB-Cluster prohibits use of DML command on a table 

### Possible Solution
We managed to "solve" this by adding dummy-columns to the tables that had no Primary Key, ex:
```sql
ALTER TABLE gravitee.node_monitoring ADD COLUMN id_mysql_fix INT NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (id_mysql_fix);
```
If all tables have a Primary Key by default this would not be an issue. I'm a bit worried though what will happen next time we upgrade Gravitee. Will the dummy-PK's be removed? And if new tables are added I might be forced to add PK to those tables as well.

### Steps to Reproduce (for bugs)
You need a Percona-cluster to reproduce this. This SQL will list all tables without PK (I got 14):
```sql
select tab.table_schema as database_name,
       tab.table_name
from information_schema.tables tab
left join information_schema.table_constraints tco
          on tab.table_schema = tco.table_schema
          and tab.table_name = tco.table_name
          and tco.constraint_type = 'PRIMARY KEY'
where tco.constraint_type is null
      and tab.table_schema not in('mysql', 'information_schema', 
                                  'performance_schema', 'sys')
      and tab.table_type = 'BASE TABLE'
  and tab.table_schema = 'gravitee' --  schema name 
order by tab.table_schema,
         tab.table_name;
```
### Context
Our upgrade failed and Gravitee could not run unless all tables had a PK (eg manual workaround, creating dummy PK's)
The STRICT option for mySQL is set on the DB-host and can not be be changed individually for just one db.

### Environment
* Version used: 3.9.2
* Browser Name and version: Chrome
* Operating System and version: Red Hat Enterprise Linux Server 7.9 (Maipo)
* DB: Percona Server 5.7 and Percona XtraDB cluster

**Comment by itemco** [comment]
Awesome, thanks! As from what I've heard this STRICT-thing will be mandatory in MySQL v8 (next version after 5.7). The workaround (creating dummy PK's) seems to cause no problems from what I've seen so far.

**Comment by itemco** [comment]
This is still an issue as mentioned above.

**Comment by itemco** [comment]
As mentioned, this is still an issue! Today we can not install later versions of Gravitee as the installation fails due to everything mentioned above. Please, just make sure ALL tables have Primary Keys by default! How hard can it be?

**Comment by gaetanmaisse** [comment]
🎁  Merry Christmas @itemco! It took a while but be pleased to see I just merged the PR adding PK on all the tables. 
We also added a test to ensure this constraint will be respected in the future 😉 

This fix will be part of the `3.15.20`, that will be released next week

**Comment by itemco** [comment]
This is still not fixed in 3.20.2!
What's wrong with you people?! This is such a simple problem and fix!
Try again, and try harder this time!

**Comment by brasseld** [comment]
Sorry to hear @itemco 

We have some internal unit tests which we are running every day on Mysql 5 and 8 with strict mode (https://github.com/gravitee-io/gravitee-api-management/pull/2848/files) 
We have not detected any missing constraint at the moment.

Can you please share with us what are the tables for which the PK is missing ?

Thanks a lot.

**Comment by brasseld** [comment]
We got it! Subscriptions_metadata.

We are investigating why we have not detected that one with our UTs.

**Comment by itemco** [comment]
This is what I found after 43 tables created.
api_groups
application_groups
databasechangelog
group_event_rules 

Then the application hangs unless I disable STRICT on db, which I can't, as it's not mine.
So there could be more, in 3.17.2 we had 88 tables in total.

Good luck!

**Comment by itemco** [comment]
I have no clue what you are talking about. This is the problem:

MySQL [pdt_icc_gravitee]> describe api_groups;
+----------+-------------+------+-----+---------+-------+
| Field    | Type        | Null | Key | Default | Extra |
+----------+-------------+------+-----+---------+-------+
| api_id   | varchar(64) | NO   |     | NULL    |       |
| group_id | varchar(64) | NO   |     | NULL    |       |
+----------+-------------+------+-----+---------+-------+
2 rows in set (0.01 sec)

MySQL [pdt_icc_gravitee]> describe views;
+--------------+---------------+------+-----+---------+-------+
| Field        | Type          | Null | Key | Default | Extra |
+--------------+---------------+------+-----+---------+-------+
| id           | varchar(64)   | NO   | PRI | NULL    |       |
| name         | varchar(64)   | NO   |     | NULL    |       |
| description  | varchar(4000) | YES  |     | NULL    |       |
| default_view | bit(1)        | YES  |     | NULL    |       |
| hidden       | bit(1)        | YES  |     | NULL    |       |
| order        | int           | YES  |     | NULL    |       |
| created_at   | timestamp(6)  | YES  |     | NULL    |       |
| updated_at   | timestamp(6)  | YES  |     | NULL    |       |
+--------------+---------------+------+-----+---------+-------+
8 rows in set (0.01 sec)

Any Primary Key in the first table? Yes? No?

**Comment by itemco** [comment]
I'm out. Have a great weekend!

**Comment by itemco** [comment]
I think you are validating this in a wrong way.

From what we've seen so far, you're updating PK afterwards?

You need to turn on strict enforcing on your DB before you test anything.
Adding PK afterwards is NOT a valid solution. The DB will block the installation as soon as it finds a table without a Primary Key.
And that's why Gravitee always stops at after 43 tables complaining about "users" already exists. Infinite loop. Same behavior in 3.17.2 as in 3.20.2.

Hope this hint might help you to understand the actual problem

/Anders

**Comment by itemco** [comment]
This issue is still NOT fixed in your latest patch. We incorporated your latest patch to our 3.20.2-download and it made no difference. You need to add Primary Key in ALL CREATE-statements, not in later UPDATE-SQL's,
The database configured with STRICT=Enforcing will NOT allow your installation to fully complete.
If I disable STRICT=ENFORCING on db the installation works.
Please ADD PK on ALL CREATE-statements if you really wanna solve this problem, thank you!
