### ISSUE TITLE
[portal] api owner can't suscribe others applications

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#633]
when logged iwth api's owner login:
on administration apis subscription page, i can validate pending api key:
![image](https://user-images.githubusercontent.com/22543323/26922790-7237f810-4c40-11e7-9314-80fe977c5886.png)

but if i want to add susbscription for application, i haven't enought rights
![image](https://user-images.githubusercontent.com/22543323/26922853-b048acd0-4c40-11e7-92b2-edc46b42c2b2.png)

only admin can do that

it could be useful, in particular when new version of api is created and all api keys have to be recreated

### Your Environment
* Version used: 1.6.3

**Comment by brasseld** [comment]
I think that you do not have sufficients right to create a subscription for the selected application.
That's the reason why you get this message.

**Comment by NicolasGeraud** [comment]
When the user select an app, we look for the app's subscriptions to know if a subscription already exists.

But the owner is not allowed to see app's plans of someone else.

**Comment by brasseld** [comment]
Will be fixed by https://github.com/gravitee-io/issues/issues/741

**Comment by brasseld** [comment]
Fixed in 1.13
