### ISSUE TITLE
[resource-auth-provider] move gravitee-resource-auth-provider api in gateway

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#6332]
To avoid classloader issues, we need to move the gravitee-resource-auth-provider at the gateway level

- [ ] rename `gravitee-resource-auth-provider` to `gravitee-resource-auth-provider-api`
- [ ] Add `gravitee-resource-auth-provider-api` to gateway
- [ ] remove `gravitee-resource-auth-provider` from [gravitee-policy-basic-authentication](https://github.com/gravitee-io/gravitee-policy-basic-authentication)
- [ ] remove `gravitee-resource-auth-provider` from [gravitee-resource-auth-provider-inline](https://github.com/gravitee-io/gravitee-resource-auth-provider-inline)
- [ ] remove `gravitee-resource-auth-provider` from [gravitee-resource-auth-provider-http](https://github.com/gravitee-io/gravitee-resource-auth-provider-http)
- [ ] remove `gravitee-resource-auth-provider` from [gravitee-resource-auth-provider-ldap](https://github.com/gravitee-io/gravitee-resource-auth-provider-ldap)

**Comment by phiz71** [comment]
Partially done in 3.15.x with : https://github.com/gravitee-io/issues/issues/7198
