### ISSUE TITLE
We need have portal in zh language.

### ISSUE THREAD

**Issue by DukeMay** [gravitee-io/issues#6337]
###  Possible Solution

how to do that?

**Comment by DukeMay** [comment]
Hi @mouligno 
Nice meet you
OK , I'll try to translate. How do I submit my results? Which branch will I push?

**Comment by mouligno** [comment]
Hi @DukeMay 
you can create a feature branch on Gravitee-portal-webui repo to submit your ZH translation.

**Comment by DukeMay** [comment]
I've created a pull request
Added zh i18n #457

**Comment by mouligno** [comment]
Thanks @DukeMay
