### ISSUE TITLE
[policy] [oauth2] Oauth policy always OK with resource of type Access Management

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#634]
I defined an api with policy OAuth2.
this policy uses OAuth Gravitee Acces Management resource.

When i call api without authorisation header, i have 401 error : OK
If i put authorisation header (Bearer), i have OK.
but i have OK also if i put unknown token (ex: 1234)

I tried with generic OAuth resource, and when token is invalid i have error 401.

### Your Environment
* Version used: 1.6.3
* Browser Name and version:
* Operating System and version:

**Comment by brasseld** [comment]
Hi @vdelattre,

I'm not able to reproduce your issue.
Are you sure that you're sending an invalid token when doing tests ?
Perhaps, the browser is overriding the outbound request and this later does not correspond to the one you're thinking about ?
Did you take a look to the `developer console` with Chrome ? This way, you should be able to have a look to the request.

**Comment by vdelattre** [comment]
Call are made with postman

Le 13 juin 2017 12:57 PM, "Brassely David" <notifications@github.com> a
écrit :

**Comment by brasseld** [comment]
Postman is based on chrome ;)

Anyway, if you have a complete scenario to reproduce the issue I will be happy to have a look to it. Currently, I've found no way to reproduce it.

**Comment by vdelattre** [comment]
here is my  scenario:
create resource:
"resources": [
    {
      "name": "GraviteeAM",
      "type": "oauth2-am-resource",
      "enabled": true,
      "configuration": {
        "serverURL": "http://10.155.16.55:9080",
        "securityDomain": "siteapi",
        "clientId": "app",
        "clientSecret": "12345"
      }
    }
  ],

and create policy:
{
        "methods": [
          "GET",
          "POST",
          "PUT",
          "DELETE",
          "HEAD",
          "PATCH",
          "OPTIONS",
          "TRACE",
          "CONNECT"
        ],
        "oauth2": {
          "extractPayload": true,
          "checkRequiredScopes": false,
          "requiredScopes": [],
          "oauthResource": "GraviteeAM"
        },
        "description": "Description of the OAuth2 Gravitee Policy",
        "enabled": true
      }

first try: i disable OAuth policy and call api: return 200 OK
second, i enable OAuth policy. I call token access api (POST http://10.155.16.55:8092/siteapi/oauth/token)
i get access token.

third, i had in header: Authorization= Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6Im9wZW5pZCIsImFjdGl2ZSI6dHJ1ZSwiZXhwIjoxNDk3MzU2MDcwLCJ0b2tlbl90eXBlIjoiYmVhcmVyIiwianRpIjoiM2RhMWRkMmQtOWI4Mi00OTY4LWFmZWMtZjFhMjdmZGZjNDU5IiwiY2xpZW50X2lkIjoiYXBwIiwidXNlcm5hbWUiOiJmbHgifQ.a6ooL7xoNaXXiIMOl0HcCK_uXPD5XEAJ8oV8-V1jrtzVf5T4zsvocsb3RdY3GOFdKCMoEMvl37byy4U1v_DqrvbDJencSEbZjgGa7-zoZuba-fpyU4NFoWVlbP7FszQPbXPcMJG1cJLSQkxGbADSGx5xdQQhRR5rWopgR7yHBndXh_LOgOj4dxggw0ocxeNsvvQP1RuC8wzwEYPLKJkkZjVt6W6er38S7lGaSID4VSiX6PPf-nItl37CUyBbDaFUYFKKkn--7bI73FEguPfmpgRr3X9CrADPJLCk--golTEeyhiy1STMWhEFJjcNOUdeITvNjQIS90DzrnzaQ-V2xw

i call api: return 200 OK.

i remove Authorization header: error 401

i put again Authorization header but with value= 1234

i got return 200 OK

**Comment by brasseld** [comment]
I'm sorry but I'm still not able to reproduce your issue.
Can you have a try by checking the token by yourself ?

```
curl -X POST http://10.155.16.55:8092/siteapi/oauth/check_token?token=your_access_token
```

**Comment by vdelattre** [comment]
check token by api works well

**Comment by brasseld** [comment]
even if you send with a bad token ?

**Comment by vdelattre** [comment]
if i send bad token, i have error

**Comment by vdelattre** [comment]
i restarted Access Management, and i can't reproduce this issue

**Comment by brasseld** [comment]
I keep this issue `open` because it is strange to me....

**Comment by brasseld** [comment]
Ok, as we seen together, it was due to a bad configuration of the Gravitee.io AM resource.
