### ISSUE TITLE
[management-ui] in the user screen the column sorting is not operational

### ISSUE THREAD

**Issue by YoranSys** [gravitee-io/issues#6345]
### Expected Behavior
Sort should be possible on last login tab.

### Current Behavior

Sort is visible but not implemented: 

https://user-images.githubusercontent.com/11197007/136530825-f45f42b8-c295-4fed-9f90-dd423ff4718e.mp4

### Your Environment
* Version used: 3.11.1

**Comment by gaetanmaisse** [comment]
Closing the issue as it looks to be fixed in AM 3.18+
