### ISSUE TITLE
Can't login after installation - "POST /management/user/login" Error (404): "Not found"

### ISSUE THREAD

**Issue by sveryovka** [gravitee-io/issues#636]
I have installed MongoDB and Elastic, downloaded graviteeio-full-1.6.3 and have run 3 components included into graviteeio-full-1.6.3.

### Expected Behavior
I am expecting to be able to login as admin/admin

### Current Behavior
I see "Method not allowed" message in the browser and 
[Tue Jun 13 2017 14:27:51 GMT+0000 (Coordinated Universal Time)] "POST /management/user/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36"
[Tue Jun 13 2017 14:27:51 GMT+0000 (Coordinated Universal Time)] "POST /management/user/login" Error (404): "Not found"
in the logs

### Possible Solution
Probably documentation is not covering some necessaryr steps related to security setup.

### Steps to Reproduce (for bugs)
1. Install JDK 8, set JAVA_HOME
2. Install and start MongoDB
3. Install and start ElasticSearch 2.4.1
4. Download and unzip graviteeio-full-1.6.3.zip
5. Run 3 components from graviteeio-full-1.6.3.zip (gateway, api and UI)
6. Navigate to UI  (localhost:80). UI was started using node's http-server (http-server -p 80)
7. Eneter admin/admin into login form

### Context
I was trying to setup test installation of gravitee to learn it

### Your Environment
* Version used: 1.6.3
* Browser Name and version: Google Chrome
* Operating System and version: Windows Server 2016 datacenter

**Comment by brasseld** [comment]
Hello @sveryovka,

How do you run components ?
Did you update `constants.json` in UI ? If you work locally, you should have something like this:

```json
"baseURL": "http://localhost:8083/management/",
```

**Comment by sveryovka** [comment]
I have not changed any files. 

I am running everything (Mongo, Elastic and Gravitee) on the single VM. 

After starting Mongo and Elastic I've just unzipped graviteeio-full-1.6.3.zip archive and has done folloiwng:
1. cd graviteeio-gateway-1.6.1\bin and run "gravitee" 
2. cd graviteeio-management-api-1.6.1\bin and run "gravitee"
3. cd graviteeio-management-ui-1.6.2 and run "http-server -p 80"

http://localhost:8083/management/ asks for password but also gives 404

**Comment by brasseld** [comment]
You can try with http://localhost:8083/management/apis which should respond you with an empty array.
Also, again, please update `constants.json`with this property:
```
"baseURL": "http://localhost:8083/management/"
```

**Comment by sveryovka** [comment]
My bad. For some reason when I saw your response on my phone I have missed that I actually need to change ```constants.json``` and just concetrated on the way to start components. Sorry for not been attentive enough.

I will publish pull request to update https://docs.gravitee.io/apim_installguide_portal.html document with statement that ```constants.json``` needs to be updated. 

Thank you for the help.

**Comment by brasseld** [comment]
No problem @sveryovka 

Waiting for your PR ;)

**Comment by bitsofinfo** [comment]
Same issue

**Comment by NicolasGeraud** [comment]
hi @bitsofinfo 

what do you mean ? Have you tried the answer provided by @brasseld without success ?

**Comment by bitsofinfo** [comment]
Yes the constants.json in the management-ui container has this value which appears correct., yet I get a 404 at http://192.168.1.122:81/management/

```
{
  "baseURL": "http://192.168.1.122:81/management/",
```

**Comment by NicolasGeraud** [comment]
your configuration means that the management api is reachable from `http://192.168.1.122:81/management/`

could you try a GET on http://192.168.1.122:81/management/apis ?
you should get an empty array. If you have a 404, this means that your management api is not reachable

**Comment by bitsofinfo** [comment]
I get an empty array at http://192.168.1.122:81/management/apis

When I go to http://192.168.1.122:81/management/ I get BA prompt, put in admin/admin and get a 404

**Comment by bitsofinfo** [comment]
How do I just see the user interface?

**Comment by NicolasGeraud** [comment]
` http://192.168.1.122:81/management/` is the root of the management api. The user interface should be expose on another route depending on your configuration.

how do you run gravitee ? behind a proxy ? on a vm ? on docker ?

**Comment by bitsofinfo** [comment]
I'm just trying to evaluate this using the "docker" example in the documentation

https://docs.gravitee.io/apim_installguide_docker.html

I have mongo/es running, started all 3 containers and went to that url, thats it.

**Comment by NicolasGeraud** [comment]
ok, so according to the documentation, the ui should be on port 80.
try http://192.168.1.122:80

**Comment by bitsofinfo** [comment]
yep hitting 80 works, my bad
