### ISSUE TITLE
API Primary Owner role check

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6360]
Related to #5016

### Expected behavior
As a group primary owner, my group needs to be primary owner of the API to get PO role.

### Current behavior 
If i'm PO of a group and that group is part of an API, I get PO role and permisisons.

### Possible solution
To get PO Role on an API : 
- a User is PO of the API 
- a User is PO of a group AND the group is PO of the API

**Comment by a-cordier** [comment]
The following tables sum up the rules enforced for a user `user-1` that is member of a group `group-1`

| User Role for `user-1` In Group `group-1` | Default API role for users in group `group-1` | `group-1` listed in API groups ? | API Primary Owner | Inherited Role | `user-1` listed in API members ? |
|:-:|:-:|:-:|:-:|:-:|:-:|
| :man_shrugging: | :man_shrugging: | :x: | `user-2` | `NONE` | :x: |
| `PRIMARY_OWNER` | `USER` | :white_check_mark: | `user-2` | :arrow_down:`USER`  | :white_check_mark: |
| `PRIMARY_OWNER` | `NONE` | :white_check_mark: |`user-2` | :arrow_down:`NONE`  | :white_check_mark: (NO ROLE) |
| `PRIMARY_OWNER` | :man_shrugging: | :x: | `group-1` | `PRIMARY_OWNER` | :white_check_mark: |
| `OWNER` | `USER` | :white_check_mark: | `group-2` | `OWNER` | :white_check_mark: |

**Comment by RubenMMSantos** [comment]
Hi, from the table row 2 is failing, user ends up with no API role. 

Verified with dev on https://apim-3-10-x-console.cloud.gravitee.io/

**Comment by mouligno** [comment]
LGTM
