### ISSUE TITLE
API Path-based creation deprecation

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6377]
As APIM I want to start deprecate path-based creation for API from 3.15 to deprecate totally in 3.20.

### Expected Behavior

By default, path-based creation isn't available in the UI. 
Path-based creation can be enable with configuration toggle (organization settings).
We won't block API Import of old API definition.

![path-based deprecation by design](https://user-images.githubusercontent.com/3227037/137143925-7686b7b8-7fd9-430d-b04a-578dd270a912.png)

### Current Behavior

Design studio & Path-based are both available.

### Testing scenario
Start a new APIM
- path-based shouldn't be visible in UI
- i can still import path-based API Definition with API 

Activate path-based creation
- i can choose between both type of creaiton

**Comment by mouligno** [comment]
If i use the direct link to path-based API, even if it's disabled, i can access. Could we block this and still allow import by API ?

**Comment by mouligno** [comment]
We should keep the import link for path based also don't you think ?

**Comment by marcambier** [comment]
> We should keep the import link for path based also don't you think ?
If we import a V1 APIs definitions using the 'V2 Import' button behind 'Design Studio' card, it will automatically migrate the API to V2.
So yes, if we want to keep the previous 'V1Import' feature, we have to distinct import buttons.

**Comment by mouligno** [comment]
Yep I think we should keep both import for now

**Comment by mouligno** [comment]
LGTM

**Comment by LiliaEn** [comment]
Tested on the default environment version 3.15.0
Browser: Chrome Version 95.0.4638.69, macOS Big Sur v11.6

- [ ] Checked if the new toggle switch is displayed in Organisation Settings;
- [ ] Checked that Path Based option is not displayed when the toggle is disabled;
- [ ] Checked that Path Based option is displayed when the toggle is enabled;
- [ ] Created and Imported APIs using Design Studio;
- [ ] Created and Imported APIs using Path Based;
