### ISSUE TITLE
[managment] Add a domain field for application creation

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6383]
As an API Consumer, I want to describe domain i'd used for my application so API Publisher can set CORS to make it work.

### Expected Behavior

- Field is not mandatory

<img width="1715" alt="Capture d’écran 2021-10-13 à 18 25 40" src="https://user-images.githubusercontent.com/3227037/137174523-e0549c7a-c3f6-45b3-ad5b-94d43610e08a.png">

<img width="2420" alt="Capture d’écran 2021-10-18 à 15 51 08" src="https://user-images.githubusercontent.com/3227037/137744714-258fba11-2492-4dcc-ae0e-6f86f36a72f0.png">

### Testing

- [ ] Given a user with permission to create an application, when I register my application, the help sidebar explains what is domain field.
- [ ] Given a user with permission to create an application, when I register my application, then I'm able to fill my domain.
- [ ] Given a user with permission to create an application, when I register my application, then I'm able to not fill my domain.
- [ ] Given a user with permission to create an application, when I register my application, then I'm able to fill several domains.
- [ ] Given a user with permission to update an application, when I update my application, the help sidebar explains what is domain field.
- [ ] Given a user with permission to update an application, when I update my application, then I'm able to update domains.

**Comment by RubenMMSantos** [comment]
issue related to this ticket
https://github.com/gravitee-io/issues/issues/6383

**Comment by RubenMMSantos** [comment]
Issue raised during testing was fixed - #6605
- [ ] Given a user with permission to create an application, when I register my application, the help sidebar explains what is domain field.
- [ ] Given a user with permission to create an application, when I register my application, then I'm able to fill my domain.
- [ ] Given a user with permission to create an application, when I register my application, then I'm able to not fill my domain.
- [ ] Given a user with permission to create an application, when I register my application, then I'm able to fill several domains.
- [ ] Given a user with permission to update an application, when I update my application, the help sidebar explains what is domain field.
- [ ] Given a user with permission to update an application, when I update my application, then I'm able to update domains.

Ticket tested on https://apim-master-console.cloud.gravitee.io/
v3.14.0-SNAPSHOT
