### ISSUE TITLE
[console] View domain used by application

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6384]
As an API Publisher, I want to see domainsused by applications that subscribed to my APIs in order to properly set CORS for my API.

### Expected Behavior

![domain-view](https://user-images.githubusercontent.com/3227037/137748791-2fe5abf5-eb68-430f-b308-5ede657e1db7.png)

### Testing

- [ ] Given an API Publisher and a subscription with domain field filled, when I view the subscription then I can see the domain.
- [ ] Given an API Publisher and a subscription with domain field empty, when I view the subscription then the value for domain is empty.

**Comment by RubenMMSantos** [comment]
Ticket verified and working as expected
- [ ] Given an API Publisher and a subscription with domain field filled, when I view the subscription then I can see the domain.
- [ ] Given an API Publisher and a subscription with domain field empty, when I view the subscription then the value for domain is empty.

As extra testing:
- after the subscriptions were validated, domain field was changed on created applications
- changes were double checked via APiIs->Subscriptions->subscriptions details
- made changes to domain field via Portal and checked on APIM Console that changes were correctly displayed
- made changes to domain field via APIM Console and checked on Portal that changes were correctly displayed
