### ISSUE TITLE
[gateway] [oauth2] improve wildcard support for allowed redirect_uris

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#6397]
## User story

As an administrator or application owner, I want to register allowed redirect_uris with this pattern : `https://*.mydomain.*` to avoid to register potentially infinite redirect_uris.

## Possible solution

Currently we support wildcard in redirect_uris but only has a suffix. The goal is to update that part by using regex pattern.

## How to test

- [ ] Create a security domain
- [ ] Allow wildcard in domain settings
- [ ] Create a web application with `https://*.mydomain.*` redirect_uri
- [ ] Call the authorization endpoint with query parameter redirect_uri=https://sub.mydomain.com
- [ ] You should not have mismatch_redirect_uri exception

**Comment by patelami** [comment]
Env: Nightly
Result: PASS

Given I have create a web application with https://*.mydomain.* redirect_uri
And I initiate login flow
Then I should be redirected to user authentication screen
