### ISSUE TITLE
[gateway] self account management : reset password endpoint

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#6398]
## User story

As an end-user I would like to change my password without using the "Forgot my password" option.

## Possible solution

Add a new endpoint in the Self-service account API. We should discuss about what will be the payload to ensure security.

## How to test

- [ ] Sign-in to the AM cloud app 
- [ ] Go to the My Account space and reset my password
- [ ] Sign-out
- [ ] I should be able to sign-in again with my new password

**Comment by patelami** [comment]
Env: Nightly
Result: PASS

Given I have sign in to cloud app
And I go to user profile
Then I should see reset password link
When I update the password
And re-login to the cloud app 
Then I should be able to sign in with new password
