### ISSUE TITLE
[policy] [oauth2] How to configure oauth2 policy

### ISSUE THREAD

**Issue by cacidavidschermers** [gravitee-io/issues#640]
### Expected Behavior

The gravitee.io I've up and running locally and in OpenShift. How do I configure the gravitee-policy-oauth2? In general it's not clear to me where to configure policies. In plugins there are zip files and in the management-ui there are policies. From the documentation it's not clear how and where to configure the oauth2 policy.

**Comment by brasseld** [comment]
Hi @cacidavidschermers,

Don't know about your timezone, but I will be happy to provide you with some explanations using Gitter chat: https://gitter.im/gravitee-io/gravitee-io

**Comment by cacidavidschermers** [comment]
Hi,

That’s possible to chat now.

Best regards, David

Van: Brassely David [mailto:notifications@github.com]
Verzonden: donderdag 15 juni 2017 14:16
Aan: gravitee-io/issues <issues@noreply.github.com>
CC: David Schermers <David.Schermers@caci.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [gravitee-io/issues] How to configure oauth2 policy (#640)


Hi @cacidavidschermers<https://github.com/cacidavidschermers>,

Don't know about your timezone, but I will be happy to provide you with some explanations using Gitter chat: https://gitter.im/gravitee-io/gravitee-io

**Comment by brasseld** [comment]
Hi @cacidavidschermers 
After our chat, is it clear to you ?
Please close this issue and create a new one about the drag'n drop of policies.
Thanks a lot.

**Comment by cacidavidschermers** [comment]
Hi David,

It is clear to me, Thank you for you're help.
Regards, David
