### ISSUE TITLE
[repository] Inconsistent requirements in repository unit tests - updating item that doesn't exist in the repo

### ISSUE THREAD

**Issue by Yaytay** [gravitee-io/issues#641]
The test for PageRepository expects an exception when asked to update a Page that doesn't exist (PageRepositoryTest.java line 153).
The test for ViewRepository expects a null return value when asked to update a View that doesn't exist (ViewRepositoryTest line 112).

The behaviour should be consistent.

**Comment by aelamrani** [comment]
👍 
Moreover, we should add tests on other repositories on update when not exists...
