### ISSUE TITLE
[policy] Wrong imports and dependencies

### ISSUE THREAD

**Issue by Matsa59** [gravitee-io/issues#642]
### Expected Behavior

Generate a policy based on gravitee artifact should generate file with that kind of import : 

```java
// ...
import io.gravitee.policy.api.PolicyChain;
import io.gravitee.policy.api.PolicyResult;
import io.gravitee.policy.api.annotations.OnRequest;
import io.gravitee.policy.api.annotations.OnResponse;
// ...
```

It also should add this dependency in `pom.xml`:
```xml
<!-- https://mvnrepository.com/artifact/io.gravitee.policy/gravitee-policy-api -->
<dependency>
    <groupId>io.gravitee.policy</groupId>
    <artifactId>gravitee-policy-api</artifactId>
    <version>1.1.0</version>
    <scope>provided</scope>
</dependency>
```

### Current Behavior

Generate a policy base on `io.gravitee.maven.archetypes` with artefact `gravitee-policy-maven-archetype` create files with bad imports.

```java
// ...
import io.gravitee.gateway.api.policy.PolicyChain;
import io.gravitee.gateway.api.policy.PolicyResult;
import io.gravitee.gateway.api.policy.annotations.OnRequest;
import io.gravitee.gateway.api.policy.annotations.OnResponse;
// ...
```

It also doesn't add the needed dependencies to `pom.xml`.

### Possible Solution

Fix the archetypes (or something like that).
Currently, developers can add this to their dependencies (in `pom.xml`) :
```xml
<!-- https://mvnrepository.com/artifact/io.gravitee.policy/gravitee-policy-api -->
<dependency>
    <groupId>io.gravitee.policy</groupId>
    <artifactId>gravitee-policy-api</artifactId>
    <version>1.1.0</version>
    <scope>provided</scope>
</dependency>
```

and replace all :
```java
import io.gravitee.gateway.api.*
```
by
```java
import io.gravitee.policy.api.*
```

### Steps to Reproduce (for bugs)

1. Execute this mvn command :
```
mvn archetype:generate\
    -DarchetypeGroupId=io.gravitee.maven.archetypes\
    -DarchetypeArtifactId=gravitee-policy-maven-archetype\
    -DarchetypeVersion=1.0.0\
    -DartifactId=gravitee-policy-paging\
    -DgroupId=fr.apizr.gravitee.extension.policy\
    -Dversion=1.0.0\
    -DpolicyName=PagingPolicy
```

### Environment

* Version used: 1.3.0
* Browser Name and version: N/a
* Operating System and version: Mac 10.12.5

**Comment by Matsa59** [comment]
Download the SNAPSHOT version fix the problem.
Should deploy new version to official maven repositories (or something like that)

**Comment by brasseld** [comment]
Hi @Matsa59,

Maven archetype 1.1.0 has been released.
Documentation has been updated.
