### ISSUE TITLE
[management][Analytics] OpenSearch support

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6423]
As APIM I want to support OpenSearch

Related to #6169 

Modification to handle - from @marcambier investigation
 
> gravitee-reporter-elasticsearch : ElasticsearchReporter.doStart() :
> In the switch statement, find a way to idenfity OpenSearch.
> Suggestion : opensearch endpoint exposes '"distribution":"opensearch"' : ensure it's reliable. Then add 'distribution' to ElasticsearchInfo object and use it.
> When openSearch is used, instantiate dedicated components, like it's done for each ES version : OpenSearchBeanRegistrer / OpenSearchBulkIndexer / OpenSearchBulkIndexer /...
> As it's a fork of ES7, use the same behavior as ES7.
> 
> gravitee-repository-elasticsearch :
> Check conditions using "ElasticsearchInfo.getVersions()". for example this recurrent one : "info.getVersion().getMajorVersion() > 6".
> Should that behavior be applied to OpenSearch too ? (yes, according to my tests).
> If they should, replace them all with something like ElasticsearchInfo.shouldUseDocType()
> 
> + Create a docker-compose dedicated to running APIM with OpenSearch
> 
> + Enhance documentation to communicate around OpenSearch support (for example, https://docs.gravitee.io/apim/3.x/apim_installguide_repositories_elasticsearch.html)

### Testing

- [x] Given an APIM set with OpenSearch, when I navigate to analytics dashboard then I get the same comportment as with an APIM set with ElasticSearch
- [x] Given an APIM set with OpenSearch, when I search for an API then I get the same results as with an APIM set with ElasticSearch
- [x] Given an APIM set with OpenSearch, when I search for an Application then I get the same results as with an APIM set with ElasticSearch
- To be continued with all feature using ES

**Comment by RubenMMSantos** [comment]
1st step of testing done, search functionality using latest Elastic Search has been completed.
Functionality working fine with no weird behaviour observed.

Ticket will be in "Blocked by QA" while we wait for the APIM environment that will have OpenSearch configured so we can perform the 2nd and last step of testing.

cc @LiliaEn

**Comment by LiliaEn** [comment]
2nd step was completed on the opensearch environment.
The following areas were covered:
- Dashboard- > Analytics
- APIs-> Analytics
- APIs-> Logs
- Applications-> Analytics
- Health Check
- Gateway-> Monitoring
- Portal: Applications-> Analytics
