### ISSUE TITLE
[policy] [transform-header] How to extract payload OAuth2 username

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#643]
i have OAuth policy that extract payload
i have Transform header policy which add this payload in header variable.
But it's all json payload.

How can i extract json field of this payload ?

here is value i put:
{#context.attributes['oauth.payload']}

and here is what is extracted:
X-Process-User:	{"scope":"read write delete","active":true,"exp":1497536237,"token_type":"bearer","jti":"5e075c1c-f4eb-42a5-8b56-fd367133b242","client_id":"VDE","username":"flx"}

is it possible to access directly to field?

thanks

### Your Environment
* Version used: 1.6.3

**Comment by brasseld** [comment]
You can use this EL:

```
```

**Comment by brasseld** [comment]
Please provide your feedback.

**Comment by vdelattre** [comment]
thanks a lot!
it works great! ;)
i suggest you to add this example in documentation!
