### ISSUE TITLE
APIM - Search APIs by their labels causing unexpected results

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#6432]
When using the gravity API's to filter through the API's, there are unexpected results.

Expected Behavior
When trying to search through the API's in a environment, given a value for the labels, getting result that corresponds with the given labels when making the call.

Current Behavior
Making call to the following API:
POST http://localhost:8083/management/organizations/DEFAULT/environments/DEFAULT/apis/_search?q=labels: label.

The response besides the API's that contains the label as a searched keyword, returns also an API that do not have the label included, but the label is part of it's name.

Steps to Reproduce (for bugs)
1. Imported API's examples (attached);
2. Made a call from postman to the specified API
3. Compared results, and checked that in one of them there is no label included, but yet, it is part of one's name and is part of the results in the response, and should not be. For example: in the API's included, two of them contain the label='label', and one of them is named label, and all three of them are returned back from the call with the upper post command.

* Version used: 3.10.3
* Browser Name and version: Chrome
* Operating System and version: Windows 10

[dummyAPIs.zip](https://github.com/gravitee-io/issues/files/7390305/dummyAPIs.zip)

**Comment by phiz71** [comment]
The advanced search with keyword like "labels" "owner", ... has been introduced in 3.12
https://github.com/gravitee-io/issues/issues/2839

So your request does not work as you would expect.
