### ISSUE TITLE
[gateway][policy] fix license management of data-logging-masking and assign-metrics policies

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#6435]
data-logging-masking policy and assign-metrics uses the gravitee-license-api v1.0.0 ;
Which is incompatible with the gravitee-license-node v1.2.1 provided by gateway.
There has been a breaking change cause LicensedNode.license() was removed (from this PR https://github.com/gravitee-io/gravitee-license/pull/8)

**Steps to reproduce :**
- Start an EE gateway, with both data-logging-masking policy and assign-metrics policies
- Get an NoSuchMethodError during plugins installations, on LicensedNode.license()

**Expected behavior :**
- Plugins should install without any error

**Comment by LiliaEn** [comment]
@aelamrani @mouligno This ticket cannot be tested in 3.10.x environment since it is related to EE policies. Moving it to blocked until a we will decide how to proceed.
