### ISSUE TITLE
Create a library to share component between Gravitee products

### ISSUE THREAD

**Issue by gaetanmaisse** [gravitee-io/issues#6444]
**Description**

The goal of this issue is to create a new: 
 - GitHub repository containing 
   - a Yarn 3 monorepo
   - an Angular workspace with angular lib builder
   - Storybook config + Chromatic
   - CommitLint, ESLint, Husky
   - CircleCI config
 - NPM package published on GitHub registry `@gravitee-io/ui-particles`

We should also create a small ADR (Architecture Decision Record) on Slab to explain: 
 - the purpose of the new UI lib
 - some info regarding the future of the existing ui-components lib

**Comment by ThibaudAV** [comment]
Start ADR here : https://gravitee.slab.com/posts/share-stuff-between-console-ui-7848eeve
