### ISSUE TITLE
[AM Resource] Set Version V3_X by default on creation form

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6454]
When creating an AM resource in design studio, the version should be set to V3_x instead of V1_X.

![Gravitee_io_Management_et_Todoist.png](https://images.zenhubusercontent.com/61249a08867aba590067cd6f/7dcb6b41-8509-4633-9bc3-78680e048ae5)

**Comment by LiliaEn** [comment]
Tested on 3.10.x env
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
AM Resource version gets set to 3.x by default as expected.
