### ISSUE TITLE
[policy] [SSL Enforcement] 500 error instead of 403 when DN is not correctly formatted

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#6457]
# Current Behavior

SSL Enforcement Policy returns a 500 error instead of a 403 error when the Distinguish Name is not correctly formatted

# Steps to Reproduce

1\. Create an API with SSL Enforcement Policy configured with a wrong allowlisted DN (for instance, not starting with `CN`) 2\. In the gateway, set an active truststore and a "request" clientAuth 3\. Call the API:

 { "message": "java.lang.reflect.InvocationTargetException", "http_status_code": 500 }

**Comment by gaetanmaisse** [comment]
We've decided to improve the schema form to avoid this kind of issue. 
The distinguished names must now follow a regex pattern: `^(?: *[A-Z]+ *= *(?:\\w|\\*|\\?| )+,?)*$` 
So for instance: `CN=localhost,O=GraviteeSource*,C=??`
