### ISSUE TITLE
[APIM][alerts] Add HTTP_SIGNATURE_INVALID_SIGNATURE to api metrics list

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6462]
Related to #6319

Since we're adding it in response template, we should have it also in alerts.

**Comment by phiz71** [comment]
Since we need the alert-engine plugin, it will not be testable on APIM 3.10.x azure environment. @RubenMMSantos @LiliaEn  are you ok if we test it locally with @mouligno ?

**Comment by RubenMMSantos** [comment]
@phiz71 seems to be straight forward to test, happy for you and @mouligno to cover testing on this
