### ISSUE TITLE
CICD - Access token management by administrator

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6468]
Link to #6467 

As an admin, I can generate a token for users in order to create token for my service users.

### Expected Behavior

- Personal token generation
- Add the ability for admin to generate a personal token for user
- Revoke a token

<img width="1849" alt="Capture d’écran 2021-10-28 à 12 12 57" src="https://user-images.githubusercontent.com/3227037/139236079-fd6b2680-2552-40a1-aa22-35d0f8d31774.png">

### Testing

- [x] Given an administrator, when I've registered a service user, then I can generate an access Token.
- [x] Given an access token for service user, when I try to view the APIs through the management API, then I get a 200 result.
- [x] Given an access token for service user who owns API 1, when I try to view the APIs through the management API, then I get one result `API 1`.
- [x] Given an access token for service user who owns API 1, when i try to update the version to `2.0` using the management API, then I successfully update the API 1.
- [x] Given an access token for service user, when the service user is added to a group owning API, then I can update it via the management API.

**Comment by LiliaEn** [comment]
Tested on the default environment version 3.14.0
Browser: Chrome Version 94.0.4606.81, macOS Big Sur v11.6
The scenarios provided in the ticket description were covered and the following ones + exploratory:
- [ ] Create an API as a service user using a valid access token
- [ ] Update an API as a service user using a valid access token
- [ ] Retrieve previous created/updated API
- [ ] Generate multiple access tokens and check if the same actions can be performed with all of them
- [ ] Remove an access token and check that an error is displayed when trying to use deleted token
- [ ] Update the environment permissions (e.g. from API Publisher to Read Only) and check that a permission error is displayed when trying to create/update etc. an API
- [ ] Update the group permissions at the API level, e.g. from OWNER to READ_ONLY and check that the proper actions can be done. (Please note for this scenario there is a general issue already reported: https://github.com/gravitee-io/issues/issues/6475
- [ ] Delete an API that is stopped
- [ ] Get single APIs that the service user is a member of
- [ ] Get a single API that a service user is not member off- bug logged for that: https://github.com/gravitee-io/issues/issues/6650
