### ISSUE TITLE
management-ui texts not loaded in Dutch browser

### ISSUE THREAD

**Issue by cacidavidschermers** [gravitee-io/issues#647]
### Expected Behavior

When using an Dutch browser or another non EN of FR browser the texts on the management-ui are not shown, just the resource keys.

As a workaround the en.json is copied to nl.json and that works for the time beeing. Where using gravitee.io in OpenShift with docker and after a restart of the pod this manual action must be done again.
 
### Possible Solution

Load EN resource keys on a non EN or FR browser

**Comment by aelamrani** [comment]
Duplicate of https://github.com/gravitee-io/issues/issues/604
