### ISSUE TITLE
[Portal] Possibilty to disable promoted card on page list

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6472]
As an admin, I can disable the promoted card on portal APIs list

<img width="1759" alt="Capture d’écran 2021-10-29 à 10 27 38" src="https://user-images.githubusercontent.com/3227037/139402500-15d1ba1f-e8f9-4463-8abc-89f1f779e421.png">

### Testing

- [ ] Given an administrator, when I toggle off `Show promoted banner on page list` then I navigate to the portal and don't see the promoted banner
- [ ] Given an administrator, when I toggle on `Show promoted banner on page list` then I navigate to the portal and see the promoted banner

**Comment by LiliaEn** [comment]
Tested on the release-test environment version 3.14.0
Browser: Chrome Version 95.0.4638.69, macOS Big Sur v11.6
The following issues were reported: [6740](https://github.com/gravitee-io/issues/issues/6740) [6742](https://github.com/gravitee-io/issues/issues/6742)
The ticket will be blocked until the above issues will be fixed.
