### ISSUE TITLE
Group with Read only permission get weird API list 

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6475]
### Expected behavior

If a user is part of a group with read only permission and that group is associated to APIs, he should see these APIs in his APIs list.

### Current behavior & steps to reproduce 

As an admin :
- I create a new role `READ ONLY` for API with all permissions `READ` checked.
- I create a new group `Read only group` with default API Role `READ ONLY` and associate it to all existing APIs.
- I add a **user1** to this group and check that he got `READ_ONLY`role

As user1 : 
- I log in to the console UI and can't see any APIs
- I copy the access url for an API that's associated to the group `read only group` (from the console with admin account) and can access with read only permissions
=> I can access APIs with url but can't see them in the APIs list

As an admin : 
- I update `READ ONLY` role by adding creation permission for subscriptions.

As user1 : 
- I can see all the APIs associated with `Read only group`

=> by adding a update/delete/create permission on review/suscription/metadata, user1 can see the APis but not with read only permissions.
=> If i add permission on rating, user1 can't see the APIs.

### Possible Solution

Problem with a check for permission on the user's API list build ? 

### Your Environment

* Version used: master 3.13
* Browser Name and version:
* Operating System and version:

**Comment by a-cordier** [comment]
Some insights about this oddity

  - When retrieving the list as a manager, if the membership of the current user is inherited from a group implementation checks that this group has a role associated with either `CREATE`, `UPDATE` or `DELETE` permission
  - This check is not performed for a direct user membership
  - This check is not performed when retrieving a single entity (`READ` is sufficient) 

see [ApiServiceImpl](https://github.com/gravitee-io/gravitee-api-management/blob/cb6341a8d67fabc8f08dbc283dd3021586716e0d/gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java#L1035)
