### ISSUE TITLE
API Key \\ Unexpected error: key is valid and not revoked/expired

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#6483]
Expected Behavior
The plan ID's to remain unchanged when exporting/importing an API with plans defined on another environment

Current Behavior
Every time an API is updated with PUT request, the plans are updated with a different ID and this is causing issues, and throwing error.

Steps to Reproduce (for bugs)
1. Export an existing API (with a keyless plan and an apikey plan);
2. Replace all occurrences of the API id in the json file;
3. Import the exported json file to create a new API;
4. Make the following call locally to update the API
![image](https://user-images.githubusercontent.com/89140082/139696741-bec8d04f-9513-4907-a3fa-79315fadef7c.png)

5. Once it returned 200 OK, but then when checked the API, the call doubled all the plans:
![image](https://user-images.githubusercontent.com/89140082/139696552-91b3e2d0-cfd9-420d-a928-ebfb755e43a0.png)
 

Your Environment
* Version used: 3.12.1, 3.10.3
* Browser Name and version: Chrome 
* Operating System and version: Win10

**Comment by mouligno** [comment]
Hi @zveljanoski 

Thanks for your feedback, this is a known issue #6042.
