### ISSUE TITLE
[Portal] Direct Search from the API Info 

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6486]
As an API consumer, when i view an API detail page, I can access quick search from the API display right column.
- list of APIs from the same owner
- list of APIs with the same tag

### Possible Solution

- Link to the advanced search on the owner name : `ownerName: owner`
- Link to the advanced search on the different tags used.
- Update link from label to integrate advanced search behavior `label:`

### Testing

- [x] As an API Consumer, when i view an API and i click on ownerName, then i can view all APIs owned by him
- [x] As an  API Consumer, when i view an API and i click on tag, then i can view all APIs with the same tag.

**Comment by LiliaEn** [comment]
Tested on the release-test environment version 3.14.0
Browser: Chrome Version 95.0.4638.69, macOS Big Sur v11.6
The following issue was reported: [6738](https://github.com/gravitee-io/issues/issues/6738)
Ticket will be blocked until the above issue will be fixed.
