### ISSUE TITLE
[console]Login Error after password reset

### ISSUE THREAD

**Issue by LjupchoKostoski** [gravitee-io/issues#6488]
- Description
  - After a successful password reset of the specific user in Management UI , an error is shown after logging in to the UI
  - Error: "specific Application can not be found"
  - Within the UI for the user that had the password reset, multiple 'Default application' are now shown in the tab 'Application'
  - For every failed login new 'Default application' is created for the user

- Your Environment
  - Version used: Apim + Cockpit test environment
  - Browser Name and version: Chrome
  - Operating System and version: Windows 10

**Comment by gaetanmaisse** [comment]
I tried to reproduce it with the following setups:
 - APIM only, create a new user on APIM (user 1), log as an admin user and reset `user 1` password. Update `user 1`'s password and login 
 - APIM connected to Cockpit `dev` env, then create a new user on APIM (user 1), log as an admin user and reset `user 1` password. Update `user 1`'s password and login 
 - APIM connected to Cockpit `nightly` env + previous scenario

Unfortunately I never faced the described issue, @LjupchoKostoski does your user have specific roles or has been created on cockpit side first? 

@mouligno do you have any idea of what I could be missing?

**Comment by mouligno** [comment]
I don't see it, @LjupchoKostoski can you provide more info ?

**Comment by gaetanmaisse** [comment]
Ok, I get it 🤯 

There is an issue when:
 - You create an account but don’t log in right now
 - An admin update your user to set you a role to another environment
 - You then try to lo gin 💥 
(f you log in once before being added to an env there is no problem)

Working to fix this, but spoiler alert, I will impact a lot of files

**Comment by phiz71** [comment]
👏🏻  It was tricky. 
It's ok for me. 
@LiliaEn @RubenMMSantos , it won't be testable on azure env since they are not linked with a cockpit.
It's ok locally.
