### ISSUE TITLE
[management] fix Jetty's class loader

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#6495]
On 3.10.x, we fixed Jetty's classLoader, making it use Gravitee's context classLoader.
This ticket reports this fix on last version, and rollbacks some hacks that are fixed by this change too.

**Comment by marcambier** [comment]
**Steps to test :**
Ensure image uploading is still working :
- on portal : when you upload an avatar image on your account
- on console : when you upload a logo for your API

**Comment by LiliaEn** [comment]
Tested on the default environment version 3.13.0-SNAPSHOT.
Browser: Chrome Version 94.0.4606.81, macOS Big Sur v11.6
Image Uploading works as expected.
