### ISSUE TITLE
APIM 3.13.0 [Settings > Client Registration > Providers] Unable to create a client registration provider

### ISSUE THREAD

**Issue by RubenMMSantos** [gravitee-io/issues#6499]
Logged in as an admin, when trying to create a client registration provider i am unable to and an error is displayed on screen - error "server unreachable"

### Expected Behavior
As an admin, i should be able to create a client registration provider

### Current Behavior
i am unable to create a client registration provider

### Steps to Reproduce (for bugs)
1. log in as an admin
2. go to #!/environments/DEFAULT/settings/client-registration/
3. on Providers, click on "+" symbol
4. Fill out the necessary info
5. Click "Create"
6. Notice the error displayed

### Your Environment

* Version used: 3.13.0
* Browser Name and version: Google Chrome, v95.0.4638.69
* Operating System and version: macOS Big Sur v11.6.1

**Comment by mouligno** [comment]
@RubenMMSantos still accurate in 3.15.+ ?
