### ISSUE TITLE
[policy] policy to check existing param

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#650]
It could be useful to have policy to check that query param or header exists in request and / or check that value is in good type and good value

### Your Environment
* Version used: 1.6.3

**Comment by Matsa59** [comment]
You can use the groovy policy to check query param, header, content, ...
Have a look on `onRequest` and `onRequestContent`

for example : 
```
if (request.headers.containsKey('X-Gravitee-Break')) {
    result.state = FAILURE
    result.code = 500
    result.error = 'Stop request processing due to X-Gravitee-Break header'
} else {
    request.headers.'X-Groovy-Policy' = 'ok'
}
```
