### ISSUE TITLE
[Form-Data] Http Callout Policy with multipart/form-data Content-length issue

### ISSUE THREAD

**Issue by LjupchoKostoski** [gravitee-io/issues#6501]
- Description:
  - API with Http Callout Policy with multipart/form-data content-type is created
  - When request to Http Callout Policy URL is sent directly with postman Content-length have some value
  - When request to Http Callout Policy URL is sent through gateway with same Body like previous request , Content-length 
     have different value

 
![Form1](https://user-images.githubusercontent.com/89591105/140298978-1a63fdd4-21b5-42af-bd81-a10e08bdfda3.PNG)
![Form2](https://user-images.githubusercontent.com/89591105/140298986-e93d415a-351a-4f1c-8625-974eb7cc9229.PNG)

- Environment
 - Version used: Docker Desktop 3.5.10
 - Browser Name and version: Chrome
 - Operating System and version: Windows 10

**Comment by ytvnr** [comment]
@LjupchoKostoski, can you provide your test case please ?

**Comment by mouligno** [comment]
@LjupchoKostoski any news ?

**Comment by marijatimovska** [comment]
@mouligno @ytvnr Ljupco left the L2 support team, If there is anything I can do please inform me.

**Comment by mouligno** [comment]
@marijatimovska we couldn't reproduce, do you have the proper test case ?
