### ISSUE TITLE
[portal] Different representation of date format in 'Try it out" swagger admin console/dev portal

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#6506]
### Current Behavior
When you add a Swagger Page, publish it and enable "Try it out" mode you will notice that when you test the same route/path in admin console and dev portal you will not get the same representation of DATE. This is only happening if the Swagger is in YAML format, you will not get the same problem if the Swagger Page is in JSON.

admin console (format expected by the user): 1970-01-01
portail dev: 1970-01-01T00:00:00.000Z

* JSON
![image](https://user-images.githubusercontent.com/57534152/140444873-3beea01e-0997-4b4a-8638-cb82ee142f18.png)

![image](https://user-images.githubusercontent.com/57534152/140443469-9a3fccf3-cde4-40dd-8819-ebe81d278819.png)

* YAML
![image](https://user-images.githubusercontent.com/57534152/140444998-86c96c3e-ad48-478b-a528-2189c21d1dde.png)

![image](https://user-images.githubusercontent.com/57534152/140445147-73ef96b2-e933-4044-a315-1d1aec346da0.png)

### Expected Behavior
Date filed should be the same both in admin console and dev portal.

### Steps to Reproduce (for bugs)
1.  Simply have an Swagger with Date (yyyy-mm-dd) both in JSON and YAML.
2.  Import the APIs, enable "Try it out" and test the feature both in admin console and dev portal.

### Environment
* Version used: 3.5.6 on Docker-Desktop
* Operating System and version: Windows 10

**Comment by mouligno** [comment]
LGTM
