### ISSUE TITLE
[gateway] ILM managed indice are not handled by elasticsearch reporter

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#6507]
We should be able to choose ILM index mode (without date in the name)
`gravitee.analytics.elasticsearch.index_mode=ilm`

But setting this as env variable or through gravitee.yml of the gateway do not change the index names.

https://github.com/gravitee-io/_support_team/issues/49

📖 Need to add some documentation
☸️ Need probably to add some conf in helm chart ?

### Expected Behavior
Indices should be generated without date in the name
We should continue to access analytics, logs, monitoring via apim

#### Gateway side

Index is generated with date in the name

#### REST api side

ILMIndexNameGenerator is used to do the queries to Elastic search, so the index does not match what we have in ES.

### Possible Solution

As it's done in `ElasticSearchRepositoryConfiguration`, we should instanciate the right indexNameGenerator on reporter side.

Those beans are registered in Elastic`(5|6|7)`xBeanRegistrer.java

ILMIndexNameGenerator for reporter package should look like this:
```

@PostConstruct
    public void initialize() {
        indexNameTemplate = configuration.getIndexName() + "-%s";
    }

    @Override
    public String generate(Reportable reportable) {
        String type = null;
        if (reportable instanceof Metrics) {
            type = Type.REQUEST.getType();
        } else if (reportable instanceof Log) {
            type = Type.LOG.getType();
        } else if (reportable instanceof Monitor) {
            type = Type.MONITOR.getType();
        } else if (reportable instanceof EndpointStatus) {
            type = Type.HEALTH_CHECK.getType();
        }

        return String.format(indexNameTemplate, type);
    }
```

### Steps to Reproduce (for bugs)

1. Start APIM
2. Query elasticsearch with http://localhost:9200/_cat/indices and http://localhost:9200/_ilm/status
3. Check that the indices have the good name
4. Create an API, call it through gateway and verify analytics, logs, etc 

### Your Environment

* Version used: 3.5.16

**Comment by brasseld** [comment]
Hi @marcambier could we provide example for Logstash also ?
https://github.com/gravitee-io/gravitee-reporter-conf/tree/master/logstash

**Comment by marcambier** [comment]
> Hi @marcambier could we provide example for Logstash also ? https://github.com/gravitee-io/gravitee-reporter-conf/tree/master/logstash

done !
