### ISSUE TITLE
[console] Can't define truststore

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#6514]
From endpoint's configuration, if I switch on off "trust all" flag, I'm not able to define a truststore anymore

https://user-images.githubusercontent.com/1457497/141071169-48591012-bbc3-43fa-a153-33b47fb5ee01.mov

⚠️ This bad behavior is just on console, it's not reproducible in storybook ui-components.

**Comment by mouligno** [comment]
Same behavior detected on #6487
