### ISSUE TITLE
[management] split AM roles and IdP roles

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#6515]
If an end-user has new roles (new role, new promotion, new team, ...). We should not keep the old IdP role values in its profile.

**Comment by remisultan** [comment]
@patelami 

Here is how to create a Role Mapper 
![image](https://user-images.githubusercontent.com/8531515/147110366-3458604c-3ad2-4b5a-ad27-ab7b6c3eb1be.png)
![image](https://user-images.githubusercontent.com/8531515/147110417-b1a76ff7-1535-465a-8ee7-3f340d9dccf3.png)
![image](https://user-images.githubusercontent.com/8531515/147110574-634f6601-2ed5-41df-a793-97198b2ea225.png)

When you go through the login flow and succeed to login you can check if the user has the dynamic role applied

`Settings > Users > <User> > Roles`

And see the dynamically applied roles
