### ISSUE TITLE
[portal] Error popup in management-ui for non EN/FR browsers

### ISSUE THREAD

**Issue by cacidavidschermers** [gravitee-io/issues#652]
When using an non EN/FR browser the resource text are correctly loaded now in 1.7.0
But there is still an error popup shown once the browser has loaded the management ui.

See screenshot: [screenshot.docx](https://github.com/gravitee-io/issues/files/1090807/screenshot.docx)

### Possible Solution

The management-ui is trying to retrieve an nl.json file which is not found, In that case do no show a popup just continue

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/gravitee-management-webui/commit/774042e487ceb4dc5700b0cb56277d6c0e9052d1
