### ISSUE TITLE
[console] UI bug, logs data says that data is not send to a backend server but it is send.

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#6525]
### Current Behavior

After configuring Health-Check in Console everything is fine for a period of time (return code 200), after some time logs say that these is no data sent to the backend giving 404 error, but data is send. This was tested with https://webhook.site, as the URL from the webhook is added as and endpoint. The data from the POST in HC can later be seen on the webhook site.

![image](https://user-images.githubusercontent.com/57534152/140731904-e51d1a0c-52eb-4029-85f7-2621850b64c6.png)

### Expected Behavior
After configuring the HC with POST method the logs should not say that give a 404 error with message no body send to the endpoint (we don't see the content of the body) but the body is sent to the backend. 

### Steps to Reproduce (for bugs)
1. Import or create a simple API and add the URL from the https://webhook.site .
2. Configure Health-Check for example using a config like this:

![image](https://user-images.githubusercontent.com/57534152/140730979-31832f3c-2912-42d6-93e3-6b95964d7774.png)

![image](https://user-images.githubusercontent.com/57534152/140731562-b9fcc468-8d46-473e-8d41-147e5776bef2.png)

![image](https://user-images.githubusercontent.com/57534152/140731072-cc8e2160-a98f-487e-bece-1e65cc5222b7.png)

3. Wait for the request to be send to the backend.
4. You will see the POST you configured in HC on the webhooks request log.

![image](https://user-images.githubusercontent.com/57534152/140731483-9b462b87-48c9-4e99-b5b1-2be91f82c966.png)

### Your Environment
* Version used: 3.5.8 on Docker-Desktop
* Operating System and version: Windows 10

**Comment by gaetanmaisse** [comment]
🕵🏻  I did some investigations but wasn't able to reproduce the problem described in the issue on APIM 3.5.x environment. After a moment, we end up having `410` errors due to too many calls done to `webhook.site`. 

Also, in the issue, it's mentioned the endpoint returns a `404` which doesn't seem to match the fact that the body wouldn't have been sent. 

❓ Can you try to reproduce it on https://apim-3-5-x-console.cloud.gravitee.io and share the API you used? (You can login with your Google Gravitee account)

**Comment by marijatimovska** [comment]
I will test on https://apim-3-5-x-console.cloud.gravitee.io and as well as try to replicate on my side in my environment, see if I will get the same error as you.

**Comment by marijatimovska** [comment]
@gaetanmaisse I reproduce it on [https://apim-3-5-x-console.cloud.gravitee.io/](https://apim-3-5-x-console.cloud.gravitee.io) , and I can see that the body is indeed send to the backend and the 404 is not due to that. I will test now on my side on 3.5.8 and 3.5.26 and share my results.

**Comment by marijatimovska** [comment]
@gaetanmaisse I am not able to replicate the issue I will need to to few more tests if nothing happens I will probably arrange a call with the customer so they can show me the issue. I will test with a real backend and send data to a wrong route to get a 400 response and se if I get the body on my side

**Comment by marijatimovska** [comment]
Hello @gaetanmaisse I will close this issue as there are no problems regarding the body of the message and I was no able to replicate the potential bug.
