### ISSUE TITLE
API HTTP Connector-> When Use Proxy is enabled, Save button gets disabled

### ISSUE THREAD

**Issue by LiliaEn** [gravitee-io/issues#6538]
When Use Proxy is enabled, Save button gets disabled and it doesn't get enabled anymore when making other changes. The page should be refreshed 

### Expected Behaviour
Save button should get enabled when a new change is made

### Current Behaviour
When Use Proxy is enabled, Save button gets disabled and it doesn't get enabled anymore when making other changes. Please see the video:
https://drive.google.com/file/d/14oBPZomvaQLyDHcRjRVQcH2wfHFToUEg/view?usp=sharing

### Steps to Reproduce (for bugs)

1. Access the default env
2. Select an existing API
3. Go to Proxy-> Endpoints
4. Select an Endpoint and go to Configuration
5. Enable Use Proxy
6. Make another change on the configuration
7. Check Save button

### Your Environment
Version used: Default 3.13.0-SNAPSHOT
Browser Name and version: Chrome Version 94.0.4606.81
Operating System and version: macOS Big Sur v11.6

**Comment by LiliaEn** [comment]
https://github.com/gravitee-io/issues/issues/6132

**Comment by gcusnieux** [comment]
Hi @LiliaEn, the behaviour is good, when the proxy is enabled, the user must add host and port. 

![Capture d’écran 2021-11-10 à 10 20 01](https://user-images.githubusercontent.com/1457497/141085700-e155462e-bb62-4b65-b6ab-fc07797ecaf4.png)

**Comment by LiliaEn** [comment]
Invalid issue
