### ISSUE TITLE
Organization owner who is not a member of any environment

### ISSUE THREAD

**Issue by ibahloul** [gravitee-io/issues#6554]
According to the APIM permissions, OO should have access to the environment list of his organization:
![image (27)](https://user-images.githubusercontent.com/82866977/141500482-8af2323f-f679-49ec-9e18-4f2db0125293.png)

**Current behavior:**
![image (28)](https://user-images.githubusercontent.com/82866977/141500508-432bf033-b951-4753-bcfa-06bb45a4b0c8.png)
![image (29)](https://user-images.githubusercontent.com/82866977/141500527-35734de2-9be6-4f76-b14d-436bb17c815d.png)

**Further information:**
He has access to his organization's settings via the URL but there is no link since the main menu (on the left) is not displayed. He can't access his user profile either.

**Comment by gaetanmaisse** [comment]
Closing as it has been fixed in APIM 3.18+
