### ISSUE TITLE
[Console] An organization user (and environnement admin) can't delete a dictionary he has created

### ISSUE THREAD

**Issue by ibahloul** [gravitee-io/issues#6556]
### Steps to Reproduce (for bugs)
1. Login as organization user & environment admin
2. Go to the env settings > GATEWAY - Dictionaries
2. Create a new dictionary
3. Delete it

### Expected Behavior
The dictionary is deleted.

### Current Behavior
The dictionary is not deleted. An error 500 occurs.

### Screenshots
![image](https://user-images.githubusercontent.com/82866977/141679614-7837b346-3514-49d8-9c50-ceab9908ad8e.png)

**Comment by mouligno** [comment]
not reproduce

**Comment by ibahloul** [comment]
https://watch.screencastify.com/v/lx6b42r53xzPa3UYqpz8

**Comment by LiliaEn** [comment]
Tested on 3.10.x
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Works as expected
