### ISSUE TITLE
[gateway] [healthcheck] how to detect/alert on slow backend - with healthcheck ?

### ISSUE THREAD

**Issue by AnselmeDewavrin** [gravitee-io/issues#656]
Hi,
We have backends that get sometimes slow. From 100ms response time they sometimes get to 4000.
Is there a way to detect slowed backends and get an alert (for example by email) ?

### Expected Behavior
I thought the healthcheck would take into account the timeout set for the endpoint. Read timeout for example.

### Current Behavior
Even with response times higher than the timeouts set at the endpoint, the healthcheck is green

### Steps to Reproduce (for bugs)
1. choose any one of your api that has a healthcheck set and green
2. lower drastically the timeeout settings at endpoint
3. the healthcheck is still green

### Context
Don't know how to check quickness of my apis

### Your Environment

* Version used: 1.7.0

**Comment by brasseld** [comment]
In next version, request / read timeout will be treated with a 408 status code and the request will be marked  as failed.
