### ISSUE TITLE
[Console] API search doesn't return all expected results

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6565]
Some APIs doesn't return when you search by context-path.

### Expected Behavior

Get all API's matching the context path

### Current Behavior

Some APIs doesn't appear in result list as they should do.

### Possible Solution

Issue with APIs indexation ? 

### Steps to Reproduce (for bugs)

1. Search for `/` on APIs page
2. you just get few results

we should keep the same API list 

### Context

Search is also used from the management API.

### Your Environment

* Version used: 3.10.5
* Browser Name and version:
* Operating System and version:

**Comment by NicolasGeraud** [comment]
also happens in 3.5.22
