### ISSUE TITLE
Cockpit review

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6567]
https://github.com/gravitee-io/gravitee-cockpit/issues/1376
https://github.com/gravitee-io/gravitee-cockpit/issues/1303
https://github.com/gravitee-io/gravitee-cockpit/issues/1304
https://github.com/gravitee-io/gravitee-cockpit/issues/1306
https://github.com/gravitee-io/gravitee-cockpit/issues/1302

**Comment by gaetanmaisse** [comment]
Done
