### ISSUE TITLE
[apim][console] Cannot configure healthcheck at API Level

### ISSUE THREAD

**Issue by gcusnieux** [gravitee-io/issues#6569]
Since the changes for SMEs, we have a display problem for the Healthcheck configuration at the API level.
<img width="1908" alt="Capture d’écran 2021-11-16 à 16 04 17" src="https://user-images.githubusercontent.com/1457497/142010370-d18fdcec-1fa8-4b47-992b-ff77f55aa141.png">

**Comment by LiliaEn** [comment]
Tested on the default environment version 3.13.0-SNAPSHOT.
Browser: Chrome Version 94.0.4606.81, macOS Big Sur v11.6
Works as expected.

**Comment by gcusnieux** [comment]
https://github.com/gravitee-io/gravitee-api-management/blob/master/gravitee-apim-console-webui/src/management/api/proxy/backend/healthcheck/healthcheck-configure.controller.ts#L72-L74

Not Work if an api has more than one group or more than one endpoint
