### ISSUE TITLE
User created from AM cannot connect to APIM, if newsletter is enabled

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#6572]
When new user is created from AM and tries to connect to APIM, the console login raises "server unreachable" message.

It appears that when trying to login, the newsletter needs to access to `newsletter.gravitee.io`, that prevents the user to login, because of the server where Gravitee is hosted, cannot access to public network.

As a workaround, if the newsletter is disabled in the gravitee.yml file, the login works:
```yml
newsletter:
   enabled: false
```
this way the popup is turned off and as a workaround can be used.

* Version used: 3.10.3
* Browser Name and version: Google Chrome
* Operating System and version: Windows 10

**Comment by gaetanmaisse** [comment]
@zveljanoski from what I investigated even if `newsletter.gravitee.io` isn't reachable you should not face any issue as the network error will be caught. 

I wasn't able to reproduce the issue using 3.10.8, can you give it another try? And record a video if you're still facing the issue?

**Comment by apoddany** [comment]
@gaetanmaisse You can close this one as seems related to specific proxy configuration and the workaround is suitable
