### ISSUE TITLE
[gateway] Vhost mode does not work with HTTP/2

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#6574]
When gateway exposes apis with HTTP/2,  virtual host mode does not work.

When a consumer calls an api, the appropriate entrypoint is selected again the `Host` header (if present in the request). Such header does not exists in HTTP/2 (replaced by `:authority` header).

It is not working, at least since version 3.5.x.

**Comment by gaetanmaisse** [comment]
It looks like some tooling part were missing and so the build was failing:
 - https://github.com/gravitee-io/release/pull/402
 - https://github.com/gravitee-io/gravitee-gateway/pull/847
