### ISSUE TITLE
[management] Rollback introduces duplicated plans

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6595]
Link to this ticket : https://github.com/gravitee-io/issues/issues/6042

API rollback process lead to plans inconsistencies in database.

**How to reproduce (bug1) :**
- Deploy an API with one plan
- Add a plan to this API
- Rollback to the previous deployment
==> The second plan is present in plans table, but not in api.definition

**How to reproduce (bug2) :**
- Create an API with one plan
- Export it
- Create another plan
- Deploy it
- Import back the API with one plan
- Rollback to the API with 2 plans
==> The second plan is present in api.definition, but not in plans table

**Comment by LiliaEn** [comment]
Tested on the default environment version 3.10.8
Browser: Chrome Version 94.0.4606.81, macOS Big Sur v11.6
First bug in the description is fixed and works as expected. The second one can still be reproduced. Created a separate issue for that, to track them separately.
[#6622](https://github.com/gravitee-io/issues/issues/6622)

**Comment by marcambier** [comment]
@LiliaEn, as dicussed together, the behavior you noticed is a regression introduced by this fix. I'm working on it.

**Comment by RubenMMSantos** [comment]
Issue tested and confirmed as fixed.
Performed some extra checks with API's that had more plans and everything working as expected.
Ticket tested on https://apim-master-console.cloud.gravitee.io, APIM version 3.14.0-SNAPSHOT
Google Chrome Version 96.0.4664.55
macOS Big Sure v11.6.1 (20G224)
