### ISSUE TITLE
Service User: "Reset Password" CTA should not be displayed for service users

### ISSUE THREAD

**Issue by LiliaEn** [gravitee-io/issues#6602]
"Reset Password" CTA should not be displayed for service users

### Expected Behavior
"Reset Password" CTA should not be displayed for service users

### Current Behavior
"Reset Password" CTA is displayed for service users
<img width="921" alt="Screenshot 2021-11-22 at 13 10 30" src="https://user-images.githubusercontent.com/49516050/142867648-2ccb163a-52b0-49d3-85d4-26db586c1a41.png">

### Steps to Reproduce (for bugs)
1. Login to console as an admin
2. Go to Organisation Settings-> Users
3. Create a new Service User
4. Check if Reset Password CTA is displayed

### Your Environment
Tested on the default environment version 3.14.0
Browser: Chrome Version 94.0.4606.81, macOS Big Sur v11.6

**Comment by LiliaEn** [comment]
[](https://github.com/gravitee-io/issues/issues/6467)

**Comment by LiliaEn** [comment]
Retested on default env 3.14.0.
Reset password is still displayed for service users that have email.

**Comment by mouligno** [comment]
We can close since the issue is on the email if a service user is created with email.
