### ISSUE TITLE
DCR providers should be scoped by org

### ISSUE THREAD

**Issue by ibahloul** [gravitee-io/issues#6604]
### Steps to Reproduce
1. Configure a DCR provider
2. Log in to an environment of another organization

### Expected Behavior
The DCR provider configured on the first env is not available.

### Current Behavior
The DCR provider configured on the first env is available.

### Question
Shall we scope DCR providers by env?

**Comment by mouligno** [comment]
Discussed with @ibahloul :
- DCR configuration is set at env level but shared with any org/env of cockpit installation 
- Should the DCR be configurable at org level and shared with child envs ?

**Comment by RubenMMSantos** [comment]
waiting master environment to be available again

**Comment by LiliaEn** [comment]
The final decision is that DCR Providers are scoped by environment.
Tested on the default env 3.18.0 version 
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Working as expected.
