### ISSUE TITLE
When adding a new policy to an existing API will throw 500 error upon calling

### ISSUE THREAD

**Issue by LiliaEn** [gravitee-io/issues#6613]
Adding a new policy to an existing API will break the api and will return 500 error. Even after removing that certain policy 500 error will still be thrown

### Expected Behavior
A new policy should not break the API. 

### Current Behavior
When adding a new policy to an existing API will throw 500 error upon calling. Even after the policy is removed the API still throws 500 error. Example of API that throws 500: https://apim-master-console.cloud.gravitee.io/#!/environments/DEFAULT/apis/2c7440b9-024c-4ba9-b440-b9024c4ba9ad/portal

### Steps to Reproduce (for bugs)
1. Login to Console as an admin
2. Find an existing API
3. Go to Design
4. Add a new policy e.g. Mock
5. Save and Deploy the API
6. Call the gateway
7. Remove the policy previously added
8. Save and Deploy the API
9. Call again the gateway

### Your Environment
* Version used: 3.14.0
* Browser Name and version: Chrome Version 94.0.4606.81
* Operating System and version: macOS Big Sur v11.6

**Comment by mouligno** [comment]
@LiliaEn is it still accurate in 3.15.x ? do you have more info ?

**Comment by LiliaEn** [comment]
This issue is not reproducible anymore in any environment including 3.15.x.
