### ISSUE TITLE
[Policies] Add a condition for execution

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6614]
As an API Publisher, I want to add a condition to the execution of a policy.

### Expected Behavior

In design studio / platform policies studio, on each policy configuration : 
- I can add a condition for the execution 
- Expression is managed with Expression Language
- Hint should be "You can add a condition for the execution of this policy using Expression Language"

![image](https://user-images.githubusercontent.com/3227037/143254255-1b6c5d03-a815-41fc-aceb-147c79ce9f67.png)

#### Design studio
- [ ] Add a condition on a policy, the condition should be stored
- [ ] I can add a condition on every policies
- [ ] I can remove a condition on a policy.

#### Platform policies
- [ ] Add a condition on a policy, the condition should be stored
- [ ] I can add a condition on every policies
- [ ] I can remove a condition on a policy.

**Comment by LiliaEn** [comment]
Tested on the default environment version 3.15.0
Browser: Chrome Version 95.0.4638.69, macOS Big Sur v11.6

- Added a condition to a policy and checked that the policy is executed only when the condition is met;
- Removed a condition from a policy and checked that the policy is executed successfully without any condition ;
- Added an invalid condition and checked that an error message is displayed;
The majority of the tests were done using Mock policy, the following conditions were applied and they work as expected:
{#response.status == 200} 
{#request.path == '/echo7'} 
{#context.attributes['testattribute'] == 'test'}
{#properties['path'] == "/echo8"}
{#dictionaries['testd']['test'] == 'value1'} 
{#endpoints[default].equals("default:")}
