### ISSUE TITLE
[Policies] View if a policy is conditional 

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6615]
As an API Publisher, I can easily view if a condition apply on my policy

### Expected Behavior

When opening an API in the design studio, I can view a specific picto on policies that are conditional.

![image](https://user-images.githubusercontent.com/3227037/143259369-4ffc593c-2de2-4e4e-940f-9d0950453ada.png)

### Pre-requisites
- update story book

### Testing 

- [ ] Add a condition on a policy, you should see the picto on the policy.
- [ ] Remove the condition, you shouldn't see the picto

**Comment by LiliaEn** [comment]
Tested on the default environment version 3.15.0
Browser: Chrome Version 95.0.4638.69, macOS Big Sur v11.6
Works as expected
