### ISSUE TITLE
Impossible to contact the owner of API on developer portal when the owner is a group

### ISSUE THREAD

**Issue by djo54150** [gravitee-io/issues#6616]
Hello ,

When we try to contact the owner of the api with the contact fonction on the developer portal, the error "An unexpected error occurred" appears.

In the error log: 15:04:26.146 <span class="error">[gravitee-listener-70]</span> ERROR i.g.r.a.s.impl.EmailServiceImpl - Error while sending email notification javax.mail.internet.AddressException: Illegal address

Gravitee version : 3.9.4 Configuration of the problematic API: Owner : A group with a primary owner. This primary owner has a correct mail address metadata : email-support | email-support |mail | $

 {(api.primaryOwner.email)!''} 

<div class="table-wrap">
  | [support@change.me](mailto:support@change.me) | 
</div>

I think that the variable api.primaryOwner.email doesn't work when the owner is a group.

I have tried changing this value by the email address of the primary owner and it works.

Coud you please fix this issue?

Regards, Jonathan

**Comment by mouligno** [comment]
hi @djo54150 

Thanks for bringing that up, we'll fix it on a maintenance version for 3.10 since 3.9 isn't supported anymore.

**Comment by mouligno** [comment]
### Possible solution 

Prevent use of api.primaryOwner.email if a group is PO.
