### ISSUE TITLE
Portal Documentation Page cannot handle lots of menu options

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#6618]
When dealing with a lot of text in the right side menu, the page of the documentation gets unordered (the footer gets above the edge of the screen)

Current behavior:

![image](https://user-images.githubusercontent.com/89140082/143263948-89e9d82d-62a2-4b37-b4dd-79eec3b9551d.png)

Steps to Reproduce
1. Add a lot of documentation
2. Scroll up/down the portal/documentation tab

Version used: 3.5.18, 3.12.1
Browser Name and version: Google Chrome
Operating System and version: Windows 10

**Comment by mouligno** [comment]
LGTM
