### ISSUE TITLE
[APIM Management] When you check/activate HTTP Proxy with System Proxy in Endpoint configuration, Save button goes grey.

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#6619]
### Expected Behavior
When I check/activate HTTP Proxy with System Proxy in Endpoint configuration I should be able to Save my configuration.

### Current Behavior
When HTTP Proxy with System Proxy in Endpoint configuration is checked we should be able to use the Save button.

### Steps to Reproduce (for bugs)
1. Create/Import any API.
2. Go to Proxy -> Endpoints and go to the Edit Endpoint button.

![image](https://user-images.githubusercontent.com/57534152/143272732-5e978a2f-e31d-43ba-8bc7-f6849a564bc9.png)

3. Go to Configuration Tab at the top.

![image](https://user-images.githubusercontent.com/57534152/143272877-ce83261c-a656-47bd-9a3f-715c5102a240.png)

4.  Check/Activate HTTP Proxy with System Proxy, Save button goes grey.

![image](https://user-images.githubusercontent.com/57534152/143273448-a9ecc546-d76a-4710-a3e9-0382c05064ea.png)

### Your Environment
* Version used: 3.5.22 on Docker-Desktop
* Operating System and version: Windows 10

**Comment by marijatimovska** [comment]
An update:
- This is also happening when in the Endpoints we go to Add New Group and here in Configuration we do the same. Check/Activate Http Proxy together with System Proxy.

![image](https://user-images.githubusercontent.com/57534152/143452904-bbc374d4-a28f-4d6a-98e8-c963f4b4dcb6.png)

**Comment by phiz71** [comment]
I think it's more or less the same as this one: https://github.com/gravitee-io/issues/issues/5896

**Comment by mouligno** [comment]
LGTM
