### ISSUE TITLE
Rollback doesn't revert the plan definition correctly

### ISSUE THREAD

**Issue by LiliaEn** [gravitee-io/issues#6622]
This is the second scenario from [#6595](https://github.com/gravitee-io/issues/issues/6595)

### Expected Behavior
Rollback should correctly revert the plan definition

### Current Behavior
500 error is displayed when trying to rollback.
After a few tries it seems to work but when rolling back to a previous version that had 2 plan definitions, the second plan is not displayed.
<img width="1438" alt="Screenshot 2021-11-25 at 07 58 25" src="https://user-images.githubusercontent.com/49516050/143404917-5baf1856-8ccf-41fb-b2bf-55c77e8bcaf2.png">
<img width="1325" alt="Screenshot 2021-11-25 at 08 19 45" src="https://user-images.githubusercontent.com/49516050/143404927-7b52361c-1fc6-4eb4-8eb8-87aa0c7a9e77.png">
<img width="1338" alt="Screenshot 2021-11-25 at 08 19 56" src="https://user-images.githubusercontent.com/49516050/143404932-4b0791c1-9774-4c22-9f38-a9d4f6d38245.png">

### Steps to Reproduce (for bugs)

1. Create an API with one plan
2. Export it
3. Create another plan
4. Deploy it
5. Import back the API with one plan
6. Rollback to the API with 2 plans

==> The second plan is present in api.definition, but not in plans table

### Your Environment
* Version used: 3.10.8
* Browser Name and version: Chrome Version 94.0.4606.81
* Operating System and version: macOS Big Sur v11.6

**Comment by marcambier** [comment]
This is a regression introduced by this ticket fix : https://github.com/gravitee-io/issues/issues/6595
As discussed together, I close this ticket, and fix it within the original one.
