### ISSUE TITLE
[Design studio] View if a flow is conditional 

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6626]
As an API Publisher, I can easily view if a condition apply on my flow

### Expected Behavior
When opening an API in the design studio, I can view a specific picto on flow that are conditional.

### Pre-requisites
update story book

### Testing

- [ ]  Add a condition on a flow, you should see the picto on the flow.
- [ ]  Remove the condition, you shouldn't see the picto

**Comment by mouligno** [comment]
LGTM

**Comment by LiliaEn** [comment]
Tested on the default environment version 3.15.0
Browser: Chrome Version 95.0.4638.69, macOS Big Sur v11.6
Works as expected.
