### ISSUE TITLE
[console] Analytics/metrics are no more present if index_per_type: true with ES 5.x

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#6630]
### Current Behavior
After upgrading from APIM 3.10.x to 3.13.0, latest gateway metrics and other API Analytics are no more present in the UI Console
This happens with Elasticsearch 5.x and the following ES settings enabled in the gateway and rest-api configurations : 
```
    index: gravitee
    index_mode: daily
    index_per_type: true
```
ES appears to be still filled with the new data but they can not be displayed in the UI Console
Older data from 3.10.x (last 90 days) can still be viewed.
This appears to be related to the mapping type feature of ES 5.x that has been deprecated in ES 7.x.

### Your Environment

* Version used: APIM 3.13.0 Docker + ES 5.2.2

**Comment by a-cordier** [comment]
Problem reproduced with 
  - elasticsearch 5.6.5
  - gravitee-reporter-elastisearch 3.9.0
  - gravitee-apim-gateway 3.13.x
  
The problem no longer arises with gravitee-reporter-elastisearch 3.10-SNAPSHOT (current version on master branch)

The issue in 3.9 appears to come from bad index name generation

**Comment by phiz71** [comment]
tested locally: ok
Can't be tested on 3.13.x environment since we use ES v7
