### ISSUE TITLE
Backport #6042 in 3.5.x

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#6638]
Backport in 3.5.x the issue regarding Plan is duplicated when importing an api with one plan  see #6042

**Comment by gaetanmaisse** [comment]
@marcambier and I walk through all the commits done on `3.10.x` to fix issues related to plan duplication and most of them are updating code coming from the API Promotion feature implemented in APIM `3.10.x`. It means: 
 - it doesn't make sense to apply most of the changes as the base code isn't the same
 - some of the fixes will "disable/hide" some features
 - backporting everything will need a huge amount of work as it is more reimplementing things than backporting

@apoddany is there a very specific issue we absolutely need to fix or was this ticket a more global "clean things" issue? 

@mouligno does it worth it to spend a lot of time on this while the 3.5 almost reach EoL?

**Comment by mouligno** [comment]
Depends of @apoddany feedbacks but i'm not sure it worths it.

**Comment by marcambier** [comment]
As discussed with @apoddany , concerned customer in now in 3.10, so no need to fix the 3.5 import behavior.
