### ISSUE TITLE
[management] handle null value when getting instances

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#6639]
null values in GATEWAY_STARTED events make the call to /instances crash with an NPE

⚠️ maybe need an investigation on "why do we have null values sometime" -> seems to occur with jdbc

### Expected Behavior
We should see the instances list or unitary instance even if a data is missing

### Current Behavior
When converting GATEWAY_STARTED instance to an InstanceEntity, if a date field is missing, then we have a NPE
It may happen to `last_heartbeat_at` field, `started_at` field and `stopped_at` field.

### Possible Solution
Since, Long.parseLong is not null safe, we should check if timestamp is null.

**Comment by phiz71** [comment]
Approved and merged, but don't know if we will be able to test it on 3.5.x environment
