### ISSUE TITLE
[portal] Can't save a documentation by fetching swagger from gitlab

### ISSUE THREAD

**Issue by SirBigoo** [gravitee-io/issues#664]
When I try to retrieve swagger from a gitlab project, I can't save my configuration even if all fields are checked and valid.
![capture du 2017-06-29 16 19 01](https://user-images.githubusercontent.com/17948077/27692463-0d43ee3e-5ce7-11e7-8697-32e22ba2d421.png)

### Expected Behavior
Save button had to be clickable.

### Current Behavior
Can't save configuration.

### Steps to Reproduce (for bugs)
1. Create an API
2. Go to documentation and click on options
3. Configure gitlab fetching (cf. PJ)
4. Can't save

### Context
I would like to retrieve swagger from gitlab insted from my local computer.

### Your Environment
* Version used: 1.5.1
* Browser Name and version: Google Chrome Version 58.0.3029.96 (64-bit) 
* Operating System : Linux mint 17.3 Cinnamon 64-bit 2.8.8 (3.19.0-32-generic)

**Comment by brasseld** [comment]
You encounter this issue because the page is not yet created when you're trying to configure gitlab.
You must not be able to configure page is this one is not yet created.
