### ISSUE TITLE
[console] NoClassDefFoundError opening or creating swagger pages

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#6649]
In console, go into an API, menu Documentation > pages.
Select a swagger page, or try to create a new one.

**Current behavior :**
HTTP 500 error, an error message is displayed, and can't show the page (see stacktrace below)

**Expected behavior :**
No error, page is created and showable

![image](https://user-images.githubusercontent.com/87964124/143896196-f9a808e6-6f5a-424e-938e-edd9bc716cfd.png)

**Comment by LiliaEn** [comment]
Tested on the default environment version 3.14.0
Browser: Chrome Version 94.0.4606.81, macOS Big Sur v11.6
Works as expected.

- [ ] Created and published new Swagger Page
- [ ] Updated an existing Swagger Page
- [ ] Viewed an existing Swagger page
