### ISSUE TITLE
[APIM Portal] Not able to publish documentation in APIM Portal in a desired order

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#6652]
### Current Behavior
Not able to POST a page in APIM Portal in a desired order. 

![image](https://user-images.githubusercontent.com/57534152/144054753-1da393b6-bcfe-4ffb-8c65-5b3603665c5d.png)

The pages are posted in a consecutive order. If we view all the pages and if the last page is 8 the next page we POST will be with order 9 instead of the one we desire. 

### Expected Behavior
We should be able to put any order number of a page we want in the documentation. If I want the order to be 100 it should POST the page as 100 instead of the one next in line. Another example where this is important if we for example delete page with order 10, 11, and 12 and we want to add new pages to the freed spots we should be able to otherwise we will have few empty order numbers that will never be filled unless we delete all pages and start posting them from the beginning. 

### Steps to Reproduce (for bugs)
 1. Create or Import any API.
 2. Go to Postman and POST a page to http://localhost:8083/management/organizations/DEFAULT/environments/DEFAULT/portal/pages/ or to your correct URL
Body: 
{
"name": "string",
"type": "MARKDOWN",
"content": "string",
"order": 0,
"published": true,
"visibility": "PUBLIC",
"lastContributor": "string"
}
 3. Delete any page between 4 and the latest one.
 4. Add a page with order number or the page you deleted and you will see that the order number can't be customized, it will keep added to the order that is next in line. If next is 10 in line and we want to put 100 in order it will still be 10 instead of 100.

![image](https://user-images.githubusercontent.com/57534152/144052591-5f2274e1-01f7-4e1c-bfa6-cb4eeb05d4f6.png)

### Your Environment
* Version used: 3.8.3, 3.5.24 and 3.10.7 on Docker-Desktop
* Operating System and version: Windows 10

**Comment by gaetanmaisse** [comment]
After digging into the code it looks like the current behaviour is intended as there are dedicated lines of code to achieve that. Here is the current process to handle a POST page request:

1. Check if page type is `system` and throw a specific error if it is
2. Query the database to find the current max portal page order
3. Replace payload's order by the current max portal page order
4. Set the last contributor
5. Save the page

So the behaviour expected in this issue should be discussed with the Product Owner and might be considered as a new feature? cc @mouligno

**Comment by mouligno** [comment]
I confirm, @marijatimovska you could raise a feature request. 

We need to update documentation also then.

**Comment by marijatimovska** [comment]
@mouligno I will close this issue because a a feature request is raised.
