### ISSUE TITLE
Dashboard Query filter not working as expected.

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#6653]
When setup the dashboard query filter, it does not work and it is responding with an error message.

Current Behavior

![image](https://user-images.githubusercontent.com/89140082/144066835-c92040b6-d128-428b-9ff4-7bbf1592bde9.png)

Steps to Reproduce (for bugs)
1. try to setup a query filter
2. enable filter preview 
3. this is the query tried (and should work): path:\monpath\

Version used: 3.12.1, 3.10.1
Browser Name and version: Chrome
Operating System and version: Win10

**Comment by ppgravitee** [comment]
Not a bug, work as describe in the documentation tooltip
