### ISSUE TITLE
[portal] Jump to anchors in Markdown documents does not work - Syntax bug

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#6659]
### Current Behavior
By adding anchor points to a Markdown document and publishing the document to the portal in Gravitee, the reference/jump to the anchor points no longer works. When we reference the default auto-generated anchors like (#general-design-principles), the jump to the paragraph # Allgemeine Design-Prinzipien works. If there is a custom anchor it does not work.

### Expected Behavior
If the anchor name is custom, such as "alg-1", it does not work. It works on GitHub and other tools, as this is the correct markdown syntax.

### Steps to Reproduce (for bugs)
1. Create or Import any API.
2. Create a two test Markdown page and in one put this : Working Example
```
- [Einleitung](#einleitung)
  - [Vorwort](#vorwort)

<a name="einleitung"></a>

# Einleitung

Lorem ipusm...

<a name="vorwort"></a>

## Vorwort

Lorem ipusm...
```

Non-working example:

```
- [Allgemeine Design-Prinzipien](#alg)
  - [MUSS: API-First Ansatz verfolgen](#alg-1)


<a name="alg"></a>

# Allgemeine Design-Prinzipien

Lorem ipsum...

<a name="alg-1"></a>

## MUSS: API-First Ansatz verfolgen

Lorem ipsum
```

Lorem ipsum

3. Go to the portal and compare both pages to see the differene

### Your Environment
* Version used: 3.10.7 on Docker-Desktop
* Operating System and version: Windows 10

**Comment by mouligno** [comment]
LGTM
