### ISSUE TITLE
[Portal] Application page list pagination

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6665]
As an API Consumer, I want to use some pagination to view applications.

**Comment by RubenMMSantos** [comment]
working as expected
tested on https://apim-release-test-console.cloud.gravitee.io/#!/environments/default/instances/c7db215f-c518-4007-9b21-5fc51850070c/environment & https://apim-release-test-portal.cloud.gravitee.io/applications/mine?page=1&size=6
3.14.0-SNAPSHOT
