### ISSUE TITLE
[console] Alerts page documentation is not properly displayed

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#6680]
On alerts list pages, sidebar documentation is not properly displayed.

Current Behavior :
- In console, go to an API alerts page (or the organization alerts page)
- Open the help sidebar
- The documentation sidebar shows 'undefined'

Expected Behavior :
The documentation sidebar should show the relevant alerts documentation

**Comment by LiliaEn** [comment]
Tested on the default environment version 3.14.0
Browser: Chrome Version 94.0.4606.81, macOS Big Sur v11.6
Works as expected.
