### ISSUE TITLE
[policy] [groovy] Groovy  scripts fails to resolve method even if whitelisted

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#6681]
In 3.13.0, the Groovy Policy fails with 500 error as : 

```
[vert.x-eventloop-thread-1] [] ERROR i.g.policy.groovy.GroovyPolicy - Unable to run Groovy script
java.lang.SecurityException: Failed to resolve method [ class javax.crypto.Mac getInstance java.lang.String ]
	at io.gravitee.policy.groovy.sandbox.SecuredInterceptor.onStaticCall(SecuredInterceptor.java:58)
	at org.kohsuke.groovy.sandbox.impl.Checker$2.call(Checker.java:192)
```
 With the following script: 

```
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.security.InvalidKeyException;

String secret = "1234560"
String message = "Message"

Mac mac = Mac.getInstance("HmacSHA256")
SecretKeySpec secretKeySpec = new SecretKeySpec(secret.getBytes(), "HmacSHA256")
mac.init(secretKeySpec)
byte[] digest = mac.doFinal(message.getBytes())
request.headers.'Authentification' = Base64.getEncoder().encodeToString(digest)
```

### Steps to Reproduce (for bugs)

1. Import the attached API export  [test-groovy-1-0.txt](https://github.com/gravitee-io/issues/files/7659560/test-groovy-1-0.txt) (rename it to  `.json`)
2. Add the following in gravitee.yml of the gateway and rest-api in the groovy whitelist section : 
```
      - class java.util.Base64
      - class java.util.Base64$Encoder
      - class javax.crypto.Mac
      - class javax.crypto.spec.SecretKeySpec
```
3. Try to call the API

No issues in 3.10.7

### Your Environment

* Version used: 3.13.0 (works ok with 3.10.7)
* Browser Name and version:
* Operating System and version:

**Comment by phiz71** [comment]
Tested locally: OK
Can't test on 3.13.x environment since we cannot easily change the configuration in gravitee.yml or in env var.
