### ISSUE TITLE
[portal] Change password and add new user

### ISSUE THREAD

**Issue by mikexd91** [gravitee-io/issues#669]
How can i change password for admin? and i am unable to add new user, it says user registration is disabled. I am using the version installed through docker

**Comment by brasseld** [comment]
You can have a look to `${management_api}config/gravitee.yml`
Password stored in this file are encrypted using BCrypt

**Comment by mikexd91** [comment]
@brasseld thanks, i saw it, any idea how i can edit the file inside docker. I cant seem to vim or nano inside docker

**Comment by brasseld** [comment]
You're welcome.

An option would be to use a docker volume to mount your own `gravitee.yml` file

**Comment by NicolasGeraud** [comment]
if you want to edit the file inside your container : `docker exec -ti <CONTAINER_NAME> /bin/bash`

**Comment by mikexd91** [comment]
@NicolasGeraud  Hi after changing the file, do i need to do anything else? i tried to add an user but the portal doesn't seem to reflect the changes i made

**Comment by brasseld** [comment]
Did you restart the management-api container ?

User registered in gravitee.yml are mainly defined as technical users. It would be better to use an LDAP or a social provider (google, github, ...).

Thanks for your feedback.

**Comment by brasseld** [comment]
Hi @mikexd91,

What are the news ?

**Comment by mikexd91** [comment]
@brasseld  yes it works thank you

**Comment by brasseld** [comment]
Cool ! I'm closing this issue.
