### ISSUE TITLE
Raise error if import a new API with an existing plan on the targeted environment

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6691]
Import an API which does not exist but with plan identified by ID that correspond to an existing plan ID on the targeted env.
`POST apis/import`

### Expected behavior
Should Respond with error indicating Plan already exists

### Current behavior
200 : API is created with plan (auto-generated ID)

**Comment by mouligno** [comment]
Need to be done with HR ID - required for promotion

**Comment by marcambier** [comment]
As discussed together, the expected behavior of this ticket is not relevant anymore with the new crossId behavior. So I close the ticket.
CrossId and ids target behavior will be properly documented.
