### ISSUE TITLE
Use provided plan ID when importing new API

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6692]
Import an API which does not exist but with plan identified by ID that does not correspond to any plan on the targeted env
`POST apis/import`

### Current behavior
200 : API is created with plan (auto-generated ID)

### Expected behavior
API is created with plan and should use provided plan ID

**Comment by mouligno** [comment]
Need to be done with HR ID - required for promotion

**Comment by marcambier** [comment]
As discussed together, the expected behavior of this ticket is not relevant anymore with the new crossId behavior. So I close the ticket.
CrossId and ids target behavior will be properly documented.
