### ISSUE TITLE
Raise error if update API try to update an existing plan belonging to another API

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6693]
Import an API with plan identified by ID that correspond to an existing plan ID on the targeted env but not linked to same API
`PUT /apis/:id/import`

### Current behavior
security issue 200 : plans are updated, but if one input plan ID, after env tranformation, matches a plan OD of another API. Another API's plan is updated

### Expected behavior
Error, plan already used by another API

**Comment by mouligno** [comment]
Need to be done with HR ID - required for promotion

**Comment by LiliaEn** [comment]
Tested on the default environment version 3.15.0
Browser: Chrome Version 95.0.4638.69, macOS Big Sur v11.6
Tested also on Management API using Postman
Works as expetced.
