### ISSUE TITLE
[management] HealthCheck does not take into account Proxy settings

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#6698]
In 3.1.3.1, HTTP Proxy settings are no more taken into account with HealthCheck
Endpoints that go through a Proxy have a HealthCheck KO (504) but flow are OK
In 3.12.4, the same endpoints that go through a Proxy have a HealthCheck Ok and a flow OK

In parallel, if an endpoint not proxied is configured with a dummy Proxy, HealthCheck keeps OK status but should go to 502

### Steps to Reproduce (for bugs)

1. Create an API with an endpoint that goes through a Proxy
2. Enable HealthCheck
3. 504 is returned in HC logs

### Your Environment

* Version used: 3.13.1
* Browser Name and version:
* Operating System and version:

**Comment by a-cordier** [comment]
Hi @apoddany 

I could not reproduce the issue with 3.13.1. 

With an HTTP Connect Proxy configured at the entry point level both health checks and actual client calls are OK.

Is there any additional detail I should be aware of to reproduce ?

**Comment by a-cordier** [comment]
@apoddany 

Reproduced.

Actually the issue only occurs when the config is inherited from a group.

Working on it

**Comment by phiz71** [comment]
Tested on 3.13.x environment: ok
