### ISSUE TITLE
[Portal] Allow alert notification via webhook

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6703]
:scroll:
**As an API Consumer**
**I want to get notified via webhook when an alert raise**
**So that I can automate some process**

### :information_source: **Information**
- Default behavior stay the same ie notification to all members of the application
- Allow to toggle notifications via webhook per alert
- if toggled on, form appears to set HTTP Method & URL for webhook
- if toggled on, submit button is disabled if HTTP Method & URL are not filled
- Webhook payload is not configurable.
-  check if webhook plugin available before proposing webhook notif

Webhook payload : 
- alert title (sentence of the condition)
- alert description if provided
- application info (id/name...)
- notification timestamp
- api info is applicable

 

### :link: **Dependencies & Linked stories**

- Alert Engine

### **Mockups**
<img width="1774" alt="Capture d’écran 2021-12-09 à 09 28 22" src="https://user-images.githubusercontent.com/3227037/145361008-b65de37d-baad-4c90-baf9-9eb4d4fd4636.png">

### **Documentation required**
:link:Provide link to the issue for documentation update

### **Acceptance criteria**
- [ ] Given '...'
- [ ] Then '...'
- [ ] When '...'

### :warning: **Potential impacts**
*To be populated after dev*

### :ballot_box_with_check: **Definition of Done checklist**
***For each User Story everything on the list must be considered, select only what was required***
- [ ] Acceptance criteria met and tested
- [ ] Sonar Cloud quality gate passes
- [ ] CircleCi checks pass
- [ ] Cypress or Postman API check passes
- [ ] Test containers passed if modifications on the repository modules
- [ ] Translation for portal UI checked
- [ ] Developer created draft documentation PR
- [ ] New migration scripts checked
Can be run multiple times but only makes changes the first time
Display to user what script has done
- [ ] Validated on appropriate environment
- [ ] Existing test cases refactored

:checkered_flag::superhero:

**Comment by LiliaEn** [comment]
Tested on the local dev environment version 3.15.0.
The following scenarios were covered:

- [ ] Toggle on/off the notifications via webhook
- [ ] When toggled on, a new field is displayed for the webhook url, and a dropdown for HTTP method
- [ ] Created a webhook alert using a valid webhook url
- [ ] Checked if the webhook notification is displayed
- [ ] Checked all the details in the notification: title, description, api info etc.
- [ ] Checked that no notification is coming when the webhook url is invalid
