### ISSUE TITLE
Alert not correctly displayed/saved

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#6705]
When trying to set up a new alert, with the following settings

![image](https://user-images.githubusercontent.com/89140082/145407249-e78622b4-829a-481c-bff2-62aae0b84b4c.png)

the field **Calculate** in the condition is not saved/updated as intended.

Also attached a video for issue.

Used versions: APIM 3.10.07, AE 1.4.1

https://user-images.githubusercontent.com/89140082/145406934-63f4d3f2-673f-4679-9aa9-4b5a9c8076f2.mp4

**Comment by LiliaEn** [comment]
Tested on the default env v3.18.0 
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Alert with "count" function is saved and displayed correctly.
