### ISSUE TITLE
[policy][retry] Check compatibility with APIM 3.10.x and upper

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#6707]
Since APIM 3.10.x, the 1.1.x version of the gravitee-policy-retry is used. However, this plugin still rely on gravitee-parent 19, which uses Vert.x 3.8.5, whereas APIM uses Vert.x 4.x.

The circuit-breaker lib might not have too much changed, so it should continue to work. But we have to be sure of that.

At least, we should bump gravitee-parent and use gravitee-bom in this policy.

**Comment by mouligno** [comment]
LGTM
