### ISSUE TITLE
[management] Checking "Show the URL to download the content" in the swagger documentation generates and error

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#6713]
**Describe the bug**
When we check the option "Show the URL to download the content" in Swagger Configuration there is an error in the console, but there is no error in the portal.

**To Reproduce**
Steps to reproduce the behaviour:
1. Import/Create any API.
2. Go to Pages of that API and add a Swagger documentation. 
3. Go to Configuration of that Swagger and check the option "Show the URL to download the content".

![image](https://user-images.githubusercontent.com/57534152/145552499-a6c896e9-b3fd-4f72-b860-bc9070881ac7.png)

4. Go back to Page and you will see an error.

![image](https://user-images.githubusercontent.com/57534152/145552679-7f516ff5-b1ed-4800-8118-ac1c8f7a010e.png)

The error is present only in the Management Console.

**Expected behavior**
When we check the option we should not get any errors just like in the Developer Portal.

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser: Chrome

***Which other features may be impacted by this fix. This could be populated after fix**
Maybe where does the download link in the Portal needs to be moved.
It is too close to the title above.

![image](https://user-images.githubusercontent.com/57534152/145553937-4f7816a4-8fbf-452a-8c7f-431502a93bad.png)

**What are the impacted versions?**
 -3.10.5, 3.10.7

**Comment by RubenMMSantos** [comment]
Issue tested and confirmed has fixed.
Other feature that was impacted also confirmed as fixed.
Issue verified on environment  https://apim-3-10-x-console.cloud.gravitee.io/ & https://apim-3-10-x-portal.cloud.gravitee.io/

**Comment by skf-trax** [comment]
Good to see that the issue has been identified, how can I get notified when the fix is available?

**Comment by gechu** [comment]
Good to see that the issue has been identified, how can I get notified when the fix is available?
