### ISSUE TITLE
[gateway] HTTP2 endpoint may lead to bad request

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#6719]
**Describe the bug**
Configuring an endpoint with HTTP2 may cause errors

**To Reproduce**
Steps to reproduce the behaviour:

1. Create  an api with an enpoint able to answer in HTTP2
2. Configure the endpoint with http2 like this
![image](https://user-images.githubusercontent.com/5955401/145577357-f59493a3-b12d-4847-9f82-79a1df6ceae9.png)

3. Call your api. The endpoint is correctly called but may answer a 400 bad request

```
curl -D- https://apim-master-gateway.cloud.gravitee.io/jhaeyaert
HTTP/2 400
date: Fri, 10 Dec 2021 12:43:38 GMT
content-type: text/html
content-length: 150
x-gravitee-transaction-id: 2602ce3a-6978-4517-82ce-3a697895179f
x-gravitee-request-id: 2602ce3a-6978-4517-82ce-3a697895179f
strict-transport-security: max-age=15724800; includeSubDomains

<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
4. Call the endpoint directly to check the endpoint works correctly, forcing the http2 protocol if not used by default. 
```
curl -D- --http2 https://load-tests-echo-api.cloud.gravitee.io/echo
HTTP/2 200
date: Fri, 10 Dec 2021 12:58:43 GMT
content-type: application/json
content-length: 440
strict-transport-security: max-age=15724800; includeSubDomains

{
  "headers" : {
    "Host" : "load-tests-echo-api.cloud.gravitee.io",
    "X-Request-ID" : "6f92f947c0827119a9d478802e5c2d11",
    "X-Real-IP" : "127.0.0.1",
    "X-Forwarded-For" : "127.0.0.1",
    "X-Forwarded-Host" : "load-tests-echo-api.cloud.gravitee.io",
    "X-Forwarded-Port" : "443",
    "X-Forwarded-Proto" : "https",
    "X-Scheme" : "https",
    "user-agent" : "curl/7.64.1",
    "accept" : "*/*"
  },
  "query_params" : { }
}
```

**Expected behaviour**
The gateway should send a valid request to the endpoint.

**Useful information**
Seems to be related to the `Host` header that is no more a valid header for http2 and should be filtered. 
It also depends how sensitive is the backend when an invalid header is sent. In the given example, the backend is behind an Nginx http proxy which seems to reject the request when the `Host` header is sent for an http2 request.

**Desktop (please complete the following information):**
Not relevant

**Potential impacts**
***Which other features may be impacted by this fix. This could be populated after fix***
Not relevant

**Linked stories**
Not relevant

**What are the impacted versions?**
Bug confirmed from 3.5.x and above.

**How to test**

 - Import the API [echo-api.json.zip](https://github.com/gravitee-io/issues/files/8967809/echo-api.json.zip)
 - Call it `curl --http2 -D- http://localhost:8082/echo`
 - Play with custom header in endpoint configuration

**Comment by mouligno** [comment]
To test if still accurate in 3.10+

**Comment by grignix** [comment]
Hi @gcusnieux  
Please tell me when to expect a solution to this problem approximately, this issue blocks the solution to my issue https://github.com/gravitee-io/issues/issues/7760

**Comment by gcusnieux** [comment]
Hello @grignix , 
we will work on thi topic, I will come back to you quickly
