### ISSUE TITLE
[management] When importing an API through file or URL path-mapping for analytics are not created.

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#6723]
**Describe the bug**
When I import an API through file or URL and check the option "Create the path-mappings for analytics" or when I want to update/create path mappings in Analytics through Swagger the path mappings are not created or just /.

For testing purpose I am using the Petstore API (ex:https://petstore.swagger.io/v2/swagger.json)

**To Reproduce**
Steps to reproduce the behaviour:
1. Import an API through file or URL(ex:https://petstore.swagger.io/v2/swagger.json).
2. Check option "Create the path-mappings for analytics" and import the API.
3. Go to Analytics and go to Path mappings and you will see that there are no paths there.
4. By hand create or if you have update the already patch there though Swagger and you will see that nothing will change or just / will be created from all the paths in the Swagger.

![image](https://user-images.githubusercontent.com/57534152/145599933-b28d0a4d-5f3b-4254-9a44-3e164991f0c4.png)

**Expected behaviour**
When importing an API through file or URL and check the option "Create the path-mappings for analytics" or when I want to update/create path mappings in Analytics through Swagger all the path mappings should be created.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**What are the impacted versions?**- 3.5.16, 3.5.24

**Comment by mouligno** [comment]
Second part of the ticket will be fixed with : https://github.com/gravitee-io/issues/issues/6856

**Comment by phiz71** [comment]
OK
