### ISSUE TITLE
[alert] alert per endpoint when healthcheck status change

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#6728]
When APIM is connected to Alert Engine, it is possible to configure the following alert at api level: `Alert when the health status of an endpoint has changed`. That way, when the health status of one the configured api endpoints changes, a notification is fired.

Unfortunately, if multiple endpoints are configured, it is not possible to receive a notification per endpoint.

The objective is to provide a way to send a notification per endpoint defined by adding a section allowing to aggregate the events per endpoint name.

**Comment by RubenMMSantos** [comment]
Hi @marcambier, can we have Alert Engine on 3.10.X environment or do we have to check this locally? thanks

**Comment by phiz71** [comment]
To test AE on 3.10.x env, we should have a EE version.
So you will have to check it locally.

**Comment by RubenMMSantos** [comment]
waiting on permission changes from change_management

**Comment by RubenMMSantos** [comment]
tested locally with the dev, working as expected
