### ISSUE TITLE
[apim][connector-kafka] 500 random errors when consume a topic

### ISSUE THREAD

**Issue by gcusnieux** [gravitee-io/issues#6730]
## :collision: Describe the bug
We have 500 random errors on the kafka connetor.

```
13:35:28.853 [vert.x-eventloop-thread-1] ERROR i.g.c.kafka.ReadDataConnection - Kafka consume unable to seek for a given partition 
13:57:03.587 [vert.x-eventloop-thread-1] ERROR i.g.connector.kafka.KafkaConnector - Unexpected error while listening for a given topic for websocket 
13:57:17.007 [vert.x-eventloop-thread-1] ERROR i.g.c.kafka.ReadDataConnection - Kafka consume unable to seek for a given partition 
13:57:19.609 [vert.x-eventloop-thread-0] ERROR i.g.c.kafka.ReadDataConnection - Kafka consume unable to seek for a given partition 
13:59:10.533 [vert.x-eventloop-thread-1] ERROR i.g.connector.kafka.KafkaConnector - Unexpected error while listening for a given topic for websocket 
13:59:35.598 [vert.x-eventloop-thread-0] ERROR i.g.c.kafka.ReadDataConnection - Kafka consume unable to seek for a given partition 
14:00:50.797 [vert.x-eventloop-thread-0] ERROR i.g.c.kafka.ReadDataConnection - Kafka consume unable to seek for a given partition 
14:01:00.988 [vert.x-eventloop-thread-1] ERROR i.g.c.kafka.ReadDataConnection - Kafka consume unable to seek for a given partition
```

When we debug we notice that the KafkaConsumer is already closed...

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Create a kafka api and deploy it
2. Consume and Produce topics
3. See error

## :rainbow: Expected behaviour

No error

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop :

***Please complete the following information:***

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

https://github.com/gravitee-io/issues/issues/6686

**Comment by ppgravitee** [comment]
Wait for Jupiter
