### ISSUE TITLE
Show Promoted API Banner: Other APIs section is displayed when the toggle is disabled and it disappears when the toggle is enabled if there are no APIs in a certain category

### ISSUE THREAD

**Issue by LiliaEn** [gravitee-io/issues#6742]
When there are no APIs in a certain category ( e.g. Featured, Starred), Other APIs section is displayed when Show Promoted APIs Banner toggle is disabled, and it disappears when the toggle is enabled

### Expected Behaviour
Other APIs section should not be displayed when Show Promoted APIs Banner is disabled and/or there are no APIs in a certain category

### Current Behaviour
When there are no APIs in a certain category ( e.g. Featured, Starred), Other APIs section is displayed when Show Promoted APIs Banner toggle is disabled, and it disappears when the toggle is enabled. Please see the screenshots:
<img width="1423" alt="Screenshot 2021-12-15 at 09 33 31" src="https://user-images.githubusercontent.com/49516050/146167444-ce3a1365-00c1-4184-b626-660d0a87914c.png">
<img width="1420" alt="Screenshot 2021-12-15 at 09 35 49" src="https://user-images.githubusercontent.com/49516050/146167494-d94bf772-c1b8-4a12-bd47-b531fb533cd8.png">

### Steps to Reproduce (for bugs)
1. Login to console
2. Make sure Show Promoted APIs banner is enabled
3. Login to Portal
4. Make sure there are no APIs in Featured or Trending or Starred categories
5. Go to Featured, Trending or Starred pages 
6. Check the page and if Other APIs section is displayed
7. Go back to console
8. Disable Show Promoted APIs banner
8. Go back to Portal
9. Go to Featured, Trending or Starred pages 
10. Check the page 

### Your Environment
Version used: 3.14.0-SNAPSHOT (release-test env)
Browser Name and version: Chrome Version 95.0.4638.69
Operating System and version: macOS Big Sur v11.6

**Comment by LiliaEn** [comment]
[6472](https://github.com/gravitee-io/issues/issues/6472)

**Comment by mouligno** [comment]
Other APIs should be removed if we're not displaying promoted banner.

**Comment by LiliaEn** [comment]
Tested on the release-test environment version 3.14.0
Browser: Chrome Version 95.0.4638.69, macOS Big Sur v11.6
Works as expected.
