### ISSUE TITLE
[apim console] Creating simultaneous changes in dictionaries(one user, two tabs) overwrites the changes in one or the other.

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#6750]
## :collision: Describe the bug
If we open two tabs of Dictionaries (using the same user) and make simultaneous/parallel modification on both of them the changes will not be saved fully from both tabs.

## :sunrise_over_mountains: To Reproduce
1. Open two tabs of dictionaries.
2. Create few or one test dictionary, it does not matter on which tab(refresh the other tab to get changes from the other).
3. Create a test property on one of the tabs, save the property then go to the other tab, save property but don't make any and refresh.

![image](https://user-images.githubusercontent.com/57534152/146350511-ce7ade85-445b-4b77-aa3d-15ac7014d274.png)

4. Go back to the first tab where you created a test property and refresh again and you will see that the property you made is gone.

For better understanding view the video in this ticket.

## :rainbow: Expected behavior
All the changes made in the tabs should be synchronized and taken into account.

## :movie_camera: Useful information

View video info with @marijatimovska 

## :computer: Desktop :

 - OS: Windows 10 on Docker-Desktop
 - Browser Chrome

## :warning: Potential impacts

***What are the impacted versions?***
- 3.5.17, 3.5.24

**Comment by mouligno** [comment]
LGTM

**Comment by gaetanmaisse** [comment]
This has been reverted as it causes a lot of other troubles, like https://github.com/gravitee-io/issues/issues/6996.
Concurrent edition of the same data in 2 different tabs isn't handled by Gravitee as of time of writing.
