### ISSUE TITLE
Allow to increase websocket max frame size and max message size in `gravitee.yaml`

### ISSUE THREAD

**Issue by JulienFauvel** [gravitee-io/issues#6751]
# Describe the bug

When sending 6+Mb message through websocket, the client may be disconnected With this log on the gateway:

<span class="error">[vert.x-eventloop-thread-5]</span> [] ERROR i.vertx.core.net.impl.ConnectionBase - Max frame length of 65536 has been exceeded.

# To Reproduce

Repository to reproduce: [https://github.com/JulienFauvel/gravitee-websocket-body-size](https://github.com/JulienFauvel/gravitee-websocket-body-size)

# Expected behaviour

Be able to send bigger than 6Mb body by allowing to configure max frame size and max message size in the `gravitee.yaml` configuration file.

**Comment by vdusauto** [comment]
Any update on this issue ? Can this fix be planned ?

**Comment by gaetanmaisse** [comment]
It looks like it's available https://github.com/gravitee-io/gravitee-node/pull/138 for a year. 
Configuration can be done with the following keys
 - `http.websocket.maxWebSocketFrameSize`
 - `http.websocket.maxWebSocketMessageSize`
 
I will create a PR to reflect this in the `gravitee.yml` file
