### ISSUE TITLE
[Debug mode] View global request/answer of an API call

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6762]
## :rainbow: Feature

**As an** API Publisher

**I want to** view the global request and answer of an API call

**So that** I can understand what's happened

## :sunrise_over_mountains: Additional information

- View headers / body for request / answer

## :link: Dependencies

Link a story or other related things...

## :camera: Mockups 

https://www.figma.com/file/MxLXjCNRnhyMnpapRDgKOT/Try_iT_V4?node-id=291%3A461

## :books: Documentation required

https://github.com/gravitee-io/gravitee-docs/issues/630

## :superhero: Acceptance criteria

- [x] Given an API Call made through the debug mode Then I can view headers and content for both request and answer When I look at the debug mode
- [x] Given an API Call made through the debug mode and failed then I can view header and content for request and error code / error message for response

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :heavy_check_mark: Definition of Done

***For each User Story everything on the list must be considered, select only what was required***
- [ ] Acceptance criteria met and tested
- [ ] Sonar Cloud quality gate passes
- [ ] CircleCi checks pass
- [ ] Cypress or Postman API check passes
- [ ] Test containers passed if modifications on the repository modules
- [ ] Translation for portal UI checked
- [ ] Developer created draft documentation PR
- [ ] New migration scripts checked
Can be run multiple times but only makes changes the first time
Display to user what script has done
- [ ] Validated on appropriate environment
- [ ] Existing test cases refactored

:rocket:

**Comment by LiliaEn** [comment]
Tested on the default env v3.16.0 
Browser: Chrome Version 97.0.4692.99 , macOS Big Sur v11.6
- Checked that the request and response of an API call is correctly displayed;
- Checked that errors are displayed appropriately and  correctly;
- Checked that all inspector elements are displayed: headers, attributes, body, etc.
