### ISSUE TITLE
[Debug mode] Timeline display of API Call

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6763]
## :rainbow: Feature

**As an** API Publisher

**I want to** view the timeline of my API Call

**So that** I can navigate through it

## :sunrise_over_mountains: Additional information

version degradé: 3

- Display policies in their order of execution
- Show on which flow it has been executed
- ~a policy can be executed on both header flow and content flow~
- horizontal Scroll on the timeline
- one level to display policies (up for request / down for answer)

## :link: Dependencies

https://www.figma.com/file/MxLXjCNRnhyMnpapRDgKOT/Try_iT_V4?node-id=291%3A461

## :camera: Mockups 

Insert screenshots, drawings...

## :books: Documentation required

https://github.com/gravitee-io/gravitee-docs/issues/630

## :superhero: Acceptance criteria

- [x] Given an API Call made via the debug mode Then I can understand what's happened When I navigate through the timeline
- [x] Given an API Call made via the debug mode Then i can view the order of policies matching execution order on the gateway when i look at the timeline
- [x] I can scroll through the timeline
- [ ] Given an API Call made via the debug mode Then I can view the request / response policies separate when I look at the timeline (request on the top level, answer down level)

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :heavy_check_mark: Definition of Done

***For each User Story everything on the list must be considered, select only what was required***
- [ ] Acceptance criteria met and tested
- [ ] Sonar Cloud quality gate passes
- [ ] CircleCi checks pass
- [ ] Cypress or Postman API check passes
- [ ] Test containers passed if modifications on the repository modules
- [ ] Translation for portal UI checked
- [ ] Developer created draft documentation PR
- [ ] New migration scripts checked
Can be run multiple times but only makes changes the first time
Display to user what script has done
- [ ] Validated on appropriate environment
- [ ] Existing test cases refactored

:rocket:

**Comment by LiliaEn** [comment]
Tested on the default env v3.16.0 
Browser: Chrome Version 97.0.4692.99 , macOS Big Sur v11.6
- Checked the timeline display of the debug steps
- Checked the order of the policies
- Checked that plans are also displayed in the timeline
- Scrolling
- On Request/On response policies 
- Disabled policies (not displayed)
