### ISSUE TITLE
[Debug mode] View global flow input/output

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6768]
## :rainbow: Feature

**As an** API Publisher

**I want to** view the input/output of a selected flow

**So that** I can understand what's happened

## :sunrise_over_mountains: Additional information

- View headers / body for input / output
- If there is an error, display the policy error code + message and link to specific policy to understand what's happened.
- link to scope ? 

## :link: Dependencies

Link a story or other related things...

## :camera: Mockups 

https://www.figma.com/file/MxLXjCNRnhyMnpapRDgKOT/Try_iT_V4?node-id=291%3A461

## :books: Documentation required

https://github.com/gravitee-io/gravitee-docs/issues/630

## :superhero: Acceptance criteria

- [x] Given an API Call made through the debug mode Then I can view headers and content for both request and answer of a flow When I look at a specific flow in the the debug mode
- [x] Given an API Call made through the debug mode and failed in a flow then I can view header and content for input and error code / error message for output of this flow

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :heavy_check_mark: Definition of Done

***For each User Story everything on the list must be considered, select only what was required***
- [ ] Acceptance criteria met and tested
- [ ] Sonar Cloud quality gate passes
- [ ] CircleCi checks pass
- [ ] Cypress or Postman API check passes
- [ ] Test containers passed if modifications on the repository modules
- [ ] Translation for portal UI checked
- [ ] Developer created draft documentation PR
- [ ] New migration scripts checked
Can be run multiple times but only makes changes the first time
Display to user what script has done
- [ ] Validated on appropriate environment
- [ ] Existing test cases refactored

:rocket:

**Comment by LiliaEn** [comment]
Tested on the default env v3.16.0 
Browser: Chrome Version 97.0.4692.99 , macOS Big Sur v11.6
- Checked that the input/output is displayed correctly in the debug mode for the whole flow
- Checked that errors are displayed when smth fails and the appropriate policy is marked accordingly
