### ISSUE TITLE
[portal] Closed plan

### ISSUE THREAD

**Issue by mikexd91** [gravitee-io/issues#677]
After Plan is used for subscription and plan is subsequently closed. the closed plan will stay in the closed tab with no further actions. Would it be possible to republish this closed plan or actually delete this closed plan. Currently the closed plan is just staying there with no actionable action.

**Comment by brasseld** [comment]
Hi @mikexd91,

That's a good question.
Why would you like to re-open a closed plan ? Do you have a specific use-case in mind ?

**Comment by mikexd91** [comment]
@brasseld Hi sorry for the late message, I have found another way that can satisfy my usage by simply stopping and starting the API, closing issue
