### ISSUE TITLE
Issues when using * as wildcard for paths

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#6771]
When using the (.*) as a wildcard in a API's path, it is working as expected and it can be used as a substitute in a path.

![image](https://user-images.githubusercontent.com/89140082/146750871-d3bd526b-c34f-46a0-8b1c-4b444a968da4.png)

![image](https://user-images.githubusercontent.com/89140082/146750924-9e0d28ec-0947-4c05-8733-a1ea173def33.png)

When using * as a wilcard, in a API's path, it is not working as expected when used as a substitute in a path.

![image](https://user-images.githubusercontent.com/89140082/146751171-76015473-2c8f-42e0-bf23-b9ff5594acb5.png)

![image](https://user-images.githubusercontent.com/89140082/146751239-2c3d52fe-a53d-41a7-a01c-a682867c3fdc.png)

Getting the same issue for a paths based and for design studio API's

Used versions: APIM 3.10.07, 3.5.18

**Comment by ThibaudAV** [comment]
Is it sure that it should work with a `*` and not only with valid RegExp like `(.*)` ?

**Comment by mouligno** [comment]
Imho it's normal tu use RegExp for this. Maybe we could raise a feature request ? @zveljanoski @apoddany

**Comment by gaetanmaisse** [comment]
Closing as a proper `RegExp` should be used
