### ISSUE TITLE
[management] Healthcheck scheduled every seconds instead of configured value after import

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#6775]
## :collision: Describe the bug
When importing an API from previous version as 3.5 with a HealthCheck configured every 5 mins, will trigger a HC every seconds.

In previous version, the HC is configured as : 
```
            "healthcheck": {
              "enabled": true,
              "trigger": {
                "rate": 5,
                "unit": "MINUTES"
              },
```
After the import in 3.10.x, the schedule is configured in the UI as : 
`* */5 * * * *
`
instead of : 
`0 */5 * * * *
`
## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Import the attached API in 3.10.x
2. Check the content of the HC configured at the endpoint level
3. Start the API
4. Go to healthCheck
5. A HC will be triggered every second

## :rainbow: Expected behaviour
Have the HC triggered every 5 Mins
## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop :

***Please complete the following information:***

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***
3.10.x tested in 3.10.5 and 3.10.8

## :link: Dependencies

Link a story or other related things...

**Comment by apoddany** [comment]
[echo-1.txt](https://github.com/gravitee-io/issues/files/7750551/echo-1.txt)

**Comment by mouligno** [comment]
LGTM
