### ISSUE TITLE
[management] Use provided page ID when importing new API

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#6790]
Import an API which does not exist but with page identified by ID that does not correspond to any page on the targeted env

**Current behavior**

200 : API is created with page (auto-generated ID)

**Expected behavior**

200 : API is created with page and should use provided page ID

**Related to :** https://github.com/gravitee-io/issues/issues/6692 (same behavior for plans)

**Comment by mouligno** [comment]
Need to be done with HR ID - required for promotion

**Comment by marcambier** [comment]
As discussed together, the expected behavior of this ticket is not relevant anymore with the new crossId behavior. So I close the ticket.
CrossId and ids target behavior will be properly documented.
