### ISSUE TITLE
Preserve request url with nginx proxy_pass

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6791]
In order to handle multihost url with nginx
Allow to forward a specific url in nginx instead of source url
Send the URL in a HTTP Header ? `X-FORWARDED-FOR` ?

### Expected behavior
Use the correct host provided 

### Current behavior
We use the source url to rewrite url

### Your Environment

* Version used: 3.5.16
* Browser Name and version:
* Operating System and version:

**Comment by apoddany** [comment]
Can we have some feedback about the current status about this one (specification conformance) ?

**Comment by gaetanmaisse** [comment]
Closing since the original ticket has not received any feedback.
