### ISSUE TITLE
[management] UI bug in Platform Overview, boxes get unchecked while data and filters stay the same and refreshes page number to one.

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#6792]
## :collision: Describe the bug
In Dashboard in Platform Overview (all dashboards), when we go to Top APIs and select for example two filters/boxes on page one then go to page two and select one or few more boxes the Platform Overview will refresh and go back to page one and if we go back to page two we see that the boxes are unchecked and if here we go back again on page on some of the boxes will be unchecked also. While doing this all the filters above are intact as well as the data (in Status) is correct. 

## :sunrise_over_mountains: To Reproduce
1. Import or Create enough APIs so you have more than one page for testing.
2. Go to Dashboard(Platform Overview) and in Top APIs select few boxes/filters on the first page, now go to the second page and select one or few more you will se that it will refresh and you will be back on page one. Now to go page two and you will see that the boxes in page two some or all are unchecked and now to back to page one and same will happen here, you will see that the boxes, some or all are unchecked. All this time look at the filters above and the number in Status, at it will stay the same and it will be correct. Only the boxes "look like" they are unchecked.

![image](https://user-images.githubusercontent.com/57534152/147232419-8c7b9719-205d-4636-9a59-7b6ba1d9eb24.png)

## :rainbow: Expected behavior
The boxes/filters we check should always stay the same. This it not that big of a problems if the number of APIs is small, 2-3 pages but what if the number of pages is 100? It would not be practical.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material:

- [ticket.zip](https://github.com/gravitee-io/issues/files/7769030/ticket.zip)

## :computer: Desktop :

***Please complete the following information:***
 - OS: Windows 10, Docker-Desktop
 - Browser: Google Chrome

## :warning: Potential impacts

***What are the impacted versions?***
-3.5.26

**Comment by gaetanmaisse** [comment]
This issue has been closed as this screen will be reworked during the Angular migration, the new screen will land in APIM in 2023.
