### ISSUE TITLE
[Management] Choose between API Key or Application Key

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6793]
## :rainbow: Feature

**As a** API Consumer

**I want to** choose between API Key and Application Key 

**So that** it could be easier to deal with multiple APIs

## :sunrise_over_mountains: Additional information

- Option is proposed at the 2nd subscription on plans with API Key
- Should be stored at application level
- Can't be updated once behavior is selected

## :link: Dependencies

Link a story or other related things...

## :camera: Mockups 

Insert screenshots, drawings...

## :books: Documentation required

https://github.com/gravitee-io/gravitee-docs/issues/636

## :superhero: Acceptance criteria

- [ ] Given an application with a subscription on an API-Key plan Then I can choose between API Key or Application Key behavior When I subscribe to another API-Key plan.
- [ ] Given an application on Application Key mode Then I can use the Application Key When I subscribe to a new API-Key plan
- [ ] Given an application on API-Key mode Then a new API Key When I subscribe to a new API Key Plan.

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :heavy_check_mark: Definition of Done

***For each User Story everything on the list must be considered, select only what was required***
- [ ] Acceptance criteria met and tested
- [ ] Sonar Cloud quality gate passes
- [ ] CircleCi checks pass
- [ ] Cypress or Postman API check passes
- [ ] Test containers passed if modifications on the repository modules
- [ ] Translation for portal UI checked
- [ ] Developer created draft documentation PR
- [ ] New migration scripts checked
Can be run multiple times but only makes changes the first time
Display to user what script has done
- [ ] Validated on appropriate environment
- [ ] Existing test cases refactored

:rocket:

**Comment by RubenMMSantos** [comment]
When “Allow to share API key on an application” is enabled on settings, there is no popup displayed when subscribing an application to a new API-key plan (the application already has 1 subscription to another API-Key plan active)

**Comment by RubenMMSantos** [comment]
Issue tested on environment https://apim-master-console.cloud.gravitee.io/ with APIM version 3.17
Scenarios covered:

- [ ] popup is displayed when creating subscriptions between existing Application and more than 1 API (popup is displayed when creating the 2nd subscription)
- [ ] when creating an Application and at least 2 subscriptions to APIs are created, popup is displayed when finishing the creation journey
- [ ] popup is displayed when creating a subscription via API > Subscriptions
- [ ] after selecting "Shared API Key" option, user cannot change selection
- [ ] Any subscription created after selecting "Shared API Key" is automatically created with "Shared API Key" and user cannot choose "API Key / Shared API Key"
