### ISSUE TITLE
[Management] Accept/Reject Application Key subscription

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6798]
## :rainbow: Feature

**As a** API Publisher

**I want to** accept or reject a subscription using Application Key

**So that** I can manage my APIs

## :sunrise_over_mountains: Additional information

- Info message to inform that the application is in Application Key mode
- Two options only Accept or Reject
- Not possible to update the App key info
- Management API - 400 if trying to override API-Key info 

## :link: Dependencies

Link a story or other related things...

## :camera: Mockups 

Insert screenshots, drawings...

## :books: Documentation required

https://github.com/gravitee-io/gravitee-docs/issues/636

## :superhero: Acceptance criteria

- [x] Given a subscription using Application Key Then the application can use my API when I accept it
- [x] Given a subscription using Application Key Then the application can not use my API when I reject it

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :heavy_check_mark: Definition of Done

***For each User Story everything on the list must be considered, select only what was required***
- [ ] Acceptance criteria met and tested
- [ ] Sonar Cloud quality gate passes
- [ ] CircleCi checks pass
- [ ] Cypress or Postman API check passes
- [ ] Test containers passed if modifications on the repository modules
- [ ] Translation for portal UI checked
- [ ] Developer created draft documentation PR
- [ ] New migration scripts checked
Can be run multiple times but only makes changes the first time
Display to user what script has done
- [ ] Validated on appropriate environment
- [ ] Existing test cases refactored

:rocket:

**Comment by RubenMMSantos** [comment]
ticket verified on envir https://apim-master-console.cloud.gravitee.io/, APIM version 3.17
acceptance criteria passed
