### ISSUE TITLE
[Management] Prevent Application Key update

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6800]
## :rainbow: Feature

**As a** API Publisher

**I can not** update an Application Key

**So that** it doesn't impact other subscriptions

## :sunrise_over_mountains: Additional information

- not possible to update App Key
- message that it can be done at application level
- Management API - 400 if trying to update a shared key

## :link: Dependencies

Link a story or other related things...

## :camera: Mockups 

Insert screenshots, drawings...

## :books: Documentation required

https://github.com/gravitee-io/gravitee-docs/issues/636

## :superhero: Acceptance criteria

- [x] Given a subscription with Application Key Then I can't update the application key When I am at API level.

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :heavy_check_mark: Definition of Done

***For each User Story everything on the list must be considered, select only what was required***
- [ ] Acceptance criteria met and tested
- [ ] Sonar Cloud quality gate passes
- [ ] CircleCi checks pass
- [ ] Cypress or Postman API check passes
- [ ] Test containers passed if modifications on the repository modules
- [ ] Translation for portal UI checked
- [ ] Developer created draft documentation PR
- [ ] New migration scripts checked
Can be run multiple times but only makes changes the first time
Display to user what script has done
- [ ] Validated on appropriate environment
- [ ] Existing test cases refactored

:rocket:

**Comment by RubenMMSantos** [comment]
ticket verified on envir https://apim-master-console.cloud.gravitee.io/, APIM version 3.17
acceptance criteria passed
