### ISSUE TITLE
[Management] Awareness that a subscription is made through Application Key

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6801]
## :rainbow: Feature

**As a** API Publisher

**I want to** be aware that a subscription with an Application Key

**So that** i can manage my security

## :sunrise_over_mountains: Additional information

- Info message on subscription details
- Notification in the console when an application using my API switch to Application Key (at 2nd subscription)

## :link: Dependencies

Link a story or other related things...

## :camera: Mockups 

Insert screenshots, drawings...

## :books: Documentation required

https://github.com/gravitee-io/gravitee-docs/issues/636

## :superhero: Acceptance criteria

- [x] Given a subscription with Application Key Then I can view that it's using application key When I check subscriptions details.

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :heavy_check_mark: Definition of Done

***For each User Story everything on the list must be considered, select only what was required***
- [ ] Acceptance criteria met and tested
- [ ] Sonar Cloud quality gate passes
- [ ] CircleCi checks pass
- [ ] Cypress or Postman API check passes
- [ ] Test containers passed if modifications on the repository modules
- [ ] Translation for portal UI checked
- [ ] Developer created draft documentation PR
- [ ] New migration scripts checked
Can be run multiple times but only makes changes the first time
Display to user what script has done
- [ ] Validated on appropriate environment
- [ ] Existing test cases refactored

:rocket:

**Comment by RubenMMSantos** [comment]
Feature confirmed as implemented as expected
Verified on https://apim-master-console.cloud.gravitee.io & https://apim-master-portal.cloud.gravitee.io
