### ISSUE TITLE
[Portal] Alerts - Add a description field for alert

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6803]
:scroll:
**As an API Consumer**
**I want to describe the behavior of my alert**
**So that I can provide more information**

### :information_source: **Information**
- Text field to store custom info
- Not required to validate an alert
- Add it to email notification

### :link: **Dependencies & Linked stories**

- Alert Engine

### **Mockups**

<img width="1459" alt="Capture d’écran 2021-12-24 à 07 35 54" src="https://user-images.githubusercontent.com/3227037/147325346-be264163-3972-46ea-abb9-961af1e0f545.png">

### **Documentation required**
:link:Provide link to the issue for documentation update

### **Acceptance criteria**
- [ ] Given '...'
- [ ] Then '...'
- [ ] When '...'

### :warning: **Potential impacts**
*To be populated after dev*

### :ballot_box_with_check: **Definition of Done checklist**
***For each User Story everything on the list must be considered, select only what was required***
- [ ] Acceptance criteria met and tested
- [ ] Sonar Cloud quality gate passes
- [ ] CircleCi checks pass
- [ ] Cypress or Postman API check passes
- [ ] Test containers passed if modifications on the repository modules
- [ ] Translation for portal UI checked
- [ ] Developer created draft documentation PR
- [ ] New migration scripts checked
Can be run multiple times but only makes changes the first time
Display to user what script has done
- [ ] Validated on appropriate environment
- [ ] Existing test cases refactored

:checkered_flag::superhero:

**Comment by LiliaEn** [comment]
Tested locally the following scenarios:
- Description field is displayed
- Alert can be added with a description
- Alert can be added without a description
- Description can be edited
- Email notification contains the description when it's added
- Email notification doesn't contain description when it's not added
