### ISSUE TITLE
[gateway] [management-api] Have a PID file for Gravitee processes

### ISSUE THREAD

**Issue by blackillzone** [gravitee-io/issues#681]
### Expected Behavior
It would be a quick and good feature to have a PID file once the service is started (for both management service and gateway service).

### Current Behavior
No PID file.

### Possible Solution
From here, I'm actually using systemd to handle Gravitee as a Linux service. There is an option for PID file, but it will only check the presence of an existing PID file, and remove it if it persist after a service stop. It will not create it.
So it should be in the start script as a java option (for example: -Dpidfile.path=/var/run/gravitee.pid). What do you think ?

### Context
A PID file permit to quickly check the PID of the process with standard monitoring solution. We could say that's old but it's a standard things on Linux, to store process ID, and almost all monitoring scripts are using this to get the process ID, and hen check the availability of this process.

### Your Environment

* Version used: 1.6.1
* Browser Name and version: 
* Operating System and version: CentOS 7.2

**Comment by NicolasGeraud** [comment]
hi @blackillzone ,
sounds good. pidfile path should also be configured in the gravitee.yml.

Do you want to implement it ?

**Comment by blackillzone** [comment]
Great, I would like to, but you're too quick for me :).

And the idea to add it as a configuration variable inside the gravitee.yml is a good bonus, but not mandatory for us at the moment, if we already have, at least, one pid file available.

But it would be a welcome feature for next versions :).

Thanks for reactivity !

**Comment by brasseld** [comment]
Hi @blackillzone 
Running gravitee component as a daemon: https://docs.gravitee.io/apim_installguide_gateway.html

SY !
