### ISSUE TITLE
[management] role creation with space character

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#6810]
When creating a role with spaces in name, user is redirected to en empty page.

**Current behavior**
- In console > organization settings > role
- Click 'add a role'
- Enter a role name with spaces
- User is redirected to an empty page (cause role name spaces are replaced by underscores in created role)

**Expected behavior**
- User should be redirected to correct role page

![image](https://user-images.githubusercontent.com/87964124/147344753-b2d8f091-008a-4c2a-97ea-78bcd8d4d0b9.png)
![image](https://user-images.githubusercontent.com/87964124/147344859-9869f697-07bc-48b4-90bd-90bdd95a057f.png)
![image](https://user-images.githubusercontent.com/87964124/147344898-dc3c8cf4-355d-41e8-93f5-c9250531b240.png)

**Comment by mouligno** [comment]
LGTM
