### ISSUE TITLE
Investigation - Handle application key

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6812]
### Questions to investigate 

- How to handle the shared key ? keep current behavior and update all api keys to the same value ? Store a new collection of shared key ? 
- Should we anticipate a way to switch from a mode to another ? What are the impact on the implementation choice ? 
- impact of moving to a new collection ? to keep current behavior ? Risk of each ? 
-

**Comment by marcambier** [comment]
What has been discussed during our first investigation session :

- Database model changes, to validate with architecture team regarding gateway performances :
	- in table application :
		+ add enum (UNDEFINED (default) / NOT_SHARED_API_KEY / SHARED_API_KEY)
	- in table keys :
		- subscription => subscriptions[]
		- api => apis[] (check if it's relevant to keep this data)
		- plan => plans[] (check if it's relevant to keep this data)
	
On the 2nd subscription, user chooses his API KEY mode (shared or not), which defined the enum in application table.
Once this enum has been defined, it will never change.
