### ISSUE TITLE
No warning message when API is not up to date

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#6815]
## :collision: Describe the bug:
We have two users, both direct members of the API, in my case I uses admin and api1(with extended API config. in API Scope, meaning api1 can create/delete/update the Design of the API). When more than two users are making changes in Design. create/delete/update policies non of them gets notified that the API is not up to date and the changes are getting deployed and it becomes one big mess because the changes are getting overwritten.

Similar to -> https://github.com/gravitee-io/issues/issues/6624

## :sunrise_over_mountains: To Reproduce
1. User A and user B are on the same configuration page -> Design.
2. User A makes a modification in the Policies and saves the change but does not deploy it, User B makes changes on the same Policy and does nor get notified on the change of the user A.
3. Then user B deploys his change and User A still does not get any warning that the API is not up to date.
4. Then user A deploys his change and overwrites the changes of the User B and here user B does not get any messages.

Meaning no matter what changes do both user make on the Policies both users don't get notified.
I tried more scenarios not just in Policies and I did not get notified.

## :rainbow: Expected behavior
We should always get notified at least if the changes on the policies are deployed if more than two users are on the same page in this case Policies.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material:

![image](https://user-images.githubusercontent.com/57534152/147493083-f9130ba9-caa4-4fe2-8cc3-eb5fa4cdf726.png)

## :computer: Desktop :

***Please complete the following information:***
 - OS: Windows 10
 - Browser: Google Chrome

## :warning: Potential impacts

***What are the impacted versions?***
- 3.5.27

**Comment by mouligno** [comment]
Hi @marijatimovska 
I think there is some issue with the Nginx configuration, you should have the warning message. What kind of configuration do you use ?

**Comment by mouligno** [comment]
It should work with ETag and If-Match HTTP headers and look likes Nginx is overwriting theses.
