### ISSUE TITLE
[Portal] Choose between API Key or Application Key

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6816]
## :rainbow: Feature

**As a** API Consumer

**I want to** choose between API Key or Application Key

**So that** I can easily manage my API

## :sunrise_over_mountains: Additional information

- Choice is made on 2nd subscription on an API Key Plan
- Choice is definitive
- Message to confirm, explain behavior

## :link: Dependencies

Link a story or other related things...

## :camera: Mockups 

https://www.figma.com/file/XhlNukO4Tve88WDFjIr1ym/Shared_key_portal?node-id=0%3A1

## :books: Documentation required

https://github.com/gravitee-io/gravitee-docs/issues/636

## :superhero: Acceptance criteria

- [x] Given an API Consumer Then I can choose between API Key and Application Key When I subscribe on a second API-Key plan
- [x] Given an API Consumer and an application in API-Key mode then a new API Key is generated When I subscribe to an API-Key plan 
- [x] Given an API Consumer and an application in App-Key mode then I can use the same key when i subscribe a new API-Key plan
- [x] Check the behavior with toggle ON/OFF from #6990 

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :heavy_check_mark: Definition of Done

***For each User Story everything on the list must be considered, select only what was required***
- [ ] Acceptance criteria met and tested
- [ ] Sonar Cloud quality gate passes
- [ ] CircleCi checks pass
- [ ] Cypress or Postman API check passes
- [ ] Test containers passed if modifications on the repository modules
- [ ] Translation for portal UI checked
- [ ] Developer created draft documentation PR
- [ ] New migration scripts checked
Can be run multiple times but only makes changes the first time
Display to user what script has done
- [ ] Validated on appropriate environment
- [ ] Existing test cases refactored

:rocket:

**Comment by omatthewsgravitee** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Graviteeio---API-Management-601c1f73be51260015c7bb26/issues/gravitee-io/issues/6816?planning-poker) with ZenHub @a-cordier @marcambier @RubenMMSantos
