### ISSUE TITLE
[Portal] Revoke Application Key

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6818]
## :rainbow: Feature

**As a** API Consumer

**I want to** revoke my Application Key

**So that** manage security

## :sunrise_over_mountains: Additional information

- Revoke for all APIs

## :link: Dependencies

Link a story or other related things...

## :camera: Mockups 

https://www.figma.com/file/XhlNukO4Tve88WDFjIr1ym/Shared_key_portal?node-id=0%3A1

## :books: Documentation required

https://github.com/gravitee-io/gravitee-docs/issues/636

## :superhero: Acceptance criteria

- [ ] Given an API Consumer then I can not access my APIs with my Application when I revoke it

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :heavy_check_mark: Definition of Done

***For each User Story everything on the list must be considered, select only what was required***
- [ ] Acceptance criteria met and tested
- [ ] Sonar Cloud quality gate passes
- [ ] CircleCi checks pass
- [ ] Cypress or Postman API check passes
- [ ] Test containers passed if modifications on the repository modules
- [ ] Translation for portal UI checked
- [ ] Developer created draft documentation PR
- [ ] New migration scripts checked
Can be run multiple times but only makes changes the first time
Display to user what script has done
- [ ] Validated on appropriate environment
- [ ] Existing test cases refactored

:rocket:

**Comment by RubenMMSantos** [comment]
ticket verified and confirmed as working as expected
verified on https://apim-master-console.cloud.gravitee.io, APIM 3.17 & https://apim-master-portal.cloud.gravitee.io
Scenarios checked:
- [ ] Shared API Key can be revoked in Portal and its reflected on Console
- [ ] Shared API Key can be revoked in Console and its reflected on Console
- [ ] Revoked Shared API key (done on Portal) is no longer valid to make calls to the API
