### ISSUE TITLE
Deleted alert only disables it in AlertEngine

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#6826]
## :collision: Describe the bug
When I delete an alert, it disables it in AE instead of deleting it.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
0. Configure an APIM/AE platform
1. Create an alert in APIM
2. Call the technical api in AE `GET http://localhost:18072/_node/triggers`: you see your trigger
3. Delete the alert in APIM
4. Call the technical api in AE `GET http://localhost:18072/_node/triggers`: you see your trigger

## :rainbow: Expected behaviour
the trigger must disappears from AE

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***
Perhaps the same behaviour in AM

***What are the impacted versions?***
I've tested with APIM 3.13 and AE 1.5 but I think the unregister method in the same since v1.x

**Comment by mouligno** [comment]
Need to check if we need to update the call to AE or the behavior in AE

**Comment by mouligno** [comment]
@Johngren any thoughts on this ?

**Comment by ppgravitee** [comment]
@remisultan // @passionne is it fixed now?

**Comment by remisultan** [comment]
@ppgravitee 

Right now Alert Engine only allows enabling/disabling triggers and not deleting

**Comment by gaetanmaisse** [comment]
Closing as it looks to be an Alert Engine improvement/change more than an APIM bug
