### ISSUE TITLE
[gateway] Javascript Policy returns 500 OK in case of failure

### ISSUE THREAD

**Issue by a-cordier** [gravitee-io/issues#6831]
## :collision: Describe the bug

Javascript Policy returns 500 OK in case of failure

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to the Proxy Design Section
2. Add a Javascript Policy with an invalid syntax
3. Call the gateway, passing through the policy
4. Get a 500 OK

## :rainbow: Expected behaviour

The Http Response message should be Internal Server Error, Not OK

## :movie_camera: Useful information

```shell
curl -i localhost:8082/products
HTTP/1.1 500 OK
X-Gravitee-Transaction-Id: 4c90e88e-5ef8-427b-90e8-8e5ef8027bde
X-Gravitee-Request-Id: 4c90e88e-5ef8-427b-90e8-8e5ef8027bde
X-Powered-By: Express
Vary: Origin, Accept-Encoding
X-Requested-By: Shubhendu Madhukar
Content-Type: application/json
ETag: W/"6b-lMc+A/YrQW0b/oPlcuH6lVP5F7I"
Date: Fri, 31 Dec 2021 11:32:26 GMT
Connection: close
Keep-Alive: timeout=5
Content-Length: 237

{"message":"<eval>:1:37 Expected an operand [...]"}
```

**Comment by RubenMMSantos** [comment]
issue verified on environment 3.13.X
https://apim-3-13-x-console.cloud.gravitee.io/
