### ISSUE TITLE
[Management] Access more API info from Javascript policy

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6832]
## :rainbow: Feature

As an API Publisher, I want to access API info from Javascript Policy in order to maximize value of it : 
- API properties
- Dictionaries (TBC)

## :sunrise_over_mountains: Additional information

- `{#properties['my-property']}` is currently raising a 500 error
- we should have a way to access all API Properties 

## :link: Dependencies

https://github.com/gravitee-io/issues/issues/7207

## :camera: Mockups 

Insert screenshots, drawings...

## :books: Documentation required

Provide link to the issue for documentation update

## :superhero: Acceptance criteria

- [ ] Given an API with API Properties Then I can use one of this property When I configure JS Policy
- [ ] Given a environment with at least one dictionary Then I can use one of this dictionary property When I configure JS Policy

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :heavy_check_mark: Definition of Done

***For each User Story everything on the list must be considered, select only what was required***
- [ ] Acceptance criteria met and tested
- [ ] Sonar Cloud quality gate passes
- [ ] CircleCi checks pass
- [ ] Cypress or Postman API check passes
- [ ] Test containers passed if modifications on the repository modules
- [ ] Translation for portal UI checked
- [ ] Developer created draft documentation PR
- [ ] New migration scripts checked
Can be run multiple times but only makes changes the first time
Display to user what script has done
- [ ] Validated on appropriate environment
- [ ] Existing test cases refactored

:rocket:

**Comment by gcusnieux** [comment]
@mouligno  It's really a bug? 
There is nothing in the documentation that explains that you can use EL.
It's the same thing on the groovy policy
