### ISSUE TITLE
[management] password expiration policy

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#6836]
## :rainbow: Feature

**As a** 'application owner / domain owner'

**I want to** 'set a maximum password duration'

**So that** 'when the password expires the user is redirected to setting password page'

## :sunrise_over_mountains: Additional information

- Add new expiration settings into the password policy
- Store lastResetPasswordDate in the User profile
- Check profile information during login process
  - if expiration policy is activated -> check the current date against lastResetPasswordDate
- If the password has been expired, add an information message into the login page (warning zone)

## :books: Documentation required

Provide link to the issue for documentation update

## :superhero: Acceptance criteria

- [ ] Given 'an end user wants to sign in'
- [ ] When 'the password is expired'
- [ ] Then 'an error message is displayed on the login page to tell the user to set a new password'

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

We must not have any regression issues related to the password policy settings 

:warning: remember to test with a user coming from social IDP to validate that this kind of user are not impacted by this feature.

***What are the impacted versions?***

3.16

## :heavy_check_mark: Definition of Done

***For each User Story everything on the list must be considered, select only what was required***
- [ ] Acceptance criteria met and tested
- [ ] Sonar Cloud quality gate passes
- [ ] CircleCi checks pass
- [ ] Cypress or Postman API check passes
- [ ] Test containers passed if modifications on the repository modules
- [ ] Translation for portal UI checked
- [ ] Developer created draft documentation PR
- [ ] New migration scripts checked
Can be run multiple times but only makes changes the first time
Display to user what script has done
- [ ] Validated on appropriate environment
- [ ] Existing test cases refactored

:rocket:

**Comment by patelami** [comment]
Env: nightly
Result: PASS


Given I have set password expiration day to 1 on application level
And I instantiate login flow 
Then I should see password expired message on sign in form

<img width="485" alt="Screenshot 2022-02-21 at 15 25 04" src="https://user-images.githubusercontent.com/14215437/154963900-939736a9-d9c5-4d1a-94e4-fc3c333e6989.png">
 

Given I navigate to Users > Users activity
Then
I should see last password reset date 
<img width="281" alt="Screenshot 2022-02-21 at 15 27 03" src="https://user-images.githubusercontent.com/14215437/154964279-8d6fd50b-0f68-4c04-b373-0e5e7ad44ad5.png">

Given I have set inherit configuration switch to 1
And the password expiration is set to 1 day on domain level
And I instantiate login flow
Then I should not be sign in
And I should see error message: `login_failed: account's password is expired`

Given I have set inherit configuration switch to 0
And I go to application level password policy I set expiration date to 0
And I go to domain level settings and I set expiration date to 1
And I instantiate login flow
Then I should be successfully login to the application
