### ISSUE TITLE
generate console services from swagger/openapi

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#6838]
Generate services in console-ui from swagger/openapi definition as it is done for portal

**Comment by gaetanmaisse** [comment]
Discussion: 
 - Generate only models? Ask feedback from Cockpit
 - If services are generated, what about AngularJS vs Angular vs Cypress?

To keep in mind: 
 - Does the boilerplate worths it?
 - We will still need custom services for custom use cases
