### ISSUE TITLE
[portal] keep generated-sources out of git

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#6841]
Openapi generated sources should not be part of the git repository.
It should be regenerated during the build on CI side.

**Comment by gaetanmaisse** [comment]
Discussion:
 - Should we really remove it?
 - Should we add a check on CI to ensure each time the openapi file is updated the Portal SDK is updated too?

**Comment by marcambier** [comment]
I close this ticket, as dicussed with team, the current state is OK.
