### ISSUE TITLE
document release process

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#6842]
Document release process

- Map/Chart of all steps and their purpose
- Cheatsheet -> which commands to run to release the product
- Process for a global release vs a single component

**Comment by phiz71** [comment]
Is this document enough ?
https://gravitee.slab.com/posts/the-apim-release-n2agyj7y

**Comment by sursak123** [comment]
https://app.diagrams.net/?mode=google&gfw=1#G12Dvm4es6T-RW0I_gusaqifUwtmegtOnj
