### ISSUE TITLE
Improve Readyness probes in the Helm charts used for our dev envs

### ISSUE THREAD

**Issue by gaetanmaisse** [gravitee-io/issues#6845]
## :rainbow: Description

With the current helm chart + values we are using for our dev environment there are some downtimes each time a new version is deployed. 

This is due to a lack of configuration of liveness and readiness probe. When a new version is deployed, the new pods are started and k8s is thinking right away that everything is running. So the "old" pods are killed even if the new ones aren't ready, leading to downtime for the users.

It would be nice to have a real rollout deployment with zero downtime.

## :sunrise_over_mountains: Additional information

Some first investigations around this have been made for ElementZero env, see:
 - https://github.com/gravitee-io/gravitee-element-zero/commit/be2f5a45d15b3f57995b2e8d31ad18684f311165
 - https://github.com/gravitee-io/gravitee-element-zero/commit/8e5749c3b6a7811b221d8e5ff0c0e6b68d43d39a

**Comment by sursak123** [comment]
Created ticket for this in techops jira and assigned to Alex.  As alex is not in zenhub, i assigned to myself for tracking. Will keep updated status based on techops daily standup update on this ticket
