### ISSUE TITLE
[console] Link to my account is broken in org settings

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6848]
## :collision: Describe the bug
In Organization settings, I can't access my account. 

Other links work.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to Organization settings
2. Click on your avatar 
3. Click on My account
4. Nothing happen

## :rainbow: Expected behaviour
Link to work

## :movie_camera: Useful information
Only with this link with new screens

## :computer: Desktop :

***Please complete the following information:***

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by phiz71** [comment]
Already present, at least in 3.10
