### ISSUE TITLE
[management] Path-mapping import fail

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6856]
Related to https://github.com/gravitee-io/issues/issues/6723 

### Describe the bug
When I want to update/create path mappings in Analytics through Swagger the path mappings are not created or just /.

For testing purpose I am using the Petstore API (ex:https://petstore.swagger.io/v2/swagger.json)

### To Reproduce

- Import an API through file or URL(ex:https://petstore.swagger.io/v2/swagger.json).
- Go to Analytics > Path mappings and import your swagger for path mapping
- Nothing is created or updated

### Expected behavior
when I want to update/create path mappings in Analytics through Swagger all the path mappings should be created.

### Desktop (please complete the following information):

OS: Windows 10
Browser Chrome
What are the impacted versions?- 3.5.16, 3.5.24

**Comment by phiz71** [comment]
should be fixed with https://github.com/gravitee-io/gravitee-api-management/pull/1041

**Comment by phiz71** [comment]
Fixed
