### ISSUE TITLE
[APIM - Organization Settings - Sharding Tags] Unable to delete sharding tags

### ISSUE THREAD

**Issue by RubenMMSantos** [gravitee-io/issues#6862]
When trying to delete a sharding tag, the confirmation pop up is displayed but after clicking "delete" nothing happens and the sharding tags remain and no info is displayed as to why it wasn't deleted. No erros displayed on console

### Expected Behavior
After clicking "delete" on pop up, sharding tag should be deleted

### Current Behavior
After clicking "delete" on pop up, sharding tag is not deleted

### Steps to Reproduce (for bugs)
1. go to https://apim-release-test-console.cloud.gravitee.io/#!/organization/settings/tags
2. select sharding tags from side menu
3. if shardings tags is empty, create a sharding tag
4. try to delete a sharding tag

link to video of issue: https://drive.google.com/file/d/1trhkI721vRozBmeZhPucR6FHgA4OtoFw/view?usp=sharing

### Your Environment
* Version used: https://apim-release-test-console.cloud.gravitee.io/ (3.14)
* Browser Name and version: google chrome Version 96.0.4664.110
* Operating System and version: macOS Big Sur v11.6.1

**Comment by mouligno** [comment]
I think the delete action is not mapped for new screens.

**Comment by mouligno** [comment]
LGTM

**Comment by LiliaEn** [comment]
Tested on the release-test env, version 3.14.0
Browser: Chrome Version 95.0.4638.69, macOS Big Sur v11.6
Works as expected.
