### ISSUE TITLE
[repository][JDBC] Run TestContainer tests on a specific version of a database

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#6867]
## :rainbow: Feature

**As a** Developer

**I want to**  easily run TestContainers on repositories with the version of the DB I want. (e.g. postgresql 12.6)

**So that** tests with TestContainers could be run on every supported DB (See https://docs.gravitee.io/apim/3.x/apim_installguide_repositories_jdbc.html#supported_databases)

## :sunrise_over_mountains: Additional information

The version could be specified in the `jdbcType` env var.
```
mvn test -DjdbcType=posgtresql-tc~12.6
```

We could also use this ticket to make some cleaning in the TestContainer configuration, 2 containers are started when running the tests (one of the two is not used)
And should we keep "embedded" database ?

:rocket:

**Comment by marcambier** [comment]
Questions :
- how to handle launching database tests for all versions ? CircleCi ? Makefile ? (handle it on another ticket)
