### ISSUE TITLE
[APIM - Portal] Unable to reply to a rating

### ISSUE THREAD

**Issue by RubenMMSantos** [gravitee-io/issues#6869]
After rating an API on portal, i am unable to reply to the rating comment with another user that has permission to do, clicking on the REPLY button simply has no action and no error is displayed

### Expected Behavior
As a user with permissions i should be able to reply to an API rating

### Current Behavior
i am unable to reply to an API rating

### Steps to Reproduce (for bugs)
1. go to ****/catalog/api/8ec6848e-5ae8-47a7-8684-8e5ae897a7a9?aq=ALL
2. login as api1
3. search for api "New One"
4. Notice the API has 3 ratings
5. Try to reply to any of the ratings by clicking on the "Reply" button
6. Notice it has no action at all

### Your Environment
Version used: 3.14
Browser Name and version: google chrome Version 96.0.4664.110
Operating System and version: macOS Big Sur v11.6.1

**Comment by phiz71** [comment]
Already present, at least in 3.10.

**Comment by phiz71** [comment]
Actually, the problem can be reproduced on https://components.gravitee.io/?path=/story/molecules-gv-rating-list--add-answer

It's a UI-component bug

**Comment by RubenMMSantos** [comment]
Issue verified and confirmed as fixed.
Verified on envir 3-10-X
![Screenshot 2022-05-23 at 12.12.15.png](https://images.zenhubusercontent.com/612518f668e84e3f309d282d/012ced95-6f56-46f5-9f2f-b6a887734718)
