### ISSUE TITLE
[gateway] : Downgrade Vert.x version to 3.4.1

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#687]
Since Vert.x 3.4.2 we have conflict with the policy gravitee-policy-groovy causing the following error : 

`Caused by: java.lang.ClassNotFoundException: org.codehaus.groovy.runtime.m12n.PropertiesModuleFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 108 common frames omitted`

Rollback to the 3.4.1 version fix the problem.

**Comment by brasseld** [comment]
See https://github.com/vert-x3/vertx-examples/commit/891905fe402cb21fcb981af8cc56e6c6f165ebfe
