### ISSUE TITLE
[management] Deleted dynamic dictionnary is never undeploy

### ISSUE THREAD

**Issue by gcusnieux** [gravitee-io/issues#6870]
## :collision: Describe the bug
When we delete a dynamic dictionary the dictionnary is always deploy in the gateway. 

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Create a dynamic dictionary "dynamic" with HTTP provider
**target:** https://api.gravitee.io/echo
**jolt:**
```
[
  {
    "operation": "shift",
    "spec": {
      "headers": {
        "*": {
          "$": "[#2].key",
          "@": "[#2].value"
        }
      }
    }
  }
]
```  
2. Create an api with a mock policy and return 
```
{
  "host": "{#dictionaries['dynamic']['Host']}"
}
```
3. Call the api with `curl http://localhost:8083/echo` and see
```
{
  "host": "api.gravitee.io"
}
```
4. Delete the dynamic dictionary 
5. Call the api with `curl http://localhost:8083/echo` and see
```
{
  "host": "api.gravitee.io"
}
```
## :rainbow: Expected behaviour
After dictionary deletion, we should see an error after the curl and see 
```
The template evaluation returns an error. Expression:
{
  "host": "{#dictionaries['dynamic']['Host']}"
}%
```

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop :

***Please complete the following information:***

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by phiz71** [comment]
Ok
