### ISSUE TITLE
[gateway] [webauthn] include device identifier at webauthn login

### ISSUE THREAD

**Issue by remisultan** [gravitee-io/issues#6871]
## :collision: Describe the bug
When we login via Webauthn, we are not passing the device identifier when this one is active

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Login to AM
2. Click on Login Settings (Or within your app) and activate `Passwordless`
3. Enable MFA with Device Identifier
3. Initiate the login flow and login
4. Notice you are not asked to keep the device

## :rainbow: Expected behaviour
The deviceId should be passed hence activating / disabling MFA regarding if the device is known

**Comment by patelami** [comment]
Env: nightly
Result PASS
