### ISSUE TITLE
[apim] Upgrade lucene to 8.x or 9.x

### ISSUE THREAD

**Issue by gcusnieux** [gravitee-io/issues#6876]
## 🧰  Technical improvements

We are using the latest version of Lucene 7.x, version 8.x was released in 2019 and version 9.x was released in 2021.
According to the changelogs, there are some improvements on the performance and the query possibilities.
But the api and index format has changed, it is not enough to just change the version.

**Comment by k-oliver** [comment]
@gcusnieux Lucene has a backwards codecs libary that should allow to read and update older indexes too. Please consider updating to lucene 8.x.

**Comment by gaetanmaisse** [comment]
Closing as it has be done
