### ISSUE TITLE
[policy] [basic-auth] Protect api w/ simple basic auth

### ISSUE THREAD

**Issue by bitsofinfo** [gravitee-io/issues#689]
How can I protect an api just with basic-auth, is this supported? I can't seem to find it in the UI or docs

**Comment by brasseld** [comment]
Hi @bitsofinfo 

We are not supporting basic-authentication currently cause it's not really used when developing APIs.

But we can think about a Basic authentication policy.
What would be your users source ? Database, LDAP, inline ?

**Comment by bitsofinfo** [comment]
its actually used quite a bit more than you think! Lots of legacy apis out there, not are all green-field.

Requirement is take a Authorization header, the uname/pw and send it to LDAP for auth

**Comment by NicolasGeraud** [comment]
is it a feature request or do you want to implement it ?

**Comment by bitsofinfo** [comment]
feature request

**Comment by brasseld** [comment]
For legacy APIs, right !

Even if we are implementing this basic authentication policy, it is still better to associate an apikey to authenticate the application and get a better tracking with analytics.

Wdyt ?

**Comment by brasseld** [comment]
https://github.com/gravitee-io/gravitee-policy-basic-authentication
https://github.com/gravitee-io/gravitee-resource-auth-provider
https://github.com/gravitee-io/gravitee-resource-auth-provider-inline

A LDAP implementation should be provided soon.

**Comment by NicolasGeraud** [comment]
@brasseld this will close #64

**Comment by brasseld** [comment]
👍

**Comment by brasseld** [comment]
My mistake, reopen until the PR has been reviewed.
