### ISSUE TITLE
[Tech] Debug Mode - Wrap DS with Angular component into ui-particles

### ISSUE THREAD

**Issue by ThibaudAV** [gravitee-io/issues#6892]
- Add a project in the workspace ui-particles specific for the DS
- Wrap DS into Angular component + Module. (use the one already present in Angular from apim and complete it)
- Use it inside Apim AngularJS and Angular

**Comment by ytvnr** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Graviteeio---API-Management-601c1f73be51260015c7bb26/issues/gravitee-io/issues/6892?planning-poker) with ZenHub @gaetanmaisse @ThibaudAV @LiliaEn
