### ISSUE TITLE
[Tech] Debug Mode - Extract DS menu

### ISSUE THREAD

**Issue by ThibaudAV** [gravitee-io/issues#6893]
- Extract DS menu into parent Angular component
- Add angular routing
- Hide and set tabId to use DS from ui component with minimal impact

**Comment by ThibaudAV** [comment]
Point of vigilance 
- see the behavior of the blocking mode when you have unsaved changes
- attention on routing there are several parameters, flow selected ext... which are to be passed to DS

**Comment by ppgravitee** [comment]
To be tested together with #6893

**Comment by LiliaEn** [comment]
Tested on the default env v3.16.0 
Browser: Chrome Version 97.0.4692.99 , macOS Big Sur v11.6
Performed smoke testing on API Design and it works as expected.
