### ISSUE TITLE
[helm] api template doesn't support opening of service core port 

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#6895]
## :collision: Describe the bug
The current api template doesn't allow to open the service core port:
https://github.com/gravitee-io/helm-charts/blob/master/apim/3.x/templates/api/api-deployment.yaml#L106-L108

the gateway template does correctly support it, instead:
https://github.com/gravitee-io/helm-charts/blob/master/apim/3.x/templates/gateway/gateway-deployment.yaml#L126-L129

The need is to be able to access the service core port of the api module for:
-health-check end-point
-prometheus metrics scraping 

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop :

***Please complete the following information:***

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by gaetanmaisse** [comment]
After a discussion with @leleueri there are multiple questions we would like to have @gravitee-io/archi feedback on:
 - It has been implemented on gateway side, is there any reason for not having done this on management api side? like security concerns etc
  - If we decide to handle this should we only rely on a service to be `enabled` to open the port? Or should we create another value to explicitly open a port (and use the value defined there)

**Comment by gaetanmaisse** [comment]
Discussed with @gravitee-io/archi, no special reason to not allow that and no need for an extra flag.
