### ISSUE TITLE
[portal] Text editor in webui

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#69]
_From @brasseld on May 4, 2016 14:52_

Some parts of the webui should use a text editor library for clarity:
- API descriptor
- Text area in policy configuration (for example for XSLT transformation, Mock, ...)

It would be nice to integrate with something like CodeMirror : https://codemirror.net/

_Copied from original issue: gravitee-io/release#51_

**Comment by M3lkior** [comment]
Could you list the targeted pages / parts of UI in details ?

**Comment by brasseld** [comment]
Hi @M3lkior,

Text editor is mainly required in policy and resource configuration.
Policy form is generated using https://github.com/json-schema-form/angular-schema-form

**Comment by M3lkior** [comment]
Okay @brasseld , thanks

I need to add an angular form plugin to manage codeMirror (http://angular-ui.github.io/ui-codemirror/) in json schema : https://github.com/philippbosch/angular-schema-form-ui-codemirror
