### ISSUE TITLE
Top-right menu is not displayed anymore

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#6903]
## :collision: Describe the bug
I am not able to see my account profile anymore.

## :sunrise_over_mountains: To Reproduce
1. Login with Google.
2. Cannot see my logo on the top right corner.

## :rainbow: Expected behaviour
Should be able to see the top-right menu?

## :movie_camera: Useful information

<img width="1920" alt="Capture d’écran 2022-01-12 à 07 47 25" src="https://user-images.githubusercontent.com/1580262/149080265-0763a28e-4e32-4354-9e1f-29911bbf5f5d.png">

If I access the menu by changing the URL, here is what I have:

![Capture d’écran 2022-01-12 à 08 08 27](https://user-images.githubusercontent.com/1580262/149080413-bc8d3e99-ac6c-4a07-9361-9ea4e3e45b1f.png)

I checked the browser's log, I don't see any errors.

## :computer: Desktop :

***Please complete the following information:***
 - Browser [e.g. chrome, safari] Chrome Version 97.0.4692.71 (Build officiel) (x86_64)

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by phiz71** [comment]
I am able to reproduce it. I think it's related to the fact that the newsletter has not been proposed.

**Comment by LiliaEn** [comment]
Tested on the default environment version 3.15.0
Browser: Chrome Version 95.0.4638.69, macOS Big Sur v11.6
Works as expected
