### ISSUE TITLE
Portal - Categories link goes to 404

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6904]
## :collision: Describe the bug
As i tried to navigate through the categories as user and admin, i got 404 on category pages.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to the portal and try the categories link
2. See error

## :rainbow: Expected behaviour
View category content

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop :

***Please complete the following information:***

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by mouligno** [comment]
can't reproduce on master, maybe a conf pb ?

**Comment by RubenMMSantos** [comment]
Issue still reproducible
envir: https://apim-release-test-portal.cloud.gravitee.io/catalog/categories

![Screenshot 2022-01-21 at 11 05 59](https://user-images.githubusercontent.com/14939456/150516664-3809d4ce-2d82-4dc6-be95-7431f22065a5.png)

![Screenshot 2022-01-21 at 11 09 43](https://user-images.githubusercontent.com/14939456/150517203-8c28a114-0c07-4f74-b721-024702209d55.png)

**Comment by gcusnieux** [comment]
Hi @RubenMMSantos,

https://apim-release-test-portal.cloud.gravitee.io isn't auto deploy. 
I redeployed manually but it's preferable to test on apim-master

**Comment by mouligno** [comment]
LGTM

**Comment by RubenMMSantos** [comment]
Issue re-tested and confirmed has fixed.

Issue verified on envir: https://apim-release-test-portal.cloud.gravitee.io/catalog/categories
