### ISSUE TITLE
[Portal] Main Documentation anchor doesn't work

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6905]
## :collision: Describe the bug
On the portal, if you go to global documentation, anchors redirect you to portal home page.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:

## :rainbow: Expected behaviour
Jump on the documentation section.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop :

***Please complete the following information:***

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by RubenMMSantos** [comment]
issue still reproducible on https://apim-release-test-portal.cloud.gravitee.io/

**Comment by mouligno** [comment]
Closed since it's duplicate of #6952
