### ISSUE TITLE
ES v5.x support in Gravitee Docker

### ISSUE THREAD

**Issue by chicco785** [gravitee-io/issues#691]
### Expected Behavior

I expect to be able to select which version of elasticsearch reporter is used. 
Ideally this could be something that is defined via an environment variable.

e.g. ES_VERSION=5.x or ES_VERSION=2.x

### Current Behavior
Currently, while also code for ES v5.x is developed, docker images include only the old reporter (compatible only with ES v2.x).

**Comment by NicolasGeraud** [comment]
hi @chicco785 

you talk about reporter (dedicated to store analytics) but there's also multiple implementations of the repository plugins (redis, mongo, cassandra, dynamodb).

If we follow your request, we should also add an envvar for repository...

Our docker images goal is to provide a demo platform to try gravitee. 

In the next release, we will replace ES2 by es5 an we will have a single implementation for ES2 and 5
see gravitee-io/gravitee-repository-elasticsearch/pull/18

**Comment by chicco785** [comment]
hi @NicolasGeraud sounds great :) when is the next release planned?

regarding docker images, i was thinking as well, it could be nice as well to expose more env variables
i saw in the scripts that there are many settings, that could be used for fine-tuning the configuration.

if you think, when I have time i make create a PR for that.

cheers

**Comment by brasseld** [comment]
This issue is not more relevant since https://github.com/gravitee-io/issues/issues/937
Our default HTTP connector can now be used to manage multiple versions of Elasticsearch.
