### ISSUE TITLE
[management] HTTP2 is set by default when creating new groups

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#6910]
## :collision: Describe the bug
There are 2 unexpected behaviors:
  - It is not possible to see / modify the HTTP version on a group (choose between 1.1 and 2) while it is possible to do it on an endpoint.
  - When creating an API, the default HTTP version is 1.1, but when creating a new group it is HTTP2 by default. 

Consistent behaviors would be expected.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:

1. Create an API
2. Go to the Proxy / Endpoints section
3. Edit the group -> we do not see the HTTP version
4. Edit the endpoint and disable the inheritance of the http configuration -> the HTTP version is 1.1
5. Create a new group with a new endpoint
6. Edit the new endpoint and disable the inheritance of the http configuration -> the HTTP version is 2

tested in APIM 3.10.8/9 and 3.5.28

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop :

***Please complete the following information:***

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by gcusnieux** [comment]
not reproduced in 3.15.x
