### ISSUE TITLE
When filtering through the logs, showing results as the maximum alows, and no other pages even though there are more results

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#6913]
Not all results in the logs are displayed, when filtering through the payload and when maximum for the page is reached.

1. Go to logs of an api
2. Search through the logs with an payload criteria
3. Set maximum results per page on 10
4. The results displayed are the maximum set as per page
5. When maximum per page set at 15, that is the final result, even though there should be more results

![image](https://user-images.githubusercontent.com/89140082/149161119-e5933572-d633-42fa-95e0-50419d672e69.png)
![image](https://user-images.githubusercontent.com/89140082/149161164-a5b89fd2-212e-4c2b-ad1d-3bd0d7b94b33.png)
![image](https://user-images.githubusercontent.com/89140082/149161193-dfc36d8e-907b-4e06-b22a-cb0261a6d082.png)

In the pictures above, the maximum results on a page is limiting the results shown, meaning even though there should be more results included, but they are not displayed and and there is not second/third, and so on... page, with the rest of the results.

And these are the results without payload as a search criteria:

![image](https://user-images.githubusercontent.com/89140082/149161432-c920ec50-5be5-428b-89f2-e367301d6fe8.png)

and the difference is that there are more pages, with all of the results included.

Used versions: APIM 3.10.3, 3.12.4

**Comment by gaetanmaisse** [comment]
Same origin as https://github.com/gravitee-io/issues/issues/6912

Some explanation is available here https://github.com/gravitee-io/issues/issues/6912#issuecomment-1049680523

**Comment by gcusnieux** [comment]
Hi @RubenMMSantos @LiliaEn It's deployed on env 3.10.X if you want 😄

**Comment by RubenMMSantos** [comment]
issue verified and confirmed as fixed
Navigation through the logs page working as expected when using the filters
verified on envir 3-10-X
