### ISSUE TITLE
[Management] Condition on logging configuration is not properly removed

### ISSUE THREAD

**Issue by allandenis38** [gravitee-io/issues#6914]
## :collision: Describe the bug
When trying to remove a condition already set in the logging con by clicking on the Trash icon
The input fields switch to edit mode and keeps the condition. 

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Select an API
2. Go to Analytics > Logs > Logging configuration
3. Enter a condition and save
4. Click on the Trash Icon to remove it. 

## :rainbow: Expected behaviour
Condition should be completely removed

## :movie_camera: Useful information
<img width="1536" alt="Screenshot 2022-01-11 at 12 57 02" src="https://user-images.githubusercontent.com/11437254/149164000-7263469e-c8ae-42c7-8de2-009bf0394c35.png">

## :computer: Desktop :

***Please complete the following information:***
 - OS: MacOS 
 - Browser: Chrome Version 97.0.4692.71 (Official Build) (x86_64)
 
## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by mouligno** [comment]
Can not reproduce
