### ISSUE TITLE
[node] node_health metric returns null values in 3.10

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#6924]
## :collision: Describe the bug
While enabling prometheus metrics, node_health metric shows null values

3.10.9 : 
```
# curl http://localhost:18082/_node/metrics/prometheus | grep node_health
node_health{application="gio-apim-gateway",instance="7a17546ee7f4",probe="http-server",} 0.0
node_health{application="gio-apim-gateway",instance="7a17546ee7f4",probe="api-sync",} 0.0
node_health{application="gio-apim-gateway",instance="7a17546ee7f4",probe="management-repository",} 0.0
node_health{application="gio-apim-gateway",instance="7a17546ee7f4",probe="ratelimit-repository",} 0.0
node_health{application="gio-apim-gateway",instance="7a17546ee7f4",probe="cpu",} 0.0
node_health{application="gio-apim-gateway",instance="7a17546ee7f4",probe="memory",} 0.0
```
3.5.28 : 
```
# curl http://localhost:18082/_node/metrics/prometheus | grep node_health
node_health{application="gio-apim-gateway",instance="5cfbf819f8d4",probe="ratelimit-repository",} 1.0
node_health{application="gio-apim-gateway",instance="5cfbf819f8d4",probe="http-server",} 1.0
node_health{application="gio-apim-gateway",instance="5cfbf819f8d4",probe="management-repository",} 1.0
```
In addition, some metrics name have changed and not documented (`http_server_requestCount_total` <-> `http_server_requests_total`) : 

3.10.9 : 
```
# curl http://localhost:18082/_node/metrics/prometheus | grep http_server_requests_total
http_server_requests_total{application="gio-apim-gateway",code="200",instance="7a17546ee7f4",local="localhost:18082",method="GET",path="/_node",remote="127.0.0.1:44722",} 1.0
http_server_requests_total{application="gio-apim-gateway",code="200",instance="7a17546ee7f4",local="localhost:18082",method="GET",path="/_node/metrics/prometheus",remote="127.0.0.1:44750",} 1.0
0http_server_requests_total{application="gio-apim-gateway",code="200",instance="7a17546ee7f4",local="localhost:18082",method="GET",path="/_node/metrics/prometheus",remote="127.0.0.1:45196",} 1.0
http_server_requests_total{application="gio-apim-gateway",code="200",instance="7a17546ee7f4",local="localhost:18082",method="GET",path="/_node/metrics/prometheus",remote="127.0.0.1:44802",} 1.0

# curl http://localhost:18082/_node/metrics/prometheus | grep http_server_requestCount_total

```
3.5.28 : 
```
# curl http://localhost:18082/_node/metrics/prometheus | grep http_server_requests_total

# curl http://localhost:18082/_node/metrics/prometheus | grep http_server_requestCount_total
http_server_requestCount_total{application="gio-apim-gateway",code="200",instance="5cfbf819f8d4",local="localhost:18082",method="GET",path="/_node/metrics/prometheus",remote="127.0.0.1:45772",} 1.0
http_server_requestCount_total{application="gio-apim-gateway",code="200",instance="5cfbf819f8d4",local="localhost:18082",method="GET",path="/_node/metrics/prometheus",remote="127.0.0.1:45810",} 1.0
```

Internal API for the management-api appear to have the same behavior
Maybe related to #6873 

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Enable prometheus metrics on the gateway 
2. call the above Internal API in each version

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop :

***Please complete the following information:***

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by brasseld** [comment]
Indeed, that is relative to #6873

**Comment by apoddany** [comment]
Yes I was meaning 0.0 value compared to 3.5

**Comment by RubenMMSantos** [comment]
Hi @phiz71 do we have prometheus metrics enabled on 3.10.X environment or do we need to check this locally?

**Comment by phiz71** [comment]
> Hi @phiz71 do we have prometheus metrics enabled on 3.10.X environment or do we need to check this locally? thanks

Prometheus metrics are not enabled on 3.10.x env but we could easily test locally

**Comment by phiz71** [comment]
Actually, the naming pb has been fixed, but there is still an issue with the value of health metrics. It seems that they are never updated.

**Comment by phiz71** [comment]
> Actually, the naming pb has been fixed, but there is still an issue with the value of health metrics. It seems that they are never updated.

Fixed with latest commit on gravitee-node.
Once again, it can be tested locally.

**Comment by RubenMMSantos** [comment]
Issue verified together with dev (ticket checked locally).

Expected results confirm, ticket ready to release
