### ISSUE TITLE
[management] [design studio] Conflict with keyboard shortcuts 

### ISSUE THREAD

**Issue by gcusnieux** [gravitee-io/issues#6935]
## :collision: Describe the bug
In policy studio; when User want to use `Ctrl+Space` to start completion on code editor, the focus is put in the input for filter flows

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to 'Design' on api
2. Add mock policy
3. Edit th response body content
4. Add {#} and press `Ctrl+Space` to start completion
5. See the weird behaviour

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

https://user-images.githubusercontent.com/1457497/149359925-5097a157-94d3-4804-a5ad-2c43bff1e465.mov

**Comment by phiz71** [comment]
OK
