### ISSUE TITLE
[gateway] self account management : manage webauthn credentials - manage challenge

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#6936]
WebAuthn registration ceremony relies on "challenge" secured value to be done.

For this purpose we need : 

- a new endpoint `GET /api/webauthn/credentials/registration/options` : returns the publicKeyCredentialCreationOptions object contains a number of required and optional fields that a server specifies to create a new credential for a user => this step generate the "challenge" which has to be stored in AM for the next step

The `POST /api/webauthn/credentials` endpoint handle the following payload : 

```
PublicKeyCredential {
    id: 'ADSUllKQmbqdGtpu4sjseh4cg2TxSvrbcHDTBsv4NSSX9...',
    rawId: ArrayBuffer(59),
    response: AuthenticatorAttestationResponse {
        clientDataJSON: ArrayBuffer(121),
        attestationObject: ArrayBuffer(306),
    },
    type: 'public-key'
}

Decoded 

{
    challenge: "p5aV2uHXr0AOqUk7HQitvi-Ny1....",
    origin: "https://webauthn.guide",
    type: "webauthn.create"
}
```

The `challenge` value received by the client will be compared with the value store in AM server.

**Comment by ashraf706** [comment]
The implementation context has been changed and this issue is irrelevant.
