### ISSUE TITLE
[Policy] Json to Json isn't working properly

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6937]
## :collision: Describe the bug
Using the Json to Json policy, I got a 200 response but my JOLT transformation isn't done.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to policy studio an import this API using Json to Json policy
[Antoine-Planets-1-0.json.zip](https://github.com/gravitee-io/issues/files/7869060/Antoine-Planets-1-0.json.zip)

3. Call your API - [gateway-url]/antoine-planets
4. Empty response with a 200 response code

## :rainbow: Expected behaviour

Expected response, working on 3.14 

```
[
    {
        "myName": "Uranus",
        "myDensity": 1.27
    },
    {
        "myName": "Neptune",
        "myDensity": 1.638
    },
    {
        "myName": "Jupiter",
        "myDensity": 1.3262
    },
    {
        "myName": "Mars",
        "myDensity": 3.9341
    },
    {
        "myName": "Mercure",
        "myDensity": 5.4291
    },
    {
        "myName": "Saturne",
        "myDensity": 0.6871
    },
    {
        "myName": "La Terre",
        "myDensity": 5.5136
    },
    {
        "myName": "Vénus",
        "myDensity": 5.243
    }
]
```
## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop :

***Please complete the following information:***

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by LiliaEn** [comment]
Tested on the default environment version 3.15.0
Browser: Chrome Version 95.0.4638.69, macOS Big Sur v11.6
Works as expected
