### ISSUE TITLE
[management] APIs sort by name displays an error

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#6938]
## :collision: Describe the bug
On APIs list, trying to sort API by name is not working and leads to an error.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to console as admin
2. Click on APIs
3. Click on the arrow beside 'name' column label to order it
4. See error : `unexpected docvalues type NONE for field 'name' (expected=SORTED). Re-index with correct docvalues type. `

## :rainbow: Expected behaviour
APIs list should sort by name without any error

## :computer: Desktop :

 - OS : Linux
 - Browser : firefox

**Comment by LiliaEn** [comment]
Tested on the default environment version 3.15.0
Browser: Chrome Version 95.0.4638.69, macOS Big Sur v11.6
Works as expected
