### ISSUE TITLE
[CI] Improve Gh comment on PR

### ISSUE THREAD

**Issue by ThibaudAV** [gravitee-io/issues#6939]
## Description

On the APIM side, we currently have multiple CircleCI code snippets to add messages as comments (for instance https://github.com/gravitee-io/gravitee-ui-components/pull/607#issuecomment-1248914739) or directly as an update of the PR description (https://github.com/gravitee-io/gravitee-api-management/pull/2466#issue-1374822092). 

This issue aims to have a single method in an orb to do so. Maybe in a dedicated orb?

Then it could be used in: 
- ui-particles
- ui-component
- apim
...

**Comment by mouligno** [comment]
@ThibaudAV is it still accurate ?
