### ISSUE TITLE
[Gateway] Step 2 - Have a dedicated policy chain for debug mode

### ISSUE THREAD

**Issue by gaetanmaisse** [gravitee-io/issues#6945]
**Description**

Create and use DebugPolicy (a policy wrapper) + DebugPolicyChainFactory

**Comment by LiliaEn** [comment]
Performed smoke test around APIs create and call.
Tested on the default env, v3.16 SNAPSHOT
Browser: Chrome Version 95.0.4638.69, macOS Big Sur v11.6
