### ISSUE TITLE
[Gateway] Step 3 - Use an executionContext dedicated to Debug Mode 

### ISSUE THREAD

**Issue by gaetanmaisse** [gravitee-io/issues#6946]
**Description**

 - Create a `DebugExecutionContextFactory`. 
 - Create `DebugExecutionContext` and its methods that will manage `DebugInfo` (start time, end time, headers, body...)

**Comment by ppgravitee** [comment]
To be tested with #6949

**Comment by LiliaEn** [comment]
Tested on the default environment v3.16 SNAPSHOT
Browser: Chrome Version 97.0.4692.99 , macOS Big Sur v11.6
Performed some smoke testing around API create/deploy and call using Try It mode.
