### ISSUE TITLE
[gateway] 503 errors may occur when redeploying an api 

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#6948]
## :collision: Describe the bug
In previous version, we've made some improvements to avoid http 500 during the redeployment of an api when there is an high traffic (see #6553). 

We recently discovered that 503 errors can still occur during the redeployment of an api which have a lot of configured policies in the request flow (or slow ones).

## :sunrise_over_mountains: To Reproduce
1. Create an simple api using the APIM console
2. Add a latency policy on the request flow and set a latency to 3 seconds (latency is a simple way to simulate slow request flow we could have if we configure a lot of policies)
3. Deploy the api
3. Make calls to the apis and redeploy the apis
5. You should have unexpected 503 errors

## :rainbow: Expected behavior
No error is expected during api redeployment.

## :movie_camera: Useful information
Not relevant

## :computer: Desktop :

***Please complete the following information:***
Not relevant

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

I managed to reproduce the same error using the latest 3.10.x and the master branch (3.15.x)

**Comment by RubenMMSantos** [comment]
Issue not reproducible, no 503 errors displayed after redeploying API.
Issue verified on envir 3.15.
