### ISSUE TITLE
[Gateway] Step 4 - Refactor debug event saving

### ISSUE THREAD

**Issue by gaetanmaisse** [gravitee-io/issues#6949]
**Description**

Introduce a dedicated `DebugEventProcessorFactory`, instantiating `DebugEventProcessor` to save debug events after executing the policy chain. 

`DebugEventProcessor` is responsible for: 
 - reading the debug execution context to build the final event object #6947 
 - updating the event in database

Refactor DebugReactor to remove any use of `EventRepository`: its responsibility is only to deploy and undeploy debug APIs 

To test: 
- Go to try it and send a debug request
- Look in the console that you have a `payload` attribute containing some `debugsteps` in the response (one per policy)

**Comment by LiliaEn** [comment]
Tested on the default env v3.16.0 
Browser: Chrome Version 97.0.4692.99 , macOS Big Sur v11.6
`debugSteps` are displayed.
![Screenshot 2022-02-14 at 12 56 26](https://user-images.githubusercontent.com/49516050/153868483-b22ffb1e-f290-412c-8606-c8443f083de3.png)
