### ISSUE TITLE
[Gateway] Step 5.a - Handle error during policy execution

### ISSUE THREAD

**Issue by gaetanmaisse** [gravitee-io/issues#6950]
**Description**

If an error occurs during a policy execution, then the step should be in error. Two cases:

- `chain.failWith` -> for example, in GenerateHttpSignature Policy, when headers are not valids
- Runtime exception -> for example,  invalid EL

**Technical propositions**

Extend `OnErrorProcessorChainFactory` to handle any error during the execution of a policy.
Display the error in red in the front, specific error messages will be handle in another issue

Or, just use the new `DebugPolicyChain`

#### ON_REQUEST
- add an invalid condition on a policy and check you only have `error.message` in the `result` map of the event.
- Use GenerateHttpSignaturePolicy with required headers, and make a call without it. You should have `error.message`, `error.key`, `error.status` and `error.contentType`
- same for JsonValidation with an invalid scheme

#### ON_RESPONSE
- add an invalid condition on a policy and check you only have `error.message` in the `result` map of the event.
- UseJsonValidation with an invalid scheme. You should have `error.message`, `error.key`, `error.status` and `error.contentType`

**Comment by LiliaEn** [comment]
[7117](https://github.com/gravitee-io/issues/issues/7117)

**Comment by LiliaEn** [comment]
Tested on the default env v3.16.0 
Browser: Chrome Version 97.0.4692.99 , macOS Big Sur v11.6
- Checked errors displayed when a policy has an invalid condition
- Errors displayed when a policy is not configured correctly
- Errors displayed when there is no authorization
- Errors displayed when there is a misconfiguration on the API
