### ISSUE TITLE
[Portal] Applications-> Hovering over an application to see the subscription will make the app crash and return 404 error

### ISSUE THREAD

**Issue by LiliaEn** [gravitee-io/issues#6953]
Hovering over an application to see the subscription will make the app crash and return 404 error

### Expected Behaviour
When hovering over an application, on My Subscriptions tab, the available subscriptions for that app should be displayed

### Current Behaviour
Hovering over an application to see the subscription will make the app crash and return 404 error. Please see the video and the screenshot: https://drive.google.com/file/d/1DjIvDtuVZAkDyMthNxqlR4wNR6XLqlAJ/view?usp=sharing
![Screenshot 2022-01-17 at 09.09.02.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/7d2f09d9-4fe8-48f8-9d54-e071dacc41e1)

### Steps to Reproduce (for bugs)
1. Login to Portal
2. Go to Applications-> My Subscriptions
3. Hover over the apps

Please note that this is not reproducible for all the apps, but the majority of them

### Your Environment
* Version used: default env - v3.15.0
* Browser Name and version: Chrome Version 95.0.4638.69
* Operating System and version: macOS Big Sur v11.6

**Comment by RubenMMSantos** [comment]
issue is still reproducible on https://apim-release-test-portal.cloud.gravitee.io/applications/subscriptions

**Comment by mouligno** [comment]
LGTM

**Comment by RubenMMSantos** [comment]
issue re-tested and confirmed has fixed.
Verified on envir: https://apim-release-test-portal.cloud.gravitee.io/applications/subscriptions
