### ISSUE TITLE
In some case, a revision of a modification on a page is saved while there is no change

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#6960]
## :collision: Describe the bug
While reading the code, it seems we have a potential bug here: https://github.com/gravitee-io/gravitee-api-management/blob/9b231f1188ac2a50327b9db3a6df982d30071e80/gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PageServiceImpl.java#L838

If we already have a homepage, we will still save a revision before even if the change is not effective.

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by gaetanmaisse** [comment]
After investigation it looks the behavior is ok, the `onlyOneHomepage` method will unset any other Home Page so the change will be effective at the end.
