### ISSUE TITLE
Health check logger produces error when the endpoint response contains headers

### ISSUE THREAD

**Issue by a-cordier** [gravitee-io/issues#6964]
## :collision: Describe the bug

A FreeMarker template error is reported in the logs and the health check is not indexed if the endpoint response contains custom HTTP headers. 

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:

1. Add a health check to an API the resolves to an HTTP response with custom header (eg x-env: dev)
2. Check the gravitee-health index
3. Check your logs

 :x: nothing is indexed
:bug: the following error is reported in the logs 

```
13:54:05.022 [RxCachedThreadScheduler-1] [] ERROR i.g.e.t.f.FreeMarkerComponent - Impossible to generate from template /es7x/index/health.ftl
freemarker.template.TemplateModelException: ?size is unsupported for freemarker.ext.beans.OverloadedMethodsModel
----
FTL stack trace ("~" means nesting-related):
- Failed at: #list headerValue as value  [in template "es7x/index/health.ftl" at line 51, column 21]
- Reached through: @compress single_line=true  [in template "es7x/index/health.ftl" at line 8, column 1]
----
```

## :rainbow: Expected behaviour
The check should be indexed with no templating error

**Comment by RubenMMSantos** [comment]
Ticket verified on https://apim-release-test-console.cloud.gravitee.io/ with APIM v3.15
Issue not reproducible and working as expected
