### ISSUE TITLE
[management] API Flow execution order error, can't delete a header after it was previously used in a condition.

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#6966]
## :collision: Describe the bug
We are not able to remove/delete a header with Transform Header Policy which previously was used in a Condition Check in another API.

{#request.headers['Application'] == null || #request.headers['Application'] != null && #request.headers['Application'][0] != #context.attributes['secret']} EL to test with.

## :sunrise_over_mountains: To Reproduce
1. Import the API shared here.

2. Make a POST call from Postman and add Application header with the same value from the Propertie Secret which you will find in the TEST API from bellow

3. Test in 3.15.2 or 3. What this case is all about is that we send a header which is used in a Condition and right before this header is is begin send to the gateway we delete it.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material:

[apis.zip](https://github.com/gravitee-io/issues/files/8132029/apis.zip)

## :computer: Desktop :

***Please complete the following information:***
 - OS: Windows 10, Docker-Desktop
 - Browser: Google Chrome

## :warning: Potential impacts

***What are the impacted versions?***
- 3.15.2 and 3.15.3

**Comment by ytvnr** [comment]
### Understanding the internal behaviour
- The gateway will iterate on the available flows and evaluate the condition, first for REQUEST phase, and then for RESPONSE phase.
- For each flow matching the condition, we will add it to the chain

### What happens in your case
**On REQUEST**

1. you call your api passing the "accept" headers, so condition for flow 1 is valid, and same for flow 2: both flows are executed. Headers are added to the request, and `accept` header is deleted
2. backend is called and answer

**On RESPONSE**
1. your condition on flows are once again evaluated. For flow1, we again check that the header `accept` is equal to '*/*' in request object. But it has been deleted previously: you try to access a `null` object to compare it with '*/*' -> it results in error `Templates evaluation returns an error...`

### How to protect against this kind of error ?

You can try to formulate your condition like this to avoid the error:
`{#request.headers['accept'] != null && #request.headers['accept'][0].equals("*/*")}`

With the previous explication, the behaviour will be as following:
**ON REQUEST**: conditions for both flows are true, request phase is executed correctly for both flows
**ON RESPONSE**: condition is not correct for flow 1, so only flow 2 will be executed for response

**Comment by mouligno** [comment]
@marijatimovska Ok for you ? Can we close this ?

**Comment by marijatimovska** [comment]
@mouligno I will test this out now

**Comment by mouligno** [comment]
@marijatimovska can we close this one ?

**Comment by marijatimovska** [comment]
@mouligno Yes we can close this one, I will create a follow up or reopen this one if needed.

The EL condition that we used in our case, which still needs to be tested.

EL -> {#request.headers['Application'] == null || #request.headers['Application'] != null && #request.headers['Application'][0] != #context.attributes['secret']} 

While in the next flow the Application header is getting removed.

**Comment by marijatimovska** [comment]
@mouligno I am reopening this bug since it is a regression. The solution EL-> {#request.headers['Application'] == null || #request.headers['Application'] != null && #request.headers['Application'][0] != #context.attributes['secret']}

Is working properly in 3.10.10 and 3.12.4 the issue is for all 3.15.X version.

The EL used to work and in the latest 3.15.X is it no longer working. The steps have been updated above.

**Comment by mouligno** [comment]
@ytvnr any input on that ?

**Comment by marijatimovska** [comment]
Tested with a new EL -> {(#request.headers['Application'] == null || #request.headers['Application'].size() ==0) || #request.headers['Application'] != null && #request.headers['Application'].size() > 0 && #request.headers['Application'][0] == #properties['secret']} - Working example in 3.15.X
