### ISSUE TITLE
Let the API Owner choose the Accept-Encoding

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#6967]
For testing the Caching Policy functionality, created simple API with a 'Free' plan and a Main flow that only includes a Caching Policy. Unfortunately this simple API throws empty response body's after executing it 2 times or more.

Steps to reproduce the behaviour:
1. Import attached file or create an API with backend that support Content-Encoding (like: https://jsonplaceholder.typicode.com/photos) 
2. call the api from postman and with header `Accept-Encoding: gzip, deflate, br`
3. the first couple of calls are ok, and then this is the message in postman:
![image](https://user-images.githubusercontent.com/89140082/149984121-1a9eba81-22ce-4b7e-81a5-052ff4d7376b.png)

Looking at the Analytics in Gravitee for the 'Caching' API, it seems that after couple of executions the Caching Policy is activated and the request time goes down:
![image](https://user-images.githubusercontent.com/89140082/149984405-8824c0e1-f6a0-46cd-97f9-be7abdfa88a3.png)

Looking in the logs, the return body from the backend is logged like this:
![image](https://user-images.githubusercontent.com/89140082/149985066-3d4ac07a-9bca-4272-9f99-49db4034fb79.png)

The requests that are showing no backend request, there's no logging shown.

 One would expect the Caching to 'kick in' and throw the saved backend response, but empty responses are send back (including a statuscode 200 OK).

Used versions: APIM 3.14.0, 3.12.4

**Comment by gcusnieux** [comment]
Hi @zveljanoski, I don't reproduce. Could you share an export of yours API ?

**Comment by zveljanoski** [comment]
hello @gcusnieux , attached

[Cache-v1.txt](https://github.com/gravitee-io/issues/files/7985157/Cache-v1.txt)

**Comment by gcusnieux** [comment]
Hi @zveljanoski, 

I imported yours API on https://apim-3-14-x-console.cloud.gravitee.io/#!/environments/default/apis/5b28172a-9604-454e-a817-2a9604b54e5f/portal

And I don't reproduce with simple curl command,

`curl https://apim-3-14-x-gateway.cloud.gravitee.io/cache`

Could you retry ? or could you give me more details please ?

Thx

**Comment by zveljanoski** [comment]
Hi @gcusnieux,

just tested from my end, called the api you've shown in the previous comment.

![image](https://user-images.githubusercontent.com/89140082/152144718-8e9f2cc7-5d7d-4c33-a65e-148deeedb525.png)

If you can check the logs there,

thanks

**Comment by gcusnieux** [comment]
Ok, I reproduced.

Postman enable cookie jar by default.
We must disable this option to use cache-resource 
```
Disable cookie jar
Prevent cookies used in this request from being stored in the cookie jar. Existing cookies in the cookie jar will not be added as headers for this request.
```

![Capture d’écran 2022-02-02 à 13 23 35](https://user-images.githubusercontent.com/1457497/152154039-d4012697-bc82-4500-8304-241d71d873ca.png)

**Comment by zveljanoski** [comment]
Hello, I disabled it, and tried again, yet the same result:
![image](https://user-images.githubusercontent.com/89140082/152169213-6f94f2c9-049d-4923-938b-9e917f014fe6.png)

**Comment by gcusnieux** [comment]
Ok, you should restart API to release the cache

**Comment by zveljanoski** [comment]
Wasn't it restarted? I fired on https://apim-3-14-x-gateway.cloud.gravitee.io/cache as you can see from the picture..

**Comment by gcusnieux** [comment]
@zveljanoski if you want to remove this error, you must start and stop the api. 
But definitily, it's a bug, it should work without changing the postman options

**Comment by zveljanoski** [comment]
Thanks @gcusnieux, for the clarification.

**Comment by gcusnieux** [comment]
Finally the problem isn't the cache but the Gateway does not support Brotli compression. https://en.wikipedia.org/wiki/Brotli

**Comment by LiliaEn** [comment]
Tested on 3.15.X env
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Works as expected.
