### ISSUE TITLE
[gateway] impossible to use AlertProcessor

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#6969]
I should be able to use Alert Engine

### Expected Behavior
It should work as expected

### Current Behavior
NullPointerException when trying to add the AlertProcessor in processors list

### Possible Solution
Do not use Arrays.asList() to instanciate the processors list: it instantiate a Arrays$ArrayList which is not java.util.ArrayList

**Comment by LiliaEn** [comment]
Tested locally on 3.15
Alert processor works as expected.
