### ISSUE TITLE
[APIM - Portal] Error message displayed as soon as Portal page loads

### ISSUE THREAD

**Issue by RubenMMSantos** [gravitee-io/issues#6976]
As soon as the Portal main page loads, a banner is displayed with the message "An unexpected error occurred"

### Expected Behavior
Portal should load without any errors

### Current Behavior
As soon as the Portal main page loads, a banner is displayed with the message "An unexpected error occurred"

### Steps to Reproduce (for bugs)
1. go to https://apim-release-test-portal.cloud.gravitee.io/
2. notice the error
3. ![Screenshot 2022-01-20 at 10.46.40.png](https://images.zenhubusercontent.com/612518f668e84e3f309d282d/6fbdb0ca-4e59-41c9-b80a-6f860b49d646)
4.

### Your Environment

* Environment: https://apim-release-test-portal.cloud.gravitee.io/
* Version used: APIM 3.15.0-SNAPSHOT
* Browser Name and version: Google Chrome Version 97.0.4692.71
* Operating System and version: Mac OS v11.6.1 (20G224)

**Comment by gcusnieux** [comment]
Related to a redeploy ?
I can't reproduce

**Comment by LiliaEn** [comment]
Tested on both master and release-test env - version 3.15.0
Browser: Chrome Version 95.0.4638.69, macOS Big Sur v11.6
Works as expected
