### ISSUE TITLE
[Console] Condition Logging on API is not displayed after saving

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#6978]
## :collision: Describe the bug
When adding a Condition in the Logging of an API, the Condition is not displayed after Saving

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to API -> Analytics -> Logs -> Configure logging
2. Apply a Condition and Save
<img width="973" alt="Capture d’écran 2022-01-20 à 17 47 57" src="https://user-images.githubusercontent.com/79909781/150386521-a2597dcb-497e-4c7b-ab4c-04e69d33526b.png">
3. Check the Condition field
<img width="735" alt="Capture d’écran 2022-01-20 à 17 49 49" src="https://user-images.githubusercontent.com/79909781/150386547-f225156a-f3bf-40e4-99fc-dfeb0f2a213b.png">
4. Associated Audit 
<img width="1373" alt="Capture d’écran 2022-01-20 à 17 53 13" src="https://user-images.githubusercontent.com/79909781/150386574-3a6b8bb1-4f67-4c6f-ba5e-e206e8b36213.png">

## :rainbow: Expected behaviour
Have the Condition displayed in the field after saving

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop :

***Please complete the following information:***
tested in 3.13.3

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by gaetanmaisse** [comment]
This bug has been fixed in 3.14+ so I guess we can close this issue as 3.13 isn't supported anymore. cc @mouligno

**Comment by gcusnieux** [comment]
I confirm, has been fixed in 3.10.x with https://github.com/gravitee-io/gravitee-api-management/commit/8116481590ff5b31d74f79bb93fa25d4fa88a0ec

**Comment by LiliaEn** [comment]
Tested on the  3.10.X env
Browser: Chrome Version 98.0.4758.80 , macOS Big Sur v11.6
Works as expected
<img width="1246" alt="Screenshot 2022-03-04 at 15 56 53" src="https://user-images.githubusercontent.com/49516050/156796997-16adc998-0b0b-4181-960f-3ff9f1f049e9.png">
