### ISSUE TITLE
[policy] Use onRequestContent cause 504 on every requests

### ISSUE THREAD

**Issue by Matsa59** [gravitee-io/issues#698]
### Expected Behavior

Using `onRequestContent` should allow us to manage the body request (or content request).

### Current Behavior

Currently, if we use the `onRequestContent` the request return 504 every time.

### Steps to Reproduce (for bugs)

1. Create API
2. Add mock
3. Add groovy policy
4. copy past the following groovy to `onRequestContent` scope
```java
if (request.headers.containsKey('X-Gravitee-Break')) {
    result.state = FAILURE
    result.code = 500
    result.error = 'Stop request processing due to X-Gravitee-Break header'
} else {
    request.headers.'X-Groovy-Policy' = 'ok'
}
```

### Context

Try to transform request content to query parameters.

### Your Environment

* Version used: 1.8
* Operating System and version: Centos

**Comment by Matsa59** [comment]
Add ```return request.content``` at the end of the groovy fix the problem (thanks @brasseld)

I found another bug : use ```request.parameters``` in the `onRequestContent` scope does not update the parameters content.

Here my groovy : 
```
import groovy.json.JsonSlurper
import groovy.json.JsonOutput

def jsonSlurper = new JsonSlurper()
def content = jsonSlurper.parseText(request.content)
request.parameters.'username' = "login"
request.parameters.'password' = "password"
return request.content
```

No query parameter appear in log

**Comment by brasseld** [comment]
Hi @Matsa59,

Yes, this does not work for a very good reason.
When you are manipulating stream through `onRequestContent` or `onResponseContent` it means that the proxy request has already being defined to get a reference to the back-end streaming and plug this later to our policy streaming.
So, I don't know what is your case, but I would advise you to use `onRequest` or `onResponse` if you want to manipulate HTTP headers / query parameters *before* playing with streams.

**Comment by brasseld** [comment]
Groovy policy documentation must be improved.

**Comment by Matsa59** [comment]
Fix by assign content
