### ISSUE TITLE
Enhance Cache Policy

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#6980]
As an API Publisher

I want the ability to setup a cache policy for any http verbs including POST

So that I can cache elements of response from through any verb

<p></p>

**Acceptance criteria**

- I have the ability to define the methods (array) for which the cache should be applied.

- I have the ability to define the response status code for which the cache should be applied.

**Comment by NicolasGeraud** [comment]
Link to feature: https://gravitee.productboard.com/feature-board/planning/features/8231655

**Comment by NicolasGeraud** [comment]
I suggest creating a v2 of this policy and removing the "safe method" filter. This way we cache every request and if you just want to cache GET, you create a Flow or use the new "condition" feature available on all policies.

Less code, less tests, less bugs.

Because it will not be compatible with the previous version, I suggest to deploy 2 versions of this policy. V1 will be deprecated and a message will encourage user to use v2. Plugin ID will also change to allow 2 versions to be loaded in the same time.

I also suggest adding a `response condition` field that supports EL to allow users to only cache 200 responses or use jsonPath to check the content before putting it to the cache.

What do you think?

**Comment by brasseld** [comment]
My thoughts:
I would prefer to keep a checkbox to support safe methods only (or not), I think it’s easier to check a box (which is checked by default) than defining a condition default behavior. This will allow to not compromise backward compatibility.
Regarding my previous point, I don’t see good motivations for introducing a new policy ID for a policy which will do the same thing as the previous version. And we don’t have strong deprecated policy management for users / customers (what if they are upgrading without updating all the APIs concerned). Also, if we keep in mind the concept of Marketplace, I think that’s something we should avoid.
If we are looking to rely on the flow or policy condition, we should do it for all the policies (where it’s accurate), and not do it one by one (resource-filtering ?, dynamic-routing ?)
Agree for the condition on the response. Again, this can be added to the existing version, no need to create a new policy for this.
If we are introducing a new version of the cache policy, what would be the rule : do we allow to embed it into previous LTS (3.5.x / 3.10.x) ?
