### ISSUE TITLE
[portal] highlighted api does not belong to the category

### ISSUE THREAD

**Issue by gcusnieux** [gravitee-io/issues#6982]
## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to 'Console'
2. Click on 'Create a category and add apis'
3. Go to 'Portal'
4. The first API doesn't belong to the category

## :rainbow: Expected behaviour
The first API must belong to the category

## :movie_camera: Useful information
![Capture d’écran 2022-01-21 à 09 54 23](https://user-images.githubusercontent.com/1457497/150496908-08509911-00c2-4b24-ad88-f92a3679271e.png)
![Capture d’écran 2022-01-21 à 09 54 06](https://user-images.githubusercontent.com/1457497/150496913-8d529828-bd06-4690-b426-724b318fa78c.png)

## :computer: Desktop :

***Please complete the following information:***

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by mouligno** [comment]
LGTM

**Comment by RubenMMSantos** [comment]
Issue re-Tested on the default environment version 3.15.0
Browser: Chrome Version 97.0.4692.99 macOS Big Sur v11.6.1
