### ISSUE TITLE
[Gateway] Step 5.c - Debug Platform policies

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#6983]
**Description**

Be able to also debug policies defined at platform level

**How to do**

Take a look at `PlatformConfiguration` to use the `DebugPolicyFactory`

**How to test**

 - Go to organization settings
 - Add some platform policies 
 - Go to the APIs list -> select an API
 - Go to Design -> Dbug tab
 - Send a debug request 
 - Check if the defined platform policies are well displayed in the timeline

**Comment by LiliaEn** [comment]
Tested on the default env v3.16.0 
Browser: Chrome Version 97.0.4692.99 , macOS Big Sur v11.6
- Checked that platform On Request policies are executed and displayed in debug mode correctly 
- Checked that platform On Response policies are executed and displayed in debug mode correctly
