### ISSUE TITLE
[Portal] Number of APIs display per Category is incorrect

### ISSUE THREAD

**Issue by RubenMMSantos** [gravitee-io/issues#6989]
When clicking on a category in Portal, the number of APIs displayed does not match the number of APIs that actually belong to that category

### Expected Behavior
Categories should display the APIs that belong to the category

### Current Behavior
APIs that don't belong to the category are displayed as if they they belong to it

### Steps to Reproduce (for bugs)
1. go to https://apim-release-test-console.cloud.gravitee.io/#!/environments/default/settings/categories
2. Click on one of the categories
3. Scroll down and notice the APIs that belong to the category
4. go to https://apim-release-test-portal.cloud.gravitee.io/catalog/categories
5. Click on the same category as before
6. notice the APIs displayed do not match what is set on the Console side

### Your Environment
* envir: https://apim-release-test-console.cloud.gravitee.io/#!/environments/default/settings/categories/new-category / https://apim-release-test-portal.cloud.gravitee.io/catalog/categories
* Version used: 3.15.0-SNAPSHOT
* Browser Name and version: Google Chrome Version 97.0.4692.99
* Operating System and version: Mac OS v11.6.1

MORE INFO: Issue also reproducible on **Master** and **3.13.X**

![Screenshot 2022-01-24 at 11 12 36](https://user-images.githubusercontent.com/14939456/150777241-ddfc4b81-e115-49b1-8251-099ccbb1f407.png)
![Screenshot 2022-01-24 at 11 13 54](https://user-images.githubusercontent.com/14939456/150777244-d67027c1-4c51-4651-b22a-afd6a6553c66.png)

**Comment by mouligno** [comment]
LGTM

**Comment by RubenMMSantos** [comment]
issue re-tested and confirmed as fixed.

Tested on envir: https://apim-release-test-console.cloud.gravitee.io/#!/environments/default/settings/categories / https://apim-release-test-portal.cloud.gravitee.io/catalog/categories
