### ISSUE TITLE
Only getting "No context-path matches the request URI" as a response

### ISSUE THREAD

**Issue by Cynicide** [gravitee-io/issues#699]
Hello,

We have downloaded the docker distribution of Gravitee and we're trialing it with our API. We have imported a swagger file and set up an application and a subscription (keyless). I have also made the API public in the general tab. At the moment even though we are providing the correct context-path the gateway still advises that there is no match.

### Expected Behavior

We would expect to see a response from our API filtered through Gravitee.

### Current Behavior

At the moment we get "No context-path matches the request URI." I have checked the logs for the gateway and there is nothing logged after startup. The gateway shows up in instances and appears to be healthy. I have ticked on "Dump HTTP requests" but nothing shows up in the gateway logs.

### Steps to Reproduce (for bugs)

1. Send a request to http://<ipaddress>:8000/apiname/
2. Get "No context-path matches the request URI." back

### Context

At the moment there is no effect as we're only trialing the product, but my CTO is providing pressure to get something in place.

### Your Environment

* Version used: Gateway is 1.8.1 (build: 195)
* Browser Name and version: Chrome 59.0.3071.115 (Official Build) (64-bit)
* Operating System and version: Client: Windows 10, Server: Ubuntu Linux 16.04 LTS running Docker 1.12.3

**Comment by NicolasGeraud** [comment]
hi @Cynicide 
is your api started ?
<img width="175" alt="capture d ecran 2017-07-20 08 20 22" src="https://user-images.githubusercontent.com/1028285/28403263-52ef1e52-6d24-11e7-80bf-1491f4f7d279.png">

**Comment by NicolasGeraud** [comment]
By the way, if your CTO need a professional support, let him know that GraviteeSource could help him.
https://graviteesource.com

**Comment by Cynicide** [comment]
Hi Nicolas, thanks for your reply. I have just checked and yes the API is started.

**Comment by brasseld** [comment]
Hi @Cynicide, can you tell us what is the context-path you settled for your API in Gravitee ?

**Comment by Cynicide** [comment]
Sure, it's /evsrestapi-rc this was chosen via the swagger import.

![2017-07-20 20_40_31-gravitee io management](https://user-images.githubusercontent.com/13057767/28413662-c5686102-6d8b-11e7-8419-bddc6f38c32c.png)

**Comment by brasseld** [comment]
So your gateway should be accessible from http://gateway_host:gateway_port/evsrestapi-rc

No ?

**Comment by Cynicide** [comment]
Yes, that is correct. I've posted a screenshot of the output and the url in case there are any issues with it.

![context-pth-error](https://user-images.githubusercontent.com/13057767/28414338-8b3d2028-6d8e-11e7-89a7-aaac4da68cb8.jpg)

**Comment by brasseld** [comment]
I you have a a look to gateway logs, you must see your API deployment.
Is it the case ?

**Comment by Cynicide** [comment]
OK, I restarted the gateway to generate a fresh set of logs. I can see it connecting to mongo and loading plugins but I can't see it loading any API. If I connect to mongo I can see two collections. Events and RateLimit. Should there be another collection for API's?

**Comment by brasseld** [comment]
For sure you must have more collections !
Others collections are : `apis` `applications` `pages` ...

Are you using our docker compose `demo` ? Or you are using your own docker containers ?

**Comment by Cynicide** [comment]
I'll have to check as I didn't set this up myself, a colleague did. It was deployed as a stack in Rancher and there may have been changed made to make it work. In this case I suspect what's being created in the webui is not making it to mongo. Can you confirm, does the WebUI write directly to mongo or does it call the management api to make changes? Based on that I'll look at the logs for the management ui or management api more closely.

**Comment by brasseld** [comment]
Ok, so every action done on the WebUI is dispatched to Management-API which is responsible to write into MongoDB.

If you see your API in the portal, it means that this one is registered in MongoDB.
So I'm pretty sure that the gateway and the management-api are not using the same MongoDB instance...

**Comment by Cynicide** [comment]
Thanks everyone. If anyone else comes in with a similar issue. The problem was the person who deployed the traefik docker compose and I'm not sure was deployed on this environment as a result demo.gravitee.io was being resolved externally.

**Comment by brasseld** [comment]
Do you mean that your colleague use this docker-compose file: https://github.com/gravitee-io/gravitee-docker/blob/master/environments/demo/docker-compose-traefik-latest.yml

And by doing so, `demo.gravitee.io` has been resolved externally ?
