### ISSUE TITLE
Toggle Shared API-Key Mode

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6990]
## :rainbow: Feature

As an administrator, I can toggle on/off the shared API-Key Mode at environment level.

## :sunrise_over_mountains: Additional information

ON - API Consumer are proposed to use a shared API-Key across application.
OFF - Keep actual behavior - One API-Key / subscriptions

By default, this mode is toggled off.
Using custom key, you can still use the same key for several apis on a application

settings > 
## :link: Dependencies

Link a story or other related things...

## :camera: Mockups 
<img width="1475" alt="Capture d’écran 2022-02-08 à 14 31 27" src="https://user-images.githubusercontent.com/3227037/152997191-d0392ed9-c57f-4215-aede-25ffda952679.png">

Insert screenshots, drawings...

## :books: Documentation required

Provide link to the issue for documentation update

## :superhero: Acceptance criteria

- [ ] Given '...'
- [ ] Then '...'
- [ ] When '...'

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :heavy_check_mark: Definition of Done

***For each User Story everything on the list must be considered, select only what was required***
- [ ] Acceptance criteria met and tested
- [ ] Sonar Cloud quality gate passes
- [ ] CircleCi checks pass
- [ ] Cypress or Postman API check passes
- [ ] Test containers passed if modifications on the repository modules
- [ ] Translation for portal UI checked
- [ ] Developer created draft documentation PR
- [ ] New migration scripts checked
Can be run multiple times but only makes changes the first time
Display to user what script has done
- [ ] Validated on appropriate environment
- [ ] Existing test cases refactored

:rocket:

**Comment by RubenMMSantos** [comment]
Issue tested on environment https://apim-master-console.cloud.gravitee.io/ with APIM version 3.17
Scenarios covered:
- [ ] option is displayed on Settings > Settings (turned off by default)
- [ ] with option turned off, popup is not displayed when creating at 2nd subscription between API and Application
- [ ] with option turned on, popup is displayed when creating at 2nd subscription between API and Application
