### ISSUE TITLE
[gateway] Redis sentinel is not working well with vertx-redis-client

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#6993]
## :collision: Describe the bug

We recently move from lettuce to vertx-redis-client for performance reasons. Unfortunately, we discovered that the sentinel mode is not well supported and the vertx-redis-client seems to continuously send request to the sentinel server to get the master url (or something like this). After multiple calls, it simply stop working.

The idea is to rollback to lettuce and open an issue on vertx github repository. We will switch back to vertx redis client once the issue is resolved.

## :sunrise_over_mountains: To Reproduce
N/A

## :rainbow: Expected behaviour
We should continue to support Sentinel mode in 3.15.

## :movie_camera: Useful information
N/A

## :computer: Desktop :

***Please complete the following information:***
N/A
## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

Latest 3.15

## :link: Dependencies

N/A

**Comment by RubenMMSantos** [comment]
waiting on info about how to test or if it can be tested

**Comment by phiz71** [comment]
It's quite technical and already well tested locally.
