### ISSUE TITLE
[APIM] Can Transfer Ownership via cURL or Postman where there is no Primary Owner in the Group.

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#6994]
## :collision: Describe the bug
I am able to Transfer Ownership of an API to a Group where there is no Primary Owner by only via Postman or cURL. I am not able to do this via the UI. 

## :sunrise_over_mountains: To Reproduce
1. Create a simple API like for ex. Echo.
2. Create a Group and use the test users which are available by default.

![image](https://user-images.githubusercontent.com/57534152/150827930-868fc1bc-28b1-4996-ac5a-91e6f6f4d886.png)

3. Go to Postman or via cURL POST to this URL:
`http://localhost:8083/management/organizations/DEFAULT/environments/DEFAULT/apis/<apiID>/members/transfer_ownership`

This this body:

```
{
  "id": "<groupID>",
  "type": "GROUP",
  "role": "Primary Owner"
}

```
4. Then go to the Console and you will see that the GROUP you Transferred Ownership which does not have a Primary Owner is now the Primary Owner of the API.

## :rainbow: Expected behavior
Just like with the UI we should not be able to Transfer Ownership to a Group in which there is no Primary Owner.

## :computer: Desktop :

***Please complete the following information:***
 - OS: Windows 10, Docker-Desktop
 - Browser: Google Chrome

## :warning: Potential impacts

***What are the impacted versions?***
- 3.10.8, 3.10.10

**Comment by mouligno** [comment]
LGTM
