### ISSUE TITLE
Issue when deleting the properties of a dictionary

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#6996]
When trying to delete a property in the dictionaries, after save properties is clicked, the deleted property is back there (not deleted).

In addition, a video with the exact behavior.

https://user-images.githubusercontent.com/89140082/150954405-54c972b6-7ae9-4d08-882a-9d4e56e159b3.mp4

Used versions: APIM 3.10.9

**Comment by RubenMMSantos** [comment]
issue verified and confirmed has fixed.
verified on envir 3-10-X
