### ISSUE TITLE
[console] minified version  of vendors~app-7d7faf8af18040ceb269.js

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#7001]
## :collision: Describe the bug
When accessing the APIM Console, the downloaded javascript file (vendors~app-7d7faf8af18040ceb269.js) appears to be an un-minified version of Angular v12.2.3. 
It should be moved to a minified version.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Open the DevTools of your browser 
2. Make an access to the UI Console
3. Check the content of the downloaded javascript files

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop :

***Please complete the following information:***

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by Spitfire1900** [comment]
I am still interested in seeing this get released.
