### ISSUE TITLE
[Import/Export API] Add crossId, identifying entities across environments

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#7003]
As an API Publisher, I want to be able to promote my API through several environments with consistency.

### Current behavior 

If I promote API1 from A to B to C and then update API1 on A then promote to C => the API can't be promoted

### Expected behavior

Promotion of an API from/to any environment is consistent and it's still the same API.
Same behavior for Import/Export since it's the same feature but manually (or through a CI/CD)

### Entities identified for crossId
- API
- Plans
- Pages

### Retro compatibility
Generate crossId on export API
When importing, we may use old behavior if crossId isn't reference yet

### crossId definition
Random string 

### Potential impacts
- Duplicate API
- Import/export API
- Promote API
- Rollback API
- API Creation

### More informations

https://gravitee.slab.com/posts/adr-005-apim-api-promote-import-cross-environment-identifier-ekt7hmlr

**Comment by omatthewsgravitee** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Graviteeio---API-Management-601c1f73be51260015c7bb26/issues/gravitee-io/issues/7003?planning-poker) with ZenHub @a-cordier @mouligno @marcambier @RubenMMSantos

**Comment by a-cordier** [comment]
Set up
--
  - Two env. on cockpit, `DEV` and `UAT`
  - DEV and UAT linked to seperated installations, using their own databases.
  - An API that contains plans and page to be promoted between the two environments. page has a folder hierarchy to ensure parent child relationship is preserved

Behaviour
--
|source|target|operation|comments
|---|---|---|---|
|3.10 DEV|3.10 UAT|Create|Is created on target env with same plans and pages. Plans are not created in the same order
|3.10 DEV|3.10 UAT|Update|⚠️ Error on plans (you can't delete a plan with subscriptions. You need to close the plan to accept promote. Closing subscription does not solve the problem. Pages updates look ok (no duplicates). The order of the plans changes randomly on destination 
|3.15 DEV|3.10 UAT|Create|Same behaviour as above
|3.15 DEV|3.10 UAT|Update|Same behaviour as above
|3.15 DEV|3.15 UAT|Create|Works as expected, order of plans is preserved
|3.15 DEV|3.15 UAT|Update|No error on plan updates that have an active subscription, no need to close the plan
|3.16 DEV|3.15 UAT|Create|Same as before
|3.16 DEV|3.16 UAT|Update|Same as before (works as expected)
|3.15 UAT|3.16 UAT|Update|Reverse promotion is not supported (this is expected)
|3.16 DEV|3.16 UAT|Create|❓Plans are not created in the same order  
|3.16 DEV|3.16 UAT|Update|Same as before, plan order is preserved
|3.16 UAT|3.16 DEV|Update|Backward promotion works
