### ISSUE TITLE
[management] "Host" header not overwritten if redefined in Endpoint configuration

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#7007]
## :collision: Describe the bug
When setting the "Host" header in the endpoint configuration, it does not overwrite the default but get duplicated instead.
This is preventing Policies such as "Dynamic routing" to perform correctly if Host header is used in it.

## :sunrise_over_mountains: To Reproduce
1. Create a simple API in 3.13.3 or 3.14.0
2. In the Endpoints configuration, add a new header called "Host" with any kind of value
3. Call the API and check the logs -> 2 "Host" entries will appears in the Headers 
4. Perform the same steps in 3.9 or 3.10.10 -> Only one Host entry is see in gateway headers

## :rainbow: Expected behavior
appears to be a regression from 3.10/3.9

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material:

3.14 Version
<img width="423" alt="Capture d’écran 2022-01-27 à 18 41 35" src="https://user-images.githubusercontent.com/79909781/151416683-81d8566a-64e3-4265-98f7-d91b7113d21d.png">

3.10.10 Version
<img width="402" alt="Capture d’écran 2022-01-27 à 18 26 02" src="https://user-images.githubusercontent.com/79909781/151416702-3751cc98-ca27-4472-9147-2de8a59b49de.png">

## :computer: Desktop :

***Please complete the following information:***
 - OS: Windows 10, Docker-Desktop
 - Browser Google Chrome

## :warning: Potential impacts

***What are the impacted versions?***
- 3.14.0/3.13.3 works as expected in 3.9 and 3.10.10

**Comment by RubenMMSantos** [comment]
Issue confirmed as fixed and working as expected
verified on https://apim-3-15-x-console.cloud.gravitee.io
