### ISSUE TITLE
[management] [mfa] Recovery codes

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#7014]
## :rainbow: Feature

If a user loses or is otherwise unable to use the enrolled MFA factor, this feature will allow the user to input a recovery code to bypass the factor and get access to their account.

## :sunrise_over_mountains: Additional information

- Create a new MFA Factor Recovery code plugin (validate recovery codes by looking into the database)
- Generate recovery codes during MFA enrollment process (if the option is enabled in the application settings)

## :books: Documentation required

Provide link to the issue for documentation update

## :superhero: Acceptance criteria

- [ ] Given 'a user trying to authenticate'
- [ ] Then 'the user has been successfully authenticated'
- [ ] When 'using their MFA recovery code'

## :warning: Potential impacts

***What are the impacted versions?***

3.17.0

## :heavy_check_mark: Definition of Done

***For each User Story everything on the list must be considered, select only what was required***
- [ ] Acceptance criteria met and tested
- [ ] Sonar Cloud quality gate passes
- [ ] CircleCi checks pass
- [ ] Cypress or Postman API check passes
- [ ] Test containers passed if modifications on the repository modules
- [ ] Translation for portal UI checked
- [ ] Developer created draft documentation PR
- [ ] New migration scripts checked
Can be run multiple times but only makes changes the first time
Display to user what script has done
- [ ] Validated on appropriate environment
- [ ] Existing test cases refactored

:rocket:

**Comment by omatthewsgravitee** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Graviteeio---Access-Management-5b17f74af58c642fb89cc49f/issues/gravitee-io/issues/7014?planning-poker) with ZenHub @ashraf706 @leleueri @patelami @remisultan @TrikyGeeky

**Comment by patelami** [comment]
Env: Nightly

Given I am existing user to the application
And Recovery code MFA is activated on my application domain
And I initiate login flow
Then I should see option to download recovery code

Given I am new user of an application 
And Recovery code MFA is activated on my application domain
And I initiate login flow
Then I should see option to download recovery code

Given I have used the recovery code once to login to the application
And I initiate a login flow again
And use same recovery code
Then I get invalid code error message
And I am not able to login to the application

Given I am new user of an application 
And Recovery code MFA is activated on my application domain
And I initiate login flow and enter valid email factor code
Then I am presented with recovery codes with options to download
And I have not clicked on continue
And I sign-out
And I initiate the login flow again
Then on successful login I should see recovery code again
