### ISSUE TITLE
[management] [gateway] add RESET_PASSWORD flow

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#7015]
## :rainbow: Feature

Add a new flow step to customize the reset password journey of users, for example :

- Trigger a webhook call
- Add custom verification

## :books: Documentation required

Update this documentation page : 

https://docs.gravitee.io/am/current/am_userguide_policies.html

Provide link to the issue for documentation update

## :superhero: Acceptance criteria

- [ ] Given 'a user wants to reset its password'
- [ ] Then 'the policy will be triggered'
- [ ] When 'the user reset its password with a POST RESET_PASSWORD policy'

## :warning: Potential impacts

***What are the impacted versions?***

3.17.0

## :heavy_check_mark: Definition of Done

***For each User Story everything on the list must be considered, select only what was required***
- [ ] Acceptance criteria met and tested
- [ ] Sonar Cloud quality gate passes
- [ ] CircleCi checks pass
- [ ] Cypress or Postman API check passes
- [ ] Test containers passed if modifications on the repository modules
- [ ] Translation for portal UI checked
- [ ] Developer created draft documentation PR
- [ ] New migration scripts checked
Can be run multiple times but only makes changes the first time
Display to user what script has done
- [ ] Validated on appropriate environment
- [ ] Existing test cases refactored

:rocket:

**Comment by omatthewsgravitee** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Graviteeio---Access-Management-5b17f74af58c642fb89cc49f/issues/gravitee-io/issues/7015?planning-poker) with ZenHub @leleueri @remisultan @patelami @TrikyGeeky @ashraf706

**Comment by patelami** [comment]
Env: Nightly
Result: PASS

Given I have setup Latency policy on Reset Password flow
And I have set up a value of 5 seconds in the Latency policy
And I initiate login flow
And I request a password reset
Then I should see latency of 5 seconds
