### ISSUE TITLE
[Console] Not full log message is displayed in logs while the full one is received.

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#7017]
## :collision: Describe the bug
When we sent a request though Postman and later we go to the Logs and view the request we just made you will be able to see that the full request message is not displayed while we get the same full and correct message in our Endpoint.

As an FYI I tested this in 3.10.3 and the Logs show the full message of the request. The issue is in 3.10.8 and 3.10.10

## :sunrise_over_mountains: To Reproduce
1. Create/Import a simple API ex. Echo.
2. In endpoint of the API use your own https://webhook.site/ URL to test.
3. Bellow you will a file in which we have a json which you can use to test in Postman.
4. Test with POST method in Postman using the message bellow and then check if you got the same message in https://webhook.site/ .
5. Now to to the LOGS in your Analytics and you will see that most of the message is not present.

![image](https://user-images.githubusercontent.com/57534152/151389738-f75fe873-a11b-4576-9f70-79555d03451f.png)

## :rainbow: Expected behavior
We should be able to see the full request/response payload in the Logs of our API.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material:

[Sample.zip](https://github.com/gravitee-io/issues/files/7951608/Sample.zip)

## :computer: Desktop :

***Please complete the following information:***
 - OS: Windows 10, Docker-Desktop
 - Browser: Google Chrome

## :warning: Potential impacts

***What are the impacted versions?***
- 3.10.8, 3.10.10

**Comment by ThibaudAV** [comment]
https://github.com/gravitee-io/gravitee-api-management/pull/1270

**Comment by mouligno** [comment]
LGTM

**Comment by LiliaEn** [comment]
Tested on the 3.10 env
Browser: Chrome Version 97.0.4692.99 , macOS Big Sur v11.6
Works as expected
![Screenshot 2022-02-21 at 10 00 38](https://user-images.githubusercontent.com/49516050/154932513-3a580f17-fffa-4a96-b790-4ba49e0307de.png)
