### ISSUE TITLE
[policy] [jwt] No clear understanding on How the JWT policy can be used for gateway authentication

### ISSUE THREAD

**Issue by danc** [gravitee-io/issues#702]
After reading #462, I can't have a clear understanding of the use of JWT policy

### Expected Behavior
I may  have a limited understanding of the usage of JWT, but here's what I understood so far  : 
- An external application can provide a jwt token containing some claims and signed info, allowing API authentication
- this single token could be used on gravitee gateways to authenticate an API call based on its JWT policy.
- signature of a JWT token is based on a secret (stored in gravitee.yml config)

"The gateway is responsible of authorizing the incoming HTTP request by validating the provided JWT token" : on which information does the gateway rely to authorize the HTTP request ???

based on the info found in gravitee.yml, I just find the secret and the issuer as JWT content related info : are they the only minimal info we need to use during  JWT token creation ?

### Context
I try to generate a JWT token from a python script : 
```
import jwt
encoded = jwt.encode({'sub': 'admin', 'iss': 'gravity-management-auth'}, 'myJWT4Gr4v1t33_S3cr3t', algorithm='HS256')
```
and use this token to call a defined API 
```
 curl  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJncmF2aXR5LW1hbmFnZW1lbnQtYXV0aCIsInN1YiI6ImFkbWluIn0.Og3YEfb9gUcRdl_SwH4GF2-GyyAkFU0-4AUJMxW_8Kg"    http://localhost:8000/myapi
```

Is my test too simplistic or do I miss some background understanding ?

Could you describe a minimal but working example of JWT policy in action ?

### Your Environment
#
* Version used: 1.8.1 (docker)
* Browser Name and version: Firefox 54.0
* Operating System and version: Ubuntu 16.04

**Comment by brasseld** [comment]
Hi @danc 

I think you misunderstand the JWT policy and the way it works.
Typically, JWT is provided by an authorization server which is compliant with OpenID specification.
This authorization server is responsible to generate this JWT and which is including several information (claims). Then, this JWT is used by consumer to call an API by putting it in Authorization header.
The authorization server is using a private key to `sign` the JWT and you have to pass the public key to the JWT policy to validate the incoming token.

What do you want to achieve exactly ? Do you need an authorization server ? In this case, you can use the gravitee.io one called Access Management. It is an OAuth2 / OpenID server to manage authorization.

About your test case, I think you miss an expiration date in your JWT. Also you have to sign it and provide the public key to the JWT policy.

I would be happy to help you if you need more.

Regards,

**Comment by danc** [comment]
OK thanks for the first insights.
I Suspected Access Management was mandatory to authenticate the user and provide the right JWT token (thus I tried with raw python programmation).  Unfortunately, Gravitee AM doesn't seem available as docker images like API management (which are very clean and easy to use !). So it requires a bit more more to be put in practice. 
I'll try it, but the doc seem to be work in progress on this points.

**Comment by brasseld** [comment]
No, Access Management is not mandatory. It is just easier to use it to generate a 'valid' JWT and use a public key with JWT policy.

Anyway, your note about docker for AM is absolutely right and we have to provide the same easy-to-use docker images for AM!

About your test case, can you tell me which python library you are using to generate JWT token ?
What is missing on your side is:
* Use a private key to generate the JWT token
* Add an expiration date claim to the JWT token (`exp`)
* Use public key in JWT policy.

Tell your python lib (pyJwt ?) and I will have a look asap to make it works for you.

Regards,

**Comment by danc** [comment]
Thanks for your kind answer, I just tried to put up a quick and dirty basic example with pyjwt, your are right, but in my final use case, I'd have to rely on a LDAP server for user authentication and management for API access. 
I succeeded in connecting a LDAP server to management API (and added LDAP users to API management), but I'm missing the auth and end-to-end use case.

**Comment by brasseld** [comment]
So, that the reason to live of Access Management !

We are providing a LDAP connector to Access Management. By using it, end-to-end are generating token (access_token Oauth2, JWT, id_token, ...) using Oauth2 `API` (specification is probably a better word here).

So, for you, only docker containers are missing for AM ?

**Comment by danc** [comment]
Yeah, I think so.
Loved the rest of what I saw , mostly.

**Comment by brasseld** [comment]
Ok, let me know how can I can help you.
I will be glad to help you on these topics.

Also, I will try to provide you with a working (but dirty) example using PyJWT asap.

**Comment by danc** [comment]
I'll try to build the docker images for Access Management, based on the existing doc. (but if you have plans to do so, let me know )
This will make my day !
Thanks for your help !

**Comment by brasseld** [comment]
We have plan, but our biggest challenge is the time... and actually... we have no time for this kinf of stuff... unfortunately.

In any case, I will be happy to help you to 'build' these docker images. If you want, we can have a chat on gitter (https://gitter.im/gravitee-io/gravitee-io) to make conversation a bit easier.

**Comment by brasseld** [comment]
Hi @danc,

We are now providing a docker-compose to start quickly with Gravitee.io AM.
Also, you may found helpful documentations at https://docs.gravitee.io/am_quickstart_secure_apis.html

**Comment by danc** [comment]
Thanks ! I'll play soon with it !

**Comment by brasseld** [comment]
Cool, please provide feedback !

```shell
curl -L http://bit.ly/graviteeio-am | bash
```

**Comment by yogeshgarg1904** [comment]
Hi, we have tried many ways to validate the token, but it is not working. We have created the application and subscribed with the API and same we have given in the payload also but still not working. 

Please help!

![image](https://user-images.githubusercontent.com/15274040/73911986-5cc8fb80-48d9-11ea-9eed-68e23c4ad110.png)


![image](https://user-images.githubusercontent.com/15274040/73912076-9ef23d00-48d9-11ea-9f2f-87b3cab0e6bf.png)
