### ISSUE TITLE
Policy Rest-to-Soap doesn't work anymore

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#7025]
## :collision: Describe the bug
The rest2soap policy now crash with:
```
{
    "message": "java.lang.NoSuchMethodError: 'io.gravitee.common.http.HttpHeaders io.gravitee.gateway.api.Request.headers()'",
    "http_status_code": 500
}
```
## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. import [demo-demo.json.zip](https://github.com/gravitee-io/issues/files/7965996/demo-demo.json.zip)

2. execute the request ```curl --location --request GET 'http://localhost/apim/gateway-dev/demo' 
--header 'Content-Type: application/json' 
--data-raw '{
    "intA":1,
    "intB":6
}'```
3. You have the error
4. remove the soapAction in the policy config and enable the TransformHeader policy to enable the workaround

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***
Depending on the reason of this issue, other policies could be impacted

***What are the impacted versions?***
 - version 3.15.0 (don't know when iut has been introduced)

**Comment by RubenMMSantos** [comment]
Hey @ytvnr is the response in the screenshot the expected response? 

![Screenshot 2022-01-31 at 13 46 16](https://user-images.githubusercontent.com/14939456/151804843-13725c23-df34-46ae-9050-edc36d75dce2.png)
