### ISSUE TITLE
Allow helm chart to disable/enable the newsletter signup for apim3.x

### ISSUE THREAD

**Issue by oyviaase** [gravitee-io/issues#7027]
## :rainbow: Feature

**As a** 'helm user'

**I want to** 'be able to disable the newsletter popup in apim3.x by setting a value in the helm values file'

**So that** 'my users aren't annoyed by a newsletter popup about a newsletter they probably aren't interested in'

## :sunrise_over_mountains: Additional information

Nothing

## :link: Dependencies

Nothing

## :camera: Mockups 

Nothing

## :books: Documentation required

[The helm documentation](https://docs.gravitee.io/apim/3.x/apim_installguide_kubernetes.html) will need an update

## :superhero: Acceptance criteria

- [ ] Given 'a set value in the values file'
- [ ] Then 'disable the newsletter popup'
- [ ] When 'said value is set to false'

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***
The newsletter popup isn't always shown to end users the first time they login/sign up to an helm installed apim3 instance.
***What are the impacted versions?***

## :heavy_check_mark: Definition of Done

***For each User Story everything on the list must be considered, select only what was required***
- [ ] Acceptance criteria met and tested
- [ ] Test containers passed if modifications on the repository modules
- [ ] Developer created draft documentation PR
- [ ] New migration scripts checked
Can be run multiple times but only makes changes the first time
Display to user what script has done
- [ ] Validated on appropriate environment
- [ ] Existing test cases refactored

:rocket:

**Comment by gaetanmaisse** [comment]
🚀  Released in 3.1.34
