### ISSUE TITLE
[portal] [logs] Is there a way to filter requests in Logs screen

### ISSUE THREAD

**Issue by Joindewalvis** [gravitee-io/issues#703]
### Expected Behavior
In the Logs screen I get an overview of all requests in a table, with the follwoing fields:
Request Id | Method | Path | Status | Response time | Application | Plan | Date

I would like to filter on these fields, or even on some of the detail fields, displayed when you click on the 'eye' at the end of a request row.

### Current Behavior
Currently I'm only able to filter on the timeframe.

### Possible Solution
Add additional filter options above the table with requests

### Your Environment

* Version used: 1.8.1

**Comment by brasseld** [comment]
Hi @Joindewalvis 
Currently, there is no way to filter from the logs screen itself. We are looking to provide such filters in a future version.
The only way to filter logs is from the analytics screen where you have a 'view logs' button in the 'timeframe' section.

<img width="1435" alt="capture d ecran 2017-07-21 a 19 12 00" src="https://user-images.githubusercontent.com/133094/28474360-afe36634-6e48-11e7-91cf-ea06f8ec6f66.png">

**Comment by Joindewalvis** [comment]
Hi, 
Is there a way to query this log-information myself? Does the underlying management-api support custom queries on the log, and if not where can I adjust this?

**Comment by brasseld** [comment]
Hi @Joindewalvis,

The only way to query lof information is to call Elasticsearch. 
Currently, the management API does not support queries on the log but we have several users / customers who are waiting for such feature.
You can have a look to https://github.com/gravitee-io/gravitee-management-rest-api/blob/master/gravitee-management-api-service/src/main/java/io/gravitee/management/service/impl/LogsServiceImpl.java

**Comment by Joindewalvis** [comment]
Thx for the info

**Comment by brasseld** [comment]
I'm re-opening this issue because this feature must be implemented in future version of Gravitee.io
