### ISSUE TITLE
[Gateway] Step 3.b - save server response

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#7039]
During a debug session, we should save the api's backend answer as a dedicated step.

### Possible Solution
Two possibilities:
1. create a step of type "backend" and fill it with the content of the response
2. as we done for policyChainFactory, create a dedicated `InvokerDebugDecoratorFactory`, with that, we are able to save content from backend, and elapsed time during backend processing

### Chosen solution

Use a InvokerDebugDecorator to decorate the ProxyConnection and write it to the DebugExecutionContext

--

To test: 
- Go to try it and send a debug request
- Look in the console that you have a `payload` attribute containing some a `backendResponse` attribute in the response

**Comment by LiliaEn** [comment]
Tested on the default env,  v3.16
Browser: Chrome Version 97.0.4692.99 , macOS Big Sur v11.6
`backendResponse` attribute is displayed in the response.
![Screenshot 2022-02-14 at 12 46 02](https://user-images.githubusercontent.com/49516050/153866919-48b53a5e-c967-4ad4-95f3-1aa281de3339.png)
