### ISSUE TITLE
Flow configuration screen not updating properly

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#7043]
When designing new flows, and trying to switch between the flows, always seeing one flow (the configurations used are not updated).

Attached a video of the behavior:

https://user-images.githubusercontent.com/89140082/152328063-b734d421-b817-4d45-8d61-ca8f736c5d81.mp4

Used versions: APIM 3.10.10, 3.15.0

**Comment by marijatimovska** [comment]
Please contact me when working on this ticket so I can share more information.

**Comment by mouligno** [comment]
Flows are updating accordingly
