### ISSUE TITLE
Errors when using MSSQL db - i.g.g.s.s.s.ApiSynchronizer - Unable to extract api definition from event [9b4ef96b-0036-4997-8ef9-6b0036599742].

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#7049]
Receiving error i.g.g.s.s.s.ApiSynchronizer - Unable to extract api definition from event [9b4ef96b-0036-4997-8ef9-6b0036599742]

Created new installation of APIM with MSSQL with docker-compose. After the installation was completed I created and deployed simple api in the console and I got that error in the gateway logs:

 i.g.g.s.s.s.ApiSynchronizer - Unable to extract api definition from event [9b4ef96b-0036-4997-8ef9-6b0036599742]

The api is also not accessible with postman. We are getting the error:
No context-path matches the request URI. 
I Also get 404 status, and we get the following error in the gateway log:

i.g.g.r.p.notfound.NotFoundProcessor - No handler can be found for request /test, returning NOT_FOUND (404)

**Comment by apoddany** [comment]
linked to #7053
