### ISSUE TITLE
Add & delete of a scope creates duplicates in scope list

### ISSUE THREAD

**Issue by ctschacher** [gravitee-io/issues#7055]
1.  ## <g-emoji class="g-emoji" alias="boom" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4a5.png">
     💥 
     </g-emoji> Describe the bug Every time a scope is added & deleted it creates a duplicate in the scope list. The duplicates, however, disappear again after leaving the scope section and coming back.
2.  ## <g-emoji class="g-emoji" alias="sunrise_over_mountains" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f304.png">
     🌄 
     </g-emoji> To Reproduce Steps to reproduce the behaviour: 1\. Go to the Settings of an application --> OAuth 2.0 / OIDC --> Scopes 3\. Click on ADD SCOPES & choose one scope 4\. Delete that scope again 5\. Click on ADD SCOPES again and you'll see that this scope now exist more than once in the list (in fact, one duplicate is added everytime you add & delete one)
3.  ## <g-emoji class="g-emoji" alias="movie_camera" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f3a5.png">
     🎥 
     </g-emoji> Useful information !<span class="error">[Screenshot 2022-02-04 at 16 27 13]</span>([https://user-images.githubusercontent.com/15231507/152556954-a5cca746-fd4e-4759-9cca-d764292b360e.png](https://user-images.githubusercontent.com/15231507/152556954-a5cca746-fd4e-4759-9cca-d764292b360e.png))
4.  ## <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">
     💻 
     </g-emoji> Desktop :

**Please complete the following information:**

*   OS: macOS Monterey 12.2
*   Browser: Chrome

**What are the impacted versions?**

*   so far only tested with AM v3.14.1

**Comment by gaetanmaisse** [comment]
Closing as it looks to be fixed in AM 3.18+
