### ISSUE TITLE
[managemen] Image not found when sending a email

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#7057]
If I try to send an email I get the following error:
```
Error while sending email notification
org.springframework.mail.MailSendException: Failed messages: javax.mail.MessagingException: IOException while sending message;
  nested exception is:
        java.io.FileNotFoundException: /opt/graviteeio-management-api/templates/images/GRAVITEE_LOGO_RVB-11.png
```

It seems that this file doesn't exist in the specified directory.

**Comment by RubenMMSantos** [comment]
issue verified and confirmed has fixed
verified on environment https://apim-3-15-x-console.cloud.gravitee.io/
![Screenshot 2022-02-07 at 12 07 18](https://user-images.githubusercontent.com/14939456/152785184-2610ef92-137c-4ca8-a5a3-e14a1c8f1dd7.png)
