### ISSUE TITLE
error after migration to 1.8.2 : no primary owner

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#706]
I just installed version 1.8.2.
i executed migration script convert role.

when i start ui, i have error for api without primary owner. Same with application
and same when call api : /management/apis

{
    "message": "11 apis has no identified primary owners in this list fa345a61-dbaf-41e1-b45a-61dbaf61e1a8 / 79d530f4-2e90-4b8f-9530-f42e90fb8f03 / 9e425efe-e11b-4257-825e-fee11b42572f / ea34659e-0719-4939-b465-9e0719c93909 / b8ef6d00-0fef-43ec-af6d-000fef53ece6 / e31b095e-63cc-4e61-9b09-5e63cc7e6183 / 29ee6c48-9808-4941-ae6c-4898084941a2 / 2b2c972f-2566-4f35-ac97-2f2566ff35d1 / c2afed65-eb48-4f87-afed-65eb48ff870e / 0223418b-e2ff-4b2d-a341-8be2ff6b2d79 / 16fde8ea-6344-4f62-bde8-ea63443f621a.",
    "http_status": 500
}

{
    "message": "22 applications has no identified primary owners in this list 9bf6c0de-c898-45de-b6c0-dec898b5dea1 / eacf261d-16f8-4c24-8f26-1d16f82c2419 / 7de7c738-29d8-4ed9-a7c7-3829d80ed93b / cc907cab-b254-4957-907c-abb25479575f / 19bd95e2-cde6-4740-bd95-e2cde6c74049 / 40644b49-4d77-44f8-a44b-494d7734f8b2 / ee4c6da9-f831-4e01-8c6d-a9f8314e0191 / 045d88bc-dafe-43a2-9d88-bcdafea3a24b / 88f20d86-d111-4913-b20d-86d111b913a4 / 60715d91-86b2-4b7d-b15d-9186b27b7dbb / f8a0e94a-4cd4-48e9-a0e9-4a4cd4e8e90a / 438377f9-4d35-420f-8377-f94d35f20fed / 9fcf5be0-6884-4708-8f5b-e06884770894 / 4dd3e5fe-dd28-4464-93e5-fedd28946494 / e080adb8-383d-40d9-80ad-b8383d10d93f / 55f01b36-44c1-461b-b01b-3644c1961be0 / 6fabc561-ef0a-4ca7-abc5-61ef0adca73f / dc8aab2f-e24f-498b-8aab-2fe24fc98bfb / 6236f963-fc88-4433-b6f9-63fc88f433a7 / eb96870e-e61a-4edc-9687-0ee61a7edccf / 36078ab8-d2ec-4cef-878a-b8d2ec7cef17 / 12f34f82-2816-404e-b34f-822816604e8a.",
    "http_status": 500
}

### Your Environment
* Version used: 1.8.2

**Comment by brasseld** [comment]
Hi @vdelattre,

Please provide logs when running migration script

**Comment by vdelattre** [comment]
log is just:
MongoDB shell version: 3.2.12
connecting to: gravitee
bye

**Comment by brasseld** [comment]
According to the script, you must have logs printed.
https://github.com/gravitee-io/release/blob/master/upgrades/1.8.0/mongodb/1-convert-roles.js#L14

Can you tell me how you run script ?

**Comment by vdelattre** [comment]
just:
 mongo gravitee < /data/db/1-convert-roles.js

**Comment by brasseld** [comment]
I think it's because you have tried to run script a second time to get logs, no ?

**Comment by vdelattre** [comment]
forgot this issue
i made mistake in creating migration script (all script whas in comment)

now it's ok
