### ISSUE TITLE
Release check automation - Snyk Integration using CLI

### ISSUE THREAD

**Issue by omatthewsgravitee** [gravitee-io/issues#7066]
Investigate the SNYK CLI

- automate Docker Image Scan

- Initiate scan for new maintenance branch and remove old branch

- any other helpful things

**Comment by gaetanmaisse** [comment]
WIP PR https://github.com/gravitee-io/gravitee-api-management/pull/1606

**Comment by gaetanmaisse** [comment]
See https://github.com/gravitee-io/gravitee-api-management/pull/1606#issuecomment-1108307472

**Comment by marcambier** [comment]
Snyk analysis is automated in release process. I close the ticket.
