### ISSUE TITLE
Release check automation: Difference in bundle size against previous version (in %)

### ISSUE THREAD

**Issue by omatthewsgravitee** [gravitee-io/issues#7067]
**Description**

The end goal is to display the difference in bundle size against the previous version (in %) in a slack notification. 

The size validation should be done just after the bundling, before pushing it to the download website. If the difference is too big then add a manual approval step + send notification on slack.

Reference here https://download.gravitee.io/#graviteeio-apim/distributions/

Variance rules:
Which team validate the bundle 
Difference < 1% : None
Difference < 5% : Scrum Team
Difference > 5% : Archi Team

**Comment by Hakim187** [comment]
PR is now created : https://github.com/gravitee-io/release/pull/487
