### ISSUE TITLE
Alert creation redirects from api to platform level

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#7086]
When in analytics and trying to get to alerts and create one alert on API level (for a specific API), when clicked on the plus button, to create new alert for that API, getting redirected to platform creation of an alert, and not an alert that is for that API precise:

![analytics_new_alert](https://user-images.githubusercontent.com/89140082/152994452-435d53c3-b855-4215-9e57-4392ecc9243f.png)

After clicking the alerts, expected behavior is to redirect to create an alert for the API, but instead getting redirected to platform alert creation:

![redirect2](https://user-images.githubusercontent.com/89140082/152994748-bcd41569-8943-4d2c-a123-a1b2cea0b2b0.png)

Used versions: APIM 3.10.9, AE 1.5.5

**Comment by LiliaEn** [comment]
Tested on the default env v3.18.0 
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Works as expected.
