### ISSUE TITLE
[APIM Console] Duplicate plans created on double click

### ISSUE THREAD

**Issue by yoga-v** [gravitee-io/issues#7087]
## :collision: Describe the bug
In the Gravitee APIM Console, duplicate plans are created if the create button is double clicked

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to APIM Console and navigate the plans
2. Click on Create a plan by following the steps and in the last section, double click the create button.
3. This will create duplicate plans with the same details.

## :rainbow: Expected behaviour
Duplicate plans should not be created.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop :

***Please complete the following information:***
 - OS: Windows 10
 - Browser Chrome v97

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by gaetanmaisse** [comment]
Closing as it has been fixed in the latest version of APIM thanks to the migration of the screen to Angular and a new UI 🎉 
![image](https://user-images.githubusercontent.com/4112568/216269876-7b959e1f-b80b-4d3e-b419-015daa2a2c67.png)
