### ISSUE TITLE
[Debug mode] View diff between input/output body

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7090]
## :rainbow: Feature

**As an** API Publisher

**I want to** view the diff between input/output body

**So that** I can understand what's happened

## :sunrise_over_mountains: Additional information

- Can be applicable at global/flow/policy level
- Color code to view diff : addition / edition / deletion
- respect the input/output line display to visually view the changes
- using a one column diff if display is easier 
- also include formating 

## :link: Dependencies

Link a story or other related things...

## :camera: Mockups 

https://www.figma.com/file/MxLXjCNRnhyMnpapRDgKOT/Try_iT_V4?node-id=291%3A461

## :books: Documentation required

https://github.com/gravitee-io/gravitee-docs/issues/630

## :superhero: Acceptance criteria

- [x] Given an input and output (policy/flow/global) then I can view that body has been added
- [x] Given an input and output (policy/flow/global) then I can view that body has been removed
- [x] Given an input and output (policy/flow/global) then I can view that body has been updated

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :heavy_check_mark: Definition of Done

***For each User Story everything on the list must be considered, select only what was required***
- [ ] Acceptance criteria met and tested
- [ ] Sonar Cloud quality gate passes
- [ ] CircleCi checks pass
- [ ] Cypress or Postman API check passes
- [ ] Test containers passed if modifications on the repository modules
- [ ] Translation for portal UI checked
- [ ] Developer created draft documentation PR
- [ ] New migration scripts checked
Can be run multiple times but only makes changes the first time
Display to user what script has done
- [ ] Validated on appropriate environment
- [ ] Existing test cases refactored

:rocket:

**Comment by LiliaEn** [comment]
Tested on the default env v3.17.0 
Browser: Chrome Version 98.0.4758.80 , macOS Big Sur v11.6
- Checked that new body is marked with green
- Deleted body is marked with red
- Updated body is marked with yellow
- Line by Line view is displayed correctly
- Side by Side view is displayed correctly
- Raw view is displayed correctly
