### ISSUE TITLE
[Portal]Documentation Swagger: Field is displayed as required in Portal while not set as required

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#7099]
# Describe the bug

When uploading a Swagger Page in .yaml there some filed that are not required are being set as required in the Portal, while in Console the fields are displayed as they should. This is only happening if the Swagger is is .yaml format. If we converte the same file to .json we will not see the same issue.

# To Reproduce

*   Create/Import simple API.
*   Go to Pages and import the Swagger bellow as a Swagger page.
*   See in the Console and compare with Portal the fields below: (GET/Documents)

!<span class="error">[image]</span>([https://user-images.githubusercontent.com/57534152/153607033-a267c353-84bd-4780-973a-26227979e884.png](https://user-images.githubusercontent.com/57534152/153607033-a267c353-84bd-4780-973a-26227979e884.png))

!<span class="error">[image]</span>([https://user-images.githubusercontent.com/57534152/153607099-879a879e-6fef-472e-9ffa-4e576b33c143.png](https://user-images.githubusercontent.com/57534152/153607099-879a879e-6fef-472e-9ffa-4e576b33c143.png))

*   See the error

# Expected behaviour

We should be able to have the same behavior in the Portal as in the Console.

<span class="error">[testSwagger.zip]</span>([https://github.com/gravitee-io/issues/files/8049220/testSwagger.zip](https://github.com/gravitee-io/issues/files/8049220/testSwagger.zip))

**Comment by mouligno** [comment]
@gravitee-io/apim couldn't it be link to the swagger lib on portal / console ?

**Comment by mouligno** [comment]
@marijatimovska I think it's the same :  https://github.com/gravitee-io/issues/issues/7510

**Comment by mouligno** [comment]
@marijatimovska did you check ?
