### ISSUE TITLE
[gateway] - too many organization registering when deploying organization flows

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#7101]
When modifying policies at organization level, an event is sent to register the new version of the organization flows (with policies)

### Expected Behavior
For an event, organization should be redeployed once.

### Current Behavior
For the same event, organization is registered many times.
![image.png](https://images.zenhubusercontent.com/60252d20f8dcd31b2b4afa22/0caf2be3-4dcf-41ff-a831-61df0f14b3fe)

### Possible Solution
Avoid manipulating the same event multiple times

### Steps to Reproduce (for bugs)
1. Go to Organization settings / Policies
2. Modify a flow
3. Save
4. Check the logs of the gateway to see the repetition of organization registration

### Your Environment
* Version used: 3.15.x

**Comment by gaetanmaisse** [comment]
Closing as per https://github.com/gravitee-io/gravitee-api-management/pull/2358#pullrequestreview-1094553565
