### ISSUE TITLE
Debug-> Long texts (tokens etc) are not wrapped and exceed the allocated screen

### ISSUE THREAD

**Issue by LiliaEn** [gravitee-io/issues#7106]
Long texts (tokens etc) are not wrapped and exceed the allocated screen

### Expected Behavior
Long texts should be wrapped and fit the screen

### Current Behavior
Long texts (tokens etc) are not wrapped and exceed the allocated screen
![Screenshot 2022-02-14 at 10.37.30.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/8eb9ae2e-acbe-413b-a9aa-83646380fc2f)

### Steps to Reproduce (for bugs)
1. Login to console
2. Create an API with e.g. Generate GWT Policy (or any other that will generate a token or some long texts) (On master, you can use "Echo with Generate JWT policy" API )
3. Go to Design-> Debug
4. Run a request
5. Scroll to the right to see the whole text/token

### Your Environment

* Version used: default env - v3.16.0
* Browser Name and version: Chrome Version 97.0.4692.99 
* Operating System and version: macOS Big Sur v11.6

**Comment by gaetanmaisse** [comment]
Closing as this view was only temporary and will be replace by the real screen in https://github.com/gravitee-io/issues/issues/6765
