### ISSUE TITLE
[management] add the id of the Identity Provider on GET /domains/:domaind/users/:userid

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#7108]
Currently , when using the API GET /domains/:domaind/users/:userid , it only returns the label of the Identity Provider as : 
("source": "Default Identity Provider")

Adding a sourceId field would allow to do a  GET /domains/domaind/identities/:identityid 

***Please complete the following information:***

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by leleueri** [comment]
The first implementation using new metadata parameter may not be the right one...

**Comment by leleueri** [comment]
The get User now provide a new field sourceId
