### ISSUE TITLE
[Debug Mode] View call metrics

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7111]
As an API Publisher, I want to view some metrics about my requests in order to analyze my work.

### List of metrics : 
- apiResponseTimeMs 
- proxyResponseTimeMs 
- proxyLatencyMs

### Tasks
- Spike test on the metrics to check value with real call
- if valuable - check with UX/UI to integrate this in mockups

<img width="1294" alt="Capture d’écran 2022-03-14 à 17 20 35" src="https://user-images.githubusercontent.com/1457497/158215779-d1cad08b-eb40-436b-813d-9b7b603f8dd2.png">

**Comment by LiliaEn** [comment]
Tested on the default env v3.17.0 
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Tested that the following metrics are displayed when running a request:

- apiResponseTimeMs
- proxyResponseTimeMs
- proxyLatencyMs
