### ISSUE TITLE
Json is only partially visible in editor under API Documentaiton

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#7116]
The json file in editor is only visible partially and you need to select all the lines to make it fully visible.
Attached a video.

Steps to reproduce the behaviour:
1. Api documentation
2. Click on import documentation from swagger
3. Try to inspect the imported json
4. Only partially shown the json on the left 

https://user-images.githubusercontent.com/89140082/154082526-b8e4c7a9-bdcc-421a-a310-e187ba10068e.mp4

Used versions: APIM 3.15.3, 3.15.2

**Comment by zveljanoski** [comment]
The same behavior detected with the portal documentation: 

https://user-images.githubusercontent.com/89140082/154088122-eade7b21-4c7c-43d7-8332-4a4f8c4e0902.mp4

**Comment by mouligno** [comment]
Closed as it been fixed with [#7017](https://github.com/gravitee-io/issues/issues/7017)
