### ISSUE TITLE
[debug mode] transform context path to be able to use it as in real life

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#7128]
## :rainbow: Feature

For the moment, debugged api are deployed using a transformed version of the path: `/api` becomes `/1234-api` where 1234 is the event id.

## How to test ?

Test with an API that has multiple paths (for example https://api.gravitee.io). Try to add policies playing with context path (`request.contextPath` or `attributes["context-path"])

- configure a flow `/echo`
- configure another flow `/whoami`
- test in try it mode that you can reach both of them.

![image](https://user-images.githubusercontent.com/47851994/154958394-dee471c4-3e3f-4d76-9cef-9990152ca2b1.png)

![image](https://user-images.githubusercontent.com/47851994/154958367-fc8c177f-5871-484c-8ac7-cebdd91e51a4.png)

Test it on the same gateway together

**Comment by LiliaEn** [comment]
Tested on the default env v3.17.0 
Browser: Chrome Version 98.0.4758.80 , macOS Big Sur v11.6

- Used an API with multiple paths and a few flows;
- Tested that when sending a request using the path of a certain flow, only that flow is executed and the resolved path is displayed correctly;
- Used a Mock policy with {#request.contextPath} in the Response body to checked if the correct context path is returned;
- When sending a request without specifying a path, the flows defined with specific paths will not get executed;
