### ISSUE TITLE
[management-webui]Portal default user picture relative url

### ISSUE THREAD

**Issue by AYCsen** [gravitee-io/issues#713]
The default user picture relative url seems to be wrong. It doesn't take the "/portal" of our default URL, because of **"/"** before **"assets/default_user_picture"**.
(This only happen with the default user picture, since only default user picture use relative url)

### Expected Behavior
Default user picture in the navbar : 
![expected_image](https://user-images.githubusercontent.com/30430994/28612311-2c760d2e-71ef-11e7-85bf-269c186b5749.PNG)
With this code :
![expected_code](https://user-images.githubusercontent.com/30430994/28612357-4ec412f4-71ef-11e7-8962-247f12877cdd.PNG)

### Current Behavior
Default user picture in the navbar : 
![image](https://user-images.githubusercontent.com/30430994/28612332-3d2e3ce0-71ef-11e7-97fc-0d7cfd3ac9d7.PNG)
With this code :
![code](https://user-images.githubusercontent.com/30430994/28612356-4ec0af92-71ef-11e7-8869-43e7110130d1.PNG)

### Environment

* Version used: 1.8
* Browser Name and version: Google Chrome, Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by tcompiegne** [comment]
Hello @AYCsen ,

That should by fix in version 1.8.3, thanks to : https://github.com/gravitee-io/issues/issues/705

**Comment by AYCsen** [comment]
Hello @tcompiegne ,

Sorry for the duplicate of #705 and thanks for the quick reply.
