### ISSUE TITLE
[gateway-api] bad behavior on TransformationException if no policyChain

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#7130]
## :collision: Describe the bug
We have weird behaviour resulting in timeout when a `TransformationException` occurs in a `TransformableRequestStream` or `TransformableResponseStream` and no `policyChain` is set.

With the fix, the API will end will a readable error instead of timeout.

## :sunrise_over_mountains: To Reproduce

You can check with this API: https://apim-3-10-x-console.cloud.gravitee.io/#!/environments/DEFAULT/apis/69635ef0-422e-4259-a35e-f0422ef25959/design

Flows are already configured to have the error

### JsonToJson Policy
Steps to reproduce the behaviour:
1. Go to Design studio
2. Add JsonToJson with a bad JOLT specification
3. Try your api postman
4. It ends in a timeout error (postman)

### JsonToXml Policy
Steps to reproduce the behaviour:
1. Go to Design studio
2. Add JsonToXml twice in a row to reproduce the error
3. Try your api postman
4. It ends in a timeout error (postman)

### JWS Policy
Not reproduced

### XmlToJson Policy
Steps to reproduce the behaviour:
1. Go to Design studio
2. Add XmlToJson with a bad input generated by Assign content policy
3. Try your api postman
4. It ends in a timeout error (postman)

### XSLT Policy
Steps to reproduce the behaviour:
1. Go to Design studio
2. Add Xslt policy with a bad timesheet
3. Try your api postman
4. It ends in a timeout error (postman)

## :rainbow: Expected behaviour
The chain should fail properly. (no timeout)

## :movie_camera: Useful information

- [x] `JsonToJson` Policy and `XsltPolicy` are good examples but we need **to investigate if other policies are in this case**.
- [x] We should fix this policies to build the `TransformableStream` with a `PolicyChain`
- [x] Discuss with @gravitee-io/archi if there is an error in the way we behave in case of `TransformationException` in `gravitee-gateway-api`

**Comment by LiliaEn** [comment]
Tested on the 3.10.X env
Browser: Chrome Version 98.0.4758.80 , macOS Big Sur v11.6
Works as expected.
