### ISSUE TITLE
[console] Secondary endpoint feature not working/switching if the Health-check is down on the primary endpoint.

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#7135]
## :collision: Describe the bug
The HealthCheck is not switching to secondary Endpoint when the Primary Endpoint is Down. This was testes in 3.10.10 and 3.9.1 it is working like it should.

## :sunrise_over_mountains: To Reproduce
1. Import the API shared in this ticket.
2. Make a call to the the initial endpoint from Postman and you will see that even though HC is down on the primary dummy endpoint the calls are not going to the secondary endpoint.

Unlike in 3.10.10 when we make a call to the primary endpoint and the HC on the primary endpoint is down the call is going to the secondary endpoint.

![image](https://user-images.githubusercontent.com/57534152/154438604-04c4a019-5fc8-4aef-99a0-a9d8636ba1b6.png)

![image](https://user-images.githubusercontent.com/57534152/154438645-628baeb6-e643-4047-af6a-dd056d3399bc.png)

![image](https://user-images.githubusercontent.com/57534152/154438686-a9062848-2a47-4b58-bae4-52311d3de555.png)

Note: Not sure if this is another bug or normal behavior but HC is enabled in both endpoints and the HC only makes calls on the primary endpoint and there are no calls from the second endpoint.

![image](https://user-images.githubusercontent.com/57534152/154438923-fdca145d-ce1b-4e7f-bf17-0946e1a8dc71.png)

## :rainbow: Expected behavior
Health-check should work exactly like it was working previously, meaning when the primary endpoint is down the HC should go to the secondary.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material:

[Test-Health-Check-1-0 (1).zip](https://github.com/gravitee-io/issues/files/8087026/Test-Health-Check-1-0.1.zip)

## :computer: Desktop :

***Please complete the following information:***
 - OS: Windows 10
 - Browser: Google Chrome

## :warning: Potential impacts:

***What are the impacted versions?***
- 3.15.2, 3.15.3

**Comment by mouligno** [comment]
LGTM

**Comment by LiliaEn** [comment]
Tested on 3.15.x env
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Works as expected
