### ISSUE TITLE
[logs] API request logs on elasticsearch

### ISSUE THREAD

**Issue by AYCsen** [gravitee-io/issues#714]
Currently elasticsearch gravitee index with "request" type contains all the necessary informations to trace an api call and got an "api" field that use generated ID stored in the "management" database (default MongoDB).
**For example**: _2a7b84ae-f5a1-473c-bb84-aef5a1873cf1_
![mongo_gravitee_api_mapi_update](https://user-images.githubusercontent.com/30430994/28614444-2c6e0a82-71f6-11e7-8e96-e9fa0d79483e.png)

As we regroup all of our dashboard on kibana, we got a gravitee dashboard. But kibana can't use the mongo database to get api informations, and to make our dashboard more human-readable i want to have the API name in the elasticsearch gravitee request logs, maybe using a flag on management-api configuration.
![kibana_gravitee](https://user-images.githubusercontent.com/30430994/28614047-b0964bb4-71f4-11e7-8c06-6fd3134f30e4.PNG)
Even if the api name change and the older api logs keep the wrong name, the current dashboard looks  unreadable.

### Current Behavior
Elasticsearch "gravitee" index with type "request" :
```
{
    ...
    "api" : "2a7b84ae-f5a1-473c-bb84-aef5a1873cf1",
    ...
}
```

### Expected Behavior
Elasticsearch "gravitee" index with type "request" :
```
{
    ...
    "api" : "2a7b84ae-f5a1-473c-bb84-aef5a1873cf1",
    "api-name" : "MYAPI - Frontend"
    ...
}
```

### Environment
* Version used: 1.8

**Comment by brasseld** [comment]
Ok, so IMHO, you're not only waiting for API name but probably also:
* Application name
* Plan name

Two solutions:
* Wait for someone who wants to contribute to this issue by providing a patch
* Use a ingest pipeline for Elasticsearch 5.x and provide your own processor to retrieve this kind of information before indexing data.

**Comment by brasseld** [comment]
I'm closing this issue.
It should be done by an ES ingest pipeline processor.
