### ISSUE TITLE
[helm] Add support for ingressClassName to apim3 charts

### ISSUE THREAD

**Issue by vliska** [gravitee-io/issues#7140]
## :collision: Describe the bug
Annotation kubernetes.io/ingress.class is deprecated since 1.18 (see https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation).

Add option to fill ingressClassName in the apim3 helm charts.

Note: 
Annotation can't be used together with the ingressClassName (!!!) when installing helm chart (but can be used when upgrading) - it fails on k8s api validation when installing the ingress object, so we need a solution/switch (either use annotation or use ingressClassName, but not both at the same time).

## :rainbow: Expected behaviour
Helm charts supports setting ingressClassName value on ingress objects and NOT including kubernetes.io/ingress.class annotation.

## :movie_camera: Useful information
https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation
Even though it's stated in documentation that both ingressClassName and kuberenets.io/ingress.class is supported at the same time, it's not the case and new installation (not upgrade) fails with

```
Error: Ingress.extensions "<ingress name>" is invalid: annotations.kubernetes.io/ingress.class: Invalid value: "<ingressClassName>": can not be set when the class field is also set
```

so we really need a solution when we can exclude the annotation if ingressClassName is set.
See also this comment:
https://github.com/strimzi/strimzi-kafka-operator/issues/4679#issuecomment-814888797

**Comment by HerrmannHinz** [comment]
any progress? need to patch each ingress generated by the helm chart manually afterwards atm.
