### ISSUE TITLE
Login redirection is sometimes not working

### ISSUE THREAD

**Issue by gaetanmaisse** [gravitee-io/issues#7141]
## :collision: Describe the bug

Login redirection is sometimes not working

## :sunrise_over_mountains: To Reproduce

1. Go to APIM console
2. Try to login
3. There are some requests sent to the backend but you're blocked on the login page

## :rainbow: Expected behaviour

After the login is completed we should be redirected to the home page i.e. dashboard

## :movie_camera: Useful information

NA

## :computer: Desktop :

 - OS: MacOS
 - Browser: All are impacted

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

NA

**Comment by LiliaEn** [comment]
Tested on the default env v3.16.0 and 3.16.x env.
Browser: Chrome Version 98.0.4758.80 , macOS Big Sur v11.6
Works as expected.
