### ISSUE TITLE
[Debug Mode] Dynamic table for request headers

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7149]
## :rainbow: Feature

As an API Publisher, I want to add headers to my debug request

## :sunrise_over_mountains: Additional information

Talk to greg and audrey for deletion
autocompletion on standards headers?

## :link: Dependencies

Link a story or other related things...

## :camera: Mockups 

https://www.figma.com/file/MxLXjCNRnhyMnpapRDgKOT/Debugmode_v4

## :books: Documentation required

Provide link to the issue for documentation update

## :superhero: Acceptance criteria

- [ ] Given '...'
- [ ] Then '...'
- [ ] When '...'

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :heavy_check_mark: Definition of Done

***For each User Story everything on the list must be considered, select only what was required***
- [ ] Acceptance criteria met and tested
- [ ] Sonar Cloud quality gate passes
- [ ] CircleCi checks pass
- [ ] Cypress or Postman API check passes
- [ ] Test containers passed if modifications on the repository modules
- [ ] Translation for portal UI checked
- [ ] Developer created draft documentation PR
- [ ] New migration scripts checked
Can be run multiple times but only makes changes the first time
Display to user what script has done
- [ ] Validated on appropriate environment
- [ ] Existing test cases refactored

:rocket:

**Comment by LiliaEn** [comment]
Tested on the default env v3.17.0 
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Tested the following scenarios:
- Add headers to the request and run
- Delete headers
- Search for headers
- Select existing headers
