### ISSUE TITLE
Admin without rights

### ISSUE THREAD

**Issue by geraudmasson** [gravitee-io/issues#715]
Hi,

I'm a powerless admin, I can't even change the endpoint of an api where I'm not the primary owner.
I would like to be able to change anything anywhere anytime ! To be God on the api manager with admin rights.
![problemapi](https://user-images.githubusercontent.com/26602276/28725667-78120dc0-73be-11e7-8f92-7a8f263bca86.png)
![admin power](https://user-images.githubusercontent.com/26602276/28725668-78128778-73be-11e7-813a-20984dc28dc0.png)

And be able to change the primary owner

**Comment by NicolasGeraud** [comment]
hi, are you also member of the api (directly or via a group) ?

**Comment by geraudmasson** [comment]
Not at all. I don't have create the api, but I am an admin on management and portal

**Comment by NicolasGeraud** [comment]
Hi @geraudmasson , are you logged as the admin user or as "geraudmasson" user with admin rights ?

**Comment by NicolasGeraud** [comment]
hi @geraudmasson is it still a bug ?
