### ISSUE TITLE
[console] Cannot add policy to flow

### ISSUE THREAD

**Issue by gcusnieux** [gravitee-io/issues#7159]
## :collision: Describe the bug
We introduced a regression with rework for debug mode.
We cannot add a policy to a flow.
It's reproductible with Policy Studio / Empty story, just try to drag and drop a policy.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:

## :movie_camera: Useful information

https://user-images.githubusercontent.com/1457497/154924369-92bc0add-49cf-4429-8bec-b9dfec7bd908.mov

## :computer: Desktop :

***Please complete the following information:***

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by mouligno** [comment]
LGTM
