### ISSUE TITLE
[APIM import] 3.16 - 3.15 backward compatibility issue

### ISSUE THREAD

**Issue by a-cordier** [gravitee-io/issues#7168]
## :collision: Describe the bug

importing a 3.15 definition on 3.16 and then importing the 3.16 export on 3.15 raise duplications errors

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
 1. export a definition from 3.15 
 2. import the definition on 3.16
 3. export a new definition of the same API from 3.16
 4. import the 3.16 exported definition on 3.15
 5. 💥 

There's a duplicate system folder error and pages get duplicated

## :rainbow: Expected behaviour

As that's a use case that can come up quite often, we should handle this gracefully

**Comment by a-cordier** [comment]
The issue is reproduced with the exact same scenario by switching from 3.16 to 3.14

No regression here, then.

**Comment by mouligno** [comment]
you mean 3.15 to 3.14 ?
