### ISSUE TITLE
[helm-chart] manage cookie settings

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#7171]
## :rainbow: Feature

Currently, the[ cookie settings ](https://github.com/gravitee-io/gravitee-access-management/blob/master/gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml#L67)can't be define into the AM HelmChart for the Gateway.

The only way to define them is by using the env vars.

We should be able to do it using the values.yaml like the other settings

**Comment by famaridon** [comment]
+1

**Comment by Spitfire1900** [comment]
Does this include the ability to manage the http.cookie.session.secure setting?

**Comment by farmborough** [comment]
@Spitfire1900 it's manageable in the helm chart for `http.cookie.secure` but not `http.cookie.session.secure`.
