### ISSUE TITLE
[resource-cache-redis] User cannot save configuration

### ISSUE THREAD

**Issue by gcusnieux** [gravitee-io/issues#7172]
## :collision: Describe the bug

The user cannot add a redis resource, the from is never valid.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to env with Redis Cache Resource installed
2. Edit an API (Design / Resources tab)
3. Try to add a Redis resource

## :rainbow: Expected behaviour

User should add a redis cache resource

![Capture d’écran 2022-03-02 à 10 10 40](https://user-images.githubusercontent.com/1457497/156331179-bbf70ad2-cb8b-4c34-b81a-520ca626f945.png)

**Comment by LiliaEn** [comment]
Tested on the default env v3.17.0 
Browser: Chrome Version 98.0.4758.80 , macOS Big Sur v11.6
Works as expected.
