### ISSUE TITLE
[APIM] Platform policies must be executed whatever the API policy chain fails or not

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#7178]
## :collision: Describe the bug
When defining policies at platform level on the response phase, if the policy chain failed during the API policy chain execution, then the response platform policies are skipped.

## :sunrise_over_mountains: To Reproduce
1. Define platform policies on the response phase
2. Create an api with a policy that fail during the request phase
3. The platform policy is not executed

## :rainbow: Expected behavior
The platform policies should be executed whatever occurred during the API policy flow.

## :movie_camera: Useful information
N/A

## :computer: Desktop :

***Please complete the following information:***
N/A

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

If you add a Metric Reporter policy at platform level you are not sure that it will be executed if you have failure on api flows.

***What are the impacted versions?***

## :link: Dependencies

N/A

**Comment by mouligno** [comment]
On hold since some work on the gateway should resolve this
