### ISSUE TITLE
[policy-javascript 1.1.0] Error NullPointerException when executing code in Javascript policy On-request content script

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#7179]
## :collision: Describe the bug
NullPointerException is raised when executing Javascript policy, with the following code, in On-request content script field.
` var test = 'test'; `
The error is:
`[vert.x-eventloop-thread-0] [] ERROR i.g.p.javascript.JavascriptPolicy - Unable to run Javascript script java.lang.NullPointerException: null
at io.gravitee.gateway.buffer.netty.BufferImpl.<init>(BufferImpl.java:51)
at io.gravitee.gateway.buffer.netty.BufferImpl.<init>(BufferImpl.java:55)
at io.gravitee.gateway.buffer.netty.BufferFactoryImpl.buffer(BufferFactoryImpl.java:39)
at io.gravitee.gateway.api.buffer.Buffer.buffer(Buffer.java:39)
at io.gravitee.policy.javascript.JavascriptPolicy.lambda$onRequestContent$1(JavascriptPolicy.java:153)`

## :sunrise_over_mountains: To Reproduce
Step1. Create simple API with Javascript policy
Step2. Add the following code in On-request content script field:
` var test = 'test'; `
Step3. Make a request to the API with postman.

***Please complete the following information:***
 - Docker installation 3.15.3
 - policy-javascript 1.1.0
 
## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by jhaeyaert** [comment]
FYI: when dealing with script on a `XXXContent` phase, the **last instruction of the script must be the new body content.**
So in your case, the script does not have any body content returned which explains the NPE. 

A valid script for for you case could be:

```javascript
var test = 'test';

test; // <--- The last instruction is the new body content.
```

Where `'test'` string will replace the request or response body depending on where you use the policy.

@mouligno I let you re qualify this issue because this specificity is not well documented.

**Comment by gaetanmaisse** [comment]
I think we have to add it here https://github.com/gravitee-io/gravitee-policy-javascript#onrequestcontent--onresponsecontent too

**Comment by mouligno** [comment]
Anything missing for release ? Doc is merged : https://github.com/gravitee-io/gravitee-docs/pull/761

**Comment by LiliaEn** [comment]
Tested on 3.15.x env
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Working as expected.
