### ISSUE TITLE
[Debug mode] Display where a policy is configured

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7183]
As an API Publisher, I want to know where the policy is set

### Additional information

Policies are properly displayed in the debug mode but we don't know where they are configured.

### Policies level :
- platform
- plan
- flow
- security

### Requirements

- mockup to display platform vs API label ? tag ?
![image](https://user-images.githubusercontent.com/47851994/157629326-aa087de5-40b1-41ff-acc5-287f6e33cb6d.png)

### What to do ?

1. Externalize PolicyResolver.Policy inner class to have a dedicated class called `PolicyMetadata`. Existing `PolicyMetadata` class is renamed to `PolicyManifest` because its purpose is to build the policy.
2. Instead of passing parameters to build a `Policy` thanks to `PolicyManager.create()`, we now pass the `PolicyMetadata` object which holds the policy condition too.
3. Add the new `stage` info into `PolicyMetadata`. This stage is defined at the `FlowResolver` level. 
4. `*FlowChainprovider` needed a `SimpleFlowProvider` to be created. It makes it hard to read the class without providing that much value. We now delegate the creation of this `SimpleFlowProvider` into the constructor of `*FlowChainprovider` 
5. Improve performance avoiding creating a `FlowPolicyResolver` for each `Flow`. Same thing is done to avoid instantiating `PolicyMetadata` for each step of a flow.
6. Manage stage for Security level policies. Also, manage the case of internal policies (`CheckSubscription` policy is executed for Oauth2 or JWT plans for example.)
7. Improve display of card in Debug Mode when they have no icon to display. 
8. Display policy stage in cards

**Comment by LiliaEn** [comment]
Tested on the default env v3.17.0 
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Correctly displays where the policy is configured 
- Platform
- Plan
- API
- Security
    - Header
    - Body
