### ISSUE TITLE
Spike : How to handle renovate ?

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#7185]
We have to ensure our vulnerable dependencies are updated.
How to handle properly all renovate PRs ?

Suggestions :
- dedicate a dev to handle renovate PRs, and rotate
- upgrade all dependencies once on all projects with mvn versions plugin (like it has been done on APIM monorepo)
- reduce the periodicity of renovate checks

Questions :
- how to test that properly and ensure non regression ?
- when merging PR ? freeze merging before releases ? etc..

**Comment by sursak123** [comment]
@gaetanmaisse , can you let us know what needs to be done for this ticket pls?

**Comment by sursak123** [comment]
Can we have our discussion around renovate PR process by following the noise reduction best practices ? - Package grouping by setting up matchpackagepatterns - https://docs.renovatebot.com/noise-reduction/
