### ISSUE TITLE
[groovy][doc] response.content doesn't exist in OnResponseContent scope

### ISSUE THREAD

**Issue by Matsa59** [gravitee-io/issues#719]
The groovy's documentation is not up to date or gravitee gateway doesn't have the right behaviour.

### Expected Behavior

Unmarshal a json and marshal to json

### Current Behavior

Following the documentation : https://docs.gravitee.io/apim_policies_groovy.html (the groovy for onResponseContent) I got cause an infinite loop.

```
import groovy.json.JsonSlurper
import groovy.json.JsonOutput

def jsonSlurper = new JsonSlurper()
def content = jsonSlurper.parseText(response.content)

// your groovy script

return JsonOutput.toJson(content)
```

### Possible Solution

API Publishers can fix the problem by using `response` instead of `response.content`

```
import groovy.json.JsonSlurper
import groovy.json.JsonOutput

def jsonSlurper = new JsonSlurper()
def content = jsonSlurper.parseText(response)

// your groovy script

return JsonOutput.toJson(content)
```

### Context

Trying to edit the response content.

### Your Environment

* Version used: 1.8.3
* Operating System and version: Debian

**Comment by brasseld** [comment]
Hi @Matsa59,

I had a quick look to your issue and I'm not able to reproduce it.

Please have a look to my configuration:
<img width="1133" alt="capture d ecran 2017-08-21 a 10 19 02" src="https://user-images.githubusercontent.com/133094/29509923-351b2f8e-865a-11e7-9ebb-f3fecfec0570.png">
