### ISSUE TITLE
[Management] Update audit event on Shared API Key

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7192]
## :rainbow: Feature

As an administrator, I want to view APIs impacted by a change on an API Key in audit .

## :sunrise_over_mountains: Additional information

- ~~APIKEY_CREATED - add list of APIs concerned~~
- APIKEY_RENEWED- add list of APIs concerned
- APIKEY_EXPIRED - add list of APIs concerned

If event contains API info, we display API list 

## :link: Dependencies

Link a story or other related things...

## :camera: Mockups 

Insert screenshots, drawings...

## :books: Documentation required

Provide link to the issue for documentation update

## :superhero: Acceptance criteria

- [ ] Given '...'
- [ ] Then '...'
- [ ] When '...'

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :heavy_check_mark: Definition of Done

***For each User Story everything on the list must be considered, select only what was required***
- [ ] Acceptance criteria met and tested
- [ ] Sonar Cloud quality gate passes
- [ ] CircleCi checks pass
- [ ] Cypress or Postman API check passes
- [ ] Test containers passed if modifications on the repository modules
- [ ] Translation for portal UI checked
- [ ] Developer created draft documentation PR
- [ ] New migration scripts checked
Can be run multiple times but only makes changes the first time
Display to user what script has done
- [ ] Validated on appropriate environment
- [ ] Existing test cases refactored

:rocket:

**Comment by omatthewsgravitee** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Graviteeio---API-Management-601c1f73be51260015c7bb26/issues/gravitee-io/issues/7192?planning-poker) with ZenHub @a-cordier @marcambier @mouligno @RubenMMSantos

**Comment by RubenMMSantos** [comment]
ticket verified and confirmed as working as expected
verified on https://apim-master-console.cloud.gravitee.io, APIM 3.17
![Screenshot 2022-03-16 at 12 46 58](https://user-images.githubusercontent.com/14939456/158608594-e000921d-7459-4985-925e-4cb8f0c1c10a.png)
