### ISSUE TITLE
[metrics-reporter-policy] metrics reporting not done at the good time

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#7194]
## :collision: Describe the bug

When using metrics reporter policy, it happens sometime that the reporting is done before the assignation of metrics.
It is often the case when a mock policy is added like this:

![image](https://user-images.githubusercontent.com/47851994/155686032-b61fca66-b9ee-4b7d-a764-fa0f1b6d22db.png)

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Use the API attached
2. check in webhook.site that `status`, `proxyLatencyMs` and `proxyResponseTimeMs` are set to 0

**A test should also be done by removing the MetricsReporter from API level and put it at Platform level**

## :rainbow: Expected behaviour
We should have the good value for these three fields.

## :movie_camera: Useful information

[post-post (1).json.zip](https://github.com/gravitee-io/issues/files/8139908/post-post.1.json.zip)

**Comment by LiliaEn** [comment]
Tested on the env v3.15.X
Browser: Chrome Version 98.0.4758.80 , macOS Big Sur v11.6
Tested Using Platform Policy and API policy
Works as expected in both cases
![Screenshot 2022-03-02 at 13 44 50](https://user-images.githubusercontent.com/49516050/156373344-16124299-e8f3-4810-8c71-639bbc209e12.png)
