### ISSUE TITLE
[APIM][policy-basic-authentication] Error message is received when using basic authentication policy

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#7198]
## :collision: Describe the bug
When using basic authentication policy error is given with status 500.
```
"message": "java.lang.IllegalArgumentException: Required type parameter does not match the resource type",
    "http_status_code": 500
```

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Install APIM with plugin gravitee-resource-auth-provider-inline-1.1.0 and gravitee-policy-basic-authentication-1.3.0
2. Create API and go to Design studio.
3. Create new resource for Inline authentication.
4. Go back to Design tab and add Basic Authentication policy on the flow.
5. Add new entity provider and select the resource created previously.
6. Run a query with Postman using the user/password combination that was set in the resource.

***Please complete the following information:***
 - OS: Docker installation APIM 3.15.3
 - gravitee-resource-auth-provider-inline-1.1.0
 - gravitee-policy-basic-authentication-1.3.0

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by phiz71** [comment]
This error message is actually send by the `gravitee-resource-auth-provider` plugin.

**Comment by phiz71** [comment]
Tests can't be achieved on dev environments.
Tested locally with @a-cordier => ok
