### ISSUE TITLE
Portal-> Filtering by a certain Category on All APIs page will return all existing APIs

### ISSUE THREAD

**Issue by LiliaEn** [gravitee-io/issues#7201]
Filtering by Category on All APIs page doesn't work

### Expected Behavior
When selecting a certain category only the APIs from that category should be displayed

### Current Behavior
Filtering by a certain Category on All APIs page will return all existing APIs Please see the video: https://drive.google.com/file/d/126tTP5ywAZQo9Ab1BgA8_1W0JXdk6kL3/view?usp=sharing

### Steps to Reproduce (for bugs)
1. Login to APIM Portal
2. Make sure you have at least 1 category and an API added to that category
3. Go to Catalog->All APIs
4. Filter by category and check the results

### Your Environment
* Version used: env - v3.16.0, 3.15.0
* Browser Name and version: Chrome Version 98.0.4758.80 
* Operating System and version: macOS Big Sur v11.6

**Comment by mouligno** [comment]
LGTM
