### ISSUE TITLE
[Spike investigation] Check Support of RHEL8

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7208]
## :rainbow: Feature

As an administrator, I want to run APIM using RHEL8 in order to respect supported version of RHEL

## :sunrise_over_mountains: Additional information

- RHEL7 won't be supported after 31 of march - https://access.redhat.com/support/policy/updates/errata
- Spike objective is to install APIM RPM on RHEL8 and validate compatibility. 
- https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/upgrading_from_rhel_7_to_rhel_8/index
- 

## :link: Dependencies

Link a story or other related things...

## :camera: Mockups 

Insert screenshots, drawings...

## :books: Documentation required

Provide link to the issue for documentation update

## :superhero: Acceptance criteria

- [ ] Given APIM Then I want to work properly When I use RHEL 8

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :heavy_check_mark: Definition of Done

***For each User Story everything on the list must be considered, select only what was required***
- [ ] Acceptance criteria met and tested
- [ ] Sonar Cloud quality gate passes
- [ ] CircleCi checks pass
- [ ] Cypress or Postman API check passes
- [ ] Test containers passed if modifications on the repository modules
- [ ] Translation for portal UI checked
- [ ] Developer created draft documentation PR
- [ ] New migration scripts checked
Can be run multiple times but only makes changes the first time
Display to user what script has done
- [ ] Validated on appropriate environment
- [ ] Existing test cases refactored

:rocket:

**Comment by brasseld** [comment]
After dealing with other script issues for AM, I ran installation scripts for the following distributions:
- Amazon 2
- Amazon 2018
- RHEL 7
- CentOS 7
- RHEL 8
- CentOS 8
- Suse 12

Everything was ok with Gravitee's RPMs for both APIM and AM.
