### ISSUE TITLE
[management] Bad template

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#721]
Default Templates use the toString() method for different objects such as api, owner, ...

The result is an ugly email.

### Your Environment

* Version used: 1.8.3

**Comment by shoaibjdev** [comment]
True, have just encountered this bug while evaluating GraviteeIO for forthcoming project.

Your subscription to the API ApiEntity{id='c1351ee2-d26e-4d22-b51e-e2d26e5d229e', name='FS CustomerService', version='0.0.1', description='CBS Service for Customer Module', proxy=io.gravitee.definition.model.Proxy@5ba76b9d, paths={/loans/query/cif=io.gravitee.definition.model.Path@4c154069, /deposits/query/cif=io.gravitee.definition.model.Path@45be1f2f, /=io.gravitee.definition.model.Path@54ca68d0}, createdAt=Mon Aug 14 17:37:58 EAT 2017, updatedAt=Mon Aug 14 17:42:37 EAT 2017, visibility=PUBLIC, state=STARTED, primaryOwner=io.gravitee.management.model.PrimaryOwnerEntity@34d11a57, role=null, tags=[], view=null, group=null, metadata={}} with plan io.gravitee.management.model.PlanEntity@b5540426 has been approved.

**Comment by NicolasGeraud** [comment]
this is easy to fix on your template if you can't wait to the next release.

**Comment by shoaibjdev** [comment]
@NicolasGeraud  - Have looked into templates but not sure for example subscriptionApproved.html but not sure how to change it. I presume the change is required in Management API project java classes. If it's doable by changing template, please guide.

**Comment by NicolasGeraud** [comment]
@shoaibjdev as you can see in the pull request, the fix needs a new version of the management-api. Sorry.

We will schedule a maintenance release next week.
