### ISSUE TITLE
[console] Can't access a newly created API with import

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#7216]
## :collision: Describe the bug
Given an imported API **and** no default group is attached to it
When I try to access the detail page of this API
Nothing happens

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:

1. Make sure there is no default group to be associated to each new API
2. Import an API from link or from file
3. Go back to APIs list
4. Try to access the newly created API

## :movie_camera: Useful information

There is a 500 Error on this call `/management/organizations/DEFAULT/environments/DEFAULT/apis/{apiId}/groups`
And a NullPointerException in API Management logs

## :warning: Potential impacts

Introduced in 3.10.11

## :link: Dependencies
Bug introduced with #6360

**Comment by RubenMMSantos** [comment]
issue verified on https://apim-3-10-x-console.cloud.gravitee.io/ environment and confirmed has fixed. Scenarios below were checked as extra testing

- [ ] created new api > exported > deleted API from APIM > imported API > able to access API details
- [ ] Repeated the same steps but also added a plan to the API when creating it > able to access API details
- [ ] made changes to the API > exported API > Deleted API from APIM > Imported API > able to access API details
- [ ] made changes to API > exported API > reverted changes > imported API with changes > able to access API details
