### ISSUE TITLE
gateway outage when frequent dynamic properties

### ISSUE THREAD

**Issue by ApizrTech** [gravitee-io/issues#7217]
## :collision: Describe the bug
Hi Gravitee team,
In APIM, when a dynamic property is activated with frequent activity, the gateway stops servicing requests after a few days (api calls returned "no context path"), with following error message in logs :
Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Define an API
2. In API resources create a dynamic property, with frequent activity
3. After a while, the error happens. For us the problem happened after 4 days

## :movie_camera: Useful information
I investigated and saw much activity in audit tab.
In mongodb repository I saw many documents (30k) in two collections (audits and events (iirc)).
I activated the slow query log and found queries about audits. I added missing indices, slow queries gone but it did not solve the gateway problem.
Finally, because it was on a test env I dared to empty the audits collection and the service was back (I had to resync  each api in the UI).

## Suggestions
The dynamic property refresh causes an api republish, so an event, is it necessary ?
A purge of old events ?

## :warning: Potential impacts
Gateway not servicing requests

***What are the impacted versions?***
3.12.1 (build: 2591) revision#3ea1977f1

Thanks,
Anselme

**Comment by a-cordier** [comment]
@mouligno in some sort. This means that now that the behaviour is fixed on 3.15.x we have to find our way around this audit spamming issue. A complete stack trace might be helpful here.

**Comment by mouligno** [comment]
@ApizrTech are you able to help on this ?
