### ISSUE TITLE
[debug mode] request does not return the good path

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#7220]
## :collision: Describe the bug
Currently, `request.path` returns the contextPath instead of the real request path.

## :sunrise_over_mountains: To Reproduce

[Test-1 (1).json.zip](https://github.com/gravitee-io/issues/files/8168494/Test-1.1.json.zip)

Steps to reproduce the behaviour:

1. Imported the provided api just above
2. run a debug call on `/echo`
3. Check that `path` == `contextPath`

## :rainbow: Expected behaviour
`path` should be the exact path used by the request: `api's context path + debug request path`
From the previous example, it should be `/my/long/context/path/echo`

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :link: Dependencies

Introduces by: https://github.com/gravitee-io/issues/issues/7128

**Comment by ytvnr** [comment]
introduced by https://github.com/gravitee-io/issues/issues/7128

**Comment by LiliaEn** [comment]
ReTested on the default env v3.17.0 
Browser: Chrome Version 98.0.4758.80 , macOS Big Sur v11.6
Works as expected
![Screenshot 2022-03-02 at 13 23 44](https://user-images.githubusercontent.com/49516050/156370091-0c716bbc-3099-4c54-91db-25eeb0c209e4.png)
