### ISSUE TITLE
[expression-language] Improve map access with dot

### ISSUE THREAD

**Issue by gcusnieux** [gravitee-io/issues#7228]
## :rainbow: Feature

**As a** 'API Publisher'

**I want to** 'use simple syntax to access map data with expression language expression'

**So that** '...'

## :sunrise_over_mountains: Additional information

It would be simpler to access to map value with dot syntax like `{#context.attributes.api}`
Default syntax `{#context.attributes['api']}` should be always work

:rocket:

**Comment by mouligno** [comment]
LGTM
