### ISSUE TITLE
[APIM][Portal UI] How to disable metrics on the APIM Portal?

### ISSUE THREAD

**Issue by DanilEvt** [gravitee-io/issues#7231]
## :collision: Describe the bug
After some time running my services, I end up having a 500 errors on the catalog page when the app tries to retrieve the API metrics.
```bash
{
  "errors" : [ {
    "status" : "500",
    "message" : "Cannot invoke \"java.lang.Double.doubleValue()\" because the return value of \"[java.util.Map](http://java.util.map/).get(Object)\" is null",
    "code" : "errors.unexpected"
  } ]
}
```
```bash
[gravitee-listener-552303] ERROR i.g.r.a.p.r.provider.ThrowableMapper - Internal error
java.lang.NullPointerException: null
    at io.gravitee.rest.api.portal.rest.resource.ApiMetricsResource.getHealthRatio(ApiMetricsResource.java:97)
    at io.gravitee.rest.api.portal.rest.resource.ApiMetricsResource.getApiMetricsByApiId(ApiMetricsResource.java:74)
```
## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. It's not clear

## :movie_camera: Useful information
<img width="555" alt="image" src="https://user-images.githubusercontent.com/100578907/156581177-1bbe5ee0-0b2c-4e81-97d8-e99bc73f4f27.png">

<img width="250" alt="image" src="https://user-images.githubusercontent.com/100578907/156581321-4cd8fc35-fc65-4212-80be-dd0648f80aa0.png">

## :computer: Desktop:

***Please complete the following information:***
 - Environment: APIM and Portal 3.15.3
 - OS: macOS
 - Browser safari

**Comment by apoddany** [comment]
Issue also replicated in previous 3.5 version.
This appears to be related when Health-Check is enabled.
We should at least catch the exception and set empty value when health metric can not be calculated/retrieved for an API and allow the API to be displayed anyway in Portal.

**Comment by DanilEvt** [comment]
> hi @DanilEvt
> 
> Thanks for reaching to us, we're working on a way to let user select which API information they'd like to display on the portal card. Would that fit your need ?

Yes, thank you, we will wait

**Comment by ThibaudAV** [comment]
📝 Internal zendesk link 
https://graviteesource.zendesk.com/agent/tickets/3691
https://graviteesource.zendesk.com/agent/tickets/4027

**Comment by LiliaEn** [comment]
Issue doesn't have clear steps of reproducing.
Tested on Portal when Healthcheck of an API is enabled and no errors are displayed.
Tested on 3.15.x
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
