### ISSUE TITLE
[APIM][Portal UI] In the metadata tab the field for name is not in English

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#7235]
## :collision: Describe the bug
In the metadata tab the field for name is not in English.

![image](https://user-images.githubusercontent.com/98313939/156737596-a63b29ec-46a1-481c-bb5e-306a48481059.png)

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to portal Applications tab > Metadata tab

## :rainbow: Expected behaviour
The field should be in English.

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.10.10
 - OS: Docker Installation
 - Browser Chrome

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by gaetanmaisse** [comment]
Closing as it has been fixed and released in APIM 3.15.19
