### ISSUE TITLE
[APIM][Portal UI] Tab for metadata does not animate properly on load

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#7236]
## :collision: Describe the bug
In the portal UI the tab for metadata does not load properly when you are on the General Information tab and click on Metadata tab. 

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to Applications tab in the Portal UI.
2. Choose application available.
3. You are now on General information tab, click on Metadata tab.

## :rainbow: Expected behaviour
When you click Metadata tab the bottom part of the page should animate sliding from right to left and the top part remains still.

## Current behaviour
When you click Metadata tab, bottom part of the page shows up without animation. The top part slides from left to right instead.
**This behavior happens only when you are in General information and click on Metadata tab.** Works well when you swap from other tabs in the menu.

## :movie_camera: Useful information

https://user-images.githubusercontent.com/98313939/156743030-a33b3450-da96-45fd-97e7-d9fdc5656e90.mp4

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.10.10
 - OS: Docker Installation
 - Browser Chrome

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by mouligno** [comment]
@kirestoj01 are you sure of the support 2 tag ?
