### ISSUE TITLE
[Management] Policy studio - Save reload the page

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7238]
## :collision: Describe the bug

When I save using the action bar, the page is reloaded.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:

## :rainbow: Expected behaviour

Previous version, page wasn't reloaded and you could stay on the flow you're currently working on

## Current behaviour

Every time you save, you're redirected to the default flow

## :movie_camera: Useful information

Is it link to Save bar ? Angular migration ? 

## :computer: Desktop:

***Please complete the following information:***
 - Environment: [e.g. 3.10.x]

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by mouligno** [comment]
LGTM

**Comment by LiliaEn** [comment]
Tested on the 3.16.x env
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Works as expected.
