### ISSUE TITLE
[APIM][Portal UI] Delete/remove member button does not work

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#7241]
## :collision: Describe the bug
Delete/remove member button does not work

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to portal UI > Choose application > Members tab
2. If no member present, create a new member
3. Click on the Delete/remove (trash bin) icon, nothing happens

## :rainbow: Expected behaviour
Clicking the button should remove the user from the list.
## Current behaviour
Clicking the button does nothing.

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.10.10
 - OS: Docker Installation
 - Browser Chrome

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by RubenMMSantos** [comment]
issue still reproducible on master-envir.
Also, on 3-10-X environment, there is no button on portal do add/remove users from applications
![Screenshot 2022-05-18 at 11.29.37.png](https://images.zenhubusercontent.com/612518f668e84e3f309d282d/16f65ca4-d2e5-426f-a065-8b662f3a334a)

**Comment by RubenMMSantos** [comment]
issue confirmed has fixed on 3-10-X environment.
![Screenshot 2022-05-18 at 12.07.08.png](https://images.zenhubusercontent.com/612518f668e84e3f309d282d/651f8e2d-bb7b-4636-b088-b6a55a6db520)
![Screenshot 2022-05-18 at 12.07.15.png](https://images.zenhubusercontent.com/612518f668e84e3f309d282d/a2455d01-6eff-4d60-9482-6db318a7f42e)
![Screenshot 2022-05-18 at 12.07.24.png](https://images.zenhubusercontent.com/612518f668e84e3f309d282d/ed730e45-ce65-4653-b918-ea3cf59007fd)
