### ISSUE TITLE
[Management] Handle 2 subscriptions to the same API with Shared Key Mode

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#7248]
- If application is already in shared mode, if consumer tries to subscribe to an Api key plan, within an API that has already another apiKey subscription using it's shared api key  : error "you can't subscribe to a 2nd Apikey plan on the same API in shared mode"

- if not yet choose the api key mode, if consumer subscribes a second apikey plan on the same API, don't show the popup for api key mode proposal

**Comment by RubenMMSantos** [comment]
ticket verified on envir https://apim-master-console.cloud.gravitee.io/, APIM version 3.17
behaviour as expected in ticket description
