### ISSUE TITLE
What's the use of Views menu under Configuration?

### ISSUE THREAD

**Issue by shoaibjdev** [gravitee-io/issues#725]
### Expected Behavior
It's not a bug or feature request but a general question as unable to locate documentation on the same.

### Current Behavior
What's the use of **Views** sub-menu found under **Configuration** menu.

### Steps to Reproduce (for bugs)

1. Login to GraviteeIO Management UI
2. Click on Configurations menu on left hand side
3. A sub menu **Views** will appear with option to add Views

### Your Environment

* Version used: 1.8.3
* Browser Name and version: Mozilla Firefox
* Operating System and version: CentOS 7.3

**Comment by brasseld** [comment]
Hi @shoaibjdev,

I've forgot your issue :(
So, in the context of Gravitee.io APIM, a view is a kind of "category" for APIs.

This way, it makes you able to create multiple views in the portal for all your APIs and sort them by functional domain, ...

Is it ok for you ?

**Comment by shoaibjdev** [comment]
Hi @brasseld - That's really great feature, I just tried it by creating views and linking my related API's to these portal views under API -> General -> Portal views (drop-down)
It really makes sense for API consumers to browse the API collection by category. 

Thank you very much for responding.
