### ISSUE TITLE
[management] allow to use System Proxy on Generic Oauth2 resource as already present for AM resource

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#7258]
## :collision: Describe the bug
Currently if the gateway needs to go through a proxy to reach the introspection endpoint of a Generic Oauth2 resource, it is not possible to setup Proxy definition or use System Proxy.
This is already possible with an AM resource (Enable Use System Proxy).

Adding System Proxy settings at the gateway or JVM level does not allow to overcome the issue leading to connection timeout.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to API -> Design -> Resources
2. Add a Generic Oauth2 resource -> System Proxy settings is not present
3. Add a AM Oauth2 resource -> System Proxy settings can be enabled/disabled

## Current behaviour
A clear and concise description of what is currently happening.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.15.3

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by mouligno** [comment]
To check - behavior with Zendesk

**Comment by phiz71** [comment]
This issue has finally been splitted in 2.

**First part**
This issue will be used to fix the current plugin only, with a duplication of code.

Related PRs are:
- [x] https://github.com/gravitee-io/gravitee-resource-oauth2-provider-generic/pull/33
- [ ] https://github.com/gravitee-io/release/pull/496
- [ ] https://github.com/gravitee-io/gravitee-api-management/pull/1889

**Second part**
This new issue (#7739) has been created to handle the mutualization of the code in `gravitee-common`
Related PRs are:
- [ ] https://github.com/gravitee-io/gravitee-resource-oauth2-provider-generic/pull/32
- [ ] https://github.com/gravitee-io/gravitee-connector-http/pull/27
- [ ] https://github.com/gravitee-io/gravitee-policy-jwt/pull/72
- [ ] https://github.com/gravitee-io/gravitee-policy-callout-http/pull/41
- [ ] https://github.com/gravitee-io/gravitee-policy-metrics-reporter/pull/17
- [ ] https://github.com/gravitee-io/gravitee-resource-oauth2-provider-am/pull/34
- [ ] https://github.com/gravitee-io/gravitee-api-management/pull/1784

**Comment by LiliaEn** [comment]
Tested on 3.10.x
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
System Proxy option is displayed and can be enabled/disabled and used in oAuth2 resource.
