### ISSUE TITLE
[Management] De-correlate API Key and Subscription lifecycle

### ISSUE THREAD

**Issue by a-cordier** [gravitee-io/issues#7266]
API publisher should be able to close a subscription even if the underlying application is using the shared API key mode

⚠️ It should not, however pause, resume nor close the API key(s) used by this subscription

ℹ️  this needs an update on the GW API key refresher to filter out closed, paused and expired subscriptions

**Comment by marcambier** [comment]
@RubenMMSantos , details about what to test :

For a non-shared API key, behavior no changed :
- From application subscription, closing the subscription closes all his api keys
- From api subscription, closing the subscription closes all his api keys
- From api subscription, pausing/resuming the subscription pauses/resumes all his api keys

For a shared API key, subscription lifecycle doesn't impact shared API key.
For example closing a subscription doesn't impact shared API key ;
The shared API key can't be used for a call using the closed subscription, but can still be used to call another subscription which has not been closed.
Same behavior for pausing/resuming.
