### ISSUE TITLE
[APIM] Encoding issue in the logging when body content is in different format

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#7267]
## :collision: Describe the bug
When making requests with different encoding, the API logs do not show the body of the request properly.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Created simple API with backend: https://jsonplaceholder.typicode.com/todos
2. Enable logging in the analytics.
3. Make a postman or curl call to the API.
4. See the log.

## Current behaviour
A clear and concise description of what is currently happening.

## :movie_camera: Useful information
![image](https://user-images.githubusercontent.com/98313939/157481743-f62ae3c0-3a2c-4c89-ad5c-54dd1bfae594.png)
![image](https://user-images.githubusercontent.com/98313939/157481784-b9dc1d16-3b7a-4bb3-bea1-f30dbcc9092c.png)
![image](https://user-images.githubusercontent.com/98313939/157481828-506e0c83-fc39-436e-96a4-571c63e599ff.png)

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.10.9, 3.16.0
 - OS: Docker Installation
 - Browser Chrome

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by ThibaudAV** [comment]
I tested to reproduce with this step : https://github.com/gravitee-io/issues/issues/7267 , but it seems to work perfectly on the 3.10.x and 3.16.x environment.
This have maybe corrected with an intermediate fix 🤷‍♂️ 
Kire Stojanovski or Arnaud Poddany Can you do the test again and confirm ?

**Comment by LiliaEn** [comment]
Tested on 3.10.x
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Logs are displayed as expected
![Screenshot 2022-05-19 at 10.46.56.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/7d28a999-ebfc-4bce-bcef-806c650baa02)
