### ISSUE TITLE
[APIM] Documentation in the console is empty.

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#7272]
## :collision: Describe the bug
The documentation in the Management API console is empty.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to Dashboard of console.
2. Click on question mark icon.
3. See empty field.

## Current behaviour
A clear and concise description of what is currently happening.

## :movie_camera: Useful information
![image](https://user-images.githubusercontent.com/98313939/157691904-401fc7b7-9837-43f6-8ee3-b32a4eaca8e6.png)

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.15.4
 - OS: Docker Installation
 - Browser Chrome

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by phiz71** [comment]
Duplicates https://github.com/gravitee-io/issues/issues/7323
