### ISSUE TITLE
[Management] Application subscriptions API keys buttons are not visible

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#7273]
Scenario to reproduce :
- In 3.15
- Create an application with subscription to API keys plans
- Logout / Clear cache / Login as admin
- Go to Application > Subscriptions > click on the API key subscription
- On the API keys list, buttons to revoke / renew API key are not displayed
- Go to API List > Click on a random API
- Go back to Application > Subscriptions > click on the API key subscription
- On the API keys list, buttons to revoke / renew API key are now visible

**Comment by RubenMMSantos** [comment]
issue confirmed as fixed.
Verified on https://apim-3-15-x-console.cloud.gravitee.io/
