### ISSUE TITLE
[migration] null pointer exception for old started gateways

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#7277]
## :collision: Describe the bug
With the introduction of try-it mode (now, debug mode) in 3.11, we add environment and organization hrids into the event properties.

When a Gateway starts, the event is correctly sent with those new properties.

Unfortunately, for the old already started gateway (not properly stopped, that appears as `UNKNOWN` in the UI), it is possible that the event does not contains the property, leading to an NPE

## How to fix

Check nullity in `InstanceServiceImpl.extractProperty`

## :rainbow: Expected behaviour
No NPE

## 🧪 How to test ?

Start a gateway in 3.10.x 
Stop the DB and the gateway (so STOP event is not saved) 
Migrate to 3.15.x, verify we have no NPE when consulting instances in Console

**Comment by LiliaEn** [comment]
Tested locally using 3.10.x and 3.15.x.
Works as expected.
