### ISSUE TITLE
Count function, when saving alert, not saved properly

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#7279]
## :collision: Describe the bug
Count function, when saving alert, not saved properly, dropdown field staying empty

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to Alerts
2. Click on Create\Update an existing alert
3. Scroll down to count function in the rules 
4. See error in the video attached 

https://user-images.githubusercontent.com/89140082/157854285-fce1df6f-1d51-4d53-8a82-1bbca8f2b989.mp4

Used version: 3.10.11

**Comment by LiliaEn** [comment]
Tested on the default env v3.18.0 
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Works as expected
