### ISSUE TITLE
[management] Duplicated shared Api Key after application creation

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#7281]
**Context :**
- API 1 with 1 apiKey plan with auto validation
- API 2 with 1 apiKey plan with auto validation

**Scenario :**
- Create a new application
- On the subscription step, subscribe to Api 1 api key plan
- On the subscription step, subscribe to Api 2 api key plan
- Finish the application creation
- On validation, choose the "Shared" api key mode
- Go check your subscriptions in Application>Subscription menu

**Current behavior :**
- Shared API key is duplicated :
![image](https://user-images.githubusercontent.com/87964124/157874440-e72a295a-5e4c-4568-a6f3-50e380a7fc36.png)

**Expected behavior :**
- Shared API key shouldn't be duplicated

**Comment by RubenMMSantos** [comment]
Issue verified on https://apim-master-console.cloud.gravitee.io/, APIM 3.17.
Issue no longer reproducible
![Screenshot 2022-03-14 at 13 37 17](https://user-images.githubusercontent.com/14939456/158183298-2d5ff17e-6289-496e-9bf9-13bec3936794.png)
