### ISSUE TITLE
[Management] Trying to subscribe to application that has a revoked/expired shared API Key generates a subscription without shared API key details

### ISSUE THREAD

**Issue by RubenMMSantos** [gravitee-io/issues#7282]
If an application has a revoked/expired shared api key, an empty subscription is created when subscribing to an application from api > subscriptions

Same behaviour happens if the application does not have any active/valid shared API key

### Expected Behavior
Subscription should be created using a valid shared api key

### Current Behavior
Empty Subscription is created without shared API key details

### Steps to Reproduce (for bugs)
1. create an application
2. create an API with api_key plan, subscribe to the application
3. with another API (with api key plan), subscribe to the application and select shared api key mode
4. go to application > subscriptions and revoke/renew the shared api key
5. on a 3rd API (with api key plan), subscribe to the application
6. notice the error displayed saying the api key is already expired
7. refresh the page
8. notice a new subscription was created
9. click on it and notice the subscription does not have shared API key details
10. going to the application > subscriptions and clicking on the subscription that was created will have the same issue
![Screenshot 2022-03-11 at 13.28.39.png](https://images.zenhubusercontent.com/612518f668e84e3f309d282d/f2cf9699-49c3-438c-aada-d24ec7b2df20)
![Screenshot 2022-03-11 at 13.28.55.png](https://images.zenhubusercontent.com/612518f668e84e3f309d282d/dbabb123-99dc-4111-9834-4fcebf9af55c)

### Your Environment
* Version used: APIM 3.17
* Browser Name and version: google chrome 99.0.4844.51 (Official Build) (x86_64)
* Operating System and version: MacOS Monterey 12.2.1 (21D62)

**Comment by RubenMMSantos** [comment]
issue is still reproducible on https://apim-master-console.cloud.gravitee.io/, APIM v3.17

I am now able to create a subscription using Shared API Key between an application that does not have any valid "Shared API Key" and an API.

**Comment by marcambier** [comment]
@RubenMMSantos ; as discussed with you and Antoine, this behavior sound relevant, so I put the ticket back in "To test".

**Comment by RubenMMSantos** [comment]
issue confirmed as fixed
issue verified on https://apim-master-console.cloud.gravitee.io, APIM 3.17
