### ISSUE TITLE
[gateway] EL template evaluation error when testing headers

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#7283]
## :collision: Describe the bug
Given an API with a mock policy with this condition: `{#request.headers['Accept'] == null || #request.headers['Accept'][0] == "text/xml"}`
When I call the API without sending Accept header
Then I have this error: `The template evaluation returns an error`

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Create a new API by importing [Florent-1-0.json.zip](https://github.com/gravitee-io/issues/files/8232945/Florent-1-0.json.zip)
2. Go on the `Debug Mode` screen and send the request...
3. ... or send a curl command: `curl -H 'Accept:' https://[gateway]/florent

## :rainbow: Expected behaviour
The condition should be evaluated

## Current behaviour
The template evaluation returns an error

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.15+

**Comment by RubenMMSantos** [comment]
issue verified and double checked with Dev.
Confirmed as fixed and working as expected.
