### ISSUE TITLE
[APIM Console] APIs not showing in a selected User when the Group they are in is Updated.

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#7285]
## :collision: Describe the bug
APIs not showing in a selected User when the Group they are in is Updated. It does not matter if what type is the user when it comes to the IDP, or if this user is a member of an API directly or vie Inheritance. When a group is created and UPDATED to for example User and User in Roles&Members and then we go to any of the users which are in the Group we will have a loading bar in the section of the APIs.

## :sunrise_over_mountains: To Reproduce
1. Create a Group and Update it to User Role for Application and API.
2. Add member/s.
3. Go to Organization Settings, Users and select a user which is a member of the Group above.
4. Got to API and see the error. Video of the issue is bellow.

## :rainbow: Expected behavior:
We should be able to see the default UI like for other sections when we go to the API list for any User like this:

![image](https://user-images.githubusercontent.com/57534152/157902942-1b66688a-8f05-4e3b-9f16-b5b6b2d1b134.png)

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material:

[bug.zip](https://github.com/gravitee-io/issues/files/8233445/bug.zip)

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.15.4 on Docker-Desktop
 - OS: Windows 11
 - Browser: Google Chrome

## :warning: Potential impacts

***What are the impacted versions?***
3.15.4

**Comment by LiliaEn** [comment]
Tested on 3.15.x
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Works as expected
![Screenshot 2022-05-17 at 14.21.35.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/fb330d1a-fd9d-42f7-85ff-a59c01976766)
