### ISSUE TITLE
[management-ui] improve UX for IdP priority order

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#7286]

**Comment by LalithaGu** [comment]
Env: Nightly
Result: PASS

Pre-test setup -
I have setup the Identity providers and Social/Enterprise providers

Scenario 1 -
Given I go into an Application --> IDP
And I select all the IDP and Save
Then the IDP Priority Order is saved successfully

Scenario 2-
Given I go into an Application --> IDP
And I deselect the first IDP and Save
Then the first IDP is moved to the bottom of the list
Checked every IDP that is deselected is moved to the end of the list

Scenario 3-
Given I go into an Application --> IDP
And I move the last selected IDP to the top priority 1 position
And I deselect it and Save
Then this IDP is moved to the bottom of the list
And Select this IDP and Save
Then this IDP is moved to the end of the selected IDPs

Scenario 4-
Given I go into an Application --> IDP
And I deselect all the IDPs and Save
Then there is no order and the IDP are just shown in UI but no order is saved for deselected IDPs

Scenario 5-
Given I go into an Application --> IDP
And I try to move the IDP from Identity Provider list to the Social/Enterprise provider list
Then IDP cannot be moved across the 2 lists. IDP within each list can be moved within each list only
