### ISSUE TITLE
[Management] Accepting subscription ignores custom API key

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#7298]
**Scenario :**
- Enable the custom API key environment setting
- Have an API with an API plan with auto-validation off
- Create an application (shared API key mode off)
- Subscribe to this plan
- In the task, go to the "new subscription task" and click accept
- Enter a custom api key and validate

**Current behavior :**
The input custom API key is ignored ; subscription is created with an auto-generated api key.

**Expected behavior :**
The input custom API key is not ignored ; subscription is created with this key.

**Comment by RubenMMSantos** [comment]
expected behaviour verified and confirmed.
envir -  https://apim-master-console.cloud.gravitee.io/, APIM 3.17
