### ISSUE TITLE
[management-api] NullPointerException from Analytics Tab

### ISSUE THREAD

**Issue by pisix** [gravitee-io/issues#730]
### Expected Behavior

Analytics screen

### Current Behavior

Infinite Loading

### Context

 Unable to see Stats from Analytics Tab, I get NullPointerException as shown in this screen shoot
<img width="949" alt="capture" src="https://user-images.githubusercontent.com/1443226/29405257-b659da8e-833d-11e7-9c2f-feddcb6061d5.PNG">
### Your Environment

* Version used: 1.8.3
* Browser Name and version: Google Chrome
* Operating System and version: Windows 10
* ES Version : 5.5.1
* Gravitee reporter ES: 5x-1.6.0

**Comment by brasseld** [comment]
Can you share version of the elasticsearch-repository plugin ?
You must use this one: https://download.gravitee.io/graviteeio-apim/plugins/repositories/gravitee-repository-elasticsearch/gravitee-repository-elasticsearch-5x-1.8.0.zip

Also, I think that you have an other issue while starting the management-api. Can you restart your management-api and share the logs with us ?

**Comment by pisix** [comment]
I used the version 5x-1.6.0, but after changing to version 5x-1.8.0 as you suggest, Analytics tabs works now.
