### ISSUE TITLE
[APIM] Events not being displayed correctly

### ISSUE THREAD

**Issue by RubenMMSantos** [gravitee-io/issues#7300]
Going to APIs > Audit > Events, is not displaying events related to the API, instead it is only displaying 1 event and several errors in browser console

### Expected Behavior
Events should displayed so user can see a timeline of events related to the API

### Current Behavior
Only 1 event is displayed

### Steps to Reproduce (for bugs)
1. Create an API
2. Deploy API
3. Do some more actions (like create a plan, stop the api, start the API, publish API)
4. go to Audit > Events
5. Notice only 1 event is displayed and there are errors in browser console
![Screenshot 2022-03-15 at 10.58.40.png](https://images.zenhubusercontent.com/612518f668e84e3f309d282d/76e45843-3fc4-4173-9563-10943e4e8e92)

### Extra info
Issue can be back tracked to APIM 3.10 and is present on APIM 3.15, 3.16 and master (3.17)

### Your Environment
* Version used: 3.10
* Browser Name and version: google chrome version 99.0.4844.51 (Official Build) (x86_64)
* Operating System and version: MacOS Monterey, v12.2.1 (21D62)

**Comment by LiliaEn** [comment]
Tested on the 3.10.X env
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Works as expected.
![Screenshot 2022-03-16 at 12 15 49](https://user-images.githubusercontent.com/49516050/158589988-324f3dce-b3a1-47a6-9f7b-01ae6983eb81.png)
