### ISSUE TITLE
Prevent following policies to reach endpoint when input is invalid: JSON Validation, JSON Threat Protection, XML Threat Protection and Regex Threat Protection

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#7301]
## :collision: Describe the bug

When using `Json validation` policy, if the json is invalid, the request is still propagated to the backend.
⚠️ The same behaviour should occur on `XmlThreatProtection, `JsonThreatProtection` and `RegexThreatProtection`

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
You can find an API attached.

[Antoine-Planets-1-0 (1) 2.json.zip](https://github.com/gravitee-io/issues/files/8362201/Antoine-Planets-1-0.1.2.json.zip)

**Json Validation**

Then, do a call to this API with for example, the following in the body:
`GET /antoine-planets/json-validation`
````
{"name-wrong": "Witney Houston"}
````
-> Request should not be propagated to backend because not valid. (attribute should be `name`)

**Json Threat Protection**

Then, do a call to this API with for example, the following in the body:
`GET /antoine-planets/json-threat`
````
{
    "name": {"first": "whitney", "last": "houston"}
}
````
-> Request should not be propagated to backend because not valid. (max entries for an object is 1)

**Xml Threat Protection**

Then, do a call to this API with for example, the following in the body:
`GET /antoine-planets/xml-threat`
````
<root>
    <name>Houston</name>
    <firstname>Whitney</firstname>
</root>
````
-> Request should not be propagated to backend because not valid. (max elements are 2, to make it work, remove firtname attribute)

**Regex Threat Protection**

Then, do a call to this API with for example, the following in the body:
`GET /antoine-planets/regex-threat`
````
<script>console.log("hello")</script>
````
-> Request should not be propagated to backend because not valid. (not allowed to send Javascript injection)

## :rainbow: Expected behaviour
If the policy returns an error, then the request should not be propagated to backend.

## :movie_camera: Useful information
**How to fix that ?** 

Do not use a `Transformable***StreamBuilder` (request and response implementation). It flushes the content (call `write` on super) causing the request to be send to backend.

We can use a `BufferedReadWriteStream` (as it is done in `RequestValidationPolicy`).
With that, we only `write` and `end` if the validation went well.

Code will look like this:

```
@Override
                public void end() {
                    try {
                        JsonNode schema = JsonLoader.fromString(configuration.getSchema());
                        JsonNode content = JsonLoader.fromString(buffer.toString());

                        ProcessingReport report = getReport(schema, content);
                        if (!report.isSuccess()) {
                            request.metrics().setMessage(report.toString());
                            sendErrorResponse(JSON_INVALID_PAYLOAD_KEY,
                                    executionContext, policyChain,
                                    HttpStatusCode.BAD_REQUEST_400);
                        } else {
                            if (buffer.length() > 0) {
                                super.write(buffer);
                            }
                            super.end();
                        }
                    } catch (Exception ex) {
                        request.metrics().setMessage(ex.getMessage());
                        sendErrorResponse(JSON_INVALID_FORMAT_KEY,
                                executionContext, policyChain,
                                HttpStatusCode.BAD_REQUEST_400);
                    }
                }
```

**Comment by LiliaEn** [comment]
Tested on the default env v3.18.0
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Works as expected.
400 error is displayed when the input is invalid and the policies to not reach the endpoint.
