### ISSUE TITLE
Performance Test (profiling) - Analyze memory consumption of AM Gateway

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#7306]
Investigate the GW memory footprint to determine if and how to improve it.
Maybe look into classloader optimization.

Should look in term of JVM HEAP consumption perspective but also in term of non heap.

In a kubernetes deployment, we have to sure that the default settings for the memory resource requested for the Pod is consistent with the one consumed by the GW/Management. (for the GW, maybe we can compare with the APIM GW)

We should also be able to provide : 
* global GW memory required without domain
* how the memory evolved according to the number of domain / app

**Comment by farmborough** [comment]
https://docs.google.com/document/d/1rus_wrJaCz7MTILKwFluR0kigeOwR64iLQMd55GtD_E/edit
