### ISSUE TITLE
[APIM Console][Policy]Dropdown menu for Methods not showing up as it should.

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#7312]
## :collision: Describe the bug
In Resource Filtering Policy the dropdown menu in which we choose the methods we need does not show up like it should.
View the video bellow to see the issue.

## :sunrise_over_mountains: To Reproduce
1. Create/Import Simple API.
2. Design -> Add  Resource Filtering Policy and go bellow to Settings to Whitelist or Blacklist.
3. Add new rule and when you have to choose the Methods the list is very small instead of it showing all the methods upfront.

## :rainbow: Expected behavior
We should see the whole dropdown menu.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material:
[bug.zip](https://github.com/gravitee-io/issues/files/8260686/bug.zip)

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.15.4 on Docker Desktop
 - OS: Windows 11
 - Browser: Google Chrome

## :warning: Potential impacts

***What are the impacted versions?***

## :link: 3.15.4. Seen this behavior in older versions.

Link a story or other related things...

**Comment by gaetanmaisse** [comment]
Duplicate of https://github.com/gravitee-io/issues/issues/8348
