### ISSUE TITLE
[Vuln] CWE-113 - Improper Neutralization of CRLF Sequences in HTTP Headers

### ISSUE THREAD

**Issue by gaetanmaisse** [gravitee-io/issues#7314]
### 📝 Description

Investigate
 - https://app.snyk.io/org/gravitee.io/project/62522eda-67ae-4079-8306-18e19b59ad2f#issue-a03c65e6-261b-40e3-827e-9bf08d46d193

Todo
 - Check the vuln
 - Some details related to the vuln https://community.veracode.com/s/question/0D53400004DJusECAT/how-to-fix-crlf-http-response-splitting-in-java

**Comment by ppgravitee** [comment]
@gaetanmaisse any update?
