### ISSUE TITLE
[Vuln] CWE-601 - Open Redirect

### ISSUE THREAD

**Issue by gaetanmaisse** [gravitee-io/issues#7315]
### 📝 Description

Investigate
 - https://app.snyk.io/org/gravitee.io/project/62522eda-67ae-4079-8306-18e19b59ad2f#issue-c3cd6958-aa8e-4043-b668-ce15b2213a1c

Todo
 - Do we need to sanitize params?
 - Discuss with the Cockpit team to rework the redirection?

**Comment by ppgravitee** [comment]
@gaetanmaisse any update?
