### ISSUE TITLE
[APIM Console] Read only roles not working part 2

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#7319]
## :collision: Describe the bug
Related to ticket [7243](https://github.com/gravitee-io/issues/issues/7243).
When we have a group and we have members in this group with the default USER Role from API Scope and later we add this Group as a member of an API later when we login to the user the APIs are not shown and also if we go to the user it self and we go to the API tab the API are not there as well. BUT when we change to OWNER Role from USER we are able to see everything.

## :sunrise_over_mountains: To Reproduce
1. Import/Create a simple API.
2. Create a Group and add one of the default user from Gravitee (api1) and give the user User permission on all.
3. Add the Group to the simple API as a member.
4. Go to organization settings and you will see that in the API part of the user added in the Group there are no API related to the Group, make sere that in the Groups tab the user has User and User Role.
5. Log in with the user and you will see no API in the APIs tab even though the Group the user is in is a member of the API/s.
6. Now change the Role from User to Owner and login again all is okay and you can see the API/s.

## :rainbow: Expected behavior
When we add a user to a group/s and that group is a member on or more API/s we should see those API/s in al lists including in the Console when we log in.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material:
[bug.zip](https://github.com/gravitee-io/issues/files/8263181/bug.zip)

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.10.10, 3.10.11, seen similar behavior in 3.15.X on Docker-Desktop
 - OS: Windows 11
 - Browser: Google Chrome
 
## :warning: Potential impacts

***What are the impacted versions?***
3.10.10, 3.10.11, seen similar behavior in 3.15.X on Docker-Desktop

**Comment by mouligno** [comment]
On hold as #7243
