### ISSUE TITLE
[gateway] gateway only keeps last set-Cookie header from backend response even with different cookie-names

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#7325]
## :collision: Describe the bug
When upgrading to 3.15, the gateway response only keeps the last set-Cookie header from backend response even with different cookie-names.

![mceclip1](https://user-images.githubusercontent.com/79909781/158863018-b81b4ff9-5e8f-4b7d-9484-52bb10bc7444.png)

From https://datatracker.ietf.org/doc/html/rfc6265
```
Servers SHOULD NOT include more than one Set-Cookie header field in
   the same response with the same cookie-name.  (See Section 5.2 (https://datatracker.ietf.org/doc/html/rfc6265#section-5.2) for
   how user agents handle this case.)
```
Here we have different cookie-names

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:

## Current behaviour
A clear and concise description of what is currently happening.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.15.3. The bug is not present in 3.5

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by gcusnieux** [comment]
Hi @LiliaEn, I close this issue, it's complicated to test without having the hand on the backend, but I added an integration test.
