### ISSUE TITLE
GitHub rule - 1 code owner approval with no open discussion

### ISSUE THREAD

**Issue by omatthewsgravitee** [gravitee-io/issues#7343]

**Comment by leleueri** [comment]
Options enabled:
* At least one approval on the PR
* No open discussion before merge

Done on : 
* gravitee-access-management (master and maintenance branches)
* gravitee-am-identity-provider-saml (master)
* gravitee-am-identity-provider-cas (master)
* gravitee-am-identity-provider-http-flow (master)
* gravitee-am-identity-provider-kerberos (master)
* gravitee-am-gateway-saml-idp (master)
