### ISSUE TITLE
Debug->The icon of a conditional policy is not displayed in the timeline

### ISSUE THREAD

**Issue by LiliaEn** [gravitee-io/issues#7346]
The icon of a conditional policy is not displayed in the timeline

### Expected Behavior
The icon of a conditional policy should be displayed in the timeline

### Current Behavior
The icon of a conditional policy is not displayed in the timeline![Screenshot 2022-03-21 at 08.45.43.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/c9515db7-587e-4c16-9746-c7c047e48613)

### Steps to Reproduce (for bugs)
1. Login to Console
2. Select an API that has a policy
3. Add a valid condition on the policy
4. Go to Debug and run a request
5. Check the conditional policy in the timeline

### Your Environment
* Version used: default env - v3.17.0
* Browser Name and version: Chrome Version 99.0.4844.51
* Operating System and version: macOS Big Sur v11.6

**Comment by LiliaEn** [comment]
[7226](https://app.zenhub.com/workspaces/graviteeio---api-management-601c1f73be51260015c7bb26/issues/gravitee-io/issues/7226)

**Comment by gcusnieux** [comment]
Hi @LiliaEn It's deployed on 3-17-x env

**Comment by LiliaEn** [comment]
Tested on the 3.17.X
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
New conditional icon is displayed accordingly.
![Screenshot 2022-03-23 at 09.59.01.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/7328f6e7-2647-4e51-88ef-b000467f0986)
