### ISSUE TITLE
I create keyless and oauh2 plans on the same api, but I cannot call api different paths on these plans. it works with keyless plan every time.

### ISSUE THREAD

**Issue by aliFetvaci61** [gravitee-io/issues#7356]
I create keyless and oauh2 plans on the same api, but I cannot call api different paths on these plans. it works with keyless plan every time.

APIM version 3.6.0

![image](https://user-images.githubusercontent.com/16122994/159629810-73369fe6-2d98-482a-983c-bee1c3f10f7c.png)

**Comment by gaetanmaisse** [comment]
Can you update to the latest version and reopen the issue if you're still facing the problem?
