### ISSUE TITLE
[gateway] Implement ApiKey and Subscription managers

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#7360]
During the implemenation of the Shared API key feature, we agreed on a workaround solution on the Apim Gateway side.
We were conscious that this workaround was... a workaround.
This ADR that point the issue and provide a long term solution to get rid of the workaround: https://gravitee.slab.com/posts/adr-008-api-key-and-subscription-managers-ywqaq2dx

**Acceptance criterias:**
- [ ] Non regression in everything related to api keys and subscriptions

**Comment by RubenMMSantos** [comment]
this ticket is being tested together with #7311
