### ISSUE TITLE
[HELM] Helm chart to implement PodDisruptionBudget

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#7364]
## :collision: Describe the bug
Kubernetes now implements PodDisruptionBudget. 
https://docs.microsoft.com/en-us/azure/aks/operator-best-practices-scheduler#plan-for-availability-using-pod-disruption-budgets

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:

## Current behaviour
A clear and concise description of what is currently happening.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: [e.g. 3.10.x]

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by brasseld** [comment]
Already available as per https://github.com/gravitee-io/helm-charts/commit/843876aae1d548d9e312049c79d7e1204373627d
