### ISSUE TITLE
[APIM] Logging condition with timestamp returns status 500

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#7367]
## :collision: Describe the bug
Condition editor in the logging configuration of the API that prevents to consume the API (the API returns a 500 code).
The bug appears when both duration conditions are set (In API logging settings, and in the condition field when configuring logging)

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. In Settings > API logging, set a maximum duration (for example: 10000000)
2. In the API, go to Analytics > Logs > Configure the logging and enable the logging
3. Cick on Show editor to edit the condition
4. Select Duration and add a duration time (for example: 10 minutes), click on Save, Save the logging configuration and deploy the API
5. The condition will not show right away, refreshing or swapping page and going back to it will show the new condition in format:   
 ({) && #request.timestamp <= 1648122185999l && (})
6. Try to consume API

## :rainbow: Expected behaviour
Condition in the format #request.timestamp <= 1648122185999l should appear, without ({), && and (}) 

## Current behaviour
A clear and concise description of what is currently happening.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment:  3.10.10
 
## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by LiliaEn** [comment]
Tested on 3.10.x env
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
No error is displayed when a consuming an API with timestamp condition set on logging.
