### ISSUE TITLE
[management] Investigate UEBA implementation analysis

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#7375]
## :rainbow: Feature

This feature will enable a more intelligent and automated way of adapting the user's access and potential MFA requirement when signing in. It extend the existing hardcoded adaptive access capability and also works with Alert Engine to let application owners and platform administrations know when activated.

The solution may also include integration with third-party providers that can drive risk-based, adaptive access decisions.

![image](https://user-images.githubusercontent.com/1927438/160290629-98df7d21-6224-4a20-b5b4-a24eb18b759b.png)

When a user attempts to sign in, a risk-based authentication solution analyzes factors such as:

- Device - Is the user on a known device ? (fingerprint deviceId)
- Location - Geo-location and Geo-velocity 
- Network - Is the person logging in from a familiar IP address ?
- Sensitivity - Based on http request
- others ?

## :sunrise_over_mountains: Additional information

The goal of this issue is to determine what potential v1 solution we can offer to our users : 

- Which use cases should be included
- What is the result of this analysis ? a score ? a level of risk (low, medium, high) ?
- How we can package that solution ? Is a plugin ? Native one by Gravitee + possibility to add external vendor ?

**Comment by Johngren** [comment]
We will focus on Geo-location and Geo-velocity in v1 of UEBA

### Start to store user logins Geo-location for every authenticator

- If a user login from a new “suspicious” location an alert will be triggered

- Can we send a “is this really you”? Email or sms and send metadata about the suspicion behaviour like usedID, user-agent and also advice some kind of action (revoke session and tokens, advice to change password…)

- MFA will be enforced by configuration in AM for the next login after a “suspicious” login

- Not in v1 - Different levels of alerts (severe, warning, possible)?

### Also use this data for Geo-velocity model and

- If a user login from a location which it is impossible to travel from based on the geo-location of previous login an alert will be triggered

- Can we send a “is this really you”? Email or sms and send metadata like usedID, user-agent and also advice some kind of action (revoke session and tokens, advice to change password…)

- MFA will be enforced by configuration in AM for the next login after a “suspicious” login

- Not in v1 - Different levels of alerts (severe, warning, possible)?
