### ISSUE TITLE
[management] [mfa] FIDO2 factor

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#7378]
## :rainbow: Feature

**As a** 'an application owner'

**I want to** 'validate the MFA challenge of my end-users via FIDO2 procotol (biometrics / security key)'

**So that** 'they can access their account'

## :sunrise_over_mountains: Additional information

- **Should-we re-use user webauthn credential during MFA enrollment step ** ??

## :camera: Mockups 

<img width="1266" alt="Capture d’écran 2022-03-27 à 20 50 17" src="https://user-images.githubusercontent.com/1927438/160296176-33234aef-b102-4fe9-be6c-27aad42699fc.png">

## :books: Documentation required

Provide link to the issue for documentation update

## :superhero: Acceptance criteria

- [ ] Given 'an end-user who wants to sign-in with MFA enabled' Then 'the end-user will verify its account' When 'using FIDO2 factor'

## :warning: Potential impacts

***What are the impacted versions?***

3.18

## :heavy_check_mark: Definition of Done

***For each User Story everything on the list must be considered, select only what was required***
- [ ] Acceptance criteria met and tested
- [ ] Sonar Cloud quality gate passes
- [ ] CircleCi checks pass
- [ ] Cypress or Postman API check passes
- [ ] Test containers passed if modifications on the repository modules
- [ ] Developer created draft documentation PR
- [ ] New migration scripts checked
Can be run multiple times but only makes changes the first time
Display to user what script has done
- [ ] Validated on appropriate environment
- [ ] Existing test cases refactored

:rocket:

**Comment by omatthewsgravitee** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Graviteeio---Access-Management-5b17f74af58c642fb89cc49f/issues/gravitee-io/issues/7378?planning-poker) with ZenHub @remisultan @farmborough @ashraf706 @leleueri @patelami

**Comment by patelami** [comment]
env: 3.18

Given I have disable passwordless 
And I have created and enable FIDO2 factor
And I initiate loginflow 
Then I should see MFA challenge to verify with finger print
And I successfully verify with my fingerprint on device 
Then I should be able to successfully sign in  **PASS**

Given I have disable passwordless 
And I have created and enable FIDO2 factor
And I have create and enable OTP factor
And I initiate loginflow 
Then I should see both option to setup with OTP and fingerprint MFA challenge on first attempt
And I successfully verify with my fingerprint on device 
Then I should be able to successfully sign in 
And I initiate the loginflow again
Then I should be given fingerprint MFA challenge   **PASS**

Given I have enable passwordless 
And I have disable FIDO2 factor
And I initiate login flow
Then I should see password less option on setup
