### ISSUE TITLE
[management] Handle organization level commands

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#7408]
The `commands` collection contains a mandatory `environment_id`.

But some commands at organization level, are not related to a specific environment. And so they are inserted in the collection with the `DEFAULT` environment (see `CommandServiceImpl.send`).
For example, when you come from `UserResource.deleteUser`.

We should be able to handle those organization level commands properly, by linking them to an organization instead of an environment.

**Comment by LiliaEn** [comment]
Tested on the default env v3.18.0 
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Checked that a newly created user is returned correctly upon searching (Index user data for search)
