### ISSUE TITLE
[gateway] move buffer implementation in gravitee-gateway-api

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#7427]
## Refactor

Move `BufferImpl` and `BufferFactoryImpl` from `gravitee-apim-gateway-buffer` in `gravitee-gateway-api`

## Why ?

Today, when we want to use Buffer in a policy (often to test), we need to import a dependency from `gravitee-apim-gateway` and indicate precisely the version.

The interfaces are in `gravitee-gateway-api` and there is no particular reason to not have the implementation here too.

## What to do ?
- Move BufferImpl and BufferFactoryImpl to the new package (need to add a dependency to vertx in `gravitee-gateway-api`)
- Get rid of ServiceLoaderHelper to load factory
- Don't modify explicitly the policies, they can keep the old dependency (avoid to migrate to a more recent version of gravitee-gateway-api that may involve regression)

**Comment by mouligno** [comment]
@ytvnr is it still accurate ?
