### ISSUE TITLE
[APIM] Transfer ownership option is not available to org admin (in memory admin) if primary owner is other user.

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#7430]
## :collision: Describe the bug
Transfer ownership option is not available to org admin (in memory admin) if PRIMARY_OWNER is other user.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Create simple API with other than the ADMIN user,.
2. Log out, and log in as ADMIN.
3. Open the API from the APIs page.
4. See missing option to transfer ownership.

## Current behaviour
A clear and concise description of what is currently happening.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.15.4 3.15.6 3.16.2 3.17.0
 

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by mouligno** [comment]
Link to https://github.com/gravitee-io/issues/issues/7395

**Comment by a-cordier** [comment]
Fixed on 3.10.x, waiting for 3.10.x to be merged back into 3.15.x

**Comment by LiliaEn** [comment]
Tested on 3.15.x env
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Works as expected.
