### ISSUE TITLE
[Console] API Key plan has normal API Key subscription and Shared API Key subscription at the same time

### ISSUE THREAD

**Issue by RubenMMSantos** [gravitee-io/issues#7431]
Using the same plan in an API, i was able to subscribe to an Application using API Key and to another Application using Shared API Key.

### Expected Behavior
If a plan has a subscription using API Key or Shared API Key, it should only be possible to create more subscriptions of the same type. To subscribe to different types user should create a new plan in the API

### Current Behavior
Using the same API plan, i can subscribe to an App using API Key and to a different App using Shared API Key

### Steps to Reproduce (for bugs)
Please click the link for info about the issue
https://drive.google.com/file/d/14l-HDc8ubUeqzHqlardkoBURKU8gQ-dS/view?usp=sharing

1. create 2 APIs and 1 Application
2. subscribe the 2 APIs to the application using API Key
3. create 2 more APIs and 1 Application
4. subscribe the 2 APIs to the application using Shared API Key
5. using 1 of the 2 APIs from step 1, subscribe to the Application that is using the Shared API Key
6. notice the subscription is created successfully and now the same plan has 1 subscription using API Key and another subscription using Shared API Key

### Your Environment
* Version used: https://apim-3-17-x-console.cloud.gravitee.io/
* Browser Name and version: google Chrome Version 99.0.4844.84 (Official Build) (x86_64)
* Operating System and version: macOS Monterey v12.2.1 (21D62)

**Comment by marcambier** [comment]
As discussed together, this is the expected behavior :

An API key plan can be consumed by multiple applications, some using a shared API key, and some using an exclusive API key.
Using shared API keys or plain old API keys is exclusive at the application level, not at the API

So I close this ticket.
