### ISSUE TITLE
Set a testing environment

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7434]
Cockpit connected to master APIM
- Multi environment
- Multi organization 
- Several type of users (cockpit admin/ cockpit user/ local admin/ local user)
-

**Comment by ThibaudAV** [comment]
With ACCOUNT_OWNER
- ✅  Go on default org and default env
- ✅  Create Org + Env and connect to installation
- ✅  Go new org + new env OK

With ORGANIZATION_OWNER or USER
- ❌ Go on default org and default env
- ❌ Go new org + new env OK

With ENVIRONMENT_OWNER or USER
- ✅  Go on default org and default env
- ✅  Go new org + new env OK
