### ISSUE TITLE
[M-API] PATCH method on Import API

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7443]
## :rainbow: Feature

As a devops, I want to update only specific info on my API in order to avoid mistake by adding full API Defintion.

Based on spike - https://github.com/gravitee-io/issues/issues/7417 

## :sunrise_over_mountains: Additional information

After further investigation and spike, the selected solution is more powerful than expected on the short term answer.
The idea is to implement a PATCH method on a resource api/:id/definition that let user update/add/remove value using the JSON path.

By default, the behavior is to update the value.

Main advantage of this solution is that we can also update/add/remove value from abstract components of the API (policies/endpoints/resources…). Users just need to know  the json path since it doesn’t rely on a model, so it would work also for their custom policies for example.

On the other hand, it brings a lot of capabilities to users and we need to prevent critical information updates (like API’s ID)

## :link: Dependencies

N/a

## :camera: Mockups 

N/a

## :books: Documentation required

https://graviteedocs.blob.core.windows.net/7443-patch-import/apim/3.x/apim_publisherguide_partial_update_apis.html

## :superhero: Acceptance criteria

- [x] Given an existing API Then i can update the API name When i use the PATCH method passing only the new name as a payload
- [x] Given an existing API Then i can update an API Plan name When i use the PATCH method passing only the new plan > name as a payload
- [x] Given an existing API Then i can update an endpoint weight When i use the PATCH method passing only the new endpoint > weight as a payload

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :heavy_check_mark: Definition of Done

***For each User Story everything on the list must be considered, select only what was required***
- [x] Acceptance criteria met and tested
- [x] Sonar Cloud quality gate passes
- [x] CircleCi checks pass
- [x] Cypress or Postman API check passes
- [x] Test containers passed if modifications on the repository modules
- [x] Translation for portal UI checked
- [x] Developer created draft documentation PR
- [x] New migration scripts checked
Can be run multiple times but only makes changes the first time
Display to user what script has done
- [x] Validated on appropriate environment
- [x] Existing test cases refactored

:rocket:

**Comment by LiliaEn** [comment]
Tested on the default env v3.18.0 
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
The following use cases were tested using Patch:

- [ ] Update API version;
- [ ] Update API name;
- [ ] Add a Flow;
- [ ] Add policy to a plan flow;
- [ ] Add policy to a flow;
- [ ] Update a policy configuration;
- [ ] Remove a policy from a plan flow;
- [ ] Add properties;
- [ ] Remove Properties;
- [ ] Add Resources;
- [ ] Update Resources;
- [ ] Update the weight of a specific backend;
- [ ] Update the target of an endpoint;
- [ ] Switch endpoint backup;
- [ ] Dry Run - preview the updates;
