### ISSUE TITLE
[APIM] apiPrimaryOwner property of a group disappears when the group is updated through console/api call

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#7448]
## :collision: Describe the bug
When a group that is PRIMARY_OWNER property is updated in the default role, the group is losing the apiPrimaryOwner property in the database.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Create simple api.
2. Create group > Add a user as PRIMARY_OWNER > Transfer ownership of the API to the group.
3. Open group settings > Update the groups default role 
4. Find the group in the database, see missing property "apiPrimaryOwner"
5. The property is dropped if the group is updated by using curl/postman call to as well.

## Current behaviour
A clear and concise description of what is currently happening.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.15.5
 - Docker Installation

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by mouligno** [comment]
LGTM
