### ISSUE TITLE
[Debug Mode] Add Conditional icon in legend

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7457]
As a debug user, i would like to see all icons used in the timeline in the legend

![image](https://user-images.githubusercontent.com/3227037/161789935-cb8c0169-cd63-49ea-b1c4-9178cd3d1846.png)

### Additional informations

We miss the conditional policy icon

**Comment by RubenMMSantos** [comment]
Enhancement verified and working as expected, user can now see conditional icon when using Debug Mode
Verified on envir https://apim-master-console.cloud.gravitee.io/, APIM v3.18
![Screenshot 2022-04-25 at 09 31 05](https://user-images.githubusercontent.com/14939456/165051125-efdbae9b-14b4-4ce9-946a-8874e33df29b.png)
