### ISSUE TITLE
[apim->cockpit] Fix multi organisation login

### ISSUE THREAD

**Issue by ThibaudAV** [gravitee-io/issues#7461]
### Expected Behavior
Login to apim by cockpit on each environment of each organisation

### Current Behavior
Login to apim only work with default environment 

### Steps to Reproduce (for bugs)

1. Go to cokpit
2. Create Organisation 
3. Create Environement
4. Add apim installation on it
5. Login to each environment of each organisation
6. Se if apim console work
7.

### Your Environment

* Version used: master
* Browser Name and version: i.e
* Operating System and version: Atari

**Comment by LiliaEn** [comment]
Tested on the Cockpit pre-prod and APIM default env v3.18.0 
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Login to multiple environments from multiple orgs works as expected.
