### ISSUE TITLE
[management] null environment error when trying to process a task

### ISSUE THREAD

**Issue by a-cordier** [gravitee-io/issues#7462]
## :collision: Describe the bug

~Despite tasks not being scoped to a specific environment, the management API tries get the current environment when processing one, leading to an error when the user accept or reject the task~

EDIT The problem site was actually the promotion service that was sending the cockpit response without an environment ID

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:

1. Perform a promotion
2. As an admin, try to accept or reject the task
3. Get a "Environment null not found error"

## :rainbow: Expected behaviour

The promotion task processing should not try to access the current environment

**Comment by RubenMMSantos** [comment]
issue confirmed has fixed and working as expected.
Accepting a promotion no longer throws an error and the API gets created correctly.
Verified by promoting apis across several environments using cockpit
