### ISSUE TITLE
How to add Policies  for a path

### ISSUE THREAD

**Issue by kevin-jiang** [gravitee-io/issues#747]
![policy](https://user-images.githubusercontent.com/5965992/29752076-bbfd831a-8b89-11e7-8f08-71664b7551e8.png)

does any one know how to add or edit policies for a path ,  on the policies page, i can only add or delete  a path,  but can't add or edit policies for a path

**Comment by NicolasGeraud** [comment]
hi @kevin-jiang , just Drag&drop
