### ISSUE TITLE
[APIM] Policies (or flow) are getting ignored when best match is used in flow mode

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#7472]
## :collision: Describe the bug
When the flow mode "Best match" is used, the policies (or maybe the whole flow), is ignored. 

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Create simple API > Go to design > Add mock policy on a flow (any flow)
2. Go to configuration set "Best Match" > Call with curl/postman.
3. Check response, mock policy is ignored and backend response is received.

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.15.6, 3.17.0
 - OS: Docker install
 

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by mouligno** [comment]
it has been fixed in 3.10.13 and moved to all versions #7412
