### ISSUE TITLE
[APIM] Cockpit user with permission ORGANIZATION_OWNER & ORGANIZATION_USER should be able to log in APIM console 

### ISSUE THREAD

**Issue by ThibaudAV** [gravitee-io/issues#7473]
1.  ## ### Expected Behavior make user with cockpit ORGANIZATION_OWNER & ORGANIZATION_USER can login into console

1.  ## ### Current Behavior that not working

1.  ## ### Possible Solution Check permission consistency

1.  ## ### Steps to Reproduce (for bugs)

1\. Go to cockpit with ORGANIZATION_OWNER or ORGANIZATION_USER 2\. Login to apim 3\. See consol work

1.  ## ### Context

1.  ## ### Your Environment [###ERROR: ###](###)

*   Version used: master
*   Browser Name and version: Netscape
*   Operating System and version: Xbox

1.  <g-emoji class="g-emoji" alias="boom" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4a5.png">
     💥 
     </g-emoji> Describe the bug Cockpit user with ORGANIZATION_OWNER & ORGANIZATION_USER can't login into console
2.  <g-emoji class="g-emoji" alias="sunrise_over_mountains" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f304.png">
     🌄 
     </g-emoji> To Reproduce Steps to reproduce the behaviour: 1\. Go to cockpit with ORGANIZATION_OWNER or ORGANIZATION_USER 2\. Login to apim 3\. See consol work
3.  <g-emoji class="g-emoji" alias="rainbow" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f308.png">
     🌈 
     </g-emoji> Expected behaviour make user with cockpit ORGANIZATION_OWNER & ORGANIZATION_USER can login into console
4.  ## Current behaviour

1.  <g-emoji class="g-emoji" alias="movie_camera" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f3a5.png">
     🎥 
     </g-emoji> Useful information !<span class="error">[image.png]</span>([https://images.zenhubusercontent.com/611a27474390b479699cead2/3199aafa-13ff-4a40-b59a-551c4d863c6d](https://images.zenhubusercontent.com/611a27474390b479699cead2/3199aafa-13ff-4a40-b59a-551c4d863c6d))
2.  <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">
     💻 
     </g-emoji> Desktop:

 _**Please complete the following information:**_ 

*   Environment: master
*   OS: Xbox
*   Browser: Netscape

1.  <g-emoji class="g-emoji" alias="warning" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/26a0.png">
     ⚠️ 
     </g-emoji> Potential impacts

 _**Which other features may be impacted by this fix. This could be populated after fix**_ 

 _**What are the impacted versions?**_ 

1.  <g-emoji class="g-emoji" alias="link" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f517.png">
     🔗 
     </g-emoji> Dependencies

Link a story or other related things...

**Comment by gaetanmaisse** [comment]
Related to https://github.com/gravitee-io/issues/issues/6554

**Comment by gaetanmaisse** [comment]
Closing as a lot of work has been done to improve multi tenancy for APIM 4.2
