### ISSUE TITLE
[jest] As a user I should be able to see all the information related to gateway

### ISSUE THREAD

**Issue by patelami** [gravitee-io/issues#7474]
[api test]

- [x] [As a user, I should be able to list all the gateway information](https://docs.gravitee.io/apim/3.x/management-api/3.0/#operation/listInstances)
- [x] [As a user, I should be able to get monitoring instances for gateway instances](https://docs.gravitee.io/apim/3.x/management-api/3.0/#operation/listInstances)

**Comment by ctschacher** [comment]
PR: https://github.com/gravitee-io/gravitee-api-management/pull/1682
