### ISSUE TITLE
[APIM] Duplicate pages when importing API

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#7485]
## :collision: Describe the bug
If we import API that is having API doc pages, the doc pages duplicate.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Create simple API > Create doc page/s > Export the api
2. Import the API again > Go to pages
3. See duplicates of pages including Aside folder

## Current behaviour
A clear and concise description of what is currently happening.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.10.7; 3.10.13
 - OS: Docker installation

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by mouligno** [comment]
This behavior has been fixed in 3.16 with the integration of crossId
