### ISSUE TITLE
[management] not_equals alert filter displays an empty list

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#7489]
**Steps to reproduce**
- In environment settings > alerts
- Create a new alert
- Select the rule "alert when the lifecycle of a node has changed"
- Click "add a filter"
- Select "hostname" "string" "not equals to"
- The "value" list is empty
![image](https://user-images.githubusercontent.com/87964124/162896741-0f68f68f-7605-418a-a79b-5c6c3e640268.png)

**Expected behavior**
- If the condition contains a list of values, the "value" field should be a list containing values
- If the condition doesn't contains values, the "value" field should be a text 

**Example of behavior with 'equals' condition**

When it contains values, it's a list :
![image](https://user-images.githubusercontent.com/87964124/162896942-bb31e706-ed2f-4762-84ac-e72309877a43.png)

When it doesn't contains values, it's an input field :
![image](https://user-images.githubusercontent.com/87964124/162897141-bdc675f0-81f4-46e8-89b0-0c5574169e9f.png)

**Comment by LiliaEn** [comment]
Tested on the default env v3.18.0 
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Works as expected
