### ISSUE TITLE
[Portal] Improve application list performances

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7497]
## :rainbow: Enhancement

**As a** user with a lot of applicaitons

**I want to** load fastly my applications

## :sunrise_over_mountains: Additional information

- Use the same behavior than for API performances part : loading only ID to compare and optimize traffic
- Link to https://github.com/gravitee-io/issues/issues/6254
- Link to https://github.com/gravitee-io/issues/issues/7836

**Comment by LiliaEn** [comment]
Tested on 3.18.x env
Application listing works smoothly
Tested using around 50 apps
