### ISSUE TITLE
[management] API is invisible on non-default environment

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#7498]
**Steps to reproduce**
- An APIM with 2 environments
- Create an API on the non-default environment
- Restart APIM
- Go to the API list : it's empty

**Expected behavior**
- Created API should be visible

**Comment by LiliaEn** [comment]
Tested on the default env v3.18.0 
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Works as expected
