### ISSUE TITLE
[Debug Mode] 500 Internal Server Error when using Transform Headers policy in combination with API-Key validationkey

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#7499]
## :collision: Describe the bug
500 Internal Server Error raised on api-key Plan with Transform Headers policy 

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Import attached API
2. Subscribe to the API and retrieve the api-key
3. Run the API in DEBUG mode by setting the x-gravitee-api-key to the api-key in the Headers
4. 500 Internal error is raised in the DEBUG window
<img width="1724" alt="Capture d’écran 2022-04-12 à 19 15 23" src="https://user-images.githubusercontent.com/79909781/163017858-b9126ec0-de24-42e8-8c5a-de98ce62a087.png">

5. the same steps work as expected in 3.16.2 (200 OK)
<img width="1332" alt="Capture d’écran 2022-04-12 à 19 17 12" src="https://user-images.githubusercontent.com/79909781/163018135-0b4a027b-b843-4e75-ace9-4d0bf961ebdf.png">

## Current behaviour
A clear and concise description of what is currently happening.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material
[test-debug-api-key-V1.txt](https://github.com/gravitee-io/issues/files/8475104/test-debug-api-key-V1.txt)

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.17.1 (not reproducible in 3.16.2

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by mouligno** [comment]
I just reproduced on our 3.16.x env, something coming from 3.16.3 i guess then.

**Comment by mouligno** [comment]
can it be linked to https://github.com/gravitee-io/issues/issues/7396 ?

**Comment by gcusnieux** [comment]
> can it be linked to #7396 ?
yes it's a regression

**Comment by LiliaEn** [comment]
Tested on 3.16.x env.
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Works as expected.
