### ISSUE TITLE
[management] personal token creation fails

### ISSUE THREAD

**Issue by a-cordier** [gravitee-io/issues#7507]
## :collision: Describe the bug

Creating a personal token fails because of environment not being found

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to your user account in APIM
2. Click on create personal token
3. Validate the creation
4. See error (Environment [null] cannot be found)

## :rainbow: Expected behaviour

Token should be created

## Current behaviour

Token creation fails because the audit service tries to access the current environment. 
This resource is not environment scoped.

**Comment by LiliaEn** [comment]
Tested on the default env v3.18.0 
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Works as expected![Screenshot 2022-04-13 at 13.24.49.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/77cf11f6-3873-4e59-b098-34d21c20a9f7)
