### ISSUE TITLE
[Upgrader] Deploy APIs that gets out of sync by upgrader

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7511]
Following https://github.com/gravitee-io/issues/issues/7205, we've introduced an upgrader to fix the logging conditions.

Running this upgrader introduce an out-of-sync state for APIs that get updated by it. 

The enhancement we propose is : 
- if API was already out of sync, don't deploy but build a report for user for API where logging is not well configured
- if API was synced, deploy it and add a comment "Automatically deployed by Gravitee during upgrade to 3.X.X" to inform user in history

**Comment by gcusnieux** [comment]
Tested by @a-cordier thx
