### ISSUE TITLE
[Management] Isolate analytics between environments

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7520]
The objective is to verify that analytics are well isolated between environments.

### Additional information : 
- We need to check that 2 APIs on different env are not pushing metrics to the same ES index.
- how are analytics isolated for now ? 
- Is it a common ES index ? 
- How are they retrieved in dashboards ? especially global dashboard ?

**Comment by ytvnr** [comment]
An analytic record have this informations:
- api
- application
- plan
- subscription

If the user is not admin, when looking for analytics, a query is built with specific filters containing the ids of apis or applications we want to display, if he is an admin, there is no specific filter on apis or applications
The ids of apis or applications are `findByUser` and filtered on the current environment.

### Answering issue questions

#### We need to check that 2 APIs on different env are not pushing metrics to the same ES index.

Default behavior only creates an index by type and date, for example: `gravitee-request-2022.04.25`.
There is nothing creating a dedicated index per environment, or further `organization-environment`.
Moreover, neither the organization nor the environment are registered as field in a record -> it implies a preprocessing work to find apis/applications ids for the current environment of the authenticated user.

#### how are analytics isolated for now ?

They are not.
You have these kinds of indices, with day date as suffix, representing different analytics:
```
gravitee-monitor-*
gravitee-request-*
gravitee-health-*
gravitee-log-*
```

The data inside is only differentiated thanks to its fields.

#### Is it a common ES index ?

Regarding what as been said, yes. 

I personally don't know if it's a problem. Maybe adding fields for environment and organization can be good enough.

#### How are they retrieved in dashboards ? especially global dashboard ?

As explained above, query is built for the current authenticated user (which is on an environment). Then, depending on what to display, ids of apis/applications are retrieved from database (findByUser + filtering on the environment). For an admin user, there is no particular filtering on apis/applications.
