### ISSUE TITLE
[Management] Domains / Subdomains / Vhost management

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7523]
In order to allow to call an API on several environment, we need to disable context-path mode and switch to virtual host. Other way, we wouldn't be able to call the api /my-great-api on dev env and staging on the same gateway.

### Additional information 

When creating an env in Cockpit, DNS entries for each subcomponents must be dynamically registered (1 dns entry per org/env for API portal, API gtw, APIM console).

Customers may want to use their own DNS. (e.g., *.mycompany.com), For APIM Gtw needs to be aware in order to properly route incoming request to the appropriate API => again vhost needs leveraged here.
  
Customers should configure this through Cockpit, and appropriate configuration should be propagated to the installations.

Domain restriction: when creating an env, the env should get propagated to APIM with proper domain restriction based on DNS entry in order to prevent collision on APIs vhost configuration. Domain restriction is already implemented in APIM missing part is that cockpit do not propagate the domain contraints.

### Objective 
=> Making sure that everything's fine on APIM side so cockpit team can propagate domain constraints.

**Comment by ytvnr** [comment]
needs an improvment on debug mode side to be able to handle vhost properly
