### ISSUE TITLE
[idp] include user mappers during reset password 

### ISSUE THREAD

**Issue by remisultan** [gravitee-io/issues#7530]
## :collision: Describe the bug
When the reset password happens, if some fields are mapped via user mappers in the identity provider, these fields are not mapped and can cause discrepancies when login back.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Apply mapping on an identity provider
2. Reset the password of a user
3. The mapping is not applied

## :rainbow: Expected behaviour
When the reset password happens, if some fields are mapped via user mappers in the identity provider, the field should be mapped.

## Current behaviour
When the reset password happens, if some fields are mapped via user mappers in the identity provider, these fields are not mapped and can cause discrepancies when login back.

**Comment by leleueri** [comment]
A new option has been added into the UserProvider section of the HTTPIdentityProvider.

![image](https://user-images.githubusercontent.com/3110552/170304197-27098dcd-b323-4cef-9046-46e6bb7b478d.png)

This can help if the HTTP backend can't change the output to match the one provided by the AuthenticationProvider endpoint.

:warning: If EL are used for the Mapper, only profile is available into the EL context.
