### ISSUE TITLE
[Permissions] Attaching group to API should be under MEMBER permission

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7532]
## :collision: Describe the bug
When a user has the permission UPDATE on the DEFINITION role of an API, he can add and remove groups to/from the API

## :rainbow: Expected behaviour
It should be under MEMBER update permission 

## Current behaviour
It is under DEFINITION update permission

## :movie_camera: Useful information
Impact on permissions & roles

**Comment by ppgravitee** [comment]
Need to completely rework the permission system, will be treated once we deal with this topic
