### ISSUE TITLE
[Management] Service discovery Healthcheck isn't working

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7533]
## :collision: Describe the bug
It is not possible anymore to configure an healthcheck on a service discovery endpoint group.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:

## :rainbow: Expected behaviour
We should be able to set a HC on a service discovery group endpoint without adding a endpoint to the group

## Current behaviour
we can't

## :movie_camera: Useful information
It has been introduced in 3.13 with the work on the HTTP Connector and some checks on HTTP/GRPC endpoint to set a HC.

## :computer: Desktop:

***Please complete the following information:***
 - Environment: [e.g. 3.10.x] 3.15+

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by mouligno** [comment]
Could it have a linked with https://github.com/gravitee-io/issues/issues/7505 ?

**Comment by LiliaEn** [comment]
Tested on 3.15.x
Browser: Chrome Version 99.0.4844.74 , macOS Big Sur v11.6
Working as expected-> Health Check can be configured on service discovery group.
