### ISSUE TITLE
[Groovy] Groovy Policy sample from documentation fails to execute

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#7535]
## :collision: Describe the bug
Groovy policy gives error message:

```
{
    "message": "Unable to run Groovy script: Failed to resolve method [ class groovy.json.JsonSlurper parseText java.lang.Object ]",
    "http_status_code": 500
}
```
Please update the documentation for the Groovy policy if necessary.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Create API and add the Groovy policy in the flow.
2. Use the Groovy script from the documentation.
3. Use the payload from the documentation to do curl/postman call.
4. See error in response.

## Current behaviour
A clear and concise description of what is currently happening.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: APIM 3.10.9, 3.17.1 with Groovy policy version 1.50.0, 2.2.0
 - OS: Docker Installation
 

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by mouligno** [comment]
Not sure there is an issue there, i've been able to make the script working on a request phase (using request instead of response)

```
import groovy.json.JsonSlurper
import groovy.json.JsonOutput

def jsonSlurper = new JsonSlurper()
def content = jsonSlurper.parseText(request.content)
content[0].firstname = 'Hacked ' + content[0].firstname
content[0].country = 'US'
return JsonOutput.toJson(content)
```

If you want to use it on response phase,  your backend should send the object 

```
[
    {
        "age": 32,
        "firstname": "John",
        "lastname": "Doe"
    }
]
```

**Comment by gaetanmaisse** [comment]
Closing based on https://github.com/gravitee-io/issues/issues/7535#issuecomment-1102820833
