### ISSUE TITLE
MongoDB with self-signed SSL certificate (through Helm chart)

### ISSUE THREAD

**Issue by gaetanmaisse** [gravitee-io/issues#7539]
**Description**

MongoDB with self-signed SSL certificate isn't working

We need to :
 - Add new attributes to handle Truststore in MongoFactory
 - Handle connection to MongoDB with self-signed SSL certificate

PR: https://github.com/gravitee-io/gravitee-api-management/pull/1641

We will also need to:
 - Update the documentation: https://github.com/gravitee-io/gravitee-docs/pull/758
 - Handle attributes in helm charts: https://github.com/gravitee-io/helm-charts/pull/251

**Comment by gaetanmaisse** [comment]
The fix has been merged in 3.10.x and released in 3.10.14, we now need to release it in all upper support branches before updating the doc + helm

**Comment by Mattiamato** [comment]
Hi, could you please also include the PR https://github.com/gravitee-io/gravitee-api-management/pull/1734 in the next 3.10.x release? This will allow us to set the correct value for retryWrites to connect to DocumentDB with SSL. Thank you!

**Comment by gaetanmaisse** [comment]
Closing as it has been released as part of 3.1.45 release of the helm chart
