### ISSUE TITLE
[gateway] API Gateway doesn't failover for all connection failures

### ISSUE THREAD

**Issue by YaytayAtWork** [gravitee-io/issues#754]
### Expected Behavior
Given an API with two endpoints, if one of the endpoints is down the gateway doesn't always failover to the other one.

This happens when the server hosting the endpoint is up, but the target service is not listening on the endpoint (i.e. when a docker image isn't running).
The server returns an immediate ICMP packet and this is reported to the gateway as:
ERROR i.g.g.http.vertx.VertxHttpClient - Server proxying failed: No route to host: srv-blah.blah.com/172.28.128.233:9000

### Current Behavior
A 502 error is returned.
VertxHttpClient.java:98
The failover explicitly only works for timeout failures.

### Possible Solution
I think the failover behaviour should be invoked for any I/O error that prevents a connection being established.

### Steps to Reproduce (for bugs)
1. Set up an API with two endpoints, configured for failover pointing to a single target server.
2. One of the endpoints should be fully operational, the other should be down.
3. Make a number of requests to the API.
4. Some requests will succeed (thanks to round robin) and some will fail (thanks to this issue).
The correct behaviour would be for all requests to succeed.

### Your Environment
* Version used: graviteeio-full-1.8.3
* Operating System and version: CentOS 7.
* JDK: jdk1.8.0_141

**Comment by NicolasGeraud** [comment]
this issue is resolved via #786
