### ISSUE TITLE
[APIM] Errors while creating Platform Policies.

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#7547]
## :collision: Describe the bug
Related: https://github.com/gravitee-io/issues/issues/7548

Two error occur when we try to create a Platform Policy or save while an Empty Platform flow. The moment we try to save we get one of these errors:

![image](https://user-images.githubusercontent.com/57534152/164474043-8055abdc-498c-447a-8ad2-f3d64cb5bde0.png)

![image](https://user-images.githubusercontent.com/57534152/164474165-27078366-5503-4fed-aa56-3e0290a99307.png)

Issue is happening is Postgresql as a DB.

## :sunrise_over_mountains: To Reproduce
1. Start up the installation bellow. (docker-compose)
2. Go to Organization Settings -> Policies -> Design New One->Configure any Policy -> Save.
3. We get the error in the second picture.
4. Delete the Policy -> Save.
5. You will get the other error.

## :rainbow: Expected behavior
We should be able to save without an issue and be able to configure Platform Policies.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material:

[Postgresql 3.15.5.zip](https://github.com/gravitee-io/issues/files/8531625/Postgresql.3.15.5.zip)

## :computer: Desktop:

***Please complete the following information:***
 - Environment: Docker-Desktop
 - OS: Windows 11
 - Browser: Google Chrome

## :warning: Potential impacts

***What are the impacted versions?***
- 3.15.5, 3.15.7, 3.16.3 and 3.17.1

**Comment by LiliaEn** [comment]
Tested on the 3.15.x- jdbc env.
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Works as expected.

**Comment by omatthewsgravitee** [comment]
closed because can't fix now. Re-open if needed (could need a workshop after quality sprints)
Could be a problem with Cockpit integration
