### ISSUE TITLE
[policy] [ip-filtering] Policy needs gravitee-policy-api.version to be updated

### ISSUE THREAD

**Issue by YaytayAtWork** [gravitee-io/issues#755]
The IPFilteringPolicy generates:
Caused by: java.lang.AbstractMethodError: io.gravitee.policy.ipfiltering.IPFilteringPolicy$1.contentType()Ljava/lang/String;
        at io.gravitee.gateway.handlers.api.ApiReactorHandler.sendPolicyFailure(ApiReactorHandler.java:218)
        at io.gravitee.gateway.handlers.api.ApiReactorHandler.lambda$doHandle$11(ApiReactorHandler.java:110)

when the request fails the policy.

This is because the Request interface has had "contentType" added to it, but the policy hasn't been updated to reflect this.

Searching for gravitee-policy-api.version shows that quite a few other policies are also still on 1.0.0.

### Expected Behavior
A 403 Forbidden response.

### Current Behavior
A 500 response, with the stack trace above in the gravitee log.

### Possible Solution
Update gravitee-policy-api.version in the pom and implement contentType for PolicyResult.

### Steps to Reproduce (for bugs)
1. Configure an API with an IP Filter Policy.
2. Send in a request that break the policy.

### Context
Getting a confusing error message.

### Your Environment
* Version used: 1.8.3
* Operating System and version: CentOS 7
* JDK: 1.8.141

**Comment by YaytayAtWork** [comment]
Also, SubnetUtils.isInRange doesn't work correctly for some CIDRs with version 3.4 of commons.net.
This appears to be fixed in 3.6.

**Comment by brasseld** [comment]
Hi @YaytayAtWork,

Can you provide a PR for these issues ?

**Comment by brasseld** [comment]
Ok, let me fix it.
The issue is accurate for this policy.
