### ISSUE TITLE
Gateway does not re-connect automatically to Elasticsearch

### ISSUE THREAD

**Issue by DanilEvt** [gravitee-io/issues#7562]
## :collision: Describe the bug
After elasticsearch is restored, gateway does not automatically connect to elasticsearch. Logs disappear and analytics is not available. Manually restarting the gateway helps.
`0:21:14.418 [vert.x-eventloop-thread-2] [] ERROR i.g.e.client.http.HttpClient - Unable to get a connection to Elasticsearch: The timeout of 30000 ms has been exceeded when getting a connection to elasticsearch:9200
10:21:14.419 [vert.x-eventloop-thread-5] [] ERROR i.g.e.client.http.HttpClient - Unable to get a connection to Elasticsearch: The timeout of 30000 ms has been exceeded when getting a connection to elasticsearch:9200
10:21:16.224 [RxComputationThreadPool-4] [] ERROR i.g.r.e.i.DocumentBulkProcessor - Unexpected error while bulking data with the ES client
java.lang.IllegalStateException: No endpoint available`

## :rainbow: Expected behaviour
Gateway should automatically re-connect to Elasticsearch when it is reachable.

## :computer: Desktop:

***Please complete the following information:***
 - Environment: [3.15]
 - OS: [CentOS]
 - Browser [chrome]

**Comment by phiz71** [comment]
Hello @DanilEvt.
I'm closing this old issue as we can not reproduce with the latest 3.15.13.
