### ISSUE TITLE
CircleCI Optimization - Resource class update

### ISSUE THREAD

**Issue by sursak123** [gravitee-io/issues#7565]
Higher resource class for jobs 

### Expected Behavior
Build completes successfully with same time 

### Current Behavior
More credits used for larger resources which will increase the cost of build

### Possible Solution
Minimize the cost with optimized resource class selection

### Steps to Reproduce (for bugs)
NA

### Context

Build uses more credits

### Your Environment

* Version used:
* Browser Name and version:
* Operating System and version:

**Comment by sursak123** [comment]
Raised PR after changing xlarge resource to large. This will use 20 credits compared to 40 credits for xlarge. The build time is same and verified coverage_build, sonarcloud and other jobs for comparision

**Comment by leleueri** [comment]
fixed by https://github.com/gravitee-io/gravitee-access-management/pull/1837
