### ISSUE TITLE
Be able to write integration tests for APIM plugins

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#7567]
It could be interesting to have like a lightweight gateway that could be used in APIM plugins (policies, resources, tracer, reporter...) so they could be tested in integration tests.

An idea could be to extract what is existing in the *gateway-container* submodule in some sort of test framework.
It could also have a link with the μ-gateway project

**Comment by gaetanmaisse** [comment]
Closing as there is now a Gateway Test SDK, documentation will be merged soon: https://github.com/gravitee-io/gravitee-api-management/pull/1939
