### ISSUE TITLE
[gateway] manage PolicyException on reset password flow

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#7574]
When a flow fails on the RESET_PASSWORD flow, a blank page is displayed with `internal error` message.

### Expected Behavior
We should redirect to the "reset password" cofirmation page with an error message

### Current Behavior
A blank page is displayed with `internal error` message.

### Possible Solution
Implement a Failure Handler on the RESET_PASSWORD flow to redirect in case of PolichyCHainException

### Steps to Reproduce (for bugs)
1. create a http callout that hit a not found resource (enable the exit on error toggle)
2. reset the user password

**Comment by patelami** [comment]
Env: 3.17.x
Result: PASS

Given I have added HTTP call out flow on reset password
And an HTTP callout hits not found unknown resource
And I setup exit on error true with custom message
And Initiate a login flow
And I successfully reset password
Then I should see custom error message **PASS**
