### ISSUE TITLE
Display errors at Gateways Monitoring

### ISSUE THREAD

**Issue by ctschacher** [gravitee-io/issues#7578]
## :collision: Describe the bug
There are some display errors when displaying the Monitoring of a gateway instance (compare video with 'Expected behaviour')

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to 'Gateways'
2. Click on one of the displayed instances
3. Click on 'Monitoring'

## :rainbow: Expected behaviour
1. The percentage values are well centered inside the doughnut chart
2. The doughnut title (e.g. 'CPU', 'HEAP') doesn't touch the chart 
3. The doughnut segment are not constantly redrawn every 2 seconds

## :movie_camera: Useful information
https://images.zenhubusercontent.com/61280156/4666ea74-d737-4cb6-888e-d521ad000b2f/gateway_monitoring.mov

## :computer: Desktop:

***Please complete the following information:***
 - Environment: [e.g. 3.18.0-snapshot]
 - OS: MacOS
 - Browser Chrome

**Comment by ppgravitee** [comment]
fixed in 3.20
