### ISSUE TITLE
Helm deployment, APIM Gateway endpoint and context path overlapping

### ISSUE THREAD

**Issue by NassimBounouas** [gravitee-io/issues#7584]
## :collision: Describe the bug
Hi,

I'm not sure if it's a real bug, a rewrite issue from my configuration or a documentation issue. I'm looking for more information, especially if I missed something.

I deployed the api management on Kubernetes using helm. The gateway is exposed using ingress nginx behind a domain "https://apim.mydomain.com/gateway" as templated in [the default values](https://github.com/gravitee-io/helm-charts/blob/master/apim/3.x/values.yaml#L901).

Since I'm using the latest helm version, the API has an environment variable `portal.entrypoint` set to "https://apim.mydomain.com/gateway" as provided by [the helm-chart pull request #218](https://github.com/gravitee-io/helm-charts/pull/218/files) following the issue #7169 

I created an API but the context path must be set to `/gateway/myapi` to let the API be reachable. However on the API catalog page the API access URL  is set as `https://apim.mydomain.com/gateway/gateway/myapi` which is not reachable since the working URL is `https://apim.mydomain.com/gateway/myapi`

I tried three methods

1. Set a rewrite rule as following but this mess up with the access URL which takes the regex part
```
path: /gateway(/|$)(.*)
hosts:
  - apim.mydomain.com
annotations:
  cert-manager.io/cluster-issuer: "letsencrypt-prod"
  kubernetes.io/ingress.class: nginx
  nginx.ingress.kubernetes.io/ssl-redirect: "false"
  nginx.ingress.kubernetes.io/rewrite-target: /$2
```

2. Edit the API deployment after the helm deployment to revert the entrypoint to `https://apim.mydomain.com/`, this is solving the access url issue but it's quite dirty since the context-path of all the APIs must start by the gateway path which is not related to the API.

3. Completely remove the environment variable after deployment to authorize the url modification through "Organization settings" > "Sharding tags" > "Entrypoint mappings" > "Default entrypoint" which is grayed out if an environment variable is provided

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Deploy Apim using the helm chart with ingress-nginx
2. Configure an API with a context-path set to `gateway/myapi`
3. Call it to check if it's reachable on `https://yourdomain.com/gateway/myapi` then compare the url with the access url on the developper portal which will be set to `https://yourdomain.com/gateway/myapi`

## :rainbow: Expected behaviour

At least a way to deactivate the behavior introduced  by [the pull request #218 on the helm chart](https://github.com/gravitee-io/helm-charts/pull/218/files) without deactivating the gateway.

Maybe do I wrongly use the helm chart ? @gaetanmaisse since you reviewed the PR, can you give me your opinion about my situation ? Thank you

A way to differentiate the gateway access path, the api context-path and set the access url on the catalog to the correct API adress.

**Comment by gaetanmaisse** [comment]
This PR https://github.com/gravitee-io/helm-charts/pull/337 will remove `/gateway` from the gateway ingress path so you shouldn't face your issue anymore.
