### ISSUE TITLE
[management] Auto fetch of documentation is not working

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#7589]
## :collision: Describe the bug
Even if the auto-fetch is activated for a documentation page in the console, the page is not updated from the external source.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to Settings -> Documentation
2. Create a new page markdown page and give it a name
3. Select "Import from an external source (gitlab, bitbucket, ...)" and select WWW
4. Put `https://raw.githubusercontent.com/gravitee-io/issues/master/README.md` in the URL field (or any other markdown file you can modify)
5. Select Auto-Fetch
6. Click Save
7. Click fetch
8. Modify the external file (`https://raw.githubusercontent.com/gravitee-io/issues/master/README.md`)

## :rainbow: Expected behaviour
As by default, the fetcher is activated every 5min, then after 5min the page should have been fetched from the source and updated.

## Current behaviour
The page is not updated.

## :movie_camera: Useful information
The bug was introduced in 3.11.x.
Since a refactoring, auto fetch option is not saved in the page configuration, so the scheduler don't know that the page needs to be updated.

## :warning: Potential impacts

***What are the impacted versions?***
3.15 and higher

## :link: Dependencies

Link a story or other related things...

**Comment by LiliaEn** [comment]
Tested on 3.15.x env.
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Auto-fetch is working as expected.
