### ISSUE TITLE
Add unbundled policies to dev environments 

### ISSUE THREAD

**Issue by gaetanmaisse** [gravitee-io/issues#7598]
### 📝 Description

Some policies like `policy-javascript` aren't part of the default APIM bundle nor EE bundle. 
They are currently not deployed on our dev envs, the goal of this issue is to include them. 

### 🔎 Technical Details

Need to update the distribution? Or maybe just the helm values?

**Comment by ppgravitee** [comment]
check with @phiz71

**Comment by LiliaEn** [comment]
Tested on 3.10.x , 3.15.x , 3.16.x, 3.17.x.
Javascript policy is displayed.
Still waiting for master env to be working in order to check on the last version and will close this ticket at that time.

**Comment by LiliaEn** [comment]
Tested on default env as well- 3.18.0 version
Javascript policy is displayed.
