### ISSUE TITLE
[management] mongodb queries fail when encountering a document with a field set to `undefined`

### ISSUE THREAD

**Issue by a-cordier** [gravitee-io/issues#7610]
## :collision: Describe the bug

When a document contains a field explicitly set to `undefined` mongodb query fails because there is no converter for the `BsonUndefined` type

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Set a field to undefined on a document in your db
2. Perform a findAll query
3. The query fails

```
org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type org.bson.BsonUndefined to type java.lang.String
```

related to https://github.com/spring-projects/spring-data-mongodb/issues/2350

## :rainbow: Expected behaviour

The query should not fail and we should set the field to null in that case

**Comment by a-cordier** [comment]
see https://github.com/gravitee-io/_support_team/issues/153

**Comment by RubenMMSantos** [comment]
"real" fix is pending user feedback, this is an internal fix that was covered locally by the dev.
