### ISSUE TITLE
[management] Error while deleting a user

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#7613]
## :collision: Describe the bug
On a JDBC database, I have an error when deleting user.
```
11:17:30.957 [gravitee-listener-57] ERROR i.g.r.j.m.JdbcAbstractCrudRepository - Failed to update users item:
org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; ERROR: null value in column "organization_id" violates not-null constraint
```

It only occurs when this option is enabled:
```yaml
user:
  anonymize-on-delete:
    enabled: true
```

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:

1. Enable the `user.anonymize-on-delete.enabled` option in `gravitee.yml` file
2. Start Gravitee
3. Create a user
5. Try to delete the user

## :rainbow: Expected behaviour
The user should be logically deleted, with anonymized data.

## Current behaviour
Error while "updating" the user

## :warning: Potential impacts

***What are the impacted versions?***
3.10.x and upper

**Comment by RubenMMSantos** [comment]
Behaviour reproduced on envir 3-10-x-jdbc with no errors displayed after creating/deleting a user.
Database was checked together with dev to confirm data for deleted users was anonymised after deletion.
