### ISSUE TITLE
[gateway] Silent re-authentication flow not followed when user needs consent

### ISSUE THREAD

**Issue by igordreher** [gravitee-io/issues#7616]
## :collision: Describe the bug
`prompt=none` parameter not respected when needing user consent.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to Applications -> <application> -> Settings -> General
3. Scroll down to Consent
4. Turn off skip user approval
5. Initiate login flow with a logged user without consent passing `prompt=none` query param

## :rainbow: Expected behaviour
Should redirect to `redirect_uri` passing error and error_description as query params.

## Current behaviour
It redirects to consent page.

## :movie_camera: Useful information

https://user-images.githubusercontent.com/62728088/166328315-e79dc73b-6b2d-4553-b2d0-061b98044587.mp4

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.17.0
 - OS: Linux
 - Browser chrome

**Comment by NathanFirmo** [comment]
Same problem here 😢

**Comment by tcompiegne** [comment]
Hey @igordreher and @NathanFirmo,

Thanks for pointing out, it seems indeed that is a bug. 

We will do some tests on our side and provide a fix.

Kind regards
