### ISSUE TITLE
[Debug Mode] Encrypted value are not interpreted

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7629]
## :collision: Describe the bug
In debug mode, the encrypted properties are not interpreted.  
On a mock policy, it does display the encrypted value.
But also, it can result of skipped policy if an encrypted property is used in a condition.

EDIT: This bug is also present for the plan configured on tags not configured on the gateway and that are not filtered

## :sunrise_over_mountains: To Reproduce
- I’ve created an API
- I’ve added one property and encrypted it
- i use it in a mock policy
- in debug mode, i got the encrypted value
- in postman (or any other call), i got the value i’ve set

## :rainbow: Expected behaviour
Encrypted properties should be interpret as in real use case.

## Current behaviour
Encrypted properties are not decrypted.

## :computer: Desktop:

***Please complete the following information:***
 - Environment: [e.g. 3.10.x] 3.16 + 

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...
[Echo-Benjamin-1-0.json.txt](https://github.com/gravitee-io/issues/files/8638331/Echo-Benjamin-1-0.json.txt)

**Comment by ppgravitee** [comment]
@mouligno is this one still on hold or is the doc sufficient?
