### ISSUE TITLE
Fix EnvironmentNotFoundException for task

### ISSUE THREAD

**Issue by ThibaudAV** [gravitee-io/issues#7635]
Next to ExecutionContext refactoring we can't see subscription task in the console.
We have this 404 error :
![image](https://user-images.githubusercontent.com/4974420/167567748-47d51141-67d2-4669-8b77-c21b49536ad0.png)

**Comment by LiliaEn** [comment]
Tested on 3.10.x
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Works as expected.
![Screenshot 2022-05-18 at 12.06.42.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/dda376f4-ca33-4b3f-851c-75ed0b7c0f12)
