### ISSUE TITLE
Configure alerts from AM

### ISSUE THREAD

**Issue by Johngren** [gravitee-io/issues#7638]
## :rainbow: Feature

**As an admin in AM

**I want to be able to configure Risk Assessments Alerts

**So that I can receive alerts from Alerts Engine

## :sunrise_over_mountains: Additional information

This is regarding the UI of using Risk Assessment Alert

## :link: Dependencies

Link a story or other related things...

## :camera: Mockups 

Insert screenshots, drawings...

## :books: Documentation required

Provide link to the issue for documentation update

## :superhero: Acceptance criteria

- [ ] Given the need to use Risk Assessment Alerts Then it should be configurable When the admin visits Alert page in AM

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

:rocket:

**Comment by omatthewsgravitee** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Graviteeio---Access-Management-5b17f74af58c642fb89cc49f/issues/gravitee-io/issues/7638?planning-poker) with ZenHub @ashraf706 @farmborough @patelami @remisultan

**Comment by patelami** [comment]
env: 3.18


This is not currently configured on nightly. As discussed with team the adaptive MFA scenarios are tested and covered to cover this story.  

The coverage is added to the story #7555
