### ISSUE TITLE
[Console] Promote API Designer

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7645]
## :rainbow: Feature

As an API Publisher, I want to be aware of API Designer capabilities when I create my API

## :sunrise_over_mountains: Additional information

Link to API Designer presentation page (`target: _blank`)

The rule for the link is:

- if the installation is already connected to a cockpit instance, then the link redirect to this cockpit instance. With the information we have for the moment, we can only redirect to the login form of cockpit
- if not, the link redirects to an explanation page on the Gravitee.io website: https://www.gravitee.io/platform/api-designer?utm_source=apim

## :link: Dependencies

Link a story or other related things...

## :camera: Mockups 

![image](https://user-images.githubusercontent.com/3227037/167861205-d1aff9b3-6d23-4bc7-9fe6-fe281e4ea3cb.png)

https://www.figma.com/file/ypt1ab4iyg1aEzYIwRiYFl/API-Creation-Workflow?node-id=573%3A4297

## :books: Documentation required

Provide link to the issue for documentation update

## :superhero: Acceptance criteria

- [ ] Given '...' Then '...' When '...'
- [ ] Given '...' Then '...' When '...'
- [ ] Given '...' Then '...' When '...'

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

:rocket: APIM 3.18.0

**Comment by gaetanmaisse** [comment]
_Note_: First implementation will use the current design system

**Comment by mouligno** [comment]
Our test env is linked to cockpit, I'm well redirect to cockpit login or cockpit page. Any way to test the website link for non-linked env ?

**Comment by LiliaEn** [comment]
Tested on the default env v3.18.0 
Browser: Chrome Version 99.0.4844.74 , macOS Big Sur v11.6
Checked that New API Designer is displayed as expected and redirects the user to cockpit;
Checked that API creation is working as before;
Checked that API Import is working as before;
Checked that path based API creation is working as before;
