### ISSUE TITLE
[Management] Toggle on system role edition

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7659]
## :rainbow: Feature

As an administrator, I want to toggle on/off the edition on system role.

## :sunrise_over_mountains: Additional information

- Toggle off by default
- `gravitee.yml`

## :link: Dependencies

Related to https://github.com/gravitee-io/issues/issues/7157

## :camera: Mockups 

Insert screenshots, drawings...

## :books: Documentation required

Provide link to the issue for documentation update

## :superhero: Acceptance criteria

- [ ] Given system role edition toggle `ON` Then i can update permissions list  When I view the System role (Primary Owner & Environment Admin)
- [ ]  Given system role edition toggle `OFF` Then i can NOT update permissions list  When I view the System role (Primary Owner & Environment Admin)

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

:rocket: 3.18+

**Comment by a-cordier** [comment]
testing this ticket needs to set the flag properly in the helm chart and then redeploy APIM to check that System Role Edition is enabled/disabled accordingly. As there is another ticket with a config flag (jupiter mode toggle) I think the best is to wait for the feature to be merged and perform both test at once

**Comment by LiliaEn** [comment]
Tested on the default env v3.18.0 
Browser: Chrome Version 99.0.4844.74 , macOS Big Sur v11.6
Tested with the toggle on, the permissions for system roles can be updated correctly;
Tested with the toggle off, system roles are not editable.
