### ISSUE TITLE
[management] Search API by crossId returns all APIs

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#7660]
**Steps to reproduce**
- create 2 APIs and export the both to generate their crossId
- call the API search endpoint with the `crossId` criteria as parameter (see https://docs.gravitee.io/apim/3.x/management-api/3.17/#operation/getApis)

**Current behavior**
Endpoint returns all APIs

**Expected behavior**
Endpoint should return only the API with matching crossId

**Comment by LiliaEn** [comment]
Tested on 3.16.x env.
Working as expected.
![Screenshot 2022-05-17 at 08.39.41.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/d39aec2c-bafa-437e-9c43-4f3f3a857444)
