### ISSUE TITLE
[APIM]Update a role API requires a id field when this is not necessary/required based on the doc.

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#7661]
## :collision: Describe the bug
Following [this](https://docs.gravitee.io/apim/3.x/management-api/3.17/#operation/updateRole_1) when we try to update a role we are not able to without giving it an ID, we get an error message:

{
    "message": "The given id must not be null!",
    "http_status": 500
}

Not sure if this is fully a bug or maybe an enhancement needs to be made.

By this:

![image](https://user-images.githubusercontent.com/57534152/168301311-2b851200-469b-4895-855b-76d23eac1f8b.png)

an Id is not needed.

## :sunrise_over_mountains: To Reproduce
1. Using Postman or cUrl simply try to use the PUT command to try and update a role.

## :computer: Desktop:

***Please complete the following information:***
 - Environment: Docker-Desktop
 - OS: Windows 11
 - Browser: Google Chrome

## :warning: Potential impacts

***What are the impacted versions?***
- 3.17.1

**Comment by gaetanmaisse** [comment]
`id` is now part of the required fields:

<img width="250" alt="image" src="https://user-images.githubusercontent.com/4112568/182098097-949cf414-9fee-45ee-9d6d-c325f0cd64de.png">
