### ISSUE TITLE
[Gateway] Hazelcast is referring to a queue but get a topic

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7681]
## :collision: Describe the bug

The OOM is due to a bad configuration (on Gravitee Gateway side).

https://github.com/gravitee-io/gravitee-api-management/blob/676e17904090a8612d1ef36c1768cbb1dff1927d/gravitee-gateway-services/gravitee-gateway-services-heartbeat/src/main/java/io/gravitee/gateway/services/heartbeat/HeartbeatService.java#L125

We are getting a topic here but the hazelcast.xml is referring to a queue: https://github.com/gravitee-io/gravitee-api-management/blob/676e17904090a8612d1ef36c1768cbb1dff1927d/gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/hazelcast.xml#L26

And so, the max-size is not applied correctly.

## :sunrise_over_mountains: To Reproduce

https://github.com/gravitee-io/_support_team/issues/172

## Current behaviour
A clear and concise description of what is currently happening.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: APIM 3.10+

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by gaetanmaisse** [comment]
_Notes_:
 - Remove this part from gravitee-io/gravitee-api-management@676e179/gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/hazelcast.xml#L26
