### ISSUE TITLE
[management-ui] [adaptive access] Frontend implementation

### ISSUE THREAD

**Issue by omatthewsgravitee** [gravitee-io/issues#7689]
## :rainbow: Feature

**As a** 'application owner'

**I want to** 'configure my MFA adaptive access options'

**So that** 'MFA will be triggered intelligently for my end-users'

## :camera: Mockups 

https://www.figma.com/file/njZKzkZvcI5VSGGDEHUFwh/MFA?node-id=1%3A145

![image](https://user-images.githubusercontent.com/6514033/171126718-4214b221-45d8-4333-9b78-8977cf6d6676.png)

![image](https://user-images.githubusercontent.com/6514033/171126939-30b48f5a-198a-47af-8d0d-66a305d0e359.png)

![image](https://user-images.githubusercontent.com/6514033/171127014-7f669808-a59c-449a-b485-80249389c558.png)

![image](https://user-images.githubusercontent.com/6514033/171127112-41195682-2374-4238-a297-f5db5ee6689e.png)

:rocket:

**Comment by omatthewsgravitee** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Graviteeio---Access-Management-5b17f74af58c642fb89cc49f/issues/gravitee-io/issues/7689?planning-poker) with ZenHub @ashraf706 @farmborough @leleueri @patelami @remisultan

**Comment by patelami** [comment]
env: 3.18

All the scenarios tested for this feature are added to the ticket #7555 . The feedback around ui improvement is added to this [ticket](https://github.com/gravitee-io/issues/issues/7944#issue-1289917662).
