### ISSUE TITLE
[JEST test] Flows - create global flows and use them

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7694]
### Scenario
the idea is to test that when we create several flows, it triggers the one expected regarding the call made to the gateway

### Additional information

**Comment by ThibaudAV** [comment]
## Test summerise :

- Create Global Flow with `/env`
  - And Transform Headers policy to add headers "global-flow-ok"
  
- Create an API
  - With root flow with `/env/:envId`
  - And Transform Headers policy to add headers "root-flow-ok"

- Create Keyless Plan
  - With flow `/env/:envId/keyless` and Transform Headers policy to add headers "plan-flow-ok"

- Start API

> Should return 200 OK on `GET /`
> Should return 200 OK on `GET /env`
> Should return 200 OK on `GET /env/foo`
> Should return 200 OK on `GET /env/foo/keyless`
