### ISSUE TITLE
[JEST test] create several plan flows and use them

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7695]
### Scenario
the idea is to test that when we create several plan flows, it triggers the one expected regarding the call made to the gateway

### Additional information

**Comment by ThibaudAV** [comment]
## Test summerise :

- Create an API

- Create 2 different plans (Keyless & ApiKey)

- Create an Application and Subscribe on Keyless & ApiKey plans

- Change the flow on the Keyless plan to `GET /plan/keyless/foo`
  - Add a Mock Policy with `This is Keyless Foo`.

- Add a flow on the Keyless plan `GET /plan/keyless/:planName`
  - Add a Mock Policy with `This is Keyless PlanName`.

- Add a flow on ApiKey `POST /plan/apikey`
  - Add a Mock Policy with `This is ApiKey POST`.

- Add a flow to root `GET /plan`
  - Add a Policy Attribute with an attribute `X-test: root-flow`

- Start the API 

- Call on the `GET /plan/keyless/foo` endpoint with the Keyless plan
  -  should return `This is Keyless PlanName` with `X-test`

- Call on the `GET /plan/apikey` endpoint with the ApiKey plan
  -  should return `This is ApiKey POST` without any `X-test`

- Switch Flow Mode to BestMatch

- Call on the `GET /plan/keyless/foo` endpoint with the Keyless plan
  - should return `This is Keyless Foo` with `X-test`
