### ISSUE TITLE
[JEST Test] add policies to flows and use it 

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7696]
### Scenario
the idea is to test complex flows with various policies chained and interactions between each other 
- attributes
- contexts
- properties

### Additional information

Some common scenarii that chains policies from real use case : 
- Dynamic routing in order to call a specific endpoint
- Set and use the cache policy
- Get some info from the request, use it in a Callout to retrieve info from third party, modify the request with Assign Content or Transform Header 

### Test summarize 

- Create an API
- Create keyless plan
- Set up a cache resource
- Add some policies
  - callout some info using header from the request (ex: categories on chucknorris jokes API)
  - cache response content 
  - assign content to the response
- call the API, make sure that it's working well 
- recall the API, make sure cache is used
- wait till the cache is expired
- recall the API, working without cache

**Comment by jhaeyaert** [comment]
Very interested by this work, hope we could reuse it for testing jupiter 🤩
