### ISSUE TITLE
Add X-Frame-Options herader inside console + portal nginx config

### ISSUE THREAD

**Issue by ThibaudAV** [gravitee-io/issues#7710]
Add :
`add_header X-Frame-Options "SAMEORIGIN" always;`
inside

[gravitee-api-management/default.conf.tmpl at master · gravitee-io/gravitee-api-management](https://github.com/gravitee-io/gravitee-api-management/blob/master/gravitee-apim-console-webui/docker/config/templates/default.conf.tmpl)

**Comment by RubenMMSantos** [comment]
Console side validated in ticket [#7736](Improve default security for nginx config)
Portal side validated
![Screenshot 2022-05-24 at 13.14.37.png](https://images.zenhubusercontent.com/612518f668e84e3f309d282d/b51925dc-6f8f-4f3b-9d56-6c196ee6d801)
