### ISSUE TITLE
Use X.509 certificate based auth with mongodb

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#7729]
## :rainbow: Feature

We planned to use X.509 certificate auth with MongoDB Atlas. 
We have tested it on our applications and it is ok. But we have no documentation on how to do it with Gravitee AM. 
We need documentation about how to do it with the Helm chart.

ZDT: 4231

**Comment by leleueri** [comment]
Fixed by https://github.com/gravitee-io/issues/issues/5856 & https://github.com/gravitee-io/helm-charts/pull/281

**Comment by leleueri** [comment]
We have to amend the Documentation to give HelmChart usage example

**Comment by gaetanmaisse** [comment]
Closing since the original ticket has been closed after a discussion with the customer.
