### ISSUE TITLE
[Technical] Detect plugin errors at install phase

### ISSUE THREAD

**Issue by ThibaudAV** [gravitee-io/issues#7733]
Currently, if there is an error when installing a plugin an error is added in the log and apim will still start normally. 

So we have no way to detect these errors only with the IC

Proposals:
- Add an e2e that allows to look at the logs at apim startup and throw if it contains ERROR
- Add a startup mode for apim with a flag like `failure-on-plugin-error`. used by e2e 
others ... 

Topic added because :
Gravitee node has bum a version no more compatible with some plugin. (via a pr Snyk)
And the only way to see the error is at the start of apim. or when the QA test the plugin alert

**Comment by ThibaudAV** [comment]
Subject to be discussed with the Archi Team before. There are many ways to deal with it and some of them are planned in their team

**Comment by a-cordier** [comment]
putting on hold until @ThibaudAV is back to get more context around the issue
