### ISSUE TITLE
Improve default security for nginx config

### ISSUE THREAD

**Issue by ThibaudAV** [gravitee-io/issues#7736]
Configure this following flag to improve default apim security :

- X-XSS-Protection
> This header can prevent some types of cross-site scripting attacks.
- X-Content-Type-Options
> This header can prevent attacks in which the browser is tricked into misinterpreting
the MIME type of a piece of data.
- Content-Security-Policy
> This header helps to prevent XSS, clickjacking and code injection attacks.
- X-Permitted-Cross-Domain-Policies
> When using Adobe technologies (PDF, Flash etc) this header can be implemented to
instruct the browser on whether content can be loaded from other domains. Setting
strict values can help to mitigate the risk of cross-domain attacks.

For Nginx:
```

add_header X-XSS-Protection "1; mode=block";

add_header X-Content-Type-Options nosniff;

add_header X-Permitted-Cross-Domain-Policies none;Copy

add_header Content-Security-Policy "default-src 'self';";
```

**Comment by RubenMMSantos** [comment]
Response headers verified in console, headers are as expected.
![Screenshot 2022-05-24 at 13.09.54.png](https://images.zenhubusercontent.com/612518f668e84e3f309d282d/ffb2a2d0-0123-4aed-be6a-b713248d1545)
