### ISSUE TITLE
[Console] Padding issue on content of some Console screen

### ISSUE THREAD

**Issue by gaetanmaisse** [gravitee-io/issues#7738]
## :collision: Describe the bug

There is a weird space in some of the screens:
![image.png](https://images.zenhubusercontent.com/601d5c7b3af73910acbaa2a1/e319fe07-c9e1-4100-9340-fe3796574ef9)

## :sunrise_over_mountains: To Reproduce
1. Go to https://apim-3-10-x-console.cloud.gravitee.io/#!/environments/3-10-x/apis/79e5cf20-de0b-a454-7fa0-d44be6753dbc/portal
2. Check the weird space on both sides of the content 

![image.png](https://images.zenhubusercontent.com/601d5c7b3af73910acbaa2a1/89abb095-abd0-4b8d-a62e-5e39f3924b32)![image.png](https://images.zenhubusercontent.com/601d5c7b3af73910acbaa2a1/d9f376c0-a267-44b3-9d86-f72fcbfd0b77)

## :rainbow: Expected behaviour

Content should be next to the side menu without any space

## Current behaviour

See screenshot

## :movie_camera: Useful information

NA

## :computer: Desktop:

NA

## :warning: Potential impacts

***What are the impacted versions?***

This could come from `ui-component` and so impact all versions

## :link: Dependencies

NA

**Comment by RubenMMSantos** [comment]
issue verified and confirmed has fixed
