### ISSUE TITLE
[Platform] Mutualize System proxy configuration

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#7739]
## :rainbow: Feature

Regarding this discussion -> https://github.com/gravitee-io/gravitee-resource-oauth2-provider-generic/pull/32#discussion_r869425045

The goal of this issue is to mutualize all the `System Proxy` configuration into `gravitee-common` lib.

**Comment by a-cordier** [comment]
Tests done on master, locally using squid as a system proxy

- [ ] healthcheck
- [ ] callout
- [ ] jwt
- [ ] oauth2 generic
- [ ] oauth2 am
- [ ] metrics
