### ISSUE TITLE
[Policy] Cache Policy : cache not cleared/refreshed after Time to Live

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#7740]
## :collision: Describe the bug
When enabling Cache Policy in a flow/Plan, the content of the cache is not cleared/refreshed after the Time to live the element in cache.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Create an API with API key plan (endpoint https://api.gravitee.io/whattimeisit)
2. Add a default Cache resource (default settings)
3. Add a Cache Policy from this Resource and set the TTL to 5s
4. Make requests to the API for more than 5s
5. The response keep retrieving the cache value after 5s
6. Stop making requests to the API for 5s or more
7. Make new requests to the API
8. Cache gets updated (like if TTL acts as Time to Idle)

## :rainbow: Expected behaviour
Cache to be cleared/refreshed after TTL set in the Policy

## Current behaviour
Cache not cleared after TTL

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: replicated in 3.15.8 but not in 3.10.3

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by LiliaEn** [comment]
Tested on 3.15.x
Browser: Chrome Version 99.0.4844.74 , macOS Big Sur v11.6
Works as expected
