### ISSUE TITLE
[reporter] File reporter log files are missing headers details

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#7741]
## :collision: Describe the bug
When enabling File reporter at the gateway level, the associated generated file for log (log-2022-05-24.json) does not include headers content as  `"empty": false`  : 
```
    "clientRequest": { 
        "method": "GET", 
        "headers": { 
            "empty": false 
        }, 
        "uri": "/echo" 
    }, 
```

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Enable File reporter at the gateway level
2. Create an API, enable logging, and make some requests
3. Check the content of the generated log-2022-05-24.json file

## :rainbow: Expected behaviour
Have headers details in the generated file

## Current behaviour
headers details are missing

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: replicated in 3.15.8 but not in previous 3.10.3

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by gaetanmaisse** [comment]
Not sure it can be tested on our dev environments 🤔

**Comment by gaetanmaisse** [comment]
I will test it locally
