### ISSUE TITLE
APIM Connection with Google connect fails

### ISSUE THREAD

**Issue by vdusauto** [gravitee-io/issues#7743]
## :collision: Describe the bug
I can't define Google as an Identity provider to connect to APIM

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to 'Organization settings'
2. Click on 'Authentication'
3. Click on 'Add'
4. Configure a Google Provider
5. Try to login with Google

## :rainbow: Expected behaviour
Google Login form should display once

## Current behaviour
An error message is displayed : OAuth 2 parameters can only have a single value: state

##Version
Latest of APIM

**Comment by phiz71** [comment]
Hello @vdusauto, would it be possible to have more information on how you configure your IDP ?
Because it is something we use a lot internally, and it works very well

**Comment by vdusauto** [comment]
Hello Florent,

I can't explain more simply than :

   - I click on create Create new identity provider
   - Select Google IDP
   - Fill in the form up to client_id/client_secret
   - And that's it...

[image: image.png]

Here is the error :

[image: image.png]

We can setup a call if you'd like. I tried on several APIM with same issue.

Thanks !

Victor Dusautois
APIzr - Accélérer votre digitalisation
www.apizr.fr
Tel: 06 28 74 38 87


Le mar. 24 mai 2022 à 18:13, Florent Chamfroy ***@***.***> a
écrit :

**Comment by vdusauto** [comment]
@phiz71 I found this : 
https://stackoverflow.com/questions/29694840/googles-openid-connect-says-oauth-2-parameters-can-only-have-a-single-value-c

https://www.cloudsponge.com/news/2015/04/14/gmail-oauth2-broken-and-fixed/

We're running on APIM 3.15.3
Thanks !

**Comment by phiz71** [comment]
Hello @vdusauto ,
We have tried with our latest 3.15.x version (3.15.8) and unfortunately we didn't reproduce your problem 😕

On Google, what is the type of your `OAuth 2.0 Client ID` ? Is it an old configuration ?
What have you configured in `Authorized JavaScript origins` and `Authorized redirect URIs ` ?

Have you tried with a new `OAuth 2.0 Client ID` ?

**Comment by phiz71** [comment]
Hello @vdusauto ,
good news, we've finally managed to reproduce your issue.
It was working for us, because our IDP was simply called "google" and we were in a very specific use case.

We have found the root cause And will provide a fix as soon as possible.

As a workaround, could you try to name your IDP "Google" ?

**Comment by LiliaEn** [comment]
Tested on 3.15.x env
Browser: Chrome Version 99.0.4844.74 , macOS Big Sur v11.6
Working as expected
