### ISSUE TITLE
[gateway] Max logging size must accept smaller size than MB

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#7761]
When defining the `max_size` on the gateway, this one only accepts MB as the default unity.
We should be able to accept smaller size than MB which doesn't really make sense in most of the cases.

For backward compatibility, I propose the following rule:

`max_size: 1` -> without unity, consider MB
`max_size: 1MB` or `max_size: 1mb` or `max_size: 1M` or `max_size: 1m` -> with unity, consider MB
`max_size: 1KB` or `max_size: 1kb` or `max_size: 1K` or `max_size: 1k` -> with unity, consider KB
`max_size: 1B` or `max_size: 1b` -> with unity, consider B

**Comment by LiliaEn** [comment]
Closing this ticket as it's for 3.5.x and cannot be tested.
cc: @gaetanmaisse
