### ISSUE TITLE
remove distinction between CE and EE distribution

### ISSUE THREAD

**Issue by ppgravitee** [gravitee-io/issues#7770]
With the new license framework introduced by @gravitee-io/archi team, we can now change the way we build APIM packages to have one and only one packaging.
We will remove the CE/EE distinction.

Todo list:
- [x] make APIM depending on `gravitee-node:1.24.1` and `gravitee-plugin:1.23.1`
- [x] remove `ee` profile in `gravitee-apim-gateway-standalone-container` and `gravitee-apim-rest-api-standalone-container`
- [x] remove dependency on `gravitee-license`
- [x] remove `distribution-ee` profile in `gravitee-apim-distribution` and dispatch former dependencies
- [x] use the `1.3.0` version of `gravitee-notifier-slack` which is now a public plugin (no longer a EE plugin)
- [x] use the `2.0.1` version of `gravitee-policy-data-logging-masking` which remains a EE plugin but use the new license framework
- [x] use the `2.0.1` version of `gravitee-policy-assign-metrics` which remains a EE plugin but use the new license framework
- [x] use the new version of Alert-Engine connector
- [x] adapt the `config.yml`

**Comment by phiz71** [comment]
Closing this issue since we can see on apim-master that we are in EE version, with the new docker image. Everything is working well.
