### ISSUE TITLE
Add Pendo analytics tool

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7781]
## Description

Pendo is a product analytics tool, it has been integrated into Cockpit and to get cross-product data we will need to integrate it on APIM (trial saas deployment too)

## Technical details

Recap after discussion with @mouligno @ThibaudAV 

Two new configuration keys should be added in `gravitee.yml`
 - A flag to activate or deactivate the Pendo analytics service
 - The key to use in Pendo analytics service

These data will be fetched by the console with the `/console` request sent before loading the app.

The console will have 2 implementations of a Pendo service interface:
 - The one calling the real Pendo service
 - A fake one, just doing nothing

Accordingly to the activation flag, either the real or the fake implementation will be instantiated.

⚠️ We need to check everything is ok when navigating from AngularJS to Angular and vice versa.

**Comment by ThibaudAV** [comment]
https://github.com/gravitee-io/gravitee-api-management/commit/6a7b126cbed5ba60a7a3db052764de426f678d08

**Comment by ThibaudAV** [comment]
Test by QA was not needed on this subject. It's more an internal feature only intended for SASS use. 
This optional tool, if enable, only initialise at the bootstrap and send event on login (apim console). So if some regression was made we can see it immeasurably.
