### ISSUE TITLE
[management] Regression in API imports

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#7807]
## :collision: Describe the bug
This [commit](https://github.com/gravitee-io/gravitee-api-management/commit/c0fd2ecbb47cd7e63e227882702b05f6e8e4aa80) made in 3.10.x and merged in upper branches has introduced some regressions.

### fix a regression in members import with roles
When importing an API with members, roles can be added to members. Before Gravitee APIM 3.x, only one role was allowed:

```json
"members": [{
    "...": "...",
    "role": "MY-ROLE-NAME"
}]
```

Starting with 3.x, multiple roles can be added. For this, we use another field and role must be added by their Ids:
```json
"members": [{
    "...": "...",
    "roles": [
      "1111-1111-1111-1111",
      "2222-2222-2222-2222"
    ]
}]
```

With this regression, roles are all considered as role names. As a consequence, no members can be imported if using `roles` field

### fix a regression on API import when no plan imported
When importing an API with an empty `plans` field, if the API already exists and has plans, then all these plan should be deleted.

With this regression, no plan are deleted.

## :computer: Desktop:

***Please complete the following information:***
 - Environment: Introduced in 3.10.x and present in 3.15.x, 3.16.x and 3.17.x

**Comment by RubenMMSantos** [comment]
Following scenarios were covered for this ticket per envir:
3.10
- [ ] create API with no plan and export
- [ ] add plan to existing API
- [ ] import previous definition and verify that API was updated (plan got deleted)
- [ ] created API with several members/roles and exported api
- [ ] removed members and imported previous definition (with members aded) and verified members/roles were correctly added
- [ ] delete api and imported previous definition (with members aded) and verified members/roles were correctly added
3.15
- [ ] create API with no plan and export
- [ ] add plan to existing API
- [ ] import previous definition and verify that API was updated (plan got deleted)
- [ ] created API with several members/roles and exported api
- [ ] removed members and imported previous definition (with members aded) and verified members/roles were correctly added
- [ ] delete api and imported previous definition (with members aded) and verified members/roles were correctly added
3.16
- [ ] create API with no plan and export
- [ ] add plan to existing API
- [ ] import previous definition and verify that API was updated (plan got deleted)
- [ ] created API with several members/roles and exported api
- [ ] removed members and imported previous definition (with members aded) and verified members/roles were correctly added
- [ ] delete api and imported previous definition (with members aded) and verified members/roles were correctly added
3.17
- [ ] create API with no plan and export
- [ ] add plan to existing API
- [ ] import previous definition and verify that API was updated (plan got deleted)
- [ ] created API with several members/roles and exported api
- [ ] removed members and imported previous definition (with members aded) and verified members/roles were correctly added
- [ ] delete api and imported previous definition (with members aded) and verified members/roles were correctly added
