### ISSUE TITLE
debug mode join multi value headers

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#7809]
## :collision: Describe the bug

In Debug Mode, if the form request contains several times the same header, then the values are join as one string with `,` separator.

The problem is that it alters the request, and if you want to access headers values as an array, then you will just have a string with all the values

## :sunrise_over_mountains: To Reproduce
1. Go to an API in Debug Mode and configure a transform header like this
![image](https://user-images.githubusercontent.com/47851994/172851440-6d73d0f9-1e50-4b88-9615-257f5a9b49df.png)

3. Send a request like this
![image](https://user-images.githubusercontent.com/47851994/172850574-e74ed8dc-99d9-4e74-9ffe-8c574b9a86db.png)

4. you see only test1 has been added with the values joined
![image](https://user-images.githubusercontent.com/47851994/172851330-697f5bdb-5cf1-43db-951b-26042afb7387.png)

## :rainbow: Expected behavior
We expect to have a header `test1: val1` and another `test2:val2`

**Comment by LiliaEn** [comment]
Tested on 3.17.x
Browser: Chrome Version 99.0.4844.74 , macOS Big Sur v11.6
Working as expected
![Screenshot 2022-06-13 at 09.26.31.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/82b0d7f0-1b8d-41c6-beed-acf901c16d7e)
