### ISSUE TITLE
Groovy policy error on HTTP headers (backport of 3.17)

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#7811]
## :collision: Describe the bug

Backport of https://github.com/gravitee-io/issues/issues/7810

Since the modification of HTTP Headers in 3.15.x, accessing a header through a groovy script via `request.headers.'My-Header'` will return a string instead of an array of values, meaning it becomes impossible to do array operation (`join` for example).

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
Add a groovy script to your policy and use:
```groovy
if (request.headers.containsKey('test')) {
     userAgent = request.headers.'test'.join('|');
request.headers.'test2' = userAgent;

   }
```
It should fail with
```
22:05:55.485 \[vert.x-eventloop-thread-1\] \[\] ERROR i.g.policy.groovy.GroovyPolicy - Unable to run Groovy script  
java.lang.SecurityException: Failed to resolve method \[ class java.lang.String join java.lang.String \]  
        at io.gravitee.policy.groovy.sandbox.SecuredInterceptor.onMethodCall(SecuredInterceptor.java:49)
```

## :rainbow: Expected behaviour
We should be able to join all the values in a string if we want

**Comment by mouligno** [comment]
LGTM
