### ISSUE TITLE
HTTP headers breaking changes from 3.15

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#7812]
## :collision: Describe the bug

3.15 of APIM introduced a new implementation of HTTP Headers which causes multiple breaking changes.

We start to have more and more ticket about this kind of issues:

- https://github.com/gravitee-io/issues/issues/7741
- https://graviteesource.zendesk.com/agent/tickets/4261
- https://graviteesource.zendesk.com/agent/tickets/4241
- https://graviteesource.zendesk.com/agent/tickets/3551
- https://github.com/gravitee-io/issues/issues/7810 & https://github.com/gravitee-io/issues/issues/7811
- https://github.com/gravitee-io/issues/issues/7754

## Some types of problem

- We have three different implementations of `HeaderMapAdapter` (in Groovy policy, Assign Content policy and Metrics reporter policy) which returns a `String` or a `List<String>` for the `get(key)` **-> proposition to move this adapter to `gravitee-gateway-api`**
- We can have some problem when migrating from < 3.15 to 3.15.+ on methods relying on the result of the access to headers, like for this [groovy issue](https://github.com/gravitee-io/issues/issues/7810) with `request.headers.'User-Agent'.join(',')` which was returning a string instead of an array. Other issues would be about `contains`/`containsKey`, etc. -> **proposition is to organize a workshop to compare former and new implementation and extract a contract which does not causes regression.**

## Attention points

We should particularly pay attention to policies using headers through their configuration (and not relying on an IDE with compilation checks):
- Groovy Policy
- Javascript Policy
- Expression Language
- Freemarker

Also, a problem has been detected on `http-connector`, multi valued headers only had the first value propagated to the backend.

## Documentation

If breaking changes persists, we should clearly document it.
By the way, it's an opportunity to improve the documentation on that part and what is possible to do with headers.

## Testing

Opportunity to improve tests:
- on core modules 
- on policies working with headers (reproduce use cases from support tickets)

**Comment by mouligno** [comment]
LGTM
