### ISSUE TITLE
Replace Python script by distribution to build bundle

### ISSUE THREAD

**Issue by gaetanmaisse** [gravitee-io/issues#7813]
## Description

During the package phase of the current release process, a Python script is used to build the full bundle. 
It's not very convenient and contains a lot of dark magic. 
The goal of this issue is to remove this Python script and use the bundle generated with the distribution POM

Wait for the 3.18 release before doing this

**Comment by ThibaudAV** [comment]
TODO : 
- [ ] Merge 3.18.x to master

**Comment by gaetanmaisse** [comment]
Merge has been done 🚀
