### ISSUE TITLE
Spike regression pack

### ISSUE THREAD

**Issue by ppgravitee** [gravitee-io/issues#7817]
Goal: Dig into the regression pack to identify:
- Which lines are already covered by a test
- Which lines are planned in this sprint
- Which lines will be automated in the futur with ticket ID

Update: use the use case files instead of reg pack to add empty tests in the code https://docs.google.com/spreadsheets/d/1sWdKKoi3MnJR6gCmyT8eXZaircI4yktoWvxXFwcLbaQ/edit#gid=1446856125

**Comment by gaetanmaisse** [comment]
How to follow the progres: 

> On écrit tous les scenarios dans jest (recopie du regression pack) et on mets ceux qui ne sont pas implémentés en skip
comme ça tu peux utiliser ton rapport pour voir une full view des tests avec ce qui passe et ce qui n’est pas encore implem
