### ISSUE TITLE
[management] issues with API imports

### ISSUE THREAD

**Issue by RubenMMSantos** [gravitee-io/issues#7822]
Whilst doing regression on API imports across versions, some issues were detected that need to be fixed in order to validate ticket [#7807](https://github.com/gravitee-io/issues/issues/7807)

3.15
- for every API import done there is an error displayed but the import is still done and the api gets created/updated
![Screenshot 2022-06-10 at 13.27.19.png](https://images.zenhubusercontent.com/612518f668e84e3f309d282d/da076778-c3c9-4eb1-8ff4-47883870709a)
- when importing an API definition (with no plans) to update an existing API (that has a plan) the update does not delete the existing plan - this is the expected behaviour mentioned on [#7807](https://github.com/gravitee-io/issues/issues/7807)
- when importing an API definition (with multiple roles) to update/create an API the update does add the multiple roles to the API definition - this is the expected behaviour mentioned on [#7807](https://github.com/gravitee-io/issues/issues/7807)

3.17
- when importing an API definition (with no plans) to update an existing API (that has a plan) the update does not delete the existing plan - this is the expected behaviour mentioned on [#7807](https://github.com/gravitee-io/issues/issues/7807)
- when importing an API definition (with multiple roles) to update/create an API the update does add the multiple roles to the API definition - this is the expected behaviour mentioned on [#7807](https://github.com/gravitee-io/issues/issues/7807)

The behaviours mentioned above were verified on each respective envir for APIM 3.15 and 3.17

**Comment by LiliaEn** [comment]
Tested on 3.10.x
Browser: Chrome Version 99.0.4844.74 , macOS Big Sur v11.6
The error is still displayed when trying to import the APi, but the APi gets imported
The other 2 issues are not reproducible in 3.10
![Screenshot 2022-06-24 at 09.34.54.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/ea71d774-9aba-4169-a6d8-dd7c7cfddb3c)

**Comment by gcusnieux** [comment]
No problem with roles in 3.15.10 with this import.
[APi-Pub-1-0.json.zip](https://github.com/gravitee-io/issues/files/9009326/APi-Pub-1-0.json.zip)
