### ISSUE TITLE
APIM Console-> "API out of sync" banner is displayed even after deployment 

### ISSUE THREAD

**Issue by LiliaEn** [gravitee-io/issues#7830]
"API out of sync" banner is displayed even after deployment 

### Expected Behavior
After deployment, the API should not display "Out of sync" state

### Current Behavior
The APIs are displayed as "out of sync" even after deployments. Reproducible on existing an newly created APIs

### Steps to Reproduce (for bugs)
1. Login to APIM as an admin
2. Find an API which is out of sync and deploy it
3. Create and new API and at the last creation step click on "Create and Start the API"
4. Check if "API out of sync" banner is displayed

### Your Environment
* Version used: default env - v3.18.0
* Browser Name and version: Chrome Version 99.0.4844.74
* Operating System and version: macOS Big Sur v11.6

**Comment by mouligno** [comment]
fixed

**Comment by LiliaEn** [comment]
Tested 3.18.x env
Browser: Chrome Version 99.0.4844.74 , macOS Big Sur v11.6
Working as expected
