### ISSUE TITLE
[gateway] Remember device isn't proposed when user connect with Webauthn

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#7832]
The checkbox "remember your device" not displayed when user connect using Webauthn

### Expected Behavior

Whatever is the authentication way, the MFA challenge page should display the remember device checkbox if enabled

### Current Behavior

the MFA challenge page displayes the remember device checkbox only when user connect using login/password

### Steps to Reproduce (for bugs)
1. Enable Webauthn on your app
2. Enable MFA OTP on your app with RememberDevice
3. Connect user for the first time, register the webauthn device and enroll MFA
4. logout the user
5. Connect user using webauthn
6. MFA Challenge is displayed but the checkbox remember device is missing

![image.png](https://images.zenhubusercontent.com/6026363e864bfc6af2b3aa2c/88907dea-312f-4aae-9d1b-de57a96cf4d3)
![image.png](https://images.zenhubusercontent.com/6026363e864bfc6af2b3aa2c/dbca5514-ee4c-441f-a8ac-78e68f9fad28)

Looks like the call  `checkIfDeviceExists(ctx, client, user.getId(), deviceId, deviceType, rememberDeviceSettings)` is missing from “Authenticate V1” script. Probaly linked to https://github.com/gravitee-io/gravitee-access-management/pull/1889

**Comment by tcompiegne** [comment]
Fixed by https://github.com/gravitee-io/issues/issues/5363
