### ISSUE TITLE
[Console] Application List performances

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7836]
## :rainbow: Feature

As a user, I want to be able to navigate through all my applications smoothly

## :sunrise_over_mountains: Additional information

- We should be able to handle 20k+ applications
- Pagination of application in order to load applications smoothly 
- We need a paginate resource for application
  - Application resources doesn't support pagination - low endpoints for user with a lot of APIs
  - Same behavior as for APIs paginated :
```
size | integer <int32> [ 1 .. 100 ]Default: 20
-- | --
page | integer <int32> >= 1Default: 1
```
- Linked to this work : https://github.com/gravitee-io/issues/issues/6254

**Comment by LiliaEn** [comment]
Tested on 3.18.x env
Pagination works as expected:
         - items per page can be updated;
         - navigating back and forth;
         - number of apps gets updated accordingly when navigating back and forth;
Tested locally with more than 20k apps:
         - navigating back and forth using 100 items per page or less;
         - apps searching;
![Screenshot 2022-08-16 at 19 39 24](https://user-images.githubusercontent.com/49516050/184964353-3e0a3b8f-a7b5-433e-8bf9-504da8b4514c.png)
![Screenshot 2022-08-16 at 19 54 17](https://user-images.githubusercontent.com/49516050/184964383-593014cd-4998-4dcf-a813-9a6a0732c935.png)
![Screenshot 2022-08-16 at 20 01 54](https://user-images.githubusercontent.com/49516050/184964428-1b3649c9-d9db-4a60-b57a-4972a61f6d07.png)

- Tried to access Subscription page of an API- Server unreachable error is displayed
- Tried to access Subscription page of an APP- same error as above
***Please note that this was not happening on the dev env where I was using around 20 apps
![Screenshot 2022-08-16 at 20 11 58](https://user-images.githubusercontent.com/49516050/184964469-81cebbb9-4f1f-4173-b490-ea0106b6675c.png)
![Screenshot 2022-08-16 at 19 30 23](https://user-images.githubusercontent.com/49516050/184964582-c962fbe6-4749-4ea8-ac8f-a0cacd889dc9.png)

**Comment by LiliaEn** [comment]
Retested locally ->The above errors are not displayed anymore after the last fix.
"Server unreachable" is still displayed when searching for an app to subscribe to an API because of the UI Component and also because I am using 20k apps with similar names. The component executes a search request on each letter. This is not related to application performance. The issue is reported here to be tracked/fixed separately: [8329](https://github.com/gravitee-io/issues/issues/8329)
