### ISSUE TITLE
APIM Console-> Copy Texts for Import an Existing API section is not correct

### ISSUE THREAD

**Issue by LiliaEn** [gravitee-io/issues#7848]
Copy Texts for Import an Existing API section is not correct

### Expected Behavior
Some appropriate texts should be displayed. TBD (Ask PO, PdM etc.)

### Current Behavior
Please see the screenshot for the current result: ![Screenshot 2022-06-17 at 11.42.17.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/3081ce58-a0ff-431f-a2d1-7cdfa0161685)

### Steps to Reproduce (for bugs)
1. Login to APIM Console
2. Go to APIs-> Create API
3. Check the placeholder text for Import an Existing API section

### Your Environment
* Version used: default env - v3.18.0 and 3.18.x env.
* Browser Name and version: Chrome Version 99.0.4844.74
* Operating System and version: macOS Big Sur v11.6

**Comment by ppgravitee** [comment]
Fixed
