### ISSUE TITLE
[console] Search for API owner not working as expected

### ISSUE THREAD

**Issue by ctschacher** [gravitee-io/issues#7854]
## :collision: Describe the bug
I was not able to search for a specific API owner using ownerName e.g. `ownerName:api1`. Despite having several APIs created by this user only one was displayed.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to 'APIs'
2. Make sure you have several APIs from a user you want to search for
3. Click into the search bar and type 'ownerName:<USERNAME>'

## :rainbow: Expected behaviour
I will get a filtered view seeing all the APIs that were created by a specific user

## Current behaviour
The results are incomplete, only a fraction of the APIs that should be displayed are actually shown

***Please complete the following information:***
 - Environment: 3.18
 - OS: macOS 12.3.1
 - Browser Chrome 102

**Comment by LiliaEn** [comment]
New issue -> When searching by ownerName, the APIs that have a User (a member) that matches the searching name are returned as well:
![Screenshot 2022-06-30 at 14.20.48.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/0f845198-52ea-4733-8dbf-fc073fa1b465)

**Comment by gcusnieux** [comment]
Could you retry ? It seems good now

**Comment by LiliaEn** [comment]
Above issue not reproducible anymore.
Tested on 3.18.0 
Browser: Chrome Version 99.0.4844.74 , macOS Big Sur v11.6
Searching by ownerName works as expected.
