### ISSUE TITLE
[console] Listening host in virtual-host mode is changed to 'null' when saving

### ISSUE THREAD

**Issue by ctschacher** [gravitee-io/issues#7856]
## :collision: Describe the bug
After switching to virtual-hosts mode, the entry for 'Listening host' is empty (there's just the hint 'Listening host' written in the input field). After modifying something (e.g. listening path) and pressing 'Save' that input field value changes to 'null' and that endpoint can not be reached. Only after manually removing that 'null' (=> leaving empty string) you can save again and this time it will stay empty (and endpoint will work). **But with every deploy of the API the 'null' will appear again.**

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to 'APIs'
2. Click on 'Proxy'
3. Click on 'Switch to virtual-hosts mode'
4. Modify existing path or add another Virtual Host
5. Press 'Save'

## :rainbow: Expected behaviour
It will just save, leaving all fields as they were after input.

## Current behaviour
Input text field will be filled with 'null' which leads to an error when trying to connect to this endpoint

## :movie_camera: Useful information
https://images.zenhubusercontent.com/61280156/7c4e717a-a1a8-4949-bdf3-40cb40390e92/screen_recording_2022_06_20_at_14_54_49.mov

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.18
 - OS: MacOS 12.3.1
 - Browser Chrome 102

## :warning: Potential impacts
***What are the impacted versions?***
Tested with 3.10.x, 3.17.3 and 3.18 (same behaviour on all of them)

**Comment by ytvnr** [comment]
It also resolves https://github.com/gravitee-io/issues/issues/7139 so I closed it as it was not part of a sprint
