### ISSUE TITLE
[APIM] Entrypoints are case sensitive

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#7858]
## :collision: Describe the bug
When trying to consume APIs the entrypoint is case sensitive.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Create API
2. Try to consume the API with postman or curl
3. API is consumed only if the entrypoint is used exactly like it is defined in the API in the console

## :rainbow: Expected behaviour
When trying to consume API we should be able to use it without case sensitivity

## Current behaviour
API is "not found" if the letters in the entrypoint are not same case as in the URL we use to consume the API

![image](https://user-images.githubusercontent.com/98313939/174798183-4a35c004-d1de-4771-b587-3ace9f09d3a7.png)
![image](https://user-images.githubusercontent.com/98313939/174798303-58b10c7d-990b-4979-927c-2db50cf54e3e.png)

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.10.16; 3.15.9; 3.16.4; 3.17.3
 - OS: Docker installation
 

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by phiz71** [comment]
@kirestoj01 it's not a bug. The path part of a URL should always be considered case-sensitive.	

Here are some links:
https://www.w3.org/TR/WD-html40-970708/htmlweb.html

>  URLs in general are case-sensitive (with the exception of machine names). There may be URLs, or parts of URLs, where case doesn’t matter, but identifying these may not be easy. **Users should always consider that URLs are case-sensitive.**

https://webmasters.stackexchange.com/questions/90339/why-are-urls-case-sensitive
