### ISSUE TITLE
[console] SAVE and RESET buttons remain deactivated after endpoint configuration has been modified

### ISSUE THREAD

**Issue by ctschacher** [gravitee-io/issues#7861]
## :collision: Describe the bug
The configuration of an endpoint group can't be saved or reset as the SAVE and RESET buttons remain deactivated even after the config has been modified. However, this applies only to changes made in the CONFIGURATION tab, if something changes in the GENERAL tab (e.g. the name) these two button become active and clickable but even then changes from the CONFIGURATION tab are not saved.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to 'APIs'
2. Click on one of the APIs 
3. Go to the Proxy -> Endpoints (Backend services)
4. Click on the cog wheel to edit the configuration of the group
5. Click on the CONFIGURATION tab and make some changes

## :rainbow: Expected behaviour
The SAVE and RESET buttons become available as soon as a change was made

## Current behaviour
The SAVE and RESET buttons remains inactive

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.18
 - OS: MacOS 12.3.1
 - Browser Chrome 102

## :warning: Potential impacts

***What are the impacted versions?***
Also reproducible on 3.17.3 (haven't checked other versions yet)

**Comment by gaetanmaisse** [comment]
Closing as it looks to be fixed on the latest 3.15 and 3.18, I wasn't able to reproduce this issue on our dev envs.
