### ISSUE TITLE
[management] rollback API with api key plan throws an error

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#7863]
**Steps to reproduce**
- Create an API with an API key plan
- Publish it
- Make some modification to the API
- Go to Audit > History
- Try to rollback the first published API

**Current behavior**
- An error displays "An error occurs while trying to rollback the API"

**Expected behavior behavior**
- API is rollback without any error

**Comment by RubenMMSantos** [comment]
issue verified
successfully rolled back API to a previous definition.
