### ISSUE TITLE
[management] API history shows inconsistent differences on plans

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#7864]
**Steps to reproduce**
- Create an API with a plan
- Publish it
- Make some modification to the API in order to have the 'api out of sync baneer', but don't deploy the API
- Go to Audit > History
- Select the 'to deploy' version, and hit 'diff with published API'

**Current behavior**
- UI shows differences in data that were not modified

**Expected behavior**
- UI should not show differences in data that were not modified

**Comment by LiliaEn** [comment]
Tested on 3.18.0 
Browser: Chrome Version 99.0.4844.74 , macOS Big Sur v11.6
Working as expected
