### ISSUE TITLE
Wrong "response" template variable in assign attributes policy

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#7866]
## :collision: Describe the bug
The assign attributes policy defines request and response variables in the template engine context but it seems the response variable isn't correct:

```java
private static final String REQUEST_VARIABLE = "request";
private static final String RESPONSE_VARIABLE = "request";
```

(source: https://github.com/gravitee-io/gravitee-policy-assign-attributes/blob/master/src/main/java/io/gravitee/policy/assignattributes/AssignAttributesPolicy.java#L46)

## :sunrise_over_mountains: To Reproduce
N/A

## :rainbow: Expected behaviour
N/A

## Current behaviour
N/A

## :movie_camera: Useful information
N/A

## :computer: Desktop:

N/A

## :warning: Potential impacts

Seems to be there since the beginning so all supported version of APIM and AM are impacted.

## :link: Dependencies

N/A

**Comment by gaetanmaisse** [comment]
Closing as it has been fixed https://github.com/gravitee-io/gravitee-policy-assign-attributes/releases/tag/1.5.1
