### ISSUE TITLE
Organisation Settings-> Error is displayed when trying to delete a sharding tag

### ISSUE THREAD

**Issue by LiliaEn** [gravitee-io/issues#7870]
Error is displayed when trying to delete a sharding tag. The tag is still displayed as available. When trying to delete it the second time it gets removed and no error is displayed. Even when the error is displayed if the page gets refreshed the tag will not be displayed anymore.

### Expected Behavior
The tag should be deleted without any error from the first try

### Current Behavior
Error is displayed when deleting a sharding tag for the first time. Please see the video
https://drive.google.com/file/d/13PxS_Wi3Sn51RmMvZnE0wp5ol10k6akZ/view?usp=sharing
![Screenshot 2022-06-22 at 08.32.53 (2).png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/5ea708d4-ad53-48ed-8b61-6bc7da4c4a99)

### Steps to Reproduce (for bugs)
1. Login to APIM as an admin
2. Go to Organisation Settings-> Sharding tags
3. Delete an existing sharding tag (if none exists, add one and then delete it)

### Your Environment
* Version used: - v3.18.0
* Browser Name and version: Chrome Version 99.0.4844.74
* Operating System and version: macOS Big Sur v11.6

**Comment by mouligno** [comment]
@LiliaEn did you reproduce in previous versions ?
