### ISSUE TITLE
Generate JWT policy with x5c-certificate in header sometimes adds wrong certificiate

### ISSUE THREAD

**Issue by ingvarbs** [gravitee-io/issues#7874]
## :collision: Describe the bug
We have 2 APIs that use the generate JWT-policy using the generated JWTs to authenicate against backed. Sometimes the wrong serticicate i s added to the x5c-header. When this tharts we have to 

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Add 2 APIs that use the generate JWT policy with 2 different certificates and select "Add a certificate as an X5C attribute"
2. Use API 1 and ensure the generated JWT is correct
3. Use API 2
4. Use API 1 and check JWT once more, the JWT will be invalid and will have the certificate belonging to API2 in the header. It will be signed with correct certificate

## :rainbow: Expected behaviour
The policy will generate a JWT with configured certificate.

## Current behaviour
the JWT will have the certificate belonging to API2 in the header. It will therefore not validate. It is signed with correct certificate

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.15.9 (using container -images from gravitee)
 - OS: Kubernetes-cluster (okd, OS fedora-Core)

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

3.15.9

## :link: Dependencies

Link a story or other related things...
We started getting this bug after upgrading from 3.12.2 to 3.15.9

**Comment by ThibaudAV** [comment]
Hi 👋, i've try to reproduce, But I did not have any error. 

I used [https://dinochiesa.github.io/jwt/](https://dinochiesa.github.io/jwt/) to config the policy on 2 APIs created and when I validate the jwt there is no confusion between. The jwt of an api is always valid by the same private and public key

Would you have more element to give ? like an export of an api with the problem ? or maybe I'm not doing the right reproduction scenario? 

I used version 3.15.14 of api management and 1.5 of jwt generate policy
