### ISSUE TITLE
[portal] Access to http dump through Log menu

### ISSUE THREAD

**Issue by lusoalex** [gravitee-io/issues#788]
Hello,

For some support diagnostic, we need sometimes to enable the "Dump http request" option.

In order to ease support/run actions, it would be great to be able to access to the http dump directly through the Portal logs menu instead of having to browse every instance logs folder.

Regards,
Alexandre.

**Comment by brasseld** [comment]
For this feature, we are proposing to add a new `log` section in gateway configuration to enable HTTP dump. Dump can be activated on different way:
* Between consumer and API gateway
* Between API Gateway and backend services
* Both
* None

Also, a good thing would be to be able to enable / disable dump without having to redeploy the API...
