### ISSUE TITLE
500 error when accessing user api details in organization settings category issue on JDBC 

### ISSUE THREAD

**Issue by Okhelifi** [gravitee-io/issues#7882]
Description

Here is a fix on the api search mehod. This issue happens when you try to access the user details in the organization settings for example. The query is conditioned by the inclusion or exclusion of the categories for a performance purpose. However the row mapper always tries to access to the column category. Doing rs.getString("category") will always throw an exception on all relational databases. To avoid it we check the inclusion of the categories and adapt the child adder lambda.

Here we add a missing unit tests too that reveal that with mongo we return all fields we we don't include the categories.

The commit 6c3d791 is a "partial cherry pick" from master to improve repository test time.

### Expected Behavior
Api list should be displayed when the admin access the user details in the organisation settings

### Current Behavior
Infinite loading on the api card + error on the browser network ( or on the backend logs if you can access it )

### Steps to Reproduce (for bugs)
Run APIM with jdbc and access the user details in the organisation settings.

### Your Environment
* Version used: 3.15.9

**Comment by mouligno** [comment]
Tested with @Okhelifi LGTUs
