### ISSUE TITLE
Interrupt policy

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#7883]
Interrupt policy can be used to break the entire request processing in case of a condition (to define on the policy. By default, if no policy condition is defined, the policy will always break request processing).

Breaking the request processing means that no more policy will be executed and no endpoint will be called by the gateway.

By default, the policy will return a response payload to the consumer which is containing the message (see the configuration section).

If you want to override this standard response from the policy, you can define an errorKey which will be then be used to define a Response Template.

TODO:

- [x] Create the policy
- [ ] Add in the default bundle of APIM for versions: [TO COMPLETE] (release.json & pom.xml of distribution)

**Comment by mouligno** [comment]
This policy is not compatible with 3.10.x since conditional policies came with 3.15+, right ?
