### ISSUE TITLE
Unable to add JsonToXml policy into a Flow

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#7887]
## :collision: Describe the bug
I'm trying to add the JsonTo Xml policy into a flow but the save button never appears. If I try to add another policy it works but JsonToXml does not.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Just try to add the JsonToXml policy, won't work
2. Try with another policy, it works

## :movie_camera: Useful information

https://user-images.githubusercontent.com/5955401/175254889-ee1405d1-88e1-4154-a770-41ee9d390e20.mov

## :computer: Desktop:

***Please complete the following information:***
 - Environment:  latest master (3.19.0-SNAPSHOT)
 - OS:  macos
 - Browser chrome

**Comment by gaetanmaisse** [comment]
Closing as it has been fixed

https://user-images.githubusercontent.com/4112568/191825671-096bfa1b-c536-4bbb-8f6c-fe136ce8b837.mp4
