### ISSUE TITLE
[console] Subscription pull-down menu displays APIs the user doesn't have access to 

### ISSUE THREAD

**Issue by ctschacher** [gravitee-io/issues#7890]
## :collision: Describe the bug
When a user wants to subscribe his application to a API plan the pull-down menu that shows all available APIs can also contain APIs that the user doesn't have access to (but are listed on the Portal) which leads to the user being kicked out of the application/subscription configuration section and forwarded to the dashboard homepage

![Screenshot 2022-06-23 at 16.20.29.png](https://images.zenhubusercontent.com/6109168564d750632be5206b/0a50598b-b16d-4593-aa12-e3d073c7171c)

Response (seen in dev tools) when user clicks on API owned by admin:
```
{
  "message" : "You do not have sufficient rights to access this resource",
  "technicalCode" : "forbidden",
  "http_status" : 403
}
```

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Login as a non-admin user
2. Click on 'Applications'
3. Click on 'Subscribe to APIs'
4. Choose an API from the pull-down menu that belong to admin

## :rainbow: Expected behaviour
The user shouldn't see any APIs he doesn't have access to. And/or he should be able to go on normally, without being kicked out.

## Current behaviour
The user is being kicked out of the application/subscription configuration section and forwarded to the dashboard homepage

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.18
 - OS: MacOS 12.3.1
 - Browser Chrome 102

## :warning: Potential impacts
***What are the impacted versions?***
So far only tested on 3.17 & 3.18, both show the described behaviour.

**Comment by marcambier** [comment]
This behavior is reproducable since 3.10

**Comment by RubenMMSantos** [comment]
issue verified and confirmed has fixed
verified on envir 3-10-x
