### ISSUE TITLE
[Expression Language] Support Inline lists

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#7894]
## :collision: Describe the bug

We are not able to use a list in an EL.

## :sunrise_over_mountains: To Reproduce

Let's say we want to use this EL: `{ #request.headers.containsAllKeys({'X-Gravitee-Endpoint', 'X-Gravitee-Other'}) }`

It will not work with the error:
`Expression [{ #request.headers.containsAllKeys({‘{’}‘X-Gravitee-Endpoint’, 'X-Gravitee-Other'}) }] @61: Found closing ‘}’ at position 61 but most recent opening is ‘(’ at position 34`

It's due to this regex https://github.com/gravitee-io/gravitee-expression-language/blob/9dc3004d56bf748b329c8ccabb757d366bc382f8/src/main/java/io/gravitee/el/spel/SpelTemplateEngine.java#L38

## :rainbow: Expected behaviour
We should be able to use list

## :movie_camera: Useful information
If fxed, update [EL whitelist](https://github.com/gravitee-io/gravitee-expression-language/blob/1.9.x/src/main/resources/whitelist#L77) to authorize: `method io.gravitee.common.util.MultiValueMap containsAllKeys java.util.List`

**Comment by gaetanmaisse** [comment]
Tested on 3.18.x env, working as expected ✅ 
![image](https://user-images.githubusercontent.com/4112568/190437487-87cc95e8-c8ca-4384-887e-e9896d0395a4.png)
