### ISSUE TITLE
Portal-> Admin cannot add members to an application 

### ISSUE THREAD

**Issue by LiliaEn** [gravitee-io/issues#7895]
Admin cannot add members to an application 

### Expected Behavior
Admin should be able to add new members to an application from Portal

### Current Behavior
Admin cannot add members to an application from portal. There is no option to do that. (Please note that this is not reproducible on master or other older versions)
![Screenshot 2022-06-24 at 09.17.12.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/164ed9fe-66dc-4b18-8808-daff9be8da4c)

### Steps to Reproduce (for bugs)
1. Login to Portal as an admin
2. Select an existing app
3. Go to Members
4. Try to add new members

### Your Environment
* Version used: 3-18-x env
* Browser Name and version: Chrome Version 99.0.4844.74
* Operating System and version: macOS Big Sur v11.6

**Comment by phiz71** [comment]
@LiliaEn it seems that the environment was not well configured. I did some changes. Could you retry ?

**Comment by LiliaEn** [comment]
@phiz71 I just retested again and it works fine. Thanks

**Comment by LiliaEn** [comment]
Tested 3.18.x env
Browser: Chrome Version 99.0.4844.74 , macOS Big Sur v11.6
Working fine after fixing the environment configuration issue.
