### ISSUE TITLE
Portal->Admin cannot transfer ownership of an app

### ISSUE THREAD

**Issue by LiliaEn** [gravitee-io/issues#7896]
Admin cannot transfer ownership of an app

### Expected Behavior
Admin should be able to transfer ownership of an app

### Current Behavior
There is no option to transfer ownership of an app. Please note that this is not reproducible on master or older versions
![Screenshot 2022-06-24 at 09.17.12.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/7252351f-4429-4a98-9310-5c803e5a4f96)

### Steps to Reproduce (for bugs)
1. Login to Portal as an admin
2. Select an app
3.Go to Members
4. Try to Transfer Ownership

### Your Environment
* Version used: 3-18-x env
* Browser Name and version: Chrome Version 99.0.4844.74
* Operating System and version: macOS Big Sur v11.6

**Comment by phiz71** [comment]
I think it's the same root cause as #7895

**Comment by LiliaEn** [comment]
Tested 3.18.x env
Browser: Chrome Version 99.0.4844.74 , macOS Big Sur v11.6
Working fine after fixing the environment configuration issue.
