### ISSUE TITLE
Semantic release - versioning improvement

### ISSUE THREAD

**Issue by ppgravitee** [gravitee-io/issues#7897]
In order to provide a better developer experience when working on APIM monorepo and policies at the same time, we should update the CircleCI orb to:

1. Remove the automatic generation of a new version when building a PR if the version has been updated manually 
   - We should trust the version set in the pom.xml
2. Add a control to check the version is following a defined pattern if it has been updated manually in the pom.xml
3. Create a git hook to automagically update the version in a pom of a policy when switching branch
   - To discuss and check to be sure there is no unwanted side effect
4. Replace the `mvn upgrade-version` by a manual `sed`
   - The goal here is to speed up the process and avoid issue when new modules are added

**Comment by gaetanmaisse** [comment]
Tested in https://github.com/gravitee-io/gravitee-policy-citest/pull/34 with: 
 - ✅ A custom version that doesn't match the one computed by semantic release, build is ko
 - ✅ A custom version that matches the one computed by semantic release, build is ok, a version is published
 - ✅ No change on the version, build is ok, a version is published with a version computed by semantic release
