### ISSUE TITLE
[repository] [redis] Add support for Redis Sentinel

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#79]
_From @brasseld on February 22, 2016 20:35_

See http://redis.io/topics/sentinel

_Copied from original issue: gravitee-io/gravitee-repository-redis#1_

**Comment by vlemaitre** [comment]
Hi,

I am working to add the support of Redis Sentinel.
There are few differences with Redis repository plugin.

What do you advise for the implementation ?
- Keep 1 redis plugin with the possibility to support  sentinel
- create a new "redis-sentinel" plugin

**Comment by brasseld** [comment]
Hi @vlemaitre 

I would be prefer to provide a single redis plugin with sentinel support if possible.

Thanks a lot

**Comment by vlemaitre** [comment]
OK
The implementation is ok.
It works.
But now I am facing issues to provide both tests for Redis Server and Redis Sentinel Cluster...

I am going to submit a pull request today even if all tests are not completed.
I will finish the work next year ;-)

**Comment by brasseld** [comment]
No worry,

Please push your code and I will have a first look.

**Comment by vlemaitre** [comment]
Done here : https://github.com/gravitee-io/gravitee-repository-redis/pull/58

**Comment by brasseld** [comment]
Sounds good to me.

So, if I understand well, the problem is now about the way to test the redis connector with sentinel support, right ?

**Comment by vlemaitre** [comment]
Yes exactly.
I am trying to start a RedisSentinel into test configuration...
Hope to have the time before leaving this afternoon ;-)

**Comment by brasseld** [comment]
Afternoon is ended at 8.P.M, no ? :-P

I'm sure you will have time ;)

**Comment by vlemaitre** [comment]
Not today. I have to leave early :-D

**Comment by brasseld** [comment]
So take your bag and your laptop, go out, and return home :)

Will see that point next year !

Enjoy your holidays / family !

**Comment by vlemaitre** [comment]
Thanks you too.

**Comment by vlemaitre** [comment]
Happy new year David !
I have updated my pull request regarding test configuration.
2 problems remain : 
* for Redis Sentinel configuration, it works only if the Sentinel server is started before RedisConnectionFactory is called. I don't know how to manage this... any ideas ?
* how to run tests on the 2 configurations (Redis and Redis Sentinel) at each execution ?

**Comment by brasseld** [comment]
Hi @vlemaitre !

Thanks a lot ! Al the best ! Hope you had a nice time during holidays.

About the first point, I have to take a look.
About the second, I think a good option would be to do as it is done for JDBC connector: https://github.com/gravitee-io/gravitee-repository-jdbc/blob/master/pom.xml#L210

So, create two executions, with two different properties file.

WDYT ?

**Comment by vlemaitre** [comment]
I think this is the right solution. I have just updated in this way.

The repository connection method (redis or sentinel) depends on the content of repository.properties.
So we need a method to to switch/update the content of repository.properties from the test execution configuration plugin. 

And I am not able to find how to do this for the moment...

**Comment by brasseld** [comment]
Ok I got you.

Will see how we can handle multiple properties file per execution test.

**Comment by brasseld** [comment]
Hi @vlemaitre 

How is it going here ?

Were you able to run properly all the tests (simple redis / sentinel)?

**Comment by vlemaitre** [comment]
Hi @brasseld 

Yes I am able to run the tests but not both redis and redis sentinel in the same execution.
I need to switch the property file to select the test configuration.

I didn't get time to look for a solution to run all the tests in the same execution.

**Comment by brasseld** [comment]
ok no worries.

thanks for your feedback.

**Comment by cboitel** [comment]
Any update on this one ? Is sentinel now officially supported ? Looks like not.

**Comment by cpuydebois** [comment]
Hi,

given that this issue seems stucked for a little while, I allowed myself to make a new PR to deal with this subject, knowing that we will need to be able to use REDIS in HA (therefore behind a Sentinel stack).

gravitee-io/gravitee-repository-redis#100

It seems that the unit tests have been removed since the initial PR (anyway, Redis Embeded does not seem maintained anymore ...)

Awaiting your feedback.
Thanks

**Comment by cpuydebois** [comment]
ping @brasseld
