### ISSUE TITLE
[console] User should not be able to access Application Analytics page

### ISSUE THREAD

**Issue by ctschacher** [gravitee-io/issues#7901]
## :collision: Describe the bug
A normal user shouldn't have access to the Application Analytics page but that link to _Analytics_ is visible and clickable. It will even start to show the page shortly (with analytics data) before a permission problem is displayed and the user is redirected to the home page.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Log in as a user & go to 'Applications'
2. Click one one of them
3. Click on 'Analytics'

## :rainbow: Expected behaviour
If user doesn't have any access to Analytics then that link should maybe not be available to him at all.

## Current behaviour
Shortly displaying Analytics page

## :movie_camera: Useful information
https://images.zenhubusercontent.com/61280156/29db6347-68e5-49aa-95a3-d294c88bbd47/screen_rec_analytics_page_shortly_displayed.mov

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.18
 - OS: MacOS 12.3.1
 - Browser Chrome 102

**Comment by mouligno** [comment]
not sure i can reproduce. I've tested with api1 and application1. Any more info @ctschacher  ?

**Comment by RubenMMSantos** [comment]
Also tried to reproduce and worked fine for me
