### ISSUE TITLE
[policy][cache] strange behaviour when policy cache TTL is higher than resource cache TTL

### ISSUE THREAD

**Issue by a-cordier** [gravitee-io/issues#7907]
## :collision: Describe the bug

With a TTL set to 600 s (default) at the policy level and a TTL set to 5 s at the resource level, cache is not applied at all.

Is this an expected behaviour ?

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Define a cache resource with TTL set to 5 s and IDLE to 0
2. Set up an API with a cache policy (scope API, plan keyless) with the default TTL (600 s)
3. Call e.g. http://worldtimeapi.org/api/timezone/Europe/Paris to check is the cache is applied
4. It is not

## :rainbow: Expected behaviour

🤷‍♂️ Should the resource TTL apply instead of bypassing the cache ?

## Current behaviour

The cache is bypassed

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material
<img width="1310" alt="Screenshot 2022-06-24 at 15 19 16" src="https://user-images.githubusercontent.com/3619261/175545176-f4f5b731-38d7-46ce-9e99-233517ac886c.png">
<img width="1545" alt="Screenshot 2022-06-24 at 15 19 38" src="https://user-images.githubusercontent.com/3619261/175545190-ca55f8ca-ede8-4ddf-9e58-022cd8fbde5c.png">

**Comment by LiliaEn** [comment]
Tested on 3.15.x
Browser: Chrome Version 103.0.5060.53 , macOS Big Sur v11.6
Caching works as expected.
Policy TTL is used when it is lower than the resource TTL
Resource TTL is used when the policy TTL is higher than the resource
