### ISSUE TITLE
[management] Unable to use prefix for mongodb collections when running with Java 17

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#7918]
## :collision: Describe the bug
When we enabled prefix in our gravitee.yml file or via environmental variable on Management API, mongodb is unable to start properly. This is happening on a fresh installation as well as on an installation that we upgrade to from a version in which the prefix was enabled and okay.

Few ways I have tested this in the impacted version and in none it does not seem to work:

1. Run a fresh installation of one of the non working version, pull the gravitee.yml file, configure the prefix, push the gravitee.yml file to management api container, re start the container the the error.
2. Create a volume mount to the config file so it copies and runs at the same time when you use the docker-compose up command. You will see the error immediately. 
3. Create a env. variable named management_mongodb_prefix=dev_ run the docker compose and you will se the error.
4. Run a fresh installation of one of the non working version, pull the gravitee.yml file, configure the prefix, push the gravitee.yml file to management api container, clean out all the collections , re start the container, see the error.
5. Run a fresh installation of one of the non working version, pull the gravitee.yml file, configure the prefix, push the gravitee.yml file to management api container, run the script for the collections 

## :sunrise_over_mountains: To Reproduce

So you can undeestand please test in 3.10.11 and 3.15.3 to compare or 3.10.11 and any other 3.15, 3.16 or 3.17 version.
In the docker-compose file you have two comments for apim management, one for correct mounting one for and env variable, if you want to test.

NOTE!!!! If you are using the same files and folder and just changing the version in the .env file pleas do not forget to delete the volumes for elastic and mongo...`docker volume remove <volume/s name>`

1. (3.10.11) Run the docker-compose bellow, push the grvaitee.yml file(find bello), re-start the container.
2. You will not see an issue.
3. Do the same steps from 1. in for example 3.15.3
4. After you have re-started the container with now configured grvaitee.yml file you will see some expectations in the logs when it comes to the mongodb

## :rainbow: Expected behavior
We should be able to have a custom prefix and configure it without an issue.

## :movie_camera: Useful information
Screen shot, video, logs, other supporting material
[testcase.zip](https://github.com/gravitee-io/issues/files/8993301/testcase.zip)

## :computer: Desktop:

***Please complete the following information:***
 - Environment: Docker-Desktop
 - OS: Windows 11
 - Browser: Google Chrome

## :warning: Potential impacts:

***What are the impacted versions?***
- 3.15.X, 3.16.X and 3.17.X

**Comment by gaetanmaisse** [comment]
_Note_: Issue is present when using a JRE 17 and not JRE 11

**Comment by gaetanmaisse** [comment]
Maybe it needs to be tested in pair with QA+Dev because the `prefix` option isn't used on our dev envs.

To test locally: 
  - Use a JRE 17
  - Run APIM
  - Everything should be ok, on the UI + no error logs

It might be tested with a docker-compose using `3.15-latest` tag

**Comment by LiliaEn** [comment]
Tested locally by @phiz71
