### ISSUE TITLE
[console] API Publisher can't see any API events

### ISSUE THREAD

**Issue by ctschacher** [gravitee-io/issues#7922]
## :collision: Describe the bug
API Publisher can't see any API events on the Home Dashboard. As user api1, I've created an API, started and stopped it again but none of these actions appear in the API Events section of the Home Board. When I log in as admin I can see those events.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. As api1 user go to 'APIs' and create some events (e.g. stop, start API)
2. Click on 'Dashboard'
3. Make sure the time range covers the time you made these actions mention above
4. Check section 'API Events'

## :rainbow: Expected behaviour
I would expect to see some events showing up in that section after API has been modified

## Current behaviour
No events are shown ("No Data to display here")

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.18
 - OS: MacOs 12.3.1
 - Browser Chrome 102

## :warning: Potential impacts
***What are the impacted versions?***
So far only tested with 3.17.3 & 3.18, both show that behaviour

**Comment by mouligno** [comment]
I've reproduced in 3.10
