### ISSUE TITLE
[helm] "labels" can not be used/set when enabling Prometheus metrics

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#7927]
## :collision: Describe the bug
When enabling Promeheus metrics with Helm Charts, it is not possible to use/set the labels.
https://github.com/gravitee-io/helm-charts/blob/c150d1755a6b9e5b9a373925d62ab0d82b401525/apim/3.x/templates/api/api-configmap.yaml#L142

## :rainbow: Expected behaviour
be able to use/set "labels" with Gravitee Helm Charts as documented :
https://docs.gravitee.io/apim/3.x/apim_installguide_rest_apis_metrics.html

***Please complete the following information:***
 - Environment: [e.g. 3.10.x]

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by gaetanmaisse** [comment]
I've got some exciting news to share - we've finally squashed that pesky bug that's been bugging you! 🎉 
The fix is included in the latest version of the APIM Helm Chart (v3.1.62), so you can finally take a breather and let your API do the heavy lifting.
