### ISSUE TITLE
[console] Can't import from file after error in previous attempt due to importing malformed API definition 

### ISSUE THREAD

**Issue by ctschacher** [gravitee-io/issues#7934]
## :collision: Describe the bug
When I try to import an API definition from a file that is malformed (invalid JSON) then it's not possible to choose another file (valid JSON) to import an API. The only way to provide a valid file in this case is to cancel and enter the import API mode again.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to 'API'
2. Click on '+' (add new API)
3. Click on 'Import an API'
4. Click on 'Choose file'
5. Choose a file first that doesn't contain valid JSON (-> Error:  "Input file must be a valid API definition file")
6. Choose another file with valid JSON
7. Click on 'Import'

## :rainbow: Expected behaviour
The valid file should be imported successfully.

## Current behaviour
The 'Import' button seems clickable but after pressing it doesn't trigger any action and there's also no error message in the GUI or console.

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.18
 - OS: MacOS 12.3.1
 - Browser Chrome 103

## :warning: Potential impacts
***What are the impacted versions?***
So far I've tried with 3.18 and 3.17.3, both showed the described behaviour.

**Comment by gaetanmaisse** [comment]
Closing as it will be handled when building the new API creation workflow
