### ISSUE TITLE
[Task] Generate the e2e sdk in CI ?

### ISSUE THREAD

**Issue by a-cordier** [gravitee-io/issues#7941]
### 📝 Description

Should we run the e2e sdk generation script in CI ?

When ?

  - on a release ?
  - when merging on master ?

**Comment by gaetanmaisse** [comment]
Maybe we should regenerate the SDK in the PR workflow and fail the CI (or add a comment) if there are some uncommitted changes.

**Comment by marcambier** [comment]
This has been replaced with https://github.com/gravitee-io/issues/issues/8374
