### ISSUE TITLE
[Gateway] [MFA] Step Up force challenge during login

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#7945]
When a user login with a known device and if the StepUp rule is true, the MFA challenge is prompted.

### Expected Behavior

The user is signing in and have a known device (remember device checked during last auth and still active).
As the stepup is to protected on already authenticated call the challenge shouldn't be triggered

### Current Behavior

The challenge is triggered

### Steps to Reproduce (for bugs)

1. User using FIDO2 Factor
2. MFA Settings : 
![image.png](https://images.zenhubusercontent.com/6026363e864bfc6af2b3aa2c/3e0b6bf5-e80d-4a40-859a-daa4244d2a3e)
3. Authenticate user (without the active parameter)
4. on the MFA challenge check 'remember device'
5. logout the user
3. Authenticate user with the active parameter set to true
4. The MFA Challenge is prompted

**Comment by leleueri** [comment]
Other wrong behaviour:

- Adaptive MFA / Conditional  set to false
- no remember device
- no step rule defined

When the user logged in ==> challenge is prompt :heavy_check_mark: 
When the user has an active session, a call to the authorize endpoint prompt the challenge :x: (No expected as the step up isn't configured)

**Comment by remisultan** [comment]
> When the user has an active session, a call to the authorize endpoint prompt the challenge ❌ (No expected as the step up isn't configured)

It is expected since Adaptive MFA returns false and is evaluated every time (unlike Step up Auth where it is only when the user is strongly authenticated)? 🤔

Let's talk about it

**Comment by patelami** [comment]
env: 3.18
result: PASS
