### ISSUE TITLE
Alerts-> Alert when the health status of an endpoint has changed cannot be triggered at the platform level

### ISSUE THREAD

**Issue by LiliaEn** [gravitee-io/issues#7948]
Alert when the health status of an endpoint has changed cannot be triggered at the platform level

### Expected Behavior
"Alert when the health status of an endpoint has changed" should be triggered at the platform level

### Current Behavior
"Alert when the health status of an endpoint has changed" cannot be triggered at the platform level
![Screenshot 2022-06-30 at 13.49.15.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/d9790737-e250-44cd-b51a-11ccaa372136)

**Please note that this alert at the API level is working fine.
![Screenshot 2022-06-30 at 13.49.37.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/9b0aba1b-6097-4ef4-ac9e-6280bf2922d3)

### Steps to Reproduce (for bugs)
1. Login to APIM as an admin
2. Go to Settings-> Alerts 
3. Add a new alert with this rule: Alert when the health status of an endpoint has changed 
4. Save it
5. Create API 1 with the BE of API2
6. Configure API1 Healthcheck (make sure the status is green)
7. Stop API2 (Healthcheck of API 1 should show red status
8. Check if the Alert was triggered

### Your Environment
* Version used: 3.18.0
* Browser Name and version: Chrome Version 99.0.4844.74
* Operating System and version: macOS Big Sur v11.6

**Comment by mouligno** [comment]
The alert is triggered at API level which make sense since an alert set on API at environment level is a template shared with all APIs.
