### ISSUE TITLE
[Gateway] Ignore FIDO2 factor challenge when user authenticated using WebAuthn

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#7951]
As a EndUser authenticated using WebAuthn/Passwordless, 
If I have FIDO2 actor enrolled and active on the APP, 
then I don't have to prompt MFA challenge (even if I have multiple factors)

### Current Behavior

Because the user have multiple factors, the challenge is prompted

### Steps to Reproduce (for bugs)
1. Enroll two factor for a user (OTP and FIDO2)
2. Signin using Passwordless
3. the mfa challenge is prompted

**Comment by patelami** [comment]
env: 3.18
Result: PASS
