### ISSUE TITLE
[helm] not able to set api.properties.encryption.secret

### ISSUE THREAD

**Issue by JulienFauvel** [gravitee-io/issues#7955]
## :collision: Describe the bug

Not being able to set the encryption secret in the current Helm chart

## :rainbow: Expected behaviour

Being able to customize it. Like the JWT Secret in the current helm chart or through a Kubernetes secret

**Comment by gaetanmaisse** [comment]
I've got some exciting news to share - we've finally squashed that pesky bug that's been bugging you! 🎉 
The fix is included in the latest version of the APIM Helm Chart (v3.1.62), so you can finally take a breather and let your API do the heavy lifting.
