### ISSUE TITLE
[management][mfa] display OPTIONAL when a new app is created

### ISSUE THREAD

**Issue by remisultan** [gravitee-io/issues#7969]
## :collision: Describe the bug
When creating a new application and wanting to activate MFA, the first option shown after choosing a factor is `Conditional` when the first available is `Optional`.

<img width="959" alt="image" src="https://user-images.githubusercontent.com/8531515/177161848-4d4b49e5-43f6-4066-8bd9-26873ebf4ee0.png">

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Create An Application
2. Create a Factor
3. Go to your application MFA settings 
4. Select a factor
5. Notice the option chosen is `Conditional`

## :rainbow: Expected behaviour
The first option shown after choosing a factor in application should be `Optional`

## Current behaviour
The first option shown after choosing a factor in application should be `Conditional`

**Comment by patelami** [comment]
Env:3.18
Result: PASS
