### ISSUE TITLE
[Gateway] Factor can't be registered if device is already known

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#7971]
MFA challenge skip during Factor enrollment when the Device is known.

### Expected Behavior

During an enrollment, the challenge have to be prompt even if the device is already known in order to confirm the registration.

### Current Behavior

During an enrollment, the challenge is skipped because the device is already known and the factor registration isn't finalized

### Steps to Reproduce (for bugs)
1. Create a domain with OTP factor
2. Create an instance of FingerPrint plugins
3. create an app with OTP enabled as factor and the remember device toggle active (for 10 minutes to have time to do the use case)
4. create a fresh new user
5. authenticate this user
6. register the OTP factor (select remember device) and provide challenge code
7. logout the user
8. in the Management UI, check that the user have an actice device id
9. go the factor tab linked to the user and remove the OTP factor
10.authenticate this user
11. Flash ther OTP QRCode and click verify
12. the challenge is skipped and the factor isn't linked to the user profile

**Comment by patelami** [comment]
Env: 3.17.x
Result: PASS
