### ISSUE TITLE
[APIM-PostgreSQL] Quota and RateLimit Platform Policies do not as expected. X-Quota-Reset header returns -1.

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#7975]
## :collision: Describe the bug
If we configure Quota or RateLimit Platform Policies they simply do not work and if we go to the response header the X-Quota-Reset header returns -1, meaning the policies are not being executed. This issue is only if we use PostgreSQL as our DB instead of mongoDB. 

## :sunrise_over_mountains: To Reproduce
1. Unzip the zip file bellow, start up the docker-compose file.
2. Create a simple Echo API and go to the Organization Settings so create a Platform Policy
3. Configure Quota or Rate Limit and test in Postman.
4. You will see that after you have reached the limit you will not get any error, meaning the policies did not get executed and in Response Headers the X-Quota-Reset header returns -1.

![image](https://user-images.githubusercontent.com/57534152/177328885-39e10486-91e5-4069-b7b5-d25ecef099c2.png)

## :rainbow: Expected behavior
The expectation is the normal behavior like we have with the MongoDB or if we configure the same policies on API lvl which they work as they should.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

[Postgresql 3.15.9.zip](https://github.com/gravitee-io/issues/files/9046334/Postgresql.3.15.9.zip)

## :computer: Desktop:

***Please complete the following information:***
 - Environment:  3.15.11 and 9 on Docker-Desktop
 - OS: Windows 11
 - Browser: Google Chrome

## :warning: Potential impacts

***What are the impacted versions?***
- 3.15.9, 3.15.11

**Comment by RubenMMSantos** [comment]
Issue verified and confirmed as fixed.
Both Quota & Rate Limit policies work as expected when applied at Platform level.
User can see "successful" error messages when the conditions specified to trigger the policies are meet
