### ISSUE TITLE
[GKO] Create API using CRD on M-API

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7980]
## :rainbow: Feature

As a user, I want to create an API in M-API using a valid CRD (syntax and matching existing model) in order to manage my APIs using K8.

## :sunrise_over_mountains: Additional information

- [x] Define CRD Template for API, yaml version of api_def ? 
- [x] Transform CRD to config_map containing api_definition
- [x] Gateway listen through config_map to sync api_defintion 
- [x] Need to provide ManagementContext (#7982 ) (Not mandatory in case of GKO + gateway only - #8136)
- [x] GKO publish api_def to APIM Management

## Out of scope 

- Validation is not part of this issue ( #8135)
- ReadOnly in Console/M-API is not part of this issue (#8141 )

## :superhero: Acceptance criteria

- [x] Given a valid CRD Then my API is created When GKO read it
- [x] Given a valid CRD then my API is accessible in the M-API and get the `read_only` value in it  when created with GKO
- [x] Given a valid CRD then there is no event sent to the gateway when created with GKO / M-API
- [x] Given a not valid CRD (syntax error) then an error is logged for config_map generation

## Documentation

- [x] What is an API CRD ? 
- [x] Relation between API CRD and ManagementContext CRD ?
- [x] How to create and API using CRD ?

**Comment by RubenMMSantos** [comment]
All acceptance criteria validated and behaviour working as expected.
