### ISSUE TITLE
[GKO] Update an API using CRD

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7981]
## :rainbow: Feature

As a user, I want to update an API in M-API using a valid CRD (syntax and matching existing model) in order to manage my APIs using K8.

## :sunrise_over_mountains: Additional information

- [ ] Should rely on Create behavior (#7980)
- [ ] Sync only if there is changes in CRD 
- [ ] Update API using M-API
- [ ] Events & revision number are part of config_map
- [ ] Update only CRD Managed APIs
  - [ ] If a CRD API match an existing API in M-API (not managed by CRD) it shouldn't get updated and raise warning.( #8138 )

## :link: Dependencies

Link to #7980 

## :superhero: Acceptance criteria

- [x] Given an existing API managed via CRD, Then the API get properly updated in M-API when i push an updated version CRD
- [x] Given an existing API managed via M-API, Then the API is not updated and I got a warning in GKO When i tried to update it with CRD

## Documentation

- [x] How to update an API ? 
- [x] How the update sync works ?

**Comment by RubenMMSantos** [comment]
Feature verified:
- [ ] API is properly updated
- [ ] API only gets updated when there are changes
- [ ] CRD API match an existing API in M-API (not managed by CRD) then it does not get updated and a warning message can be seen

![Screenshot 2022-08-08 at 13 44 03](https://user-images.githubusercontent.com/14939456/183420863-411338c7-a85a-4c8b-bb63-721eaa379b4c.png)
