### ISSUE TITLE
[Jupiter] RxJava3

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7990]
## :rainbow: Feature

As a developer, I want to upgrade RxJava to version 3

## :sunrise_over_mountains: Additional information

Need to check if supported by our Vertx version first
also upgrade policies already migrated to RxJava

## :warning: Current progress

| Component | Dev | Review | Merge | Version |
|-----|:--------:|:---------:|:---:|-----|
| gravitee-bom  | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | 2.7 |
| gravitee-common-elasticsearch  | :heavy_check_mark: | ✔️  | ✔️ | 4.0.0-alpha.1 |
| gravitee-kubernetes  | :heavy_check_mark: | :heavy_check_mark: | ✔️  | 1.0.0-alpha.1 |
| gravitee-node  | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | 2.0.0-alpha.3 |
| gravitee-expression-language  | :heavy_check_mark: | ✔️   | ✔️ | 2.0.0-alpha.2 |
| gravitee-gateway-api | :heavy_check_mark: |      ✔️    | ✔️ | 2.0.0-alpha.1 |
| gravitee-cockpit-api | :heavy_check_mark: |   ✔️       | ✔️  | 2.0.0-alpha.1 |
| gravitee-api-management  | :heavy_check_mark: |   ✔️       | ✔️ | 3.20.0-SNAPSHOT |
| gravitee-policy-ratelimit  | :heavy_check_mark: |    ✔️      | ✔️ | 2.0.0-alpha.1 |
| gravitee-policy-jwt  | :heavy_check_mark: |   ✔️  | ✔️ | 3.0.0-alpha.1 |
| gravitee-reporter-elasticsearch  | :heavy_check_mark: |   ✔️  | ✔️ | 4.0.0-alpha.1 |
| gravitee-endpoint-kafka-advanced  | ✔️ | ✔️ | ✔️ | 1.0.0-alpha.2 |
| gravitee-entrypoint-sse-advanced  | ✔️ | ✔️ | ✔️ | 2.0.0-alpha.2 |
| gravitee-commons  | :heavy_check_mark: |     ✔️     |  ✔️ | 2.0.0-alpha.1 |
| gravitee-ae-connectors  | ✔️ | ✔️ | ✔️ | 2.0.0-rxjava2-to-rxjava3-SNAPSHOT |
| gravitee-policy-keyless  | ✔️ | ✔️ | ✔️ | 2.0.0-alpha.1 | 
| gravitee-policy-oauth2  | ✔️ | ✔️ | ✔️ | 2.0.0-alpha.1 |
| gravitee-policy-apikey  | :heavy_check_mark: |   ✔️  | ✔️ | 3.0.0-alpha.1 |
| gravitee-policy-json-xml | ✔️ | ✔️ | ✔️ | 2.0.0-alpha.1 |
| gravitee-cockpit-connectors  | :heavy_check_mark: |   ✔️  | ✔️ | 3.0.0-alpha.2 |

**Comment by marcambier** [comment]
The package migration command, using sed :
```
for file in `find . -iname "*.java"`; do
        sed -i "s/io\.reactivex\.schedulers\./io\.reactivex\.rxjava3\.schedulers\./g" $file
        sed -i "s/io\.reactivex\.disposables\./io\.reactivex\.rxjava3\.disposables\./g" $file
        sed -i "s/io\.reactivex\.functions\./io\.reactivex\.rxjava3\.functions\./g" $file
        sed -i "s/io\.reactivex\.observers\./io\.reactivex\.rxjava3\.observers\./g" $file
        sed -i "s/io\.reactivex\.Maybe/io\.reactivex\.rxjava3\.core\.Maybe/g" $file
        sed -i "s/io\.reactivex\.Single/io\.reactivex\.rxjava3\.core\.Single/g" $file
        sed -i "s/io\.reactivex\.Completable/io\.reactivex\.rxjava3\.core\.Completable/g" $file
        sed -i "s/io\.reactivex\.Flowable/io\.reactivex\.rxjava3\.core\.Flowable/g" $file
        sed -i "s/io\.reactivex\.annotations\./io\.reactivex\.rxjava3\.annotations\./g" $file
        sed -i "s/io\.vertx\.lang\.reactivex\./io\.vertx\.lang\.rxjava3\./g" $file
        sed -i "s/io\.reactivex\.\*/io\.reactivex\.rxjava3\.core\.\*/g" $file
done
```

**Comment by ppgravitee** [comment]
We rely on this on cockpit side for our own rxJava update, can you warn us or merge this PR https://github.com/gravitee-io/gravitee-cockpit-connectors/pull/171 when you're done? Thanks

**Comment by Sicofonia** [comment]
Closed in task: https://graviteecommunity.atlassian.net/browse/APIM-95
