### ISSUE TITLE
[Jupiter] Security chain tracing

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7992]
## :rainbow: Feature

As an API Publisher, I want to be able to trace all security chain

## :sunrise_over_mountains: Additional information

- tracing during plan selection
- tracing for security policy 
- Add TracingHook on top of SecurityPolicy execution

## :superhero: Acceptance criteria

- [ ] Given tracing enabled Then I can view what's happened on security chain When i've made a call

**Comment by gcusnieux** [comment]
Hi @mouligno ,
We already have the type of plan selected, I think that's enough for now. What do you think 
![Capture d’écran 2022-07-13 à 16 44 28](https://user-images.githubusercontent.com/1457497/178763010-a251979d-d742-4d8b-95d8-dcde0a247806.png)
?

**Comment by mouligno** [comment]
Good for now
