### ISSUE TITLE
Best_Match flow, how to use it, and exceptions when a conditions are conflicted

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#7999]
<ol> 
 <li> 
  <ol> 
   <li>:collision: Describe the bug<br> The "best match" flows mode will use the flow with the deepest path expression matching the request. </li> 
  </ol> </li> 
</ol> 
<p>For example, if your input request path is "/book/15/chapter/99" :</p> 
<p>flow "/bee/11/**" doesn't match<br> flow "/book/15**" matches<br> flow "/book/15/chapter/**" matches better, because matching path is deeper<br> So, the last one will be used.<br> Path can contains variables or regular expressions, for example, the last flow path could be "/book/:bookId/chapter/**".</p> 
<p>It is not recommended to have multiple path matching with same depth. For example :</p> 
<p>flow "/book/:bookId/**"<br> flow "/book/15/**"<br> In that case, both flows matches best, and gateway will execute both.</p> 
<ol> 
 <li> 
  <ol> 
   <li>:sunrise_over_mountains: To Reproduce<br> Steps to reproduce the behaviour:<br> 1. Have two flows<br> 2. The condition on both to be the same <br> 3. When making a call the condition is true for both flows<br> 4. This is the error: { "message": "Cannot invoke \"java.lang.Float.floatValue()\" because \"selectedFlowScore[i]\" is null", "http_status_code": 500 }</li> 
  </ol> </li> 
</ol> 
<p>When doing a call, sometimes the call is ok and sometimes with the error above. These are the expressions that for each flow:</p> 
<p>/telematics-brands/(?!cloudboxx)<span class="error">[a-z_]</span>+/(vehicle-models|credentials|available-)(.*)<br> /telematics-brands/(?!cloudboxx)<span class="error">[a-z_]</span>+/available-capabilities</p> 
<p>So, when the flows are different, no issue, but when the first one evaluates as the one below, the issue occurs.</p> 
<p>Received an exception, where the error, could not immediately be identified, as it seemed to originate from Java code and did not contain a helpful error message. So maybe an error message describing the underlying problem would be useful in the future.</p> 
<p>Tested in apim 3.15.8<br> Linked with #zd4424</p>

**Comment by mouligno** [comment]
@marcambier isn't the use case we got there in Todo : https://github.com/gravitee-io/issues/issues/6654 ?
