### ISSUE TITLE
[API Definition V4] deploy v4 api definition

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#8009]
## :rainbow: Feature

As an AsyncAPI API Publisher, I want to manage lifecycle states of an api_defintion v4 (Deployed / Started / Stopped)

## :sunrise_over_mountains: Additional information

- [x] Update Synchronizer v4 to deploy API

## :superhero: Acceptance criteria

- [x] Given a valid async api v4 Then i can view it in the log events when i deploy it to the gateway
- [x] Given a valid async api v4 Then i can view the log events when i start/stop it 

## Remaining tasks
Update test sdk to be able to deploy api v4 #8286
Some unit test could also be implemented to at least test new code

**Comment by guillaumelamirand** [comment]
This has been partialy implemented with #8238.

**Comment by LiliaEn** [comment]
Tested on v3.19.0
The following scenarios were covered:
- Create Async API
- Start Async API
- Stop Async API
- Create Keyless plan
- Publish keyless plan
- Deploy Async API
- Checking the log events when each of the above action was done
