### ISSUE TITLE
[Jupiter benchmark] Optimize cache

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#8030]
With Jupiter and the new execution mode, each policy must complete before the next one is executed.

Policy execution now includes the eventual transformation made on the request or response body. To make sure the different transformation are not re-executed during the execution of the reactive chain, we are relying on Maybe.cache() and Flowable.cache(). The caching is then operated by the reactive framework itself and allows to keep the code relatively simple. 

To optimize caching, we’ve already spotted the different places where it requires to applying caching and it works as expected. However, depending on the number of policies and body transformations that may occur during the request execution, this caching mechanism can be memory intensive because each transformation that has been cached is kept until the end of the request execution (not eligible to GC). 

Ex: 

xml2json → json2xml → assign-content → Backend → xml2json → json2xml → assign-content
keeps 3 version of the request body and 3 versions of the response body in memory.

We should find a way to optimize the caching by only keeping the latest useful version of the request or response body and release the other ones as soon as possible (at least make them eligible to the GC).

**Comment by LiliaEn** [comment]
Tested on the default env v3.19.0 
Browser: Chrome Version 103.0.5060.53 , macOS Big Sur v11.6
- Tested using multiple policies that involve a body transformation 
    - Applied conditions on policies using EL
    - Applied a request body when calling in debug mode
    - Enabled logging in response/request
Tests were done with Jupiter mode enabled and also V3+Jupiter using debug mode and Postman.
***** Please note that the testing for this feature is still ongoing, it will also be covered while testing some other upcoming Jupiter features.
