### ISSUE TITLE
[Jupiter benchmark] Define Performance test objectives and task

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#8031]
- Define perf objectives
- Define tooling

**Comment by jhaeyaert** [comment]
We had workshop with the team to define the short term objective (sept.) and produced a list of tasks we could do to reach it: https://docs.google.com/spreadsheets/d/16chghWpYZlJvVLYd21LmLURnZ8L6a9wYjYt9XHc2Ayw/edit?usp=sharing

**Comment by jhaeyaert** [comment]
@Sicofonia Feel free to close it once it's ok for you because on my side this task is ok.

**Comment by Sicofonia** [comment]
This will be tested along with issue #7988 (Reactive Timeout)
