### ISSUE TITLE
The Websocket protocol is not logged

### ISSUE THREAD

**Issue by Sachkov-Aleksandr** [gravitee-io/issues#8033]
Hello. We have installed Gravitee APIM 3.17.3 in Kubernetes. There is a frontend that connects to the backend via the Websocket protocol. Their communication is stable and data is transmitted smoothly through the API gateway, but I don’t see connection data in the Gravitee logs. In the case of HTTP connections, there are no problems.

Steps to reproduce the behaviour:

1.  Run test frontend & backend
2.  Go to Gravitee API console
3.  Go to API gateway's log
4.  See what don’t see connection logs.

Expected behaviour I wanted to see the logs of each established connection and the data on it.

Current behaviour I don’t see connection logs.

Desktop:

*   Environment: K8s 1.23, Gravitee APIM 3.17.3
*   OS: Windows
*   Browser: Google Chrome

**Comment by Sachkov-Aleksandr** [comment]
Hello, colleagues!
Will someone answer me here?

**Comment by mouligno** [comment]
Hi @Sachkov-Aleksandr 

Thanks for reporting us this issue, we're looking forward to investigate it

**Comment by Sachkov-Aleksandr** [comment]
Hi @mouligno 
Please tell me if there are any solutions to my problem?

**Comment by Sachkov-Aleksandr** [comment]
Hi @mouligno
Please tell me if there are any solutions to my problem?

**Comment by mouligno** [comment]
Hi @Sachkov-Aleksandr this is part of our on going backlog. We'll let you know once we got any progress

**Comment by Sachkov-Aleksandr** [comment]
Hi @mouligno
Please tell me if there are any solutions to my problem?

**Comment by gaetanmaisse** [comment]
After some investigation, it looks like connection request logs are available only in case of error.
We might have found the root issue but the fix won't be straightforward. A deeper investigation and some internal discussion will be needed.

**Comment by Sachkov-Aleksandr** [comment]
Hi @gaetanmaisse
Tell me, please. Will the problem be solved only in versions 3.18 or will there be a patch under 3.17?

**Comment by gaetanmaisse** [comment]
3.17 has reached EoL at the end of July so it will be fixed and released in 3.18

**Comment by grignix** [comment]
This problem also exists in gravitee 3.15.x

**Comment by grignix** [comment]
up
