### ISSUE TITLE
[gateway] [multi-languages] manage languages at domain level

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8040]
## :rainbow: Feature

**As a** 'security domain owner'

**I want to** 'use my custom languages for the internationalization of application forms and email templates'

**So that** 'I can activate multi languages for the applications'

## :sunrise_over_mountains: Additional information

- Fetch languages from the database first (at domain level)
- If no language has been defined fallback to the filesystem one

## :link: Dependencies

Link a story or other related things...

## :books: Documentation required

Provide link to the issue for documentation update

## :superhero: Acceptance criteria

- [ ] Given '...' Then '...' When '...'
- [ ] Given '...' Then '...' When '...'
- [ ] Given '...' Then '...' When '...'

- [ ] Jest test for acceptance criteria

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

:rocket:

**Comment by omatthewsgravitee** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Graviteeio---Access-Management-5b17f74af58c642fb89cc49f/issues/gravitee-io/issues/8040?planning-poker) with ZenHub @ashraf706 @audrey-tlm @farmborough @leleueri @patelami @remisultan

**Comment by tcompiegne** [comment]
Duplicate of #8071

**Comment by patelami** [comment]
Env: master
Result: PASS

Given I have added english dictionary 
And added translation for the title in english
And I initiate a login flow
Then I should see the english sign in title

Given I have added french dictionary 
And added translation for the title in french
And I initiate a login flow
Then I should see the french sign in title


**PS:
I can see the line is translated but we do not have enough spacing between two lines.**

<img width="587" alt="Screenshot 2022-08-30 at 12 49 14" src="https://user-images.githubusercontent.com/14215437/187432380-82a42502-9c83-49b4-86ea-5181d256ca6e.png">

**Comment by tcompiegne** [comment]
UI issue report has been referenced here : https://github.com/gravitee-io/issues/issues/8401
 
This issue can be closed.
