### ISSUE TITLE
[gateway] [forms] use the new default theme

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8042]
## :rainbow: Feature

**As a** 'administrator'

**I want to** 'update the current HMTL and Email templates design'

**So that** 'I can improve the overall look and feel of AM'

## :sunrise_over_mountains: Additional information

- All templates MUST be updated
- All templates MUST rely on internationalization

Be sure to use the concept of **CSS custom properties** (CSS variables) : 

https://css-tricks.com/a-complete-guide-to-custom-properties/

```
<html xmlns:th="http://www.thymeleaf.org">
        <head>
            <title>Login custom</title>
            <style>
              :root {
                --primary-color: red;
              }
              button {
                background: var(--primary-color);
              }
            </style>
            <style id="custom-theme" th:text="${domain.theme.css}">
              :root {
                --primary-color: green;
              }
            </style>
        </head>
```

## :link: Dependencies

Link a story or other related things...

## :camera: Mockups 

<img width="720" alt="Capture d’écran 2022-07-06 à 21 06 42" src="https://user-images.githubusercontent.com/1927438/177624518-550749c6-9454-428d-a931-2762b7c915e5.png">

## :books: Documentation required

Provide link to the issue for documentation update

## :superhero: Acceptance criteria

- [ ] Given '...' Then '...' When '...'
- [ ] Given '...' Then '...' When '...'
- [ ] Given '...' Then '...' When '...'

- [ ] Jest test for acceptance criteria

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

:rocket:

**Comment by omatthewsgravitee** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Graviteeio---Access-Management-5b17f74af58c642fb89cc49f/issues/gravitee-io/issues/8042?planning-poker) with ZenHub @ashraf706 @audrey-tlm @farmborough @leleueri @patelami

**Comment by patelami** [comment]
The text on reset password is different compared to figma. Is this final approved version? 

<img width="615" alt="Screenshot 2022-08-15 at 14 51 32" src="https://user-images.githubusercontent.com/14215437/184648162-74c263a0-0699-4a4b-ab48-89c1c1d9cba1.png">

**Comment by patelami** [comment]
When we open the application and login form on mobile phone, it will open in bigger resolution and you have to zoom out to load the correct resolution,

**Comment by ashraf706** [comment]
> The button on password reset is `sent` . We should rename it to `send`.
> 
> <img alt="Screenshot 2022-08-15 at 14 34 14" width="638" src="https://user-images.githubusercontent.com/14215437/184645237-9b2882fe-1167-4a55-97e7-ad741d3ae59a.png">


@patelami , button text updated to "Send" in issues/#8315-display-default-form-mangement-side branch, fyi

**Comment by ashraf706** [comment]
> The text on reset password is different compared to figma. Is this final approved version?
> 
> <img alt="Screenshot 2022-08-15 at 14 51 32" width="615" src="https://user-images.githubusercontent.com/14215437/184648162-74c263a0-0699-4a4b-ab48-89c1c1d9cba1.png">

I think "We have sent.."  is grammatically more accurate than "We sent..." in this context.

**Comment by ashraf706** [comment]
> When we open the application and login form on mobile phone, it will open in bigger resolution and you have to zoom out to load the correct resolution,

We haven't considered different screen size in this feature. Let's reconfirm with @tcompiegne.
