### ISSUE TITLE
[gateway] [emails] use the new default theme

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8043]
## :rainbow: Feature

**As a** 'administrator'

**I want to** 'update the current HMTL and Email templates design'

**So that** 'I can improve the overall look and feel of AM'

## :sunrise_over_mountains: Additional information

- All templates MUST be updated
- All templates MUST rely on internationalization

## :link: Dependencies

Link a story or other related things...

## :camera: Mockups 

[Link to the Figma file](https://www.figma.com/file/PKtV6NcsNzGBuzV3cmGHJj/Custom-login?node-id=1%3A776)

![Capture d’écran 2022-07-22 à 10.49.16.png](https://images.zenhubusercontent.com/61fc4917f078f31c2ae16580/51279951-7af0-4490-9145-556f4a2006f1)

## :books: Documentation required

Provide link to the issue for documentation update

### Confirm Registration

- [ ] Given 'an admin user with rights to create new user in the conosle (domain user)' Then 'a registration email to confirm the user account is sent to the user in french' When 'user is created with the locale 'fr' in additional info and the pre-register toggle is switched on '
- [ ] Given 'an admin user with rights to create new user in the conosle (domain user)' Then 'a registration email to confirm the user account is sent to the user in english' When 'user is created with the locale 'en' in additional info and the pre-register toggle is switched on '
- [ ] Given 'an admin user with rights to create new user in the conosle (domain user)' Then 'a registration email to confirm the user account is sent to the user in english' When 'user is created without locale in additional info and the pre-register toggle is switched on '

### Reset Password

- [ ] Given 'an end user with additional information containing locale set to 'fr' ' Then 'a reset password email is sent to the user in french' When 'user click on Forgot Password and fill the form with the right email address'
- [ ] Given 'an end user with additional information containing locale set to 'en' ' Then 'a reset password email is sent to the user in english' When 'user click on Forgot Password and fill the form with the right email address'
- [ ] Given 'an end user without additional information ' Then 'a reset password email is sent to the user in english' When 'user click on Forgot Password and fill the form with the right email address'

### Account Blocked

**Context:** 
brute force enable with : 
* 2 Max login failures after which the account will be blocked.
* "Send account recovery email" enabled

![image](https://user-images.githubusercontent.com/3110552/180438034-1145f49e-d480-4cc5-8b58-e0410d0029d8.png)

- [ ] Given 'an end user with additional information containing locale set to 'fr' ' Then 'a blocked account email is sent to the user in french' When 'user has two login failures'
- [ ] Given 'an end user with additional information containing locale set to 'en' ' Then 'a blocked account email is sent to the user in english' When 'user has two login failures'
- [ ] Given 'an end user without additional information' Then 'a blocked account email is sent to the user in english' When 'user has two login failures'

### MFA Challenge

**Context:** 
Application has the Email Factor configured and the user has enroll this factor

- [ ] Given 'an end user with additional information containing locale set to 'fr' ' Then 'a challenge email is sent to the user in french containing the code' When 'user signed in'
- [ ] Given 'an end user with additional information containing locale set to 'en' ' Then 'a challenge email is sent to the user in english containing the code' When 'user signed in'
- [ ] Given 'an end user without additional information ' Then 'a challenge email is sent to the user in english containing the code' When 'user signed in'

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

:rocket:

**Comment by omatthewsgravitee** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Graviteeio---Access-Management-5b17f74af58c642fb89cc49f/issues/gravitee-io/issues/8043?planning-poker) with ZenHub @ashraf706 @audrey-tlm @farmborough @leleueri @patelami

**Comment by patelami** [comment]
Env: nightly

<img width="564" alt="Screenshot 2022-08-04 at 09 31 19" src="https://user-images.githubusercontent.com/14215437/182801867-ae67212d-8f4c-4f9d-bee6-486c6107ffe4.png">

**Comment by patelami** [comment]
**Self Registration confirmation:** 

Given an admin has created new user with additional attribute  set to locale = fr_FR
And I have enable self registration
Then I should receive email to confirm registration in french

Given an admin has created new user with additional attribute  set to locale = en_GB
And I have enable self registration
Then I should receive email to confirm registration in english

Given an admin has created new user with without any additional attribute 
And I have enable self registration
Then I should receive email to confirm registration in english 

**Reset Password**

Given an admin has created new user with additional attribute  set to locale = fr_FR
And I request password reset
Then I should receive email with a link to reset password in french

Given an admin has created new user with additional attribute  set to locale = en_GB
And I request password reset
Then I should receive email with a link to reset password in english

Given an admin has created new user with without any additional attribute 
And I request password rest
Then I should receive email with a link to reset password in english

**MFA challange**

Given an admin has created new user with additional attribute  set to locale = fr_FR
And I have setup and enabled email mfa 
And I initiate a login flow
Then I should receive email in french

Given an admin has created new user with additional attribute  set to locale = en_GB
And I have setup and enabled email mfa 
And I initiate a login flow
Then I should receive email in english

Given an admin has created new user with without any additional attribute 
And I have setup and enabled email mfa 
And I initiate a login flow
Then I should receive email in english


**Brut force**
Given an admin has created new user with additional attribute  set to locale = fr_FR
And I attempt to login with incorrect password twice
Then I should receive email in french about blocked email
