### ISSUE TITLE
[management-ui] [emails] improve Help and Tips section

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8051]
## :rainbow: Feature

**As a** 'security domain owner or application owner'

**I want to** 'to help developers to design templates'

**So that** 'I can meet my business requirements '

## :sunrise_over_mountains: Additional information

- Be sure to list all available values in the execution context

## :link: Dependencies

Link a story or other related things...

## :camera: Mockups 

<img width="764" alt="Capture d’écran 2022-07-06 à 21 27 43" src="https://user-images.githubusercontent.com/1927438/177627767-efc69a9b-9ccb-476e-ae70-666f9e549f14.png">

## :books: Documentation required

Provide link to the issue for documentation update

## :superhero: Acceptance criteria

- [ ] Given '...' Then '...' When '...'
- [ ] Given '...' Then '...' When '...'
- [ ] Given '...' Then '...' When '...'

- [ ] Jest test for acceptance criteria

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

:rocket:

**Comment by omatthewsgravitee** [comment]
Duplicate of #8050
