### ISSUE TITLE
[gateway] provide default languages

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8054]
## :rainbow: Feature

**As a** 'administrator'

**I want to** 'to provide default set of languages'

**So that** 'Application owner can easily and quickly set up internationalization to their apps'

## :sunrise_over_mountains: Additional information

- List of languages still need to be defined, at least : en, fr, it, de, ...
- Static property file provided separately (already present for FR and EN)
- Default language: Define default languages into the gravitee.yaml file in order to create dictionaries during domain creation. That way, a default language can be defined easily in the UI (at domain level)

## :superhero: Acceptance criteria

Have 2 browsers - one FR and one ENG and check the translation has happened.
Includes all the test in the buttons 

- [ ] Jest test for acceptance criteria

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

:rocket:

**Comment by patelami** [comment]
Env: Master

As a user I should be able to see more properties in help and tips

As a user, I should be able to add translations and properties.

**Comment by patelami** [comment]
This story is not ready to test yet.

**Comment by tcompiegne** [comment]
This one has been tested via the #8457
