### ISSUE TITLE
[management] [multi-languages] storage at domain level

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8071]
## :rainbow: Feature

Following https://github.com/gravitee-io/issues/issues/8067 : 

**As a** 'security domain owner'

**I want to** 'to create / update / delete my translation dictionaries'

**So that** 'I can propose new translations for my form and email templates'

## :sunrise_over_mountains: Additional information

- CRUD operations from the UI to the data storage layer
- Managing translation dictionaries will require the DOMAIN_I18N_DICTIONARIES permission at API level

## :link: Dependencies

https://github.com/gravitee-io/issues/issues/8067

## :camera: Mockups 

<img width="691" alt="Capture d’écran 2022-07-14 à 21 54 56" src="https://user-images.githubusercontent.com/1927438/179071875-88a558c2-5470-4fcf-8afb-60c676be441d.png">

![image](https://user-images.githubusercontent.com/1927438/179186447-610c4810-9010-4056-ad07-f4eb50433f52.png)

## :books: Documentation required

Provide link to the issue for documentation update

## :superhero: Acceptance criteria

- [x] Given 'a security domain owner wishing to create a new translation dictionary' Then 'an empty dictionary is created' When 'I click on ADD A NEW LANGUAGE button'
- [x] Given 'a security domain owner wishing to add a new entry in the dictionary' Then 'a new entry (key, value) is added to the selected dictionary' When 'I click on ADD A NEW TRANSLATION and SAVE CHANGES button'
- [ ] Given 'a security domain owner wishing to remove an entry in the dictionary' Then 'the entry has been removed' When 'I click on the remove icon and the SAVE CHANGES button'

- [ ] Jest test for acceptance criteria

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

:rocket:

**Comment by omatthewsgravitee** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Graviteeio---Access-Management-5b17f74af58c642fb89cc49f/issues/gravitee-io/issues/8071?planning-poker) with ZenHub @ashraf706 @audrey-tlm @farmborough @leleueri @patelami @remisultan

**Comment by patelami** [comment]
@farmborough 

there are different chevron symbol used to sort the language, display name, key and value alphabetically. However, I can only sort Key. sorting for Display, Language  and Value is not working. 

Also, i can not see the chevron sign in mockups, does is it make more sense to remove the sign completely? 
<img width="955" alt="Screenshot 2022-08-10 at 15 06 35" src="https://user-images.githubusercontent.com/14215437/183922594-628f9f9c-aae3-4990-97bd-223b5a24df8a.png">

**Comment by patelami** [comment]
Please can we add data-testid to following elements: 

1. Language title: data-testid = textLanguageTitle
2. Translations title: data-testid = textTranslationTitle
3. Add a new language button: data-testid = textAddLanguageButton
4. Delete button: data-testid = textDeleteButton
5. Language code text box: data-testid =textLanguageCodeInput
6. Display name text box: data-testid = textDisplayNameInput
7. Add button: data-testid = textAddButton
8. Cancel button: data-testid = textCancelButton
9. language dropdown: data-testid = textLanguageDropdown
10. Add new translation button: data-testid = textAddNewTranslationButton
11. Save changes button = data-testid = textSaveChangesButton
12. Key textbox: data-testid = textKeyInput
13. Value: data-testid = textValueInput
14. Add new key button: data-testid = textAddButton
15. Cancel: data-testid = textCancelButton

I believe add and cancel button (7, 8, 14, 15 ) are same buttons.

**Comment by farmborough** [comment]
@patelami The chevrons are provided by the `ng-datatable` Angular tag (by default, it seems) and are present wherever data tables are used in AM. They also don't seem to be wired up in the other tables I checked (e.g. domain settings -> forms). I'll try and get them to work for all columns or see if it is possible to hide them.
