### ISSUE TITLE
[Jupiter] Issue with response template and invoker timeout

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#8075]
## :rainbow: Feature

As an API Publisher, I want to use response template in Jupiter mode as I used to do in v3 when endpoint/invoker returns timeout

## :sunrise_over_mountains: Additional information

- Same behavior as in v3

## :superhero: Acceptance criteria

- [ ] Given an API with response template customized Then I get the expected response When I reach the customized code.

**Comment by Sicofonia** [comment]
This was tested on 11/08/2022. Working as expected.
