### ISSUE TITLE
[console] Several errors when viewing data in the user card

### ISSUE THREAD

**Issue by grignix** [gravitee-io/issues#8080]
## :collision: Describe the bug

Steps to reproduce the behaviour:
1. Go to Organization settings->Users->Any user who has at least 6 items in the list (Groups or APIs or Applications or Tokens)
2. See error

In the example below, the number of Apis 69
![image](https://user-images.githubusercontent.com/26620272/178147130-699963e4-58d6-4779-8d12-691c784779ab.png)
Сounts number of elements incorrectly, 
if there are more than 100 elements, then what is above 100 is not displayed in the list and it is impossible to scroll through the list because the buttons are not active
At least elements Groups, APIs, Applications, Tokens have this problem

***Please complete the following information:***
 - Environment: [e.g. 3.15.11, 3.18.1]
 - OS: [e.g. Ubuntu, Win10]
 - Browser [e.g. chrome, firefox, edge]

**Comment by grignix** [comment]
In settings
http://localhost:8084/#!/organization/settings/tags Sharding Tags & Entrypoint mappings
http://localhost:8084/#!/organization/settings/tenants Tenants
Search does not work if the item you are looking for is not in the "Items per page"
![image](https://user-images.githubusercontent.com/26620272/178552507-c8297d6b-ad06-401b-978f-29f750982008.png)
![image](https://user-images.githubusercontent.com/26620272/178552976-0713537c-0208-4e1e-8301-d804b18ce7f9.png)

![image](https://user-images.githubusercontent.com/26620272/178552748-613b42e2-b587-4646-b6c1-2ad328839c5f.png)

**Comment by gaetanmaisse** [comment]
Closing as it has been fixed in the latest 3.15+ versions ⬇️ 
![image](https://user-images.githubusercontent.com/4112568/216110648-2878552d-eef8-4fa4-9d1a-a3e19675c58c.png)
