### ISSUE TITLE
API output json formatting

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#8084]
## :collision: Describe the bug
The standard serialisation of JSON content seems to default to camel casing properties inside objects

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Made a flow using assign content policy and groovy policy
2. Assign content:
![image](https://user-images.githubusercontent.com/89140082/178266513-8b1fd4b4-e567-4d82-a3b5-ead27117553c.png)
3. Groovy policy:
![image](https://user-images.githubusercontent.com/89140082/178266845-1120639e-29f0-4ebd-b35c-8cbd729e1e15.png)
5. Call/Response from postman
![image](https://user-images.githubusercontent.com/89140082/178267056-c22a5536-a6d1-409a-b599-f91661c17d5e.png)

## :rainbow: Expected behaviour
In the groovy script not doing any transformations on the variable names, for the json fields, yet after the call is made instead of Uppercase they are changed with lowercase letters, apart from the ID (picture above).

Expected, json output to be intact after the call is made. 

## :computer: Desktop:

***Please complete the following information:***
 - Environment tested: [e.g. 3.15.9]
 - Browser [e.g. chrome]

**Comment by gaetanmaisse** [comment]
It looks like it's the default behavior of Groovy's `JsonOutput`: https://stackoverflow.com/questions/38545194/how-to-keep-letter-case-in-json-converter-method-in-groovy
