### ISSUE TITLE
[Jupiter] Support Failover

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#8086]
## :rainbow: Feature

When failover is enabled and the endpoint does not work, then I should fall back to the second one.

## :sunrise_over_mountains: Additional information

When running standalone container tests in Jupiter mode (see [this issue](https://github.com/gravitee-io/issues/issues/7993)), then it appears that the current implementation of `FailoverInvoker` was not compatible with Jupiter.

Failover document: https://docs.gravitee.io/apim/3.x/apim_publisherguide_backend_services.html#configure_failover

## Acceptance Criteria
- [ ] Failover feature should work like V3 Gateway

**Comment by Sicofonia** [comment]
Refined, ready for sprint

**Comment by jhaeyaert** [comment]
To test it you can enable the Failover on a Jupiter api and configure your backend to point on` http://localhost:12332`

Run the following command to start listening on the local port: ` nc -l 12332 -k`

Try you api, you should see multiple request coming to your local netcat (1 + N where N is the number of failover attempts).

**Comment by LiliaEn** [comment]
Tested on the default env v3.19.0 
Used the same API to cover both Jupiter and V3 with a webhook site as BE. 
The number of requests received on the webhook site is equal to number of failover attempts set +1.
![Screenshot 2022-08-18 at 18 40 22](https://user-images.githubusercontent.com/49516050/185459966-2a3320f8-3d58-4485-b8f0-6bcb77e6b7bc.png)
![Screenshot 2022-08-18 at 18 40 30](https://user-images.githubusercontent.com/49516050/185459978-776148bd-e0b7-4f77-af4f-53557016c673.png)
![Screenshot 2022-08-18 at 18 40 59](https://user-images.githubusercontent.com/49516050/185459995-7aff42e1-bc89-430b-9cd5-ce9c9d986028.png)
