### ISSUE TITLE
List of APIs of a user does not work correctly in the org settings

### ISSUE THREAD

**Issue by grignix** [gravitee-io/issues#8087]
## Describe the bug

Starting from version api 3.15.9 display of rights to api in the user card does not work correctly in version 3.15.8 everything is OK

## To Reproduce

Steps to reproduce the behaviour:

1.  create several, any api (if you already have several api, you can not create api)
2.  create a new(not admin) user(doesn't matter how, Active Directory or gravitee.yml)
3.  log in as a new user and make sure that he does not see any api
     <span class="image-wrap" style="">![](https://user-images.githubusercontent.com/26620272/178341696-bcd7c12b-00cc-41f9-ac98-d95f99cf1808.png)</span>
     [!https://user-images.githubusercontent.com/26620272/178341696-bcd7c12b-00cc-41f9-ac98-d95f99cf1808.png!](https://user-images.githubusercontent.com/26620272/178341696-bcd7c12b-00cc-41f9-ac98-d95f99cf1808.png)
4.  log in as an admin and look at the new user (and all others), all the apis that are on the server appeared in the list of his api and due to the error [https://github.com/gravitee-io/issues/issues/8080](https://github.com/gravitee-io/issues/issues/8080), you can’t look more than 100 APIs and the scrolling buttons don’t work
     <span class="image-wrap" style="">![](https://user-images.githubusercontent.com/26620272/178346779-4b9bfaa7-b332-4e38-93c1-61385be2342d.png)</span>
     [!https://user-images.githubusercontent.com/26620272/178346779-4b9bfaa7-b332-4e38-93c1-61385be2342d.png!](https://user-images.githubusercontent.com/26620272/178346779-4b9bfaa7-b332-4e38-93c1-61385be2342d.png)

**Comment by gaetanmaisse** [comment]
Closing the issue as it's fixed in the latest versions of APIM
