### ISSUE TITLE
Default value for console.ui.url is incorrecte in the Helm chart

### ISSUE THREAD

**Issue by jgiovaresco** [gravitee-io/issues#8094]
## :collision: Describe the bug
By default, the Helm chart installs APIM behind the same host and it configures Ingresses to use paths to redirect to the right component.

Therefore, APIM console is available at `https://apim.example.com/console/` The trailing `/` is important!

However, in the `gravitee.yml` configuration the URL for the console is built to `https://apim.example.com/console` (without the trailing `/`) 

Unfortunately, it breaks the login through Cockpit.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Deploy an APIM with Helm behind the same host
2. Connect the installation in Cockpit
3. Try to login

## :rainbow: Expected behaviour
The console should be accessible

## Current behaviour
A blank page.

## Workaround
In the meantime, it requires defining an environment variable to set `console.ui.url` parameter to the right value

```
env:
  - name: gravitee_console_ui_url
    value: https://apim.example.com/console/
```

**Comment by gaetanmaisse** [comment]
I've got some exciting news to share - we've finally squashed that pesky bug that's been bugging you! 🎉 
The fix is included in the latest version of the APIM Helm Chart (v3.1.62), so you can finally take a breather and let your API do the heavy lifting.
