### ISSUE TITLE
[console] Sharding Tags, Entrypoint mappings, Tenants, search does not work if the item you are looking for is not in the "Items per page"

### ISSUE THREAD

**Issue by grignix** [gravitee-io/issues#8096]
gravitee 3.15.12
In settings
http://localhost:8084/#!/organization/settings/tags Sharding Tags & Entrypoint mappings
http://localhost:8084/#!/organization/settings/tenants Tenants
Search does not work if the item you are looking for is not in the "Items per page"
![image](https://user-images.githubusercontent.com/26620272/178552507-c8297d6b-ad06-401b-978f-29f750982008.png)
![image](https://user-images.githubusercontent.com/26620272/178552976-0713537c-0208-4e1e-8301-d804b18ce7f9.png)
![image](https://user-images.githubusercontent.com/26620272/178552748-613b42e2-b587-4646-b6c1-2ad328839c5f.png)
probably the error is related to https://github.com/gravitee-io/issues/issues/8080

**Comment by gaetanmaisse** [comment]
Closing as it has been fixed in the latest 3.15+ versions ⬇️
![image](https://user-images.githubusercontent.com/4112568/216111356-1605dbff-5d87-4094-9962-0d77c0e00289.png)
