### ISSUE TITLE
[policy][gravitee-policy-callout-http] Truncated request.content when it contains accents

### ISSUE THREAD

**Issue by alambert-idkids** [gravitee-io/issues#8109]
## :collision: Describe the bug
Hi Gravitee Team !
I encounetred a probleme with the policy Http Callout. 

Via this one, I want to make a call with the original body of the request.

When the body doesn't contains accented characters, everything is ok !
But when the body contains accented characters, the sent body is truncated ✂️ 

## :sunrise_over_mountains: To Reproduce

1. Create a new API
2. Add HTTP Callout policy on request flow
3. Configure the policy:
- Scope: REQUEST_CONTENT
- HTTP Method: POST
- Request body: {#request.content})

4. Make a POST request to the API with body containing accents
```JSON
{
    "name": "name with accents éà"
}
```

## :rainbow: Expected behaviour
The backend server receives the following body:
```JSON
{
    "name": "name with accents éà"
}
```

## 🌧️   Current behaviour
The backend server receives the following body:
```JSON
{
    "name": "name with accents éà"
```

## :movie_camera: Useful information
![image](https://user-images.githubusercontent.com/109204829/178690455-74e6e287-9553-49d7-9870-328465e0fe63.png)

Simple node.js server code:

```Javascript
const http = require('http')

const port = process.env.PORT || 3000

const server = http.createServer(async (req, res) => {
    const buffers = [];
  
    for await (const chunk of req) {
      buffers.push(chunk);
    }
  
    const data = Buffer.concat(buffers).toString();
  
    console.log(data);

    res.end();
  });

server.listen(port, () => {
  console.log(`Server running at port ${port}`)
})
```

## :computer: Environment:

- APIM: 3.17.4, 3.18.3, 3.10.11
- HTTP Callout policy:  1.15.0

## 🩹 Possible fix

The fix is ​​potentially the same as [this](https://github.com/gravitee-io/gravitee-notifier-webhook/pull/4/commits/124c1c61fd9466c916dbfad089e1054d922f0228)

The content length should be miscalculated

![image](https://user-images.githubusercontent.com/109204829/178694263-1a094577-70fd-4ac6-a7c0-2df9ebe148ff.png)

**Comment by gaetanmaisse** [comment]
@alambert-idkids 🎉  the fix for this issue has been released in 1.15.1: 
 - https://github.com/gravitee-io/gravitee-policy-callout-http/releases/tag/1.15.1
 - https://download.gravitee.io/graviteeio-apim/plugins/policies/gravitee-policy-callout-http/gravitee-policy-callout-http-1.15.1.zip
