### ISSUE TITLE
override default theme prototyping 

### ISSUE THREAD

**Issue by omatthewsgravitee** [gravitee-io/issues#8111]
## :rainbow: Feature

**As a** '...'

**I want to** '...'

**So that** '...'

## :sunrise_over_mountains: Additional information

Detailed behaviour, rules or additional interesting stuffs...

## :link: Dependencies

https://github.com/gravitee-io/issues/issues/8044

Link a story or other related things...

## :camera: Mockups 

[Loom demo link](https://www.loom.com/oauth-callback?login_success=true&provider=slack-openid-connect&redir=https%3A%2F%2Fwww.loom.com%2Fshare%2F96e8dcd5f330456ba7f4d82c6e4f764f&user_role=client)

![image.png](https://images.zenhubusercontent.com/61fc4917f078f31c2ae16580/d2a936e4-dbb1-4195-a851-622c0bf19c70)

## :books: Documentation required

Provide link to the issue for documentation update

## :superhero: Acceptance criteria

- [ ] Given '...' Then '...' When '...'
- [ ] Given '...' Then '...' When '...'
- [ ] Given '...' Then '...' When '...'

- [ ] Jest test for acceptance criteria

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

:rocket:

**Comment by audrey-tlm** [comment]
Review needed from @tcompiegne

**Comment by audrey-tlm** [comment]
Open to feedback from the AM team
