### ISSUE TITLE
[management-ui] [policy] Enroll MFA policy allows RecoveryCode

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#8119]
## :collision: Describe the bug

If RecoveryCode is enabled, the policy proposes it as a choice. It shouldn't.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Configure an SMS factor and a recovery code
2. Configure then Enroll MFA policy
3. Recovery code factror is part of the list

## :rainbow: Expected behaviour

Only SMS factor shold be proposed but Recovery Code shoudn't as it is a special factor type

**Comment by patelami** [comment]
Env: [3.17](https://am.management.v3-17-x.gravitee.xyz/management/auth/login?error)
Is this merged to 3.17.x ? I can still reproduce this issue on 3.17.x

https://user-images.githubusercontent.com/14215437/180986177-7f438dfd-15df-4cfe-8605-02324d13a4e1.mov

**Comment by patelami** [comment]
Result: PASS
