### ISSUE TITLE
[management] [override theme] UI/UX integration at domain level

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8122]
## :rainbow: Feature

Following #8121

**As a** 'security domain owner'

**I want to** 'manage my theme in the Console UI'

**So that** 'I can easily custom my form and email templates'

## :sunrise_over_mountains: Additional information

- This issue will not manage the "preview" frame, will be done in another issue

## :link: Dependencies

Link a story or other related things...

## :camera: Mockups 

**Please note: Faded areas are not included**

![image.png](https://images.zenhubusercontent.com/61fc4917f078f31c2ae16580/29ae58ec-0ab0-460f-a3f5-1c7137a75cf5)

## :books: Documentation required

Provide link to the issue for documentation update

## :superhero: Acceptance criteria

- [ ] Given 'a security domain owner wishing to create a custom theme' Then 'a custom theme is created' When 'I change default values and I click on the PUBLISH button'
- [ ] Given 'a security domain owner wishing to reset to the default theme' Then 'the custom theme is removed and the default theme is applied' When 'I click on the RESET button'

- [ ] Jest test for acceptance criteria

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

:rocket:

**Comment by patelami** [comment]
Env: nightly
Result: PASS

Given 'a security domain owner wishing to create a custom theme' Then 'a custom theme is created' When 'I change default values and I click on the PUBLISH button'

Given 'a security domain owner wishing to reset to the default theme' Then 'the custom theme is removed and the default theme is applied' When 'I click on the RESET button'
