### ISSUE TITLE
[gateway] [override theme] [forms] theme integration

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8125]
## :rainbow: Feature

Following all the management tasks done around the theme concept, I want to integrate this into the gateway HTML form templates.

## :sunrise_over_mountains: Additional information

- HTML form templates will be customized with the theme data of the security domain  

## :link: Dependencies

Link a story or other related things...

## :camera: Mockups 

Insert screenshots, drawings...

## :books: Documentation required

Provide link to the issue for documentation update

## :superhero: Acceptance criteria

- [ ] Given 'a user wants to customize the colour of a login page ' Then 'when they take a new colour palate, and apply a colour' When 'I want to login I can see the new colours applied'
- [ ] Repeat for all pages 

:rocket:

**Comment by patelami** [comment]
Env: Master
Result: Pass

Given I have selected different theme 
And I publish it
And I initiate a login flow
Then I should see new theme colour applied to the login page

<img width="604" alt="Screenshot 2022-08-30 at 16 10 35" src="https://user-images.githubusercontent.com/14215437/187474455-e7b1d825-1e54-445d-b997-aace0e48f652.png">
