### ISSUE TITLE
Max_clauses_count: 1024 

### ISSUE THREAD

**Issue by dihtec** [gravitee-io/issues#8129]
## :collision: Describe the bug
Dear, good afternoon!

When using gravitee's managemnte api, when hitting more than 1024 API's registered, it presents me with this error preventing me from performing searches, someone could help me to increase this index, I made a query in .yml and could not find a parameter to change.

Erro: ERROR i.g.m.rest.provider.ThrowableMapper - Internal error
org.apache.lucene.search.BooleanQuery$TooManyClauses: maxClauseCount is set to 1024 

![image](https://user-images.githubusercontent.com/109388994/179307377-58b94bd2-2a43-423c-b83a-3f4bf4165a2f.png)

**Comment by phiz71** [comment]
Hello @dihtec and sorry for the delay 🙏🏻 .
Thanks for your issue. Actually we opened recently the same ticket (https://github.com/gravitee-io/issues/issues/8568) which has been fixed.

The fix is currently available in 3.18.12 and will be available soon in other supported versions.
