### ISSUE TITLE
[management] Management API fails to start if API without primary owner

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#8130]
Some users have APIs with no primary owners in their database.

APIM 3.17 was resilient to thos database inconsistencies.
From APIM 3.18, management API doesn't start if an API has no primary owner.

**Steps to reproduce**
- Create an API
- Remove its primary owner, in database, in memberships table
- Restart management API

**Current behavior**
Management API fails to start

**Expected behavior**
Management API starts

gz#4526

**Comment by gaetanmaisse** [comment]
Closing as it has been released in 3.18.3
