### ISSUE TITLE
[GKO] Start/stop API on gateway

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#8136]
## :rainbow: Feature

As an API Publisher, I want to be able to start and stop my API from the CRD 

## :sunrise_over_mountains: Additional information

- [x] Gateway connected through websocket to Kube API server
- [x] Gateway listening to config_maps
- [x] CRD contains state of the API : `Start` `Stop` - quid of structure ?
  - [x] Gateway won't handle request for stopped APIs
- https://github.com/gravitee-io/gravitee-api-management/blob/master/gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java#L2084-L2099

## :link: Dependencies

#7977 

## :superhero: Acceptance criteria

- [x] Given a valid CRD with a started flag then i can call the gateway
- [ ] Given a valid CRD with a stoped flag then i can not call the gateway

## Documentation 

- [ ] How to start/stop your API using CRD ?

**Comment by RubenMMSantos** [comment]
Featured verified and confirmed as fixed
Acceptance criteria validated
