### ISSUE TITLE
[portal] Always throwing Method Not Alllowed on every action

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [gravitee-io/issues#814]
Hello.
I have just donwloaded gravitee full `1.9.2` version. I have launched MongoDB and Elasticsearch `2.x` version.

Then I have launched gateway and after that management api. After that I have installed http-server for my node js and launched portal with it.

When I try to login or open some pages it always throws Method not allowed red notification message.

### Your Environment

I'm using gravitee `1.9.2`
MongoDB `3.4.7`
Elastic `2.4.2`
Node JS `7.7.1`

![image](https://user-images.githubusercontent.com/8684688/30934875-bee899dc-a3f0-11e7-9377-6d82f82aa40a.png)

Logs from my portal:

    [Thu Sep 28 2017 01:50:31 GMT+0600 (Центральная Азия (зима))] "GET /portal/i18n/ru.json" Error (404): "Not found"
    [Thu Sep 28 2017 01:50:31 GMT+0600 (Центральная Азия (зима))] "GET /management/user/" Error (404): "Not found"
    [Thu Sep 28 2017 01:50:31 GMT+0600 (Центральная Азия (зима))] "GET /themes/assets/GRAVITEE_LOGO1-01.png" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
    [Thu Sep 28 2017 01:53:46 GMT+0600 (Центральная Азия (зима))] "POST /management/user/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
    [Thu Sep 28 2017 01:53:46 GMT+0600 (Центральная Азия (зима))] "POST /management/user/login" Error (404): "Not found"
    [Thu Sep 28 2017 01:54:46 GMT+0600 (Центральная Азия (зима))] "POST /management/user/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
    [Thu Sep 28 2017 01:54:46 GMT+0600 (Центральная Азия (зима))] "POST /management/user/login" Error (404): "Not found"
    [Thu Sep 28 2017 01:59:56 GMT+0600 (Центральная Азия (зима))] "POST /management/user/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
    [Thu Sep 28 2017 01:59:56 GMT+0600 (Центральная Азия (зима))] "POST /management/user/login" Error (404): "Not found"

Management API shows this:

    01:14:43.210 [gravitee] INFO  i.g.m.s.c.BasicSecurityConfigurerAdapter - Loading authentication provider of type gravitee at position 1
    01:14:44.949 [gravitee] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@7d90644f{/management,null,AVAILABLE}
    01:14:44.983 [gravitee] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@5b0d480c{HTTP/1.1,[http/1.1]}{0.0.0.0:8083}
    01:14:44.984 [gravitee] INFO  org.eclipse.jetty.server.Server - Started @18480ms
    01:14:44.986 [gravitee] INFO  i.g.m.standalone.node.ManagementNode -    Starting component: InitializerService
    01:14:44.987 [gravitee] INFO  i.g.common.service.AbstractService - Initializing service Initializer Service
    01:14:45.071 [gravitee] INFO  i.g.m.standalone.node.ManagementNode - Gravitee.io - Management API id[fb34a23f-c005-4199-b4a2-3fc005819934] version[1.9.2] pid[6052] build[216#e07d277b382d0027082f983bc0609827d37fd746] jvm[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/25.121-b13] started in 14724 ms.

I think that Portal not looking to correct addresses of API's. However, all assets are minified and it is hard to understand how portal makes requests to API's

**Comment by brasseld** [comment]
Hi @SuperMasterBlasterLaser,

You have to update `constants.json` in portal and set the correct baseURL.
According to your log, you have configure it as follow:
`baseURL: http://localhost:8083/management/`

Thanks for your feedback.
