### ISSUE TITLE
[GKO] Deploy the same API on multiple clusters

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#8140]
## :rainbow: Feature

As an API publisher using K8, I want to be able to deploy my API on several clusters relying on the same M-API. 

## :sunrise_over_mountains: Additional information

- ![image](https://user-images.githubusercontent.com/3227037/180222180-92467e05-2a0f-496d-a519-a9527a596773.png)

## ❓ Pending questions

- What about an API that is stopped on one cluster and started on another ? rely on cross-cluster consistency from user ?
- Do we need one API per cluster in M-API ? Created with first operator, rely on crossId for an update ?
- Quid of UI & M-API if not consistent CRD in every cluster
- Quid of deletion from one cluster only ? (would delete related subscriptions / analytics on M-API) => document that need to remove connexion from ManagmeentContext before deleting API ?
  - document process for deletion case 
- Should we prefix with cluster name ?  
- related to validation #8135 ?
- quid of subscription
- use of sharding tags to start/stop api on specific cluster ?

![image](https://user-images.githubusercontent.com/3227037/189136262-8fb79534-3b8b-4816-bbd5-92b853113927.png)

## :superhero: Acceptance criteria

- [ ] Given '...' Then '...' When '...'

**Comment by ThibaudAV** [comment]
Note for future us: 
It will be necessary to calculate a hash of an apidefinition to check if this changes or not. 
In case of multicluster
