### ISSUE TITLE
[Management] View list of API managed by CRD

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#8142]
## :rainbow: Feature

As a user, I want to view list of my APIs managed by CRD in the console.

## :sunrise_over_mountains: Additional information

- Use the `ManagedByKubernetes` field to get the flag
- Add an icon in the list of icons
- Add a field in https://github.com/gravitee-io/gravitee-api-management/blob/48512798a74efe0030b4a62e26aec9478de6da9f/gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/search/lucene/transformer/ApiDocumentTransformer.java to be able to search by `managedBy` field

## Out of scope

- Mockups are required from UX team
- Only the one related to the current ManagementContext and push to a M-API 
- Opportunity to work on the page list by adding some filters, search, tabs : 
  - ![SCR-20220215-kvi (1)](https://user-images.githubusercontent.com/3227037/180940990-17b52561-3ba1-4349-8869-71278e516d21.png)

## :superhero: Acceptance criteria

- [x] Given an API managed by CRD i can view it in the list prefixed/icon in order to have a clear view of which APIs are managed through console or K8

**Comment by RubenMMSantos** [comment]
feature verified and working as expected.
Acceptance criteria validated
![Screenshot 2022-09-02 at 14 01 10](https://user-images.githubusercontent.com/14939456/188165374-51e323a0-d2d1-4cf8-b35a-13095b91504f.png)
