### ISSUE TITLE
[Management] Export CRD from existing API Definition

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#8143]
## :rainbow: Feature

As a user, I want to export a valid CRD for my API in order to facilitate my transition to a K8 managed APIs.

## :sunrise_over_mountains: Additional information

- API v2 only
- Export from console & M-API
- Option in export menu 
- Yaml export from M-API 
- Foundation for export to CRD and add next resources later
- Filter documentation pages references

## 🚫 Out of scope

- Documentation pages 

## 📖 Documentation 

- How export work ? 
- Limitations

## :superhero: Acceptance criteria

- [x] Given a v2 API then i can use the CRD generated with GKO when I export it from APIM
- [x] Given a v2 API then i don't view any references to documentation when I export it from APIM

**Comment by RubenMMSantos** [comment]
Feature working as expected.
acceptance criteria verified and confirmed.
