### ISSUE TITLE
[oauth] Oauth2 on AM Web UI not working 

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [gravitee-io/issues#815]
Hello.

I have downloaded standalone gateway and access management web ui.

When I launch gateway it launches on `localhost:8092` and ui on `localhost:8081`

In my `constants.json` I have written this

    {
      "portalTitle": "Access Management",
      "baseURL": "http://localhost:8092/management",
      "authentication": {
        "oauth2": {
          "authorize": "http://localhost:8092/admin/oauth/authorize",
          "userInfo": "http://localhost:8092/admin/userinfo",
          "clientId": "admin",
          "redirectUri": "http://localhost:8081/oauth/callback",
          "logoutUri": "http://localhost:8092/admin/logout?target_url=http://localhost:8081/logout/callback"
        }
      }
    }

However when login finishes successfully it redirects to `4200` port and doesn't work.

**Comment by brasseld** [comment]
Hi.

There is absolutely no reason to be redirected to 4200.
Are you trying to access the management UI using the admin account ?

**Comment by SuperMasterBlasterLaser** [comment]
@brasseld Yes I'm entering by writing `admin adminadmin`

**Comment by brasseld** [comment]
@SuperMasterBlasterLaser perhaps you have an issue with your browser cache, no ?

There is no way to retrieve such port (`4200`), so the only thing I'm seeing, is a problem with the cache. Can you have a try by disabling it or force refresh of your page ?

**Comment by brasseld** [comment]
No more information.

I'm closing it.

**Comment by wenwenbaba** [comment]
In graviteeio-am-management-ui-2.5.0 --> constants.json
configuration like this -->  "redirectUri": "http://192.168.88.233:4200/login/callback"
but , I can't find 4200 port anywhere .
