### ISSUE TITLE
[gateway][expression-language] String Condition Evaluator not work as expected

### ISSUE THREAD

**Issue by gcusnieux** [gravitee-io/issues#8153]
## :collision: Describe the bug
A condition like `{#request.headers['foobar'] != null}` return true when the foobar header is not present.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Create an new Echo API 
2. Go to the policy studio, add a Transform Header policy that add a new header (like: `foo`: `bar`) 
3. Add a condition to this policy `{#request.headers['foobar'] != null}`
4. Go to the Try it tab and run a try it (without any header)
5. 💥 The response contains `foo`: `bar`

## :rainbow: Expected behaviour
The Transform Header policy should have been skipped and so `foo`: `bar` shouldn't be here

## Current behaviour

NA

## :movie_camera: Useful information

NA

## :computer: Desktop:

NA

## :warning: Potential impacts

Impacted version: 3.15+

## :link: Dependencies

I added a unit test to reproduce the case https://github.com/gravitee-io/gravitee-expression-language/pull/52

This problem breaks the following tests on master:
 - add-condition-on-flows-and-test-them.spec.ts
 - add-policies-to-flows-and-use-them.spec.ts
 - call-my-api-including-query-params-headers-body-and-view-debug-session-with-proper-info.spec.ts

**Comment by LiliaEn** [comment]
Tested on 3.15.x env.
Browser: Chrome Version 99.0.4844.74 , macOS Big Sur v11.6
Working as expected
- When using {#request.headers['kjebercerc'] != null} condition and `kjebercerc` doesn't exist, the policy is not executed and the new header added using Transform Headers is not  displayed in the response
- When using {#request.headers['kjebercerc'] != null} condition and `kjebercerc` == null, the policy is not executed and the new header added using Transform Headers is not  displayed in the response
- When using {#request.headers['kjebercerc'] != null} condition and `kjebercerc` exists, the policy is executed and the new header added using Transform Headers is  displayed in the response
- When using {#request.headers['kjebercerc'] == null} condition and `kjebercerc` doesn't exist, the policy is executed and the new header added using Transform Headers is  displayed in the response
- When using {#request.headers['kjebercerc'] == null} condition and `kjebercerc` == null, the policy is executed and the new header added using Transform Headers is displayed in the response
- When using {#request.headers['kjebercerc'] == null} condition and `kjebercerc` exists, the policy is not executed and the new header added using Transform Headers is not  displayed in the response
![Screenshot 2022-07-27 at 09 58 26](https://user-images.githubusercontent.com/49516050/181207525-9f972cd7-1035-432a-b0ce-c3db5c001160.png)
![Screenshot 2022-07-27 at 09 58 41](https://user-images.githubusercontent.com/49516050/181207553-a9a39902-4c0a-40a2-8ee0-c933837ceba8.png)
![Screenshot 2022-07-27 at 09 59 18](https://user-images.githubusercontent.com/49516050/181207607-935ca276-1747-467c-8df1-44b658422456.png)
![Screenshot 2022-07-27 at 09 59 35](https://user-images.githubusercontent.com/49516050/181207650-4824d5c8-706d-46c4-be90-5e3e3b2a4df1.png)
![Screenshot 2022-07-27 at 09 59 54](https://user-images.githubusercontent.com/49516050/181207689-dbce8a79-1078-4815-86f2-17f88250fef6.png)
![Screenshot 2022-07-27 at 10 00 10](https://user-images.githubusercontent.com/49516050/181207712-4e70cbdb-3d71-46ce-961c-0e965e3ad0d5.png)
![Screenshot 2022-07-27 at 10 00 26](https://user-images.githubusercontent.com/49516050/181207732-32b5e752-cec9-4fdd-81c6-65e3bf473b09.png)
![Screenshot 2022-07-27 at 10 00 41](https://user-images.githubusercontent.com/49516050/181207768-20e3da56-fe04-4747-afa0-38555847fc2b.png)
