### ISSUE TITLE
Encoded redirect url

### ISSUE THREAD

**Issue by geraudmasson** [gravitee-io/issues#816]
Hello,

I have a problem with redirects urls : 

If there is presence of reserved characters, as stated in RFC 2396 section 2.2, the url must be encoded.
But I have got this error : 

error="invalid_grant", error_description="Invalid redirect: http%3A%2F%2F..... does not match http://....

Should I put the encoded url in my redirect uris as well?

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/graviteeio-access-management/issues/186
