### ISSUE TITLE
[management] API primary owner is mandatory, and always set

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#8162]
Some customers have API without primary owners in their database.

This is not normal and we have to understand how the customer managed to create those anomalies in database.
At a first glance, they are using some API calls to delete primary owners. It's possible for example with [this endpoint](https://docs.gravitee.io/apim/3.x/management-api/3.18/#operation/deleteApiMember)

Once we understood, we have to :

1 - Fix the APIM processes that leads to having an API without primary owner.

2 - Find a way to correct those anomalies (suggestion : upgrader ?). In order to be sure that, when APIM runs, there is no API without primary owner in database.

3 - Remove from APIM all workarounds to handle those API without primary owners.

As an example, here is a non-exhaustive list of current workarounds :
- https://github.com/gravitee-io/gravitee-api-management/blob/947423fddffb5502d39a8dd2faf5c593bf5e808a/gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java#L3212-L3234
- https://github.com/gravitee-io/gravitee-api-management/commit/7f808fd6fb178a9bf2f6a415f9de7bd08c4ea08f
- https://github.com/gravitee-io/gravitee-api-management/commit/59265b824b10ce3a1e2f19d17984a037fb698350

**Comment by a-cordier** [comment]
As discussed with @mouligno the upgrader will simply go through API primary owner inconsistency and warn in the startup logs.

The guards are not removed at the moment but a release note will be added to inform users that they should check the logs and fix APIs without a PO.

**Comment by RubenMMSantos** [comment]
When trying to remove a Primary Owner from an API using "Remove an API member" request, user is no longer able to.

Request now returns a message informing the user
![Screenshot 2022-10-03 at 10 25 07](https://user-images.githubusercontent.com/14939456/193544059-bebde65a-3536-453a-851c-73d491069509.png)
