### ISSUE TITLE
[Console] Links analytics improvements

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#8170]
## Global context

Regarding external links in APIM, we need to be able to understand better how our users behave. In order to achieve that, we need to add `utm` information to several links in APIM.

## List of links to update 

- [ ] Cockpit API Promotion link (link in popup on API page that appears if APIM isn't registered in Cockpit yet) - `utm_source=apim&utm_campaign=API_promotion&utm_medium=InApp`
- [ ] Discover cockpit link - in organization settings where we can have various state depending of the status of APIM/Cockpit registration
  - [ ] not register - `utm_source=apim&utm_campaign=DiscoverCockpit&utm_term=not_register&utm_medium=InApp`
  - [x] successfully registered - `utm_source=apim&utm_campaign=DiscoverCockpit&utm_term=registered&utm_medium=InApp`
  - [ ] need to accept on cockpit - `utm_source=apim&utm_campaign=DiscoverCockpit&utm_term=pending&utm_medium=InApp`
  - [ ] rejected from cockpit - `utm_source=apim&utm_campaign=DiscoverCockpit&utm_term=rejected&utm_medium=InApp`
  - [ ] not linked anymore - `utm_source=apim&utm_campaign=DiscoverCockpit&utm_term=removed&utm_medium=InApp`
- [x] ~Try API Designer link - `utm_source=apim&utm_campaign=api_designer&utm_medium=InApp`~

**Comment by phiz71** [comment]
The last point can only be done in 3.18.x
>  Try API Designer link - utm_source=apim&utm_campaign=api_designer&utm_medium=InApp

**Comment by phiz71** [comment]
@mouligno can you confirm that the following corresponding table is ok ?

<table>
<tr>
	<th>Cockpit Installation Status
	<th>utm_term param to use
<tr>
	<td>PENDING
	<td>pending
<tr>
	<td>ACCEPTED
	<td>registered
<tr>
	<td>REJECTED
	<td>rejected
<tr>
	<td>DELETED
	<td>removed
<tr>
	<td>Any other status (even no status)
	<td>not register<b>ed</b>
</table>

Can you also check and confirm the case (small/upper case, Snake/camelCase) of utf_campaign ? They seem quite heterogeneous 🤔 

- API_promotion
- DiscoverCockpit
- api_designer

**Comment by mouligno** [comment]
👍 for the table

Let's go with this convention naming : 
````
api_promotion
discover_cockpit
api_designer

**Comment by phiz71** [comment]
To test all the possible cockpit installation status, we relied on console unit tests:
 - https://github.com/gravitee-io/gravitee-api-management/pull/2347/files#diff-e246d10d3940029b9d5acc674f22f8cb4a5c3aedad212b67b8b0b8f6bac37b74
 - https://github.com/gravitee-io/gravitee-api-management/pull/2347/files#diff-6803674cc6c1cf48e4f4d3cfe77da5f58d60c7cd31f2c7b7843c11728f422383

**Comment by RubenMMSantos** [comment]
After confirming with Developer, ticket will be moved to done due to the complexity for testing and console unit test have run successfully
