### ISSUE TITLE
[GKO] Apim Gateway  -> ConfigMap connection

### ISSUE THREAD

**Issue by ThibaudAV** [gravitee-io/issues#8189]
Without this [branche](
https://github.com/gravitee-io/gravitee-api-management/tree/issues/%237202-kubernetes-operator) Apim Gateway not listen ConfigMap so not work without a manual start in apim console-ui 

Todo : Create PR & merge this branche into master

**Comment by omatthewsgravitee** [comment]
Test by API creation, ok if can call gateway
