### ISSUE TITLE
[portal] Small ui bug the OK popup is red

### ISSUE THREAD

**Issue by AnselmeDewavrin** [gravitee-io/issues#82]
Hi all,
when saving, everything is fine but the color of the popup is red
![bug_gravitee_ui](https://cloud.githubusercontent.com/assets/18033361/16189344/3d7937fa-36da-11e6-9d81-e0edc30543ce.PNG)

thanks,
Anselme

**Comment by NicolasGeraud** [comment]
Hi @AnselmeDewavrin , what version of gravitee.io are you using?

You say "when saving" and the message is "API Deployed".

Are you saving the API or are you deploying it ?

thanks.

**Comment by AnselmeDewavrin** [comment]
sorry, this screenshot is when deploying.

I'm using 0.14.0

Thanks

**Comment by AnselmeDewavrin** [comment]
after a failed operation, every successfull operation gives a red popup.
