### ISSUE TITLE
[portal] background-color of "sign in with my OAuth2 provider" is incorrect

### ISSUE THREAD

**Issue by blackfich** [gravitee-io/issues#820]
The background-color of the "sign in with my OAuth2 provider" is incorrect. Also it should be possible to customize both background and text color.

### Expected Behavior
content of the constants.json:
```json
  "authentication": {
    "oauth2": {
      "clientId": "XXXXXXX-XXXXXXXX-XXXXXXXXX",
      "name": "my OAuth provider",
      "backgroundColor": "#cc9900",
      "color": "#ffffff",
      "authorizationEndpoint": "http://xxxxxxxxxxxxx/auth",
      "scope": ["profile", "openid"]
    }
  }
```

```html
<button class="btn btn-block btn-person_outline" style="background-color:#cc9900, color:#ffffff;" data-ng-repeat="provider in $ctrl.providers" ng-click="$ctrl.authenticate(provider.id)">....</button>
```

### Current Behavior
content of the constants.json:
```json
  "authentication": {
    "oauth2": {
      "clientId": "XXXXXXX-XXXXXXXX-XXXXXXXXX",
      "name": "my OAuth provider",
      "color": "#cc9900",
      "authorizationEndpoint": "http://xxxxxxxxxxxxx/auth",
      "scope": ["profile", "openid"]
    }
  }
```

```html
<button class="btn btn-block btn-person_outline" style="background-color:{};" data-ng-repeat="provider in $ctrl.providers" ng-click="$ctrl.authenticate(provider.id)">....</button>
```

The value of the `color` attribute is not correctly injected. Instead we just have `{}`

### Steps to Reproduce (for bugs)
1. Navigate to the login page with OAuth2 provider enabled
2. Inspect the HTML for the button

### Your Environment
* Version used: 1.9.2
* Browser Name and version: Firefox 55
* Operating System and version: CentOS/7

**Comment by brasseld** [comment]
Will be closed by https://github.com/gravitee-io/issues/issues/1595

**Comment by aelamrani** [comment]
Closed by https://github.com/gravitee-io/issues/issues/2013
