### ISSUE TITLE
Error while trying to connect using IDP with group mapping

### ISSUE THREAD

**Issue by Okhelifi** [gravitee-io/issues#8205]
Using an old version of APIM we can create an IDP with group mapping

![Screenshot 2022-07-26 at 14.38.52.png](https://images.zenhubusercontent.com/606db0512360be8646b6dd7a/96693b0b-09da-4cc0-a41b-4c658c6acde2)

Moreover the environment id is necessary to know if the group is manageable or not.
If the environment id is null in the execution context an error occurred and the user can not connect to the application anymore. 

![Screenshot 2022-07-26 at 14.48.15.png](https://images.zenhubusercontent.com/606db0512360be8646b6dd7a/315cbabb-c7c6-4a36-8a99-995d667b300b)

We need to check the environment data before checking the group permission

### Expected Behavior
The user is able to connect to the application with and IDP containing group mapping

### Current Behavior
The user is not able to connect to the application with and IDP containing group mapping

### Steps to Reproduce (for bugs)
- Start APIM in 3.5
- login as admin
- Create a google idp
- logout
- connect as a user using the google idp
- logout
- connect as admin
- create a group
- add the user in the group
- add a group mapping in the idp
- migrate your app to 3.18
- try to login using the idp

**Comment by gaetanmaisse** [comment]
Tested and everything is ok following the scenario of `Steps to Reproduce (for bugs)`
