### ISSUE TITLE
Unify GatewayConfiguration

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#8206]
## :rainbow: Technical enhancement

Unify the way we manage GatewayConfiguration (and probably the same is needed for REST Api)

### ⌚  Today State

We have multiple way to access configuration:
- Using Spring's `@Value` and dealing with default value each place we inject it
- using Spring's `Environment` through autowiring
- Using Gravitee's node `Configuration` object, which is basically a wrapper of Environment, providing a read map of the properties from environment, property file, etc.)
- Using `GatewayConfiguration`, which processes configuration from `System.getProperty` to aggregate it to lists for most of the cases (tags, environments, etc.)

With the introduction of Jupiter mode, we also define new default values for configuration.
You can see an example in APIM with `TimeoutConfiguration`

### 👀 What do we want ?

The goal of this ticket is to find a way to unify all those configuration in one and only class to have only one access to configuration from the class. It also allow to avoid many `@Value` field or lot of parameters in the constructor of our classes.

With that, we will know that we have a single source of truth, already computed depending on particular conditions if needed.

**Comment by phiz71** [comment]
Could it be linked to #7711 ?
