### ISSUE TITLE
[Prometheus] Allow to exclude labels for some specific categories

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#8218]
When exposing metrics on the APIM gateway through the `/prometheus` endpoint, it is possible to define the expected labels to export.

By default, the following are enabled:
 - local
 - http_method
 - http_code

As an example, this produces metrics with the expected labels such as:

```
# HELP http_server_bytes_written_total Number of bytes sent by the server
# TYPE http_server_bytes_written_total counter
http_server_bytes_written_total{application="gio-apim-gateway",instance="my-host",local="localhost:18082",} 4.90672576E8
http_server_bytes_written_total{application="gio-apim-gateway",instance="my-host",local="0.0.0.0:8082",} 5.11805139E8
# HELP http_client_requests_total Number of requests sent
# TYPE http_client_requests_total counter
http_client_requests_total{application="gio-apim-gateway",instance="my-host",local="?",method="GET",} 781706.0
```

It is possible to override the list of labels to include thanks to the `services.metrics.prometheus.labels` configuration. The inconvenient is that these labels are included for every metrics categories and, depending on the metrics, could increase dramatically the number of cardinalities and crash the gateway with an `OutOfMemory` error (see https://github.com/gravitee-io/issues/issues/2057).

The idea is to be able to add some labels exclusions or inclusions for a specific category. For exemple, it could be possible to add the `remote` label only for the `http.client` category and not the `http.server` one. In that case, the user is able to generate metrics per backend endpoint (which are bounded, no risk to get infinite cardinalities), whereas it will be disabled for http.server which corresponds to the incoming gateway request (which are unbounded cause we can have an infinite number of different callers reaching the gateway).

**Comment by gaetanmaisse** [comment]
Closing it as a dedicated issue has been created for the doc part: https://graviteedevops.atlassian.net/browse/DOC-207
