### ISSUE TITLE
[gateway] set focus on password field when login already known

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#8219]
When the login form is display with the login_hint provided as parameter, the focus should be on the password field as the login field is on readonly.

### Expected Behavior

Focus must be set by default on the password field

### Current Behavior

Focus is on the login field

### Steps to Reproduce (for bugs)

1. call the authorize endpoint with the login_hint parameter in addition of the other ones.
2. the login page is displayed but the focus is on the login field. (this field is readonly)

**Comment by patelami** [comment]
Env: 3.15.x

Result: PASS

https://user-images.githubusercontent.com/14215437/190134037-95f1888f-b460-4fd0-a09d-e4d7bb739f7d.mov
