### ISSUE TITLE
APIM Console-> When dragging Json to XML policy in Design Studio, Save button is not displayed 

### ISSUE THREAD

**Issue by LiliaEn** [gravitee-io/issues#8227]
When dragging Json to XML policy in Design Studio, Save button is not displayed 

### Expected Behavior
When dragging and dropping Json to XML policy, Save button should be displayed to be able to confirm the changes

### Current Behavior
When dragging and dropping Json to XML policy in Design Studio, Save button is not displayed. The policy doesn't require any field, so if no change is made on the policy configuration there is no option to save it. Please see the video
https://drive.google.com/file/d/11z-cXkJrzdnOnBWuw8jKJk8BGXNcEKBU/view?usp=sharing

### Steps to Reproduce (for bugs)
1. Login to APIm Console as an admin/api publisher
2. Create an API or use an existing one
3. Go to Design Studio
4. Drag and drop Json to XML policy - notice that Save button is not displayed and the changes cannot be saved
5. Drag and drop another policy e.g. XML to Json -> notice that Save button is displayed even if no changes were made

### Your Environment
* Version used: default env - v3.19.0, 3.17.0 
* Browser Name and version: Chrome Version 103.0.5060.53
* Operating System and version: macOS Big Sur v11.6

**Comment by phiz71** [comment]
✅  Tested on dev-env 3.18.x
