### ISSUE TITLE
[gateway] Websocket connection error when reaching a non secure endpoint

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#8228]
## :collision: Describe the bug
When you have a websocket endpoint in your API and test using Postman, you will be able to connect but the moment you send a Request you will get a 400 error Response.

## :sunrise_over_mountains: To Reproduce
1. Enable websocket in the GW gravitee.yml file

![image](https://user-images.githubusercontent.com/57534152/181504821-e4d9d39d-e019-4b5c-896b-03871b878461.png)

2. Use this WS https://www.bitstamp.net/websocket/v2/ , this is a chat WS so when we send a specific json body it will reply. ( https://www.bitstamp.net/websocket/v2/ )
3. Test in 3.10.15(works well) and 3.18 or 3.15 to compare. 

![image](https://user-images.githubusercontent.com/57534152/181505342-de13368a-13e1-4a6d-a38c-ac50f0f6a3b9.png)

![image](https://user-images.githubusercontent.com/57534152/181505294-a69d9411-e87e-4b9a-9e1c-9c9c1020f21e.png)

## :rainbow: Expected behavior
We should be able to use websocket without any issue.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: Docker-Desktop
 - OS: Windows 11
 - Browser: Google Chrome
## :warning: Potential impacts

***What are the impacted versions?***
- 3.15.X and 3.18.X

**Comment by marijatimovska** [comment]
Please contact me so I can provide more information on this ticket.

**Comment by phiz71** [comment]
It seems that the bug occurs only when `requestTimeout` is set. @marijatimovska do you confirm ?

**Comment by gaetanmaisse** [comment]
After some extra investigation, it looks like there are more issues than just the `requestTimeout` ones, I will update the description of this issue accordingly

**Comment by gaetanmaisse** [comment]
Tested on 3.15.x, it looks ok. But it appears that connecting to WS server behind a redirection isn't easy... it's working with Postman but wasn't able to connect using `curl`, `ws`, `wscat` 🤷🏻
