### ISSUE TITLE
[SME] Mock async endpoint

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#8229]
## Global requirements 

In order to be able to test entrypoints independently of the endpoints, the objective is to be able to simulate an async backend
The scenario we are trying to recreate is to use this mock endpoint in a end to end scenario where we can create an async API with API definition in which we declare the mock endpoint in the endpoints section of the definition.
We should be able to subscribe to the newly created API (SSE entry point) and the consumer should received the events emitted by the mocked endpoint.

## Additional information 
We'd like to have an endpoint that emits a message on a fixed time cadence. 

## Extra Tasks
- [x] Develop an endpoint invoker
- [x] Implement basic endpoint connector resolver (based on entrypoint / endpoint compatibility)
- [x] Invoke the endpoint connector (should be the mock endpoint connector in our case)
- [x] Handle endpoint configuration

## Acceptance Criteria
- [x] Have the ability to create a Mock endpoint as part of an API creation.
- [x] Cadence will be defined in the configuration
- [x] Message content will be defined in the configuration
- [x] Message count will be defined in the configuration (if no message count is specified, there is no limit)

**Comment by marcambier** [comment]
Here is the postman collection to create an API with a mock endpoint, with a published keyless plan, and deploy it.
[Mock_endpoint.postman_collection.zip](https://github.com/gravitee-io/issues/files/9371494/Mock_endpoint.postman_collection.zip)

**Comment by LiliaEn** [comment]
Tested on default env v3.19.0
The following scenarios were covered:
- Create an API with a mock endpoint
- Create and publish a Keyless plan for the API
- Start the API
- Call the API using curl command and "Accept: text/event-stream" header
- Checked that the message content defined in the API configuration is displayed
- Checked that the message count defined in the API config is correctly applied
- Checked that an error is displayed when trying to create an API with a dummy endpoint/endpoint group
