### ISSUE TITLE
China does not show correctly on default Geo dashboard

### ISSUE THREAD

**Issue by zhangkuansky** [gravitee-io/issues#8230]
# Describe the bug

I deploy the Gravitee system by docker-compose (images from docker hub), 3.18 (and 3.10, 3.6); at first, all countries are shown on the default Geo dashboard. But after API is called by different ips (country), China does not show correctly on the default Geo dashboard. The color turns white instead of blue.

!<span class="error">[image]</span>([https://user-images.githubusercontent.com/68380400/181516967-eab4fca9-512a-443e-a868-fb9c21ed23f0.png](https://user-images.githubusercontent.com/68380400/181516967-eab4fca9-512a-443e-a868-fb9c21ed23f0.png))

To simulate calls from Asia, you can use the following script: 

<div class="preformatted panel" style="border-width: 1px;"> 
 <div class="preformattedContent panelContent"> 
  <pre>#!/usr/bin/env bash
for (( i = 0; i &lt; 200; ++i )); do
    for (( VAR = 0; VAR &lt; 200; ++VAR )); do
        curl -s YOUR_GW_ENDPOINT -H "X-Forwarded-For: 1.0.${VAR}.1"
    done
done</pre> 
 </div> 
</div>

**Comment by gaetanmaisse** [comment]
I'm super late to the party, but I was able to reproduce the issue, and it looks related to the country code CN not being unique. For details, see: https://www.highcharts.com/forum/viewtopic.php?t=33579#p117910
