### ISSUE TITLE
[Jupiter] regression: somes plans are not usable

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#8232]
**Steps to reproduce**
- Create an API in Jupiter mode, with an Api key plan and a JWT plan
- Create an simple application with client_id matching JWT plan configuration
- Subscribe app to the Api Key plan
- Subscribe app to the JWT plan
- Try to call the API using Api key
- Try to call the API using JWT plan
- Pause the API key subscription
- Try to call the API using Api key
- Try to call the API using JWT plan

**Current result**
- Get unexpected 401 unauthorized on the JWT call

**Expected result**
- Both API calls should work while related subscription is not paused

**Comment by RubenMMSantos** [comment]
Issue verified and confirmed as fixed.
Pausing the API key does not have any impact on JWT subscription.
Pausing JWT subscription does not have any impact on API Key subscription.
verified on APIM 3.19
