### ISSUE TITLE
[gateway] [http-callout] When payload in policy contains accents the payload gets truncated

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#8235]
## :collision: Describe the bug
When you configure HTTP Callout Policy for example on the Login Flow on an application on AM and the request body contains letter/s with accents the body will bet truncated.

Related/Similar issue https://github.com/gravitee-io/issues/issues/8109

## :sunrise_over_mountains: To Reproduce
1. Create a domain and an application on AM side, configure what you need to make it work.
2. Go to Design -> Flows -> Login.

![image](https://user-images.githubusercontent.com/57534152/181731136-4491b61f-0593-42d6-8e64-8d09d150c209.png)

3. On post login choose and configure HTTP Callout Policy.

![image](https://user-images.githubusercontent.com/57534152/181731332-98639163-fb09-4dac-a756-375becc571c6.png)

-Request Body:

```
{
	"users": [{
		"sso_infos": "test",
		"last_name": "test",
		"first_name": "tést",
		"role": "test",
		"service_code_geo": "tést",
		"perimeter": "test",
		"template": "test",
		"access_code": "test",
		"application_id": "test",
		"idp": "{}"
	}]
}
```

- Post Method
- URL : https://webhook.site/
- Exit on Error: true

4. Create a user related to the domain and initiate a login flow:

![image](https://user-images.githubusercontent.com/57534152/181731799-8f6afa73-c25c-4391-8fa4-2924b3dad116.png)

5. In webhooks you will get the request, to compare remove the accents and test again you will get the full body.

## :rainbow: Expected behavior
Letter/s with accents should not truncate the payload.

## :computer: Desktop:

***Please complete the following information:***
 - Environment: Docker-Desktop
 - OS: Windows 11
 - Browser: Google Chrome

## :warning: Potential impacts

***What are the impacted versions?***
- 3.17.3, 3.18.0

**Comment by gaetanmaisse** [comment]
Should be fixed by https://github.com/gravitee-io/gravitee-policy-callout-http/pull/47 (related to https://github.com/gravitee-io/issues/issues/8109)

**Comment by patelami** [comment]
Env: 3.18.x
Result: PASS

We can now see full  JSON body. 
<img width="377" alt="Screenshot 2022-08-31 at 15 29 23" src="https://user-images.githubusercontent.com/14215437/187703900-57b802c2-47bf-4977-8d2f-2ab3b144aae9.png">
