### ISSUE TITLE
Implement new plugin type to deal with EntryPoint

### ISSUE THREAD

**Issue by guillaumelamirand** [gravitee-io/issues#8238]
## :rainbow: Feature

As an developer 
I want to be able to propose new kind of entrypoints
So that my client can propose new async api based on this new entrypoint

## :sunrise_over_mountains: Additional information

- [x] This new plugin should be located inside apim mono repository, and it could be under <del>`gravitee-api-management / gravitee-apim-connectors / gravitee-apim-connectors-entrypoints`</del> > `gravitee-apim-plugins/gravitee-apim-plugins-entrypoint`
- [x] Existing gravitee-plugin-connector is a good starting point
- [x] Add this new module to sonar coverage; Update circle ci if required to build it.
- [x] New interfaces would be required to properly define an entrypoint .
Those interfaces could be : 
- EntryPointConnectorFactory
  - supportedApiType():  list the supported api types
  - supportedMode(): list the supported modes 
    - ConnectorMode : REQUEST_RESPONSE, PUBLISH or SUBSCRIBE
  - create(): allow to create a connector instance
- EntryPointConnector
  - accept(): check if the current request is supported and return a complexity information to allow resolution priority. For example, http get has only one criteria (GET method) while SSE has 2 ( GET method and Content-type) so both could be the request but because SSE has more criteria it should be evaluated first.
  - handleRequest(): should be implemented while new request is made by a customer for example to transform incoming buffer into messages
  - handleResponse(): should be implemented to adapt client response for exemple to transform outgoing messages to buffer
- [x] Existing HandlerEntrypoint resolution should be renamed to HttpAcceptor.
- [x] Prepare the entry point connector resolver based on those new interfaces

## :superhero: Acceptance criteria

- [x] I am able to implement new entrypoint plugin
- [x] Entrypoint configuration is validated using new plugin while creating/updating an api
- [x] I am able to list all available entrypoints and access to their configuration (same as /connectors)

**Comment by guillaumelamirand** [comment]
To be aligned with AM, we will use gravitee-apim-plugins/gravitee-apim-plugins-entrypoint as module names.

**Comment by guillaumelamirand** [comment]
EntryPointConnector#accept() has been split into two methods :

- matchesCriteria(): which should return the number of criteria to match the context (should always return the same value)
- matches(): which check if the given context matches the criteria

**Comment by guillaumelamirand** [comment]
Current status of the implementation:
- entrypoint plugin framework has been implemented
- entrypoint configuration while creating an new api is validating with the related entrypoint plugin available
- Api V4 deploiment has been implemented
- AsyncApiReactor has been implemented to be able to call an async api
- SSE Entrypoint has been implemented

Remaining work:
- unit tests could be added here and there 
- Update test sdk to be able to deploy api v4 #8286
- Update test sdk to handle entrypoint #8249
- Implement some integration test to validate new execution chain for async api

**Comment by LiliaEn** [comment]
Tested on default env v3.19.0
New SSE entrypoint is implemented and working as expected when creating/updating an async API.
![Screenshot 2022-08-11 at 08.28.28.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/66b08c20-5410-4c8a-ab0e-2857061e3ae4)
