### ISSUE TITLE
[Gateway Testing SDK] Add the capability to register new entrypoint plugin

### ISSUE THREAD

**Issue by guillaumelamirand** [gravitee-io/issues#8249]
### Expected Behavior

I should be able to register connectors (entrypoints/endpoints) in order to test them in a runtime gateway.

### Current Behavior

Nothing is implemented yet.

### Possible Solution

In case of testing a non connector component (policy for example), we should ensure a default one is set to the api and registered to the gateway.

### Context

This is required du to the introduction of the new entrypoint connector for SME.

**Comment by gaetanmaisse** [comment]
Nothing to test on QA side as it was pure technical tooling to be able to write integration tests for async API.
✅  Simple SSE integration test is working.
