### ISSUE TITLE
[Async] [Websocket entrypoint] Send messages

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#8255]
## :rainbow: Feature

As an API Consumer, I want to send messages through my websocket connection establish on a AsyncAPI.

## :sunrise_over_mountains: Additional information

- Format messages supported 
  - Binary
  - Text

## :superhero: Acceptance criteria

- [ ] Given an Async API using a WS entrypoint Then I can publish messages through the WS connection.

**Comment by LiliaEn** [comment]
This ticket was tested together with https://github.com/gravitee-io/issues/issues/8254
Tested on default env v3.20.0 
The following scenarios were covered using Kafka endpoint and websocket entrypoint:
1. Entrypoint config:
- Subscriber = true
-  Publisher= false
Endpoint:
- Producer: false

“Binary” messages are sent/received in Postman, and the Text messages created manually, no message is displayed in Kafka UI

2.Entrypoint config:
- Subscriber = true
- Publisher= true
Endpoint:
- Producer: true

“Binary” messages are sent/received in Postman, and the Text messages created manually
Messages are displayed in Kafka UI 

3. Entrypoint config:
- Subscriber = false
- Publisher= true
Endpoint:
- Producer: true

Binary messages are not sent/received. Text messages are sent/received.
Messages are received in Kafka UI

4. Entrypoint config:
- Subscriber = false
- Publisher= false
Endpoint:
- Producer: true

The connection is established and closed in the same time

5. Entrypoint config:
- Subscriber = true
- Publisher= true
Endpoint:
- Producer: false

No messages are received in Kafka UI
Text and Binary messages are sent/received in Postman

A few scenarios covered using Mock endpoint:
1. Entrypoint config:
- Subscriber = true
- Publisher= false

Getting Text and Binary messages in Postman
No message in the logs

2. Entrypoint config:
- Subscriber = true
- Publisher= true
Getting Text and Binary messages in Postman.
Messages are displayed in the logs
