### ISSUE TITLE
[Async] [Websocket entrypoint] Secure connection

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#8256]
## :rainbow: Feature

As an API Publisher, I want my consumers subscribe to my WS entrypoint using SSL in order to establish a secure connection.

As an API Consumer, I want to connect through SSL in order to establish a secure connection with the AsyncAPI.

## :sunrise_over_mountains: Additional information

- Configuration for API_Publisher
- Connection for API_Consumer
- Authentication headers are properly propagated: https://community.gravitee.io/t/apim3-websockets-stomp-security-copying-http-headers-for-ws/696/8

## :superhero: Acceptance criteria

- [ ] Given an Async API using a WS entrypoint Then i can connect to it using SSL

**Comment by LiliaEn** [comment]
Closing the ticket as this is just a setup in the gateway yml file.
