### ISSUE TITLE
[Async] [SSE entrypoint] Connection

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#8258]
## :rainbow: Feature

As an API Consumer, I want to establish a SSE connection to an Async API

## :superhero: Acceptance criteria

- [x] Given an Async API configured with a SSE entrypoint then my connexion should keep alive even if there is no events processed

## Remaining tasks

- Update test sdk to be able to deploy api v4 #8286
- Update test sdk to handle entrypoint #8249

**Comment by guillaumelamirand** [comment]
This has been partialy implemented with #8238

**Comment by LiliaEn** [comment]
Tested on default env v3.19.0.
Working as expected
![Screenshot 2022-08-10 at 10.36.45.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/946edb7e-7d2a-4789-9638-87b01092f89b)
![Screenshot 2022-08-10 at 10.37.14.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/00c840ad-92cb-4cdc-97ed-ce5bba6283b3)
