### ISSUE TITLE
[Async] [SSE entrypoint] Receive message

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#8259]
## :rainbow: Feature

As an API Consumer, I want to received message through my SSE connection

## :sunrise_over_mountains: Additional information

- Format message dependant of endpoint messages

## :superhero: Acceptance criteria

- [x] Given an Async API configured with a SSE entrypoint then I see events coming from the API When i properly connect to the API via SSE.

**Comment by guillaumelamirand** [comment]
Has been implemented with #8258. See there for further details.

**Comment by LiliaEn** [comment]
Tested on the default env 3.19.0
Events are correctly received
![Screenshot 2022-08-10 at 10.07.18.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/89869e03-b9e0-4c66-9114-8e8084feaca2)
![Screenshot 2022-08-10 at 10.07.29.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/0022bb04-0f90-49a1-a55a-832fd772bc80)

**Comment by LiliaEn** [comment]
Tested on the default env 3.19.0
Events are correctly received
![Screenshot 2022-08-10 at 10.07.18.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/89869e03-b9e0-4c66-9114-8e8084feaca2)
![Screenshot 2022-08-10 at 10.07.29.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/0022bb04-0f90-49a1-a55a-832fd772bc80)
