### ISSUE TITLE
[management] Response template config asks for Content-Type but Accept header param is taken into account instead

### ISSUE THREAD

**Issue by ctschacher** [gravitee-io/issues#8263]
### Description
When creating a custom response template the GUI asks you to enter a `Content-Type` but that seems to be misleading since it's not the Content-Type that triggers a specific response template but instead it's the `Accept` header key that matters. 

![Screenshot 2022-08-01 at 12.11.26.png](https://images.zenhubusercontent.com/6109168564d750632be5206b/9668f6d7-42f0-4c65-90f4-c8e25bff351d) 

### Steps to Reproduce 
1. Create an API with a rate-limit (e.g. 3 requests per 30 seconds)
2. In Proxy settings click on Response Templates
3. Specify a content type other then the default `*/*` (e.g. `application/json`), fill the rest as you like
4. Call that API with the previously specified content type & trigger an error by sending more than 3 requests

### Expected Behavior
When the error is triggered I should see the response that was configured.

### Observed Behavior
Instead of the configured response you'll see the standard response for that error (`429 - Rate limit exceeded ! You reach the limit of 3 requests per 30 seconds`)

### Your Environment
* Version used: 3.10, 3.18
* Browser Name and version: Chrome v103
* Operating System and version: MacOS 12.4

**Comment by gaetanmaisse** [comment]
Tested, looks good

![image](https://user-images.githubusercontent.com/4112568/183853164-fe982882-d0ca-4761-be4c-ba7b1dfcb4ba.png)
