### ISSUE TITLE
[AM-MFA] MFA Support for Phones Numbers with Extensions

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#8266]
## :rainbow: Feature

This is an enhancement for the MFA feature.

- Use case :
  Enrollment screen for a twillio phone factor should offer an optional field to enter an extension.  If an extension is present in the user's enrollment data, the MFA call should then utilize Twillio's sendDigits function to direct the call to the extension before playing the audible message containing the MFA code.  
- Impact :
  We are an insurance company in the process of implementing MFA for our Agencies.  There is a subset of agencies that are firm on not requiring the involvement of a personal device for MFA.  The best solution for these users will be to offer a phone call factor to their office phone and in many cases this will require extension support.  This would greatly improve adoptability and user acceptance of MFA for our user base. 
- Criticality :
   While there may be other work-arounds for the set of users that would like this feature, extension support is the solution that would provide the least amount of friction to adoption of MFA.  As a company that works with independent agents, these agencies have the option of choosing other insurance carriers over us and the user friendliness of our agency systems is a large factor in that decision.  This feature is very important to maintaining the usability of our systems for our independent agents. 

## :white_check_mark: Acceptance criteria

- [ ] Given '...' When '...' Then '...'

## :ballot_box_with_check: Developer sub-tasks 

- [ ] Jest test for acceptance criteria

**Comment by apoddany** [comment]
closing as raised as a FR to AM PO
