### ISSUE TITLE
[management] User locale claims isn't taking into account

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#8268]
When a user has the standard claim "locale", then this value is used to initialize the preferredLanguage field if this preferredLanguage field is null. Due to this behaviour, If the "locale" claim is updated, the preferredLanguage field will not be updated as it is not null anymore.

### Expected Behavior

The preferredLanguage takes precedence on the locale claim value.
So the preferredLanguage must remain null even if the locale claim exists.

### Current Behavior

The preferredLanguage takes the value of the locale claim during the user creation/authentication and can't be update

### Steps to Reproduce (for bugs)
1. Create a user with the locale claim
2. run authentication flow for this user
3. check the user collections/table, the user profile should have the preferredLanguage equals to the locale claim
4. update the claims in the user profile
5. run authentication flow for this user
6. check the user collections/table, the user profile should have the preferredLanguage equals to the first value of the locale claim (not the new one) --> preferredLanguage isn't updated

**Comment by omatthewsgravitee** [comment]
On hold until Eric returns

**Comment by patelami** [comment]
Env: 3.19.0
Result: PASS

Given I have created user with local = fr in user profile
And my browser is set in EN
Then I should receive email in french

Given I have created user with local = en in user profile
And my browser is set in FR
Then I should receive email in english

Given I have set locale to en 
and preferredLanguage to fr
Then I should always see emails in FR
