### ISSUE TITLE
Platform alerts never triggered

### ISSUE THREAD

**Issue by Okhelifi** [gravitee-io/issues#8269]
Here is a simple platform alert
![Screenshot 2022-08-02 at 09.10.09.png](https://images.zenhubusercontent.com/606db0512360be8646b6dd7a/0d092789-92f6-4788-ba7b-7cf3c602cf5a)

This alert should be fired each time the status of an api change. However we filter the alert triggers with the organizatio and environment value even if this is something we don't send to AE. That's why this alert is never fired.

### Expected Behavior
We should fire the alert when it's necessary.

### Current Behavior
The platform alerts are never fired

### Steps to Reproduce (for bugs)

1. create an api
2. activate heath check on the api
3. activate alerts in the organization settings
4. create a platform alert based on heath checks
5. try it.

This test can be done with multiple organizations and environments to be sure that we trigger the good ones according to the alert definition

**Comment by gaetanmaisse** [comment]
Tested on 3.18 env and was working fine ✅
