### ISSUE TITLE
[regex-threat-support-policy] Policy failed silently on a call with a boolean parameter

### ISSUE THREAD

**Issue by gcusnieux** [gravitee-io/issues#8272]
## :collision: Describe the bug
The policy failed silently on a call with a boolean parameter (with no value)

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Create and deploy an api with regex-threat-support-policy on flow `/**`
2. Call the api `curl http://localhost:8082/myapi?refresh`
3. See error `500`

## Current behaviour
A clear and concise description of what is currently happening.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: [e.g. 3.10.x]

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by gaetanmaisse** [comment]
Tested on 3.10 env, ✅
