### ISSUE TITLE
[Jupiter] HTTP Request timeout adjustments

### ISSUE THREAD

**Issue by ytvnr** [gravitee-io/issues#8273]
## :rainbow: Feature

This [issue](https://github.com/gravitee-io/issues/issues/7988) implied the deletion of the ability to be able to use an infinite timeout.

The aim of this issue is to fix that:

- [x] In V3 Mode (jupiter fully disabled), keep the behaviour: if `http.requestTimeout` is `unset` or `<=0`,
  - then timeout is disabled
  - add a warn in the logs saying that a proper timeout should be set, we recommand 30000ms.
- [x] If Jupiter enabled (both jupiter mode or v3 compatibility), if `http.requestTimeout` is `unset`, then we should:
  -  use a default 30000ms timeout
  - add a warn log indicating we chose this value because no was set
- [x] If Jupiter enabled (both jupiter mode or v3 compatibility), if `http.requestTimeout` is `<=0`, then we should:
  -  disable timeout
   - add a warn in the logs saying that a proper timeout should be set, we recommand 30000ms.

**Comment by LiliaEn** [comment]
The following scenarios were covered:
V3
- Timeout not set- warning message is displayed
![Screenshot 2022-08-08 at 13.15.56.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/3be2fe26-bac5-4506-856e-7e1b1de1cb87)
![Screenshot 2022-08-08 at 13.16.39.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/3bfa88dc-2b62-461e-baa0-066f95f43736)
- Timeout set to 0 - warning message is displayed
![Screenshot 2022-08-08 at 13.16.23.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/fb7dc1f0-214d-4ccb-9b05-04e9e2873d22)
![Screenshot 2022-08-08 at 13.16.39.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/f3244ada-acab-4917-9507-e1d41d0b1f6b)
- Timeout set above 0 - no warning message is displayed
- Timeout set above the default value (over 30000) - no warning message is displayed

Jupiter Mode
- Timeout not set- warning displayed that timeout cannot be unset
![Screenshot 2022-08-08 at 13.28.49.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/cb5f353d-e2bb-435e-ac2b-e0c6120efb65)
![Screenshot 2022-08-08 at 13.09.17.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/1ecef43e-fdc1-4025-afd6-43e51b1f613c)
- Timeout set to 0 - warning displayed that a value greater than 0 should be set
![Screenshot 2022-08-08 at 13.28.37.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/7b875c47-f3bf-4981-b820-59c3c8843581)
![Screenshot 2022-08-08 at 13.10.26.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/0d04eaf9-c31c-438a-b3bc-809b0c5e8adc)
- Timeout set to less than 0 - warning displayed that a value greater than 0 should be set
- Timeout set above 0 - no warning message
- Timeout set above the default value - no warning message

**Comment by LiliaEn** [comment]
Some more scenarios covered:

- Timeout set to 0 or less (which means no timeout) -> Used Latency policy and set the time duration to 31000ms- when calling the API, no error is displayed
- Timeout not set (defaults to 30000)-> Used Latency policy and set the time duration to 31000ms- when calling the API, 504 error is displayed
- Timeout set to 2000ms-> Updated the BE timeout to 3s- when calling the API, 504 error is displayed
- Timeout set to 2000ms-> Used Latency policy with time duration 2100- when calling the API, 504 error is displayed
- Timeout set to default value-> Updated the BE timeout to 10s and used Latency policy with time duration 21000ms when calling the API, 504 error is displayed
- Timeout set to default value-> Updated the BE timeout to 8s and used Latency policy with time duration 20000ms when calling the API, no error is displayed
