### ISSUE TITLE
[Gateway Testing SDK] Add the capability to deploy api v4

### ISSUE THREAD

**Issue by guillaumelamirand** [gravitee-io/issues#8286]
Expected Behavior
I should be able to create and deploy api V4 in order to test them in a runtime gateway.

Current Behavior
Nothing is implemented yet.

Context
This is required du to the introduction of the new api definition V4 and is mandatory to test everything that will be implemented for SME.

**Comment by gaetanmaisse** [comment]
Nothing to test on QA side as it was pure technical tooling to be able to write integration tests for async API.
✅  Simple SSE integration test is working.
