### ISSUE TITLE
[API Definition V4] Subscribe to V4 APIs

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#8287]
## :rainbow: Feature

As API Consumer, I want to subscribe to a V4 API.

## Acceptance criteria

- [x] Be able to subscribe to v4 api
- [x] Be able to manage subscriptions to v4 api
- [x] No impact on v2 api 

## :sunrise_over_mountains: Additional information

- PlanService has been duplicated to handle the new PlanEntity
- New plan entity has been introduced because of the new flow (pre/post removed by request/response/subscribe/publish)
- Must find a way to create a MetaPlan object with flow dependencies
- Current SubscriptionService uses v2 apiService and PlanService so having MetaPlan could factorize the PlanService for managing subscription

## :telescope: Out of scope

- Subscribe to a api v4 with subscription listener and webhook entrypoint

## :warning: Potential impacts

- Subcribing to V2 APIs must continue to work

:rocket:

**Comment by guillaumelamirand** [comment]
In order to test you can use the following collection:
[https://app.zenhub.com/files/61280156/f3b215b2-6f3e-4aea-85f6-8f2011711eb9/download](https://app.zenhub.com/files/61280156/f3b215b2-6f3e-4aea-85f6-8f2011711eb9/download)

**Comment by LiliaEn** [comment]
Tested on default env v3.19.0
The following scenarios were covered:
- Creating v4 API
- Creating API Key plan
- Publishing the plan
- Start and Deploy the APi
- Create an application
- Subscribe to API
- Get the API Key
- Call the API
- Create a Keyless plan and try to subscribe- error is displayed
- Call an API that requires api key, without the key- no data is returned but the error messages will be handled in another ticket
- Created 2 API Key Plans and subscribed to 2 different apps
- Called the API using the 2 APi keys
- Create a new API in UI (V2) with an API Key Plan and a new app
- Subscribed V2 API to an app
