### ISSUE TITLE
[management] [multi-languages] UI languages

### ISSUE THREAD

**Issue by omatthewsgravitee** [gravitee-io/issues#8289]
## :rainbow: Feature

**As a** 'security domain owner'

**I want to** '.create, update and delete dictionaries and their translations in the management UI'

**So that** 'I can propose new translations for my form and email templates'

## :sunrise_over_mountains: Additional information

[Figma screen design](https://www.figma.com/file/PKtV6NcsNzGBuzV3cmGHJj/Custom-login?node-id=808%3A2753)

## :white_check_mark: Acceptance criteria

- [ ] Given 'a security domain owner wishing to create a new translation dictionary' Then 'an empty dictionary is created' When 'I click on ADD A NEW LANGUAGE button'
- [ ] Given 'a security domain owner wishing to add a new entry in the dictionary' Then 'a new entry (key, value) is added to the selected dictionary' When 'I click on ADD A NEW TRANSLATION and SAVE CHANGES button'
- [ ] Given 'a security domain owner wishing to remove an entry in the dictionary' Then 'the entry has been removed' When 'I click on the remove icon and the SAVE CHANGES button'

## :ballot_box_with_check: Developer sub-tasks 

- [ ] Jest test for acceptance criteria

**Comment by tcompiegne** [comment]
Comments from my current review : 

- The **Translations** section should only be visible if there is at least one language
- Missing SAVE CHANGES button for the add dictionary action
- Both SAVE CHANGES should turn blue after clicking on the ADD button from the dialog component

**Comment by patelami** [comment]
Env: Nightly
Result: PASS

 Given 'a security domain owner wishing to create a new translation dictionary' Then 'an empty dictionary is created' When 'I click on ADD A NEW LANGUAGE button'

 Given 'a security domain owner wishing to add a new entry in the dictionary' Then 'a new entry (key, value) is added to the selected dictionary' When 'I click on ADD A NEW TRANSLATION and SAVE CHANGES button'

 Given 'a security domain owner wishing to remove an entry in the dictionary' Then 'the entry has been removed' When 'I click on the remove icon and the SAVE CHANGES button'
