### ISSUE TITLE
Improve code quality and test coverage on entrypoints work

### ISSUE THREAD

**Issue by Sicofonia** [gravitee-io/issues#8291]
Remaining work :

- [x] Add missing java doc where missing on new interface
- [x] Add missing jacaoco plugin or coverage on plugin repository
- [x] Handle http/2 connection on SSE connectors by calling writeHeaders method to sanitize
- [x] Rename model class where prefix should be the specialization for example ListenerHttp > HttpListener
- [x] New sonar projet regarding plugin doesn't work : https://app.circleci.com/pipelines/github/gravitee-io/gravitee-api-management/10301/workflows/e59adee9-e5b6-4eb6-920e-b69bb507c359/jobs/131930
- [x] Improve code coverage see https://sonarcloud.io/summary/new_code?id=gravitee-io_gravitee-api-management_rest-api&pullRequest=2255 and https://sonarcloud.io/summary/new_code?id=gravitee-io_gravitee-api-management_gateway&pullRequest=2255 
- [x] fix and reactivate SseEntrypointConnectorTests

**Comment by marcambier** [comment]
@ytvnr, SseEntrypointConnectorTests were failing, so I had to disable them while working on entrypoints [here](https://github.com/gravitee-io/gravitee-api-management/blob/master/gravitee-apim-plugin/gravitee-apim-plugin-entrypoint/gravitee-apim-plugin-entrypoint-sse/src/test/java/io/gravitee/plugin/entrypoint/sse/SseEntrypointConnectorTest.java#L47)
I let you have a look at that in this ticket.

**Comment by guillaumelamirand** [comment]
Draft PR has been created to fix SSE tests: https://github.com/gravitee-io/gravitee-api-management/pull/2381

**Comment by guillaumelamirand** [comment]
Coverage on plugin seems to be working: https://sonarcloud.io/component_measures?id=gravitee-io_gravitee-api-management_plugins&metric=new_coverage&pullRequest=2374&view=list

**Comment by gaetanmaisse** [comment]
Closing it as it was only a technical task
