### ISSUE TITLE
[policy][oauth2] Error when token expiration is greater then cache TTL

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#8295]
**Steps to reproduce**
- Add a cache resource on your API with TTI an TTL set to 60 seconds
- Add a oauth2 resource on your API
- Set an Oauth2 plan using this oauth2 resource and cache resource
- Try to use this oauth2 plan by calling the API

**Current behavior**
Gateway doesn't answer and fails with error :
```
com.google.common.base.VerifyException: single ttl can't be bigger than ttl defined in the configuration
	at com.google.common.base.Verify.verify(Verify.java:126)
	at io.gravitee.node.cache.standalone.StandaloneCache.put(StandaloneCache.java:129)
	at io.gravitee.resource.cache.inmemory.InMemoryCacheDelegate.put(InMemoryCacheDelegate.java:68)
	at io.gravitee.policy.oauth2.Oauth2Policy.handleSuccess(Oauth2Policy.java:254)
```

**Expected behavior**
To avoid this error,
If time to token expiration time is greater than cache TTL,
Cache element TTL should be set to cache TTL.

**Comment by mouligno** [comment]
Something linked to : https://github.com/gravitee-io/issues/issues/7907 ?

**Comment by marcambier** [comment]
@mouligno ,
Nice catch. At a first glance, it's the same problem, but in another policy;

**Comment by LiliaEn** [comment]
Tested on 3.15.x env
No error is displayed when token expiration is greater than cache TTL.
