### ISSUE TITLE
In some situation the order of upgrader is not respected

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#8299]
# Describe the bug

If we have 2 upgraders U1 and U2, and U1 must run before U2\. (a classic use case) If we have 2 m-API M1 and M2 start (99.99% of deployments) if U1 takes time to be executed we will have this scenario:

*   M1 run U1 and set the status of this upgrader to RUNNING
*   M2 tries to run U1, and because it runs, he starts U2

# Expected behaviour

respect the order

# Current behaviour

we don't control the order

**Comment by gaetanmaisse** [comment]
The solution could be not to start another upgrader if one is already running

**Comment by gaetanmaisse** [comment]
The new Upgrader Framework has been implemented in the `master` branch of APIM, closing this issue as it will be fixed as soon as APIM 4.0 is out
