### ISSUE TITLE
[gateway] Sub context path based routing

### ISSUE THREAD

**Issue by AnselmeDewavrin** [gravitee-io/issues#83]
Hi all,

I wish I had a routing to different backends, based on the right part of the context path:

/products/all leads to server1 or server2
/products/part leads to server3 or server4

Of course it's already possible to create 2 apis to do this, but this would be great to do this in only 1 api, for clarity's sake.

I know it's planned to use properties to store backend urls attached to each right-part of context paths, but I think this will impeach connection pooling... This is why I'd rather suggest a additionnal column in the http load-balancing configuration table, that would contain a right-part context path patern matcher.

Anselme

**Comment by brasseld** [comment]
Hi @AnselmeDewavrin,

According to the new policy [Dynamic routing](https://github.com/gravitee-io/issues/issues/87), do you think this issue is still relevant ?

**Comment by AnselmeDewavrin** [comment]
Hi David,
No, you're right the dynamic routing policy fulfills this need.
Thanks,
Anselme

**Comment by brasseld** [comment]
Closed according to user's feedback.
