### ISSUE TITLE
[management] Temporary: allow null value for host in virtual-hosts

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#8300]
Previously, we fixed these two issues:
https://github.com/gravitee-io/issues/issues/7139
https://github.com/gravitee-io/issues/issues/7856

Unfortunately, it has been a breaking change for some users, since they used this bug to achieve a "multi context-path" feature.

This issue is there to rollback what have been done (except for a part in the UI).

A github issue will be created to propose a new feature that will prevent the host of a virtual-host to be null and in the same time, allow some users to have a multiple context-path feature.

### Expected Behavior
After this rollback, a user should be able to create virtual-host with a null or empty value

### Current Behavior
Currently, a user is not allowed to create virtual-host with a null or empty value

### Steps to Reproduce (for bugs)
1. Create an API
2. Go to Proxy settings of this API
3. In the Entrypoint menu, switch to virtual-hosts mode
4. Create a listening path, with no host and /foo as path
5. Create a listening path, with no host and /bar as path
6. Save and deploy

The API should be deployed and callable with `GATEWAY_URL/foo` and `GATEWAY_URL/bar`

### Your Environment
* Version used: 3.18.4

**Comment by gaetanmaisse** [comment]
Tested on 3.18.x env, everything is ok ✅
