### ISSUE TITLE
 Gateway platform policy does not take effect

### ISSUE THREAD

**Issue by Tank-zhu** [gravitee-io/issues#8302]
## :collision:  versions?
>  3.15.9

## :collision: Describe the bug
>  I created a whitelist on the platform policy but it didn't take effect

![image](https://user-images.githubusercontent.com/10337065/183852987-d0e739e0-a69e-4e41-8cc0-2493c77207e2.png)

![image](https://user-images.githubusercontent.com/10337065/183853100-e3c7b377-5a50-4027-a419-72f58da37515.png)

## Current behaviour
![image](https://user-images.githubusercontent.com/10337065/183853174-3c90634a-c9db-4d21-b4f2-983ddfe39e8f.png)

## :rainbow: Expected behaviour
![image](https://user-images.githubusercontent.com/10337065/183855486-25df93ab-78f4-479a-90c7-acf5ac452989.png)

## :collision: After code tracking, it is found that the [**pathinfo**] method is always empty, which causes the policy to fail.

![image](https://user-images.githubusercontent.com/10337065/183853274-5862f7a7-d42e-4d4c-9dde-f0097f5ae2aa.png)

![image](https://user-images.githubusercontent.com/10337065/183853409-4e93e11d-798e-4312-bb27-c3dd10427025.png)

![image](https://user-images.githubusercontent.com/10337065/183853471-418d7fec-9a83-4f79-9eaf-e80887bcc610.png)

![image](https://user-images.githubusercontent.com/10337065/183853618-2cc85ae6-d7fc-498d-a05b-148e394f4ce3.png)

## :collision: Use the contextPath method to judge as 'true'
```java 

public boolean evaluate(ExecutionContext context, Flow flow) {
        Pattern pattern = cache.computeIfAbsent(flow.getPath(), this::transform);

        return (flow.getOperator() == Operator.EQUALS)
         //contextPath replace pathInfo 
            ? pattern.matcher(context.request().contextPath()).matches()
            : pattern.matcher(context.request().contextPath()).lookingAt();
    }
`
![image](https://user-images.githubusercontent.com/10337065/183856626-45687f3d-de2f-4a18-be66-0df6e800a408.png)

**Comment by gaetanmaisse** [comment]
Quoting @marcambier on that PR: https://github.com/gravitee-io/gravitee-api-management/pull/2521
> I agree with this new behavior which makes more sense to me: the platform flows path includes API context path. Still has to be confirmed by the product team. But it seems it works like that for a while, and this change is not retro-compatible.

After discussion, the Product team is advocating avoiding breaking changes in a maintenance version, it might be done for APIM 4.0 but not for APIM 3.15.
