### ISSUE TITLE
[management] [override theme] [view mode] display default gateway forms if there is no custom ones

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8315]
## :rainbow: Feature

**As a** 'security domain owner'

**I want to** 'starts from the default gateway templates to customize my own templates'

**So that** 'it's easier to configure compare to start from scratch'

## :sunrise_over_mountains: Additional information

- Add gateway templates into the classpath of the Management API

```
formService.findByDomainAndTemplate(domain, formTemplate.template()))
                .defaultIfEmpty(// find form from the classpath)
                .map(form -> Response.ok(form).build())
```

## :white_check_mark: Acceptance criteria

- [ ] Given '...' When '...' Then '...'

## :ballot_box_with_check: Developer sub-tasks 

- [ ] Jest test for acceptance criteria

**Comment by patelami** [comment]
Env: master
Result: PASS

As a user, I should be able to see the default HTML for each page selected in dropdown.
