### ISSUE TITLE
[management] [override theme] [view mode] load gateway assets

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8316]
## :rainbow: Feature

**As a** 'security domain owner'

**I want to** 'get access to the gateway assets'

**So that** 'I can properly preview my custom templates'

## :sunrise_over_mountains: Additional information

- /management/domains/themes/assets/**
- main.css will be duplicated between gateway and management part of AM

## :white_check_mark: Acceptance criteria

- [ ] Given 'a not authenticated HTTP call' When 'GET is requested on an asset to preview a template' Then 'the asset is download'

## :ballot_box_with_check: Developer sub-tasks 

- [ ] Jest test for acceptance criteria

**Comment by patelami** [comment]
Env: Nightly


Given I have selected different colour theme
And I can see it in preview
And I publish the theme
Then I should see this theme implemented **PASS**

Given I have added custom logo
And I  publish it 
Then I should see the logo when I load the application page (fail)

**Comment by tcompiegne** [comment]
Settings have been changed in the QA environment  : https://github.com/gravitee-io/issues/issues/8450

Now everything is fine.
