### ISSUE TITLE
[AM-Registration] User in not able to logging after they have set up an password via the confirmation link (complete reugstation))

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#8321]
## :collision: Describe the bug
When we create a user in our domain and we enable the option "Enable pre-registration" so that the user can setup their own password, later when the user set the password he is not able to login even though the password in 100% correct and this will happen up until the user sets a new password and the option is set to that when a user logins in he will be automatically redirected.

## :sunrise_over_mountains: To Reproduce
1. Create a new domain, application and go to Settings -> Users
2. Make sure you have SMTP setup so you get a mail.
3. Create a user and enable the "Enable pre-registration".
4. Go to your mail and finish the setup.
5. Try to login into your application and you will get an error. 

## :rainbow: Expected behavior
When we create a new user with "Enable pre-registration" we should be able to use the user to login into our application.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material.

## :computer: Desktop:

***Please complete the following information:***
 - Environment: Docker-Desktop - AM (3.15.10, 3.15.11, 3.17.14)
 - OS: Windows 11
 - Browser: Google Chrome

## :warning: Potential impacts

***What are the impacted versions?***
- 3.15.10, 3.15.11, 3.17.14

**Comment by ashraf706** [comment]
The pull request is merged: https://github.com/gravitee-io/gravitee-access-management/pull/2045
