### ISSUE TITLE
[management] NullPointerException when deleting a group - 3.15

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#8323]
backport from #8320 
After a migration from a version < 3.8, when I delete a group, I have this error:
`Cannot invoke "java.util.Set.stream()" because the return value of "io.gravitee.repository.management.model.Page.getAccessControls()" is null`

**Comment by LiliaEn** [comment]
Tested on the v3.15.x
Browser: Chrome Version 103.0.5060.53 , macOS Big Sur v11.6
Working as expected
