### ISSUE TITLE
[APIM-UI] Filters for status codes do not work for the Platform Dashboard for the Line Chart (Response status)

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#8325]
## :collision: Describe the bug
When  we to go our Platform Analytics and go to the Line Chart (Response status) ad choose one error code (filer) all data is still being displayed. 

![image](https://user-images.githubusercontent.com/57534152/185126591-b5dfd39a-c21f-45b2-9c09-af81bbc1e72d.png)

![image](https://user-images.githubusercontent.com/57534152/185126687-7534ac5d-cf1a-4c92-bb32-6322fcc5efb1.png)

## :sunrise_over_mountains: To Reproduce
1. Create a simple API and make few request but make sure you make with more than one status code.
2. Go to Platform Analytics and choose one filter (status code)
3. You will see you still have all the data in the Line chart even though you have a selected filter.

## :rainbow: Expected behavior
When we choose a filter the Analytics should only display data related to the filter not all.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: Docker-Desktop, APIM 3.18.4
 - OS: Windows 11
 - Browser: Google Chrome

## :warning: Potential impacts

***What are the impacted versions?***
- 3.15.13
- 3.18.4

**Comment by RubenMMSantos** [comment]
Issue verified and confirmed has fixed.
When we to go our Platform Analytics and go to the Line Chart (Response status) and choose one error code (filer) only data related to the chosen error is displayed

![Screenshot 2022-08-19 at 15 00 18](https://user-images.githubusercontent.com/14939456/185635398-711c16fc-5bb0-44bb-9f68-f8055474ac9b.png)
