### ISSUE TITLE
[management] The right click menu on side navigation links does not work properly.

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#8326]
## :collision: Describe the bug

The right click menu on the navigation links on the left side of the console (Dashboard, APIs, Applications, Gateways...) does not provide the right menu when hovering on links, hence it is not possible to open links in new tabs.  

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Open APIM console. 
2. Hover the mouse on one of the navigation links on the left.
3. Right click on one of the links.
4. See wrong menu pop up.

## :rainbow: Expected behaviour
When you right click on one of the links on the side you should get the menu for links where you have option to open in new tab.

## Current behaviour
When you right click on one of the links on the side you get the default webpage menu.

## :movie_camera: Useful information
Expected menu:
![image](https://user-images.githubusercontent.com/98313939/185124324-f3168d9e-e0e1-4c28-ba40-bec53db45680.png)
The menu that opens up on right click:
![image](https://user-images.githubusercontent.com/98313939/185124546-1bd45eb3-a401-47d4-97aa-c491b0870e34.png)

## :computer: Desktop:

***Please complete the following information:***
 - Environment: [3.15.13, 3.17.5, 3.18.4]
 - OS: [Docker installation]
 - Browser [Chrome, Firefox]

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

- 3.15.13
- 3.17.5
- 3.18.4

## :link: Dependencies

Link a story or other related things...

**Comment by RubenMMSantos** [comment]
issue verified and confirmed as fixed.
Right clicking on the left menu options now allows to open directly on new tabs
