### ISSUE TITLE
Label issue in the dashboards

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#8327]
## :collision: Describe the bug
When defined a label for a http status in the analytics of the dashboard, expecting to see the label in the dashboard

Instead, seeing only the http status, as label is not defined at all

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Global dashboards
2. Set up a label for http status
3. Call the api 
4. Check in the dashboards if the label defined earlier is present in the dashboards, or only the http status is

## :rainbow: Expected behaviour
Expecting to see the label when defined in the dashboards.

## Current behaviour
There is no label even though it is already defined

## :movie_camera: Useful information
![image](https://user-images.githubusercontent.com/89140082/185137956-72130970-96a8-4edb-b727-e0bb39526bd1.png)

![image](https://user-images.githubusercontent.com/89140082/185138041-2f86e12f-48fb-4096-808e-734eb37f8f67.png)

## :computer: Desktop:

***Please complete the following information:***
 - Environment: [3.18.3]
 - Browser [chrome]

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

- 3.15.13
- 3.18.4

**Comment by RubenMMSantos** [comment]
issue verified and confirmed as fixed.
Label defined for HTTP status is now correctly displayed

![Screenshot 2022-08-19 at 15 08 47](https://user-images.githubusercontent.com/14939456/185636998-b971ee88-a8ee-4ac8-8f77-22e68dbcc3ee.png)
