### ISSUE TITLE
[management] Top APIs and Top Applications in the dashboard are not working as links 

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#8328]
## :collision: Describe the bug
When you open the dashboard in the console to view the APIs or applications by calls, clicking the name of the api/application should work as a link to the api/application. It is just plain text and not a link.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Prepare few apis/applications with few calls to log in the analytics.
2. Open Dashboard>Analytics
3. See widgets Top APIs and Top Applications having just names of apis/apps that are not links to the respective api/app

## :rainbow: Expected behaviour
When you open the Analytics tab in the Dashboard and try to click the names of apis/apps in the mentioned widgets, the names should work as links to the respected apis/apps

## Current behaviour
The names of the apis/apps in the mentioned widgets do not work as links.

## :movie_camera: Useful information
![image](https://user-images.githubusercontent.com/98313939/185160412-2004cdbf-31c9-4882-89f9-bcbb6b231c9f.png)
## :computer: Desktop:

***Please complete the following information:***
 - Environment: [3.15.13, 3.18.4]
 - OS: [Docker Installation]
 

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

- 3.15.13
- 3.18.4

## :link: Dependencies

Link a story or other related things...

**Comment by RubenMMSantos** [comment]
Issue verified and confirmed has fixed.
When user is on Analytics tab in the Dashboard and tries to click the names of apis/apps in the mentioned widgets, the names now work as links to the respected apis/apps

![Screenshot 2022-08-19 at 11 57 53](https://user-images.githubusercontent.com/14939456/185604279-de98084b-133c-4f9b-a1a1-834276926fc4.png)
