### ISSUE TITLE
Server unreachable error is displayed when searching for apps on API- Subscription page, when there are multiple apps with similar name

### ISSUE THREAD

**Issue by LiliaEn** [gravitee-io/issues#8329]
Server unreachable error is displayed when searching for apps on API- Subscription page, when there are multiple apps with similar name

### Expected Behavior
No error should be displayed when searching for apps with similar names

### Current Behavior
Server unreachable error is displayed when searching for apps on API- Subscription page, when there are multiple apps with similar name
![Screenshot 2022-08-17 at 16.53.42.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/0d661568-8c1f-4cc5-8198-6728699b45bc)

### Steps to Reproduce (for bugs)
1. Login to console
2. Make sure you have multiple apps with similar name (for this test I used 20k+ apps and the name of all them were starting with "My app - 1...")
3. Go to APIs and select an API
4. Go to Subscriptions and click on ADD button
5. Search for an app using the first characters of the name e.g. "My app..." or just "My"

### Your Environment
* Version used:-  v3.18.x (local env)
* Browser Name and version: Chrome Version 103.0.5060.53
* Operating System and version: macOS Big Sur v11.6

**Comment by RubenMMSantos** [comment]
issue verified and no longer reproducible.
No error displayed when searching for searching for apps on API- Subscription page, when there are multiple apps with similar name
