### ISSUE TITLE
[SME] Handle endpoints inherited configuration

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#8331]
## Global requirements 
As for V3 endpoints, V4 endpoints can use their own configuration,
Or inherit the configuration shared at endpointGroup level.

That is handled by those data in API definition :

```
    "endpointGroups": [
        {
            "sharedConfiguration": "this is the endpoint group configuration in json"
            "endpoints": [
                {
                    "inheritConfiguration": false,
                    "configuration": "this is the endpoint configuration in json"
                }
            ]
        }
    ]
```

## Acceptance Criteria
- [x] Endpoint group configuration is used when inheritConfiguration is true
- [x] Endpoint configuration is used when inheritConfiguration is false

**Comment by LiliaEn** [comment]
Tested on default env v3.19.0
The following scenarios were covered:
- inheritConfiguration = true + sharedConfiguration defined-> when calling the api, the endpoint group config is returned
- inheritConfiguration = true  and NO sharedConfiguration -> when calling the api, the default config is returned 
- inheritConfiguration = false + sharedConfiguration defined-> when calling the api, the endpoint config is returned
- inheritConfiguration = false + NO sharedConfiguration defined-> when calling the api, the endpoint config is returned
