### ISSUE TITLE
Failed to import API

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#8335]
## :collision: Describe the bug
When trying to import an API, shows an error saying the Primary Owner(c65c1cd9-a190-4608-9c1c-d9a190e60882) wasn't found, however the group exists and it has an user as primary owner.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Create a group named SUEZ and add on it an Primary Owner user
2. On settings, change the "API Primary Owner mode" to "GROUP: an API primary owner can only be a group"
3. Create a sharding tag named "edge"
4. Try to import the api
5. The API will be imported, however if you export it, the "Plan" on json definition will be empty.

## :movie_camera: Useful information

![image](https://user-images.githubusercontent.com/89140082/185636605-09bc04ee-67ba-4b1d-bcc6-e95a8f88ef0c.png)

![image](https://user-images.githubusercontent.com/89140082/185636650-3275fded-f19b-422f-a774-4fb0c1972f57.png)

***Please complete the following information:***
 - Environment: [e.g. 3.15.3]

**Comment by mouligno** [comment]
@zveljanoski Not sure to understand the link between the step to reproduce and the bug ? is the API correctly imported or not ? is the plan missing only?
