### ISSUE TITLE
[management] Keep V4 OpenAPI private

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#8340]
The current openApi generated file, exposed under `/openapi.yaml` contains V3 and V4 API.

As for now, we don't want to communicate on V4 API, and avoid user confusion ; we don't want to expose V4 openApi.

So we have to generate 2 openApi files :
- 1 public containing only V3 API
- 1 private containing V3+V4 API (used by tests-sdk generator)

Find the best way to do it.
Suggestion (we have to verify it works like expected) :
- Move all v3 resources to a dedicated v3 package
- Execute 1 swagger-maven-plugin with v3 package / Execute 1 swagger-maven-plugin with v3 and v4 package

**Comment by mouligno** [comment]
V4 APIs marked as alpha
