### ISSUE TITLE
[portal] 404 on trendings page

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#8341]
When loading portal trendings API pages, the portal gets a 404 error on /metrics resource.
But this should not happen since there is no API to show.

Digging into the database and the code, I've found that it's because at some point, the portal API loads subscriptions for available APIs. But as the current user can't see any APIs, the subscription are filtered based on an empty API list. So it returns all available subscriptions ! And when the final list of APIs is computed, it returns API the current user is not allowed to access.

### Steps to Reproduce (for bugs)
1. Ensure there is no published API on the portal (or start from a fresh empty database)
2. Create an API with an APIKey plan with a user api1
3. Create an application with user application1 (or use Default application)
3. Subscribe to the API with the application of application1
4. log in the portal with admin user
5. go to catalog -> trendings

**Comment by LiliaEn** [comment]
Tested on 3.15.x env
Browser: Chrome Version 103.0.5060.53 , macOS Big Sur v11.6
Working as expected. No error is displayed when accessing Trending page with admin user
