### ISSUE TITLE
[APIM-UI] console does not list all apis

### ISSUE THREAD

**Issue by santos-edu** [gravitee-io/issues#8342]
## :collision: Describe the bug
APIM UI does not list all apis, only after reloading the page that all apis are loaded in the list

## :sunrise_over_mountains: To Reproduce

Steps to reproduce the behaviour:
For example, having more than 30 API's in your gateway, click on APIs in the left menu of the console. Specifically in this url: apim-ui-url/console/#!/environments/default/apis/

It will be observed that the result is always a smaller number than the total number of APIs.

If you reload the page a few times, the issue is resolved and all APIs are listed on the screen.

## :rainbow: Expected behaviour
See all existing APIs in the UI list

## Current behaviour
Giving a false impression about how APIs exist in the gateway.

## :movie_camera: Useful information

total: 32 APIs:
![image](https://user-images.githubusercontent.com/42344004/186006683-68010350-e691-4640-b356-89299b4e7b39.png)
listed on first time: 20 APIs:
![image](https://user-images.githubusercontent.com/42344004/186008421-5471c525-e4e4-423b-aa1e-897fa87cdd4f.png)
If I reload the page a few times the 33 APIs are listed.

## :computer: Desktop:

- This issue has occurred to everyone at the company I work for, and the vast majority are using macOS Monterey 12.5.
- Google Chrome Browser Version 104.0.5112.79 (Official Build) (x86_64)

**Comment by gaetanmaisse** [comment]
Closing as this issue was related to the "infinite scroll" of the API list. 
The UX has been reworked in the latest version of APIM, it's now using a pagination ⬇️ 

![image](https://user-images.githubusercontent.com/4112568/216271841-ef913bad-3e79-4dbb-83e1-9552db3ea6d7.png)
