### ISSUE TITLE
[management] Inconsistent API out of sync banner

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#8343]
### Steps to reproduce
- On an API flow, add a mock policy with the reponse body : `</test>`
- Save your policy and click 'deploy' in the 'API out of sync' baneer

### Expected Behavior
The API should be deployed and the 'API out of sync' banner should hide

### Current Behavior
The API is deployed, but the 'API out of sync' banner keeps visible

**Comment by LiliaEn** [comment]
Tested on 3.18.x env
Browser: Chrome Version 103.0.5060.53 , macOS Big Sur v11.6
Working as expected
