### ISSUE TITLE
List of api's in users section, not properly showing api's associated to a user

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#8344]
## :collision: Describe the bug
Used api1 account, not associated with any api, first login, in the api's section there is not any (expected because there is no api related to it).
In the organization settings->users, seeing all the api's that are present in the environments, associated to the api1 account (not expected)

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Create api's
2. Login with new user, not associated to any of the api's
3. Got to api's section, no api shown
4. Go to organization settings->users and in api section, we are seeing all the api's from the env, like associated with the user

## :rainbow: Expected behaviour
Not to see the api's that are not associated to the user 

## Current behaviour
api's shown as associated with a newly created used, even should not bw

## :movie_camera: Useful information
![image](https://user-images.githubusercontent.com/89140082/186112037-045f943e-022a-44f9-8167-d4da8140596a.png)

![image](https://user-images.githubusercontent.com/89140082/186112102-3171ee0e-b2b8-485f-b202-02096ca57168.png)

## :computer: Desktop:

***Please complete the following information:***
 - Environment: [e.g. 3.18.4]

**Comment by mouligno** [comment]
LGTM
