### ISSUE TITLE
[helm] port name in helm template too long

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#8345]
## :collision: Describe the bug

The following error occurs during a test deployment.
helm-controller reconciliation failed: Helm upgrade failed: failed to create resource: Deployment.apps "abc-d-01--abcd-efg" is invalid: spec.template.spec.containers[0].ports[1].name: Invalid value: "abcd-efg-techapi": must be no more than 15 characters

To solve it, I just truncate port name for bridge and technical port on api and gateway deployment templates.

Additional context
We are trying to deploy 2 control plane on the same cluster and must rename the release, deployments and pods.

see proposed PR : https://github.com/gravitee-io/helm-charts/pull/292

## Current behaviour
A clear and concise description of what is currently happening.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.18.4

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by gaetanmaisse** [comment]
Fix has been released in APIM Helm Chart 3.1.54 (and will be available for other products in their next release).
