### ISSUE TITLE
List of API's from a user, not showing correctly

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#8346]
⚠️ For test QA : The fixe was made for all this screen's table : 

- identity-providers
- roles
- tags
- tenants
- user

in Organisation Settings

I think we can test some of it to see everything work correctly 

----
## :collision: Describe the bug
There is a display issue with the listing of APIs in the page users in organization settings. The number of apis that are listed here evolves according to the number of items per page that is chosen: If chosen 5 items per page, it will display only 1 page of 5 items, if chosen 10 items par page, it will display only 1 page of 10 items.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to organization settingss
2. Go to users
3. Scroll down to apis from that particular user
4. It is showing the number we choose as a maximum, even so, there are more api's associated to the given user

## :rainbow: Expected behaviour
Expected when chosen 5, 5 to be shown and the rest on other pages...

## Current behaviour
Only 5 or the number chosen shown as all the apis are shown

## :movie_camera

https://user-images.githubusercontent.com/89140082/186117896-90d03b66-16f8-4871-aa85-ac4efec22966.mp4

***Please complete the following information:***
 - Environment: [e.g. 3.18.4]

**Comment by mouligno** [comment]
Pagination is broken in org settings

**Comment by phiz71** [comment]
PR is on 3.15.x but milestone is 3.18.x, who is right ?

**Comment by RubenMMSantos** [comment]
issue verified, working as expected.

**Comment by grignix** [comment]
Hi @zveljanoski
You only found an error in one place, but there is a similar error in other places.
Please look:
https://github.com/gravitee-io/issues/issues/8080
https://github.com/gravitee-io/issues/issues/8096
