### ISSUE TITLE
[gateway] opensearch ism template is missing rollover_alias and first index is not created

### ISSUE THREAD

**Issue by jose-deniz-ns90** [gravitee-io/issues#8358]
1.  ## <g-emoji class="g-emoji" alias="boom" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4a5.png">
     💥 
     </g-emoji> Describe the bug When enabling ilm index_mode in the gateway and setting an ilm policy, it is failing as the plugin.index.lifecycle.rollover_alias is not set in the associated template of the index. In addition, the first index is not set with the expected naming (ie gravitee-request instead of gravitee-request-000001)
2.  ## <g-emoji class="g-emoji" alias="sunrise_over_mountains" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f304.png">
     🌄 
     </g-emoji> To Reproduce In the gateway gravitee.yml file, enable the ilm and associate a policy as follows :

 elasticsearch:
 enabled: true
 endpoints:

*   [http://$](http://%24) {ds.elastic.host}

:$

 {ds.elastic.port} 

lifecycle: policy_property_name: plugins.index_state_management.policy_id policies: request: hot_delete index: gravitee index_per_type: true index_mode: ilm

 Restart the gateway, make an API request and check the indexes in ES

 1\. 1\. :rainbow: Expected behaviour
 Have ilm index mode setting works as daily index mode without manual operations. Expected to have a first index named `gravitee-request-000001`

 1\. 1\. Current behaviour
 An index named `gravitee-request` is created.

 1\. 1\. :movie_camera: Useful information
 Error is logged including opensearch response:
 ```ERROR i.g.e.client.http.HttpClient - Unable to put template mapping: status<span class="error"><span class="error">[400]</span></span> template[{
 "index_patterns": <span class="error"><span class="error">["gravitee-request*"]</span></span>,
 "settings": 

 { "plugins.index_state_management.policy_id": "hot_delete", "index.lifecycle.rollover_alias": "gravitee-request", "index.number_of_shards":1, "index.number_of_replicas":1, "index.refresh_interval": "5s" .............. } 

 response[{"error":

 <div class="error"> <span class="error">Unknown macro: 

 {"root_cause"} 

</span> 
 </div>

 ,"status":400}]
 ```

 1\. 1\. :computer: Versions:

 *****Please complete the following information:*****

*   apim-gateway: <span class="error"><span class="error">[3.18.6]</span></span>
*   gravitee-reporter-elasticsearch: 3.12.4
*   opensearch: 1.2.4

 1\. 1\. :link: Dependencies

 There was a comment to introduce a property to manage alias name in bug [https://github.com/gravitee-io/issues/issues/7110](https://github.com/gravitee-io/issues/issues/7110)([https://github.com/gravitee-io/issues/issues/7110](https://github.com/gravitee-io/issues/issues/7110))
 _We may need to introduce a policy_property_rollover_alias as we have for index.lifecycle.name in the gravitee.yml_
 ILM settings for elasticsearch added.

**Comment by jose-deniz-ns90** [comment]
policy_property_rollover_alias added 
https://github.com/gravitee-io/gravitee-reporter-elasticsearch/commit/2022a8e8341d612688f7639d43dad47092c062a9

Tested successfully using properties in gravitee.yml:
```
    lifecycle:
      policy_property_name: plugins.index_state_management.policy_id
      policy_property_rollover_alias: plugins.index_state_management.rollover_alias

```
opensearch templates created and indexes too
Template:
```
{
  "order": 0,
  "index_patterns": [
    "gravitee-log*"
  ],
  "settings": {
    "index": {
      "refresh_interval": "5s",
      "number_of_shards": "1",
      "number_of_replicas": "1",
      "plugins": {
        "index_state_management": {
          "policy_id": "hot_delete",
          "rollover_alias": "gravitee-log"
        }
      }
    }
  }, ....................
```
Index:
```
{ - 
  "gravitee-log-000001": { - 
    "settings": { - 
      "index": { - 
        "refresh_interval": "5s",
        "number_of_shards": "1",
        "plugins": { - 
          "index_state_management": { - 
            "policy_id": "hot_delete",
            "rollover_alias": "gravitee-log"
          }
        },
        "provided_name": "gravitee-log-000001",
        "creation_date": "1661433298600",
        "number_of_replicas": "1",
        "uuid": .................
        "version": { - 
          "created": "135238227"
        }
      }
    }
  }
}
```

**Comment by vliska** [comment]
Bump, we just stumbled upon this. There is no way how to do ILM properly in opensearch 2.x - and elasticsearch-curator is not compatible, so it can't be used.
