### ISSUE TITLE
[gateway] [override theme] [forms] be able to change color for the icons

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8359]
Currently we can't change the icon color of our default templates (eyes, arrows, ...) which do not match our overall color palettes.

<img width="860" alt="theme-2" src="https://user-images.githubusercontent.com/1927438/186704316-885af45c-55bc-4e74-a036-f04ef660224b.png">

**Comment by patelami** [comment]
Env: Master
Result: PASS

This is currently fixed
<img width="615" alt="Screenshot 2022-09-01 at 09 43 41" src="https://user-images.githubusercontent.com/14215437/187871914-630269bf-c70b-4ac4-952a-d53f13b762dd.png">
