### ISSUE TITLE
Rate limiter with a key defined seems to also depend on IP

### ISSUE THREAD

**Issue by masterbox** [gravitee-io/issues#8360]
I defined a rate limiter (also tested with quota) in an API flow, base on a key. For test purposes this key is the path : {#request.path}
This API has a keyless plan only.
The rate limiter is working well on one computer, but If we try with multiple IP adresses, each IP has it's own limit, which is not the desired behavior.

Here is a screenshot of the quota configured : 
![Capture d’écran 2022-08-24 115648](https://user-images.githubusercontent.com/613339/186804187-cf2ed2a2-a319-4362-a268-a1e216641d92.png)
NB : here the max request is dynamic, but we tried with a static one as well.

**Comment by mouligno** [comment]
hi @masterbox, which version are you using ?

**Comment by mouligno** [comment]
btw can you try with `{#request.contextPath}` ?

**Comment by masterbox** [comment]
Hi.
Sorry I thought I indicated the version.
The gateway is in 3.10.0.

I'll try with contextPath and tell you if it's any different.

**Comment by masterbox** [comment]
Hi,
I tried with contextPath, the result is the same, when I excess the limit rate on one IP, I try on another computer, I'm not blocked.

**Comment by mouligno** [comment]
Hi 

I wasn't able to reproduce in 3.18.+. Can you please try with latest version of Gravitee, 3.10.x is not supported anymore.

**Comment by masterbox** [comment]
Hi, thanks. I'm asking for the update and retry afterwards.
