### ISSUE TITLE
[V4] Properly handle error when dealing with api v4 

### ISSUE THREAD

**Issue by guillaumelamirand** [gravitee-io/issues#8361]
### Expected Behavior

After implementing #8287, it is now possible to subscribe to a api v4 with an api-key plan. However when doing so and while using a wrong api key, the connection never stop.

### Current Behavior

A correct error should be send back to client depending on the entrypoint and the connection should be closed.

### Possible Solution

A new method should be added to EntryPointConnector in order to allow entrypoint to deal with the error.
AsyncReactor should evolved to deal with errors.

### Steps to Reproduce (for bugs)

Follow the attached collection [https://app.zenhub.com/files/61280156/729ec1f4-ebde-4762-8e49-87d7f93124c1/download](https://app.zenhub.com/files/61280156/729ec1f4-ebde-4762-8e49-87d7f93124c1/download) to subscribe to an api v4 with api key plan.
> when connecting to the gateway with curl command and wrong api key, connection is still opened.
 
```
curl -vv http://localhost:8082/test-jupiter-v4-2 -H "X-Gravitee-Api-Key: 4241bef3-113d-46b6-9cda-93199791f23" -H "Accept: text/event-stream" 
*   Trying 127.0.0.1:8082...
* Connected to localhost (127.0.0.1) port 8082 (#0)
> GET /test-jupiter-v4-2 HTTP/1.1
> Host: localhost:8082
> User-Agent: curl/7.79.1
> X-Gravitee-Api-Key: 4241bef3-113d-46b6-9cda-93199791f23
> Accept: text/event-stream
> 
```
### Your Environment

* Version used:
* Browser Name and version:
* Operating System and version:

**Comment by guillaumelamirand** [comment]
We have things going regarding how policies will be handled for SME, I'll pause this one until policy mechanism is well implemented.

**Comment by guillaumelamirand** [comment]
Error will be handled in two phases :

1. If any error occurred during connection establishement the same behaviour as today will be apply
2. If any error occured while processing message, entrypoint will be called to deal with it properly.

**Comment by guillaumelamirand** [comment]
I put this one in hold waiting for #8403 to be merged.

**Comment by guillaumelamirand** [comment]
PR are here : 

- https://github.com/gravitee-io/gravitee-gateway-api/pull/142
- https://github.com/gravitee-io/gravitee-api-management/pull/2419

**Comment by LiliaEn** [comment]
Tested on the default env 3.20.0
Error handling was covered for:
- Invalid API Key
- Message Flow
- Connection establishment
Error for policies and other plans (oAUTh2 and JWT) will be covered in the following task: https://graviteecommunity.atlassian.net/browse/APIM-188
