### ISSUE TITLE
[management] can not import Paths Based API 

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#8365]
## :collision: Describe the bug
Paths based APIs can not be imported anymore even if the feature is still present.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Enable Enable path based API creation in "Organization Settings"
2. Create a dummy Path Based API (bottom right link "create" in API creation window)
3. Export the API
4. Remove the created API and try to import it (bottom right link "import")
5. See error : 
`An error occurs while trying to parse API definition com.fasterxml.jackson.databind.JsonMappingException: Flows are only available for definition >= 2.x.x at [Source: (String)"{"name":"pathbased","crossId":"c0d0f60c-302d-4568-90f6-0c302d756897","version":"1","execution_mode":"v3","description":"pathbased","visibility":"PRIVATE","paths":{"/":[]},"gravitee":"1.0.0","flow_mode":"DEFAULT","flows":[],"resources":[],"properties":[],"members":[{"source":"memory","sourceId":"admin","roles":["6c3c254d-d6e6-415b-bc25-4dd6e6115b59"]}],"pages":[{"id":"ba8f0eda-fd8a-3b44-80ea-7b52d4f6f123","crossId":"377f9c8e-3e89-44a1-bf9c-8e3e89b4a134","name":"Aside","type":"SYSTEM_FOLDER","orde"[truncated 1574 chars]; line: 1, column: 2074]
`

## :rainbow: Expected behaviour
As the feature is still present, we should be able to do so.

## Current behaviour
A clear and concise description of what is currently happening.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.18.5

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by mouligno** [comment]
Problem has been identified around the export of v1 APIs in 3.18+,

**Comment by mouligno** [comment]
LGTM
