### ISSUE TITLE
Regular expression regression in Validate Request policy

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#8367]
## :collision: Describe the bug
After upgrading to 3.18.5 we have an issue with the "validate request" policy on a specific regex.

The regex pattern is to validate a trigram in a request parameter, "[A-Z]{3}", but it's not working anymore in 3.18.5 (confirmed working in 3.18.4), a way to make it work is modifying it to "[A-Z][A-Z][A-Z]".

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Create an api
2. Use Validate Request policy
3. Set it up like in the picture: 

![image](https://user-images.githubusercontent.com/89140082/187156781-3339d8a0-e06a-4f58-bb1f-0d989e6f8400.png)

5. Call the endpoint and check the response/error in postman:

![image](https://user-images.githubusercontent.com/89140082/187156430-c0090c4e-3e08-465b-bdf9-a7f2bcc7fd6c.png)

6. A way to workaround is to use "[A-Z][A-Z][A-Z]", instead of "[A-Z]{3}"

## :rainbow: Expected behaviour
To works with the shortened expressions 

***Please complete the following information:***
 - Environment: [e.g. 3.18.5]

**Comment by zveljanoski** [comment]
Maybe related to this one:
https://github.com/gravitee-io/issues/issues/8217

**Comment by kirestoj01** [comment]
This also happens in the Dynamic Routing policy.

**Comment by RubenMMSantos** [comment]
Using the provided example we can see in the printscreen below the policy working as expected.

![Screenshot 2022-09-15 at 14 46 26](https://user-images.githubusercontent.com/14939456/190420416-77f91950-c5b6-46bf-9b95-ac3b181d81c5.png)
