### ISSUE TITLE
[gateway] [themes] Error message rendering issue

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#8368]
When authentication fails with a long error message, the border doesn't wrap the message.

![image.png](https://images.zenhubusercontent.com/6026363e864bfc6af2b3aa2c/d281d177-b85e-4afd-9251-6b9273556647)

### Expected Behavior

the Red border should wrap the error message 

### Current Behavior

The error message is out of the red border

### Related issue

This is a UAT for #8042

**Comment by patelami** [comment]
Env: master
Result PASS
<img width="599" alt="Screenshot 2022-09-13 at 15 14 08" src="https://user-images.githubusercontent.com/14215437/189924734-8cdc6cf4-72bb-457e-adf6-2d3075b32074.png">
