### ISSUE TITLE
[management] [override theme] [view mode] forms preview mode

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8369]
## :rainbow: Feature

**As a** 'security domain owner'

**I want to** 'preview my form templates with the resolved data'

**So that** 'I can be sure my form templates are well displayed'

## :sunrise_over_mountains: Additional information

- Add a new query param (preview) in the forms resource to query the resolved templates
- Use the Thymeleaf template engine to process the data

```
    @Autowired
    private TemplateEngine templateEngine;

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @ApiOperation(value = "Find a form",
            notes = "User must have the DOMAIN_FORM[READ] permission on the specified domain " +
                    "or DOMAIN_FORM[READ] permission on the specified environment " +
                    "or DOMAIN_FORM[READ] permission on the specified organization")
    @ApiResponses({
            @ApiResponse(code = 200, message = "Form successfully fetched"),
            @ApiResponse(code = 500, message = "Internal server error")})
    public void get(
            @PathParam("organizationId") String organizationId,
            @PathParam("environmentId") String environmentId,
            @PathParam("domain") String domain,
            @QueryParam("preview") boolean preview,
            @NotNull @QueryParam("template") Template formTemplate,
            @Suspended final AsyncResponse response) {

        checkAnyPermission(organizationId, environmentId, domain, Permission.DOMAIN_FORM, Acl.READ)
                .andThen(formService.findByDomainAndTemplate(domain, formTemplate.template()))
                // TODO
                .map(form -> {
                    if (!preview) {
                        return Response.ok(form).build();
                    }
                    Map<String, Object> variables = Map.of("domain", domain, "client", client, ...);
                    org.thymeleaf.context.Context context = new org.thymeleaf.context.Context();
                    context.setVariables(variables);
                    final String processedTemplate = templateEngine.process(form.getContent(), context);
                    form.setContent(processedTemplate);
                    return Response.ok(form).build();
                });
                .defaultIfEmpty(Response.ok(new Form(false, formTemplate.template())).build())
                .subscribe(response::resume, response::resume);
    }

```

## :white_check_mark: Acceptance criteria

- [ ] Given '...' When '...' Then '...'

## :ballot_box_with_check: Developer sub-tasks 

- [ ] Jest test for acceptance criteria

**Comment by leleueri** [comment]
For UX, instead of calling the GET method as mention in the issue description, we will provide a POST endpoint to allow rendering the template without publishing it first.

**Comment by patelami** [comment]
- MFA enroll page error: 
<img width="1440" alt="Screenshot 2022-09-09 at 13 55 15" src="https://user-images.githubusercontent.com/14215437/189356125-b20dbe7c-0efe-49ed-9d80-ae88b156171c.png">


- Unable to see logo on the preview page
- MFA challenge and MFA challenge alternative publish button is inactive 
<img width="743" alt="Screenshot 2022-09-09 at 13 48 57" src="https://user-images.githubusercontent.com/14215437/189356081-d4f9e0b1-50cd-4d95-a8f8-a4592d443a42.png">

**Comment by tcompiegne** [comment]
MFA enroll page error has been tracked here : #8463

Other errors have been fixed.

Closing this ticket.
