### ISSUE TITLE
[Task] Generate SDK in each PR and fail build if there are uncommitted changes

### ISSUE THREAD

**Issue by gaetanmaisse** [gravitee-io/issues#8374]
### 📝 Description

When we moved from the old `swagger.json` to the new `openapi.yaml` in 3.17.0 we missed some naming issues, leading to https://github.com/gravitee-io/issues/issues/8074

To avoid this kind of issue next time we work around these subjects we could:
 - generate the TS SDK of the Management + Portal APIs in each PR
 - fail the build if there are uncommitted changes

**Comment by marcambier** [comment]
As discussed with the team, we choose to implement it in another way :
- remove the SDK generated sources from git repository
- let the CI (or the developper) regenerate them when needed
