### ISSUE TITLE
[gateway] SyncManager hang after connection issue

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#8377]
When the backend connection is broken (ex: MongoDB server restart), the SyncManager may be unable to reschedule the sync.

### Expected Behavior

The sync process (scheduled every 5 second by default) should be executed once the connection is reestablidhed

### Current Behavior
The sync process (scheduled every 5 second by default) isn't executed once the connection is reestablidhed

### Steps to Reproduce (for bugs)

1. Enable sync service log to DEBUG
`    <logger name="io.gravitee.am.gateway.services.sync" level="DEBUG" />`
2. start GW
3. check logs like these one are present
```
18:53:45.000 [sync-1] [] DEBUG i.g.a.g.s.sync.ScheduledSyncService - Synchronization #79 started at 2022-08-29T16:53:45.000665Z
18:53:45.000 [sync-1] [] DEBUG i.g.a.g.services.sync.SyncManager - Refreshing sync state...
18:53:45.000 [sync-1] [] DEBUG i.g.a.g.services.sync.SyncManager - Events synchronization
18:53:45.004 [sync-1] [] DEBUG i.g.a.g.s.sync.ScheduledSyncService - Synchronization #79 ended at 2022-08-29T16:53:45.004822Z
```
4. restart mongoDB
5. after the restart MongoDB reconnection logs should be visible but synchronization logs are missing

These behaviour may not be reproductible every time, multiple attempts may be requried

**Comment by leleueri** [comment]
Issue comes from the blockingGet that may block indefinitely after a connection lost.

**Comment by guillaumelamirand** [comment]
blockingGet shouldn't be "blocking" indefinitely but once it failed it won't retry anymore. How did you see this behaviour about "block indefinitely after a connection lost" ?

**Comment by leleueri** [comment]
> blockingGet shouldn't be "blocking" indefinitely but once it failed it won't retry anymore. How did you see this behaviour about "block indefinitely after a connection lost" ?

After some connection issue on the DB, the update made on the UI were not propagated to the GW, by doing thread dump, I saw a thread waiting on the blockingGet of the sync process.

**Comment by patelami** [comment]
Env: 3.15

As a user, I should be able to create domain
As a user, I should be able to enable the domain
As a user, I should be able to create application
As a user, I should be able to update the application
As a user, I should be able to create user
