### ISSUE TITLE
[idp] [MongoDB] queries are not well parsed for the user management features

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8379]
It's OK for the authentication part but not the user management part (user registration or reset password). 

For example : 

`{$or : [ {username: ?}, { numpolicy : { $regex : ?, $options : i}} ]}` becomes `{$or : [ {""username"": ?}, { ""numpolicy"" : { ""$regex"" : ?, ""$options"" : i}} ]}`

**Comment by patelami** [comment]
Env: 3.18.x
Result: PASS

Verified in logs that the user has been found with complex query and email is sent. The smtp server on nightly is broken so enable to receive emails.
