### ISSUE TITLE
[policy] XSLT parameter get cached depending on the number of gateways

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#8382]
## :collision: Describe the bug
When using XSLT policy with parameters, those parameters will be cached depending on the number of gateways in use.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Create an API with XSLT Policy with a parameter set to a test header value (see attached : 
[xslt-xslt.txt](https://github.com/gravitee-io/issues/files/9452837/xslt-xslt.txt)

2. Make requests on the API with a different test header value
3. You will notice that the value is cached in the output

```
curl --location --request GET 'https://apim-master-gateway.team-apim.gravitee.xyz/xslt' \
--header 'test: 1' \
--header 'Content-Type: application/xml' \
--data-raw '<?xml version="1.0" encoding="UTF-8"?>
<test>
```

`<?xml version="1.0" encoding="UTF-8"?><test>1</test>
`
## Current behaviour
A clear and concise description of what is currently happening.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.17.2 3.15

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by RubenMMSantos** [comment]
issue verified, header value no longer cached.
