### ISSUE TITLE
[SME] Rework ExecutionContext, Request, Response structure for SME

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#8386]
As things progress on SME we face new needs regarding Connector that require to simplify how `ExecutionContext` and Request / Response are structured.

Currently, we have 2 types of request / response

- `Request`: allows to access http request body
- `MessageRequest`: allows to access message flux (but not request body)

For connector implementation, we need to have access to a request that provides access to both request body and messages. Indeed, connector is responsible to take the request body and transform it to message.

A first implementation introduced a kind of hack by adding the required method at upper level but we don't want it to be accessible everywhere, especially at policy level.

The objective is to rework on the structure of the `ExecutionContext` / `Request` / `Response` objects to make sure everything will be safe for futures implementations.

### Acceptance Criteria

Jupiter execution must continue to work as previously
All new Connectors (SSE, Mock, Http-post) must continue to work as expected

**Comment by gaetanmaisse** [comment]
Closing as it's a technical refactoring, testing will be done during non regression phase
