### ISSUE TITLE
[helm chart] ability to change the "pathType" of the ingress and remove default annotations

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#8393]
## :collision: Describe the bug
On Gravitee helm chart, when configuring an [ingress ](https://github.com/gravitee-io/helm-charts/blob/master/apim/3.x/values.yaml#L927)on the gateway part.
It is not possible to change the "pathType" of the ingress because that value is [hard coded](https://github.com/gravitee-io/helm-charts/blob/master/apim/3.x/templates/gateway/gateway-ingress.yaml#L31).

Second, if Nginx is not used,  default [annotations](https://github.com/gravitee-io/helm-charts/blob/master/apim/3.x/values.yaml#L938) can not be removed.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.18.5

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by gaetanmaisse** [comment]
@apoddany can you give more context and the impacts of the issues

**Comment by gaetanmaisse** [comment]
The `remove default annotations` part will be handled with https://github.com/gravitee-io/issues/issues/8728

**Comment by gaetanmaisse** [comment]
I've got some exciting news to share - we've finally squashed that pesky bug that's been bugging you! 🎉 
The fix is included in the latest version of the APIM Helm Chart (v3.1.62), so you can finally take a breather and let your API do the heavy lifting. 

_Note_: https://github.com/gravitee-io/issues/issues/8393#issuecomment-1433191685
