### ISSUE TITLE
[gateway] 502 error received on GET request with non Zero Content-length (expected 400)

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#8394]
## :collision: Describe the bug
When submitting a GET request on an API with a non Zero Content-length, the request will take time to proceed and will return a 502 error but a 400 would be expected

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Create a sample passthrough echo API to a backend
2. send a GET request with a Content-length with a value : 
`curl --location --request GET 'http://localhost:8082/echo' --header 'Content-Length: 13'
`
3. a 502 bad gateway will be received

## :rainbow: Expected behaviour
receive a 400 Bad Request

## Current behaviour
502 Bad Gateway received
in 3.5.30 it will make the request to hang.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.15.15, 3.18.5, 3.5.30

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by gaetanmaisse** [comment]
Closing since the original ticket has been closed after a discussion with the customer.
