### ISSUE TITLE
[gateway] [forms] overlap issue in the default templates if the title is too big

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8401]
![image](https://user-images.githubusercontent.com/1927438/188103591-9e1d0db8-e82f-4a6d-bf72-5a0683877ae5.png)

**Comment by leleueri** [comment]
Same for the resetPassword form
![image](https://user-images.githubusercontent.com/3110552/189602967-031c18e8-b250-4a67-9ae2-3732b66beddf.png)

**Comment by leleueri** [comment]
will be fixed by #8467

**Comment by patelami** [comment]
Env: 3.19.0
Result: PASS

<img width="606" alt="Screenshot 2022-09-27 at 16 28 47" src="https://user-images.githubusercontent.com/14215437/192570084-9aaec189-c39b-47a5-8520-8914bbe3cca1.png">

<img width="607" alt="Screenshot 2022-09-27 at 16 30 57" src="https://user-images.githubusercontent.com/14215437/192570065-2812010c-946c-4fc1-a751-7355ebb57e74.png">
