### ISSUE TITLE
Improve dev experience with policies and Gateway test SDK

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#8412]
Working in the same time on APIM Gateway and policies is often problematic since there is a circular dependency between APIM Test SDK and policies.

To allow a better dev experience, we had a meeting and decided to:

- [ ] Make possible to deploy on artifactory a temporary version of APIM with a specific version (like we do for plugins)
- [ ] Build a distribution only if the workflow is going to deploy something on azure or if we need docker image for e2e tests (i.e. only on master and support branches)

**Comment by marcambier** [comment]
Could be related with : https://graviteecommunity.atlassian.net/browse/APIM-145
