### ISSUE TITLE
API out of sync banner is displayed inconsistently when there is a dynamic property on the API

### ISSUE THREAD

**Issue by LiliaEn** [gravitee-io/issues#8424]
API out of sync banner is displayed inconsistently even when the API is deployed, when there is a dynamic property on the API and making any changes that require deployment

### Expected Behavior

API out of sync banner should not be displayed when the last changes of the API were deployed

### Current Behavior

API out of sync banner is displayed inconsistently even when the API is deployed when the API has a dynamic property configured and any changes that need to be deployed are made.

### Steps to Reproduce (for bugs)

1.  Login to APIM console as an admin
2.  Create an API or use an existing one
3.  Configure a dynamic property that will get updated every 2 sec
4.  Save the changes and deploy the API
5.  Make some other changes that require deployment
6.  Save the changes and deploy - notice that API out of sync banner is displayed even if the API was deployed
7.  Keep doing this for a few times, the banner sometimes disappears

[https://drive.google.com/file/d/1Wjh0pGcomz9Qs13kHMIiXA4d29UBmc1D/view?usp=sharing](https://drive.google.com/file/d/1Wjh0pGcomz9Qs13kHMIiXA4d29UBmc1D/view?usp=sharing)

### Your Environment

*   Version used:- v3.19.x
*   Browser Name and version: Chrome Version 104.0.5112.101
*   Operating System and version: macOS Big Sur v11.6

**Comment by marcambier** [comment]
We confirmed this behavior is reproducible on previous versions (at least on 3.18).
I label this ticket as a "bug", and send it in the support backlog.

**Comment by gaetanmaisse** [comment]
To test with a smallest frequence of update

**Comment by gaetanmaisse** [comment]
Closing as it looks to be fixed in the latest version of APIM 3.18, 3.19, 3.20 thanks to the technical rework of the dynamic properties mechanism
