### ISSUE TITLE
[management] Unable to create backend to backend application with DCR

### ISSUE THREAD

**Issue by gtardini** [gravitee-io/issues#8425]
# [Describe the bug](#describe-the-bug)

I am using Gravitee APIM version 3.18.8 and I have configured Auth0 as my provider for DCR, everything works fine for all kinds of applications (SPA, Web...) except for Machine to Machine (Backend to Backend) Applications. When I reach the end of the application creation flow and push the button to create the application I get a bad request error with no further information.

# [To Reproduce](#to-reproduce)

Steps to reproduce the behaviour:

1.  From the Admin Portal, under "Settings->Client Registration->Add a Client Registration Provider with client credentials", configure DCR
2.  From the Admin Portal, under "Application", create a new application of type backend to backend. Insert all the information for the application and reach the end of the flow.
3.  Click the button "Create the application"
4.  See error in red alert with the following message "Unexpected error while registering client: Unexpected response from OIDC Registration endpoint: error<span class="error">[Bad Request]</span> description[]"

# [Expected behaviour](#expected-behaviour)

Successful application creation both on Gravitee and Auth0.

**CURRENT BEHAVIOUR BAD REQUEST ERROR AND NO APPLICATION GETS CREATED, NEITHER ON GRAVITEE NOR AUTH0.**

# [Useful information](#useful-information)

Gravitee Application Logs corresponding to the error in the red failure alert: `ERROR i.g.r.a.s.i.c.a.r.c.DiscoveryBasedDynamicClientRegistrationProviderClient - Unexpected response from OIDC Registration endpoint: error<span class="error"><span class="error">[Bad Request]</span></span> description[] ERROR i.g.r.a.s.i.c.a.r.c.DiscoveryBasedDynamicClientRegistrationProviderClient - Unexpected error while registering client: Unexpected response from OIDC Registration endpoint: error<span class="error"><span class="error">[Bad Request]</span></span> description[] io.gravitee.rest.api.service.impl.configuration.application.registration.client.DynamicClientRegistrationException: Unexpected response from OIDC Registration endpoint: error<span class="error"><span class="error">[Bad Request]</span></span> description[]`

# [Potential impacts](#potential-impacts)

Enable Machine to Machine (Backend to Backend) creation with DCR, at the moment it seems to me it is not possible.

🔗 Dependencies Looks very similar to <span class="error">[this closed bug]</span>([[https://github.com/gravitee-io/issues/issues/2511](https://github.com/gravitee-io/issues/issues/2511)([[https://github.com/gravitee-io/issues/issues/2511|https://github.com/gravitee-io/issues/issues/2511])|| [https://github.com/gravitee-io/issues/issues/2511](https://github.com/gravitee-io/issues/issues/2511)|https://github.com/gravitee-io/issues/issues/2511])|] [https://github.com/gravitee-io/issues/issues/2511](https://github.com/gravitee-io/issues/issues/2511)]([[https://github.com/gravitee-io/issues/issues/2511|https://github.com/gravitee-io/issues/issues/2511| [https://github.com/gravitee-io/issues/issues/2511](https://github.com/gravitee-io/issues/issues/2511)|https://github.com/gravitee-io/issues/issues/2511]])])

**Comment by Quadexx** [comment]
+1
