### ISSUE TITLE
[management] Healthcheck does not work properly if the backend has latency more than 2 seconds

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#8429]
## :collision: Describe the bug
When you have set Healthcheck on API, if the backend has latency longer than 2 seconds, the healthcheck is not logged neither as OK or no response, making the load balancer try to send the request to unresponsive backend.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Create 2 APIs, and set API 2 to be backend for API 1. 
2. In API 2 use latency policy set with more than 2 seconds of latency. Use mock policy to mock any response. 
3. In API 1 set healthcheck for the backend and monitor the logged healthcheck. 
4. See how the healthcheck is not logging any checks done. For better view set 2nd backend that works without latency to have for comparison.

## :rainbow: Expected behaviour
When the healthcheck does not receive response from backend within some time limit it should log that the backend is not healthy so the load balancer will forward calls to other backends.

## Current behaviour
Healthcheck does not log checks when there is latency longer than 2 seconds.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: [3.18.2, 3.18.7]
 - OS: Docker Install
 

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by mouligno** [comment]
LGTM, backend with 2 sec latency get logged as 504 since the timeout period is 1000ms.
