### ISSUE TITLE
[gateway] allow TLSv1.3 when contacting backend

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#8433]
The gateway relies on vertx http client under the hood and it appears that, by default, the supported tls protocols are TLSv1, TLSv1.1 and TLSv1.2. TLSv1.3 is not supported by default and there is currently no way to configure it.

Technically, the fix is pretty easy as it consists to add TLSv1.3 to the list of supported protocols but we need to think about how we want it to be added to the support tls protocol. I see multiple options and we need to discuss about the consequences:
* Add TLSv1.3 by default (don't see particular issue as it add a more robust protocol to the list :man_shrugging:)
* Make it possible to configure at endpoint level (seems to be effortful)
* Align it with http.ssl.tlsProtocols config (but it is currently targeting the http server only, not the client)
* Add a dedicated configuration such as http.client.ssl.tlsProtocols config (may be overkill)

**Comment by kamiiiel** [comment]
Making TLSv1.3 the default protocol seems to be the easiest way to implement this and other protocols can be picked up automatically if the backed doesn't support V1.3
Because all the back-ends may not support the latest protocol, having a special configuration (like http.client.ssl.tlsProtocols) doesn't seem to work as we expect.

**Comment by jhaeyaert** [comment]
Yes that's my opinion too. I'm just wondering if we should introduce a dedicated config key for that or not. The use case I have in mind is more about security where the user wants absolutely to avoid TLSv1 for instance and so want to provide the list of supported tls protocols by his own.

Currently, there is an `http.ssl.tlsProtocols` config that we could apply both on http server and http client. I'm wondering if it makes sense or not (same for ciphers). I was first not convinced but since we already use `http.ssl.openssl` configuration and it is applied on server and client, maybe we could do the same for `http.ssl.tlsProtocols` and `http.ssl.ciphers` ?
