### ISSUE TITLE
[Jupiter] Handle response template in case of 502 proxy error

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#8437]
The current implementation on Jupiter does not well handle the case where the v3 HttpConnector return a 502 proxy error.
With the V3 engine, it basically interrupt the execution chain with the following error key `GATEWAY_CLIENT_CONNECTION_ERROR` that can be used to define a template message.

This behavior must be adapted for Jupiter engine to ensure backward compatibility.

**Comment by RubenMMSantos** [comment]
Configuring a "unreachable" endpoint and then making a request to it a 502 error is displayed and Jupiter picks up the response template that was configured for this scenario.
![Screenshot 2022-10-03 at 13 38 18](https://user-images.githubusercontent.com/14939456/193578396-e12efa15-e674-4f33-bf49-64a0cc500538.png)

![Screenshot 2022-10-03 at 13 38 30](https://user-images.githubusercontent.com/14939456/193578431-f1760afd-054
![Screenshot 2022-10-03 at 13 38 40](https://user-images.githubusercontent.com/14939456/193578463-d6edd2f9-1673-46b9-8883-b9daef61540e.png)
1-4ac3-b0ff-4131c94ae0e2.png)
