### ISSUE TITLE
[console] Validate request button does not work when trying to subscribe api with general conditions set

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#8442]
## :collision: Describe the bug
When General condition feature is set on a plan, the validate the request button in the portal does not work when trying to subscribe to the plan as there is no screen displayed to accept the general condition.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:

1. Create simple API with api key plan. 
2. Create markdown page with "general conditions" for the api. Set the page previously created as general conditions page in the plan.
3. Go to the API in the Portal (catalog>all apis> the api used for this test)
4. Click on subscribe button > choose the plan with the general conditions setup > click next > choose application > click next > no screen displayed to accept the general condition > see disabled validate request button.

## :rainbow: Expected behaviour
When general conditions feature is set, the validate button should be clickable to see the conditions page.

## Current behaviour
The Validate the request button does not work. (is disabled)

## :movie_camera: Useful information

https://user-images.githubusercontent.com/98313939/189655570-0da478e3-f8a2-4f15-ae1a-1e622e8425d3.mp4

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.18.7 3.18.8
 - OS: Docker Install

**Comment by mouligno** [comment]
LGTM but the validation screen is weird. I'm creating a specific issue for this. 
![image](https://user-images.githubusercontent.com/3227037/190441904-2b8b0e20-1c49-4c74-b899-c3448e13df51.png)
