### ISSUE TITLE
[management] [mfa] send same OTP code to multiple devices

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8444]
## :rainbow: Feature

**As a** 'an application owner'

**I want to** 'send the same MFA challenge via SMS and Email at the same time'

**So that** 'they can access their account'

## :sunrise_over_mountains: Additional information

- Create a new EE plugin to do this feature
- The plugin will be an extension of the Email MFA but targeting multiple resources

## :books: Documentation required

Provide link to the issue for documentation update

## :superhero: Acceptance criteria

- [ ] Given 'an end-user who wants to sign-in with MFA enabled' Then 'the end-user will receive the same security code via SMS/HTTP or email to verify its account' When 'using OTP Sender factor'

## :warning: Potential impacts

***What are the impacted versions?***

3.15

## :heavy_check_mark: Definition of Done

***For each User Story everything on the list must be considered, select only what was required***
- [ ] Acceptance criteria met and tested
- [ ] Sonar Cloud quality gate passes
- [ ] CircleCi checks pass
- [ ] Cypress or Postman API check passes
- [ ] Test containers passed if modifications on the repository modules
- [ ] Developer created draft documentation PR
- [ ] New migration scripts checked
Can be run multiple times but only makes changes the first time
Display to user what script has done
- [ ] Validated on appropriate environment
- [ ] Existing test cases refactored

:rocket:

**Comment by patelami** [comment]
Env: 3.15.x
Result: PASS

Given I have set and enabled email SMTP for an application
And I initiate a login flow
Then I should ask to setup email when I sign in first time
And I click on next button
Then I should receive the code in email
