### ISSUE TITLE
Duplicate flows when saving an API multiple times too quickly

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#8447]
## :collision: Describe the bug

When saving an API after doing some modifications, if clicked multiple times on the save button (for example when the interface is slow and we're not sure if we missclicked), many flows are being duplicated in the API and they need to be deleted one by one after that, which can be quickly annoying.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Import the API provided on the zd ticket 4769
2. Then try to add new flow
3. Because of the nature of the api and the number of the flows the whole api is lagging when scrolling up/down on the flows
4. Try to save the new flow and will see that it was saved multiple times

## :rainbow: Expected behaviour
Expected to save only one instance of the flow

## Current behaviour
Saving multiple instances of the same flow, which is not expected

## :movie_camera: Useful information

![image](https://user-images.githubusercontent.com/89140082/189904377-ae422e16-9336-455a-9456-808d9b9ff439.png)

***Please complete the following information:***
 - Tested in 3.18.5

**Comment by gaetanmaisse** [comment]
Closing as it has been fixed in APIM 3.20+
