### ISSUE TITLE
[UI] Unable to load logo from URL and Favicon URL in new theme

### ISSUE THREAD

**Issue by patelami** [gravitee-io/issues#8450]
### Expected Behavior
As a user I should see updated logo from URL 

### Steps to Reproduce (for bugs)

1. Go to domain level settings > theme
2. Change the logo in hosted logo URL for login page: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
3. Update favicon URL to: https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/android.svg
4. The logo would appear in preview
5. Publish the theme
6. Initiate the login flow

### Current Behavior

- Logo would appear on preview in theme settings, but not on the application home page
[Application Home page](https://am.gateway.master.gravitee.xyz/ami-test/login?client_id=633ea133-b397-48c2-bea1-33b39788c261&response_type=code&redirect_uri=https%3A%2F%2Fwww.asda.com%2F)

- I can not see the browser tab icon updated from Favicon URL

[Settings > Theme](https://am.management.master.gravitee.xyz/environments/default/domains/ami-test/settings/theme?reload=true)

### Your Environment

* Version used: Master (3.19 release)

**Comment by leleueri** [comment]
Settings have been updated to the nightly environment to allow the two domains `github.githubassets.com` `dev.w3.org` in the img CSP directive.

Images are now visible.
