### ISSUE TITLE
[Gateway] Plan selector should throw 401 on wrong API-Key even if a keyless plan is available

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#8452]
## :collision: Describe the bug

With the refactoring of plan selection rules, we are no longer throwing 401 in case the API-Key provided by the consumer is not linked to any valid subscription if a keyless plan is available.

Related to #7824 

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Create an API with an API-Key plan & Keyless plan
2. Call your API with a valid API-Key, you get the api-key flow
3. Call your API without any API-Key, you get the keyless plan
4. Call your API with an unvalid API-Key, you get the keyless plan

## :rainbow: Expected behaviour
We should get a 401.

## :computer: Desktop:

***Please complete the following information:***
 - Environment: [e.g. 3.10.x] 3.18.7+

**Comment by gaetanmaisse** [comment]
All's good, validation has been done by the QA team (report can be found [here](https://docs.google.com/spreadsheets/d/1ZPw9cs3BHPmryWWFXJhb-Jo3uQ0mhMQLxOruTyPh0-Y/edit#gid=0))
