### ISSUE TITLE
[doc] Document theme builder for 3.19 release

### ISSUE THREAD

**Issue by ashraf706** [gravitee-io/issues#8454]
Need to update documentation for the new theme builder feature. 
The document could be in the Branding section: https://docs.gravitee.io/am/current/am_userguide_branding.html

**Comment by leleueri** [comment]
Working branch : https://github.com/gravitee-io/gravitee-docs/tree/issues/%238454-document-theme-builder-am

**Comment by tcompiegne** [comment]
PR https://github.com/gravitee-io/gravitee-docs/pull/861 has been reviewed and validated by technical writer. Wait the 3.19.0 before merging the PR. This issue can be closed for the time being.
