### ISSUE TITLE
[console] Issues when modifying API properties

### ISSUE THREAD

**Issue by ctschacher** [gravitee-io/issues#8456]
## :collision: Describe the bug
There are 2 issues when modifying an existing API property:
1. When the user wants to only modify the property key then there's no way to save and deploy it (no save pop-up or other save button available) 
2. When you start typing in the property value text field you can only type a single character and the `You have unsaved changes` pop-up appears preventing the user to continue typing since focus in not on the text field anymore 

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to an existing API
2. Click on 'Design' -> Properties
3. Try modifying an existing property key/value pair

## :rainbow: Expected behaviour
1. After modifying the property key identifier I should have the option to save my changes
2. I want to be able to change more than a single character at once in the property value text field

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.17.2 & 3.18.9-SNAPSHOT (haven't checked other versions yet)
 - OS: MacOs 12.6
 - Browser: Chrome version 105.0.5195.102 (Official Build) (x86_64)

**Comment by gaetanmaisse** [comment]
Closing as it looks to be fixed, at least in 3.20+
