### ISSUE TITLE
Multi oauth plan selection without selection rule

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#8460]
Usually when using multiple oauth plans, you should define selection rules to make sure plan selection will behave properly and the the right plan to execute will be selected.
Plan selection has recently evolved and the selection algorithm has been improved based on that assumption.
As selection rules are not always set it can have side effects such has dropping 401. 
This issue aims to revert back to the previous behavior.

**Comment by gaetanmaisse** [comment]
Validated by QA, result are available [here](https://docs.google.com/spreadsheets/d/1ZPw9cs3BHPmryWWFXJhb-Jo3uQ0mhMQLxOruTyPh0-Y/edit#gid=0)
