### ISSUE TITLE
[management-ui] [theme] error message too big when preview action failed

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8461]
We should work with the UX/UI team to find a better way to display this error.

![image.png](https://images.zenhubusercontent.com/601c1e775322cf42b09d4dc1/d06ea84c-24c2-4aab-b5f3-e6bc2bfc8345)

**Comment by patelami** [comment]
Env: 3.19.X
Result: PASS 
<img width="1430" alt="Screenshot 2022-09-20 at 11 51 01" src="https://user-images.githubusercontent.com/14215437/191239548-99fa4e06-bce2-4e2b-b086-00c0946900cf.png">
