### ISSUE TITLE
[gateway] [forms] we should not set static width for our html components

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8467]
That will lead to weird CSS issues : 

<img width="504" alt="css-issues" src="https://user-images.githubusercontent.com/1927438/190612008-2995c500-2fd7-461e-abea-10d0699e7262.png">

We should rely on percentage for at least the buttons, inputs, and zones

**Comment by patelami** [comment]
Env: 3.19.0 
Result : PASS

<img width="655" alt="Screenshot 2022-09-27 at 16 49 58" src="https://user-images.githubusercontent.com/14215437/192574301-9a519bb7-7f86-401d-a5f5-ea44b62c793a.png">
