### ISSUE TITLE
[doc] inform users about assets

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#8477]
Add note into documentation to say that all CSS provided by default by the GW prior to the 3.19 will be removed in a later version.

**Comment by leleueri** [comment]
Will be fixed into the PR linked to https://github.com/gravitee-io/issues/issues/8454

**Comment by tcompiegne** [comment]
PR https://github.com/gravitee-io/gravitee-docs/pull/861 has been reviewed and validated by technical writer. Wait the 3.19.0 before merging the PR. This issue can be closed for the time being.
