### ISSUE TITLE
[apim-policy]Assign Attributes or Metrics Reported not triggered when scope is On_Content_Response for Assign Attribute

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#8478]
1.  💥 Describe the bug Assign Attributes Policy when set to Scope On_Content_Response does not get triggered but if this is done on Request, so AA Policy on On_Content_Reqeust the policy works as expected.
2.  <g-emoji class="g-emoji" alias="sunrise_over_mountains" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f304.png">
     🌄 
     </g-emoji> To Reproduce Steps to reproduce the behaviour: 1\. Import the zip bellow. 2\. Import both the APIs on APIM and curl on Postman 3\. You have two cases where it worked as it should and you need to disable all but the Http Callout and with HC on Request and Response you will se the expected behavior. 4\. For the second case you need to enable and disable this:

!<span class="error">[image]</span>([https://user-images.githubusercontent.com/57534152/191007000-5bbaa792-5f6c-4ab4-b2ca-63efe571a5cc.png](https://user-images.githubusercontent.com/57534152/191007000-5bbaa792-5f6c-4ab4-b2ca-63efe571a5cc.png))

Also also in the Metrics Reporter first send a request with this:

{ "requestId": "$

 {request.id}",

 "transactionId": "${request.transactionId}",

 "requestContent": "${context.attributes['initialRequestContent']?json_string}"

 }

 and you will see the data in webhook.

 Now send a request with:

 {

 "requestId": "${request.id} 

", "transactionId": "$

 {request.transactionId} 

", "requestContent": "$

 {context.attributes['initialRequestContent']?json_string} 

", "responseContent": "$

 {context.attributes['initialResponseContent']?json_string} 

" }

and because of the last like you will not see anything in webhooks

1.  <g-emoji class="g-emoji" alias="rainbow" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f308.png">
     🌈 
     </g-emoji> Expected behaviour The policy should work on Response as it does on Request
2.  <g-emoji class="g-emoji" alias="movie_camera" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f3a5.png">
     🎥 
     </g-emoji> Useful information

<span class="error">[data.zip]</span>([https://github.com/gravitee-io/issues/files/9598438/data.zip](https://github.com/gravitee-io/issues/files/9598438/data.zip))

1.  ## :compuer: Desktop:

 _**Please complete the following information:**_ 

*   Environment: Docker-Desktop
*   OS: Windows 11
*   Browser: Google Chrome

1.  <g-emoji class="g-emoji" alias="warning" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/26a0.png">
     ⚠️ 
     </g-emoji> Potential impacts

 _**What are the impacted versions?**_ 

*   3.17.5, 3.18.8

**Comment by gaetanmaisse** [comment]
I'm closing this according to CSM's feedback
