### ISSUE TITLE
[gateway] unable to register user with password policy

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#8480]
If a template coming from the previous version is used for resetPassord, registerConfirmation or Registration then the from can't be validate. 

In 3.19, password-validation.js has changed, we should move this new version in password-validation-v2.js and restore the previous password-validation.js to allow existing custom templates to work after the migration

**Comment by patelami** [comment]
Env: 3.19.0
Result: PASS

Given I am using the[ password reset template from 3.18 version](https://github.com/gravitee-io/gravitee-access-management/blob/3.18.x/gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/reset_password.html) in 3.19 version
Then I should be able to successfully reset password
