### ISSUE TITLE
Update API Designer promotion behavior

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#8485]
Follow up #7645 & #8170

### Expected behavior

Since the Cockpit landing page has been updated, we should update the link for API Designer as follow : 
- Installation linked to cockpit - `https://cockpit.gravitee.io/?utm_source=apim&utm_campaign=api_designer&utm_medium=InApp&utm_term=registered`
- Installation not linked to cockpit - `https://cockpit.gravitee.io/?utm_source=apim&utm_campaign=api_designer&utm_medium=InApp&utm_term=not_registered`

### Additional informations

utm_term should match the following table : 

<table>
<tr>
	<th>Cockpit Installation Status
	<th>utm_term param to use
<tr>
	<td>PENDING
	<td>pending
<tr>
	<td>ACCEPTED
	<td>registered
<tr>
	<td>REJECTED
	<td>rejected
<tr>
	<td>DELETED
	<td>removed
<tr>
	<td>Any other status (even no status)
	<td>not register<b>ed</b>
</table>

**Comment by phiz71** [comment]
linked to https://github.com/gravitee-io/issues/issues/8334

**Comment by phiz71** [comment]
Shouldn't we use `https://cockpit.gravitee.io` when an installation is already linked to cockpit ?

**Comment by mouligno** [comment]
![image](https://media2.giphy.com/media/TJawtKM6OCKkvwCIqX/giphy.gif?cid=ecf05e47ohhgketfhp1vbasbjls9ayc8t4f3740vjx2v0dwz&rid=giphy.gif&ct=g)

**Comment by mouligno** [comment]
LGTM
