### ISSUE TITLE
[management-ui] simplify UX on delete dictionary 

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#8487]
When a i18n dictionary is deleted using the "bin" icon, we have to click on "save changes" after confirm the deletion in the dialog box.
Maybe we should send the delete request once the dialog box is closed to simplify the UX (I personnaly always forgot to click on save until now)

1. one lang
![image](https://user-images.githubusercontent.com/3110552/191475631-8a74bad7-188d-4e80-aa0e-d5ac0e74dbdb.png)
2. ask for deletion
![image](https://user-images.githubusercontent.com/3110552/191475700-a51d46cb-5ade-4a93-86f3-f7574799bbb8.png)
3. still need to save to validate the deletion
![image](https://user-images.githubusercontent.com/3110552/191475773-52541afc-5481-4760-8fd7-43b0c99e76cd.png)

**Comment by audrey-tlm** [comment]
yes please!

**Comment by ashraf706** [comment]
Discussed with @audrey-tlm and confirmed that we can remove the save change button for both add or delete language and translations

**Comment by tcompiegne** [comment]
👍

**Comment by ashraf706** [comment]
Fixed is implemented as part of : https://github.com/gravitee-io/gravitee-access-management/pull/2117

**Comment by patelami** [comment]
Env: Nightly
Result: PASS

Given I have deleted the translation 
And I have confirmed the deletion
Then the dictionary is removed from the list

https://user-images.githubusercontent.com/14215437/192564968-849b0730-072c-4bc6-a251-649f732d636d.mov
