### ISSUE TITLE
[Policy - HTTP-signature] Http-signature Policy is not compatible with 3.18.X

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#8488]
## :collision: Describe the bug
The Http Signature Policy has not been upgraded and the old versions are not compatible with 3.18.X of APIM

https://download.gravitee.io/#graviteeio-apim/plugins/policies/gravitee-policy-http-signature/

***What are the impacted versions?***
- 3.18.X

**Comment by ThibaudAV** [comment]
The policy works in 3.18.x with version 1.5
