### ISSUE TITLE
[gateway] [forms] CSS fix on forms pages

### ISSUE THREAD

**Issue by audrey-tlm** [gravitee-io/issues#8495]
Hi team, I have some feedback for some CSS values used in forms pages. I've attached a screenshot showing the new CSS values for some HTML elements. Thanks!

![Fix.png](https://images.zenhubusercontent.com/61fc4917f078f31c2ae16580/92478793-5ffd-433e-821e-be3fdc087e02)

**Comment by patelami** [comment]
Env: 3.19
PASS


<img width="1440" alt="Screenshot 2022-09-29 at 13 32 40" src="https://user-images.githubusercontent.com/14215437/193032230-57bd4d9f-6096-4246-a4e3-865fd23fd49e.png">
