### ISSUE TITLE
[management] Status codes in the dashboard are not sorted in order

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#8497]
## :collision: Describe the bug
The status codes in the dashboard in the Response status chart, are not sorted.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Create API and make several requests with curl or postman.
2. Have a mock policy to respond different status codes.
3. Go to Dashboard>Analytics>Response Status chart
4. See status codes not sorted

## :rainbow: Expected behaviour
The status codes should be sorted by name, ascending.

## Current behaviour
The status codes are not sorted.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.18.7
 - OS: [Docker Install]
 

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by gaetanmaisse** [comment]
Tested on 3.18.x env, working fine ✅ 
![image](https://user-images.githubusercontent.com/4112568/191829542-3c1f996f-afae-4878-a7d1-0c93964629cc.png)
