### ISSUE TITLE
[gateway] In Jupiter mode calls with a wrong ApiKey fallback on a Keyless instead of 401

### ISSUE THREAD

**Issue by gaetanmaisse** [gravitee-io/issues#8498]
## :collision: Describe the bug

In Jupiter mode calls with a wrong ApiKey fallback on a Keyless instead of 401.
Same behavior as https://github.com/gravitee-io/issues/issues/8452 but with Jupiter engine 

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:

 - Create an API with an API-Key plan & Keyless plan
 - Call your API with a valid API-Key, you get the api-key flow
 - Call your API without any API-Key, you get the keyless plan
 - Call your API with an invalid API-Key, you get the keyless plan 💥 

## :rainbow: Expected behaviour

Call an API with an invalid API-Key should lead to a 401 error

## Current behaviour

Keyless plan is selected

**Comment by RubenMMSantos** [comment]
Issue verified and confirmed as fixed.
When calling an API with an invalid API-Key the response returns a 401 error
![Screenshot 2022-09-29 at 12 27 21](https://user-images.githubusercontent.com/14939456/193019712-bf6c2a1e-5186-4daa-ac43-e6a9bd14fea3.png)
