### ISSUE TITLE
When upgrading from an old version to a new one, the previous gateway instance is still displayed in UI

### ISSUE THREAD

**Issue by LiliaEn** [gravitee-io/issues#8499]
When upgrading from an old version to a new one, the previous gateway is still displayed in UI

### Expected Behaviour
Previous gateway instance should not be displayed after upgrading to a newer version

### Current Behaviour
Previous gateway instance is still displayed in UI. Please see the screenshots:
![Screenshot 2022-09-22 at 13.21.40.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/ffd91903-85aa-4231-96d5-247f4a286b0e)
![Screenshot 2022-09-22 at 13.27.07.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/eee973ff-b4bb-4c99-89ca-9640e8cda8c2)

### Steps to Reproduce (for bugs)
1. Run an older version locally e.g. 3.18 (run this command in docker/quick-setuo/mongodb folder: APIM_REGISTRY=graviteeio.azurecr.io APIM_VERSION=3.18.x-latest docker-compose up)
2. Create some data
3. Stop the current version and upgrade to a newer one e.g. 3.19 ( APIM_REGISTRY=graviteeio.azurecr.io APIM_VERSION=3.19.x-latest docker-compose up)
4. Go to UI-> Gateways
5. Check the gateway instances displayed

### Your Environment
* Version used: 3.18-latest and 3.19-latest
* Browser Name and version:
* Operating System and version: macOS Big Sur v11.6

**Comment by gaetanmaisse** [comment]
Extracted from a slack discussion:
> Basically, it means you have the previous event from Gateway with the type `GATEWAY_STARTED`. If the last heartbeat was more than 5 minutes ago then the gateway appears as `UNKNOWN`
The question is, why was the event not updated to `GATEWAY_STOPPED`? Did you kill your docker-compose? My theory is the database shutdown before the gateway, making it impossible for it to update the event properly
So, I would say it’s not a bug.

Some UI improvements could be done to handle this case but it doesn't look like a blocking bug. WDYT @mouligno?

**Comment by mouligno** [comment]
Agreed
