### ISSUE TITLE
[gateway] [oauth2] basic client authentification failed for some special characters

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8501]
```URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: "'*"```

Regression from : https://github.com/gravitee-io/issues/issues/7803

**Comment by patelami** [comment]
Env: 3.15.x

Given I have created service with special characters in the client secret 
And I try and request access token for the service using curl command
Then I should successfully get the response
