### ISSUE TITLE
[management-ui] Deleted translation remains after deletion until saving

### ISSUE THREAD

**Issue by ashraf706** [gravitee-io/issues#8502]
#### Here is recoding: 

https://user-images.githubusercontent.com/10583111/191787189-b49ac96e-237d-4524-9faf-5c3233fd5616.mp4

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to `Domain ->Texts` and create a language and 2 translations.
2. Save them and all good as expected.
3. The deleted translation will remain and the other one which is not deleted will be removed from the table

## :rainbow: Expected behaviour
The deleted description should be removed.

**Comment by patelami** [comment]
env: 3.19
Result: PASS

Given i have deleted the translations
Then I should see the entry is removed from the list

https://user-images.githubusercontent.com/14215437/192559105-818a9758-a74e-4306-9a2f-a0f3a5c6040b.mov
