### ISSUE TITLE
IllegalArgumentException seen in logs when using comma in LDAP URL configuration.

### ISSUE THREAD

**Issue by farmborough** [gravitee-io/issues#8504]
## :collision: 
The help text for providing the URL of an LDAP identity provider asserts that it is possible to provide a second fail-over URL by separating with a comma, e.g.

`ldap://myserver.example.com:389, ldap://myserver2.example.com:389`

However, providing a URL string such as this triggers an `IllegalArgumentException` which is captured in the logs. It doesn't impede the creation of the IDP. It's not known if this prevents the IDP from functioning and should be investigated.

This is the help text:

`If fail-over functionality is desired, more than one URL can be specified, separated using comma (,)`

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to domain -> settings -> identities -> providers
2. Click the New IDP + button
3. Complete the form. For the purposes of the bug, it doesn't matter if you don't have any LDAP servers running. Just make sure you provided two URLs separated with a comma, as shown above.
4. Save and check the gateway logs. There should be an IllegalArgumentException logged, caused by the ldap URL you provided.

## :rainbow: Expected behaviour
Providing a fail-over URL for an LDAP server should not trigger an exception.

## Current behaviour
Runtime exception in logs. It's not clear whether this prevents the IDP from working.

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.18.x

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***
>= 3.18.x

**Comment by leleueri** [comment]
https://github.com/gravitee-io/gravitee-access-management/pull/2210
