### ISSUE TITLE
backport #8429 in 3.15

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#8510]
## :collision: Describe the bug
backport #8429 in 3.15
A similar behavior as #8429  was observed in 3.15 when a connection got closed by the backend.
The HealthCheck entry is not stored and the only error is : 
```
"level":"ERROR","thread":"vert.x-eventloop-thread-0","logger":"io.gravitee.gateway.services.healthcheck.rule.EndpointRuleHandler","message":"An error has occurred during Health check response handler","context":"default","exception":"io.vertx.core.http.HttpClosedException: Connection was closed\n"}
```

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:

## :rainbow: Expected behaviour
get all HC entries stored even if there is an issue on backend

## Current behaviour
if a Connection closed is received from the backend, no entries is seen in HC

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: [e.g. 3.10.x] 3.15.9

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by gaetanmaisse** [comment]
Closing as it has been backported and was part of APIM 3.15.18
