### ISSUE TITLE
[management] reset theme not apply on live preview

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#8513]
When we reset the theme, the live preview doesn't apply the default values.

![Reset-Theme-Preview.gif](https://images.zenhubusercontent.com/6026363e864bfc6af2b3aa2c/57375e29-cd0d-43c8-94c2-f79f8370541a)

**Comment by patelami** [comment]
Env: 3.19
Result: PASS


https://user-images.githubusercontent.com/14215437/192753949-fd9602b7-b5c8-43f1-8703-b86fc8b94e28.mov
