### ISSUE TITLE
[gateway] wrong css for error on weauthen enrollment page 

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#8514]
The error message is not following the error style (red into a shape)

![image.png](https://images.zenhubusercontent.com/6026363e864bfc6af2b3aa2c/327dbd57-a456-4651-8c53-9114830a0c33
)

**Comment by patelami** [comment]
Env: 3.19.0
I can still styling missing on the error message.

<img width="607" alt="Screenshot 2022-09-27 at 15 12 05" src="https://user-images.githubusercontent.com/14215437/192551933-1e7d4c49-f254-4ddc-b16b-1d2bd18757b8.png">

**Comment by patelami** [comment]
Env: 3.19.0
Result: PASS


<img width="609" alt="Screenshot 2022-09-28 at 12 17 34" src="https://user-images.githubusercontent.com/14215437/192765856-71273b34-9132-424f-9a55-78a8ca4b7733.png">
