### ISSUE TITLE
[MFA] Unable to sign in with new user if the self registration email is sent twice. 

### ISSUE THREAD

**Issue by patelami** [gravitee-io/issues#8515]
### Steps to Reproduce (for bugs)

1. Enable default IDP (mongo DB)
2. Setup and enable email MFA
3. The EnforceMFA policy should be enabled with an empty field.

<img width="1408" alt="Screenshot 2022-09-27 at 10 13 47" src="https://user-images.githubusercontent.com/14215437/192486003-68ac0e04-9498-4595-9c59-06d84f0f4cfe.png">

4. Create new user with self registration on
5. Send self registration email Twice
6. Setup and register user with the most updated link
7. Initiate the login flow
8. Register the user for email MFA

### Current behaviour (for bugs)
<img width="482" alt="Screenshot 2022-09-27 at 10 59 57" src="https://user-images.githubusercontent.com/14215437/192496775-b19a6722-7ab1-4bed-932d-5333826dd50b.png">

### Your Environment

* Version used: 3.15.x

**Comment by leleueri** [comment]
The EnforceMFA policy should be enabled with an empty field.

**Comment by leleueri** [comment]
![image](https://user-images.githubusercontent.com/3110552/192495685-87c03851-dad5-4c20-bd62-f7fdd6d62773.png)

![image](https://user-images.githubusercontent.com/3110552/192495749-624c9b46-33a2-432b-a21d-37948c424fb8.png)
