### ISSUE TITLE
[gateway] [forms] remove 'button' css class from the error text section

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8517]
Currently there is a cursor pointer when we hover error section which make me think this zone is 'clickable'.

**Comment by patelami** [comment]
Env: 3.19

@leleueri @tcompiegne 

I can still see beam cursor on the error. Are we expecting arrow cursor or beam cursor on error message? 


https://user-images.githubusercontent.com/14215437/192806259-f1aeed1f-c326-437d-a588-550993605c5f.mov

**Comment by patelami** [comment]
Env: 3.19
Result: PASS

the hand cursor is not shown when hovering on error message
