### ISSUE TITLE
[gateway] [forms] MFA alternative challenge CSS is broken

### ISSUE THREAD

**Issue by ashraf706** [gravitee-io/issues#8519]
<img width="500" alt="broken-alternative-challenge" src="https://user-images.githubusercontent.com/10583111/192515422-d579ebd0-a59a-46e8-b2fb-7e962f1a1102.png">

###  Step to reproduce:

1. Add couple of factors in the app (lets's say SMS and recovery code).
2. Register the MFA and complete sign in process
3. Log out
4. Login and during MFA challenge steps select `Having trouble? Try other methods` link to get the broken form

**Comment by tcompiegne** [comment]
I had the same issue with the MFA enroll page, I will handle this one.

**Comment by patelami** [comment]
<img width="605" alt="Screenshot 2022-09-28 at 11 44 04" src="https://user-images.githubusercontent.com/14215437/192759655-5446d54b-5d2c-4536-beca-cc9c391fdc80.png">
