### ISSUE TITLE
[gateway] [forms] bad french traduction for recovery code

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8520]
`mfa.recovery.code=Récupérer le code` => `mfa.recovery.code=Code de secours`

**Comment by patelami** [comment]
Env: 3.19.0
Result: PASS

<img width="601" alt="Screenshot 2022-09-28 at 15 07 28" src="https://user-images.githubusercontent.com/14215437/192801179-9d9bd206-a982-4b80-bd98-fcfd1cd9c215.png">
