### ISSUE TITLE
[gateway] [forms] missing description for MFA recovery code

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8521]
I would expect the MFA recovery code to have the following text : "Veuillez saisir l'un de vos codes de secours"

MFA recovery code : 

<img width="663" alt="Capture d’écran 2022-09-27 à 16 22 41" src="https://user-images.githubusercontent.com/1927438/192553013-f55873b4-2601-4ed5-afc1-eabdb4d1f28f.png">

MFA email : 

<img width="627" alt="Capture d’écran 2022-09-27 à 16 23 46" src="https://user-images.githubusercontent.com/1927438/192553147-41163237-6b2c-44c4-9b45-844b3b979c7e.png">

**Comment by patelami** [comment]
Env: 3.19
Result: PASS
<img width="604" alt="Screenshot 2022-09-28 at 11 21 04" src="https://user-images.githubusercontent.com/14215437/192758258-4b4d293c-7139-4701-afc7-3c231f735464.png">


<img width="604" alt="Screenshot 2022-09-28 at 11 39 17" src="https://user-images.githubusercontent.com/14215437/192758764-65c553cb-7e17-484b-864a-b583d0bf2ecf.png">
