### ISSUE TITLE
[gateway] [forms] missing placeholder and autofocus for the MFA challenge page

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8522]
Excepted behavior : 

<img width="639" alt="Capture d’écran 2022-09-27 à 16 27 30" src="https://user-images.githubusercontent.com/1927438/192554068-b1c13e14-ec16-4fd5-8759-95d885054557.png">

**Comment by patelami** [comment]
Env: 3.19.0

Result: PASS

<img width="598" alt="Screenshot 2022-09-28 at 15 06 41" src="https://user-images.githubusercontent.com/14215437/192806476-d4b71560-4172-47bd-bcec-ca2a42bab1f5.png">
