### ISSUE TITLE
[gateway] [emails] add background and align center

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8523]
![image](https://user-images.githubusercontent.com/1927438/192561282-84bb894e-fc19-409e-af49-5ce3ac1d5801.png)

**Comment by patelami** [comment]
Env: 3.19.0
Result: PASS
<img width="976" alt="Screenshot 2022-09-29 at 10 12 02" src="https://user-images.githubusercontent.com/14215437/192991660-2d7a659a-9664-4367-a1b6-0aa1d71f7a8a.png">
