### ISSUE TITLE
[gateway] sms enrollment is broken

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#8528]
When the user doesn't have phoneNumber, the SMS Factor can"t be enrolled because the field is not editable and the phone number can't be provided

![image.png](https://images.zenhubusercontent.com/6026363e864bfc6af2b3aa2c/1d60b3de-5485-4427-be30-ab41b4bbd074)

**Comment by tcompiegne** [comment]
I think we can set it after clicking the dropdown country flags but indeed it's very weird.

**Comment by ashraf706** [comment]
Pull request created: https://github.com/gravitee-io/gravitee-access-management/pull/2137

**Comment by patelami** [comment]
Env: 3.19
Result: PASS
<img width="614" alt="Screenshot 2022-09-30 at 15 21 30" src="https://user-images.githubusercontent.com/14215437/193290866-eb57b1a3-9027-4cea-9ed7-164b965306fa.png">
