### ISSUE TITLE
[console] Dynamic Properties broken scheduler

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#8529]
## :collision: Describe the bug
Not able to change the first value for schedule in Dynamic Properties. If the first Dynamic Properties was set to for example 10 seconds no matter how may times you change it it will be stuck on the first one.

It can also be seen here, no matter what value we set here the value you set first will stay.

![image](https://user-images.githubusercontent.com/57534152/192753651-89d8d455-1cd0-4a1c-9879-f4016f7b59f3.png)

## :sunrise_over_mountains: To Reproduce
1. Create/Import simple API and go to Design to Properties
2. Create a Dynamic Properties

![image](https://user-images.githubusercontent.com/57534152/192754250-57cf38ea-5bef-4440-81ae-751c41b228d0.png)

3. The moment you set the time it will reset (UI BUG?) and later if we close the config you will se the scheduler, meaning the DP are configured:

![image](https://user-images.githubusercontent.com/57534152/192754021-a58b1bc7-bd0d-41d4-879a-3c669652eb1f.png)

4. Now try to reconfigure to a different time and minimize and you will see the time did not change.

WORKAROUND: Export the API, change the time and Import the same API.

## :rainbow: Expected behavior
We should be able to reconfigure the Dynamic Properties without an issue.

## :computer: Desktop:

***Please complete the following information:***
 - Environment: Docker-Desktop 3.18.X
 - OS: Windows 11
 - Browser: Google Chrome
 
## :warning: Potential impacts

***What are the impacted versions?***
- 3.18.X

**Comment by gaetanmaisse** [comment]
Merged, will be released in 3.18.14
