### ISSUE TITLE
[gateway] [form] wrap error on registration confirmation page

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#8530]
The error message isn't wrapped by a red shape in the confirm registration form.

![image.png](https://images.zenhubusercontent.com/6026363e864bfc6af2b3aa2c/d029887a-2831-4e52-b54b-b7f0c356ca33)

**Comment by patelami** [comment]
Env: 3.19
Result: PASS
<img width="605" alt="Screenshot 2022-09-29 at 16 11 17" src="https://user-images.githubusercontent.com/14215437/193070135-51d87e96-bb0a-4684-8b7e-577b30981105.png">
