### ISSUE TITLE
[gateway] [forms] bad alignment for grey sections

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8534]
Must be :  

```
text-align: center;
padding: 8px
```

<img width="696" alt="Capture d’écran 2022-09-28 à 22 33 29" src="https://user-images.githubusercontent.com/1927438/192883289-73b4d037-e1ef-4584-87cf-0be077d3d199.png">

<img width="664" alt="Capture d’écran 2022-09-28 à 22 32 55" src="https://user-images.githubusercontent.com/1927438/192883301-4749b8e4-b531-42e5-b543-29d090e7cb93.png">

**Comment by patelami** [comment]
Env: 3.19
Result: PASS

<img width="602" alt="Screenshot 2022-10-03 at 09 09 57" src="https://user-images.githubusercontent.com/14215437/193569531-fdf3ef98-6148-44d1-bc50-21f5b57389aa.png">
