### ISSUE TITLE
[gateway] [forms] switch account should be a simple link

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8536]
Currently the switch account action has the same style as a social button.

**Comment by patelami** [comment]
Env: 3.19.0
Result: PASS

<img width="608" alt="Screenshot 2022-09-29 at 16 15 04" src="https://user-images.githubusercontent.com/14215437/193070693-250941f8-f2cd-4131-8c61-a92a93d31a77.png">
