### ISSUE TITLE
[UI] Text is not aligned in centre for button

### ISSUE THREAD

**Issue by patelami** [gravitee-io/issues#8538]
The text on button is aligned top and not centre.   

![Screenshot 2022-09-29 at 09.50.58.png](https://images.zenhubusercontent.com/6037d57eba9d3cc0b0412549/2d12fc5d-bb37-46f3-bc29-6f38f7124ed4)

**Comment by leleueri** [comment]
@patelami can you try to force the refresh of the page ?
I don't have this issue, maybe  you main.css has been cached by the browser

**Comment by leleueri** [comment]
Not an issue as the main.css was cached by the browser
