### ISSUE TITLE
[gateway] [forms] remove style for FranceConnect button

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8539]
Current behavior : 

<img width="594" alt="Capture d’écran 2022-09-29 à 11 20 38" src="https://user-images.githubusercontent.com/1927438/192996966-2fac4c75-673d-4832-8a89-1df32391bbf3.png">

Expected behavior : 

![image (6)](https://user-images.githubusercontent.com/1927438/192997659-a16d0664-1a8b-4a9e-a6e3-1befb2f6450c.png)

**Comment by patelami** [comment]
Env: 3.19.0
Result: PASS

<img width="600" alt="Screenshot 2022-09-29 at 16 17 28" src="https://user-images.githubusercontent.com/14215437/193071235-0f39c1f8-b50c-4139-b033-89cd418f1284.png">
