### ISSUE TITLE
[portal] Incorrect oauth2 redirect_uri if serving the application under a path

### ISSUE THREAD

**Issue by fredrikhl** [gravitee-io/issues#854]
### Expected Behavior
If hosting the webui-application for apim under a path prefix, e.g. `https://example.org/prefix/`, then `https://example.org/prefix/` should be the `redirect_uri`-parameter sent to the oauth2 authorization endpoint.

Currently `window.location.origin` is used as `redirect_uri`, which will not include any path prefix.

### Possible Solution
The `redirect_uri` should be set to `window.location.origin + window.location.pathname`. Note that this would cause the `redirect_uri` for all current users *not* using a path prefix to change; `https://api.example.org` → `https://api.example.org/`.

Alternatively, the application could respect an `authentication.oauth2.redirectUri`-setting in the `constants.json` config file.

### Steps to Reproduce (for bugs)

1. Configure the application to use OAuth2, and host it under some path prefix, e.g.:

```
# /etc/nginx/default.d/example.conf
location /ui/ {
    alias /opt/gravitee/apim-ui/;
    try_files $uri$args $uri$args/ $uri $uri/ /index.html =404;
}
```

2. Try to complete login using OAuth2.

**Comment by brasseld** [comment]
Hi @fredrikhl, 

I'm not sure that path prefix change is a big deal.
It's just a matter of authorized redirect uris from authorization server configuration. So I supposed current users can handle it very easily.

In any case, we can add a "breaking changes" in the migration guide (https://docs.gravitee.io/apim_installguide_migration.html) to reflect it.

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/gravitee-management-webui/commit/1b57b9bb6997042d18c7f58c36887df07cae7120
