### ISSUE TITLE
[management] Archived applications make user unable to view other applications

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#8540]
## :collision: Describe the bug

With a 'user' role, the applications (being application primary owner or owner) can not be displayed if the user was already a member of a deleted application.
The response payload is :

{
  "message" : "1 applications has no identified primary owners in this list 08e91205-6f3e-41ce-a912-056f3e21ce86.",
  "technicalCode" : "unexpected",
  "http_status" : 500
}

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:

- log in with admin
- create an application
- add application1 as member of this application (I tested with USER role, but I think its the same with another role)
- Delete the application
- log out
- log in with appication1
- try to list all your applications

## Current behaviour
A clear and concise description of what is currently happening.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: [3.18.7]
 
 

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by apoddany** [comment]
maybe linked to #8567

**Comment by phiz71** [comment]
Fixed in 3.18.12 with https://github.com/gravitee-io/issues/issues/8567
