### ISSUE TITLE
[gateway] [forms] clean up templates

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8548]
For simplicity I think we can remove references to placeholder.js and material.js scripts which are not used anymore for the 3.19.0.

Please have a look to the list of the default templates to remove any dead / useless javascript codes : 

https://github.com/gravitee-io/gravitee-access-management/tree/3.19.x/gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views

**Comment by patelami** [comment]
Env: 3.19
Result: PASS

I can see the preview of all the screens in  theme section loading fine.
