### ISSUE TITLE
Helm charts to be upgraded, system proxy to be included for configuration

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#8549]
## :collision: Describe the bug

the part for declaring/deploying system proxy is missing in the helm charts and needs to be added

https://docs.gravitee.io/apim/1.x/apim_policies_callout_http.html#http_client_proxy_options

**Comment by a-cordier** [comment]
Hi, 

I just double checked the helm charts and configuring system proxy is doable by replicating the whole system configuration block under the gateway section of a values file

see https://github.com/gravitee-io/helm-charts/blob/543c79d684d088b6e3bc495e76b583ca4f8a369f/apim/3.x/templates/gateway/gateway-configmap.yaml#L189

**Comment by ppgravitee** [comment]
#system:
#  # Proxy configuration that can be used to proxy request to api endpoints (see endpoint http configuration -> Use system proxy).
#  proxy:
#    type: HTTP #HTTP, SOCK4, SOCK5
#    host: localhost
#    port: 3128
#    username: user
#    password: secret

cf [https://docs.gravitee.io/apim/3.x/apim_installguide_gateway_configuration.html](https://docs.gravitee.io/apim/3.x/apim_installguide_gateway_configuration.html )
