### ISSUE TITLE
[gateway] [form] disable button on ForgotPassword

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#8552]
On forgotPassword if the field is empty, the submit button should be disabled

![image.png](https://images.zenhubusercontent.com/6026363e864bfc6af2b3aa2c/d2ef36a4-dfc9-4f68-aa8f-574e0ea86afen)

**Comment by tcompiegne** [comment]
Tests on 3.19.x environment :

Nominal case : PASS
Custom field : PASS
Multiple custom fields : PASS
Confirm identity : PASS
