### ISSUE TITLE
Error when trying get the subscribers to an api

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#8567]
## :collision: Describe the bug
when using the rest-api to get the subscribers to an api and doing the following call

http://localhost:8083/management/organizations/DEFAULT/environments/DEFAULT/apis/a4ca3212-cd0e-4029-8a32-12cd0ee029c1/subscribers?

, getting the following message as a response

{
    "message": "3 applications has no identified primary owners in this list a3b41961-054e-4d5f-b419-61054eed5f95 / c6da3a66-8fe0-4f6d-9a3a-668fe0ef6d79 / 79d31608-e052-4338-9316-08e052f338d2.",
    "technicalCode": "unexpected",
    "http_status": 500
}

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:

1. create an application
2. subscribe to the api with the newly created application
3. the application needs to be on pending
4. delete the application from the environment 
5. make the call 
6. in the response message the list is getting bigger with the applications we are deleting 

![image](https://user-images.githubusercontent.com/89140082/195625567-85689009-9917-41d9-a193-b9d7aed576db.png)

 - Environment: [e.g. 3.18.10]

**Comment by kirestoj01** [comment]
This bug also causes issues with the Analytics. 
![image](https://user-images.githubusercontent.com/98313939/195789521-eaa1e9d7-c1ee-408f-a214-4e0b7c72c49a.png)
