### ISSUE TITLE
Creating API with consumer id instead of storing API in DB

### ISSUE THREAD

**Issue by venkpoli** [gravitee-io/issues#857]
Hi Team,
Is there a way to create api with consumer id, so that i can store consumer it in my DB to authenticate my api instead of storing api in my db to validate.

BR
Venkatesh.P

**Comment by brasseld** [comment]
I'm sorry, but I still did not get you on this issue.

What are you looking for exactly ?
Do you need something like webhook and be called when a new API or application is created in Gravitee ?

**Comment by brasseld** [comment]
No more news, closing this ticket.
