### ISSUE TITLE
Create envir/setup for remote gRPC to be used with APIM

### ISSUE THREAD

**Issue by RubenMMSantos** [gravitee-io/issues#8574]
There is a current need to test the compatibility between APIM Jupiter mode and gRPC server, but it is really hard and time consuming to perform this test locally due to incompatibility issues.

For more information -> https://github.com/gravitee-io/issues/issues/8083
link to the gRPC server docker-compose that was used: https://github.com/gravitee-io/gravitee-sample-apis/blob/7760-fix-grpc-ssl/docker-compose.yml

Running both gRPC server and APIM on docker containers does not solve this problem because the containers are not able to communicate with each other.

An attempt was done to merge both containers into one to try and solve the "communication" problems between gRPC server and APIM but with no success.

**Comment by marcambier** [comment]
Additional information : For my local tests of GRPC server, I used this docker-compose : https://github.com/gravitee-io/gravitee-sample-apis/blob/7760-fix-grpc-ssl/docker-compose.yml
Here is a demo how I test it locally : https://drive.google.com/file/d/1VxT1ZLRwIaa_auYg7etBTgGVAzMrhtBN/view?usp=sharing
