### ISSUE TITLE
Not able to open Application and API in a new tab by right-clicking their names

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#8589]
# Describe the bug

When you open the applications tab in the console and right-click on the application name, you get the wrong right-click menu. There is the same behaviour for API names in the APIs tab.

# Reproduce 

Steps to reproduce the behaviour:

 1\. Go to the applications or APIs tab in the console

 2\. Right-click on any applicationAPIi name

 3\. See the right-click menu there is no “Open in a new tab“ option

# Impacted Version

3.18+

**Comment by mouligno** [comment]
@ThibaudAV angular migration ?

**Comment by ThibaudAV** [comment]
Yes :/ , we could add a <a> component to the ✏️  (or 👁️ ) button on the right to be able to do it. 

Workaround that I use when it happens: Open the api and do a cmd+click on the previous page of your browser 😁
