### ISSUE TITLE
Proxy fields not disabled when System proxy activated in endpoint configuration

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#8590]
# Describe the bug

When System Proxy is enabled on endpoint configuration on a group and only on one endpoint, the proxy settings get greyed out, which is normal. 

After a refresh or when coming back to the screen, the System Proxy is still enabled, but the fields related to proxy settings are active instead of greyed out.

!<span class="error">[image]</span>([https://user-images.githubusercontent.com/57534152/197217385-cfba29a0-134b-4562-8b4e-ea4bf3067974.png](https://user-images.githubusercontent.com/57534152/197217385-cfba29a0-134b-4562-8b4e-ea4bf3067974.png))

# To Reproduce

Steps to reproduce the behaviour: 

1.  Create an API
2.  Go to Proxy > Endpoints > Select an endpoint > Configuration > Enable Use Proxy and System Proxy
3.  Save > Proxy-related fields are disabled
4.  Refresh > Proxy-related fields aren’t disabled anymore

# Expected behavior 

Proxy-related fields should stay disabled after the refresh.

# Impacted versions

3.18+

**Comment by mouligno** [comment]
can the config be updated ? or do we "just" have the field in UI ?
