### ISSUE TITLE
API Subscription not working after closing and re-creating

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#8600]
<ol> 
 <li> 
  <ol> 
   <li>:collision: Describe the bug<br> create an application and subscribe that to an API with a Shared API Key. After that we close the subscription and re-create it on the same API for the same Application and the same Shared API Key. </li> 
  </ol> </li> 
</ol> 
<p>When performing a call using this Shared API Key, that is active for this Application, always getting a '401 - Unauthorized' message:</p> 
<p>!<span class="error">[image]</span>(<a href="https://user-images.githubusercontent.com/89140082/197790899-e65ad00d-a107-4ed0-ba25-51e47d953921.png" class="external-link" rel="nofollow noreferrer">https://user-images.githubusercontent.com/89140082/197790899-e65ad00d-a107-4ed0-ba25-51e47d953921.png</a>)</p> 
<ol> 
 <li> 
  <ol> 
   <li>:sunrise_over_mountains: To Reproduce<br> Steps to reproduce the behaviour:<br> 1\. Create two api's<br> 2\. Subscribe to both api's with shared api key<br> 3\. Try and test both are working with the same key<br> 4\. Close the subscription and re-create it on the same API for the same Application and the same Shared API Key<br> 5\. do the test and call the api's with the shared key, check the error (response in postman)</li> 
  </ol> </li> 
</ol> 
<ol> 
 <li> 
  <ol> 
   <li>:rainbow: Expected behaviour<br> The shared key to work for both api's as it did previously</li> 
  </ol> </li> 
</ol> 
<ol> 
 <li> 
  <ol> 
   <li>Current behaviour<br> Not working 401</li> 
  </ol> </li> 
</ol> 
<ol> 
 <li> 
  <ol> 
   <li>:movie_camera: Useful information<br> !<span class="error">[image]</span>(<a href="https://user-images.githubusercontent.com/89140082/197791758-8962f3c7-1f99-41a2-82ad-f062c76754e1.png" class="external-link" rel="nofollow noreferrer">https://user-images.githubusercontent.com/89140082/197791758-8962f3c7-1f99-41a2-82ad-f062c76754e1.png</a>)<br> !<span class="error">[image]</span>(<a href="https://user-images.githubusercontent.com/89140082/197791810-04be982d-2a78-4967-9057-e4a8acdcff46.png" class="external-link" rel="nofollow noreferrer">https://user-images.githubusercontent.com/89140082/197791810-04be982d-2a78-4967-9057-e4a8acdcff46.png</a>)<br> !<span class="error">[image]</span>(<a href="https://user-images.githubusercontent.com/89140082/197791837-8f4652df-fcee-4b5d-ba4b-699127275a81.png" class="external-link" rel="nofollow noreferrer">https://user-images.githubusercontent.com/89140082/197791837-8f4652df-fcee-4b5d-ba4b-699127275a81.png</a>)</li> 
  </ol> </li> 
</ol> 
<p>**<b>Please complete the following information:</b>**</p> 
<ul class="alternate" type="square"> 
 <li>Environment: <span class="error">[e.g. 3.17.2]</span></li> 
</ul>

**Comment by mouligno** [comment]
@zveljanoski is it still the case with latest 3.18.x ?

**Comment by ppgravitee** [comment]
Antoine Mouliere commented: reproduced on 3.18.x - API : 0947dc57-8017-49d0-87dc-57801799d00d
