### ISSUE TITLE
Provide "forgot password" url for IdentityFirstLogin

### ISSUE THREAD

**Issue by ppgravitee** [gravitee-io/issues#8608]
Currently, the identityFirstLogin page doesn’t display the forgot password link and the variable forgotPasswordAction is not provided to the template engine.

Some users may want to display a forgot password on this page, so the variable should be generated and provided to the template engine to allow its usage in the template.

:note: Need to ask to the PO if we also have to display the “forgot password” link in the default template.

**Comment by ppgravitee** [comment]
Sagar Chauhan commented: Environment: 3.18.x
Version 3.18.10
Result: PASS

*Steps*
1. Enabled ‘Forgot password’ and ‘Identifier-first login’ for my domain

!Screenshot 2022-11-03 at 13.42.58.png|width=1693,height=683!

The Forgot password link does not display

!Screenshot 2022-11-03 at 13.44.52.png|width=504,height=312!

2. Created and enabled a custom Form for Identifier-first login with the [HTML|https://github.com/gravitee-io/gravitee-access-management/blob/3.18.x/gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/identifier_first_login.html] and code snippet as per below and saved.

{noformat}<div th:if="${allowForgotPassword}">
                            <a th:href="${forgotPasswordAction}">Forgot Password ?</a>
                        </div>{noformat}

!Screenshot 2022-11-03 at 13.58.45.png|width=2281,height=897!

4. Initiated login flow where the Forgot Password link is displayed

!Screenshot 2022-11-03 at 14.01.39.png|width=513,height=346!

4. Clicked on Forgot Password link and taken Forgot password page where I entered the users email address.

!Screenshot 2022-11-03 at 14.02.49.png|width=797,height=318!

5. Received the password reset link, reset the password successfully and was able to login into the application with the new password.

!Screenshot 2022-11-03 at 14.04.30.png|width=1476,height=472!

!Screenshot 2022-11-03 at 14.04.50.png|width=769,height=289!

!Screenshot 2022-11-03 at 14.06.53.png|width=761,height=175!

CC [~accountid:60b76af048b8950069705689]

**Comment by leleueri** [comment]
https://github.com/gravitee-io/gravitee-access-management/pull/2212
