### ISSUE TITLE
Groups break an api in a shared environment

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#8621]
# Describe the bug

In the case of shared environments (multiple environments in the same database), groups of one environment can be added to an API of another environment. The consequence is that it breaks the UI

<span class="image-wrap" style="">![picture](https://user-images.githubusercontent.com/1028285/199672528-8e6d7e43-9f9c-4359-82e8-00e0db7920ef.jpg)</span>

# To Reproduce

Steps to reproduce the behaviour:

1.  Create 2 environments (A and B) in the same APIM installation
2.  Create an API on both env
3.  In env A, create a group and click on "Assign this group to all APIS"
4.  open the API of env B
5.  The UI is broken and you will see the group in the database

# Expected behaviour

Groups must be limited to their environment.

# Current behaviour

Groups are assigned to all environments

**Comment by NicolasGeraud** [comment]
here is a mongo script to clean the database
[cleanGroups.txt](https://github.com/gravitee-io/issues/files/9926670/cleanGroups.txt)

**Comment by gaetanmaisse** [comment]
Closing as it is fixed in the latest version of APIM (at least APIM 3.20+)
