### ISSUE TITLE
issue: applications has no identified primary owners in this list 

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#8625]
## :collision: Describe the bug
When trying to access the logs of an api facing an issue, or in other instance when creating new api

![image](https://user-images.githubusercontent.com/89140082/199933808-b9fe4cbe-875a-4136-83c0-87fac00d8180.png)

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Created an application, and subscribe to an api
2. Delete the application
3. Try to access the logs
![image](https://user-images.githubusercontent.com/89140082/199934507-fa9c9985-4960-463b-bd0a-3b8219dedac1.png)

If then we restore, the deleted application, we are able to access the logs again

Second case:
1. When using the ui to create new api, not possible seeing the error from the screenshot above
2. It  is also the case when deploying an API via the M-APIs, geting the same error
3. Still the API is created, but not shown in the UI. 
4. After a restart of the M-API the API is shown in the UI as Not Started.

## :rainbow: Expected behaviour
To be able to see the logs/create new api (not replicated)
## Current behaviour
The error occurs, and there are no logs visible in the ui, but the exception shown in the screenshot

## :computer: Desktop:

***Please complete the following information:***
 - Environment: [e.g. 3.18.10]
 
might be related

https://github.com/gravitee-io/issues/issues/8540

https://github.com/gravitee-io/issues/issues/8567

**Comment by zveljanoski** [comment]
getting the same error regardless if the api has keyless or has an api-key plan

**Comment by atouboulic** [comment]
Hello, I have the same issue with version 3.19.0 after migrating from version  3.10.0.

**Comment by akshaygarg** [comment]
I think they are related : https://github.com/gravitee-io/issues/issues/8641

**Comment by phiz71** [comment]
Fixed in 3.18.12 with https://github.com/gravitee-io/issues/issues/8567
