### ISSUE TITLE
[APIM] Update helm charts for version 3.19.x

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#8633]
Please update helm charts for version 3.19.x

**Comment by gaetanmaisse** [comment]
Wait for 3.20.1 next week and update to it directly

**Comment by gaetanmaisse** [comment]
I've got some exciting news to share - we've finally squashed that pesky bug that's been bugging you! 🎉 
The fix is included in the latest version of the APIM Helm Chart (v3.1.62), so you can finally take a breather and let your API do the heavy lifting.
