### ISSUE TITLE
Swagger Required Parameters, should not be required

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#8634]
## :collision: Describe the bug
The parameters in a swagger file, should not be required, as defined in the definition, yet still are 

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1\. Import the attached api 
2\. Publish it
3\. Go to portal and check documentations 
4\. This is how the parameters are defined (required: false)
![image](https://user-images.githubusercontent.com/89140082/200332281-cdd749fe-9bd6-4539-ae85-788b1566b406.png)

5\. Yet we are seeing them as required in the portal
![image](https://user-images.githubusercontent.com/89140082/200332491-b7c145ad-0ad5-4af4-838c-1ad5dbe3f3b8.png)

6\. Also one parameter that is really defined as required, is not shown at all in the portal 
def:
![image](https://user-images.githubusercontent.com/89140082/200332688-7cd47a82-2830-4a74-8901-12667ab9ee8c.png)
portal:
![image](https://user-images.githubusercontent.com/89140082/200332850-75503149-f900-499d-a593-e8b82a085c5a.png)
7\. Even though the fields are shown as required in the portal, we are not able to fill them 

https://user-images.githubusercontent.com/89140082/200333395-4d92a4a3-38ef-462b-b0f7-283976ca5dc5.mp4

## :rainbow: Expected behaviour
(required: false) not to be required field

## Current behaviour
required: false is still required

[jsonShortened.zip](https://github.com/gravitee-io/issues/files/9952490/jsonShortened.zip)

 - Environment: tested 3.18.11, 3.15.18

**Comment by phiz71** [comment]
Duplicates #7099
