### ISSUE TITLE
[management-api] Access Control for sharding tags

### ISSUE THREAD

**Issue by fredrikhl** [gravitee-io/issues#864]
Currently, any API owner can apply any existing tag to their API, controlling which shards the API will get deployed to.

Given the following setup:

* Tags: "test", "production"
* QA cluster: test.example.org, tags: "test,production"
* Production cluster: api.example.org, tags: "!test,production"

As a system owner, I want to restrict access to the production cluster, but I want any odd developer to deploy their APIs to the test cluster. Currently there's no way for me to do that, other than setting up two separate Management APIs with separate databases and separate authentication integrations.

### Expected Behavior

I should be able to create roles, and then restrict assignement of certain tags to users that have that role. Only API owners with the given role will be able to assign the "production" tag to their API, marking it for deployment to the production cluster.

### Current Behavior
Currently, any API owner can assign any existing sharding tag to their API. There is no way to restrict API owners from assigning any tag to their own API.

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/issues/issues/1995

Gravitee.io API 1.25.x
