### ISSUE TITLE
Dev Portal gives error after an application is archieved 

### ISSUE THREAD

**Issue by akshaygarg** [gravitee-io/issues#8641]
When an application is deleted, it also deletes the reference to an owner. This causes an error on the devportal while making a call to get all the which are are available for a user.

Please check the snapshot below, at the moment i can cleanup the data from the db and it stops the error but i think there should be way around like disabling the archive behavior.

![image](https://user-images.githubusercontent.com/3895934/201103814-939243c3-0b56-4036-9168-01681e98f449.png)

**Comment by phiz71** [comment]
Fixed in 3.18.12 with https://github.com/gravitee-io/issues/issues/8567
Will be part of the next 3.19.4 (no ETA yet)
