### ISSUE TITLE
 APIMx3 installation in Openshift

### ISSUE THREAD

**Issue by mira1991** [gravitee-io/issues#8645]
Hello,

I tried to install the latest helm chart of APIMx3 in an openshift cluster v 4.10.
the API pods are crashing. In the logs, i found this java error:

ERROR i.g.r.a.s.node.GraviteeApisNode - An error occurred while starting component interface io.gravitee.rest.api.service.InitializerService
java.util.NoSuchElementException: No value present

I use the image below : graviteeio/apim-management-api:3.18.10

Any one had an idea about it please !

Thanks 🙂

**Comment by gaetanmaisse** [comment]
Can you try the last 3.18 version and let us know if you're still facing the issue?

**Comment by gaetanmaisse** [comment]
I hope you're doing well. It seems that there hasn't been any activity on your issue for quite some time, so I will be closing it for now. Don't worry though, if you still need help with this or have any other issues, feel free to open a new one anytime. Thanks for your understanding and have a great day!
