### ISSUE TITLE
[AM] - Theme edition page desn't render correctly

### ISSUE THREAD

**Issue by NathanFirmo** [gravitee-io/issues#8654]
1.  ## :collision: Describe the bug
     Theme edition page desn't render correctly, because the css file is not loaded.
2.  ## :sunrise_over_mountains: To Reproduce
     Steps to reproduce the behaviour:

1\. Install Gravitee AM on docker as described in <span class="error">[docs]</span>([https://docs.gravitee.io/am/current/am_installguide_docker_compose.html](https://docs.gravitee.io/am/current/am_installguide_docker_compose.html)).
 2\. Go to ***settings > theme***.
 3\. See the error

!<span class="error">[image]</span>([https://user-images.githubusercontent.com/79997705/202271169-35bf3a7d-c21e-4198-9453-5744345e1500.png](https://user-images.githubusercontent.com/79997705/202271169-35bf3a7d-c21e-4198-9453-5744345e1500.png))

1.  ## :rainbow: Expected behaviour
     It should be able to render correctly.

!<span class="error">[image]</span>([https://user-images.githubusercontent.com/79997705/202276133-ed6ea377-9f19-4f51-b737-2d8e0966317d.png](https://user-images.githubusercontent.com/79997705/202276133-ed6ea377-9f19-4f51-b737-2d8e0966317d.png))

1.  ## Current behaviour
     The css assets were not found.

!<span class="error">[image]</span>([https://user-images.githubusercontent.com/79997705/202271748-6c7e524f-b643-45cf-8a67-5ce3b54899ce.png](https://user-images.githubusercontent.com/79997705/202271748-6c7e524f-b643-45cf-8a67-5ce3b54899ce.png))

1.  ## :computer: Desktop:

***OS***: Pop!_OS 22.04 LTS x86_64 
 ***Kernel***: 6.0.6-76060006-generic 
 ***CPU***: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8) @ 2.100GHz 
 ***GPU***: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
 ***Memory***: 17866MiB 

****What are the impacted versions?**** `3.19.2`

1.  ## :rocket: Workaround

Expose the port of the Web UI container intead of use nginx to access it. First you need to add the ***"ports"*** prop at webui service in docker-compose.yml.
 ~~~yml
 webui:
 image: graviteeio/am-management-ui:$

 {GIO_AM_VERSION} 

 container_name: gio_am_webui
 restart: always
 ports:

*   8080:8080
     depends_on:
*   management
     environment:
*   MGMT_API_URL=[http://localhost:$](http://localhost:$) {NGINX_PORT}/am
     - MGMT_UI_URL=[http://localhost:$](http://localhost:$){NGINX_PORT}

/am/ui
 volumes:

*   ./logs/am-webui:/var/log/httpd
     ~~~
     Then you need to run ***docker compose up*** again and finally open web ui in **[http://localhost:8080**](http://localhost:8080**) instead of **[http://localhost:80/am/ui**](http://localhost:80/am/ui**).

**Comment by leleueri** [comment]
Thanks for highlighting this issue.
We reproduced it and we will work to fix it as soon as possible.

**Comment by remisultan** [comment]
This was fixed apparently
On latest 3.19 and above

<img width="1564" alt="image" src="https://github.com/gravitee-io/issues/assets/8531515/3b3d4e32-f50e-49cc-854b-5e2ce44b71cb">
