### ISSUE TITLE
[AM] - Bot detection possibly has a false alarm

### ISSUE THREAD

**Issue by NathanFirmo** [gravitee-io/issues#8657]
## :collision: Describe the bug
the bot detection, added in [this PR](https://github.com/gravitee-io/gravitee-access-management/pull/1133) is possibly having a false alarm.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1\. Follow docs and create an bot detection plugin as [described here](https://docs.gravitee.io/am/current/am_userguide_bot_detection_plugins.html).
2\. Enable the bot detection following [this docs](https://docs.gravitee.io/am/current/am_userguide_bot_detection.html).
3\. Go to login page
4\. See error

![image](https://user-images.githubusercontent.com/79997705/202562323-7e003d04-83a8-4c94-a8d0-55b50d84ec54.png)

## :rainbow: Expected behaviour
It should deny only bots login tries.

## Current behaviour
It deny all login tries.

## :movie_camera: Useful information
This is my bot detection config.

![image](https://user-images.githubusercontent.com/79997705/202562666-1cc0caa1-9377-4995-9d0e-9d541925caa9.png)

localhost was added as allowed domain.

![image](https://user-images.githubusercontent.com/79997705/202715097-6ac720e5-10b8-452e-a477-7a3253af4b51.png)

When I call google reCaptcha API directly, I receive data correctly, and you can see that I have a high score, that shoudn't be denied.

![image](https://user-images.githubusercontent.com/79997705/202562955-10931b74-70ba-44eb-835b-452b41eec55b.png)

Nevertheless, in the logs we see this message:

![image](https://user-images.githubusercontent.com/79997705/202563929-f522003b-7b17-4459-861b-657967fab012.png)

## :computer: Desktop:

**OS**: Pop!_OS 22.04 LTS x86_64 
**Kernel**: 6.0.6-76060006-generic 
**CPU**: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8) @ 2.100GHz 
**GPU**: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
**Memory**: 17866MiB                                  

***What are the impacted versions?*** `3.19.2`

**Comment by leleueri** [comment]
AM 3.19.4 contains this fix
