### ISSUE TITLE
No confirmation message after a subscription to an API on the portal

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#8660]
1.  ## <g-emoji class="g-emoji" alias="boom" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4a5.png">
     💥 
     </g-emoji> Describe the bug After subscribing to ann API, I can't see anymore the message on the last step confirming my subscription.
2.  ## <g-emoji class="g-emoji" alias="sunrise_over_mountains" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f304.png">
     🌄 
     </g-emoji> To Reproduce Steps to reproduce the behaviour: 1\. Go to the developer portal 2\. Select an API with a non-keyless plan at least 3\. Subscribe to it 4\. See the last step empty

**Comment by mouligno** [comment]
Content is here but we got an issue with display 
![image](https://user-images.githubusercontent.com/3227037/203079278-e11d223a-3d89-42d4-866f-b1eb18063db3.png)

**Comment by gaetanmaisse** [comment]
Closing as it's fixed in the latest versions of APIM.
