### ISSUE TITLE
[APIM][JDBC] Flow condition field is limited to 256 chars (varchar 256)

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#8671]
<ol> 
 <li>## :collision: Describe the bug<br> The flow condition field is limited to 256 chars, making impossible to import apis from old version for example 3.10.x in to 3.18.12 </li> 
 <li>## :sunrise_over_mountains: To Reproduce<br> Steps to reproduce the behaviour:<br> 1\. Create simple API in environment APIM 3.10.x<br> 2\. In the designer put a flow condition that is longer than 256 characters, save and export the api.<br> 3\. Create APIM environment 3.18.12<br> 4\. Try import the api. </li> 
 <li>## :rainbow: Expected behaviour<br> Api should be imported in the 3.18.x without issue. 
  <ol> 
   <li>Current behaviour<br> The api can not be imported. Gives error: </li> 
  </ol> </li> 
</ol> 
<p>Sorry, we can't seem to parse the definition<br> An error occurs while save flows</p> 
<p>And Stacktrace:</p> 
<p>```<br> 15:44:14.097 <span class="error">[gravitee-listener-58]</span> ERROR i.g.r.j.m.JdbcAbstractCrudRepository - Failed to create flows item:<br> org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; ERROR: value too long for type character varying(256); nested exception is org.postgresql.util.PSQLException: ERROR: value too long for type character varying(256)<br> Caused by: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(256)<br> 15:44:14.101 <span class="error">[gravitee-listener-58]</span> ERROR i.g.r.a.s.i.c.flow.FlowServiceImpl - An error occurs while save flows<br> io.gravitee.repository.exceptions.TechnicalException: io.gravitee.repository.exceptions.TechnicalException: Failed to create flows item.<br> Caused by: org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; ERROR: value too long for type character varying(256); nested exception is org.postgresql.util.PSQLException: ERROR: value too long for type character varying(256)<br> Caused by: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(256)<br> ```</p> 
<ol> 
 <li>## :computer: Desktop:</li> 
</ol> 
<p>**<b>Please complete the following information:</b>**</p> 
<ul> 
 <li>Environment: <span class="error">[3.18.8; 3.18.12; 3.19.3]</span></li> 
 <li>OS: <span class="error">[Docker]</span></li> 
</ul>

**Comment by gaetanmaisse** [comment]
@kirestoj01  Looks the same as https://github.com/gravitee-io/issues/issues/8823 no?

**Comment by kirestoj01** [comment]
@gaetanmaisse seems the upgrader is failing due to the same issue, only in my case is when we try import api, and the other one is when the upgrader is upgrading the api, but yes same problem i think
