### ISSUE TITLE
Portal UI - Issue with categories layout when the card overhangs the edge

### ISSUE THREAD

**Issue by mireilleroche** [gravitee-io/issues#8678]
# Describe the bug

An overflow is not handled when we are on a small window and not all categories cards can be displayed.

# To Reproduce

Steps to reproduce the behaviour:

1.  Go to 'Portal UI web application'
2.  Click on 'Catalog'
3.  Reduce the window to have a card half displayed.
4.  Scroll right horizontally
5.  See bad display: [https://user-images.githubusercontent.com/32935203/203823973-d5e425cf-2c9d-407c-bf44-849140f4b5e7.png](https://user-images.githubusercontent.com/32935203/203823973-d5e425cf-2c9d-407c-bf44-849140f4b5e7.png)

# Expected behaviour

Have a responsive behavior on the categories cards area

# Current behaviour

Before scrolling: [https://user-images.githubusercontent.com/32935203/203824251-243da7a3-d2ae-4545-8cd3-820d2a8016c7.png](https://user-images.githubusercontent.com/32935203/203824251-243da7a3-d2ae-4545-8cd3-820d2a8016c7.png)

**Comment by gaetanmaisse** [comment]
@mireilleroche regarding your comment:
> Have a responsive behavior on the categories cards area

What do you have in mind more precisely? 
 - Move to a two-column layout? 
 - Resize all the category cards
 - Have a scroll on the category cards themselves and not the whole screen

**Comment by mireilleroche** [comment]
Hello @gaetanmaisse ,

we thought of a display (flex) where the cards that do not contain in the current line go to the next line while managing the space available to the window as well as possible.

Thanks
