### ISSUE TITLE
 APIM Websocket connection lost

### ISSUE THREAD

**Issue by gianx89** [gravitee-io/issues#8689]
<ol> 
 <li>## :collision: Describe the bug<br> My WebScoket connections (STOMP) passing through Gravitee APIM are established and immediately dropped.</li> 
 <li>## :sunrise_over_mountains: To Reproduce<br> I’m running Gravitee APIM 3.18 on Docker. </li> 
</ol> 
<p>This is my setup:</p> 
<ul> 
 <li>*<b>Gravitee APIM 3.18</b>*</li> 
 <li>*<b>Nginx</b>* as reverse proxy in front of Gravitee</li> 
 <li>*<b>Consul</b>* 1.13.2</li> 
 <li>*<b>RabbitMQ</b>*</li> 
 <li>*<b>Gravitee Consul Service Discovery plugin</b>* enabled on my API</li> 
 <li>Gravitee APIM Gateway started with: '*<b>gravitee_http_websocket_enabled=true</b><b>' and '</b><b>gravitee_http_websocket_subProtocols=v10.stomp, v11.stomp, v12.stomp</b>*'</li> 
 <li>My backend is a *<b>Spring Boot 2.7.5</b>* application registered through Consul and correctly discovered by Gravitee APIM.</li> 
 <li>My backend application has *<b>WebSocket, STOMP and REST</b>* functionalities enabled.</li> 
 <li>My backend application uses RabbitMQ as WebSocket and STOMP broker.</li> 
 <li>My backend application has two WebSocket endpoints: one for *<b>SockJS</b>* and one for "pure" WebSockets.</li> 
 <li>On the same Spring Boot application, I serve both REST and WebSocket services.</li> 
 <li>Rest services are correctly consumed though Gravitee APIM and Consul.</li> 
 <li>The Spring Boot Application sends STOMP messages to Front End Javascript or Angular clients connecting through WebSockets or SockJS connections and using the STOMP protocol.</li> 
</ul> 
<p>*<b>All works fine if I bypass Gravitee APIM.</b>*</p> 
<p>If an app connects to my WebSockets through Gravitee in order to receive STOMP messages:</p> 
<ul> 
 <li>Using SockJS: all is fine.</li> 
 <li>*<b>Using WebSockets: it can establish a connection but it gets immediately dropped.</b>*</li> 
</ul> 
<p>```<br> Opening Web Socket...<br> Web Socket Opened...<br> &gt;&gt;&gt; CONNECT<br> accept-version:1.1,1.0<br> heart-beat:10000,10000<br> Whoops! Lost connection to wss://host.docker.internal/apim/xxx/yyy/notifications/ws<br> ```</p> 
<p>My *<b>Nginx configuration</b>* is:</p> 
<p>```<br> location /apim/ </p> { proxy_pass https://apim_gateway/; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Host $server_name; proxy_set_header X-Forwarded-Prefix /apim; proxy_set_header X-Forwarded-Proto $scheme; proxy_read_timeout 1800000s; proxy_connect_timeout 1800000s; proxy_send_timeout 1800000s; send_timeout 1800000s; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection "Upgrade"; proxy_http_version 1.1; } 
<p>```<br> I tried to:</p> 
<ul> 
 <li>Exclude Nginx</li> 
 <li>Exclude Consul</li> 
</ul> 
<p>It continues to drop WebSocket connections. When I bypass Gravitee APIM all is fine. So I wrote a NodeJS application that discovers my service through Consul and connects to my Websockets bypassing Gravitee. I made a container and tested it: all is fine, connection isn't dropped.</p> 
<p>So it seems that the problem is Gravitee APIM. Am I missing some configuration? Am I misunderstanding something? Is it a bug?</p> 
<ol> 
 <li>## :rainbow: Expected behaviour<br> I want to establish and maintain "pure" WebSocket connections through Gravitee APIM in order to receive STOMP messages.</li> 
 <li>## Current behaviour<br> WebSocket connections are established and immediately dropped. SockJS works fine.</li> 
 <li>## :computer: Desktop:</li> 
</ol> 
<p>**<b>Please complete the following information:</b>**</p> 
<ul> 
 <li>Environment: 3.18</li> 
 <li>OS: Ubuntu 22.04</li> 
 <li>Docker</li> 
</ul>

**Comment by gianx89** [comment]
@jhaeyaert any updates?

**Comment by phiz71** [comment]
Hello @gianx89, the fix has been merged and will be available in the next 3.18.x maintenance release. This version should be released end of this week or beginning of next week.

**Comment by gianx89** [comment]
I'll try it as soon as possible
