### ISSUE TITLE
[management] Management API does not send event to Alert engine properly when gateway is down

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#8699]
# ## :collision: Describe the bug
 When the gateway is down, management api is not sending event to AE until the gateway starts running again. 
# ## :sunrise_over_mountains: To Reproduce
 Steps to reproduce the behaviour:
 1\. Create alert with "Alert on the health status of the node" rule.
 2\. Add filter: Status > String > Not equals to > Healthy
 3\. Remove/Stop gateway
 4\. See no alert triggered until the gateway is started again. 
# ## :rainbow: Expected behaviour
 When GW is down, the management api should send event to AE to fire an alert. 
# ## Current behaviour
 When GW is down, the management api is not sending event to AE to fire an alert. Instead is sending event to AE when the GW starts working again. 
# ## :movie_camera: Useful information
 Screenshot, video, logs, other supporting material 
# ## :computer: Desktop: 

***Please complete the following information:***

* Environment: [3.18.12; 3.19.4]
* OS: [Docker]

**Comment by a-cordier** [comment]
Note: I tried to investigate on the issue but unfortunately the AE image we have in our quick setup does not run on arm architectures.

**Comment by aelamrani** [comment]
@a-cordier can we use the AE deployed on our dev env for the time being?
