### ISSUE TITLE
[policy] Dynamic routing policy

### ISSUE THREAD

**Issue by AnselmeDewavrin** [gravitee-io/issues#87]
Dear all,

An idea : it be great to have a dynamic routing policy based on this scheme: 
regex1 match -> url1 with dynamic content
regex2 match -> url2 with dynamic content
...
With dynamic content made of properties, dsl, etc.
Thanks,
Anselme

**Comment by brasseld** [comment]
Hi @AnselmeDewavrin,

So the idea would be to create a new policy for dynamic-routing.
This policy expects some rules in its configuration and a rule should be:
If Regex 1 match then redirect to an URL 1
If Regex 2 match then redirect to an URL 2

Defined URLs must themselves be dynamic by using Expression Language and Regex capture / replacement.

**Comment by brasseld** [comment]
Hi @AnselmeDewavrin,

There is now a new policy named "Dynamic Routing" which allows this kind of dynamic endpoint addressing.

https://github.com/gravitee-io/gravitee-policy-dynamic-routing

This policy will be available as part of release 0.14.2
