### ISSUE TITLE
Health Check doesn't support EL On Endpoint

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#8700]
# Describe the bug

When using expression language as an endpoint, the health check is not working

# To Reproduce

Steps to reproduce the behaviour: To reproduce:

1.  Create a simple API
2.  Update the proxy endpoint to use an EL, for instance: {#properties['backend']}
3.  Define a property backend (via the policy studio) to a valid URL: [https://api.gravitee.io/echo](https://api.gravitee.io/echo)
4.  Configure the healthcheck
5.  Deploy the API

# Expected behaviour

if el is used for the endpoint, expecting to work as if hardcoded

# Current behaviour

if el is used, healthcheck is not working

# Useful information

!<span class="error">[image]</span>([https://user-images.githubusercontent.com/89140082/205651929-d538a7e7-df98-4886-9b7b-6f9df78bf16b.png](https://user-images.githubusercontent.com/89140082/205651929-d538a7e7-df98-4886-9b7b-6f9df78bf16b.png))

Tested in:

*   Environment: <span class="error">[e.g. 3.18.13]</span>

fixed previously it seems: [https://github.com/gravitee-io/issues/issues/8639](https://github.com/gravitee-io/issues/issues/8639)

**Comment by ppgravitee** [comment]
@zveljanoski @apoddany this is the expected behaviour not a bug, see with @mouligno for further information

**Comment by gaetanmaisse** [comment]
Reopening as a fix was done on the Endpoints themselves to handle EL properly, but HC is still ko.
