### ISSUE TITLE
Redoc documentation is not working, and keep loading

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#8703]
## :collision: Describe the bug
Redoc documentation is not working, and keep loading

Only swagger can be displayed

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1\. Import docs
2\. Go to api, pages
3\. Upload the documentation
4\. Go to portal, do api's documentation
5\. If configured as redoc it keeps loading on the portal and nothing shown
![image](https://user-images.githubusercontent.com/89140082/205882426-c30361cc-5288-4b13-befe-c8e3d829f81f.png)
6\. If configured as swagger in the console it is shown properly:
![image](https://user-images.githubusercontent.com/89140082/205882632-c2c65f06-1495-4435-96ce-44247ae628a6.png)

## :rainbow: Expected behaviour
expected redoc to work as well

## Current behaviour
only swagger is working 

Tested in 3.18.13, 3.18.6, 3.20.0

zd5391, 5807

**Comment by ppgravitee** [comment]
We don't support Redoc, see with @mouligno for further information

**Comment by phiz71** [comment]
Actually we do support Redoc in the portal

**Comment by phiz71** [comment]
@zveljanoski is it the same for all openapi/swagger files ? Or just for a specific one ?
