### ISSUE TITLE
Security : Allow Helm chart template to set api.properties.encryption.secret

### ISSUE THREAD

**Issue by mnarvart** [gravitee-io/issues#8730]
1.  ## 💥 Describe the bug

[-describe-the-bug](#-describe-the-bug)

[-describe-the-bug](#-describe-the-bug)

[-describe-the-bug](#-describe-the-bug)

[-describe-the-bug](#-describe-the-bug)

Using gravitee installation using helm charts, on gravitee api startup there is the following security warning :

##############################################################

SECURITY WARNING ##############################################################

You still use the default secret. This known secret can be used to access protected information. Please customize the ‘api.properties.encryption.secret’ parameter

##############################################################

Gravitee helm chart does not allow to set api.properties.encryption.secret with values. A workaround is to use extraEnv to set the property as proposed on ticket [https://community.gravitee.io/t/helm-chart-installation-how-to-set-api-properties-encryption-secret/1379/1](https://community.gravitee.io/t/helm-chart-installation-how-to-set-api-properties-encryption-secret/1379/1) but it would be better to create a explicit property on helm chart to fix the securty warning.

1.  ## 🔗 Dependencies

[-dependencies](#-dependencies)

[-dependencies](#-dependencies)

[-dependencies](#-dependencies)

[-dependencies](#-dependencies)

([https://community.gravitee.io/t/helm-chart-installation-how-to-set-api-properties-encryption-secret/1379/1](https://community.gravitee.io/t/helm-chart-installation-how-to-set-api-properties-encryption-secret/1379/1))

**Comment by gaetanmaisse** [comment]
I've got some exciting news to share - we've finally squashed that pesky bug that's been bugging you! 🎉 
The fix is included in the latest version of the APIM Helm Chart (v3.1.62), so you can finally take a breather and let your API do the heavy lifting.

**Comment by fptiangco** [comment]
Hi, it seems this may still be present in the apim-4.2.0 helm chart?

**Comment by phiz71** [comment]
Hello @fptiangco.
According to these lines:
- https://github.com/gravitee-io/gravitee-api-management/blob/4.2.x/helm/templates/api/api-configmap.yaml#L523-L526
- https://github.com/gravitee-io/gravitee-api-management/blob/4.2.x/helm/tests/api/configmap_api_properties_test.yaml

It is possible to configure the encryption key like this:
```yaml
api:
  api:
    properties:
      encryption:
        secret: my-secret
```

Could you have a try?
