### ISSUE TITLE
Bug with Elasticsearch 8.5.3: Impossible to perform CountQuery

### ISSUE THREAD

**Issue by manhkhoa168** [gravitee-io/issues#8732]
Hello, When I use Docker image combination between Management API (graviteeio/apim-management-api:latest) with Elasticsearch 8.5.3 (docker.elastic.co/elasticsearch/elasticsearch:8.5.3), the error "Unable to count" happened

gio-apim-management-api | 10:11:41.212 <span class="error">[vert.x-eventloop-thread-1]</span> ERROR i.g.e.client.http.HttpClient - Unable to count: url<span class="error">[/gravitee-request-2022.12.15/_doc/_count?ignore_unavailable=true]</span> status<span class="error">[400]</span> query[{ gio-apim-management-api | "query": { gio-apim-management-api | "bool":

 { gio-apim-management-api | "filter": [ gio-apim-management-api | ] gio-apim-management-api | } 

gio-apim-management-api | } gio-apim-management-api | }] response[{"error":{"root_cause":[

 {"type":"illegal_argument_exception","reason":"request [/gravitee-request-2022.12.15/_doc/_count] contains unrecognized parameter: [ignore_unavailable]"} 

],"type":"illegal_argument_exception","reason":"request <span class="error">[/gravitee-request-2022.12.15/_doc/_count]</span> contains unrecognized parameter: <span class="error">[ignore_unavailable]</span>"},"status":400}] gio-apim-management-api | 10:11:41.214 <span class="error">[vert.x-worker-thread-2]</span> ERROR i.g.r.e.a.query.CountQueryCommand - Impossible to perform CountQuery gio-apim-management-api | io.gravitee.elasticsearch.exception.ElasticsearchException: Unable to count gio-apim-management-api | at io.gravitee.elasticsearch.client.http.HttpClient.lambda$count$15(HttpClient.java:392) gio-apim-management-api | at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57) gio-apim-management-api | at io.vertx.reactivex.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:49) gio-apim-management-api | at io.vertx.reactivex.ext.web.client.HttpRequest$4.handle(HttpRequest.java:474) gio-apim-management-api | at io.vertx.reactivex.ext.web.client.HttpRequest$4.handle(HttpRequest.java:471) gio-apim-management-api | at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:400) gio-apim-management-api | at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:387) gio-apim-management-api | at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:365) gio-apim-management-api | at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:332) gio-apim-management-api | at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:294) gio-apim-management-api | at io.vertx.ext.web.client.impl.HttpContext.lambda$null$8(HttpContext.java:550) gio-apim-management-api | at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) gio-apim-management-api | at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63) gio-apim-management-api | at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38) gio-apim-management-api | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) gio-apim-management-api | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) gio-apim-management-api | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) gio-apim-management-api | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) gio-apim-management-api | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) gio-apim-management-api | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) gio-apim-management-api | at java.base/java.lang.Thread.run(Unknown Source)

There are two differences that I changed in the configuration

*   Change Elasticsearch version from 7.7.0 to 8.5.3
*   Comment config line "xpack.monitoring.enabled=false" as it is no longer available as of version 7.8.0 ([https://www.elastic.co/guide/en/elasticsearch/reference/current/monitoring-settings.html](https://www.elastic.co/guide/en/elasticsearch/reference/current/monitoring-settings.html))

I want to know the cause and how to fix it so that I can use the latest version of Elasticsearch. Thanks!

**Comment by mouligno** [comment]
hi @manhkhoa168 

We currently not support ES8 but it is under our radar for future versions.

**Comment by manhkhoa168** [comment]
> hi @manhkhoa168
> 
> We currently not support ES8 but it is under our radar for future versions.

so what is the latest version of Elasticsearch that I can use?

**Comment by mouligno** [comment]
We do support ES5/6/7 right now.

**Comment by kuhnroyal** [comment]
There have been some recent changes to the reporter. Is ES 8 supported now?
