### ISSUE TITLE
MongoDB error: Authentication failed

### ISSUE THREAD

**Issue by manhkhoa168** [gravitee-io/issues#8734]
Hello, When I use MongoDB docker (mongo:6.0.3) and config environments

*   MONGO_INITDB_ROOT_USERNAME=root
*   MONGO_INITDB_ROOT_PASSWORD=root

then I config environtment of management api docker (graviteeio/apim-management-api:latest)

*   gravitee_management_mongodb_uri=mongodb://root:root@mongodb:27017/gravitee-apim?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000

the error "Authentication failed" happened

 gio-apim-management-api | Caused by: com.mongodb.MongoCommandException: Command failed with error 18 (AuthenticationFailed): 'Authentication failed.' on server mongodb:27017\. The full response is 

 {"ok": 0.0, "errmsg": "Authentication failed.", "code": 18, "codeName": "AuthenticationFailed"} 

 gio-apim-management-api | at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:198)
 gio-apim-management-api | at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:413)
 gio-apim-management-api | at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:337)
 gio-apim-management-api | at com.mongodb.internal.connection.CommandHelper.sendAndReceive(CommandHelper.java:101)
 gio-apim-management-api | at com.mongodb.internal.connection.CommandHelper.executeCommand(CommandHelper.java:45)
 gio-apim-management-api | at com.mongodb.internal.connection.SaslAuthenticator.sendSaslStart(SaslAuthenticator.java:230)
 gio-apim-management-api | at com.mongodb.internal.connection.SaslAuthenticator.getNextSaslResponse(SaslAuthenticator.java:137)
 gio-apim-management-api | ... 59 more
 gio-apim-management-api | Exception in thread "RxCachedThreadScheduler-1" io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: [https://github.com/ReactiveX/RxJava/wiki/Error-Handling](https://github.com/ReactiveX/RxJava/wiki/Error-Handling)([https://github.com/ReactiveX/RxJava/wiki/Error-Handling](https://github.com/ReactiveX/RxJava/wiki/Error-Handling)) | org.springframework.data.mongodb.UncategorizedMongoDbException: Exception authenticating MongoCredential

 {mechanism=SCRAM-SHA-1, userName='root', source='gravitee-apim', password=<hidden>, mechanismProperties=<hidden>}; nested exception is com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='root', source='gravitee-apim', password=<hidden>, mechanismProperties=<hidden>} 

 gio-apim-management-api | at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
 gio-apim-management-api | at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
 gio-apim-management-api | at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
 gio-apim-management-api | at io.reactivex.internal.operators.single.SingleDoFinally$DoFinallyObserver.onError(SingleDoFinally.java:79)
 gio-apim-management-api | at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onError(SingleDoOnSuccess.java:65)
 gio-apim-management-api | at io.reactivex.internal.operators.maybe.MaybeSwitchIfEmptySingle$SwitchIfEmptyMaybeObserver.onError(MaybeSwitchIfEmptySingle.java:87)
 gio-apim-management-api | at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver.onError(MaybeFlatten.java:102)
 gio-apim-management-api | at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeOnMaybeObserver.onError(MaybeSubscribeOn.java:96)
 gio-apim-management-api | at io.reactivex.internal.operators.maybe.MaybeCreate$Emitter.tryOnError(MaybeCreate.java:100)
 gio-apim-management-api | at io.reactivex.internal.operators.maybe.MaybeCreate$Emitter.onError(MaybeCreate.java:86)
 gio-apim-management-api | at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:48)
 gio-apim-management-api | at io.reactivex.Maybe.subscribe(Maybe.java:4290)
 gio-apim-management-api | at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
 gio-apim-management-api | at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
 gio-apim-management-api | at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
 gio-apim-management-api | at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
 gio-apim-management-api | at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
 gio-apim-management-api | at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
 gio-apim-management-api | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 gio-apim-management-api | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 gio-apim-management-api | at java.base/java.lang.Thread.run(Unknown Source)
 gio-apim-management-api | Caused by: org.springframework.data.mongodb.UncategorizedMongoDbException: Exception authenticating MongoCredential

 {mechanism=SCRAM-SHA-1, userName='root', source='gravitee-apim', password=<hidden>, mechanismProperties=<hidden>}; nested exception is com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='root', source='gravitee-apim', password=<hidden>, mechanismProperties=<hidden>} 

 gio-apim-management-api | at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:140)
 gio-apim-management-api | at org.springframework.data.mongodb.core.MongoTemplate.potentiallyConvertRuntimeException(MongoTemplate.java:3044)
 gio-apim-management-api | at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:2980)
 gio-apim-management-api | at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:2692)
 gio-apim-management-api | at org.springframework.data.mongodb.core.ExecutableFindOperationSupport$ExecutableFindSupport.doFind(ExecutableFindOperationSupport.java:220)
 gio-apim-management-api | at org.springframework.data.mongodb.core.ExecutableFindOperationSupport$ExecutableFindSupport.oneValue(ExecutableFindOperationSupport.java:132)
 gio-apim-management-api | at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.lambda$getExecution$6(AbstractMongoQuery.java:188)
 gio-apim-management-api | at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.doExecute(AbstractMongoQuery.java:152)
 gio-apim-management-api | at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.execute(AbstractMongoQuery.java:127)
 gio-apim-management-api | at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137)
 gio-apim-management-api | at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121)
 gio-apim-management-api | at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:160)
 gio-apim-management-api | at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:139)
 gio-apim-management-api | at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
 gio-apim-management-api | at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:81)
 gio-apim-management-api | at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
 gio-apim-management-api | at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
 gio-apim-management-api | at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
 gio-apim-management-api | at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
 gio-apim-management-api | at jdk.proxy5/jdk.proxy5.$Proxy230.findByNodeIdAndType(Unknown Source)
 gio-apim-management-api | at io.gravitee.repository.mongodb.management.MongoNodeMonitoringRepository.lambda$findByNodeIdAndType$0(MongoNodeMonitoringRepository.java:49)
 gio-apim-management-api | at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
 gio-apim-management-api | ... 10 more
 gio-apim-management-api | Caused by: com.mongodb.MongoSecurityException: Exception authenticating MongoCredential

 {mechanism=SCRAM-SHA-1, userName='root', source='gravitee-apim', password=<hidden>, mechanismProperties=<hidden>} 

 gio-apim-management-api | at com.mongodb.internal.connection.SaslAuthenticator.wrapException(SaslAuthenticator.java:276)
 gio-apim-management-api | at com.mongodb.internal.connection.SaslAuthenticator.getNextSaslResponse(SaslAuthenticator.java:139)
 gio-apim-management-api | at com.mongodb.internal.connection.SaslAuthenticator.access$100(SaslAuthenticator.java:49)
 gio-apim-management-api | at com.mongodb.internal.connection.SaslAuthenticator$1.run(SaslAuthenticator.java:65)
 gio-apim-management-api | at com.mongodb.internal.connection.SaslAuthenticator$1.run(SaslAuthenticator.java:59)
 gio-apim-management-api | at com.mongodb.internal.connection.SaslAuthenticator.doAsSubject(SaslAuthenticator.java:283)
 gio-apim-management-api | at com.mongodb.internal.connection.SaslAuthenticator.authenticate(SaslAuthenticator.java:59)
 gio-apim-management-api | at com.mongodb.internal.connection.DefaultAuthenticator.authenticate(DefaultAuthenticator.java:57)
 gio-apim-management-api | at com.mongodb.internal.connection.InternalStreamConnectionInitializer.authenticate(InternalStreamConnectionInitializer.java:207)
 gio-apim-management-api | at com.mongodb.internal.connection.InternalStreamConnectionInitializer.finishHandshake(InternalStreamConnectionInitializer.java:81)
 gio-apim-management-api | at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:185)
 gio-apim-management-api | at com.mongodb.internal.connection.UsageTrackingInternalConnection.open(UsageTrackingInternalConnection.java:54)
 gio-apim-management-api | at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.open(DefaultConnectionPool.java:535)
 gio-apim-management-api | at com.mongodb.internal.connection.DefaultConnectionPool$OpenConcurrencyLimiter.openWithConcurrencyLimit(DefaultConnectionPool.java:911)
 gio-apim-management-api | at com.mongodb.internal.connection.DefaultConnectionPool$OpenConcurrencyLimiter.openOrGetAvailable(DefaultConnectionPool.java:852)
 gio-apim-management-api | at com.mongodb.internal.connection.DefaultConnectionPool.get(DefaultConnectionPool.java:178)
 gio-apim-management-api | at com.mongodb.internal.connection.DefaultConnectionPool.get(DefaultConnectionPool.java:167)
 gio-apim-management-api | at com.mongodb.internal.connection.DefaultServer.getConnection(DefaultServer.java:103)
 gio-apim-management-api | at com.mongodb.internal.binding.ClusterBinding$ClusterBindingConnectionSource.getConnection(ClusterBinding.java:175)
 gio-apim-management-api | at com.mongodb.client.internal.ClientSessionBinding$SessionBindingConnectionSource.getConnection(ClientSessionBinding.java:192)
 gio-apim-management-api | at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:592)
 gio-apim-management-api | at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$3(OperationHelper.java:574)
 gio-apim-management-api | at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:600)
 gio-apim-management-api | at com.mongodb.internal.operation.OperationHelper.withSourceAndConnection(OperationHelper.java:573)
 gio-apim-management-api | at com.mongodb.internal.operation.FindOperation.lambda$execute$2(FindOperation.java:690)
 gio-apim-management-api | at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:65)
 gio-apim-management-api | at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:722)
 gio-apim-management-api | at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:86)
 gio-apim-management-api | at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:191)
 gio-apim-management-api | at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:135)
 gio-apim-management-api | at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:92)
 gio-apim-management-api | at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:2968)
 gio-apim-management-api | ... 29 more

I want to know the cause and how to fix it. Thanks!

**Comment by mouligno** [comment]
Hi @manhkhoa168 

Please use MongoDB 3/4/5 instead of 6.

I'll keep the ticket open as a feature for further support ;)
