### ISSUE TITLE
Invalid interpolation format

### ISSUE THREAD

**Issue by manhkhoa168** [gravitee-io/issues#8736]
Hello, while I use graviteeio/apim-management-api:latest and config environment **gravitee_security_providers_0_users_1_password=this_is_password** to change password of **admin** user, I see a error

ERROR: Invalid interpolation format for "environment" option in service "management-api"

I also use **gravitee.security.providers<span class="error">[0]</span>.users<span class="error">[1]</span>.password=this_is_password** instead, but same error appear. I want to know the cause and how to fix it. Thanks!

**Comment by jhaeyaert** [comment]
Does `this_is_password` is properly bcrypt encoded ?

**Comment by manhkhoa168** [comment]
> Does `this_is_password` is properly bcrypt encoded ?

yes i encrypted the password and set **this_is_password** to $2b$12$Xt5zt7.NbS...

**Comment by manhkhoa168** [comment]
> Does `this_is_password` is properly bcrypt encoded ?

Hello, can you suggest me any other problem i am facing or how to solve it?

**Comment by phiz71** [comment]
Hello @manhkhoa168, I think you have to escape the `$` character in your docker-compose.
So `$2b$12$Xt5zt7...` should be `$$2b$$12$$Xt5zt7...`

**Comment by gaetanmaisse** [comment]
@manhkhoa168 did you try to escape `$` as suggested by @phiz71 ?

**Comment by gaetanmaisse** [comment]
I'm closing the issue for now, feel free to reopen it if you're still facing the problem
