### ISSUE TITLE
Ratelimit with Redis

### ISSUE THREAD

**Issue by manhkhoa168** [gravitee-io/issues#8745]
Hello,
I have a question about rate limit using Redis instead of MongoDB.
When I research I see the Redis repository plugin moved to https://github.com/gravitee-io/gravitee-api-management/tree/master/gravitee-apim-repository/gravitee-apim-repository-redis
But I'm not found gravitee-repository-redis-3.1.0-SNAPSHOT.zip or anyone in https://oss.sonatype.org/content/repositories/snapshots to download.
I want to question for the rate limit by Redis is available currently?

**Comment by mouligno** [comment]
Hey @manhkhoa168 

You can find it there : https://download.gravitee.io/#graviteeio-apim/plugins/repositories/gravitee-repository-redis/

**Comment by gaetanmaisse** [comment]
Closing the issue, feels free to reopen it if needed.
