### ISSUE TITLE
Image Rendering on the portal, different then from console

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#8749]
# Describe the bug 

When setting up an image for an API, it is shown in the console but not shown in the portal.

# To Reproduce 

Steps to reproduce the behaviour:

1.  Create a few APIs
2.  Add images to them
3.  Subscribe an application to the apps.
4.  Check them in the list on console !<span class="error">[image]</span>([https://user-images.githubusercontent.com/89140082/208634219-3be97512-1a8c-49fc-ae7c-def52085c309.png](https://user-images.githubusercontent.com/89140082/208634219-3be97512-1a8c-49fc-ae7c-def52085c309.png))
5.  Check them in the list, in the right nav on the portal !<span class="error">[image]</span>([https://user-images.githubusercontent.com/89140082/208634394-45db2ca3-81a0-4210-a851-c85691f742d2.png](https://user-images.githubusercontent.com/89140082/208634394-45db2ca3-81a0-4210-a851-c85691f742d2.png))

Tested in 3.18.9, 3.19.0

**Comment by mouligno** [comment]
More info : API subscribed to widget on portal application page doesn't use API's images. It is using real images on application subscriptions list.
