### ISSUE TITLE
[management] Migration tool for path based APIs is splitting all policies in different flows

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#8758]
## :collision: Describe the bug
When we use the migration tool for path based APIs to designer, instead of migrating whole flows with all policies, the tool is migrating the API to have a flow for each policy with only 1 policy in the flow.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Create path based API, add few policies per flow/path
2. Activate the migration tool
3. See how each policy has its own flow (splits also by path)

## :rainbow: Expected behaviour
When API is migrated, all policies in one flow should remain in one flow after migration

## Current behaviour
When API is migrated, each policy from the flows already present, is getting new flow with only that policy present inside.

## :computer: Desktop:

***Please complete the following information:***
 - Environment: [3.18.3]
 - OS: [Docker Install]

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by mouligno** [comment]
Normal behavior
