### ISSUE TITLE
Swagger Rendering Issue

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#8759]
## :collision: Describe the bug
When importing swagger for a documentation, seeing differences between the swagger from the file, and in the portal after importing.

The main difference is the boolean types are in ""

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1\. Upload the file from zd#5453
2\. Check as is before upload

![image](https://user-images.githubusercontent.com/89140082/209090670-2aeadde2-683d-438f-a2ad-ad6232f3e7fe.png)

3\. Check the data from the file in the console

![image](https://user-images.githubusercontent.com/89140082/209090731-9c7b4a26-1064-4688-9db9-dd520ab39c67.png)

4\. Check the dat in the portal

![image](https://user-images.githubusercontent.com/89140082/209090821-58cad141-adfa-4501-a0db-bffb89b27c7a.png)

## :rainbow: Expected behaviour
Expected to be no differences between the swagger in the portal, console and the file that is uploaded

## Current behaviour
In the portal suspicious behavior hence the boolean types in ""

Tested in 3.18.9]

**Comment by phiz71** [comment]
Duplicates #7099
