### ISSUE TITLE
[APIM] APIs table, version column 

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#8772]
<ol> 
 <li>## :collision: Describe the bug<br> In the <em>version</em> column, I would expect to see the API's version, and not the "Gravitee API's version". </li> 
</ol> 
<p><span class="image-wrap" style=""><img src="https://user-images.githubusercontent.com/133094/209940382-9996a51f-2f1b-470c-8144-6dd178820f19.png"></span></p> 
<p>We should probably consider to rename this column ?</p>

**Comment by gaetanmaisse** [comment]
@mouligno @audrey-tlm any thoughts about a new name for this column?

**Comment by audrey-tlm** [comment]
We could go with "Gravitee version" instead
