### ISSUE TITLE
[APIM- Migrate to Design Studio] Policies lost when upgrading older version Path Based API to Design Studio in new versions.

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#8789]
1.  1.  :collision: Describe the bug
         When we have an Path Based API from older version like 3.5.X and upgrade the API along with APIM to 3.18.14 and Migrate the API to Design Studio policies on plan level are lost.

Pre Migration:

!<span class="error">[image]</span>([https://user-images.githubusercontent.com/57534152/210241318-1e0e7704-685c-4302-a4cb-dca53a8b41b1.png](https://user-images.githubusercontent.com/57534152/210241318-1e0e7704-685c-4302-a4cb-dca53a8b41b1.png))

!<span class="error">[image]</span>([https://user-images.githubusercontent.com/57534152/210241335-9d174a7a-424a-4d81-86a0-81fb79f43e99.png](https://user-images.githubusercontent.com/57534152/210241335-9d174a7a-424a-4d81-86a0-81fb79f43e99.png))

Post Migration to Design Studio:

No policy:

!<span class="error">[image]</span>([https://user-images.githubusercontent.com/57534152/210241432-3a78f647-f319-4336-a05f-75e8f0863027.png](https://user-images.githubusercontent.com/57534152/210241432-3a78f647-f319-4336-a05f-75e8f0863027.png))

Issue happens with Assign Content Policy also so I do not think it is Policy related.

1.  1.  :sunrise_over_mountains: To Reproduce
         1\. Export zip and import the API as path based in 3.18.14
         2\. Before Migration to to plans and see the Policy from screen shots above.
         3\. After you have seen the policy does exist on plan level migrate the API to Design Studio
         4\. Go to Design and you will see there is no policy on the Plan level.

1.  1.  :rainbow: Expected behavior:
         No policies on plan level should get lost when we migrate.

1.  1.  :movie_camera: Useful information

<span class="error">[Test.zip]</span>([https://github.com/gravitee-io/issues/files/10332012/Test.zip](https://github.com/gravitee-io/issues/files/10332012/Test.zip))

1.  1.  :computer: Desktop:

****Please complete the following information:****

*   Environment: Docker-Desktop 3.18.14
*   OS: Windows 11
*   Browser: Google Chrome

1.  1.  :warning: Potential impacts

****What are the impacted versions?****

*   3.18.14

**Comment by phiz71** [comment]
Duplicates https://github.com/gravitee-io/issues/issues/8632
Which has been fixed in 3.18.18
https://docs.gravitee.io/apim/3.x/changelog-3.18.html#api_2
