### ISSUE TITLE
[management] API icons not displayed in the API list screen

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#8809]
<ol> 
 <li> 
  <ol> 
   <li>:collision: Describe the bug<br> When upgrading to 3.19.x the icons of APIs are lost.<br> Issue recreated in both MongoDB and JDBC environments. (JDBC Test was up to 3.19.6)</li> 
  </ol> </li> 
</ol> 
<ol> 
 <li> 
  <ol> 
   <li>:sunrise_over_mountains: To Reproduce<br> Steps to reproduce the behaviour:<br> 1\. Create environment with 2-3 simple APIs. <br> 2\. Add icons on the APIs.<br> 3\. Upgrade the environment to 3.19.4+<br> 4\. See missing icons.</li> 
  </ol> </li> 
</ol> 
<ol> 
 <li> 
  <ol> 
   <li>:rainbow: Expected behaviour<br> The icons should remain on the apis after upgrade.</li> 
  </ol> </li> 
</ol> 
<ol> 
 <li> 
  <ol> 
   <li>Current behaviour<br> The icons disappear from the apis.</li> 
  </ol> </li> 
</ol> 
<ol> 
 <li> 
  <ol> 
   <li>:movie_camera: Useful information<br> Screenshot, video, logs, other supporting material</li> 
  </ol> </li> 
</ol> 
<ol> 
 <li> 
  <ol> 
   <li>:computer: Desktop:</li> 
  </ol> </li> 
</ol> 
<p>**<b>Please complete the following information:</b>**</p> 
<ul class="alternate" type="square"> 
 <li>Environment: <span class="error">[3.19.x]</span></li> 
 <li>OS: <span class="error">[Docker Install]</span></li> 
</ul> 
<p>**<b>What are the impacted versions?</b>**<br> Impact is on both MongoDB and JDBC environments starting 3.19.0+</p>

**Comment by gaetanmaisse** [comment]
I think we need to backport https://github.com/gravitee-io/gravitee-api-management/pull/2671/commits/e0350a9e5cc3b16004739eb6a7d3f001271aef6a 
Can you confirm @ThibaudAV?
