### ISSUE TITLE
can't read /opt/graviteeio/apim/management-ui/constants.json: No such file or directory

### ISSUE THREAD

**Issue by EphraimXX** [gravitee-io/issues#8813]
## :collision: Describe the bug
 Hi, I'm trying to install Gravitee on an EC2 instance. I've followed the prerequisites for provisioning the machine and the security groups. But on running the command `curl -L https://bit.ly/install-apim-3x | sudo bash`, I get the  error `can't read /opt/graviteeio/apim/management-ui/constants.json: No such file or directory`, `sed: can't read /opt/graviteeio/apim/portal-ui/assets/config.json: No such file or directory`, and `Error: Package: graviteeio-apim-3x-3.20.0_alpha.1-0.noarch (graviteeio)
           Requires: graviteeio-apim-management-ui-3x = 3.20.0-alpha.1`. 

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Set up an EC2 instance according to the prerequisites and set up the necessary security groups.
2. Connect to the EC2 instance using OpenSSH
3. Run the command `curl -L https://bit.ly/install-apim-3x | sudo bash` 

## :rainbow: Expected behaviour

I expected it to run smoothly like it was displayed in the documentation

## Current behaviour

Error messages:  `can't read /opt/graviteeio/apim/management-ui/constants.json: No such file or directory`, `sed: can't read /opt/graviteeio/apim/portal-ui/assets/config.json: No such file or directory`, and `Error: Package: graviteeio-apim-3x-3.20.0_alpha.1-0.noarch (graviteeio)
           Requires: graviteeio-apim-management-ui-3x = 3.20.0-alpha.1`. 

## :movie_camera: Useful information

![image](https://user-images.githubusercontent.com/122064412/211016986-cabaca01-c248-4bbc-9a13-05a47fc5aef6.png)
![image](https://user-images.githubusercontent.com/122064412/211017002-0b636445-4b52-48d7-8619-bf376a7dce88.png)
![image](https://user-images.githubusercontent.com/122064412/211017023-15f0f07d-f672-44d5-8181-eb9a9e70f3b3.png)

## :computer: Desktop:

***Please complete the following information:***
 - OS: AWS Linux Machine connecting through Windows PowerShell

**Comment by mouligno** [comment]
hi @EphraimXX can you try with latest 3.20.0 ?

**Comment by EphraimXX** [comment]
How do I do that, please?
Still new to Gravitee

**Comment by EphraimX** [comment]
Hi @mouligno, how do I install the latest version please?

**Comment by gaetanmaisse** [comment]
We've cleaned the package registry (removed the `alpha` version that was causing this) so you should be able to rerun the same script and shouldn't face any issues.

I'm closing the issue but feel free to reopen it if needed
