### ISSUE TITLE
Question: how to use path params?

### ISSUE THREAD

**Issue by Mattue** [gravitee-io/issues#8824]
Hi, can you please advice on how to use path params in gravitee.

According to documentation `:param` should work, but `

 {#request.pathParams['param']} 

` and `

 {#request.headers.keySet} 

` both returning nothing to me.

Context:

I have flow with following configuration
 ```
 POST /myFlow/:myId
 ```

And I'm making HTTP Callout in this flow to `webhook.site` with following body
 ```

 {#request.pathParams.keySet} {#request.pathParams['myId']} 

```

After deploy I'm making request - `POST [https://my.gravitee.host/myFlow/123](https://my.gravitee.host/myFlow/123)`

And empty lines are returned 😔 

I was expecting following
 ```
 myId
 123
 ```

End of context.

Thank you in advance!

**Comment by gaetanmaisse** [comment]
Also closing this one @Mattue, as the syntax was ok, everything should be back on track with the fix ;)
