### ISSUE TITLE
Management API Internal API node configuration endpoint returns HTTP 500

### ISSUE THREAD

**Issue by kieranswhite** [gravitee-io/issues#8837]
## :collision: Describe the bug
When trying to utilise the node configuration endpoint for the management API internal API in the Gravitee docker image for `3.18.17` we receive a HTTP 500 and exceptions in the Docker container logs. We've reproduced this with the Helm chart implementation and basic Docker compose setup.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Launch Gravitee Docker compose with images set to `3.18.17`
2. Exec into the management API container: ```docker exec -it gio_apim_management_api /bin/sh```
3.  Curl the internal node configuration endpoint: ```curl -X GET http://localhost:18083/_node/configuration```
4. The curl will return with a HTTP 500 and error logs in the management API process will return with something like the following:
```
│ gravitee-api java.lang.NullPointerException: Cannot invoke "org.springframework.core.env.PropertiesPropertySource.getPropertyNames()" because "nodeConfiguration" is null 
```

## :rainbow: Expected behaviour
We'd expect the Gravitee node configuration to return as a JSON as outlined here: https://docs.gravitee.io/apim/3.x/apim_installguide_rest_apis_technical_api.html
This was working in a previous Docker image (`3.18.4`)

## Current behaviour
A clear and concise description of what is currently happening.
We receive a HTTP 500 (internal server error) and error logs in the management API container

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material
![image](https://user-images.githubusercontent.com/6289007/214063396-ac883bc6-f3f5-4e9d-a164-760414565d27.png)

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.18.17
 - OS: MacOS docker-compose or EKS with Helm
 - Browser N/A

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by gaetanmaisse** [comment]
👋🏻 Hey @kieranswhite!

In [APIM 3.18.19](https://docs.gravitee.io/apim/3.x/changelog-3.18.html#apim_3_18_19_2023_02_17) we fixed the following technical endpoints:
 - `/_node/monitor` (https://github.com/gravitee-io/issues/issues/8838)
 - `/_node/configuration` (https://github.com/gravitee-io/issues/issues/8875)

So I will close that issue but feel free to reopen if you're still facing the issue after upgrading to 3.18.19!
