### ISSUE TITLE
[JWT Policy] error raised in the logs when GATEWAY_KEYS is used for the resolver

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#8848]
# Describe the bug

When using GATEWAY_KEYS for the resolver in the JWT Policy, the following error is raised in the gateway logs : 

<div class="preformatted panel" style="border-width: 1px;"> 
 <div class="preformattedContent panelContent"> 
  <pre>ERROR i.gravitee.policy.v3.jwt.JWTPolicyV3 - [api-id:0c45b792-bd70-3e07-8d7a-9fe92baac04c] [request-id:f1e860d4-2896-416e-a860-d42896016e87] [request-path:/myapi] Cannot invoke "String.indexOf(String)" because "s" is null</pre> 
 </div> 
</div>

The behavior of the Policy appears to work as expected but each API call fills the logs with this error.

# To Reproduce

Steps to reproduce the behaviour

*   Create an API with a JWT Policy with GATEWAY_KEYS resolver option
*   Attempt to make a call to the API
*   See error in the logs

**Comment by gaetanmaisse** [comment]
Closing this issue as I wasn't able to reproduce the issue. 
I got some logs but only when the JWT policy configuration was not correct. 
Will need more info to investigate deeper.
