### ISSUE TITLE
Cant access my API using gravitee.io 8082

### ISSUE THREAD

**Issue by YoganandChandran** [gravitee-io/issues#8857]
Hi guys,

Hope you are doing well,

I create one sample API (localhost:8080/filetransfer/upload) in SpringBoot + Kafka  for upload JSON data. It works fine. I use that API in Gravitee.io 

<img width="625" alt="bad gateway" src="https://user-images.githubusercontent.com/94908803/216529806-2acd94ee-fbec-4e39-9145-1df4bc8faba2.PNG">

Backend and create one new proxy API(localhost:8082/upload) by creating APIKey plan . If i try to access the new proxy API it shows 502 bad gateway please help me to resolve this issue. In logs it doesn't show anything.I also create a plan and subscription for that API by creating one new Application upload.

Thanks

**Comment by gaetanmaisse** [comment]
Hey! Can you provide a GitHub repo that reproduces the issue? Or at least an export of the API? Otherwise, we won't be able to help you much

**Comment by YoganandChandran** [comment]
> Hey! Can you provide a GitHub repo that reproduces the issue? Or at least an export of the API? Otherwise, we won't be able to help you much

Hey, Hi ! Thanks for your concern! I changed my API path to /filetransfer/upload after I post this issue here So,don't be confused. I post my export of an API here to help me to solve this issue. Thanks.

<img width="633" alt="UpdateAPI" src="https://user-images.githubusercontent.com/94908803/217155847-cfd78978-92bb-4492-90e2-36c780f56942.PNG">

[TestAPI.zip](https://github.com/gravitee-io/issues/files/10671757/TestAPI.zip)


Please help as soon as possible to solve this issue.

**Comment by YoganandChandran** [comment]
> Hey! Can you provide a GitHub repo that reproduces the issue? Or at least an export of the API? Otherwise, we won't be able to help you much

HI, I upload my project here for your verification !

[springbootkafka.zip](https://github.com/gravitee-io/issues/files/10671829/springbootkafka.zip)
