### ISSUE TITLE
Failed to resolve method [ class org.codehaus.groovy.runtime.EncodingGroovyMethods encodeBase64 byte[] ]

### ISSUE THREAD

**Issue by sekaijin** [gravitee-io/issues#8859]
groovy onRequestContent

I'm trying to base64 encode the body received by POST.
 But the method is not available.

the groovy documentation says to use
 ```
 "myString".bytes.encodeBase64().toString();
 ```
 but it doesn't work.
 ```
 Failed to resolve method [ class B encodeBase64 byte[] ]
 ```
 in the gravity documentation
 "The complete whitelist can be found here: gravity groovy whitelist ->
 [https://raw.githubusercontent.com/gravitee-io/gravitee-policy-groovy/master/src/main/resources/groovy-whitelist](https://raw.githubusercontent.com/gravitee-io/gravitee-policy-groovy/master/src/main/resources/groovy-whitelist)"
 ```
 ...
 method org.codehaus.groovy.runtime.EncodingGroovyMethods encodeBase64 byte[]
 method org.codehaus.groovy.runtime.EncodingGroovyMethods encodeBase64 byte[] boolean
 method org.codehaus.groovy.runtime.EncodingGroovyMethods encodeBase64 byte[] boolean boolean boolean
 method org.codehaus.groovy.runtime.EncodingGroovyMethods encodeBase64 java.lang.Byte[]
 method org.codehaus.groovy.runtime.EncodingGroovyMethods encodeBase64 java.lang.Byte[] boolean
 ...
 ```

Yet that doesn't work.
 ```
 import org.codehaus.groovy.runtime.EncodingGroovyMethods

return EncodingGroovyMethods.encodeBase64("myString".bytes).toString()
 ```
 ```
 Failed to resolve method [ class org.codehaus.groovy.runtime.EncodingGroovyMethods encodeBase64 byte[] ]
 ```
 Thank

**Comment by sekaijin** [comment]
No Suggest ?

**Comment by gaetanmaisse** [comment]
@sekaijin can you export an API with this issue? I'm not able to reproduce the problem on our environments, the same script is working fine

**Comment by gaetanmaisse** [comment]
I'm closing the issue due to inactivity, feel free to reopen and provide the export of API reproducing the problem.
