### ISSUE TITLE
Configuration of gRPC passthrough

### ISSUE THREAD

**Issue by sgerbino** [gravitee-io/issues#8861]
1.  ## 💥 Describe the bug We are attempting to configure a gRPC passthrough the Gravitee API. We have stood up our gRPC microservice and we are able to query it directly via a gRPC client. We have then inserted the Gravitee gateway in between by configuring an entry point of type `grpc`. When we send client requests through the gateway the requests we get the followin logs from the gRPC service:

<pre> 

 {"created":"@1675468222.745268260","description":"Error received from peer ipv4:69.164.192.67:33762","file":"/root/.hunter/_Base/dd58157/6580fd1/2a0e7af/Build/gRPC/Source/src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"Stream removed","grpc_status":2} 

 </pre>

Is there a guide anywhere to show how a simple gRPC passthrough should be configured?

1.  🌄 To Reproduce Steps to reproduce the behaviour: 1\. Create an API 2\. Click Proxy -> Backend Services 3\. Create an endpoint that points to the gRPC server with type `grpc` 4\. Click Proxy -> General 5\. Create an entry point such as `/grpc` 6\. Stand up an nginx server using `grpc_pass` to forward a hostname such as `something.io` to the internal Gravitee entrypoint `mysite.io/grpc` 7\. Send a gRPC using a gRPC client 8\. Observe gRPC server logs

1.  🌈 Expected behaviour I expect the gRPC client to send a request and get a response through the Gravitee API gateway.

1.  ## Current behaviour When sending a gRPC through the Gravitee gateway, the client receives the following response: `14: Received http2 header with status: 502`

1.  💻 Desktop:

**Please complete the following information:**

*   Environment: 3
*   OS: Ubuntu 22.04

1.  <g-emoji class="g-emoji" alias="warning">
     ⚠️ 
     </g-emoji> Potential impacts

**Which other features may be impacted by this fix. This could be populated after fix**

**What are the impacted versions?**

1.  ## 🔗 Dependencies

We see that this issue has similar logs, but we have turned off logging and it has not resolved: [https://github.com/gravitee-io/issues/issues/8574](https://github.com/gravitee-io/issues/issues/8574)

**Comment by brasseld** [comment]
Hi @sgerbino 
Have you configured the gateway with http2 support ?

**Comment by sgerbino** [comment]
I've followed this guide to enable HTTP2:

<img width="1354" alt="Screenshot 2023-02-06 at 5 09 45 PM" src="https://user-images.githubusercontent.com/778036/217098903-7d65096c-c9d3-4e83-96f6-d6b73d10acb0.png">

Set the endpoint as follows:

<img width="1079" alt="Screenshot 2023-02-06 at 5 10 43 PM" src="https://user-images.githubusercontent.com/778036/217099055-7436157e-4796-454c-9243-4823632224f5.png">

Set the entry point like this:

<img width="754" alt="Screenshot 2023-02-06 at 5 11 39 PM" src="https://user-images.githubusercontent.com/778036/217099179-22a7d340-68a9-4aaa-8435-d72c7d665fef.png">

And set the gRPC pass on nginx:

```console
server {
	listen 80 http2;
	listen [::]:80 http2;

	server_name _;

	rewrite ^(.*)$ /grpc/$1;

	location / {
		grpc_pass localhost:8082;
	}
...
`

When I use my gRPC client pointing at this address `<hostname>:80` I get the same error:
`14: Received http2 header with status: 502`

And on the server, it is the same error reported in the original ticket.

Any ideas?

**Comment by brasseld** [comment]
What if you calling the gravitee gw directly, without going through nginx @sgerbino ?

**Comment by sgerbino** [comment]
I can't because gRPC doesn't support putting a path for example I can use the target `<hostname>:<port>` but not `<hostname>:<port>/<path>`. The entrypoint requires 3 characters so I'm required to put `/grpc` as the entry point. (This is why I've been trying to use the nginx method).

I tried to use the virtual host option where I seem to map `my.domain.com` to an entry point -- but this hasn't worked for us (it seems to not map anywhere). Perhaps I'm not using this option correctly?

This is what I've tried:
<img width="1722" alt="Screenshot 2023-02-07 at 12 14 34 PM" src="https://user-images.githubusercontent.com/778036/217316194-515d07db-fbc7-465c-ad8f-cf1944eeb693.png">

I'm not sure if there's another place to setup the `/grpc` part to make this work. But when I set up the configuration as it is shown above, sending it to gravitee gateway results in a 404.

**Comment by brasseld** [comment]
Do you have a backend which I could run so I can have a look ?

**Comment by sgerbino** [comment]
> Do you have a backend which I could run so I can have a look ?

`139.144.17.130:50051`

**Comment by brasseld** [comment]
There is no particular to call there ?
Are you able to call that one with grpcurl? If so, can you please provide the command you are using ?

**Comment by sgerbino** [comment]
Hi, I've got the query working using `grpcurl`. You need the descriptors file located here: https://github.com/koinos/koinos-proto-descriptors/blob/grpc/koinos_descriptors.pb because we don't have server side reflection. Using the above file, the following query works for me:

```console
❯ grpcurl -protoset koinos_descriptors.pb -plaintext 139.144.17.130:50051 koinos.services.koinos/get_resource_limits
{
  "resourceLimitData": {
    "diskStorageLimit": "524288",
    "diskStorageCost": "23915",
    "networkBandwidthLimit": "1048576",
    "networkBandwidthCost": "3619",
    "computeBandwidthLimit": "287500000",
    "computeBandwidthCost": "18"
  }
}
```

**Comment by YoganandChandran** [comment]
> Hi @sgerbino Have you configured the gateway with http2 support ?

@brasseld please check this issue ->https://github.com/gravitee-io/issues/issues/8857

**Comment by sgerbino** [comment]
Is there any update on this ticket? Is there any more information I can provide that would be helpful?
