### ISSUE TITLE
Issue when deleting an api, containing 2 empty spaces in the name '  '

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#8867]
## :collision: Describe the bug
In 3.18.18, when used two empty spaces in the name, an api cannot be deleted (screenshot attached)

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1\. Create an api with '  ' 2 empty spaces 
2\. Try to delete it
3\. See behavior on the picture
![image](https://user-images.githubusercontent.com/89140082/218057297-02e970aa-8561-4ac2-99d4-c663f6abc5b0.png)

## :rainbow: Expected behaviour
To be able to delete the api

## Current behaviour
Not deleting if '  ' included in the name

Tested in 3.18.18

**Comment by gaetanmaisse** [comment]
@zveljanoski can you export the API you used to reproduce the issue because I tested it on our 3.18.x env and everything is working fine

**Comment by gaetanmaisse** [comment]
Ok, it looks like the issue isn't coming from the validation but the `<code></code>` block used to display the name of the API.
