### ISSUE TITLE
[apim] Question - How CORS works on API?

### ISSUE THREAD

**Issue by Mattue** [gravitee-io/issues#8871]
Hey!

I'm playing with CORS configuration on API level and not sure that I'm configuring it right.

I have set CORS enabled and allowed only `GET` and `allow-me` header as it says in <span class="error">[blog]</span>([https://www.gravitee.io/blog/blog-the-day-i-understood-cors](https://www.gravitee.io/blog/blog-the-day-i-understood-cors)). But still, I'm able to process request with `HTTP 200` with `POST` and `not-allow-me` header.

!<span class="error">[изображение]</span>([https://user-images.githubusercontent.com/9050530/218143744-a843331b-0618-48c3-8291-25d56ecc99d4.png](https://user-images.githubusercontent.com/9050530/218143744-a843331b-0618-48c3-8291-25d56ecc99d4.png))

!<span class="error">[изображение]</span>([https://user-images.githubusercontent.com/9050530/218144011-a8c7b07b-4626-4722-8f85-2c12591c13c2.png](https://user-images.githubusercontent.com/9050530/218144011-a8c7b07b-4626-4722-8f85-2c12591c13c2.png))

What I'm doing wrong?

Thanks in advance!

**Comment by a-cordier** [comment]
Hello @Mattue 

I can see that you are using Postman, which does not implement [SOP](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) as a browser do. If you want to test CORS enforcement, you would need to make your request from a browser (using fetch or any XHR library).

**Comment by Mattue** [comment]
Hi @a-cordier 

For sure it was a dumb question, sorry. Thank you for your reply!

It's working as expected, just forgot to write back

Regards!
