### ISSUE TITLE
[Helm] add the ability to change the metrics default labels for the metrics in the helm chart

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#8874]
## :collision: Describe the bug
Helm Chart do not provide the ability to change the metrics labels from : 
```
# metrics service
  metrics:
    enabled: false
# default: local, http_method, http_code
#    labels:
#      - local
#      - remote
#      - http_method
#      - http_code
#      - http_path
```
https://github.com/gravitee-io/gravitee-api-management/blob/master/gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-distribution/src/main/resources/config/gravitee.yml#L291

config-map.yaml : 
```
      {{- if .Values.gateway.services.metrics.enabled }}
      metrics:
        enabled: {{ .Values.gateway.services.metrics.enabled }}

```
https://github.com/gravitee-io/helm-charts/blob/master/apim/3.x/templates/gateway/gateway-configmap.yaml#L331

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: [e.g. 3.10.x]

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by gaetanmaisse** [comment]
I've got some exciting news to share - we've finally squashed that pesky bug that's been bugging you! 🎉 
The fix is included in the latest version of the APIM Helm Chart (v3.1.62), so you can finally take a breather and let your API do the heavy lifting.
