### ISSUE TITLE
Dynamic properties API out of sync

### ISSUE THREAD

**Issue by Zeyad-Haitham99** [gravitee-io/issues#8878]
## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:

## Current behaviour
A clear and concise description of what is currently happening.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: [e.g. 3.10.x]

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by gaetanmaisse** [comment]
👋🏻  @Zeyad-Haitham99, without any information we won't be able to help much.
I will close this issue, in the meantime, you can create a new one and fill in the template to give as much information as possible.
