### ISSUE TITLE
Deploy on Kubernates cluster

### ISSUE THREAD

**Issue by Zeyad-Haitham99** [gravitee-io/issues#8879]
<html>
<body>

ERROR i.g.r.api.services.sync.SyncManager - An error occurs while synchronizing APIs
--
Thu, Feb 16 2023 1:04:05 pm | java.lang.NullPointerException: Cannot invoke "io.gravitee.repository.management.api.EventRepository.searchLatest(io.gravitee.repository.management.api.search.EventCriteria, io.gravitee.repository.management.model.Event$EventProperties, java.lang.Long, java.lang.Long)" because "this.target" is null

</body>
</html>

**Comment by gaetanmaisse** [comment]
👋🏻  @Zeyad-Haitham99, without any information we won't be able to help much.
I will close this issue, in the meantime, you can create a new one and fill in the template to give as much information as possible (full stack trace, values you're using to deploy etc)
