### ISSUE TITLE
Changing the default logo in the Theme has no effect 

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#8882]
# Describe the bug

When trying to change the default logo of the Console in Organization Settings -> Theme -> logo, it has no effect on the top left logo of the Console.

# To Reproduce

Steps to reproduce the behaviour:

1.  Go to Organization Settings -> Theme
2.  Change the logo with a different file in nginx /usr/share/nginx/html/themes/assets, add your new logo file
3.  Check the Console UI, the top left logo remains the same

This was working in 3.15.

**Comment by gaetanmaisse** [comment]
We made this a deliberate change when we added the new UI to APIM. The APIM product is intended to be branded for Gravitee, whereas the portal is intended to be customizable for the customer's branding.
Going forward we intend to make this separate even stricter - APIM Console is for the API publisher to work in, whereas the portal is where customers work in and see their own branding. We need to do more to make the portal's branding better, but that is still the strategy.
