### ISSUE TITLE
[management] Improve helm chart to be able to set no values for SMTP configuration

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#8889]
## Describe the bug

It is currently impossible to set with helm charts no values for SMTP configuration, so that the config would be available to be set in the console UI. Need to improve charts so that if you leave no configuration for SMTP, the gravitee.yml file would have all the SMTP configuration commented out or removed completely so that it would be possible to edit in UI. This is important since this configuration should remain same on each deployment, to avoid manually editing the gravitee.yml file on each redeployment of the environments. Behavior is similar if not same in docker-compose (if set SMTP with ENV variables works fine, if nothing is set in the variables, the default gravitee.yml configuration is used that already has some dummy settings and you cant change those in UI)

## Expected behaviour

If no configuration is set for SMTP In charts there would not be any default values in gravitee.yml file for SMTP, allowing to manually configure the SMTP configuration in the UI.

## Useful information

Default config in gravitee.yml file that overrides the UI:

email:
 enabled: false
 host: smtp.my.domain
 subject: "<span class="error">[Gravitee.io]</span> %s"
 port: 587
 from: noreply@my.domain

Desired configuration:

#email:

1.  enabled: false
2.  host: smtp.my.domain
3.  subject: "<span class="error">[Gravitee.io]</span> %s"
4.  port: 587
5.  from: noreply@my.domain

**Comment by gaetanmaisse** [comment]
Done, it is available in the latest version of APIM Helm chart. 

⚠️  You need to explicitly set an empty `smtp` block in your `Values.yml` if you want to override the default values: 
```yaml
    smtp:
```
