### ISSUE TITLE
[policy] [dynamic-routing] Add documentation

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#89]
The README file of https://github.com/gravitee-io/gravitee-policy-dynamic-routing/blob/master/README.adoc do not provide any configuration example.

The README must show how to configure the policy

**Comment by brasseld** [comment]
Fixed by commit https://github.com/gravitee-io/gravitee-policy-dynamic-routing/commit/6bd0f74616f994a75ac667d661c0c1a934d95b17
