### ISSUE TITLE
Application search field in management console

### ISSUE THREAD

**Issue by fabMrc** [gravitee-io/issues#8922]
Hi

In 3.19.1 members of applications does not see any application by default when click on applications tab To see their applications they must write 'space' and enter and all associated applications are displayed Before and it was a more valuable user experience, application list was displayed without any search action

**Comment by gaetanmaisse** [comment]
Hey @fabMrc 👋🏻 
I'm not able to reproduce the issue you describe with the last 3.19, or I misunderstood the problem.
Can you provide a screen recording (or a gif) in which you face the issue?

**Comment by fabMrc** [comment]
```
{
  "message" : "2 applications has no identified primary owners in this list 6f7202b0-5cb2-48da-b202-b05cb2c8da2f / 6e8cf14a-7f14-42ab-8cf1-4a7f14a2abbf.",
  "technicalCode" : "unexpected",
  "http_status" : 500
}
```
So I restore these to application and as a consequence I am now PRIMARY OWNER and there is no problem with search field that display all application i have to see by default
I do not know why these two applications was not associated to a PRIMARY OWNER

**Comment by gaetanmaisse** [comment]
Did you upgrade from an old APIM version at one time or another? Or was 3.19 the first install of APIM?

**Comment by fabMrc** [comment]
Upgraded from 3.17.3
