### ISSUE TITLE
Only first matching flow is executed

### ISSUE THREAD

**Issue by oyviaase** [gravitee-io/issues#8935]
## Describe the bug

The first matching flow for an API is the only flow being exectued even if there are multiple matches. This only applies to API that's created on this version, an API created on an older instance that's been upgraded triggers all the matching flows

## To Reproduce

Steps to reproduce the behaviour:

1.  Create a new API, with an echo endpoint
2.  Go to 'Design'
3.  Add a "Transform Headers" and add a header called "Test" with "test1" as value
4.  Add a new "API Flows"
5.  In the new flow add "Override HTTP Method" and set it to `POST`
6.  Create a new application and subscribe to the newly created API
7.  Use curl/postman or another tool to call the API
8.  Watch it fail

## Expected behaviour

The echo server should reply that it got an post request together with the header set in step 3

## Current behaviour

The echo server reply that it got a `GET` request with the header set in step 3

## Useful information

Curl with the override HTTP method flow running first

curl --header "X-Gravitee-Api-Key: xxxxx" [https://gw-xxx.xxx/v1/echo](https://gw-xxx.xxx/v1/echo) Welcome to echo-server! Here's what I know.

> Head to /ws for interactive websocket echo!

-> My hostname is: echo-server

-> Requesting IP: xxx.xxx.xxx.xxxx:xxx

-> Request Headers |

HTTP/1.1 POST /

....

Accept-Encoding: deflate, gzip Accept: **/** User-Agent: curl/7.85.0 X-Forwarded-For: xxx.xxx.xxx.xxx X-Forwarded-Host: echo.xxx.xxx.xxx X-Forwarded-Port: 443 X-Gravitee-Request-Id: 08652d1f-c4bd-47e6-a52d-1fc4bd77e60f X-Gravitee-Transaction-Id: 08652d1f-c4bd-47e6-a52d-1fc4bd77e60f ...

Curl with the header flow running first

curl --header "X-Gravitee-Api-Key: xxxxx" [https://gw-xxx.xxx/v1/echo](https://gw-xxx.xxx/v1/echo) Welcome to echo-server! Here's what I know.

> Head to /ws for interactive websocket echo!

-> My hostname is: echo-server

-> Requesting IP: xxx.xxx.xxx.xxxx:xxx

-> Request Headers |

HTTP/1.1 GET /

....

Accept-Encoding: deflate, gzip Accept: **/** Test: test1 User-Agent: curl/7.85.0 X-Forwarded-For: xxx.xxx.xxx.xxx X-Forwarded-Host: echo.xxx.xxx.xxx X-Forwarded-Port: 443 X-Gravitee-Request-Id: 08652d1f-c4bd-47e6-a52d-1fc4bd77e60f X-Gravitee-Transaction-Id: 08652d1f-c4bd-47e6-a52d-1fc4bd77e60f ...

## Environment

Gravitee running on ok4.10

 _**What is the impacted version?**_ graviteeio/apim-management-api:3.15.21

## Potential impacts

 _**Which other features may be impacted by this fix. This could be populated after fix**_ 

 _**What are the impacted versions?**_ 

## Dependencies

Link a story or other related things...

**Comment by gaetanmaisse** [comment]
@oyviaase which flow mode are you using? `Default` or `Best Match`?

You can see it in the `Configuration` Tab of the `Design` Studio
![image](https://user-images.githubusercontent.com/4112568/231516419-7b1ddece-3905-4a24-9e30-1b16aab1238c.png)

**Comment by oyviaase** [comment]
@gaetanmaisse I seem to have been using `Best Match` instead of `Default` changing it to `Default` fixe the issue. I can't remember ever setting it to `Best Match` mode, at least the new API I created defaulted to `Default` flow mode, so it might be an artifact left from whichever version I originally configured the API in that set it to `Best Match`.

Another short question, is that when there are more than one equally matching paths for "Best match" does it always select the first matching path or should it select all of them?


![image](https://user-images.githubusercontent.com/9009359/231690575-dd8cdcf3-165f-4f27-9793-a71cc5e3c414.png)

**Comment by gaetanmaisse** [comment]
> is that when there are more than one equally matching paths for "Best match" does it always select the first matching path or should it select all of them?

In `Best match` mode, the gateway will always select a single flow, the closest match based on an internal algo.
You can be interested by this unit tests class as it provides a lot of examples of flow selection in various context: https://github.com/gravitee-io/gravitee-api-management/blob/638e168fd5d0c3d576278a301b6d1f6a673a685e/gravitee-apim-gateway/gravitee-apim-gateway-flow/src/test/java/io/gravitee/gateway/jupiter/flow/BestMatchFlowBaseTest.java#L77

**Comment by gaetanmaisse** [comment]
@oyviaase, as your base issue look to be solved, I will close this issue. Feels free to reopen it if needed!
