### ISSUE TITLE
 Entrypoint mappings in a multi environment setup with shared gateways

### ISSUE THREAD

**Issue by sjanssens1977** [gravitee-io/issues#8955]
## </g-emoji> Feature

**As a** Gravitee.io APIM solution architect/engineer.

**I want to** be able to configure entrypoint mappings assigned to a specific environment

**So that** only the entrypoint appropriate for the environment are shown in the environment specific developer portal

## </g-emoji> Additional information

I have a multi environment setup (DEV|TST|ACC) with an internal and an external gateway. The internal gateway is shared by the three environments and the external gateway is shared by the TST and ACC environment

Virtual hosts used for API entrypoint definitions:

*   [apig-dev.internal.example.org](http://apig-dev.internal.example.org/)
*   [apig-tst.internal.example.org](http://apig-tst.internal.example.org/)
*   [apig-acc.internal.example.org](http://apig-acc.internal.example.org/)
*   [apig-tst.example.org](http://apig-tst.example.org/)
*   [apig-acc.example.org](http://apig-acc.example.org/)

Sharding tags:

*   internal
*   external

Entrypoint mappings:

*   [apig-dev.internal.example.org](http://apig-dev.internal.example.org/) - internal
*   [apig-tst.internal.example.org](http://apig-tst.internal.example.org/) - internal
*   [apig-acc.internal.example.org](http://apig-acc.internal.example.org/) - internal
*   [apig-tst.example.org](http://apig-tst.example.org/) - external
*   [apig-acc.example.org](http://apig-acc.example.org/) - external

When I create and deploy a API to the internal gateway for the DEV environment I want the developer portal to show the virtual host name used in the definition. In this case [apig-dev.internal.example.org](http://apig-dev.internal.example.org/). With the current configuration all 3 virtual hosts mapped to the internal gateway are shown in the developer portal, which is incorrect.

I do not want to create different sharding tags (internaL_dev, internal_tst, internal_acc, external_dev, …) since this complicates API propagation between environment (DEV → TST → ACC).

For the moment I'm using the "overwrite entrypoint"-feature on the API to accomplish what I want.

**Comment by anthonyjgatti** [comment]
Hello @sjanssens1977, thanks for creating the issue. We will take a look at this at the beginning of our next sprint and give an analysis of the effort involved and update accordingly. Thanks!

**Comment by anthonyjgatti** [comment]
Hello @sjanssens1977, sorry for the delay. We did some internal research on this and determined that we **will** move forward with this request. Thank you for filing it! We do have to do some intermediate work to determine if we want to first introduce the notion of environments as a formal construct within a given APIM instance. Right now we have this with our Cockpit product but we are discussing alternative options. Please feel free to reach out and follow up.

I do not have a timeline on this feature yet but we will follow up as soon as we have a good idea on when we will take this up. Thank you again!
