### ISSUE TITLE
Gravitee does not assign groups based on JWT token groups using `{(#jsonPath(#profile, '$.groups') matches '_group_name')}`

### ISSUE THREAD

**Issue by zemiak** [gravitee-io/issues#8960]
## Describe the bug

We are trying to map user groups using `

 {(#jsonPath(#profile, '$.groups') matches '_group_name')} 

` Groups Mapping conditions. This is not working on 3.20.0 for us.

## To Reproduce

Steps to reproduce the behaviour:

1.  setup a keycloak authentication server

1.  have a user with groups

1.  map the groups into the token in keycloak

1.  setup the keycloak authentication in Gravitee

1.  select "Computed during each user authentication" for Group and Role mappings option

1.  define a Role Mapping with: ` {(#jsonPath(#profile, '$.groups') matches '_group_name' )}

` -> ADMIN roles

1.  login

## Expected behaviour

User is ADMIN

## Current behaviour

User is not ADMIN (cannot access Settings)

## Useful information

By observing the logs, we can see that groups are indeed in the token and JWT profile:

gio_apim_management_api | 14:05:34.960 <span class="error">[gravitee-listener-87]</span> ERROR i.g.r.a.service.impl.UserServiceImpl - Using mapping: "picture", no fields are located in

 {"sub":"a7bcb15a-4d9a-4b7b-b2a2-f4bb6bbe9fa1","name":"Miroslav Vasko","groups":["_appdev_devops","_appdev_devops_su","_appdev_shared"],"groupsJoined":",_appdev_devops,_appdev_devops_su,_appdev_shared,","preferred_username":"zemiak","given_name":"Miroslav","family_name":"Vasko","email":"[[[[miroslav.vasko+hello@cargo-partner.com| mailto:miroslav.vasko+hello@cargo-partner.com]| [mailto:miroslav.vasko+hello@cargo-partner.com| mailto:miroslav.vasko+hello@cargo-partner.com]]| [[mailto:miroslav.vasko+hello@cargo-partner.com| mailto:miroslav.vasko+hello@cargo-partner.com]| [mailto:miroslav.vasko+hello@cargo-partner.com| mailto:miroslav.vasko+hello@cargo-partner.com]]]| [[[mailto:miroslav.vasko+hello@cargo-partner.com| mailto:miroslav.vasko+hello@cargo-partner.com]| [mailto:miroslav.vasko+hello@cargo-partner.com| mailto:miroslav.vasko+hello@cargo-partner.com]]| [[mailto:miroslav.vasko+hello@cargo-partner.com| mailto:miroslav.vasko+hello@cargo-partner.com]| [mailto:miroslav.vasko+hello@cargo-partner.com| mailto:miroslav.vasko+hello@cargo-partner.com]]]]"} 

Debug logs when authenticating the user related to group matching:

14:32:22.176 <span class="error">[gravitee-listener-62]</span> DEBUG i.g.r.m.m.t.NoTransactionManager - Creating new transaction with name <span class="error">[io.gravitee.rest.api.service.impl.UserServiceImpl.createOrUpdateUserFromSocialIdentityProvider]</span>: PROPAGATION_REQUIRED,ISOLATION_DEFAULT; 'graviteeTransactionManager',+io.gravitee.rest.api.service.exceptions.AbstractManagementException 14:32:22.202 <span class="error">[gravitee-listener-62]</span> ERROR i.g.r.a.service.impl.UserServiceImpl - Using mapping: "picture", no fields are located in

 {"sub":"a7bcb15a-4d9a-4b7b-b2a2-f4bb6bbe9fa1","name":"Miroslav Vasko","groups":["_appdev_devops","_appdev_devops_su","_appdev_shared"],"groupsJoined":",_appdev_devops,_appdev_devops_su,_appdev_shared,","preferred_username":"zemiak","given_name":"Miroslav","family_name":"Vasko","email":"[[[[miroslav.vasko+hello@cargo-partner.com| mailto:miroslav.vasko+hello@cargo-partner.com]| [mailto:miroslav.vasko+hello@cargo-partner.com| mailto:miroslav.vasko+hello@cargo-partner.com]]| [[mailto:miroslav.vasko+hello@cargo-partner.com| mailto:miroslav.vasko+hello@cargo-partner.com]| [mailto:miroslav.vasko+hello@cargo-partner.com| mailto:miroslav.vasko+hello@cargo-partner.com]]]| [[[mailto:miroslav.vasko+hello@cargo-partner.com| mailto:miroslav.vasko+hello@cargo-partner.com]| [mailto:miroslav.vasko+hello@cargo-partner.com| mailto:miroslav.vasko+hello@cargo-partner.com]]| [[mailto:miroslav.vasko+hello@cargo-partner.com| mailto:miroslav.vasko+hello@cargo-partner.com]| [mailto:miroslav.vasko+hello@cargo-partner.com| mailto:miroslav.vasko+hello@cargo-partner.com]]]]"} 

14:32:22.205 <span class="error">[gravitee-listener-62]</span> DEBUG i.g.r.a.service.impl.UserServiceImpl - the expression

 {(#jsonPath(#profile, '$.groups') matches '_appdev_shared' )} didn't match [miroslav.vasko+hello@cargo-partner.com](mailto:miroslav.vasko+hello@cargo-partner.com) on user's info

 14:32:22.206 <span class="error">[gravitee-listener-62]</span> DEBUG i.g.r.a.service.impl.UserServiceImpl - the expression {(#jsonPath(#profile, '$.groups') matches '_appdev_shared' )} 

didn't match [miroslav.vasko+hello@cargo-partner.com](mailto:miroslav.vasko+hello@cargo-partner.com) on user's info

## Environment

Gravitee 3.20.0, docker-compose setup

**Comment by zemiak** [comment]
@gaetanmaisse 

I am getting a different error now 

in the UI:
`The template evaluation returns an error. Expression: {jsonPath(#profile, '$.groups').contains('_appdev_shared')}`

in Gravitee Management logs:
```
gio_apim_management_api | Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1001E: Type conversion problem, cannot convert from java.lang.String to boolean
gio_apim_management_api | 	at org.springframework.expression.spel.support.StandardTypeConverter.convertValue(StandardTypeConverter.java:87)
gio_apim_management_api | 	at org.springframework.expression.common.ExpressionUtils.convertTypedValue(ExpressionUtils.java:57)
gio_apim_management_api | 	at org.springframework.expression.common.LiteralExpression.getValue(LiteralExpression.java:92)
gio_apim_management_api | 	at io.gravitee.el.spel.SpelTemplateEngine.eval(SpelTemplateEngine.java:70)
gio_apim_management_api | 	... 126 common frames omitted
gio_apim_management_api | Caused by: org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [boolean] for value '{jsonPath(#profile, '$.groups').contains('_appdev_shared')}'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value '{jsonPath(#profile, '$.groups').contains('_appdev_shared')}'
gio_apim_management_api | 	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:47)
gio_apim_management_api | 	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:192)
gio_apim_management_api | 	at org.springframework.expression.spel.support.StandardTypeConverter.convertValue(StandardTypeConverter.java:82)
gio_apim_management_api | 	... 129 common frames omitted
gio_apim_management_api | Caused by: java.lang.IllegalArgumentException: Invalid boolean value '{jsonPath(#profile, '$.groups').contains('_appdev_shared')}'
gio_apim_management_api | 	at org.springframework.core.convert.support.StringToBooleanConverter.convert(StringToBooleanConverter.java:66)
gio_apim_management_api | 	at org.springframework.core.convert.support.StringToBooleanConverter.convert(StringToBooleanConverter.java:32)
gio_apim_management_api | 	at org.springframework.core.convert.support.GenericConversionService$ConverterAdapter.convert(GenericConversionService.java:386)
gio_apim_management_api | 	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41)
gio_apim_management_api | 	... 131 common frames omitted
```

**Comment by zemiak** [comment]
Tried single quotes, double quotes, outer braces or not, curly braces or not :/

**Comment by gaetanmaisse** [comment]
Ok, thanks for the feedback we will look at it deeper and try to reproduce it

**Comment by zemiak** [comment]
Well, it is still valid

**Comment by phiz71** [comment]
Hello @zemiak
Did you fix your problem?
Have you tried with `{#jsonPath(#profile, '$.groups').contains('_appdev_shared')}`?
