### ISSUE TITLE
X-Forwarded-For header and ip filtering policy

### ISSUE THREAD

**Issue by grignix** [gravitee-io/issues#8978]
## Describe the bug

There is a problem in gravity when using the X-Forwarded-For header and ip filtering policy, Gravitee does not take into account from which address the connection was made if the X-Forwarded-For header was set

## To Reproduce

our ip is 192.168.50.11 address of our gravity gateway gw.gr.lab

make a request "curl [http://gw.gr.lab](http://gw.gr.lab)", the request passes (200) we prohibit in "ip filtering policy" our ip address 192.168.50.11 make a request "curl [http://gw.gr.lab](http://gw.gr.lab)", the request does not pass (403)

Now we set the X-Forwarded-For header and make a request from our ip 192.168.50.11 "curl --header "X-Forwarded-For: 8.8.8.8" [http://gw.gr.lab](http://gw.gr.lab)" request passes(200)

## Expected behaviour

Forbids our ip 192.168.50.11 from which we make the request and X-Forwarded-For ip

## Current behaviour

Gravitee does not take into account and does not prohibit the ip 192.168.50.11 from which the connection was made if the X-Forwarded-For header was set

## Environment

Gravitee 3.15.22, 3.20.2

**Comment by gaetanmaisse** [comment]
Hi @grignix, I wasn't able to reproduce the issue on our environments, can you export and share the API you're using? To be sure we've exactly the same config on the policy + endpoint side?

**Comment by grignix** [comment]
[q1-1-0(1).zip](https://github.com/gravitee-io/issues/files/11668454/q1-1-0.1.zip)

my ip = 192.168.50.11
how to use api

curl --header "X-Forwarded-For: 8.8.8.8" http://gw.gr.lab
ok
curl http://gw.gr.lab
{"message":"Your IP (192.168.50.11) or some proxies whereby your request pass through are not allowed to reach this resource.","http_status_code":403}

**Comment by grignix** [comment]
up
