### ISSUE TITLE
Connected user in portal get  "User[0] cannot be found" when clicking on an API in the catalogue

### ISSUE THREAD

**Issue by pascal-schetelat** [gravitee-io/issues#8997]
## Describe the bug

When a user that has created its account in the portal and has requested a subscription for an API, any attempt to see the API page will lead to an error page "User<span class="error">[0]</span> cannot be found"

In the browser network call, the api call is :

<pre>GET [https://XXX/portal/environments/DEFAULT/apis/](https://XXX/portal/environments/DEFAULT/apis/)([https://XXX/portal/environments/DEFAULT/apis/)([https://XXX/portal/environments/DEFAULT/apis/)([https://XXX/portal/environments/DEFAULT/apis/)([https://XXX/portal/environments/DEFAULT/apis/](https://XXX/portal/environments/DEFAULT/apis/](https://XXX/portal/environments/DEFAULT/apis/)([https://XXX/portal/environments/DEFAULT/apis/](https://XXX/portal/environments/DEFAULT/apis/](https://XXX/portal/environments/DEFAULT/apis/)([https://XXX/portal/environments/DEFAULT/apis/)([https://XXX/portal/environments/DEFAULT/apis/](https://XXX/portal/environments/DEFAULT/apis/](https://XXX/portal/environments/DEFAULT/apis/)([https://XXX/portal/environments/DEFAULT/apis/](https://XXX/portal/environments/DEFAULT/apis/](https://XXX/portal/environments/DEFAULT/apis/)([https://XXX/portal/environments/DEFAULT/apis/)([https://XXX/portal/environments/DEFAULT/apis/)([https://XXX/portal/environments/DEFAULT/apis/](https://XXX/portal/environments/DEFAULT/apis/](https://XXX/portal/environments/DEFAULT/apis/)([https://XXX/portal/environments/DEFAULT/apis/](https://XXX/portal/environments/DEFAULT/apis/](https://XXX/portal/environments/DEFAULT/apis/)([https://XXX/portal/environments/DEFAULT/apis/)([https://XXX/portal/environments/DEFAULT/apis/](https://XXX/portal/environments/DEFAULT/apis/](https://XXX/portal/environments/DEFAULT/apis/)([https://XXX/portal/environments/DEFAULT/apis/](https://XXX/portal/environments/DEFAULT/apis/)))))

 {api_id} 

/subscribers?statuses=ACCEPTED</pre>

<pre>{
 "errors" : [ {
 "status" : "404",
 "message" : "User <span class="error">[0]</span> can not be found.",
 "code" : "errors.user.notFound",
 "parameters" : 

 { "user" : "0" } 

 } ]
 }</pre>

## To Reproduce

Steps to reproduce the behaviour:

*   Create a user in the portal
*   Create an application
*   Requests a subscription for an API
*   While the requests in pending, go to catalogue > click on the API you requested
*   error page "User<span class="error">[0]</span> cannot be found"
*   When the request is validated, the issue disappears

Interesting enough, when using keycloak as an identity provider, the issue happen before:

*   Create a user in the portal using keycloak IdP
*   go to catalogue > click on any API
*   error page "User<span class="error">[0]</span> cannot be found"
*   the issue is resolved if you create an application that is successfully subscribed to that API. Other API will still crash.

## Expected behaviour

I expect my user to be able to view public API description and documentation I expect my user to be able to see the API description and documentation while waiting for the validation of their subscription

## Current behaviour

A clear and concise description of what is currently happening.

Connected user in portal get "User<span class="error">[0]</span> cannot be found" when viewing an API

## Useful information

[<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/4366344/230046259-43b1f26e-e703-409d-b5cb-d22c97be43d9.png)</span>](https://user-images.githubusercontent.com/4366344/230046259-43b1f26e-e703-409d-b5cb-d22c97be43d9.png)

Seems that the api call crash because of the url encoded parameter `subscribers?statuses=ACCEPTED`

Without status accepted, no issue.

This seems link to the display of subscribers statistics, which I could not find a way to disable [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/4366344/230050056-07ae12dc-05dc-473f-8e65-96ffef3cf999.png)</span>](https://user-images.githubusercontent.com/4366344/230050056-07ae12dc-05dc-473f-8e65-96ffef3cf999.png)

## Environment

 _**What is the impacted version?**_ 

here are the docker tag implied :

graviteeio/apim-portal-ui:3.18.12 graviteeio/apim-management-api:3.18.12 graviteeio/apim-management-ui:3.18.12 graviteeio/apim-gateway:3.18.12

We deploy those image on kubernetes v1.24.7 without helm (manually crafted manifest)

## Potential impacts

 _**Which other features may be impacted by this fix. This could be populated after fix**_ 

 _**What are the impacted versions?**_ 

## Dependencies

Link a story or other related things...

**Comment by pascal-schetelat** [comment]
The issue is pretty damaging considering it is client facing portal.

Is there any update on the issue ?

**Comment by phiz71** [comment]
Hello @pascal-schetelat, first I would like to apologize for the very late response.

Since May, we have made multiple fixes on the dev portal.
Have you had the opportunity to test with the latest supported version of APIM? (currently 3.20.25)

**Comment by pascal-schetelat** [comment]
Hi, thank you for your response.
We started testing gravitee 4.2 and the issue seems to still be there.

I created a new user in our api portal, clicked on subscribe and got this : 

![image](https://github.com/gravitee-io/issues/assets/4366344/fbb7aa87-91bc-4029-b9b6-361bb2e25f92)

You see for yourself here  https://api-portail.dev.bdnb.io
