### ISSUE TITLE
Unable to upgrade from 3.11.x further

### ISSUE THREAD

**Issue by zemiak** [gravitee-io/issues#9011]
## Describe the bug

Hello. We are trying to migrate from Gravitee 1.x to the latest 3.20.3\. We were able to go to 3.11 but not further. The problem is a liquibase DDL change script `liquibase/changelogs/v3_12_1/schema.yml`

## To Reproduce

Steps to reproduce the behaviour:

1.  Run Gravitee 1.x with some APIs and APPs (docker-compose)
2.  change the APIM_VERSION to 3.20
3.  See error

## Expected behaviour

Being able to upgrade to the latest 3.20.3

## Current behaviour

`liquibase/changelogs/v3_12_1/schema.yml` produces the following errors

### APIM

gio_apim_gateway | Caused by: liquibase.exception.MigrationFailedException: Migration failed for changeset liquibase/changelogs/v3_12_1/schema.yml::3.12.1::GraviteeSource Team: gio_apim_gateway | Reason: liquibase.exception.DatabaseException: ERROR: column "api" contains null values <span class="error">[Failed SQL: (0) ALTER TABLE api_gravitee.keys ALTER COLUMN api SET NOT NULL]</span>

### Database (PostgreSQL)

gio_apim_postgres | 2023-04-12 12:35:34.401 UTC <span class="error">[34]</span> ERROR: column "api" contains null values gio_apim_postgres | 2023-04-12 12:35:34.401 UTC <span class="error">[34]</span> STATEMENT: ALTER TABLE api_gravitee.keys ALTER COLUMN api SET NOT NULL

## Environment

1.x -> 3.11 -> 3.20.3

## Potential impacts

Not able to migrate to the latest version

Thanks for taking a look!

**Comment by gaetanmaisse** [comment]
Hey @zemiak, after upgrading to 3.11 can you check if you've rows in `api_gravitee.subscriptions` table with `api` equals to null? If so these are causing issue to apply the liquibase changelog for 3.12.1 so you need to review them and discard them if they looks weird or unused

**Comment by zemiak** [comment]
Hello @gaetanmaisse 

```
select count(*) from api_gravitee.subscriptions where api is null;
```
--> 0

can I somehow get to the liquibase scripts on Github?

Thanks

**Comment by zemiak** [comment]
@gaetanmaisse 

Hello, nope. We are stuck on 1.x, because it has no sense to upgrade to 3.x and not be able to reach to the latest version afterwards

**Comment by gaetanmaisse** [comment]
@zemiak can you try to: 
 - Update to 3.11
 - Manually execute the SQL script that would be executed by APIM: 
```sql
-- Please replace `${gravitee_prefix}` with the prefix you're using.

-- Create `id` column on the `keys` table, nvarchar(64)
ALTER TABLE ${gravitee_prefix}keys ADD id VARCHAR(64);

-- Fill the `id` column with the `key` value
UPDATE ${gravitee_prefix}keys SET id = key;

-- Add a not null constraint on the `id` column
ALTER TABLE ${gravitee_prefix}keys ALTER COLUMN id SET NOT NULL;

-- Drop current primary key
ALTER TABLE ${gravitee_prefix}keys DROP CONSTRAINT pk_${gravitee_prefix}keys;

-- Add a new primary key on the `id` column
ALTER TABLE ${gravitee_prefix}keys ADD CONSTRAINT pk_${gravitee_prefix}keys PRIMARY KEY (id);

-- Add an `api` column on the `keys` table, nvarchar(64)
ALTER TABLE ${gravitee_prefix}keys ADD api VARCHAR(64);

-- Fill the `api` column with the `api` value of the matching subscription
UPDATE ${gravitee_prefix}keys SET api = ( SELECT s.api FROM ${gravitee_prefix}subscriptions s WHERE s.id = subscription)

-- ⚠️ THERE SHOULDN'T BE ANY NULL VALUE IN THE `api` COLUMN ⚠️
SELECT * FROM ${gravitee_prefix}keys WHERE api IS NULL;
-- ⚠️ OR THE FASTEST WAY ⬇️ ⚠️
DELETE FROM ${gravitee_prefix}keys WHERE api IS NULL;
-- ⚠️

-- Add a not null constraint on the `api` column
ALTER TABLE ${gravitee_prefix}keys ALTER COLUMN api SET NOT NULL;

-- Create indexes
-- With key column
CREATE INDEX idx_${gravitee_prefix}keys_key ON ${gravitee_prefix}keys (key);
-- With api and key columns
CREATE INDEX idx_${gravitee_prefix}keys_key_and_api ON ${gravitee_prefix}keys (api, key);
```
 - Try to update to 3.20

Doing so you should be able to see the keys with null api and remove them, and liquibase will skip the db update related to 3.12.1 as you will have manually applied it.

**Comment by gaetanmaisse** [comment]
I'm closing the issue as it didn't get any attention lately. Feel free to reopen it if needed!

**Comment by zemiak** [comment]
Late, but better than never: before upgrade, I did run this SQL query:

```sql
DELETE FROM api_gravitee.keys WHERE ( SELECT s.api FROM api_gravitee.subscriptions s WHERE s.id = subscription) is null;
```

Indeed, there were 4 keys with a non-existing subscriptions. Now I was able to go up to 4.0.8.

Thanks for your help @gaetanmaisse !
