### ISSUE TITLE
Unable to show API's created in APIM 3.20.4 in firefox 112.0

### ISSUE THREAD

**Issue by oyviaase** [gravitee-io/issues#9024]
## Describe the bug

We can't see any of the API created on this version, older API are still visible

## To Reproduce

1.  Create an API in any browser
2.  Click on API tab in a firefox browser
3.  See error

## Expected behaviour

As an admin user should I be able to see all the APIs that exists in this gravitee version. Any API owner or user should be able to see their APIs

## Current behaviour

In Firefox am I unable to find any APIs created with the affected version. In vivaldi am I only able to see the APIs created in Firefox, not the one I created in Vivaldi

## Useful information

Screenshoot taken before creating a 3rd API in Vivaldi [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/9009359/232794414-e326b5bc-8626-42c8-ae06-08e53df00d3b.png)</span>](https://user-images.githubusercontent.com/9009359/232794414-e326b5bc-8626-42c8-ae06-08e53df00d3b.png)

## Environment

APIM 3.20.4 Firefox: 112 on fedora 37 Vivaldi: 5.8.2955.3

## Potential impacts

 _**Which other features may be impacted by this fix. This could be populated after fix**_ 

 _**What are the impacted versions?**_ At least version 3.20.4, this might be an related issue reporting it for 3.20 [https://github.com/gravitee-io/issues/issues/8891](https://github.com/gravitee-io/issues/issues/8891)

## Dependencies

Link a story or other related things...

**Comment by gaetanmaisse** [comment]
@oyviaase are you still facing this issue with the latest 3.20? On our side we've devs working with Firefox on a daily basis and no one never noticed such behavior

**Comment by oyviaase** [comment]
Haven't tested in a while, however some more testing after I had reported this issue makes me suspect that it is https://github.com/gravitee-io/issues/issues/9026 that's causing the problems I've had in Firefox, and the chromium based vivaldi browser. So this issue can probably be closed.

**Comment by gaetanmaisse** [comment]
Thanks for the feedback @oyviaase, we've identified that having an issue in sending a mail to notify an API creation is putting it in a weird state; we will investigate and find a better way to handle that. Closing the issue for now but feels free to reopen it.
