### ISSUE TITLE
[Task] 

### ISSUE THREAD

**Issue by BharathAlli** [gravitee-io/issues#9056]
### </g-emoji> Parent Issue

[https://github.com/gravitee-io/issues/issues/

 {number} 

| [https://github.com/gravitee-io/issues/issues/%7Bnumber%7D](https://github.com/gravitee-io/issues/issues/%7Bnumber%7D)]

### </g-emoji> Description

unable to dowunload these .env and ngnix.conf

mkdir -p config curl -L [https://gh.gravitee.io/gravitee-io/graviteeio-access-management/master/docker/compose/docker-compose.yml](https://gh.gravitee.io/gravitee-io/graviteeio-access-management/master/docker/compose/docker-compose.yml) -o "docker-compose.yml" curl -L [https://gh.gravitee.io/gravitee-io/graviteeio-access-management/master/docker/compose/.env](https://gh.gravitee.io/gravitee-io/graviteeio-access-management/master/docker/compose/.env) -o ".env" cd config && 

 { curl -L [https://gh.gravitee.io/gravitee-io/graviteeio-access-management/master/docker/compose/config/nginx.conf| https://gh.gravitee.io/gravitee-io/graviteeio-access-management/master/docker/compose/config/nginx.conf] -o "nginx.conf" ; cd -; } 

### </g-emoji> Technical Details

this is error message:

unexpected character "{" in variable name

### </g-emoji> Additional Information

 _No response_

**Comment by BharathAlli** [comment]
Any update?

**Comment by jampack** [comment]
@BharathAlli they made the AM git repo private for some reason that they didn't disclose and now the documentation with links referring to that repo are broken. No news from them and no idea how long it will take to come back up as its already a 5 days old issue.

**Comment by jampack** [comment]
BTW .env is simple it has 2 variables just for changing ports.

**Comment by BharathAlli** [comment]
@jampack any idea of this issue https://github.com/gravitee-io/issues/issues/9060 ?
