### ISSUE TITLE
[helm chart] apim3 - duplicate field annotations in deployment

### ISSUE THREAD

**Issue by vliska** [gravitee-io/issues#9082]
## Describe the bug

Can't install 3.2.0 helmrelease of apim3 in fluxcd (or any tool that actually validates the helm chart/rendered manifests prior installation) due to:

 Helm upgrade failed: error while running post render on files: map<span class="error"><span class="error">[string]</span></span>interface {}(nil): yaml: unmarshal errors:
 line 36: mapping key "annotations" already defined at line 28

it's due to duplicate annotations section in ui-deployment.yaml: [https://github.com/gravitee-io/helm-charts/blob/master/apim/3.x/templates/ui/ui-deployment.yaml#L55](https://github.com/gravitee-io/helm-charts/blob/master/apim/3.x/templates/ui/ui-deployment.yaml#L55) [https://github.com/gravitee-io/helm-charts/blob/master/apim/3.x/templates/ui/ui-deployment.yaml#L82](https://github.com/gravitee-io/helm-charts/blob/master/apim/3.x/templates/ui/ui-deployment.yaml#L82)

Whole section with common annotations is present twice (probably copy+paste error).

## To Reproduce

Try to install apim3 via e.g. flux or

## Current behaviour

Can't install apim3 version 3.2.0 via helm chart.

## Environment

helm 3.x fluxcd 2.0.0-rc.5

 _**What is the impacted version?**_ 

3.2.0

## Potential impacts

Can't install gravitee apim3.

**Comment by gaetanmaisse** [comment]
Thanks for the PR @vliska, we are currently moving the APIM Helm Charts into the `api-management` repository (that will be public again in the next couple of weeks), so merging your PR might take some extra time. In any case, we will take care of it by the end of next week!
