### ISSUE TITLE
Dynamic routing from flow to flow is not working as expected starting from 3.18.22

### ISSUE THREAD

**Issue by Mattue** [gravitee-io/issues#9092]
## Describe the bug

It's not clear how to route from flow to flow within one API when changing incoming request URI

## To Reproduce

1.  Run Gravitee version `3.18.22` or above
2.  Go to [webhook.site](https://webhook.site) and copy `Your unique URL`
3.  In attached API definition change `<webhook.url>` to your [webhook.site](https://webhook.site) unique URL (2 places: `url`, `target`)
4.  In Gravitee version `3.18.22` or above import attached API definition and start API
5.  Make request to this API to following URL `GET http://<gateway.host>/test/xxx/yyy`
6.  See that [webhook.site](https://webhook.site) got only 1 request

## Expected behavior

As its working in versions between `3.18.18` and `3.18.21` [webhook.site](https://webhook.site) will receive 2 requests. One from default gateway behavior (defined in `API->Proxy->Endpoints`) and one from `HTTP Callout` policy in `/:object` flow.

## Current behavior

Starting from Gravitee versions `3.18.22`, flow `/:object` is not executed.

## Useful information

I have service that can send requests in form `/xxx/yyy` where `xxx` is mandatory for this service. And we can't change that. Let's say it's external data vendor. I have back-end that can receive requests in form `/:object`. I know that `/:object` may be used by several consumers. And it makes scene to create `/:object` flow to make universal data transformation (for example add custom header)

**Taking all above.**

 _In version 3.18.18_ 

I have created plan specifically for this vendor with flow `starts with /xxx`. In that flow, using `dynamic routing` policy I'm changing url from `/xxx/yyy` to `/yyy` (from `/xxx/(.*)` to `/

 {#group[0]}`). And this was working as expected. When I receive `/xxx/yyy`request, both`starts with /xxx`and`:/object` flows are executing.

 _When updated to 3.18.22 and above_ 

 Only one flow `starts with /xxx` is working and I have no idea how to correctly invoke `/:object` flow.

 h2\. Addition

 Maybe this was not expected behavior from the beginning. In that case, can you please advice how to handle requests in form `/xxx/yyy` with removing `xxx` (like header or body change).

 h2\. Environment

 _**What is the impacted version?**_ 

 3.18.22 and above

 h2\. Potential impacts

 I know that there was URL parsing change in `3.18.25`, `3.19.14`, `3.20.9` - [8921](https://github.com/gravitee-io/issues/issues/8921)

 h2\. Attachment

 <pre>{

 "name": "test",

 "crossId": "12e2be9c-39e5-4eda-a2be-9c39e5deda9f",

 "version": "1",

 "execution_mode": "v3",

 "description": "test",

 "visibility": "PRIVATE",

 "flows": [

 {

 "id": "4a213116-54b5-4c96-a131-1654b54c96ba",

 "name": "",

 "path-operator": { "path": "/:object", "operator": "EQUALS" },

 "condition": "",

 "consumers": [],

 "methods": [],

 "pre": [

 {

 "name": "HTTP Callout",

 "description": "",

 "enabled": true,

 "policy": "policy-http-callout",

 "configuration": {

 "method": "GET",

 "fireAndForget": false,

 "scope": "REQUEST",

 "errorStatusCode": "500",

 "errorCondition": "{#calloutResponse.status >= 400 and #calloutResponse.status <= 599}",

 "url": "

 ",

 "exitOnError": false

 }

 }

 ],

 "post": [],

 "enabled": true

 }

 ],

 "gravitee": "2.0.0",

 "flow_mode": "BEST_MATCH",

 "resources": [],

 "properties": [],

 "plans": [

 {

 "id": "41eaa442-6b30-4987-aaa4-426b30c98727",

 "crossId": "a6ddbfa5-f317-4f33-9dbf-a5f317bf33fa",

 "name": "public",

 "description": "public",

 "validation": "AUTO",

 "security": "KEY_LESS",

 "type": "API",

 "status": "PUBLISHED",

 "api": "8040b1a4-73ab-4918-80b1-a473ab391858",

 "order": 1,

 "characteristics": [],

 "tags": [],

 "paths": {},

 "flows": [

 {

 "id": "c323caea-1563-4c21-a3ca-ea1563fc2178",

 "name": "",

 "path-operator": { "path": "/xxx/", "operator": "STARTS_WITH" },

 "condition": "",

 "consumers": [],

 "methods": [],

 "pre": [

 {

 "name": "Dynamic Routing",

 "description": "",

 "enabled": true,

 "policy": "dynamic-routing",

 "configuration": {

 "rules": [

 {

 "pattern": "/xxx/(.*)",

 "url": "/{#group[0]} 

"
 }
 ]
 }
 }
 ],
 "post": [],
 "enabled": true
 }
 ],
 "excluded_groups": [],
 "comment_required": false
 }
 ],
 "id": "8040b1a4-73ab-4918-80b1-a473ab391858",
 "path_mappings": [],
 "proxy": {
 "virtual_hosts": [

 { "path": "/test" } 

 ],
 "strip_context_path": false,
 "preserve_host": false,
 "groups": [
 {
 "name": "default-group",
 "endpoints": [

 { "backup": false, "inherit": true, "name": "default", "weight": 1, "type": "http", "target": " " } 

 ],
 "load_balancing": 

 { "type": "ROUND_ROBIN" } 

,
 "http": 

 { "connectTimeout": 5000, "idleTimeout": 60000, "keepAlive": true, "readTimeout": 10000, "pipelining": false, "maxConcurrentConnections": 100, "useCompression": true, "followRedirects": false } 

 }
 ]
 },
 "response_templates": {}
 }

 </pre>

**Comment by SidoDenis** [comment]
+1, routing is not working in our project as well

**Comment by burdakin** [comment]
+++
Having same troubles with Dynamic Routing policy

**Comment by phiz71** [comment]
Hello @Mattue, firstly I would like to apologize for this very late answer.

I can see in your API definition that the flow in your plan is configured to be executed when the path **Starts with** `/xxx/` and the the other flow is configured to be executed when the path **Equals** `/:object`

So when you call your API with `/test/xxx/yyy`, only the first flow will be executed because the path `/xxx/yyy` starts with `/xxx`. Whereas the second flow will not be executed, the path is not equals to `/:object`

Actually in 3.18.22, we have fixed this issue: https://github.com/gravitee-io/issues/issues/8945 that could explain why your case was working before

I would recommend for your API to either configure the second flow with **Starts with** or to change the path to `/:object/:object2` or `/:object/yyy`

Hope it helps.

**Comment by Mattue** [comment]
@phiz71 thank you for your reply!

We have experimented a while to understand working approach and found forking solution!
And yes it's was setting correct flow configuration.
