### ISSUE TITLE
Environment variables not applied on apim-gateway

### ISSUE THREAD

**Issue by fadas-sk** [gravitee-io/issues#9094]
## Describe the bug

Environment variables not applied on apim-gateway with docker compose

## To Reproduce

Installing APIM Download the docker-compose.yml file as docker-compose-apim.yml. `curl ~~L [https://bit.ly/docker-apim-3x](https://bit.ly/docker-apim-3x) -o docker-compose-apim.yml` Edit docker-compose-apim.yml Add the following line to $services.gateway.environment. `~~ gravitee.http.websocket.enabled=true` Run docker compose to download and start all of the components docker compose -f docker-compose-apim.yml up -d

## Expected behaviour

the file /opt/graviteeio-gateway/config/gravitee.yml must contain my configuration gravitee>http>websocket>enabled=true

## Current behaviour

the file /opt/graviteeio-gateway/config/gravitee.yml stay contain my configuration gravitee>http>websocket>enabled=false and remain commented

## Useful information

I tried doing this in a clear environment and the result is the same

## Environment

graviteeio-apim-gateway-3.20.0

**Comment by gaetanmaisse** [comment]
@fadas-sk you can use environment variables to configure the APIM Gateway & Management API, they will be loaded by the components during the startup but will not be updated in the `gravitee.yml`.

You can get more info about that at: https://docs.gravitee.io/pages/apim/3.x/installation-guide/partial/how-to-configure.html
The most interesting part: 
> There are three different ways to configure this component:
> - environment variables
> - system properties
> - gravitee.yml
>
> The order in which they are listed above corresponds to their order of precedence. In other words, environment variables override the other two configuration types, and system properties override gravitee.yml.

**Comment by fadas-sk** [comment]
I confirm the variables are indeed effective. My problem is that I did not deploy any plans and without plans no pase request, thank you for your help
