### ISSUE TITLE
Assign content policy not working

### ISSUE THREAD

**Issue by syafifira** [gravitee-io/issues#9106]
my API called Branch has several fields in the body. ie: brnName,brnCd,add1\. So, I want provide certain fields only for different user. Let say, if user A called the branch API, I want t provide all fields, but I want to restrict to user B. I want to provide brnName only

This is my json body

[ 

 { "addr1": "string", "addr2": "string", "addr3": "string", "addr4": "string", "addr5": "string", "bnkConcept": "BOTH", "brnAbbrevCd": "string", "brnLvl": "string", "brnName": "string", "cityCd": "string", "cntryCd": "string", "districtCd": "string", "manager": "string", "parentBrn": "string", "postCd": "string", "regCd": "string", "stateCd": "string", "telno": "string", "brnCd": "string" } 

 ]

This is my Gravitee APIM console:

[<span class="image-wrap" style="">![](https://github.com/gravitee-io/issues/assets/137779929/f3bb7ee3-a1b0-456b-ad1e-7953457be376)</span>](https://github.com/gravitee-io/issues/assets/137779929/f3bb7ee3-a1b0-456b-ad1e-7953457be376)

and this is the result in Postman

[<span class="image-wrap" style="">![](https://github.com/gravitee-io/issues/assets/137779929/5475ee05-413d-4173-812a-33607334bb2c)</span>](https://github.com/gravitee-io/issues/assets/137779929/5475ee05-413d-4173-812a-33607334bb2c)

currently I am using version 3.20.12

**Comment by gaetanmaisse** [comment]
I think the issue is because the response from your endpoint is an array, so `body.brnCd` isn't a valid value here
