### ISSUE TITLE
Groovy FAILURE: Unable to run Groovy script: No such property: FAILURE

### ISSUE THREAD

**Issue by vdusauto** [gravitee-io/issues#912]
The example provided in the doc doesn't work.

### Expected Behavior

FAILURE should be a known value, authorizing to exit code before the end with a different HTTP status code.

### Current Behavior

Policy crashed, returning a HTTP 500

### Steps to Reproduce (for bugs)
Create a policy with example from documentation:

if (request.headers.containsKey('X-Gravitee-Break')) {
    result.state = FAILURE
    result.code = 500
    result.error = 'Stop request processing due to X-Gravitee-Break header'
} else {
    request.headers.'X-Groovy-Policy' = 'ok'
}

### Context

Exiting script if JSON content is incorrect.

### Your Environment

* Version used: 1.11.4
* Browser Name and version: Chrome last version
* Operating System and version: Linux

**Comment by aelamrani** [comment]
You should add the import and use it on this way:
```
import io.gravitee.policy.groovy.PolicyResult.State
...
result.state = State.FAILURE;
```
