### ISSUE TITLE
Binary data gets mangled when using URL rewriting or assign content policy

### ISSUE THREAD

**Issue by pcgaustad** [gravitee-io/issues#9132]
## Describe the bug

[describe-the-bug](#describe-the-bug)

[describe-the-bug](#describe-the-bug)

[describe-the-bug](#describe-the-bug)

Binary data gets mangled when using a URL rewriting or assign content policy. This goes for whatever data the policy applies to, whether it is in the request or response. In this report I describe the bug for a response with a URL rewriting policy.

## To Reproduce

[to-reproduce](#to-reproduce)

[to-reproduce](#to-reproduce)

[to-reproduce](#to-reproduce)

1.  Create a new API with a minimal plan and a backend that can respond with binary data. Do not apply any policies.

1.  Send a request which will make the backend return some predefined binary data. In my case `\x00\x00\x00\x00\xff\xff\xff\xff`

1.  Save the binary data somehow, e.g. with `curl --output test.bin "https://example.com"`

1.  Compare the binary data in the response with the predefined data, e.g. with hexdump, and observe that it equals the predefined data.

1.  Apply a URL rewrite policy for header and body, as simple as it gets, as in the image below.

[<span class="image-wrap" style="">![](https://github.com/gravitee-io/issues/assets/85640936/4cd0483d-117f-4be3-a554-08242805ce99)</span>](https://github.com/gravitee-io/issues/assets/85640936/4cd0483d-117f-4be3-a554-08242805ce99)

1.  Repeat step 2 and 3.

## Expected behaviour

[expected-behaviour](#expected-behaviour)

[expected-behaviour](#expected-behaviour)

[expected-behaviour](#expected-behaviour)

The binary data in the response equals the predefined binary data, that is `\x00\x00\x00\x00\xff\xff\xff\xff`.

## Current behaviour

[current-behaviour](#current-behaviour)

[current-behaviour](#current-behaviour)

[current-behaviour](#current-behaviour)

The binary data in the response is `\x00\x00\x00\x00\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd`. The `\xff` get turned into 'REPLACEMENT CHARACTER' (U+FFFD).

## Useful information

[useful-information](#useful-information)

[useful-information](#useful-information)

[useful-information](#useful-information)

I have also verified that binary data don't get mangled when the client communicates directly with the endoint.

I have not observed any problems with data in utf-8 encoding.

I have only been able to do tests with a SOAP API. As the HTTP headers seem pretty standard I assume the bug is unrelated to the protocol.

cURL verbose output:

< HTTP/2 200 < cache-control: private < content-type: multipart/related; type="application/xop+xml";start="<[http://tempuri.org/0](http://tempuri.org/0)>"; boundary="uuid:807159d0-9955-43f4-9c6a-2e83d5d5a3ec+id=486";start-info="text/xml" < date: Tue, 11 Jul 2023 11:09:13 GMT < mime-version: 1.0 < server: Microsoft-IIS < set-cookie: ASP.NET_SessionId=s3g1xlx1czihcxjochdqujxi; path=/; HttpOnly; SameSite=Lax; Sec ure < x-gravitee-request-id: 8ce96063-3290-4767-a960-633290c76764 < x-gravitee-transaction-id: 8ce96063-3290-4767-a960-633290c76764 < x-content-type-options: nosniff

Response data:

Content-ID: <[http://tempuri.org/0](http://tempuri.org/0)> Content-Transfer-Encoding: 8bit Content-Type: application/xop+xml;charset=utf-8;type="text/xml"

<s:Envelope xmlns:s="[http://schemas.xmlsoap.org/soap/envelope/">](http://schemas.xmlsoap.org/soap/envelope/%22%3E)<s:Header><h:ContentType xmlns:h="[http://www.gecko.no/ephorte/services/documents/v3"/>](http://www.gecko.no/ephorte/services/documents/v3%22/%3E)<h:FileName xmlns:h="[http://www.gecko.no/ephorte/services/documents/v3">\example\test.bin](http://www.gecko.no/ephorte/services/documents/v3%22%3E%5C%5Cexample%5Ctest.bin)</h:FileName></s:Header><s:Body><xop:Include href="cid:[http://tempuri.org/1/638246777541059478](http://tempuri.org/1/638246777541059478)" xmlns:xop="[http://www.w3.org/2004/08/xop/include"/>](http://www.w3.org/2004/08/xop/include%22/%3E)</s:Body></s:Envelope>

Content-ID: <[http://tempuri.org/1/638246777541059478](http://tempuri.org/1/638246777541059478)> Content-Transfer-Encoding: binary Content-Type: application/octet-stream

<span class="error">[binary data]</span>

## Environment

[environment](#environment)

[environment](#environment)

[environment](#environment)

APIM 3.15.21 (due to #9026)

**Comment by glorytiger** [comment]
This bug happens here as well for APIM 3.15.21

Created a API with URL Rewriting policy and a echo backend.

With URL Rewriting enabled:

```
printf '\x00\x00\x00\x00\xff\xff\xff\xff' | curl -H "Content-Type:application/octet-stream" --data-binary @- https://<URL_TO_API> --output a.bin
hexdump -C a.bin
00000000  00 00 00 00 ef bf bd ef  bf bd ef bf bd ef bf bd  |................|
00000010
```

With URL Rewriting disabled:

```
printf '\x00\x00\x00\x00\xff\xff\xff\xff' | curl -H "Content-Type:application/octet-stream" --data-binary @- https://<URL_TO_API> --output b.bin
hexdump -C b.bin
00000000  00 00 00 00 ff ff ff ff                           |........|
00000008
```

**Comment by phiz71** [comment]
Hello @pcgaustad and @glorytiger, first I would like to apologize for this late answer.

The purpose of the URL rewriting policy is to replace URL strings in headers or in the body by an other URL. Since this replacement mechanism relies on regex, the policy assumes that the body content is a string and does not expect binary content.

If you just want to replace URLs in headers, you can unselect `Rewrite HTTP response body` option in the policy configuration.

**Comment by glorytiger** [comment]
Hi @phiz71 and thank you for the response.

I see that we didn't mention that this applies also if the `Rewrite HTTP response body` is turned off.

```
printf '\x00\x00\x00\x00\xff\xff\xff\xff' | curl -H "Content-Type:application/octet-stream" --data-binary @- https://gw-qa.intark.uh-it.no/cn-test/url-rewrite-binary --output a.bin && hexdump -C a.bin
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    24    0    16  100     8     92     46 --:--:-- --:--:-- --:--:--   139
00000000  00 00 00 00 ef bf bd ef  bf bd ef bf bd ef bf bd  |................|
00000010
```

![A](https://github.com/gravitee-io/issues/assets/56641017/95208e70-6d2d-437f-957f-e4f21529f762)

**Comment by phiz71** [comment]
Hi,
could you remind me the version of APIM you are using ?
Have you tested with the latest versions available ?
Latest 3.x is 3.20.32
Latest 4.x is 4.3.1
