### ISSUE TITLE
OutOfMemoryError in the gateway logs with API advanced logging mode

### ISSUE THREAD

**Issue by keepeek-rd** [gravitee-io/issues#9174]
## Describe the bug

I get an "OutOfMemoryError" in the gateway logs when I activate the advanced logging for API.

## To Reproduce

Steps to reproduce the behaviour:

1.  Go to "APIs"
2.  Click on "Logs"
3.  Click on "Configure the logging"
4.  Enabled with client & proxy + headers & payloads + request & response + without condition
5.  Wait for lot's of requests
6.  See error in gateway logs relating an OutOfMemory

`

## Expected behaviour

I would like to be able to leave the advanced logging enabled without having outofmemory.

## Current behaviour

The gateway works incorrectly and nothing goes up in the gravity GUI

## Useful information

OutOfMemory stacktrace `11:03:00.001 <span class="error"><span class="error">[vert.x-eventloop-thread-3]</span></span> [] ERROR i.g.g.s.h.rule.EndpointRuleHandler - An error has occurred during Hea$ io.vertx.core.http.impl.NoStackTraceTimeoutException: The timeout period of 29998ms has been exceeded while executing G$ 11:14:13.414 <span class="error"><span class="error">[vert.x-eventloop-thread-3]</span></span> [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception java.lang.OutOfMemoryError: Java heap space at java.base/java.util.Arrays.copyOf(Unknown Source) at java.base/java.lang.String.<init>(Unknown Source) at io.netty.buffer.ByteBufUtil.decodeString(ByteBufUtil.java:1276) at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:1246) at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:1241) at io.netty.buffer.WrappedByteBuf.toString(WrappedByteBuf.java:967) at io.gravitee.gateway.buffer.netty.BufferImpl.toString(BufferImpl.java:99) at io.gravitee.gateway.core.logging.LoggableClientRequest.lambda$endHandler$1(LoggableClientRequest.java:80) at io.gravitee.gateway.core.logging.LoggableClientRequest$$Lambda$1090/0x0000000801456228.handle(Unknown Source) at io.gravitee.gateway.core.logging.LoggableClientRequest.lambda$endHandler$1(LoggableClientRequest.java:83) at io.gravitee.gateway.core.logging.LoggableClientRequest$$Lambda$1090/0x0000000801456228.handle(Unknown Source) at io.gravitee.gateway.http.vertx.VertxHttpServerRequest$$Lambda$1091/0x0000000801456450.handle(Unknown Source) at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63) at io.vertx.core.http.impl.HttpEventHandler.handleEnd(HttpEventHandler.java:76) at io.vertx.core.http.impl.Http1xServerRequest.onEnd(Http1xServerRequest.java:561) at io.vertx.core.http.impl.Http1xServerRequest.lambda$pendingQueue$1(Http1xServerRequest.java:126) at io.vertx.core.http.impl.Http1xServerRequest$$Lambda$1044/0x000000080142b000.handle(Unknown Source) at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240) at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:130) at io.vertx.core.http.impl.Http1xServerRequest.handleEnd(Http1xServerRequest.java:542) at io.vertx.core.http.impl.Http1xServerConnection$$Lambda$466/0x00000008010964c8.handle(Unknown Source) at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:71) at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:163) at io.vertx.core.http.impl.Http1xServerConnection.onEnd(Http1xServerConnection.java:191) at io.vertx.core.http.impl.Http1xServerConnection.onContent(Http1xServerConnection.java:181) at io.vertx.core.http.impl.Http1xServerConnection.handleOther(Http1xServerConnection.java:161) at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:149) at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:155) at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)`

If I disable advanced logging mode, I do not have OutOfMemory.

## Environment

*   APIM 3.20.14
*   Docker
*   Xmx/Xms=256mo

**Comment by gaetanmaisse** [comment]
@keepeek-rd logging can significantly impact performance and memory usage, and I guess you're hitting the limit of your GW instance by activating all the logging options. Here are a couple of things you can do to avoid the OOM: 
 - Review the logging configuration and maybe uncheck some settings: client & proxy + headers & payloads + request & response -> If payloads are huge, logging them has a big impact
 - Add a condition to "sample" the requests and get full logs but only for some of them
 - Increase the memory limit of Gateway to allow it to handle the load

**Comment by keepeek-rd** [comment]
I indicated this ticket as being a BUG because I find it strange that after a while it goes outofmemory (as if there was a memory leak). If it was just a one-time memory problem, I would get this OOM quickly out of it after several days?
When you activate logging, once it's saved in ES, isn't the memory cleared?
