### ISSUE TITLE
Invalid form parameter when ResponseMode is set to form_post 

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#9179]
## [Describe the bug](#describe-the-bug)

When an authorization code flow is executed with the reponse_mode set to form_post, the HTML form generated by AM may note contains the reponse parameters (code, state...) according to the response_type.

## [To Reproduce](#to-reproduce)

Steps to reproduce the behaviour:

1.  Create a domain and an app with active users
2.  Initiate hybrid flow by using `response_type=code id_token token` for example and add the `response_mode=form_post&nonce=546897`
3.  authenticate the user
4.  the callback URL is called without parameter

## [Expected behaviour](#expected-behaviour)

the callback URL is called with parameter code, id_token...

## [Current behaviour](#current-behaviour)

the callback URL is called without parameter because by default hybrid flow will generate parameter as fragment. As consequence the `login_sso_post` template can't fill the hidden form fields before submitting the form.

## [Useful information](#useful-information)

*   [https://openid.net/specs/oauth-v2-form-post-response-mode-1_0.html](https://openid.net/specs/oauth-v2-form-post-response-mode-1_0.html)
*   [https://openid.net/specs/openid-connect-core-1_0.html#HybridFlowAuth](https://openid.net/specs/openid-connect-core-1_0.html#HybridFlowAuth)

## [Environment](#environment)

3.19

**Comment by remiwuillemin** [comment]
Hello @leleueri , it seems that I encounter the same issue. 
Have you, by chance, found a workaround ?
Rémi
