### ISSUE TITLE
[APIM] Categories with chinese name can't be asigned to any API.

### ISSUE THREAD

**Issue by zzuzdm** [gravitee-io/issues#9188]
## Describe the bug

Categories with chinese name can't be assigned to any API.

## To Reproduce

Steps to reproduce the behaviour:

1.  Create a category with chinese name

## Expected behaviour

The category can be assigned to any api.

## Current behaviour

The `key` will be empty. The category can't be assigned to any api.

## Useful information

[<span class="image-wrap" style="">![](https://github.com/gravitee-io/issues/assets/7220588/9a489c1f-a365-4723-a171-90eee33c604d)</span>](https://github.com/gravitee-io/issues/assets/7220588/9a489c1f-a365-4723-a171-90eee33c604d) [<span class="image-wrap" style="">![](https://github.com/gravitee-io/issues/assets/7220588/999f7839-729f-4095-a418-04f985085be6)</span>](https://github.com/gravitee-io/issues/assets/7220588/999f7839-729f-4095-a418-04f985085be6)

## Environment

APIM 4.0.3 mongodb 6.0.8

**Comment by songlai** [comment]
Query { "$java" : Query: { "environmentId" : "DEFAULT", "key" : ""}, Fields: {}, Sort: {} } returned non unique result.

应该是了

**Comment by songlai** [comment]
我怀疑 Organization settings -> Sharding Tags 添加的时候一样有这样的问题。

`Write operation error on server mongodb:27017. Write error: WriteError{code=11000, message='E11000 duplicate key error collection: gravitee.tags index: _id_ dup key: { _id: "" }', details={}}.; nested exception is com.mongodb.MongoWriteException: Write operation error on server mongodb:27017. Write error: WriteError{code=11000, message='E11000 duplicate key error collection: gravitee.tags index: _id_ dup key: { _id: "" }', details={}}.`
