### ISSUE TITLE
Cannot import SOAP API's with xsd imports

### ISSUE THREAD

**Issue by ezci** [gravitee-io/issues#9199]
## Describe the bug

SOAP API's with xsd import links can't be imported since XML options used in SoapMessageBuilder is not enabled for downloads.

## To Reproduce

Steps to reproduce the behaviour:

1.  Open Create API dialog.
2.  Click on "Upload API" tab.
3.  Upload the attached wsdl file (uploaded as txt due to github policy, extension needs to be changed back to wsdl) [TelephoneWebServic.txt](https://github.com/gravitee-io/issues/files/12417446/service-references_TelephoneWebService_wsdl_localhost_8080_TelephoneWebService_TelephoneWebServic.txt)
4.  Click on Import button [<span class="image-wrap" style="">![](https://github.com/gravitee-io/issues/assets/4889289/ab8840da-0e56-4c2d-a84e-93098332bac1)</span>](https://github.com/gravitee-io/issues/assets/4889289/ab8840da-0e56-4c2d-a84e-93098332bac1)
5.  See error on right bottom as "Bad Format";

## Expected behaviour

Should be able to upload API's with xsd imports.

## Current behaviour

Error thrown.

## Useful information

**Comment by gaetanmaisse** [comment]
Closing, see for details https://github.com/gravitee-io/gravitee-api-management/pull/5047#issuecomment-1710070108
