### ISSUE TITLE
[APIM] Improve code block visibility on documentation pages in the developer portal

### ISSUE THREAD

**Issue by sjanssens1977** [gravitee-io/issues#9210]
## Describe the bug

[describe-the-bug](#describe-the-bug)

Code blocks are not displayed very clearly in the developer portal.

Notice the difference in rendering between the console markdown documentation WYSIWYG editor and the develop portal.

[<span class="image-wrap" style="">![](https://github.com/gravitee-io/issues/assets/20815334/0ecd5db0-76b5-497a-9b05-9178d8d79125)</span>](https://github.com/gravitee-io/issues/assets/20815334/0ecd5db0-76b5-497a-9b05-9178d8d79125)

[<span class="image-wrap" style="">![](https://github.com/gravitee-io/issues/assets/20815334/7fc4212d-7cc2-4401-9937-bd7f00c2087c)</span>](https://github.com/gravitee-io/issues/assets/20815334/7fc4212d-7cc2-4401-9937-bd7f00c2087c)

Using AsciiDoc type instead of Markdown makes no difference since code blocks in AsciiDoc type documentation pages are rendered in the same way as the markdown versions.

Is there a way to improve the rendering to make code blocks stand-out more (like the WYSIWYG render) in the developer portal?

## To Reproduce

[to-reproduce](#to-reproduce)

Create a Markdown type documentation page that contains a code block and publish is on the developer portal.

## Expected behaviour

[expected-behaviour](#expected-behaviour)

The code blocks in documentation pages should be rendered like the are presented in the WYSIWYG editor.

## Current behaviour

[current-behaviour](#current-behaviour)

Hardly any distinction between regular paragraph text and code blocks

## Useful information

[useful-information](#useful-information)

See above

## Environment

[environment](#environment)

_**What is the impacted version?**_ Tested on both 3.20.16 and 4.0.4

**Comment by bill-pond** [comment]
This issue happens for inline code as well. In the Markdown editor you have a nice pink box around the inline code, but when rendered in developer portal, it becomes normal text (might be even worse as it is lightly bigger than normal).

**Comment by sjanssens1977** [comment]
Keep-alive

**Comment by pascal-schetelat** [comment]
Same here. I must say the markdown rendering is not pleasing.
Code block is hard to discern from text, the documentation look dated.

It pains me to show our doc like this : https://api-portail.bdnb.io/catalog/api/f4905edc-db58-3a3b-a8e5-c5dfc6692ee5/doc?page=39ca1b93-4d44-449a-8a1b-934d44e49af9#vous-cherchez-des-donn%C3%A9es-sur-des-b%C3%A2timents-dans-une-zone 

Is there a way to add custom css ?

**Comment by JesterX666** [comment]
We still need this.
