### ISSUE TITLE
Connect to an ES and/or Mongo cluster is impossible through docker deployment . Manage the  configuration of gravitee.yml through an external source

### ISSUE THREAD

**Issue by olivadeo** [gravitee-io/issues#924]
Not possible to specify a connection to an ES and/or Mongo on docker deployment
### Expected Behavior
Possibility to specify cluster connection on a docker deployment .
Possibility to set the configuration file  content from an external consul cluster with confd

### Current Behavior
ENV variable to connect to standalone instances

### Your Environment

* Version used: 1.10.4
* Browser Name and version: 
* Operating System and version:

**Comment by NicolasGeraud** [comment]
hi @olivadeo ,

do you want to work on that feature ? I can help you.

**Comment by olivadeo** [comment]
Hi Nicolas, 
Actually, I would  like to know if it will be possible to source configuration in gravitee.yml by from an external cluster of parameters like consul, through something like confd .

In the current version of dockerfile, it's not possible to configure a cluster connection to ES an Mongo.
I guess that it's not verey complicated to that possibility, but it will be not enough for our need.

What we do is manage environment per environment in a consul cluster. 
Parameters are prefixed by the environment and country code. ex : recette/pt/mongo.url
In the dockerfile, before launching the service, config files are sourced by a call to the cluster through
a docker-entrypoint.sh, which call consul .
Then configuration is ready and the service is launched


As would like  to use community images of gravitee, Is it possible to implement this kind of configuration, by adding a docker-entrypoint.sh ?

Below an example : 

**docker-entrypoint.sh**
_set -e
confd -onetime -backend consul -node $CONSUL -prefix "$ENVIRONMENT" -log-level="debug"_

with consul = url of the consul cluster, and prefix = env/businessUnit

In the confd configuration path, assume that tmpl and toml files are present to allow confd to source the configuration

**tmpl file sample** (for gravitee, will be gravitee.tmpl)
_export const HTTP = axios.create({
  baseURL: '{{getv "/sly/app/admin-core/url"}}:{{getv "/sly/app/admin-core/port"}}',
  headers: {
    // Authorization: 'Bearer {token}'
  }
});

export const HTTP_PRODUCT = axios.create({
  baseURL: '{{getv "/sly/app/admin-core/rest-product-api-url"}}',
  headers: {
    // Authorization: 'Bearer {token}'
  }
});_


**toml file sample**  (for gravitee, will be gravitee.toml)
_[template]
src = "http-common.tmpl"
dest = "src/resources/config/http-common.js"
mode = "0644"
keys = [
"/sly/app/admin-core/url",
"/sly/app/admin-core/port",
"/sly/app/admin-core/rest-product-api-url",
"/sly/app/transformation/scr/ws/url"
]_

Of course, the use of the docker-entry-point.sh will have to be configurable at the launch of the image.

With this kind of way to source the conf, It's possible to manage natively, multi env, and multi business unit , with a single image. 
In case of the user do not used a consul configuration cluster, it could always the "default" mode at the launch of the image.

There's anyway an issue with gravitee.yml, as it exists currently.
It looks that it's necessary to remove /add comment to use cluster or no cluster configuration for Mongo and ES.


So, to resume, I would likee to have the possibility to source gravitee.yml by an external configuration, by executing the script docker-entry-point.sh.

thx.

**Comment by brasseld** [comment]
All properties within `gravitee.yml` can be overridden using environment variables.
