### ISSUE TITLE
How to remove X-Gravitee-Api-Key authentication for the specified URL

### ISSUE THREAD

**Issue by wordplat** [gravitee-io/issues#926]
### Expected Behavior

Remove X-Gravitee-Api-Key authentication for the specified URL.

### Current Behavior

In normal, I request a url by HTTP_METHOD GET with header X-Gravitee-Api-Key, it works.
But In browser's javascript, browser auto send a HTTP_METHOD OPTIONS before request the url, and the OPTIONS method do not auto set a header X-Gravitee-Api-Key, so it would return 401 errors.

### Possible Solution

Want a policies configuration to remove X-Gravitee-Api-Key authentication for the specified URL.

### Your Environment

* Version used: 1.11.0

Regards,
Thank you!

**Comment by brasseld** [comment]
Hi @wordplat,

I think you just have to configure CORS for your API
Administration > Select your API > Proxy > CORS

Thanks for your feedback.

**Comment by wordplat** [comment]
Hi, I found the configuration. But I got another problem.
Sometimes I configure a OAuth2 policies in the root url `/`, it will invalid. But configure a OAuth2 policies in the child url `/some/path`, it works. I don't know Why the root url `/` OAuth2 policies doesn't work.
Which I mean invalid is that I don't send a `Authorization` header it can still request the child url `/some/path`, I think there are some bugs here.

**Comment by brasseld** [comment]
Sorry but I did not get you.

You mean that you can invoke `/some/path` without an `Authorization` header while you have put an OAuth2 policy ?

**Comment by wordplat** [comment]
Yes. I can invoke `/some/path` without an `Authorization` header while I have put an OAuth2 policy in root url '/'
But I can invoke `/some/path` an `Authorization` header while I have put an OAuth2 policy in child url '/some/path'

**Comment by brasseld** [comment]
your previous comment is not clear. Are you sure about what you wrote ?

**Comment by brasseld** [comment]
FYI, there is no inheritance.
Perhaps you can share the json descriptor of your API (Export API).

**Comment by wordplat** [comment]
The second question I'm giving doesn't look like a bug, and my problems have been solved. Thank you very mush.
