### ISSUE TITLE
GKO fails with panic in case "limit" is specified in SpikeArrest configuration

### ISSUE THREAD

**Issue by kamiiiel** [gravitee-io/issues#9260]
## [Describe the bug](#describe-the-bug)

When passing an integer value to the Policy configuration, GKO will cause a panic and stops working completely.

## [To Reproduce](#to-reproduce)

Steps to reproduce the behaviour: This should be configuration for SpikeArrest plugin to reproduce:

 configuration:
 async: false
 addHeaders: true
 spike:
 dynamicLimit: "0"
 periodTime: 5
 limit: 2500
 periodTimeUnit: SECONDS
 key: ""

## [Current behaviour](#current-behaviour)

GKO stops working completely

**Comment by gaetanmaisse** [comment]
Closing as this issue has been fixed and released in GKO 0.9.0

**Comment by oleksiyp** [comment]
@gaetanmaisse  As a comment I'd like to add that would be nice to make every place potentially causing a panic safe, by reducing blast radius (for example to one processed resource). Not sure how this is achievable in Golang without exceptions
