### ISSUE TITLE
[management] Webhook

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#930]
The purpose of this issue is to provide extension point via webhooks.

A webhook is a POST request sent with a payload on a specific event.

Initial supported events must be:
  - CRUD on API
  - CRUD on Application
  - CRUD on User

**Comment by brasseld** [comment]
Initial supported events must be:
- CRUD on API
- CRUD on Application
- CRUD on User (?)

**Comment by NicolasGeraud** [comment]
subscription and endpoints health ?

**Comment by brasseld** [comment]
No for endpoint health, since health-check is done by the gateway.. and it's not the responsability of the gateway to invoke a webhook.

For subscription, perhaps, I have no use-case in mind...

**Comment by NicolasGeraud** [comment]
For subscription the idea is to connect the validation process to an external BPM tool

**Comment by brasseld** [comment]
Is this required for an initial implementation of webhooks ?

**Comment by NicolasGeraud** [comment]
I don't know. For you, what is the first use case addressed by webhooks ?

**Comment by NicolasGeraud** [comment]
user creation ?

**Comment by brasseld** [comment]
Manage interactions between APIM and AM (and it is the same for one of our user / customer).
I'm creating a new application, invoke webhook on app_create, the AM server generates a client_id / client_secret... and we are able to use them to authenticate application calls on API gateway (thanks to oauth2 / jwt plan).

**Comment by NicolasGeraud** [comment]
this is implemented with the same mechanism than notification. It is a "Notifier".
The currents implemented events are the same than those which triggered an email.

see #929
