### ISSUE TITLE
Portal Swagger Custom Header retrieval issue  

### ISSUE THREAD

**Issue by basavarajbj17** [gravitee-io/issues#9340]
## [Describe the bug](#describe-the-bug)

Have added custom header in swagger docs for a service and the same is published in Portal application for testing the service using Try it option.

When I click on the Execute option of the service in swagger option from documentation section. Below request is generated

curl -X 'POST' '[http://localhost:8082/corporate-service/api/getBalance](http://localhost:8082/corporate-service/api/getBalance)' -H 'accept: application/json' -H 'X-SBM-Token: undefined' -H 'Content-Type: application/json' -d '

 { "AcctId": "string", "cId": "string" } 

'

And we can see the custom header parameter X-SBM-Token is not showing the actual entered value but shows as "undefined".

I have attached sample screen shot for same [<span class="image-wrap" style="">![](https://github.com/gravitee-io/issues/assets/12071173/db1415d9-581a-4a65-be75-d6514238eded)</span>](https://github.com/gravitee-io/issues/assets/12071173/db1415d9-581a-4a65-be75-d6514238eded)

**Comment by phiz71** [comment]
Hello @basavarajbj17, we have recently update the version of the swagger-ui embedded in both portal and console.

Could you try to update to the latest version of APIM (3.20.26, 4.0.15, 4.1.6 or 4.2.0) and check if you still have the problem ?
