### ISSUE TITLE
[APIM] Can't change picture and background for backend-to-backend application

### ISSUE THREAD

**Issue by Mattue** [gravitee-io/issues#9357]
## [Describe the bug](#describe-the-bug)

[describe-the-bug](#describe-the-bug)

[describe-the-bug](#describe-the-bug)

[describe-the-bug](#describe-the-bug)

[describe-the-bug](#describe-the-bug)

[describe-the-bug](#describe-the-bug)

Can't change picture and background for backend-to-backend application both on portal-ui and management-ui

## [To Reproduce](#to-reproduce)

[to-reproduce](#to-reproduce)

[to-reproduce](#to-reproduce)

[to-reproduce](#to-reproduce)

[to-reproduce](#to-reproduce)

[to-reproduce](#to-reproduce)

Prerequisites:

1.  Configure gravitee with correct Dynamic Client Registration
2.  Allow Backend-to-Backend applications creation

Portal-ui

1.  Go to portal-ui
2.  Create application with type `backend-to-backend`
3.  Go to your application
4.  Click on `Choose a file`
5.  Choose any file as new picture
6.  Click `SAVE`
7.  See `404` page and error in network console `ApplicationType <span class="error"><span class="error"><span class="error"><span class="error"><span class="error"><span class="error"><span class="error"><span class="error"><span class="error">[null]</span></span></span></span></span></span></span></span></span> can not be found`

Management-UI

1.  Go to management-ui
2.  Create application with type `backend-to-backend`
3.  Go to your application
4.  Click `Change picture` and choose any picture
5.  Click on `SAVE`
6.  See error `ApplicationType <span class="error"><span class="error"><span class="error"><span class="error"><span class="error"><span class="error"><span class="error"><span class="error"><span class="error">[null]</span></span></span></span></span></span></span></span></span> can not be found`

Same steps for background change

## [Expected behaviour](#expected-behaviour)

[expected-behaviour](#expected-behaviour)

[expected-behaviour](#expected-behaviour)

[expected-behaviour](#expected-behaviour)

[expected-behaviour](#expected-behaviour)

[expected-behaviour](#expected-behaviour)

Picture and background is changing successfully both on portal-ui and management-ui

## [Current behaviour](#current-behaviour)

[current-behaviour](#current-behaviour)

[current-behaviour](#current-behaviour)

[current-behaviour](#current-behaviour)

[current-behaviour](#current-behaviour)

[current-behaviour](#current-behaviour)

In attempt to change picture `ApplicationType <span class="error"><span class="error"><span class="error"><span class="error"><span class="error"><span class="error"><span class="error"><span class="error"><span class="error">[null]</span></span></span></span></span></span></span></span></span> can not be found` error occurs

## [Useful information](#useful-information)

[useful-information](#useful-information)

[useful-information](#useful-information)

[useful-information](#useful-information)

[useful-information](#useful-information)

[useful-information](#useful-information)

Screenshot, video, logs, other supporting material

Portal-ui error screenshot

[<span class="image-wrap" style="">![](https://github.com/gravitee-io/issues/assets/9050530/de9ea48d-00d3-4f72-9f25-6355cf820183)</span>](https://github.com/gravitee-io/issues/assets/9050530/de9ea48d-00d3-4f72-9f25-6355cf820183)

Management-ui error screenshot

[<span class="image-wrap" style="">![](https://github.com/gravitee-io/issues/assets/9050530/e832ba2a-f8a2-4532-a180-52aae213d0cd)</span>](https://github.com/gravitee-io/issues/assets/9050530/e832ba2a-f8a2-4532-a180-52aae213d0cd)

Application update PUT request (masked)

<pre>{

"name": "oauthapp-test",

"description": "oauthapp-test",

"groups": [],

"settings": {

"oauth":

 { "client_id": "xxx", "client_secret": "xxx", "redirect_uris": [], "response_types": [ "code", "none" ], "grant_types": [ "authorization_code", "client_credentials" ], "renew_client_secret_supported": false } 

},

"picture": "data:image/jpeg;base64,...",

"picture_url": null,

"disable_membership_notifications": false,

"api_key_mode": "UNSPECIFIED",

"background": "data:image/jpeg;base64,..."

}</pre>

Application update PUT response

<pre>{

"message" : "ApplicationType <span class="error">[null]</span> can not be found",

"parameters" : { },

"technicalCode" : "applicationType.notFound",

"http_status" : 404

}</pre>

## [Environment](#environment)

[environment](#environment)

[environment](#environment)

[environment](#environment)

[environment](#environment)

[environment](#environment)

APIM 3.20.22, but was not working eather on 3.20.10 but with different error text

## [Potential impacts](#potential-impacts)

[potential-impacts](#potential-impacts)

[potential-impacts](#potential-impacts)

[potential-impacts](#potential-impacts)

[potential-impacts](#potential-impacts)

[potential-impacts](#potential-impacts)

APIM 3.20.22

## [Dependencies](#dependencies)

[dependencies](#dependencies)

[dependencies](#dependencies)

[dependencies](#dependencies)

[dependencies](#dependencies)

[dependencies](#dependencies)

Looks like same error with application `type` like it was here - #9157 , #9158

**Comment by gaetanmaisse** [comment]
@Mattue are you facing the issue with a specific Application or even with a fresh one? I tried to reproduce with the latest 3.20 and didn't have any issues (set both the background and the image of the application)

**Comment by Mattue** [comment]
@gaetanmaisse , it's not working for **backend-to-backeand** applications. Tested right now on 3.20.24 and issue still exists

**Comment by Mattue** [comment]
Issue still exists in 3.20.30. Looks like it's dependent to some bug how BACKEND-TO-BACKEND application type is handled by apim-api.
No issue with application type SIMPLE

More over, I can't add BACKEND-TO-BACKEND application to a group with same error https://github.com/gravitee-io/issues/issues/9158
