### ISSUE TITLE
[GKO] Subscriptions Resource Types

### ISSUE THREAD

**Issue by jbouchery** [gravitee-io/issues#9366]
Hi Gravitee Team !

I didn't found the information but is there a roadmap to handle Subscriptions as Resource Types between applications and apidefinitions in the Kubernetes Operator ? Or did i miss something about it ?

Regards,

**Comment by jmcx** [comment]
Hi @jbouchery, you're correct this is not yet supported and is not yet scheduled on the roadmap although we would love to support it at some point. Perhaps we could meet to discuss your usage of GKO in more depth sometime? Cheers

**Comment by jbouchery** [comment]
Hi @jmcx ,

Thanks for the meeting. As we discussed, i understand that subscriptions could be a bit tricky to implement as Resource Types. It's simple in a JWT Plan use case but hard for a API KEY Plan as it's not trivial to return the generated API Key. 

Feel free to close this issue.

Regards,
