### ISSUE TITLE
[policy] [dynamic-routing] Simplify dynamic routing policy matchers

### ISSUE THREAD

**Issue by AnselmeDewavrin** [gravitee-io/issues#94]
Dear all,

The dynamic routing policy works well, however we must explicitly include the context path (or wildcard it). Could it be implicit ?

Thanks,
Anselme

**Comment by brasseld** [comment]
Hi @AnselmeDewavrin,

Yes, context-path will be implicit in the next version of the policy.

Expression language will also be updated to inject capture group.
Previously, you were able to replace capture group using the `{#group_0}` property.
In next version, you will have to use an indexed array like this: `{#group[0]}`
