### ISSUE TITLE
[management-api] [ldap] [roles] Adding roles to users in Gravitee requires a specific design of an organizations LDAP tree

### ISSUE THREAD

**Issue by jasama** [gravitee-io/issues#948]
### Expected Behavior
When searching for a user to add a role to in the Management API, it should not be required that the object in LDAP is of class `person`, as this enforces constraints on an organizations LDAP tree.

### Current Behavior
When searching for a user to add a role to in the Management API, it is required that the object in LDAP is of class `person`.

### Possible Solution
Make the `objectclass` filter in the following locations configurable:

- https://github.com/gravitee-io/gravitee-management-rest-api/blob/cdec63bbee2ee9f06395d2625e7bd6caa3866437/gravitee-management-api-idp/gravitee-management-api-idp-ldap/src/main/java/io/gravitee/management/idp/ldap/lookup/LdapIdentityLookup.java#L89

- https://github.com/gravitee-io/gravitee-management-rest-api/blob/cdec63bbee2ee9f06395d2625e7bd6caa3866437/gravitee-management-api-idp/gravitee-management-api-idp-ldap/src/main/java/io/gravitee/management/idp/ldap/lookup/LdapIdentityLookup.java#L108

### Your Environment
* Version used: API Management, 1.11.4

**Comment by brasseld** [comment]
Do you think you can do these changes with our help ?

**Comment by jasama** [comment]
Adapting the identity lookup to an organizations tree is a slippery slope. We'll rather adapt the organizations tree, if necessary.

**Comment by brasseld** [comment]
Hi @jasama 

Why reopening this issue ?

**Comment by jasama** [comment]
Hi @brasseld 

This is a needed feature for me in order to be able to use Gravitee.

If appropriate, the objectclass filter could have been excluded, but that might create problems for other users?

**Comment by brasseld** [comment]
Your PR seems good to me, there is no reason to exclude objectclass filter.

I need to test your PR more deeper with existing LDAP, then, your patch will be included into 1.13.x scheduled for the end of the month.

Is it ok for you ?

**Comment by jasama** [comment]
@brasseld 

Yes, it is. We'll manage.

Thanks!
