### ISSUE TITLE
Add checksum for archives provided as download

### ISSUE THREAD

**Issue by blackillzone** [gravitee-io/issues#949]
Currently, we don't have any possibility to validate a download in our automation process, due to the absence of checksum (MD5, SHA1...), for all Gravitee archives.
Is this possible to add it for all the zip files provided via https://download.gravitee.io/ ? I think it would add more robustness for all automation processes, for everyone.

I would see something like simple checksum file, under each releases:

```
graviteeio-full-1.12.0.zip
graviteeio-full-1.12.0.zip.md5
graviteeio-full-1.12.0.zip.sha1
graviteeio-full-1.12.1.zip
graviteeio-full-1.12.1.zip.md5
graviteeio-full-1.12.1.zip.sha1
```

What do you think about it ?

**Comment by NicolasGeraud** [comment]
done.
I now need to update dockers images.
