### ISSUE TITLE
[policy] [mock] Policy cannot access request content

### ISSUE THREAD

**Issue by AnselmeDewavrin** [gravitee-io/issues#950]
It would be sometimes useful to use request body parts in a mock, but this does not seem to be possible.

Thanks in advance

Anselme

### Expected Behavior
using the following syntax in the mock body
{#request.content}
should show the request body

### Current Behavior
it gives an exception in the logs :
org.springframework.expression.spel.SpelEvaluationException: EL1008E:(pos 9): Property or field 'content' cannot be found on object of type 'io.gravitee.gateway.reactor.handler.el.EvaluableRequest' - maybe not public?

### Your Environment

* Version used: 1.9.2
* Browser Name and version:
* Operating System and version:

**Comment by Matsa59** [comment]
Cause error on groovy script (onResponseContent)

```java
import groovy.json.JsonSlurper
import groovy.json.JsonOutput

def jsonSlurper = new JsonSlurper()
def content = jsonSlurper.parseText(request.content)
content.firstname = 'Hacked ' + content.firstname
content.country = 'US'

return JsonOutput.toJson(content)
```

with following request : 
```curl
curl -X POST \
 <URL> \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -d '{
	"firstname": "ok"
}'
```

**Comment by mgirin** [comment]
Any ideas here please?  I am trying to extract request body content in Java onRequest to validate the body

**Comment by brasseld** [comment]
@mgirin in the mock policy ?

**Comment by mgirin** [comment]
@brasseld thanks for reaching out.  I am just trying to get a simple scenario working when I have a custom policy and trying to parse and validate request content in the OnRequest method, public void onRequest(Request request, Response response, ExecutionContext executionContext, PolicyChain policyChain).  Is there a reason why it is not possible to get request.content and it was set to Null in the Request object?  What is the best way to extract the content of the request and run through the policy rules, like we normally do to validate headers or attributes?

**Comment by brasseld** [comment]
package io.gravitee.policy;

import com.fasterxml.jackson.databind.JsonNode;
import com.github.fge.jackson.JsonLoader;
import com.github.fge.jsonschema.core.report.ProcessingReport;
import com.github.fge.jsonschema.main.JsonSchemaFactory;
import com.github.fge.jsonschema.main.JsonValidator;
import io.gravitee.common.http.HttpStatusCode;
import io.gravitee.gateway.api.Request;
import io.gravitee.gateway.api.Response;
import io.gravitee.gateway.api.buffer.Buffer;
import io.gravitee.gateway.api.stream.BufferedReadWriteStream;
import io.gravitee.gateway.api.stream.ReadWriteStream;
import io.gravitee.gateway.api.stream.SimpleReadWriteStream;
import io.gravitee.policy.api.PolicyChain;
import io.gravitee.policy.api.PolicyResult;
import io.gravitee.policy.api.annotations.OnRequestContent;

@SuppressWarnings("unused")
public class JsonValidationPolicy {

    /**
     * The associated configuration to this JsonMetadata Policy
     */
    private JsonValidationPolicyConfiguration configuration;

    private static final JsonValidator validator = JsonSchemaFactory.byDefault().getValidator();

    /**
     * Create a new JsonMetadata Policy instance based on its associated configuration
     *
     * @param configuration the associated configuration to the new JsonMetadata Policy instance
     */
    public JsonValidationPolicy(JsonValidationPolicyConfiguration configuration) {
        this.configuration = configuration;
    }

    @OnRequestContent
    public ReadWriteStream onRequestContent(Response response, Request request, PolicyChain policyChain) {
        return new BufferedReadWriteStream() {

            Buffer buffer = Buffer.buffer();

            @Override
            public SimpleReadWriteStream<Buffer> write(Buffer content) {
                buffer.appendBuffer(content);
                return this;
            }

            @Override
            public void end() {
                try {
                    JsonNode schema = JsonLoader.fromString(configuration.getSchema());
                    JsonNode content = JsonLoader.fromString(buffer.toString());

                    ProcessingReport report;

                    if (configuration.isValidateUnchecked()) {
                        report = validator.validateUnchecked(schema, content, configuration.isDeepCheck());
                    } else {
                        report = validator.validate(schema, content, configuration.isDeepCheck());
                    }

                    if (!report.isSuccess()) {
                        request.metrics().setMessage(report.toString());
                        policyChain.streamFailWith(PolicyResult.failure(HttpStatusCode.BAD_REQUEST_400, "Bad request"));
                    } else {
                        // Write content
                        super.write(buffer);

                        // Mark the end of content
                        super.end();
                    }
                } catch (Exception ex) {
                    request.metrics().setMessage(ex.getMessage());
                    policyChain.streamFailWith(PolicyResult.failure(HttpStatusCode.BAD_REQUEST_400, "Bad request"));
                }
            }
        };
    }
}
```

I hope it's helpful ;)

**Comment by mgirin** [comment]
This is awesome, @brasseld, and thank you!

**Comment by mgirin** [comment]
Hi @brasseld A separate question on the proxy requests coming through the gateway.  I need to create a custom policy and apply to an API proxy, which would attach an X509 Certificate private key, supplied by a trading partner, in the outbound request from my internal API platform.  So, the flow is: internal API goes to Gravitee API Gateway in the outbound call, the Gateway proxy with a custom policy takes the outbound call and attaches an X509 cert before that call is made back to the trading partner, which validates the cert.  I know how to attach an X509 in Java to an HTTP client, but is this doable in the Gateway?  Each trading partner has its own X509, so the certs are to be maintained on the server where Gateway is installed, inside the JKS store, accessible in Java-based custom policy via keystore access.  So I would want to determine the trading partner name in the policy, retrieve the X509  from the store, attach it in the request, and send the request out in the outbound call.

**Comment by brasseld** [comment]
Sorry, I miss your message.

May I ask you to create a dedicated issue for your use-case.
It will be easier to manage and track.

Thanks a lot!

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/issues/issues/1789
