### ISSUE TITLE
[portal] save the open/close state of the new help panel on the right for a user in his browser

### ISSUE THREAD

**Issue by tdaghelet** [gravitee-io/issues#951]
Can you add possibility to open/close the new help panel on the right ? It's helpful for a first approach but it takes a lot of place when you work especially on the policies tab

### Expected Behavior

add a button or a checkbox to open/close this panel

### Your Environment

* Version used: 1.12.1
* Browser Name and version: Chrome 62.0.3202.94
* Operating System and version: Win 10 pro

**Comment by brasseld** [comment]
Hi @tdaghelet,

You have an icon next to the user panel in the top nav (right)
Isn't it sufficient ?

**Comment by tdaghelet** [comment]
Ok, maybe i have a problem with my configuration, but i didn't see any icon to close the panel

![image](https://user-images.githubusercontent.com/3962585/34109364-98542536-e403-11e7-9ed2-0f0aacc34e02.png)

**Comment by brasseld** [comment]
<img width="87" alt="capture d ecran 2017-12-18 a 15 00 59" src="https://user-images.githubusercontent.com/133094/34109546-37dd8a7a-e404-11e7-8933-5489dad79a11.png">

**Comment by tdaghelet** [comment]
OMG ! sorry David, i was expecting a cross icon or something like that...

**Comment by brasseld** [comment]
Perhaps it must be stored in browser storage to avoid clicking on the icon each time you go on the portal.

So we may keep it as opened ;)
