### ISSUE TITLE
Slow documentationpage

### ISSUE THREAD

**Issue by Safranil** [gravitee-io/issues#9510]
## Describe the bug

[describe-the-bug](#describe-the-bug)

The APIs documentation pages are slow to display when the collection `page_revisions` have thousand of changes.

This can lead to the connection being dropped by Gravitee if the timeout is too low (5000 ms in the default Docker Compose file).

## To Reproduce

[to-reproduce](#to-reproduce)

Steps to reproduce the behaviour:

1.  Add a documentation page from an external source (URL)
2.  Configure auto fetch to every minutes

## Expected behaviour

[expected-behaviour](#expected-behaviour)

Add a way to drop old revisions or add an index to speed-up the query time.

## Current behaviour

[current-behaviour](#current-behaviour)

The request on `page_revisions` is missing some indexes to speed up the query, leading to slow documentation page or errors if the timeout is hit.

## Useful information

[useful-information](#useful-information)

MongoDB log when loading a documentation page with a lot of revisions:

<pre>{"t":

 {"$date":"2024-02-09T10:38:57.619+00:00"} 

,"s":"I", "c":"COMMAND", "id":51803, "ctx":"conn20","msg":"Slow query","attr":{"type":"command","ns":"gravitee.page_revisions","command":{"find":"page_revisions","filter":

 {"_id.pageId":"a679ce36-4e7f-437f-b9ce-364e7f837fa0"} 

,"sort":

 {"_id.revision":-1} 

,"limit":1,"$db":"gravitee","lsid":{"id":

 {"$uuid":"f8eb2794-3e73-490b-af68-04fba7c37913"} 

}},"planSummary":"COLLSCAN","keysExamined":0,"docsExamined":237659,"hasSortStage":true,"cursorExhausted":true,"numYields":315,"nreturned":1,"queryHash":"74F9C45F","planCacheKey":"74F9C45F","reslen":17612,"locks":{"FeatureCompatibilityVersion":{"acquireCount":{"r":316}},"ReplicationStateTransition":{"acquireCount":{"w":316}},"Global":{"acquireCount":{"r":316}},"Database":{"acquireCount":{"r":316}},"Collection":{"acquireCount":{"r":316}},"Mutex":{"acquireCount":

 {"r":1} 

}},"storage":{"data":

 {"bytesRead":4229234332,"timeReadingMicros":3057126} 

,"timeWaitingMicros":{"cache":7}},"protocol":"op_msg","durationMillis":3455}}</pre>

I added theses index to improve the performance of this query (no slow query being printed in logs and the documentation page is displayed instantly) :

<pre>db.getCollection(`page_revisions`).createIndex(

 { "_id.pageId" : 1 } 

,

 { "name": "_ipi1" } 

);

  db.getCollection(`page_revisions`).createIndex(

 { "_id.revision" : 1 } 

,

 { "name": "_ir1" } 

);

  db.getCollection(`page_revisions`).reIndex();</pre>

## Environment

[environment](#environment)

_**What is the impacted version?**_

3.20.28

## Potential impacts

[potential-impacts](#potential-impacts)

_**Which other features may be impacted by this fix. This could be populated after fix**_ The documentation editor in the console is also impacted by this issue and the load time is greatly improved after indexes were added.

_**What are the impacted versions?**_

**Comment by phiz71** [comment]
Hello @Safranil, thank you for your feedback.
In APIM 3, mongo indices have to be created manually and we have a creation script here: https://github.com/gravitee-io/gravitee-api-management/blob/3.20.x/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/create-index.js

Unfortunately, your indices are not present in this script probably because we've never faced your situation (a page with thousands of revision).

Starting with APIM 4, we have introduced a mechanism to automatically create required indices, so you shouldn't have to do it manually.
We will check if the indices you created have been identified on our side.

**Comment by phiz71** [comment]
@Safranil 
For version 4.x, we have introduced this upgrader https://github.com/gravitee-io/gravitee-api-management/blob/4.0.x/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/index/pagerevisions/PageIdIndexUpgrader.java
It creates an index based on `_id.pageId`.

However we didn't determine that your second index (based on `_id.revision`) was required.

Have you tested with only the first index? If yes, did you get better performance when you created the second index?

Thank you.

**Comment by Safranil** [comment]
As I remember, both were required.

I ended up to remove all history with `db.page_revisions.remove({createdAt:{$lte: new Date(2024, 1, 1)}})`.

I think a clean-up task can be useful for certain use-cases.
