### ISSUE TITLE
[management-ui] Can't save policy when checking/uncheking HTTP METHOD

### ISSUE THREAD

**Issue by tdaghelet** [gravitee-io/issues#955]
Hello,

We can't save a policy when we check or uncheck a HTTP METHOD (GET, POST, etc), the save button stay disabled and we have to write in a field to activate it

### Expected Behavior
Enable the button SAVE when we check or uncheck a http method

### Current Behavior
The button SAVE stay disabled

### Steps to Reproduce (for bugs)

1. Add a policy and save it
2. Uncheck POST
3. You can't save

### Your Environment

* Version used: 1.12.1
* Browser Name and version: Chrome 62
* Operating System and version: Win 10 PRO

**Comment by aelamrani** [comment]
Not reproductible on 1.28
