### ISSUE TITLE
Incompatible Qos between entrypoint and RabbitMQ endpoint

### ISSUE THREAD

**Issue by graviteeio** [gravitee-io/issues#9603]
h2. Describe the bug :&#10;The HTTP GET entrypoint for the RabbitMQ endpoint currently only supports None and Auto for QoS but allows users to select At-Least-Once or At-Most-Once although they are incompatible.&#10;&#10;h2. To Reproduce :&#10;Steps to reproduce the behaviour:&#10;# Create an API with an HTTP GET entrypoint and a RabbitMQ endpoint.&#10;# Edit the the QoS for the HTTP GET entrypoint.&#10;# There are options for Auto, At-Least-Once, and At-Most-Once.&#10;&#10;h2. Expected behaviour :&#10;The only QoS options for the RabbitMQ endpoint and HTTP GET entrypoint should be Auto or None.&#10;&#10;h2. Current behaviour :&#10;Incompatible QoS options for RabbitMQ are able to be selected through the UI for an entrypoint.&#10;&#10;h2. Desktop :&#10; - Environment: 4.2.x&#10;&#10;~* Please see Zendesk Support tab for further comments and attachments.~

**Comment by ppgravitee** [comment]
Wrong format, see https://github.com/gravitee-io/issues/issues/9608 instead
