### ISSUE TITLE
Liquibase changelog 4.0.20-dashboards adding NOT NULL column without default value

### ISSUE THREAD

**Issue by mkozina-gk-software** [gravitee-io/issues#9626]
## Describe the bug

[describe-the-bug](#describe-the-bug)

Repository <span class="error">[MANAGEMENT]</span> fails after upgrade to 4.3.0-alpha.2\. Liquibase changelog _4.0.20-dashboards_ tries to add column _type_ to table _dasboards_ , but it fails, when this table is not empty, because there is no default value defined.

## To Reproduce

[to-reproduce](#to-reproduce)

Steps to reproduce the behaviour: 1.Run Gravitee version 4.3.0-alpha.2 with DB backend in PostgreSQL on top of existing database from older version (with some rows in table _dasboards_ . 2\. Start of _gravitee-apim3-api_ and _gravitee-apim-gateway_ will fail.

## Expected behaviour

[expected-behaviour](#expected-behaviour)

All Liquibase changelog will be robust and pass.

## Current behaviour

[current-behaviour](#current-behaviour)

Start of application is blocked due to failing Liquibase changelog.

## Useful information

[useful-information](#useful-information)

[gravitee_4.3.0-alpha.2_liquibase.log](https://github.com/gravitee-io/issues/files/14697022/gravitee_4.3.0-alpha.2_liquibase.log).

## Environment

[environment](#environment)

 _**What is the impacted version?**_ Running latest Gravitee build at kubernetes, Gravitee version

## Potential impacts

[potential-impacts](#potential-impacts)

 _**Which other features may be impacted by this fix. This could be populated after fix**_ See dependencies links

 _**What are the impacted versions?**_ 

## Dependencies

[dependencies](#dependencies)

[https://github.com/gravitee-io/gravitee-api-management/blame/master/gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/changelogs/v4_0_20/schema-dashboards.yml#L16](https://github.com/gravitee-io/gravitee-api-management/blame/master/gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/changelogs/v4_0_20/schema-dashboards.yml#L16)

[https://github.com/gravitee-io/gravitee-api-management/commit/3d049c6900e4520e9734f2a03774b32b79792acd](https://github.com/gravitee-io/gravitee-api-management/commit/3d049c6900e4520e9734f2a03774b32b79792acd)

**Comment by mkozina-gk-software** [comment]
Now also in version 4.2.5 - @ytvnr - seems to be from this https://github.com/gravitee-io/gravitee-api-management/commit/3d049c6900e4520e9734f2a03774b32b79792acd

**Comment by ytvnr** [comment]
Hi @mkozina-gk-software thank you for this issue,

Indeed, there was a miss here, we are currently working on a fix and will release it soon.

Sorry for the inconvenience
