### ISSUE TITLE
[portal] add personal css with my theme

### ISSUE THREAD

**Issue by GGui** [gravitee-io/issues#963]
Hi,

I would like to add a personal css in the portail ui in order to customize my documentation style.
It could be a new parameter in the constants.json like 
"theme": {
    "name": "default",
    "logo": "themes/assets/GRAVITEE_LOGO1-01.png",
    "loader": "assets/gravitee_logo_anim.gif",
    **"css": "themes/heme.css"**
  }

Regards,

**Comment by brasseld** [comment]
Why not loading them automatically  from a `stylesheets` directory instead of adding them manually into the config file ?

**Comment by brasseld** [comment]
Reopen issue
