### ISSUE TITLE
[management-api]Oauth2 Map is not support json path search

### ISSUE THREAD

**Issue by yang-dw** [gravitee-io/issues#965]
I can't configure management-api for some complex oauth2 Program .  For example

![qq 20171229172751](https://user-images.githubusercontent.com/28995740/34434594-1c038b26-ecc2-11e7-86da-251aad4ec7e3.jpg)

**Comment by yang-dw** [comment]
two level is not support

**Comment by brasseld** [comment]
Sorry, but I didn't get you.

Please be more precise on the issue you face and what is expected.

**Comment by yang-dw** [comment]
I use oauth2 for login,so I must config the map to my gravitee ,but, My oauth2 program return nested Json String. gravitee can't analysis detail info

**Comment by brasseld** [comment]
Oh I see, I've got the point !

Ok, let me know when your pull request is ready, I will have a look as soon as possible to embed patch in next version.

**Comment by yang-dw** [comment]
Already
