### ISSUE TITLE
[policy] [jwt] authentification scheme is not checked

### ISSUE THREAD

**Issue by GGui** [gravitee-io/issues#966]

**Comment by brasseld** [comment]
Sorry @GGui but I don't understand the purpose of this issue.

Are you talking about the `Authorization` scheme ? I mean `Authorization: Bearer xx-xxx-xxx` ?

**Comment by GGui** [comment]
yes, we don't check if the authorization scheme "Bearer" is in Authorisation header and if it is well "Bearer".
