### ISSUE TITLE
[gateway] assign ip of x-forwared-for header to remoteAddress metric

### ISSUE THREAD

**Issue by GGui** [gravitee-io/issues#969]
I would like to display in remoteAddress metric, the client ip address (exemple for un mobile phone, display the mobile phone ip)

**Comment by sahlex** [comment]
Azure's Application Gateway tends to deliver not only the client's IP address but a combination of IP:PORT in the X-Forwarded-For (XFF) header. Gravitee's implementation seems to have trouble using this as no logs appear in elasticsearch when a request comes in through an azure app gateway.

**Comment by brasseld** [comment]
Hi @sahlex may I ask you to create a dedicated issue please ?

**Comment by sahlex** [comment]
Sure
