### ISSUE TITLE
[portal Policies] Add the possibility to create 2 routes with different HTTP method 

### ISSUE THREAD

**Issue by tdaghelet** [gravitee-io/issues#975]
Hello,

It could be great to add the possibility to create two identical routes (or more) with different HTTP method.

For example :
GET /customer/12
POST /customer/12

With the HTTP method on the route and not individually on each policy

### Expected Behavior
Provide the possibility to have many routes with same name and different HTTP method setted directly on the route and not individually by policy

### Current Behavior
Currently, you have to put all policies on the same route (generally a GET route and a POST route represent different process), it's not simple to differentiate each process with this design.

**Comment by brasseld** [comment]
Should be closed by #3895
