### ISSUE TITLE
Error starting Gateway - Mongo DB

### ISSUE THREAD

**Issue by mbonfanti** [gravitee-io/issues#985]
I'm trying to start API Gateway but i get this error trying to start app. I've configured an existing mondodb server, but I don't understand how to seed the database.

Error:
org.springframework.data.mongodb.UncategorizedMongoDbException: Query failed with error code 13 and error message 'not authorized on gravitess to execute command { find: "apis", filter: {} }' on server itdgtosax000142.idg.audi.vwg:27017; nested exception is com.mongodb.MongoQueryException: Query failed with error code 13 and error message 'not authorized on gravitess to execute command { find: "apis", filter: {} }' on server itdgtosax000142.idg.audi.vwg:27017

**Comment by NicolasGeraud** [comment]
hi,
it seems that your mongo user configured in the gravitee.yml file is not correct

**Comment by NicolasGeraud** [comment]
have you created a dedicated mongo user for the gravitee database ?

**Comment by mbonfanti** [comment]
Yes. I've created too low priviledged user. Now database is created and
manager started. Thanks

Il 9 gen 2018 6:08 PM, "Nicolas Géraud" <notifications@github.com> ha
scritto:
