### ISSUE TITLE
Import a Swagger descriptor，can not access api

### ISSUE THREAD

**Issue by linyintao2010** [gravitee-io/issues#987]
### Expected Behavior

Import a Swagger descriptor that contain a lot of apis，can access any one api by gateway。

### Current Behavior
Because of this swagger file contain  lots of apis service,  I try to access ones of the apis using lots of way  but fail.
thank you

**Comment by brasseld** [comment]
Hi @linyintao2010,

As far as I understand, you have imported successfully a swagger descriptor to create an API.
Now that you have an API, you must have to create an API plan to make it accessible through the gateway: did you create such plan ?

Regards,

**Comment by linyintao2010** [comment]
yes,i create the plan and pubish it.

**Comment by NicolasGeraud** [comment]
hi @linyintao2010 ,
when you say ` I try to access ones of the apis using lots of way but fail.`, what does it means ?
What requests have you tried ? What are the gateway responses ?

**Comment by brasseld** [comment]
Please do the following:

```
curl -X GET http://localhost:18082/_node/apis/ -H 'Authorization: Basic YWRtaW46YWRtaW5hZG1pbg=='
```

Get the id of your API, then,

```
curl -X GET http://localhost:18082/_node/apis/{api_id} -H 'Authorization: Basic YWRtaW46YWRtaW5hZG1pbg=='
```

And provide us with results of both commands.

**Comment by brasseld** [comment]
The response you get is not a common response from API Gateway, so I suppose it is coming from your backend services...

So, according to what I'm seeing, you reach the gateway, the gateway is calling your backend services, and the backend services respond with a 404 status  code.

**Comment by linyintao2010** [comment]
hi@brasseld 
i do the following，can get the swagger api info。but i do not know how to Consume an API by impoirting swagger url.

Backend services work well.

**Comment by brasseld** [comment]
Can you provide us with the results of the command I sahre with you in my previous comment ?

**Comment by linyintao2010** [comment]
![image](https://user-images.githubusercontent.com/30648802/34764997-2eb092c4-f62b-11e7-9142-cecbb851c696.png)

**Comment by brasseld** [comment]
Sorry, but the screenshot is not complete, I need the "plans" property also.

**Comment by linyintao2010** [comment]
hi @brasseld 
![image](https://user-images.githubusercontent.com/30648802/34765106-9bd6fc94-f62b-11e7-8dff-614f6f0bbdf0.png)

**Comment by brasseld** [comment]
Ok, so according to what I'm seeing, you must be able to invoke the gateway:

```
curl -v -X GET http://localhost:8082/cheliang?api-key=xxxx-xxxx-xxxx-xxxx
```

What is the results of such command ?

**Comment by linyintao2010** [comment]
![image](https://user-images.githubusercontent.com/30648802/34765887-a27079ac-f62d-11e7-8629-39965fa674d9.png)

---------------------------------------------------------------------------------------------------
computer ip 192.168.60.140

![image](https://user-images.githubusercontent.com/30648802/34765928-c2398260-f62d-11e7-8204-138390b08636.png)

**Comment by brasseld** [comment]
Ok, LGTM.

What is the expected result ?

Can you show me your curl which is invoking your backend  services directly ?

**Comment by linyintao2010** [comment]
![image](https://user-images.githubusercontent.com/30648802/34766484-8dacbb5a-f62f-11e7-9916-643d33a432c0.png)

**Comment by brasseld** [comment]
Ok, but if I don't know the path (only the path, not the host) you're trying to invoke, I can't help you.

**Comment by linyintao2010** [comment]
hi @brasseld 
thank you . i will continue to try myself

**Comment by linyintao2010** [comment]
hi @NicolasGeraud
thank you, this request  way you provide can work.
but api-key property why not put in http header

**Comment by NicolasGeraud** [comment]
you can do it with the following header : `X-Gravitee-Api-Key`
https://docs.gravitee.io/apim_quickstart_consume.html#test_an_api

**Comment by NicolasGeraud** [comment]
You can also configure the header name (https://docs.gravitee.io/apim_policies_apikey.html#gateway_level)

**Comment by linyintao2010** [comment]
@NicolasGeraud 
This is the first attempt.it can not work by put x-gravitee-api-key in http header.

**Comment by NicolasGeraud** [comment]
it's case sensitive.

**Comment by NicolasGeraud** [comment]
@linyintao2010 as I can see on your screenshot, your api-key is recognized because the response you've got is the response of your backend.

Please, pay attention of your requests. You have request the `/car` path and it seems that your api only recognize `/cars`

**Comment by linyintao2010** [comment]
hi @NicolasGeraud 
i see. thanks a lot
