### ISSUE TITLE
[management-ui] CORS configuration

### ISSUE THREAD

**Issue by tdaghelet** [gravitee-io/issues#998]
It seems that some fields in CORS configuration are mandatory and the UI doesn't force us to fill them.

In result, we get an HTTP 400 error without detail and it's difficult to understand that these fields are missing.

### Expected Behavior
If the fields Access-Control-Allow-Origin and/or Access-Control-Allow-Headers are not filled, the UI should forbid us to save the form.

Currently, only Access-Control-Allow-Method field is well configured

### Steps to Reproduce (for bugs)

1. Enable CORS in proxy
2. Configure one method (like GET) and call the API
3. You'll get an HTTP 400

### Your Environment

* Version used: 1.12.2

**Comment by tdaghelet** [comment]
Here is an example of a decorated md-chips with min and max chips validation : https://codepen.io/jakobadam/pen/PpwKmz

what do you think about this ?

**Comment by aelamrani** [comment]
Not reproductible on 1.28
